### ISSUE TITLE
[Spell] Wild Mushroom ID:88747

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Blackwing-Lair#1]
![image](https://user-images.githubusercontent.com/14857593/36740544-f9907300-1bf7-11e8-9bd8-7bea45d9a815.png)

**How it works:**
- Mushrooms have 1163HP.
- Mushrooms stay visible all the time.
- You can plan infinite number of mushrooms.

**How it should work:**
- Mushrooms should have 5HP.
- Mushrooms should go invisible after 6 second.
- When you cast the spell for 4th time, the first mushroom should disappear.

**Comment by fvicaria** [comment]
I need the exact spell id and the context of the use, quest, item etc
