### ISSUE TITLE
[Inscription] [skill=773]

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1001]
**Links:**
[skill=773]
https://www.wowhead.com/inscription
from WoWHead or our Armory

**What is happening:**
When milling herbs from Cata expansion the game crash.
 [Azshara's Veil] [item=52985]
 [Cinderbloom] [item=52983]
 [Stormvine] [item=52984]

**What should happen:**
The game should not crash

**Comment by wow-mania** [comment]
Please test this in dev.
Tried multiple times and all worked fine.

**Comment by sarahkay88** [comment]
That's picking. U need scribing. He broke them. Milling the herbs into parts for glyphs

**Comment by sarahkay88** [comment]
https://www.wowhead.com/inscription - proff
https://www.wowhead.com/spell=51005/milling - spell

**Comment by Echinaceax** [comment]
yes he means when his mills together Cata herbs his game crashes

[Azshara's Veil] [item=52985]
[Cinderbloom] [item=52983]
[Stormvine] [item=52984]

**Comment by Echinaceax** [comment]
This could also do with the wrong cata Download at you stated in outland crashes @wow-mania 

just a thought
