### ISSUE TITLE
 [Alchemy] [skill=171]

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1002]
**Links:**
[skill=171]
https://www.wowhead.com/alchemy

from WoWHead or our Armory

**What is happening:**
When i use transmution it say i have a CD to midnight but thats not correct.
It takes to about 03.00 or so when daily quests are reseted then Transmution is reset too

![transmute](https://user-images.githubusercontent.com/39439201/54880322-ded83f00-4e43-11e9-839b-3d66c89b3492.jpg)

**What should happen:**
https://cata-twinhead.twinstar.cz/?spell=11480

![no cd](https://user-images.githubusercontent.com/39439201/54880604-a5ed9980-4e46-11e9-999c-617de5e9718f.jpg)

**Comment by Kitzunu** [comment]
Research is needed here.

Dont trust information from another servers database

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/59565201-9306f180-9050-11e9-91f6-60ba4b99a744.png)
