### ISSUE TITLE
[zone=3483] Hellfire Peninsula Crashes

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1004]
**Links:**
[zone=3483]
https://www.wowhead.com/hellfire-peninsula
from WoWHead or our Armory

**What is happening:**
Random gamecrash all over the area for Alliance.
Game crashes very randomly in all around the area.
No specific spot or place.
Just crashing and u have to restart game again.
Sometimes i can fly from Dark Portal to Zangamarsh without crash, and sometimes when i do the same flight the game can crash 7 - 10 times.
Looks to be only Ally thats affected by this bug.

**What should happen:**

Game should not crash

**Comment by Echinaceax** [comment]
Hmmm, i'll keep flying around and see

**Comment by TheManiax** [comment]
@wow-mania 
Apparently it only happens to **Alliance**
Reproducing is easy, just make an ally and fly over the area
You get multi crashes in multi spots

**Comment by TheManiax** [comment]
[44.28 , 52.73]

**Comment by sarahkay88** [comment]
![World of Warcraft 24_03_2019 15_56_20](https://user-images.githubusercontent.com/42302580/54882193-71321000-4e4f-11e9-9321-ec9e7e66285c.png)
this is were I crashed

**Comment by Saintres** [comment]
Ok so i made a troll hunter and still crashing in Hellsfire so its not only ally crashing

**Comment by sarahkay88** [comment]
![World of Warcraft 24_03_2019 16_14_29](https://user-images.githubusercontent.com/42302580/54882257-092ff980-4e50-11e9-9b82-8d66c6e50e87.png)

**Comment by Echinaceax** [comment]
odd that you all crash and i havent yet 
Gone though all things i know to reproduce and i get nothing (no crash in Hellfire)

**Comment by sarahkay88** [comment]
![World of Warcraft 24_03_2019 16_23_24](https://user-images.githubusercontent.com/42302580/54882376-45178e80-4e51-11e9-885f-2afb5a7714b5.png)
flying from temple of Telhamer to honour hold

**Comment by sarahkay88** [comment]
![World of Warcraft 24_03_2019 16_34_12](https://user-images.githubusercontent.com/42302580/54882515-c15ea180-4e52-11e9-9a8d-610c133f114a.png)
**valley of bones**
 sorry about the quest I was reading it when I crashed 
location under the map

**Comment by sarahkay88** [comment]
![World of Warcraft 24_03_2019 16_39_56](https://user-images.githubusercontent.com/42302580/54882597-91fc6480-4e53-11e9-9ea3-5ba07ce7d22c.png)

**Comment by sarahkay88** [comment]
![World of Warcraft 24_03_2019 16_44_31](https://user-images.githubusercontent.com/42302580/54882655-25ce3080-4e54-11e9-91b3-5df2ff5c2918.png)

**Comment by sarahkay88** [comment]
[23.46, 42.12]

**Comment by sarahkay88** [comment]
[14.11, 57.47]

**Comment by sarahkay88** [comment]
[16.02, 42.84]

**Comment by sarahkay88** [comment]
[34.59, 30,59]

**Comment by sarahkay88** [comment]
[51.72, 34.38]

**Comment by sarahkay88** [comment]
[58.41, 28.49]

**Comment by sarahkay88** [comment]
[70.47, 62.86]

**Comment by sarahkay88** [comment]
[53.03, 76.09]

**Comment by sarahkay88** [comment]
[45.12, 81.74]

**Comment by Saintres** [comment]
crashed at Cenarion Post. dunno co ords.

**Comment by Saintres** [comment]
Crashed at the ally flightpath inside the Dark Portal

**Comment by Saintres** [comment]
Crashed at 60,79 - 60,58

**Comment by Saintres** [comment]
Crashed at 56,92 - 59,46

**Comment by Saintres** [comment]
Crashed 56,93 - 59,72

**Comment by Saintres** [comment]
Crashed 53,04-61,03

**Comment by Saintres** [comment]
23,35-42,07

**Comment by wow-mania** [comment]
The thing is running the Launcher does not fix
Having 1.0.1 and updating to 1.0.2 is not the same thing
You need to get 1.0.2 from start
the Launcher does not fix the crash
the crash is caused by cache missing
which is not part of the Launcher check

**Comment by Echinaceax** [comment]
Ah makes sense @wow-mania 
this is why i dont crash then...

I downloaded from wow-mania site
