### ISSUE TITLE
[Quest] Je'neu of the Earthen Ring - id 824 - Blackfathom Deeps

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#1008]
**Links:**
https://www.wowhead.com/quest=824/jeneu-of-the-earthen-ring
https://www.wowhead.com/npc=12736/jeneu-sancrea
from WoWHead or our Armory

**What is happening:**
You have been asked to bring an item to Je'neu Sancrea who is standing in the Blackfathom Deeps. He isn't there.

**What should happen:**
The npc must placed.

Pitsecond: ORC warlock

**Comment by Rushor** [comment]
move to https://github.com/WoWManiaUK/Blackwing-Lair/issues/3663
