### ISSUE TITLE
[Quest] He's Holding Out on Us.

### ISSUE THREAD

**Issue by TenmanWoW** [WoWManiaUK/Blackwing-Lair#101]
Same phase issue with Prince Anduin, who also does not follow you to SI:7.

http://www.wowhead.com/quest=27064/hes-holding-out-on-us

It's worth noting that this quest has been marked obsolete by Blizz. It's been too long since I did this quests on retail to recall if this one was actually part of the chain.
![wowscrnshot_051218_151105](https://user-images.githubusercontent.com/25806987/39961213-36663a4c-55f7-11e8-969e-b5a812ceea52.jpg)

![wowscrnshot_051218_151530](https://user-images.githubusercontent.com/25806987/39961216-5d2fa866-55f7-11e8-8eef-d2cb59e8eba4.jpg)

**Comment by Echinaceax** [comment]
Using this report now as the issue remained bugged #3542
