### ISSUE TITLE
[NPC/Daily] Alegorn <Cooking Trainer>-4210- (issue 2) - Darnassus

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1011]
**Links:**

https://www.wowhead.com/npc=4210/alegorn

![cooking damas](https://user-images.githubusercontent.com/39439201/54886903-8594fd80-4e8d-11e9-8dad-20c164acab7b.jpg)

**What is happening:**
- Can take all 5 dailies 

**What should happen:**
- Should be only one daily per day

**Comment by Echinaceax** [comment]
_new info_ 

Since the "wrong currency fix" we have gone from 5 dailies a day to 0

- [ ] 5 dailies a day 
- [ ] 1 daily a day

**Comment by Rushor** [comment]
wotlk and classic quest pools were mixed here somehow. will fix

**Comment by Rushor** [comment]
fixed

only one quest and quest available and no wotlk fuck

![I](https://i.imgur.com/97oos1M.jpg)
