### ISSUE TITLE
[Daily/Cooking] list from Orgrimmar (Issue1)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1016]
_I will list all cooking dailies from Orgrimmar_

**What is happening:**
- [x] Stealing From Our Own - 9 gold 40 silver and 1 Chef's Award (at lvl10)
https://cata-twinhead.twinstar.cz/?quest=26233

**What should happen:**
- Stealing From Our Own - 1 silver 25 copper and 1 Chef's Award (at lvl10)

_Side note: Conflicted info on wowhead and Cata - twinhead
some not sure if its meant to be_ 

- 3 silver 50 copper (lvl 10)
or 
- 1 silver 25 copper (lvl 10)

**Edited for More** 

![marogg](https://user-images.githubusercontent.com/39439201/55284071-b1255580-536f-11e9-8739-18dad82e7edf.jpg)

**need these to be checked too** 

- [ ] Everything Is Better with Bacon (1 silver 25 copper)
- [ ] Careful, This Fruit Bites Back  (1 silver 25 copper)
- [ ] Crawfish Creole  (1 silver 25 copper)
- [ ] Even Thieves Get Hungry (11 gold  40 silver 0 copper)

**Comment by sarahkay88** [comment]
I believe this appears to be the same for all cooking NPC I found the same issue with NPC Alegorn.
link: https://www.wowhead.com/npc=4210/alegorn
he supplies the cooking daily's in Darnassus

**Comment by Echinaceax** [comment]
![marogg](https://user-images.githubusercontent.com/39439201/55284071-b1255580-536f-11e9-8739-18dad82e7edf.jpg)

**need these to be checked too** 

- [ ] Everything Is Better with Bacon (1 silver 25 copper)
- [ ] Careful, This Fruit Bites Back  (1 silver 25 copper)
- [ ] Crawfish Creole  (1 silver 25 copper)
- [ ] Even Thieves Get Hungry (11 gold  40 silver 0 copper)

**Comment by Echinaceax** [comment]
New info - Dailies scale to lvl

**Comment by Echinaceax** [comment]
@Kitzunu - No scaling to level seen atm
Tested with lvl85 and lvl20 same price 

level 20

![20 lvl same](https://user-images.githubusercontent.com/39439201/57192357-e6553280-6f2f-11e9-99f2-a6758b30dbf9.jpg)

level 85

![85 lvl](https://user-images.githubusercontent.com/39439201/57192371-f8cf6c00-6f2f-11e9-9c05-cdd3b27fc50c.jpg)
