### ISSUE TITLE
[NPC] Caynrus - visual bug - Darnassus

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1018]
**Links:**
NPC - https://www.wowhead.com/npc=4240/caynrus

**What is happening:**
Visual bug of blue and white box in his hand  see SS.

![World of Warcraft 25_03_2019 15_05_32](https://user-images.githubusercontent.com/42302580/54930619-7c4c7500-4f0f-11e9-8780-8f91ec36ba0b.png)

**What should happen:**
Should be no blue and white box.

**Comment by Dranah** [comment]
Looks like a client issue, cannot display his weapon or something...
