### ISSUE TITLE
[Quest] Hero's Call: Hyjal

### ISSUE THREAD

**Issue by TenmanWoW** [WoWManiaUK/Blackwing-Lair#102]
http://www.wowhead.com/quest=29391/guardians-of-hyjal-call-of-the-ancients

Upon accepting the quest, none of the NPC's are to be found to assist, as the quest directs. 

http://www.wowhead.com/npc=40955/goldrinn
http://www.wowhead.com/npc=41504/tortolla

**Comment by Echinaceax** [comment]
from 2018 this report 
Quest is obviously not meant to have been available at the release of the progressive status 

noting this info for future issue
