### ISSUE TITLE
[NPC] Lareth Beld - Mage Trainer - Darkshore

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1029]
**Links:**
https://www.wowhead.com/npc=49968/lareth-beld
**What is happening:**
This is the mage trainer located in Darkshore, The trainer does not show its skill book so I can see which spell I can and cannot train. 
**What should happen:**
When spoken to he should display the spell book so I can see which spells I can and cannot train.

**Comment by Kitzunu** [comment]
Not fixed
![image](https://user-images.githubusercontent.com/24550914/54990958-34375c00-4fbc-11e9-89a9-7e86959fad63.png)

**Comment by Rushor** [comment]
works now

![I](https://i.imgur.com/XTyIEoW.jpg)
