### ISSUE TITLE
Random death

### ISSUE THREAD

**Issue by TenmanWoW** [WoWManiaUK/Blackwing-Lair#103]
I'm not sure how to even describe this. We were just standing there discussing our recent findings and I died. Combat log shows nothing other than "Tenman died"

![wowscrnshot_051318_021034](https://user-images.githubusercontent.com/25806987/39964854-2a8946a4-5653-11e8-8457-e940e3f04f7c.jpg)

Then Kadaj died something like 40 times in a row.

Then Hotshotgg died the same amount of times.

**Comment by fvicaria** [comment]
Need to send me location and coords

**Comment by TenmanWoW** [comment]
Upon further examination, it appears it's a problem with the uber heal spell. The location pictured above is azshara. I will get specific coords tomorrow. It also happened in Uldum, Hyjal, and even Dal.
