### ISSUE TITLE
[NPC] Stephanie Krutstick - Archaeology trainer - Darkshore

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1033]
**Links:**
https://www.wowhead.com/npc=51997/stephanie-krutsick

**What is happening:**
NPC should provide me with Archaeology training however when spoken to doesn't offer me the option to train

**What should happen:**

Should provide me with the option to train this profession.

**Comment by Kitzunu** [comment]
not fixed
![image](https://user-images.githubusercontent.com/24550914/54991125-92643f00-4fbc-11e9-9bfb-d76f685013d8.png)

**Comment by Rushor** [comment]
hm works locally, restarted the server again. maybe also delete the cache :o

**Comment by Kitzunu** [comment]
@Rushor weird. Still no change.

I also reloaded everything ingame + deleted cache
