### ISSUE TITLE
[Item/Fishing] Violet Perch -58899- Darkshore

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1035]
**Links:**
https://cata-twinhead.twinstar.cz/?item=58899#objective-of

**What is happening:**
- this item is been fished without a quest in Darkshore 

**What should happen:**
- fishing for Thunder Falls quest 
https://cata-twinhead.twinstar.cz/?quest=26536

**Comment by Repsidian** [comment]
[issue 2] 
Links:
https://cata-twinhead.twinstar.cz/?item=58899#objective-of

What is happening:

this item is been fished without a quest in Azuremist isle
What should happen:

fishing for Thunder Falls quest
https://cata-twinhead.twinstar.cz/?quest=26536
