### ISSUE TITLE
[Quest] Power Over the Tides -ID 13523 -Darkshore

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1036]
**Links:**
Quest -https://www.wowhead.com/quest=13523/power-over-the-tides
NPC - https://www.wowhead.com/npc=32932
ITEM - https://www.wowhead.com/item=44975

**What is happening:**

When the item is used on the required mob https://www.wowhead.com/npc=32937 it releases the spirit has intended, however it is not then registered on the quest. Making the quest incompletable.

**What should happen:**
When the spirit is released the quest should acknowledge this and add it to the required number needed to complete the quest.

**Comment by Echinaceax** [comment]
reported here #705
