### ISSUE TITLE
[Item/fishing] Hardened Walleye -58503- Stormwind

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1037]
**Links:**
https://www.wowhead.com/item=58503/hardened-walleye

**What is happening:**
- Quest item fished up before having the quest 

**What should happen:**
- Must have quest first

**Comment by Rushor** [comment]
https://www.wowhead.com/quest=26414/hitting-a-walleye is required now for seeing the fish loot.

**Comment by Kitzunu** [comment]
Not fixed
![image](https://user-images.githubusercontent.com/24550914/54992608-fb998180-4fbf-11e9-9ef6-f69ce4d9945e.png)
