### ISSUE TITLE
[Quest] An ocean not so deep  - ID 13560 -Darkshore

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1038]
**Links:**
Quest - https://www.wowhead.com/quest=13560/an-ocean-not-so-deep
NPC - https://www.wowhead.com/npc=32979
Mobs - https://www.wowhead.com/npc=32852
BOT NPC - https://ptr.wowhead.com/npc=34207/foolhardy-adventurer
**What is happening:**

For this quest u are required to swim into the ocean to location [53.04, 11.06] to obtain a robot to help complete the quest. However the robot is missing its spells.

It also provides you with the breathing bar has if you were swimming in water. The issue is when you surface the bar doesn't reset. therefore you end up dying inside of the bot. you release your spirit and you come straight back to life were you die, you don't have to run back to your corpse.

**What should happen:**
The robot should have an aoe spell. (UNABLE TO FIND WHAT THE SPELL IS CALLED THO).
https://ptr.wowhead.com/npc=34207/foolhardy-adventurer
once leaving the water the breathing bar should reset and you shouldn't die.
when dying and releasing spirit you should be a ghost at the graveyard, you should then run back to your corpse to be brought back to life.

**Comment by Rushor** [comment]
okay fixed

![I](https://i.imgur.com/x96BAK8.jpg)
![I](https://i.imgur.com/hVz4Qnq.jpg)

you can enter the bot now, get to the murlocs, start the Depth Charge Countdown Pulse spell and they will get killed.
