### ISSUE TITLE
[Quest] No accounting for taste - ID 13527 - Darkshore

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1039]
**Links:**
Quest - https://www.wowhead.com/quest=13527/no-accounting-for-taste
NPC - https://www.wowhead.com/object=194105
**What is happening:**

The  bear carcase cannot be looted, preventing you from completing the quest

**What should happen:**
You are to loot the bears carcase located near by in order to complete this quest

**Comment by Rushor** [comment]
![](https://i.imgur.com/sWAvtr0.jpg)
