### ISSUE TITLE
[Spell] Arcane Blast

### ISSUE THREAD

**Issue by TenmanWoW** [WoWManiaUK/Blackwing-Lair#104]
Arcane blast (30451) does not trigger Arcane missles (5143) despite the tooltip on Arcane missles stating 40% chance when casting an offensive spell.

**Comment by TheManiax** [comment]
Make sure you don't have Brain Freeze talent in your spec.
![image](https://user-images.githubusercontent.com/14857593/39966064-a06929d6-56ba-11e8-9a5a-cdb3d67345b1.png)

**Comment by TenmanWoW** [comment]
Then I have no idea what is causing it. Any thoughts on that?
