### ISSUE TITLE
[Quest] War supplies - ID 13509 -Darkshore

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1042]
**Links:**
Quest - https://www.wowhead.com/quest=13509/war-supplies
NPC -https://www.wowhead.com/npc=32963
ITEM - https://www.wowhead.com/item=44999

**What is happening:**
Instead of burning the supplies the item put the depuff on the player causing damage to the player. there for unable to complete quest.

![World of Warcraft 25_03_2019 19_31_33](https://user-images.githubusercontent.com/42302580/54948696-2db1d180-4f35-11e9-9ace-bc658b1e4160.png)

![World of Warcraft 25_03_2019 19_42_28](https://user-images.githubusercontent.com/42302580/54949108-3fe03f80-4f36-11e9-9c61-1de0299980c3.png)
the box's also have imps inside

**What should happen:**

When near the supplies this item should burn them enabling the player to complete the quest, it should not go on the player.

there should be no imp in the box's

**Comment by Rushor** [comment]
fixed so far

![I](https://i.imgur.com/zqSVvQT.jpg)
