### ISSUE TITLE
[NPC] Teromoth (out of range issue) - Terokkar Forest

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1043]
**Links:**

from WoWHead or our Armory

**What is happening:**
When a warrior (human in this case) fight, i get the message im out of range even if i stand close to the red circle i get from targeted mob.
When i cast my fight abillities its ok but autoattac say im out of range.

**What should happen:**

**Comment by Echinaceax** [comment]
its the npc bugged not you :)
Name the npc and coords

**Comment by Kitzunu** [comment]
Well, you would have to tell me which one because there are 45 spawned of them.

On the one, I tested on it works, but it is probably not the same one you encountered the issue for.

I will leave this open for a while more. If no info is added I will close it until there is

**Comment by Kitzunu** [comment]
Will close until further info is added because I cannot reproduce
