### ISSUE TITLE
[Quest] Timely Arrival  -Darkshore

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1044]
**Links:**
Quest - https://www.wowhead.com/quest=13510/timely-arrival
NPC - https://www.wowhead.com/npc=32964

**What is happening:**

Auto completes

**What should happen:**
This is an escort quest. you should have to escort the NPC to safety.

**Comment by Rushor** [comment]
escortevent and fight added

![I](https://i.imgur.com/pOyw4zs.jpg)
![I](https://i.imgur.com/evGL6ei.jpg)
