### ISSUE TITLE
Mages spell cast while knocked over

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1045]
**What is happening:**

When my level 16 mage is casting spells against mobs forsaken lotters https://www.wowhead.com/npc=34046/forsaken-looter in Darkshore, she is sometimes knocked over, however this doesn't prevent her from continuing to cast her spells.

**What should happen:**

The spell should be interrupted.

**Comment by Echinaceax** [comment]
@Keader - main report fixed 

i noticed though that when i was knocked over i got a debuff "purse snatch" this caused GCD and i died

**Comment by Keader** [comment]
Hmm, try now...
Gcd should not be triggered anymore.

**Comment by Echinaceax** [comment]
@fixed thx keader
