### ISSUE TITLE
[Quest] Ending the Threat - Darkshore

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1047]
**Links:**
Quest -https://www.wowhead.com/quest=13515/ending-the-threat
NPC -https://www.wowhead.com/npc=33178

**What is happening:**

Cant speak with the NPC to start the attack, you can attack the mob but it takes little to no damage.

**What should happen:**
You Should speak with the NPC that u obtained the quest with. the surrounding NPCs then start to help with the attack.
Maybe an issue with the damage that the boss takes 2?

**Comment by sarahkay88** [comment]
I plled the boss out n left the NPC's to attack whilst I cam and made this report, on my return to the game the boss had only just reached half health and the surround mobs had respawned

**Comment by Echinaceax** [comment]
Agree with @sarahkay88 
Took 5 soul fire to get it down (npc was grey for me) 
something definitely not right with that "damage taken on the npc

**Comment by Rushor** [comment]
done. you can now start the attack by clicking the gossip and the boss will loose his shield once the questgiver yelled.

![I](https://i.imgur.com/AIlvvoQ.jpg)
![I](https://i.imgur.com/E9fZ7bC.jpg)
![I](https://i.imgur.com/Cjq3t73.jpg)
![I](https://i.imgur.com/xY8KGNk.jpg)
![I](https://i.imgur.com/ou0Rnxx.jpg)
