### ISSUE TITLE
[Quest] Twice Removed  - ID 13565 -Darkshore

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1051]
**Links:**
Quest - https://www.wowhead.com/quest=13565/twice-removed
NPC - https://www.wowhead.com/npc=33126
ITEM - https://www.wowhead.com/item=45911

**What is happening:**
Item just spawns a tree when used on the required mobs nothing happens with the quest.
**What should happen:**
Should go towards the quest to enable completion.

**Comment by Rushor** [comment]
creatures will spawn and give the credit

![I](https://i.imgur.com/Pnz4QsE.jpg)
