### ISSUE TITLE
[Quest] Pie for Billy -60401- Elwynn Forest

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Blackwing-Lair#1052]
**Links**
https://www.wowhead.com/item=60401/tender-boar-meat
https://www.wowhead.com/npc=246/auntie-bernice-stonefield

**What is happening** 

You are supposed to gather 4 Tender Boar Meat, wowhead showing that droprate of the linked item is 22%, yet i have killed over 20 pigs to gather 4 of them, could check drop rate here, 

**What should happen**
- quest item Tender Boar Meat should drop

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/56204015-c1fbe980-6046-11e9-8fc6-f8dd4da4fb5a.png)
