### ISSUE TITLE
[npc=18115] Daggerfen Muckdweller - Zangarmarsh

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1053]
**Links:**
[npc=18115]
https://www.wowhead.com/npc=18115/daggerfen-muckdweller
from WoWHead or our Armory

**What is happening:**
There is some [npc=18115]Daggerfen Muckdweller that  is untargeteble in 24,47 - 27,38
in the house/tower. It's in Zangarmarch.

**What should happen:**
U should be able to target these guys

**Comment by Rushor** [comment]
hmm works fine on dev - could you please check the guid if possible for the creauture if still wrong?

**Comment by Kitzunu** [comment]
@Rushor I found the NPC's

Entry: 19733
DB GUID: 70587, 70586, 70585, 70584

**Comment by Kitzunu** [comment]
They were only targetable with GM ON

**Comment by Rushor** [comment]
nice thank you!

**Comment by Kitzunu** [comment]
@Rushor Great!
