### ISSUE TITLE
[Quest] Missing text when handing in a quest

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Blackwing-Lair#1054]
Missing "RewardText"

- [x] https://www.wowhead.com/quest=14442/my-favorite-subject
- [x] https://www.wowhead.com/quest=14469/hand-me-downs
- [x] https://www.wowhead.com/quest=14323/absorbent
- [x] https://www.wowhead.com/quest=14131/a-little-pick-me-up
- [x] https://www.wowhead.com/quest=14132/thats-just-rude
- [x] https://www.wowhead.com/quest=14345/wash-out
- [x] https://www.wowhead.com/quest=14435/the-blackmaw-doublecross

**Comment by Kitzunu** [comment]
I will check my database to see if it works there.

**Comment by Kitzunu** [comment]
Does not work on my core either.

**Comment by sarahkay88** [comment]
https://www.wowhead.com/quest=28263/meet-with-maginor-dumas
https://www.wowhead.com/quest=27271/journey-to-the-wizards-sanctum

**Comment by Kitzunu** [comment]
- [ ] https://www.wowhead.com/quest=26192/orphans-like-cookies-too inkl, progression text

**Comment by Saintres** [comment]
This quest is minnsing text when hand it in 
https://www.wowhead.com/quest=29021/samophlange

**Comment by sarahkay88** [comment]
- [ ] https://www.wowhead.com/quest=14162/report-to-horzak

**Comment by Kitzunu** [comment]
Added for quests 26028, 26100, 26073, 26016

**Comment by sarahkay88** [comment]
@Kitzunu 
- [  ] https://www.wowhead.com/quest=26660/zombie-juice

**Comment by sarahkay88** [comment]
- [ ] https://www.wowhead.com/quest=165/the-hermit

**Comment by sarahkay88** [comment]
- [ ] https://www.wowhead.com/quest=26780/nighttime-in-the-jungle
- [ ] https://www.wowhead.com/quest=26782/the-moshogg-bounty
