### ISSUE TITLE
[NPC] Innkeeper Farley - ID 295 Elwynn Forest

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Blackwing-Lair#1055]
https://www.wowhead.com/npc=295/innkeeper-farley

![Screenshot_3](https://user-images.githubusercontent.com/43518434/55001200-589f3280-4fd4-11e9-95f2-5f40715a9577.png)

**What is happening**
The NPC is showing the Trick or Treat as it is shown on the screenshot while there is no Halloween event going on, might be related to all innkeepers.

**What should happen:**
He shouldnt be showing that as on option once you are talking to him

**Comment by Echinaceax** [comment]
@Kitzunu - still not clickable

**Comment by Kitzunu** [comment]
That wasnt reported, but I will look into it.

it seems to have something to do with The Hallow's End event

**Comment by Kitzunu** [comment]
Fixed
