### ISSUE TITLE
[NPC] Frenzied Cyclone - visual- Darkshore

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1057]
**Links:**
https://www.wowhead.com/item=45911

**What is happening:**
some of these mobs are invisible they can be killed but then cannot be looted even though they sparkle to say there is loot,
![World of Warcraft 26_03_2019 15_11_52](https://user-images.githubusercontent.com/42302580/55009221-1aa50d00-4fda-11e9-8a18-fb12848bf795.png) - **what they should look like.**

![World of Warcraft 26_03_2019 15_17_37](https://user-images.githubusercontent.com/42302580/55009370-563fd700-4fda-11e9-8ab1-8347a0f555bf.png)
**what some look like now**

**What should happen:**
They should look like world pool n should be loot able.

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/59153954-2d6ea000-8a67-11e9-9411-6581d74d0d3e.png)
