### ISSUE TITLE
[Quest] The last Refugee - Darkshore

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1058]
**Links:**
Quest - https://www.wowhead.com/quest=13605/the-last-refugee
NPC - https://www.wowhead.com/npc=33232
**What is happening:**

Quest auto completed.

**What should happen:**

This is an escort quest, you should have to escort the NPC to safety.

**Comment by Rushor** [comment]
fixed and all roleplay added at the end.

![I](https://i.imgur.com/vauQZpe.jpg)
![I](https://i.imgur.com/TyH5gZG.jpg)
![I](https://i.imgur.com/nXzCLvs.jpg)
![I](https://i.imgur.com/Ws7OJU1.jpg)
![I](https://i.imgur.com/kobppXY.jpg)
![I](https://i.imgur.com/PG2k22Y.jpg)
