### ISSUE TITLE
[Missing Quest] Gurtar's Request - Ashenvale - 13875

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#1059]
**Links:**
[Quest] https://www.wowhead.com/quest=13875/gurtars-request
[Begin] https://www.wowhead.com/npc=34242/guardian-gurtar
[End] https://www.wowhead.com/npc=33726/splintertree-demolisher
from WoWHead or our Armory

**What is happening:**

NPC is present

**What should happen:**

Pitsecond: ORC warlock

**Comment by Echinaceax** [comment]
Not sure what the issue is here ?
