### ISSUE TITLE
[Quest] Hero's call: Mt Hyjal

### ISSUE THREAD

**Issue by TenmanWoW** [WoWManiaUK/Blackwing-Lair#106]
The NPC in SW, when talked too, does have the option of transportation to moonglade. However, after the animation, you're still in SW and have to restart the dialogue box to ask again.

http://www.wowhead.com/quest=27726/heros-call-mount-hyjal

**Comment by TenmanWoW** [comment]
And asking again produces the original result of still being in SW. The portal is non-interactive, as well.

**Comment by Echinaceax** [comment]
Working on dev
 
![hero call hyjal](https://user-images.githubusercontent.com/39439201/65968787-fbdd7280-e463-11e9-9599-a05e61f7ab6e.jpg)
