### ISSUE TITLE
[Quest] Against the wind - ID 13452 - Darkshore

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1060]
**Links:**
Quest - https://www.wowhead.com/quest=13542/against-the-wind
NPC - https://www.wowhead.com/npc=3694
ITEM - https://www.wowhead.com/item=44868
**What is happening:**

Cannot destroy the braces in the moon well. Keeps saying require Auberdine moon well. even when stood inside it. She starts to act has if she about to break them, then stops.

**What should happen:**

The moon well should destroy the braces so you can complete the quest.

**Comment by Xman993** [comment]
you get  [**Frenzied Cyclone Bracers**](https://www.wowhead.com/item=44868/) when you're not on the quest what shouldn't happen.

**Comment by Echinaceax** [comment]
> you get [**Frenzied Cyclone Bracers**](https://www.wowhead.com/item=44868/) when you're not on the quest what shouldn't happen.

seperate issue @Xman993 (please report the item) thank you

**Comment by Echinaceax** [comment]
i completed this fine just now :)
