### ISSUE TITLE
[NPC = 44128] Sarithra - Silvermoon 

### ISSUE THREAD

**Issue by dandancanfly** [WoWManiaUK/Blackwing-Lair#1063]
**Links:**

https://www.wowhead.com/npc=44128/sarithra

**What is happening:**

I am a Tauren shaman. Sarithra in Silvermoon provides the menu to train warrior skills [although I can't actually train]

![image](https://user-images.githubusercontent.com/11138461/55013016-b163d080-4fbe-11e9-9f2f-f575989fe038.png)

**What should happen:**

She should provide a "I only train warriors, shaman, I cannot train you"-style dialog.

**Comment by Kitzunu** [comment]
Well, now she doesnt train Warriors either :joy:
![image](https://user-images.githubusercontent.com/24550914/55027601-f4956200-5005-11e9-9041-991fb602ad03.png)
