### ISSUE TITLE
[Quest] Mutual Aid - Darkshore

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1067]
**Links:**
QUEST - https://www.wowhead.com/quest=13576/mutual-aid
NPC - https://www.wowhead.com/npc=33117
ITEM - https://www.wowhead.com/item=44959

**What is happening:**

You can spam the item on one dead mob to complete the quest.

**What should happen:**
Should only be use on one mob at a time, you should have to kill one mob use item, kill another mob use item to complete the quest.

**Comment by Rushor** [comment]
added an 18 sec cooldown to prevent abuse

![I](https://i.imgur.com/M7rn737.jpg)
