### ISSUE TITLE
[Wintergrasp]  Cant Fly - Wintergrasp

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1069]
**Links:**
https://www.wowhead.com/item=25533/swift-purple-wind-rider

![cant fly](https://user-images.githubusercontent.com/39439201/55028909-2825bb80-5009-11e9-965e-392b9186cf36.jpg)

**What is happening:**
- Cant fly (Swift purple wind rider) 

**What should happen:**
- With cold weather flying you should be able too fly here

**Comment by Kitzunu** [comment]
Is wintergrasp in progress?

**Comment by Echinaceax** [comment]
> Is wintergrasp in progress?

Nope is a dead zone 

- No npcs

**Comment by Echinaceax** [comment]
BUMP 
Cant we get this fixed please.
Took a FP from Sholazer Basin to Zul'drak and i cant Go through WG ..this isnt good 

![no flying](https://user-images.githubusercontent.com/39439201/58024993-c0c14f00-7b13-11e9-9115-04eefbb490b5.jpg)

Iam stuck on the FP now for how ever long the battle is on lol

**Comment by Keader** [comment]
```
@wow-mania wow-mania added Fixed in Dev  and removed Fixed but not in ptr/dev yet  labels 37 minutes ago
```
```
Server uptime: 26 Minute(s) 7 Seconds(s).
```
Yeah it not work.

**Comment by Keader** [comment]
@wow-mania change label when you build it.
ftp access is fucked :/
