### ISSUE TITLE
[Hostiles] Mobs Seeing Range

### ISSUE THREAD

**Issue by jsfriendGaming** [WoWManiaUK/Blackwing-Lair#107]
In WoW you usually have to be like 5 - 10 yards away for a Hostile mob to come and attack you.  I've been noticing that when I run near a Hostile and I'm not in a 10 yard range to even cast a spell that I get attacked.  Now I don't know if this is Cata or a Bug but I definitely don't think this is right.  The pictures below show you how far away I am before the charge and then the 2nd one shows you all 4 of them ganged up on me within secs.
![wowscrnshot_051218_212617](https://user-images.githubusercontent.com/38737813/39969515-425f55ee-56a2-11e8-8640-55890d9dc370.jpg)
![wowscrnshot_051218_212621](https://user-images.githubusercontent.com/38737813/39969516-45054e0c-56a2-11e8-85f8-d3b1d90d72d3.jpg)

**Comment by jsfriendGaming** [comment]
Here's a Video that I just made Don't worry it's Unlisted https://youtu.be/a5xHVoB1raM

**Comment by Dranah** [comment]
Mobs attack range has always depended on the difference of level between the creature and the player. It has never been a static number.
The higher level you are, the closer you can get to a mob without it aggroing.
Hitboxes and visual size of the mobs also affect how close you can get, as well as how great distance you have to run after the pull until you can attack with melee abilities.
Mobs have a group-pull behavior, which means if you aggro a mob that has other mobs loosely spreaded around it, even the mobs that are out of the normal "aggro range" will engage together with the mob you originally aggroed.
Lastly, mobs that patrol tend to be affected by server lag and their pathing is sometimes glitchy, which means they aren't exactly where you see they are.

Please provide links and evidences from trustworthy sources if you still insist the mobs you encountered are bugged.
