### ISSUE TITLE
[NPC ]  Stoneguard Kurjack - missing -Ragefire Chasm

### ISSUE THREAD

**Issue by dandancanfly** [WoWManiaUK/Blackwing-Lair#1070]
**Links:**

https://www.wowhead.com/npc=44217/stone-guard-kurjack

https://www.wowhead.com/quest=31036/enemies-below

I picked up the quest in Thunder Bluff, although I don't think it matters which version of the quest is picked up.

**What is happening:**

NPC 44217 is missing in RFC, can't turn in the quest 31036.

![image](https://user-images.githubusercontent.com/11138461/55031005-0108c300-4fe4-11e9-9004-4d58b4e329aa.png)

**What should happen:**

The NPC should exist so we can turn in the quest

**Comment by Rushor** [comment]
all those must be fixed with alliance/horde checks in core script

**Comment by Keader** [comment]
Well, has  no script, looks db only lol

**Comment by Rushor** [comment]
creature added.

only visible to horde

![I](https://i.imgur.com/yIletW3.jpg)
![I](https://i.imgur.com/Q03RZfH.png)
