### ISSUE TITLE
[Wintergrasp/pvp] NPCs missing - Wintergrasp

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1071]
**Links:**
https://www.wowhead.com/wintergrasp

**map shows npcs but there not there** (only FP here) 

_Side note not sure if it because WG isnt actually active atm (but info here just incase)_

![WG no npc](https://user-images.githubusercontent.com/39439201/55031206-640f4f80-500e-11e9-9982-ff9cb808ba48.jpg)

**Horde**

**What is happening:**

_Commander Dardosh_
- [ ] https://www.wowhead.com/npc=31091/commander-dardosh
 https://www.wowhead.com/quest=13178/slay-them-all

_Lieutenant Murp_
- [ ]  https://www.wowhead.com/npc=31107/lieutenant-murp
https://www.wowhead.com/quest=13223/defend-the-siege
https://www.wowhead.com/quest=13185/stop-the-siege

_Siegesmith Stronghoof_
- [ ] https://www.wowhead.com/npc=31106/siegesmith-stronghoof
 https://www.wowhead.com/quest=13191/fueling-the-demolishers

_Hoodoo Master Fujin_
- [ ] https://www.wowhead.com/npc=31101/hoodoo-master-fujin
https://www.wowhead.com/quest=13202/jinxing-the-walls
https://www.wowhead.com/quest=13192/warding-the-walls

_Vieron Blazefeather_
- [ ] https://www.wowhead.com/npc=31102/vieron-blazefeather
https://www.wowhead.com/quest=13193/bones-and-arrows 

_Primalist Mulfort_
- [ ] https://www.wowhead.com/npc=31053/primalist-mulfort
https://www.wowhead.com/quest=13194/healing-with-roses

_Tactical Officer Kilrath_
- [ ] https://www.wowhead.com/npc=31151/tactical-officer-kilrath
https://www.wowhead.com/quest=13539/toppling-the-towers
https://www.wowhead.com/quest=13183/victory-in-wintergrasp

**What should happen:**
- all should be here :)

**Comment by Echinaceax** [comment]
**Ally** 

_Commander Zanneth_
- [ ] https://www.wowhead.com/npc=31036/commander-zanneth
https://www.wowhead.com/quest=13177/no-mercy-for-the-merciless

**Comment by Echinaceax** [comment]
Any ETA on this ?

**Comment by Rushor** [comment]
this seem to work now, if correct phasing aura is there on char, you can see them
