### ISSUE TITLE
Dariness the Learned <Archaeology Trainer>- 93538- (Missing) - Dalaran

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1074]
**Links:**

https://www.wowhead.com/npc=93538/dariness-the-learned

**What is happening:**
- Trainer missing 

**What should happen:**
- Should be here

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/56071930-2fcbbb00-5d92-11e9-9a52-9411d01d96da.png)
