### ISSUE TITLE
Hellsfire (Dark Portal) [npc=18944]  

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1077]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/npc=18944/fel-soldier
[npc=18944]
**What is happening:**
These Fel Soldiers [npc=18944] spawn up way to many on same time and make the server lag lots. And they just keep spawning more and more.

**What should happen:**
They should spawn 1 by 1 in their portals and walk the way to the stairs just inside the dark Portal.

**Comment by Echinaceax** [comment]
#609
