### ISSUE TITLE
[Quest/Order] Farshire - 11928 - missing prereq - Borean Tundra

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1079]
**Links:**
https://www.wowhead.com/borean-tundra
from WoWHead or our Armory

**What is happening:**
The startquests comes in a wrong order, for instance you can get  [quest=11928] Farshire
in the beginning and that is to early.

**What should happen:**
You should complete 3 quests befor getting this one from same NPC [npc=25816]

**Comment by Dranah** [comment]
Each quest/chain requires a separate report.

**Comment by Dranah** [comment]
https://www.wowhead.com/quest=11928/farshire should require https://www.wowhead.com/quest=11897/plug-the-sinkholes to be handed in before becoming available.

Currently available without prereq.
