### ISSUE TITLE
[NPC] Dentaria Silverglade - missing -Darkshore

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1081]
**Links:**
NPC - https://www.wowhead.com/npc=32973/dentaria-silverglade#comments
QUEST - https://www.wowhead.com/quest=13518/the-last-wave-of-survivors

**What is happening:**
Missing from her locations in Darkshore

**What should happen:**

Should be located either in the inn or on the dock depending on how far into the quests you are.

**Comment by sarahkay88** [comment]
this prevents NPC - https://www.wowhead.com/npc=32959/cerellean-whiteclaw#comments from spawning.
He has two further quests:
quest 1 - https://www.wowhead.com/quest=13563
quest 2 - https://www.wowhead.com/quest=13570

**Comment by Rushor** [comment]
duplicate https://github.com/WoWManiaUK/Blackwing-Lair/issues/1032
