### ISSUE TITLE
[Quest] Bearer of good fortune- ID 13557 - Darkshore

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1086]
**Links:**
Item -https://www.wowhead.com/item=44927/corruptors-master-key#comments
Quest -https://www.wowhead.com/quest=13557/bearer-of-good-fortune

**What is happening:**

Item doesn't register the animals being freed.

**What should happen:**
when freed the animals should register towards the quest.

**Comment by sarahkay88** [comment]
ho its finally dropped

**Comment by Echinaceax** [comment]
reported already #704
