### ISSUE TITLE
[Quest] The Ritual Bond -ID 13569 -Darkshore

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1090]
**Links:**
Quest - https://www.wowhead.com/quest=13569/the-ritual-bond
NPC -https://www.wowhead.com/npc=33048
from WoWHead or our Armory
**What is happening:**

Was not provided with the above quest

**What should happen:**
Should be Provided with the above quest.

**Comment by sarahkay88** [comment]
further reading says its a follow on quest from one I previously reported

**Comment by Echinaceax** [comment]
@Rushor wasnt given quest in quest log
