### ISSUE TITLE
[NPC] Zjolnir <Raptor Handler>-7952- Durotar

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1091]
_Using a belf priest_

**Links:**
NPC - https://www.wowhead.com/npc=7952/zjolnir
1. https://www.wowhead.com/quest=7664/ivory-raptor-replacement
2. https://www.wowhead.com/quest=7665/red-raptor-replacement

![mount quests](https://user-images.githubusercontent.com/39439201/55093778-5e207980-50b5-11e9-890d-fc23450a373e.jpg)

**What is happening:**
- NPC is offering replacements

**What should happen:**
- According to comments not sure TBH 
https://www.wowhead.com/quest=7665/red-raptor-replacement

so ive reported it anyway (just coz i see it) and with Blue (?)

**Comment by Kitzunu** [comment]
I will close this issue under the label Pending.

From my understanding, only the original mounts were removed so they cannot be obtainable.
Though WoW-Head says these quests are now no longer available however that is bfa info and if you check WoWiki or Gamepedia there is no logged changelog that they actually were removed from the game.
