### ISSUE TITLE
[Quest] Stepping up the Surveillance  - Darkshore

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1093]
**Links:**
Quest - https://www.wowhead.com/quest=13948/stepping-up-surveillance
NPC- https://www.wowhead.com/npc=34402

**What is happening:**
quest completes just by having the item on in the are

**What should happen:**
You should have to go to the platform and spy on the npc

**Comment by sarahkay88** [comment]
had to run back to the npc to hand a different quest in and found it.

**Comment by Rushor** [comment]
texts and quest complete added

![I](https://i.imgur.com/DWHUBc1.jpg)
