### ISSUE TITLE
[NPC] Kitha <Demon Trainer>-6027- Durotar

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1096]
**Links:**
https://www.wowhead.com/npc=6027/kitha

![no window](https://user-images.githubusercontent.com/39439201/55098387-f7538e00-50bd-11e9-82a7-c724cbe45731.jpg)

**What is happening:**
- NPC isnt opening for my warlock 
- Inactive

**What should happen:**
- Should open a window 

```
UPDATE `creature_template` SET `gossip_menu_id`='12670', `npcflag`='3' WHERE subname like '%Demon Trainer%';
```

**Comment by Kitzunu** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/1812
