### ISSUE TITLE
[Quest] The seeds of Life -13882- Darkshore

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1097]
**Links:**
Quest - https://www.wowhead.com/quest=13882/the-seeds-of-life
NPC - https://www.wowhead.com/npc=34301
ITEM 1 - https://www.wowhead.com/item=46354 -SEED OF EARTH
ITEM 2 -https://www.wowhead.com/item=46356 - SEED OF THE SEE (can obtain)
ITEM 3 -https://www.wowhead.com/item=46355 - SEED OF THE SKY

**What is happening:**
Cannot interact with the NPC Onu -  https://www.wowhead.com/npc=147758/onu to receive the of earth - doesn't provide correct speech dialog
Cannot capture NPC Darkshore wisp -https://www.wowhead.com/npc=34306/darkshore-wisp to receive seed of the sky - these should also be moving but are currently stationary

**What should happen:**

Should be able to interact with the required NPCS in order to complete the quest

**Comment by sarahkay88** [comment]
prevents 3 further quests:
quest 1 - https://www.wowhead.com/quest=13925
quest 2 - https://www.wowhead.com/quest=13885
quest 3 - https://www.wowhead.com/quest=13891

**Comment by Rushor** [comment]
all done,

you can get the seeds by spellclick and from the object and the item from onu

![I](https://i.imgur.com/aojBz68.jpg)
![I](https://i.imgur.com/3nI6kxT.jpg)
![I](https://i.imgur.com/VFGPqAD.jpg)
![I](https://i.imgur.com/kgm4pjA.jpg)
