### ISSUE TITLE
[Quest] Slay Darkscale Warlord -ID 13899 - Darkshore

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1099]
**Links:**
Quest - https://www.wowhead.com/quest=13899/the-darkscale-warlord
NPC - https://www.wowhead.com/npc=34402

**What is happening:**
When picked up the quest is already classed has completed

**What should happen:**
I should have to slay the Darkscale Warlord before the quest is completed

**Comment by Echinaceax** [comment]
This one explain more info 

will close this one #716

**Comment by Rushor** [comment]
yes that's correct the quest is autocomplet, but there must be an action to fight against the lord and then he will tirn friendly 

https://www.wowhead.com/quest=13899/the-darkscale-warlord#videos:id=33159

**Comment by Rushor** [comment]
![](https://i.imgur.com/pT5g74B.jpg)
![](https://i.imgur.com/BmoKrqD.jpg)
