### ISSUE TITLE
[Quest] Save krennan Aranas

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Blackwing-Lair#11]
http://www.wowhead.com/quest=14293/save-krennan-aranas

You have to  save  the npc Krennan Aranas, after accepting the  q  an horse  appear and you ride to the npc  who jump on the horse so you can bring him to safety.

but after accepting the  q no horse appears  so you cant do the asignment

![wowscrnshot_030718_201332](https://user-images.githubusercontent.com/33811022/37112952-379a4d5e-2244-11e8-9e49-b0f54add1866.jpg)
![wowscrnshot_030718_201337](https://user-images.githubusercontent.com/33811022/37112953-37b6871c-2244-11e8-94d3-bd86c4ff5fa1.jpg)

**Comment by Dranah** [comment]
Indeed , there is an improvement, you get mounted - but the NPC Krennan Aranas is missing.
NPC ID 35753 is the Krenan Aranas you have to pick up by the tree >> Coords (65,4;62,2)
NPC ID 35907 is the Krenan Aranas that mounts the horse behind you after you pick him.
Spell ID 68219 is the horse ability that must be able to pick up the NPC and make him mounted.

**Comment by Rushor** [comment]
A lot must be improved here. You always drop below the ground. Will fix the pathing.

Reported by Giles

![I](https://i.imgur.com/mHflaIX.jpg)
![I](https://i.imgur.com/qoh0s50.jpg)
![I](https://i.imgur.com/V5my3RG.jpg)

**Comment by giles1508** [comment]
This worked great after the fix dude :)
