### ISSUE TITLE
[NPC] Warlord Wrathspine - Darkshore

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1100]
**Links:**
https://www.wowhead.com/npc=34423/warlord-wrathspine
**What is happening:**
Can be fully killed which prevents you from handing in the quest https://www.wowhead.com/quest=13899/the-darkscale-warlord
and also collecting a further quest.

**What should happen:**

at 1% health he should turn friendly allowing me to hand my quest in and collected the next quest https://www.wowhead.com/quest=13900/the-offering-to-azshara

**Comment by Rushor** [comment]
he will turn freindly and despawn after 60 seconds
