### ISSUE TITLE
[NPC]  Takrin Pathseeker -3336- Durotar

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1102]
**Links:**

https://www.wowhead.com/npc=3336/takrin-pathseeker
Quest - https://www.wowhead.com/quest=840/conscript-of-the-horde

![takrin](https://user-images.githubusercontent.com/39439201/55107173-ef511980-50d0-11e9-9c02-994a1fbc20c3.jpg)
![quest missing](https://user-images.githubusercontent.com/39439201/55107177-f11add00-50d0-11e9-92d4-caccaeceadb1.jpg)

**What is happening:**
- Quest giver doesnt give quest

**What should happen:**
- Should give this quest 
https://cata-twinhead.twinstar.cz/?search=Conscript+of+the+Horde

**Comment by Dranah** [comment]
Doesnt this have pre quests?

**Comment by Echinaceax** [comment]
> Doesnt this have pre quests?

Didnt see one Dranah

**Comment by Rushor** [comment]
has prevquest https://www.wowhead.com/quest=871
