### ISSUE TITLE
[Quest]  Spirits Be Praised -25189- (auto completed) - Durotar

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1103]
**Links:**
https://www.wowhead.com/quest=25189/spirits-be-praised

**What is happening:**
(auto completed)

**What should happen:**
https://www.wowhead.com/quest=25189/spirits-be-praised#videos:id=35529

**This quest was marked obsolete by Blizzard and cannot be obtained or completed.**

_Escort Grandmatron Tekla to Raggaran_

**Comment by Venom64bit** [comment]
There are two Grandmatron Tekla
First Coords: 40,46 35,40 (Where the quest should begin)
Second Coords: 40,04 40,22
