### ISSUE TITLE
[NPC]  Spiketooth <Slavedriver>-39590- Durotar

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1104]
**Links:**

npc - https://www.wowhead.com/npc=39590/spiketooth
1. https://www.wowhead.com/quest=25259/gaur-icehorn
2. https://www.wowhead.com/quest=25257/ghislania
3. https://www.wowhead.com/quest=25258/griswold-hanniston

**What is happening:**
- none of these quest npcs has Gossip in chat window 
- i could complete though by just attacking them without initiating the fight 

**What should happen:**
https://www.wowhead.com/quest=25259/gaur-icehorn#videos:id=35652
https://www.wowhead.com/quest=25257/ghislania
https://www.wowhead.com/quest=25258/griswold-hanniston

**Comment by Echinaceax** [comment]
@Rushor reopened this

**Comment by Rushor** [comment]
yeah one fix killed the other fix back in the days. now works with correct creature script. all implemented
