### ISSUE TITLE
[NPC]  Call of Duty (horde) - 25924- Durotar / Vashj'ir

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1106]
**Links:**
https://www.wowhead.com/quest=25924/call-of-duty
https://www.wowhead.com/npc=41621/commander-thorak

**What is happening:**
- He dont have the quest "call of duty (unlocks Vashj'ir lvl80 ) 

**What should happen:**
Quest end https://www.wowhead.com/npc=41618/erunak-stonespeaker

**Comment by Rushor** [comment]
you first need to do http://cata.cavernoftime.com/quest=28790 then http://cata.cavernoftime.com/quest=28805 and then you will get Call of Duty

![I](https://i.imgur.com/Wcjz0dr.jpg)

that works on dev

**Comment by Eirolla** [comment]
Quest is not eligible on Blackwing Lair.

**Comment by Sammy974** [comment]
Once accepted, nothing happens.

**Comment by Sammy974** [comment]
The ship brougth me to Stonetalon Mountains then went back to the Orgrimmar dock. There's something wrong.

**Comment by Echinaceax** [comment]
@Sammy974 made report for the ship bug here #4570
