### ISSUE TITLE
[Quest] A New Home -ID 13910 - Darkshore

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1107]
**Links:**
Quest -https://www.wowhead.com/quest=13910/a-new-home
NPC -https://www.wowhead.com/npc=34340
ITEM - https://www.wowhead.com/item=46385

**What is happening:**
Can't build a new hut on the beech at the correct spot, used the item but nothing happens. Unable to complete the quest

**What should happen:**
When used at the correct spot a new hut for murloc's is supposed to be made completing the quest

**Comment by Rushor** [comment]
credit and hut and murlocspawns added
![I](https://i.imgur.com/IfWgiQi.jpg)
