### ISSUE TITLE
[npc=42015] Gnomish Bomber (Mass spawn) Urgent - Stonetalon Mountains

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1111]
**Links:**
https://www.wowhead.com/npc=42015/gnomish-bomber
from WoWHead or our Armory

**What is happening:**
There is a mass spawn on these Bombers in Windshear Craig/ Stonetalon Mountain
66,31 - 59,21
Cause huge lagg, they should not be here / so many.

**What should happen:**
I have no clue

**Comment by wow-mania** [comment]
Not cause of lag.
They are not spawning. They are fixed.
I will reduce some.

**Comment by Saintres** [comment]
they are like hundred
