### ISSUE TITLE
[NPC]  Orgrimmar Grunt (lvl85)  -31416- Orgrimmar

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1113]
**Links:**

https://www.wowhead.com/npc=31416/orgrimmar-grunt

![grunt](https://user-images.githubusercontent.com/39439201/55117821-5f20cd80-50ec-11e9-9226-fbbc866a393e.jpg)

**What is happening:**
- positioning 

**What should happen:**
Tell him to get off the bed, shouldn't be stood on top bed :)

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/63310748-2d5b0e00-c2fc-11e9-8d6b-733566b7b854.png)
