### ISSUE TITLE
[quest=25809]  [Leave No Man Behind! ] - Stonetalon Mountains

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1115]
**Links:**
https://www.wowhead.com/quest=25809/leave-no-man-behind
from WoWHead or our Armory

**What is happening:**
There is some miners that i probably should rescue but they are interactive and not targetable so i cant complete this quest
[npc=41283]

**What should happen:**
They should be activated so i can target and talk/rescue them

**Comment by Rushor** [comment]
credit emotes and despawn added

![I](https://i.imgur.com/zaUPtCA.jpg)
