### ISSUE TITLE
[NPC]  Roxxik <Engineering Trainer>-11017- Orgrimmar

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1116]
**Links:**

https://www.wowhead.com/npc=11017/roxxik

![offers me eng](https://user-images.githubusercontent.com/39439201/55119218-4b2b9a80-50f1-11e9-8b8f-52458b5731a5.jpg)

**What is happening:**
- Offers me engineering without the profession
- Shouldnt do that 

**What should happen:**
Only for Engineers

**Comment by Rushor** [comment]
remember to delete cache before testing
