### ISSUE TITLE
[quest=25837]  [A Proper Peace Offerin'] - Stonetalon Mountains

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1117]
**Links:**
https://www.wowhead.com/quest=25837/a-proper-peace-offerin
https://www.wowhead.com/item=56042/boulderslide-cheese
from WoWHead or our Armory

**What is happening:**
this quest is not completable since this item [item=56042] dont drop from required mobs.
Droprate according to wowhead is 32-35%, id say 0 % is more correct, killed over 70 mobs
Quest not completable.
[npc=11918]
[npc=11915]
[npc=11917]
**What should happen:**
These guys should drop the item [item=56042] 
[npc=11918]
[npc=11915]
[npc=11917]

**Comment by Kitzunu** [comment]
Fixed, will send when I am home
