### ISSUE TITLE
[Quest] Blown Away (horde) - Ogrimmar

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1118]
**Links:**

https://www.wowhead.com/quest=29401/blown-away

**What is happening:**
- Limited balloons (needs more)

**What should happen:**

this is how it should look :)

- May need to add more 

![balloon map](https://user-images.githubusercontent.com/39439201/55120638-1c182780-50f7-11e9-805b-74b778f12955.jpg)

**Comment by mfranca0009** [comment]
Added more balloons within Orgrimmar and used the image above for reference.

![balloons](https://user-images.githubusercontent.com/26092980/85956899-ee9fd680-b956-11ea-93b6-a53e90e994b5.jpg)

Needs testing in PTR 👍

**Comment by Echinaceax** [comment]
confirmed fixed
much better @mfranca0009 thanks
