### ISSUE TITLE
[Spell] Arcane Charge

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Blackwing-Lair#1122]
**Links:**
[[Arcane Charge]](https://www.wowhead.com/spell=36032/arcane-charge) ID:36032

**What is happening:**
The aura is being consumed upon using [Arcane explosion] ID: 1449

**What should happen:**
The aura should be consumed upon any arcane damaging spell except [Arcane blast] ID:30451 and [Arcane explosion] ID:1449.
Note: The aura lasts 6 second.

**Extra info:**
What you need to fix is to set [Arcane Charge] not to be consumed upon using [Arcane explosion] ID:1449

**Comment by Keader** [comment]
Fixed.
