### ISSUE TITLE
[Spell] Ritual of Refreshment

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Blackwing-Lair#1125]
**Links:**
[[Ritual of Refreshment]](https://www.wowhead.com/spell=43987/conjure-refreshment-table)

**What is happening:**
The spell is not working.

**What should happen:**
Begins a ritual that creates a refreshment table. Raid members can click the table to acquire Conjured mana food. The tables lasts for 3min or 50 charges. Requires the caster and 2 additional party members to complete the ritual. In order to participate, all players must right-click the refreshment portal and not move until the ritual is complete.

**Comment by Keader** [comment]
Fixed
