### ISSUE TITLE
[Spell] Focus magic

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Blackwing-Lair#1126]
**Links:**
Focus magic ID:54646

**What is happening:**
When it procs , the player who has the aura , is effected by the +3% crit chance, not the focus magic caster (Mage).

**What should happen:**
When the target critically hits your chance to critically hit with spells is increased by 3% for 10sec.

**Comment by Keader** [comment]
Fixed.

**Comment by sarahkay88** [comment]
#3753 same kind of report just worded differently.

**Comment by Keader** [comment]
wtf? is not even same problem.
