### ISSUE TITLE
[quest=25741] [Preparations for the Future] - Stonetalon Mountains

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1138]
**Links:**
https://www.wowhead.com/quest=25741/preparations-for-the-future
https://www.wowhead.com/npc=41185/queen-silith
https://www.wowhead.com/item=55280/deepmoss-venom-sac
from WoWHead or our Armory

**What is happening:**
Im suppose to collect [item=55280] Deepmoss Venom Sac (10) and its alot of spiders 
that when i point at them they should have the item but there is only 1 in the whole area that drop it and thats [npc=41185] Queen Silith
However there is three different spider in the area and 1 is not targetable.
[npc=4007] Deepmoss Venomspitter. "green spider" = targetable
[npc=4005] Deepmoss Creeper. "Grey spider" = targetable
[npc=4006] Deepmoss Webspinner. " Brown Spider" = NOT targetable

**What should happen:**
All spiders in the area should drop the item.

**Comment by Kitzunu** [comment]
Fixed, will send when I am home

**Comment by Echinaceax** [comment]
[npc=4006] Deepmoss Webspinner. " Brown Spider" = NOT lootable now 

10/10 only from [npc=4007] Deepmoss Venomspitter
![10](https://user-images.githubusercontent.com/39439201/57488411-47279680-72b3-11e9-8409-912ad17bc02a.jpg)
