### ISSUE TITLE
[Quest] A Job for the Multi-Bot 

### ISSUE THREAD

**Issue by Grisweld** [WoWManiaUK/Blackwing-Lair#114]
The Quest {A Job for the Multi-Bot} In the gnome starting area is bugged. The geysers are actually non functioning Imps standing in the slime pools. So it does not allow the Bot to auto clean them as it should. While this does not stop you from leveling further and moving onto the next quest area it does hinder the process since you have to kill mobs to level enough to move on rather then chain quest to the next zone, I believe it stops you from acquiring three more quest for the Gnome starter zone before moving onto Kharanos.

**Comment by Saintres** [comment]
Confirmed. Quest not working

**Comment by Dranah** [comment]
This report is obsolete (was from previous core)
New one open at https://github.com/WoWManiaUK/Blackwing-Lair/issues/706
