### ISSUE TITLE
[NPC]  Seer Liwatha <Priest Trainer> / Tyelis <Priest Trainer> - Orgrimmar

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1144]
_I am a blood elf priest_

**Links:**
npc Seer Liwatha  - https://www.wowhead.com/npc=44735/seer-liwatha (tauren priest) 
npc  tyelis - https://www.wowhead.com/npc=45337/tyelis
quest - https://www.wowhead.com/quest=28476/twilight-scheming

![quest priest](https://user-images.githubusercontent.com/39439201/55196067-9657b300-51ae-11e9-8a8a-825dbb57ec0a.jpg)

**Tauren**

![tauren](https://user-images.githubusercontent.com/39439201/55196437-a58b3080-51af-11e9-9143-c0f01580ac26.jpg)

**Blood elf**

![belf](https://user-images.githubusercontent.com/39439201/55196454-b76cd380-51af-11e9-9f7b-ed5f3899c941.jpg)

**What is happening:**
- Tauren trainer gave me the tauren quest 
- Shouldn't give none taurens the quest 
- Shouldn't have 2 quests same from different trainers in Orgrimmar

**What should happen:**
-  Seer Liwatha Only for Tauren

**Comment by Kitzunu** [comment]
Fixed
