### ISSUE TITLE
[quest=14052] [Take it up with Tony] - Northern Barrens

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1149]
**Links:**
https://www.wowhead.com/quest=14052/take-it-up-with-tony
from WoWHead or our Armory

**What is happening:**
[npc=34749] is hostile
 [Take it up with Tony] is obviously a hord quest that even ally can take but not complete

**What should happen:**
Ally should not be able to take this quest ?

**Comment by mfranca0009** [comment]
Should be all fixed in PTR, needs testing 👍 

This quest should be marked for Horde only now and Alliance players should not be able to pick it up.

**Comment by HrafnValknutt** [comment]
Fix in Dev confirmed.

**Comment by mfranca0009** [comment]
Fix on live server, all set 👍
