### ISSUE TITLE
[quest=14046] [The Baron's Demands] - Northern Barrens

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1150]
**Links:**
https://www.wowhead.com/quest=14046/the-barons-demands
from WoWHead or our Armory

**What is happening:**
Looks like this is allso a hord quest that ally can take
Im suppose to talk to this guy and he dont give  me the choise to choose to free him.
Not completable

**What should happen:**

**Comment by Saintres** [comment]
Even as a hord i cant do this quest since i dont get the opption to free him.
That opption dont show up in the chatwindow.
Comment from Wowhead
if you choose "never, you two-timing dog!" it doesn't change the quest. He only says some unimportant things and you can still choose to free him
.Quest not completable

**Comment by Rushor** [comment]
![](https://i.imgur.com/5IrYUck.jpg)
![](https://i.imgur.com/vaDDGMv.jpg)
![](https://i.imgur.com/1rlkx5r.jpg)
