### ISSUE TITLE
[Quest] The Eyes of Ashenvale -14117- Azshara

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1151]
**Links:**
https://www.wowhead.com/quest=14117/the-eyes-of-ashenvale
https://www.wowhead.com/npc=35095/talrendis-scout

**What is happening:**
- No Talrendis Scout as far as a can see 
- Cant complete 

**What should happen:**
- should be quite a few 

_Side note: can have a drop chance of_ https://www.wowhead.com/item=47039/scouts-orders

**Comment by Rushor** [comment]
well there are far too less spawns of them

**Comment by Rushor** [comment]
added a few spawns of them mostly near the wood files
