### ISSUE TITLE
[quest=14034] [Club Foote] - Northern Barrens

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1157]
**Links:**
https://www.wowhead.com/quest=14034/club-foote
from WoWHead or our Armory

**What is happening:**
Im suppose to start a barfight with this guy but i dont get the option.
According to wowhead atleast.
The option should probably be in the text/chatwindow with this guy
Or somehow "club him" dunno how to do that, have not item to use for it 

**What should happen:**
He should somhow give me the schematics for a ship [item=46827]

**Comment by rzenne** [comment]
still not working

**Comment by mfranca0009** [comment]
Started working on this, but having difficulty with Chief Engineer Foote still displaying a gossip interaction for player when he's essentially dead from being clubbed.

Will look into it again tomorrow most likely.

**Comment by mfranca0009** [comment]
Quest is scripted and now completable, needs testing in PTR 👍

**Comment by Constant20** [comment]
Confirmed fixed in PTR

**Comment by mfranca0009** [comment]
Fix on live server, all set 👍
