### ISSUE TITLE
[Portol] Shattrath portol to Ogrimar - missing - Shattrath City

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1165]
**Links:**
(unable to find a direct link for this portal, can only find mage portal links)

**What is happening:**
The portal to Ogrimmar from Shattrath city is missing, only has one to Stormwind

**What should happen:**

Should have a portal to each of the fractions main city

**Comment by Rushor** [comment]
added

![I](https://i.imgur.com/iFROxRK.jpg)
