### ISSUE TITLE
[NPC] Auctioneer Itoran - Missing - Shattrath City

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1167]
**Links:**
https://www.wowhead.com/npc=50143/auctioneer-itoran

**What is happening:**
Missing from his location in Shattrath city , bank the of Aldor - alliance auctioneer.

**What should happen:**
Should be located in Shattrath city in the bank of Aldor.

**Comment by Echinaceax** [comment]
@Kitzunu - Npc there now but not clickable for an Auctioneer

**Comment by Kitzunu** [comment]
Check now
