### ISSUE TITLE
[NPC] Auctioneer Kalaren - missing -Shattrath City

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1169]
**Links:**
https://www.wowhead.com/npc=50139/auctioneer-kalaren

**What is happening:**
Missing from the Scryer Bank in Shattrath City.

**What should happen:**
Should be located in Shattrath City in the scryer bank.

**Comment by Echinaceax** [comment]
@Kitzunu npc here now, just not clickable for an Auctioneer

**Comment by Kitzunu** [comment]
check now
