### ISSUE TITLE
[NPC] Orphan Matron Mercy - misssing -Shattrath City

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1176]
**Links:**
https://www.wowhead.com/npc=22819/orphan-matron-mercy#comments

**What is happening:**

Is not located in the orphan area of the lower city ( she is vital for orphan week)

**What should happen:**
Should be located in the lower city - co-ord on web link.

**Comment by Echinaceax** [comment]
@Kitzunu - not showing 
![not show](https://user-images.githubusercontent.com/39439201/55647201-5eb7bf00-57dd-11e9-9190-e56c4068406f.jpg)

**Comment by Rushor** [comment]
creature is part of event 10. only spawns if event 10 is active.

for gms (.event start 10)
