### ISSUE TITLE
[Quest] To the Summit -25478- Dustwallow Marsh

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1177]
**Links:**

https://www.wowhead.com/quest=25478/to-the-summit

![no dio window](https://user-images.githubusercontent.com/39439201/55257754-25bd9e80-5261-11e9-8b6b-745ef442fd3b.jpg)

_Blocking questline_ 

![list](https://user-images.githubusercontent.com/39439201/55257884-8d73e980-5261-11e9-85ba-316270d339f2.jpg)

**What is happening:**
- Dyslix Silvergrub does borrow me a wind rider 
- Cant complete (no dialog window)

**What should happen:**
_Borrow a wind rider from Dyslix Silvergrub and speak with Kanati Greycloud at Westreach Summit in Thousand Needles._
![list](https://user-images.githubusercontent.com/39439201/55257872-8220be00-5261-11e9-9819-76afc6e80dd6.jpg)

**Comment by Venom64bit** [comment]
Tried today and it's still not working yet.
It is important to unlock this QuestLine bacause the reward is the extremely useful River Boat for traveling in Thousand Needles.

**Comment by Rushor** [comment]
will add teleport for it

![I](https://i.imgur.com/06ZoHVr.jpg)
![I](https://i.imgur.com/qGNmxqk.jpg)

**Comment by Rushor** [comment]
also added that the questneder will not be killed directly

![I](https://i.imgur.com/hmBFkPb.jpg)

**Comment by Echinaceax** [comment]
bugged not working again @Rushor 

![bugged again for thousand needles](https://user-images.githubusercontent.com/39439201/78402161-6bdada00-75fa-11ea-9c72-b5d38fc9bde1.jpg)
