### ISSUE TITLE
[NPC] Lorokeem - Shattrath City

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1178]
**Links:**
https://www.wowhead.com/npc=19052/lorokeem

**What is happening:**
doesn't offer Alchemy Training

**What should happen:**
Should offer training has intended.

**Comment by Rushor** [comment]
is intended, it only shows the options with special conditions:

INSERT INTO `conditions` (`comment`) VALUES (NULL);
INSERT INTO `conditions` (`comment`) VALUES ('Gossip option requires level 68 or higher');
INSERT INTO `conditions` (`comment`) VALUES ('Gossip option requires an Alchemy skill of 350 or higher');
INSERT INTO `conditions` (`comment`) VALUES ('Gossip option requires player to have the spell \'Elixir Master\' learned');
INSERT INTO `conditions` (`comment`) VALUES ('Gossip option requires level 68 or higher');
INSERT INTO `conditions` (`comment`) VALUES ('Gossip option requires an Alchemy skill of 350 or higher');
INSERT INTO `conditions` (`comment`) VALUES ('Gossip option requires player to have the spell \'Transmutation Master\' NOT learned');
INSERT INTO `conditions` (`comment`) VALUES ('Gossip option requires player to have the spell \'Elixir Master\' NOT learned');
INSERT INTO `conditions` (`comment`) VALUES ('Gossip option requires player to have the spell \'Potion Master\' NOT learned');
INSERT INTO `conditions` (`comment`) VALUES ('Gossip option requires player to have the quest \'Master of Transmutation\' rewarded OR');
INSERT INTO `conditions` (`comment`) VALUES ('Gossip option requires level 68 or higher');
INSERT INTO `conditions` (`comment`) VALUES ('Gossip option requires an Alchemy skill of 350 or higher');
INSERT INTO `conditions` (`comment`) VALUES ('Gossip option requires player to have the spell \'Transmutation Master\' NOT learned');
INSERT INTO `conditions` (`comment`) VALUES ('Gossip option requires player to have the spell \'Elixir Master\' NOT learned');
INSERT INTO `conditions` (`comment`) VALUES ('Gossip option requires player to have the spell \'Potion Master\' NOT learned');
INSERT INTO `conditions` (`comment`) VALUES ('Gossip option requires player to have the quest \'Master of Elixirs\' rewarded OR');
INSERT INTO `conditions` (`comment`) VALUES ('Gossip option requires level 68 or higher');
INSERT INTO `conditions` (`comment`) VALUES ('Gossip option requires an Alchemy skill of 350 or higher');
INSERT INTO `conditions` (`comment`) VALUES ('Gossip option requires player to have the spell \'Transmutation Master\' NOT learned');
INSERT INTO `conditions` (`comment`) VALUES ('Gossip option requires player to have the spell \'Elixir Master\' NOT learned');
INSERT INTO `conditions` (`comment`) VALUES ('Gossip option requires player to have the spell \'Potion Master\' NOT learned');
INSERT INTO `conditions` (`comment`) VALUES ('Gossip option requires player to have the quest \'Master of Potions\' rewarded');
