### ISSUE TITLE
[Quest] Gasping for Breath - id 14395 - Gilneas

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Blackwing-Lair#118]
The  quest Gasping for Breath is not  working there is no interaction with the watchman  possible. They  are  marked  for the  quest but  no response at all. You cant  bring them a  shore
https://www.wowhead.com/quest=14395/gasping-for-breath
 i added the  youtube link how it  should  work
https://www.youtube.com/watch?v=CMkX1hMSF7s

![image](https://user-images.githubusercontent.com/33811022/48959508-261df400-ef66-11e8-93d6-15c38f4c8b04.png)

**Comment by Pitmaster** [comment]
This one is still bugged. I don't see a watchman at all. 

Pitfourth

**Comment by TheBolshe** [comment]
I managed to complete it but there were too few of drowned watchguards in the zone and if you click one when you are carrying another you have to wait 3 minutes before you can do anything

**Comment by Kitzunu** [comment]
Added 51 spawns

**Comment by Rushor** [comment]
the script for them is not working correctly somehow

**Comment by giles1508** [comment]
I did this quest today on a fresh toon on test,  and it works perfect,

**Comment by Dranah** [comment]
I've just tested this quest on the PTR and I have only found 1 single watchman.
I also saw a bunch of "sparkle spots" which may be where the NPCs are supposed to be, but they aren't there. 
Not sure if something was reverted but it needs to be looked at.

**Comment by Rushor** [comment]
okay just as note we have npc 36440. in db it has phaseid 183

**Comment by Dranah** [comment]
ok, 182 is another type of watchmen.
I cannot locate any single 36440 in the area
Not even in GM mode.
There is only a visual sparkle where it teleports me if i .go creature id 36440

**Comment by Rushor** [comment]
okay pls recheck that. fix is enabled again
