### ISSUE TITLE
[Spell] Burning Embers Warlock Talent Not Working Destruction

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1180]
**Links:**
https://wowwiki.fandom.com/wiki/Burning_Embers_(warlock_talent)
couldnt find the wowhead link so had to use the wowwiki one
**What is happening:**
- there is no Damage-over-time effect popping on the mob from soul fire or the imp fire bolt

**What should happen:**
There should be a Damage-over-time effect placed on the mob when the warlock uses soul fire or the imp uses its fire bolt

**Comment by Kitzunu** [comment]
Please use the template that is made when you create an issue, to make it easier for the devs to find the problem.

Good first report though :)

**Comment by Keader** [comment]
This was a hard one lol
Fixed.
