### ISSUE TITLE
[NPC] Erich Lohan - Visual -Stormwind

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1181]
**Links:**

https://www.wowhead.com/npc=3627/erich-lohan

**What is happening:**
This Npc is currently walking around Stormwind trying to sell the best drink, however he sometimes goes falls through textures and walks through building and all you can see is his speech bubble.

**What should happen:**

she shouldn't fall through the floor, he shouldn't walk through building and you should be able to see him

**how to see it**!
wait for him outside the blue recluse - this is were it happend

**Comment by Kitzunu** [comment]
This is probably bad pathing
