### ISSUE TITLE
[Spell] Decimation - Warlock

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1182]
**Links:**
https://wowwiki.fandom.com/wiki/Decimation

**What is happening:**
every time Shadow Bolt , Incinerate or Soul Fire is cast on a target with 100% health it procs the reduced cast time of Soul Fire by 40%

**What should happen:**
Every time Shadow Bolt , Incinerate or Soul Fire is cast on a target at or below 25% health it procs the reduced cast time of Soul Fire by 40%

**Comment by Keader** [comment]
Fixed.
