### ISSUE TITLE
[Quest] Feast at theblue recluse - missing - Stormwind

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1184]
**Links:**
Quest -https://www.wowhead.com/quest=1271/feast-at-the-blue-recluse
NPC - https://www.wowhead.com/npc=1141
**What is happening:**
Quest is not offered. should be available from level 35
**What should happen:**
Should be available by the NPC at level 35

**Comment by Rushor** [comment]
fixed. available once you did all quests from https://classic.wowhead.com/npc=4794/morgan-stern and https://classic.wowhead.com/quest=1222/stinkys-escape
