### ISSUE TITLE
[Item/Spell] Dragonwrath, Tarecgosa's Rest Staff 

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1185]
**Links:**
https://www.wowhead.com/item=71086/dragonwrath-tarecgosas-rest

**What is happening:**
when you deal damage you have a chance to gain the buff Wrath of Tarecgosa, duplicating the harmful spell it doesnt proc at all 

**What should happen:**
when you deal damage you have a chance to gain the buff Wrath of Tarecgosa, duplicating the harmful spell it should duplicate the spell that is used

**Comment by Keader** [comment]
Fixed.
May this spell will have a little change.
We cant find for now, what should be the chance to players with pets.
Without pet is about 8~10% of proc chance, without any icd.
With pet, we guess 15%... for now.
