### ISSUE TITLE
[NPC] Spackle Thornberry - inactive -Stormwind

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1186]
**Links:**

NPC - https://www.wowhead.com/npc=5520/spackle-thornberry

**What is happening:**

This NPC demon trainer is inactive - was also checked by a warlock.

**What should happen:**

Should provide a speech text .

**Comment by Kitzunu** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/1812
