### ISSUE TITLE
[NPC] Stormwind Rat - Critter -Stormwind

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1188]
**Links:**

https://www.wowhead.com/npc=62954/stormwind-rat

**What is happening:**
well killed outside the dungeon stockade - https://www.wowhead.com/the-stockade are dropping loot nightstone - https://www.wowhead.com/item=52180/nightstone

**What should happen:**
Shouldn't drop this loot.

**Comment by sarahkay88** [comment]
also drops item https://www.wowhead.com/item=8827/elixir-of-water-walking

**Comment by Kitzunu** [comment]
LOL
Super rats

**Comment by Kitzunu** [comment]
Correct Entry is `49540`
