### ISSUE TITLE
[NPC] Celestine of the Harvest - Stormwind

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1190]
**Links:**
https://www.wowhead.com/npc=44395/celestine-of-the-harvest#starts

**What is happening:**
try to talk to the Druid trainer Celestine to train for skills and nothing happens your toon just does the motion and thats it

**What should happen:**
window should pop up so you can train skills

**Comment by Kitzunu** [comment]
Duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/721
