### ISSUE TITLE
[Quest] Looming threat -27062- Razorfen Downs

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1195]
**Links:**
quest - https://www.wowhead.com/quest=https://www.wowhead.com/quest=27062/looming-threat
npc - https://www.wowhead.com/npc=44837/koristrasza

![missing npc razer](https://user-images.githubusercontent.com/39439201/55270749-29721500-52a3-11e9-8e0d-ae701ea90e49.jpg)

**What is happening:**
- NPC missing 
- Shows on map but isnt there 
- Cant complete 

**What should happen:**
- Npc should be in there waiting

**Comment by Kitzunu** [comment]
Fixed in the DEV Realm.
Dont forget to delete cache before testing.
