### ISSUE TITLE
[Quest] Diabolical Plans - Ashenvale - 26447

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#1196]
**Links:**
https://www.wowhead.com/quest=26447/diabolical-plans
https://www.wowhead.com/item=23798/diabolical-plans
from WoWHead or our Armory

**What is happening:**
Item has to drop, it doesn't. It is the start of the quest, don't know wheter the quest, if the item drops work.

**What should happen:**
Item should drop, low droprate.

Pitsecond: ORC warlock

**Comment by Kitzunu** [comment]
Which NPC should drop this?

**Comment by TheManiax** [comment]
@Kitzunu  It's a zone drop.
[WoWhead](https://www.wowhead.com/item=23798/diabolical-plans#comments:id=775057)
> Drops in Demon Fall Canyon in Ashenvale off of random demons.

**Comment by Kitzunu** [comment]
Fixed, will send when I am home.

Keep in mind this is only for hordes AND the item has < 3 drop chance

**Comment by Echinaceax** [comment]
@Kitzunu - still no drop

**Comment by Kitzunu** [comment]
Drop chance is less than 3%

I am pretty sure this works

**Comment by Echinaceax** [comment]
@Kitzunu - then i'll trust ya :)
