### ISSUE TITLE
[Quest] Security! - Ashenvale - 13871

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#1197]
**Links:**
https://www.wowhead.com/quest=13871/security
https://www.wowhead.com/npc=34206/kaldorei-assassin
https://www.wowhead.com/item=46147/kaldorei-assassins-head
from WoWHead or our Armory

**What is happening:**
Nothing

**What should happen:**
Kaldorei Assassin  should attack you outside the building, she doesn't show up. After killing here you should loot here head.

Pitsecond: ORC warlock

**Comment by Rushor** [comment]
![I](https://i.imgur.com/VbBboKz.jpg)

can now be found stealthed outside of the building
