### ISSUE TITLE
[Quest] To Greymane Manor

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Blackwing-Lair#120]
https://www.wowhead.com/quest=14465/to-greymane-manor

You have to go true the gate up to the manor. you cant get to the manor there are more  gates on 1 place  and it wont  let you pass it
![image](https://user-images.githubusercontent.com/33811022/48970558-b105f980-f00d-11e8-95e3-d9532ca74dd0.png)

**Comment by wow-mania** [comment]
That is correct. You only see the gate for your phase.
Make sure you are on the correct phase and not using a GM.

**Comment by TheBolshe** [comment]
I have the same issue. I can't open the gates and i see two of them. 
![image](https://user-images.githubusercontent.com/26492864/57081134-7018bc00-6cf4-11e9-824e-a78016be2304.png)

**Comment by UnknownCombine** [comment]
I have the same issue. I can't open the gates and i see two of them.
![WoWScrnShot_052219_144632](https://user-images.githubusercontent.com/50812024/58195852-4e7d7580-7c9f-11e9-98ae-c678b2c584ed.jpg)
