### ISSUE TITLE
[NPC] Behsten - missing -Stormwind

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1201]
**Links:**

https://www.wowhead.com/npc=35365/behsten

**What is happening:**
missing from his location in the Stormwind keep.

**What should happen:**

should hiding in the right corner as you walk into the Battlemaster's room in Stormwind. He's stealthed and has all the gear typical of a 19 Rogue twink, from Feet of the Lynx to the Engineering Goggles. (taken from wowhead comments)

**Comment by Kitzunu** [comment]
He is there
![image](https://user-images.githubusercontent.com/24550914/55278537-dda88580-530d-11e9-8f26-cb162df236ce.png)

**Comment by sarahkay88** [comment]
yup im blind ha
