### ISSUE TITLE
[NPC] Caregiver Chellan - Azuremyst Isle

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Blackwing-Lair#1203]
Entry ` 1653`

Has two vendor gossips
![image](https://user-images.githubusercontent.com/24550914/55277886-5525e700-5305-11e9-93ab-ee12cb21e2e2.png)

**Comment by Echinaceax** [comment]
where is the link ?

please use the template as it is easier for devs

**Comment by Kitzunu** [comment]
No link cuz i gave the ID 😂

**Comment by Rushor** [comment]
16553
