### ISSUE TITLE
 [quest=29087] [Sludge Investigation] - Northern Barrens

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1204]
**Links:**
https://www.wowhead.com/quest=29087/sludge-investigation
from WoWHead or our Armory

**What is happening:**
I cant click on the tracks and investigate them.
No chance to complete the quest
 [quest=29087]

**What should happen:**

The track should be "clickable" to be investigated

**Comment by mfranca0009** [comment]
Quest is completable now, it will need further revision for proper text warnings showing up later on.
