### ISSUE TITLE
[quest=14006] [Read the Manual] - Northern Barrens

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1205]
**Links:**
[quest=14006]
[item=11148]
https://www.wowhead.com/item=11148/samophlange-manual-page
from WoWHead or our Armory

**What is happening:**
The droprate on this item is way to low according to wowhead that say 33%
so far i killed about 30 and got 1 drop

**What should happen:**

The item should drop more frequent

**Comment by Kitzunu** [comment]
Fixed, will send when I get home

After doing some research I found that 70%+ drop rate seems most accurate here.
