### ISSUE TITLE
[NPC] Oraphan Matron Nightingale - Missing -Stormwind

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1208]
**Links:**

https://www.wowhead.com/npc=14450/orphan-matron-nightingale#comments

**What is happening:**

Missing from her location in Stormwind.

**What should happen:**

Should be located outside the orphanage, co-ords on web link.

**Comment by Kitzunu** [comment]
DB GUID `313767` 
Entry `14450`

Is spawned, but cannot be seen with or withon GM ON

**Comment by Echinaceax** [comment]
> Is spawned, but cannot be seen with or withon GM ON

Tester are done WITHOUT GM on, not all testers (this isnt the place for this convo)

**Comment by Kitzunu** [comment]
@Echinaceax It is info for Rushor, he will need it :)

**Comment by Rushor** [comment]
the creature is only available and you are only able to see it while event 10 (Children's Week) is acive https://wowgaming.altervista.org/aowow/?event=10

(for gms - you can test it with .event start 10)

**Comment by sarahkay88** [comment]
https://wow.gamepedia.com/Orphan_Matron_Nightingale

**Comment by Echinaceax** [comment]
@Rushor correct she is visible when the event is started 

- she is meant to sell https://www.wowhead.com/npc=14450/orphan-matron-nightingale#sells
- [ ] freshly-squeezed-lemonade  - https://www.wowhead.com/item=23161/freshly-squeezed-lemonade
- [ ] https://www.wowhead.com/item=23160/friendship-bread

- [ ] doesnt offer quest - https://www.wowhead.com/quest=1468/childrens-week

**Comment by sarahkay88** [comment]
@Rushor  all events are turned on in the new cata and she is still no there.
