### ISSUE TITLE
[Quest] Exodus -24438- autocomplete- Gilneas City

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Blackwing-Lair#121]
https://www.wowhead.com/quest=24438/exodus

With this  quest  you  are  send  down to the  stables, when you  get there an carriage is standing there  with horses. You  enter it  and there  follow  an cinematic of the ride  and  an  attack. then the quest  complete. there is  no  vehicle as you can see in ss.
I linked the  youtube video  how this  quest  work

![image](https://user-images.githubusercontent.com/33811022/48970627-dd6e4580-f00e-11e8-93e3-caf8056014ec.png)

https://www.youtube.com/watch?v=x9oL3GK1778

**Comment by wow-mania** [comment]
This will be quite hard to fix. The quest is auto-completed so all you have to do is go deliver it.

**Comment by TheBolshe** [comment]
I just can't interact with the carriages at all.
![image](https://user-images.githubusercontent.com/26492864/57083189-6e50f780-6cf8-11e9-9193-b3f3f21a6a2d.png)

**Comment by Rushor** [comment]
that's just the static object, the npc need to be spawned

**Comment by Frostmanx** [comment]
Its autocompleted now as long as you walk all the way to the npc and turn in the quest 

![WoWScrnShot_052819_203457](https://user-images.githubusercontent.com/50195620/58489196-65810380-8188-11e9-815c-2157f51c2279.jpg)

**Comment by Rushor** [comment]
oh okay we got that report now https://github.com/WoWManiaUK/Blackwing-Lair/issues/2502

I'm closing this once, since the other report is more detailed. Working on a fix now. Will take some time.
