### ISSUE TITLE
[NPC] Soolie Berryfizz - Missing - Ironforge

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1212]
https://www.wowhead.com/npc=5178/soolie-berryfizz

**What is happening:**

This is the alchemy supplies NPC, she is missing from her location.

**What should happen:**

Should be located in the Berryfizz's potions and mixed drinks in Tinker Town, co-ord on web link

**Comment by Echinaceax** [comment]
@Rushor 
![mapid 0](https://user-images.githubusercontent.com/39439201/55490249-bfa39380-5633-11e9-9fe6-c10b4249e9ff.jpg)

**Comment by Rushor** [comment]
hm can you recheck that :o for me it works: 
.go c id 5178

**Comment by Echinaceax** [comment]
@Rushor 
Working now ...just missing one more recipe 
https://www.wowhead.com/item=5642/recipe-free-action-potion
