### ISSUE TITLE
[Quest] Saving Princess Stillpine

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#122]
![screenshot_1](https://user-images.githubusercontent.com/20323863/48982952-37433e00-f0e9-11e8-9fa4-8f117a8bd43b.png)

As I passed to do other quest this npc was already standing here non attackable. Then I did pick quest and killed aprox 20 npc, no second spawn of high chef, and this guy still cant be attacked.

edit:
this is second ss with coordinates under minimap and with message that I am not able to attack this target, and also I dont see health fram above ``hostile`` npc
![screenshot_2](https://user-images.githubusercontent.com/20323863/48983049-673f1100-f0ea-11e8-91db-90ab8c43b70c.png)

**Comment by TheSale** [comment]
a gm come to help me, and he spawned High Chef on different location, and again it was non attackable, he killed it with command, but not by attacking it. I will try it later I think I did not completed it.

**Comment by wow-mania** [comment]
GMs are not allowed to spawn NPCs this will not work and will double my work.

**Comment by TheSale** [comment]
damn, I did not know that. I want to look few more things around stormwind before I go back to bloodmyst island, I will test it normal way when I get there.

**Comment by TheSale** [comment]
it works now
