### ISSUE TITLE
[NPC] Alindia - missing - Darnassus

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1220]
**Links:**
https://www.wowhead.com/npc=3562/alaindia

**What is happening:**

Cannot located him walking about Darnassus, spent age looking for him

**What should happen:**

Should be walking around Darnassus.

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/55490374-f8dc0380-5633-11e9-80b6-02a7477a6cc8.png)
