### ISSUE TITLE
[NPC] Kor'kron Reaver - Dalaran

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1223]
**Links:**
https://www.wowhead.com/npc=30755/korkron-reaver

**What is happening:**

The mobs are red and can be targeted and killed

**What should happen:**
Dalaran is a neutral zone, they shouldn't be red and I shouldn't be able to kill them

**Comment by Kitzunu** [comment]
Will be fixed when Janitor applies Fixes, probably tomorrow :)
Remember to delete the cache before testing
