### ISSUE TITLE
[Object] Teleport to violent stand crystal -Dalaran

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1224]
**Links:**
https://www.wowhead.com/object=191229/teleport-to-violet-stand-crystal

**What is happening:**

Doesn't work when used

**What should happen:**
Should teleport the player to violet stand.

**Comment by Rushor** [comment]
you need the quest=12790 to use it

**Comment by sarahkay88** [comment]
i could have sworn I already had the quest, but must have been a different alt. Either way u were right. I just took the quest n tested n it works. Cheer n sorry.
