### ISSUE TITLE
[NPC] Minigob Manabonk <The Mischievous Mage>-32838- Dalaran

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1225]
**Links:**

https://www.wowhead.com/npc=32838/minigob-manabonk

**What is happening:**
- Annoyance 
- As there is no population atm in PTR can he be set as "inactive" for now
it is interfering with NPC testers there atm 

- I did my kill ability (as adviced a few weeks ago) but re spawns in a few secs , so makes no difference to the bugging ability that is currently causing testers 

**What should happen:**
- Should be Mischievous but not on a PTR :)

**Comment by Kitzunu** [comment]
I can't stop to wonder, how does it interfere with testing? O.o

**Comment by Echinaceax** [comment]
> I can't stop to wonder, how does it interfere with testing? O.o

Ok ...i'll be literal ...its annoying !!!

**Comment by Kitzunu** [comment]
WTB better laugh emoji for Github
the current one sucks Q.Q

**Comment by sarahkay88** [comment]
It's completely annoying u can't spend two minutes in dala so yea it interferes but yea not an issue I'll just avoid testing in dalaran simples.

**Comment by Dranah** [comment]
This NPC is super annoying on live too. Not only he keeps sheeping you, that's just plain maddening, but he also spams your mailbox with his stupid 44817 (the mischief maker).
You ban other players for doing this, floods your mail and you take 10minutes to delete all, this need to be fixed...
He needs a cooldown as to how frequently he can sheep a specific player and a limit of max. 1 mail to be sent to same person.

**Comment by Echinaceax** [comment]
haha awesome thanks jani :)

**Comment by sarahkay88** [comment]
![World of Warcraft 20_05_2019 15_19_51](https://user-images.githubusercontent.com/42302580/58028584-f6b20380-7b12-11e9-8def-1ffd0b3922e6.png)
I spent a few mins in dala getting training n this still isn't fixed if anything hes got faster lol

**Comment by sarahkay88** [comment]
![World of Warcraft 20_05_2019 15_22_33](https://user-images.githubusercontent.com/42302580/58028657-219c5780-7b13-11e9-8947-6daa1bbb4154.png)
first page

**Comment by Echinaceax** [comment]
yip not funny 

![minigob](https://user-images.githubusercontent.com/39439201/58029884-cc197800-7b1d-11e9-9de8-0947237b2b17.jpg)

**Comment by Echinaceax** [comment]
@wow-mania This guy is still on speed, low population still,  so the person that is unluck and has to go   to Dalaran get Sheeped all the time, its still WHOpper annoying  💯

**Comment by Echinaceax** [comment]
Stopping players for fishing in peace now @wow-mania 
cant we just deactivate him or as Nellie suggested make him killable lol

**Comment by Kitzunu** [comment]
I'll check, I think I figured out a way to make the delay longer

**Comment by Kitzunu** [comment]
I made the occurrence 2hrs now, was 30 mins before. 
This should hopefully make it less painful ^^

**Comment by Echinaceax** [comment]
ABOUT TIME @Kitzunu LMAO

**Comment by Nellieb1y** [comment]
Please just delete the NPC.   Cannot even use the hairdresser in Dalaran, thanks to being constantly manabonked, and my progress lost.   This was to be my base of operations for leveling in northrend.  I can't think straight  when here... so much for "sanctuary"

**Comment by Rushor** [comment]
fix will be active with next serverupdate

**Comment by Nellieb1y** [comment]
thank you... manabonkind interrupts any action that I am trying to perform!    https://cdn.discordapp.com/attachments/533728620112510986/676030838147645446/WoWScrnShot_020920_124145.jpg

**Comment by Nellieb1y** [comment]
unchanged for <85 as of today.  Considering all the nonfunctional NPCs in he game, making it impossible to do Deepholm without one or two GM interventions per day, or hunting a rare or doing a dungeon boss for a drop which is in Wowhead in this patch level (but no drop), it should not be a big deal to delete the NPC
