### ISSUE TITLE
[NPC] Brassbolt Mechawrench - positioning -Dalaran

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1227]
**Links:**
https://www.wowhead.com/npc=35594/brassbolt-mechawrench

**What is happening:**

Stood on the bar/bench

**What should happen:**
Should be located in the lower right hand side of the building

**Comment by Kitzunu** [comment]
Fixed.
Also added one missing in The Silver Enclave
