### ISSUE TITLE
[Spell] Druid Flight Form Icons

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1229]
**Links:**
https://wowwiki.fandom.com/wiki/Flight_Form  https://wow.gamepedia.com/Swift_Flight_Form

**What is happening:**
there is two flight form icons the swift flight form and the normal flight form

**What should happen:**
the normal flight form should upgrade to swift flight form and only show one icon

**Comment by Keader** [comment]
Will show only the swift after character relog having both spells.
