### ISSUE TITLE
[Quest] Mac'Aree Mushroom Menagerie

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#123]
![fungus](https://user-images.githubusercontent.com/20323863/48983625-95741f00-f0f1-11e8-9b89-e1967abd3ab9.png)
![fungus loot](https://user-images.githubusercontent.com/20323863/48983628-9907a600-f0f1-11e8-9845-6e52d4dfd088.png)

The IT does not glow (spark) someone who dont know the quest will spend great deal of time to find this (as I did and found it by accident)

**Comment by wow-mania** [comment]
Just checked retail info. As-is. It is meant to be hard to find. Check comments on Wowhead.
