### ISSUE TITLE
[NPC] Archmage Aranhir Starsinger - missing -dalaran

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1230]
**Links:**
https://www.wowhead.com/npc=47581/archmage-aranhir-starsinger#comments

**What is happening:**
Missing from his location
**What should happen:**
Should be located in Simply Enchanting in dalaran

**Comment by Kitzunu** [comment]
Will be fixed when Janitor applies Fixes, probably tomorrow :)
Remember to delete the cache before testing
