### ISSUE TITLE
[NPC] Sunreaver Agent - Dalaran

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1233]
**Links:**
https://www.wowhead.com/npc=36776/sunreaver-agent

**What is happening:**

NPC is red and can be killed

**What should happen:**
Dalaran is neutral area, shouldn't be red and shouldn't be killable

**Comment by Kitzunu** [comment]
@sarahkay88 This NPC should be hostile for Alliance, did you test with Horde or Ally?

**Comment by sarahkay88** [comment]
Ah OK well I never usually go to underbelly n yea I think you may be right it might have been my ally toon. I don't think I did the horde ones. Sorry you can close this one.
