### ISSUE TITLE
[NPC] Orc Warlock traniners - display - Ogrimmar

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1235]
**Links:**
https://www.wowhead.com/npc=72145/groldar
https://classic.wowhead.com/npc=3325/mirket
https://www.wowhead.com/npc=72144/zevrost
**What is happening:**
display is not translating common tongue (orc language)

**What should happen:**
Needs to be translated into common tongue (English)

**Comment by Dranah** [comment]
Works fine. Might be a client issue on your side.
![WoWScrnShot_051119_060219](https://user-images.githubusercontent.com/31132743/57564786-60633c80-73b2-11e9-89db-493a995b2ef9.jpg)
