### ISSUE TITLE
[quest=28876]  [To the Mor'shan Rampart] - Northern Barrens

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1237]
**Links:**
https://www.wowhead.com/quest=28876/to-the-morshan-rampart
from WoWHead or our Armory

**What is happening:**
This quest you cant complete since Kadrak (questreciver) is missing.

**What should happen:**

Report to Kadrak at the Mor'shan Rampart on the border between the Northern Barrens and Ashenvale.

**Comment by Kitzunu** [comment]
Fixed in the DEV Realm.
Dont forget to delete cache before testing.
