### ISSUE TITLE
[Spell] Hunter Camouflage 

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1240]
**Links:**
https://wowwiki.fandom.com/wiki/Camouflage

**What is happening:**
when i click camouflage nothing happens at all

**What should happen:**
when camouflage is active the hunter goes in stealth when stationary and is undetectable

**Comment by Keader** [comment]
fixed.

**Comment by Dranah** [comment]
Spell works now.
However, the hunter is also invisible to members of his own faction (horde to horde for ex.)
Party members can see them, but non-partied cannot.
I dont think this is intended, stealth should only make you invisible towards enemies.

**Comment by Keader** [comment]
With group:

![image](https://user-images.githubusercontent.com/7120913/56921556-71e84280-6a9c-11e9-883f-61db751e233e.png)


Without group:

![image](https://user-images.githubusercontent.com/7120913/56921600-95ab8880-6a9c-11e9-8b56-e4f1d03d41e8.png)

You need be close to see.
Nothing wrong here.

**Comment by Nemuriciu** [comment]
Issue needs reopen.

**What is happening:**
Camouflage stealth should **not** be broken by movement or placing traps.

**What should happen:**
Camouflage stealth should **only** be broken by combat.

Example video:
https://youtu.be/wey_3fGhtB8?t=121
