### ISSUE TITLE
[NPC] Innkeeper Gryshka - Display - Ogrimmar

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1245]
**Links:**
https://www.wowhead.com/npc=6929/innkeeper-gryshka

**What is happening:**
Display
2x -browse
1x - make home

**What should happen:**
Should be
1x - browse
1x - make home

**Comment by Echinaceax** [comment]
The 2nd one (isnt needed right?) coz 31433 isnt there

![2nd 1](https://user-images.githubusercontent.com/39439201/55418516-20b76280-5573-11e9-83a0-75a36d38e467.jpg)

**Comment by Rushor** [comment]
well just .go c id 6929

**Comment by Echinaceax** [comment]
@Rushor - i did already..just letting you know (SS) :)
