### ISSUE TITLE
[NPC] Eunice Burch <Cooking Trainer>-4552- Undercity

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1247]
_Issue1_

**Links:**
https://www.wowhead.com/npc=4552/eunice-burch#teaches-recipe

**What is happening:**
- [x] See doesnt have cooking training 

**What should happen:**
- She should be a cooking trainer 

_Issue2_

- [ ] She offers daily quest without having the profession

**Comment by Echinaceax** [comment]
@Rushor 

1. issue 1 (fixed)
2. issue 2 ...

**Comment by Rushor** [comment]
done
