### ISSUE TITLE
[Daily/Cooking] list from Thunderbluff

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1248]
_Issue1_

**Links:**
https://cata-twinhead.twinstar.cz/?npc=3026

![aska mistrunner](https://user-images.githubusercontent.com/39439201/55284492-2a28ab00-5378-11e9-99de-2d4bbad20a2c.jpg)

**What is happening:**
- Wrong currency for lvl10

**What should happen:**
- [x] Corn Mash (1 silver 25 copper)
- [x] "Magic" Mushrooms (1 silver 25 copper)
- [x] Mulgore Spice Bread  (1 silver 25 copper)
- [x] Perfectly Picked Portions (1 silver 25 copper)
- [x] Pining for Nuts (1 silver 25 copper)

_Issue2_

- [x] She offers me a daily when i dont have the profession

**Comment by Echinaceax** [comment]
@Rushor 
All fixed with wrong currency (fixed)

Just waiting for issue 2 :)

**Comment by Rushor** [comment]
yep will do

**Comment by Rushor** [comment]
@Echinaceax second issue fixed too now. could you check that issue for all other cooking quests too and create issues if needed? thank you

**Comment by Rushor** [comment]
ah nvm will do that

**Comment by Echinaceax** [comment]
@Kitzunu @Rushor New info - Dailies scale to lvl
will retest as i lvl up
