### ISSUE TITLE
[NPC] Prospector Nachlan

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#125]
Can`t interact with npc
Blood watch 56,54
Prospector Nachlan [Explorers league] mining trainer
https://www.wowhead.com/npc=18804/prospector-nachlan

**Comment by sarahkay88** [comment]
this has reverted still none interactable .

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/I8Z0uPr.jpg)
