### ISSUE TITLE
[Spell] Aveneger's Shield - Id 31935 - Prot Paladin

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#1253]
**Links:**
https://www.wowhead.com/spell=31935/avengers-shield
https://wowwiki.fandom.com/wiki/Glyph_of_Focused_Shield
from WoWHead or our Armory

**What is happening:**
When using the ability on target dummies The Shield should bounce to up to 2 additional targets but is only striking the selected target (similar to the effect of Glyph of Focused Shield was in effect) but if there are multi mobs nearly stacked it bounces...possibly a range issue with bounces
May not seem a huge issue but as a paladin tank you shield throw is your main source of pulling multiple mobs at a distance.

This Range is to far to bounce shield (Wotlk typical spacing between mobs)
![World of Warcraft 31_03_2019 16_45_37](https://user-images.githubusercontent.com/45798884/55291283-d8fad480-53d4-11e9-8116-eb686cda5c0f.png)

This is how close the need to be for a bounce.
![World of Warcraft 31_03_2019 16_48_08](https://user-images.githubusercontent.com/45798884/55291293-edd76800-53d4-11e9-8960-90ada686fd84.png)

**What should happen:**
The Shield should bounce to up to 2 additional targets after striking the targeted Mob/npc within a set range

**Comment by Keader** [comment]
Fixed.
Was missing like 2.5 yards of distance haha

**Comment by Marvin5678** [comment]
i still hve that issue

**Comment by Echinaceax** [comment]
Hi @Marvin5678 
is it still a distance issue ?

**Comment by Marvin5678** [comment]
it is still an issue with me plese help

**Comment by Echinaceax** [comment]
Hi @Marvin5678 
is it still a distance issue ?

**Comment by Marvin5678** [comment]
yes it still targeting only main target not the others

**Comment by Echinaceax** [comment]
### confirmed still has issues 

@Keader still has issues

out of range issue = no bounce 
https://gyazo.com/75e7b4b152ebf5e0af59c8a5490d57fe

range good = bounce to other target
https://gyazo.com/9537d0c12d5c6cb7664d28cc798dbed9

spare test on different mobs, seems to only work when mobs are in range of each other 
https://gyazo.com/d224226a2bee5b17c29dfa32dfb0e44b

**Comment by Marvin5678** [comment]
i try it it is still an issue with me tnx anyway

**Comment by Echinaceax** [comment]
i confirmed the issue for you @Marvin5678 
Will be fixed when Coders get to it on the list 
thanks

**Comment by Marvin5678** [comment]
Thank you!

**Comment by mfranca0009** [comment]
World of Warcraft: Wrath of the Lich King Patch 3.0.3 (04-Nov-2008): The Avenger’s Shield bounce distance has been reduced to 10 yards (from 15).

**Comment by mfranca0009** [comment]
Should be fixed, the bounce distance was set to 7.5 yards and I've updated it to 10 yards based on the patch 3.0.3 patch note. It should be correct, there was no changes for bounce distance after 3.0.3 for Cataclysm.

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 

much better @mfranca0009 

![image](https://user-images.githubusercontent.com/39439201/107856120-5f342e80-6e26-11eb-879e-1b65a318cfef.png)
