### ISSUE TITLE
[NPC] Brew of the Month - Missing - Ogrimmar

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1254]
**Links:**

https://www.wowhead.com/npc=44853/branzlit

**What is happening:**
This NPC is missing from his location.
His buddy Ray'ma also a member of the brew of the month is their but not this vendor

**What should happen:**

He should be stood beside Ray'ma in the valley of strength Ogrimmar.

**Comment by Kitzunu** [comment]
https://cata-twinhead.twinstar.cz/?npc=27812

**Comment by Kitzunu** [comment]
Fixed in the DEV Realm.
Dont forget to delete cache before testing.

**Comment by Echinaceax** [comment]
@Kitzunu - must be same reason for this too. i'll recheck tomorrow :) 
 
![noppp](https://user-images.githubusercontent.com/39439201/55515536-1bd5da00-566b-11e9-9f80-d9af5a53d24d.jpg)

**Comment by Kitzunu** [comment]
Nop, thats another NPC :D

Do .lo c Ray'Ma and go to that NPC and the Brew Vendor should be next to him :)
