### ISSUE TITLE
[Spell]Inquisition - Id 84963 - Paladin

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#1256]
**Links:**
https://www.wowhead.com/spell=84963/inquisition

from WoWHead or our Armory

**What is happening:**
As Describe in tool tip for spell inquisitions duration should increase from 4-8-12 sec depending on amount of holy power used. but this is not working eve at 3 stacks of  holy power duration stays at 4 secs.

**What should happen:**
 Inquisitions_ duration should increase from 4-8-12 sec depending on amount of holy power used.

**Comment by bagi84** [comment]
Just checking reti spec and when https://www.wowhead.com/spell=223817/divine-purpose procs Inquisition does work as intended with 3 stacks of holy power

**Comment by Keader** [comment]
Fixed.
