### ISSUE TITLE
[Location] Roof Grommash hold - Ogrimmar - low prio/visual issue.

### ISSUE THREAD

**Issue by ghost** [WoWManiaUK/Blackwing-Lair#1257]
**What is happening:**
In the location on the roof were the quartermaster's are located you can only run so far in, then there appears to be like an invisible object/wall that stops the player form going all the way in.

**What should happen:**
There appears to be no ledge preventing the player from reaching the back of the room therefore there shouldn't be anything that stops them, maybe they are meant to be stood on a platform that has vanished - hence low prio - visual issue

**Comment by Echinaceax** [comment]
Map issue, 
doesnt prevent player from accessing the vendors 
We are not map editing so setting as is
