### ISSUE TITLE
[NPC] Goram <Guild Vendor>-46572- Orgrimmar

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1263]
**Links:**

https://www.wowhead.com/npc=46572/goram

**What is happening:**
- Seems that these are unlocked before they should be (check link) 
- They all unlocked in stages according to "guild level"

**What should happen:**
- shouldn't be available until guild level reaches correct status (see link) 
https://www.wowhead.com/npc=46572/goram

Side note: Same as Undercity guild vendor #1246

**Comment by Dranah** [comment]
These issues aren't priority atm, these are misc items not high end gear.

**Comment by Echinaceax** [comment]
still an issue https://github.com/WoWManiaUK/Blackwing-Lair/issues/3968
