### ISSUE TITLE
[Spell] Beacon of light - Paladin - High Priority -53563- (causing server crashes)

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#1264]
**Links:**
https://www.wowhead.com/spell=53563/beacon-of-light
from WoWHead or our Armory

**What is happening:**
After casting beacon of light on a target the next spell I cast causes a server crash 

**What should happen:**
I should be able to heal with out fear of wiping out millions of gamers everywhere

**Comment by Keader** [comment]
Fixed.
Fixed spell too (has not working, even after fix crash)
