### ISSUE TITLE
[NPC] Zangen Stonehoof - chat/speach - Thunder Bluff

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1267]
**Links:**
https://www.wowhead.com/npc=4721/zangen-stonehoof

**What is happening:**
This NPC's in game general chat log isn't converted into common tounge
![World of Warcraft 31_03_2019 20_02_34](https://user-images.githubusercontent.com/42302580/55293607-1de03480-53f0-11e9-9a07-55a2c300132c.png)

**What should happen:**
Should be converted into English so that it can be understood.

**Comment by Dranah** [comment]
There is no such as english in wow... he speaks Taurahe and you're a blood elf that does not speak that language. Please test with a tauren char.

**Comment by Dranah** [comment]
@wow-mania please revert the fix and let us test with a proper race char.

**Comment by Kitzunu** [comment]
Will close since it was labled as invalid (Not a bug)
