### ISSUE TITLE
[NPC] Shay Pressler <Guild Vendor>-46602- (issue1) -  Stormwind 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1269]
_Issue1_

**Links:**
https://www.wowhead.com/npc=46602/shay-pressler

![sw1a](https://user-images.githubusercontent.com/39439201/55294986-99e67680-5408-11e9-937e-99b7ca8b6f86.jpg)
![sw1](https://user-images.githubusercontent.com/39439201/55294989-9c48d080-5408-11e9-8c60-9abac929144c.jpg)

**What is happening:**

- [ ] Seems that these are unlocked before they should be (check link) 
- [ ] They all unlocked in stages according to "guild level"

**What should happen:**
- shouldn't be available until guild level reaches correct status (see link) 
https://www.wowhead.com/npc=46602/shay-pressler

**Comment by Rushor** [comment]
Which faction has the guild?

**Comment by Echinaceax** [comment]
@Rushor Ally

**Comment by Dranah** [comment]
These issues are no priority atm. These are misc items, not high end gear.

**Comment by Echinaceax** [comment]
this issue is that they are availble to but without guild rep level
