### ISSUE TITLE
[Spell/Modifier] Holy Power - Paladin resource - Holy Spec (Mainly)

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#1270]
**Links:**
### Main Spell/Modifier -
https://www.wowhead.com/spell=85247/holy-power
### Related Spells -
https://www.wowhead.com/spell=20473/holy-shock
https://www.wowhead.com/spell=82326/holy-light
https://www.wowhead.com/spell=19750/flash-of-light
https://www.wowhead.com/spell=210191/word-of-glory
https://www.wowhead.com/spell=135403/divine-light
https://www.wowhead.com/spell=173379/holy-radiance
https://www.wowhead.com/spell=85222/light-of-dawn
### Related Talent -
http://cata-shoot.tauri.hu/?spell=85512

from WoWHead or our Armory

**What is happening:**
### General Background Info-
**Holy power**
This will be an additional resource that paladins get in Cataclysm. This Resource used by all paladin Spec for different reasons. Some abilities generate Holy Power and others consume either all available or 3 Holy Power. Many spells take advantage of it, like Templar's Verdict, Tower of Radiance and Zealotry. Holy power Charges stack up to a maximum of 3.
While out of combat one stack will get remove per 10sec (unless you refresh it with a heal or talents related abilities).
The Holy Power Resource is shown on a separate Bar displayed under the mana bar on a paladins HUD.
The standard Holy Power Charge Generating abilities for a Holy Paladin are Holy Shock ,Holy Radiance and with the talent 'Tower of Radiance' Divine Light and Flash of Light should also Generate a Holy Power Charge.
### Issues -
- [ ] Holy Shock and Holy Radiance are having various different issues in game, examples are as follows
1. Sometimes works as desired showing a charge of Holy Power and applying the desired effect and modifiers for the spells that require Holy Power Charges
2. Sometimes doesn't grant a charge of holy power but displays the Abilities that require a Charge as able to use but not working due to no charges being available for use.
3. Grants a Charge of Holy power But then instantly removes the charge rendering the abilities that use a charge useless.
- [ ] The Talent 'Tower of Radiance' Not granting Charges of Holy Power from the spells stated in the tooltip.
- [ ] Word of Glory Not scaling with the amount of Holy Power Charges available but removing all charges when used. 
- [ ] Light of Dawn Not Scaling with the amount of Holy Power Charges available but removing all charges when used.
- [ ] Beacon of Light Cannot Generate spells using the Talent tree Ability 'Tower of Radiance' due to once the described heals are used on a Beacon of light Target they Crash the test server.
### Related Issues - 
I honestly believe the Holy Power Issue is the solo problem with the remaining Issues with paladin spells for all specs. All the issues revolve  around Holy Power usage and scaling.

If You need any Help recreating the issues im happy to help anyway I can . 

**What should happen:**

All the Abilities used for Examples above Should behave, scale and modify spell effects  as described in their links above.

**Comment by Keader** [comment]
Is not a generical bug. Need a script for each one.
So not make sense all bugs in same topic.
Please @Echinaceax , @Kitzunu split it.
