### ISSUE TITLE
[NPC] Kobolt Tunnler -475- Elwynn Forest 

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#1274]
**Video**

https://www.dropbox.com/s/q930670t1nge4r0/path%20rendered.mp4?dl=0
U can see the bug here.

**What is happening:**

The NPC going through the fence.

**What should happen:**

The npc need to jump the fence, or go around.

P.S. 
They can not attack through the fence too.

**Comment by Echinaceax** [comment]
npc - https://www.wowhead.com/npc=475/kobold-tunneler
