### ISSUE TITLE
[Quest] Wanted: "Hogger" -176- ( Final Cinema BUG )  -Elwynn Forest

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#1275]
**Links:**

![hogger](https://user-images.githubusercontent.com/6819293/55326989-5da72a80-5489-11e9-9183-62c504f42876.png)

**What is happening:**

NPC spawn x2 (2 npc each type)

**What should happen:**

NPC spawn x1 (1 npc each type)

**Comment by Echinaceax** [comment]
npc - https://www.wowhead.com/quest=176/wanted-hogger

**Comment by wow-mania** [comment]
I can only see one.

**Comment by Echinaceax** [comment]
> I can only see one.

this might help jani 

![its here](https://user-images.githubusercontent.com/39439201/55333335-5edf5400-5497-11e9-957e-9a9b28122480.jpg)

**Comment by Kitzunu** [comment]
@fvicaria as per request I checked on dev and confirmed this, all NPC's spawned in the roleplay has a duplicate copy of themselfs
![image](https://user-images.githubusercontent.com/24550914/55334611-de6e2280-5499-11e9-92ab-3e156a8760ec.png)

**Comment by Kitzunu** [comment]
I believe this is handled in core scripts `npc_hogger`

**Comment by Rushor** [comment]
seems fixed now

![I](https://i.imgur.com/U45kHEB.jpg)
