### ISSUE TITLE
[NPC] Rogue Wizard -474- (objects ignoring, not attacking on melee range) - Elwynn Forest

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#1276]
**Video/Image**

![WoWScrnShot_040119_155840](https://user-images.githubusercontent.com/6819293/55333244-2d668880-5497-11e9-9a88-b778566b64ce.jpg)

[Video](https://i.imgur.com/j3GIZqm.gif)

**Links:**

Npc Link: https://www.wowhead.com/npc=474/rogue-wizard

**What is happening:**

NPC is ignoring the Object. After mana going low, the npc does not run to the target to attack in melee

**What should happen:**

Object should block the npc from casting spell. Afet mana going low the npc need to run to the targetr and attack in melee.

**Comment by Echinaceax** [comment]
according to wowhead if click on "abilities" it does show only shows "frostbolt"
So i think hes meant to be range only

**Comment by Xman993** [comment]
yes. the bolt is ignoring line of sight. u can see it on the video.

**Comment by Rushor** [comment]
the creature must use the bolt on erange and then go to melee once it is OOM. That's how all creatures in the world behave.
