### ISSUE TITLE
[Quest] Orders from Base Camp - Stonetalon Mountain - 26016

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#1279]
**Links:**
https://www.wowhead.com/quest=26016/orders-from-base-camp
https://www.wowhead.com/npc=41023/overlord-kromgar
from WoWHead or our Armory

**What is happening:**

Perfect quest but Overlord Krom'gar is absent.

**What should happen:**

You should be able to deliver the quest at Overlord Krom'gar.

Pitsecond: ORC warlock

**Comment by Kitzunu** [comment]
Fixed when Janitor applies fix
(Probably tomorrow morning)
