### ISSUE TITLE
[Quest]  Thunder Falls

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#128]
Fishing daily quest in stormwind.
I had 35 attempts from different locations
28,61
26,59
27,61
27,60
24,59
23,59
22,58
22,57
20.59
not even 1 violet perch fished
https://www.wowhead.com/quest=26536/thunder-falls

**Comment by wow-mania** [comment]
I assume you had the quest.

**Comment by Echinaceax** [comment]
i might have the reason for that ...these are fishing in Darkshore and no meant too :)
will link 

#1035

**Comment by Echinaceax** [comment]
Did find the zone for this 

![fishing violet perch](https://user-images.githubusercontent.com/39439201/57202413-2efb0300-6fa5-11e9-9339-f5fe7d364cf8.jpg)
