### ISSUE TITLE
[Quest] Da Voodoo: Stormer Heart - Stonetalon Mountain - 26060

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#1280]
**Links:**
https://www.wowhead.com/quest=26060/da-voodoo-stormer-heart
https://www.wowhead.com/npc=3995/witch-doctor-jinzil
https://www.wowhead.com/item=56796/stormer-heart
https://www.wowhead.com/npc=4008/cliff-stormer
from WoWHead or our Armory

**What is happening:**

The Cliff Stormer doesn't drop quest item, the Stormer heart.

**What should happen:**

The Cliff Stormer should drop Stormer heart.

Pitsecond: ORC warlock

**Comment by Kitzunu** [comment]
Fixed when Janitor applies fix
(Probably tomorrow morning)
