### ISSUE TITLE
[Quest] All's Quiet on the Southern Front - Stonetalon Mountain - 26073

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#1282]
**Links:**
https://www.wowhead.com/quest=26073/alls-quiet-on-the-southern-front
https://www.wowhead.com/spell=78346/kromgar-champion#comments
from WoWHead or our Armory

**What is happening:**
Overlord Krom'gar isn't there.

**What should happen:**

A simple message quest to Overlord Krom'gar. He should be in place.

Pitsecond: ORC warlock

ps. maybe also look to the reward.

**Comment by Kitzunu** [comment]
Fixed when Janitor applies fix
(Probably tomorrow morning)
