### ISSUE TITLE
[Quest] Nothing Left for You Here - 26134 - (issue2) - Stonetalon Mountain

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#1285]
**Links:**
https://www.wowhead.com/quest=26134/nothing-left-for-you-here
https://www.wowhead.com/npc=35286/furien
https://www.wowhead.com/npc=42039/high-chieftain-cliffwalker
from WoWHead or our Armory

**What is happening:**
Furien isn't there. Missing.

**What should happen:**

Furien should be on his place.

Pitsecond: ORC warlock

**Comment by Kitzunu** [comment]
Can someone confirm this please?

>https://www.wowhead.com/npc=35286/furien#comments:id=1621828
I made a ticket about this quest and a GM responded to me that this quest in fact is not broken or bugged. The quest is not even a "real quest", all of the "Warchief´s commands" are so called "breadcrumbs" to guide players in the right direction. However, have u already start questing in that area (not starting with the Command quest) and most likley done quest involving something with Furien, he will no longer be there. And reason why the "?" showing on map is cus of the log saying where he supposed to be, but seeing as Furien is a npc who wanders around and moves places along the questchain, hes somewhere else really. And if this is the case for you, just abandon the quest as it wont do you any good anymore. GM also then said in the future they will probably add some code to make the quest invalid so players dont go chasing ghosts! :)

**Comment by Echinaceax** [comment]
Reported by me in March #899

**Comment by Rushor** [comment]
![I](https://i.imgur.com/F6aEwIz.jpg)
