### ISSUE TITLE
[NPC] Torian - Inactive - Silvermoon

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1286]
**Links:**
https://www.wowhead.com/npc=16649/torian

**What is happening:**
Doesn't open his chat when targeted

**What should happen:**
As a none warlock he should say he cant train the player and for warlocks he should open his training page

**Comment by Rushor** [comment]
same issue as https://github.com/WoWManiaUK/Blackwing-Lair/issues/1236 .  will combie those
