### ISSUE TITLE
[NPC] Trainee Sinther - missing -Silvermoon

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1287]
**Links:**
https://www.wowhead.com/npc=18628/trainee-sinthar

**What is happening:**
unable to locate the NPC above

**What should happen:**
Should be located in Murder Row.

**Comment by Echinaceax** [comment]
![no  not](https://user-images.githubusercontent.com/39439201/55417640-62470e00-5571-11e9-9e15-db8b8d330fb1.jpg)

**Comment by Rushor** [comment]
creature guid 1007119 id: 18628 dev restarted
