### ISSUE TITLE
[NPC] Brother Malach - Undercity

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1289]
**Links:**
https://www.wowhead.com/npc=5679/lysta-bancroft

![lysta](https://user-images.githubusercontent.com/39439201/55347273-b0e2a280-54b4-11e9-86de-933df4ff96de.jpg)

**What is happening:**
- not translating to common tongue

**What should happen:**
Should be converted into English so that it can be understood.

**Comment by Rushor** [comment]
Remember to delete the cache before testing - server is restarting now and the fix will be applied on the DEV Realm.

**Comment by Echinaceax** [comment]
He doesnt speak at all now :)

**Comment by Rushor** [comment]
well on my server he speaks but are you sure that the event was started?

**Comment by Echinaceax** [comment]
@Rushor 
i stood there and and only Brother Malach speaks

"Well done Edward and Tyler. You are progressing along in your training quite nicely. We shall test your mettle again soon
Edward, Tyler. Prepare for your first challenge.
Lysta, summon in the captives.
Not a challenge at all it seems. Let us see how you handle your second test. Lysta, bring forth minions of the Lich King.
Lysta, summon in undead captives.
It is time to face your final challenge, young warriors! Prepare for your hardest fight yet.
Lysta, summon forth... the abomination!"

- Then what happens the npc #1306 and #1304
- then they start fighting and kill him 


he doesnt speak anytime through this fight (on dev)
 i waited for Lysta to speak (yes i cleared cache)

![lol](https://user-images.githubusercontent.com/39439201/55411139-64a36b00-5565-11e9-8f19-16ab084b5eaa.jpg)
![lol lol](https://user-images.githubusercontent.com/39439201/55411148-6836f200-5565-11e9-8b26-6af031cecfa3.jpg)

**Comment by Rushor** [comment]
Multpile spawns appear see https://github.com/WoWManiaUK/Blackwing-Lair/issues/1306

**Comment by Dranah** [comment]
Is this even a bug? Those undead npcs tend to speak gutterspeak, that a bloodelf cannot understand...

**Comment by Dranah** [comment]
Ok so... apparently Lysta was never meant to speak. In the original SS you linked, it is Brother Malach speaking, you can see the ear of the chat bubble pointing to him, not Lysta. So Lysta not speaking is intended, Brother Malach is supposed to tell everything. The chat has been fixed and is in english now, apparently it does not have the [Gutterspeak] tag, so it is in common.
Nothing more to fix here.

**Comment by Echinaceax** [comment]
Ooops my bad - wrong npc link and title 
human error ..but 

i did see that Malach was fixed so no harm done :)
