### ISSUE TITLE
[Item] Bag of Shiny Things

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#129]
[Bag of Shiny Things] reward received from quest Rock Lobster
https://www.wowhead.com/quest=26442/rock-lobster
 [Bag of Shiny Things]
https://www.wowhead.com/item=67414/bag-of-shiny-things#contains

Same issue as with bag that I open for game tokens in darkmoon fair 
when I open I receive nothing, there is no loot from them.

**Comment by Repsidian** [comment]
i just completed the daily quest on the server and i got nothing out the bag and it says here that its been fixed confirmed and fixed in dev from last year

**Comment by Echinaceax** [comment]
Same here - bag still empty

**Comment by Kitzunu** [comment]
works
