### ISSUE TITLE
[NPC] Blastgineer Fuzzwhistle - Stonetalone Mountain - 40901

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#1291]
**Links:**
https://www.wowhead.com/npc=40901/blastgineer-fuzzwhistle
from WoWHead or our Armory

**What is happening:**

Doesn't have quests

**What should happen:**

Should have quests

Pitsecond: ORC warlock

**Comment by Rushor** [comment]
it's a questchain. you first have to complete https://www.wowhead.com/quest=26001/the-missing-blastgineer in order to get https://www.wowhead.com/npc=40901/blastgineer-fuzzwhistle from him.

**Comment by Rushor** [comment]
Remember to delete the cache before testing - server is restarting now and the fix will be applied on the DEV Realm.
