### ISSUE TITLE
[Item] Tiny Treasure Chest - 67539 - 

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#1292]
**Links:**

https://www.wowhead.com/item=67539/tiny-treasure-chest#contains

**What is happening:**
Drop is empty

**What should happen:**
Should have loots 

https://www.wowhead.com/item=67539/tiny-treasure-chest#contains

**Comment by Rushor** [comment]
Remember to delete the cache before testing - server is restarting now and the fix will be applied on the DEV Realm.

**Comment by Echinaceax** [comment]
![fixed](https://user-images.githubusercontent.com/39439201/55368967-c972ad00-54f4-11e9-96e2-72dc3ffd4bfd.jpg)
