### ISSUE TITLE
[NPC] Mirkin - Stonetalon Mountain - 41891

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#1293]
**Links:**
https://www.wowhead.com/npc=41891/mirkin
from WoWHead or our Armory

**What is happening:**

Nothing

**What should happen:**

Should be able to interact, sell stuff but he doesn't.

Pitsecond: ORC warlock

**Comment by Rushor** [comment]
Remember to delete the cache before testing - server is restarting now and the fix will be applied on the DEV Realm.
