### ISSUE TITLE
[Spell] Nightfall - Affliction Warlock Talent

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1294]
**Links:**
https://www.wowhead.com/spell=264571/nightfall
from WoWHead or our Armory

**What is happening:**
When the talent procs it allows u to fire numerous shadow bolts 

**What should happen:**
When the talent procs it should only make your next shadow bolt instant

**Comment by Dranah** [comment]
Consumed on use now.
