### ISSUE TITLE
[Object] STAY OUT! - Stonetalon Mountains - 203186

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#1295]
**Links:**
https://www.wowhead.com/object=203186/stay-out
from WoWHead or our Armory

**What is happening:**

Gives quest. Double for alliance and horde.

**What should happen:**

Should give only for horde or only alliance.

Pitsecond: ORC warlock (not tested by alliance)

**Comment by Rushor** [comment]
remember to delete the cache before testing - server is restarting now.
