### ISSUE TITLE
[NPC] Doranir - chat -Silvermoon

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1299]
**Links:**
https://www.wowhead.com/npc=47361/doranir

**What is happening:**
No chat when targeted needs chat adding. currently reads needs txt ytdb

**What should happen:**

Needs chat adding.

**Comment by sarahkay88** [comment]
same issue for the NPC stood next to him-
NPC Aelnara - https://www.wowhead.com/npc=47362/aelnara

**Comment by Rushor** [comment]
remember to delete the cache before testing

**Comment by Echinaceax** [comment]
![not fixed](https://user-images.githubusercontent.com/39439201/55363811-a50bd600-54de-11e9-823d-96f6de6ee40a.jpg)

Not fixed :)

**Comment by Rushor** [comment]
ahh no wait i need to restart

**Comment by Rushor** [comment]
remember to delete the cache before testing - server is restarting now.
