### ISSUE TITLE
[NPC] Craggle Wobbletop

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#130]
I can interact with npc, but he dont offer to sell toys.

Stormwind location not fix it walk around
Craggle Wobbletop [Toys and Novelties]
![toys and npc](https://user-images.githubusercontent.com/20323863/49021187-5cd85200-f192-11e8-8e53-b54805178f20.png)

**Comment by wow-mania** [comment]
Please add links to every NPC, quest etc. Thanks.

**Comment by wow-mania** [comment]
Restart also fixed.
