### ISSUE TITLE
[NPC] Innkeeper Velandra - display -Silvermoon

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1300]
**Links:**
https://www.wowhead.com/npc=16618/innkeeper-velandra

**What is happening:**
Display 
1x - home 
2x - browse goods

**What should happen:**
Should be 
1x - home
1x - browse goods

**Comment by Rushor** [comment]
Remember to delete the cache before testing - server is restarting now and the fix will be applied on the DEV Realm.
