### ISSUE TITLE
[quest=27220] [Nat's Bargain] - Dustwallow Marsh

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1302]
**Links:**
https://www.wowhead.com/quest=27220/nats-bargain
https://www.wowhead.com/item=33166/pagles-fish-paste-extra-strength
from WoWHead or our Armory

**What is happening:**
Just take this paste -- yeah, it smells a little foul -- smear it on yourself, and swim into the deep part of Tidefury Cove to the southwest. Let me know how it works! but no shark is coming.
Tried it 4 times with smearing it on different places. No shark coming what so ever

**What should happen:**
Just take this paste -- yeah, it smells a little foul -- smear it on yourself, and swim into the deep part of Tidefury Cove to the southwest. Let me know how it works!  And the shark should appear

**Comment by simonverse** [comment]
same issue

**Comment by Rushor** [comment]
If you are swimming in range of the spot you can see on the picture, the questmob will spawn > kill him > get credit.

![I](https://i.imgur.com/2YWbbRo.jpg)
![I](https://i.imgur.com/jACwtGa.jpg)
