### ISSUE TITLE
[NPC] Male Human Captive -5680- Undercity

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1304]
**Links:**

https://www.wowhead.com/npc=https://www.wowhead.com/npc=5680/male-human-captive/male-human-captive

**What is happening:**
- Double / triple spawns 

**What should happen:**
Only one should spawn

**Comment by Rushor** [comment]
some more should spawn (3 at least) as you can see https://www.wowhead.com/npc=5680/male-human-captive in the screenshot https://www.wowhead.com/npc=5680/male-human-captive#screenshots:id=41598

**Comment by Echinaceax** [comment]
@Rushor has to be spacing then 

![nope1](https://user-images.githubusercontent.com/39439201/55415583-8d2f6300-556d-11e9-8162-804e9d0fab7f.jpg)
