### ISSUE TITLE
[NPC] Captive Abomination -5687- Undercity

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1306]
**Links:**

https://www.wowhead.com/npc=5687/captive-abomination

**What is happening:**
- Double / triple spawned

**What should happen:**
one one copy of them

**Comment by Rushor** [comment]
attack group will now be summoned only one time

**Comment by Echinaceax** [comment]
@Rushor 
Lysta is dead at this part ....the text from Brother Malach its still appearing :)

![dead](https://user-images.githubusercontent.com/39439201/55415670-b94ae400-556d-11e9-8384-5b8a6d850fe9.jpg)





Spacing (they are all onside each other :)

**Comment by Rushor** [comment]
okay i will move that issue to https://github.com/WoWManiaUK/Blackwing-Lair/issues/1289 it's the sam reason somehow. will combine the issues.
