### ISSUE TITLE
[quest=27188]  [What's Haunting Witch Hill?] - Dustwallow Marsh

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1307]
**Links:**
https://www.wowhead.com/quest=27188/whats-haunting-witch-hill
from WoWHead or our Armory

**What is happening:**
This quest is not counting the kills or anything, in WOTLK u got a spirit spawned when u killed mobs here but nothing now.
According to wowhead you should get the killingblow to get counted for in the quest bubt im alone here and im shurely get the blow and no count  lol
Quest not working / completable

**What should happen:**
Comment from Wowhead

As with the old version of this quest, make sure you (not your pet, party member etc.) get the killing blow on the zombies/ghosts to get the information from them.

**Comment by BlueDragonKing7** [comment]
Tried this quest today, didn´t work either.

**Comment by simonverse** [comment]
same

**Comment by Rushor** [comment]
kill the creatures and you get the credit 

![I](https://i.imgur.com/gdaECUZ.jpg)
