### ISSUE TITLE
[quest=27287] [The Deserters] Dustwallow Marsh

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1310]
**Links:**
https://www.wowhead.com/quest=27287/the-deserters
from WoWHead or our Armory

**What is happening:**
Get information about Reethe from Balos Jacken and the deserters in Dustwallow Marsh. 
The local lieutenant seems to be Balos Jacken. See if you can get some information out of him.
I get him to surrender but nothing more happens and he start over again to fight me.
Did this 5 times and same resault
Not completable
**What should happen:**
He should surrender and give me information

**Comment by Rushor** [comment]
push him down to 20 percent and he will turn friendly and you can complete the quest
