### ISSUE TITLE
[NPC] Marogg <Infantry Chef> -42506- Orgrimmar

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1312]
_issue2_

**Links:**

https://www.wowhead.com/npc=42506/marogg

**What is happening:**
- [ ] He doesnt have cooking training 

**What should happen:**
- he should offer cooking training

**Comment by Echinaceax** [comment]
nope :)
![nope1](https://user-images.githubusercontent.com/39439201/55414568-a9ca9b80-556b-11e9-8e58-7d926392be9d.jpg)

**Comment by Rushor** [comment]
https://www.wowhead.com/npc=42506/marogg is that one https://i.imgur.com/BB5Zr0a.jpg
