### ISSUE TITLE
[NPC/Vendor] Bliztik - 2481 - - Duskwood - (missing)

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#1313]
**Links:**

 NPC Link = http://www.wow-mania.com/armory/?npc=2481

**What is happening:**

He is missing

**What should happen:**

He shold be at 18.0, 54.4

**Here**
![WoWScrnShot_040219_124813](https://user-images.githubusercontent.com/6819293/55397122-c18f2900-5545-11e9-8a9a-3d19012cf4f1.jpg)

**Comment by Kitzunu** [comment]
Removed in 4.0.3a
