### ISSUE TITLE
[Spell] Earthquake - 61882 Shaman

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Blackwing-Lair#1315]
**Links:**
https://www.wowhead.com/spell=61882/earthquake

**What is happening:**
The spell learned by elemental shamans as a last point in elemental tree is doing no dmg to targeted dummies shown on both screenshot and combat log
![Screenshot_11](https://user-images.githubusercontent.com/43518434/55412685-35422d80-5568-11e9-90e1-c82e53199300.png)
![Screenshot_10](https://user-images.githubusercontent.com/43518434/55412701-396e4b00-5568-11e9-8fff-940e35a3f33f.png)

**What should happen:**
The spell is supposed to damage the targeted area as shown in description of the spell:
![Screenshot_12](https://user-images.githubusercontent.com/43518434/55412792-5b67cd80-5568-11e9-8812-876d17af6d7b.png)
Would need some gear to check if it does knockup targets.

**Comment by Dranah** [comment]
The spell now works but the damage values are incorrect.

The base damage of tick (ID 77478 in spellwork) is supposed to be 325 damage, and the SP coefficient 11%

Current experimental values show a base damage of 240 with a SP coefficient of 15,5%

Need to correct values. Currently spell underperforms with zero gear and overscales with higher gear.

**Comment by Keader** [comment]
No regression, is a new issue.
Fixed.
(Maybe need use .reload spell_bonus_data, before test).

**Comment by Dranah** [comment]
The SP coefficient is off by 0,2%, too minor to deal with. Otherwise works fine.
