### ISSUE TITLE
[Spell] Fire Nova - 1535 Shaman

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Blackwing-Lair#1316]
**Links:**
https://www.youtube.com/watch?v=n4qllfFlibc
https://www.wowhead.com/spell=1535/fire-nova

**What is happening:**
Once you put the Flame Shock on the target and use Fire Nova to damage all surrounding enemies you lose Flame Shock DoT on the target which should not happen as you can see in the youtube link i have sent already. 
![Screenshot_13](https://user-images.githubusercontent.com/43518434/55413874-75a2ab00-556a-11e9-8301-bd1ade36e346.png)
![Screenshot_14](https://user-images.githubusercontent.com/43518434/55413886-7a675f00-556a-11e9-8af4-6fbf76e62e32.png)
![Screenshot_15](https://user-images.githubusercontent.com/43518434/55413891-7c312280-556a-11e9-8c77-1b8b5f3016da.png)

**What should happen:**
You can DoT multiple targets with Flame Shock, all of them will emit the Fire Nova damaging surrounding enemies but the DoT will still remain on the targer until the timer is gone, shown also on the video.

**Comment by Keader** [comment]
Fixed.
