### ISSUE TITLE
[Quest - 10144] Disrupt Their Reinforcements  - Hellfire Peninsula

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#1317]
**Links:**
  
  *Zone - [Hellfire Peninsula](https://www.wowhead.com/hellfire-peninsula)
  *Quest  - [Disrupt Their Reinforcements](https://www.wowhead.com/quest=10144/disrupt-their-reinforcements)
  *Quest Item -  [Kingston's Primers](https://www.wowhead.com/item=28106/kingstons-primers)

**What is happening:**

After u take the quest from [Forward Commander Kingston](https://www.wowhead.com/npc=19310/forward-commander-kingston), and you collect 4x [Demonic Rune Stone](https://www.wowhead.com/item=28513/demonic-rune-stone), you can not use [Kingston's Primers](https://www.wowhead.com/item=28106/kingstons-primers) to destroy the portals! its says "you have no target".

**What should happen:**

You need to be able to use [Kingston's Primers](https://www.wowhead.com/item=28106/kingstons-primers) on portals, consume 4x [Demonic Rune Stone](https://www.wowhead.com/item=28513/demonic-rune-stone) and get a complete mark.

**Comment by Chargelol** [comment]
i even cant attack any npcs to get the item invalid target ou of range

**Comment by Dranah** [comment]
This works fine. You need to be standing inside the portal otherwise it cannot target.
![WoWScrnShot_051119_052840](https://user-images.githubusercontent.com/31132743/57564541-af5aa300-73ad-11e9-84ac-fcc181dd7721.jpg)

**Comment by Chargelol** [comment]
thanks for info gues i dit it wrong or was used to bigger range for it to work
