### ISSUE TITLE
[npc=42921]Dragul Giantbutcher (Double double spawn) -  Deepholm

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1318]
**Links:**
https://www.wowhead.com/npc=42921/dragul-giantbutcher
from WoWHead or our Armory

**What is happening:**
There is 4 - 6 of this npc [npc=42921]

**What should happen:**
Should only be 1

**Comment by Kitzunu** [comment]
Will be fixed when Janitor applies Fixes, probably tomorrow :)
Remember to delete the cache before testing

**Comment by Echinaceax** [comment]
@Kitzunu 
new labels - priorities changed

**Comment by Kitzunu** [comment]
@Echinaceax Yea I know ^^
I am still learning, so I am taking the easy ones :P

**Comment by Echinaceax** [comment]
![woooo](https://user-images.githubusercontent.com/39439201/55431956-fde87680-5591-11e9-98ea-f0bf9ffd1955.jpg)

**Comment by Kitzunu** [comment]
@Echinaceax As I said, it will be applied tomorrow :)

**Comment by Echinaceax** [comment]
then not fixed in dev "not ready for confirmation" 
ok i understand now thx
