### ISSUE TITLE
[NPC] Draenei Starting Zone -Yellow Mobs- Azuremyst Isle (get random agro)

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#1319]
**Links:**
[Vale Moth](https://www.wowhead.com/npc=16520/vale-moth) - ID 16520 -
[Volatile Mutation](https://www.wowhead.com/npc=16516/volatile-mutation) - ID 16516 -
[Nestlewood Owlkin](https://www.wowhead.com/npc=16518/nestlewood-owlkin) - ID 16518 -
[Mutated Owlkin](https://www.wowhead.com/npc=16537/mutated-owlkin) - ID 16537 -
[Mutated Root Lasher](https://www.wowhead.com/npc=16517/mutated-root-lasher) - ID 16517 -

**What is happening:**
Getting agro when attacking his friend.
[Volatile Mutation](https://www.wowhead.com/npc=16516/volatile-mutation) , [Nestlewood Owlkin](https://www.wowhead.com/npc=16518/nestlewood-owlkin) , [Mutated Owlkin](https://www.wowhead.com/npc=16537/mutated-owlkin) and [Mutated Root Lasher](https://www.wowhead.com/npc=16517/mutated-root-lasher) get aggro on you when u fight near him. Only [Vale Moth](https://www.wowhead.com/npc=16520/vale-moth)  stays cool!

**What should happen:**

They need all to stay cool!

**Comment by Xman993** [comment]
[Blood Elf Scout](https://www.wowhead.com/npc=16521/blood-elf-scout) -ID 16521- get aggro too

**Comment by Echinaceax** [comment]
@fvicaria 
Same issue as #879
