### ISSUE TITLE
[Quest - 9540 ] Totem of Tikti - Azuremyst Isle 

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#1320]
**Links:**

[Totem of Tikti ](https://www.wowhead.com/quest=9540/totem-of-tikti)

**What is happening:**

Doesn't get wings and falling

**What should happen:**

Need to get wings and slow falling

**Comment by Kitzunu** [comment]
This is a very sketchy fix... 

Atm a random player within range:5 will get the wings, but usually you dont do this in grp, and if you do I guess one has to retake the quest.

I dont know why SMART_TARGET_ACTION_INVOKER wasn't working here...
