### ISSUE TITLE
[NPC/Vendor-21145] Little Azimi -  Bloodmyst Isle-

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#1326]
**Links:**

[Little Azimi ](https://www.wowhead.com/npc=21145/little-azimi)

**What is happening:**

Vendor does not sell item

**What should happen:**

 Vendor need to sell item

**Comment by Echinaceax** [comment]
@Rushor 

![still no](https://user-images.githubusercontent.com/39439201/55492191-152d6f80-5637-11e9-90b8-1585f9a4e78d.jpg)

**Comment by Rushor** [comment]
okay now should worlk
