### ISSUE TITLE
[Quest] Axis of Awful - ID 26868 Missing Quest Item Loch Modan

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Blackwing-Lair#1328]
**Links:**
https://www.wowhead.com/item=60681/cannarys-cache
https://www.wowhead.com/quest=26868/axis-of-awful
(*) https://www.wowhead.com/item=60502/clever-plant-disguise-kit
(*) https://www.wowhead.com/item=60503/potent-murloc-pheromones
**What is happening:**
Once you are on the quest Axis of Awful you get the bag which should contain items such as those 2 linked above marked with (*), but once you accept the quest and open the bag you get nothing from it.
![torba](https://user-images.githubusercontent.com/43518434/55488706-d8f71080-5630-11e9-8529-82e7a1257801.png)
![Screenshot_16](https://user-images.githubusercontent.com/43518434/55488718-deecf180-5630-11e9-9c4c-6feb8ff81470.png)

**What should happen:**
Once you open the bag you need to get those 2 items to be able to complete the quest.

**Comment by Echinaceax** [comment]
@Kitzunu - not fixed bag empty
