### ISSUE TITLE
[Quest] Ending Their World ID: 9759  -  Azuremyst Isle 

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#1330]
**Links:**

[Video - Ending Their World](https://www.youtube.com/watch?v=EhWedvMTAkw)
[WowHead - Ending Their World](https://www.wowhead.com/quest=9759/ending-their-world)
[CataTwinheadDB - Ending Their World](https://cata-twinhead.twinstar.cz/?quest=9759)

**NPC Likns:**

[Demolitionist Legoso](https://cata-twinhead.twinstar.cz/?npc=17982) - ID 17982 -
[Sironas](https://cata-twinhead.twinstar.cz/?npc=17678) - ID 17678 - 
[Enraged Ravager](https://cata-twinhead.twinstar.cz/?npc=17527) - ID 17527 -
[Sunhawk Agent](https://cata-twinhead.twinstar.cz/?npc=17610) - ID 17610 - 
[Sunhawk Saboteur](https://cata-twinhead.twinstar.cz/?npc=17609) - ID 17609 - 

**What is happening:**

When you take the quest from [Demolitionist Legoso](https://cata-twinhead.twinstar.cz/?npc=17982) and he finish the dialog. [Demolitionist Legoso](https://cata-twinhead.twinstar.cz/?npc=17982) start running, but the wrong way([Image](https://user-images.githubusercontent.com/6819293/55493141-b7018c00-5638-11e9-9559-a37be2405b14.jpg)). Does not get aggro if you're attacked([Image](https://user-images.githubusercontent.com/6819293/55493477-46a73a80-5639-11e9-9840-5ace7a04078e.jpg)). But when you start fighting [Sunhawk Agent](https://cata-twinhead.twinstar.cz/?npc=17610) and [Sunhawk Saboteur](https://cata-twinhead.twinstar.cz/?npc=17609) it works all fine.

**What should happen:**

Demolitionist Legoso](https://cata-twinhead.twinstar.cz/?npc=17982) should always defend you, and the path should be fixed. More details on [Video - Ending Their World](https://www.youtube.com/watch?v=EhWedvMTAkw)

**Images**

![WoWScrnShot_040319_174819](https://user-images.githubusercontent.com/6819293/55493141-b7018c00-5638-11e9-9559-a37be2405b14.jpg)

![WoWScrnShot_040319_171413](https://user-images.githubusercontent.com/6819293/55493477-46a73a80-5639-11e9-9840-5ace7a04078e.jpg)

**Comment by Rushor** [comment]
attacking works fine now.

![I](https://i.imgur.com/WvCUgxt.jpg)
