### ISSUE TITLE
[NPC] Gor'Kresh - ID 27078 Loch Modan

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Blackwing-Lair#1331]
**Links:**
https://www.wowhead.com/quest=27078/gorkresh

**What is happening:**
2 of those NPCs are spawned at the same time, making it harder to complete the quest.

![Screenshot_18](https://user-images.githubusercontent.com/43518434/55495733-d818ab80-563d-11e9-8d6a-89f42a8a3791.png)

**What should happen:**
Only 1 of those NPC should be alive at the same time.

**Comment by Kitzunu** [comment]
Fixed in the DEV Realm.
Dont forget to delete cache before testing.

**Comment by Echinaceax** [comment]
@Kitzunu - still x2 
Its "spacing i think tho ...coz there are 3 sets of 2s :)

or - @Rushor need to restart :)

![still 2](https://user-images.githubusercontent.com/39439201/55512972-d4e4e600-5664-11e9-9810-9da9930b53da.jpg)

**Comment by Kitzunu** [comment]
Maybe I forgot to apply the SQL file lol
I'll check it tomorrow, now it's time for sleep zZzz

**Comment by Kitzunu** [comment]
Check again.

.lo c Gor'Kresh

If there are dups of another NPC, please open a new issue.
