### ISSUE TITLE
[Quest] The Winds of Loch Modan - ID 27116 Loch Modan

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Blackwing-Lair#1332]
**Links:**
https://www.youtube.com/watch?v=NKSLjtrwSRk
https://www.wowhead.com/quest=27116/the-winds-of-loch-modan

**What is happening:**
Once you accept the quest, the NPC is not summoning the Skystrider ( the mechanized chicken ) to take you the Algaz Station where you are supposed to the deliver the quest. This is the last quest in this quest chain provided by this guy starting at Farstriders Lodge.
![Skystrider](https://user-images.githubusercontent.com/43518434/55496492-75c0aa80-563f-11e9-8928-a9aaba4648ca.png)
 
The screenshot is showing that after taking the quest you are not riding the vehicle.
Such quests usually are bugged if you are mounted in the moment of accepting the quest, which was not the case in my scenario.

**What should happen:**
Ride the Skystrider to Algaz Station and then speak with Mountaineer Stormpike.
This is what is written on wowhead and also shown in video how it should look like, altough im not able to find the ID of the Skystrider.

**Comment by Drostthehunter** [comment]
I went there by foot and i was able to complete the quest even tho it wasnt showing on my World Map as a completed quest, yet the Vehicle part that should take you there is not working at all.
![Screenshot_19](https://user-images.githubusercontent.com/43518434/55496821-3181da00-5640-11e9-96f5-eeb703f71280.png)

**Comment by Rushor** [comment]
fixed!

![I](https://i.imgur.com/DarcgRd.jpg)
