### ISSUE TITLE
[Zone/Raid] Magtheridon's Lair - Hellfire Peninsula

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#1334]
**Links:**

[Hellfire Channeler](https://www.wowhead.com/npc=17256/hellfire-channeler#pickpocketing)

**What is happening:**

2x on each cube

**What should happen:**

1x on each cube

![image](https://wow.zamimg.com/uploads/screenshots/small/84073.jpg)

**Comment by Rushor** [comment]
oh the issue happens again! refix incoming
