### ISSUE TITLE
[Quest] Stop The Ascension ID 11260 - Howling Fjord

### ISSUE THREAD

**Issue by Felfyre** [WoWManiaUK/Blackwing-Lair#1336]
**Links:**
https://www.wowhead.com/quest=11260/stop-the-ascension
from WoWHead or our Armory

**What is happening:**
Halfdan the Ice-Hearted is double spawned

**What should happen:**

Halfdan the Ice-Hearted should only be spawned once

**Comment by Echinaceax** [comment]
@Rushor nows theres 0
![1 2](https://user-images.githubusercontent.com/39439201/55644916-81df7000-57d7-11e9-8ebf-f2497df15dfb.jpg)

**Comment by Rushor** [comment]
the creature is spawned by using https://www.wowhead.com/item=33346/vrykul-scroll-of-ascension
