### ISSUE TITLE
[Quest] Orabus the Helmsman  ID 11661- Howling Fjord

### ISSUE THREAD

**Issue by Felfyre** [WoWManiaUK/Blackwing-Lair#1339]
**Links:**
https://www.wowhead.com/quest=11661/orabus-the-helmsman
https://www.youtube.com/watch?v=3oz3U975URM&feature=youtu.be
from WoWHead or our Armory

**What is happening:**
A) Orabus The helmsman spawns twice
B) after using quest item, boat does not spawn, no crewmmen to fight before fighting Orabus
     (See Video)

**What should happen:**

A) Orabus Should only spawn once
B) after using quest item, a boat should spawn, glide in, and 5 waves consisting of 1 crewman for the first 4 waves, and finally Orabus the Helmsman should happen (See Video)

**Comment by Rushor** [comment]
the wave spawns will be very very future fix maybe once https://github.com/TrinityCore/TrinityCore/pull/20447 is implemented 
will fix the double spawn

**Comment by Felfyre** [comment]
Should I ignore double spawns then?

**Comment by Rushor** [comment]
from now on yes - all fixed again :>

**Comment by Echinaceax** [comment]
@fvicaria - DEV May need server restart :)

**Comment by Echinaceax** [comment]
@Rushor 

![nop nope](https://user-images.githubusercontent.com/39439201/55654356-7bf68880-57f1-11e9-9e66-640e040ee60b.jpg)

yes cleared cache and new server restart :)

**Comment by Rushor** [comment]
The creature is spawned by using https://www.wowhead.com/item=34844/horn-of-the-ancient-mariner
