### ISSUE TITLE
[NPC] Zanzi Mindslave

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#134]
Very slow movement speed

The Cape of Stranglethorn 51,31
Zanzil Mindslave hostile npc
https://www.wowhead.com/npc=43223/zanzil-mindslave

![wowscrnshot_112618_202150](https://user-images.githubusercontent.com/20323863/49037264-10087180-f1ba-11e8-8d7f-8212ed2d13a2.jpg)

**Comment by wow-mania** [comment]
By the way these are not critical issues and we are looking for things that stop the player on its track at the moment only.
