### ISSUE TITLE
[NPC] Fel Orc Neophyte - ID 17429 - The Blood Furnace - Hellfire Ramparts

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#1342]
**Links:**

[Fel Orc Neophyte](https://www.wowhead.com/npc=17429/fel-orc-neophyte)

**What is happening:**

can not attack [Fel Orc Neophyte](https://www.wowhead.com/npc=17429/fel-orc-neophyte)

**What should happen:**

you should be able to attack

![Fel Orc Neophyte](https://wow.zamimg.com/uploads/screenshots/small/85844.jpg)

**Comment by Echinaceax** [comment]
@wow-mania - checked both with name and with ID number
 
![both](https://user-images.githubusercontent.com/39439201/55654598-240c5180-57f2-11e9-8fc8-01b777d42232.jpg)
