### ISSUE TITLE
[NPC] Mo'grosh Darkmauler - 44758- Loch Modan

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1344]
**Links:**
https://www.wowhead.com/npc=44758/mogrosh-darkmauler

![spacing](https://user-images.githubusercontent.com/39439201/55553428-6cd3e580-56e0-11e9-866b-16c4ede1bb1e.jpg)

**What is happening:**
- Spacing (i think) 
- Definitely to closed together (not double spawned i dont think)

**What should happen:**
- Space them apart a bit

**Comment by Rushor** [comment]
yep will do that :)

**Comment by Rushor** [comment]
there are double spawns all over the place - will remove them https://www.wowhead.com/npc=44758/mogrosh-darkmauler
