### ISSUE TITLE
[NPC] Infesting Jormungar ID 30148 - Storm Peaks

### ISSUE THREAD

**Issue by Felfyre** [WoWManiaUK/Blackwing-Lair#1349]
**Links:**
https://www.wowhead.com/npc=30148/infesting-jormungar
from WoWHead or our Armory

**What is happening:**

the corpses of the dead infesting jormungar in Gimorak's Den move around. they dont attack, but they dont stay still either

**What should happen:**

they shouldnt move

**Comment by Felfyre** [comment]
There are no live infesting jormungar in Gimoraks Den, and they are needed for:
https://www.wowhead.com/quest=13055/cave-medicine

**Comment by Kitzunu** [comment]
Fixed. Delete cache before testing.

They are alive and well now, ready to kill you :D
