### ISSUE TITLE
[Quest] Raining Down Destruction - ID 11982 Missing Quest Grizzly Hills

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Blackwing-Lair#1351]
**Links:**
https://www.wowhead.com/quest=11981/find-kurun
https://www.wowhead.com/quest=11982/raining-down-destruction
https://www.wowhead.com/npc=26260/kurun

**What is happening:**

After completing the quest [Find Kurun] linked above you get no further quests, and this is a start of a chain quests consisting of 8 quests
![Screenshot_33](https://user-images.githubusercontent.com/43518434/55578071-5ac06a00-5715-11e9-8c6b-8594b9fab541.png)

![Screenshot_34](https://user-images.githubusercontent.com/43518434/55578074-5dbb5a80-5715-11e9-80f4-a3d41c0f4dcd.png)

![Screenshot_32](https://user-images.githubusercontent.com/43518434/55578085-6449d200-5715-11e9-952b-f849fc171061.png)

**What should happen:**

After completing https://www.wowhead.com/quest=11981/find-kurun the Kurun [https://www.wowhead.com/npc=26260/kurun] should give you the following quest.

**Comment by Kitzunu** [comment]
Test now

**Comment by Drostthehunter** [comment]
As soon as im done in raid!

**Comment by Echinaceax** [comment]
> As soon as im done in raid!
@Drostthehunter - not you ...he means me :)
