### ISSUE TITLE
[Quest] See You on the Other Side - ID 12121 Grizzly Hills

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Blackwing-Lair#1353]
**Links:**
https://www.wowhead.com/quest=12121/see-you-on-the-other-side
https://www.wowhead.com/item=36834/charged-drakiljin-mallet
https://www.youtube.com/watch?v=g5JE9d2p5Ls

**What is happening:**

When you use Charged Drakjin Mallet on the gongs, you are summoning the spirit that should kill you and thats the time you enter the spirit world. The death is happening and you are entering the spirit realm but there is no completition of the quest that the Drakjin have killed you so you can not turn in the quest in the spirit realm. 

![Screenshot_35](https://user-images.githubusercontent.com/43518434/55579909-a412b880-5719-11e9-9d39-8186b4ee39dd.png)

![Screenshot_36](https://user-images.githubusercontent.com/43518434/55579925-ae34b700-5719-11e9-9a81-6c0c6d067d63.png)

![Screenshot_37](https://user-images.githubusercontent.com/43518434/55579928-b12fa780-5719-11e9-99aa-c6dcbac4cf31.png)

**What should happen:**

Once he kills you and put you to spirit realm you need to get a quest completed. Shown in video how it should look like.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/d3Lidq7.jpg)

fixed with next update
