### ISSUE TITLE
[Quest] Into the World of Spirits ID 11333 - Howling Fjord

### ISSUE THREAD

**Issue by Felfyre** [WoWManiaUK/Blackwing-Lair#1355]
**Links:**
https://www.wowhead.com/quest=11333/into-the-world-of-spirits
https://www.wowhead.com/item=33635/reagent-pouch
from WoWHead or our Armory

**What is happening:**

No reagent pouches spawned

**What should happen:**

There should be punches spawned around both wrecks. According to WoWHead comments, multiple spawns are the norm

**Comment by Echinaceax** [comment]
![under](https://user-images.githubusercontent.com/39439201/55650206-62e7da80-57e5-11e9-97e6-b4822cf22655.jpg)

**Comment by Felfyre** [comment]
This is dev or live version?

**Comment by Echinaceax** [comment]
> This is dev or live version?

Sorry Dev :)

**Comment by Rushor** [comment]
all stuff that is fixed is on "dev" in first place :) Once the issue is closed it is on live version
