### ISSUE TITLE
[Quest] Danger! Explosives! ID 11218 - Howling Fjord 

### ISSUE THREAD

**Issue by Felfyre** [WoWManiaUK/Blackwing-Lair#1358]
**Links:**
https://www.wowhead.com/quest=11218/danger-explosives
https://www.wowhead.com/item=33188/whisper-gulch-ore-fragment
https://www.wowhead.com/item=33187/whisper-gulch-gem
from WoWHead or our Armory

**What is happening:**

Ores and gems spawn after using quest item, howet they almost instantaneously despawn, leaving you only time to interact with one of the 3-4 piles

**What should happen:**

Ore and gems piles should stay for enough time for a player to interact with all piles

**Comment by Rushor** [comment]
no longer despawn that fast
