### ISSUE TITLE
[Spell] Warlock Buff Spell

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1359]
**Links:**
https://www.wowhead.com/spell=183582/dark-intent
from WoWHead or our Armory

**What is happening:**
doesnt put the 3% buff on the warlock only puts it on the target

**What should happen:**
Should put a buff on the target and the warlock for 3% haste

**Comment by Keader** [comment]
Fixed.

**Comment by Dranah** [comment]
Haste is now added to both targets.
However, periodic crits do not proc the intended buff (85759) that should increase the other persons periodic damage and healing by 3% (on caster) or 1% (on party)

**Comment by Keader** [comment]
Rain of fire is not damage over time.

**Comment by Keader** [comment]
Has no issue here, cant crit is the problem.
Because proc only can happen when a dot crit.

**Comment by Keader** [comment]
I said that was not problem here, but... since nobody test in wow mania, caused by crit, i will left it open o.o
