### ISSUE TITLE
[Item] Westguard Command Insignia ID 33311 - Howling Fjord 

### ISSUE THREAD

**Issue by Felfyre** [WoWManiaUK/Blackwing-Lair#1360]
**Links:**
https://www.wowhead.com/item=33311/westguard-command-insignia

from WoWHead or our Armory

**What is happening:**
Right clicking the item does not dismiss the Westguard Sergeant

**What should happen:**
Right clicking should dismiss the Westguard Sergeant

**Comment by Rushor** [comment]
This bug concerns:

Westguard Command Insignia, Lafoo's Bug Bag, Jaloot's Favorite Crystal, Moodle's Stress Ball, Summon Dajik the Wasp Hunter

all fixed now.

**Comment by Rushor** [comment]
first click spawn https://i.imgur.com/XjCfFeT.jpg

second click dismiss https://i.imgur.com/PsW7YyZ.jpg
