### ISSUE TITLE
Item Mezhen's Writings ID 34090 - Howling Fjord 

### ISSUE THREAD

**Issue by Felfyre** [WoWManiaUK/Blackwing-Lair#1361]
**Links:**
https://www.wowhead.com/item=34090/mezhens-writings#starts

From WoWHead or our Armory

**What is happening:**

Item cannot be used, even though it is correct faction version

**What should happen:**
Should be able to Right click to take quest

**Comment by Rushor** [comment]
okay, the quest was disabled for unkown reason. will remove that.

**Comment by Rushor** [comment]
in order to accept you first need to complete quest: 11235

**Comment by Rushor** [comment]
![I](https://i.imgur.com/N0uBTMn.jpg)
