### ISSUE TITLE
Quest Jack Likes His Drink ID 11466 - Howling Fjord 

### ISSUE THREAD

**Issue by Felfyre** [WoWManiaUK/Blackwing-Lair#1362]
**Links:**
https://www.wowhead.com/quest=11466/jack-likes-his-drink
https://www.wowhead.com/npc=24639/olga-the-scalawag-wench

from WoWHead or our Armory

**What is happening:**

Olga does not give the option to bribe her in her gossip window

**What should happen:**

Olga should give you the option to bribe her so she gives Jack Adam's a drink and you can loot him

**Comment by Echinaceax** [comment]
not fix
