### ISSUE TITLE
[Quest] The Way to His Heart... ID 11472 - Howling Fjord 

### ISSUE THREAD

**Issue by Felfyre** [WoWManiaUK/Blackwing-Lair#1363]
**Links:**
https://www.wowhead.com/quest=11472/the-way-to-his-heart#comments

from WoWHead or our Armory

**What is happening:**

No schools of tasty reef fish in the area. Just 2 schools of imperial manta rays
Killed the few sharks in the area - no drop. Dunno if that's just bad luck or if it's not in their loot table. Supposed to be a 16% drop

**What should happen:**

There should be schools of tasty reef fish to use quest item on
The few sharks in the area should drop tasty reef fish as well

**Comment by Rushor** [comment]
there are several spawns for it: http://cata.cavernoftime.com/?object=186949 

but the object needs to spawn after use. that is missing currently.

**Comment by Echinaceax** [comment]
completed this way myself just now 
https://www.wowhead.com/quest=11472/the-way-to-his-heart#videos:id=1783
