### ISSUE TITLE
Quest The Clutches of Evil ID 11157 - Howling Fjord 

### ISSUE THREAD

**Issue by Felfyre** [WoWManiaUK/Blackwing-Lair#1366]
**Links:**
https://www.wowhead.com/quest=11157/the-clutches-of-evil
from WoWHead or our Armory

**What is happening:**

Was unable to take quest. Captain Adam's did not have this for me. A comment on the quest by 6fire9 (see comments on the WoWHead link) listed this as the first part of a chain, however I did all the later quests in the first chain without having this

**What should happen:**
Make quest available

**Comment by Kitzunu** [comment]
You need to hand in quest 11501 for this quest to be available.
![image](https://user-images.githubusercontent.com/24550914/58670451-66a86100-833f-11e9-933b-3407093b6521.png)
