### ISSUE TITLE
[Item] Cleansing Vial - ID 23361-  Hellfire Peninsula.

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#1367]
**Links:**

[Cleansing Vial](https://www.wowhead.com/item=23361/cleansing-vial)
[Aggonis](https://www.wowhead.com/npc=17000/aggonis)
**What is happening:**
[Cleansing Vial](https://www.wowhead.com/item=23361/cleansing-vial) spawn 2x [Aggonis](https://www.wowhead.com/npc=17000/aggonis)

**What should happen:**

[Cleansing Vial](https://www.wowhead.com/item=23361/cleansing-vial) spawn 1x [Aggonis](https://www.wowhead.com/npc=17000/aggonis)

**Comment by Rushor** [comment]
only one spawn now
