### ISSUE TITLE
[NPC/Vendor] Logistics Officer Ulrike - ID 17657 - Hellfire Peninsula

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#1368]
**Links:**

[Logistics Officer Ulrike ](https://www.wowhead.com/npc=17657/logistics-officer-ulrike)

**What is happening:**

Do not sell items

**What should happen:**

Need to sell items

**Comment by Kitzunu** [comment]
Delete cache before testing
