### ISSUE TITLE
[Quest] The Scrapbot Construction Kit ID 13843 - Storm Peaks

### ISSUE THREAD

**Issue by Felfyre** [WoWManiaUK/Blackwing-Lair#1369]
**Links:**
https://www.wowhead.com/quest=13843/the-scrapbot-construction-kit
from WoWHead or our Armory

**What is happening:**

Works, but is available to non-engineers

**What should happen:**

Should only be available to engineers

**Comment by Kitzunu** [comment]
Try now, very unsure of this :D

Should only be able to pick up if you have Engineering

Dont forget to delete your cache :)

**Comment by Felfyre** [comment]
If you mean me, I can't, I had ti turn quest in to see if it worked

**Comment by Kitzunu** [comment]
Not you :)
