### ISSUE TITLE
[Quest] Losing Your Tail - Gilneas - 24616

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#1370]
**Links:**
https://www.wowhead.com/quest=24616/losing-your-tail
https://www.wowhead.com/npc=37953/dark-scout#comments
from WoWHead or our Armory

**What is happening:**
The - to be killed - Dark Scout isn't present.

**What should happen:**

The Dark Scout should be present.

Pitfourth: worgen warlock

**Comment by giles1508** [comment]
got to this point last night @Rushor   and there is no dark scout that attacks you so something has regressed

**Comment by Rushor** [comment]
yeah it's phasing

**Comment by Rushor** [comment]
@giles1508 pm me pls, i need to check in which phase the player is at that point of the quest :)

**Comment by Rushor** [comment]
If you are in phase 186 and if you have the quest active, the event will start close to the area in the video

![](https://i.imgur.com/Qw1HzRT.jpg)
![](https://i.imgur.com/zoPFgIq.jpg)
![](https://i.imgur.com/LjQujzU.jpg)
