### ISSUE TITLE
Quest Slaves of the Stormforged ID 12957 - Storm Peaks 

### ISSUE THREAD

**Issue by Felfyre** [WoWManiaUK/Blackwing-Lair#1371]
**Links:**
https://www.wowhead.com/quest=12957/slaves-of-the-stormforged
from WoWHead or our Armory

**What is happening:**

Postive responses from mechagnomes do not give quest credit

**What should happen:**

Positive responses from mechagnomes should give quest credit

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/7Oa0O99.png)
