### ISSUE TITLE
NPC King Jokkum ID 30105 - Storm Peaks

### ISSUE THREAD

**Issue by Felfyre** [WoWManiaUK/Blackwing-Lair#1375]
**Links:**
https://www.wowhead.com/npc=30105/king-jokkum#starts
https://www.wowhead.com/quest=12924/forging-an-alliance#comments

from WoWHead or our Armory

**What is happening:**

King Jokkum is hostile when he is not supposed to be, the quest linked above sends you to talk to him

**What should happen:**

King Jokkum should not be hostile

**Comment by Kitzunu** [comment]
This has nothing to do with the NPC.

The reason for this is because your Reputation is Hated with Sons of Hodir.
You need to be at least neutral with them to be able to hand this quest in.
