### ISSUE TITLE
[Quest]  Preparations - Gilneas - 24628

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#1378]
**Links:**
https://www.wowhead.com/quest=24628/preparations
https://www.wowhead.com/item=50017/moonleaf
https://www.wowhead.com/npc=37873/vassandra-stormclaw
from WoWHead or our Armory

**What is happening:**

The plants doesn't loot

**What should happen:**

Plants, Moonleaf should loot.

Pitfourth, worgen warlock

ps. Vassandra Stormclaw looks to be on the wrong place. According to wowhead.

**Comment by Rushor** [comment]
Tested with Giles, item is added now. works
