### ISSUE TITLE
[Quest] - Liberation Day - Gilneas - 24575

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#1379]
**Links:**
https://www.wowhead.com/quest=24575/liberation-day
https://www.wowhead.com/object=201775/ball-and-chain
https://www.wowhead.com/npc=37783/lorna-crowley
from WoWHead or our Armory

**What is happening:**
Slaves are chained to a ball, the ball doesn't react to the key.

**What should happen:**
Slaves who are chained to a ball must be freed by using keys loot from guards. Looting goes great, about 70% but the sprankling balls who are reacting an mouse over, doesn't react to the keys.

Pitfourth: worgen warlock

**Comment by Rushor** [comment]
this will be a nice one. going to fix it :)

**Comment by giles1508** [comment]
just to add to this,   the mobs you kill for the keys are giving ashtongue deathsworn rep

**Comment by Rushor** [comment]
okay double spawn removed

**Comment by Rushor** [comment]
also the item 49881 need to drop for 1-3 random pieces per mob

**Comment by Rushor** [comment]
![](https://i.imgur.com/N6IXcbX.jpg)
![](https://i.imgur.com/9U4Nrug.jpg)
