### ISSUE TITLE
[Quest] Big Gulp

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#138]
Fishing daily quest in stormwind Big Gulp
https://www.wowhead.com/quest=26488/big-gulp#comments

I tried this 30 times and no success, chances should be around 25-30% to get Monkfish, and from that should be 5-10% chance to get locket, but nothing after 30 attempts so I give up.

![fishing valley of heroes](https://user-images.githubusercontent.com/20323863/49091317-d5591480-f25f-11e8-9c34-ab5999641fd3.png)

You can see that I have active quest, location Valley of heroes, skill was at the end 100 in fishing, and you can see all I got for 30 attempts in this location.

**Comment by wow-mania** [comment]
Chance is 7% only. Fixed.
