### ISSUE TITLE
[Dungeon]  Scarlet Monastery - Tirisfal Glades

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#1380]
**Links:**
[Scarlet Renegade](http://wowhead.com/?npc=44736) - ID 44736 - Scarlet Monastery: Graveyard
[Scarlet Renegade](http://wowhead.com/?npc=44739) - ID 44739 - Scarlet Monastery: Library
[Scarlet Renegade](http://wowhead.com/?npc=44742) - ID 44742 - Scarlet Monastery: Armory
[Scarlet Renegade](http://wowhead.com/?npc=44751) - ID 44751 - Scarlet Monastery: Cathedral

[Joseph the Awakened](http://wowhead.com/?npc=44728) - ID 44728- Scarlet Monastery: Graveyard
[Joseph the Awakened](http://wowhead.com/?npc=44738) - ID 44738- Scarlet Monastery: Library

[High Inquisitor Whitemane](https://www.wowhead.com/npc=3977/high-inquisitor-whitemane) - ID 3977 - Scarlet Monastery: Cathedral

Scarlet Renegade and Joseph the Awakened are missing. need to be add. 
 
On the "first boss" in Scarlet Monastery: Cathedral , when u fight Scarlet Commander Mograin
the door behind him need to be closed. after hi die. the door need to open and [High Inquisitor Whitemane](https://www.wowhead.com/npc=3977/high-inquisitor-whitemane) need to get out. but the door is always open. and when she need to go out the door close and she goes through it

**Comment by Rushor** [comment]
door is only open midfight now. questgiver and Scarlet Renegade added. (i have them set to freindly faction)

![I](https://i.imgur.com/7erldCK.jpg)
![I](https://i.imgur.com/VxMT2DI.jpg)

Cheers.
