### ISSUE TITLE
[Quest] Stranded at the Marsh - Gilneas - 24468

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#1382]
**Links:**
https://www.wowhead.com/quest=24468/stranded-at-the-marsh
from WoWHead or our Armory

**What is happening:**
The npc's who are waiting rescue ar not able to communicate.

**What should happen:**

You should be able to rescue these men.

Pitfourth: worgen warlock

**Comment by Rushor** [comment]
todo:

respawn all creatures
add phasing
add sparring
add questcredit

**Comment by Rushor** [comment]
![](https://i.imgur.com/eaMvOhI.jpg)
![](https://i.imgur.com/RHloGbO.jpg)
