### ISSUE TITLE
[Quest]  The Battle for Gilneas City - Gilneas - 24904

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#1385]
**Links:**
https://www.wowhead.com/quest=24904/the-battle-for-gilneas-city
from WoWHead or our Armory

**What is happening:**
Nothing (wrong phasse)

**What should happen:**

There should be a battle.

Pitfourth worgen warlock

**Comment by sarahkay88** [comment]
I did this on every wogen class possible n it worked has intended. So either it's a new bug or something was done wrong. I'll make a wogen n double check

**Comment by sarahkay88** [comment]
unable to check since no npc's offer training any more

**Comment by Echinaceax** [comment]
unable to check since no npc's offer training any more

they broken again too?

**Comment by sarahkay88** [comment]
Yup

**Comment by Frostmanx** [comment]
The battle is not happening but how ever you get the quest auto-completed. But npc which is required to hand in the quest is in another phase (187) npc=38611

![WoWScrnShot_052819_205857](https://user-images.githubusercontent.com/50195620/58491154-1f2da380-818c-11e9-89f1-6fba9631a096.jpg)

**Comment by giles1508** [comment]
comfirmed,   im currently on this part  if testing and the NPC isnt here,

**Comment by Rushor** [comment]
creature added

**Comment by Echinaceax** [comment]
still has issues it seems @Rushor

**Comment by gamer100** [comment]
When the phase is  set, the npc Krennan Aranas teleport  you  to  gilnaes  and  quest is complete after that, then the npc is there  to continue the chain. Just complete the quest keep  you unpahsed
