### ISSUE TITLE
[NPC] Nuri <Guild Vendor> (Issue1) - Exodar 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1388]
**Links**
https://www.wowhead.com/npc=51501/nuri#sells:0+2

![nuri p1](https://user-images.githubusercontent.com/39439201/55743474-b0a55280-5a32-11e9-91d3-4ccefde4342d.jpg)
![nuri p2](https://user-images.githubusercontent.com/39439201/55743479-b307ac80-5a32-11e9-9724-06261509e067.jpg)

**What is happening:**

- [ ] Seems that these are unlocked before they should be (check link) 
- Without required guild lvl

**What should happen:**
- shouldn't be available until guild level reaches correct status (see link)

**Comment by Kitzunu** [comment]
I have added conditions to all items to only show when you get the required reputation and achievement for the guild.

if you want to test the fix the faction id for guild is = 1168

so
```
.mod rep 1168 neutral/friendly/honored/revered/exalted
```
and for achievement
```
.achievement add ID
```

Remember all of the items require a Reputation and an achievement
