### ISSUE TITLE
[Quest] Diggin' For Worms

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#139]
Fishing daily quest in stormwind Diggin' For Worms
https://www.wowhead.com/quest=26420/diggin-for-worms

I had 30 attempts here and I give up, I did had active quest, I used worm bait, I was located in olivia`s pound and my skill level was at the end 131 in fishing and you can see all catch I had in those attempts on my addon.

![fishing olivia pound](https://user-images.githubusercontent.com/20323863/49091422-249f4500-f260-11e8-9b07-f48b3e931e8d.png)

**Comment by wow-mania** [comment]
Chance is only 3%. Fixed but you need to fish on average about 33 time to get 1.

**Comment by TheSale** [comment]
Daily fishing quests are doable, they work, now, I do get objective items, however, it does not matter where I fish, I will get items anyway, and they even if I have enough to complete quest I still keep getting them from fishing. It is not that important to change at this moment, but would be really nice. I am happy that works. I wont comment on other quests this is enough.
GJ Janitor! :)
