### ISSUE TITLE
[Mount] Winged Guardian 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1395]
**Links:**
mount - https://www.wowhead.com/item=69846/winged-guardian
video - https://youtu.be/PIq8MZM5zQo

**What is happening:**
- Mount bugs when you land 
- Mount is slow when you land on ground - 60% 

**What should happen:**
- It should bug when landing on ground 
- Should be 100% ground mount and 310 flight mount 

**Reproduce** 
- Land - dismount - and mount again 

note: it seems to not happen all the time

**Comment by Keader** [comment]
Mount work.
It's based in your Riding skill level.

**Comment by Echinaceax** [comment]
> Mount work.
> It's based in your Riding skill level.

yes mount works but not as intended.

i just noticed you can reproduce also by logging out mounted and log back in and run on the ground :)

**Comment by Keader** [comment]
Now fixed.

**Comment by Echinaceax** [comment]
thanks  @Keader i'll retest when finished what im doing :)

**Comment by Echinaceax** [comment]
fixed thanks :)
