### ISSUE TITLE
[Spell/pala] holy-power - 85247

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1396]
**Links:**
https://www.wowhead.com/spell=85247/holy-power

https://www.wowhead.com/spell=20473/holy-shock
https://www.wowhead.com/spell=173379/holy-radiance

**What is happening:**
- [ ] Holy Shock and Holy Radiance

1. Sometimes works as desired showing a charge of Holy Power and applying the desired effect and modifiers for the spells that require Holy Power Charges
2. Sometimes doesn't grant a charge of holy power but displays the Abilities that require a Charge as able to use but not working due to no charges being available for use.
3. Grants a Charge of Holy power But then instantly removes the charge rendering the abilities that use a charge useless.

**What should happen:**
Abilities used for Examples above Should behave, scale and modify spell effects  as described in their links above.

please note : that these pala spells are affected by this issue #1397 #1399 
(i will close these spells as bagi said its not the spells thats the main issue here is the broken holy power)

main tester @bagi84

**Comment by Keader** [comment]
Fixed.

**Comment by Keader** [comment]
But remember: Each 10 sec, 1 holy power is removed if player is out of combat.

**Comment by Dranah** [comment]
Works as intended, holy radiance only generates HP with holy talent "tower of radiance".
