### ISSUE TITLE
[Talent/pala] Tower of Radiance -88855 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1397]
**Links:**

https://cata-twinhead.twinstar.cz/?spell=88855

**What is happening:**
- [ ] The Talent 'Tower of Radiance' Not granting Charges of Holy Power from the spells stated in the tooltip.

**What should happen:**
- should grant holy power as stated in tool tip

main tester @bagi84

**Comment by Keader** [comment]
why you closed?

**Comment by Echinaceax** [comment]
> why you closed?

because bagi explained that its the holy power that is the issue #1396
