### ISSUE TITLE
[Spell/pala] Word of Glory 85673

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1398]
**Links:**

https://cata-twinhead.twinstar.cz/?spell=85673

**What is happening:**
- [ ] Word of Glory Not scaling with the amount of Holy Power Charges available but removing all charges when used. 

**What should happen:**
Abilities used for Examples above Should behave, scale and modify spell effects  as described in their links above.

main tester @bagi84

**Comment by Dranah** [comment]
i've already reported dis one
https://github.com/WoWManiaUK/Blackwing-Lair/issues/936
