### ISSUE TITLE
[Quest] Young and Vicious

### ISSUE THREAD

**Issue by Zunrin** [WoWManiaUK/Blackwing-Lair#14]
**How it should work:**
A raptor (Swiftclaw) should spawn and run around the island when you accept the quest and you need to use the rope on him.

**How it currently works:**
Swiftclaw does not spawn.

Links:
http://www.wowhead.com/quest=24626/young-and-vicious
http://www.wowhead.com/npc=38002/swiftclaw
http://www.wowhead.com/npc=37989/swiftclaw
(I guess one id corresponds to the NPC before you use the rope, and the other once you use the rope)

**Comment by Zunrin** [comment]
Still no sign of Swiftclaw.

**Comment by fvicaria** [comment]
It is there. Maybe phase issue.

**Comment by Zunrin** [comment]
The quest is now doable.

A few things could be tweaked:
- When using the item, you dont instantly mount the raptor, instead a usable raptor appears where you stand (right clicking it makes you mount it)
- The animation is a bit weird
![image](https://user-images.githubusercontent.com/23452669/37607265-e1527a54-2b97-11e8-8072-52afe7c8e6fc.png)
- The area to turn the raptor in seems a little small

**Comment by fvicaria** [comment]
Will be as-is for now.
