### ISSUE TITLE
[Spell/pala] Tower of Radiance

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1400]
**Links:**

https://cata-twinhead.twinstar.cz/?spell=53563

**What is happening:**
- [ ] Beacon of Light Cannot Generate spells using the Talent tree Ability 'Tower of Radiance' due to once the described heals are used on a Beacon of light Target they Crash the test server.

**What should happen:**
shouldnt crash the server, thats naughty :)

main tester @bagi84

**Comment by Echinaceax** [comment]
has this one been retested @bagi84 ?

**Comment by Keader** [comment]
Why closed?

**Comment by Echinaceax** [comment]
> Why closed?
Coz you said this one was fixed last week :)
so i closed this one that i re did

**Comment by Keader** [comment]
beacon of light is fixed, but Tower of Radiance no.

**Comment by Keader** [comment]
Fixed too. :)

**Comment by Keader** [comment]
Now fixed in dev xD
