### ISSUE TITLE
[NPC] Blood Elf Orphan -22817-  ( 2 issues) - Children's week 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1403]
_Issue 1_ (tested in DEV)
children's week

**Links:**
Event - https://www.wowhead.com/npc=22817/blood-elf-orphan#starts
quest 1 - https://www.wowhead.com/quest=10945/hchuu-and-the-mushroom-people
quest 2 - https://www.wowhead.com/quest=10951/a-trip-to-the-dark-portal

**What is happening:**

- [x] Hch'uu and the Mushroom People (auto completed)
- [x] A Trip to the Dark Portal (auto completed) 

**What should happen:**
- no quest should auto complete when they have specific instructions 

**A Trip to the Dark Portal**

> Take your orphan, Salandria, up the steps of the Stair of Destiny to stand before the Dark Portal in Hellfire Peninsula. Make sure to call for her if she is not present when you arrive.

**Hch'uu and the Mushroom People**

> Take your orphan, Salandria, to Sporeggar in Zangarmarsh. Make sure to call for her if she is not present when you arrive. Then, speak with Hch'uu.

Also note: i think the Orphans are missing their gossip "Ooo thats pretty" etc...
they are not showing text in chat

**from video**

![orphan gossip](https://user-images.githubusercontent.com/39439201/55876770-b7e67080-5b98-11e9-85c1-e7fabf48fe2b.jpg)

**Comment by Echinaceax** [comment]
New findings 

After completing https://www.wowhead.com/quest=10953/visit-the-throne-of-the-elements
Take your orphan, Salandria, to the Throne of the Elements in Nagrand. Make sure to call for her if she is not present when you arrive. Then, speak with Elementalist Sharvak.

- I am not given anymore follow up quests from the Orphan

- Wrong quest order too 
quest order here https://www.wowhead.com/npc=22817/blood-elf-orphan#starts

**Comment by Echinaceax** [comment]
@Rushor - still got some issues 

dark portal still auto completes (use diff toon) 
![comp1](https://user-images.githubusercontent.com/39439201/56065505-4f081f80-5d75-11e9-9268-2c79f62b2222.jpg)

![comp2](https://user-images.githubusercontent.com/39439201/56065535-6941fd80-5d75-11e9-912d-a12b3795029c.jpg)

**Comment by mfranca0009** [comment]
Both quests listed are now properly triggering at the proper areas, and are not auto-completing. Also, the Blood Elf Orphan has the proper texts and emote texts triggering for the specified quests above.
