### ISSUE TITLE
[NPC] Orphan Matron Battlewail -51989- Children's week 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1406]
Tested in PTR (With event started)
**Links:**
npc - https://www.wowhead.com/npc=51989/orphan-matron-battlewail
event - https://www.wowhead.com/quest=172/childrens-week

![orc](https://user-images.githubusercontent.com/39439201/55842119-6dcaa400-5b32-11e9-9205-1e366d736a7b.jpg)

**What is happening:**
- She doesnt offer the start quest 

**What should happen:**
- She should offer start quest to give the whistle 
https://www.wowhead.com/item=18597/orcish-orphan-whistle

please note: that we cant test Orcish Orphan without the whistle :)

**Comment by Rushor** [comment]
she sould stat that quest: https://www.wowhead.com/quest=172/childrens-week

**Comment by Echinaceax** [comment]
@Rushor i know :)

**Comment by Echinaceax** [comment]
@Rushor - still not sorry

**Comment by mfranca0009** [comment]
WoWhead is incorrect, look at cata.cavernoftime:
http://cata.cavernoftime.com/npc=14451#starts

Should be entry 14451, not 51989. Same NPCs but different entries.

**Comment by mfranca0009** [comment]
All set, now offers the Children's Week start quest 👍

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 

![image](https://user-images.githubusercontent.com/39439201/108500145-a18abf00-72af-11eb-8f71-ee7d6885ed3b.png)
