### ISSUE TITLE
[NPC] Ormak Grimshot <Hunter Trainer> Orgrimmar

### ISSUE THREAD

**Issue by kenobii** [WoWManiaUK/Blackwing-Lair#1408]
**Links:**

![bug](https://user-images.githubusercontent.com/49500938/55920673-15e27a80-5bd0-11e9-970a-c620e6cc6b23.jpg)

**What is happening:**

I can not train hunting, leatherwork and skinning.

**What should happen:**

Coaches should open training options but I can not access with my character.

**Comment by Echinaceax** [comment]
https://www.wowhead.com/npc=3352/ormak-grimshot

he is a hunter trainer not a professions trainer.

Ask a guard in Orgrimmar for professions then pick leaver working and skinning and open your map (a red flag with appear)

**Comment by kenobii** [comment]
But I can not train with the class coaches. I click on the option, but nothing happens.

**Comment by kenobii** [comment]
![image](https://user-images.githubusercontent.com/49500938/55922974-e9336080-5bd9-11e9-86ed-06594900f863.png)
 
These give no choice.

**Comment by Echinaceax** [comment]
@Kitzunu 
very odd because me and bagi both trained here a few weeks ago 
so something messed up recently in last update)

**Comment by Kitzunu** [comment]
@echinaceax
Go to dev and see if it is bugged, if it is confirm it and if not close it :P 

I doubt it is bugged too, but havent checked 👍

**Comment by Echinaceax** [comment]
@Kitzunu  im checking on PTR atm and yes its bugged (cant click on training) 

![org trainer](https://user-images.githubusercontent.com/39439201/55958478-02cfb900-5c69-11e9-95df-5c7572bdf579.jpg)

**Comment by sarahkay88** [comment]
deffo a new bug it worked when I checked the npc in Ogrimmar n I stood next to an hunter has he trained.

**Comment by Echinaceax** [comment]
> deffo a new bug it worked when I checked the npc in Ogrimmar n I stood next to an hunter has he trained.

And bagi actually use the trainer for his hunter spell test

**Comment by kenobii** [comment]
I tried again, but to no avail. Ormak gives the option, but when I click nothing happens.
Will it be a problem of my character?

**Comment by sarahkay88** [comment]
No anvil for what? You dont need an a vile to receive hunter traininh

**Comment by sarahkay88** [comment]
I totally misread that. Its only fixed in dev it hasn't been updated to ptr yet. They will do it soon

**Comment by kenobii** [comment]
When I click on "i have come for training" nothing happens.

**Comment by kenobii** [comment]
Ah okay. Thank you.

**Comment by Echinaceax** [comment]
@kenobii - i see that the fixed in dev 
so will be implemented on PTR soon
