### ISSUE TITLE
[Quest] Razormaw

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#141]
when summoned they come with a delay from nowhere instantly kill lvl 21 player 
![2 mobs](https://user-images.githubusercontent.com/20323863/49106020-51fcea80-f282-11e8-8107-6baebaf9c6c8.png)
![kill](https://user-images.githubusercontent.com/20323863/49106032-5b865280-f282-11e8-93be-0c714cfd043a.png)

**Comment by wow-mania** [comment]
Works fine.

**Comment by TheSale** [comment]
I tested now 3 times and he dont spawn

**Comment by TheSale** [comment]
video
https://mega.nz/#!RNNT2IqK!0bw93Zyk2QQ57550gbnLu5sbTSNH6sIuHxZyWx9glvI

**Comment by TheSale** [comment]
https://mega.nz/#!0QtCUQ6R!x_3J8RILm93rI5bPt5keFMl0K_4gcHLq3DQZcpTFIm8
I was not lazy so I tested it again 2 times, just to point out it is still issue with that quest, but its not important almost at all for starting server

**Comment by gantor2** [comment]
Consumed dragonbones - ID 24221  was used but did not trigger the even to spawn Razormaw - ID 17592 Tried with 2 attempts
