### ISSUE TITLE
[NPC] Thuwd <Skinning Trainer> - Orgrimmar

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1410]
**Links:**
https://www.wowhead.com/npc=7088/thuwd

![thewd](https://user-images.githubusercontent.com/39439201/55960769-b89d0680-5c6d-11e9-8e80-17ebb3b941ca.jpg)

**What is happening:**
- Inactive 

**What should happen:**
- Should offer skinning

reported by @kenobii

**Comment by sarahkay88** [comment]
again was working the other week
