### ISSUE TITLE
[Quest /Priest] Healing the Wounded -10072-  Sunstrider Isle

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1424]
**Links:**
Quest - https://cata-twinhead.twinstar.cz/?quest=10072
npc -  https://cata-twinhead.twinstar.cz/?npc=15284

![healing the wounded](https://user-images.githubusercontent.com/39439201/56098074-cb793a80-5efc-11e9-9c97-46a0820d58d1.jpg)

**What is happening:**
- Healed the "Wounded Outrunners"
- No quest credit 

**What should happen:**
- Should get quest credit when you heal the Wounded Outrunners

note: i did kinda report it here https://github.com/WoWManiaUK/Blackwing-Lair/issues/23#issuecomment-454104660 but at the time couldnt find any reference via wowhead

**Comment by Kitzunu** [comment]
fixed
