### ISSUE TITLE
[Object] PX-238 Winter Wondervolt -180797- Winter Veil - Eversong Woods

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1429]
(Horde test)

**Links:**
object - https://cata-twinhead.twinstar.cz/?object=180797
quest - https://www.wowhead.com/quest=8828/winters-presents
npc  - https://cata-twinhead.twinstar.cz/?npc=15732

![doesnt](https://user-images.githubusercontent.com/39439201/56100326-962e1600-5f17-11e9-9ccc-bb34ca2c21cd.jpg)

**What is happening:**
- Object not working 

**What should happen:**
- Should port to orgrimmar

**Comment by sarahkay88** [comment]
same has the one in Exodar for alliance

**Comment by Echinaceax** [comment]
misunderstood the quest :)
