### ISSUE TITLE
[Race] Can`t create worgen or goblin

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#143]
I wanted to test goblin and to see does goblin zone works and I actually can`t create ether of them....
I first thought that my game is not updated even if I use launcher, so I run it again, and check is everything open for changes (read only disabled) and it is, I change name of wow mania wotlk folder, and run launcher again and same thing, I cant create them! And it offer to upgrade to cataclysm that when I click redirect me to wow mania forum. 
Version that is displayed for me in client is 1.0.2 alpha
![no gob req cata](https://user-images.githubusercontent.com/20323863/49125195-77f4b000-f2bf-11e8-9cf7-06408217e1e2.png)

**Comment by wow-mania** [comment]
Not an issue. Account needs upgrade.
