### ISSUE TITLE
[NPC]  Marniel Amberlight <Innkeeper>  ( Hallow's End ) - Eversong Woods

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1430]
**Links:**
https://cata-twinhead.twinstar.cz/?npc=15397

![clickkk](https://user-images.githubusercontent.com/39439201/56100717-8ebd3b80-5f1c-11e9-8134-7321eddae93d.jpg)

**What is happening:**
- Cant click "trick or treat" 

**What should happen:**
- Should be able to click on trick or treat when event is on

**Comment by Echinaceax** [comment]
@Kitzunu - no trick or treat option at all now :)

**Comment by Kitzunu** [comment]
Turn on the event...

**Comment by Kitzunu** [comment]
.event start 12

**Comment by Echinaceax** [comment]
![its on](https://user-images.githubusercontent.com/39439201/56305952-9d386c80-6141-11e9-9a9b-83802a7673b6.jpg)

**Comment by Kitzunu** [comment]
Oh thought this was another issue

**Comment by Kitzunu** [comment]
Mb
