### ISSUE TITLE
[quest=9798]  [Blood Elf Plans] - Northshire Valley

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1432]
**Links:**
https://www.wowhead.com/quest=9798/blood-elf-plans
from WoWHead or our Armory

**What is happening:**
This quest drops in human start zone in Northshire Valley
[quest=9798]
[npc=50039] Goblin Assassin droped the quest

**What should happen:**
This quest should not drop here

**Comment by Kitzunu** [comment]
Fixed, but I dont have access to Dev atm.
Waiting to get that back :D

**Comment by Kitzunu** [comment]
Fixed in dev
