### ISSUE TITLE
[Object] Apple bob - Azure Watch - Old hallows eve event

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1433]
**Links:**

https://www.wowhead.com/object=180523/apple-bob

**What is happening:**

When clicked you get splashed by water

**What should happen:**

When clicked you should receive 5 bobbing apples - https://www.wowhead.com/item=20516

**Comment by Kitzunu** [comment]
@Rushor This seems to be some kind of range issue.

If I stand in the Apple bob thingy I you get the apples, but if you stand a bit further away you wont get any apples

**Comment by Echinaceax** [comment]
@sarahkay88 - same as horde
but i could get 60 apples ...

**Comment by sarahkay88** [comment]
I was stood at the side right next to it n no apples just the water splash 😂

**Comment by Echinaceax** [comment]
> I was stood at the side right next to it n no apples just the water splash

me too :)
