### ISSUE TITLE
[NPC] Azuremyst Peacekeepers - Azure Watch 

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1435]
**Links:**

https://www.wowhead.com/npc=51905/azuremyst-peacekeeper

**Whats Happening:**
So I clicked these npc in Azure watch and they only display the following message
![World of Warcraft 15_04_2019 14_58_28](https://user-images.githubusercontent.com/42302580/56138714-50ad2f80-5f8f-11e9-921b-ee75a508dbbe.png)
I didn't even ask about tailoring

**What should happen:**
When clicked these npcs should direct the play to several different locations
i.e profession traning
class training
innkeeper ect

**Comment by sarahkay88** [comment]
FYI is message is wrong by the way since npc valn https://www.wowhead.com/npc=47431/valn
provides you with tailoring.

**Comment by Rushor** [comment]
merged those 2 issues. it's almost the same https://github.com/WoWManiaUK/Blackwing-Lair/issues/1134.
