### ISSUE TITLE
Event starting at wrong times

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Blackwing-Lair#1436]
Several seasonal events starts right after a restart/build
![image](https://user-images.githubusercontent.com/24550914/56139520-5740a480-5f99-11e9-8aca-5f91d0ad2f46.png)

**Comment by sarahkay88** [comment]
I thought this was so we could test that they worked.

**Comment by Kitzunu** [comment]
@sarahkay88 You might be correct, though since I have not seen anything about that I thought I would report it :P

**Comment by Echinaceax** [comment]
@sarahkay88 - they are for testing :) but they are all active at the same time lol

**Comment by sarahkay88** [comment]
well not all for me - I cannot receive the xmas ones they just have a grey ! mark lol

**Comment by Echinaceax** [comment]
> Several seasonal events starts right after a restart/build

yes all active at the same time is a bit much :)

**Comment by sarahkay88** [comment]
spread the love instead of trying to test al,l designate one people to test a certain one, instead of trying to test all of them :)

**Comment by Dranah** [comment]
event issues are no priority at the current state

**Comment by Echinaceax** [comment]
### Update on this 

from live client 1.1.0
event times are messed up / calender

Darkmoon never comes on when calender says (GM has to activate manually each month)

MANY Events are still broken, so no rush to fix timer :)

**Comment by Echinaceax** [comment]
closing this for now, we see if the fix #5058 has any effect on this
