### ISSUE TITLE
[NPC] Magistrix Nizara <Silvermoon City Quartermaster>

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1438]
**Links:**
npc - https://www.wowhead.com/npc=50484/magistrix-nizara
sale item - https://www.wowhead.com/item=67535/silvermoon-satchel

![rev](https://user-images.githubusercontent.com/39439201/56145819-4d24a300-5fa5-11e9-95c3-ffe89be80270.jpg)

![hon](https://user-images.githubusercontent.com/39439201/56145939-9d9c0080-5fa5-11e9-840e-cca398225be5.jpg)

**What is happening:**
- She has the item available (when i am not revered) 

**What should happen:**
- Should only be available if i have rep to revered

**Comment by Echinaceax** [comment]
@Rushor - new info in , please revert
https://cdn.discordapp.com/attachments/294190741394161664/568415575601315850/Screenshot_20190418-133811.png

**Comment by Rushor** [comment]
@Echinaceax @Kitzunu said no and maniac said no? i think it should stay as is? I'm not sure mylady :octocat:

**Comment by Echinaceax** [comment]
@rusher - update 
fixes are a go until further notice

**Comment by Rushor** [comment]
okay :)
