### ISSUE TITLE
[Class] Priest mana issue

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#144]
This is like mini lvl 5 solo raid boss :D
![wowscrnshot_112818_014043](https://user-images.githubusercontent.com/20323863/49125293-de79ce00-f2bf-11e8-91eb-9b1e3cdc062b.jpg)

I just created new priest and recorded starting zone questing it took more than 20 min...
I did not slack, I did not spent time killing more mobs than it was needed. with this rate I expected to leave starting zone under 10 min, it can be even faster like 5min, without looting and multi pulling that is impossible in this scenario, and if sit and wait for mana after every 2-3 mobs this video would take 25-30 min.

I did not edit video, it is raw, and I am sorry for bad quality of video and sound I forgot to test before recording.
https://mega.nz/#!xMdi3aLL!-zoKpEUGO8WepT3OBAlK8SrE20KKf5oyUwVt-ekz5Cc

I recorded video because based on picture people dont have enough information and can assume that I spammed spells with 15 mobs at once, that I used heal to get out of mana and present issue, or that it was anomaly for that one situation and it cant be reproduced. I tested 2 times and it was the same, and with this ratio, it will slow down leveling even more, like doing quest in mines behind goldshire..

Compared to other caster human mage he have much cheaper spells at same level 5
fireball 8 mana arcane missiles free on proc and fire blast 29 mana
for priest is  almost duble for some spells
Smite 15 mana, Fheal 41 mana, SWP(dot) 32, and PWS (shield) 49 mana
mana regen is not that bad it take 10-20 seconds from zero to full, but I think that issue are spell costs, but not sure

**Comment by Keader** [comment]
Mana use come from dbc.
Each classe has diff amount of mana and mana regen...
Just checking around i dont saw nothing wrong.

**Comment by TheSale** [comment]
ummmm I disagree with you bro.
this is only video that I could find for 1-10 leveling on yt in expansion close to cata.
https://www.youtube.com/watch?v=Ocq7QofwbbQ
I believe this is mop, but things should be the same.

Also this guy has full heirlooms, but still difference is enormous... 
priest that dont spend mana at all, and my priest that after 2-3 mobs is oom, and you can see on video that I died at lvl 5... that should be impossible...

now my priest is lvl 10 in westfal I can kill no more than 3 npc. after that oom, if I pull 4 lvl 10 - lvl 12 I will die

I remember 100% when I played cata, that I could put dots on 5+ mobs at lvl 5 use shield heal re-dot them, use shield, heal and kill them without being out of mana

**Comment by TheSale** [comment]
ok 1 more video https://www.youtube.com/watch?v=sHiVgDSUci8
lvl 19 priest on retail cataclysm expansion without 1 single heirloom, with heavy use of spells do not drop under 60% of mana.
@Keader
