### ISSUE TITLE
[NPC]  Rathis Tomber <Trade Supplies> - Ghostlands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1440]
**Links:**

https://www.wowhead.com/npc=16224/rathis-tomber

**What is happening:**
- hes not trading goods

**What should happen:**
- Meant to be a trade vender too

**Comment by Kitzunu** [comment]
You need to complete https://www.wowhead.com/?quest=9152 to be able to buy from this NPC

>https://www.wowhead.com/npc=16224/rathis-tomber#comments:id=226933
Need to complete Tomber´s Supplies first if you want to buy something from him.
Sells the same stuff that all other basic Trade Goods merchants
