### ISSUE TITLE
[Quest] Toetem of Yor - azuremyst isle

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1442]
**Links:**

Quest -https://www.wowhead.com/quest=9541/totem-of-yor
NPC - https://www.wowhead.com/npc=17362

**What is happening:**

Doesn't provide you with the underwater breathing.

**What should happen:**
Should provide the player with underwater breathing whilst completing the quest.

**Comment by Kitzunu** [comment]
This is also sketchy, a random player in Range:10 will get the buff, so if you do it in a group you might need to do it one at a time until SMART_TARGET_ACTION_INVOKER is working in DB...
