### ISSUE TITLE
[Quest] Murder Was The Case That They Gave Me - Westfall

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1443]
**Links:**
https://www.wowhead.com/quest=26209/murder-was-the-case-that-they-gave-me
from WoWHead or our Armory

**What is happening:**
you have to talk to the homeless to get clue 1 2 3 4 but u can only get clue 2 3 4 there and when u talk to them none of them give you clue 1

**What should happen:**
you have to talk to the homeless to get clue 1 2 3 4

**Comment by Repsidian** [comment]
not being able to do this quest stops u from doing any quest in westfall as it is a chain quest which sends u to other quests

**Comment by sarahkay88** [comment]
![World of Warcraft 16_04_2019 18_11_14](https://user-images.githubusercontent.com/42302580/56229989-259c0c00-6073-11e9-8b0d-9a3581d31eac.png)
it could complete this
