### ISSUE TITLE
[NPC] Innkeeper Gryshka - (Hallow's end) - Ogrimmar

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1444]
**Links:**
https://www.wowhead.com/npc=6929/innkeeper-gryshka

![no trick](https://user-images.githubusercontent.com/39439201/56175932-93a3ed00-5ff9-11e9-8734-1fe036a5477a.jpg)

**What is happening:**
- doesnt offer "trick or treat" option 

**What should happen:**
- She should give "trick or treat" when event is on

**Comment by Rushor** [comment]
reapplied the fix. pls make sure that the event 12 is on and the debuff https://wowgaming.altervista.org/aowow/?spell=24751 is not active on the player.
