### ISSUE TITLE
[Quest] Crawfish Creole -26226- Orgrimmar

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1446]
**Links:**
https://www.wowhead.com/quest=26226/crawfish-creole

**What is happening:**
- Not giving quest credit 
- Cant complete

**What should happen:**
- Should give quest credit

@Rushor - please fix this coz i cant test more dailies its stuck on this broken one :)

**Comment by Lerixo** [comment]
Can confirm. Looting the critters wont yiel quest progress.

**Comment by Rushor** [comment]
item is added now

![I](https://i.imgur.com/eDbXIEU.jpg)
