### ISSUE TITLE
[Quest] Ram on the Lam - Id 25905 - Dun Morogh

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#1456]
**Links:**
Quest - https://www.wowhead.com/quest=25905/rams-on-the-lam
Npc - https://www.wowhead.com/npc=1261
from WoWHead or our Armory

**What is happening:**

The Quest is Accepted and your told to use the /e Whistle emote to call the stolen rams running around the area but the rams don't respond to the emote.

**What should happen:**

The Quest should be accepted and your instructed to use the /e whistle emote to round up he stolen rams in the area, using the emote should cause the rams to follow u back to the Ranch to complete the quest.

**Comment by Rushor** [comment]
By torin23 (6,908 –  2·15·23)  on 2010/11/29 (Patch 4.0.3) |   |  
-- | -- | --
