### ISSUE TITLE
[Item] Thunder Bluff Satchel

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1465]
**Links:**
https://www.wowhead.com/npc=50483/brave-tuho
https://www.wowhead.com/item=67534/thunder-bluff-satchel

![blufff](https://user-images.githubusercontent.com/39439201/56239032-41fa7180-6090-11e9-8d2a-17946ea6caf5.jpg)

**What is happening:**
-Sells thunder-bluff-satchel without rep 

**What should happen:**
- Requires rep first

**Comment by Echinaceax** [comment]
@Kitzunu - Ooops didnt reallize it was u that renames my title :)
thought it was me ...i need sleep lol

**Comment by Kitzunu** [comment]
It is an item issue, not npc :)

**Comment by Kitzunu** [comment]
Item will now only show if your reputation is Revered or Exalted

**Comment by Echinaceax** [comment]
@Kitzunu new info in , please revert
https://cdn.discordapp.com/attachments/294190741394161664/568415575601315850/Screenshot_20190418-133811.png
