### ISSUE TITLE
[GM Island ] Bounty Hunter (server crash) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1473]
**Links:**
![mall stone dude](https://user-images.githubusercontent.com/39439201/56257821-cae3ce00-60cd-11e9-8fb8-33b1b61e8ae5.jpg)

**What is happening:**
- Bounty hunter at GM island is crashing the server when you click on his bounty

**What should happen:**
- Thats naughty, he shouldn't do that :)

**Comment by wow-mania** [comment]
Fixed. But we will remove it anyways.

**Comment by Echinaceax** [comment]
@wow-mania Can we fix him and get him back. thanks :)

**Comment by Rushor** [comment]
id is 70007

**Comment by Rushor** [comment]
readding with next update

**Comment by Echinaceax** [comment]
tested and working :)
