### ISSUE TITLE
[Quest] Hero of the Sin'dorei -9328- Silvermoon

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1474]
**Links:**
quest - https://www.wowhead.com/quest=9328/hero-of-the-sindorei
npc - https://www.wowhead.com/npc=16802/lorthemar-theron

![cant hand in](https://user-images.githubusercontent.com/39439201/56263041-ac87cd80-60e1-11e9-90a1-26d2592bddbb.jpg)

**What is happening:**
- completed but cant hand it in 

**What should happen:**
- Should hand in if its completed

**Comment by Rushor** [comment]
that bug sometimes happens. remove the quest and retake it and it should work

https://i.imgur.com/adpCILj.jpg
