### ISSUE TITLE
[NPC] Erunak Stonespeaker <The Earthen Ring> Vashj'ir

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1475]
**Links:**

https://www.wowhead.com/npc=40105/erunak-stonespeaker

**What is happening:**
- HS mouse icon

**What should happen:**
- He not Innkeeper 

not sure what hes meant to have :)

**Comment by Kitzunu** [comment]
Could you get me the Entry of this NPC please?

.npc info on dev, scroll up to find Entry: ####

**Comment by Rushor** [comment]
concerns npc entries: 36915 and 41618

**Comment by Rushor** [comment]
it works fine for me - could you tell me what exactly is not working?

**Comment by Echinaceax** [comment]
his mouse over is a 

![HS icon](https://user-images.githubusercontent.com/39439201/56599359-b1271700-65f6-11e9-9863-458ad9ba6516.jpg)

hes not meant to have that (speech bubble maybe)

im sure i put a "low priority label" on this one :)

**Comment by Rushor** [comment]
oh well i think he should be an innkeeper 

see https://wowwiki.fandom.com/wiki/Erunak_Stonespeaker ((also serves as unlabeled Innkeeper) )

**Comment by Echinaceax** [comment]
@Rushor - haha cool :)
