### ISSUE TITLE
[Quest] Feeding the hungry and hopeless - ID 26271 - Westfall

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1477]
**Links:**
Quest -https://www.wowhead.com/quest=26271/feeding-the-hungry-and-the-hopeless
NPC - https://www.wowhead.com/npc=42575
item - https://www.wowhead.com/item=57991

**What is happening:**
The item works has intended however the homeless do not eat the stew this prevents the quest from completing
**What should happen:**
When the item is placed at there feet the homeless should eat the stew allowing me to feed 20.

**Comment by Echinaceax** [comment]
yip im on that quest now too and cant complete it.

@Rushor @Kitzunu - fix please lol

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/O4iLsn5.jpg)
