### ISSUE TITLE
[ITEM] Gnoll Attack Order -display - Westfall

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1478]
**Links:**

https://www.wowhead.com/item=58111/gnoll-attack-orders
**What is happening:**
Missing Item Pgae

**What should happen:**
Should display content speech - 
_minions our leader has spoken,  You are to attack sentinel hall and free the admiral. You may keep anything you find in your rampage._
~ Helix

**Comment by Echinaceax** [comment]
![goss](https://user-images.githubusercontent.com/39439201/56392703-6aba6c80-6232-11e9-98f1-4bf7da2c6d04.jpg)

still not fixed 
@Rushor @Kitzunu - can we maybe get some low level zones fixed ?

**Comment by Rushor** [comment]
page text 3633

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/1BOtgEK.jpg)

going to fix event more soon.

Remember to delete the cache.
