### ISSUE TITLE
[Druid/trainer] Trainer Not Training Spell Starting Areas

### ISSUE THREAD

**Issue by DiomacheTharghan** [WoWManiaUK/Blackwing-Lair#1482]
**Links**

**Whats happening** 

I noticed that any druid trainer is not working since i was trying to do couple of levels. 

**What should happen**
- Class trainer should train me

_So as much as it's "too early" to report stuff, just keep in mind that trainers are not working._

**Comment by Kitzunu** [comment]
Please read the wiki on how to report an issue to make a proper report and please use the template that has been made

**Comment by sarahkay88** [comment]
this is a major issue again! I just cam across the same issue for mages

**Comment by DiomacheTharghan** [comment]
> 
> 
> Please read the wiki on how to report an issue to make a proper report and please use the template that has been made

There's nothing on github on this bug, meaning it hasn't beed reported yet. 

I checked everything on the wiki, and it match with my current situation of client/addons/launcher and so it. I don't think i need to link you on wowhead or any bluepost regarding "a TRAINER that should train spells lol", it is pretty much obvious on its own. 

If you want a video, there'a twitch stream that i did before to witness the problem.

I just saw the page "how to properly report an issue", if there's a template, please link it to me because i can't find it.

**Comment by Echinaceax** [comment]
@DiomacheTharghan 
hi , i have re edited your report and title for you

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/56304647-e0451080-613e-11e9-8a6f-e00f7d967216.png)
![image](https://user-images.githubusercontent.com/24550914/56304694-fbb01b80-613e-11e9-992a-c0a053e143ab.png)

**Comment by Echinaceax** [comment]
@DiomacheTharghan - with tag this as duplicate coz you reported same issue x2 ok
