### ISSUE TITLE
[Quest] Life of the party - ID 14153 - Blocks goblin starter chain (phasing issue)  - Kezan

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#149]
https://www.wowhead.com/quest=14153/life-of-the-party

First quest and problem... there are no npc at the pool party Kezan 60,80

![wowscrnshot_112818_225842](https://user-images.githubusercontent.com/20323863/49185635-abd4e180-f362-11e8-8ca4-6d5bbdefa240.jpg)

**Comment by wow-mania** [comment]
NPCs are there. Phase is messed up.

**Comment by Echinaceax** [comment]
have the same issue :)

**Comment by gamer100** [comment]
The phase issue is  still there and there  are just hostile npc

![image](https://user-images.githubusercontent.com/33811022/62411510-1f1aab80-b5f4-11e9-944d-f0f7f6724c7c.png)

**Comment by Rushor** [comment]
okay almost done. just need to fix one crash here

**Comment by gamer100** [comment]
@Rushor and the interaction with the  npc,s they dont interact

**Comment by Rushor** [comment]
yes fixing that tomorrow morning :>

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/PLh4SU1.jpg)
