### ISSUE TITLE
[Druid/trainer] Trainer Not Training Spells in Starting Areas 

### ISSUE THREAD

**Issue by DiomacheTharghan** [WoWManiaUK/Blackwing-Lair#1490]
**Links:**
NPC - Every Single Trainer in Starting Areas (Tested in multi Region)
For example: https://www.wowhead.com/npc=38243/zentabra (tested)

**What is happening:**
Trainers are not training any spells.

**What should happen:**
Should provide the classes with training

**Comment by Echinaceax** [comment]
@DiomacheTharghan 
Are you a tester or are you a player just reporting ?

**Comment by DiomacheTharghan** [comment]
Player, but can be tester if needed.

**Comment by Echinaceax** [comment]
@DiomacheTharghan - very nice 
i'll let you know soon

**Comment by DiomacheTharghan** [comment]
Don't know if i've to open another thread, but also 
https://www.wowhead.com/npc=3156/nartok

Is not working, which is WARLOCK trainer.

I'll test more classes right as we speak

**Comment by DiomacheTharghan** [comment]
**UPDATE:**
https://www.wowhead.com/npc=44380/jabul In Razor Hill is not Even allowing me to talk to him.
https://www.wowhead.com/npc=44726/shalla-whiteleaf in Orgrimmar - Same

**Comment by Echinaceax** [comment]
@DiomacheTharghan - all must be made as single reports :)

**Comment by DiomacheTharghan** [comment]
Sure, one sec

**Comment by DiomacheTharghan** [comment]
@Echinaceax done
