### ISSUE TITLE
[Hunter/trainer] Hunter Training not working

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Blackwing-Lair#1496]
**Link**
- [ ] https://wowwiki.fandom.com/wiki/Vord
- [ ] https://wowwiki.fandom.com/wiki/Deremiis
- [ ] https://wowwiki.fandom.com/wiki/Killac
- [ ] https://wowwiki.fandom.com/wiki/Jocaste
- [ ] https://wowwiki.fandom.com/wiki/Dorion
- [ ] https://wowwiki.fandom.com/wiki/Jeen%27ra_Nightrunner
- [ ] https://www.wowhead.com/npc=44249/sarisse-jume
- [ ] https://www.wowhead.com/npc=44247/wulf-hansreim
- [ ] https://www.wowhead.com/npc=5515/einris-brightspear
- [ ] https://www.wowhead.com/npc=5516/ulfir-ironbeard
- [ ] https://www.wowhead.com/npc=5117/regnus-thundergranite
- [ ] https://www.wowhead.com/npc=5116/olmin-burningbeard

![image](https://user-images.githubusercontent.com/33811022/56305937-9873b880-6141-11e9-99f7-84c395114526.png)

They open the window  but that is all

Hunter class training is not working, I have  tried tried exodar, Darnassus, Stormwind and ironforge

**What should happen**
 Trainer should train when clicked

**Comment by sarahkay88** [comment]
please add npc link there is a new way of reporting issue and if you don't use it they will close the report
