### ISSUE TITLE
Quests not displayed on map

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#15]
I've no idea what causes this. As you progress with the quest chains, at some point quests stop appearing on your map as intended. No addons in use, and using Launcher properly.

When testing as an orc, the map tracking breaks after the very first quest to kill boars. ALL quests I take afterwards will not be shown on the map, not even with a designated quest helper addon downloaded.

For Tauren, it appears to begin happening when you have to leave bloodhoof village
Quests which no longer work with map:
http://www.wowhead.com/quest=20441 Rite of vision
http://www.wowhead.com/quest=24459 Morin Cloudstalker
http://www.wowhead.com/quest=24523 Wildmane totem
Edit: Also breaks after the first quest for humans.
Not enough data for other starter zones yet.

PS: tried abandoning and retaking quests 1 by 1, none of them work on their own either
Clearing cache, relogging, restarting etc, obviously all don't work either, it does not look like client-issue.

**Comment by fvicaria** [comment]
Please recheck on the latest build. Also check addons etc. I cannot reproduce this.

**Comment by Dranah** [comment]
It happens on the new client too. With or without addons active. Zunrin said he encountered this problem too, so it cannot be on my end.
Zunrin also said something about how on another server with same problem it was specific quests that would break the map tracking.
I can confirm that some quest chains work just fine. You can only reproduce this with certain quests, not all. Which one have you tried?

**Comment by Echinaceax** [comment]
- started new area (Burning steppes)
- The first 3 quest are showing 

![burning steppes](https://user-images.githubusercontent.com/39439201/51049176-5fb9c580-15cd-11e9-9022-9256e5b78f55.jpg)
