### ISSUE TITLE
[Item] Ironforge Satchel -67528

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1507]
**Links:**
https://www.wowhead.com/item=67528/ironforge-satchel
https://www.wowhead.com/npc=50309/captain-stonehelm

**What is happening:**
- Can buy this sactchel without having required rep

**What should happen:**
-shouldnt be available without rep

**Comment by sarahkay88** [comment]
And this one @Echinacea lol

**Comment by Echinaceax** [comment]
![proof](https://user-images.githubusercontent.com/39439201/56364726-92d4ac00-61ef-11e9-818d-b4d8647f5885.jpg)

**Comment by Echinaceax** [comment]
@sarahkay88  All satchel will be REP Revered
