### ISSUE TITLE
[Item] Gnomeregan Satchel -67530-

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1508]
**Links:**
https://www.wowhead.com/item=67530/gnomeregan-satchel
https://www.wowhead.com/npc=50308/master-tinker-trini

**What is happening**

Can buy this sactchel without having required rep

**What should happen:**
-shouldnt be available without rep

**Comment by sarahkay88** [comment]
Your gonna have a lot of angry players lol

**Comment by Echinaceax** [comment]
> Your gonna have a lot of angry players lol
just seen what u sent me

**Comment by sarahkay88** [comment]
@Echinacea need to stop the release of this fix happening. 😂
