### ISSUE TITLE
[Item] Gilnean Satchel -67532-

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1509]
**Links:**
https://www.wowhead.com/item=67532/gilnean-satchel
https://www.wowhead.com/npc=50307/lord-candren

**What is happening:**
- Can buy this sactchel without having required rep

**What should happen:**
- shouldnt be available without rep

**Comment by sarahkay88** [comment]
Please don't release this fix either, this is suppose to be this way

**Comment by Echinaceax** [comment]
@kits - nope, i can still buy them :)
