### ISSUE TITLE
[Item] Darnassian Satchel -67526-

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1510]
**Links:**
https://www.wowhead.com/item=67526/darnassian-satchel
https://www.wowhead.com/npc=50305/moon-priestess-lasara

**What is happening:**
- Can buy this sactchel without having required rep

**What should happen:**
-shouldnt be available without rep

**Comment by sarahkay88** [comment]
Don't fix what isn't broken its meant to be this way....

**Comment by Echinaceax** [comment]
update @sarahkay88 All satchel will be REP Revered
