### ISSUE TITLE
[Item] Stormwind Satchel -67531-

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1511]
**Links:**
https://www.wowhead.com/item=67531/stormwind-satchel
https://www.wowhead.com/npc=49877/captain-lancy-revshon

**What is happening:**
- Can buy this sactchel without having required rep

**What should happen:**
- shouldn't be available without rep

**Comment by sarahkay88** [comment]
FYI this is suppose to be this way, along with tabbards.

**Comment by bagi84** [comment]
https://cdn.discordapp.com/attachments/294190741394161664/568415575601315850/Screenshot_20190418-133811.png

They are available from friendly for all cities for both faction and have been like that since 4.0.3 its was exactly the same in retail

**Comment by Echinaceax** [comment]
> They are available from friendly for all cities for both faction and have been like that since 4.0.3 its was exactly the same in retail

thats the thing though bagi, i tested with 0 rep on lvl1 if you remember in 1st test

**Comment by sarahkay88** [comment]
Always read the comments

**Comment by Echinaceax** [comment]
Gotcha @sarahkay88

**Comment by Echinaceax** [comment]
update @sarahkay88 All satchel will be REP Revered
