### ISSUE TITLE
[Quest/npc] Greatfather Winter is Here! (winter veil)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1512]
**Links:**
_Ally_
quest - https://www.wowhead.com/quest=7022/greatfather-winter-is-here
npc - https://www.wowhead.com/npc=13444/greatfather-winter

_Horde_
Quest - https://www.wowhead.com/quest=6961/great-father-winter-is-here
npc - https://www.wowhead.com/npc=13445/great-father-winter

**What is happening:**
- Greatfather winter is missing 
- Cant deliver quest

**What should happen:**
- Should be in city of the quest

**Comment by sarahkay88** [comment]
#4006 rushor patched from mania so he is now bk for ally, will check horde n do a new report.

**Comment by Rushor** [comment]
not from mania. everything is completely new :D
