### ISSUE TITLE
[NPC] Nuri <Guild Vendor> (Issue2) - Exodar

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1515]
**Links:**

https://www.wowhead.com/npc=51501/nuri#sells:0+2

_Issue2_

![nuri p3](https://user-images.githubusercontent.com/39439201/55743483-b4d17000-5a32-11e9-8b5e-6c03a3a2ff06.jpg)

- [ ] Items missing 
https://www.wowhead.com/item=65363/guild-herald

- [ ] Mounts missing 
https://www.wowhead.com/item=63125/reins-of-the-dark-phoenix
https://www.wowhead.com/item=62298/reins-of-the-golden-king
https://www.wowhead.com/item=116666/blacksteel-battleboar

- [ ] Pets Missing 
https://www.wowhead.com/item=63398/armadillo-pup
https://www.wowhead.com/item=63138/dark-phoenix-hatchling
https://www.wowhead.com/item=71033/lil-tarecgosa

**Comment by Rushor** [comment]
some items listed there are not from cata

**Comment by Echinaceax** [comment]
@Rushor i was going to link from twinhead , i should have really
