### ISSUE TITLE
[Spell] Control Pet - 79682

### ISSUE THREAD

**Issue by Nillermaid** [WoWManiaUK/Blackwing-Lair#1519]
**Links**
spell - https://cata-twinhead.twinstar.cz/?spell=79682
npc - https://cata-twinhead.twinstar.cz/?npc=3352

![WoWScrnShot_041819_220447](https://user-images.githubusercontent.com/6054280/56384979-7f910300-6226-11e9-98af-5f49f223c21e.jpg)
![WoWScrnShot_041819_220501](https://user-images.githubusercontent.com/6054280/56384985-828bf380-6226-11e9-9358-e389d301e92f.jpg)

**Whats happening** 
trainers just dont have that spell to learn from them. It is shown in spellbook as "see your trainer". All other pet-related skills are learned.   

**What should happen**
- Trainer should have it in the list ready for  (lvl 10)

**Comment by Nillermaid** [comment]
a little update - 
![WoWScrnShot_041819_223018](https://user-images.githubusercontent.com/6054280/56386083-92590700-6229-11e9-9b8e-873607e6de93.jpg)
somehow at pet trainer i can see that "control pet" ability is learned, but its not learned in skilbook and has no effect on character.

**Comment by Echinaceax** [comment]
@Nillermaid - different trainer ..so make new report for each trainer that has issues

**Comment by Nillermaid** [comment]
@Echinaceax its the same for orgrimmar trainer and this one, i checked both

**Comment by Echinaceax** [comment]
@Nillermaid - could be in the newest fixes ...it will be updated soon hopefully

**Comment by Nillermaid** [comment]
@Echinaceax as u can see, on 2nd screenshot in razor hill i have a different pet - crocolisk, so already tried that - didnt help. Still have that spell showing up as "learned" at trainers, still glows in spellbook saying "go see trainer" and still no effect on current pet =)

**Comment by Echinaceax** [comment]
@Nillermaid - yes im in DEV now on a hunter toon to figure out something

**Comment by Echinaceax** [comment]
@wow-mania @Rushor - tested on dev at lvl 10 
learnt the ability "control pet" and "dismiss" for this test 

i have also no pet bar 
- tested with blizz UI and bartender4 (no pet bar)
- Reloaded UI (no pet bar)
- Dismissed pet and recalled pet (still no pet bar

**Comment by Saintres** [comment]
This is the same in Stormwind and for Ally.

**Comment by Dranah** [comment]
The issue is same as for warlocks. The trainers have wrong spell ID. So learning it wont give you the ability you need.
Spell ID at trainer: 79682
![WoWScrnShot_042219_234545](https://user-images.githubusercontent.com/31132743/56533855-cd747680-6558-11e9-829a-6d64ee284d8f.jpg)
Spell ID you actually need: 93321
![WoWScrnShot_042219_234552](https://user-images.githubusercontent.com/31132743/56533873-d6654800-6558-11e9-8c7d-1ed87c79eb09.jpg)

**Comment by Echinaceax** [comment]
Yes i see that know, same issue as you have with Warlock #1611
thanks @Dranah
