### ISSUE TITLE
[Object] Apple bob - 180523- (Hallow's end) - Silvermoon

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1520]
**Links:**
https://cata-twinhead.twinstar.cz/?spell=101507

**What is happening:**
- not giving apples (did before Wednesday fix update)

**What should happen:**
- should give apples when event is active

**Comment by Kitzunu** [comment]
#1468 
![image](https://user-images.githubusercontent.com/24550914/56390719-efa28780-622c-11e9-96ab-05597ec9f5ee.png)
