### ISSUE TITLE
[Item] Worn Mace -36- (item not working)

### ISSUE THREAD

**Issue by Jekenius** [WoWManiaUK/Blackwing-Lair#1521]
**Links:**

from WoWHead or our Armory
https://cata-twinhead.twinstar.cz/?quest=14011
https://cata-twinhead.twinstar.cz/?item=36

**What is happening:**
I got shaman quest to learn and practice Primal Strike ability, but i cant use it with my starter weapon. That weapon also have animation like i wield no weapon at all, my character tries to fist target dummys.

![WoWScrnShot_041919_030023](https://user-images.githubusercontent.com/45003723/56388140-6ac96500-6250-11e9-821d-eb2509ba7fe9.jpg)
![WoWScrnShot_041919_030030](https://user-images.githubusercontent.com/45003723/56388145-6d2bbf00-6250-11e9-875d-a60505ac467f.jpg)
![WoWScrnShot_041919_030048](https://user-images.githubusercontent.com/45003723/56388146-6ef58280-6250-11e9-9f0d-fda2aa1aa12d.jpg)

**What should happen:**
That worn mace shamans have as first weapon is surely weapon, or at least it should be if it isnt.

**Comment by Echinaceax** [comment]
@Rushor @Kitzunu - must have broken 
it was fine on the class test we did at lvl1 - 10

**Comment by Jekenius** [comment]
That isnt really issue with a quest, if that weapon will count as a normal weapon there should be no problem to finish that, i suppose. The thing is even weapon is equipped primal strike tooltip says there's no melee weapon equipped

**Comment by Jekenius** [comment]
ill get a screenshot to show the tooltip

**Comment by Jekenius** [comment]
![WoWScrnShot_041919_035550](https://user-images.githubusercontent.com/45003723/56390993-98fe7300-6257-11e9-9baa-0447c738d0d4.jpg)
on the right bottom corner tooltip says "no melee weapon in main hand equipped"

**Comment by Echinaceax** [comment]
@Jekenius ah i see

**Comment by Jekenius** [comment]
i didnt complete this quest because i havent other melee weapon except starter one which seems to not be weapon

**Comment by Rushor** [comment]
works fine for now

![I](https://i.imgur.com/aV15Fat.jpg)
