### ISSUE TITLE
[NPC]  Chip Endale /  Candy Cane  - Kazan

### ISSUE THREAD

**Issue by Jekenius** [WoWManiaUK/Blackwing-Lair#1523]
**Links:**
https://github.com/WoWManiaUK/Blackwing-Lair/issues/850
prev issue about these npc, isnt fixed yet

https://github.com/WoWManiaUK/Blackwing-Lair/issues/1522
undoable quest in "Give Sassy the News" chain(explanations below)

from WoWHead or our Armory
https://cata-twinhead.twinstar.cz/?quest=14153
https://cata-twinhead.twinstar.cz/?quest=24520
https://cata-twinhead.twinstar.cz/?npc=35053
https://cata-twinhead.twinstar.cz/?npc=35054

**What is happening:**
![WoWScrnShot_041919_033040](https://user-images.githubusercontent.com/45003723/56389812-b8e06780-6254-11e9-8d7b-92ab8291104e.jpg)
![WoWScrnShot_041919_033039](https://user-images.githubusercontent.com/45003723/56389813-b978fe00-6254-11e9-876d-a88d33467bfa.jpg)
There shouldnt be both of these npc giving quest to player due to the goblin starter quest chain plot. Also, quest "Life of the Party" shouldnt be accessible before completing "Give Sassy the News", which cant be done because part of quest chain before "Give Sassy the News" is undoable.

**What should happen:**
There should be only one npc giving quests to the player, opposite to your character gender(for male player character there should be Candy Cane and for female player character there should be Chip Endale)
Also, any of these npc shouldnt give "Life of the Party" quest before completing "Give Sassy the News" quest.
https://www.youtube.com/watch?v=5RGSFIG4xCI
https://www.youtube.com/watch?v=LDj3e8rGNcs
these videos should be example of "opposite gender giving quests to you"

**Comment by Kitzunu** [comment]
Quest 14113 (Female) and 14153 (Male) Now requires you to have completed quest 24520.

Candy Cane will now only give quest: 14113, 26712 to Female Chars
Chip Endale will now only give quest: 14153, 14153 to Male Chars

**Comment by Echinaceax** [comment]
@Kitzunu - "Give Sassy the News"  (fixed) 

> Candy Cane will now only give quest: 14113, 26712 to Female Chars
> Chip Endale will now only give quest: 14153, 14153 to Male Chars

not fixed ...i can still pick up quest from both 
#848 still given by both chip and candy

**Comment by Kitzunu** [comment]
hm weird, it's fixed if you are on a male char o.o

I will look into it

**Comment by Kitzunu** [comment]
Fixed now

**Comment by Jekenius** [comment]
hope that another part of that issue will be fixed too(player shouldnt be able to get "Life of the Party" before doing "Give Sassy the News")

**Comment by Kitzunu** [comment]
@Jekenius That is fixed, you will only be able to pick up Life of the Party after completing Give Sassy the News

**Comment by Echinaceax** [comment]
@Kitzunu - "Life of the Party" is reported too #149

**Comment by Jekenius** [comment]
anyway you cant start doing "Life of the Party", because you cant finish "Necessary Roughness" as i can see atm, which is required to do "Give Sassy the News"
