### ISSUE TITLE
[Quest] Spared from Madness - ID 26736 -  Stranglethorn Vale

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1525]
**Links:**
https://www.wowhead.com/quest=26736/spared-from-madness
from WoWHead or our Armory

**What is happening:**
you open the cage to let them free and they stand there looking at you and do nothing and then the cage door closes

**What should happen:**
you open the cage to let them free and they run out and the quest completes

**Comment by zippoking** [comment]
Confirmed. After opening the cage, the quest is still not complete.

![Spared from Madness - how it is](https://user-images.githubusercontent.com/18005338/59510593-60c08d00-8eb4-11e9-9fcc-5e8a7cd4b516.png)

**Comment by Rushor** [comment]
credit added

![I](https://i.imgur.com/4bLDwq7.jpg)
![I](https://i.imgur.com/peNHHnc.jpg)
