### ISSUE TITLE
[QUEST] Wanted: redridge Gnolls - double - Redridge Mountain

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1526]
**Links:**

Quest - https://www.wowhead.com/quest=26504/wanted-redridge-gnolls
Start -https://www.wowhead.com/object=204344

**What is happening:**
There are two wanted post boards both displaying the same quest, one counteracts the other
![World of Warcraft 18_04_2019 23_09_49](https://user-images.githubusercontent.com/42302580/56394911-a3f1dd00-6230-11e9-8fe9-1b563a25fab4.png)

**What should happen:**
 one quest

**Comment by Kitzunu** [comment]
There is supposed to be 2 of them, I believe there is depending from which way you come from :P

Anyhow, after checking videos and screenshots all of them have 2 boards

**Comment by Echinaceax** [comment]
> Anyhow, after checking videos and screenshots all of them have 2 boards

videos can be from other private servers, so this isnt 100% though @Kitzunu

**Comment by Echinaceax** [comment]
my mistake - yes your right @Kitzunu :)
