### ISSUE TITLE
[NPC] Lashtail Egg

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1528]
**Links:**
https://www.wowhead.com/stranglethorn-vale
https://www.wowhead.com/npc=686/lashtail-raptor
https://www.wowhead.com/npc=42620/lashtail-egg
from WoWHead or our Armory

**What is happening:**
When fighting the Lashtail Raptors in Stranglethorn vale if you pull a raptor that is close to the eggs the eggs follow the raptor aswell and start attacking you

**What should happen:**
When pulling a Lashtail raptor near the Lashtail eggs the Raptor only should come running towards you and the eggs should stay where they are

**Comment by Kitzunu** [comment]
Could you get links please

**Comment by Kitzunu** [comment]
fixed
