### ISSUE TITLE
[Profession] Enchanting - trade window issue 

### ISSUE THREAD

**Issue by ghost** [WoWManiaUK/Blackwing-Lair#1530]
**Links:**
https://www.wowhead.com/enchanting

**What is happening:**
lvl 76 enchanting.
when you try to enchant another players gear using the trade window it automatically closes just before you can completed the enchant tried this on two different testers now. More info just to be clear this was two different items on two different plays and two different enchants.. Same issue.
**What should happen:**
When enchanting another players gear via trade they entre their item in the lower window, the enchanter completes the enchanted and press's complete.

**Comment by Echinaceax** [comment]
@Rushor - could be item coz saaint enchanted me ok on horde before new server

**Comment by sarahkay88** [comment]
the enchant was put on a scroll then was put on the item, so isn't an item issue

**Comment by Echinaceax** [comment]
@sarahkay88 - oh you said 

> trade window it automatically closes before you can completed the enchant 

so i replied to that ...not a scroll trade

**Comment by sarahkay88** [comment]
Yep.. I was enchanting via trade window but it closed so sent it on a scroll. But if it was an item. Issue them the enchant wouldn't go on the item. It made the mechanics of enchanting and just has it finished it auto closed. Of the item was an issue then has I said even by using the scroll they wouldn't be able to enchant it.

**Comment by sarahkay88** [comment]
I Mentioned the scroll has a reference to explain how it wasn't an item issue.

**Comment by sarahkay88** [comment]
More info just to be clear this was two different items on two different plays and two different enchants.. Same issue.

**Comment by Keader** [comment]
Nothing that i can do here.
Is client side issue.
When client open enchanting window, he send a ```CMSG_CANCEL_TRADE``` packet that cancel it.

Just for future references, stack trace of cancel:

```
>    worldserver.exe!WorldSession::SendTradeStatus(const TradeStatusInfo & info)Linha 84    C++
     worldserver.exe!WorldSession::SendCancelTrade()Linha 662    C++
     worldserver.exe!Player::TradeCancel(bool sendback)Linha 13235    C++
     worldserver.exe!WorldSession::HandleCancelTradeOpcode(WorldPacket & __formal)Linha 669    C++
     worldserver.exe!WorldSession::Update(unsigned int diff, PacketFilter & updater)Linha 360    C++
     worldserver.exe!World::UpdateSessions(unsigned int diff)Linha 2876    C++
     worldserver.exe!World::Update(unsigned int diff)Linha 2227    C++
     worldserver.exe!WorldUpdateLoop()Linha 437    C++
     worldserver.exe!main(int argc, char * * argv)Linha 340    C++
```

**Comment by Echinaceax** [comment]
Bumping this report now that we have xfaction trade enabled :)

**Comment by mfranca0009** [comment]
Was able to put together a solution through server-side and it seemed to fix the problem 👍

**Comment by Echinaceax** [comment]
confirmed fixed in ptr
