### ISSUE TITLE
[NPC] Robby Flay - Stormwind City - issue 3

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1531]
**Links:**
https://www.wowhead.com/npc=42288/robby-flay#starts
from WoWHead or our Armory

**What is happening:**
no longer gives you a daily quest and when he gave the quest he didnt give the right amount of gold as stated in wowhead

**What should happen:**
Should give a daily quest to someone who is level 10 or above and give the right amount of gold

![Robby flay complete](https://user-images.githubusercontent.com/49073659/56400156-263acb00-624a-11e9-8b1a-ebc3a98e3101.png)

**Comment by Echinaceax** [comment]
@Repsidian 
slide the bar - it scales with lvl

lvl 10 

![10](https://user-images.githubusercontent.com/39439201/56400498-7ae34380-6254-11e9-8dd6-8eb14d11501a.jpg)

lvl 120

![120](https://user-images.githubusercontent.com/39439201/56400504-85054200-6254-11e9-9062-504af81d6a21.jpg)

**Comment by Repsidian** [comment]
@Echinaceax i understand what your trying to show me but the information you are using is coming from another private server and not wowhead like we was told to use plus we dont go to level 120 we go to 85 and on the link i show from wow head there is no slider bar cause its not BFA

**Comment by Echinaceax** [comment]
@Repsidian - sorry but the 1st and 2nd SS are from wowhead :)
https://www.wowhead.com/quest=26190/a-fishermans-feast

Scroll down until you see the slidy bar 

![wowhead](https://user-images.githubusercontent.com/39439201/56423236-7433eb00-62ab-11e9-81f6-1cca09ef0f7c.jpg)

**Comment by Echinaceax** [comment]
@Rushor @Kitzunu - could be the issue when you fixed this issue #1005
