### ISSUE TITLE
[Profession] Herbalism - Experience Issue

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1533]
**Links:**
https://www.wowhead.com/skill=2553/cataclysm-herbalism
from WoWHead or our Armory

**What is happening:**
When you herb you are suppose to gain experience from the herb if the level of the herb is green yellow or orange but this isnt the case it only happens every now and again

**What should happen:**
should always give you experience when you pick the herb up off the floor if the skill colour is orange yellow or green

**Comment by Rohatej** [comment]
Same issue for mining
