### ISSUE TITLE
[Dungeon] Ragefire Chasm being "outdated"

### ISSUE THREAD

**Issue by DiomacheTharghan** [WoWManiaUK/Blackwing-Lair#1534]
**Links:**
ZONE/DUNGEON - https://www.wowhead.com/ragefire-chasm
NPC - https://www.wowhead.com/npc=61716/invoker-xorenth
https://www.wowhead.com/npc=61724/commander-bagran

**What is happening:**
Simply Ragefire Chasm is not updated to Cataclysm Version.
![WoWScrnShot_041919_183515](https://user-images.githubusercontent.com/44828921/56433799-85dcb900-62d2-11e9-97b7-cd589bdbf1cc.jpg)

**What should happen:**
Should be totally different, quest are missing, or alteast NPCs are, and a bit the scructure of it.
https://www.youtube.com/watch?v=5zc9rL3t8Bo

**Comment by Echinaceax** [comment]
@Rushor  this too #1070

**Comment by DiomacheTharghan** [comment]
@Echinaceax Are you guys planning to release the beta on sunday with an "outdated" scheme of dungeons?

**Comment by Echinaceax** [comment]
@DiomacheTharghan - please ask @fvicaria 
im only a tester same as the others, release dates are not anthing to do with me

**Comment by DiomacheTharghan** [comment]
@Echinaceax how can i message him? I mean, apart from calling him via "@" system here

**Comment by wow-mania** [comment]
Log issues as needed. Don't enter issue like that...
"this is wrong fix it!" "quest are missing, fix it!" "dungeons are wrong fix it!"
Read wiki and log an issue at a time following the guidelines please.

**Comment by DiomacheTharghan** [comment]
@wow-mania explain to me how did report it wrong. There's a link, how it should be, location, and NPC missing. The fact i commented that as "outdated" doesn't make the report any true or correct
