### ISSUE TITLE
[Profession] Tailoring - level requirment issue

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1536]
**LINK**
https://www.wowhead.com/tailoring

**What is happening:**
Yo are required to be a certain level in order to receive and learn new patters see ss - the next pattern for my toon to learn requires me to be level 25, however my toon is only twenty and can learn this pattern. To learn the skill works ie professional journeyman also requires a level but this works has intended and your unable to train until you reach that level. however you can continue to learn patterns past this point rendering the skill pointless.
![World of Warcraft 19_04_2019 22_14_10](https://user-images.githubusercontent.com/42302580/56444409-871cde80-62f0-11e9-8a4e-6cae35c05677.png)

**What should happen:**
Player should be the correct level before getting the required patterns.

**Comment by Kitzunu** [comment]
"Requires: Tailoring (150)"
There's the requirememt, the level req you are talking about is to wear the item
