### ISSUE TITLE
[ITEM] Mistmantle's Revenge - Duskwood

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1537]
**Links:**

item - https://cata-twinhead.twinstar.cz/?item=59363
quest - https://www.wowhead.com/quest=26674/mistmantles-revenge
npc - https://www.wowhead.com/npc=265

**What is happening:**

Item doesn't work preventing quest completion

**What should happen:**
Should call the spirit of Stalvan Mistmanle

**Comment by Echinaceax** [comment]
reported here #441
