### ISSUE TITLE
[NPC] Graveyard spirit

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#154]
I was in some higher level zones (doing archaeology) and I spent a lot of time trying to escape from mobs, I could progress only few steps from my corpse before I was dead again. And on the end of the day I had total of 43 deaths on lvl 22
I think that I attract mobs more than I should. people will complain on it eventually
![43 deaths](https://user-images.githubusercontent.com/20323863/49200268-57e6ee80-f39c-11e8-8e08-6ddccab42662.png)

graveyards where I found no spirit were
Blasted Lands 48,50
Burning Steps 60,47
Burning Steps 28,44
Northern Stranglethorn 56,87
![graveyard ghost missing](https://user-images.githubusercontent.com/20323863/49200330-a1373e00-f39c-11e8-9824-bdcd52f9c300.png)

![graveyard ghost missing 2](https://user-images.githubusercontent.com/20323863/49200344-aac0a600-f39c-11e8-9905-d699ee074bc5.png)

![graveyard ghost missing 3](https://user-images.githubusercontent.com/20323863/49200354-b14f1d80-f39c-11e8-80d5-427038bba0ab.png)

![graveyard ghost missing 4](https://user-images.githubusercontent.com/20323863/49201096-d6915b00-f39f-11e8-881a-d975b4f3409b.png)

**Comment by TheSale** [comment]
same thing
Eastern plaguelands 62.21
![wowscrnshot_120518_134746](https://user-images.githubusercontent.com/20323863/49514456-69e0f980-f894-11e8-80af-21a6d0ffaea7.jpg)

**Comment by wow-mania** [comment]
fixed

**Comment by Echinaceax** [comment]
**I have one too** 
The spirit healer is on the other side of the wall.

Spirit healer area list - https://www.wowhead.com/npc=6491/spirit-healer

![spirit healer is on the wrong side of the wall](https://user-images.githubusercontent.com/39439201/50648131-adee1980-0f7a-11e9-9e07-c4bb9cab08c0.jpg)

![scarlet mon](https://user-images.githubusercontent.com/39439201/50648577-e80beb00-0f7b-11e9-9dfd-9601043ee09a.jpg)

![scarley mon healer](https://user-images.githubusercontent.com/39439201/50648663-1ab5e380-0f7c-11e9-8956-6e6eead7f7de.jpg)
