### ISSUE TITLE
[Quest] Stranglethorn Fever - Strangelthorn vale

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1542]
**Links:**
https://www.wowhead.com/quest=26597/stranglethorn-fever
from WoWHead or our Armory

**What is happening:**
when you try talk to Witch Doctor Unbagwa it does nothing you cant talk to him as it doesnt give you the option to speak to him

**What should happen:**
you should be able to speak with Witch Doctor Unbagwa and he should summon Mokk the gorilla so you can obtain the heart

**Comment by Echinaceax** [comment]
Reported before, title was worded different (so may be the reason it didnt show in search)
#733
