### ISSUE TITLE
[Zone] Stranglethorn Vale - Death

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1543]
**Links:**
https://www.wowhead.com/the-cape-of-stranglethorn
from WoWHead or our Armory

**What is happening:**
died in stranglethorn vale and was portaled to the spirit healer in westfall

**What should happen:**
be portaled to stranglethorn vale spirit healer

Coords : 44.01, 91.52

**Comment by Kitzunu** [comment]
Please add where you died, nothing to be done if we dont know where

**Comment by Echinaceax** [comment]
@Kitzunu - here is the spirit heals in STV 
https://www.wowhead.com/the-cape-of-stranglethorn

**Comment by sarahkay88** [comment]
I died at co-ords 53,13, 30.14 and same happened to me

**Comment by sarahkay88** [comment]
50.61, 47.89

**Comment by georgeapostolov** [comment]
61.3, 41.9

**Comment by georgeapostolov** [comment]
50.4, 69.1

**Comment by georgeapostolov** [comment]
45.9, 79.1

**Comment by Rushor** [comment]
with next update ghost in Stranglethorn Vale finally fixed 
![I](https://i.imgur.com/gydJQc0.jpg)
![I](https://i.imgur.com/XzCzm5r.jpg)
