### ISSUE TITLE
[Dwarf/Pala] visual bug

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1544]
**Links:**

![dwarf bug](https://user-images.githubusercontent.com/39439201/56452523-bf90dc80-6331-11e9-8cd6-cf48bc8bbb7d.jpg)

**What is happening:**
- Head held to the side (head knocked off) 
- during fights the male dwarf head falls off to the side  

**What should happen:**
- Really shouldnt be like that lol, poor Panzer
- logging out and back fixes it until he fights again

note : reproduce testing tomorrow to figure how it happens

**Comment by Rushor** [comment]
okay then https://github.com/WoWManiaUK/Blackwing-Lair/issues/3962

so i think it's some kind of ride vehicle aura. clear reproduction is in https://github.com/WoWManiaUK/Blackwing-Lair/issues/3962 and we can fix it. will close this then
