### ISSUE TITLE
[Quest] Prepare for Takeoff -ID 26695 -  Cape of Stranglethorn

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1548]
**Links:**
https://www.wowhead.com/quest=26695/prepare-for-takeoff
from WoWHead or our Armory

**What is happening:**
you should be able to find the bombs behind Narkk but they are not there or not lootable

**What should happen:**
you should be able to loot the bombs from behind Narkk

**Comment by zippoking** [comment]
Object: https://www.wowhead.com/object=204587/narkks-handbombs
Item: https://www.wowhead.com/item=59524/narkks-handbombs

**Comment by jarvik76** [comment]
Confirming still an issue Sept 19th

**Comment by Rushor** [comment]
object added

![I](https://i.imgur.com/mt1g0F5.jpg)
