### ISSUE TITLE
[Item/Object] Chest (node) not clickable - Menethil Harbor

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1554]
**Links:**
coods - 9.05. 57.02

![chest](https://user-images.githubusercontent.com/39439201/56460440-f6530b00-63a2-11e9-8c7c-aba8252e7717.jpg)

**What is happening:**
- Should be clickable or text to indicate that the "box is locked"

**What should happen:**
- nothing happens and no text appears to state otherwise

**Comment by Kitzunu** [comment]
That is just texture, no "real" chest :D
