### ISSUE TITLE
[Quest] Filthy Animals -ID 25008 - Southern Barrens

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1555]
**Links:**
https://www.wowhead.com/quest=25008/filthy-animals
from WoWHead or our Armory

**What is happening:**
when you pull a hecklefang scavenger to kill it for the quest it disappears into the floor and starts killing you 

**What should happen:**
when you pull a hecklefang scavenger you should be able to kill it

**Comment by Kadajj** [comment]
![WoWScrnShot_041220_144718](https://user-images.githubusercontent.com/38867875/79070273-a1ec1e00-7ccc-11ea-9eb6-ff378fd51f18.jpg)
![WoWScrnShot_041220_144800](https://user-images.githubusercontent.com/38867875/79070276-a31d4b00-7ccc-11ea-9b5b-1f099d5bbda0.jpg)
