### ISSUE TITLE
[Quest] Sowing a Solution - ID 24566 - Southern Barrens

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1558]
**Links:**
https://www.wowhead.com/quest=24566/sowing-a-solution
from WoWHead or our Armory

**What is happening:**
i use the quest item on the mobs and nothing happens

**What should happen:**
when i use the quest item on the mobs its suppose to do something that you observe happen

**Comment by Rushor** [comment]
Upon spellhit creatures will give questcredit now with internal cd of 30 seconds.
