### ISSUE TITLE
[Spell] Paladin Templar's Verdict- id 85256- Retribution Paladin

### ISSUE THREAD

**Issue by quortonn** [WoWManiaUK/Blackwing-Lair#1563]
https://www.wowhead.com/spell=85256/templars-verdict
![WoWScrnShot_042019_212808](https://user-images.githubusercontent.com/49811949/56461453-c102e900-63b3-11e9-8917-d244a742fc95.jpg)
![WoWScrnShot_042019_213810](https://user-images.githubusercontent.com/49811949/56461510-a1b88b80-63b4-11e9-9904-1dc9c48400cd.jpg)
![WoWScrnShot_042019_211606](https://user-images.githubusercontent.com/49811949/56461475-0cb59280-63b4-11e9-84c0-af224f6bb472.jpg)
![WoWScrnShot_042019_211703](https://user-images.githubusercontent.com/49811949/56461479-1e973580-63b4-11e9-9a20-7524c2ecf68e.jpg)
![WoWScrnShot_042019_211755](https://user-images.githubusercontent.com/49811949/56461480-34a4f600-63b4-11e9-8971-abbf38bd39b4.jpg)

**What is happening:**
The spell Templar's Verdict (ss n1) has 3 damage modifiers based on the holy power stacks spent to use it. Based on my weapon damage (ss n2), you can see the damage dealt with 1 spel used with 1 holy power charge (ss n3), the damage done with 1 spell used with 2 holy power charges (ss n4) and the damage done with 1 spell used with 3 charges of holy power (ss n5). The damage of the spell used with 3 holy power charges is much lower than how much it should be. 

**What should happen:**
The damage of the Templar's Verdict used with 3 charges of holy power should be higher than the damage of the same spell used with 2 charges of holy power.

**Comment by sarahkay88** [comment]
relates to #1270

**Comment by Keader** [comment]
Try now.
It was doing with 2 holy power, damage of 3 holy power
and doing with 1 holy power, damage of 2 holy power
