### ISSUE TITLE
[Quest] Unbidden Visitors - Durotar

### ISSUE THREAD

**Issue by DiomacheTharghan** [WoWManiaUK/Blackwing-Lair#1567]
**Links:**
QUEST - https://www.wowhead.com/quest=25194/unbidden-visitors
MOBS - https://www.wowhead.com/npc=39337/wayward-plainstrider

**What is happening:**
Wayward Plainstrider are just getting killed with no reaction related to the quest

**What should happen:**
Wayward Plainstrider should run to the BARRENS when around 30% or below.
https://www.youtube.com/watch?v=WIjRYxns6WU

**Comment by Rushor** [comment]
duplicate and already fixed https://github.com/WoWManiaUK/Blackwing-Lair/issues/1886
