### ISSUE TITLE
[Quest] Crossroads Caravan Pickup - Northern Barrens

### ISSUE THREAD

**Issue by DiomacheTharghan** [WoWManiaUK/Blackwing-Lair#1568]
**Links:**
QUEST - https://www.wowhead.com/quest=13949/crossroads-caravan-pickup
NPC - https://www.wowhead.com/npc=34258/halga-bloodeye

**What is happening:**
Halga is not providing any option to go with the caravan/kodos and the event cannot start.
![WoWScrnShot_042019_221200](https://user-images.githubusercontent.com/44828921/56461839-8d2ac200-63b9-11e9-9592-faecea1d72f0.jpg)

**What should happen:**
Halga should provide the option to start the quest event and lead you to the next camp
https://www.youtube.com/watch?v=MagB40Ml32I

**Comment by sarahkay88** [comment]
#960
