### ISSUE TITLE
[NPC] Selma Saldean

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#157]
She is located in Westfall 56,30
she should start 2 quests
https://www.wowhead.com/quest=26266/hope-for-the-people
https://www.wowhead.com/quest=26241/westfall-stew

**Comment by wow-mania** [comment]
Quests have requirements.
https://www.wowhead.com/quest=26270/you-have-our-thanks
Please double check before rushing to open issues.

**Comment by TheSale** [comment]
I know that, I posted that quest in comment of Farmer Saldean, but I did not know will you fix that since issue was closed when you fixed him as vendor, but did not assign quests to him.
and quest were not available for me and I did not know is the issue selma or farmer.

**Comment by wow-mania** [comment]
So there is no problem pending?

**Comment by TheSale** [comment]
I dont have access to this quests, Farmer has no quests Selma has no quests.
NPC Farmer Saldean and NPC Selma Saldean dont give any quests to me.
My mage lvl 11 is stuck in westfall with no quests to do, I know that is work in progress just trying to describe situation.

**Comment by wow-mania** [comment]
Check the requirements on our wotlk Armory. For these old quests they are the same.

**Comment by TheSale** [comment]
http://www.wow-mania.com/armory/?quest=9

https://www.wowhead.com/quest=26270/you-have-our-thanks
this dont exist on wotlk armory on our site, I check quests that farmer start and searched for specific quest and not found.

anyway, still no quests on Saldeans farm
![no quest](https://user-images.githubusercontent.com/20323863/49345834-a8a36380-f68a-11e8-9011-9643d6f0f583.png)

**Comment by wow-mania** [comment]
It's a long quest chain until you can talk to them.
![image](https://user-images.githubusercontent.com/12248683/49363766-7a4d7480-f6da-11e8-88a9-49983fd8e2b4.png)

Go to Lieutenant Horatio Laine at the start of Westfall after you got Hero's "Call: Westfall!". Finish all his initial quests and then start chain.
It works. I have done it.

**Comment by TheSale** [comment]
ugh I really cant remember how exactly it works, but not all quests should be prequest for saldeans farm, I can admit that I am mistaken, since on wowhead is for current patch and not for 4.3.4.
I tested on another server it was no biggie,and without completing the series of Hot on the trail I still can get quests. I only remmember that westfall stew was pre quests to that stew to refugees to feed them.

I post issue with chain quest that I cant complete and finish quest
https://github.com/WoWManiaUK/Blackwing-Lair/issues/159

However I dont have database from cata to see exactly quests, requirements, and which quests belong to that expansion... that sux 
I did tested on another server but mop expansion and you can see that I did not do Hot on trail quest chain, but selma and farmer do offer quests.
![wowscrnshot_120418_023756](https://user-images.githubusercontent.com/20323863/49413708-1fb32780-f771-11e8-81c1-17de8b122fef.jpg)


I found this quest that lead to farmer but  I dont think it is starting or unlocking quests, it is is more like introduction I believe.
https://www.wowhead.com/quest=26236/shakedown-at-the-saldeans


btw this way of testing is very slow and un efficient,my char get stuck in westfall for 4 days on lvl12 when 1 bug lead to another bug, to another bug that stop progress. Even it is best way to test stuff, by taking players paths it is very annoying...

**Comment by Echinaceax** [comment]
Tracing this back as we are currently looking at this questline from another report 

janitor is right,  you havent done the questline i see from your SS 

![Image1](https://user-images.githubusercontent.com/39439201/85960533-73651180-b9a4-11ea-806b-a5b80dd2d743.jpg)

This quest you must complete to get all the other quests in correct order

then when you complete lou's parting thoughts then the quests are availible 

![Image2](https://user-images.githubusercontent.com/39439201/85960609-11f17280-b9a5-11ea-9f6f-ac4affad5699.jpg)
