### ISSUE TITLE
[Quest] Hands Off Me Dig! - ID 25106 - Southern Barrens

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1570]
**Links:**
https://www.wowhead.com/quest=25106/hands-off-me-dig
from WoWHead or our Armory

**What is happening:**
need to go into the digsite and find the tools for the npc that gives you the quest

**What should happen:**
cant find the quest item as it does not spawn

**Comment by Kadajj** [comment]
all items are there to be collected. quest doable.

![WoWScrnShot_041220_142257](https://user-images.githubusercontent.com/38867875/79069932-e88c4900-7cc9-11ea-8f0c-dba39b9d82fc.jpg)
![WoWScrnShot_041220_142627](https://user-images.githubusercontent.com/38867875/79069936-eb873980-7cc9-11ea-8ba4-4f0e61175bea.jpg)
![WoWScrnShot_041220_142638](https://user-images.githubusercontent.com/38867875/79069941-ede99380-7cc9-11ea-92ee-14194ddf0259.jpg)
![WoWScrnShot_041220_142751](https://user-images.githubusercontent.com/38867875/79069942-efb35700-7cc9-11ea-8f7e-0fa0cd2151cb.jpg)
