### ISSUE TITLE
[Quest] Secondhand Diving Gear - ID 27236 - Dustwallow Marsh

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1574]
**Links:**
https://www.wowhead.com/quest=27236/secondhand-diving-gear#screenshots
from WoWHead or our Armory

**What is happening**
the tool kit and damaged diving gear do not appear on the island for you to loot

**What should happen:**
Tool kit and Damaged diving gear should appear on the island

**Comment by simonverse** [comment]
yup, not working
