### ISSUE TITLE
[NPC] Cassa Crimsonwing - Inactive - Dustwallow Marsh

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1575]
**Links:**
https://www.wowhead.com/search?q=cassa+crimsonwing
https://www.wowhead.com/quest=27239/survey-alcaz-island
from WoWHead or our Armory

**What is happening:**
doesnt give you the gryphon to survey alcaz island

**What should happen:**
should give you a gryphon to survey alcaz island

**Comment by BlueDragonKing7** [comment]
Tried to do this quest today, same problem.

**Comment by simonverse** [comment]
same problem today

**Comment by Rushor** [comment]
duplicate and fixed
