### ISSUE TITLE
[Quest/item] Captured Totem - Dustwallow Marsh

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1576]
**Links:**
https://www.wowhead.com/quest=27336/the-grimtotem-weapon
from WoWHead or our Armory

**What is happening:**
the totem follows you around and when u pull a crocolisk it does nothing 

**What should happen:**
its suppose to stay in one spot when you pull a crocolisk it is suppose to hit a beam on the crocolisk and kill it

**Comment by BlueDragonKing7** [comment]
Tried to do this quest. Still not fixed

**Comment by Rushor** [comment]
okay fixed. this is how it works. 1) plant the totem 2) aura get applied on Mottled Drywallow Crocolisk 3) kill Mottled Drywallow Crocolisk 4) you will get credit

![I](https://i.imgur.com/vZqUvD9.jpg)
![I](https://i.imgur.com/Vd3dFxD.jpg)
