### ISSUE TITLE
[Quest/item] Ooze Buster - Dustwallow Marsh

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1577]
**Links:**
https://www.wowhead.com/quest=27347/corrosion-prevention
from WoWHead or our Armory

**What is happening:**
cant zap the oozes as the quest item just goes on cooldown

**What should happen:**
oozes are suppose to get zapped buy the quest item

**Comment by simonverse** [comment]
same issue

**Comment by Rushor** [comment]
all fixed.
you need to get close to the channel object. use the item on the ooze. then kill the ooze and you will get the credit

![I](https://i.imgur.com/EhmCm4L.jpg)
![I](https://i.imgur.com/aOdtWxl.jpg)
