### ISSUE TITLE
[Quest/item] Wreath - Dustwallow Marsh

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1578]
**Links:**
https://www.wowhead.com/quest=27291/peace-at-last
https://www.wowhead.com/item=33082
from WoWHead or our Armory

**What is happening:**
nothing happens when i click the quest item

**What should happen:**
a wreath is suppose to be laid on the floor of the tomb stone

**Comment by Rushor** [comment]
![I](https://i.imgur.com/0apP5qz.jpg)
![I](https://i.imgur.com/CyEgR84.jpg)
