### ISSUE TITLE
[Quest] Confirming the Suspicion -  ID 27426 - Dustwallow Marsh

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1579]
**Links:**
https://www.wowhead.com/quest=27426/confirming-the-suspicion
from WoWHead or our Armory

**What is happening:**
you dont get a visual on the map showing you where to go and do the quest

**What should happen:**
the quest should appear on your map and show you where to farm the items

**Comment by Kitzunu** [comment]
Needs to be done from sniffs, really low prio atm.

**Comment by Rushor** [comment]
already fixed

![I](https://i.imgur.com/pLPuahY.jpg)
