### ISSUE TITLE
[Quest] Meet Two-Shoed Lou

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#158]
https://www.wowhead.com/quest=26215/meet-two-shoed-lou

NPC is missing on location 49,19 in westfall
![wowscrnshot_113018_042325](https://user-images.githubusercontent.com/20323863/49266856-0a2fbc00-f458-11e8-9228-865f70cb8ded.jpg)

**Comment by Echinaceax** [comment]
still issues #4382

**Comment by rzenne** [comment]
worked fine for me today.

**Comment by Echinaceax** [comment]
really?
good to know.
thanks @rzenne 

player reported still bugged, so they must have done something wrong since this was fixed before
