### ISSUE TITLE
[Fishing/Daily/Npc] Grimnur Stonebrand <Fishing Trainer> - Ironforge

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1583]
**Links:**
https://www.wowhead.com/npc=5161/grimnur-stonebrand

![fishing](https://user-images.githubusercontent.com/39439201/56465218-c3883180-63f9-11e9-9c28-188b6ad477b9.jpg)

**What is happening:**
- He offers new daily quests when the broken quests are still in quest log

**What should happen:**
- Should be only 1 daily available visible at one time

**Comment by Rushor** [comment]
should be fixed now. you can only retake one daily a day
