### ISSUE TITLE
[Fishing/daily] Live Bait -29347- Dun Morogh

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1584]
**Links:**
https://www.wowhead.com/quest=29347/live-bait

_Use Grimnur's Bait on yourself, then jump into Helm's Bed Lake in Dun Morogh_

![wash off](https://user-images.githubusercontent.com/39439201/56465352-1236cb00-63fc-11e9-822d-f0e48608851d.jpg)

**What is happening:**
- When you use quest item on yourself u get a buff
- When you jump into water the buff is suppose to wash off 
 and bait the "Catch Cold Water Crayfish"
- the buff stays on me , cant bait 

**What should happen:**
https://www.wowhead.com/quest=29347/live-bait#videos:id=96414

**Comment by Rushor** [comment]
okay you can get the fish now and complete the quest at the questender

![I](https://i.imgur.com/FKyLjBK.jpg)
![I](https://i.imgur.com/jwCwJKR.jpg)

**Comment by rzenne** [comment]
weird worked on other characters but my dwarf it will not work for.  It says you got fish but doesn't add it bag.
