### ISSUE TITLE
[Bank] Bag Slot  Bug

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#1585]
**Links:**

from WoWHead or our Armory

**What is happening:**

I bought a slot [image1](https://user-images.githubusercontent.com/6819293/56468893-bd627700-6432-11e9-9900-4943dfd4fb53.png) and have a bag!
after purchase a slot u can put a bag in the slot but your bag space dose not expand. 
when you put the bag in the slot. The icon in the slot stays but I still do not get any more space. and the bag stays in the bank [image2](https://user-images.githubusercontent.com/6819293/56468915-129e8880-6433-11e9-954f-71828f3aed7c.png)

**What should happen:**

You need to get as many slots as your bag has. 

**Image**

image1
![image1](https://user-images.githubusercontent.com/6819293/56468893-bd627700-6432-11e9-9900-4943dfd4fb53.png)

image2
![image2](https://user-images.githubusercontent.com/6819293/56468915-129e8880-6433-11e9-954f-71828f3aed7c.png)

**Comment by sarahkay88** [comment]
Is that an addon your using?

**Comment by Kitzunu** [comment]
It works, disable your addons and use the latest game launcher
![image](https://user-images.githubusercontent.com/24550914/56470049-f9e99f00-6441-11e9-8566-72a31913c9e7.png)
