### ISSUE TITLE
[NPC] King Bangalash -  Northern Stranglethorn

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#1586]
**Links:**

[King Bangalash](https://www.wowhead.com/npc=731/king-bangalash)
[Jungle Panther](https://www.wowhead.com/npc=31636/Jungle-Panther)

**What is happening:**
[King Bangalash](https://www.wowhead.com/npc=731/king-bangalash) dont use [Leaping Rush](https://www.wowhead.com/spell=75002) and [Mangle](https://www.wowhead.com/spell=75930/mangle)
[Jungle Panther](https://www.wowhead.com/npc=31636/Jungle-Panther) dose not get aggro on you, only if u attack them.

**What should happen:**

[Jungle Panther](https://www.wowhead.com/npc=31636/Jungle-Panther) need tog et aggro on you
[King Bangalash](https://www.wowhead.com/npc=731/king-bangalash) need to use  [Leaping Rush](https://www.wowhead.com/spell=75002) and [Mangle](https://www.wowhead.com/spell=75930/mangle)

**Comment by Echinaceax** [comment]
@Kitzunu - as far as i can tell only think hes doing is melee swing 

![still not](https://user-images.githubusercontent.com/39439201/57486644-ba7ad980-72ae-11e9-96e1-447fd97dcda4.jpg)

**Comment by Rushor** [comment]
all done

![I](https://i.imgur.com/nmYa0X2.jpg)
