### ISSUE TITLE
[NPC] Blacksilt Scout - Bloodmyst isle

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1587]
**Links:**
NPC - https://www.wowhead.com/npc=17326/blacksilt-scout
quest -https://www.wowhead.com/quest=9629/catch-and-release

**What is happening:**
There is only 1 or 2 of these NPC makes it hard to do the above quest

**What should happen:**
Should be more than one npc

**Comment by Rushor** [comment]
lowered the rspawntimer for them (11 spawns are there currently)
