### ISSUE TITLE
[NPC] Azuremyst Peacekeepers -Azuremyst isle

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1588]
**Links:**

https://www.wowhead.com/npc=51905/azuremyst-peacekeeper
**What is happening:**
Sometime when these NPC walk from Azure Watch to Stilpine hold they jump really high in the air

**What should happen:**
should follow the path.

**Comment by sarahkay88** [comment]
oops brb

**Comment by Rushor** [comment]
![I](https://i.imgur.com/Gk9K03U.jpg)

pathing is adjusted now
