### ISSUE TITLE
[NPC] Captain Danuvin -821-  Westfall

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1591]
**Links:**
https://www.wowhead.com/npc=821/captain-danuvin
https://www.wowhead.com/quest=26288/jango-spothide

![2 of them](https://user-images.githubusercontent.com/39439201/56478649-2a1c5680-64b1-11e9-988d-49054f9a5578.jpg)
![2more](https://user-images.githubusercontent.com/39439201/56478726-a9118f00-64b1-11e9-86f9-b24841585112.jpg)

**What is happening:**
- double spawn, both offer same quest 
- [ ] coods - 56.38, 49.34
- [ ] coods - 56.44, 47.64 (take this one out)

**What should happen:**
- Should be only 1 other them

**Comment by Kitzunu** [comment]
He is supposed to be at both places, but I dont know if they both should be visible at the same time.

Might be missing phase/aura

**Comment by Echinaceax** [comment]
> He is supposed to be at both places, but I dont know if they both should be visible at the same time.
> 
> Might be missing phase/aura

yes and not inside another npc :)
