### ISSUE TITLE
[Event/Quest] Honor the Flame

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1593]
https://www.wowhead.com/quest=11848/honor-the-flame 
This one is in Eversong Woods but presumably all similar quests behave the same.

They award the lvl 80 reward (4gold something) of money to all levels. This is an extreme amount of money for a level 1-10 player that are questing in the area.

**Comment by sarahkay88** [comment]
I should have level her man I'm skint :)
