### ISSUE TITLE
[Quest/Order] Fairbreeze Village - Missing prerequisite

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1594]
https://www.wowhead.com/quest=9256/fairbreeze-village

How it should work: Should be unlocked by completing https://www.wowhead.com/quest=8483/the-dwarven-spy
How it works atm: currently available without prerequisite

**Comment by Echinaceax** [comment]
![now quest order](https://user-images.githubusercontent.com/39439201/56525288-10c7e880-654b-11e9-962d-c047cfaa0de8.jpg)
