### ISSUE TITLE
[Quest] King of Centaur Mountain - Northen Barrens

### ISSUE THREAD

**Issue by DiomacheTharghan** [WoWManiaUK/Blackwing-Lair#1596]
**Links:**
QUEST - https://www.wowhead.com/quest=13995/king-of-centaur-mountain
NPC - https://www.wowhead.com/npc=34634/gorgal-angerscar

**What is happening:**
Event is not starting, so it's impossible to complete the quest/kill the mobs.

**What should happen:**
Event should start as soon as you pick the quest, do a quick talk while running to the spot that engage the event, then collecting the quest objective.
https://www.youtube.com/watch?v=IO0QJBnS9OI&t=4s

**Comment by Rushor** [comment]
all fixed

![I](https://i.imgur.com/CQislq6.jpg)
![I](https://i.imgur.com/4cCaB2B.jpg)
![I](https://i.imgur.com/1VW2j2T.jpg)
![I](https://i.imgur.com/oQvRb2o.jpg)
![I](https://i.imgur.com/1gc3neL.jpg)
