### ISSUE TITLE
[Pet skills] Growl and Bite/Claw

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#16]
Testing as a blood elf hunter with their Dragonhawk pet.
None of the 2 pet abilities you start with seem to work in effect. You see them being cast on the combat log, but no effect taken.

1. Growl ability does not produce the large chunk of aggro that it should. It should make enough threat for the pet to hold aggro without problem. (currently it makes just 1 point of threat which is the base threat value of a detected spell cast that has no effect on the mob at all, i.eg. popping an aura)
http://www.wowhead.com/spell=2649/growl
2. Bite ability is expected to do damage, but it does not. It can be dodged or missed, but when it does actually "hit", it deals no damage. Also generates the same base 1 threat point.
http://www.wowhead.com/spell=17253/bite

This makes hunter pet almost useless, it does pretty much nothing but white melee swings and cannot hold aggro at all. Marking as prior.
EDIT: appears to affect other type of pets' same abilities too

**Comment by Dranah** [comment]
Equivalent of Bite for other type of pets

ID - 16827 Claw (Basic Attack) (Level 85)
=================================================
Description: Claw the enemy, causing ${$M1+(($RAP*0.40)*0.20)} damage.

uses same formula as bite

**Comment by Echinaceax** [comment]
Hunter pet still having issues with not holding aggro with growl ability, 
i recently lvled my hunter and have noticed that none of my pets are holding aggro very well, and as a Beastmaster its important that the pet holds most of the aggro while in open world
