### ISSUE TITLE
[NPC] Innkeeper Keldamyr

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#160]
Located in Teldrassil 55.52
Can`t set as home destination, no vendor option
![wowscrnshot_120418_075259](https://user-images.githubusercontent.com/20323863/49424384-b21bf100-f79a-11e8-8d9f-e200b02d74da.jpg)

**Comment by wow-mania** [comment]
Please add wowhead link to npcs when possible.

**Comment by TheSale** [comment]
https://www.wowhead.com/npc=6736/innkeeper-keldamyr
I think it is ok now

**Comment by Echinaceax** [comment]
@Rushor - reopened coz its not clickable now :)
