### ISSUE TITLE
[ITEM] Herculars Rod... - Hillsbrad

### ISSUE THREAD

**Issue by DiomacheTharghan** [WoWManiaUK/Blackwing-Lair#1602]
**Links:**
QUEST - https://www.wowhead.com/quest=28331/helculars-rod-giveth
ITEM - https://www.wowhead.com/item=63508/helculars-rod
NPC - https://www.wowhead.com/npc=48269/dark-ranger

**What is happening:**
Using item on the proper NPCs (rangers) but nothing is happening

**What should happen:**
https://www.youtube.com/watch?v=jonofaYpgfE
Should empower the Ranger as in this video

**Comment by sarahkay88** [comment]
@Rushor  #340 use to work to much and now doesn't work
