### ISSUE TITLE
[ITEM] Blackrock Orc Massive - issue2 Missing text -Redridge

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1606]
**Links:**
item - https://www.wowhead.com/item=58936/blackrock-orc-missive

**What is happening:**
item page is missing

**What should happen:**
the website says - this entire page should be in orcish, you cant understand anything on the document

**Comment by Kitzunu** [comment]
fixed, finally 
![image](https://user-images.githubusercontent.com/24550914/60498723-6e994f00-9cb7-11e9-94c8-e4f930baa305.png)
