### ISSUE TITLE
Hunter "Control Pet" Spell Issue

### ISSUE THREAD

**Issue by zingyie** [WoWManiaUK/Blackwing-Lair#1607]
**What is happening:**
I learned the Spell "Control Pet" at the Trainer. But my Spellbook says I didn't learned it, so I can't control my Pet by myself.

**What should happen:**
Fix, that I can control my pet. 

![WoWScrnShot_042219_201130](https://user-images.githubusercontent.com/49880802/56516946-094d1300-653c-11e9-86c5-871b4f8399ab.jpg)
![WoWScrnShot_042219_201125](https://user-images.githubusercontent.com/49880802/56516970-15d16b80-653c-11e9-8b45-762f35c2e862.jpg)

**Comment by Echinaceax** [comment]
Already reported #1519
