### ISSUE TITLE
[NPC] Fidelio

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#161]
``Cataclysm Patch 4.0.3a (2010-11-23): All characters now know the flight paths to their faction's capital cities, starting zone hubs, and Dalaran. ``

NPC Fidelio in Teldrassil 55.50 dont have any flight paths to offer
![wowscrnshot_120418_083208](https://user-images.githubusercontent.com/20323863/49425940-2fe1fb80-f79f-11e8-8767-cc064db07aff.jpg)

**Comment by TheSale** [comment]
I just walked to darmasus and from there flight pahts were fine,a nd when I flight back to fidelio it is okay, but it should be unlocked without to have to go to darmasus on foot

**Comment by wow-mania** [comment]
The fact that you know the path does not mean you have connecting paths. This is as is.
Ex. 1->2->3 if you are at 3 and know 1 but not 2 you do not have any connecting path.

**Comment by TheSale** [comment]
I have such high expectations so that is why I want everything to work perfectly.
if it is a problem to fix it or it is time consuming, you should put label tweaking or low priority, and reopen or revisit issue when you have time.

this is what should player get when first time visit flight master at this location. same as in goldshire (there works fine) or any other starting location
![wowscrnshot_120418_134948](https://user-images.githubusercontent.com/20323863/49443051-a0067680-f7cb-11e8-82b2-2f669f5ef018.jpg)
