### ISSUE TITLE
[Quest] Livin' the life  -  Westfall

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#1610]
**Links:**

https://www.wowhead.com/quest=26228/livin-the-life

**What is happening:**

can not be return

**What should happen:**

You should be able to return it.

![image](https://user-images.githubusercontent.com/6819293/56525702-a3688780-654b-11e9-977e-040335ffd6ff.png)

**Comment by Kitzunu** [comment]
![Screenshot_20190422_223438_com android chrome](https://user-images.githubusercontent.com/24550914/56528011-d7917780-654e-11e9-8559-4ec041694324.png)
Thats the wrong quest give ma man

**Comment by Xman993** [comment]
@Kitzunu  [Two-Shoed Lou](https://www.wowhead.com/npc=42405/two-shoed-lou) (coordinates 49.6, 19.6)  is missing. so i lvl up a second char to lvl 10. [Two-Shoed Lou](https://www.wowhead.com/npc=42405/two-shoed-lou) is there and u can get the quest from it. but after u finish teh quest, he is missing.

![image](https://user-images.githubusercontent.com/6819293/56536949-99e91a80-655f-11e9-8d80-66204530fbdd.png)

But on my sec char [Two-Shoed Lou](https://www.wowhead.com/npc=42405/two-shoed-lou) is there

![image](https://user-images.githubusercontent.com/6819293/56536402-44603e00-655e-11e9-98ec-1502bbe8137b.png)

**Comment by wow-mania** [comment]
you skipped some quest you are in the wrong phase.
you are put in the correct phase when you complete previous quests.

**Comment by Xman993** [comment]
@wow-mania i dont skip any quest. and im still in the rignt zone.  i take the quest from him and after he disappeared

**Comment by Kitzunu** [comment]
@Echinaceax @sarahkay88 one of you, please confirm this as bug or not

**Comment by Kitzunu** [comment]
And please do the quests and dont use commands

**Comment by Echinaceax** [comment]
@Kitzunu - ofc i will when i get my internet up again ...after 3ish today

**Comment by sarahkay88** [comment]
@Kitzunu I won't be able to confirm it on dev has I'm still waiting for that, but I can tell you I also did this without no issue.the quest is to be handed inside the cave straight after listening to the convo after using the item, so not only is it the wrong npc it's the wrong location.

**Comment by sarahkay88** [comment]
I actually remember that I didn't do this yesterday so I can check it on blacking and get back to you.

**Comment by sarahkay88** [comment]
@wow-mania  @Kitzunu  because I don't have dev sorted yet I went and tested this on blackwing - started at https://www.wowhead.com/quest=26213/hot-on-the-trail-the-riverpaw-clan and this is the only chain quest I did to ensure I did it in order and my results are 
![World of Warcraft 23_04_2019 14_33_15](https://user-images.githubusercontent.com/42302580/56585104-136f2000-65d5-11e9-90f8-f5647040f6bb.png)

**Comment by sarahkay88** [comment]
![World of Warcraft 23_04_2019 14_37_16](https://user-images.githubusercontent.com/42302580/56585237-58935200-65d5-11e9-9680-8e40a8ab8e1b.png)

**Comment by rzenne** [comment]
Doesn't work for me.  Really seems to be hit and miss.  My hunter could get "two shoed lou "  then received "livin' the life" go to mine use box but when you return he is not back to finish quest. My warlock can't even get him to appear to do meet two shoed lou.

**Comment by Echinaceax** [comment]
Very odd, char bug?
is there any "class" quests that could be putting you out of phase ?
as you say "its very hit and miss" @rzenne

**Comment by rzenne** [comment]
Without getting past this there is really not that many quests to do. The quests to get here really seem to be you finish one to get to the next one so can't really see a way to get out of sync.

**Comment by Echinaceax** [comment]
Can we get full info on your Warlock and Hunter @rzenne 
also are you on the newest client 1.1.0 ?

Race
hair style
hair colour
which pet used

then we can test it

**Comment by rzenne** [comment]
Yes newest client.
Human
simple
blond
nose ring
various pets

**Comment by Echinaceax** [comment]
**Reproduce steps**
- Human male 
- did quests up to going to https://www.wowhead.com/npc=42308/lieutenant-horatio-laine
- completed https://www.wowhead.com/quest=26213/hot-on-the-trail-the-riverpaw-clan
- completed **Hot On the Trail: Murlocs** (shouldnt even be here) 

then after handing in **Hot On the Trail: Murlocs** i was given the completed https://www.wowhead.com/quest=26213/hot-on-the-trail-the-riverpaw-clan again 

![complete again](https://user-images.githubusercontent.com/39439201/80992157-619a3e80-8e39-11ea-87d1-d06b2a52c530.jpg)

i completed that and then was given https://www.wowhead.com/quest=26215/meet-two-shoed-lou
_completed that_ 

then was given https://www.wowhead.com/quest=26228/livin-the-life
_completed that_
https://gyazo.com/f1f3408388280f134929e2400915353d

![completed livin](https://user-images.githubusercontent.com/39439201/80992385-b63db980-8e39-11ea-8c38-08c8f4e2e439.jpg)

and he was here without any issue

![lou here](https://user-images.githubusercontent.com/39439201/80992413-c6559900-8e39-11ea-8c8e-c8700410661d.jpg)

only issues are the quest https://www.wowhead.com/quest=26213/hot-on-the-trail-the-riverpaw-clan given 2 times 

And **Hot On the Trail: Murlocs** is not meant to be given
see here quest order http://cata.cavernoftime.com/quest=26213

(i will report quest order in a different report)

**Comment by Valiante** [comment]
This guy is still buggy, as I encountered the exact same issue as OP.  Human warrior, picked up the quest, completed the quest, but when I returned the NPC was nowhere to be found and the entire quest line can no longer be followed.
