### ISSUE TITLE
[Spell] Control Demon - 93376

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1611]
https://www.wowhead.com/spell=93376/control-demon

This is the ability warlocks learn at lvl 10 to be able to control their pet (without this, you dont have a pet bar and macros dont work for pet either)
Now, the problem is, you can't actually learn it.

Warlock trainers have a different control demon spell ID among their spells to teach you, as shown on SS: This one is '80388"
![WoWScrnShot_042219_224645](https://user-images.githubusercontent.com/31132743/56529305-d3665980-6550-11e9-9d7c-470f85a1400b.jpg)

Learning this ability does nothing. The spell you need to control your demons is still missing. because this one in the spellbook is 93376 (the one I linked)
![WoWScrnShot_042219_224707](https://user-images.githubusercontent.com/31132743/56529410-fabd2680-6550-11e9-99c6-66abaa329da4.jpg)

None of warlock trainers appear to teach this one, so you aren't able to control your pets.

**Comment by sarahkay88** [comment]
@Dranah sound similar to #1519 could be the same issue :)

**Comment by Dranah** [comment]
Yes but they are different spell IDs (and hunter and warlock version of the control demon).
They are bugged in the same manner, but probably need separate fix.

**Comment by sarahkay88** [comment]
Yea that's what I meant, you just worded it better 😂
