### ISSUE TITLE
[Quest] King of the Foulweald - ID 6621 - Ashenvale

### ISSUE THREAD

**Issue by DiomacheTharghan** [WoWManiaUK/Blackwing-Lair#1612]
**Links:**
QUEST - https://www.wowhead.com/quest=6621/king-of-the-foulweald
ITEM - https://www.wowhead.com/item=16972/senanis-banner

**What is happening:**
![WoWScrnShot_042319_003824](https://user-images.githubusercontent.com/44828921/56537221-488d5b00-6560-11e9-8bbd-57470d535636.jpg)
As you can see the banner are already there (i didn't plant them) and the mob is not spawning as it's not possible to use the quest item.

**What should happen:**
https://www.youtube.com/watch?v=Tb4PbCLxhmM
Item should trigger the event and make the NPC spawn.

**Comment by Echinaceax** [comment]
@Rushor - Seems this isnt working still, in video there are not meant to be any totems up at all, also i get a "requires a foulweald totem mound"
 
https://www.wowhead.com/quest=6621/king-of-the-foulweald#videos:id=79192

**Comment by Rushor** [comment]
okay fixed everything now

![I](https://i.imgur.com/Ku4OLms.jpg)
![I](https://i.imgur.com/nFFHYu8.jpg)

There is also an alli version of that http://cata.cavernoftime.com/quest=13989. Please open a new report for that if it's bugged.
