### ISSUE TITLE
[Quest] Mysterious Azsherite - Azshara

### ISSUE THREAD

**Issue by DiomacheTharghan** [WoWManiaUK/Blackwing-Lair#1613]
**Links:**
QUEST - https://www.wowhead.com/quest=14370/mysterious-azsharite
ITEM - https://www.wowhead.com/item=49207/azsharite-sample

**What is happening:**
It's not possible to loot the item from the crystals (Loot not available)
![WoWScrnShot_042319_165521](https://user-images.githubusercontent.com/44828921/56591302-c85f0800-65e8-11e9-950c-1cfa45f0b0f8.jpg)

**What should happen:**
Should be able to loot the crystal
https://www.youtube.com/watch?v=NDECAV9RQWM

**Comment by Echinaceax** [comment]
@Kitzunu -1/5 , i looted 6 only 1 crystal others are empty 
![empty](https://user-images.githubusercontent.com/39439201/56680023-a3d95d80-66c6-11e9-90dc-d0cf31afee56.jpg)

![empty 3](https://user-images.githubusercontent.com/39439201/56680029-a8057b00-66c6-11e9-9646-835a8757618d.jpg)
