### ISSUE TITLE
[Quest] Nine's Plan -ID 14408 - Azshara

### ISSUE THREAD

**Issue by DiomacheTharghan** [WoWManiaUK/Blackwing-Lair#1614]
**Links:**
QUEST - https://www.wowhead.com/quest=14408/nines-plan

**What is happening:**
It's not possible to ring the buzzer. You can open the dialog but there's no option to ring the buzzer that open the door and start the fight the enemy
![unknown](https://user-images.githubusercontent.com/44828921/56591856-cea1b400-65e9-11e9-8642-1f6a855ddc16.png)

**What should happen:**
https://www.youtube.com/watch?v=fggpEl_Ad6I
There should be an option to ring the buzzer

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/TM11XiK.jpg)
![I](https://i.imgur.com/4fNu7Ko.jpg)
![I](https://i.imgur.com/ysXpz8D.jpg)
