### ISSUE TITLE
[Quest] Refleshification - ID 14194 - Azshara

### ISSUE THREAD

**Issue by DiomacheTharghan** [WoWManiaUK/Blackwing-Lair#1615]
**Links:**
QUEST - https://www.wowhead.com/quest=14194/refleshification
ITEM - https://www.wowhead.com/item=48104/the-refleshifier

**What is happening:**
Mobs are getting refleshed but not working.
![WoWScrnShot_042319_172652](https://user-images.githubusercontent.com/44828921/56597713-54762d00-65f3-11e9-929d-7c38be491d3a.jpg)

**What should happen:**
Channeling should provide you the quest objective (x8)
https://www.youtube.com/watch?v=Y_HFbU2_5wU

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/2JkY5qS.jpg)
![I](https://i.imgur.com/ELVj4NF.jpg)
