### ISSUE TITLE
[Quest] Get To The Airfield - ID 25998 - Dun Morogh

### ISSUE THREAD

**Issue by Epicfirefly** [WoWManiaUK/Blackwing-Lair#1619]
**Links:**
https://www.wowhead.com/quest=25998/get-to-the-airfield
from WoWHead or our Armory

**What is happening:**
Cannot get onto aircraft

**What should happen:**
you should be able to jump onto the aircraft to take you to the airfield

**Comment by Rushor** [comment]
transport added

![I](https://i.imgur.com/tBgIgdU.jpg)
