### ISSUE TITLE
[Quest] The Relics of Wakening

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#162]
https://wow.gamepedia.com/The_Relics_of_Wakening_(quest)
Quest and objectives work fine, however Sentinel Huntress is not.
It is summoned when I entered Barrow Den, but
She do not assist me
She do not spawn mist to guide me to objectives or to exit.
She do not disappear when I leave Barrow Den and it is so annoying to have her walking around...
![wowscrnshot_120418_100907](https://user-images.githubusercontent.com/20323863/49431515-fa90da00-f7ad-11e8-816f-4dadea15db5f.jpg)

I personally don`t mind any of this I know locations of objectives, log out and in remove sentinel, and I can easy kill mobs as hunter,
but if I was priest.. and mobs walk to each other and pull 3-4-5 more mobs that would suck and wondering around looking for objectives with fast spawn rate of mobs and cleaning over and over again would be depressive for fresh players.

**Comment by wow-mania** [comment]
If it is working is fine for now. We can work on it at a later time.
