### ISSUE TITLE
[Quest] Hero's Call: Arathi Highlands - missing - Ironfordge

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1623]
**Links:**

Quest -https://www.wowhead.com/quest=28573/heros-call-arathi-highlands
NPC - https://www.wowhead.com/object=207320

**What is happening:**

Quest is not offered by the hero board in Iron forge
prevent the player from obtaining 2 further quests
**What should happen:**
When player reaches the correct level the hero board should provide the above quest.

**Comment by Kitzunu** [comment]
This works.

You can do either of these quests, not both 
![image](https://user-images.githubusercontent.com/24550914/60497834-e1a1c600-9cb5-11e9-9731-8c961c988731.png)

AND

The Battle of Thandol Span needs to be completed before being able to pick up either of the quests
![image](https://user-images.githubusercontent.com/24550914/60497896-f8481d00-9cb5-11e9-9ef0-f52b4b9c00a6.png)
