### ISSUE TITLE
[Quest/Item] Potent Murloc Pheromones- Loch Modan

### ISSUE THREAD

**Issue by Epicfirefly** [WoWManiaUK/Blackwing-Lair#1624]
**Links:**
https://www.wowhead.com/quest=26868/axis-of-awful
item - https://www.wowhead.com/item=60503/potent-murloc-pheromones
from WoWHead or our Armory

**What is happening:**
When trying to spray the pheromones on the target it instead sprays of myself 

**What should happen:**
Pheromone should spray on the targeted mosshide so that the mulocs attack him

**Comment by Rushor** [comment]
that was a nice one. fixed

![](https://i.imgur.com/ck3FoM9.jpg)
![](https://i.imgur.com/cuBrDk4.jpg)
![](https://i.imgur.com/kkBGWi1.jpg)
![](https://i.imgur.com/psJQNSo.jpg)
