### ISSUE TITLE
[Fishing/daily/Item] Arctic Char -69931-  Dun Morogh

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1628]
**Links:**
Item https://www.wowhead.com/item=69931/arctic-char
quest https://www.wowhead.com/quest=29342/cold-water-fishing

**What is happening:**
- Item not dropping / fishing 

**What should happen:**
- Item should be available if you have the fishing daily

**Comment by Rushor** [comment]
added 42.9281 chance to get the loot
