### ISSUE TITLE
[QUEST] The Moshogg Bounty - Northern Stranglethron

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1632]
**Links:**
Quest -https://www.wowhead.com/quest=26399/the-moshogg-bounty
NPC - https://www.wowhead.com/npc=42814

**What is happening:**
This quest can be picked up twice and if the item is looted twice it can also be completed twice
![World of Warcraft 24_04_2019 14_56_54](https://user-images.githubusercontent.com/42302580/56667010-e4c07a80-66a4-11e9-9fe5-1754ac8a5b6d.png)

**What should happen:**
Not sure if you are meant to get this quest twice.

**Comment by Rushor** [comment]
accordning to wowhead that seems to be correct https://www.wowhead.com/npc=44018/wulfred-harrys#starts
