### ISSUE TITLE
[Quest] Diplomacy by Another Means - ID 25044 - Southern Barrens

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1633]
**Links:**
https://www.wowhead.com/quest=25044/diplomacy-by-another-means
https://www.wowhead.com/item=49782/horn-of-challenge
from WoWHead or our Armory

**What is happening:**
when you stand in the ring to use the item to summon sabresnout nothing happens
**What should happen:**
NPC Should appear when you use the item

**Comment by Kadajj** [comment]
quest is working 100%

![WoWScrnShot_041220_141008](https://user-images.githubusercontent.com/38867875/79069607-7d417780-7cc7-11ea-93ba-f98ed334a82d.jpg)
![WoWScrnShot_041220_141015](https://user-images.githubusercontent.com/38867875/79069610-7fa3d180-7cc7-11ea-8c95-bcde1f26a46b.jpg)
![WoWScrnShot_041220_141051](https://user-images.githubusercontent.com/38867875/79069612-82062b80-7cc7-11ea-8e48-2c68ffa7a7ff.jpg)
