### ISSUE TITLE
[Quest] Clap 'Em In Irons - ID 25057 - Southern Barrens

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1634]
**Links:**
https://www.wowhead.com/quest=25057/clap-em-in-irons
from WoWHead or our Armory

**What is happening:**
when u speak to the looters it gives you no other option to do anything

**What should happen:**
when you speak to the looters you should be able to use the item on them and arrest them

**Comment by Rushor** [comment]
good fix

![](https://i.imgur.com/m90GQop.jpg)
![](https://i.imgur.com/ENM3Op1.jpg)
![](https://i.imgur.com/AhUN1jY.jpg)
