### ISSUE TITLE
[Quest] Marching On Our Stomachs - ID 25042 - Southern Barrens

### ISSUE THREAD

**Issue by Repsidian** [WoWManiaUK/Blackwing-Lair#1638]
**Links:**
https://www.wowhead.com/quest=25042/marching-on-our-stomachs
from WoWHead or our Armory

**What is happening:**
quest items dont drop from the kodo's when i kill them

**What should happen:**
when you kill a kodo it should drop a quest item

**Comment by Kitzunu** [comment]
Fixed, will send when I am home
