### ISSUE TITLE
[Object] Mailbox Lag

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Blackwing-Lair#1639]
For some reason you get "freeze" lag when you exit the Mail window.

**Comment by Kitzunu** [comment]
Can someone else confirm this please

**Comment by Rohatej** [comment]
Works fine for me, no lag/freeze issue. (My Mailbox is empty.)

**Comment by Kitzunu** [comment]
hm, mine has mail in it.

**Comment by Kitzunu** [comment]
Might just be me, checked on a Mailbox without any items now

**Comment by Kitzunu** [comment]
Rushor just confirmed it as well.
Closing
