### ISSUE TITLE
[NPC] Thundering exile -2762- Arathi Highlands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1649]
**Links:**
https://www.wowhead.com/npc=2762/thundering-exile

![immune](https://user-images.githubusercontent.com/39439201/56835531-c90bce80-6874-11e9-9db9-b3ecbc769a11.jpg)

**What is happening:**
- NPC is immune 
- cant attack them but they can attack me

**What should happen:**
- Shouldnt be immune

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/56837065-636e1100-6879-11e9-986a-359dfcc17143.png)

**Comment by Kitzunu** [comment]
>Worth nothing that they're immune to nature, shammies and druids - keep in mind.

**Comment by Echinaceax** [comment]
> Worth noting that they're immune to nature, shammies and druids - keep in mind.

Immune to nature dmg then im guessing :)
hmmm ty kitz
