### ISSUE TITLE
[Quest] Lou's Parting Thoughts

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#165]
https://www.wowhead.com/quest=26232/lous-parting-thoughts
Quest [Lou's Parting Thoughts]... some weird stuff going on here :D 
it got completed and I dont know how or why...
4 thugs were originally neutral, 
they had no health bar and they were ``invalid targets``, but after they speak and started attacking, they change to ``friendly`` and beat shit out of me and quest got completed...
![wowscrnshot_120418_160114](https://user-images.githubusercontent.com/20323863/49451588-ce8e4c80-f7df-11e8-9567-75829f88347b.jpg)
![wowscrnshot_120418_160703](https://user-images.githubusercontent.com/20323863/49451600-d4842d80-f7df-11e8-867f-716646f37322.jpg)

**Comment by wow-mania** [comment]
Yes, I know about this one. :)
Also, there are double spawns

**Comment by Echinaceax** [comment]
Still bugged :)
