### ISSUE TITLE
[NPC] Rumbling Exile -2592- Arathi Highlands 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1650]
**Links:**
https://www.wowhead.com/npc=2592/rumbling-exile

![rumbling exile](https://user-images.githubusercontent.com/39439201/56836618-28b7a900-6878-11e9-8854-2fed04ec0c0c.jpg)

**What is happening:**
- Immune
- Cant attack them 

**What should happen:**
- Should be able to attack them

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/56837096-7aacfe80-6879-11e9-8e9e-38163b3c5b57.png)

**Comment by Kitzunu** [comment]
>As many other Earth Elementals, these are immune to Nature based spells, so if you're a Elemental shammy or a Balance druid, you're going to have to use a different approach on these mobs.
