### ISSUE TITLE
[General] Cooking and fishing dailies - Reset timer issues

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1653]
**Links:**
https://www.wowhead.com/npc=42288/robby-flay

**What is happening:**
- Noticed over the last few days that the daily reset time is different on this daily than with the fishing daily in Stormwind. 

_**cooking reset timer is different than the fishing (only sometimes)
could be due to broken / missing dailies**_

note:same thing happens in Ironforge for daily there too 

**What should happen:**
- All dailies should reset same time (from when you did them)

**Comment by Rushor** [comment]
i added a pool update now - pls test now :)
