### ISSUE TITLE
[Item] Scum Covered Bag -20767- The Hinterlands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1658]
**Links:**
item - https://www.wowhead.com/item=20767/scum-covered-bag#contains
npc drop - https://www.wowhead.com/npc=2656/jade-ooze

**What is happening:**
- Bags are empty
- i got x3 bags up to now all empty

**What should happen:**
need to check the loot table

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/56983044-ff05c700-6b82-11e9-8d5e-26d191fc5fda.png)
 works

**Comment by Echinaceax** [comment]
lol @Kitzunu they ALWAYS work for you ...
mine are always empty 
Did you give yourself more than that "lucky one" haha add like 5 and see if all give :)
