### ISSUE TITLE
[Quest] The art of the pirest

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#166]
Picked up in new tinker town from Doc Cog spin the priest trainer. Quest is to use flash heal 5 times on wounded infantry, however doesn't register when heal is used.

**Comment by TheSale** [comment]
What race, or where you did quest?
I tested blood elf and human priest, and had no issue with that quest.

**Comment by wow-mania** [comment]
Please link quest and add needed info. Check wiki on how to do it.

**Comment by wow-mania** [comment]
Quest: https://www.wowhead.com/quest=26200/the-arts-of-a-priest
Quest Giver NPC: https://www.wowhead.com/npc=42323/doc-cogspin
Needed NPC: https://www.wowhead.com/npc=42501/wounded-infantry

Please add all the above info plus a description of how it is working now and how it should work. The WIKI a post on how to log an issue.

**Comment by bagi84** [comment]
Quest: https://www.wowhead.com/quest=26200/the-arts-of-a-priest
Quest Giver NPC: https://www.wowhead.com/npc=42323/doc-cogspin
Needed NPC: https://www.wowhead.com/npc=42501/wounded-infantry

this should be the quest however the quest given is to use flash heal (not shadow word pain) and on a Gnome priest this is not working correctly you can learn the spell but doesn't count when cast on the npc .

**Comment by wow-mania** [comment]
I have fixed already and tested.
