### ISSUE TITLE
[NPC] Priestess Thaalia -  Northern Stranglethorn / Fort Livingston

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1660]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=26773/see-raptor
[quest=26773]
**What is happening:**
I am suppose to talk to Priestess Thaalia and do some ritual.
However she dont let me to speek with her when i get the quest to start the ritual.
[npc=44017]

**What should happen:**
She should let me speak to her and start the ritual

**Comment by sarahkay88** [comment]
this is an npc issue  -https://www.wowhead.com/npc=44017/priestess-thaalia

**Comment by Echinaceax** [comment]
quest on bq command from here #4417
