### ISSUE TITLE
[Spell] Health Funnel

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1664]
https://www.wowhead.com/spell=755/health-funnel

**How it should work:**
Sacrifices 1% of total caster health to heal pet for 6% total pet health
Should receive spell power coefficient of 54,8% per tick (added to 6% of pet's total health) only to the pet healing portion (health taxed from owner remains fix 1%)

**How it works atm:**
Sacrifices 6% to give 6%
Does not scale with spell power anyhow.
It is very taxing for the warlock's health and much less potent for pet healing than intended.

**Comment by Dranah** [comment]
Percent conversion fixed. Spell coefficient added is now 44% instead of 54%. That needs correction.

**Comment by Keader** [comment]
Done.
If server not restarted yet, use .reload spell_bonus_data before test.

**Comment by Dranah** [comment]
Looks good.
