### ISSUE TITLE
[NPC] Arcanist Arman -49636- (Booty bay) The Cape of Stranglethorn

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1665]
**Links:**
https://www.wowhead.com/npc=49636/arcanist-arman

**What is happening:**
Seeing horde quests giver yellow (!) 

![horde quest giver](https://user-images.githubusercontent.com/39439201/56867865-3e011480-69eb-11e9-8bb8-8675f91a2799.jpg)

**What should happen:**
- As an Ally i shouldnt be able to see the yellow (!) of horde quest giver
for quest https://www.wowhead.com/quest=28750/the-battle-for-andorhal

**Comment by BlueDragonKing7** [comment]
Fix is not working, I´m a rogue Ally, can still see the quest marker over the NPC

**Comment by BlueDragonKing7** [comment]
![imagen](https://user-images.githubusercontent.com/50301953/57472920-43185c00-7254-11e9-84da-cb556a53bad8.png)

**Comment by Echinaceax** [comment]
@Kitzunu - reverted
