### ISSUE TITLE
[NPC] Gim'hila -26696- (booty bay) The Cape of Stranglethorn 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1666]
**Links:**
https://www.wowhead.com/npc=https://www.wowhead.com/quest=26696/gimhila

**What is happening:**
- As An Ally player i shouldnt see horde Quest givers yellow (!) 

![horde2](https://user-images.githubusercontent.com/39439201/56868000-e499e500-69ec-11e9-903e-5d62a6192365.jpg)

**What should happen:**
- As An Ally player i shouldnt see horde Quest givers yellow (!) 
for quest - https://www.wowhead.com/quest=26696

**Comment by sarahkay88** [comment]
there is an alliance version of this quest  - https://www.wowhead.com/quest=26596/the-call-of-kalimdor this is the one ally should see.

**Comment by BlueDragonKing7** [comment]
Fix still not working, as an ally rogue, I can still see quest marker on Gim´hila
![imagen](https://user-images.githubusercontent.com/50301953/57474736-6513dd80-7258-11e9-8dd8-b73e5684596e.png)

**Comment by sarahkay88** [comment]
@Kitzunu it's reverted again
