### ISSUE TITLE
[Spell] Soul Link

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1667]
http://www.wow-mania.com/armory/?spell=19028

The spell itself works fine as it looks, but there is a problem with mounting.

**How it should work:** The spell should disappear while mounted (as pet is not present), but should re-appear when you dismount.
**How it works atm:** The spell is permanently dispelled by mounting. You need to manually recast it each time you mount/dismount.

**Comment by Keader** [comment]
Fixed.
