### ISSUE TITLE
[Spell/NPC] Tornado

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1668]
https://www.wowhead.com/npc=42895/tornado summoned by https://www.wowhead.com/spell=80066/tornado
Cast by https://www.wowhead.com/npc=49263/zephyrus in Hillsbrad Foothills.

This NPC (tornado) should be casting another spell https://www.wowhead.com/spell=80065/tornado that should be knocking people around periodically via https://www.wowhead.com/spell=80064/tornado like a good tornado does.

How it works atm: The NPC melees for about ~1k, instakilling any lowbie that is currently fighting Zephyrus. 
How it should work: The NPC should not have a melee attack. It should only be casting the spells 80064 and 80065 to knock around people.

**Comment by Kitzunu** [comment]
Try now
