### ISSUE TITLE
[Spell] Soulstone resurrection

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1669]
https://www.wowhead.com/spell=95750/soulstone-resurrection

Cast by warlocks using a soulstone https://www.wowhead.com/item=5232/soulstone on a friendly target.

**How it should work:** 
If cast on a dead target, it should function as a battle rezz, resurrecting the dead target. Unlike other battle rezzes, this does not require an accept from the target, it instantly revives them via https://www.wowhead.com/spell=18976/self-resurrection
**How it works atm:** 
Casting SS on a dead target gives an error "target is dead" and doesn't do anything.

Note: the effect works fine on living targets, storing their soul and allowing them to rezz. Only the brez function is impaired.

**Comment by Keader** [comment]
Fixed.
