### ISSUE TITLE
[Item] Snuff -3910- The Cape of Stranglethorn

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1672]
**Links:**
https://www.wowhead.com/item=3910

**What is happening:**
- Continues to drop after you gain required amount  (15)

**What should happen:**
- should stop when you reach the required amount for the quest 
https://www.wowhead.com/quest=26613/up-to-snuff

**Comment by sarahkay88** [comment]
@kitsunu 15/15 and still dropping from bloodsail corsair https://www.wowhead.com/npc=43636/bloodsail-corsair

**Comment by Kitzunu** [comment]
Forgot to apply it :D

Will be fixed next restart

**Comment by Echinaceax** [comment]
@Kitzunu - this is fixed 
think just needed a server restart :)
