### ISSUE TITLE
[Item] Dizzy's Eye -3897- The Cape of Stranglethorn

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1673]
**Links:**
https://www.wowhead.com/item=3897

**What is happening:**
- Drops without having quest 
- Cant remember which npc tho ...there are a lot 

**What should happen:**
- Should only be lootable if you have the required quest 
https://www.wowhead.com/quest=26614/keep-an-eye-out

**Comment by sarahkay88** [comment]
@Kitzunu  lol question! which NPC is this that you fixed and that i need to test,

**Comment by Kitzunu** [comment]
All
