### ISSUE TITLE
 [Rescue OOX-17/TN!] ID 648 - Tanaris

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#1676]
**Links:**

https://www.wowhead.com/quest=648/rescue-oox-17-tn

**What is happening:**
the npc to escort going wrong waypoints and flying up in air.

https://imgur.com/a/ChQNC8o

i managed to complete the quest but it shoudnt work like that ;)

**What shoud happening**
video
https://youtu.be/P3I2qClvKDQ

**Comment by Dranah** [comment]
Well, you were lucky, to me he  simply flew away....
It seems the NPC is trying to follow the old path (toward old Steamwheedle) from LK, and does not adjust to the landscape (and path) change of cataclysm. He should stop near the Caverns of Time.

**Comment by Rushor** [comment]
yes he uses the old path

**Comment by Rushor** [comment]
finally

![](https://i.imgur.com/DuBuPQx.jpg)

path updated, cosmetic spell added
