### ISSUE TITLE
[Quest] [Warchief's Command: Tanaris!] ID 28509 Tanaris

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#1677]
**Links:**
https://www.wowhead.com/quest=28509/warchiefs-command-tanaris

**What is happening:**
Missing Npc 
https://www.wowhead.com/npc=38534/megs-dreadshredder

https://imgur.com/a/Eda3Lnd

**Comment by Echinaceax** [comment]
Npc Already reported    #424
quest Also already reported #468 

Please check report isnt already here before reporting, duplicates can cause more issues
