### ISSUE TITLE
[Quest]  [Stupid Drizle!] ID 28362 - Felwood

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#1678]
**Links:**
https://www.wowhead.com/quest=28362/stupid-drizle

**What is happening:**
Npc missing
https://www.wowhead.com/npc=47556/drizle

**Comment by Echinaceax** [comment]
Already reported #611
please check the issue isnt already here first. Duplicates can cause problems
Thanks
