### ISSUE TITLE
[Quest]Winterfall Ritual Totem ID 8471 - WinterSpring

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#1679]
**Links:**
https://www.wowhead.com/quest=8471/winterfall-ritual-totem

**What is happening:**
Cant start the quest from the item its not clickable
https://www.wowhead.com/item=20742/winterfall-ritual-totem

**Comment by Rushor** [comment]
https://www.wowhead.com/item=20742/winterfall-ritual-totem#comments:id=1444219:reply=740888

the item was removed
