### ISSUE TITLE
[Item]  [Empty Firewater Flask] ID 64353 - Winterspring

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#1683]
**Links:**
https://www.wowhead.com/item=64353/empty-firewater-flask
https://www.wowhead.com/quest=28462/winterfall-firewater

**What is happening:**
Cant use the item to start the quest

**What should happen:**

U shoud be able to use the item to start the quest

**Comment by glcabatuan** [comment]
**Quest:**  http://cata.cavernoftime.com/item=64353
**NPC/s:** 
**Item/s:**  http://cata.cavernoftime.com/quest=28462
**Object/s:** 
**Spell/s:** 

**Current State:** 
The http://cata.cavernoftime.com/quest=28462 doesn't start upon r-clicking the http://cata.cavernoftime.com/item=64353

**Expected State:** 

The http://cata.cavernoftime.com/quest=28462 should start upon r-clicking the http://cata.cavernoftime.com/item=64353

**Comment by Rushor** [comment]
thanks for the detailed work man. it helps me a lot since http://cata.cavernoftime.com is better than wowhead. i can faster fix stuff with that. thanks!

**Comment by Rushor** [comment]
https://www.wowhead.com/quest=28462/winterfall-firewater

the item sould be removed. quest is removed from game
