### ISSUE TITLE
[Item] [Blue-Feathered Necklace] ID 12558 - Winterspring

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#1684]
**Links:**

https://www.wowhead.com/item=12558/blue-feathered-necklace
https://www.wowhead.com/quest=4882/guarding-secrets
**What is happening:**
Cant use the item to start the quest

**What should happen:**
U shoud be able to use the item to start the quest

**Comment by Echinaceax** [comment]
Already reported #591

please check issue hasnt been reported before reporting issues (duplicates cause problems)
