### ISSUE TITLE
[Quest/Order] Lower the Boom - Western Plaguelands

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1690]
https://www.wowhead.com/quest=26936/lower-the-boom
Should require you to first hand in https://www.wowhead.com/quest=26978/who-needs-cauldrons
https://www.wowhead.com/quest=26933/foes-before-hoes and https://www.wowhead.com/quest=26930/after-the-crusade in order to be available.

Currently available without any prerequisites and is also autocomplete.
This causes a hell of phasing problems because this quest phases the entire area

**Comment by Rushor** [comment]
@Dranah https://www.wowhead.com/quest=26978/who-needs-cauldrons
https://www.wowhead.com/quest=26933/foes-before-hoes and https://www.wowhead.com/quest=26930 all of them need to be completed first in order to get https://www.wowhead.com/quest=26936/lower-the-boom ? right?

**Comment by Dranah** [comment]
Yes, should require all three.
