### ISSUE TITLE
[Spell] Ferocious Bite cost

### ISSUE THREAD

**Issue by Nestrior** [WoWManiaUK/Blackwing-Lair#1692]
**Links:**

https://www.wowhead.com/spell=22568/ferocious-bite#changelog

**What is happening:**

Costs up to 85 Energy. 25 base + 35 extra + 25 from somewhere?

**What should happen:**

Should cost a max of 60 Energy. 25 base + up to 35 for extra damage. 

Minor thing while leveling, but will become a bigger issue at max. Would be nice if there is someone who can give insight on higher levels, but it stands as such for the moment.

**Comment by Keader** [comment]
A old hack causing it.
Fixed.

**Comment by Dranah** [comment]
**How it works atm:** Now consumes only 50 energy (25+25) from a full energy bar to increase the damage by the full 100%.
During Clearcasting procs, the original 25 energy cost is free and the spell consumes only the 25 extra energy for the 100% damage boost.

**How it should work:** The spell should consume 60 energy for the full 100% boost (25+35).
If you have only 50 energy, it should not grant the full 100% bonus.
With clearcasting up, the spell should consume the extra 35 energy, not 25.

**Comment by mfranca0009** [comment]
This should now be fixed.

- [x] base spell consumes 25 energy
- [x] 35 extra energy spent for full 100% boost (60 points total)
- [x] While clearcasting proc is active, take extra 35 energy for 100% bonus; not 25 or both (60).

**Comment by HrafnValknutt** [comment]
Fix in Dev Confirmed
