### ISSUE TITLE
Guild members not visible in roster

### ISSUE THREAD

**Issue by Frostmanx** [WoWManiaUK/Blackwing-Lair#1694]
**What is happening:**
So some of the members that are in guild are not visible even when online in guild roster but they can chat in guild chat and have the guild tag next to their name. Even the player cannot see themselves in the guild so it not just a visual bug for me. 

![WoWScrnShot_050219_130419](https://user-images.githubusercontent.com/50195620/57061824-fbd21e80-6cdb-11e9-8f5b-957b81334c3e.jpg)

**What should happen:**

The members in the guild should be visible in roster

**Comment by Echinaceax** [comment]
@Frostmanx - did you find the answer to this issue ?

**Comment by Frostmanx** [comment]
Yes after the server had a restart it seemed to have fixed itself :) Will post again if it happens! Thanks

**Comment by Echinaceax** [comment]
> @Echinaceax Yes after the server had a restart it seemed to have fixed itself :) Will post again if it happens! Thanks

Oh thats great (just wonder why you close without saying why) 
no problem

**Comment by Frostmanx** [comment]
Sorry my bad.. next time i will be sure to mention why :) thanks
