### ISSUE TITLE
[Quest/Order] The Brashtide Crew / Sinking from Within / Making Mutiny - Cape of Stranglethorn

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1697]
https://www.wowhead.com/quest=26662/the-brashtide-crew
https://www.wowhead.com/quest=26664/making-mutiny
https://www.wowhead.com/quest=26663/sinking-from-within

These quests are available at once from https://www.wowhead.com/object=204450/captain-stillwaters-charts

However, picking up any of them closes the other two, making it impossible to complete all.

How it should work: These quests should be possible to pick up at once
How it works atm: These quests are exclusive, you can only take one of them.

**Comment by Kitzunu** [comment]
I believe when quests are shown like this you can only do one at a time.

I might be wrong?
![Screenshot_20190502_231348_com android chrome](https://user-images.githubusercontent.com/24550914/57107351-0ae2bc00-6d30-11e9-93ba-8479c42870df.png)

**Comment by Dranah** [comment]
You are wrong. It means they should be all available together. And you need to finish all 3 usually to get the next in chain.
Then again, clearly the dev putting together this core had the same thought as you... because ALL similar quests are broken in same way.

**Comment by Kitzunu** [comment]
We learn something new everyday, thanks!
