### ISSUE TITLE
[Quest] Rejuvenating Touch / A Rejuvenating Touch

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#17]
Tauren and Worgen Druid starter quest.
Quest ID 27067 and 14283.

Quests don't not grant credit for using Rejuvenation on the Wounded Braves (45199) or Wounded guards (47091) and thus cannot be completed.

**Comment by Saintres** [comment]
This is still not working for my Druid (Tauren)

**Comment by Dranah** [comment]
This report is obsolete (was from previous core)
New one open at https://github.com/WoWManiaUK/Blackwing-Lair/issues/357
