### ISSUE TITLE
[Dungeon] Zul'Farrak - not doable

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1701]
Certain mobs are unattackable in the dungeon, including the end boss, which makes it impossible to finish.

bugged mob IDs
https://www.wowhead.com/npc=5649/sandfury-blood-drinker
https://www.wowhead.com/npc=7267/chief-ukorz-sandscalp
https://www.wowhead.com/npc=7797/ruuzlu

**Comment by Kitzunu** [comment]
Fixed.
