### ISSUE TITLE
[Quest] Questioning Reethe - unscripted/autocomplete - Dustwallow Marsh

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1705]
https://www.wowhead.com/quest=27261/questioning-reethe

As the title says, the quest is currently auto completed, the event does not work.

**How it should work:**
Event in text:
>>
Ogron says: I noticed some fire on that island over there. A human, too. Let's go check it out, <name>.
(He then starts walking forward until he comes to the tree to the right of Reethe's camp.)
Ogron says: That's Reethe alright. Let's go see what he has to say, yeah?
(Ogron approaches Reethe's camp and Reethe changes to an attack stance.)
Paval Reethe says: W-what do you want? Just leave me alone...
Paval Reethe says: I swear, I didn't steal anything from you! Here, take some of my supplies, just go away!
Ogron: Just tell us what you know about the Shady Rest Inn, and I won't bash your skull in.
Paval Reethe says: I... Well, I may of taken a little thing or two from the inn... but what would an ogre care about that?
Ogron: Look here, if you don't tell me about the fire--
Paval Reethe says: Not one step closer, ogre!
Paval Reethe says: And I don't know anything about this fire of yours...
(As he speaks, a small group of Alliance soldiers spawn to the right. The group consists of Lieutenant Caldwell, Private Hallan, and two Theremore Skirmishers.)
Paval Reethe says: What was that? Did you hear something?
Lieutenant Caldwell says: Paval Reethe! Found you at last. And consorting with ogres now? No fear, even deserters and traitors are afforded some mercy.
Lieutenant Caldwell says: Private, show Lieutenant Reethe some mercy.
Private Hallan says: Gladly, sir.
(She switches to a bow, shoots him once, and switches back to her sword.)
Paval Reethe staggers backwards as the arrow lodges itself deeply in his chest.
Paval Reethe says: Ugh... Hallan, didn't think you had it in you...
Lieutenant Caldwell says: Now, let's clean up the rest of the trash, men!
Ogron says: Damn it! You'd better not die on me, human!
(The group of Alliance soldiers aggro. If/when you kill them all, the scene continues, though Reethe is no longer in an attacking stance towards Ogron.)
Ogron says: Still with us, Reethe?
Paval Reethe says: Must be your lucky day. Alright, I'll talk. Just leave me alone. Look, you're not going to believe me, but it wa... oh, Light, looks like the girl could shoot...
(Paval Reethe falls over dead at this point.)
Ogron says: Looks dead to me. Not much use to us like this. You'd better go back and tell Krog what happened.
Ogron says: By the way, thanks for watching my back.

Vid: https://www.youtube.com/watch?v=YkEmxw160wY&feature=youtu.be

**Comment by Rushor** [comment]
all fixed

take the quest at the ogre and all will start. kill the guards once they turn hostile and the quest will be completed.

![I](https://i.imgur.com/t8zybhO.jpg)
![I](https://i.imgur.com/7fCVINc.jpg)
![I](https://i.imgur.com/fVjT3SI.jpg)
