### ISSUE TITLE
[Quest] Through the troll hole - 26811 - Cape of Stranglethorn

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1706]
**Links:**

quest - https://www.wowhead.com/quest=26811/through-the-troll-hole
Portal NPC - https://www.wowhead.com/npc=43253/troll-hole-credit

**What is happening:**
No portal to pass through

**What should happen:**
should be a portal that takes the player to the required location to complete the quest

**Comment by jarvik76** [comment]
Confirmed still an issue at Sept 18th
