### ISSUE TITLE
[Item] Reputation City Tabard`s

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#171]
https://www.wowhead.com/item=118365/stormwind-tabard
I run Stockade dungeon 3 times, I was lvl 30 while all mobs were 23-25lvl and all give experience to me.
I was lazy to test other tabards, but I might do that later.
The issue was that I did not get reputation... 
I am too low level and undergeared to test it earlier or to try with some higher level dungeons atm where mobs are yellow and red, but this should work also...

edit:
I just tried exodar and darmasus tabard in stockade and it is same  thing...

**Comment by Dranah** [comment]
https://www.wowhead.com/item=45574/stormwind-tabard this is the correct ID for the tabard
There is a blizzlike bug on cataclysm that Outland dungeons gave no rep with these tabards, but Stockades definitely should.
mafcallow on 2011/01/30 (Patch 4.0.3)
Stockade runs give about 500 rep each with this tabard, assuming a full clear. Take about 3-5mins per run, depending on class, spec and level

**Comment by Keader** [comment]
Fixed.

**Comment by Dranah** [comment]
Still not getting any rep

**Comment by Keader** [comment]
I can confirm it, items are fixed.
You cant get reputation is not same issue.
Check that you cant get reputation even without tabard.
Tabards is fixed, not getting reputation is other issue.

**Comment by Dranah** [comment]
Getting rep in low dungeons requires having the tabard.
So its no tabard = no rep, yes tabard = yes rep.
So what else could be responsible for not getting rep?

**Comment by Dranah** [comment]
Can confirm the tabards are now able to convert lvl 80 northrend dungeon's native reputation to the faction you wear tabard with. What needs fixing is the rep from Azeroth dungeons (and probably cata ones, but those are closed atm so can't test)

In azeroth/cata dungeons, if the mobs are in appropriate level range (not grey), you get 15 per trash and around 315 for bosses. Higher quality elites sometimes reward more, like 30-50.
If the mobs are below your level (grey), its 3 per trash and 60 rep for bosses.
Northrend level 80 dungeons give their regular rep numbers but converted to the faction you have tabard with. (this part already works)

Sources: https://wowwiki.fandom.com/wiki/Tabard
https://www.wowhead.com/item=45574/stormwind-tabard#comments

**Comment by Keader** [comment]
The issue is not tabard, is missing data.
I'm open a new issue about it.

**Comment by Dranah** [comment]
Ok the tabard itself works.
