### ISSUE TITLE
[Quest] Down with Crushcog!

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Blackwing-Lair#1715]
https://www.wowhead.com/quest=26364/down-with-crushcog

How it works:

When you are to speak with High Tinker Mekkatorque the gossip does nothing

How it should work:

Speaking with him should start an event
Shown here https://www.wowhead.com/quest=26364/down-with-crushcog#videos:id=66402

ATM this quest makes you unable to progress as gnome

**Comment by Rushor** [comment]
basic event added, more to come later

![](https://i.imgur.com/iJIhZCb.jpg)
