### ISSUE TITLE
[npc=99776] Druid trainer  Ironforge

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#1717]
**Links:**
https://www.wowhead.com/npc=99776/dareth
from WoWHead or our Armory

**What is happening:**
This trainer dont offer any training only reset my talents.

**What should happen:**
He should offer training for Druids

**Comment by Kitzunu** [comment]
fixed

**Comment by Echinaceax** [comment]
@Kitzunu - both offer training 

![both are training](https://user-images.githubusercontent.com/39439201/57192842-469aa300-6f35-11e9-87e2-64f2ba2a2939.jpg)

**Comment by Kitzunu** [comment]
fixed
