### ISSUE TITLE
[Quest/Interaction] The Black Shield - ID 27254 and 27252

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1718]
https://www.wowhead.com/quest=27252/the-black-shield = ALLY
https://www.wowhead.com/quest=27254/the-black-shield = HORDE

Currently both are available to pick up by both factions from https://www.wowhead.com/object=20992/black-shield, when only the respective faction version should be given.

**Comment by Kitzunu** [comment]
Fixed
