### ISSUE TITLE
[Dungeon] The Stockade

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#172]
https://www.wowhead.com/the-stockade#drops
I run this 3 times with enh shaman lvl 30, it was pain but I wanted to test.
All mobs were lvl 23-25, I died few times, it is not problem when I have 2-3 mobs at the time, but when there is 5-6-7... damn that sux.... I survive long enough to kill at least 1 or 2, then I can revive and finish clearing.
I am not sure if dungeon was the problem or tabard, but I did not gain reputation with stormwind tabard equipped. I have posted that as separated problem, but I mention it just if the tabard is not issue.

The issue is drop from bosses.
https://www.wowhead.com/npc=46254/hogger
https://www.wowhead.com/npc=46264/lord-overheat
https://www.wowhead.com/npc=46383/randolph-moloch

From 3 runs sample, Hogger did not drop anything so far.
Lord overheat dropped first and second time item, third time just quest item.
Randolph moloch dropped just in second run...

1 more run and only Randolph dropped item
and 5th run same result as last only drop from Randolph

and I dont know will rdf work, I am all alone there :D

**Comment by wow-mania** [comment]
Fixed loot. Mobs are as is. You are not meant to solo this at lvl 30.

**Comment by TheSale** [comment]
I did not ment to nerf mobs, I was kinda saying I hope I had someone to paly with, soloing is hard :D lol

**Comment by TheSale** [comment]
I just did 1 more run, Hogger dropped item, nice, but randolph did not.
I will try later once more, I am in mess right now, getting ready for trip.

![wowscrnshot_120518_180037](https://user-images.githubusercontent.com/20323863/49530955-8b081100-f8b9-11e8-8997-aa30f8fba4d6.jpg)
