### ISSUE TITLE
[Quest] Clamlette Surprise - auto complete - Tanaris

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1720]
https://www.wowhead.com/quest=6610/clamlette-surprise

Currently auto completed when you pick it up , has no text or instructions.

How it should work: 

"Dirge Quikcleave wants you to get the following items:

10 Giant Eggs. You will find those on the Rocs wandering Tanaris or any other species of large bird.

10 pieces of Zesty Clam Meat. You can find those in clams, naturally!

20 pieces of Fine Aged Cheddar. Get thee to a cheesery!

Gather all of the items and return to Dirge. 

Giant Egg (10)
Zesty Clam Meat (10)
Fine Aged Cheddar (20)
"

Should require these components to gather.

**Comment by sarahkay88** [comment]
@Kitzunu this still auto complete - however you can no longer receive it without the required profession
