### ISSUE TITLE
Portal: Tol Barad Requires level 96 at portal trainer

### ISSUE THREAD

**Issue by z1179** [WoWManiaUK/Blackwing-Lair#1721]
**links**
https://www.wowhead.com/spell=88345/portal-tol-barad

**Whats happening** 
- Tol Barad spell requires one to be level 96 at the portal trainer, 

**What should happen**
- should be 85

**Comment by Kitzunu** [comment]
96 in Cataclysm, that's something new O.o

**Comment by Kitzunu** [comment]
Fixed

**Comment by Echinaceax** [comment]
![tol barad](https://user-images.githubusercontent.com/39439201/57193249-51efcd80-6f39-11e9-91df-3e1c9e745f91.jpg)
