### ISSUE TITLE
[NPC] Spirit healer - Fire plume ridge

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1722]
**Links:**
https://www.wowhead.com/npc=6491/spirit-healer

**What is happening:**
- broken does rez

**What should happen:**
- should res with sickness

**Comment by Kitzunu** [comment]
2 things.

What is happening?

where is the NPC?

**Comment by Echinaceax** [comment]
@Kitzunu - sorry forgot to add SS :)
![sp heal broken](https://user-images.githubusercontent.com/39439201/57183364-502bf880-6eac-11e9-879d-15456e88f268.jpg)

I got the pop up screen as normal but when i clicked it it didnt nothing ...but then i couldnt run back to my body either coz it was through server crash it happened

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/57192270-d38e2e00-6f2e-11e9-8b5d-b357dc2ca99b.png)
