### ISSUE TITLE
[Spell/druid] Leather Specialization

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1723]
**Links:**
https://www.wowhead.com/spell=178976/leather-specialization

![leather](https://user-images.githubusercontent.com/39439201/57182742-ff63d200-6ea2-11e9-8fdf-6667d6bf5366.jpg)

**What is happening:**
- Both trainers stormwind and moonglade 

**What should happen:**
- should have same spell ID 

@Keader - seems the spell ids are different , 
spell book - 86530
trainer - 86092

**Comment by Echinaceax** [comment]
@Kitzunu - there is 2 spells now different ID's 
![leather sp  trainer](https://user-images.githubusercontent.com/39439201/57191659-5fe92280-6f28-11e9-8011-52fa8378abf4.jpg)

**Comment by Kitzunu** [comment]
Fixed
