### ISSUE TITLE
[Quest/Order] Are We There Yeti? / The Perfect Horns - Winterspring

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1724]
https://www.wowhead.com/quest=28629/are-we-there-yeti
https://www.wowhead.com/quest=28631/the-perfect-horns
from NPC https://www.wowhead.com/npc=10305/umi-rumplesnicker
These two quests should be available and possible to complete at once.
Currently you can only pick one, it closes the other, they are exclusive.

**Comment by Kitzunu** [comment]
F
I
X
E
D

**Comment by Dranah** [comment]
None of the quests are available at all now.

**Comment by Echinaceax** [comment]
![pre](https://user-images.githubusercontent.com/39439201/57193671-0e4b9280-6f3e-11e9-8d8d-478ee2ea174d.jpg)
