### ISSUE TITLE
[Spell] Weapon skills

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1725]
ID 76299 (lock) > Swords do not work
ID 76298 (mage) > Swords and daggers do not work!
ID 76301 (priest) > Daggers do not work

As stated above, some of the weapon skills that are granted by these spells are not working. This bug affects Warlocks, Mages and Priests as far as we tested, couldn't find an issue on other classes.
They simply can't equip some of the weapon types they should be able. (not visual problem)

**Comment by Keader** [comment]
i wonder if some of those spells is working...
Complete list:

![image](https://user-images.githubusercontent.com/7120913/57554928-21e56780-7349-11e9-9ad7-1f623c7a37ba.png)

**Comment by Dranah** [comment]
There have been no issues on other classes so far. I tested rogue and druid specifically, those have all weapons working as intended.

**Comment by Keader** [comment]
ok, so fixed.
