### ISSUE TITLE
[Spell] Plate Specialization - 86525 - paladin

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1726]
spell ID 86525 >> This is the spell that paladins have in their spellbook and need to learn.

But the trainers teach wrong ID. They teach ID 87511 instead, which does not give you the ability you need.

**How it should work:** Paladin trainers need to teach the correct spell ID (86525)
ID 87511 must not be taught

**Comment by Kitzunu** [comment]
Fixed
