### ISSUE TITLE
[Talent] Impact (Fire Mage)

### ISSUE THREAD

**Issue by Hitolol** [WoWManiaUK/Blackwing-Lair#173]
Impact Rank 2/2 (Spellid: 12357):
Gives your damaging spells a 10% chance to reset the cooldown on Fire Blast and to cause the next Fire Blast you cast to stun the target for 2 sec and **spread any Fire damage over time effects to nearby enemy targets within 12 yards.**

The Impact proc and Stun is working fine but nothing is spread to nearby enemy targets within 12 yards.

**Comment by Dranah** [comment]
Server crashes if you have a DoT on target and attempt to spread it to nearby mobs with Impact.

**Comment by Keader** [comment]
What DOT you used to force it?

**Comment by Keader** [comment]
I found why.
Caused by Living Bomb.
Fixed.

**Comment by Dranah** [comment]
Works good now.
