### ISSUE TITLE
Abyssal Breach not functioning as a teleport to the area with the Throne of the tides portal

### ISSUE THREAD

**Issue by z1179** [WoWManiaUK/Blackwing-Lair#1731]
**Links:**

from WoWHead or our Armory

**What is happening:**
whilst attempting to travel to the area that lies before the Throne of the Tides dungeon there is no threshold that teleports you to the area like there should be (in the vortex of the abyssal breach in vash'jir)

**What should happen:**
Should be teleported when you try to enter the massive swirling vortex in vash'jir. You should be teleported to an area that has the throne of the tides entrance in it ,aswell as an unused entrance to the abyssal maw (that is currently being used in legion i believe)

**Comment by Kitzunu** [comment]
Do you have a screenshot?

**Comment by z1179** [comment]
https://gyazo.com/e04def17c9bc4b0cacc9048a533f840b

**Comment by z1179** [comment]
that is the vortex in question, i dont have a screenshot on the other side as i cannot get there without Rdf

**Comment by Dranah** [comment]
While this problem isn't directly inside the dungeon, if it affects players ability to approach the instance, it should be fixed with priority before the release of throne of the tides.

**Comment by Keader** [comment]
Fixed.
