### ISSUE TITLE
[quest] - double spawns -Mount Hyjal

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1737]
**Links:**

https://www.wowhead.com/quest=25268/the-voice-of-goldrinn x2
https://www.wowhead.com/quest=25271/goldrinns-ferocity x2
https://www.wowhead.com/quest=25273/lycanthoth-the-corruptor
 x2
https://www.wowhead.com/quest=25352/sweeping-the-shelf x2
https://www.wowhead.com/quest=25355/lightning-in-a-bottle x2
https://www.wowhead.com/quest=25279/the-shrine-reclaimed x2
https://www.wowhead.com/quest=30078/cleaning-house x2

NPC-https://www.wowhead.com/npc=39433/ian-duran
NPC -https://www.wowhead.com/npc=39432/takrik-ragehowl

**What is happening:**

I could collect and complete these quest twice, not 100% sure but I think its because you can also take the horde quests - 

**What should happen:**
Shouldn't be able to double complete quests.

**Comment by sarahkay88** [comment]
![World of Warcraft 05_05_2019 18_54_36](https://user-images.githubusercontent.com/42302580/57198129-41564c00-6f67-11e9-879a-06971d68c6ab.png)

**Comment by Kitzunu** [comment]
It's an issue of that you can pick up the both faction's quests

**Comment by Kitzunu** [comment]
Fixed.

Cleaning House is as-is, it is a double faction quest.

**Comment by sarahkay88** [comment]
Yup. I could. Pick them all up and complete and hand them in. Same for the   cleaning house. Therefore I got xp and gold x2
