### ISSUE TITLE
[Quest] Emerald Allies

### ISSUE THREAD

**Issue by Hitolol** [WoWManiaUK/Blackwing-Lair#174]
Emerald Allies:
Speak to Alysra at the Ruins of Lar'donir in Mount Hyjal.

Issue:
Alysra is off position and the Quest can not be finished / you can not interact with Alysra.

First Picture is her current position, second one where she is supposed to be.
[https://imgur.com/a/OowIJ3o](url)

**Comment by wow-mania** [comment]
Please link quests and npcs.
You can also get id for quest items and npcs with an an ID addon.

**Comment by wow-mania** [comment]
https://www.wowhead.com/quest=25430/emerald-allies
https://www.wowhead.com/npc=38917/alysra

**Comment by 3JIoudyx** [comment]
Alysra is now hostile and the quest isn't flagged as bugged so you can't use "bq questID".
![WoWScrnShot_060419_005957](https://user-images.githubusercontent.com/51344085/58837760-ce6eec80-865c-11e9-935c-8cf68f0590fd.jpg)
