### ISSUE TITLE
[NPC] Hovel Brute - Mount Hyjal

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1742]
**Links:**
https://www.wowhead.com/npc=39642/hovel-brute

**What is happening:**
triples spawned standing in packs of 3

**What should happen:**

shouldn't be so many

**Comment by Echinaceax** [comment]
@Kitzunu - still needs more "spacing" the are still in packs of 3s 
i took GM off and they all growled and attacked me 

![3s](https://user-images.githubusercontent.com/39439201/57217873-1d8d1780-6ff4-11e9-925e-485a89178349.jpg)
