### ISSUE TITLE
Divine Storm does not generate Holy Power.

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Blackwing-Lair#1743]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/607 Former fixed issue regarding a problem with same spell.
https://www.wowhead.com/spell=53385/divine-storm spell link

What is happening: When used against 4 or more opponents the spell does not generate "Holy Power"

What should happen:  When used against 4 or more opponents the spell should generate "Holy Power"

To replicate it, create a ret paladin, take the 2nd tier talent "Divine Storm", use it on 4 or more adds.

**Comment by Dranah** [comment]
Something has been reverted here, because it worked fine when I tested.

**Comment by Keader** [comment]
Janitor dont has it anymore, idk who removed it.
Well, i need re-fix it, because i dont have it anymore too.

**Comment by Keader** [comment]
Fixed.
