### ISSUE TITLE
Cataclysm Zone Mob XP

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1745]
Here are the mob XP formulas from wiki

XP = (Char Level * 5) + 45, where Char Level = Mob Level, for mobs in Azeroth
XP = (Char Level * 5) + 235, where Char Level = Mob Level, for mobs in Outland
XP = (Char Level * 5) + 580, where Char Level = Mob Level, for mobs in Northrend
**XP = (Char Level * 5) + 1878, where Char Level = Mob Level, for mobs in Cataclysm**

With that calculation, a level 80 player killing a level 80 mob in a cataclysm zone would receive  2278 exp on x1 rates,, 9,1k  with x2 + double xp weekend and 27k+ with x12 VIP.

Currently players experience that with the weekend x4 exp they get about 2-3k, and even the vip guys with x12 only get 7-10k depending on zone and char level.

The cataclysm formula must apply in cata zones, I think currently it uses one of the lesser formulas.

**Comment by sarahkay88** [comment]
currently in twilight highland lvl 84 n for a mob with vip xp 6 n double xp weekend im getting 5580ish xp
![World of Warcraft 05_05_2019 21_17_02](https://user-images.githubusercontent.com/42302580/57199981-6ce43100-6f7d-11e9-9faf-337ab7a683b9.png)

**Comment by Echinaceax** [comment]
Currently in Zul'Drak with vip xp 6 n double xp weekend im getting 10164 xp

![kills](https://user-images.githubusercontent.com/39439201/57201131-dd4a7c80-6f94-11e9-9554-4180593ee248.jpg)

**Comment by Rushor** [comment]
calculation in core is like this:

```
switch (content)
            {
                case CONTENT_1_60:
                    nBaseExp = 45;
                    break;
                case CONTENT_61_70:
                    nBaseExp = 235;
                    break;
                case CONTENT_71_80:
                    nBaseExp = 580;
                    break;
                case CONTENT_81_85:
                    nBaseExp = 1878;
                    break;
                default:
                    TC_LOG_ERROR("misc", "BaseGain: Unsupported content level %u", content);
                    nBaseExp = 45;
                    break;
            }
```

```
if (sWorld->getIntConfig(CONFIG_MIN_CREATURE_SCALED_XP_RATIO))
            {
                // Use mob level instead of player level to avoid overscaling on gain in a min is enforced
                uint32 baseGainMin = (mob_level * 5 + nBaseExp) * sWorld->getIntConfig(CONFIG_MIN_CREATURE_SCALED_XP_RATIO) / 100;
                baseGain = std::max(baseGainMin, baseGain);
            }
```

**Comment by Keader** [comment]
I wonder how janitor scripted it.
If is a edit in KillRewarder.cpp, Player.cpp, or some player script on hooks: OnBaseGainCalculation or OnGivePlayerXP ._.

**Comment by Keader** [comment]
that last part (https://github.com/WoWManiaUK/Blackwing-Lair/issues/1745#issuecomment-489595088), only will run if CONFIG_MIN_CREATURE_SCALED_XP_RATIO is active.
If is not, use those too:

if mob level > player level:

```
baseGain = ((pl_level * 5 + nBaseExp) * (20 + nLevelDiff) / 10 + 1) / 2;
```
where nLevelDiff = mob_level - player_level

if is mob level < playerLevel and is not grey yet:

```
baseGain = (pl_level * 5 + nBaseExp) * (ZD + mob_level - pl_level) / ZD;
```

where ZD = zone level difference

**Comment by Keader** [comment]
Test now please.

**Comment by Dranah** [comment]
Nope, still too low. Dev is on default exp x1, here are my tests:
Lvl 84 in Twilight vs Lvl 84 mob, the expected XP is:
84x5+1878= 2298
Actual exp: 465
Testing as a lvl 83 in Uldum vs lvl 83 mob, the expected xp is:
83x5+ 1878 = 2293
Actual exp: 460

It seems it still uses the vanilla formula. 84x5 + 45 = 465, 83x5 +45=460.

**Comment by Keader** [comment]
Any specific region @Dranah ?!

Some dbcs files is fucked in Cata, like Hyjal is not considered cata zone haha. My fix includes hyjal too.
I tested in some cata zones, and XP looks fine.

![image](https://user-images.githubusercontent.com/7120913/57298948-d6615e00-70a9-11e9-943c-a2fdeeb8489a.png)

Tell me where you are testing, to check if is something wrong with this area.

**Comment by Dranah** [comment]
Ok, zones that work fine after last test: Hyjal, Deepholme and dungeons inside.
Zones still using wrong formula: Twilight Highlands, Uldum, Vashj'ir,

**Comment by Dranah** [comment]
Tested: TH, Uldum and Vashj'ir now give proper exp. I think everything is covered but if not, we'll find out later.

**Comment by Echinaceax** [comment]
@Keader - Uldum isnt scaling (x2 plus x6 vip x double weekend) doesnt add up 

![Grrrr](https://user-images.githubusercontent.com/39439201/57516001-26435d80-7314-11e9-95aa-695746669fb1.jpg)

**Comment by Dranah** [comment]
Weird, it gives me proper exp in Uldum.
I get 9k off those skeletons with no vip, no rested and no weekend.

**Comment by Echinaceax** [comment]
> Weird, it gives me proper exp in Uldum.
> I get 9k off those skeletons with no vip, no rested and no weekend.
> PS: i think u tested on live realm before janitor copied/released it

Maybe - coz i added this update about 2 days ago (wasnt working when i posted)
