### ISSUE TITLE
[Quest] The Last Wave of Survivors - missing npcs - Darkshore

### ISSUE THREAD

**Issue by BlueDragonKing7** [WoWManiaUK/Blackwing-Lair#1747]
**Links:**
NPC - https://www.wowhead.com/npc=32973/dentaria-silverglade
QUEST - https://www.wowhead.com/quest=13518/the-last-wave-of-survivors

from WoWHead

**What is happening:**
You reach the quest area/zone, but it´s missing the four NPCs that one has to rescue.

Cerellean Whiteclaw - https://www.wowhead.com/npc=33093/cerellean-whiteclaw
Gershala Nightwhisper - https://www.wowhead.com/npc=32911/gershala-nightwhisper
Shaldyn - https://www.wowhead.com/npc=33095/shaldyn
Volcor - https://www.wowhead.com/npc=33094/volcor

**What should happen:**
You reach the quest area/zone, and we should see the four NPCs that one has to rescue.

**Comment by Rushor** [comment]
![](https://i.imgur.com/g0gL616.jpg)

**Comment by Rushor** [comment]
same with all the other npcs that are required
