### ISSUE TITLE
[Item] Grovekeeper´s Incense - Not working- Darkshore

### ISSUE THREAD

**Issue by BlueDragonKing7** [WoWManiaUK/Blackwing-Lair#1748]
**Links:**
Quest - https://www.wowhead.com/quest=13569/the-ritual-bond#screenshots
NPC - https://www.wowhead.com/npc=33048/keeper-karithus
ITEM - https://www.wowhead.com/object=194771/grovekeepers-incense

from WoWHead or our Armory

**What is happening:**
The item appears, but when you interact only a message appears but no effect what so ever towards the quest.

**What should happen:**
One should be able to interact with the incense, and then speak with one of the spirits that apper so one can complete the quest.

**Comment by Rushor** [comment]
duplicate https://github.com/WoWManiaUK/Blackwing-Lair/issues/2071
