### ISSUE TITLE
[Quest] Elementary!

### ISSUE THREAD

**Issue by Hitolol** [WoWManiaUK/Blackwing-Lair#175]
Elementary!
Activate the four nearby elemental crucibles in the correct order to take control of the Eye of Twilight.

Issue:
You cant interact/activate the elemental crucibles.
Also there are two types of Named Mobs in the cave, Gar'gol and The Manipulator.
They spawn multiple times as seen in the second screenshot (in General there is a lot of multiple spawning of Mobs around that Area.)
[https://imgur.com/a/NKtmFnF](url)

**Comment by wow-mania** [comment]
Please always link mobs, quest, items, spells etc.
