### ISSUE TITLE
[NPC] Beth'Tilac - Firelands

### ISSUE THREAD

**Issue by z1179** [WoWManiaUK/Blackwing-Lair#1751]
**Links:**
npc https://www.wowhead.com/npc=52498/bethtilac
loot table 10man - https://www.wowhead.com/npc=52498/bethtilac#drops:mode=h10

from WoWHead or our Armory

**What is happening:**
The first boss in the firelands raid Beth'Tilac does not fight back, and the loot table is also overdropping
Loot was : https://gyazo.com/fa17ec6d778f57c7f6e3282c8a481f5e

**What should happen:**
bethtilac should atleast fight back even if the fight is tank and spank.

**Comment by Dranah** [comment]
The raid is now closed and won't be worked on until the next stage of progression.
