### ISSUE TITLE
[Dungeon] Well of Eternity 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1755]
**Links:**
https://www.wowhead.com/well-of-eternity

**What is happening:**
- Empty (no mobs) 

**What should happen:**
should be a working dungeon with mobs to kill :)

Reported by player Khranus

**Comment by Dranah** [comment]
This dungeon must not be released before Dragon Soul
Means it should stay closed and not be worked on yet.
