### ISSUE TITLE
[Raid] Blackwing Descent

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1757]
**Links:**
https://www.wowhead.com/blackwing-descent

**What is happening:**
- Mob damage low 
_adds at Omnitron defence system does only like 200 damage and the  omnitron defense system does  not attack back_

**What should happen:**
damage need increasing 

reported by player Zetsu

**Comment by Dranah** [comment]
The raid is closed now as per Jani. We'll be working on this soon so I'll leave this report open but please put every separate NPC and mechanism issue into separate reports, with the labels DUNGEON and add BWD to title.

**Comment by Kitzunu** [comment]
It is a PvP server, spells always have prio over raids.

**Comment by Rushor** [comment]
moved to https://github.com/WoWManiaUK/Blackwing-Lair/issues/3086 since i fix all at once
