### ISSUE TITLE
[Quest] The Fires of Mount Hyjal

### ISSUE THREAD

**Issue by Vastdog** [WoWManiaUK/Blackwing-Lair#176]
The Fires of Mount Hyjal:
Speak with Laina Nightsky near the Grove of Aessina in Hyjal.

Issue:
Laina Nightsky is no where to be found and all the other NPCs in the are are also gone. I was unable to complete some quests prior to this chain due to some issues, so possibly I am just not phased into the area yet.

**Comment by wow-mania** [comment]
The creature is there you probably skipped quests that change your phase. Or have applied some GM shortcuts and skipped some steps.

**Comment by Vastdog** [comment]
Hello Janitor,

Understood, thank you. I will try to get through the chain later tonight.

Kind regards,

Vast

On Dec 8, 2018, at 6:15 AM, Janitor <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #176<https://github.com/WoWManiaUK/Blackwing-Lair/issues/176>.

**Comment by Sammy974** [comment]
That quest is available but the phasing depends from other quests already bugged, not "skipped".

**Comment by hediunchained** [comment]
I have done the quests in order as per the official guide 
https://wowwiki.fandom.com/wiki/Mount_Hyjal_quests
and still both https://wowwiki.fandom.com/wiki/Quest:A_Prayer_and_a_Wing and https://wowwiki.fandom.com/wiki/Quest:The_Fires_of_Mount_Hyjal still experience phase problems

**Comment by Rushor** [comment]
The creatue is in phase 169 now
