### ISSUE TITLE
[Item] Elune´s Tear - Not Working - Ashenvale

### ISSUE THREAD

**Issue by BlueDragonKing7** [WoWManiaUK/Blackwing-Lair#1762]
**Links:**
Quest - https://www.wowhead.com/quest=13919/a-trip-to-the-moonwell
Item - https://www.wowhead.com/item=46389/elunes-tear
from WoWHead or our Armory

**What is happening:**
Once reached the moonwell the item does not interact properly with the well

**What should happen:**
The item should interact in the vecinity of the well, enabling progression on the quest

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/VrB5vOG.jpg)
