### ISSUE TITLE
[NPC] Warsong Shredder - Not working - Ashenvale

### ISSUE THREAD

**Issue by BlueDragonKing7** [WoWManiaUK/Blackwing-Lair#1763]
**Links:**
Quest -  https://www.wowhead.com/quest=13698/explosives-shredding
NPC - https://www.wowhead.com/npc=33706/warsong-shredder
from WoWHead or our Armory

**What is happening:**
I´m trying to interact with the NPC, but nothing happens.

**What should happen:**
I should be able to interact with the NPC and the destroy the explosives with its skills.

**Comment by Rushor** [comment]
finally fixed

![I](https://i.imgur.com/hzsnCer.jpg)
![I](https://i.imgur.com/ElqYar6.jpg)
