### ISSUE TITLE
[Item] Undercity Satchel -67529-

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1764]
**Links:**
https://www.wowhead.com/item=67529/undercity-satchel
https://www.wowhead.com/npc=50304/captain-donald-adams
**What is happening:**

Can buy this sactchel without having required rep
**What should happen:**

shouldn't be available without rep

**Comment by Echinaceax** [comment]
@rusher reverted some how 

![undercity scatchel](https://user-images.githubusercontent.com/39439201/62466955-e95ff900-b792-11e9-8151-e31cea8421ee.jpg)

**Comment by Kitzunu** [comment]
is it like this on live too?

**Comment by Echinaceax** [comment]
@Kitzunu yes it was reported on #2988

**Comment by Rushor** [comment]
kay refixed that. item will only be shown if rep is reverted or exalted.

**Comment by Echinaceax** [comment]
needs revered @Rushor :)
