### ISSUE TITLE
[NPC/Loot] Rom'ogg Bonecrusher - Blackrock Caverns

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1772]
**Links:**
https://www.wowhead.com/npc=39665/romogg-bonecrusher

https://www.wowhead.com/item=55777/torturers-mercy&bonus=4142
https://www.wowhead.com/item=55777/torturers-mercy&bonus=4198

![drops br nomal 5](https://user-images.githubusercontent.com/39439201/57333422-1ca3d500-711d-11e9-9726-9f3763aaaa74.jpg)

**What is happening:**
dropping both nm and hc at same time 

**What should happen:**
on normal mode he should only drop normal loot not Hc

**Comment by Dranah** [comment]
This is not fixed. Still drops heroic on normal mode.

**Comment by Dranah** [comment]
Ok after jani last fix its good now.

**Comment by Echinaceax** [comment]
> Ok after jani last fix its good now.

nope its not apparently #1941

**Comment by Dranah** [comment]
Janitor successfully reverted his fix again. Sigh.

**Comment by Dranah** [comment]
Fix was reapplied and immediately pushed to live.
