### ISSUE TITLE
[Item] Bloodtooth Banner - not working - Ashenvale

### ISSUE THREAD

**Issue by BlueDragonKing7** [WoWManiaUK/Blackwing-Lair#1773]
**Links:**
Quest - https://www.wowhead.com/quest=13989/king-of-the-foulweald
Item - https://www.wowhead.com/item=46777/bloodtooth-banner
 NPC - https://www.wowhead.com/npc=12918/chief-murgut
from WoWHead

**What is happening:**
Item does not summon the NPC required to slay

**What should happen:**
Item should summon NPC Chief Murgut to be killed

**Comment by Rushor** [comment]
ahh that was the one i was searching. so the horde part works. alliance not

**Comment by Rushor** [comment]
all fixed. horde and alliance part is working now.

![I](https://i.imgur.com/gUV4diN.jpg)

Cheers.
