### ISSUE TITLE
[Item] Strange Bloated Stomach

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#1776]
**Links:**

https://www.wowhead.com/item=67495/strange-bloated-stomach

**What is happening:**

right click to open isnt giving any loot what so ever

**What should happen:**

should be giving loot :)
they contain volatiles which is a skinners way of farming them :D

**Comment by Dranah** [comment]
Was this by any chance forgotten to be released to the live realm @wow-mania ?
The fix works on ptr but players on live complain its still empty.

**Comment by giles1508** [comment]
this is defo not working on live,   i have load in bank,  tried to open 1 today and no loot

**Comment by Rushor** [comment]
sometimes they contain nothing. ref tables are needed here aswell like in https://github.com/WoWManiaUK/Blackwing-Lair/issues/1872

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/sS9sCVa.jpg)

no always contains sth.
