### ISSUE TITLE
[Item] Obsidium Ore

### ISSUE THREAD

**Issue by Frostmanx** [WoWManiaUK/Blackwing-Lair#1777]
**Links:**
https://www.wowhead.com/item=53038/obsidium-ore#prospecting

**What is happening:** It should give gems after prospecting I have tried with 40 ores but still nothing

**What should happen:** It should give gems or for prosepcting 5 obsidium ores

**Comment by Echinaceax** [comment]
@Frostmanx - what about it ?
is it empty or ?

**Comment by Frostmanx** [comment]
@Echinaceax sorry was updating it

**Comment by Sammy974** [comment]
Check the prospecting of obsidium because i got 4 "empty slot" in 10 stacks of 5

**Comment by Sammy974** [comment]
![WoWScrnShot_061219_212317](https://user-images.githubusercontent.com/45459932/59380190-d4e61e00-8d58-11e9-8f9c-3bec8052de05.jpg)

**Comment by Kitzunu** [comment]
fixed
