### ISSUE TITLE
[Bug] Pet renamed after dismount

### ISSUE THREAD

**Issue by Bifi0815** [WoWManiaUK/Blackwing-Lair#1778]
**What is happening:**
After Dismount in Ashenvale my Pet (called Wildhog) 
renamed to: 
Waypoint (Only GM can see it)

**What should happen:**
the name of my pet should stay

![Wildhog_pet](https://user-images.githubusercontent.com/14094955/57395141-a27c5a80-71c7-11e9-9e35-1efaef651424.jpg)

**Comment by Bifi0815** [comment]
after login today Pet named right again

**Comment by Echinaceax** [comment]
@Bifi0815 - let us know if it happens again ok

**Comment by sarahkay88** [comment]
several hunters complaining about this issue today

**Comment by Repsidian** [comment]
i tamed 3 pets so far as a hunter and i have had the 2nd pet when i dismissed it that when i whistle the pet back out its name is changed to Waypoint ( only gms can see this )

**Comment by McWeaksauce** [comment]
Same happening to me. Narrowed it down to the 2nd pet slot. Dismissing and re-calling it causes it to be renamed to the above.

**Comment by Keader** [comment]
Fixed i belive.
I cant reproduce anymore in dev

**Comment by gitkulu** [comment]
@Echinaceax @Keader It is still happening today, but seemingly only with Call Pet 2.
It wouldn't be a huge deal if it was only a naming issue, but it also screws up the pet bar, it doesn't save dragged spells and auto-cast statuses.

**Comment by Echinaceax** [comment]
> but it also screws up the pet bar, it doesn't save dragged spells and auto-cast statuses (they reset after a relog).

Maybe make new report with info of this update @gitkulu
