### ISSUE TITLE
Map Quest display 

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#178]
There seems to be a issue with the quests not showing an location or area on the main map in multiple areas,  starting zones seem to work fine but I've tested Westfall, Duskwood and STV and there is nothing showing on map after quest have been accepted.
Not sure if horde are having same issue (as I'm a alliance toon). I have no addons on at all just using standard blizzard UI and set up.

**Comment by wow-mania** [comment]
#9 duplicate
