### ISSUE TITLE
[Quest] No place to run - 12261 - Dragonblight

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1780]
https://www.wowhead.com/quest=12261/no-place-to-run

This quest does not seem to grant credit. After fighting off the add waves you get the message "The Destructive ward is fully charged" but no credit. Ward despawns, waves are over and your quest isn't complete.

How it should work: you should receive credit for quest complete when that message pops

**Comment by Kitzunu** [comment]
test now
