### ISSUE TITLE
[Quest] Sarathstra, Scourge of the North - 12097 - Dragonblight

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1782]
https://www.wowhead.com/quest=12097/sarathstra-scourge-of-the-north

Missing dialogue option to speak to the NPC https://www.wowhead.com/npc=26859/rokhan to call Sarathstra. She isn't spawned, not possible to kill and complete quest this way.

How it should work: Rokhan should offer you an option and be able to call down Sarathstra for you.

**Comment by kDracku** [comment]
The problem now is the calls down the dragon but dosent help you kill it so if you are not a tank or have healing spells you cant solo it cuz inflicts so much damage for your level
