### ISSUE TITLE
[Item] Blood of Neltharion -59062- Deepholm

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1783]
**Links:**
item https://www.wowhead.com/item=59062/blood-of-neltharion

quest https://www.wowhead.com/quest=26259/blood-of-the-earthwarder

**What is happening:**
- Item dropping without having quest 

**What should happen:**
- Should drop when u have the reqired quest

**Comment by Kitzunu** [comment]
Fixed, will run when I am home
