### ISSUE TITLE
[Quest] The Conquest Pit: Bear Wrestling - ID 12427 - Grizzly Hills

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1784]
https://www.wowhead.com/quest=12427/the-conquest-pit-bear-wrestling
Cannot complete the chain because the enemy is unattackable right on the first quest.

How it should work: bear should be attackable https://www.wowhead.com/npc=27715/ironhide

**Comment by Dranah** [comment]
Was this reverted? I still can't attack the bear.

**Comment by Dranah** [comment]
![WoWScrnShot_060119_223033](https://user-images.githubusercontent.com/31132743/58753281-e1e35180-84bc-11e9-95f3-c7cef805ef1f.jpg)

**Comment by Echinaceax** [comment]
Still has issues 
Needs retesting

**Comment by Echinaceax** [comment]
no issue found on PTR 

![bear1](https://user-images.githubusercontent.com/39439201/107129027-c8fe8680-68c2-11eb-8e44-15daa751124e.jpg)
![bear2](https://user-images.githubusercontent.com/39439201/107129028-cac84a00-68c2-11eb-89c0-e16b1945a316.jpg)
![bear3](https://user-images.githubusercontent.com/39439201/107129029-cc920d80-68c2-11eb-843c-8baa059a1d99.jpg)
