### ISSUE TITLE
[Item] Masters' Gate Plans -60745- Deepholm

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1785]
**Links:**
https://www.wowhead.com/item=60745/masters-gate-plans

**What is happening:**
- item dropping without having the quest 

**What should happen:**
ally https://www.wowhead.com/quest=27004/the-twilight-plot
horde https://www.wowhead.com/quest=27005/the-twilight-plot

**Comment by Kitzunu** [comment]
Fixed, will run it in dev when I am home
