### ISSUE TITLE
[NPC] Conqueror Krenna - missing (might be phasing issue) - Grizzly Hills

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1786]
https://www.wowhead.com/npc=26860/conqueror-krenna

Missing from her location when you arrive to hand in https://www.wowhead.com/quest=12487/to-conquest-hold-but-be-careful

Might be related to the fact she would be your last enemy to fight in the Conquest pit, at which point she would no longer be visible in her original spot. However, this should not happen until you hand in https://www.wowhead.com/quest=12431/the-conquest-pit-final-showdown

How it should work: she should be present at Conquest hold as a quest ender/giver until you hand in the quest 12431 and she is phased away.

**Comment by Echinaceax** [comment]
@Kitzunu - still only seen with Gm on 
not fixed

**Comment by Rushor** [comment]
phasing fixed now.

![I](https://i.imgur.com/NJrOYkY.jpg)
