### ISSUE TITLE
[Throne of the Tides] Reputation Reward

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Blackwing-Lair#1789]

**Comment by Dranah** [comment]
Only works on normal mode, does not work on heroic.
Need to add reputation to heroic as well.
Note: as reported in https://github.com/WoWManiaUK/Blackwing-Lair/issues/2556 these small murlocs should not award rep, on heroic either.

**Comment by Rushor** [comment]
will move and fix everything else here: https://github.com/WoWManiaUK/Blackwing-Lair/issues/3868
