### ISSUE TITLE
[Spell] Shadowy Apparitions 

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#179]
![world of warcraft 16_12_2018 21_03_33](https://user-images.githubusercontent.com/45798884/50058849-42ccd680-0176-11e9-907f-1337ce371edc.png)
Ive been testing shadow priest spells and every thing seems to work thing except for https://www.wowhead.com/spell=78203/shadowy-apparitions
Ive tested one various levels of mobs and target dummies but have not manged to cause it to proc once

**Comment by Keader** [comment]
Fixed. After long work day ._.

**Comment by Dranah** [comment]
Ok holy crap.
The apparitions should not have a health bar, should not be targetable and should not receive buffs. They are not pets.
They should also not be hugging the ground as if they are stealthing.
The damage done is wrong too. Too low and doesn't scale with anything.

**Comment by Dranah** [comment]
Works as intended now.
