### ISSUE TITLE
[PvP Daily]  [Item] Seige engine Scrap -  Tol Barad Peninsula

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#1790]
**Links:**

https://www.wowhead.com/quest=28692/magnets-how-do-they-work

**What is happening:**
I use the item https://www.wowhead.com/item=62829/magnetized-scrap-collector.
The item works but it doesnt spawns the item needed to collect 
https://www.wowhead.com/item=62830/siege-engine-scrap.

**What should happen:*
The item provided shoud spawn the  Siege Engine Scrap wich u can collect.

**Comment by Rushor** [comment]
https://i.imgur.com/3Ngpp6U.jpg
https://i.imgur.com/VBPeY0Q.jpg

use the item, trigger will get hitted and the scraps will be spawned.
