### ISSUE TITLE
[npc] Gurubashi challenger -Arena- The Cape of Stranglethron

### ISSUE THREAD

**Issue by BlueDragonKing7** [WoWManiaUK/Blackwing-Lair#1791]
**Links:**
Quest - https://www.wowhead.com/quest=26452/gurubashi-challenge
Quest - https://www.wowhead.com/quest=26451/gurubashi-challenge-free-for-all-arena-combat
NPC - https://www.wowhead.com/npc=43099/stone-guard-towhide
Item - https://www.wowhead.com/item=60387/gurubashi-challenge-flag
from WoWHead or our Armory

**What is happening:**
Go into the arena, activate the flag, cooldown does activate, but no NPC is summoned to fight

**What should happen:**
Flag should summon an NPC to defeat

**Comment by sarahkay88** [comment]
so with a little help from @Echinaceax  we managed to find the npc missing https://www.wowhead.com/npc=43120/gurubashi-arena-credit
