### ISSUE TITLE
[NPC] Brathtide raider - missing - (Bootybay)Cape of Stranglethorn

### ISSUE THREAD

**Issue by BlueDragonKing7** [WoWManiaUK/Blackwing-Lair#1792]
**Links:**
Quest - https://www.wowhead.com/quest=26699/turning-the-brashtide
NPC - https://www.wowhead.com/npc=43716/brashtide-raider
from WoWHead or our Armory

**What is happening:**
There are none of the NPCs required to kill for completing the quest

**What should happen:**
Should be able to see Brashtide Raider(NPCs to kill) to complete the quest.

**Comment by Rushor** [comment]
added them
