### ISSUE TITLE
[Item] Quartzite Resin -58501- Deepholm

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1793]
**Links:**
https://www.wowhead.com/item=58501/quartzite-resin

https://www.wowhead.com/quest=26410/explosive-bonding-compound

**What is happening:**
- dropping without quest 

**What should happen:**
- should only drop if you have the reqired quest

**Comment by Kitzunu** [comment]
Fixed and ready for testing, *choo choo* the Kitzunu Train is leaving the station and is heading for a new destination !
