### ISSUE TITLE
[NPC] Initiate Goldmine / Flint Oremantle 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1794]
**Links:**

npc -  https://www.wowhead.com/npc=42574/initiate-goldmine
npc - https://www.wowhead.com/npc=43036/flint-oremantle

1. https://www.wowhead.com/npc=42607/rockslice-ripper

they are killing npc 

![killing npc](https://user-images.githubusercontent.com/39439201/57485671-9fa76580-72ac-11e9-869a-c1486c056304.jpg)

![stops access to npc](https://user-images.githubusercontent.com/39439201/57485668-9b7b4800-72ac-11e9-88a8-7c40d49d853f.jpg)

**What is happening:**
- Npcs are blocking access to quest giver 

**What should happen:**
there's shouldnt have Rockslice Rippers.

https://www.youtube.com/watch?v=H3b6itaFiw4

**Comment by Rushor** [comment]
he is free now 

![I](https://i.imgur.com/JmxoIlE.jpg)
