### ISSUE TITLE
[NPC]Deserter Agitator - not interacting - Dustwallow Marsh

### ISSUE THREAD

**Issue by BlueDragonKing7** [WoWManiaUK/Blackwing-Lair#1795]
**Links:**
Quest - https://www.wowhead.com/quest=27210/traitors-among-us
NPC - https://www.wowhead.com/npc=23602/deserter-agitator
from WoWHead or our Armory

**What is happening:**
You can speak with the NPC, but the main speach to complete quest isn´t available

**What should happen:**
Should be able to have main conversation, then NPC will attack.

**Comment by simonverse** [comment]
Same

**Comment by Rushor** [comment]
the script needs to be converted from the wotlk version

**Comment by Rushor** [comment]
fixed now

![I](https://i.imgur.com/UUc1RBa.jpg)
![I](https://i.imgur.com/rLjVpTT.jpg)
