### ISSUE TITLE
[Quest : 13642] Bathed in Light

### ISSUE THREAD

**Issue by TheBolshe** [WoWManiaUK/Blackwing-Lair#1796]
**Links:**

https://www.wowhead.com/quest=13642/bathed-in-light

**What is happening:**

When you try to use the [Unbathed Concoction](https://www.wowhead.com/item=45065/unbathed-concoction) it says that Light of Elune is required when you are standing inside the required zone

**What should happen:**

The item should be usable inside the zone to obtain a [Bathed Concoction](https://www.wowhead.com/item=45066/bathed-concoction)

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/gg9Bkr9.jpg)
