### ISSUE TITLE
[NPC] Stone Trogg Berserker -43228- Deepholm

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1799]
**Links:**
https://www.wowhead.com/npc=43228/stone-trogg-berserker

**What is happening:**
- Whopper agressive in packs of 4
- Interferes with quest objective

**What should happen:**
- Shouldnt be pack of 4 and that agressive

**Comment by golosomie** [comment]
@Echinaceax 
I think this is not a bug. what we have is very similar to sources like [this video here](https://www.youtube.com/watch?v=8TCy61Ml1_E). Quests in this area are doable

**Comment by Echinaceax** [comment]
thanks for checking @golosomie 👍
