### ISSUE TITLE
Draenei zoning maps results in wowerror #132

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#18]
When you first log in your draenei character, it starts with a wowerror. After you log back, you can carry on until you need to leave Ammen Vale.
When trying to cross Ammen vale > Azuremyst isle, you receive wowerror, everytime you log back in.

**Comment by fvicaria** [comment]
You will need to get the new torrent for that since this is a client-side issue.

**Comment by Dranah** [comment]
No longer happens on new client!
