### ISSUE TITLE
[Quest] Loss Reduction - ID 25179 - Durotar

### ISSUE THREAD

**Issue by ScoobyPwnsOnU** [WoWManiaUK/Blackwing-Lair#180]
https://www.wowhead.com/quest=25179/loss-reduction

You can't seem to obtain this quest. The grunts are on the beach but I can't find any that will give you quest.

**Comment by Dranah** [comment]
"The guards won't talk to you to give you this quest unless you have completed From Bad To Worse given by Gar'Thok."

By hafplx (4,095 –  1·17·38)  on 2010/11/29 (Patch 4.0.3) |   |  
-- | -- | --

Have you completed the prerequisite?

**Comment by ScoobyPwnsOnU** [comment]
Yea. Gar'thok doesn't have any available quests for me, so I'm pretty sure I did it

**Comment by Dranah** [comment]
Confirmed: non interactive even with prerequisite complete

**Comment by Rushor** [comment]
fixed.

you first need to complete http://cata.cavernoftime.com/quest=25173 the you can accept the quest http://cata.cavernoftime.com/quest=25179 at the  Injured Razor Hill Grunt. Then you can select a gossip at the creatures to make them follow you.

![I](https://i.imgur.com/rGzRa5u.jpg)
![I](https://i.imgur.com/GQvIKrJ.jpg)
