### ISSUE TITLE
[NPC/Spell] Scythe of Disruption

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1801]
**Links:**
spell - https://www.wowhead.com/spell=91856/scythe-of-disruption
npc - https://www.wowhead.com/npc=45949/indentured-protector#abilities

![scy](https://user-images.githubusercontent.com/39439201/57516603-55a69a00-7315-11e9-8314-bad50aecc7c2.jpg)

**What is happening:**
Indentured Protector doesnt even have this spell in his abiliies 
interupt on all my casts 

**What should happen:**
they only use https://www.wowhead.com/spell=86085/mutilate

**Comment by Keader** [comment]
Working for me.

**Comment by Echinaceax** [comment]
> Working for me.

Sorry maybe i wasnt clear 
The report was to say this spell isnt meant to be used (but it is)

**Comment by Keader** [comment]
Fixed.
Use: .reload smart_scripts before test.
Or if is after server restart, will be just there.
