### ISSUE TITLE
[Auction Houses]  Ulduar enchants

### ISSUE THREAD

**Issue by Gainarrow** [WoWManiaUK/Blackwing-Lair#1802]
Those two enchants -
"Scroll of Enchant Weapon - Blade Ward"
"Scroll of Enchant Weapon - Blood Draining"

After putting up for sale...

Cannot be found on those AH`s under "Consumable" -> "Item Enhancement"
Silvermoon, SW, IF, Dalaran. Only way is searching with direct keywords.

Can be found under those tabs on Tanaris, Booty Bay AH`s.

**Comment by sarahkay88** [comment]
@Gainarrow which action house did you out them for sale on? some of the Ah are cross fractions for example winter spring, tanaris, booty bay, and ratchet.
if u placed your items for sale on one of these ah then they can only be viewed on a cross fraction ah.

**Comment by Gainarrow** [comment]
Now those cross faction AH works, before you couldnt see your own item, now its possible (from both sides).
Others too seems to be fine.

**Comment by Kitzunu** [comment]
I understand that this works now?

if I am wrong please comment and I will re-open :D
