### ISSUE TITLE
[PvP Daily] Bombs Away! -28275- Tol Barad

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1803]
**Links:**
https://www.wowhead.com/quest=28275/bombs-away
https://www.wowhead.com/npc=48283/wellson-cannon

**What is happening:**
- Cant use cannon 
- So cant see ghost ships

**What should happen:**

 _Destroy 10 Ghastly Supply Boats._

https://www.wowhead.com/quest=28275/bombs-away#videos:id=92016

note: seen in dev (waiting verification for server test)

UPDATE: Tested myself on live and yes cannons are not accessable

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/vlAq4Z7.jpg)

**Comment by Echinaceax** [comment]
@Rushor there not boats, their bunnies lol

![not boats lol](https://user-images.githubusercontent.com/39439201/67164569-56d7fa80-f37c-11e9-8dcc-595067bda684.jpg)

**Comment by Priestelar** [comment]
I have always desired to bomb bunnies, this quest has fufilled that desire
