### ISSUE TITLE
[PvP Daily] Leave No Weapon Behind -28063- Tol Barad

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1804]
**Links:**
https://cata-twinhead.twinstar.cz/?quest=28063

**What is happening:**
- Can do both Ally and horde quest 
- without looting twice 

**What should happen:**
- should only be one or the other not both 

note: seen in dev (waiting verification for server test)

update: ive tested this on my server toon now

**Comment by Echinaceax** [comment]
new issue after this fix Ally toon cant hand quest back https://cata-twinhead.twinstar.cz/?npc=47240

**Comment by Rushor** [comment]
this has a different reason

**Comment by Echinaceax** [comment]
shall i make new report @Rushor ?
