### ISSUE TITLE
[Talent] Lava Surge

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1805]
**Links:**
https://www.wowhead.com/spell=77756/lava-surge
**What is happening:**
Lava burst is not reseting

**What should happen:**
Lava burst should reset with tick from Flame Shock

**Comment by kDracku** [comment]
Tried on dev realm it dosent proc (Lava Surge) the skill it resets (Lava Burst)  but Lava Surge dosent proc ( dosent show the buff into the right top corner ) + with the tier bonus from firelands should be instant cast and it isnt

**Comment by Keader** [comment]
```
Description: Gives your Flame Shock periodic damage ticks a $h% chance to reset the cooldown of your Lava Burst spell.
```
The only effect is reset cooldown of lava burst.
Has no visual effect.
