### ISSUE TITLE
[Druid/Spell] Flight Form and Flying

### ISSUE THREAD

**Issue by Nestrior** [WoWManiaUK/Blackwing-Lair#1809]
**Links:**
https://wowwiki.fandom.com/wiki/Flight_Form

from WoWHead or our Armory

**What is happening:**

An important feature is not included. (Aka 150% flying is not learned upon acquiring it.)

**What should happen:**

Normally you should learn the 150% flying upon learning Flight Form, at least during Cataclysm.

**Comment by Dranah** [comment]
spell ID 33943 (flight form)
should also teach https://www.wowhead.com/spell=34090/expert-riding for free
