### ISSUE TITLE
[Quest] Lost in the floods - Durotar

### ISSUE THREAD

**Issue by ScoobyPwnsOnU** [WoWManiaUK/Blackwing-Lair#181]
https://www.wowhead.com/quest=25187/lost-in-the-floods

![image](https://user-images.githubusercontent.com/41521670/50060227-e9a17a80-0156-11e9-886b-b9efd77c4408.png)

You can't seem to use the spyglass anywhere on the watchtower, making the quest undoable.

**Comment by wow-mania** [comment]
https://www.wowhead.com/spell=73817/thonks-spyglass

**Comment by Keader** [comment]
It's more @Rushor case then me lol

**Comment by Echinaceax** [comment]
lol december 19th ....
ok ive assigned @Rushor  now
