### ISSUE TITLE
[Quest] You Can Run, But You Can't Hide - 12629 - Zul'drak

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1811]
https://www.wowhead.com/quest=12629/you-can-run-but-you-cant-hide
https://www.wowhead.com/item=38687/gooey-ghoul-drool

Gooey ghoul drool isn't given when clicking the oozes. They just disappear.
Cannot complete quest.

**How it should work:**
When clicking a https://www.wowhead.com/npc=29856/gooey-ghoul-drool, they should target the player and do a (hidden) cast of https://www.wowhead.com/spell=55363/create-gooey-ghoul-drool, which creates the item https://www.wowhead.com/item=38687/gooey-ghoul-drool
 in player bag.

**Comment by zippoking** [comment]
Does not work for me. They still just disappear when you loot them.

![You can run, but you can't hide - how it is](https://user-images.githubusercontent.com/18005338/60197076-fce87d80-983e-11e9-9d19-e218c423d2ad.png)

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/60458075-f0e52d00-9c3d-11e9-97fe-40277b8a292b.png)
 fixed
