### ISSUE TITLE
[PvP Daily] Walk A Mile In Their Shoes -28065- Tol Barad

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1813]
**Links:**
https://www.wowhead.com/quest=28065/walk-a-mile-in-their-shoes

![cant escort](https://user-images.githubusercontent.com/39439201/57568493-8b688300-73e8-11e9-9388-f4a4651e253d.jpg)

**What is happening:**
- Cant click on NPC to activate 

**What should happen:**
_Escort a Farson Hold Prisoner to safety. The hold is located on the northwestern tip of the island._

Cant escort if hes not clickable 

note: can someone test horde please

**Comment by Chargelol** [comment]
same for horde npc

**Comment by Rushor** [comment]
https://www.wowhead.com/quest=28065/walk-a-mile-in-their-shoes#comments

seems to be a very bugged quest on retail aswell

**Comment by Echinaceax** [comment]
new info https://wow.gamepedia.com/Walk_A_Mile_In_Their_Shoes

![remove](https://user-images.githubusercontent.com/39439201/66477471-804d7800-ea98-11e9-9ac7-5491a22f779c.jpg)

**Comment by Sammy974** [comment]
Is it possible to remove this quest?

**Comment by Rushor** [comment]
Ohh okay will remove :( I thought that quest would be fun :D

**Comment by Rushor** [comment]
removed from game with next update
