### ISSUE TITLE
[NPC]  Sebella 

### ISSUE THREAD

**Issue by Healwho** [WoWManiaUK/Blackwing-Lair#182]
Inn keeper Sebella in Hyjal will not allow me to set hearth there as of 12:21 today.

**Comment by TheManiax** [comment]
Please provide the link for the NPC
https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

**Comment by Healwho** [comment]
https://www.wowhead.com/npc=40843/sebelia

**Comment by Healwho** [comment]
Supposed to get a sreen option to make this in my home and instead receive nothing
