### ISSUE TITLE
[Dungeon] Blackrock Spire

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1820]
**Links:**
https://www.wowhead.com/blackrock-spire
https://www.wowhead.com/npc=10429/warchief-rend-blackhand
https://classic.wowhead.com/npc=10339/gyth

**What is happening:**
at the moment the event doesn't start correctly, the speech takes place however the weaves do not entre. eventually the boss arrives but after killing him the gates do not open and the event starts a second time.

https://www.wowhead.com/npc=10447/chromatic-dragonspawn
https://www.wowhead.com/npc=10442/chromatic-whelp

**What should happen:**
this is a multi stage event in waves that you have to kill. I think around 7/8 waves before the boss appears. Warchief rend blackhand then arrives on Gyth and you kill him which should open the small gate on the right hand side allowing players to progress.

**Comment by Rushor** [comment]
fixed here https://github.com/WoWManiaUK/Blackwing-Lair/issues/2795
