### ISSUE TITLE
[NPC] ACRIDE - MISSING - Blackrock Spire

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1821]
**Links:**
npc -https://www.wowhead.com/npc=10299/acride#starts
quest - https://www.wowhead.com/quest=27445/general-drakkisath-hand-of-nefarian#comments

**What is happening:**
NPC is missing at the start of the dungeon to allow players to collect the above quest

**What should happen:**
NPC should be located at the start of the dungeon to allow players to obtain the quest

**Comment by Rushor** [comment]
added him to the start entrance close to Jalinda Spring https://github.com/WoWManiaUK/Blackwing-Lair/issues/1965

**Comment by Rushor** [comment]
oh no this is not correct

**Comment by Rushor** [comment]
added

![I](https://i.imgur.com/ggZUcU6.jpg)
