### ISSUE TITLE
[NPC] Alysra - 38917 - Mount Hyjal

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1823]
ID 38917

This NPC while i am on the beginning of her quest chain (Emerald allies https://www.wowhead.com/quest=25430/emerald-allies) is not supposed to offer the talk option:
"You turned Fandral Staghelm over the twilight's hammer. Why have you betrayed the dragonflights"
Clicking this option (even by accident) turns the dragon hostile and prevents you from progressing.
In addition, it is a giant spoiler for those that are new to the lore!

She should only offer this option at the very end of the chain when her betrayal is discovered, once you have picked up https://www.wowhead.com/quest=29437/the-fallen-guardian

**Comment by Sammy974** [comment]
In addiction, when you get the quest https://www.wowhead.com/quest=29437/the-fallen-guardian Alysra is not in her position and you can't actually talk with her.

**Comment by Rushor** [comment]
okay now you can only see the gossip option while you are on the quest chain.
