### ISSUE TITLE
[Quest]  [Keep the Fires Burning] id 13890 - (issue 2) Ashenvale

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#1824]
**Links:**
https://www.wowhead.com/quest=13890/keep-the-fires-burning
https://www.wowhead.com/item=46366/mystlash-hydra-oil
https://www.wowhead.com/item=46365/mystlash-hydra-blubber
**What is happening:**
u cant craft  Mystlash Hydra oil from mystlash-hydra-blubber at the Forge
![WoWScrnShot_051119_230951](https://user-images.githubusercontent.com/50077942/57574951-f2feec80-7441-11e9-8f80-455d3b4801b9.jpg)

**What should happen:**
u shoud be able to craft  Mystlash Hydra oil at the Forge

**Comment by Rushor** [comment]
spellfocus added
