### ISSUE TITLE
 [NPC] Andruk - inactive - Ashenvale

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#1825]
**Links:**
quest 
https://www.wowhead.com/quest=13923/to-hellscreams-watch
npc
https://www.wowhead.com/npc=11901/andruk

**What is happening:**
cant speak to andruk to send me to Hellscream's Watch. 
![WoWScrnShot_051119_233104](https://user-images.githubusercontent.com/50077942/57575106-eb8d1280-7444-11e9-884d-d3ceb44b6504.jpg)

**What should happen:**
u shoud be able to talk to andruk so he sents u to Hellscream's Watch.

**Comment by Rushor** [comment]
fly path added :)

![I](https://i.imgur.com/APXVfV6.jpg)
