### ISSUE TITLE
[PvP] Call to Arms 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1832]
**Links:**

![x2 call to arms](https://user-images.githubusercontent.com/39439201/57580002-bb755c00-74a4-11e9-83cf-e66b3ecf488a.jpg)

**What is happening:**

- Showing 2x  

**What should happen:**
- Only should be one

**Comment by Rushor** [comment]
not possible to fix that rght now
