### ISSUE TITLE
Tol Barad (join battle text missing) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1834]
**Links:**
https://www.wowhead.com/quest=28882/victory-in-tol-barad

![no text](https://user-images.githubusercontent.com/39439201/57580163-53c01080-74a6-11e9-9d09-452655c84bac.jpg)

**What is happening:**
- visual bug (no sure any other issues atm) 

**What should happen:**
- Should have txt simulal to WG in wotlk im guessing 
"the battle is about to start, would you like to queue / join etc....

**Reproduce**
Run on the bridge and window will pop up when battle is about to start 

![tol1](https://user-images.githubusercontent.com/39439201/57580193-d0eb8580-74a6-11e9-935a-d1dbcac43b0b.jpg)

**Comment by Rushor** [comment]
not fixable currently
