### ISSUE TITLE
[Item/quest] Ominous letter - Hellfire Ramparts

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1837]
**Links:**
quest/item - https://www.wowhead.com/item=23890/ominous-letter#comments
NPC - https://www.wowhead.com/npc=17536/nazan

**What is happening:**
This item dropped of the last boss - the dragon one, however players cannot open it

**What should happen:**
I believe this quest was removed in patch 4.3.4 - therefore shouldn't be in the game

**Comment by Kitzunu** [comment]
From what I can tell and read this seems accurate
https://wow.gamepedia.com/Dark_Tidings_(Alliance)
