### ISSUE TITLE
[PvP vendor]  Bypasses all progression

### ISSUE THREAD

**Issue by z1179** [WoWManiaUK/Blackwing-Lair#1838]
**Links:**

**SS**
https://imgur.com/a/k2pPW6E

**What is happening:**
Technically not a bug, but it is a bypass that i assume is unintentional The Conquest (and potentially the honor vendor, didn't look) sell gear that outperforms any gear remotely available at this time, this gear should not be available until the server progresses to the Dragon Soul stage.Dragon soul gear item levels are 397-410, the conquest gear is also 397-410, the season 11 set being available bypasses all progression raids (Firelands-378 ilvl, Bastion of twilight+Blackwing Descent- 359 ilvl) and dungeons.

**What should happen:**
for proper progression the conquest and honor pvp vendor needs to be reverted to 4.0 state, in which it would sell season 9 Vicious Gladiator gear.

**Comment by sarahkay88** [comment]
labelled has pending depending until someone can check it.

**Comment by Echinaceax** [comment]
> labelled has pending depending until someone can check it.

They PM me about it with SS

**Comment by sarahkay88** [comment]
> labelled has pending depending until someone can check it.
> 
> They PM me about it with SS

yep but I didn't want the whole debate of this is a suggestion n not a bug lol

**Comment by Echinaceax** [comment]
https://www.wowhead.com/npc=69975/captain-dirgehammer

![yes](https://user-images.githubusercontent.com/39439201/57582206-3e58df80-74c2-11e9-9dc2-f01c2557e03b.jpg)

**Comment by z1179** [comment]
How is Removing the vendor a fix? the fix should be changing the vendors sell log to season 9, not removing it all together this is unacceptable.

**Comment by Echinaceax** [comment]
@z1179 they are working with the vendors #1976
give then time
