### ISSUE TITLE
[NPC] Advanced Scout Chadwick - Missing - The Shattered halls - second issue

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1840]
**Links:**
NPC -https://www.wowhead.com/npc=54933/advance-scout-chadwick
Zone - https://www.wowhead.com/the-shattered-halls
QUESTS:
1 - https://www.wowhead.com/quest=29649/how-to-save-a-life
2 -https://www.wowhead.com/quest=29656/omroggs-warcloth
3 - https://www.wowhead.com/quest=29654/turning-the-tide

**What is happening:**
NPC is missing from start of dungeon preventing players from being able to pick up the above quest

**What should happen:**

NPC should be at the start of the dungeon so players can obtain the quests

**Comment by Rushor** [comment]
depending on which faction enters the dungeon > creature added.
