### ISSUE TITLE
[NPC] Nascent Fel Orc - Bloodfurnace

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1842]
**Links:**
NPC - https://www.wowhead.com/npc=17398/nascent-fel-orc
ZONE - https://www.wowhead.com/the-blood-furnace

**What is happening:**
These NPCS are located in the corridor after killing the first boss, however they are un -targetable and have no health bar so cannot be killed, however they continue to attack and stun players.
they can be avoid if the player runs near the wall to the opposite side, but once the player reaches the second boss they cannot progress has they come out in waves.

**What should happen:**
Players should be able to target these npc's and kill them allowing them to progress.

**Comment by sarahkay88** [comment]
not fixed

**Comment by sarahkay88** [comment]
@Kitzunu  there has been reports on discord that these adds are still untargetable

**Comment by giles1508** [comment]
this is still broken.....  the mobs are still not attackable and you simply cannot progress...

**Comment by Echinaceax** [comment]
not fixed @wow-mania

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/63408122-8efba500-c3ee-11e9-981f-262456d71cff.png)

fixed
