### ISSUE TITLE
[Fishing Dailies] Not scalling with lvl

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1846]
**Links:**

from WoWHead or our Armory

**What is happening:**

- Dalies not scaling to lvl

**What should happen:**

- Dailies is meant to scale to lvl

**Comment by Kitzunu** [comment]
I believe this might have something to do with the core missing something...

Im not sure, but in DB it shows correctly.
This concerns this, and all issues similar to this one

**Comment by Echinaceax** [comment]
@wow-mania dailies are still not scaling to char lvl :) 
lvl 85 and i get 1s 25c

**Comment by Rushor** [comment]
Not fixable currently - i have set the amount lower few months ago to prevent abuse at low level. as is for know -thanks
