### ISSUE TITLE
[Spell] Whirlwind

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Blackwing-Lair#1848]
Links:
https://www.wowhead.com/spell=1680/whirlwind

What is happening:
When you use whirlwind on 4 targets it's cooldown remains unchanged.

**What should happen:**
When you use whirlwind on 4 or more targets it's cooldown should be reduced by 6 seconds.
(Tooltip)

**Comment by Keader** [comment]
Fixed.
