### ISSUE TITLE
[NPC] Alliance Spirit Guide

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1850]
**Links:**
https://www.wowhead.com/npc=45066/alliance-spirit-guide

coords
67.6, 68.6

![spirit guide](https://user-images.githubusercontent.com/39439201/57611458-3b69f780-7573-11e9-8d07-aad9589fedd1.jpg)

**What is happening:**
- Inactive
- doesnt offer res option

**What should happen:**
- Should offer res option so you dont have to run back to your corpse

**Comment by Kitzunu** [comment]
This is core related.

All Spirit guides from cata currently has ScriptName = npc_tb_spirit_guide

```sql
SELECT * FROM creature_template WHERE NAME LIKE '%Alliance Spirit Guide%';
```

**Comment by Rushor** [comment]
are you sure baout that res option?

**Comment by Echinaceax** [comment]
hmm...not 100%

**Comment by Rushor** [comment]
https://i.imgur.com/nZwjn4A.jpg
https://i.imgur.com/3hcH8GZ.jpg
https://i.imgur.com/lzA1vTn.jpg

zone 5095 in spellinfo was missing
