### ISSUE TITLE
[PvP Daily/Item] Crocolisk Hide -63103- Tol Barad

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1851]
**Links:**
item https://www.wowhead.com/item=63103/crocolisk-hide
npc https://www.wowhead.com/npc=47591/baradin-crocolisk

**What is happening:**
- Continues to drop after you have rquired amount for quest 8/8

**What should happen:**
- Should stop when reach required amount
https://www.wowhead.com/quest=28162/swamp-bait

**Comment by Echinaceax** [comment]
new issue with this fix 

![swap bait](https://user-images.githubusercontent.com/39439201/66962195-b084b000-f070-11e9-9bb6-51a860ea5099.jpg)

i have 8/8 when i hover over but on 7/8 in bags
cant loot more

**Comment by Kitzunu** [comment]
Weird, anyways here's the fix:
```sql
UPDATE `item_loot_template` SET `QuestRequired` = 1 WHERE `item` = 63103;
```
