### ISSUE TITLE
[NPC] Corrupted Dryad - Not Working - Feralas

### ISSUE THREAD

**Issue by BlueDragonKing7** [WoWManiaUK/Blackwing-Lair#1852]
**Links:**
NPC - https://www.wowhead.com/npc=40168/corrupted-dryad
Quest - https://www.wowhead.com/quest=25436/spiteful-sisters
from WoWHead

**What is happening:**
Trying to kill Corrupted Dryads, since they are a quest objective, but their health never goes down thus making it impossible to kill

**What should happen:**
Should be able to slay Corrupted Dryad

**Comment by Rushor** [comment]
cannot see a problem here, maybe outdated https://i.imgur.com/ge0K5Gg.jpg
