### ISSUE TITLE
[NPC] Adella - phasing - Feralas

### ISSUE THREAD

**Issue by BlueDragonKing7** [WoWManiaUK/Blackwing-Lair#1854]
**Links:**
[Quest] - https://www.wowhead.com/quest=25426/war-on-the-woodpaw
[NPC] - https://www.wowhead.com/npc=39725/adella
from WoWHead

**What is happening:**
The quest marker for when one has completed the quest takes you to Feathermoon Stronghold - Feralas. But Adella[NPC] isn´t here

**What should happen:**
The quest marker for when one has completed the quest should take you Shadebough - Feralas

**Comment by Rushor** [comment]
https://i.imgur.com/tPVc9W5.jpg added
