### ISSUE TITLE
[Dungeon/Quest] Blackrock Caverns quests

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1855]
Currently you can't do any quests in the dungeon for two reasons:

1) The NPC in the beginning of the dungeon who offers the first quest is phased and not visible to players. https://www.wowhead.com/npc=49444/finkle-einhorn
This makes it impossible to accept https://www.wowhead.com/quest=28735/to-the-chamber-of-incineration
2) The quest bangs that need to auto-offer the remaining quests to players who walk past them aren't functioning.
These are invisible NPCs placed in front of boss rooms.

**How it should work:**
https://www.wowhead.com/npc=49444/finkle-einhorn should be visible to players
https://www.wowhead.com/npc=49526/corla-quest-bang should offer quest: https://www.wowhead.com/quest=28737/what-is-this-place
https://www.wowhead.com/npc=49529/karsh-quest-bang should offer quest: https://www.wowhead.com/quest=28738/the-twilight-forge
https://www.wowhead.com/npc=49530/beauty-quest-bang should offer quest: https://www.wowhead.com/quest=28740/do-my-eyes-deceive-me
https://www.wowhead.com/npc=49531/obsidius-quest-bang should offer quest: https://www.wowhead.com/quest=28741/ascendant-lord-obsidius

**Comment by Dranah** [comment]
No change. The gnome is phased out and the quest bangs dont offer quests.

**Comment by Dranah** [comment]
Fizzle is now visible as intended.
The quest bangs are now also visible NPCs you can speak to in order to pick up the quest.
This is not the blizzlike behavior, but for a temporary solution,it allows you to collect and do the quests.
However, sometime this needs fixing (no priority at all) so that the quest bangs arent visible, but offer you the quests automatically when you walk through them.

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/58232591-c7c5a880-7d31-11e9-965b-247291fb1e32.png)
