### ISSUE TITLE
[NPC] Conflagration - Blackrock Caverns Trash

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1856]
https://www.wowhead.com/npc=39994/conflagration

does not use their abilities, they are tank and spank

How it should work:
Their abilities need to be added
https://www.wowhead.com/spell=75077/burning-heat
https://www.wowhead.com/spell=76617/heat-exhaustion
https://www.wowhead.com/spell=76618/immolate

**Comment by Dranah** [comment]
They are using Immolate on their designated tank, but there are no signs of spell 75077 and 76617

**Comment by Rushor** [comment]
added

https://i.imgur.com/nzObARz.jpg

burning-heat will be added once transform is fixed
