### ISSUE TITLE
[Quest] The Rebel Lord's Arsenal -14159- Gilneas

### ISSUE THREAD

**Issue by raoin001313** [WoWManiaUK/Blackwing-Lair#1858]
**links**
https://www.wowhead.com/quest=14159/the-rebel-lords-arsenal

**Whats happening**
This issue was reported before, however im having the same issue again. I was unphased and can no longer open the cellar door to continue my quest. 

**What should happen**
I should be able to walk down to talk to Josiah Avery and turn it in. 

I have tried to abandon and retake the quest with no results. I have logged off and restarted the game with no change.

**Comment by TheBolshe** [comment]
I had this issue too, the only way to fix it for me was too create another character. It's worth to note that i tested with 4 characters and it only happened with the first one, and it was my first character ever.

**Comment by Echinaceax** [comment]
#5 but not fixed other issues there too

**Comment by Rushor** [comment]
added a save call of phasing spell once quest 14159 is accepted for phase 170

**Comment by Rushor** [comment]
okay as @Dranah said. the pahsing is working fine for the quest. If people mess up with other quests they get in adifferent phase and they they cannot continue the quest.

In future we make one report for the quest order which will fix everything.

**Comment by Echinaceax** [comment]
no issues at all with this now, i levels a worgen and left the zone perfectly fine
