### ISSUE TITLE
[Zone] Azuremyst Isle - missing quest trackers

### ISSUE THREAD

**Issue by raoin001313** [WoWManiaUK/Blackwing-Lair#1859]
As the title says, Ran into the issue during the quest to kill the blood elf spy. quest tracker is not picking up the location for the quest. Or any others.

**Comment by Dranah** [comment]
Map: 530 (Outland)
Zone: 3524 (Azuremyst Isle)

**Comment by raoin001313** [comment]
Update: The quest tracker in this area turns the quest location into the quest turn in on the map when completed.

**Comment by wow-mania** [comment]
Unless you give the exact ques ids or links we will not look into it.
