### ISSUE TITLE
[Quest] The Wolf and The Kodo - ID 25205- Durotar

### ISSUE THREAD

**Issue by ScoobyPwnsOnU** [WoWManiaUK/Blackwing-Lair#186]
https://www.wowhead.com/quest=25205/the-wolf-and-the-kodo

![image](https://user-images.githubusercontent.com/41521670/50123846-e88c4e00-0227-11e9-82d6-23b6b88cf461.png)

You can get the quest but you can't transform into the wolf. Going to the area you are supposed to go to as the wolf doesn't complete the quest either. The followup quests on the next guy are already available though(they shouldn't be until after you finish this one), so it doesn't prevent you from continuing, just from finishing this quest.

**Comment by Pitmaster** [comment]
Have someone tried to leave the available quests from his neighbor and first do this quest?

**Comment by Eirolla** [comment]
----what happens,----
 ![image](https://user-images.githubusercontent.com/26048748/62366317-33e13b80-b52f-11e9-9a1a-e3000fc1b78d.png)
----what should it be----
![image](https://user-images.githubusercontent.com/26048748/62366343-48253880-b52f-11e9-9a1d-d51739cedec1.png)

**Comment by Lumber-Jack-2** [comment]
added a basic script for that

**Comment by rzenne** [comment]
.BQ 25205 not working. Can't reach food in time using dash.

**Comment by Echinaceax** [comment]
> .BQ 25205 not working. Can't reach food in time using dash.

Thats odd, ive used the BQ command on this one before 

I check on this when PTR is online, and make a new report for this issue

@rzenne
confirmed BQ no working, thanks
