### ISSUE TITLE
[Spell] Divine Storm(should not have a cap on targets)

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Blackwing-Lair#1860]
Links:
https://www.wowhead.com/spell=53385/divine-storm

What is happening:
Divine Storm, when used in an AoE situation damages up to 4 targets around you.

What should happen:

Divine Storm, when used in an AoE situation should damage all targets around you.
(Tooltip)

**Comment by Keader** [comment]
Fixed.
