### ISSUE TITLE
[Quest] Distract Them for Me -27689- Twilight Highlands

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1868]
**Links:**

https://www.wowhead.com/quest=27689/distract-them-for-me

**What is happening:**
You can kill only Master Klem , the others you cant because you die from Deathwing

**What should happen:**
Well you should kill all 3 of  them

**Comment by Echinaceax** [comment]
this could be the cause #1377
So we'll see when deathwing aura - leave at pending for now

**Comment by sarahkay88** [comment]
npc - https://www.wowhead.com/npc=46341

**Comment by Echinaceax** [comment]
deathwing disabled for now
reopen if still issues
