### ISSUE TITLE
[Quest] Night Terrors -28170- Twilight Highlands

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1869]
**Links:**
quest - https://www.wowhead.com/quest=28170/night-terrors
video - https://www.youtube.com/watch?v=q5YzDudYFNM

**What is happening:**

You cannot enter the spirit realm while talking to Uchek

**What should happen:**
After talking to Uchek you should enter the spirit realm and cleanse the shrines

**Comment by sarahkay88** [comment]
NPC U chek id https://ptr.wowhead.com/npc=47826/uchek

**Comment by Anders98** [comment]
Bumping as seeing this in the bq list would be lovely as it rewards trinkets for all classes.

**Comment by Lerixo** [comment]
Update: Just checked yesterday: Spirit realm is enterable, but cleansing the shrines doesnt work.

**Comment by Echinaceax** [comment]
@Rushor 
comfirmed about the low HP on those mobs 

https://www.wowhead.com/npc=47824/tormented-dead
![tormented dead](https://user-images.githubusercontent.com/39439201/64724481-dc8d9e00-d4d2-11e9-9c6e-aee2fb1008bb.jpg)

https://www.wowhead.com/npc=47823/wailing-dead
![wailing dead](https://user-images.githubusercontent.com/39439201/64724569-047d0180-d4d3-11e9-9406-599d344dc086.jpg)

**Comment by Rushor** [comment]
the questitem now actually kills the creatures

![I](https://i.imgur.com/5fig6dc.png)
![I](https://i.imgur.com/10ji4Hs.png)

and questcredit is given without buff cancel or sth like that

![I](https://i.imgur.com/Z8Oez38.jpg)
