### ISSUE TITLE
[Spell] Kill Command

### ISSUE THREAD

**Issue by ScoobyPwnsOnU** [WoWManiaUK/Blackwing-Lair#187]
Kill Command, the BM Hunter spell doesn't seem to do anything when you cast it. You can cast it at any time whether you are in combat or not, it spends the focus, but does no damage, regardless of if your pet is attacking your target, if you are attacking your target, or if you both are attacking your target.
![image](https://user-images.githubusercontent.com/41521670/50130316-94429780-0242-11e9-826d-acfb7052418b.png)

**Comment by Keader** [comment]
Fixed in dev

**Comment by Dranah** [comment]
Still no sign of damage from the ability.

**Comment by Keader** [comment]
Fixed in DEV, not in PTR

**Comment by Dranah** [comment]
The spell now does damage, but way too low.
Does not seem to scale with the hunter's ranged attack power.

**Comment by Keader** [comment]
Fixed.
