### ISSUE TITLE
[Profession]-Jewel Crafting - Fire Prism 52304

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1872]
**Links:**
item - https://www.wowhead.com/item=52304/fire-prism
loot - https://www.wowhead.com/item=52304/fire-prism#contains

**What is happening:**
- They are empty (nothing inside)

**What should happen:**
- Meant to have loot inside

**Comment by kDracku** [comment]
Confirm , they're empty!

**Comment by Frostmanx** [comment]
Links: https://www.wowhead.com/item=52304/fire-prism

from WoWHead or our Armory

What is happening: Does not given any gems after opening it (no loot)

What should happen:

Should have a chance of getting few of the following gems

1-3x [Demonseye]
1-3x [Dream Emerald]
1-3x [Inferno Ruby]
1-3x [Amberjewel]
1-3x [Ember Topaz]
1-3x [Ocean Sapphire]
[Chimera's Eye]

Confirmed! Empty

**Comment by Frostmanx** [comment]
Still empty! Checked multiple times!

**Comment by Kitzunu** [comment]
I will have to look into this why sometimes you get gems and not.
I will get back to this when I know the cause

**Comment by Sammy974** [comment]
Today i clicked it and it just disappeared, it didn't give "empty slot" neither.

**Comment by Sammy974** [comment]
It gives no loot, just disappear... i tryed multiple times and always the same.

**Comment by Rushor** [comment]
itemloot added

![I](https://i.imgur.com/xMDJO5p.jpg)

If chances need to be adjusted just tell me. for now it's 40 % chance to get 1-3 from each item

**Comment by Sammy974** [comment]
Today it disappeared again. Some regression maybe?

**Comment by Echinaceax** [comment]
Still not fixed @Kitzunu 
im reopening this

**Comment by Kitzunu** [comment]
Remove lables otherwise jani will Close again

**Comment by Rushor** [comment]
ref loot need to be added then

**Comment by Rushor** [comment]
okay now fully fixed. ref table added.

![I](https://i.imgur.com/hBUbKFn.jpg)
