### ISSUE TITLE
[Guild] Ranks

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1873]
The thing is that you can make new ranks but you cannot scroll them up or bottom.
http://tinypic.com/view.php?pic=6ittn6&s=9#.XNsbqY77SUk

**Comment by Echinaceax** [comment]
seems find to me 
![1a](https://user-images.githubusercontent.com/39439201/57729983-c04e3180-7697-11e9-8578-e0a171484a34.jpg)
![1b](https://user-images.githubusercontent.com/39439201/57729991-c3492200-7697-11e9-8bc2-cf42fe923a57.jpg)

@kDracku are you using reign launcher or the .exe?

**Comment by kDracku** [comment]
I mean when you create a new rank into guild control you cannot scroll it up or botttom ,. Lets say i make the rank  Best Officer , i cannot put it under Guiild Master so as resault will stay bottom and new players that join the guuld will have the Best Officer rank

**Comment by Frostmanx** [comment]
Yes I can confirm what Dracku said. So in my guild I only have the default ranks due to this bug.

**Comment by Kitzunu** [comment]
Error message in Server Log:

```
Received not handled opcode [CMSG_QUERY_GUILD_RECIPES 0x3033 (12339)] from [Player: Kitzunu GUID Full: 0x00000000000000c4 Type: Player Low: 196, Account: 10]
```

**Comment by Echinaceax** [comment]
moved to here #3150
