### ISSUE TITLE
[Quest] Fire the Cannon -27661- Twilight Highlands

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1878]
**Links:**

https://www.wowhead.com/quest=27661/fire-the-cannon

**What is happening:**
Well you cannont kill the Lord Cannon because you die from Deathwing
**What should happen:**
Kill Lord Cannon

**Comment by Echinaceax** [comment]
Might be ok once this is fixed #1377 so leave pending for now

**Comment by sarahkay88** [comment]
Lord Cannon id -https://www.wowhead.com/npc=46785

**Comment by Echinaceax** [comment]
deathwing disabled atm
reopen if still issues
