### ISSUE TITLE
[Quest] Thunder Down Under - ID 25236- Durotar

### ISSUE THREAD

**Issue by ScoobyPwnsOnU** [WoWManiaUK/Blackwing-Lair#188]
https://www.wowhead.com/quest=25236/thunder-down-under

![image](https://user-images.githubusercontent.com/41521670/50130890-6ca0fe80-0245-11e9-9368-5d01bf1be492.png)

You can't interact with the thunder lizards at all. I think you used to right click on them maybe? It was either that or you used the quest item, and you cant use the quest item on them either. The quest is undoable.

**Comment by Eirolla** [comment]
We should be interacted with "Drowned Thunder Lizards" (NPC: 39464). After interacting an NPC pulls it to surface.

**Comment by Echinaceax** [comment]
i reported the item here #1101

**Comment by Vallox-Nemesis** [comment]
Should add quest ID 25236 to the .bq command in-game.
Also I think this should be re-opened until fixed and the related quest item ticket should be closed instead (issue 1101), as the item itself is not broken; it's just that the lizard corpses that you're meant to interact act with are currently non-interactable.
