### ISSUE TITLE
[Spell] Fulmination

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1884]
ID 88766

The spell seems to calculate damage completely wrong.

**How it works atm:** 
Without any gear, despite a ~400ish base damage of lightning shield, a one-charge fulmination (shock used when you have 4 stacks total) does only 125 damage.
However as you acquire spell power, even at 2-3k sp (level 80ish) the spell begins doing way more damage than it should. With 3860 SP, my lightning shield charge deals 2k damage to an enemy, but a 1-stack fulmination hits for 3,3k. 
The gap grows as you acquire more spell power, leading to unreasonably high damage in a buffed party.

**How it should work:** The effect should copy the total damage that your lightning shield charges beyond 3 would do. 
This means if you have 4 charges when casting earth shock, fulmination damage should be as much as 1 charge being consumed by an enemy hitting you. With 9 charges total, it should be the damage of 6 charges together.
The spell should not have a spell power coefficient and should not take benefit itself from damage modifiers that already affect lightning shield (talents, such as Elemental precision, buffs, such as Elemental mastery, etc...)
The spell CAN scale with debuff modifiers such as the 8% magic damage increase, or boss mechanics that increase the target's damage taken.

**Comment by Keader** [comment]
@Dranah can you reconfirm it, after lightning shield fixed?
Maybe it was caused by it.

**Comment by Dranah** [comment]
**Test 1:**
Lightning Shield base damage (naked 131 sp) = 424
Fulmination damage with +1 stack (total 4 stack): 100-104 ( 200+ critical)
Expected damage: 424

**Test2:**
4584 spell power
Lightning Shield damage = 1613 (fixed)
Fulmination damage with +1 stack (total 4 stack): 3200
Expected damage : 1613
Fulmination damage with +6 stack (total 9 stack): 9380
Expected damage : 6 * 1613 = 9678

I have no idea how these values are calculated.

**Comment by Dranah** [comment]
Note: it seems to be able to double-dip from certain effect such as the damage boost on Ozumat. https://www.wowhead.com/spell=76133/tidal-surge
This is not intended.
