### ISSUE TITLE
[Spell] Buff stacking: spell power % modifiers

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1885]
The following buffs that grant a % of spell power to the party should not stack with each other:

Demonic pact effect ID 53646 (10%)
Totem of Wrath effect ID 77747 (10%)
Flametongue totem effect ID 52109 (6%)
Arcane brilliance buff ID 79058 (6%)

Obviously, when multiple of them are present, the higher (10%) version must be active.

**How it works atm:** all of the effects stack, you can get a total of 35% spell power increase off them.

**Comment by kDracku** [comment]
Flametongue Totem stacks with Totem of Wrath . Tested , can confirm

**Comment by Ovahlord** [comment]
```
DELETE FROM `spell_group` WHERE `id`= 1134;
INSERT INTO `spell_group` (`id`, `spell_id`) VALUES
(1134, 52109),
(1134, 53646),
(1134, 77747),
(1134, 79038),
(1134, 79039),
(1134, 79057),
(1134, 79058);

DELETE FROM `spell_group_stack_rules` WHERE `group_id`= 1134;
INSERT INTO `spell_group_stack_rules` (`group_id`, `stack_rule`) VALUES
(1134, 3);

```

this of course requires that @Keader darling has ported my spell power pct handling to support that stack rule

**Comment by wow-mania** [comment]
@Ovahlord hey man please contact me on Discord if you have a chance. Janitor#2871

**Comment by Kitzunu** [comment]
@Ovahlord I believe you need to join a Discord server to be able to msg him.
If you already have then this is pointless :P https://discordapp.com/invite/AAfbCKE

**Comment by Dranah** [comment]
Totemic Wrath (10%) now overrides Flametongue totem (6%) and Arcane brilliance (6%), when only these effects are present.
Demonic Pact (10%) now overrides both 6% effects as well, when only these effects are presents.
Totemic Wrath (10%) still stacks with Demonic Pact (10%), granting the 10% bonus twice. (need fixing)
When both Totemic Wrath and Demonic Pact are present, the effect of any 6% auras present also seems to re-activate, despite them being properly suppressed when only one of the 10% buffs were active. This way, in a fully buffed environment, you still get the bonus from all the 4 auras.

So technically, not a lot has changed.

**Comment by Keader** [comment]
I cant reproduce...
With 4 buffs:
![image](https://user-images.githubusercontent.com/7120913/62890309-a4e7d680-bd19-11e9-894e-04fe3d038170.png)

With only demonic pact:

![image](https://user-images.githubusercontent.com/7120913/62890382-c3e66880-bd19-11e9-9ac1-52a68df1a49e.png)

**Comment by Keader** [comment]
Someone fucked the method.
Fixed it.
