### ISSUE TITLE
[Quest] Unbidden Visitors - Southfury River

### ISSUE THREAD

**Issue by Venom64bit** [WoWManiaUK/Blackwing-Lair#1886]
**Links:**

Quest: https://www.wowhead.com/quest=25194/unbidden-visitors
Quest Mob: https://www.wowhead.com/npc=39337/wayward-plainstrider
Giver: https://www.wowhead.com/npc=39324

**What is happening:**
After removing 75% of their Hp, nothing happens.

**What should happen:**
After removing 75% of their HP they should run to the other side.

YT Video: https://www.youtube.com/watch?v=VyGGIB-Fvp4

**Comment by Rushor** [comment]
https://www.youtube.com/watch?v=VyGGIB-Fvp4 percent hp should be 35

**Comment by Rushor** [comment]
if you hit 50 % of hp they will run away and give credit

![](https://i.imgur.com/Y1TmOvF.jpg)
