### ISSUE TITLE
[Dungeon] Dire Maul (issue 1)

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1887]
You cannot destroy the crystals and make progress through Immol'thar (door dosent open)

**Comment by Echinaceax** [comment]
any links and IDs ?
devs cant do much without more info

**Comment by kDracku** [comment]
The door before entering this room : https://www.wowhead.com/npc=11496/immolthar is locked + you need to destroy the crystals -> http://i63.tinypic.com/2e5tgeh.jpg  (after killing the adds surrouding the crystal nothimg happens)

**Comment by Nirvanum** [comment]
![immagine](https://user-images.githubusercontent.com/52670055/67146047-34b08080-f287-11e9-8b86-f9adf879583b.png)

**Comment by Rushor** [comment]
already fixed
