### ISSUE TITLE
[Daily JC] Ogrezonians in the Mood

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1888]
**Links:**

https://www.wowhead.com/quest=25161/ogrezonians-in-the-mood

**What is happening:**
It gives progress only by crafting not cuting
**What should happen:**
Should give progress for both
P.S : I think all JC dailies are broken

**Comment by Sammy974** [comment]
It's not giving "cut" progress today. Tested with 2 chars.

**Comment by Rushor** [comment]
refixed with next update

**Comment by Rushor** [comment]
refixed with next update
