### ISSUE TITLE
[Profession]-Jewel Crafting - Fire Prism 52304 

### ISSUE THREAD

**Issue by Frostmanx** [WoWManiaUK/Blackwing-Lair#1891]
**Links:**   https://www.wowhead.com/item=52304/fire-prism

from WoWHead or our Armory

**What is happening:** Does not given any gems after opening it (no loot)

**What should happen:**  

Should have a chance of getting few of the following gems 

1-3x [Demonseye] 
1-3x [Dream Emerald]
1-3x [Inferno Ruby]  
1-3x [Amberjewel]
1-3x [Ember Topaz]  
1-3x [Ocean Sapphire]
 [Chimera's Eye]

**Comment by Echinaceax** [comment]
Already reported (copied over to main report #1872
