### ISSUE TITLE
[NPC] Lirastrasza Twilight Highlands

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1895]
**Links:**
https://www.wowhead.com/quest=28248/victors-point
**What is happening:**
(As horde)
The NPC Lirastrasza is giving me Alliance quest
**What should happen:**
I dont need alliance quest :D

**Comment by sarahkay88** [comment]
NPC - ID https://www.wowhead.com/npc=47902
