### ISSUE TITLE
[Quest Item] Alexstrasza's Tear Twilight Highlands

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1896]
**Links:**

https://www.wowhead.com/quest=28175/shining-through-the-dark

**What is happening:**
Says i need to be , beneath the Obsidian Tree , problem is i am in the exact place but still it says that
**What should happen:**
You should plant the Alexstrasza's Tear

**Comment by sarahkay88** [comment]
Item id - https://www.wowhead.com/item=63139

**Comment by Echinaceax** [comment]
fixed here #3434
