### ISSUE TITLE
[NPC] Initiate Goldmine Twilight Highlands (issue 2)

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1897]
**Links:**

https://www.wowhead.com/quest=27782/mathias-needs-you

**What is happening:**
(as horde)
It gives me alliance quest
**What should happen:**
Im not alliance

**Comment by sarahkay88** [comment]
NPC ID - https://www.wowhead.com/npc=46243

**Comment by mfranca0009** [comment]
Ran into this issue on live, confirmed.

**Comment by mfranca0009** [comment]
This is the same as #5059, since I already marked 5059 as fixed, I'm closing this out as a duplicate.
