### ISSUE TITLE
[Quest] Death Comes From On High - (issue 1) - DK quest chain

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1899]
ID 12641

This quest worked fine about a week ago...
Now you don't even get the spells on your bar to use when  controlling the eye of acherus.

**How it should work:** 
The DK in control should receive the abilities of Eye of Acherus https://www.wowhead.com/npc=28511/eye-of-acherus in order to complete the quest. 
Namely https://www.wowhead.com/spell=51859/siphon-of-acherus 
https://www.wowhead.com/spell=52006/shroud
https://www.wowhead.com/spell=51904/summon-ghouls-on-scarlet-crusade
https://www.wowhead.com/spell=52694/recall-eye-of-acherus

**How it works atm:** 
Can't complete the quest due to having no abilities. Note I am on the correct patch using launcher, disabled all addons, relogged, cleared cache, made multiple DKs.

PS: and the NPC 28511 is slow as fuck, was already reported https://github.com/WoWManiaUK/Blackwing-Lair/issues/471

**Comment by kDracku** [comment]
Seems it dosent work for Horde - http://i66.tinypic.com/11tu51w.jpg
You cannot go down with the Eye

**Comment by gitkulu** [comment]
Not just Horde, same problem with Alliance. You can't move up or down so it's impossible to complete the objectives.

**Comment by Rushor** [comment]
on dev the quest works fine except the speed :o

**Comment by Kitzunu** [comment]
@Rushor Last I checked it did not work.
I think Janitor might have copied over the script from WotLK though and not updated it here...

I will see with him later

**Comment by Echinaceax** [comment]
@Kitzunu jani and rusher and frostman worked on this an hour ago ;)

**Comment by Echinaceax** [comment]
new test commencing from the start now so we will see :)

**Comment by Frostmanx** [comment]
Its working now like before the eye can be moved up and down only thing is the speed is slow :) But the quest can be completed without any problems!
![WoWScrnShot_052619_183053](https://user-images.githubusercontent.com/50195620/58382167-9f190980-7fe4-11e9-9ce1-48a9d7c9bad9.jpg)

**Comment by Echinaceax** [comment]
New information on this quest still bugged #4542

update - test on live no issues
