### ISSUE TITLE
[NPC] Innkeeper Kauth (probably general vendor issue)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#19]
There are problems with displays and actual price of vendor NPCs for food and drink type of items.
2 things i noticed so far:

1) Displayed vendor prices for food and drink at the title NPC are incorrect.
Example: "Refreshing Spring Water" says to cost 23 copper, however upon purchasing one time, you lose 1 silver 18 copper, which is the intended value for the item next to it, "ice cold milk".
Ice Cold Milk displays it costs 1 silver 18copper, but even with 4 silver in your bags, it says "you don't have enough money to purchase the item". Cannot determine how much its actual cost is, as a lvl 5 hardly gets above 5 silver at this point.
This is partly visual problem, as the display is wrong, partly major gold issue, as the intended price is the displayed one , which is not in effect. The amount you lose when trying to purchase a few-copper lowbie drink can easily run a lowbie's budget dry with just 2 clicks without them being aware atm.

The other vendors I tested in Deathknell, seem to have same issue with Food and Drink category items as far as I can tell. Armor and Weaponry price is displayed and deducted correctly at the other vendors.

2) Innkeeper Kauth http://www.wowhead.com/npc=6747 has two messages that show up as "I want to browse your goods". The upper one actually opens a dialogue where he explains what you can do in inns, it should be a dialogue option "What Can I do in an Inn?" that Innkeepers often have. This is merely visual problem.

**Comment by Zunrin** [comment]
For the first issue, it might actually be trying to sell you the drinks at 23c per item rather than per 5 items (would need to test with another vendor).

**Comment by Dranah** [comment]
5x23 is 115 which is 1 silver 15 copper. Not 1 silver 18 copper. The pricing is simply wrong, it has the price of the higher drink.

**Comment by Dranah** [comment]
The issue persists.

**Comment by fvicaria** [comment]
What issue? Delete cache the vendor looks perfectly fine. Post image.

**Comment by Dranah** [comment]
That was the smaller issue! Indeed, that part is fixed, I give you that.

Problem number 1 was that the vendor price for food and drinks is wrong and it is a general vendor issue. Try buying anything from him and it will cost 5 times more than displayed.

**Comment by fvicaria** [comment]
The cost is the quantity x the price of the unit
Buy a single item somewhere and check
