### ISSUE TITLE
[Battle Elixirs / Buffs] Stacking

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1900]
I have like 4 battle elixirs on me : http://i66.tinypic.com/2q8wyv5.jpg
Im pretty sure the stacking works with all , even flasks and other types of food (never tried with food or flaks) but it can be.

**Comment by kDracku** [comment]
Sometimes even the buff from Hellfire remains while you join the dungeon or the one from Terrokar Forest with 5% dmg increase

**Comment by Echinaceax** [comment]
@kDracku - 

> Sometimes even the buff from Hellfire remains while you join the dungeon or the one from Terrokar Forest with 5% dmg increase

make a seperate report anot that please :)

**Comment by Kitzunu** [comment]
Fixed
