### ISSUE TITLE
[NPC] Stone Guard Stok'ton -missing-  Shattered Halls

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1901]
**Links:**

https://www.wowhead.com/quest=29688/advancing-the-campaign

**What is happening:**

The NPC is missing

**What should happen:**
You need to talk with Stone Guard Stok'ton inside Shattered Halls

**Comment by sarahkay88** [comment]
This is the horde npc __ ally has the same issue #1840

**Comment by Rushor** [comment]
depending on which faction enters the dungeon > creature added.
