### ISSUE TITLE
[Boss] Erunak / Mindbender Ghur'sha - Throne of the Tides

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1902]
https://www.wowhead.com/npc=40788/mindbender-ghursha
https://www.wowhead.com/npc=40825/erunak-stonespeaker

This encounter is completely broken and not possible to complete.

**How it should work:**
You first fight a mind-controlled Erunak until he hits 50% health and the Mindbender detaches from him. The Mindbender is unattackable while attached to someone.
At 50%, Erunak turns friendly and Mindbender Ghursha becomes attackable.
Ghursha then periodically mind controls a player (excluding the 1# threat, alas the tank), in place of Erunak. This mind control https://www.wowhead.com/spell=76207/enslave can be cast from 60 yards away but will only take effect when Ghursha physically reaches his target, so kiting is an option to delay his MC.
This is similar to phase1 except a player is empowered and Ghursha uses the player's abilities at random (including profession casts!)
Just like Erunak, the player also must be damaged below 50% health to detach Ghursha again. Moreover, being below 50% health instantly breaks the MC if he targets you, sort of preventing trouble.
Whenever Ghursha is detached, he attacks you and can be damaged and killed.
PS: the MC has 30sec duration, then it expires on normal mode, or kills the target on heroic mode

**How it works atm:**
It's all fun and games while fighting Erunak, but at 50% when Ghursha is detached, he is by no means attackable. 
He has some kind of "mount" icon that can be clicked if a player volunteers to be under his control, but it doesn't really do anything to get the fight forward. He doesn't move and doesn't attack in melee, but will cast his magic spells.
Damaging a player under mind control below 50% health doesn't break the mind control and since you can't anyhow damage Ghursha, you cannot finish the fight.

**Comment by Frostmanx** [comment]
Yes confirmed,this needs to be fix asap!

**Comment by Keader** [comment]
I will fix it in this weekend. 💃

**Comment by Keader** [comment]
Well, i cant fix it right now, charmed creature has a bug that dont change faction.
So i disabled possess event for now, and made some scripts improvements.
Now i think that boss can be finished.

**Comment by Dranah** [comment]
This will need a proper fix later, but the encounter is doable now without the MC in p2.

**Comment by Dranah** [comment]
There is one small issue left, which is that Erunak stays in combat at 50% health when the fight ends.
This keeps the group stuck in combat.
