### ISSUE TITLE
[Boss] Commander Ulthok - (spawns twice) - Throne of the Tides 

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1903]
https://www.wowhead.com/npc=40765/commander-ulthok

**How it works:**
He is spawned and possible to engage before doing the first boss (Lady Nazjar). The encounter goes as per normal and drops loot.
Afterwards, killing Lady Naz'jar allows you to spawn the intended Commander Ulthok, being able to do the encounter again, and loot again. 

**How it should work:**
He should not be present or attackable before defeating the first boss, Lady Naz'jar.
Only after she dies and you click the object outside her room, should trigger the spawn of the Commander after the cinematic.

**Comment by Dranah** [comment]
New info:
This only seems to happen on normal difficulty.

**Comment by Echinaceax** [comment]
**New info** 
Spawning 3 at the same time (on normal mode) now

![image](https://user-images.githubusercontent.com/39439201/115567057-22b7ff80-a2bb-11eb-818e-36aa14c26195.png)

**Comment by Echinaceax** [comment]
confirmed fixed in dev
