### ISSUE TITLE
[NPC] Orsis Survivor Uldum

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1905]
**Links:**

https://www.wowhead.com/quest=27519/under-the-choking-sands

**What is happening:**
Nothing happens when you click the
**What should happen:**
You need to click them in order to survive them from the sands

**Comment by sarahkay88** [comment]
NPC ID https://www.wowhead.com/npc=45715

**Comment by HrPottemager** [comment]
I would expect this be reported under Quest-
[Quest] Under the Choking Sands - ID 27519 - Uldum
Links:
Quest - https://www.wowhead.com/quest=27519/under-the-choking-sands
NPC - https://www.wowhead.com/npc=45772/general-ammantep

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/DLYiujO.jpg)
![I](https://i.imgur.com/jo7PfGC.jpg)
