### ISSUE TITLE
[NPC} All of them from quest Uldum

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1910]
**Links:**
https://www.wowhead.com/npc=47516
https://www.wowhead.com/npc=47519
https://www.wowhead.com/npc=47520
https://www.wowhead.com/npc=47707

https://www.wowhead.com/quest=28002/crisis-management

**What is happening:**
Nothing happens when you click them
**What should happen:**
You need to reassure the guests at Schnottz's Landing :D

**Comment by Echinaceax** [comment]
devs need npc ID links - ive edited them in

**Comment by kDracku** [comment]
Sorry and thanks

**Comment by sarahkay88** [comment]
#268
