### ISSUE TITLE
[Quest Item] Bottled Bileberry Brew Mount Hyjal

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1911]
**Links:**
https://www.wowhead.com/quest=25411/a-new-master
**What is happening:**
Nothing happens when using the quest item

**What should happen:**
You need to use the Bottled Bileberry Brew on the corpse of a Twilight Inferno Lord, then speak with him

**Comment by sarahkay88** [comment]
item id -https://www.wowhead.com/item=53120

**Comment by giles1508** [comment]
tested this on about 20 kills now and indeed nothing is working,   can we get this confirmed please so we are able to .bq it,   thanks

**Comment by zippoking** [comment]
Quest: https://www.wowhead.com/quest=25411/a-new-master
Item: https://www.wowhead.com/item=53120/bottled-bileberry-brew
NPC: https://www.wowhead.com/npc=39974/twilight-inferno-lord
NPC after item use: https://www.wowhead.com/npc=40093/subjugated-inferno-lord


**How it is:**
After using the item on a dead inferno lord, nothing happens. The subjugated inferno lord does not spawn.
![A new Master - how it is](https://user-images.githubusercontent.com/18005338/60381897-99876700-9a5b-11e9-9696-02a5c3aaa2a9.png)


**How it should be:**
After using the item on a dead inferno lord, the subjugated inferno lord spawns. You can turn in the quest and accept a new one.
![a new master - how it should be](https://user-images.githubusercontent.com/18005338/60381896-99876700-9a5b-11e9-81c9-e506b719d5af.png)

**Comment by Rushor** [comment]
fixed with next update

![I](https://i.imgur.com/T0h4Hrm.jpg)
