### ISSUE TITLE
[Quest] Gather the Intelligence

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1912]
**Links:**
https://www.wowhead.com/quest=25296/gather-the-intelligence

**What is happening:**
They re missing
**What should happen:**
You should gather them

**Comment by Kitzunu** [comment]
https://www.wowhead.com/object=202968
https://www.wowhead.com/object=202969

Entries of the missing objects. (Check the loot table in db too!)

**Comment by sarahkay88** [comment]
#242
