### ISSUE TITLE
[Quest] The Activation Rune Basin -12547- Un'Goro Crater

### ISSUE THREAD

**Issue by Nestrior** [WoWManiaUK/Blackwing-Lair#1913]
**Links:**

https://www.wowhead.com/quest=12547/the-activation-rune
from WoWHead or our Armory

**What is happening:**
In the quest leading to the area, the gateway does not work. The quest itself has 1 enemy and the room is completely empty. No way to get the quest item and continue along the chain.

**What should happen:**
The area should have more enemies, including a small boss at the end of the room that drops the Rune.

**Comment by zippoking** [comment]
Missing NPC: https://www.wowhead.com/npc=28601/high-cultist-herenn
Missing NPC: https://www.wowhead.com/npc=28602/deaths-hand-acolyte

Item, which should be dropped from Herenn: https://www.wowhead.com/item=38708/omega-rune

**How it is:**
![The Activation Rune - how it is](https://user-images.githubusercontent.com/18005338/59692148-a0ed7b80-91e4-11e9-9ec0-04a3e5bccb99.png)

**How it should be:**
The NPC High Cultist Herenn should be in this room and drop the omega rune on kill.
![The Activation Rune - how should be](https://user-images.githubusercontent.com/18005338/59692150-a0ed7b80-91e4-11e9-95ff-fbf889f3d911.png)

**Comment by Rushor** [comment]
okay spawn and loot added

![I](https://i.imgur.com/v0iDrg1.jpg
