### ISSUE TITLE
[Daily JC] A Present for Lila

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1915]
**Links:**
https://www.wowhead.com/quest=25160/a-present-for-lila
**What is happening:**
It dosent give credit for cuting
**What should happen:**
Should give progress for both : crafting+cuting

**Comment by Saintres** [comment]
i Have the same problem, the cut dont count

**Comment by Toorok** [comment]
The q still doesn't count the gem cuts
