### ISSUE TITLE
[NPC] Illycor -25680- Blasted Lands

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1916]
**Links:**

https://www.wowhead.com/quest=25680/thats-not-us
https://www.wowhead.com/npc=41163/illycor

**What is happening:**
When you engage this boss quest ,  after serveral time if you re not quick to kill it (as lvl 54+ you cannot 1 shot him) you will be teleported to Andorhal - Western Plaguelands for no reason
**What should happen:**
Kill quest boss , take reward

**Comment by Echinaceax** [comment]
reported here #4809
