### ISSUE TITLE
[Boss} Ozumat -loot table- Throne of the Tides

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1919]
**links**
https://cata-twinhead.twinstar.cz/?item=55879

**Whats happening**
I got this trinket http://i68.tinypic.com/vhahpx.jpg 
Ozumat and hes loot table is: http://i64.tinypic.com/200a4w8.jpg
The trinket Sorrowsong drops from Siamat - Lost City of the Tol'Vir -> http://i67.tinypic.com/o7pmhl.jpg

**Comment by Dranah** [comment]
He still drops loot from lost city of tol'vir, all but that one trinket which kitzu fixed. Can you remove ALL tol'vir loot and add his own?

**Comment by Rushor** [comment]
reference_loot_template is messed up, will assign the correct table to GO_NEPTULONS_CACHE_NORMAL               = 205216,

**Comment by Rushor** [comment]
![I](https://i.imgur.com/RlKMxtj.jpg)
