### ISSUE TITLE
[Spell] Ancenstral Spirit/Rez

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1920]
**Links**
https://www.wowhead.com/spell=2008/ancestral-spirit

**Whats happening**

Ancenstral Spirit = Redemption = Resurection
If the target from your group dies and release and you ressurect hes corpses the target dosent see the ressurection thing (Accept , Decline).
That it wierd because you should see it if you release and some one rez your corpse

**Comment by Dranah** [comment]
cannot reproduce this
I can accept rezz without problems
Chances are your party member was noobing around, UI or client issue could be in place too.
