### ISSUE TITLE
[Item] Sorrowsong -trinket-

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1922]
**Links:**
https://cata-twinhead.twinstar.cz/?item=55879
**What is happening:**
It dosent proc
**What should happen:**
As the trinket says if the target is below 35% you get 1512 spell power for 10 seconds

**Comment by Slydee23** [comment]
reopen pls

**Comment by Rushor** [comment]
added a small adjustment. pls retry with next serverupdate :)

**Comment by Slydee23** [comment]
ill do thank you

**Comment by Slydee23** [comment]
our mage and shaman tested it and seems still not to procc
