### ISSUE TITLE
[Item] Heart of Solace -trinket-

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1924]
**Links:**
https://www.wowhead.com/item=55868/heart-of-solace&bonus=4153
http://i68.tinypic.com/2nuotc4.jpg
**What is happening:**
It dosent proc at all
**What should happen:**
As the trinket says : Your melee attacks have a chance to grant 2133 Strength for 20 sec.

**Comment by Keader** [comment]
Fixed.
Was only proccing with melee hits.
But need proc with melee hits and melee spells.
