### ISSUE TITLE
Priest [Shadow-Talent] Masochism- 88995

### ISSUE THREAD

**Issue by Frostmanx** [WoWManiaUK/Blackwing-Lair#1926]
**Links:**  https://cata-twinhead.twinstar.cz/?spell=88995

from WoWHead or our Armory

**What is happening:**  You gain 10% of mana while this talent is active from every single melee attack which are not even 10% of your maximum health. So each time you get hit you gain 10% mana and the self damage by shadow word death does not proc the mana gain .

![WoWScrnShot_051519_171310](https://user-images.githubusercontent.com/50195620/57869091-e43d7e80-7821-11e9-92aa-a00376f0eab1.jpg)

**What should happen:**

When you take a damaging attack equal to or greater than 10% of your total health or damage yourself with your Shadow Ward: Death, you instantly gain 10% of your total mana.

**Comment by Echinaceax** [comment]
@Frostmanx - nice find :)
no mana probs wouldnt that be nice lol
