### ISSUE TITLE
[NPC] Kel'Thuzad Borean Tundra

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1929]
**Links:**

https://www.wowhead.com/quest=11636/magic-carpet-ride

**What is happening:**
After talking with Yanni at Warsong Hold he will give you a ride to Gorge the Corpsegrinder
The problem is you fly above Kel'Thuzad and as low level he will one shot you (http://i67.tinypic.com/t88dus.jpg) and you arrive there dead and cant complete the quest.
**What should happen:**
Kel'Thuzad should not cast anything to you.

**Comment by Dranah** [comment]
Already reported under the quest
https://github.com/WoWManiaUK/Blackwing-Lair/issues/1738

**Comment by Kitzunu** [comment]
Please Close duplicate reports when they are seen so we keep the repo somewhat clean :D
