### ISSUE TITLE
[Spell] Shaman T12 - 4P Bonus

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Blackwing-Lair#1930]
4P : https://www.wowhead.com/spell=99206/item-shaman-t12-elemental-4p-bonus
It should make Lava Burst instant cast but it dosent.

**Comment by kDracku** [comment]
In my post down bottom had for both bonuses :P

**Comment by Keader** [comment]
I splitted it.
Is 2 bonus, 2 spells, 2 fixes.
