### ISSUE TITLE
[Item] Tendrils of Burrowing Dark -trinket- (Test)

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1936]
https://www.wowhead.com/item=56339/tendrils-of-burrowing-dark
It did 0 procs - http://i64.tinypic.com/byjq8.jpg (N/HC tested)

**Comment by Kitzunu** [comment]
For consistency please use the template that is given for future reports.

Thank you for your contribution, it is appreciated!

**Comment by Rushor** [comment]
chance is 10 percent
