### ISSUE TITLE
[Dungeon] Throne of the Tides teleporter

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1937]
https://www.wowhead.com/npc=51395/throne-of-tides-teleporter
This npc is the teleporter that should activate once you killed Lady Naz'jar, to allow players a free port between the two floors of the instance
Between this spot 
![WoWScrnShot_051619_231416](https://user-images.githubusercontent.com/31132743/57887669-5e74ff80-7830-11e9-9729-a66cf06cfb3e.jpg)
And this one
![WoWScrnShot_051619_231555](https://user-images.githubusercontent.com/31132743/57887724-8d8b7100-7830-11e9-8781-4810edea9c1a.jpg)

Currently doesn't function , you have to walk all the way. Just an annoyance but still.

**Comment by Rushor** [comment]
teleporters also fixed with next update 

![I](https://i.imgur.com/7KTfRVI.jpg)
![I](https://i.imgur.com/jSrlBov.jpg)

**Comment by Rushor** [comment]
only works of course once Lady Naz'jar is killed
