### ISSUE TITLE
[Boss] Lady Naz'jar - heroic - Throne of the tides

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1939]
https://www.wowhead.com/npc=40586/lady-nazjar

After clearing the trashes and reaching her boss room, she isn't attackable.
You have no means to engage her and therefore complete the dungeon.

This is only on heroic, she works fine on normal.
![WoWScrnShot_051619_233703](https://user-images.githubusercontent.com/31132743/57888825-8154e300-7833-11e9-8a52-0d5cb542d38c.jpg)

**Comment by Kitzunu** [comment]
Try now

**Comment by Dranah** [comment]
Still broken.

**Comment by Kitzunu** [comment]
I think this is script related

**Comment by wow-mania** [comment]
Please re-test
This works fine on dev.

**Comment by Dranah** [comment]
Fix was just applied. It works fine on PTR now.
