### ISSUE TITLE
[NPC/Loot] Rom'ogg Bonecrusher Drops No loot

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Blackwing-Lair#1941]
**Links:**
https://www.wowhead.com/npc=39665/romogg-bonecrusher

**What is happening:**

Rom'ogg Bonecrusher did not drop any loot on normal difficulty.

**What should happen:**
Rom'ogg Bonecrusher should always drop  loot on normal difficulty.

**Comment by Echinaceax** [comment]
something went wrong here #1772

**Comment by slaniaxx** [comment]
woops .) thank you

**Comment by Dranah** [comment]
Please don't open 2nd thread for same issue. Reopen old.
