### ISSUE TITLE
[NPC] Lieutenant Drake Caverns of Time: Old Hillsbrad Foothills

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1947]
**Links:**

https://www.wowhead.com/npc=17848/lieutenant-drake

**What is happening:**
You cannot attack him.
http://i63.tinypic.com/2v1vo00.jpg
**What should happen:**
After planting the Incendiary Bombs he should come back down the stairs and kill it

**Comment by georgeapostolov** [comment]
Should be fixed. I'm doing it every day.

**Comment by Denrunmt** [comment]
I can confirm that the boss is not attackable on NORMAL difficulty. On heroic he can be killed.
![Screenshot_7](https://user-images.githubusercontent.com/52254524/63234582-85333f80-c23e-11e9-9e2b-c89db061abc6.png)

**Comment by Rushor** [comment]
attackable n nh too now.
