### ISSUE TITLE
[Glyph] of Lightning Shield

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1949]
**Links:**
https://wow.gamepedia.com/Glyph_of_Lightning_Shield
**What is happening:**
Charges are dropping below 3 stacks and it should not
http://i68.tinypic.com/2j1aer5.jpg
http://i64.tinypic.com/sl1yc8.jp
http://i67.tinypic.com/2ldx56t.jpg
**What should happen:**
As the glyph says charges should not drop below 3 charges

**Comment by Dranah** [comment]
Glyph item ID 41537
Glyph ID 225
Lightning Shield spell ID 324
Glyph of Lightning shield spell ID 55448

**Comment by TheSale** [comment]
I also have same issue.
