### ISSUE TITLE
[Glyph] of Healing Stream Totem

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1950]
**Links:**
https://wow.gamepedia.com/Glyph_of_Healing_Stream_Totem
**What is happening:**
It dosent give Fire/Frost/Nature resist
http://i68.tinypic.com/et9moo.jpg
http://i68.tinypic.com/315ibn9.jpg
**What should happen:**
Healing Strem Totem should give Fire/Fost/Nature resit

**Comment by Dranah** [comment]
Glyph item ID 41533
Glyph ID 222
Spell ID healing stream 5394
Spell ID glyph of healing stream 55456
