### ISSUE TITLE
[spell] druid flight forms

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#1953]
**Links:**

https://cata-twinhead.twinstar.cz/?spell=33943       flight form
https://cata-twinhead.twinstar.cz/?spell=40120       swift flight form

**What is happening:**

when you purchase the swift version, it replaces the normal version,   and doing so causes you to not be able to use flight form

**What should happen:**

what should happen is 2 different spells,   and then on the druids shapeshift bar,   its supposed to show the form that matches what speed of flying you have,    
i.e   if you have 150 % it shows normal,     if you have 280 or 310 %   it shows swift form

**Comment by Echinaceax** [comment]
issue here in new report #1955 
@devs see which you use and close the other

**Comment by Echinaceax** [comment]
Aslo been meaning to SS this 

![no speed](https://user-images.githubusercontent.com/39439201/58034227-5c5bbb00-7b26-11e9-8b8f-d084eaed6080.jpg)

Not sure if this is why the spells bug (not sure if visual bug or system isnt regestering speed learnt)
