### ISSUE TITLE
[Spell] Hand of Gul'dan

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1959]
ID 71521

Demonology core spell with multiple issues.

- [x] 1) Damage is low

With approx 1,6k base points and a sp coefficient of 96,8%, warlock with 5,6k spell power
Expected damage: 7,1k + 15% from Demonic Knowledge = ~8,2k dmg
Actual damage on this test is somewhere around 5-6k.
The coefficient is probably wrong. 
**How it should work**: Sp coefficient must be set to 96,8% (current, by test looks like around 50-60%)

- [x] 2) The area effect

Landing a successful Hand of Guldan on an enemy should pop an aura within 4 yards increasing all target's chance to be crit by the warlock's demon pets by 10% for 15sec.
Spell ID 86000 (Curse of Gul'dan)
Aura currently doesn't work at all.

- [x] 3) An invisible pet

Comes with the package right now, when you cast the spell, it summons an invisible BUT targetable creature called "Hand of guldan" https://www.wowhead.com/npc=46157/hand-of-guldan
This guy will dutifully melee the enemies for often more damage than your own pet (while lvling), since he is a level 80 guy with a fixed 5,3k health that can come very handy when you're barely lvl 30. 
Love him, but he's not intended to be a pet. I'm not sure what purpose he normally serves for the spell, might be a marker NPC for the aura effect (Curse of Guldan) that does not work. 
![WoWScrnShot_051819_205908](https://user-images.githubusercontent.com/31132743/57973889-18df4080-79b0-11e9-8776-75c2db276856.jpg)

**How it should work:** assuming the npc is meant to be an invisible marker (as he spawns directly under target), he should not be targetable and he must not engage in combat with the enemies.

**Comment by Keader** [comment]
Low damage fixed.

**Comment by Keader** [comment]
Everything fixed now xD
