### ISSUE TITLE
[NPC] Nohi Plainswalker - Orgrimmar

### ISSUE THREAD

**Issue by ScoobyPwnsOnU** [WoWManiaUK/Blackwing-Lair#196]
https://www.wowhead.com/npc=44743/nohi-plainswalker

![image](https://user-images.githubusercontent.com/41521670/50133146-ef2ebb80-024f-11e9-97ef-769ff53ed55b.png)

Hunter trainer that doesn't train.

**Comment by Echinaceax** [comment]
@wow-mania - not fixed 

Although it was working but something mess up, coz its not working now
