### ISSUE TITLE
[Spell] [Inscription: Darkmoon Card of Destruction]

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#1961]
**Links:**
https://www.wowhead.com/spell=86615/darkmoon-card-of-destruction
https://www.wowhead.com/item=61987/darkmoon-card-of-destruction

**What is happening:**
creates this item darkmoon-card-of-destruction

**What should happen:**
shoud create a rnd card of a deck 

[Earthquake Deck]
https://www.wowhead.com/item=62046/earthquake-deck
[Hurricane Deck]
https://www.wowhead.com/item=62045/hurricane-deck
[Tsunami Deck]
https://www.wowhead.com/item=62044/tsunami-deck
[Volcanic Deck] 
https://www.wowhead.com/item=62021/volcanic-deck

**Comment by TheSale** [comment]
Same issue here, and I would set this as high priority since it is very expensive item to craft and it give one of the very good if not best trinkets pre raid in game.

**Comment by giles1508** [comment]
once this does get fixed is there any way we can get the cards that have bugged out turned into random cards please ?

**Comment by Echinaceax** [comment]
> once this does get fixed is there any way we can get the cards that have bugged out turned into random cards please ?

PM janitor and link this issue for him. he is the one for refunds

**Comment by Chargelol** [comment]
i have no idea if we get a refund on cards maybe pm janitor for bugged crads.

**Comment by TheSale** [comment]
any updates on this issue?

**Comment by Rushor** [comment]
random ace will be added now.

**Comment by Chargelol** [comment]
working now
