### ISSUE TITLE
VIP Mail

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#1962]
http://prntscr.com/nqhc6t

Vip mail do not register mail received

after using .vip mail it bug mail system for even regular mail, it dont show received mail on regular mailbox after using .vip mail, relog solve this issue.

But when I look my received mails on regular mailbox and then use  .vip mail I cant take received items from mail.

Also I cant send mail

**Comment by wow-mania** [comment]
it shows mail you have.
not notification of new mail.
as-is

**Comment by TheSale** [comment]
@wow-mania 
I had 2 new mails next to minimap you can see mail notification, I send 1 mail myself and other was notification that I have vip activated.

any time I use .vip mail my mailbox is bugged, cant send mail or take stuff from mailbox until I relog.

- it does not show new mail that is received
- it does show mail that you already have checked on regular mailbox
- it does not allow withdraw items from mail using .vip mail
- it does not allow send items or gold using .vip mail
- it bug mail system for regular mailbox as well until you have re log

if this is intent work then ok

**Comment by Echinaceax** [comment]
@wow-mania As you know this is a paid service and for that people do expect things to work.

Ok i understand the it show mail you have (correct) but 

1. not being able to send mail ?
2. Not being able to withdraw mail ?

this is not intended surely ?

**Comment by wow-mania** [comment]
Found the issue.
