### ISSUE TITLE
[Glyph] of Bloodletting

### ISSUE THREAD

**Issue by Nestrior** [WoWManiaUK/Blackwing-Lair#1963]
**Links:**
https://cata-twinhead.twinstar.cz/?item=40901

**What is happening:**
Mangle and Shred do not extend the duration of Rip on the target.

**What should happen:**
Mangle and Shred should extend the duration of Rip by 2 seconds, to a max of 6.

**Comment by giles1508** [comment]
multiple tests on lots of heroics on this and dummy and this doesn't work at all

**Comment by Rushor** [comment]
@Keader

**Comment by Dranah** [comment]
Shred properly extends it, Mangle (cat) (ID 33876) still does not.
