### ISSUE TITLE
[Zone] WoW-Reign's Mall 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1964]
**Links:**

**What is happening:**
- Players are not neutral
- Could cause many ganking issues 

**What should happen:**
- Players should be neutral (like dalaran)

**Comment by Frostmanx** [comment]
@Echinaceax  It's not neutral but you cannot attack them the last time I tried( for testing purpose of course)

**Comment by Echinaceax** [comment]
@Frostmanx haha oh good to know thx :)
