### ISSUE TITLE
[NPC] Fungal Terror -43954- Deepholm

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1973]
**Links:**
https://www.wowhead.com/npc=43954/fungal-terror

![this is when i freeze up](https://user-images.githubusercontent.com/39439201/58022980-f7e13180-7b0e-11e9-9483-b560188a94cd.jpg)

screen freeze / wow not responding

![Grrrrrr](https://user-images.githubusercontent.com/39439201/58022986-fe6fa900-7b0e-11e9-904b-5b62fedcfe41.jpg)

**What is happening:**

insane screen freeze (had to be ported by GM)
Constant sound moans groans (gives issues)
Not just me ive heard that others same issue if there are more mobs than there should be

**What should happen:**

Shouldnt be that many or agression lowed
note: will disable sound (see if that helps)
but something is wrong if ppl have to disable the sound to be able to be in that zone

**Comment by Rushor** [comment]
rework spawns from scratch

**Comment by Rushor** [comment]
![I](https://i.imgur.com/JT24nQM.jpg)
