### ISSUE TITLE
[QUEST] Inside The Frozen Citidale - Forge of Souls

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1974]
**Links:**
QUEST - https://www.wowhead.com/quest=24510/inside-the-frozen-citadel
NPC PICK UP - https://www.wowhead.com/npc=37776
HAND IN NPC -https://www.wowhead.com/npc=37597
Zone -https://www.wowhead.com/the-forge-of-souls

**What is happening:**
Unable to hand in the above quest because the gates to the dungeon are inactive and players cannot open it - this prevent players from being able to entre pit of saron and halls of refelection dungeons as this dungeon needs to be completed first

**What should happen:**
Players that do not uses the RDF should be able to activate the gate to the dungeon allowing players to hand in and complete the dungeon - there should be a cogwheel to allow players to entre

**Comment by Kitzunu** [comment]
Fixed, FoS gate should be able to be opened now

**Comment by TheSale** [comment]
if I remember correctly in cata there is no need for pre quest or anyting to enter ip PoS, but for FoS and HoR, yes!
in FoS jaina should give quest Echoes of Tortured Souls that is needed to go in PoS, but she dont have quest.

I tried this last night completed FoS, but could not go in next dungeon...

**Comment by sarahkay88** [comment]
@TheSale please make a new report for the issue to allow players to progress to next dungeon. This issue was to ooe fos for players to enter has previously the dungeon was closed.
