### ISSUE TITLE
[Wintergrasp/pvp] Join battle text missing - Wintergrasp

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1975]
**Links:**

![no text](https://user-images.githubusercontent.com/39439201/58032282-97f48600-7b22-11e9-937e-a38f654ed074.jpg)

**What is happening:**
- Join WG battle text missing 

**What should happen:**
Should have a join battle message and timer 

note: this auto - asks without out doing anything (i was in Stormwind at this time)

**Comment by sarahkay88** [comment]
![World of Warcraft 20_05_2019 17_21_15](https://user-images.githubusercontent.com/42302580/58036933-23224b80-7b24-11e9-9e61-4c1d0ad6051f.png)
![World of Warcraft 20_05_2019 17_23_15](https://user-images.githubusercontent.com/42302580/58036937-24ec0f00-7b24-11e9-8d5c-e5d4ebf83542.png)
this message spams u no matter were you are in northrend as soon has the battle becomes active u get the message box.  I been in solazar basin for over 15 mins no were near the wg but still get the message

**Comment by Kitzunu** [comment]
As far as I can see, at least from angels last post, she is queued for WG.

As for the text missing, I believe that is a client-side issue, which would require a new client update

**Comment by sarahkay88** [comment]
@Kitzunu I was queues for anything that's the issue

**Comment by Rushor** [comment]
cannot be fixed client side so far. server devs cannot do here anything

**Comment by Kitzunu** [comment]
I couldnt find anything in clinet for this either... Maybe it is missing
