### ISSUE TITLE
[PvP vendor]  Season 9 Vendor missing

### ISSUE THREAD

**Issue by z1179** [WoWManiaUK/Blackwing-Lair#1976]
**Links:**
Link to both Bloodthirsty and Vicious PvP sets : https://wow.gamepedia.com/Season_9

Link to all bloodthirsty pieces  https://cata-twinhead.twinstar.cz/?search=bloodthirsty#items

Link to all Vicious Gladiator's Pieces  https://cata-twinhead.twinstar.cz/?search=vicious+Gladiator%27s

**What is happening:**
As the season 11 vendor was deleted, a new season 9 vendor needs to be put in its place, 3 vendors will need to be added, 

1st Vendor: Honor Quartermaster
The honor quartermaster will need to sell Season 9 Blue armor&Weapons Item level 352-358, "Bloodthirsty Gladiator's " 

2nd Vendor: Conquest Quartermaster
The Conquest quartermaster will need to sell season 9 Epic Armor& weapons item level 359-365
"Vicious Gladiator's"

3rd Vendor: Glorious Conquest Quartermaster
The Glorious Conquest quartermaster will need to sell season 9 ELITE epic weapons item level 372 requiring Arena rating of 2200 or above (honestly this tier isnt required given the rate of progression and current server population, could dismiss the 2200 arena rating req.)

**Comment by Echinaceax** [comment]
any new updates on this @Rushor  @Kitzunu ?

**Comment by Kitzunu** [comment]
Got any NPC ids?

**Comment by Echinaceax** [comment]
> Got any NPC ids?

i just seen this wasnt been worked on ..i will get someone to get the ids @Kitzunu no problem

**Comment by Rushor** [comment]
@Echinaceax what should i add here now? :>

**Comment by Echinaceax** [comment]
> @Echinaceax what should i add here now? :>
i would add these now @z1179 Rusher, they are the honor ones

**honor**
Ally - Knight-Lieutenant T'Maire Sydes <Honor Quartermaster> 
https://cata-twinhead.twinstar.cz/?npc=52537
Horde - Blood Guard Zar'shi <Honor Quartermaster>
https://cata-twinhead.twinstar.cz/?npc=52536

**Comment by Slydee23** [comment]
@Echinaceax  
It looks like you found the one for next patch

Ally - Knight-Lieutenant T'Maire Sydes
https://cata-twinhead.twinstar.cz/?npc=51256

Horde - Blood Guard Zar'shi
https://cata-twinhead.twinstar.cz/?npc=46595

**Comment by Rushor** [comment]
tested and fixed with slydeer
