### ISSUE TITLE
[Spell] Anti-Magic Zone (NPC version)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1977]
ID 52894

This is the aura used by NPCs in the Acherus quest area at multiple points (Koltira escort,, Light of Dawn battle).
It should only affect friendly targets.

How it works atm: Affects ALL targets in it, including enemies.

**Comment by Keader** [comment]
Any specific place?
Because if you use .cast 52894 and walk around, close of enemys it will not hit then.
But if you walk around close of friends, it will hit then...
So, spell is working.
Maybe npcs has wrong faction or something?

**Comment by Dranah** [comment]
Possibly. I included the occasions where I saw this,  during the Koltira escort (on quest Bloody Breakout), and during the event of Light of Dawn battle. The zones are cast by Koltira in the first case, Highlord Darion Mograine (and possibly other DK NPCs) in the second, and both zones have the same ID 52894. And it affects both the player, the friendly NPCs and the hostile NPCs.

**Comment by Rushor** [comment]
try now pls
