### ISSUE TITLE
[NPC] Rugok <Legacy Justice Quartermaster> - level 359 epics

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1978]
This guy has a list of epic lvl 359 item rewards that should be sold for VALOR POINTS before Firelands patch.
How it works atm: they are currently sold for Justice points, just like the blue gears.

How it should work: should be sold for valor points

You can solve it in 3 ways: 
1) modify the currency they are sold for (from JP > to VP)
2) add a separate vendor who sells only these items for JP, remove the items being sold from current vendor
3) add two separate vendors, one selling blue quality items for JP, other selling epics for VP and remove the current one that sells both (temporarily). This latter might be handy when we need to modify it at the release of Firelands.

Epic 359 item ID list that is sold for points:
58190
58191
58192
58193
58194
58481
58482
58484
58485
58486
58195
58197
58198
58199
68812
64672
64673
64674
64676
58180
58181
58182
58183
58184
60248
60250
60251
60339
60340
60342
60349
60350
60352
60281
60283
60285
60287
60288
60290
60276
60278
60280
60304
60305
60307
60244
60245
60247
60360
60361
60363
60354
60355
60357
60344
60345
60347
60259
60261
60275
60254
60255
60257
60298
60300
60301
60313
60314
60316
60318
60319
60321
60309
60310
60312
60323
60324
60326
60329
60330
60332

**Comment by Rushor** [comment]
same issue for https://www.wowhead.com/npc=58154/toren-landow i guess

**Comment by Frostmanx** [comment]
Still there are some issues 

1. Rares are also sold for valor points and not justice points as intended
![WoWScrnShot_052719_140641](https://user-images.githubusercontent.com/50195620/58407350-39328d80-8089-11e9-813b-a622f58cf40a.jpg)

2. The class specific 359 items which are sold for valor points are missing for Priest/Paladin/Warlocks 
![Uploading WoWScrnShot_052719_141135.jpg…]()

**Comment by Dranah** [comment]
https://www.wowhead.com/npc=58155/rugok

**Comment by Dranah** [comment]
Ok so, i can confirm that it seems all item cost were changed to valor points (instead of just the ones I listed).

The horde tier sets are fine, so the 2nd) issue frostman reports is only for the alliance vendor.

**Comment by Frostmanx** [comment]
I will put the missing Item ID's for alliance tier sets

**Comment by Frostmanx** [comment]
missing item ID's for alliance Priest/locks/Paladins 
60275
60262
60261
60259
60258
60253
60254
60255
60256
60257
60344
60345
60346
60348
60347
60363
60359
60360
60361
60362
60355
60354
60356
60357
60358
60248
60249
60250
60252
60251

**Comment by Rushor** [comment]
could you list the items which should be sold for justice points then?

**Comment by Dranah** [comment]
@Rushor items meant for JP:
58126
58131
58101
58096
58106
58121
58130
58138
58163
58105
58099
58110
58125
58152
58128
58158
58133
58161
58103
58098
58108
58123
58150
58155
57924
57923
58127
58132
58160
58102
58097
58107
58122
58140
58154
57932
57930
57931
57933
57934
57929
57928
57927
58159
58139
58153
57925
57926
58129
58134
58162
58104
58100
58109
58124
58151
58157
57917
57918
57922
57914
57913
57915
57916
57919
57921
