### ISSUE TITLE
 [Achievement][Heroic: Shadowfang Keep Guild Run] id 5142

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#1979]
**Links:**
https://www.wowhead.com/achievement=5142/heroic-shadowfang-keep-guild-run

**What is happening:**
we dint got the Achievement while in a guild group .

**What should happen:**

we shoud have got the Achievement after we finished the dungeon.

**Comment by Rushor** [comment]
no, serverl missing things 

3>E:\TrinityCata\src\server\scripts\EasternKingdoms\ShadowfangKeep\instance_shadowfang_keep.cpp(104,21): error C2065:  'NPC_ASH': undeclared identifier
3>E:\TrinityCata\src\server\scripts\EasternKingdoms\ShadowfangKeep\instance_shadowfang_keep.cpp(105,21): error C2065:  'NPC_ADA': undeclared identifier
3>E:\TrinityCata\src\server\scripts\EasternKingdoms\ShadowfangKeep\instance_shadowfang_keep.cpp(106,21): error C2065:  'NPC_ARCHMAGE_ARUGAL': undeclared identifier
3>E:\TrinityCata\src\server\scripts\EasternKingdoms\ShadowfangKeep\instance_shadowfang_keep.cpp(107,21): error C2065:  'NPC_ARUGAL_VOIDWALKER': undeclared identifier
3>E:\TrinityCata\src\server\scripts\EasternKingdoms\ShadowfangKeep\instance_shadowfang_keep.cpp(109,22): error C2065:  'l_left': undeclared identifier
3>E:\TrinityCata\src\server\scripts\EasternKingdoms\ShadowfangKeep\instance_shadowfang_keep.cpp(130,32): error C2065:  'mOk': undeclared identifier
3>E:\TrinityCata\src\server\scripts\EasternKingdoms\ShadowfangKeep\instance_shadowfang_keep.cpp(133,65): error C2065:  'mOk': undeclared identifier
3>E:\TrinityCata\src\server\scripts\EasternKingdoms\ShadowfangKeep\instance_shadowfang_keep.cpp(136,79): error C2065:  'sAchievementMgr': undeclared identifier

**Comment by Bathelmo** [comment]
I've updated Janitor with the new version without those identifiers

**Comment by Bathelmo** [comment]
I cannot test this myself, my pc is too shit to hold more then 1 client

**Comment by Cenasty** [comment]
Basicly, no one works out now

We already have made several guild runs, for 3 to 5 guilds members, I think we did all dungeons in a, at least 3 guilds members groups, and yet, still no one Achievments has been done. 

https://puu.sh/E73FW/15a5066d5c.png

Aswell, this doesn't work also :

https://puu.sh/E73Hj/a601a49c60.png

**Comment by Rushor** [comment]
all runs weill be fixed here https://github.com/WoWManiaUK/Blackwing-Lair/issues/2043
