### ISSUE TITLE
Visual bug with profession trainers

### ISSUE THREAD

**Issue by ScoobyPwnsOnU** [WoWManiaUK/Blackwing-Lair#198]
I noticed if you don't have a profession trained the profession trainers display your current skill like this. I checked and training it changes it to 1 out of 75, I also made sure it didn't cause my earlier issue with being able to pick up profession quests that should have a skill requirement, and those quests are still obtainable even if I accept the profession so it shows 1/75.

![image](https://user-images.githubusercontent.com/41521670/50133374-ebe7ff80-0250-11e9-9d98-e46e190bedae.png)

**Comment by wow-mania** [comment]
This only happens until you get that profession. I won't be looking into it at this stage as is minimum.
