### ISSUE TITLE
[Dungeon] Shadowfang Keep heroic

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#1980]
There are some major problems in this dungeon.

1) Bosses have some glitch in their script which causes them to oneshot the tank with an unintended 20-30million damage swing.
They normally function well and the fights overall work nicely but at a fixed 20-25% health (this seems to match for every single boss in the dungeon, does not depend on the speed of you killing the boss) you see a random 10-digit damage swing on the MT, instantly killing him. 
The only boss who didn't produce this bug was Baron Ashbury, who doesn't melee attack at this point due to his Dark Archangel phase.

Note: this seems to be one fixed source of damage, that if you can soak/survive (bubble, battle rezz etc), you can continue the fight, but not every party may be capable of doing so. Therefore this bug will prevent most parties from completing the dungeon.

2) Reputation gain
Approximately 50% of mobs inside the dungeon award Horde expedition rep, even if you have a tabard equipped with another faction. (assuming for alliance, it is the counterpart Alliance vanguard)
There is no reason to a cataclysm dungeon to ever award Horde Expedition/Alliance vanguard rep. And if you have a specific tabard equipped, all mobs need to grant reputation with that faction.
List of NPCs inside dungeon:
https://www.wowhead.com/shadowfang-keep#npcs

3) Trash loot
There is no loot at all. Trash drops only silver coins, there is no cloth, no grey/white trash items, no greens, no rares.
Here is an example of trash loot table that need to be added (ONLY TO LEVEL 85 HEROIC DIFFICULTY!!)
https://www.wowhead.com/npc=47141/dread-scryer#drops:mode=heroic

**Comment by Rushor** [comment]
rep issue already fixed.

loot is reported in https://github.com/WoWManiaUK/Blackwing-Lair/issues/2986

/closes
