### ISSUE TITLE
[Quest]In Defense of Krom'gar Fortress - Stonetalon Mountains

### ISSUE THREAD

**Issue by Venom64bit** [WoWManiaUK/Blackwing-Lair#1982]
**Links:**
YT:https://www.youtube.com/watch?v=Pyu0qrC2-Oo
Quest: https://www.wowhead.com/quest=26058/in-defense-of-kromgar-fortress
1.NPCs: https://www.wowhead.com/npc=42017/gnome-wing-commander
2.NPCs: https://www.wowhead.com/npc=42016/gnomish-flying-machine
**What is happening:**
Nothing, there is no cannon to pick up for shoot on the enemy.
**What should happen:**
The Fortress is under attack from the Gnomish Flying Machines. You need to take a cannon for shoot them. When the Flying Machine explode, they release the Gnome Wing Commander on a parachute and the player can shoot on it.

-For info watch the YT video in Links-

**Comment by Echinaceax** [comment]
reported here #3299
