### ISSUE TITLE
[Quest] The Battle For The Ebon Hold- 13166 Phase Issue [DK stater quest]

### ISSUE THREAD

**Issue by Frostmanx** [WoWManiaUK/Blackwing-Lair#1986]
**Links:**
https://www.wowhead.com/quest=13166/the-battle-for-the-ebon-hold

**What is happening:**  After obtaining the quest and using the pink teleporter you are taken into the normal Ebon Hold phase where it has Vendors and stuff 
![WoWScrnShot_052119_231940](https://user-images.githubusercontent.com/50195620/58119365-6d88f280-7c20-11e9-879d-960ab1cce565.jpg)

**What should happen:**
It should be the phase where 10 Scourge and Patchwerk is there

![maxresdefault](https://user-images.githubusercontent.com/50195620/58119496-be98e680-7c20-11e9-8300-924b2578ff6c.jpg)

**Comment by Dranah** [comment]
Player is in phase 169 after using teleporter.
Quest objectives are in 177 (which is the correct phase for this stage of the questchain)

Player must enter phase 177 when arriving to this floor. This phase must then be removed when you hand in the quest.

**Comment by Frostmanx** [comment]
Fixed Confirmed in Dev
![WoWScrnShot_052619_161610](https://user-images.githubusercontent.com/50195620/58380706-0f6a5f80-7fd2-11e9-9dd6-94903def01d5.jpg) 

the only other issue is the SW Portal Doesn't work to hand in the quest (https://www.wowhead.com/quest=13188/where-kings-walk) and need to fly there :)

**Comment by Frostmanx** [comment]
https://www.wowhead.com/quest=13188/where-kings-walk  completed! Dk chain is fixed with minor issues :) and I have done it on dev from start without gm commands!
![WoWScrnShot_052619_162817](https://user-images.githubusercontent.com/50195620/58380885-e0092200-7fd4-11e9-8d5c-f934b338cd58.jpg)

**Comment by Frostmanx** [comment]
After completing the full quest chain and when you return to Ebon hold its still in phase 177 and not not the normal Ebon hold phase 
![WoWScrnShot_052619_170847](https://user-images.githubusercontent.com/50195620/58381299-41cb8b00-7fd9-11e9-80ba-8bf355b5d3d3.jpg)

**Comment by Rushor** [comment]
awesome nice. thanks for the testing @Frostmanx @Echinaceax

**Comment by Frostmanx** [comment]
Tested from start to finish for the second time 
![WoWScrnShot_052619_220924](https://user-images.githubusercontent.com/50195620/58384740-fd54e500-8002-11e9-9ba0-4fe88c7ebdfd.jpg) 

During the last quests you get a silenced debuff which goes away after 10-15mins after you complete the quest! Apart from that the DK chain can be done without any problems :)

**Comment by Dranah** [comment]
It can be completed by most, but Worgen/Goblin Get stuck on this quest due to phasing still. Works for other races, these two need fixing.

**Comment by Rushor** [comment]
@Dranah - worgen get stuck on the quest 13166 ?

**Comment by mattm72980** [comment]
@Rushor  I'm Worgen DK and got stuck here.

**Comment by Rushor** [comment]
yes indeed it's broke because of racemask in spellarea https://i.imgur.com/PfNhfMA.jpg

**Comment by Rushor** [comment]
for goblin and worgen fixed aswell now! 

![I](https://i.imgur.com/kHkQTm1.jpg)
![I](https://i.imgur.com/kHkQTm1.jpg)
