### ISSUE TITLE
[Item] Mylra's Knife Deepholm

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1990]
**Links:**
https://www.wowhead.com/quest=26766/big-game-big-bait
https://www.wowhead.com/item=60382/mylras-knife
**What is happening:**
When using Mylra's Knife on a dead Jadecrest Basilisks noting happens
**What should happen:**
Using the quest item (Mylra's Knife) you should obtain 5 sides from dead Jadecrest Basilisks

**Comment by Rushor** [comment]
duplicates removed and item is added upon spellhit on dead croco. (you need empty slot in inventory)

![I](https://i.imgur.com/x9PPccC.jpg)
![I](https://i.imgur.com/tL6ha8s.jpg)
