### ISSUE TITLE
[NPC] Aeosera Deepholm - Resonating Blow

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1993]
**Links:**
https://www.wowhead.com/quest=26659/resonating-blow
https://www.wowhead.com/npc=43641/aeosera
**What is happening:**
After using Stonework Mallet (https://www.wowhead.com/item=60266/stonework-mallet) on Resonating Crystal you cannot jump to the rocks and kill the dragon
**What should happen:**
After strucking the Resonating Crystal you should climb on the rocks to the dragon and kill it

**Comment by Rushor** [comment]
Links:
https://www.wowhead.com/quest=26659/resonating-blow
from WoWHead or our Armory

What is happening:
After you hit the crystal, and try to jump on the platforms, your char jumps up, but the "camera falls down again, but you can slightly see the character model standing on the rock"(hard to explain) and you take damage. If you try to jump off the rocks with the dismount button, you fall from the height you've clicked on, although your camera being on the ground (it sets your camera up again) which most likely kills you. Also Aeosera isnt attackable in any way. Quest can't be completed.

What should happen:
You should jump from rock to rock, fighting Aeosera, (dodgin her fires by alternating rocks), and finally get quest progress through defeating her. Quest should be completeable.

**Comment by fuzzydunlop** [comment]
Tried this today. For me nothing is happening. My char doesnt jump up, nor does my camera move (down). simply nothing happens after striking the the pale resonating crystal.

**Comment by kDracku** [comment]
You can jump on the rocks but the thing is you fall down from the 3-4ths one , tried also to with fly mount to put myself on the last rock but you will get 'into the rock' and the mob its not attackble

**Comment by Eirolla** [comment]
Fixed on Dup post. #2948
