### ISSUE TITLE
 [Quest] Violent Gale - Felsen the Enduring-Deepholm

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1995]
**Links:**
https://www.wowhead.com/quest=26426/violent-gale
https://www.wowhead.com/npc=44281/felsen-the-enduring-speak-credit
**What is happening:**
It dosent give credit talking to Felsen the Enduring and you cannot progres with the quest
**What should happen:**
After reaching him it should start a dialong and give credit for talking with it and you need to find the entrance to Crumbling Depths (https://www.wowhead.com/npc=44282/crumbling-depths-entrance-credit)

**Comment by Rushor** [comment]
wait i fixed that some time ago. i think it's regressed.

**Comment by Rushor** [comment]
here is a vid about it https://www.youtube.com/watch?v=jFLvCpdkZ7c

**Comment by Rushor** [comment]
refixed

![I](https://i.imgur.com/Me0C3DM.jpg)
![I](https://i.imgur.com/SflALTd.jpg)

**Comment by polymorphism98** [comment]
@Rushor - This looks like regressed once again. I can find the cave entrance and get that part complete. But the NPC part is not doable.
