### ISSUE TITLE
[Item] Horn of Challenge - Southern Barrens

### ISSUE THREAD

**Issue by Venom64bit** [WoWManiaUK/Blackwing-Lair#1996]
**Links:**
YT: https://www.youtube.com/watch?v=MymHQXDPFxw
Quest: https://www.wowhead.com/quest=24534/speaking-their-language
QuestGiver: https://www.wowhead.com/npc=11857/makaba-flathoof

**What is happening:**
You can't use the Horn of Challenge in the Arena.

**What should happen:**
After using the Horn of Challenge the enemy to be defeated should appear.

-Watch Youtube's Video in Link for more info-

**Comment by sarahkay88** [comment]
Item id -https://www.wowhead.com/item=49782

**Comment by sarahkay88** [comment]
#1633  - two different quest but related items
