### ISSUE TITLE
[Quest]  Easy money

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#1997]
**Links:**

link for the actual quest
https://www.wowhead.com/quest=27003/easy-money

link for complete quest order for uldum
https://wow.gamepedia.com/Uldum_quests

**What is happening:**
there is no camel to click on and no caravan at the quest giver to start the chain to uldum

**What should happen:**
here should be a caravan and a camel next to the quest giver, you should click the camel which then starts a cutscene,  then when cutscene ends you are taken to lower uldum where your locked in a cage next to budd and prince nadun at   59.8  71.81

**Comment by Echinaceax** [comment]
Reported already #1073
