### ISSUE TITLE
[Quest] Traitors!

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#1998]
**Links:**

link for actual quest
https://www.wowhead.com/quest=27922/traitors

link to quest order for uldum
https://wow.gamepedia.com/Uldum_quests

**What is happening:**
there is no bush at 61.7  71.3  that enables you to spy in Siamat

**What should happen:**
you are supposed to click a bush at the above location which then starts a cutscnene to spy on a conversation with Siamat,   upon completion of the cutscene you then hand in to get the next 3 quests in the chain

**Comment by kDracku** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/1908
