### ISSUE TITLE
character movement

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Blackwing-Lair#2]
Got several  chars  the killing quest work fine but when you try to loot  you stay in loot position and the loot wont open.
You have to relog to get standing  up again
i have it on draenei  bloodelf and worgen

**Comment by fvicaria** [comment]
Please be clearer. What quest, what mob, etc.
How can I reproduce it?
I think you will benefit from this....
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by gamer100** [comment]
![wowscrnshot_022718_163231](https://user-images.githubusercontent.com/33811022/36737729-056b50c6-1bdc-11e8-8186-30eef9509f52.jpg)
![wowscrnshot_022718_163245](https://user-images.githubusercontent.com/33811022/36737730-059eae6c-1bdc-11e8-9a53-a4ee4c5b9fb3.jpg)
The point is  you cant loot cause you stay in this position

**Comment by gamer100** [comment]
![wowscrnshot_022718_163708](https://user-images.githubusercontent.com/33811022/36737908-84b25938-1bdc-11e8-994f-500541f30985.jpg)
![wowscrnshot_022718_163719](https://user-images.githubusercontent.com/33811022/36737909-84d8b74a-1bdc-11e8-88a5-d3c66e039835.jpg)

**Comment by gamer100** [comment]
![wowscrnshot_022718_163933](https://user-images.githubusercontent.com/33811022/36738049-da41a5de-1bdc-11e8-9b0d-bd496e066f40.jpg)
![wowscrnshot_022718_163943](https://user-images.githubusercontent.com/33811022/36738051-da785e44-1bdc-11e8-99f1-e369030179f7.jpg)
The loot wont open and you stay in that position on al 3 chars

**Comment by fvicaria** [comment]
Fixed. It is the client issue.
Whisper me on skype or discord and I will send patch

**Comment by gamer100** [comment]
done
