### ISSUE TITLE
[Spell] Pounce

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2003]
**Links:**
https://cata-twinhead.twinstar.cz/?spell=9005

**What is happening:**

The stun duration for pounce isnt lasting a second,  when its meant to last for 3 seconds,  tested this on mobs all over WoW and its always the same,  most of them turn around to fight before i can get another spell off

**What should happen:**

the Stun duration should last for 3 seconds on all stunable targets including players

**Comment by Keader** [comment]
Tested in dummy and work fine.
Like any CC, it can get reduce time by resistence/resilience.
Tested in dummy and working fine.

**Comment by giles1508** [comment]
https://www.youtube.com/watch?v=8qq3Q0QXlXk   -    druid pounce video
https://www.youtube.com/watch?v=fZuDk-ALVvA   -  cheap shot video

in the above videos,  I have displayed that there is a clear issue with the duration,  both spells are on a 3 second stun duration,  and as you can see the rogue stun is clearly 3 seconds long,  while the druid stun is more like a second long
