### ISSUE TITLE
[Item] Super Healing Potion - Crashing the server

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#2007]
**Links:**
https://www.wowhead.com/item=22829/super-healing-potion

**What is happening:**
SERVER crashing when use 

**What should happen:**
That shouldnt happen

note: was mentioned in discord so i had to report myself

**Comment by Echinaceax** [comment]
Tested in dev - cant crash the server. tried 5x Super Healing Potion
@Devs - waiting more info

**Comment by wow-mania** [comment]
Maybe something not applied to live.
Will confirm today

**Comment by giles1508** [comment]
something has gone wrong again with this,  just had a guildie who drank this potion now and server crashed,   logged back in and asked him to drink it again to make sure and indeed server crashed again,   maybe this was the cause for all the crashes today?

**Comment by giles1508** [comment]
ok,  after a bit of testing tonight with trixie on horde side,   the server was crashing again when drinking a potion 100 %    but only when he was wearing this trinket

https://cata-twinhead.twinstar.cz/?item=68775

seems its the alchemist trinket thats still causing the server to crash

could we get this opened back up so a dev can take a look please

**Comment by Rushor** [comment]
hm this works on dev. is it still an issue on live?
