### ISSUE TITLE
[NPC] Neutral npc affecting [Spell] Travel Form 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#2008]
**Links:**
https://www.wowhead.com/spell=1066/travel-form
https://www.wowhead.com/npc=39418/green-sand-crab
https://www.wowhead.com/npc=48848/rockchewer-whelk
https://www.wowhead.com/npc=40280/swarming-serpent

**What is happening:**
- Neutral npc are removing the Aquatic form atm

**What should happen:**
not meant to do that

**Comment by Echinaceax** [comment]
@Kitzunu - this could be the same issue regarding the neutral mobs in start zones you fixed remember #879 ?

**Comment by Keader** [comment]
Sorry, i cant understand

**Comment by Echinaceax** [comment]
@Keader thats ok keader i will assign kitz ;)

**Comment by Echinaceax** [comment]
update, seems that other stealth forms are doing the same ...so it may not be a neutral npc issue, could be a spell issue as dracku mentions here https://github.com/WoWManiaUK/Blackwing-Lair/issues/3112#issuecomment-522437473
