### ISSUE TITLE
[Quest]: To the Greymane manor.

### ISSUE THREAD

**Issue by UnknownCombine** [WoWManiaUK/Blackwing-Lair#2009]
Quest: https://www.wowhead.com/quest=14465/to-greymane-manor

You have to go true the gate up to the manor. You can't get to the manor, there are more gates on one place and it wont let you pass it

When interacting with the door should open to let you pass. Besides, there should be a one door.
![WoWScrnShot_052219_144632](https://user-images.githubusercontent.com/50812024/58196177-1dea0b80-7ca0-11e9-9161-a6e95a5a82ad.jpg)

**Comment by sarahkay88** [comment]
I mentioned about double gates in the worgen report but didn't do a report so iv linked them :)

**Comment by Kitzunu** [comment]
Fixed

**Comment by Kitzunu** [comment]
I also increased the time to 5 seconds before it closes
