### ISSUE TITLE
[Achievement] Explore Southern Barrens

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#2010]
**Links:**
https://www.wowhead.com/achievement=4996/explore-southern-barrens

**What is happening:**
cant explore razorfen kraul
![WoWScrnShot_052219_225407](https://user-images.githubusercontent.com/50077942/58208254-a8545e80-7ce4-11e9-9048-259ee5d6998c.jpg)

**What should happen:**

shoud explore razorfen kraul around 40 , 94

**Comment by Chicozoba** [comment]
Hello, sorry for re-openning this thread but Razorfen Kraul is not explorable. I've tried everything I could to do it but I think it's bugged.

**Comment by Rushor** [comment]
try now pls ACHIEVEMENT_CRITERIA_TYPE_EXPLORE_AREA

**Comment by Echinaceax** [comment]
@will test in a few mins , thanks rusher

**Comment by Echinaceax** [comment]
@Rushor still cant get it , ive been at the front of the entrance and on top. still not fixed

![not yet](https://user-images.githubusercontent.com/39439201/64539446-cccd5880-d31e-11e9-87c3-19f950bc2010.jpg)

**Comment by will** [comment]
oh shit, are you making another game in the hearthstone world?

**Comment by Rushor** [comment]
strange bug

**Comment by Rushor** [comment]
boom fixed with next update

![I](https://i.imgur.com/qjUJFKw.jpg)
