### ISSUE TITLE
[NPC] Lord Harford - Missing - Plaguelands: The Scarlet Enclave.(Worgen) - DK Zone

### ISSUE THREAD

**Issue by gitkulu** [WoWManiaUK/Blackwing-Lair#2013]
**Links:**
Quest: https://www.wowhead.com/quest=28649/a-special-surprise
Missing NPC: https://www.wowhead.com/npc=49355/lord-harford

**What is happening:**

The Worgen NPC that needs to be killed is missing from the building.

**What should happen:**

Add the missing NPC.

**Comment by Frostmanx** [comment]
Hmm I don't remember seeing the worgen or goblin npc's too. Anyways the quest should work for all the races now. So the simple fix would be to add the goblin npc=49356 and the worgen npc=49355

**Comment by Echinaceax** [comment]
@wow-mania only seen with GM on 
not fix :)
