### ISSUE TITLE
[NPC] Gally-Lumpstain - Missing -Plaguelands: The Scarlet Enclave. (Goblin) -DK Zone

### ISSUE THREAD

**Issue by gitkulu** [WoWManiaUK/Blackwing-Lair#2014]
**Links:**
Quest: https://www.wowhead.com/quest=28650/a-special-surprise
Missing NPC: https://www.wowhead.com/npc=49356/gally-lumpstain

**What is happening:**

The Goblin NPC that needs to be killed is missing from the building.

**What should happen:**

Add the missing NPC.

**Comment by Kitzunu** [comment]
Please use the issue template when reporting issues.

Thank you for your time

**Comment by Echinaceax** [comment]
@wow-mania only seen with GM on (Goblin toon)
not fix :)
