### ISSUE TITLE
[Achievement] The fishing diplomat

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2021]
http://prntscr.com/nsii97

https://www.wowhead.com/achievement=150/the-fishing-diplomat

Achievement is not obtained trough many fishing in stormwind while I got ogrimar fishing checked

Achievement should be obtained just from fishing anything (one thing successful fished) from horde capital Ogrimmar and alliance capital Stormwind

**Comment by Kitzunu** [comment]
Please use the template made when reporting issues.

**Comment by TheSale** [comment]
> http://prntscr.com/nsii97
> 
> https://www.wowhead.com/achievement=150/the-fishing-diplomat
> 
> Achievement is not obtained trough many fishing in stormwind while I got ogrimar fishing checked
> 
> Achievement should be obtained just from fishing anything (one thing successful fished) from horde capital Ogrimmar and alliance capital Stormwind

**Links:**

from WoWHead or our Armory

**What is happening:**

**What should happen:**

what is out of template there?

**Comment by Kitzunu** [comment]
I will rephrase and say, please use the headings in your reports :D

Thanks for your time :)

**Comment by TheSale** [comment]
oh not to remove them?
I thought that ** ** should be removed sry

**Comment by karteil** [comment]
**Links:**
https://www.wowhead.com/achievement=150/the-fishing-diplomat

**What is happening:**
The achievement just count fish in Orgrimmar and not in Stormwind

**What should happen:**
It should simply count just one fish fished for each capital, actually only work for fish in Orgrimmar. I supposed it was an Horde-side problem but fishing with my worgen too doesn't not count the fish in Stormwind. 

Thank for your work!

**Comment by Echinaceax** [comment]
added to main report #4505

**Comment by Echinaceax** [comment]
going to reopen this one and fix it as a profession issue

**Comment by Echinaceax** [comment]
added to main report #5181

**Comment by Echinaceax** [comment]
confirmed fixed in PTR
