### ISSUE TITLE
[Quest] Lou's Parting Thoughts

### ISSUE THREAD

**Issue by UnknownCombine** [WoWManiaUK/Blackwing-Lair#2023]
https://www.wowhead.com/quest=26232/lous-parting-thoughts

Once the mission objective is complete, the NPC "Two Shoed Lou" (https://www.wowhead.com/npc=42405/two-shoed-lou), to which the mission must be delivered according to the details of the mission, is not available to interact. Which prevents the quest chain from completing.

The mission should be delivered at NPC "Lieutenant Horatio Laine" (https://www.wowhead.com/npc=42558/lieutenant-horatio-laine) according to WoWHead.
![WoWScrnShot_052319_182303](https://user-images.githubusercontent.com/50812024/58288266-777a3500-7d89-11e9-997e-ab8fe44fcaff.jpg)

**Comment by Kitzunu** [comment]
This is wrong detail on the quest.
You can hand it in to: Lieutenant Horatio Laine

I will change the description

**Comment by Kitzunu** [comment]
Fixed in dev, will be updated at next update.

You can hand the quest in, in-game at the correct questender

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/58290550-79a8b780-7dba-11e9-955c-2b803fd76f3f.png)

**Comment by gitkulu** [comment]
@Kitzunu So where is Lieutenant Horatio Laine? He's not where he's supposed to be.

![WoWScrnShot_060419_230443](https://user-images.githubusercontent.com/17096677/58914034-d2167800-871d-11e9-96cc-232b98c129bc.jpg)

**Comment by Echinaceax** [comment]
how did you even complete this with no thugs (tested in dev) 
my video https://gyazo.com/421dd045ae8d4300f94ccb7b2ad0e18d

youtube video https://www.wowhead.com/quest=26232/lous-parting-thoughts#videos:id=84168
