### ISSUE TITLE
[spell=80004] Spell Snake Trap

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#2026]
**Links:**
https://www.wowhead.com/spell=80004/snake-trap
from WoWHead or our Armory

**What is happening:**

The hunters snake trap dont do any damage to the targeted mobs.

**What should happen:**
The snakes should do some damage

**Comment by Dranah** [comment]
The snakes now dps.
There is a problem however with the trap failing when it's placed before combat begins. In this case no snakes spawn at all.
Steps to repro:
1) Place snake trap while not in combat with anything
2) engage a mob, kiting him through it
3) The trap is consumed, no snakes spawn, it has no effect.

**Comment by Keader** [comment]
Lul that's new.
Fixed.
