### ISSUE TITLE
[Quest] A Sort Of Homecoming - Plaguelands: The Scarlet Enclave - DK Zone

### ISSUE THREAD

**Issue by gitkulu** [WoWManiaUK/Blackwing-Lair#2032]
**Links:**
Missing quest: https://www.wowhead.com/quest=12751/a-sort-of-homecoming
Quest giver: https://www.wowhead.com/npc=29053/knight-commander-plaguefist
Prerequisite quest (Worgen): https://www.wowhead.com/quest=28649/a-special-surprise

**What is happening:**
Knight Commander Plaguefist does not offer the quest "A Sort Of Homecoming" to Worgens, even though the Prerequisite quest "A Special Surprise" (recent fix: #2013 ) has been completed.

**What should happen:**
Knight Commander Plaguefist should offer the quest "A Sort Of Homecoming" to Worgens who completed the Prerequisite quest "A Special Surprise".

PS: The same issue probably applies to Goblin DKs (see #2014 ) as well. Someone else will need to test this.

**Comment by gitkulu** [comment]
Possibly related to  #2053 ?

**Comment by wow-mania** [comment]
Works.
