### ISSUE TITLE
[Quest/Profession} Forged Documents (Inscription)

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2033]
**Links:**
http://prntscr.com/nswfke

from WoWHead or our Armory
https://www.wowhead.com/item=62062/bulging-sack-of-gold#reward-from-q

**What is happening:**
It show that I have received ``Bulging Sack of Gold`` but it is no where to be found in my bags, and as I clicked on link of the item, it show ID of item, but it dont show that is in my possession (as is shown for Bolt of embersilk cloth that Zoe in bags have 35 of those)

**What should happen:**
Upon on delivery quest (completing) I should receive ``Bulging Sack of Gold``
that can be opened and contain random number of gold from 10ish to 3 digit numbers (150g and more) according to comments on internet, my highest was 49g on retail..

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/58351925-6a814280-7e6a-11e9-9680-1297266b2378.png)

**Comment by TheSale** [comment]
http://prntscr.com/nt06n6

**Comment by Rushor** [comment]
gold loot added

![I](https://i.imgur.com/2OSSZ6U.jpg)
