### ISSUE TITLE
Missing Maniac Point after reaching level 60

### ISSUE THREAD

**Issue by kurabawa** [WoWManiaUK/Blackwing-Lair#2034]
**Links:**

from WoWHead or our Armory

**What is happening:**

I usually get Maniac Points (MP) for every 10th level. But when I hit level 60, i did not receive any. My inventory was quite full then so maybe it did not come in. I dont recall accidentally selling them too as they were epic grade. (This incident happened about 3 hours ago)

**What should happen:**

If im not wrong, I should receive the 15 MP for hitting level 60 automatically into my inventory

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/58351716-ecbd3700-7e69-11e9-86f5-a5e4771dcd2a.png)

Works, note that you don't get at 60 if you are a DK and if you have full inventory you're  out of luck.
Maybe you just missed it in your chat log :)

**Comment by TheSale** [comment]
@Kitzunu I also did not received on my war when I was around 50-60 might be coz full inventory
and now on my roque I hit 10 and because inventory was full I did not get mall stone and maniac points.
it should not be labeled as invalid or closed...
And you are familiar with this as you said `` if you have full inventory, you are out of luck``  
I am sure this should not be overlooked and act as it work as intended...

**Comment by kurabawa** [comment]
> ![image](https://user-images.githubusercontent.com/24550914/58351716-ecbd3700-7e69-11e9-86f5-a5e4771dcd2a.png)
> 
> Works, note that you don't get at 60 if you are a DK and if you have full inventory you're out of luck.
> Maybe you just missed it in your chat log :)

Erm, shouldn't it be sent through the mail or something if your inventory is full?

**Comment by Kitzunu** [comment]
There has never been such feature, not on WR and not on WM, so technically it works as intended.

However, I do think you could open a forum post making a suggestion for it to be implemented :)

**Comment by kurabawa** [comment]
> There has never been such feature, not on WR and not on WM, so technically it works as intended.
> 
> However, I do think you could open a forum post making a suggestion for it to be implemented :)

Gotcha, thank you :)
