### ISSUE TITLE
[NPC] Rau Cliffrunner -Missing -  Thousand Needles

### ISSUE THREAD

**Issue by Venom64bit** [WoWManiaUK/Blackwing-Lair#2038]
**Links:**
YT: https://www.youtube.com/watch?v=Y20r9qgtrVs
Quest: https://www.wowhead.com/quest=25872/the-brave-and-the-bold
QuestGiver: https://www.wowhead.com/npc=41421

**What is happening:**
The NPC designated by the quest isn't there.

**What should happen:**
He should be there to be freed.

-YT Video for more info-

**Comment by Rushor** [comment]
well he is there, but he get's killed by other creatures

**Comment by Rushor** [comment]
reduced his respawn time :)

**Comment by Echinaceax** [comment]
quest end Rau Cliffrunner isnt there tho 
https://www.wowhead.com/quest=25872/the-brave-and-the-bold#videos:id=2601

![where is he](https://user-images.githubusercontent.com/39439201/78414748-ea953e80-761d-11ea-94b1-25e9e85e993e.jpg)

**Comment by mfranca0009** [comment]
quest objective NPC missing: https://www.wowhead.com/npc=41460/captured-freewind-brave
Left Chain: https://www.wowhead.com/spell=84990/cosmetic-chains-base-left-hand
Right Chain: https://www.wowhead.com/spell=84991/cosmetic-chains-base-right-hand
Surrender: https://www.wowhead.com/spell=82426/surrender
Sit: https://www.wowhead.com/spell=91298/cosmetic-sit-lower-upper-body-high-low-priority-anim-kit
On Interact to complete quest: https://www.wowhead.com/spell=77584/the-brave-and-the-bold-captured-freewind-brave-on-interact

Will look into this further

**Comment by Echinaceax** [comment]
confirmed fixed in dev 

![fixed1](https://user-images.githubusercontent.com/39439201/87529801-cf5fb380-c68f-11ea-84a5-bd77c32ae58d.jpg)
