### ISSUE TITLE
[Dungeon] Azjol Nerub Dragonblight

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#2039]
**Links:**
https://www.wowhead.com/azjol-nerub
**What is happening:**
The problem is there are so many double or triple adds - http://i66.tinypic.com/2lsfzfb.jpg
**What should happen:**
They should be 1 by each type so you can do the (https://www.wowhead.com/achievement=1296/watch-him-die)

**Comment by Kitzunu** [comment]
These are spawned by scripts

**Comment by kDracku** [comment]
Yes i know the script but the problem is there 3 or 4 by those big ones , you can check it.

**Comment by Kitzunu** [comment]
Yea, it was more of a note that I can't fix it :P

**Comment by Rushor** [comment]
seems to be fixed

![I](https://i.imgur.com/oQSUuWi.jpg)

**Comment by kDracku** [comment]
Try to make a pull and see if there are multiple mobs ( big ones )

**Comment by Kitzunu** [comment]
I cannot reproduce this anymore
