### ISSUE TITLE
[Achievements] Respect Your Elders

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#2042]
**Links:**
https://www.wowhead.com/achievement=2038/respect-your-elders
**What is happening:**
Achievement its not working + boss does alot of dmg
**What should happen:**
After pulling and killing the boss here (https://www.youtube.com/watch?v=Y1XO6w2N6-Y) you should get the achievement.

**Comment by Echinaceax** [comment]
added to main report #4505
