### ISSUE TITLE
[Guild run Achievement] Ahn'kahet: The Old Kingdom Guild Dragonblight Shadowfang Keep + More

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#2043]
**Links:**
https://www.wowhead.com/achievement=5098/heroic-ahnkahet-the-old-kingdom-guild-run
**What is happening:**
We did the dungeon with 3 guldies and we did not get the Guild Run Achievement.
**What should happen:**
You should get the achievement after finishing the dungeon with 3 guldies

**Comment by Rushor** [comment]
uint32 Group::GetNeededMembersOfSameGuild(uint8 arenaType, Map const *map)
{
    // For arena (100% of member)
    if (arenaType && map->IsBattleArena())
        return arenaType;

    if (map->IsNonRaidDungeon())
        return 3;

    if (map->IsRaid())
    {
        if (map->GetEntry()->Expansion() == 0) // classic
            return 10;

        if (map->GetEntry()->Expansion() == 1) // TBC
            return 8;

        if (map->Is25ManRaid())
            return 20;

        return 8;
    }

    return 0;
}

it needs addition in several groups and kills

**Comment by Echinaceax** [comment]
any news on these ?

**Comment by Echinaceax** [comment]
added to main report #4505
