### ISSUE TITLE
(Quest) Hero's call: Eastern Plaguelands! 

### ISSUE THREAD

**Issue by simonverse** [WoWManiaUK/Blackwing-Lair#2045]
**Links:**h ttps://www.wowhead.com/quest=28578/heros-call-eastern-plaguelands

from WoWHead or our Armory

**What is happening:**
The npc that you are supposed to turn the quest in to isn't there. 

**What should happen:**
You should be able to report to Fiona but she doesn't spawn.

**Comment by sarahkay88** [comment]
#388
