### ISSUE TITLE
[Quest] Into Hostile terriorory -12325- Dragonblight

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#205]
Quest - https://www.wowhead.com/quest=12325/into-hostile-territory
NPC - https://www.wowhead.com/npc=27136
doesn't provide the necessary flight to complete the quest. no speech bubble to speak with him only to locations already secured.

**Comment by Dranah** [comment]
Is it possible to complete by walking there by foot?

**Comment by sarahkay88** [comment]
It is situated in a mob zone. yes you can walk there but your likely to pull a ton of mobs and spend 10/15 either killing them or if you have enough gold to fly then fly.

**Comment by Dranah** [comment]
Confirmed, but this is no priority. You just have to follow the road, apart from a few regular mobs that you can walk around there's nothing in your way.

**Comment by Dranah** [comment]
No change on this one. The quest is doable but you gotta walk by foot.

**Comment by Saintres** [comment]
This issue is allso on Redemtion.
