### ISSUE TITLE
VIP 6x on weekend is giving 8x instead of 12x

### ISSUE THREAD

**Issue by kurabawa** [WoWManiaUK/Blackwing-Lair#2050]
**Links:**

https://imgur.com/a/nBB7muI

from WoWHead or our Armory

**What is happening:**

6x VIP on weekend 2x is giving 8x xp

**What should happen:**

It should be giving 12x instead of 8x xp

![1](https://user-images.githubusercontent.com/50999600/58365600-43be1d00-7ef9-11e9-9d8c-88066af72408.png)
![2](https://user-images.githubusercontent.com/50999600/58365601-43be1d00-7ef9-11e9-8ac9-0ef5d20061b6.png)
![3](https://user-images.githubusercontent.com/50999600/58365602-43be1d00-7ef9-11e9-81b4-0a5fa70a8030.png)
![4](https://user-images.githubusercontent.com/50999600/58365603-43be1d00-7ef9-11e9-9715-e45967072524.png)

**Comment by Kitzunu** [comment]
calculats correctly now.

i.e: if you hand in quest "The Siege" with VIP and Double XP weekend you will get 241200 XP

241200 / 20100 = 12

The 20100 comes from the Blizzlike default x1 multiplier. on the NPC where you hand in it will show Blizzlike value x2 since the default server XP is x2
