### ISSUE TITLE
[Talent/Hunter] Lock and Load

### ISSUE THREAD

**Issue by gitkulu** [WoWManiaUK/Blackwing-Lair#2051]
**Links:**
Lock and Load talent Spell ID: 56343 (not on wowhead)
Lock and Load buff Spell ID: 56453 (not on wowhead)

**What is happening:**
When the Survival talent "Lock and Load" procs, the buff stacks get consumed (wasted) by ANY hunter shot.

**What should happen:**
The "Lock and Load" buff stacks should ONLY be consumed by Explosive Shot.

**Comment by sarahkay88** [comment]
http://cata-shoot.tauri.hu/?spell=56343
