### ISSUE TITLE
[Spell] Druid Rake bleed damage - tooltip bug 

### ISSUE THREAD

**Issue by kurabawa** [WoWManiaUK/Blackwing-Lair#2052]
**Links:**
https://www.wowhead.com/spell=1822/rake#modified-by

from WoWHead or our Armory

**What is happening:**
For 235 attack power, it is doing 6 bleed damage every 3 seconds

![1](https://user-images.githubusercontent.com/50999600/58384118-a6eea300-8010-11e9-9aa2-c19c2ede103f.png)
![2](https://user-images.githubusercontent.com/50999600/58384119-a9e99380-8010-11e9-9fdc-1f3d0baa09ff.png)

**What should happen:**
It should do about 35~36 bleed damage every 3 seconds.

(235 * 0.77085) / 5 = 35~36 bleed damage per 3 seconds.

**Comment by giles1508** [comment]
do you have a combat log to show the actual damage it did ?  so we can determine if this is a tooltip bug or damage bug

**Comment by giles1508** [comment]
currently testing  this in my druid,  the damage output for me seems about right,   but my tooltip shows 56 dmg,  at level 85,   so this seems like its just a tooltip bug on the debuff,  the damage aspect seems ok
