### ISSUE TITLE
Worgen-Faction recognition Issue (TBC-Woltk Srongholds,Quests and faction based items)

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#2053]
**Links:**
Stronghold WotLK -https://www.wowhead.com/faction=1050/valiance-expedition
Stronghold TBC -https://www.wowhead.com/faction=946/honor-hold
Quest items such as -
https://www.wowhead.com/item=36854/emblazoned-battle-horn
https://www.wowhead.com/item=31120/meeting-note

from WoWHead or our Armory

**What is happening:**
Due to worgen start area being incompletable once a player leaves area (via mall stone ect) the can quest quite freely up to lvl 58 but then faction quest such the dark portal opening quests or any faction stronghold quests are unavailable also the same with items in these areas the give the response "you are not the required faction to use this item" when you try to activate them.

**What should happen:**
You should be able to access all faction stronghold and quest drop items regarding the alliance in TBC and Wotlk

**Comment by sarahkay88** [comment]
I think there was a comment made in discord saying they had the same issue with gobos too

**Comment by Dranah** [comment]
Well, you aren't belonging to either faction until you finish your quest chain. You need your quest chain completed. This is not a bug, but a direct consequence of not having completed the necessary quests.

I don't know if there's point doing an artificial work around for this, fixing the quest chain would fix this problem as well.

**Comment by Dranah** [comment]
This is a suggestion, not a bug. We'll seek to fix the quest chain.
