### ISSUE TITLE
[NPC] Winterspring-Screecher - Winterspring

### ISSUE THREAD

**Issue by Venom64bit** [WoWManiaUK/Blackwing-Lair#2054]
**Links:**
Quest: https://www.wowhead.com/quest=28745/screechy-keen
QuestGiver: https://www.wowhead.com/npc=49537
NPCs: https://www.wowhead.com/npc=7456

**What is happening:**

The NPCs is not attackable.

**What should happen:**

The NPCs should be attackable.

**Comment by Venom64bit** [comment]
If you leave the quest the NPCs turn into Questgivers.

**Comment by Rushor** [comment]
attackable now
