### ISSUE TITLE
[Quest] Breaking the chain - id 25167 -  Durotar

### ISSUE THREAD

**Issue by Deanisthos** [WoWManiaUK/Blackwing-Lair#2055]
Links:
Quest: https://www.wowhead.com/quest=25167/breaking-the-chain
QuestGiver: https://www.wowhead.com/npc=3188/master-gadrin
NPCs:
 https://www.wowhead.com/npc=39251/northwatch-supply-crate
 https://www.wowhead.com/npc=39245/northwatch-lug          

**What is happening:**
soldiers with creates stands still.

**What should happen:**
they should walk with crates following a standard path
https://www.youtube.com/watch?v=HIL2bBxsxSk

**Comment by Rushor** [comment]
![I](https://i.imgur.com/MpJQkQC.jpg)

fixed
