### ISSUE TITLE
{spell] death grip

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2058]
**Links:**

https://cata-twinhead.twinstar.cz/?spell=49576    -   link to Death grip spell

**What is happening:**

Death grip isnt fully gripping caster mobs, i havent tested this outside of the DK starting zone yet,   but every caster mob I have tried to grip starts casting thier first spell 

video below
https://youtu.be/bpKerIN8bJY

**What should happen:**

the mob should be gripped all the way to the DK so you can start to attack the mob

**Comment by Keader** [comment]
Fixed.
