### ISSUE TITLE
Runeforge missing in Archerus Ebon hold [After completion of Dk quest chain]

### ISSUE THREAD

**Issue by Frostmanx** [WoWManiaUK/Blackwing-Lair#2062]
**What is happening:** Runeforge is missing where it should be after completion of the dk quest chain and returning back to archerus 
![WoWScrnShot_052719_144247](https://user-images.githubusercontent.com/50195620/58410117-258a2580-808f-11e9-8727-0831b472b62f.jpg)

**What should happen:** The runeforge should be present after completion of the quest chain in Ebon hold 

![565666](https://user-images.githubusercontent.com/50195620/58410222-59654b00-808f-11e9-9640-ac1fc6b8ae58.jpg)

**Comment by wow-mania** [comment]
The runeforges are there
![image](https://user-images.githubusercontent.com/12248683/58425418-aa763e80-8091-11e9-9162-f6acda78c300.png)

**Comment by Frostmanx** [comment]
@wow-mania not after you complete the full quest chain!
