### ISSUE TITLE
[Spell] Ghost wolf

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2063]
**Links:**
http://prntscr.com/ntvgsj
http://prntscr.com/ntw201

from WoWHead or our Armory
https://www.wowhead.com/spell=2645/ghost-wolf#changelog

**What is happening:**
As it is labeled shaman cant be dropped below normal movement speed which means it can be slowed and dazed...

**What should happen:**
in ghost wolf it should be immune to any sort of slow (pvp and pve) and shapeshifting into ghost wolf should remove any movement speed debuff that was in normal form.

with improved ghost wolf instant cast was mandatory for raid progress on Hagara the Strombinder in Dragon soul raid.
As main healer in that progress raid, I had benefit that I did not had to walk with group, in frost  phase when we have to stand outside the circle and run away from crystal spikes that 1 shoot anyone who touch them while avoiding ice block drops. In circle you get 50% movement speed reduction and huge damage received each second you stand inside. As shaman I could stand in place and spam healing, and when ice spikes come near, I would instant cast ghost wolf, enter frost circle and run around ice spikes in 1 second or 2 seconds  at the most and back to steady healing.

also I am not sure should shapeshifting remove roots, like druid, but it does not.

**Comment by Keader** [comment]
Normal speed = 100% (1)
With Ghost Wolf your speed go to 130% (1.3).

Testing with a slow (-35%)

Normal Form new speed: 0.65
with ghost wolf new speed: 1

Spell is working fine.
You speed go to minimum 100%, that is speed that you run without ghost wolf
