### ISSUE TITLE
 [Alchemy] Master specializations

### ISSUE THREAD

**Issue by dagget1337** [WoWManiaUK/Blackwing-Lair#2064]
**Links:**

from WoWHead or our Armory

**What is happening:**
Almost all Professions with my lvl85 Paladin Trixie are somehow gone, like their icons in the Professionsbook just disappeared, only Alchemy (525) and Master of Elexirs are shown and usable (although master of elexirs and flasks seem to be bugged since i only get 1 potion every time, and while i´m at it the Raid cauldron and the infinite flask which both give a random buff are bugged too, Ps. The cauldron just disappears after being used and doesnt even spawn at all), the rest like cooking (525), Herbalism (525), Fishing (?) and Archeology (?) are gone and cant be accessed by any means (/cast or macros didnt work, only for alchemy it worked). Ive had some of the icons on my toolbars which can be miraculously used ever since the bug started. 

_What i tried so far:_
- Disabling all addons 
- Deleting the Folders Interface, Cache and WTF
- Reinstalling my WoW Client
- Logging in on another Computer (my cousins computer)
- Creating macros to open these Professions

_What Swatter pops up:_
Date: 2019-05-27 16:34:13
ID: 1
Error occured in: Global
Count: 1
Message: ..\FrameXML\SpellBookFrame.lua line 1270:
   Found 3 skills for Alchemie the max is 2: (Alchemie) (Meister der Elixiere) (Meister der Tränke)
Debug:
   (tail call): ?
   [C]: ?
   [C]: assert()
   ..\FrameXML\SpellBookFrame.lua:1270: FormatProfession()
   ..\FrameXML\SpellBookFrame.lua:1292: SpellBook_UpdateProfTab()
   ..\FrameXML\SpellBookFrame.lua:136:
      ..\FrameXML\SpellBookFrame.lua:119

**What should happen:**
The Professions "missing" icons need to be fixed, it seems only to affect my Paladin Trixie why i´m adding a screenshot from my Deathknight Neptune to show that these professions do work on her.

![WoWScrnShot_052719_034618](https://user-images.githubusercontent.com/51065101/58426897-32fadc00-809e-11e9-802b-364f0815275f.jpg)

![WoWScrnShot_052719_034431](https://user-images.githubusercontent.com/51065101/58426861-165ea400-809e-11e9-9dc2-e7add719e57a.jpg)

**Comment by wow-mania** [comment]
We do not work on addons. This is not server-side

**Comment by dagget1337** [comment]
"Found 3 skills for Alchemie the max is 2: (Alchemie) (Meister der Elixiere) (Meister der Tränke)"
the cause is this, i did 2 quest for the alchemy potions. thanks to Tazdeengo we know the problem but how to fix that?

**Comment by Kitzunu** [comment]
I believe this is a client-side issue @wow-mania

**Comment by Kitzunu** [comment]
An actual closer look to this it seems like it is trying to recognize 3 skills for Alchemy when the max is 2 making the error occurred.

Alchemy, master of the potions and master of the elixirs

LUA for the lines given above:
```lua
119 function SpellBookFrame_OnEvent(self, event, ...)
136 		SpellBook_UpdateProfTab();
1270			assert(false, errorStr)
1292	FormatProfession(PrimaryProfession1, prof1);
```

However, if I know enough, shouldn't you only be able to be Master of 1 thing in Alchemy?>
Since here it is trying to read Master of Elixir and Master of Potion

**Comment by giles1508** [comment]
yes how this works is ,   when you take 1 of the 3 quests,  it removes the availablity to take the other 2

tested this over the last 2 days with trixie and today it dawned on me that he had more than 1 of the 3 and thats why it was bugging all his professions out

i got trixie to go to shattrath to unlearn the masteries so he can just learn the 1 single mastery that he wants

and this completeely fixed the UI bug

**Comment by Kitzunu** [comment]
@giles1508 What are the names of the 3 quests?

**Comment by giles1508** [comment]
https://cata-twinhead.twinstar.cz/?npc=3347    this is the quest giver

**Comment by giles1508** [comment]
and the 3 quests are there on the page that loads up

**Comment by Rushor** [comment]
is this still an issue?

**Comment by Echinaceax** [comment]
> is this still an issue?

I will take a look once in ingame @Rushor 
i'll let you know

**Comment by Rushor** [comment]
thank you, and pls some easy  explain that tells me what to fix here :D

**Comment by Echinaceax** [comment]
OK i will try my best to explain @Rushor 

As the Alchemist you get 3 specialized quests, you are only meant to be able to do one or the 3 

i chose potions master

![alch1](https://user-images.githubusercontent.com/39439201/67608077-07803880-f787-11e9-8c8a-839aef449fe2.jpg)

did the quest 

![alch2](https://user-images.githubusercontent.com/39439201/67608112-27176100-f787-11e9-90a9-c0acfbab421b.jpg)

Handed back in 

![alch3a](https://user-images.githubusercontent.com/39439201/67608137-3b5b5e00-f787-11e9-90ed-cbe4f5e05040.jpg)

got my potions master 

![alch5](https://user-images.githubusercontent.com/39439201/67608148-4b733d80-f787-11e9-99a7-e2fe6d125e6b.jpg)

i shouldnt be able to do all 3, once you are a potions master the choice should disappear 

![Alch4](https://user-images.githubusercontent.com/39439201/67608204-837a8080-f787-11e9-9740-29d8817905de.jpg)

**Comment by Rushor** [comment]
okay exlusive groups added

![I](https://i.imgur.com/qaNRYCL.jpg)
![I](https://i.imgur.com/qLP0UDn.jpg)

**Comment by Echinaceax** [comment]
still issues cant hand it back in 
i abandoned quest and cleared cache then retook it 

![cant hand back](https://user-images.githubusercontent.com/39439201/67677877-76c37b80-f985-11e9-9db6-42809a19b0a8.jpg)

**Comment by Rushor** [comment]
Can you try with a new toon aswell? That specific issue usually happens randomly to several quest with required items

**Comment by Echinaceax** [comment]
ok, in dev ?
coz this is my alch on live :)

**Comment by Echinaceax** [comment]
@Rushor correct on new toon works fine 

![alch complete](https://user-images.githubusercontent.com/39439201/67679603-b7bd8f00-f989-11e9-8155-daccfd40a9b3.jpg)

Note what i did notice was on first alchemy test toon when i unlearnt the profession it didnt remove my Achievments for that profession. not sure if that could be related.

but on a different test toon worked fine
