### ISSUE TITLE
[Fishing Dailies] - Darnassus

### ISSUE THREAD

**Issue by Sessh097** [WoWManiaUK/Blackwing-Lair#2066]
**Links:**

First Quest: https://www.wowhead.com/quest=29359/an-old-favorite
Second Quest: https://www.wowhead.com/quest=29325/a-slippery-snack

**What is happening:**

First Quest: Fishing for hours without a single Kaldorei Herring 
https://www.wowhead.com/item=69987/kaldorei-herring
Second Quest: Can't pick up Baby Octopus
https://www.wowhead.com/item=69915/baby-octopus

**What should happen:**

First Quest: Catch 8 Kaldorei Herring by fishing in Rut'theran Village
Second Quest: Gather 6 Baby Octopi from the shallow water near Rut'theran Village.

edited by Echi (third quest)

**Comment by Echinaceax** [comment]
Please report single quests as some of these issues are already fixed or being dealt with 

this one is already reported and fixed this week  https://www.wowhead.com/quest=29344/fish-fer-squrky
here 
https://github.com/WoWManiaUK/Blackwing-Lair/issues/1538

**Comment by focarol** [comment]
I heard already this might be fixed from Zinius.

i really try hard to fish that stuff
i tried in the water of Darnassus
i tried the water around Ruth'eran

i have fishing skill over 500, when i use a helper

i don't get any herring

where i have to fish? because rushor said: "area 141"

**Comment by Echinaceax** [comment]
GMs dont fix @focarol coders do, GMs complete broken quests only not fix them.

**Comment by focarol** [comment]
copy that
zinius just mentioned it isnt gamebreaking - i understand that
but for the achievment i would like to complete this quest one day
:-)
...i havent tried the lake at dalaran, maybe there i get the fish
but it is supposed to be Ruth'eran

**Comment by Echinaceax** [comment]
Yes "not gamebreaking" is the term they use :)

But from a tester/coder side of things Rushor said he added 50% drop/fish rate 
so if you say its not fixed we will reopen this issue

**Comment by Echinaceax** [comment]
> **Solution**

> You don't get the Kaldorei Herring in Rut'theran (as mentioned in the Quest-Text)
> You don't get the Kaldorei Herring in Darnassus.
> 
> **Solution**
> The Lake near Dolanaar --> There you can catch the Kaldorei Herring.
> 
> Have a nice Day

Copied from new solution report by @focarol
