### ISSUE TITLE
[Quest] Kaw the Mammoth Destroyer - ID 11879 - Borean Tundra

### ISSUE THREAD

**Issue by Sessh097** [WoWManiaUK/Blackwing-Lair#2067]
**Links:**

https://www.wowhead.com/quest=11879/kaw-the-mammoth-destroyer

**What is happening:**

Can't even attack the target "Kaw the Mammoth Destroyer" or his Mammoth "Moria"
https://gyazo.com/b6c932d66d9807d5f470e40188f4e972

**What should happen:**

Kill Kaw the Mammoth Destroyer and recover Kaw's War Halberd. Deliver Kaw's War Halberd to Arch Druid Lathorius at the D.E.H.T.A. Encampment in the Borean Tundra.

**Comment by zippoking** [comment]
I still can´t attack the npc. Quest is not fixed.

![Kaw the Mammoth Destroyer - how it is](https://user-images.githubusercontent.com/18005338/59428688-356b6e80-8dde-11e9-9006-67b5c2ff4215.png)

**Comment by Kitzunu** [comment]
```sql
SELECT * FROM smart_scripts WHERE entryorguid = 25802;
SELECT * FROM smart_scripts WHERE entryorguid = 2580200;
```

**Comment by Kitzunu** [comment]
The weird part is that this exact script works on wotlk, any thoughts @Rushor ?

**Comment by Rushor** [comment]
okay so how it should work:

You need to attack Moira. Then use spell 
Mammoth Trample http://cata.cavernoftime.com/spell=46317
on her and the event with Kaw the Mammoth Destroyer will tigger. Kill Moira > Kaw the Mammoth Destroyer will become attackable > Kill Kaw the Mammoth Destroyer > Questobject will spawn.

**Comment by Rushor** [comment]
In order to use Mammoth Trample http://cata.cavernoftime.com/spell=46317 you need to take control of one of the Wooly Mammoth Bulls.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/n2k98Js.jpg)
![I](https://i.imgur.com/zbOxwUr.jpg)
![I](https://i.imgur.com/q8G9ffC.jpg)
