### ISSUE TITLE
[Spell] Serpent Spread

### ISSUE THREAD

**Issue by Sessh097** [WoWManiaUK/Blackwing-Lair#2068]
**Links:**

http://cata-shoot.tauri.hu/?spell=87934

**What is happening:**

Even Hitting enemies with multiple Multi-shots don't afflict the Serpent Spread ( DOT )

**What should happen:**

Targets hit by your Multi-Shot are also afflicted by your Serpent Sting equal to 6/9 sec of its total duration.

**Comment by giles1508** [comment]
just testing this now and multi shot is defo doing more damage when your main target has serpent sting
just not too sure if it is equal to 6 / 9 seconds

**Comment by giles1508** [comment]
nah there is something wrong here,  after more testing im not convinced it is doing more damage,  im trying to find out exactly how this should work on retail

**Comment by Sessh097** [comment]
I mean it should spread serpent sting when you use multi shot for aoe damage, but it doesn't at all and for 10% more dmg affected with it it's working
