### ISSUE TITLE
Volatile fire not dropping from unbound emberfiend

### ISSUE THREAD

**Issue by Shammyr** [WoWManiaUK/Blackwing-Lair#2069]
**Links:**
https://www.wowhead.com/item=52325/volatile-fire
https://www.wowhead.com/npc=48016/unbound-emberfiend
from WoWHead or our Armory

**What is happening:**
I've killed around 50 of these mobs so far without seeing 1 volatile fire

**What should happen:**
the item should drop, it's important for crafting professions

**Comment by Kitzunu** [comment]
Did you intend to close this or was it a mistake?
