### ISSUE TITLE
[Quest] The Ritual Bond - ID 13569 - Darkshore

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2071]
**Links:**

Quest: https://www.wowhead.com/quest=13569/the-ritual-bond
NPC: https://www.wowhead.com/npc=33048
Object: https://www.wowhead.com/object=194771/grovekeepers-incense

**What is happening:**
![The Ritual Bond - How it is](https://user-images.githubusercontent.com/18005338/58434641-0b673c00-80bd-11e9-96c3-21fc0407fdcb.PNG)

There is no text option to proceed.

**What should happen:**

This is how it should look like:
![The Ritual Bond - How it should be](https://user-images.githubusercontent.com/18005338/58434642-0b673c00-80bd-11e9-8d4b-0648ce660fe4.PNG)

**Comment by Rushor** [comment]
okay fixed.

you can se the spirits now if you are on that quest and once doing their quest, the quest "the ritaul bod" will be completed.

![I](https://i.imgur.com/pUsn05j.jpg)
![I](https://i.imgur.com/FWiADT2.jpg)
![I](https://i.imgur.com/tHRTwHA.jpg)
![I](https://i.imgur.com/sAGy0BK.jpg)
