### ISSUE TITLE
[NPC] Julak-Doom

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2072]
https://www.wowhead.com/npc=50089/julak-doom

This is some kind of world boss that currently doesnt attack or do anything.

He is free loot to farm for epics.
Needs urgent fixing @Kitzunu 

How it should work: https://www.youtube.com/watch?v=RVG-G0UFUcs

PS: if theres no time or energy to fix him properly, just make him unattackable for now.

**Comment by giles1508** [comment]
just to add,  he respawns almost instantly not sure if he drops a second time,  as there are alliance here and ive made enemies reporting it :+1:

**Comment by TheSale** [comment]
http://prntscr.com/nu2i3y

well I tried to kill it on my druid, it took 31min with help of others, and he did not drop anything this time...

but I can confirm he respawned immediately, so tweak spawning time and all is good

**Comment by Kitzunu** [comment]
I added unit_flags 256 & 512 aka won't be attackable.

@Rushor Whenever you add SAI to the guy, don't forget to remove those flags :)

**Comment by giles1508** [comment]
the boss dropped 3 items apon killing it,  intelect dagger, plate shoulders and plate chest

**Comment by Echinaceax** [comment]
@giles1508 any IDs for these ?

**Comment by giles1508** [comment]
yup !   dagger  =  69844     chest =   67143      shoulders =   67144

**Comment by Rushor** [comment]
alright added more damage and a script for him :) will add that to other open world bosses too

**Comment by TheSale** [comment]
@Rushor http://prntscr.com/nujv1q bit more damage :D

**Comment by Dranah** [comment]
I see Zoe got what he deserved? xD

**Comment by TheSale** [comment]
well I went to test it rofl, it should be fixed, not broken AF :D

**Comment by Dranah** [comment]
I don't see the issue tbh, that is a special ability that only hits frontally. Only the tank should be hit by it, and seeing it does around 110k on a shaman, an appropriately geared tank would only receive a 60-70k blow that they can survive without problems.
It's a world boss, similar level as to BWL or BoT bosses are (drops same lvl gear too) and the gear and group it requires to do is roughly the same as well. It IS supposed to oneshot a non-tank.
Unless the ability is being spammed, or hits everywhere (not just frontally), this is not broken.
