### ISSUE TITLE
[Alchemy]Flask of Enhancement

### ISSUE THREAD

**Issue by Chicozoba** [WoWManiaUK/Blackwing-Lair#2079]
**Links:**

Flask of Enhancement : https://cata-twinhead.twinstar.cz/?item=58149

**What is happening:**

Nothing happens when you drink the flask.

**What should happen:**

A buff should be added (either agility, strength or intellect, depending on your class and specialization).

**Comment by Echinaceax** [comment]
can we get this fix please :)

**Comment by TheSale** [comment]
+1
