### ISSUE TITLE
[Rogue + Druid] Combo Points

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2080]
**Links:**

Cannot find a link with a spell ID 

**What is happening:**

Combo points are not staying on the target after death,   they are supposed to stay on your target after death so you can either use them to recuperate or redirect to another mob etc,   but currently they are vanishing upon dropping any form of combat  be that via the mob getting killed or losing ago,   

This goes for Druids also combo points in cat form should stay on target after death etc

quick video here of them dropping off 
https://youtu.be/3x2sWVWiziI

**What should happen:

below is a quick video i found at the start  of cata done by a druid,  in the video the combo points last up to 10 seconds,   but im almost sure that they changed that by 4.3.4 as i remember in pvp being able to see the combo points up until i changed target or the target released

https://www.youtube.com/watch?v=Fpd_5UXa3Oo

**Comment by Keader** [comment]
Fixed.
Combo points will stay 10 sec after dead.
