### ISSUE TITLE
[Quest] The Eye of all Storms - ID 13588 - Darkshore

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2082]
**Links:**
Quest: https://www.wowhead.com/quest=13588/the-eye-of-all-storms
Dragon: https://www.wowhead.com/npc=34243/thessera
Youtube: https://www.youtube.com/watch?v=R8xveRFTwU8

**What is happening:**
There is no Dragon Thessera to ride.
![The Eye of all Storms - how it is](https://user-images.githubusercontent.com/18005338/58437450-53d92680-80ca-11e9-8a9b-f8dcf37db8d2.PNG)

**What should happen:**

There should be a couple of other NPC´s around Malfurion. One of them should be the Dragon Thessera. You could ride the dragon and finish the quest.
![The Eye of all Storms - how it should be](https://user-images.githubusercontent.com/18005338/58437451-5471bd00-80ca-11e9-8165-9e9b19079a41.PNG)

**Comment by Rushor** [comment]
done!

![I](https://i.imgur.com/AJpCr1Z.jpg)

all path, vehicle handling and creaturespawns added. you can kill the portal and the drakes now.
