### ISSUE TITLE
Flight form not learning the proper Riding Skills

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Blackwing-Lair#2083]
>I have experienced same issues as others, I had unlearned random skills and had to train again, and also my riding skills 
http://prntscr.com/nthsob
this was first time I had to re learn skills, and in chat I had displayed some riding skills that I had learned again...
at that moment I did not know what is going on, later echi explained to me that it was actually a bug.

>now janitor told me that everything is okay and not I have for the third time to re learn everything
in chat you can see some of abilities that I have learned, and flying I started to learn with hope that it night be just first one that must be learned or second or third... but I stop learning when I had to waste 3 digit gold
http://prntscr.com/nu3f4i

>_Originally posted by @TheSale in https://github.com/WoWManiaUK/Blackwing-Lair/issues/2011#issuecomment-496297301_

The first rank of Flight Form requires Riding (150). Riding (150) is also required to learn Riding (225) for a normal flying mount. Upon learning Flight Form, you will receive Riding (225) free of cost.
Flight Form has four specific advantages over a Flying Mount.
It is free, while regular training and a mount costs 250g.  [Swift Flight Form] is attained by learning it from a Druid trainer (20gg), though artisan riding skill (5000g) is still required.

aka you should learn all flying up to Artisian Riding

**Comment by TheSale** [comment]
I was playing druid few hours testing some dungeons since I am bored AF
and reporting issues here.
I only relog on roque for few min to take couple screenshots and when I come back to druid my flyings are unlearned again.....

here you can see shaded (coz I am in combat) but I had 2 flying shapeshifts
https://prnt.sc/nu6x0r

and here I only have 1 that I cant use, and I have to learn other from trainer
and riding skills unelarned again........
http://prntscr.com/nu7eye

**Comment by TheSale** [comment]
small update
here I have all riding skills learned up to 70+
http://prntscr.com/nxh7dm
and after relog I lose all and have to learn again
http://prntscr.com/nxh8qy

I have risked and learned epic flying 
http://prntscr.com/nxhfd8

that helped and I dont have to relearn everything when I relog, save gold, time and bother.
however my lvl 60 flight form is unlearned again... 
http://prntscr.com/nxhh3i

I can help you futher with this but it should be tested so players who dont have gold to learn epic flying should not experience irritating reset every relog...

**Comment by wow-mania** [comment]
This issue is totally messed up.
You are either not learning the right skill or the skill is not being saved.
Which one is it?

**Comment by Kitzunu** [comment]
From my own tests, you do get the skills, but they don't save.

Correct me if I'm wrong

**Comment by Echinaceax** [comment]
> From my own tests, you do get the skills, but they don't save.
> 
> Correct me if I'm wrong

correct

**Comment by Echinaceax** [comment]
@wow-mania - tested and confirmed partly fixed. all spells remain now, just the druid flight form 150% disappeared

**Comment by Echinaceax** [comment]
regression fix with me added here #2906
