### ISSUE TITLE
[Boss] Ozruk - Stonecore heroic

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2085]
https://www.wowhead.com/npc=42188/ozruk

This guy works fine on normal difficulty however he has some issues on heroic.

1) Paralyze/Elementium Spike Shield interaction
He casts Paralyze (92426) right before shattering, which stuns all party members for 8 seconds.
**How it should work:** This effect should be removed by any damage taken, including the debuff Elementium Spike Shield (ID 92660) that the boss applies to those who melee attack him
**How it works atm:** the ticking damage from Elementium Spike Shield debuff is not dispelling Paralyze, leading to melee DPS getting stuck in shatter.

NOTE: other sources of damage (shatter itself and DoTs you reflect on yourself as a caster) are working properly to dispel the effect.

2) Rupture spikes don't hit in melee
**How it should work:** On heroic, the tank normally needs to dodge the ground slam to avoid getting blown up, because of the Rupture coming with it.
**How it works atm**: the Rupture spikes only seem to hit at range, they begin behind the line of melee, so staying in front of boss is perfectly safe as long as you're close to him.

**Comment by Keader** [comment]
Test now.

**Comment by Dranah** [comment]
The debuff now properly removes paralyze.
The rupture spikes also hit slightly more inside.

**Comment by Denrunmt** [comment]
The bug with Paralyze is happening again. When Ozruk casts the spell "Paralyze", he stuns me and doesn't let me hit him after that so I can get the debuff which allows me to move and get out of his aoe spell "Shatter". Please investigate!

**Comment by Denrunmt** [comment]
![Screenshot7](https://user-images.githubusercontent.com/52254524/62341480-42f2ca00-b4ec-11e9-8f29-d30f4a4d947a.jpg)

I get the stun debuff from his paralyze and he doesn't let me attack him until the debuff expires. While this debuff is on tho... I can't move while he is casting his Shatter spell. So I'm insta dead. This happens with my rogue only.

**Comment by Dranah** [comment]
You are supposed to get the debuff BEFORE you get paralyzed. Is it not applying as intended?

**Comment by Denrunmt** [comment]
@Dranah The thing is I don't get that bleeding debuff... I can even record a video if you want me to.

**Comment by Dranah** [comment]
Feel free, any information to reproduce can help.
Currently cannot reproduce the issue
![WoWScrnShot_080419_014401](https://user-images.githubusercontent.com/31132743/62417787-6d15ca80-b659-11e9-8092-b181f42e108e.jpg)

**Comment by Cenasty** [comment]
Happens sometimes to rogue class (maybe melee Druid in shapeshift form as cat or bear) to not get the Bleed effect cancelling the Paralyze resulting in the stun still working and taking the Shatter spell (so killing the person).

It can't possible for a rogue with 2 daggers  (hitting at 1.8 and 1.4 without buffs) to not get the bleed effect to cancel Paralyze and go in a safe spot.

Bleed effect chance to get might be lowered on fast speed weapon or I don't know what but we get killed 1 shatter of two.

**Comment by questbugreporter** [comment]
I died to the boss's second shatter because I was paralyzed while playing a rogue. Before the first shatter I had ONE stack of the bleed effect while I normally get 4+ on my HOLY paladin from hitting the boss between casts.
When the second paralyze dropped on me I had 0 stacks which leads me to believe that dodge works against it, as I've only seen others rogue and one feral druid stay paralyzed.
