### ISSUE TITLE
[NPC][Quest] Hold the line - ID 14347 - Gilneas

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2086]
**Links:**
Quest: https://www.wowhead.com/quest=14347/hold-the-line
NPC: https://www.wowhead.com/npc=34511/forsaken-invader

**What is happening:**
I only found 7/10 forsaken Invaders. There are no further mobs in this area. Its just empty.
Even after 90 Minutes they did not respawn. I hope i don´t have to wait for a server restart for them to respawn.

![Hold the line - how it is](https://user-images.githubusercontent.com/18005338/58439817-90ab1a80-80d6-11e9-9243-16ca8df63fe8.PNG)

![Hold the line - how it is 2](https://user-images.githubusercontent.com/18005338/58439911-234bb980-80d7-11e9-81c7-4ae1c40a80e9.PNG)

**What should happen:**

Compared to official server, there are a couple of those forsaken invaders right at the questgiver.
![Hold the line - how it should be](https://user-images.githubusercontent.com/18005338/58439942-49715980-80d7-11e9-82d7-fc31ad610ca4.PNG)

**Comment by Kitzunu** [comment]
There are 24 spawned, so it should be doable.
Though, many spawns are missing

**Comment by Kitzunu** [comment]
added 56 spawns and reduced respawn time to 500 seconds

**Comment by zippoking** [comment]
Quest is bugged again. This time not a single mob spawned. I waited 45 minutes.

It might be related to a phasing issue #2460 


![Hold the line - how it is 3](https://user-images.githubusercontent.com/18005338/59848318-20a25400-9365-11e9-8057-a0cc6428a137.png)
![Hold the line - how it is 4](https://user-images.githubusercontent.com/18005338/59848320-20a25400-9365-11e9-9c3f-eb430327a1ae.png)
![Hold the line - how it is 5](https://user-images.githubusercontent.com/18005338/59848321-213aea80-9365-11e9-89d4-18825f9d62fc.png)

**Comment by zippoking** [comment]
Well, after relog all mobs are available. Can stay closed.

**Comment by zippoking** [comment]
Well, after relog, the mobs are available, but invalid target. 
Quest cannot be completed.

![Hold the line - how it is 6](https://user-images.githubusercontent.com/18005338/59848809-5dbb1600-9366-11e9-8621-5a21561465bf.png)

**Comment by Rushor** [comment]
phasing is needed here

**Comment by Rushor** [comment]
i added phasing to them in mask 182, so you should be able to see them

**Comment by Rushor** [comment]
reopen this since the issue is still present
