### ISSUE TITLE
[Spell] Druid Stampede talent

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2087]
**Links:**
http://prntscr.com/nu6n0y

from WoWHead or our Armory
http://cata-shoot.tauri.hu/?spell=78893

**What is happening:**
no haste buff with bear feral cahrge
no free cast of Ravage, or not is available to use it without stealth or position requirements

**What should happen:**
Increases your melee haste by 30% after you use Feral Charge (Bear) for 8 sec, and your next Ravage will temporarily not require stealth or have a positioning requirement for 10 sec after you use Feral Charge (Cat), and cost 100% less energy.

**Comment by giles1508** [comment]
can confirm this isnt working,  cannot believe i didnt notice this.... playing a feral myself ...jesus

**Comment by Keader** [comment]
Duplicated and fixed today xD

**Comment by Kitzunu** [comment]
Duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/1709

**Comment by TheSale** [comment]
dear god it feels good now that it works.... damn so nice :)
4 STREBGHT
$ STAMINA
AHHHHHHH
