### ISSUE TITLE
[Spell] Faerie Fire

### ISSUE THREAD

**Issue by HarryRogue** [WoWManiaUK/Blackwing-Lair#2090]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/npc=3268/razormane-thornweaver
NPC ID = 3268
SPELL ID = 6950

**What is happening:**

Razormane Thornweaver from Nothern Barrens (ID = ?) are using Faerie Fire. 
Tooltips says that you can't be stealth or vanished under this spell but you actually can.

**What should happen:**
Stealth and vanish abilities should not be usable.

**Comment by Kitzunu** [comment]
https://www.wowhead.com/spell=6950/faerie-fire
