### ISSUE TITLE
[Quest] Lunk's Adventure: Spider Rider - ID 27959 -  (issue 1) Searing Gorge

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2093]
**Links:**
Quest: https://www.wowhead.com/quest=27959/lunks-adventure-spider-rider
Lunk: https://www.wowhead.com/npc=47280/lunk
Spider Rider Credit: https://www.wowhead.com/npc=47279/spider-rider-credit
Glassweb Spider: https://www.wowhead.com/npc=5856/glassweb-spider

According to wowhead it is NOT this Lunk https://www.wowhead.com/npc=47269/lunk, it is the one posted above.

**What is happening:**
After killing Glassweb Spiders Lunk does not spawn and you can´t access the quest.
![Rider Spieder - How it is](https://user-images.githubusercontent.com/18005338/58493984-660f9f00-8174-11e9-8676-9ee38b14a174.PNG)

**What should happen:**
After killing Glassweb Spider Lunk should spawn and offer the given quest.
![Rider Spider - How it should be](https://user-images.githubusercontent.com/18005338/58493983-660f9f00-8174-11e9-9d50-8d742f245494.PNG)

**Comment by Rushor** [comment]
Lunk will spawn now. If the quest itself is not working please open a new issue for that. ty

**Comment by zippoking** [comment]
Well, good thing is, he definitely spawns now, but way too often :-D.

He can spawn himself. So i came into this area, and there were already 3 spawns of Lunk fighting with a spider. And as soon as the spider died, another Lunk spawns.

![Lunk spawns automatically 1](https://user-images.githubusercontent.com/18005338/59068739-3ddf1900-88b5-11e9-8029-8319e8873b4d.png)
![Lunk spawns automatically 2](https://user-images.githubusercontent.com/18005338/59068740-3ddf1900-88b5-11e9-8ada-bc81d5404679.png)


So 
1. it seems that Lunk spawns for everyone and not for the specific player
2. He spawns multiple times.
