### ISSUE TITLE
[Quest] Lunk's Adventure: Cranky Little Dwarfs - ID 27983 - Searing Gorge

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2094]
**Links:**
Quest: https://www.wowhead.com/quest=27983/lunks-adventure-cranky-little-dwarfs
Lunk: https://www.wowhead.com/npc=47332/lunk
Dark Iron Steamsmith: https://www.wowhead.com/npc=5840/dark-iron-steamsmith

**What is happening:**
Lunk does not spawn after killing Dark Iron Steamsmith, therefore you can´t access the quest.

![Cranky Little Dwarfs - how it is](https://user-images.githubusercontent.com/18005338/58495619-3ebad100-8178-11e9-8d39-92e27941101a.PNG)

**What should happen:**
After killing Dark Iron Steamsmith, Lunk should spawn and offer the given quest.
![Cranky Little Dwarfs - how it should be](https://user-images.githubusercontent.com/18005338/58495617-3ebad100-8178-11e9-9ca1-5af0d359d9da.PNG)

**Comment by Rushor** [comment]
lunk will now spawn once Dark Iron Steamsmith was killed. if the quest itself is not working pease open a new issue for that :)

**Comment by zippoking** [comment]
Well, good thing is, he definitely spawns now, but way too often :-D.

So i came into this area, and there were already 2 spawns of Lunk. He should only spawn if the player kills a dwarf.
![Lunk spawns automatically 3](https://user-images.githubusercontent.com/18005338/59069817-a67bc500-88b8-11e9-8895-6e670d4da475.png)
.

**Comment by Echinaceax** [comment]
I also just see this happen @zippoking 

When you kill a https://www.wowhead.com/npc=5840/dark-iron-steamsmith a Lunk spawns on every kill
