### ISSUE TITLE
[Object][Quest] Quest Sign not clickable - Burning Steppes

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2099]
**Links:**
Can´t provide links, because i coulnd´t find out which quest you get.

**What is happening:**
The quest sign shows that there is a quest available, but the sign is not clickable.
![Quest sign in Burning Steppes not clickable](https://user-images.githubusercontent.com/18005338/58502087-1cc84b00-8186-11e9-936b-07c99c3d9e6e.PNG)

**What should happen:**
This is how it should look like:
![Quest sign in Burning Steppes - how it should be](https://user-images.githubusercontent.com/18005338/58502119-2d78c100-8186-11e9-87f5-a0b8e953c96f.PNG)

**Comment by Kitzunu** [comment]
Do you have a map location?

**Comment by sarahkay88** [comment]
@Kitzunu I believe this is an opposite fraction quests and is an horde quest https://wow.gamepedia.com/Adventurers_Wanted:_Blackrock_Depths_(Horde) the issue is that the yellow ! shouldn't be available for alliance to see

**Comment by sarahkay88** [comment]
this is the alliance version https://www.wowhead.com/quest=28068/adventurers-wanted-blackrock-depths - total different location - however this is bugged and been reported so don't click on it

**Comment by Kitzunu** [comment]
Restricted the quest to Horde now
