### ISSUE TITLE
[NPC] Undercity Battle Masters - Undercity

### ISSUE THREAD

**Issue by ScoobyPwnsOnU** [WoWManiaUK/Blackwing-Lair#210]
https://www.wowhead.com/npc=34983/deathstalker-fane
https://www.wowhead.com/npc=50676/hans-crump
https://www.wowhead.com/npc=34985/misery
https://www.wowhead.com/npc=35611/magistrix-erembria

![image](https://user-images.githubusercontent.com/41521670/50196617-72601800-0309-11e9-91d8-6e1f50f199e6.png)

None of the battle masters give you the option to queue into battlegrounds.

**Comment by wow-mania** [comment]
duplicate
