### ISSUE TITLE
[Quest] Return to Keeshan - missing - ID 28183 - Burning Steppes

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2101]
**Links:**
Quest: https://www.wowhead.com/quest=28183/return-to-keeshan
NPC: https://www.wowhead.com/npc=14437/gorzeeki-wildeyes

**What is happening:**
The NPC Gorzeeki Wildeyes offers A&H Quests. Unfortunately he doesn´t offer the Quests Return to Keeshan, instead he offers the horde version of it.
Might be an issue with #764 and #765 and #466 and #2098 

![Return to Keeshan - wrong quest](https://user-images.githubusercontent.com/18005338/58504757-a1699800-818b-11e9-93f9-d385e61cfe75.PNG)

**What should happen:**
Gorzeeki Wildeyes should offer the correct Quests for alliance players.

**Comment by Rushor** [comment]
alright all questorder and all conditions for horde and alliance player fixed now.
