### ISSUE TITLE
[NPC] Akma'hat - AI

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Blackwing-Lair#2104]
Worldboss Akma'hat need some scripting.

https://de.wowhead.com/npc=50063/akmahat

**Comment by giles1508** [comment]
Just killed this in a 5 man group,  myself ( Klubbed )   chargelol ,  trixie ,  showtooltip  and bravenorth   and only 1 item dropped,  all the scorces i can see on wowhead show 2 epics and 1 recipe dropped,   not sure if you can add that before the fix is released

**Comment by Sammy974** [comment]
This boss is not dropping anything, he's supposed to drop an epic item. Last week he dropped only 2 jewelcrafting recipes and today absolutely nothing...
