### ISSUE TITLE
[Quest] Astranaar's Burning! - ID 13849 - Ashenvale

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2115]
**Links:**
Quest: https://www.wowhead.com/quest=13849/astranaars-burning
Bucket of water: https://www.wowhead.com/item=46094/bucket-of-water
Spell throw the bucket: https://www.wowhead.com/spell=64558/throw-bucket-of-water

**What is happening:**
In #1758 there was no fire, but now there is. 
Unfortunately the next issue is, if you throw the bucket of water onto the fire, it does not count towards the quest.

![astranaars burning - how it is](https://user-images.githubusercontent.com/18005338/58579940-595e7a00-824c-11e9-8504-27428046001b.PNG)

**What should happen:**
When you throw the bucket of water onto the fire, it should count towards the quest.
![astranaars burning - how it should be](https://user-images.githubusercontent.com/18005338/58579780-04226880-824c-11e9-9e67-b4f2475ed2ef.PNG)

**Comment by zippoking** [comment]
Sry i take it back, apparently not all fires work. Got it now.

**Comment by Echinaceax** [comment]
@Rushor new issue reported on this #3310
