### ISSUE TITLE
[NPC] Darkmist Silkspinner

### ISSUE THREAD

**Issue by Djuuuu** [WoWManiaUK/Blackwing-Lair#2128]
**Links:**

https://www.wowhead.com/npc=4379/darkmist-silkspinner

**What is happening:**

Killing the mob makes you neutral with Ashtongue Deathsworn (Black Temple reputation in the Burning Crusade extention).

**What should happen:**

The mob shouldn't give that reputation or any reputation at all.

![WoWScrnShot_052919_234946](https://user-images.githubusercontent.com/51149848/58593895-84f15c80-826c-11e9-8e64-b1df73c3efdf.jpg)

**Comment by Kitzunu** [comment]
Are you sure this is because of them?

I am checking DB and there is a zero possibility for them to give any reputation rewards

**Comment by Rushor** [comment]
if there was any kind of entry for it, it's deleted now.
