### ISSUE TITLE
[Talent] Blood in the Water (Druid) 80319

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2135]
**Links:**
http://prntscr.com/nvcxwh
http://prntscr.com/nvd3wm
http://prntscr.com/nvd4h2

from WoWHead or our Armory

**What is happening:**
It does not refresh Rip on target after using Ferocious bite when target is under 25%

**What should happen:**
It should refresh Rip on target

**Comment by Keader** [comment]
Duplicated of #1927
