### ISSUE TITLE
[Spell/Druid] Skull Bash

### ISSUE THREAD

**Issue by gitkulu** [WoWManiaUK/Blackwing-Lair#2136]
**Links:**
(Spells not present on wowhead)
Skull Bash (Bear Form): http://cata-shoot.tauri.hu/?spell=80964
Skull Bash (Cat Form): http://cata-shoot.tauri.hu/?spell=80965

**What is happening:**
When using Skull Bash (in either Cat Form or Bear Form), you do not charge the target.

**What should happen:**
When using Skull Bash (in either Cat Form or Bear Form), you should charge the target.

**Comment by TheSale** [comment]
dont know about charge, but it failed several times to interrupt target casting (it was not shielded casting, it was interruptable some healing or damaging spell)

**Comment by gitkulu** [comment]
So far it never failed to interrupt for me, are you sure that it was't an NPC issue?

**Comment by TheSale** [comment]
it dont interupt in pvp and still dont charge to target

**Comment by mfranca0009** [comment]
Bear Charge (Skull Bash): https://i.gyazo.com/b47530467194a8b39be9ba0a3317cf07.mp4
Cat Charge (Skull Bash): https://i.gyazo.com/14a78cde5c6c7be0eaab86ee28f8b285.mp4
Bear Interrupt (Skull Bash): https://i.gyazo.com/2389080c58e7f017697a0e4452a7cc0c.mp4
Cat Interrupt (Skull Bash): https://i.gyazo.com/a3f810e33c14e4da4e6d16072a2c15df.mp4

Spells are working as intended, the only slight problem would be, if you hold your right mouse button (moving camera) it seems it almost fails the charge but still puts spell on cooldown. If you cast spell without messing with camera angle, it charges as normal.

Also, these two spells do not interrupt on player targets; only on NPCs with interruptable spell casts.
Spell Attribute: SPELL_ATTR7_INTERRUPT_ONLY_NONPLAYER
