### ISSUE TITLE
[Spell] Rake (Druid) 1822

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2137]
**Links:**
http://prntscr.com/nvdhf8
http://prntscr.com/nvdoiu

from WoWHead or our Armory
https://www.wowhead.com/spell=1822/rake#changelog

**What is happening:**
I think that Rake don`t perform as it should.
In description of the spell say "Deals more damage than Claw"
On first screenshot in links, on scada for 1 of each abilities over 15 second fight rake indeed come on top of claw, however Rake has improvement from talent Endless Carnage 88315
which increase rake duration for additional 6 seconds so rake from initial 9 sec goes to 15 sec.

On second screenshot where I fight and kill mob in 16-17 seconds I was keeping 1 full duaration of rake on mob and it did lowest damage of all abilities that I fully used in that fight and I did not spam Claw I used claw 4-5 times. Rake is described as superior to claw, but even improved Rake is way bad and with 35 rage cost it is better to use anything else but rake.

On a sample of 26mil damage done overall
Average damage of rake is 0.8k damage, while Claw is 2k and other attacks 1.6k-3k  that cost same amount of energy.
![Screenshot_1](https://user-images.githubusercontent.com/20323863/58631996-9d04c280-82e4-11e9-979f-1691003f4385.png)

![rake](https://user-images.githubusercontent.com/20323863/58632075-e9e89900-82e4-11e9-8b09-2e7c10036c7f.png)

![claw](https://user-images.githubusercontent.com/20323863/58632081-ed7c2000-82e4-11e9-8981-d07ab3f3ce55.png)

**What should happen:**
I think that rake should have initial damage (I don`t think it does have atm) that should not be more than damage of Claw BUT damage over time should keep rake way up than claw

I hope I give proper and enough information on this.

**Comment by gitkulu** [comment]
The initial damage of Rake works fine. That's probably your minimum hit of 0.2K.
The tooltip only shows "Deals more damage than claw" when you have Beginner Tooltips enabled, and I don't think those are very reliable. It does not take your gear into account, e.g. the amount of mastery you have, which increases bleed damage.

**Comment by TheSale** [comment]
I am 230 average ilvl with 333 polearm weapon no pvp items and only agi gear, I know it is low gear but 200 damage I should do on lvl 50 :D
200damage is nothing when with same amount of energy used... I can spam mangle or anything else instead...
![mangle](https://user-images.githubusercontent.com/20323863/58639056-72bc0080-82f6-11e9-8032-f8a8faf63a0d.png)

I agree with everything you said, that it is beginner tooltip, and may be wrong, also you are 100% right with mastery and bleed effect...

But there is no anything on lvl 85 that should make this low damage, only 4% of total damage, with 21% crited hits and average of 0.8k...

if I was naked and without weapon, I think with fists I will make more than 200 damage....

I cant say that I am right 100%, but I just know this is very bad atm
if is this as intended I will just remove 2 talent points from Endless Carnige and put it anywhere else and remove this useless spell from my action bar... till I get l 300+ ilevel and reopent this again :D

**Comment by gitkulu** [comment]
The initial damage is supposed to be very low, it's nothing but a minor bonus. You should only be using Rake to keep up the bleed. It definitely shouldn't replace Mangle (or Claw, which is pretty much useless).

You might want to take a look at http://www.tauri-veins.tk/feral-druid-wow-pve-dps-rotation-cooldowns-abilities

**Comment by TheSale** [comment]
I got some items crafted by friend I got from 230 to 272 ilvl and I will go and reforge everything to mastery to see the difference

**Comment by giles1508** [comment]
1 claw shouldn't be used in rotation ever,     2 rake should only be used when it's not on the target,  its only used to literally put the bleed up,  mangle then increases its bleed damage

**Comment by gitkulu** [comment]
I'm not sure what you expected, if Rake was as strong as Rip, you would be overpowered.
Besides, you'd definitely lose DPS by not keeping up the Rake bleed.

**Comment by TheSale** [comment]
I know you are druid player as well, and apparently you have more experience than me and if you say it is okay and work as intended then I will close the issue

this is last tests that I did 15.6milion damage overall 
http://prntscr.com/nvmpzw

in near perfect situation, no movement, no debufs, no dodging abilities, 
only steady dps, 47min spent in combat rake uptime was over 81%, damage done 10% (only)

and in most perfect situation, 95% Rake uptime give only shy 11% damage
![rake 95uptime 3](https://user-images.githubusercontent.com/20323863/58668950-dd8f2b00-833a-11e9-8372-0dc8adb7bdd7.png)
![rake 95uptime 4](https://user-images.githubusercontent.com/20323863/58668982-f4ce1880-833a-11e9-9ada-f10519be36c9.png)

Keep on mind that I had to pause other abilities to get this uptime on point, so not doing as much damage with other spells in time it will give more over time rake damage.

also cat only have 2 spells in rotation 
SHRED and RIP
Rake 1 per 15 sec (only bleed}
Mangle only 1 per min  (only to apply debuf or combo stacking if cant use shred)

Savage roar from time to time to dump combo points
Ferocious bite only when boss is under 25% (with 2 set items then under 60%)

**Comment by TheSale** [comment]
just to add this for future reference when we get to point to have full 359 gear available
https://www.youtube.com/watch?v=fYjxKL0FUEE (part 1 of 2)
http://prntscr.com/nvs6zb rake doing 8.6k crit tick on doll
http://prntscr.com/nvsc5n rake doing 14.4k crit tick on boss in hc dung

**Comment by giles1508** [comment]
i believe the reason that rake isnt up to its full potential is because there is a current issue with bleed damage not ignoring armor,  ill have to find the post to reference it
