### ISSUE TITLE
[Npc] Nimboya  Northern Stranglethorn

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#2138]
**Links:**

https://www.wowhead.com/npc=2497/nimboya

**What is happening:**
hes not at grom gol

**What should happen:**
he shoud be at grom gol at 38 ,48 and start 4 quest

**Comment by Kitzunu** [comment]
![Uploading image.png…]()

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/58902079-b6ea3f00-8702-11e9-92c8-bffa5f5033d2.png)

**Comment by Echinaceax** [comment]
kitz is he there with GM off?
