### ISSUE TITLE
[Quest] [We're Here to Do One Thing, Maybe Two... ] Ashenvale

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#2139]
**Links:**
quest 
https://cata-twinhead.twinstar.cz/?quest=25945
npc 
https://cata-twinhead.twinstar.cz/?npc=41678

**What is happening:**
aldo doesnt offer this quest

**What should happen:**
shoud offer this quest also ends https://cata-twinhead.twinstar.cz/?quest=28532.
importend quest to get into Stonetalon Mountains.

**Comment by sarahkay88** [comment]
#1288
