### ISSUE TITLE
[Item JC Daily] Stardust No.2

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#2140]
**Links:**
https://www.wowhead.com/item=52507/stardust-no-2
https://www.wowhead.com/quest=25159/the-latest-fashion
**What is happening:**
It dosent give credit if you are using it
**What should happen:**
Should work when using on a hummanoid

**Comment by Sammy974** [comment]
Any chance some of the jc quest to be fixed?

**Comment by Rushor** [comment]
fixed 

![I](https://i.imgur.com/PpsL43I.jpg)

**Comment by Echinaceax** [comment]
@Rushor this one too needs refix please :)
