### ISSUE TITLE
[Dungeon/NPC] Vexallus Magisters' Terrace

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#2141]
**Links:**
https://www.wowhead.com/npc=24744/vexallus
**What is happening:**
The boss is not giving the quest item Voltaile Essence (https://www.wowhead.com/item=73084/volatile-essence)
**What should happen:**
The boss should drop the quest item so you can progress to heroic mode and farm the mount

**Comment by Rushor** [comment]
loot added (in hc too)

![I](https://i.imgur.com/KCdjphO.jpg)

**Comment by Denrunmt** [comment]
![Screenshot_10](https://user-images.githubusercontent.com/52254524/62482409-bb43de80-b7bd-11e9-8c76-9736169e1cc6.png)

The quest item (Volatile essence) drops from Vexallus. The quest works too. But even after doing the quest I can't enter the dungeon on Heroic difficulty.

**Comment by sarahkay88** [comment]
U need to make a new report for the heroic one, this report was for an item. Sorry

**Comment by Denrunmt** [comment]
Okay, no problems.
