### ISSUE TITLE
[Npc] Winnoa Pineforest Southern Barrens  

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#2144]
**Links:**
npc 
https://www.wowhead.com/npc=37717/winnoa-pineforest
quest
https://www.wowhead.com/quest=24573/honoring-the-dead

**What is happening:**
winnoa doesnt offer the quest honoring the dead

**What should happen:**
winnoa shoud offer the quest honoring the dead

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/58661738-ea0a8800-8328-11e9-8015-a9f1eb9174a1.png)

Works.
Make sure you do the required pre quest before trying to pick up this quest
