### ISSUE TITLE
The Embalmer's Revenge Quest is not working

### ISSUE THREAD

**Issue by Menethas** [WoWManiaUK/Blackwing-Lair#2145]
The Embalmer's Revenge Quest in Duskwood is not working properly. 

It should phase you into an instance of Darkshire where it is on fire and there is an abomination attacking the town. 

Video for evidence: https://www.youtube.com/watch?time_continue=8&v=ErOLhjpgCA8

**Comment by Kitzunu** [comment]
please use the given template when reporting issues.

**Comment by sarahkay88** [comment]
#466

**Comment by sarahkay88** [comment]
#446
