### ISSUE TITLE
[Talent/Hunter] T.N.T.

### ISSUE THREAD

**Issue by gitkulu** [WoWManiaUK/Blackwing-Lair#2150]
**Links:**
(Spells not present on wowhead)
T.N.T. talent Rank 1 Spell ID:  56333
T.N.T. talent Rank 2 Spell ID: 56336
Lock and Load buff Spell ID: 56453

**What is happening:**
Periodic  damage from Black Arrow, Immolation Trap and Explosive Trap does not trigger the Lock and Load buff at all.

**What should happen:**
Periodic  damage from Black Arrow, Immolation Trap and Explosive Trap should have a 10%/20%  chance to proc Lock and Load.

**Comment by sarahkay88** [comment]
https://cata-twinhead.twinstar.cz/?spell=56333https://cata-twinhead.twinstar.cz/?spell=56333 -rank 1
https://cata-twinhead.twinstar.cz/?spell=56336 - rank 2

**Comment by sarahkay88** [comment]
lock and load link is in #2051

**Comment by Slydee23** [comment]
makes SV unplayable

**Comment by Slydee23** [comment]
should it be live or next update ?

**Comment by Keader** [comment]
in live already, not worked?

**Comment by Nemuriciu** [comment]
Issue needs reopen. 
T.N.T proc does not reset the Explosive Shot cooldown as it was intended.

**Comment by Keader** [comment]
Spell description:

> Description: When you deal periodic damage with your Immolation Trap, Explosive Trap or Black Arrow you have a $s1% chance to trigger Lock and Load.
Nothing indicate that should reset Explosive Shot cooldown.

**Comment by Nemuriciu** [comment]
@Keader 
I know that there is no indication in the spell description that the spell cooldown should be reset on proc, but that is the way it was scripted in the original version.

https://www.youtube.com/watch?v=CveT6Cb2e38   -  13:25
https://www.youtube.com/watch?v=XHDJlwn8UuE   -  3:58
https://www.youtube.com/watch?v=Q1dgpU3yFnE   -  2:26

I attached above 3 links of survival hunters doing their rotations, and specified the corresponding time of the video in which they cast the explosive shot and put it on cooldown, and then while the cooldown is active the T.N.T procs and resets the cooldown. (watch closely the Exploding Shot spell on the action bars of the players in the video)

This is an important issue which lowers the dps rotation of the surrvival hunter.

Hope this would help.

**Comment by Keader** [comment]
Your videos just sustein my theory.
Check https://youtu.be/CveT6Cb2e38?t=805 and https://youtu.be/Q1dgpU3yFnE?t=146
After lock on load proc, next proc only happens in +- 22 sec later.
Lock and Load has 22 sec cooldown.

**Comment by Keader** [comment]
Oh no, you talking about explosive shot.
I was reading about reset lock and load .-.
Yes is looks valid, fixing it.

**Comment by Slydee23** [comment]
still not resetting cd on live pls reopen
