### ISSUE TITLE
[Glyph/Hunter] Glyph of Misdirection

### ISSUE THREAD

**Issue by gitkulu** [WoWManiaUK/Blackwing-Lair#2151]
**Links:**
GlyphID: 56829 (not present on wowhead)
http://cata-shoot.tauri.hu/?spell=56829

**What is happening:**
When I use Misdirection on any of my pets, it doesn't reset the cooldown of Misdirection.

**What should happen:**
When you use Misdirection on your pet, it should reset the cooldown.

**Comment by sarahkay88** [comment]
glyph id  - https://cata-twinhead.twinstar.cz/?spell=56829

**Comment by Keader** [comment]
Fixed in #2802
