### ISSUE TITLE
[Buff] Strength of the Halaani

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2153]
**Links:**
https://www.wowhead.com/spell=33795/strength-of-the-halaani#comments
from WoWHead

**What is happening:**

The buff remains on the character even if it is no longer in Nagrand.
It remains also after exit game and clear cache.
I can't say if it just display the buff or there is the 5% increased dmg too.

**What should happen:**

This is buff is given to everyone in the faction who controls Halaa and _**are in Nagrand**_.

**Comment by Kitzunu** [comment]
@Keader not fixed, just went to Zangramarsh and still have the buff
