### ISSUE TITLE
[Buff] Blessing of Auchindoun

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2154]
**Links:**
https://www.wowhead.com/spell=33377/blessing-of-auchindoun
from WoWHead

**What is happening:**

The buff remains on the character even if it is no longer in Outlands.
It remains also after exit game and clear cache.
I can't say if it just display the buff or there is the benefits too.

**What should happen:**

It should not be displayed if my char is in Orgrimmar :)

**Comment by Sammy974** [comment]
It happens with the Hellfire buff too

**Comment by Echinaceax** [comment]
still needs fixing :)
