### ISSUE TITLE
Launching the game

### ISSUE THREAD

**Issue by Menethas** [WoWManiaUK/Blackwing-Lair#2160]

**Comment by Menethas** [comment]
Everytime I launch the game from the launcher, it resets my visual/audio settings to default. It didnt do it when I first installed it a few days ago, but now it is and idk why.

**Comment by Kitzunu** [comment]
Place your Launcher in a root drive i.e C:\

Uncheck Read-Only for the game folder and Realmlist.wtf

Start the launcher as an administrator
