### ISSUE TITLE
[Quest] Four Heads are Better than None

### ISSUE THREAD

**Issue by Djuuuu** [WoWManiaUK/Blackwing-Lair#2164]
**Links:**

https://www.wowhead.com/quest=27500/four-heads-are-better-than-none

**What is happening:**

https://www.wowhead.com/npc=46018/beeblephod
Beeble'Phod isn't in the cave and the quest therefore can't be completed.

![WoWScrnShot_053119_124510](https://user-images.githubusercontent.com/51149848/58700980-f252d980-83a1-11e9-8209-5be20806c984.jpg)

**Comment by Anders98** [comment]
Would love it added to the .bq list, as it rewards a crucial trinket for most classes.

**Comment by Rushor** [comment]
works :)
