### ISSUE TITLE
[Currency]Fossil Archaeology Fragment

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#2166]
**Links:**
https://www.wowhead.com/currency=393/fossil-archaeology-fragment

**What is happening:**
fossil fragments dont drop from survey.well the survey works but if u pick it up u get no fragments.

**What should happen:**
u shoud get fossil fragments from survey

**Comment by giles1508** [comment]
Can confirm this is happening, tested this with 5 different fossil digsites and each find gives no loot

**Comment by Sammy974** [comment]
I can confirm too. Empty slot in each fossil digsite i visited.

**Comment by Geniuskp** [comment]
Confirm

**Comment by Djuuuu** [comment]
Confirm too

**Comment by dagget1337** [comment]
Since i´m farming archeo like mad for reasons, i´m actually so far that i already got 17 rare artefacts and only 3 are left for the title, so i can only ask to give this a **higher priority** since it is possible to get 5 rare artefacts from fossil.

**Comment by Bathelmo** [comment]
another fix on blind, please test to see whether it made a change or not

**Comment by wojen616** [comment]
still doesnt work

**Comment by Echinaceax** [comment]
@wojen616 hasnt been confirmed fixed yet ...will be confirmed when they can

**Comment by Echinaceax** [comment]
@Bathelmo tested Un'goro so far and loots 3 times all empty 

fossil 

![fossil](https://user-images.githubusercontent.com/39439201/62560555-9747d200-b87d-11e9-8f5f-046c52f000e1.jpg)

no artifact logged

![none there](https://user-images.githubusercontent.com/39439201/62560588-a9297500-b87d-11e9-9545-0701bd5bbffb.jpg)

**Comment by hediunchained** [comment]
@Echinaceax the item Crate of Fossil Archaeology Fragments is added in WoD i think so that's why you arnt able to add that item

**Comment by Echinaceax** [comment]
>  the item Crate of Fossil Archaeology Fragments is added in WoD i think so that's why you arnt able to add that item. 

Oh i see thanks for that update (i just wasnt sure on that part so just thought i'd mention it :)

> And is there an ETA to when will the fossil fragment be fixed, its kind of painful to level up archeology at the moment.

Sorry no ATA on this, they fix from a prioitylist so its in the queue is all i know atm

**Comment by hediunchained** [comment]
@Echinaceax thanks for the reply

**Comment by Rushor** [comment]
moved to https://github.com/WoWManiaUK/Blackwing-Lair/issues/3012
