### ISSUE TITLE
[Talent/Hunter BM] Frenzy

### ISSUE THREAD

**Issue by Imba232** [WoWManiaUK/Blackwing-Lair#2168]
**Links:**

http://cata-shoot.tauri.hu/?spell=19623

**What is happening:**
It only procs on Bite/Claw critical strikes and the buff is 0% speed, so it's just visual and it doesn't do anything.

**What should happen:**
All pets basic attacks (Bite/Claw/Smack) should increase pet's attack speed by 2%/4%/6% and stack up to 5 times.

**Comment by hediunchained** [comment]
still not fixed 01/09/2019
