### ISSUE TITLE
Dire Maul - dungeon - issue 2  (system message lvl31)

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#2169]
**Links:**

https://www.wowhead.com/dire-maul

**What is happening:**
When trying to walk into this dungeon a message says you must be 31 to entre  - myself and levelling buddy are 43.

![World of Warcraft 31_05_2019 18_22_51](https://user-images.githubusercontent.com/42302580/58723226-74a6c200-83d1-11e9-82b5-3526a47ab3c1.png)

**What should happen:**

Wow head says level 44 
in game message is wrong - or if its right I should be able to entre

**Comment by Rushor** [comment]
yes that was fixed some time ago already. it is set to level 31 in access_requiremnt already and fixed.
