### ISSUE TITLE
[Quest] Massacre at Light's Point -12701-

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Blackwing-Lair#217]
**What should happen:** 
The quest requires you to interact with a mining cart, then the player becomes the cart and a "Scarlet Miner" takes the cart to the next zone.

Currently, Scarlet Miner just stands there, not moving and continuing the quest.

**Workaround:** 
Player can ride to the next zone with the mount obtained from a previous (optional) quest, this way will not succeed every time since mobs along the way might kill the player if player has no defensive talents/dismounts for any reason/gets hit by multiple critical strikes.

**To reproduce the issue**
simply take the said quest and try to complete it the way it should.

Quest ID : 12701

**Comment by Echinaceax** [comment]
@wow-mania - Can access the cart BUT the npc https://www.wowhead.com/npc=28819/scarlet-miner is inactive, he is suppost to pull the cart when you get in it 

and there is also Double/triple spawn (could be why) 

![cart](https://user-images.githubusercontent.com/39439201/57622377-bf30dd80-758d-11e9-87fe-fd0f6ad54081.jpg)

**Comment by Echinaceax** [comment]
@wow-mania not fixed , not sure why you closed it https://github.com/WoWManiaUK/Blackwing-Lair/issues/217#issuecomment-491807388

**Comment by Druhl** [comment]
Confirmed, same as above. Every click on the Mine Car spawns another Scarlet Miner (they stack endlessly) but none tows the car.

**Comment by Rushor** [comment]
finally fixed

![I](https://i.imgur.com/QVBJY1U.jpg)

you now get the path from the miner.
