### ISSUE TITLE
[Quest] They Set up the bomb! - Ashenvale

### ISSUE THREAD

**Issue by c2juk2000** [WoWManiaUK/Blackwing-Lair#2170]
**Links:**

https://www.wowhead.com/quest=13981/they-set-them-up-the-bomb

**What is happening:**
Quest Asking Horde Player to go into middle of Alliance base and speak to alliance NPC, but clicking NPC gives attack option..

**What should happen:**

i believe this should be a alliance quest not a horde quest

Was meant to of been fixed months ago.
https://github.com/WoWManiaUK/Blackwing-Lair/issues/952

![WoWScrnShot_053119_183508](https://user-images.githubusercontent.com/42567442/58723975-54780280-83d3-11e9-93fe-73bfc4dd57ce.jpg)

**Comment by Dranah** [comment]
Reopening old issue.
