### ISSUE TITLE
[Debuf] Resurrection Sickness 15007

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2171]
**Links:**
http://prntscr.com/nw0z4v

from WoWHead or our Armory

**What is happening:**
it does not disappear if you log off
I was playing roque and shaman for several hours and when I got back to druid still had ress sick

**What should happen:**
it should disappear after 10 min,  ether online or not

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/58727560-fbb16580-83e4-11e9-872a-36930900c1e6.png)
https://wowwiki.fandom.com/wiki/Resurrection_Sickness
