### ISSUE TITLE
[Dungeon] Steamvault

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#2174]
**Links:**
https://www.wowhead.com/the-steamvault
**What is happening:**
You cannot enter the room of the last boos (Locked)
**What should happen:**
Even by killing the 2 other bosses and activating the devices the last room dosent open

**Comment by giles1508** [comment]
quick bump,   17 days .  i know its legancy  but people  like to run these for transmog runs etc and having this not open isnt very nice
any chance we could asign a dev as no one has atm :)

**Comment by Denrunmt** [comment]
Can confirm that. 
![Screenshot_15](https://user-images.githubusercontent.com/52254524/63280399-628f3e00-c2b3-11e9-9aa5-44c4732cc179.png)

**Comment by Rushor** [comment]
emote added and gate should open now. thx Keader

![I](https://i.imgur.com/7tlDQe8.jpg)
![I](https://i.imgur.com/kCWOzrN.jpg)
![I](https://i.imgur.com/5RFXpZY.jpg)

**Comment by kDracku** [comment]
finally my achiv

**Comment by Nirvanum** [comment]
don't work for me
