### ISSUE TITLE
[NPC] Grot Deathblow Twilight Highlands

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#2175]
**Links:**
https://www.wowhead.com/npc=49387/grot-deathblow
**What is happening:**
You cannot browse hes goods (http://i63.tinypic.com/solbg1.jpg)
**What should happen:**
You should browse hes goods ^^

**Comment by Kitzunu** [comment]
I fixed this one.

duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/2387

**Comment by Kitzunu** [comment]
fixed
