### ISSUE TITLE
[Quest] Coilfang Armaments

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#2176]
**Links:**
https://www.wowhead.com/item=24367/orders-from-lady-vashj
**What is happening:**
You cannot open the quest (Begin the quest)
Its a quest that drops from adds in steamvault
**What should happen:**
You should begin and turn the quest to Ysiel Windsinger at the Cenarion Refuge - Zangamarsh.
After that you can turn the Coilfang Armaments (https://www.wowhead.com/quest=9766/coilfang-armaments)

**Comment by sarahkay88** [comment]
if you read the comments it says this quest was removed in 4.3.0 not sure how accurate this is

**Comment by Kitzunu** [comment]
marked it as Deprecated/obsolete/disabled
![image](https://user-images.githubusercontent.com/24550914/58741741-dfc9b600-841c-11e9-82ee-3e947857c29b.png)
