### ISSUE TITLE
[Core] Repair/Withdrawl from guild

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2179]
**Links:**

cant find a link for guild repairs...

**What is happening:**

guild repair and guild bank withdraw is only allowing a set amount,   even when the guild master is setting a value in the guild control options 
see below, i have set the value to 200g for the officer rank,  this value is a daily value they can withdraw or repair,   not 200g for both,  this is combined,  so they can either repair for 100g and take 100g out or they can use all 200 on repairs etc
but no matter what i set the value as its showing for the officers in my guild 1 gold max a day,  no matter what i set the value as

![WoWScrnShot_060119_023520](https://user-images.githubusercontent.com/50211643/58741865-94140e00-8416-11e9-9a14-c0ba3d7b5785.jpg)

this second screenshot is from Dev server where me and kitz went there to test and on Dev it will only allow 2 silver per day,   using same conrols as i am on live

https://cdn.discordapp.com/attachments/584187724685377556/584187730406277129/unknown.png

**What should happen:**

it should allow the selected rank to repair or withdraw or a combo of both the value of what is set in guild bank options on guild control tab

**Comment by sooky77** [comment]
hello, love your interface is elvui? but which skin
and the annimation of your vi with portrait,?

**Comment by giles1508** [comment]
I believe its called gui   what's your discord name I'll message you in a bit

**Comment by sooky77** [comment]
discord name : sooky#5187

**Comment by giles1508** [comment]
I'm out atm, when I get home ill zip it up and send it over,  it's plug and play too, so no stupid huge set up etc like most custom ui installs it's awesome

**Comment by giles1508** [comment]
sent you a friend request on discord,  ill send the UI over to you on there

**Comment by Echinaceax** [comment]
Still and issue 17.10.19 @Rushor

**Comment by Rushor** [comment]
try now pls :)

**Comment by Echinaceax** [comment]
Can we dev is up @Rushor :)
Check tomorrow for you

**Comment by Echinaceax** [comment]
Hmm, ive tested this just now and it down give at all now (10g before by adding 1000000)
now ive tested 10 - 100 - 1000000 and its 0 for the other toons tested 3 toons all have 0
