### ISSUE TITLE
[Quest] Death Knight Starting Zone order

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Blackwing-Lair#218]
When a player completes the quest: Scarlet Armies Approach (12757), it causes the area to be phased and renders other quests taken before incompleteable. The quests below are examples of quests that give "Talent Points" and must be completed before phasing. These quests being not completeable causes the player to lose talent points indefinitely.

Plaguebringer's Request(12716), 
Nowhere to Run and Nowhere to Hide(12719), 
Lambs to the Slaughter (12722) 

To reproduce, follow the DK starting zone quests until Scarlet Armies Approach (12757) can be taken, then finish the said quest without completing other quests in the area.

**Comment by Dranah** [comment]
i'll mesh this up with the other DK reports

**Comment by Dranah** [comment]
Ok so by the time you get to "Scarlet Armies Approach" youre not supposed to have ANY other quest in your log. Every other quest should have been a prerequisite to complete before carrying on with the main chain, but the prerequisites are missing so you might have accidentally skipped them. I opened a report for each quest that is missing prerequisites and allows you to leave quests uncompleted.
