### ISSUE TITLE
quest DK  the great battle chapel of light...  bug! 

### ISSUE THREAD

**Issue by sooky77** [WoWManiaUK/Blackwing-Lair#2180]
hello, the quest on the great battle of the chapel of lumier bug
when the spear is thrown the "human" is not there, but the knights of death go to the assault. when several minutes "15 min" the "human" happens it kills all the dk but the Lich King does not arrive, yesterday I am 1h20 to wait and this morning 30 min always nothing .j abstains and starts the same quest
can you please either debug the zone or make me pass this quest, and give me the recompence of this quest (here attached photo) 
"perso MAIZ"

![WoWScrnShot_060119_090247](https://user-images.githubusercontent.com/51257424/58745080-34d0f080-844c-11e9-97a7-fbd3d02d8aca.jpg)
![WoWScrnShot_060119_090253](https://user-images.githubusercontent.com/51257424/58745081-34d0f080-844c-11e9-9bbf-f4fea32ad4af.jpg)
![WoWScrnShot_060119_090312](https://user-images.githubusercontent.com/51257424/58745082-35698700-844c-11e9-9275-8ff68fc56d17.jpg)

![WoWScrnShot_060119_084900](https://user-images.githubusercontent.com/51257424/58745043-68f7e180-844b-11e9-8aab-601c8d8044db.jpg)

**Comment by Frostmanx** [comment]
Hi @sooky77 Abandon the quest and try starting the battle from start again,but this time stick close to Darion Morgraine at all times and it should work as intended. If it does't happen make a ticket in-game and a GM Should be able to help you!

**Comment by sooky77** [comment]
thank you for reactivite reponce. I will start again then following your instructions.
sorry my english is very bad (google trad)

**Comment by sooky77** [comment]
thank you it works, if I remain to rate effectively thank you

**Comment by Frostmanx** [comment]
No problem.
