### ISSUE TITLE
[Quest]A Special Surprise - ID28650 - Scarlett Enclave

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#2181]
**Links:**
previous quest - https://www.wowhead.com/quest=28650/a-special-surprise
next available quest - https://www.wowhead.com/quest=12748/a-special-surprise
quest that should be available - https://www.wowhead.com/quest=12751/a-sort-of-homecoming
Npc - https://www.wowhead.com/npc=29053
from WoWHead or our Armory

**What is happening:**
when you do a special surprise as a goblin instead of getting a sort of homecoming quest it gives you a special surprise again but to kill an orc but you cant attack the orc as a goblin so your stuck without a way to progress

**What should happen:**
once you complete the quest as any class you should be able to pick up the next quest "a Sort of homecoming" to carry on with Deathknight progression chain

![World of Warcraft 01_06_2019 08_42_08](https://user-images.githubusercontent.com/45798884/58745467-49f85000-8449-11e9-9151-9760557cbfc2.png)

**Comment by wow-mania** [comment]
this is not the

**Comment by sarahkay88** [comment]
@wow-mania - I just checked this on dev and found the same issue.... both special surprise quest are available together. if a player takes this one  https://www.wowhead.com/quest=28650/a-special-surprise upon handing in the player has no choice but to then take   https://www.wowhead.com/quest=12748/a-special-surprise which as stated above is incompletable - repo make a gobo dk do the quest chain until you reach this stage take the quest in the above order and player is stuck

**what should happen**
a gobbo should only be able to receive  https://www.wowhead.com/quest=28650/a-special-surprise which should then lead them on to  https://www.wowhead.com/quest=12751/a-sort-of-homecoming allowing them to progress.

**Comment by Kitzunu** [comment]
This is just a matter of allowableRaces
I will fix once I am ready

**Comment by Kitzunu** [comment]
try now

**Comment by sarahkay88** [comment]
@Kitzunu  I tested this - the above quest is only offered once now however the follow on quest https://www.wowhead.com/quest=12751/a-sort-of-homecoming is not offered

**Comment by Shycazia** [comment]
Same here, the Quest "a sort of homecoming" is not offered. so im stuck.

**Comment by Rushor** [comment]
prevquest is: http://cata.cavernoftime.com/quest=28649

**Comment by Rushor** [comment]
this is the goblin prev quest: http://cata.cavernoftime.com/quest=28650

**Comment by Rushor** [comment]
next quest: http://cata.cavernoftime.com/quest=12751

**Comment by Rushor** [comment]
okay refixed that, an kind 'A Special Surprise' of quest you reward here will add you http://cata.cavernoftime.com/quest=12751 and then you can continu the questline.

![I](https://i.imgur.com/bkVuP1R.jpg)
