### ISSUE TITLE
[Quest] Not On Our Watch - Borean Tundra

### ISSUE THREAD

**Issue by gitkulu** [WoWManiaUK/Blackwing-Lair#2183]
**Links:**
https://www.wowhead.com/quest=11871/not-on-our-watch
https://www.wowhead.com/npc=25843/northsea-thug

**What is happening:**
The quest requires you to obtain 12x Shipment of Animal Parts, but there are only 11 object spawns. And Northsea Thugs do not drop Shipment of Animal Parts either.

**What should happen:**
Northsea Thugs should drop Shipment of Animal Parts, and there should be at least 12 object spawns in the area.

**Comment by Kitzunu** [comment]
Northsea thug has 58% dropchance now
