### ISSUE TITLE
Bugged Quest

### ISSUE THREAD

**Issue by Davydov75** [WoWManiaUK/Blackwing-Lair#2188]
Through The troll Hole dun work portal into Zul gurub aint showing

**Comment by giles1508** [comment]
Please use the template provided matey,  with a link to quest etc,  plus zul gurub isn't meant to be open yet so this won't be open for a good few months yet, as this is a progressive server, meaning that not everything will be open at once,  there is a set plan to the raids and instances opening

**Comment by gitkulu** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/wiki/How-to-Properly-Report-an-Issue

**Comment by Kitzunu** [comment]
Duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/1706
