### ISSUE TITLE
[Item] Tome of Burning Jewels

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#2189]
**Links:**
https://www.wowhead.com/item=71949/tome-of-burning-jewels
**What is happening:**
It gives you nothing
**What should happen:**
Discovers a random Cataclysm epic gem recipe.

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/GpH3WrG.jpg)

**Comment by Rushor** [comment]
also gold added to those items: (4632 , 6827 , 9265 , 9276 , 9541 , 10479 , 10569 , 11584 , 16882 , 16883 , 16884 , 16885 , 19298 , 20601 , 20602 , 20603 , 20708 , 20766 , 20767 , 20768 , 21113 , 21150 , 21228 , 23022 , 23846 , 29569 , 32685 , 34865 , 34868 , 34953 , 37525 , 43501 , 43575 , 44751 , 45875 , 45986 , 52006 , 62062 , 69886);
