### ISSUE TITLE
[NPC] Matron Alesso

### ISSUE THREAD

**Issue by Healwho** [WoWManiaUK/Blackwing-Lair#219]
![wowscrnshot_121918_152658](https://user-images.githubusercontent.com/45921854/50246286-e7cbf700-03a2-11e9-8745-4f0bc0d21a0c.jpg)
Not able to train at the priest healer in dalaran.

**Comment by Dranah** [comment]
https://www.wowhead.com/npc=50163/matron-alesso
Confirmed.
The npc should offer 3 options when you speak to her, training, dual spec and reset talents.
Like this:
https://imgur.com/iukKmOS
