### ISSUE TITLE
[Loot] Vortex Pinnacle Trash

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2190]
https://www.wowhead.com/the-vortex-pinnacle

None of the trash drops any loot at all, just gold.
Here's a list of items the trash should be seen dropping:
https://www.wowhead.com/npc=45915/armored-mistral#drops:mode=normal

The boss loot is fine.

**Comment by Rushor** [comment]
@Dranah can you make me pls a list of every creature id which is missing loot? will be better to fix then for me

**Comment by Echinaceax** [comment]
update Normal trash are dropping loots fine (we go there very often for Volatile Air and the Rainsong trinket, However HC isnt dropping loot from trash mobs

**Comment by Echinaceax** [comment]
list is reported here #2985 
so i will close this one
