### ISSUE TITLE
[Spell] Bane of Doom

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2193]
Spell ID 603
https://www.wowhead.com/npc=11859/doomguard

This ability deals way too much damage and does not spawn its doomguards.

**How it should work:**
Has a base damage of around 1,8-2k and a spell power coefficient of 88% per tick. 
(total 7,5k~ base with 352% coeff for all the 4 ticks)
Test1: For a warlock with 6,2k spell power, the intended damage is around 7,4k per tick, with demo talents adding 15%(84740) and and 2% (47236) further increase making it 8,7k. 
(no other effects or mods have been active)
Each tick should have a 50% chance to summon a Doomguard.
Test2: for a warlock with 3,5k spell power, the intended damage is around 4,9k per tick, with demo talents adding 15% and 2% further increase, making it 5,8k per tick.

**How it works atm:**
Base damage looks fine, avg 1,9k, but the spell coefficient looks way higher than intended.
Experimentally, the SP coefficient appears to be 200% per tick (total 800% for all the 4 ticks)
Test1: The same warlock with 6,2k sp and demo talents is doing 16,9k damage per tick instead of 8,7k.
Test2: The same warlock with 3,5k sp and demo talents is doing 10,5k damage per tick instead of 5,8k.
The ticks currently do not ever spawn a Doomguard.

**Comment by Keader** [comment]
Fixed.
Note: May guardian (summoned demon) will not attack.
It's caused by a generic bug with guardians, i'm trying find why it's bugged yet.
Same of Snake Trap

**Comment by Dranah** [comment]
They usually do attack, its just their damage is worthless. Will open separate NPC report sometime.
