### ISSUE TITLE
[Quest/Order] Wings over mount hyjal - ID 25985 - Mount Hyjal

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2199]
**Links:**

https://wow.gamepedia.com/Wings_Over_Mount_Hyjal

**What is happening:**

the quest is currently located on the wrong NPC,   in the chain which you can view below,  when you hand in the quest  -   https://wow.gamepedia.com/Return_to_Nordrassil
it should allow the NPC  named https://wow.gamepedia.com/Tiala_Whitemane to allow the quest wings over mount hyjal and she is located near the starting point when you enter hyjal, 

but currently the prerequisite is missing and the quest is located on this npc =   https://www.wowhead.com/npc=41005/choluna

**What should happen:**

after handing in the return to nordrassil quest you should be able to take the breadcrumb quest which is wings over mount hyjal which the correct npc should be = https://www.wowhead.com/npc=40833/tiala-whitemane

**Comment by Dranah** [comment]
Confirmed, 3 problems :
1) missing prereq : return to nordrassil 25578 
2) wrong NPC gives it: current = choluna 41005, intended = tiala 40833
3) Missing quest text when handing in:
"Oh, you were sent here by Tiala? A wonderful student, she'll do many great things.

Altough I sense even greater potential from you.

Please, stay a while in our shrine. There's much to do, but you can't accomplish anything with a troubled mind. "
