### ISSUE TITLE
[NPC] injured goblin miner -The Storm Peaks

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#220]
NPC - https://www.wowhead.com/npc=29434
Quest - https://www.wowhead.com/quest=12832/bitter-departure

The NPC doesn't stand from his laying position to be escorted out of the cave however he just slides across the ground.

![world of warcraft 19_12_2018 21_05_31](https://user-images.githubusercontent.com/42302580/50248449-04802300-03d3-11e9-8d8b-64a6d8bb93a1.png)
![world of warcraft 19_12_2018 21_08_38](https://user-images.githubusercontent.com/42302580/50248457-0c3fc780-03d3-11e9-8992-2aaf133902c8.png)

**Comment by sarahkay88** [comment]
The npc is named the injured goblin miner.. wouldn't let me add it to title for some reason

**Comment by Dranah** [comment]
As far as I understand, this problem is merely visual.

**Comment by Dranah** [comment]
No change on this one, still visually broken. Also moves incredibly fast for an escort. The quest is doable tho.
