### ISSUE TITLE
[profession]  Archaeology -  missing nerubian crafting

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2201]
**Links:**

https://www.wowhead.com/currency=400/nerubian-archaeology-fragment#projects

**What is happening:**

when you collect nerubian fragments its not showing up in your archaeology profession window to show wht you will be crafting next

**What should happen:**

the very first time you collect any fragment your archaeology window should show you what your able to craft  before you collect enough fragments,  this should show up on the very first time you loot a fragment of each race

**Comment by Geniuskp** [comment]
Confirm

**Comment by hediunchained** [comment]
@Echinaceax this too needs some checking out.

**Comment by Echinaceax** [comment]
@hediunchained can you SS what you see in your spellbook please as giles is away atm so cant provide what i need for this thanks :)

this is what i see 

![dragonblight2](https://user-images.githubusercontent.com/39439201/62683017-ccf3d480-b9bd-11e9-9e73-18c00060b13f.jpg)
![dragonblight4](https://user-images.githubusercontent.com/39439201/62683031-d5e4a600-b9bd-11e9-8b4e-f99e9cf069a3.jpg)

**Comment by hediunchained** [comment]
@Echinaceax i already looted nerubian fragments the other day but its still greyed out
![image](https://user-images.githubusercontent.com/36192411/62723484-1e797f00-ba11-11e9-8ab1-275ca9de86c2.png)

**Comment by hediunchained** [comment]
@Echinaceax i think i found the problem, prior to level 375 archeology, you can loot nerubian fragments in the plaguelands areas and it only count once you achieve the required skill to dig for nerubian fragments in northrend.

**Comment by Echinaceax** [comment]
@hediunchained Ah yes that could be the difference, my test was in Dragonblight as there was a dig site there when i did my test

**Comment by Rushor** [comment]
moved to https://github.com/WoWManiaUK/Blackwing-Lair/issues/3012
