### ISSUE TITLE
[Talent/Hunter] Sic' Em!

### ISSUE THREAD

**Issue by Imba232** [WoWManiaUK/Blackwing-Lair#2203]
**Links:**

Spell ID: 83356

**What is happening:**

Doesn't work.

**What should happen:**

Critical hits from Arcane, Aimed or Explosive Shot should reduce the cost of pet's next basic attack by 100% for 12 sec.

**Comment by sarahkay88** [comment]
https://wow.gamepedia.com/Sic_%27Em!_(hunter_talent)

**Comment by Keader** [comment]
It's fixed already.
But i found a new issue.
Even after pet use the hability the spell is not removed.
