### ISSUE TITLE
[Talent/Hunter] Improved Steady Shot

### ISSUE THREAD

**Issue by Imba232** [WoWManiaUK/Blackwing-Lair#2204]
**Links:**

Spell ID: 53221

**What is happening:**

It gives the buff, but only after you don't have it anymore.

**What should happen:**

Casting two steady shots in a row should give you a buff for 5/10/15% attack speed for 8 sec. Now you only get it after it expired, it's not overriding itself.

**Comment by Echinaceax** [comment]
@mfranca0009 
rank 1 https://cata-twinhead.twinstar.cz/?spell=53221
rank 2 https://cata-twinhead.twinstar.cz/?spell=53222
rank 3 https://cata-twinhead.twinstar.cz/?spell=53224

![image](https://user-images.githubusercontent.com/39439201/107689006-95e43a80-6ca8-11eb-9e54-5dd1c348ea5c.png)
![image](https://user-images.githubusercontent.com/39439201/107689569-45b9a800-6ca9-11eb-8325-6970c8a3b7e5.png)
![image](https://user-images.githubusercontent.com/39439201/107688757-4b62be00-6ca8-11eb-9696-25499ad893f4.png)

also need to check https://cata-twinhead.twinstar.cz/?spell=53224#comments

_**I would like to add that it activates me as soon as the types of steady shot get enough and not after the shot hits the target ... and it is activated even if the target on which the hunter part is immune or deflects by deterence or it doesn't matter if the shot hits the targets or not as soon as the hunter gets enough kinds of steady it should jump**_

**Comment by Echinaceax** [comment]
tested 
i see no issue at all 

reporter says  

- [x] "its not overwriting it until you dont have it anymore" 
rotation https://gyazo.com/f5025b83989c7a7a2df5ff3b09f4925f
spammed Steady Shot https://gyazo.com/f5025b83989c7a7a2df5ff3b09f4925f 


- [x] buff is given and triggered correctly 


try using this rotation 
https://gyazo.com/317629e3aa6bb384bdf426683c535030

Note:
Improved Steady Shot will drop off coz of the aimed shot  2.15 cast time
the aim shot procs and became instant , Steady Shot is a filler until other things are ready 

![image](https://user-images.githubusercontent.com/39439201/107704390-7277ba80-6cbd-11eb-802d-d2a2301799f0.png)


if you still have an issue then we will look into it again
