### ISSUE TITLE
[NPC] Skyfall Star - Vortex Pinnacle

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2207]
https://www.wowhead.com/npc=45932/skyfall-star

These stars levitate somewhat above the ground, sometimes higher, sometimes lower, but their hitbox should allow melee DPSers to attack them at (nearly) all times.

Currently even when they are relatively low, melees are out of range to attack these. This means a melee-heavy party stands no chance of defeating them.

How it should work: the range in which they can be melee attacked need to be increased.

**Comment by Eirolla** [comment]
Group of Skyfall star should move on only out of combat, when combat starts, they are still wandering around.

**Comment by Rushor** [comment]
https://youtu.be/02L1UQzZjj4?t=1521 is just beta

**Comment by Rushor** [comment]
https://youtu.be/4svHdiJvtOA?t=593 This is a better video, as you can see they should move around during the fight

**Comment by Bathelmo** [comment]
the described above resembles a different bug then what was initialy explained in the first context, i am going to ask whether it's possible to closed this down and marked as fixed, the different thing you're describing is infact a different bug that should receives its own ticket.

**Comment by Echinaceax** [comment]
@Bathelmo second report here for you #2914
