### ISSUE TITLE
[Spell] Lok'lira's Bargain - Prevents mounting ( Sons of Hodir quest chain)

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#221]
Unable to mount in shapeshifter form which makes it extremely difficult to complete quest. especially the one to unlock The son of hordir reputation.
For example the following quest - https://www.wowhead.com/quest=12856/cold-hearted
picked up from - https://www.wowhead.com/npc=32540/lillehoff
wants me to fly and rescue 3 drakes. But I have to say shapeshifted to be phased to the quest chain and has mentioned I cannot mount in this form.
therefore I am unable to complete the rest of the chain quest.

**Comment by Dranah** [comment]
https://www.wowhead.com/spell=54461/brunnhildar-disguise 
I believe this is the shapeshift applied while in the quest area which cause the problem.

**Comment by Keader** [comment]
Fixed.

**Comment by Dranah** [comment]
No change on this one. Still same message "You are in a shapeshift form" when attempting to mount.

**Comment by Keader** [comment]
Someone removed my fix... again.
