### ISSUE TITLE
[Quest] Wisps of the Wood - ID 28383 - Felwood

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2212]
**Links:**
Quest: https://www.wowhead.com/quest=28383/wisps-of-the-woods
Item: https://www.wowhead.com/item=64300/swiftwind-switch
NPC: https://www.wowhead.com/npc=48454/talonbranch-wisp

**What is happening:**
When you stand next to the Talonbranch Wisps and use the item, it does not count towards the quest.
![Wisps of the Wood - how it is](https://user-images.githubusercontent.com/18005338/58762237-78ac1e80-854e-11e9-9597-44dccd60f75c.png)

**What should happen:**
You should use the Swiftmind Switch on those Talonbranch Wisps.
![Wisps of the Wood - how it should be](https://user-images.githubusercontent.com/18005338/58762238-7944b500-854e-11e9-9ca1-7f9fe66c49b8.png)

**Comment by Rushor** [comment]
fixed with next update

![I](https://i.imgur.com/r2f9WrW.jpg)
