### ISSUE TITLE
[Npc] Unbound Emberfiend  Twilight Highlands  

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#2214]
**Links:**
quest 
https://www.wowhead.com/quest=28212/hot-stuff
npc
https://www.wowhead.com/npc=48016/unbound-emberfiend
item 
https://www.wowhead.com/item=63283/molten-fury

**What is happening:**
molten fury drops without the quest also this item quest shoud be for allaince.

**What should happen:**
molten fury shoud only drop with the quest.

**Comment by Rushor** [comment]
quickly added that
