### ISSUE TITLE
[Item] Deadwood Ritual Totem - ID 20741 - not dropping - Felwood

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2215]
**Links:**
Item: https://www.wowhead.com/item=20741/deadwood-ritual-totem
starts this Quest: https://www.wowhead.com/quest=8470/deadwood-ritual-totem

Deadwood Avenger: https://www.wowhead.com/npc=7157/deadwood-avenger
Deadwood Den Watcher: https://www.wowhead.com/npc=7156/deadwood-den-watcher
Deadwood Shaman: https://www.wowhead.com/npc=7158/deadwood-shaman

**What is happening:**
The three mentioned Deadwood Furbolgs are not dropping the item, which starts a quest.

**What should happen:**
At one point the item should drop.

**Comment by Dranah** [comment]
How many kills you did test? It has approx 1% drop chance

**Comment by zippoking** [comment]
I killed 88 Mobs in total. I´m still saying its not dropping :-D

![Deadwood Ritual Totem - 3](https://user-images.githubusercontent.com/18005338/58767464-abc0d300-858b-11e9-809c-8415925d38f1.png)
![Deadwood Ritual Totem - 2](https://user-images.githubusercontent.com/18005338/58767463-abc0d300-858b-11e9-934a-7f23fb8a84b7.png)
![Deadwood Ritual Totem - 1](https://user-images.githubusercontent.com/18005338/58767462-ab283c80-858b-11e9-8b31-c4ac2fba26ef.png)
