### ISSUE TITLE
[NPC] Drizle - ID 47556 - Felwood

### ISSUE THREAD

**Issue by karteil** [WoWManiaUK/Blackwing-Lair#2216]
https://www.wowhead.com/npc=47556/drizle

**What is happening:**
The npc is in the correct area (60.6, 9.6) but he tend to hide so it's impossible to target / click / interact with it

**What should happen:**
It should stay stationary like any npc quest giver

**Comment by Kitzunu** [comment]
Please follow the Template made to log issues.
You can also read CONTRIBUTION.MD for extra help.

Thank you for taking the time to log the issue, it will be looked into

**Comment by sarahkay88** [comment]
#611
