### ISSUE TITLE
[Cooking Daily] Even Thieves Get Hungry (ID 26235) - Orgrimmar

### ISSUE THREAD

**Issue by karteil** [WoWManiaUK/Blackwing-Lair#2217]
https://www.wowhead.com/quest=26235/even-thieves-get-hungry

This quest ask the player to obtain "[Horde Infantry Rations](https://www.wowhead.com/item=57879/horde-infantry-rations)"(ID = 57879)  from "[Orgrimmar Thief](https://www.wowhead.com/npc=42594/orgrimmar-thief)" (NPC ID = 42594) but actually there are no Orgrimmar Thieves inside the city.

**Comment by Rushor** [comment]
spawn for creature added
