### ISSUE TITLE
[Quest] Strange Life Forces - ID 28656 - Winterspring

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2218]
**Links:**
Quest: https://www.wowhead.com/quest=28656/strange-life-forces

Winterfall Pathfinder: https://www.wowhead.com/npc=7442/winterfall-pathfinder
Winterfall Totemic: https://www.wowhead.com/npc=7441/winterfall-totemic
Winterfall Den Watcher: https://www.wowhead.com/npc=7440/winterfall-den-watcher

**What is happening:**
After killing the Winterspring Furbolgs you don´t get the offer to accept the quest.

**What should happen:**
After killing you should get the offer to accept the quest.
![Strange Life Forces - how it should be](https://user-images.githubusercontent.com/18005338/58763560-6df88600-855c-11e9-8403-49e36d3b3e31.png)

**Comment by Rushor** [comment]
![I](https://i.imgur.com/eUD0CAk.jpg)

quest will be force added on kill (if quest is not already active/completed or rewarded)
