### ISSUE TITLE
[Quest} Hellscream's Vigil Borean Tundra

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#2219]
**Links:**
quest 
https://www.wowhead.com/quest=11586/hellscreams-vigil
npc
https://www.wowhead.com/npc=25273/warsong-recruitment-officer

**What is happening:**
warsong recruitment officer doesnt offer this quest

**What should happen:**
warsong recruitment officer shoud offer this quest at lvl 68

**Comment by Dranah** [comment]
You mean 68?
I had no problem getting this quest, but I heard complaints that somebody didn't see it until they picked up the pre q from the Command Board.

**Comment by Chargelol** [comment]
yes u are rigth picked up the pre quest and everthing worked i forgot that u had to do  this in cataclysm
