### ISSUE TITLE
[Quest] Last Chance At Humanity - Worgen Chain

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2220]
https://www.wowhead.com/quest=14375/last-chance-at-humanity

New issue, this worked a couple weeks back
Handing in this quest properly frees you from the woodstock ,but phases you wrongly.
After handing in this quest, all the NPCs vanish and you cannot carry on questing.

How it should work:
After handing in this quest, you should be still seeing the npcs around you, including Lord Godfrey who gives the next quest.

How it works atm:
Cant progress, you are put into an empty phase.

**Comment by lanosantiago** [comment]
I'm having the exact same problem. Should I open a topic too? I'm new to the server, I don't know what I'm suposed to do when someone has already posted my issue.

**Comment by Rushor** [comment]
@Dranah https://www.wowhead.com/npc=36332 This is the questender. but that creatures is not spawned in dev right?

**Comment by Dranah** [comment]
You can hand in the quest. The problem is the phasing that takes effect by this. Handing in the quest to that NPC causes ALL npcs to phase out. They are spawned but you cant see or interact with them. The quest puts you in wrong phase...

**Comment by Rushor** [comment]
phasing adusted for now. need to look into that in more detail

**Comment by Dranah** [comment]
Doesn't work for me.

**Comment by Dranah** [comment]
This is still the break point, confirmed on live. Players get stuck at this point and cant move on.

**Comment by reusssyl** [comment]
I have the same problem.
My chars name is Blathnaid and is standing at the woodstock in Duskhaven. 
I can't write a ticket, because my char isn't lvl 10 yet.
What can i do now?

**Comment by Rushor** [comment]
wow https://i.imgur.com/PNW4xj7.jpg

**Comment by Dranah** [comment]
I still get a wowerror when handing in last stand, but the script properly continues when I log back. NPCs talk, I hand in quest, i am in proper phase. Guess this works.
![WoWScrnShot_061719_201045](https://user-images.githubusercontent.com/31132743/59626373-0174ae00-913c-11e9-8ffd-2faaca6ed265.jpg)
![WoWScrnShot_061719_201104](https://user-images.githubusercontent.com/31132743/59626385-09cce900-913c-11e9-9e2b-237d86bbf310.jpg)

**Comment by Rushor** [comment]
nice!!
