### ISSUE TITLE
[missing quest prereq]  N [81] Last Stand at Whistling Grove 

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2226]
**Links:**

link to the quest thats available too early
https://www.wowhead.com/quest=25940/last-stand-at-whistling-grove

link to quest order for hyjal ( scroll to shrine of assiena
https://wow.gamepedia.com/Mount_Hyjal_quests

**What is happening:**

the quest is available to take too early causing players to cheat the chain and miss out on about 5 - 6 quests before it 

**What should happen:**

the quest should only become available after you complete the previous chains in that zone from the demon NPC  -  https://www.wowhead.com/npc=39933/tyrus-blackhorn
and the Deer NPC -   https://www.wowhead.com/npc=39930/mylune

**Comment by Dranah** [comment]
Should require the following quests to unlock:
https://www.wowhead.com/quest=29066/good-news-and-bad-news
https://www.wowhead.com/quest=25392/oh-deer
https://www.wowhead.com/quest=25382/disrupting-the-rituals
