### ISSUE TITLE
[Quest/Order] Into the Maw! - missing prereq / duplication - Mount Hyjal

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2229]
https://www.wowhead.com/quest=25623/into-the-maw ally 1
https://www.wowhead.com/quest=25618/into-the-maw ally 2
https://www.wowhead.com/quest=25624/into-the-maw horde 1
https://www.wowhead.com/quest=25617/into-the-maw horde 2

1) Both versions of ally quest should have the following prerequisite https://www.wowhead.com/quest=25353/lightning-in-a-bottle handed in before becoming available
2) Both versions of horde quest should have the following prereq https://www.wowhead.com/quest=25355/lightning-in-a-bottle handed in before becoming available
3) There are 2 versions for each faction because of a retail glitch where the original quest giver (the summoned spirit) would disappear early. So they added an identical quest to a permanent NPC. 
These pairs must be identical in a way that when a player **picks** up one, it locks the other.
ID 25623/25618 should be exclusive with each other for ally
ID 25624/25617 should be exclusive with each other for horde
Dropping the quest should make the other quest available to pick again.

Currently its available without any prereq done, and both versions can be picked up and completed.

**Comment by Rushor** [comment]
will add conditions that you cannot see quest a if quest b is taken/rewarded/completed
