### ISSUE TITLE
[NPC] Archaeologist Andorin

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#223]
NPC - https://www.wowhead.com/npc=29650/archaeologist-andorin

This NPC is meant to provide you with Branns communicator if you lose it during your quest chain which I have done therefore I am unable to hand in the following quest: https://www.wowhead.com/quest=12926/pieces-of-the-puzzle
Quest Item - https://www.wowhead.com/item=40971/branns-communicator
![world of warcraft 19_12_2018 23_38_43_li](https://user-images.githubusercontent.com/42302580/50254858-972abd00-03e7-11e9-8292-fe66a9f0fa24.jpg)

**Comment by wow-mania** [comment]
Fixing on both wotlk and cata. :)

**Comment by Echinaceax** [comment]
nice catch @sarahkay88 :)
