### ISSUE TITLE
[NPC] Stillwater Slitherer in Uldum

### ISSUE THREAD

**Issue by Imba232** [WoWManiaUK/Blackwing-Lair#2232]
**Links:**

NPC ID: 46868

**What is happening:**

First of all, there are way too few spawns, like 5 or 6 in the whole lake, there should be way more.
Secondly, skinning them should drop Deepsea Scale, and sometimes they don't even drop anything.

**What should happen:**

More spawns, skinning Deepsea Scale (52982 ID) from them.

**Comment by Rushor** [comment]
55 spawns now, dropchance of Deepsea Scale increased.
