### ISSUE TITLE
[NPC] Dyslix Silvergrub (40358) - Mudsprocket Flight Master - Dustwallow Marsh

### ISSUE THREAD

**Issue by fuzzydunlop** [WoWManiaUK/Blackwing-Lair#2235]
https://www.wowhead.com/npc=40358/dyslix-silvergrub

Similar to the Flight Master in Splintertree Post, this Flight Point won't recognize any other connecting flight points. You **can fly to** Mudsprocket, but you **cannot fly from** it.

**What should happen:** You should be able to fly to all connection flightpoints.

**Comment by Rushor** [comment]
moved to https://github.com/WoWManiaUK/Blackwing-Lair/issues/1826
