### ISSUE TITLE
[QUEST] How to win friends and influence enemies

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Blackwing-Lair#224]
https://www.wowhead.com/quest=12720/how-to-win-friends-and-influence-enemies#comments

When killing the required npc's for the quest, the debuff  "persuading strikes" do not appear, and quest can't be completed. I've tested over 30 npc's on my last try alone and got no debuff. While I don't know debuff appearance itself is RNG, normally when this quest is done NPC's do emote certain things which weren't there today.

What should happen? 
- When player kills the npc's a debuff appears by the name of "Persuading Strikes", this debuff will then trigger an rng and has a chance to complete the quest.

I couldn't find any workarounds, and this is a mandatory quest for a Death Knight as it gives them talent points to match other players.

**Comment by Dranah** [comment]
Perhaps I misunderstood your wording, but the NPC need to stay alive in order to get the debuff. It cannot trigger when the NPC is killed.
Nonetheless, this may need further confirm, since this quest has an awful RNG and some players report of having to kill 50+ mobs even on retail.

**Comment by Dranah** [comment]
Merged into another report. Referenced.
