### ISSUE TITLE
[Quest] Fire the cannon 27661

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2241]
**Links:**

from WoWHead or our Armory
https://www.wow-freakz.com/quest_helper.php?quest=27661&name=fire-the-cannon
**What is happening:**
dying from deathwing when enter zone where npc is
first time I stepped in zone Lord cannon was there standing, and he died in same time as I did when deathwing killed me and he did not spawned since

**What should happen:**
not to die from deathiwng and kill npc

**Comment by sarahkay88** [comment]
#1878
