### ISSUE TITLE
[Quest] Portal Overload 27659

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2242]
**Links:**
https://www.wow-freakz.com/quest_helper.php?quest=27659&name=portal-overload
from WoWHead or our Armory

**What is happening:**
nothing
I have killed all 3 and not counted as objective done, and when I mouse over them, none of them are tagged as objective of quest
also they dont drop anything

**What should happen:**
after slain quest objective should be count as completed

**Comment by sarahkay88** [comment]
#1880
