### ISSUE TITLE
[Quest] Mathias Needs you

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2243]
**Links:**
http://prntscr.com/nx49qm

from WoWHead or our Armory
https://www.wowhead.com/quest=27782/mathias-needs-you
**What is happening:**
quest mark show correct location on map but he is nowhere to be found
and there are bunch of dead but alive mobs that you can kill even they are dead

**What should happen:**
you should turn quest and pick up new quest chain

**Comment by sarahkay88** [comment]
#2206

**Comment by Kitzunu** [comment]
If there are dead but alive mobs you have to report them separately.
