### ISSUE TITLE
[NPC/Mob] Twilight Pyremaw 

### ISSUE THREAD

**Issue by Nestor-21** [WoWManiaUK/Blackwing-Lair#2245]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/npc=51441/twilight-pyremaw
https://fr.wowhead.com/item=52979/ecaille-de-dragon-noircie
**What is happening:**
We can't use skinning skill on Twilight Pyremaw after death.

**What should happen:**
We should be able to use skinning skill on this mob after killing it.

** Could'nt find skinning skill's id **

**Comment by Rushor** [comment]
can you provide a source that this creature should drop that item?

**Comment by HarryRogue** [comment]
https://www.wowhead.com/npc=42824/twilight-pyremaw#skinning
https://www.wowhead.com/item=52979/blackened-dragonscale#skinned-from
30% droprate.

**Comment by mfranca0009** [comment]
Two different entries for Twilight Pyremaw
https://www.wowhead.com/npc=44189/twilight-pyremaw
https://www.wowhead.com/npc=42824/twilight-pyremaw

Fixed skin loot for both

**Comment by Echinaceax** [comment]
confirmed fix in dev of skinning 👍 
https://wowwiki.fandom.com/wiki/Twilight_Pyremaw

![skin](https://user-images.githubusercontent.com/39439201/87569851-094cac00-c6c8-11ea-953e-322396529758.jpg)
