### ISSUE TITLE
[Spell/DK] Runic Empowerment

### ISSUE THREAD

**Issue by gitkulu** [WoWManiaUK/Blackwing-Lair#2246]
**Links:**
https://www.wowhead.com/spell=81229/runic-empowerment
https://www.wowhead.com/spell=47541/death-coil

**What is happening:**
Runic Empowerment doesn't proc from Death Coil at all.

**What should happen:**
Death Coil should have a 45% chance to proc Runic Empowerment.

**Comment by Z4but0m** [comment]
When will this issue be fixed? It's been open for quite a while now and it is severely crippling the effectiveness of Unholy Deathknights. Without the ability to regenerate runes via Death Coil, it leaves them with large periods of deadlock where they can do nothing but autoattack.

**Comment by Dranah** [comment]
This is still not working.

**Comment by Keader** [comment]
Tested in ptr is working.
It stop proc when you have Runic Corruption.
Instead of regen runic, it increase your rune regeneration rate.

**Comment by Dranah** [comment]
Was testing without the talent, nonetheless, it does work now.
