### ISSUE TITLE
[Fishing/NPC]

### ISSUE THREAD

**Issue by wiwicho** [WoWManiaUK/Blackwing-Lair#2247]
**What is happening:**
The Fishing trainer does not let me train a Journeyman skill level, I went to Darnassus and Stormwind and it happen the same thing.

![WoWScrnShot_060219_141737](https://user-images.githubusercontent.com/51299856/58829089-35ac8280-8604-11e9-8917-fbb8ddb54a78.jpg)

**What should happen:**

I should be able to learn Journeyman at level 10, I am already level 21

**Comment by gitkulu** [comment]
@Echinaceax accidentally labeled as daily?

**Comment by Echinaceax** [comment]
> @Echinaceax accidentally labeled as daily?

yip :)

**Comment by sarahkay88** [comment]
NPC identified in ss -https://www.wowhead.com/npc=3607/androl-oakhand#teaches-recipe:0-1+17+2

**Comment by giles1508** [comment]
this issue doesnt seem to be NPC specific but globally on all trainers.  from reports i have had from players they cannot train anywhere at all

**Comment by sarahkay88** [comment]
Yup but has you know every NPC needs it's own report.

**Comment by Echinaceax** [comment]
Yes i agree with @sarahkay88 on this we was told to report all npc and their issue all separately. 
clarification on this would be nice @wow-mania

**Comment by sarahkay88** [comment]
![fishing proof](https://user-images.githubusercontent.com/42302580/60009248-7466b300-966d-11e9-826e-bae20ab54ca4.jpg)
