### ISSUE TITLE
[Quest] Pirate party crasher ID 14115

### ISSUE THREAD

**Issue by Maglubiyet** [WoWManiaUK/Blackwing-Lair#2249]
We need to kill 12 pirates behind the house, but no pirate is available

**Comment by Kitzunu** [comment]
Please follow the Template made to log issues.
You can also read CONTRIBUTION.MD for extra help.

Since this issue is lacking information I will close it until more has been added or until someone else confirms it because there are 34 of them spawned

**Comment by Echinaceax** [comment]
**Links**
npc missing https://www.wowhead.com/npc=35200/pirate-party-crasher
quest https://www.wowhead.com/quest=14115/pirate-party-crashers

**Comment by Rushor** [comment]
phasing issue here

**Comment by Rushor** [comment]
![](https://i.imgur.com/w88Hqfi.jpg)
