### ISSUE TITLE
[QUEST] Noth's Special Brew - 12717- Plaguelands: The Scarlet Enclave

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Blackwing-Lair#225]
Quest requires you to interact with an "cauldron" and it's finished.

 In the server at the moment, when you interact with the "cauldron", nothing happens.

https://www.wowhead.com/quest=12717/noths-special-brew#comments

No workaround could be find, mandatory quest for the DK class.

UPDATE : Completed with GM commands.

**Comment by Dranah** [comment]
This quest is actually optional as it grants no talent points and has no sequels.
Confirmed that Cauldron does not offer to hand in the quest once it is complete, it should give a question mark above the cauldron.
OBJECT ID 190936

**Comment by Kitzunu** [comment]
Fixed
