### ISSUE TITLE
[Quest] Gidwin Goldbraids - ID 27367 

### ISSUE THREAD

**Issue by fuzzydunlop** [WoWManiaUK/Blackwing-Lair#2251]
**Links:** https://www.wowhead.com/quest=27367/gidwin-goldbraids#see-also

from WoWHead or our Armory

**What is happening:** The quest NPC you're supposed to find, Gidwin Goldbraids, is not present. The questionmark to turn in the quest appears on the right location.

**What should happen:** There should be an NPC wrapped in spiderwraps to talk to. As in the video: https://www.youtube.com/watch?v=QX1PS8MVv7I

**Comment by zippoking** [comment]
Also the mobs around Gidwin Goldbraids should be dead, Right now there are alive.

How it is:
![Gidwin Goldbraids - how it is](https://user-images.githubusercontent.com/18005338/58957373-ccae4180-87a0-11e9-9e3b-a53c92f10268.png)

How it should be:
![Gidwin Goldbraids - how it should be](https://user-images.githubusercontent.com/18005338/58957371-ccae4180-87a0-11e9-88ec-f0e21d6ee8a5.png)
