### ISSUE TITLE
Karazhan Chess event

### ISSUE THREAD

**Issue by z1179** [WoWManiaUK/Blackwing-Lair#2253]
**Links:**

from WoWHead or our Armory

**What is happening:**
when reaching the Karazhan chess event encounter in the karazhan raid, Medivh acts as if the event has already been completed however the door to leave is blocked, making it both unable to complete the encounter and progress through the raid.

**What should happen:**
When you enter the room, you should click on your respective faction leaders king piece and that would start the encounter, i dont know the specifics of  how everything works, honestly ALOT of players hate this encounter with a passion and would like it to be skippable ( just google Karazhan chess event skippable and you will see what i mean)

**Comment by Keader** [comment]
Will never happen.
Not even in wotlk it is working.
