### ISSUE TITLE
[Quest] The Battle for Andorhal - ID 28749 - The Cape of Stranglethorn

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2255]
**Links:**
Quest: https://www.wowhead.com/quest=28749/the-battle-for-andorhal
NPC: https://www.wowhead.com/npc=49635/war-mage-erallier

**What is happening:**
You should talk to War-Mage Errallier, but he doesn´t have the text option to open the portal.
![The Battle for Andorhal - how it is](https://user-images.githubusercontent.com/18005338/58896931-5d304780-86f7-11e9-9ebb-a14b3b94f053.png)

**What should happen:**
You should have the text option to open the portal.
![The Battle for Andorhal - how it should be](https://user-images.githubusercontent.com/18005338/58896929-5d304780-86f7-11e9-96f3-4cf7bdaad9ca.png)

**Comment by Rushor** [comment]
same issue for horde and alliance

**Comment by Rushor** [comment]
all fixed.

available with next server update.

![I](https://i.imgur.com/FuQ9OcY.jpg)
![I](https://i.imgur.com/AU1tKuy.jpg)
![I](https://i.imgur.com/zjGO9QV.jpg)
![I](https://i.imgur.com/7tjiHHc.jpg)
