### ISSUE TITLE
[Dunegon] Anzu (druid boss)

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2256]
**Links:**
http://prntscr.com/nxkc2l
http://prntscr.com/nxkdqs

from WoWHead or our Armory
https://www.wowhead.com/npc=23035/anzu#comments

**What is happening:**
it ask for Essence infused moonstone

**What should happen:**
on HC difficulty he should stand there waiting to be killed and drop mount

**Comment by Rushor** [comment]
added in heroic

![I](https://i.imgur.com/0mu1iqa.jpg)
