### ISSUE TITLE
[Quest] The Return of Baron Geddon - ID 25464 - Mount Hyjal - breaks hyjal questline I.

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Blackwing-Lair#226]
What should happen : 
https://www.youtube.com/watch?v=-ESm5mSmxZc as shown in this video, the quest item, when channeled should stack weakness and progress the quest.

What happens: When the item is used the channeling happens, but there is no effect/progression.

Quest ID: 25464
Provided Item ID: 54463
Related NPC: https://www.wowhead.com/npc=40334/baron-geddon-credit#objective-of

**Comment by sarahkay88** [comment]
Also tried to complete this quest and same happened to me.

**Comment by Dranah** [comment]
https://www.wowhead.com/quest=25464/the-return-of-baron-geddon

**Comment by Dranah** [comment]
As it appears, this quest is the break point in the mess of hyjal quest chains and phasing. This Quest must be handed in to unlock the Alysra chain, which then unlocks the chains for goldrinn/aviana etc.
Now, some of those quests are missing prereq and are unlocked anyway, but the phasing is not.

So, within mount hyjal, this quest is the highest priority to fix.

**Comment by Sammy974** [comment]
> So, within mount hyjal, this quest is the highest priority to fix.
> PS: until then it'd be nice to set it to autocomplete

I agree, it's very important, pls fix it somehow. It's impossible to do most of the Mount Hyjal quests without completing this one.

**Comment by Anders98** [comment]
Would love for it to be assigned to a dev.

**Comment by Dranah** [comment]
One does not simply assign a dev. Devs assign themselves. Except @Keader cause he's my sidekick, but he only fix spells,so...

**Comment by Dranah** [comment]
@Kitzunu can we perhaps get an autocomplete temporary?
