### ISSUE TITLE
Jewelcrafting Daylies

### ISSUE THREAD

**Issue by 3JIoudyx** [WoWManiaUK/Blackwing-Lair#2260]
**Links:**
https://www.wowhead.com/quest=25160/a-present-for-lila

Timeless Nightstones Cut (3)
--
Timeless Nightstone (3)

**What is happening:**

When you cut these gems, only second objective is completed.

**What should happen:**

Both objectives should be comleted if these gems were made by you. I haven't tested it yet, but I'm assuming there will be the same problem with 2 similar quests

https://www.wowhead.com/quest=25158/nibbler-no

https://www.wowhead.com/quest=25161/ogrezonians-in-the-mood

**Comment by gitkulu** [comment]
All individual broken JC daylies have already been reported, including this one: #1915

**Comment by sarahkay88** [comment]
#1883

**Comment by Rushor** [comment]
refixed with next update
