### ISSUE TITLE
[Quest] Cursed Talismans - ID 10484 - Hellfire Peninsula

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2261]
**Links:**
Quest: https://www.wowhead.com/quest=10484/cursed-talismans
Item: https://www.wowhead.com/item=30157/cursed-talisman

**What is happening:**
I started the quest and 11 items dropped. The 12th and last item for the quest is just not dropping. There has to be something wrong with my character or with the mobs :-D
Or is this a visual bug and i already have 12 and therefore the items are not dropping anymore?

I killed 39 Grunts + 18 Necrolyten + 56 Peons + 8 Shamans + 26 Tormentor = 129 Mobs in total. According to Wowhead the item has a dropchance from 17% - 25% depending on the mob.
So with 129 Mobs killed, i should get plenty of the talismans.

![Cursed Talisman - Grunt](https://user-images.githubusercontent.com/18005338/58936527-40842600-8770-11e9-984b-8709d3c7b748.png)
![Cursed Talisman - Necrolyte](https://user-images.githubusercontent.com/18005338/58936528-40842600-8770-11e9-8cd6-d18fa156090e.png)
![Cursed Talisman - Peon](https://user-images.githubusercontent.com/18005338/58936529-40842600-8770-11e9-9f20-b1f40376aa9a.png)
![Cursed Talisman - Shaman](https://user-images.githubusercontent.com/18005338/58936530-40842600-8770-11e9-8dff-d6866fba629e.png)
![Cursed Talisman - Tormentor](https://user-images.githubusercontent.com/18005338/58936532-411cbc80-8770-11e9-972e-9da9f0d8a7ad.png)

**What should happen:**
The last cursed talisman should drop

**Comment by Kitzunu** [comment]
WoWHead has some wrong data since they only drop from these NPC's
![image](https://user-images.githubusercontent.com/24550914/58941350-df624f80-877b-11e9-9b17-e512d967476c.png)

I checked DB and they do drop, so there is not much I can do, but I changed the chance for drop to match what it should be

**Comment by zippoking** [comment]
So i leveled another character and by now killed over 200 of the mentioned mobs.
The same situation happens like my other character. I got 11 Talisman and then they just not dropping anymore.

Now here is what i am thinking:
- The first quest you have to do is https://www.wowhead.com/quest=10483/ill-omens. For this quest you have to get 1 Talisman from the mobs!
- After that you are on the quest i reported in here, in which you have to collect 12 Talisman.
- Which means, in total you have to get 13 Talisman. Since they are quest items, and only dropping when you are on the quest, this is what i think is happening:

1 + 11 = 12 Talisman in total (1 from Ill Omens quest and 11 from Cursed Talisman quests)

So i believe the quest is thinking that my character already got 12 Talisman, which then leads them to not dropping anymore.

**Comment by giles1508** [comment]
As I recall that's how it's supposed to work, the first one you get for the previous quest is supposed to count as one,, so your needed to collect 11 more, that's always how it's supposed to be,  so seems like the only issue here is that it's not counting the one you had on previous quest,  which it should

**Comment by zippoking** [comment]
Yeah, i went back to the questgiver and he actually has the yellow question mark above his head, but i can´t turn in the quest. So there is definitely something wrong with the amount of talisman.

![Cursed Talisman - Quest status](https://user-images.githubusercontent.com/18005338/59216661-56547980-8bbc-11e9-918f-4e39d25358a2.png)

**Comment by Kitzunu** [comment]
This quest works perfectly on dev

**Comment by rzenne** [comment]
i'm having the same problem

**Comment by rzenne** [comment]
same issue i'm having. think you need to hand in quest ill omens before accepting this quest on it gets messed up. Abandoned quest and restarted and pretty much got 12 in a row.
