### ISSUE TITLE
[Daily/Quest] Boosting Morale - Tol Barad Peninsula

### ISSUE THREAD

**Issue by gitkulu** [WoWManiaUK/Blackwing-Lair#2263]
**Links:**
https://www.wowhead.com/quest=27972/boosting-morale
https://www.wowhead.com/item=62810/barrel-of-southsea-rum

**What is happening:**
The quest objective map marker is missing, and Barrel of Southsea Rum respawns very slowly,

**What should happen:**
Add the quest objective map marker, and reduce the spawn timer of Barrel of Southsea Rum.

**Comment by Rushor** [comment]
respawn reduced
