### ISSUE TITLE
Aessina quest chain - Mount Hyjal

### ISSUE THREAD

**Issue by r1OG** [WoWManiaUK/Blackwing-Lair#2266]
There is a problem with the "Aessina" quest chain in Mount Hyjal. The problem is that the quest is not obtained in the correct order, making the whole area phase back and forth. I first ran into the issue when completing the quest chain in Shrine of Goldrinn because the quests are not to be completed in the correct order. 

Later on i ran into problems with the quest https://www.wowhead.com/quest=25630 , here the whole chain stopped because the NPC that i'm supposed to deliver the quest to simply is not there due to the phasing. 

**What is happening:**
Problems with phasing due to the quest being completed in the wrong order, making most of the quests to come unobtainable.

**What should happen:**
The quest is to follow its chain, securing the correct phasing.

**Comment by giles1508** [comment]
Issue has already been raised, there is a report for each individual quest before,  but thanks for pointing this out
