### ISSUE TITLE
[Quest] Heroes of Darrowshire - ID 27388 - Eastern Plaguelands

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2268]
**Links:**
Quest: https://www.wowhead.com/quest=27388/heroes-of-darrowshire
Carlin Redpath: https://www.wowhead.com/npc=11063/carlin-redpath
Item: https://www.wowhead.com/item=13202/extended-annals-of-darrowshire

**What is happening:**
There is no text option for Carlin Redpath. He should give you the annals of darrowshire. Quest cannot be completed.
![Heroes of Darrowshire - how it is](https://user-images.githubusercontent.com/18005338/58959701-e605bc80-87a5-11e9-9027-48c08417692e.png)

**What should happen:**
There should be a text option, that you get the annals of darrowshire.
![Heroes of Darrowshire - how it should be](https://user-images.githubusercontent.com/18005338/58959699-e605bc80-87a5-11e9-8e0d-8fff271f6702.png)

**Comment by Rushor** [comment]
item added

![I](https://i.imgur.com/fiKn1hA.jpg)
