### ISSUE TITLE
[Blood Elf Models] Blood Elf Hair/Character Select

### ISSUE THREAD

**Issue by todd0168** [WoWManiaUK/Blackwing-Lair#227]
When creating Blood Elf female, there are four of the hairstyle options that produce a bald character.
<img width="1824" alt="screenshot 2018-12-20 00 24 16" src="https://user-images.githubusercontent.com/3512819/50272851-eaa00980-03ed-11e9-9a34-69c25b8aac2c.png">

**Comment by Dranah** [comment]
Same for blood elf males, and in-game, several NPCs appear with a strangely colored blackish hair instead of their usual color.

**Comment by wow-mania** [comment]
Duplicate. We will not going to be looking at this now. It will be part of the HD texture optional patch.
