### ISSUE TITLE
[Herbalism] Cataclysm herbalism

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2270]
**Links:**
http://prntscr.com/ny06n5

from WoWHead or our Armory

**What is happening:**
Herbalism need tweaking, atm hyper farming is crazy.
I dont know is it same for mining, but herbs are respawed within 2min or less,
and there is no limit how many herbs should be spawned in zone.
You can camp 6-9 herb spots and gather them in circle without break maximizing gathering output
or you can afk farming 1 herb every 2 min or less without moving.

**What should happen:**
Herbs should have more spawn points
https://prnt.sc/ny0d6b
vs
http://prntscr.com/ny0dn7

lets say that even spawn points are enough.
spawn time of herbs might be also alright, but there should be limited amount of herbs spawned in zone. 
When NOBODY is farming, you can enter zone without collecting herbs, you will find every single herb spawned.

I dont know ratio how should be set, but I know that if I gather only 1 herb, chances to that same herb is respawned should be really low, I should farm half map before first herbs I gathered should have chance to be respawned.

I know that druids have adventage and they can gather more than others, but 50 stacks per 1 hour is insane...

I had herbalsim on shaman and I never had more than 20 stacks with focused hyper farming in 1 hour, I had to mount/dismount, and I pull crap that I have to kill before I can mount again,
Even then I thought it is weird that spawn time. Many people laugh and said how they farm much more than me, at first I did not beleive, but now I am sure that it is broken AF.

I could not find similar reports to this.

**Comment by giles1508** [comment]
Spawn rate slightly down and spawn points slightly up, that will fix it
Some areas of the map there is never any herbs when there should be spawn points all over,  so yeah drop the spawn rate and up the spawn points

**Comment by gitkulu** [comment]
It is the same with mining.

**Comment by Dranah** [comment]
Some herbs even repop after 10seconds. This is gonna ruin economy.

**Comment by TheSale** [comment]
Just to explain how fix should be implemented here, I think there is nothing wrong with the timers, but spawn points and amount of herbs that should be available on the map at any time.

![uxlQq23NRmqZ8Bt6hxYk1w](https://user-images.githubusercontent.com/20323863/59569565-b00ce600-908b-11e9-9f34-3e02c69963ae.png)
on this SS I have marked 6 herbs as example.

Let say that herbs F D and C are spawned and A B and E are not. ratio 50/50
IF I collect F herb, new herb should spawn on random location of A B E and also F (but chance is low)

if new herb spawned on B location, normally I could camp F herb entire day and it should not be spawned or have chance to be spawned until new herb is collected.

also regarding wowhead database there should be 777 spawn points in Twilight highlands
![twitwi](https://user-images.githubusercontent.com/20323863/59569658-09294980-908d-11e9-9dc3-741ecb85f7f8.png)

with 777 spawn points it would be insane to have spawn timers for all herbs, or after server reset that all 777 herbs are spawned, it should never work like that. There should for example in 777 sample only 50 herbs available at any time, with 10 sec spawn timer, but new herb can be spawned on the oposite side of the map, so you need to fly entire zone, and not just circle

![tjasm](https://user-images.githubusercontent.com/20323863/59569729-eba8af80-908d-11e9-8c59-8aadaa40609e.png)
vs
![loop](https://user-images.githubusercontent.com/20323863/59569746-2c082d80-908e-11e9-97ce-bc14924977e1.png)

I took twilight highlands only as example, issue is in all cata zones
and with mining also

**Comment by gitkulu** [comment]
Right now using Gatherer HUD almost feels like a radar hack.

**Comment by Rushor** [comment]
it's called pooling :D 

I added it for the deposits and mining in the last days.

can someone tell me all the herbalism objects in cata?

**Comment by zippoking** [comment]
Azshara’s Veil http://www.wowhead.com/item=52985
Cinderbloom http://www.wowhead.com/item=52983
Heartblossom http://www.wowhead.com/item=52986
Stormvine http://www.wowhead.com/item=52984
Twilight Jasmine  http://www.wowhead.com/item=52987
Whiptail http://www.wowhead.com/item=52988

**Comment by Drostthehunter** [comment]
https://www.wowhead.com/object=202749/azsharas-veil
https://www.wowhead.com/object=202747/cinderbloom
https://www.wowhead.com/object=202751/twilight-jasmine
https://www.wowhead.com/object=202748/stormvine
https://www.wowhead.com/object=202752/whiptail
https://www.wowhead.com/object=202750/heartblossom

**Comment by Rushor** [comment]
alright thanks guys

**Comment by Rushor** [comment]
affected zones 

616 hyjal
4815 Kelp'thar Forest
4922 Twilight Highlands
5034 Uldum
5042 Deepholm
5144 Shimmering Expanse
5145 Abyssal Depths
5146 Vashj'ir
5389 Tol Barad

**Comment by Rushor** [comment]
With next update we will also have pooling for all herb spawns in the cata level 80-85 zones for Mount Hyjal (616)'),
Kelp''thar Forest (4815)'),
Twilight Highlands (4922)'),
Uldum (5034)'),
Deepholm (5042)'),
Shimmering Expanse (5144)'),
Abyssal Depths (5145)'),
Vashj''ir (5146)'),
Tol Barad (5389)');

**Comment by Rushor** [comment]
tbc-cata seems to be fine. but low zones need to be checked

https://legacy-wow.com/herbalism-1-300/
