### ISSUE TITLE
[Spell] Research of glyphs fail

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2275]
**Links:**

from WoWHead or our Armory

**What is happening:**
By researching new glyphs using
- Northrend Inscription Research 61177
- Minor inscription Research 61288
- Book of Glyph Mastery 45912

some times fail to research glyph, as some people who had same issues told me,
there might be chance that using research, it attempt to learn glyph that we already know and it fail to learn one that we dont know.

**What should happen:**
It should always give new glyph till point we learned all glphs.

**Summary**
Glyph research is crucial and very important, there is no other way learning new glyphs, only 1 time per day or via [Book of Glyph Mastery], which is from previous expansion, and drop rate is very low, so obtaining will be really difficult, we need 40 books to learn all glyphs (that can be learned trough books)
failing on that or on any other research is not reasonable.

**Suggestion**
Increase slightly drop rate from crazy 0.5% to something sane like 3-5%
other opinions are welcome of course

someone add links please I failed to obtain

**Comment by gitkulu** [comment]
I don't know if the discovery chance is too low, but it definitely isn't supposed to be 100%.
And no need to up the drop rate of Book of Glyph Mastery, let's keep things blizzlike.

**Comment by TheSale** [comment]
I agree it should not be 100% but it should be very high chance

http://prntscr.com/nybz9t
today failed to discover new major glyph

@gitkulu I agree and disagree, we should not be overwhelmed with books, however, on retail there was different situation. first you upgrade your existing chars from wotlk to cata, that mean that there are a lot people with maxed insc and all glyphs discovered, and books stashed in banks, on alts or in guild banks

also on retail where is x1 xp rate people have to spend much more time leveling and killing nobs, doing quests, where they had a decent chance finding book, that ether is used, sold on ah, or stashed.

profession leveling is also different, on retail let say tailoring and enchanting, you need to kill a lot mobs to get cloths or greens so you can level up profession, here is much less since skill up is x2. So less time spent in northrend less chance to get book.
and also it was just a suggestion

**Comment by Sammy974** [comment]
I can confirm that. Some days ago my Northrend Inscription Research didn't discover anything. I'm aware the tooltip says "very likely" and not "sure", but it never happened to me in wotlk private shards and in cataclysm official servers. I was waiting it to happen again, before to report it, but... here we are :)

**Comment by giles1508** [comment]
I've had inscription on a number of chars on all expansions since wotlk and I've never ever had a research or glyph book fail,  I didn't even think it was possible to fail,  I for one belive it's broken... In the last few days I've had 1 Northend research work out of 4 days.... That's no where near right... I'm not on my pc atm, but I'll check different sources to find out

**Comment by sarahkay88** [comment]
https://wow.gamepedia.com/Northrend_Inscription_Research
https://wow.gamepedia.com/Minor_Inscription_Research
https://wow.gamepedia.com/Book_of_Glyph_Mastery -quote: During Wrath of the Lich King, this book represented a gate which made many of the most desirable glyphs available from a limited (but growing) number of scribes. Now that Northrend is just a waystation on the road to Cataclysm, the supply of these books is reduced but many of the glyphs it teaches are still "must-have" items.

**Comment by Sammy974** [comment]
Please, check the northrend inscription research! My research failed 2 days in a row... (yesterday and today) that's sooo bad because i'm the only one capped inscriber in my guild and books are so hard to find!

**Comment by TheSale** [comment]
yesterday again Northrend Inscription Research failed....

**Comment by sarahkay88** [comment]
#2430

**Comment by TheSale** [comment]
again research failed today
http://prntscr.com/o39okv

**Comment by gitkulu** [comment]
In about 40 researches it failed to discover something new 2 times for me.

**Comment by giles1508** [comment]
Research isn't 100% same as minor, the only thing that's 100% is books

**Comment by giles1508** [comment]
Northrend Inscription Research allows a scribe to discover major glyphs. It is learned at an Inscription skill of 385 for 10g. The cooldown resets at midnight, server time. As the tool tip indicates, it is very likely, but not guaranteed, to discover new recipes.[1][2] The chance to discover something (given you still have recipes to discover) seems however to be rather high.[3] It also produces a stack of 1 to 3 random high level Scrolls or Vellums. When you have discovered everything, you will only get scrolls and vellums.

**Comment by giles1508** [comment]
I've had 4 days in a row without a fail,

**Comment by TheSale** [comment]
http://prntscr.com/o5l04w
fail again today minor worked major failed

**Comment by 3JIoudyx** [comment]
It definitely does not work right, I've had 2 Northrend research fails in a row even though I've discovered 30-40% of all possible glyphs.

**Comment by giles1508** [comment]
I've had 1 fail in the last 9 days, it's not 100% chance to learn something,  it's just bad RNG,  but without knowing blizzards actual fail chance for it, you can't really know

**Comment by TheSale** [comment]
http://prntscr.com/o69zf5 before
http://prntscr.com/o69zsv after
again fail minor learned major failed

**Comment by TheSale** [comment]
http://prntscr.com/o7agvt
again major failed

**Comment by TheSale** [comment]
http://prntscr.com/o7ud0z
again failed

**Comment by Sammy974** [comment]
BTW books are not 100% because I got 11 and 1 failed. So books can fail too...

**Comment by Rushor** [comment]
Northrend Inscription Research 61177
    Minor inscription Research 61288
    Book of Glyph Mastery 45912

some spells were useless there and some had to be added. made a few corrections for that (db related). everthing else is up to you Keader :>

**Comment by Druhl** [comment]
I can confirm chance appears to be 0% on some glyphs or when very few remain to be discovered.

My inscription char (Makkar) has skill 297 and one remaining glyph to discover from Minor Inscription Research (https://www.wowhead.com/item=77101/glyph-of-shadow - lvl 105). I have for sure done 20 to 30 runs of MIR without discovery of this glyph.
