### ISSUE TITLE
[Quest] Add'em to the pile - ID 27539 - (issue 2) Eastern Plaguelands

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2279]
**Links:**
Quest: https://www.wowhead.com/quest=27539/add-em-to-the-pile
Item: https://www.wowhead.com/item=61372/stinking-skull
Scourge Soldier: https://www.wowhead.com/npc=8523/scourge-soldier
Cursed Mage: https://www.wowhead.com/npc=8524/cursed-mage

**What is happening:**
The Scourge Soldier and Cursed mage are not dropping the stinking skull.
I kill several of them but not a single item dropped.
![Scourge Soldier](https://user-images.githubusercontent.com/18005338/58989296-f2a90580-87e3-11e9-8ba7-febdad585663.png)
![Cursed Mage](https://user-images.githubusercontent.com/18005338/58989306-f63c8c80-87e3-11e9-9606-64c5cbd5c528.png)

**What should happen:**
The stinking skull should drop from the two mentioned mobs.

**Comment by sarahkay88** [comment]
#429
