### ISSUE TITLE
[Quest] Encrypted Letter - ID 3102 - missing - Northshire

### ISSUE THREAD

**Issue by caden684** [WoWManiaUK/Blackwing-Lair#228]
What should happen: https://youtu.be/Hk1gdnFpA9c?t=210

What happens: as shown in this video, (at the 3:30 mark) after turning in the quest "Beating Them Back!" and "Lions For Lambs", you should get then get a quest called "Simple Letter" or something of the sort for your class, but I get no quest in return as a rogue.

(Quest1)Beating them Back!: https://www.wowhead.com/quest=28757/beating-them-back
(Quest2)Lions for Lambs: https://www.wowhead.com/quest=28759/lions-for-lambs
(Quest3)Simple letter: https://www.wowhead.com/quest=3100/simple-letter

**Comment by Dranah** [comment]
Simple Letter is a warrior quest.
This is the rogue version:
https://www.wowhead.com/quest=3102/encrypted-letter

**Comment by Rushor** [comment]
rogue first [15:32:36]28764 - [Beating Them Back!]  [active]

rogue second [15:33:10]28772 - [Lions for Lambs]  [active]

in db all looks fine so far hmm

**Comment by Kitzunu** [comment]
This is weird, I have checked everything and it looks okay in DB.
But it does not give the quest in-game

**Comment by Kitzunu** [comment]
@Rushor Got any ideas?

**Comment by Rushor** [comment]
yes really weird

**Comment by Rushor** [comment]
will fix it with sai for now. on reward -  add quest

**Comment by Rushor** [comment]
okay reason AllowableRaces was wrong https://i.imgur.com/2AGPuUf.jpg
