### ISSUE TITLE
[Spell/pala] Retribution vs Global cooldown via Crusader Strike

### ISSUE THREAD

**Issue by Geniuskp** [WoWManiaUK/Blackwing-Lair#2281]
**What is happening:**
You can t see the global cooldown after using crusader strike 
https://imgur.com/a/ih9z1mj
that s my bar when I use crusader strike
**What should happen:**
https://imgur.com/a/PzPIz99
that s my bar after I use other spells  <that should happen>
Kinda annoying for us to play ret; especially when u are in burst and  spam crusader templar

**Comment by Slydee23** [comment]
can confirm

**Comment by Keader** [comment]
Fixed.
