### ISSUE TITLE
Can't leave Kezan because of bugged quests

### ISSUE THREAD

**Issue by Akinlou** [WoWManiaUK/Blackwing-Lair#2284]
**Links:**

from WoWHead or our Armory

**What is happening:**

Both "Off to the Bank" and "Fourth and Goal" quests can't be completed.

**What should happen:**

In "Off to the Bank" you can't buy the needed item to complete the quest and in "Fourth and Goal" quest the Bildgewater Buccaneer doesn't spawn to you get in and complete the quest.

Without these two quests you can't progress ingame to leave the starting zone.

**Comment by Echinaceax** [comment]
Already been reported https://github.com/WoWManiaUK/Blackwing-Lair/issues/1849 and

**Comment by Akinlou** [comment]
There are two bugged quests not just "Fourth and Goal"

**Comment by Echinaceax** [comment]
> There are two bugged quests not just "Fourth and Goal"

Yes i know :)

**Comment by Rushor** [comment]
will check

**Comment by Rushor** [comment]
In Off to the Bank you get the items https://www.wowhead.com/item=47044/stack-of-macaroons as reward after turing in the quest (added that)

**Comment by Rushor** [comment]
Fourth and Goal will be fixed and handled in https://github.com/WoWManiaUK/Blackwing-Lair/issues/1849

**Comment by Akinlou** [comment]
The problem in Off to the Bank is that you can't get the items from the 3 NPC's to complete the quest

**Comment by Echinaceax** [comment]
> The problem in Off to the Bank is that you can't get the items from the 3 NPC's to complete the quest

please make a Fourth and Goal (issue 2) report for that second issue. thanks

**Comment by Echinaceax** [comment]
> The problem in Off to the Bank is that you can't get the items from the 3 NPC's to complete the quest

fixed here #848
