### ISSUE TITLE
[Profession] Profession Bugs When Boosting Professions with Maniac Points

### ISSUE THREAD

**Issue by Unanimouss** [WoWManiaUK/Blackwing-Lair#2285]
**Links**
https://imgur.com/a/poZjQKG
https://imgur.com/a/DIxC1sh

**What is happening:**
When I Boosted my Jewelcrafting Profession It Only Went to 450, And now i am stuck at 450 **_Without the "Jewelcrafting" Spell In My Spell Book in the Profession Category._** When I Go To The Jewelcrafting Trainer It Says I Can Learn "Apprentice Jewelcrafter" For 9 Copper (Which is for Level 1-75) But the "Train" Button and The bottom Right Corner Is Grey And Un-able to Press.

**What should happen:**
I Should Be Level 525 Jewelcrafting with all recipes unlocked. Have the "Jewelcrafting" Spell In My Spell Book after spending 300 Maniac Point at the NPC "Jacob Maniac" At the WoW-Reign Mall

- [x] Issue 1 solved (450 only with boost)
- [ ] Profession Window bugs after you boost

**Comment by wow-mania** [comment]
Prefessions are boosted only to 450. That is how it is.

**Comment by giles1508** [comment]
Issue still remains that after boosting to 450 he doesn't have the skill in his profession window, yes there's nothing that can be done to increase to 525,  but he still doesn't have the skill in his profession window? Don't know if this is still an issue as it was 7 days ago,  but it seems the main point of the post was overlooked?

**Comment by WhitephoenixTheBunny** [comment]
This is as Mania. The boost is only to unlock the skill 450/0
You will NEED visit trainer to get the skill and learn recipe.

About not being boosted till 525, that's Janitor decision :P

**Comment by giles1508** [comment]
Again not what I said ;).  I said the problem is that the profession is not visable in the profession window, would also be nice if the player could confirm if its now working or not

**Comment by Unanimouss** [comment]
Yeah I had to speak to janitor and he had to personally meet me in game to grant me the ability,

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kDracku** [comment]
I got the same problem with lw , i boosted with mp and it dosent show on proff tab. https://imgur.com/9Kg8IbO

**Comment by Echinaceax** [comment]
> Again not what I said ;). I said the problem is that the profession is not visable in the profession window, would also be nice if the player could confirm if its now working or not

Still an issue, Dracku will comment soon

**Comment by Echinaceax** [comment]
@wow-mania @Rushor 
Seems to be 2 issue questions at the start and this go overlooked as invalid.
look above from dracku now, not the original poster thanks

**Comment by Rushor** [comment]
added position change of lering the spells. should work now

![I](https://i.imgur.com/Hq7Apzp.jpg)
