### ISSUE TITLE
[Quest] The hidden Clutch - ID 27832 - missing npc (Rhea again)- Badlands

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2289]
**Links:**
Quest: https://www.wowhead.com/quest=27832/the-hidden-clutch
NPC: https://www.wowhead.com/npc=46654/rhea

**What is happening:**
Rhea is not at her position. She should be in the hidden clutch, as the name of the quest suggests.
![The hidden clutch - how it is](https://user-images.githubusercontent.com/18005338/59067015-ba232d80-88b0-11e9-9730-bd4f9d181ef0.png)

**What should happen:**
For this quest to end she should be at 16.0/33.4
![The hidden clutch - how it should be](https://user-images.githubusercontent.com/18005338/59067014-ba232d80-88b0-11e9-94d6-53472d8bef41.png)

**Comment by Rushor** [comment]
creature added at that position

**Comment by Kitzunu** [comment]
Oh I totally forgot about this one lol
