### ISSUE TITLE
[NPC] Adarrah missing -  Hero's Call: Uldum!

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Blackwing-Lair#229]
Quest ID: 28558
Upon accepting the quest, the required NPC can't be found at Tanaris.

To reproduce, take the quest from any Hero's Call board and go to the tagged loaction.

NPC ID: 44833

**Comment by sarahkay88** [comment]
![world of warcraft 21_12_2018 18_04_29](https://user-images.githubusercontent.com/42302580/50356718-f8b76c80-054a-11e9-89dd-d12dc1ef976e.png)Also attempted to do this quest and the NPC is missing

**Comment by Saintres** [comment]
Tried to do the quest today and still no NPC to find in Tanaris

**Comment by Echinaceax** [comment]
for horde Also
