### ISSUE TITLE
[Quest] Stocking up ID 28177 - A Future Project ID 28178 - Mud Hunter 28179 - Burning Steppes

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2292]
**Links:**
Quest: https://www.wowhead.com/quest=28177/stocking-up
Quest: https://www.wowhead.com/quest=28178/a-future-project
Quest: https://www.wowhead.com/quest=28179/mud-hunter
NPC: https://www.wowhead.com/npc=47811/john-j-keeshan

**What is happening:**
If you take one of the three quests John J. Keeshan is offering you, then the other 2 become unavailable. 
![John F  Keeshan - how it is 1](https://user-images.githubusercontent.com/18005338/59091843-76601080-8910-11e9-9d45-12e12bc895f0.png)
![John F  Keeshan - how it is 2](https://user-images.githubusercontent.com/18005338/59091841-76601080-8910-11e9-8620-221a2578f543.png)

**What should happen:**
According to wowhead the three quests should be doable at the same time.
![John F  Keeshan - how it should be](https://user-images.githubusercontent.com/18005338/59091842-76601080-8910-11e9-9aa8-be4a70911f88.png)

**Comment by zippoking** [comment]
I still can only accept one quest, for me this issue is still not fixed.

**Comment by zippoking** [comment]
Next round: I still can only accept one quest and not all three.
![John F  Keeshan - how it is 5](https://user-images.githubusercontent.com/18005338/60401583-16156500-9b84-11e9-84eb-a49c0d211270.png)

**Comment by Kitzunu** [comment]
fixed
