### ISSUE TITLE
[NPC] Lunk (issue 2) Searing Gorge

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#2295]
**Links:**
https://github.com/WoWManiaUK/Blackwing-Lair/issues/2093#issuecomment-499680310

copied from other post as it was added to close issue of the quest on above link reported by @zippoking

![Lunk spawns automatically 1](https://user-images.githubusercontent.com/18005338/59068739-3ddf1900-88b5-11e9-8029-8319e8873b4d.png)
![Lunk spawns automatically 2](https://user-images.githubusercontent.com/18005338/59068740-3ddf1900-88b5-11e9-8ada-bc81d5404679.png)

**What is happening:**
- Over spawning
- it seems that Lunk spawns for everyone and not for the specific player
- He spawns multiple times. (every single time you kill a spider for another quest)

**What should happen:**
Should only be 1

**Comment by Kitzunu** [comment]
```sql
SELECT * FROM smart_scripts WHERE entryorguid = 5856;
```

**Comment by Kitzunu** [comment]
@Rushor If you know a better way of doing it feel free to take over.

but for the moment I added Glassweb Spider - On Just Died - Force Despawn Creature \'Lunk\' before
Glassweb Spider - On Just Died - Summon Creature \'Lunk\'
