### ISSUE TITLE
[Quest] Healing the Wounded

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#23]
QuestID 26919
Here's a video that shows the quest:
https://www.youtube.com/watch?v=L6K0SgtbbYg
Human starter priest quest. Part of the chain so you cannot carry on without completion.

Very similar issue to Rejuvenating touch. https://github.com/WoWManiaUK/Blackwing-Lair/issues/17
How it works atm: Does not give credit when using flash heal on the target npcs. Quest cannot be completed.

**Comment by Dranah** [comment]
Works as intended now.

**Comment by Echinaceax** [comment]
I have same issue with my priest
- Doesnt work as intended for me 

![heal the wounded](https://user-images.githubusercontent.com/39439201/51131308-a4449b80-182f-11e9-8922-be8ceba2cd17.jpg)

![healed](https://user-images.githubusercontent.com/39439201/51131513-3c428500-1830-11e9-9ab7-2ed8a3752df3.jpg)


- Healed but dont get credit 
- cant complete this priest task
- Side note i still got the flash heal spell though from trainer

**Comment by Dranah** [comment]
This is a different quest ID, despite the similar name. Please open new report.

**Comment by Echinaceax** [comment]
i would if i could actually find it...ive searched wowhead and there is no mention of it
