### ISSUE TITLE
[Quest] It's Never Over - ID 26616- Redridge Mountains

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#230]
Quest - https://www.wowhead.com/quest=26616/its-never-over
Npc - https://www.wowhead.com/npc=43184/john-j-keeshan

After accepting this quest you should be able to get a river boat to Everstill camp but there is no boat appearing to transport you to camp 

![microsoft edge 20_12_2018 14_58_08](https://user-images.githubusercontent.com/45798884/50292234-7b1b3000-0468-11e9-9bf9-7d6a26244968.png)
this shows the boats location from retail 

![world of warcraft 20_12_2018 14_59_00](https://user-images.githubusercontent.com/45798884/50292271-90905a00-0468-11e9-8321-806f00160c37.png)
this is the PTR looking at same location

**Comment by Saintres** [comment]
Accepted this quest today too but no boat
3 Feb. -19

**Comment by Rushor** [comment]
will add a simple path script for it for now
