### ISSUE TITLE
[Talent/Warlock] Improved Soufire - no damage increase

### ISSUE THREAD

**Issue by marcwr1** [WoWManiaUK/Blackwing-Lair#2301]
**Links:**

http://cata-shoot.tauri.hu/?spell=18120

**What is happening:**

The Buff 'Improved Soulfire' doesnt get activated via Soulfire

**What should happen:**

Your Fire and Shadow dmg should increase by 8 % for 20 sec. after using Soulfire.

**Comment by Dranah** [comment]
No proc still.
