### ISSUE TITLE
[Item] Bloodstone Teleporter - ID 203752 - not working - Blasted Lands

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2303]
**Links:**
Object: https://www.wowhead.com/object=203752/bloodstone-teleporter
Object: https://www.wowhead.com/object=203753/bloodstone-teleporter
Quest: https://www.wowhead.com/quest=26158/attune-the-bloodstone

Don´t know which object, maybe even both, since they are connected?!? The mentioned quests unlocks the teleporter. So i believe after finished the quests you can use the teleporter as often as you want.
Horde version was already reported in #666

**What is happening:**
If you click the teleporter, nothing happens. 
![Bloodstone Teleporter inside - how it is](https://user-images.githubusercontent.com/18005338/59130180-016ff380-896f-11e9-8763-3209aae5b240.png)
![Bloodstone Teleporter outside - how it is](https://user-images.githubusercontent.com/18005338/59130181-016ff380-896f-11e9-9bf0-396323fc1e50.png)

**What should happen:**
If you click the bloodstone teleporter, you should get teleported in and out the cave.

**Comment by Rushor** [comment]
will now teleport you

![I](https://i.imgur.com/6MFQS4H.jpg)
