### ISSUE TITLE
[Daily/Quest] Cannonball! - Tol Barad Peninsula

### ISSUE THREAD

**Issue by gitkulu** [WoWManiaUK/Blackwing-Lair#2304]
**Links:**
https://www.wowhead.com/quest=27987/cannonball
https://www.wowhead.com/object=206586/stack-of-cannonballs

**What is happening:**
The quest objective map marker is missing, and Stack of Cannonballs respawns very slowly.

**What should happen:**
Add the quest objective map marker, and reduce the spawn timer of Stack of Cannonballs.

**Comment by Echinaceax** [comment]
- [ ] Map marker (fixed)
- [ ] Spawn timer (still slow) though 

noticed something 
- [ ] cannonballs are clickable even with completed quest and without the quest at all. this can add more issue to players waiting for them to spawn 

shouldnt be clickable after 4/4 
and without the quest needed

**Comment by Rushor** [comment]
spawntimer reduced to 60 sec and flags added so that the object can only be lootet if quest is active.

![I](https://i.imgur.com/Qt84FgY.jpg)
![I](https://i.imgur.com/xmtlUKR.jpg)
