### ISSUE TITLE
[Item] Rod of Compulsion - Dragonblight

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2307]
**Links:**
https://www.wowhead.com/quest=12273/the-denouncement
from WoWHead 

**What is happening:**
The rod doesn't work, it doesn't have any effect on the target and the quest can't be completed.

**What should happen:**
First attack the target, while in combat use the rod on the target and he'll glow with a green light. Then kill the target to complete the quest.
https://www.youtube.com/watch?v=7AOMM3HTfrQ

**Comment by sarahkay88** [comment]
item is - https://www.wowhead.com/item=37438

**Comment by Chargelol** [comment]
dit this quest few days ago took alot of trys to complete most of time item doesnt work

**Comment by Rushor** [comment]
you need to be very close to the target. increasing the spellrange should solve it
