### ISSUE TITLE
[Dungeon/NPC] Howling Gale - Vortex Pinnacle

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2309]
https://www.wowhead.com/npc=45572/howling-gale

These guys are a knockback obstruction you have to get past in Vortex Pinnacle.

**How it should work:**
These should be targetable and attackable and attacking them with a direct attack should cause their spinning wind to allow players to pass and not knock them.

How it works atm:
They cant be targeted or attacked and therefore players cannot pass. It makes the dungeon impossible to complete.

**Comment by Dranah** [comment]
Temporary fix applied and pushed to live. We sorta just removed the knock for now, will finetune it to work blizz like later.

**Comment by Dranah** [comment]
Fix was somehow reverted. Please recheck.

**Comment by wow-mania** [comment]
Works on dev.
Just do DOE on the area.

**Comment by Dranah** [comment]
Fix is now the blizzlike effect, you can hit the storms and it turns off their knockback for a while.
I hope it will be deployed tomorrow without further issues.
