### ISSUE TITLE
[Quest/Order] The Wormwing Problem - 25655 - Mount Hyjal

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#231]
Quest - https://www.wowhead.com/quest=25655/the-wormwing-problem
NPC - https://www.wowhead.com/npc=41006
 
Can see the mobs whilst in the circle but once I leave they are phased out,,, I had to get Phoenix to phase me but she also said to report it on here

![world of warcraft 20_12_2018 14_55_38_li](https://user-images.githubusercontent.com/42302580/50293073-a0a93900-046a-11e9-89b1-8234b0495d7a.jpg)
![Uploading World of Warcraft 20_12_2018 14_55_43_LI.jpg…]()

**Comment by sarahkay88** [comment]
![world of warcraft 20_12_2018 14_55_43_li](https://user-images.githubusercontent.com/42302580/50293110-b3237280-046a-11e9-9723-523c158bd6ff.jpg)

**Comment by Icytalon** [comment]
problem still exist until now phasing area preventing many quests to be complete no Wormwing Screecher
and no Eggs when get closer to the area

**Comment by Dranah** [comment]
May be the result of wrong quest order / broken quest skipped in one of the prequel chains.
May also be the NPCs simply being wrongly phased. Will leave as pending until the quest chains are put in order.

**Comment by Saintres** [comment]
Tryed to do the quest today and its still same  issues abowe

**Comment by Dranah** [comment]
This quest should not be unlocked before completing "return to nordrassil" ID 25578
The phasing will be looked at once the quests are in proper order.
