### ISSUE TITLE
[Dungeon/NPC] Blackheart the Inciter - [SPELL] Incite Chaos

### ISSUE THREAD

**Issue by georgeapostolov** [WoWManiaUK/Blackwing-Lair#2313]
**Links:**
https://www.wowhead.com/npc=18667/blackheart-the-inciter
https://www.wowhead.com/spell=33676/incite-chaos

**What is happening:**
When he casts Incite Chaos, all party members get charmed and stuck in place. Fight resets, boss is at 100% health.

**What should happen:**
All party members should get charmed and fight each other, fight is over after boss is dead.

**Comment by Rushor** [comment]
will temp remove that event until charmai is fixed
