### ISSUE TITLE
[Talent/Mage] Hot Streak & Improved Hot Streak

### ISSUE THREAD

**Issue by gitkulu** [WoWManiaUK/Blackwing-Lair#2314]
**Links:**
Hot Streak talent: http://cata-shoot.tauri.hu/?spell=44445
Improved Hot Streak talent: http://cata-shoot.tauri.hu/?spell=44448
Hot Streak proc buff: https://www.wowhead.com/spell=48108/hot-streak

**What is happening:**
The Hot Streak talent does not work at all when you have also taken the Improved Hot Streak talent. It essentially makes the fire spec useless until you get a VERY high amount of crit.

**What should happen:**
Critical strikes from Fireball, Frostfire Bolt, Scorch, Pyroblast and Fire Blast should have a (0,85 - 2x mage critical strike chance)% chance to proc Hot Streak (according to @Dranah in #38), even after taking the Improved Hot Streak talent.

**Comment by Dranah** [comment]
Doesn't work. Hot Streak doesn't proc, neither taken alone, neither together with imp HS.
I tested with 1% crit chance, it should have 83% chance to proc on crits, I crited 12 times out of 1000 casts, not a single proc.
Tested also with 80% crit, also no proc, so it wasn't wired the wrong way.

PS: the improved hot streak procs work fine on consecutive crits as always

**Comment by Dranah** [comment]
Errr, Hot streak procs must happen with the formula-calculated chance when the mage crits.
Currently, they happen on every landed spell, not only crits. Need revert asap.

**Comment by Keader** [comment]
Sended fix to Janitor (updated on Live) and i executed in PTR.
Please do .reload spell_proc if you are on, or wait until next reset.

**Comment by Dranah** [comment]
fix works on ptr
need to apply to live asap

**Comment by Hespericless** [comment]
This seems to still be bugged in live

**Comment by Hespericless** [comment]
Apparently, when you spec on fire and don't take the improved Hot Streak talent, normal HS procs perfectly, but if you take improved HS normal stops proccing altogether.
On further investigation, this was fixed by respecking into fire, testing normal HS and THEN taking the Improved HS talent. Now it works properly but what happened is still worth looking into,
