### ISSUE TITLE
[Spell/Mage] Frostfire Bolt / Glyph of FFB

### ISSUE THREAD

**Issue by gitkulu** [WoWManiaUK/Blackwing-Lair#2315]
**Links:**
Frostfire Bolt: https://www.wowhead.com/spell=44614/flurry
GlyphID of Glyph of Frostfire: 591

**What is happening:**
Frostfire Bolt always gains the stacking dot effect of Glyph of Frostfire.

**What should happen:**
Frostfire Bolt should only gain the effect of Glyph of Frostfire if the glyph is active.

**Comment by giles1508** [comment]
Just to add to this,  my mage is only 70 so hard to tell,  but the dmg of the dot seems super low and it also slows the target when it's not supposed to, again I haven't tested much but when I get more chance

**Comment by Dranah** [comment]
Same issue was present on the other core, reported here
https://github.com/WoWManiaUK/Blackwing-Lair/issues/92

**Comment by Rushor** [comment]
http://cata.cavernoftime.com/spell=61205

**Comment by Dranah** [comment]
The dot is now only added with the glyph as intended.
The damage of the DOT doesnt check out, it is reported on the other thread with coeff. https://github.com/WoWManiaUK/Blackwing-Lair/issues/2691
