### ISSUE TITLE
[Goblin starting zone] The great bank heist Id 14122 - Kezan

### ISSUE THREAD

**Issue by Maglubiyet** [WoWManiaUK/Blackwing-Lair#2316]
Links:
https://www.wowhead.com/quest=14122/the-great-bank-heist

What is happening:
Nothing happen in the Kezan bank, no npcs, no option for robbing the money

What should happen:
a lot of things ! 
https://www.youtube.com/watch?v=2PnVIy6njLE

**Comment by bagi84** [comment]
Npc- https://www.wowhead.com/npc=34668/sassy-hardwrench (kezan)
not be confused with Npc - https://www.wowhead.com/npc=35650/sassy-hardwrench (post kezan destruction-lost isle)

**Comment by Rushor** [comment]
![I](https://i.imgur.com/E4rG6fM.jpg)

next one fixed aswell now. minigame will be added later.
