### ISSUE TITLE
[goblin starting zone] robbing hoods id 14121 - kezan

### ISSUE THREAD

**Issue by Maglubiyet** [WoWManiaUK/Blackwing-Lair#2317]
**Links:**
https://www.wowhead.com/quest=14121/robbing-hoods

**What is happening:**
The goblin hot Rod isn't available.

**What should happen:**
We should drive the Hot Rod and run over 12 nps

**Comment by Rushor** [comment]
next goblin fixed https://github.com/WoWManiaUK/Blackwing-Lair/issues/2317 
![I](https://i.imgur.com/iIgX4aS.jpg)

keys to the hot rod added. when you run over the creatures you will get the item.
