### ISSUE TITLE
[goblin starting zone] Waltz right in id 14123

### ISSUE THREAD

**Issue by Maglubiyet** [WoWManiaUK/Blackwing-Lair#2318]
**Links:**

https://www.wowhead.com/quest=14123/waltz-right-in

**What is happening:**
We can't obtain the 3 quest items. There are spawn, but we can't click on it.

**What should happen:**
We should steal this 3 quest item by clicking on it

https://www.youtube.com/watch?v=aCNQpBLklcI

**Comment by Kitzunu** [comment]
Will look into this this afternoon
