### ISSUE TITLE
[goblin starting zone] Liberate the Kaja'mite id 14124 - kezan

### ISSUE THREAD

**Issue by Maglubiyet** [WoWManiaUK/Blackwing-Lair#2319]
**Links:**
https://www.wowhead.com/quest=14124/liberate-the-kajamite

**What is happening:**
The rock doesn't explode with the kaja-mite

**What should happen:**
The rock should explode, so we can pick the deposit up

https://www.youtube.com/watch?v=aAlc7ezm1zk

**Comment by Rushor** [comment]
what is todo:

add script to handle despawn of deposit
add spawn for chest quest loot instead

**Comment by Rushor** [comment]
![](https://i.imgur.com/PWLzibp.jpg)
![](https://i.imgur.com/CujJgw4.jpg)
![](https://i.imgur.com/INVNkn5.jpg)

**Comment by Rushor** [comment]
2-3 chunk spawns must be added here. not only one.

![I](https://i.imgur.com/66nNXKM.jpg)

fixed that
