### ISSUE TITLE
[Talent/Mage] Improved Counterspell

### ISSUE THREAD

**Issue by Zhalox123** [WoWManiaUK/Blackwing-Lair#2320]
**Links:**
https://wowwiki.fandom.com/wiki/Improved_Counterspell

**What is happening:**
The talent doesnt work at all with 2 x improved talents should blank silence the target for 4 seconds but nothing happends

**What should happen:**
Should silence the target for 2/4 seconds depends on 1 or 2 points spent on the talent

**Comment by Rushor** [comment]
fixed. live with next server update

![I](https://i.imgur.com/pjMIrt4.jpg)
