### ISSUE TITLE
[NPC] Jornun - missing - Darkspear Hold

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2321]
https://www.wowhead.com/npc=38989/jornun

This NPC should provide transport for you for the quest https://www.wowhead.com/quest=25035/breaking-the-line

He's currently missing so you have to walk by foot.
The quest is otherwise doable, so this is not an urgent issue to fix.

**Comment by wow-mania** [comment]
he is there.
make sure you have the requirements to see him.

**Comment by Dranah** [comment]
I have completed every quest and picked up the one that requires his aid. What other requirements are there?
If he is phased, then that's definitely broken.

**Comment by Dranah** [comment]
The NPC is now in the correct phase, however the raptor he gives you is not mountable (he has mount icon to click, but nothing happens), he just runs away without you.

**Comment by Rushor** [comment]
fixed, condition for gossip added, speed increased and player will be on the mount automatically now

![I](https://i.imgur.com/7HzNPqD.jpg)
