### ISSUE TITLE
[NPC] Vanira - Darkspear Hold

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2322]
https://www.wowhead.com/npc=38437/vanira

This specific version of her when completing the quest https://www.wowhead.com/quest=24814/an-ancient-enemy offers an option to teleport you back to voljin to hand in your quest.
The chat option doesn't work, she won't port you home.

The quest is otherwise doable and this is not urgent to fix.
![WoWScrnShot_061019_181315](https://user-images.githubusercontent.com/31132743/59209362-6fa0fa00-8bab-11e9-95b5-062a31769696.jpg)

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/59213900-d9220800-8bad-11e9-81ed-aa2132e45a88.png)

**Comment by Dranah** [comment]
Your point is? xD
She is there, but doesn't function. It's low priority, but not working.

**Comment by Dranah** [comment]
Ah well.

**Comment by Kitzunu** [comment]
Fixed for ya @Dranah <3
