### ISSUE TITLE
[Item] Replica Blood Guard's Chain Belt

### ISSUE THREAD

**Issue by Imba232** [WoWManiaUK/Blackwing-Lair#2323]
**Links:**

https://www.wowhead.com/item=120991/replica-blood-guards-chain-belt 

**What is happening:**

Replica Blood Guard's Chain Belt is missing from vendor

**What should happen:**

Leeni "Smiley" Smalls should sell Replica Blood Guard's Chain Belt.

**Comment by Kitzunu** [comment]
I will look into it this afternoon

**Comment by Rushor** [comment]
the item has way too high id - it was added with patch 6.X 

https://www.wowhead.com/item=120991/replica-blood-guards-chain-belt

If there is a Cata 4.X version for it let me know and open a new issue for it.
