### ISSUE TITLE
[spell] Savage Roar - Drui - no damage buff

### ISSUE THREAD

**Issue by fuzzydunlop** [WoWManiaUK/Blackwing-Lair#2327]
**Links:** WowHead link expired (old spell), Reign Armory non-existent.

**What is happening:** There seems to be no damage buff, at all.

**What should happen:** Autoattacks (white hits) should do 80% more damage while savage roar is active. I did some testing and there's no increase. Took a screen shot of dmg with SR up, and one without SR active. The averages and the min-max are the same.  

![WithSR](https://user-images.githubusercontent.com/14002052/59292238-f8d43180-8c7c-11e9-8ce9-8240af8cc0c1.jpg)

**Comment by giles1508** [comment]
confirmed today by myself while testing,   this does NO increased damage,  and this is a kitty druids bread and butter attack dmg ( melee auto hits )  should be pretty much top of a ferals dmg chart when atm its half way down the list.   this needs to be fixed ASAP  gimping ferals alot !

**Comment by fuzzydunlop** [comment]
Any idea when this fix is ready ? Been a while now and no clue what the status of this one is =)

**Comment by Sevenblade11** [comment]
Any updates? It's a taaaaadd bit important for Feral DPS

**Comment by Keader** [comment]
Yeah, but no one signed me since 2 days Ago.
So Will be fixed next week

**Comment by Keader** [comment]
Fixed.
