### ISSUE TITLE
[Priest][Shadow] Shadow Word: Death

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2328]
**Links:**
https://www.wowhead.com/spell=32379/shadow-word-death

**What is happening:**
1: The Spell does not get increased damage on targets under 25% health. 

2: The Spell won't reset its cooldown if used on a target under 25% health which doesn't die, when Glyph of Shadow Word: Death is active.

**What should happen:**
1: Spell should be a very strong finisher
2: Spell should reset CD is target does not die after first use.

**Comment by Grotesqueee** [comment]
Would be nice if someone looked at this major mechanic of a spec that does not work

**Comment by Keader** [comment]
Please add "Priority High" tag in issues that have high priority
