### ISSUE TITLE
[Item] Ettin Control Orb - Redridge mountains

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#233]
Quest https://www.wowhead.com/quest=26520/saving-foreman-oslow
Npc/item https://www.wowhead.com/object=204351/ettin-control-orb
Issue-
The Orb you receive in your inventory is not working as required , it  will not interact with the npc https://www.wowhead.com/npc=43094/canyon-ettin to turn him into npc https://www.wowhead.com/npc=43197/subdued-canyon-ettin
which is preventing the completion of this quest chain

![world of warcraft 20_12_2018 16_01_33](https://user-images.githubusercontent.com/45798884/50295724-95590c00-0470-11e9-8cbf-d7c9abaaf499.png)

**Comment by Saintres** [comment]
Tryed to do the quest today but i got the same error. The orb is not working 
2019 02 03

**Comment by UnknownCombine** [comment]
Tryed to do the quest today but i got the same error. The orb is not working (25/5/19)

**Comment by Eirolla** [comment]
Tested 02/08/19 - the Same issue continues.

**Comment by mfranca0009** [comment]
Will be needed for scripting:
https://www.wowhead.com/npc=43196/huge-boulder (Boulder is crushing Foreman Oslow and Subdued Canyon Ettin will lift off of him)
https://www.wowhead.com/spell=80702/control-ettin (Summons Subdued Canyon Ettin)
https://www.wowhead.com/spell=80704/control-ettin (Control ettin and pick up rock with this spell? )
https://www.wowhead.com/item=58895/ettin-control-orb (Quest Item)

Subdued Canyon Ettin ability:
https://www.wowhead.com/spell=80739/lift-huge-boulder (Lift Boulder off of Foreman Oslow)

- Canyon Ettin should despawn once Subdued Canyon Ettin is summoned after quest item use (Spell 80702).
- Subdued Canyon Ettin should lift boulder off of Foreman Oslow when you use quest item (Spell 80704).
- Small Scene will play with Subdued Canyon Ettin talking / lifting boulder and Bridge Worker NPCs talking
- Subdued Canyon Ettin runs off to dock, throws rock into water.
- Subdued Canyon Ettin last line as a YELL type, "BYE BYE DADDY!" and runs up the hill out of Lakeshire to despawn

**Comment by Echinaceax** [comment]
NOT fixed 
- after using the quest item on the _Canyon Ettin_ the _Subdued Canyon Ettin_ isnt switching,  _Canyon Ettin_ stays 
- I cleared cache, and still nothing

![not fixed](https://user-images.githubusercontent.com/39439201/89098767-b0c91e80-d3ea-11ea-9f13-53367d1950c3.jpg)

**Comment by mfranca0009** [comment]
C++ script currently in progress of being made 👍

**Comment by mfranca0009** [comment]
Needs testing in PTR 👍 

Quest is completable, the only problem left is the Subdued Canyon Ettin not displaying animation of picking rock up and tossing rock into the water. The "Lift Boulder Ride" spell was completely broken with no animations attached. If any information comes by where it can be improved I will adjust it further.

The complete quest event should function as it should otherwise.
