### ISSUE TITLE
[Priest][Shadow] Sin and Punishment

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2332]
**Links:**
https://www.wowhead.com/spell=34433/shadowfiend
https://www.wowhead.com/spell=131556/sin-and-punishment
**What is happening:**
The part where Mind Flay crits should reduce the CD of Shadowfiend, does not work at all. Calculated it with the stopwatch, from full CD minus MF crit counts. The duration had not been reduced at all. 

**What should happen:**
Mind Flay crits should reduce Shadowfiend CD by 10 sec when this talent is active.

**Comment by Javalapa** [comment]
As of October 1st, this still is currently broken. Mind Flay criticals do not effect Shadowfiend CoolDown at all
