### ISSUE TITLE
Dual Specc Death Knight

### ISSUE THREAD

**Issue by Boztepe1** [WoWManiaUK/Blackwing-Lair#2333]
**Links:**

from WoWHead or our Armory

**What is happening:** No Dual Specc Option at DK Trainers in Acherus.

**What should happen:** Dual Specc Option at DK Trainers in Acherus
![WoWScrnShot_061119_215504](https://user-images.githubusercontent.com/51721774/59302482-59229d80-8c94-11e9-9c71-744cc3b2d88b.jpg)
![WoWScrnShot_061119_215520](https://user-images.githubusercontent.com/51721774/59302495-617ad880-8c94-11e9-8199-1768bc17f50f.jpg)
![WoWScrnShot_061119_215543](https://user-images.githubusercontent.com/51721774/59302516-6c356d80-8c94-11e9-9960-95c7e581b440.jpg)

**Comment by Boztepe1** [comment]
Grettings and thx for taking a look at the issue

**Comment by giles1508** [comment]
there is a trainer that does it,  razouvious i believe does it as your blood spec

**Comment by Boztepe1** [comment]
![WoWScrnShot_061219_092806](https://user-images.githubusercontent.com/51721774/59331501-68393800-8cf4-11e9-908a-82b916721b9e.jpg)

this one give you dual specc i didnt even recognize! thx for the help

**Comment by giles1508** [comment]
No problem, feel free to close the report :)

**Comment by Kitzunu** [comment]
Fixed.

Don't close the report
