### ISSUE TITLE
[Mage][Arcane] Presence of Mind VS Arcane Power

### ISSUE THREAD

**Issue by Xelerom** [WoWManiaUK/Blackwing-Lair#2334]
**Links:** https://www.wowhead.com/spell=205025/presence-of-mind
https://www.wowhead.com/spell=12042/arcane-power

**What is happening:** When you have PoM activate you can't use AP and vice versa .

**What should happen:**  Here you have proff when have PoM activate he can use AP (see actions bar )

https://youtu.be/uhYbdYvGofg?t=116

**Comment by Echinaceax** [comment]
Video you linked  has the rotation

![rotation](https://user-images.githubusercontent.com/39439201/107719096-b5df2280-6cd7-11eb-88da-0680b45812df.jpg)

But if you start your rotation with PoM the 1 AB is instant and the others are cast time to build up your stacks of AB 

![image](https://user-images.githubusercontent.com/39439201/107719857-71ed1d00-6cd9-11eb-88a3-46e10d29e2a4.png)


![image](https://user-images.githubusercontent.com/39439201/107719382-66e5bd00-6cd8-11eb-9da4-9ee99e35044e.png)

Yes if you start off with PoM then ofc you cant use Arcane Power until you have spent the Presence of Mind
