### ISSUE TITLE
[NPC] Schnottz Acout - missing quest text - Uldum

### ISSUE THREAD

**Issue by TapperUdan** [WoWManiaUK/Blackwing-Lair#2335]
**Links**
Quest: https://www.wowhead.com/quest=27541/lessons-from-the-past
NPC: https://www.wowhead.com/npc=45874/schnottz-scout

**What is happening:**
![WoWScrnShot_061119_225826](https://user-images.githubusercontent.com/40371076/59322589-778c9700-8c9c-11e9-97d0-7a3fba06bb09.jpg)

Unable to get the scouts journal. or progress with the quest at all.

**What should happen:**
https://www.youtube.com/watch?v=CkPfXLG1Hg0&feature=youtu.be

**Comment by sarahkay88** [comment]
The scouts journal  https://www.wowhead.com/item=61930 is the reward for completing the above quest.
to complete the quest you need to acquire the broken goggles - https://www.wowhead.com/item=61929

**Comment by giles1508** [comment]
I'm pretty sure the prequest before this haven't even been fixed yet? Would need the prequests completed first before we know if this is bugged or just not working because the quest chain isn't fully working before it

**Comment by Rushor** [comment]
quest works, but questender https://www.wowhead.com/npc=45296/harrison-jones is missing
