### ISSUE TITLE
[NPC] Harrison Jones - issue 2 - Uldum

### ISSUE THREAD

**Issue by TapperUdan** [WoWManiaUK/Blackwing-Lair#2336]
**Links:**
Quest: https://www.wowhead.com/quest=27517/be-prepared
NPCS: https://www.wowhead.com/object=205540/decrepit-skeleton
           https://www.wowhead.com/npc=45296/harrison-jones

**What is happening:**

I am able to get all the rope needed in order to complete the quest but the NPC to turn the quest does not show up.

**What should happen:**

Harrison Jones should be there to allow me to turn in the quest, but he isn't anywhere to be found. The ? shows on my minimap where he should be, but he is not visible

**Comment by sarahkay88** [comment]
#267  - issue 1

**Comment by Rushor** [comment]
phaseid was wrong sorry. fixed.
