### ISSUE TITLE
[Talent/Warrior Protection]Demoralize Range Effect

### ISSUE THREAD

**Issue by TheTankk** [WoWManiaUK/Blackwing-Lair#2338]
**Links:** https://www.wowhead.com/spell=1160/demoralizing-shout

from WoWHead or our Armory

**What is happening:** I can't post screen because i am at work. The spell Demoralizing should have range 30 yards (this is from wow head maby on Cata 4.3.4 have diffrent range) but problem is now on server have 0 yards... i need to be stack on mob/boss to use it... and on some mobs/boss i can;t use it because they have HitBox to big.

**What should happen:** Should have 30 yards

**Comment by TheTankk** [comment]
6 days... no confirm no reject... but you fix low quest from some forgoten zone.... thx guys

**Comment by Rushor** [comment]
also the CD seems to be missing.

**Comment by Keader** [comment]
@TheTankk when a issue has priority, use a @Keader to mark me, and i will try fix asap.
Working on it now.

**Comment by Keader** [comment]
30 yards is wrong, it should affect targets in 10 yards.
Has a tooltip bug (that i cant fix, cause is clientside one), that make range appear as 0 yards, but core take correct 10 yards.
I make radius 12 yards, cause tc has some little issues with ranges, so now the spell always apply if target is <= 10 yards of distance.
