### ISSUE TITLE
[Arena] Amphiteather of anguish - zul'drak 

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#2339]
**Links:**
https://www.wowhead.com/quest=12974/the-champions-call
https://www.wowhead.com/quest=9977/the-ring-of-blood-the-final-challenge
https://www.wowhead.com/quest=12932/the-amphitheater-of-anguish-yggdras

**What is happening:**
If you do the Nagrand arena first and then pick up the above quest https://www.wowhead.com/quest=12974/the-champions-call you can then complete the zuldrak arena, however if you skip Nagrand arena and then do this quest it does not unlock the zuldrak arena for players
also if players skip Nagrand arena and avoid picking up the quest they cannot do the zuldrak arena either

**What should happen:**
Players should be able to skip the arena in Nagrand and still be able to complete the arena in zuldrak with or without the quest

**Steps to reproduce**

repo  1  -
make toon do Nagrand arena at required level- ring of blood
go to dalaran collect quest  -https://www.wowhead.com/quest=12974/the-champions-call
go to zuldrak and complete arena 
**works fine**
repo 2 - 
skip Nagrand arena - ring of blood
go to dalaran collect quest - https://www.wowhead.com/quest=12974/the-champions-call
zuldrak arean wont start when it should

repo 3 -
skip Nagrand -ring of blood
skip dalaran quest
go to zuldrak arena  - required lvl - arena wont start when it should

**Comment by bagi84** [comment]
check this following repo steps and can confirm issue

**Comment by bagi84** [comment]
Amphitheatre of anguish quest chain can now be picked up  with quest complete from dala and without (both without doing ring of blood in nagrand).

**Comment by Dranah** [comment]
Players now can't access the quest once they have completed the Nagrand one.

**Comment by Dranah** [comment]
This is same issue as the one we reported and fixed at https://github.com/WoWManiaUK/Blackwing-Lair/issues/215 - possibly kitzu reverted the problem.

**Comment by Kitzunu** [comment]
Fixed

**Comment by Rushor** [comment]
do you uploaded the fix on dev folder @Kitzunu ?

**Comment by Kitzunu** [comment]
@Rushor I have not, no.
But it should be the same as WotLK now

Just need someone to test it to see if it works

**Comment by Dranah** [comment]
Well, it doesn't. Nagrand chain still closes it.

**Comment by Kitzunu** [comment]
that makes no sense...

@Rushor Could you check?

**Comment by Rushor** [comment]
will check

**Comment by Rushor** [comment]
works finr for me on dev

![](https://i.imgur.com/83AZRAc.jpg)

**Comment by zippoking** [comment]
For me this is still not working.
I finished the Arena in Nagrand, and i completed the Quest "The Champions Call" from Dalaran. But Gurgthock has no arena quest for me.

![Amphitheather of Anguish - how it is](https://user-images.githubusercontent.com/18005338/60216342-1226d180-986a-11e9-8ada-206506a21ccf.png)

**Comment by Echinaceax** [comment]
@Rushor - still issues here it seems new report closed but i'll link here #2686

**Comment by Kitzunu** [comment]
this will be impossible to fix unless someone gives me reproduction steps, because I cannot reproduce it and it has the identical code to wotlk

**Comment by hediunchained** [comment]
there is an achievement that link both of the arenas 
https://www.wowhead.com/achievement=1576/of-blood-and-anguish

maybe the problem is coming from there @Rushor ?
