### ISSUE TITLE
[Quest/order] The Hatchery must burn - missing prereq- Mount Hyjal

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#234]
quest - https://www.wowhead.com/quest=25810/the-hatchery-must-burn
NPC - https://www.wowhead.com/npc=41003

![world of warcraft 20_12_2018 16_06_13](https://user-images.githubusercontent.com/42302580/50295963-42338900-0471-11e9-9545-eec402d426b9.png)
 you are to entre the portol to speak with the next NPC to complete the quest, however you cannot entre the portol.

**Comment by Rushor** [comment]
prevquest was added, teleport works for gms

**Comment by Rushor** [comment]
finally done after so much research... https://i.imgur.com/AbNnqnC.jpg

teleport dummy npc trigger are strange xD
