### ISSUE TITLE
[profession] Alchemy mastery extra procs

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2340]
**Links:**

https://www.wowhead.com/spell=28677/elixir-master#comments
https://www.wowhead.com/spell=28672/transmutation-master#comments
https://www.wowhead.com/spell=28675/potion-master

ignore the mats on these links,  the mats have changed over the years,  but the talent remains the same

**What is happening:**

none of the above mastery talents are working,  they are not giving any additional procs at all

**What should happen:**

what should happen is that every time you craft something from your selected mastery,   so if your a potion master and your making potions  you have a chance to proc up to 5 additional potions on EVERY single craft,  this is the same for transmutations and also flasks and elixirs

so as follows

Elixir master procs extras from  -   all flasks and elixirs in game you can make
potion master procs extras from  -   all potions you can make in game 
Transmutation master procs extras from  -   any transmutations you can make in game

**Comment by Kladenets** [comment]
is there have any news ?

**Comment by Lerixo** [comment]
So to make this a bit easier:

Each mastery gives a chance for each craft, like Potion Master for Potions, Elixir Master for Elixirs and so on, 
**To yield extra items each craft.**

![Potions](https://user-images.githubusercontent.com/52600303/61868813-82ad2680-aeda-11e9-9c7b-9a2768f45a45.png)

Above, this is like the lowest rolls you can get (he is Potion master).
But i think you see what these Masteries do. The same applies for Flasks(Elixirs) and Transmutes.

I'd say the best thing is to get the working script, which is fledged out. Maybe from mania and rescript it. Imo it could be very hard to find out the exact max rolls and chances, without having the Blizzlike code.

**Comment by Eirolla** [comment]
*Checking*

**Comment by Keader** [comment]
@Rushor no core issues here, is just missing data in ```skill_extra_item_template``` table

**Comment by Eirolla** [comment]
![image](https://user-images.githubusercontent.com/26048748/63005112-89e5a580-be84-11e9-9115-4ee8e519a2d0.png)
 I will test it on dev realm when I have time. It happens on the live server.

**Comment by Rushor** [comment]
fixed!

https://i.imgur.com/dutC9v5.jpg

14 percent chance to add 3-5 extra items on each cast of:

80477,
80480,
80484,
80488,
80492,
80491,
80493,
80497,
80719,
94162,
80720,
80723,
80721);
80251,
80250,
80246,
80248,
80247,
80244,
80243,
80237,
80245);
93935,
80478,
80479,
80481,
80269,
80482,
80487,
80486,
80490,
80495,
80494,
80496,
80498,
80726,
80725);

**Comment by Slydee23** [comment]
we tried it now on live but no proccs after over 40 pots crafted

**Comment by Keader** [comment]
are you sure that i's applied already?
Can you try again later? (in 1 hour or so)

**Comment by jahbansen** [comment]
ok we will try later again, so far it didnt work

**Comment by Slydee23** [comment]
@Keader the server update is live like my Synapse Springs from Engineering already working and TB Daylies etc  but this not

**Comment by Keader** [comment]
Ah ok

**Comment by Rushor** [comment]
i think one sql was missing. will be reapplied next morning.
