### ISSUE TITLE
[Item] Canopic Jar

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2341]
**Links:**

https://www.wowhead.com/item=64657/canopic-jar

**What is happening:**

this item is yeilding no loot what so ever

**What should happen:**

this item is crafted from archaeology and it isnt very common either,  meaning that every time you find one its quite important to the crafter 

This has the chance to drop the vial of the sands recipe for achemists
https://www.wowhead.com/item=67538/recipe-vial-of-the-sands#comments

also a grey item that vendors for 2g
https://www.wowhead.com/item=67540/mummified-organ

you HAVE to have 525 skill in achemy for this to even drop but this is not dropping anything
tested the living daylight out of this opening over 100 of the jars with 525 skill in both archaeology and alchemy and not a single drop

**Comment by Kitzunu** [comment]
Fixed in dev.

current drop rate is VotS 10% organ 90% because that is the info I have found.

If someone finds other conflicting drop rates from those I put please tell me

**Comment by giles1508** [comment]
Yeah that seems about right dude

**Comment by giles1508** [comment]
I'll log dev now to confirm

**Comment by giles1508** [comment]
jars are dropping loot now,  ill add label

**Comment by dagget1337** [comment]
so, are the jars supposed to dropp 90% the organs now and by the rest 10% the recipe? Because the last jar ive opened didnt dropp either and tbh those before that gave atleast 1x organ, is it rly save to open them now? i kinda doubt they´re fully working :/
