### ISSUE TITLE
[Spell] Elusiveness

### ISSUE THREAD

**Issue by Amaaz** [WoWManiaUK/Blackwing-Lair#2342]
**Links:**
https://www.wowhead.com/spell=21009/elusiveness

from WoWHead or our Armory

**What is happening:**
Elusiveness does not give 5% more movement speed
Haven't tested it yet, but considering the movement speed aspect isn't working, the "reduced chance for enemies to see you while shadowmelded" may not be working as well

**What should happen:**

Elusiveness should give 5% more movement speed when stealthed(Night elf racial)

**Comment by Priestelar** [comment]
![image](https://user-images.githubusercontent.com/16594771/68969169-00c86c80-07ed-11ea-922e-fc7baefde2ca.png)

Confirmed that the movespeed increase is still not working when you are stealthed @Keader

**Comment by Keader** [comment]
Fixed (again)
i miss fix for rogues, just did to druids kekw
now fixed for rogues too ✌️

**Comment by golosomie** [comment]
@Keader couldn't get this to work. are you sure this is on PTR?
