### ISSUE TITLE
World Bosses Elite/Rare

### ISSUE THREAD

**Issue by Geniuskp** [WoWManiaUK/Blackwing-Lair#2343]
**Links:**

50056 | Garr <Mount Hyjal>does not spawn.
50089 | Julak-Doom <Twilight Highlands> impossible to kill due mind control on all raid members.

Rare 
50060 | Terborus <Deepholm> does not spawn.

**Comment by bagi84** [comment]
Report split down into 3 separate reports - one for each Npc . see #2373 #2374 #2375
