### ISSUE TITLE
[Npc] Bilgewater Foreman - Azshara

### ISSUE THREAD

**Issue by Absaggio** [WoWManiaUK/Blackwing-Lair#2344]
https://www.wowhead.com/quest=26337/beating-the-market

What is happening:
Can't interact with the target to start the fight

What should happen:
I should interact with him and start the fight to intimidate him

**Comment by bagi84** [comment]
Npc - https://www.wowhead.com/npc=42798/bilgewater-foreman - unable to interact with npc for quest completion

**Comment by gamer100** [comment]
Fix is  working

**Comment by Echinaceax** [comment]
@gamer100 fix in dev confirmed fixed correct ?

**Comment by gamer100** [comment]
the  quest ia  qorking npc run trough  the market and  complete  but you cant deliver the complted quest to the npc

**Comment by Echinaceax** [comment]
> This is why i did not confirmed yet

Naughty @wow-mania :)

**Comment by Rushor** [comment]
the smartai and the questid in script had to be changed in order to work

![I](https://i.imgur.com/iJ2V34a.jpg)
![I](https://i.imgur.com/j08FnpS.jpg)
