### ISSUE TITLE
[Spell/Druid] Savage Defense

### ISSUE THREAD

**Issue by Imba232** [WoWManiaUK/Blackwing-Lair#2345]
**Links:**

ID 62600

**What is happening:**

Savage Defense only absorbs 1 point of physical damage.

**What should happen:**

Each time you deal a non-periodic critical strike while in Bear Form, you have a 50% chance to gain Savage Defense, absorbing physical damage equal to 35% of your AP for 10 sec.

I don't know if it's also related to mastery, which should increase the damage absorbed by Savage Defense by 4% for each point of mastery.

**Comment by giles1508** [comment]
tested this today in heroic and i can confirm 100 % that this needs fixing ASAP  this is the druid bears  active mitigation,  without this they are just glorified punch bags....  taking silly amounts of damage.... please get onto this ASAP  healers are killing themselves healing ferals atm

**Comment by Dranah** [comment]
Spell now works by itself,but mastery doesn't affect it. It's fix 35% regardless of mastery.

**Comment by Dranah** [comment]
Mastery now affects the shield as intended.
