### ISSUE TITLE
[NPC] Dizzy Dina - ID 21824 - missing - Blade's Edge Mountains

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2346]
**Links:**
NPC: https://www.wowhead.com/npc=21824/dizzy-dina

**What is happening:**
Dizzy Dina is missing at her location she should be at.
![Dizzy Dina - how it is](https://user-images.githubusercontent.com/18005338/59380940-8b96ce00-8d5a-11e9-8519-12837c48f876.png)

**What should happen:**
Dizzy Dina should be at her location at 60.4/68.8
![Dizzy Dina - how it should be](https://user-images.githubusercontent.com/18005338/59380937-8b96ce00-8d5a-11e9-9c5f-7de42c0bfe8d.png)

**Comment by Rushor** [comment]
added

![I](https://i.imgur.com/SUa7ebT.jpg)
