### ISSUE TITLE
[NPC] Battered Red Drakes -missing - Grim Batol (normal)

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#2347]
**Links:**

https://www.wowhead.com/npc=42571/battered-red-drake 
https://www.wowhead.com/grim-batol

**What is happening:**
they are currently missing from their spot within this dungeon

**What should happen:**
After fighting there way to these npcs, players kill the nets and then these npcs should arrive, players then jump on their backs and they take a certain path around the dungeon and players use the dragons abilities to kill mobs
see video https://www.youtube.com/watch?v=37a2bWeVeB4

**Comment by Echinaceax** [comment]
Also noticed that there are drakes flying above so i tested by flight mode GM and tried to mount the Battered Red Drakes as the icon indicated and is continues to drop vermillion vanguard drakes too 
when you click on the them (totally broken) 

![vermillion vanguard](https://user-images.githubusercontent.com/39439201/59382355-cf3f0700-8d5d-11e9-8cf9-2857e6a56ecf.jpg)

**Comment by giles1508** [comment]
these drakes are super important !  otherwise this makes the instance take 4 times longer than its meant to
and they are needed to tazi you around the instance if you wipe, otherwise your looking at a good 10 minute walk back to get to the end of the instance,     on top of this you have to fight every pack at full hp when the design is to only fight them with very little hp as the drakes ahve done all the damage

**Comment by Echinaceax** [comment]
Yes defo need fixing before tests can continue in Grim batol

**Comment by Echinaceax** [comment]
@Kitzunu - stop removing my pending label when we wasn't finished in there, we know when it needs removing lol

**Comment by Rushor** [comment]
![I](https://i.imgur.com/4gG1wTV.jpg)
![I](https://i.imgur.com/jUhvjFy.jpg)

added spawn and path. they are usuable only once. https://youtu.be/37a2bWeVeB4?t=210

Organise how you use them :D

**Comment by Rushor** [comment]
okay the part where they fl you to the last boss that has been defeated will be done later. 
will fix the part of the spelldamage now

**Comment by Rushor** [comment]
okay added some more checks to that - somehow  it bugged for some people

![I](https://i.imgur.com/fCTV3wT.jpg)

**Comment by Sammy974** [comment]
They fly far from the dungeon.
![WoWScrnShot_072219_123555](https://user-images.githubusercontent.com/45459932/61626905-c572c280-ac7e-11e9-9aa1-0c154c24b376.jpg)

**Comment by Sammy974** [comment]
check the 3th and the 4th drake from the left to the right :)

**Comment by Rushor** [comment]
okay will check
