### ISSUE TITLE
[Quest] Gauging the resonant Frequency - ID 10594 (issue 1) - Blade's Edge Mountains

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2348]
**Links:**
Quest: https://www.wowhead.com/quest=10594/gauging-the-resonant-frequency
Item: https://www.wowhead.com/item=30701/oscillating-frequency-scanners
Mobs: https://www.wowhead.com/npc=21796/wyrm-from-beyond

**What is happening:**
Here, every single time you place down a scanner, the "Wyrm of beyond" spawns, and attacks you. Unfortunately their model is missing and you can´t attack them right away. They are stopping me from placing down all 5 scanners. I got to 4, but then to many of these damn Wyrms spawned. 
![Gauging the resonant frequency - how it is 2](https://user-images.githubusercontent.com/18005338/59384209-f992c380-8d61-11e9-97f8-b8fbaee3dab4.png)
![Gauging the resonant frequency - how it is 1](https://user-images.githubusercontent.com/18005338/59384213-fa2b5a00-8d61-11e9-8b7c-b099eb95c29d.png)

**What should happen:**
So for this quest you need to put down the scanners in a pentagon shape (25 yard between each other). Then they connect to each other and you need to walk trough the beams to get a stack of 5 and the quest is done. Once in a while a "Wyrm from beyond" spawns when you place down a scanner, but that should not happen every single time.
![Gauging the resonant frequency - how it should be 1](https://user-images.githubusercontent.com/18005338/59384212-f992c380-8d61-11e9-9a32-145a95eb2750.png)

**Comment by Kitzunu** [comment]
@wow-mania could this be missing textures from client? 

Checked DB and they have the same ModelID as wotlk ones

**Comment by Rushor** [comment]
different model added for now

![I](https://i.imgur.com/ksXxcDf.jpg)
![I](https://i.imgur.com/KraV7jZ.jpg)
