### ISSUE TITLE
[Quest] Gauging the resonant Frequency - ID 10594 (issue 2) - Blade's Edge Mountains

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2349]
**Links:**
Quest: https://www.wowhead.com/quest=10594/gauging-the-resonant-frequency
Item: https://www.wowhead.com/item=30701/oscillating-frequency-scanners
Mobs: https://www.wowhead.com/npc=21796/wyrm-from-beyond

**What is happening:**
The scanner should last for 3.50 min, but they are disappearing after 50 seconds. In combination with issue 1 #2348 i can´t complete the quest.

**What should happen:**
So for this quest you need to put down the scanners in a pentagon shape (25 yard between each other). Then they connect to each other and you need to walk trough the beams to get a stack of 5 and the quest is done. 
![Gauging the resonant frequency - how it should be 1](https://user-images.githubusercontent.com/18005338/59384212-f992c380-8d61-11e9-9a32-145a95eb2750.png)

**Comment by Rushor** [comment]
increased to 210 seconds.
