### ISSUE TITLE
[NPC] Thisalee Crow - Missing/Wrong quest order - Mount Hyjal

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#235]
Quest - https://www.wowhead.com/quest=25776/sethrias-demise
Quest - https://www.wowhead.com/quest=25763/the-codex-of-shadows
Quest - https://www.wowhead.com/quest=25758/a-gap-in-their-armor
Are all to be handed in to the same NPC  - https://www.wowhead.com/npc=41006

However she is not in the her place.
![world of warcraft 20_12_2018 16_37_20](https://user-images.githubusercontent.com/42302580/50298050-24b4ee00-0476-11e9-8bfc-e953bbfb3f48.png)

**Comment by sarahkay88** [comment]
She can however be found in the Shrine of Aviana which the inn for the quest arear.
![world of warcraft 20_12_2018 16_46_39](https://user-images.githubusercontent.com/42302580/50298492-2d59f400-0477-11e9-8a65-85731ae2fda7.png)

**Comment by Dranah** [comment]
She is missing the order in her quest chain and also missing her phasing/positioning for each stage of it. https://github.com/WoWManiaUK/Blackwing-Lair/issues/552

I'll leave this here (from wowhead):

**Aviana quest chain


1. Wings Over Mount Hyjal (breadcrumb quest. Don't do this one)
   Aviana's Legacy (breadcrumb quest. More XP)
1. An Offering for Aviana (use netcar at burial)
1. A Plea From Beyond (go to NPC)
1. A Prayer and a Wing (kill Blaithe)
     |
     |
     |     2. The Wormwing Problem (kill 10 Harpies)  2. Scrambling for Eggs (collect 8 eggs)
     |                            2. A Bird in Hand (Interrogate Marion)
     V
3. Fact-Finding Mission (go to Thisalee)
3. Sethria's Brood (kill 12 dragonkins)    4. A Gap in Their Armor (get 8 armors)
                                           4. Disassembly (kill 3 Juggernauts)
                                       /
                   ------------------.     5. The Codex of Shadows (go to Thisalee)
                 /                         5. Egg Hunt
                V (do you need 3, 4, and 5 to unlock 6?)
6. Sethria's Demise (kill Sethria)
6. Return to the Shrine (go back to Choluna)
6. An Ancient Reborn (use quest object)

7. The Hatchery Must Burn (go through portal)
7. Flight in the Firelands (practice a special flight mechanism)
7. Wave One (kill (collide with) 10 riders)
7. Wave Two (kill (collide with)10 lancers)
7. Egg Wave (destroy (step through) 40 eggs)
7. Return to Aviana (get ilvl 288 rare)**

**Comment by Dranah** [comment]
I'll have to sort these to report each quest that is missing prereq.

**Comment by Echinaceax** [comment]
@Dranah 
and info yet ?

**Comment by Kitzunu** [comment]
Fixed after the order here https://wow.gamepedia.com/Wings_Over_Mount_Hyjal

Keep in mind everything in 1) needs to be completed (except breadcrumbs) to unlock 2) so on so forth

**Comment by giles1508** [comment]
to add to this guys,  this quest should NOT be available at ALL until you hand in https://wow.gamepedia.com/Return_to_Nordrassil
which is after you escort fandril and then go speak to ysera only then are you able to take this breadcrumb quest from the NPC called "  Tiala Whitemane     again as i said in a previous quest,   there is a reason why all these quests arent working correcxtly,   its because they arent even supposed to be available,  so trying to fix spawn points for quests that the prequests havent been completed is pointless until we have the prequests fixed,  its cause causing more confusion for the devs who are not familiar with all the questlines and thier orders

**Comment by Dranah** [comment]
The quest order needs fixing first, every other test is irrelevant until then.
