### ISSUE TITLE
[Loot/BOSS] Temple Guardian Anhuur - Halls of Origination (issue 1) (normal)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#2350]
**Links:**
npc - https://www.wowhead.com/npc=39425/temple-guardian-anhuur
zone - https://www.wowhead.com/halls-of-origination

drops - https://www.wowhead.com/item=71637/mysterious-grimoire#dropped-by:0-2-10-9+1
event - https://www.wowhead.com/darkmoon-faire-made-easy-guide
quest - https://www.wowhead.com/quest=29445/an-intriguing-grimoire

**What is happening:**
- Dropping the Mysterious Grimoire (when event darkmoon is on)
- the first boss,  only dropped 1 item instead of 2 
- item drops without having the quest 

**What should happen:**
Should only drop on HC not normal (asfaik)
Shouldnt drop without the quest

**Comment by Rushor** [comment]
loot adjusted 

2 items in nh, 1 in hc. will rework the darkmmon items together with the whole darkmoon faire event in the future.

![I](https://i.imgur.com/imRjIHR.jpg)
