### ISSUE TITLE
[BOSS] Earthrager Ptah - Halls of Origination - normal

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#2351]
**Links:**
https://www.wowhead.com/npc=39428/earthrager-ptah
https://www.wowhead.com/halls-of-origination

**What is happening:**
didn't drop any loot

**What should happen:**
Should drop 
https://www.wowhead.com/item=56097/soul-releaser&bonus=4149
https://www.wowhead.com/item=56095/mouth-of-the-earth&bonus=4149
https://www.wowhead.com/item=56093/breastplate-of-the-risen-land&bonus=4149
https://www.wowhead.com/item=56096/bulwark-of-the-primordial-mound&bonus=4149
https://www.wowhead.com/item=56094/underworld-cord&bonus=4149
https://www.wowhead.com/item=56426/bulwark-of-the-primordial-mound&bonus=4149
https://www.wowhead.com/item=56425/breastplate-of-the-risen-land&bonus=4149
https://www.wowhead.com/item=56425/breastplate-of-the-risen-land&bonus=4149
https://www.wowhead.com/item=56423/underworld-cord&bonus=4149
https://www.wowhead.com/item=56424/soul-releaser&bonus=4149
https://www.wowhead.com/item=56422/mouth-of-the-earth&bonus=4149

should drop two of these after killing it.

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/iLyoEoU.jpg)

in HC one item
