### ISSUE TITLE
[Boss/Loot] Anraphet - Halls of origination -Normal

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#2352]
**Links:**
https://www.wowhead.com/npc=39788/anraphet
https://www.wowhead.com/halls-of-origination

**What is happening:**
dropped 1 normal loot and 2 x hc loot

**What should happen:**
shouldn't drop hc loot on normal mode - should be 2x normal mode loot

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/NCiG5pW.jpg)

2 items in nh, 1 item in hc now
