### ISSUE TITLE
[BOSS] Temple Guardian Anhuur - Halls of Origination -  (issue 2) (normal)

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#2353]
**Links:**
https://www.wowhead.com/halls-of-origination
https://www.wowhead.com/npc=39425/temple-guardian-anhuur
https://www.wowhead.com/spell=74938/shield-of-light
https://www.wowhead.com/spell=75322/reverberating-hymn

**What is happening:**
During this encounter the boss casts shield of light and reverberating hymn and players are meant to run to the levels to deactivate them,
the first time he did this the levels worked, however the second time he did it the second level on the left stopped working making him untargetable
had to use GM commands to kill it - otherwise we wouldn't have been able to progress

**What should happen:**
leaves should work when needed allowing players to attack the boss and kill him - this boss potentially stops players from progressing in the raid

**Comment by Rushor** [comment]
remove flags is needed

**Comment by Rushor** [comment]
okay added that. objects are now always usuable during the fight. make sure that you are CLOSE to the levers while using them. else it will NOT work. thanks.

![I](https://i.imgur.com/OgKfOJV.jpg)
