### ISSUE TITLE
[BOSS/Drop ] Ammunae - halls of origination  (issue 1 ) (normal) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#2354]
**Links:**
boss - https://www.wowhead.com/npc=39731/ammunae#drops:mode=heroic
HC drop - https://www.wowhead.com/item=56421/seedling-pod&bonus=4198

**What is happening:**
Drops HC gear

**What should happen:**
Shouldnt drop HC on normal mode

**Comment by giles1508** [comment]
just to add,  it should drop 2 items from the normal loot table,  just adding as all the other bosses in here are dropping 1 item :)  just want to make sure that doesnt reflect on this after the heroic loot is taken away

**Comment by Rushor** [comment]
2 items in nh and 1 in hc

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/xJCKR9D.jpg)
