### ISSUE TITLE
[BOSS/LOOT] Isiset - Halls of Origination - (normal)

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#2355]
**Links:**
https://www.wowhead.com/halls-of-origination
https://www.wowhead.com/npc=39587/isiset

**What is happening:**
loot table need checking - dropping 2 hc items and 1 normal

**What should happen:**
should drop 2x normal loot

**Comment by Rushor** [comment]
loot adjusted

![I](https://i.imgur.com/0oHT0eP.jpg)
