### ISSUE TITLE
[BOSS/Abilities ] Ammunae - Halls of origination (issue 2 ) (normal)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#2356]
**Links:**
boss - https://www.wowhead.com/npc=39731/ammunae
abilities - https://www.wowhead.com/npc=39731/ammunae#abilities

**What is happening:**
Doesn't do anything 

**What should happen:**
should use abilities

**Comment by bagi84** [comment]
does even melee or move just remains a stationary target

**Comment by giles1508** [comment]
the NPC has 2 spells also which it didnt cast,  1 is disperse,  which is the spell that causes them to split into smaller mobs,   and if memory serves me correctly you can actually kill them before they disperse ,  ill have to do more looking on this.  but in the comments section you will see that things like scatter shot or death grip or things like banish will stop the cast as will not spawn the adds,  so basically you are able to kill them without getting adds   but you have to use certain CC spells to do this,    but yesterday when testing the mobs didnt even begin to cast desperse


and the second is searing flame,  which is just a cast on its target for xxx amount of damage and xx amount over 6 seconds

**Comment by Rushor** [comment]
fixed.

he casts his 3 abilities, summons the plants and casts the grothspell at 100% energy.

![I](https://i.imgur.com/vgbq3ta.jpg)
![I](https://i.imgur.com/ESpCCRg.jpg)
