### ISSUE TITLE
[Quest] Quests missing from inside Halls of Originations - (normal)

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#2359]
**Links:**
Npc - https://www.wowhead.com/npc=28070/brann-bronzebeard
Quest - https://www.wowhead.com/quest=28746/penetrating-their-defenses
and following on Quest - https://www.wowhead.com/quest=28753
from WoWHead or our Armory

**What is happening:**
You receive no quests when speaking to Npc

**What should happen:**
You should receive a quest from NPC to get to control panel at other side of room in dungeon leading on to final quest to kill bosses

**Comment by Rushor** [comment]
prev quest is http://cata.cavernoftime.com/quest=28654

**Comment by Rushor** [comment]
![I](https://i.imgur.com/GpDgs5M.jpg)

okay quests fixed so far
