### ISSUE TITLE
[NPC] Messner - phasing issue - Redridge Mountains

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#236]
Quest - https://www.wowhead.com/quest=26586/in-search-of-bravo-company
Npc - https://www.wowhead.com/npc=43221/colonel-troteman

Issue - After travelling to Alther's Mill as Described in the Quest info Npc https://www.wowhead.com/npc=43270/messner is missing from the cage preventing completing the quest.

Location in retail
![microsoft edge 20_12_2018 16_53_39](https://user-images.githubusercontent.com/45798884/50298968-53cc5f00-0478-11e9-874b-73568f913c99.png)

Same location on PTR
![world of warcraft 20_12_2018 16_53_24](https://user-images.githubusercontent.com/45798884/50298998-69da1f80-0478-11e9-9c8c-54d2559f8a57.png)

**Comment by gantor2** [comment]
I have reached this roadblock aswell, it has something to do with  timeline problems. As you can complete quests out of order resulting in characters missing.

**Comment by Dranah** [comment]
NPC is present but phased. 
It is also phased if you haven't picked up or completed that other quest, so its phase is simply set wrong.
Nonetheless try to complete quests in the right order.

**Comment by Saintres** [comment]
Both quests are bugged. In Search of Bravo Company and Its never over. So i guess not possible to either of them.
