### ISSUE TITLE
[NPC] Living Vine - Halls of Origination

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#2361]
**Links:**
npc - https://www.wowhead.com/npc=40668/living-vine
https://www.wowhead.com/npc=40669/budding-spore

**What is happening:**
The Budding spore is missing 

**What should happen:**
they are supposed to have orange spores on the end which attack you after you kill the vines
the spores are called Budding spore

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/YqbmWnq.jpg)
