### ISSUE TITLE
[Npc] Water Warden -  Halls of Origination (normal)

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#2364]
**Links:**
Npc - - https://www.wowhead.com/npc=39802/water-warden
Ability -- https://www.wowhead.com/npc=41257/water-bubble
from WoWHead or our Armory

**What is happening:**
Just melee attacking not using any abilites

**What should happen:**
npc should spawn water puddles on floor that when touched summon https://www.wowhead.com/npc=41257/water-bubble which trap and slowly kill players unless freed by other players

**Comment by Rushor** [comment]
the puddles just add the slow effect, the miniboss itself will cast the bubbles on the player. once the bubble was killed, the trap effect will be removed.

https://www.youtube.com/watch?v=-zeIlHvEMr0

fixed

![I](https://i.imgur.com/sVnbsnD.jpg):

**Comment by Sammy974** [comment]
@Rushor The boss is doing the bubbles to all the players in the same time, also if they're far from the puddles. With all the players bubbled is impossible to free someone from them.
