### ISSUE TITLE
[BOSS/Abilities] Isiset - Halls of Origination - (issue 2) (normal)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#2365]
**Links:**
https://www.wowhead.com/npc=39587/isiset
https://www.wowhead.com/npc=39587/isiset#abilities

**What is happening:**
Did no abilities

**What should happen:**
Should do the abilities listed

**Comment by Rushor** [comment]
added

![I](https://i.imgur.com/Qbruiqc.jpg)

**Comment by Rushor** [comment]
Also dividing is fixed now

![I](https://i.imgur.com/s2RnO0w.jpg)
