### ISSUE TITLE
[BOSS/Abilities] Rajh -Halls of orginiation - (normal)

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#2366]
**Links:**
https://www.wowhead.com/halls-of-origination
https://www.wowhead.com/npc=39378/rajh#abilities
https://www.wowhead.com/spell=80352
https://www.wowhead.com/spell=87653
https://www.wowhead.com/spell=76355
https://www.wowhead.com/spell=73874
https://www.wowhead.com/spell=73872

**What is happening:**
Only casted four out of the five abilities is uses didn't cast https://www.wowhead.com/spell=80352

**What should happen:**
Should cast all of its abilities

**Comment by Rushor** [comment]
works

https://i.imgur.com/4WeUJZy.jpg

first casttime after around 10 - 25 seconds if enough sunernergy is given.
