### ISSUE TITLE
[NPC] Chaos Portal - Halls of Origination (normal)

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#2368]
**Links:**
https://www.wowhead.com/halls-of-origination
https://www.wowhead.com/npc=41055/chaos-portal

**What is happening:**
these are phased out for the normal players so it appears that they are being attacked by an invisible mob - could only be seen and killed using GM

**What should happen:**
Should be seen and targetable by normal players

**Comment by Rushor** [comment]
fixed that in advance with https://github.com/WoWManiaUK/Blackwing-Lair/issues/2370
