### ISSUE TITLE
[Npc] Void Lord - Halls of Origination (normal)

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#2369]
**Links:**
Npc - https://www.wowhead.com/npc=41364/void-lord
Ability -https://www.wowhead.com/spell=77470 

from WoWHead or our Armory

**What is happening:**
Npc is not using ability once other Mobs are dead Cause him to be motionless and un-kite able. 

**What should happen:**

Should Use https://www.wowhead.com/spell=77470 to grow and become Alive enabling himto use his spells and be kited out of void zone

**Comment by Rushor** [comment]
okay after 30 seconds after the first channel creature in front of him (void seeker) was aggroed he becomes bigger and soon after that he becomes kitable

![I](https://i.imgur.com/NZ3ILo6.jpg)
![I](https://i.imgur.com/GB4QdjY.jpg)
