### ISSUE TITLE
[BOSS/Abilities] Setesh - Halls of Origination - (normal)

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#2370]
**Links:**
https://www.wowhead.com/halls-of-origination
https://www.wowhead.com/npc=39732/setesh#abilities
https://wow.gamepedia.com/Setesh

**What is happening:**
only Auto melee auto attacks

**What should happen:**
should use his ability when fighting against players

**Comment by giles1508** [comment]
boss only drops 1 item of loot also,  should be dropping 2 items

**Comment by Rushor** [comment]
man that boss kills me xD

**Comment by Rushor** [comment]
okay script added so far.

Boss will sttack, use it's SPELL_CHAOS_BOLT, will summon the portals once he got there, and the portal will summon some wyrms, senetils and seekers (depening on hc or nh mode), and will drop 2 items.

![I](https://i.imgur.com/7aYk7aD.jpg)
