### ISSUE TITLE
[Npc] Sun touched Servant - Halls of Origination (normal) issue 1

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#2371]
**Links:**
Npc- https://www.wowhead.com/npc=39366/sun-touched
spell - https://www.wowhead.com/spell=88097
Spell - https://www.wowhead.com/spell=74101
from WoWHead or our Armory

**What is happening:**
NPc is just melee attacking during combat

**What should happen:**
NPc should use his abilites in combat

**Comment by Dranah** [comment]
We don't need two issues for same NPC behavior problem.
