### ISSUE TITLE
[Npc/mechanic] Sun touched Servant  - Halls of Origination (normal) issue 2

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#2372]
**Links:**
Npc -https://www.wowhead.com/npc=39366/sun-touched-servant
EXAMPLE - https://www.wowhead.com/quest=25323/flamebreaker

from WoWHead or our Armory

**What is happening:**
Npc just die like any other mob 

**What should happen:**
Npc should split upon death up to 2 times very similar to npcs in quest https://www.wowhead.com/quest=25323/flamebreaker

**Comment by giles1508** [comment]
the NPC doesnt split upon death as such,  it casts a spell called " disperse ", which is the spell that causes them to split into smaller mobs, and if memory serves me correctly you can actually kill them before they disperse , ill have to do more looking on this. but in the comments section you will see that things like scatter shot or death grip or things like banish will stop the cast as will not spawn the adds, so basically you are able to kill them without getting adds but you have to use certain CC spells to do this, but yesterday when testing the mobs didnt even begin to cast desperse

and the second is searing flame, which is just a cast on its target for xxx amount of damage and xx amount over 6 seconds

**Comment by Dranah** [comment]
NPC is tank and spank, missing its spells.

**Comment by Dranah** [comment]
https://www.wowhead.com/spell=88097/disperse
https://www.wowhead.com/spell=74101/searing-flames

**Comment by Rushor** [comment]
https://www.wowhead.com/spell=74101/searing-flames addedso far, npc summon is missing

**Comment by Rushor** [comment]
Okay this requires even more fixing 
https://youtu.be/8w7382enTfM?t=1690

The big mobs will split in smaller ones and those in even smaller ones. each at around 3 percent health

**Comment by Rushor** [comment]
npc 39366 and 39369 now have a similar script

Every 6 seconds they use EVENT_SEARING_FLAME and every 9 seconds they use EVENT_FLAME_WAVE

Spell depends on heroic or normal mode.

Once the are on low life (around 10 percent) they will split in 2 smaller mobs until Sun-Touched Spriteling is spawned (39370)

**Comment by Rushor** [comment]
Dispersions are fixed now on dev realm https://i.imgur.com/qdtw1tE.jpg https://i.imgur.com/mlH9SbC.jpg https://i.imgur.com/wkowXVu.jpg
