### ISSUE TITLE
[Npc] Garr - Mount Hyjal

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#2373]
**Links:**
npc - https://www.wowhead.com/npc=50056/garr
from WoWHead or our Armory

**What is happening:**
Not spawning in mount Hyjal 

**What should happen:**
Rare npc should spawn at various time in mount Hyjal location

**Comment by Rushor** [comment]
added spawn, path, adds and loot.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/EO489IJ.jpg)
![I](https://i.imgur.com/iwmQHvS.jpg)
