### ISSUE TITLE
[Priest][Shadow] Shadow Power

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2381]
**Links:**
https://imgur.com/IebZnUa

**What is happening:**
The part where critical dmg of shadow spells is increased by 100% does not work. Shadow priest crits are exactly as they should be without this buff, thus proving it does not work. 

**What should happen:**
This passive should increase critical dmg of shadow spells by 100%.

**Comment by Keader** [comment]
Tested and working.
