### ISSUE TITLE
[Quest] The Storm Kings Vengeance

### ISSUE THREAD

**Issue by XxXNumbNutzXxX** [WoWManiaUK/Blackwing-Lair#2382]
**Links:**
https://www.wowhead.com/quest=12919/the-storm-kings-vengeance
from WoWHead or our Armory

**What is happening:**

i tried the mission and was able to control the NPC to move but couldn't attack anything and couldn't use the exit feature to cancel my control of the npc so i forced closed the game and restarted and abandoned the mission
 now im stuck with the buff of gymers buddy and i cannot interact with any npcs or mobs and moving to new areas none are shown unless i relog, but i still cannot interact with anything 

**What should happen:**

[storm king vengance bug.docx](https://github.com/WoWManiaUK/Blackwing-Lair/files/3287693/storm.king.vengance.bug.docx)

**Comment by XxXNumbNutzXxX** [comment]
ok update 

the buff seems to have cleared after a 15 minute period, not sure if i did anything to force that i know i couldnt right click to cancel/clear 
i wont be trying the quest again

**Comment by Rushor** [comment]
alright attacking works so far, but you get no credit

**Comment by sarahkay88** [comment]
#212
