### ISSUE TITLE
[Quest] Reconnaissance Flight - ID 12671 - Sholazar Basin

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2383]
**Links:**
Quest: https://www.wowhead.com/quest=12671/reconnaissance-flight

**What is happening:**
When you accept the quest, you are "not" mounted on a plane. Actually you can see the outline of the plane for a second, but in general nothing is happening then. You can´t complete the quest.
![Reconnaissance Flight - how it is](https://user-images.githubusercontent.com/18005338/59462444-0aa40900-8e24-11e9-91eb-b9997b4b5ea1.png)

**What should happen:**
When you accept the quest, you are automatically mounted onto a plane. From there the plane follows a script.
![Reconnaissance Flight - how it should be](https://user-images.githubusercontent.com/18005338/59462443-0aa40900-8e24-11e9-9659-17c16eb06da0.png)

**Comment by Rushor** [comment]
maybe related to vehicle boarding

**Comment by Echinaceax** [comment]
i completed this a few weeks ago, and could finish quest and have the flight path appear

**Comment by Rushor** [comment]
yeah i tested on dev and it was indeed broke, the vehicle didn't fly and you were not mounted. fixed on dev again :)

**Comment by Echinaceax** [comment]
thanks rusher :)
