### ISSUE TITLE
[NPC] Mistwhisper Warrior/Oracle - ID 28109/28110 - invalid target - Sholazar Basin

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2384]
**Links:**
NPC: https://www.wowhead.com/npc=28109/mistwhisper-warrior
NPC: https://www.wowhead.com/npc=28110/mistwhisper-oracle
for the Quest: https://www.wowhead.com/quest=12538/the-mist-isnt-listening

**What is happening:**
The two mobs are shown as hostile, but they are not attackable. Also they don´t attack you.
![Mistwhisper NPCs invalid target - how it is](https://user-images.githubusercontent.com/18005338/59466766-696e8000-8e2e-11e9-9c17-efcd3ab9cb8e.png)

**What should happen:**
Both NPCs should be attackable and count towards the quest. Especially because there are follow up quests, which are not accessible at the moment.

**Comment by Kitzunu** [comment]
nvm my fix wont work, this is potentially something in core since I cannot find anything wrong in db.

could probably have something to do with ReputationMgr.cpp @Rushor @Keader @wow-mania

**Comment by Rushor** [comment]
realted with the both faction and switching zones https://github.com/TrinityCore/TrinityCore/issues/9469
