### ISSUE TITLE
[NPC] Grot Deathblow 

### ISSUE THREAD

**Issue by Geniuskp** [WoWManiaUK/Blackwing-Lair#2387]
**Links:**
https://www.wowhead.com/npc=49387/grot-deathblow

**What is happening:**
Grot Deathblow <Dragonmaw Clan Quartermaster> does not unlock when u  click; fact that mekes earn` rep very difficult

**What should happen:**
U should be able to open Grot Deathblow <Dragonmaw Clan Quartermaster> by a simple click

**Comment by giles1508** [comment]
This npc is locked because the quest chain to enter twilight highlands is broken,  so he doesn't get unlocked until you complete the quest line,   after you complete the quest line you can then unlock him

**Comment by Geniuskp** [comment]
so fix the quest then or u can unlock the quartermaster like others

**Comment by Kitzunu** [comment]
This is due to him not having any data in `npc_vendor`

```SQL
SELECT * FROM npc_vendor WHERE entry = 49387;
```

I don't know if this was removed because of iLvl restrictions, I haven't been active in that discussion

**Comment by Geniuskp** [comment]
Chain quest still doesn t work <Sauranok Will Point the Way> 28909. Sauranok doesn t spawn so u can t complete the quest

**Comment by Kitzunu** [comment]
I think I understood this issue wrong, I fixed what I understood here https://github.com/WoWManiaUK/Blackwing-Lair/issues/2175
