### ISSUE TITLE
[Spell] Searing Flames

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2389]
Talent ID 77657
Stacking debuff effect spell ID 77661

**How it works atm:** Stacking effect is not consumed when Lava Lash (60103) is used with Improved Lava Lash (77701)
**How it should work:** Stacking effect should be consumed when Lava Lash specced with imp. lava lash is used on target.

Makes enhas OP.
Original report by Gorsky https://github.com/WoWManiaUK/Blackwing-Lair/issues/2324

**Comment by TheSale** [comment]
https://wow.gamepedia.com/Searing_Flames
**Patch 5.0.4** (2012-08-28): Redesigned. When your Searing Totem deals damage or your Fire Elemental lands a melee attack, the damage dealt by your Flametongue Weapon is increased by 8% for 15 sec. Stacks up to 5 times. Your Lava Lash ability will consume this effect, dealing 20% increased damage for each application present. 
this is not 4.3.4 patch

**Comment by Dranah** [comment]
The redesign did not affect this part of the talent. The stacks were consumed on 4.3.4 too.

**Comment by Dranah** [comment]
original report https://github.com/WoWManiaUK/Blackwing-Lair/issues/2120
