### ISSUE TITLE
[Quest] Save the Wee Animals - ID 25385 - Mount Hyjal

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#239]
Quest - https://www.wowhead.com/quest=25385/save-the-wee-animals
NPC - https://www.wowhead.com/npc=39930
Your ment to be able to save these poor animals :(
![world of warcraft 20_12_2018 17_27_21](https://user-images.githubusercontent.com/42302580/50300627-e969ed80-047c-11e9-8124-b67dca29c8ab.png)

**Comment by giles1508** [comment]
came across this today,  had the same issue,  animals not clickable

**Comment by Echinaceax** [comment]
@rusher @Bathelmo something broke :)
Can only see animals in gm on

**Comment by zippoking** [comment]
Now i can´t accept the quest at all.
There is the yellow quest sign above the questgiver, but if i right click on the NPC, nothing happens.

I tried it with 2 different chars.

![Save the animals - how it is 1](https://user-images.githubusercontent.com/18005338/62535186-166fe280-b84b-11e9-863f-58ed09179579.png)

**Comment by Echinaceax** [comment]
@zippoking can you make new report about this (npc issue now)
