### ISSUE TITLE
[Spell] Improved Lava Lash

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2390]
ID 77701
**How it should work:** With this talent, when casting Lava Lash (60103) on a target afflicted by Flame Shock (8050), it should spread the DoT to any nearby enemies (12yrds) as well.
**How it works atm:**
Does not allow Lava lash to spread Flame Shock to nearby targets.

Original report by Gorsky #2324

**Comment by TheSale** [comment]
https://wow.gamepedia.com/Lava_Lash
**Patch 5.0.4** (2012-08-28): Weapon damage reduced from 260% to 250%. Now spreads your Flame Shock from the target to up to four enemies within 12 yards.

**Comment by Dranah** [comment]
prev report https://github.com/WoWManiaUK/Blackwing-Lair/issues/2120
