### ISSUE TITLE
[Dungeon Finder]   Heroic lockouts + RaidLockout

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2393]
**Links:**

http://us.battle.net/wow/en/game/patch-notes/4-3-0#dungeons   
this is a link that will take you to a changelog for 4.3 and its set on the duneon finder part,   dont scroll,  read from here

**What is happening:**

ok basically at the moment,  players can only do each  heroic once per day, and then they can no longer queue for random heroics without getting the same shadowfang keep heroic over and over

**What should happen:**

in 4.3 blizzard changed it so you dont ever get locked to a heroic instance if you queue via the random finder,  you only get locked if you enter manually,   or queue specific

and even then , even if you was locked to a specific instance you could still get any random heroic all day every day by queuing for it on the random finder,   at the moment this is causing ques for heroics to become massive because peopel do not want to do shadowfang keep over and over,   they want to be able to get different ones like it should be.

this makes matters worse with the current new low population, as very limited people are doing heroics as it is,  without only doing 6 a day then stopping

we need to remove the lock for random finder for heroic and make it so you only get locked when you want to queue specifically for 1 instance,  and again even after queue do a heroic specifically you should still be able to queue for randoms all day and randomly get any available heroic that we have open

**Comment by Dranah** [comment]
so if I understand well, this feature only works for SFK atm and that means the menu is endless SFK once people are saved to all else?

**Comment by giles1508** [comment]
you are 100 % correct
but the only trouble is,  SFK  doesnt give JP for killing bosses but the rest of the heroics do  :)

**Comment by Dranah** [comment]
Is that reported? If not please go ahead.

**Comment by giles1508** [comment]
When I'm at my pc I will, pain on the phone

**Comment by giles1508** [comment]
any idea how this will be fixed ?  people are getting sick of the same heroic all the time now :(

**Comment by giles1508** [comment]
came accross something today which i overlooked,   most guilds have like only a few players geared for heroics,  and today i noticed that i was in group as a tank,  and there was a group looking for a tank , but it couldnt put me with them in dungeon finder because i was saved to different instances than they were :)   there was  3 different groups all looking for different roles because the people in queue couldnt join together because they all were saved to different things haha :)

**Comment by giles1508** [comment]
referenced above as this needs to be addressed.   the vote kick option not working,  combined with this heroic lockout not working is really causing players issues,  as stated on the referenced ticket,  players are doing afk or alt -f4 rage quit,  and then your locked to an instance that you cannot finish as you cannot kick and you cannot come back to do it as you are saved...  these 2 issues really need to be sorted,  as player base is slowly increasing so it the amount of queues that are increasing,  and more and more players are doing heroics now,   and its becoming an issue,   as you cannot queue with friends as they are saved and your not... needs addressing ,  both issues

**Comment by Thiay** [comment]
Having this few dungeons and getting a lockout once completed with the dungeon-finder really makes the game very limited right now, this issue should be addressed as fast as possible, together with the implementation of the rest of the dungeons

**Comment by Sevenblade11** [comment]
With the low population on the server, this needs to be fixed. Without it, doing dungeons with guildies, friends, etc, is extremely hard and annoying. This is shown when a group of people, which each of them did two or so dungeons each, can't que together because the lack of ID's, and furthers the time in que. In addition, farming rep and gear becomes frustrating. The frustration can be increased tenfold when a boss becomes bugged or people d/c and/or leave to the point where one would have to wait the CD to attempt the dungeon again with the random que.

**Comment by Slydee23** [comment]
Any progress ?

**Comment by Rushor** [comment]
will give it to you keader. not sure where to fix that

**Comment by Rushor** [comment]
RaidLockout is also affacted by an issue. it shoud always be 7 days! :>

**Comment by Rushor** [comment]
moved to https://github.com/WoWManiaUK/Blackwing-Lair/issues/4011
