### ISSUE TITLE
[Dungeon/NPC] Deadmines combat bug

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2394]
This is currently a giant extra difficulty to the lvl 85 heroic mode of the instance. (i can't even imagine how lvl 20s deal with it if they do at all...)

As soon as players zone in, they engage these invisible level 20 stormwind guards (NPC ID 50595) standing at the entrance, and they keep the party in combat throughout the entire instance.

With cataclysm having vastly redesigned the style of healing to the point of being extremely needy on mana management, and blocking healers mana regen in combat instead of while-casting, this means the healers are completely unable to regen mana and the instance takes twice as long as necessary because everyone is always waiting for the mana to grow a bit so they won't oom halfway through the next pull.

This should not be difficult to fix and would be a major quality improvement to the dungeon.

PS: remove the NPCs or make them not attack players.

**Comment by Dranah** [comment]
![WoWScrnShot_061519_025200](https://user-images.githubusercontent.com/31132743/59545058-6f8d5b00-8f19-11e9-8eb0-d7253b679210.jpg)
these guys ^

**Comment by Dranah** [comment]
PS: for alliance, the problematic mob is the shattered hand assassin, ID 46890

**Comment by giles1508** [comment]
tested same time on live and thorns killed the 2 npc's  (  im horde )

**Comment by Dranah** [comment]
It seems you can counter this with Ret aura as well, so it ain't that urgent.

**Comment by Kitzunu** [comment]
Should these mobs be visible for the oposite faction?

**Comment by Dranah** [comment]
Nope, as far as I see on videos, each faction only sees their own faction NPCs on retail.

Entering as a **horde** you should be able to see the shattered hand guys, and the 3 quest giver NPCs to the left, Miss Mayhem, Kagtha, and Slinky Sharpshiv and their shredders and vendotron.
IDs: 46890, 46903, 46902,46889,46906, 24935

You should not see the other, alliance NPCs as horde and they should not attack you from their phase.

Entering as alliance, you should also see only ally NPCs, and not the horde ones. 
Ally visible npcs: 50595,46613,46614,491,46612,24935

Currently all NPCs are invisible to everyone but they attack hostile players in the other phase.
This not only causes combat bug, but players cant access the quests belonging to the instance.

**Comment by Kitzunu** [comment]
Ok, should fix it by making the npcs civilians :D 

I will get on it when I get time

**Comment by Rushor** [comment]
will fix that core side by team in instance checks. this concerns several instances

**Comment by Kitzunu** [comment]
Coolio

**Comment by Dranah** [comment]
Combat bug is gone, but so are all NPCs. Need own faction NPCs visible.

**Comment by Rushor** [comment]
next try

**Comment by Dranah** [comment]
Players can now see both types of NPCs on both factions.
Might be a little heavy for lvl 20s when they start getting attacked on loading screen.

**Comment by Rushor** [comment]
team in instance check seem to be broken in general atm

**Comment by Dranah** [comment]
well this could be pushed until a better fix is made. this can already prevent combat bug, since you can kill hostile npcs.

**Comment by Rushor** [comment]
finally fixed

![](https://i.imgur.com/mqM1jdT.jpg)
![](https://i.imgur.com/QP8Ohsl.jpg)
