### ISSUE TITLE
[Spell] Shadow Orbs

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2396]
ID 95740

They are properly granted with a chance as a buff when using mind flay / SWP.
They are even consumed when you cast Mind blast or Mind spike, proccing the empowered shadow buff instead.

Problem is, they do not add damage boost to the Mind Blast 8092/ Mind Spike 73510 that consumes them.

**How it should work:**
The Shadow Orbs consumed should increase the damage of the Mind blast / Mind spike that consumes them by 10% per orb (modified by mastery!)

PS: high priority as shadow priests are currently worthless

**Comment by Keader** [comment]
lul, i dont know that.
Fixing today :)

**Comment by Dranah** [comment]
Recalculated. Mastery applies wrong here.
Mastery should increase the damage done by each shadow orb, so it isn't 10+10+10 + mastery for 3 orbs, but it should be 3x (10+mastery)
Right now, mastery is only counted once, no matter the orb count.

**Comment by Dranah** [comment]
Mastery now affects each orb.
