### ISSUE TITLE
[Spell] Empowered Shadow

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2397]
ID 95799

This effect procs when Shadow Orbs 95740 are consumed by Mind Blast or Mind Spike.

Its power is supposed to scale with mastery, just like the main effect of Shadow Orbs.
The tooltip should show 10% + mastery value added, no matter how many shadow orbs were consumed.

**How it works atm:**
ID 77446 (Mastery: Shadow Orb Power) currently does not affect it, so it always grants a flat 10% increase to periodic damage effects.
Also the tooltip is wrong and shows % to scale with how many shadow orbs were consumed (shows 10% if one, 20% if two, 30% if three), however this is confusing and wrong, the effect of Empowered Shadow has no scaling with orb count. The effect of mastery is however not displayed, which it is intended to scale with.

**Comment by Keader** [comment]
Tooltip is showing exactly what it is adding to you.
Was fixed in 10,20 and 30% because  core was not support to mastery in time that it was scripted.
Now it has, so... implemented.
In the end, it will give you (10% * OrbCount) + 1.45% for each mastery point

**Comment by Dranah** [comment]
This is just wrong. By all evidence I have, Empowered Shadow doesn't have a scaling effect with orb count. No matter if you proc it with 1 orb or 3 consumed, it should give same buff: 10% + mastery.

**Comment by Dranah** [comment]
Some links:
https://eu.battle.net/forums/en/wow/topic/1302705671
"Maintain ES Buff, This is our Mastery, the Buff will increase your DoT damage by a percentage dependant on how much Mastery you have. This effects VT, SW:P, DP and MF. Keep it active at all times by using up **whatever** shadoworbs you have using MB. "
https://eu.battle.net/forums/en/wow/topic/916822046

Dozens of discussions going on about it, each say it doesnt matter if you proc the buff with 1 orb or 3.

**Comment by Dranah** [comment]
Looks good, the buff now gives same benefit no matter how many orbs proc it. It scales with your mastery.
