### ISSUE TITLE
[NPC] Grot Deathblow not fixed

### ISSUE THREAD

**Issue by Geniuskp** [WoWManiaUK/Blackwing-Lair#2398]
Chain quest still doesn t work 28909. Sauranok doesn t spawn so u can t complete the quest after u complete the board one to Garosh

**Comment by Echinaceax** [comment]
Kitz only fixed and confirmed this 12 hours ago "in dev" not on live yet https://github.com/WoWManiaUK/Blackwing-Lair/issues/2387
