### ISSUE TITLE
Zul'Drak Arena

### ISSUE THREAD

**Issue by Icyytouch** [WoWManiaUK/Blackwing-Lair#2400]
**Links:**

from WoWHead or our Armory

**What is happening:**
After I finish the champion's call quest goblin doesn't give me chain quest... Plz fix it

**What should happen:**

 After the champion's call quest when I finish It at goblin NPC according to few people who have successfully done it, the goblin should give me the arena chain quest and quest chain should start.

**Comment by Rushor** [comment]
has this not been fixed some time ago @Kitzunu ?

**Comment by Dranah** [comment]
Last report/fix about it: https://github.com/WoWManiaUK/Blackwing-Lair/issues/2339
I'm nearly sure it is responsible. Reopened that one

**Comment by Icyytouch** [comment]
No I tried doing it yesterday, the quest npc doesn't give me quest...

**Comment by Icyytouch** [comment]
Hello there,

I just signed the petition "Office of the High Commissioner for Human
Rights: URGENT PETITION ON THE UN KASHMIR REPORT" and wanted to see if you
could help by adding your name.

Our goal is to reach 200,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/mfT86hXD8X

Thanks!
Talha
