### ISSUE TITLE
[Profession boost in mail]  not showing icons or allowing spell to open

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2401]
**Links:**

No links this is custom issue from mall

**What is happening:**

currently players who boost professions from the mall,  are set to 450 skill on that said profession,  however they cannot see the icon or use the spell,  even after learning the recipies from trainer you still connot use it, i tested today with 3 different professions before i had to go shopping

below is some screens and explinations

![WoWScrnShot_061519_174503](https://user-images.githubusercontent.com/50211643/59556743-c0578f00-8fbf-11e9-9a9c-1b4030e0b56c.jpg)

in this one you can see i have just boosted up to 450 in Jewelcrafting and as you can see in the chat box its telling me i have learned the different types of professions
but as you can see in the below screen  thats not the case

![WoWScrnShot_061519_175220](https://user-images.githubusercontent.com/50211643/59556758-fac12c00-8fbf-11e9-9543-e55fa37f2680.jpg)

in this above screen you can see that i have learned all the available designs from the trainer and it will not let you learn more.....

now i found a way around this,   i managed to learn them all,  but the way i did this was to UNLEARN the profession and then RELEARN it from the trainer,  this somehow allowed the server to think i still had 450 skill and allowed me to buy them all again but for gold,  which takes alot away from the boost

I also did this again with blacksmithign and engineering

same thing but i scrolled down on the blackmisthing trainer this time and noticed that the professions were still there waiting to be learned and also in the other screenshot you can see that the apprentice blacksmithing one is available to learn,  but becaus ethe system thinks its learned it ,   it will not let me learn it again

![WoWScrnShot_061519_180042](https://user-images.githubusercontent.com/50211643/59556794-dc0f6500-8fc0-11e9-86bd-eaa646d0af1f.jpg)

![WoWScrnShot_061519_182924](https://user-images.githubusercontent.com/50211643/59556798-f8130680-8fc0-11e9-84a2-50b487540dc5.jpg)

also to add to ALL of this,   as i didnt emphasise it enough above,  after you pay to boost a prof,   and then unlearn the profession,   you can still go back and visit the trainer and learn all the way back to 450 again....  this could cause people to explit professions by unlearning them,  then taking another profession and making something,  then unlearning that again and basically keep doing that over and over

**What should happen:**

so what i believe should happen is that when you boost a profession from the Mall for MP  you should then be able to go to a trainer to learn the next step to 525, and not have to spend all the gold relearning the skills over again

im not sure how you will be able to fix this,   i know what i personally would like to happen,   but i wont mention that here :)

**Comment by Kitzunu** [comment]
You dont learn any skills.

You boost for MP to get the skill but you have to learn the spell for the profession

**Comment by giles1508** [comment]
Did you not read any of that lol? The point of the post is,  that after you boost,  you cannot physically go any further than 450....the post isn't about having to buy the spells.... The post is about after boosting you can no longer get the next step from 450 to 525 without unlearning the profession and then relearning it and buying it all over again... This is broken,  please have a read over again as I think you may have missed out bits :)

**Comment by Kitzunu** [comment]
I just added that info as a clarification for whoever decides to fix it since it is core related, dw bout it mate
