### ISSUE TITLE
[Quest] Competition Schmompetition - Northern Barrens

### ISSUE THREAD

**Issue by Ranger-Bill** [WoWManiaUK/Blackwing-Lair#2402]
The Competition Schmompetition quest in the barrens is not working correctly. The Mobs that are supposed to drop the notes are not dropping them.

**Comment by giles1508** [comment]
going to need a little more than this my friend,  devs need links to quests and npc's   thats why we have a template available

**Comment by Rushor** [comment]
https://www.wowhead.com/quest=29086/competition-schmompetition
