### ISSUE TITLE
[Spell] Feign Death

### ISSUE THREAD

**Issue by Zyconic** [WoWManiaUK/Blackwing-Lair#2404]
Feign Death should be removing the hunter from targeting from other players. 

When used, the players targeting is not cleared.

**Comment by giles1508** [comment]
hi,  can you please pop some links in here for the devs etc,  devs dont always play they are sometimes just coding for work :)  so need links to spells with ID's etc,  thats why we have the template :)  thanks

**Comment by gitkulu** [comment]
https://www.wowhead.com/spell=5384/feign-death
