### ISSUE TITLE
[talent] Death Knight Talent - Will of the Necropolis

### ISSUE THREAD

**Issue by fuzzydunlop** [WoWManiaUK/Blackwing-Lair#2406]
**Links:** https://cata-twinhead.twinstar.cz/?spell=81164

**What is happening:** The visual effects of this talent activating do occur (the glowing outline of rune tap on spellbar, symbol at topright, and the reddish bar above your character). However, it does not reset the cooldown, or make the rune tap free.
I'm uncertain if the 25% dmg reduction does work.

**What should happen:** The cooldown of rune tap should be reset and it should cost no blood runes, so that you can instantly use it.

**Comment by kDracku** [comment]
Can confirm about Rune Tap , the damage reduction works

**Comment by Bloodborne93** [comment]
Same, Reset Cooldown still don't work, damage reduction works well.

**Comment by fuzzydunlop** [comment]
Rune tap proc part is not fixed yet.

**Comment by Keader** [comment]
@fuzzydunlop what part?
everything works for me.
Can you provide reproduce steps?

**Comment by kDracku** [comment]
If you have cooldown on rune tap when will of the necropolis proc the cooldown its not reset

**Comment by Keader** [comment]
rofl, was reseting blood tap cooldown :P
