### ISSUE TITLE
[NPC] Cursade Commander Korfax - Quest Interaction - Eastern Plaguelands

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2412]
**Links:**
NPC: https://www.wowhead.com/npc=16112/crusade-commander-korfax
Quest: https://www.wowhead.com/quest=27614/scarlet-salvage
Quest: https://www.wowhead.com/quest=27615/the-wrathcaster
Quest: https://www.wowhead.com/quest=27616/the-huntsman
Quest: https://www.wowhead.com/quest=27619/the-commander

**What is happening:**
As soon as you accept one of the quests he´s offering, the others become unavailable. 
This used to work before, because i reported issues regarding the other quests. But now you can do only one.

**What should happen:**
You should be able to access all four quests at the same time.
![Crusade Commander Korfax - how it should be](https://user-images.githubusercontent.com/18005338/59564853-f2aece00-904b-11e9-85d1-e7ebd4cf42bb.png)

**Comment by Kitzunu** [comment]
fixed
