### ISSUE TITLE
[Profession] [Engineering] Discovery

### ISSUE THREAD

**Issue by Imba232** [WoWManiaUK/Blackwing-Lair#2416]
**Links:**

**What is happening:**

Crafting a cataclysm recipe should have a chance to discover a random tinker enchant. I made like 100+ and didn't discover any yet and since there are some, maybe it's not working.

**What should happen:**

Crafting a cataclysm recipe should have a chance to discover a random tinker enchant.

**Comment by Geniuskp** [comment]
Confirm!

**Comment by wow-mania** [comment]
Saying confirm is not confirming anything. :)

PLease link evidence or this will be close.

**Comment by Dyr303** [comment]
Crafted over 2k obsidium bolts and still no new tinker discovered

**Comment by Dranah** [comment]
https://wowwiki.fandom.com/wiki/Tinker_(engineering)
players report to not receive the procs
to me it's valid enough

**Comment by Sammy974** [comment]
Any chance to fix it soon? :)

**Comment by Rushor** [comment]
all spells: 82180, 82175, 82200, 82177, 84424,
84427, 82774, 84425, 82201

**Comment by Rushor** [comment]
> Crafted over 2k obsidium bolts and still no new tinker discovered

just a reminder. chance to get a new recipe from crafting that item is only 1 percent. other spells have higher chance to learn a new spell

**Comment by Rushor** [comment]
fixed fo a large amount of spells

![I](https://i.imgur.com/JzWgzoB.jpg)
