### ISSUE TITLE
[Dungeon/Loot] Shadowfang Keep Heroic

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2417]
**Links:**

https://www.wowhead.com/shadowfang-keep#drops:mode=heroic

**What is happening:**

Shadowfang keep heroic isnt giving justice points for bosses you kill like every other heroic instance does 

**What should happen:**

should give you 75 justice points every time you kill a boss in just the heroic version of this instance and NOT the normal version

**Comment by wow-mania** [comment]
As-is.

**Comment by giles1508** [comment]
can you please tell me why this was closed and why you have commented with as-is ?     every heroic 5 man boss should always give justice points,  always.   why is this being pushed aside ?

**Comment by Dranah** [comment]
Is it not possible to fix so that only heroic gives JP?

**Comment by Rushor** [comment]
on dev you get justice points? hmm

![](https://i.imgur.com/eWVyRrf.jpg)

**Comment by Rushor** [comment]
@Dranah

**Comment by Dranah** [comment]
Aye, it does. Must have been some random glitch for @giles1508

**Comment by giles1508** [comment]
you realise
you went to deadmines
and killed a boss there :)
try going to heroic shadowfang keep and kill one there

**Comment by giles1508** [comment]
removing cannot reproduce until correct instance is confirmed :)

**Comment by Dranah** [comment]
Lol rushor and I were working on the deadmines cb bug and it burnt into our mind.

**Comment by Dranah** [comment]
![WoWScrnShot_061819_111752](https://user-images.githubusercontent.com/31132743/59669567-c1084500-91ba-11e9-88f8-b53e9a879e56.jpg)

**Comment by giles1508** [comment]
its all good,  i laughed like mad when i saw the pic :D

**Comment by Rushor** [comment]
oh holy moly yes. shadowfang killed our mind haha 

sorry

**Comment by Dranah** [comment]
deadmines did
man you mixing it again :D

**Comment by Kitzunu** [comment]
You guys XD

Fixed, also will bind you to the instance when you kill the boss

**Comment by Kitzunu** [comment]
Confirmed by @giles1508 and @Kitzunu
