### ISSUE TITLE
[Spell] Shadowmeld racial 58984

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2418]
**Links:**
https://wow.gamepedia.com/Shadowmeld
from WoWHead or our Armory

**What is happening:**
Mobs stay on you even you go in stealth and keep attacking
it happen during leveling and on max level

**What should happen:**
It should drop all aggro, leave combat and reset mobs 

**Similar issues**
Roque vanish has same issues
https://github.com/WoWManiaUK/Blackwing-Lair/issues/2057

**Comment by Rushor** [comment]
https://i.imgur.com/MBopdZO.jpg 
https://i.imgur.com/ObkkDqQ.jpg
