### ISSUE TITLE
[Quest] Twilight Hylands - 28170/night-terrors

### ISSUE THREAD

**Issue by Brockers1** [WoWManiaUK/Blackwing-Lair#2419]
**Links:**
https://www.wowhead.com/quest=28170/night-terrors

**What is happening:**
npc=47826/uchek doesn't place you the trance/spirit realm to use the item

**What should happen:**
npc=47826/uchek should put you into the spirit realm so you can use 'The Light of Souls' to cleanse three shrines in 'The Gullet', 35.0 36.6.

![WoWScrnShot_061619_223100](https://user-images.githubusercontent.com/51338997/59569803-800f1400-9086-11e9-9062-d80b9befda7b.jpg)

**Comment by Rushor** [comment]
okay the quest requires you to get the realm spell and then walk around to the shrines, there you will get the questcredit. https://www.wowhead.com/quest=28170/night-terrors#videos:id=96720

**Comment by Rushor** [comment]
https://i.imgur.com/dlpj3e5.jpg
https://i.imgur.com/zvDuVma.png
