### ISSUE TITLE
[Quest] Gather the intelligence - ID 25296 - Mount Hyjal

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#242]
Quest - https://www.wowhead.com/quest=25296/gather-the-intelligence
NPC - https://www.wowhead.com/object=202701
QUEST ITEMS - https://www.wowhead.com/item=52724/twilight-communique, https://www.wowhead.com/item=52725/hyjal-battleplans
92.0,51.5 - is were the battle plans should be located
89.5,55.5 is were the communicator should be located

**Comment by sarahkay88** [comment]
![world of warcraft 20_12_2018 18_09_27](https://user-images.githubusercontent.com/42302580/50302981-96dfff80-0483-11e9-90ed-1c0e44d02774.png)
![world of warcraft 20_12_2018 18_10_25](https://user-images.githubusercontent.com/42302580/50302983-98a9c300-0483-11e9-85b4-11dbbc05d7c9.png)
searched the whole area nowhere to be seen

**Comment by sarahkay88** [comment]
added note from kitz 

https://www.wowhead.com/object=202968 https://www.wowhead.com/object=202969 Entries of the missing objects. (Check the loot table in db too!)
--

**Comment by Rushor** [comment]
https://i.imgur.com/f94HnIc.jpg
