### ISSUE TITLE
[Talent] [Spell] Impact - Talent ID 12357

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2425]
**Links:** 

https://puu.sh/DH7py/0852e9dcd4.png
https://wowwiki.fandom.com/wiki/Impact

**What is happening:**

On use, fire blast with Impact's proc spreads
- Ignite,
- Living Bomb,
- Combustions

Launch a whole Pyroblast on nearby (<10m) target  if main target had pyroblast's DoT.

Spread DoTs, but refreshes it on maximum duration instead of remaining time.
(A living bomb will stand for 12 seconds after spread instead of the timer on the main target where the Fire blast + Impact has been used)

**What should happen:**

DoTs should be spreaded on target within 10m.
No subsequent spells should be launched automaticaly
Nearby target should get remaining DoTs timers isntead of refreshing it to maximum duration.

**Comment by sarahkay88** [comment]
#816

**Comment by Cenasty** [comment]
I saw these thread and I never saw Impact failing to reset the cooldown 
Plus, I tryed pyromaniac's thread before sending this thread. It worked even I think spread only work if you don't kill the kill. If it kills it, I don't think it'll spread.

**Comment by Keader** [comment]
> DoTs should be spreaded on target within 10m.

Wrong. Spell has 12 yards radius. So it will spread to targets with distance > 10 yards.

> No subsequent spells should be launched automaticaly

Wrong, it can make other talents proc.

> Nearby target should get remaining DoTs timers isntead of refreshing it to maximum duration.

The only thing that may is a issue.
Has any proof about it? i realy not sure about this one.

**Comment by Keader** [comment]
Ah yes, you are correct about timers.
Fixing it.

**Comment by Cenasty** [comment]
> > No subsequent spells should be launched automaticaly
> 
> Wrong, it can make other talents proc.
>
About this one. I just checked a video on Halfus Wyrmbreaker done on officiel server (US Illidan-PvP)
https://youtu.be/yO23-64OX0U?t=74 

Timer about 1:10.
You'll see a pyroblast proc.
He'll use it on his main target (Time Warden)
He'll use Impact in order to spread DoTs
A secondary pyroblast is not launched as it is (atm) on the server.
But Halfus Wyrmbreaker (foca, on the right of the screen) will have Combustion + Pyroblast (DoT)

**Comment by Keader** [comment]
Ahh, now i got what you mean with "no subsequent spells"

**Comment by Keader** [comment]
Hey @Cenasty i tried for 2 hours, but the only way that i can handle with it is 2:

1 - Dont let impact spread , proc Pyromaniac
2 - Let it make animation, but it will proc pyromaniac correctly.

So we need make a choice here. :/

**Comment by Cenasty** [comment]
Thanks for trying, but I didn't really got the point

1. What do you mean by 'Don't let Impact Spread' ? Isn't it the basic of the talent ?
2. By animation do you mean the subsequent pyroblast on nearby target ? (Which will trigger pyromaniac by having multiples pyroblast applying DoTs ?
The fact is (if I understood the 2nd choice), Making an animation to launch pyroblast on nearby target will make that nearby are gonna take the initial hit of the pyroblast.
So instead of just taking the XXXX amount from Pyroblast's DoT, they will take an additional YYYY amount from pyroblast initial hit (which shouldn't exist when you spread using Impact)

**Comment by Keader** [comment]
If i make initial damage = 0, but make animation of pyroblast flying into target?

**Comment by Cenasty** [comment]
It would be blizzlike in term of damage and DPS.

Like 'Launch Pyroblast on every nearby target within 12 yards from the initial main target who has taken Impact AND who suffered from an existing Pyroblast's DoT.

But it'll make another problem, since it'll be a new animation, the DoT will be 'refreshed' I guess ? 

Like
Initial target with 5 sec remaining Pyroblast's DoT
- Takes Impact
- Every nearby within 12 yards (etc..)
- Each target in range will be affected by a 12 sec pyroblast's fresh DoT ?

**Comment by Keader** [comment]
No, i will change pyroblast duration to original duration
it will do 0 damage
the only bad issue is animation of a big fire ball flying to targets xD

**Comment by Cenasty** [comment]
If DoTs are correctly 'spreaded' by the moment you use Impact, with the **good damage** with the **right duration** and **triggers Pyromaniac,** on **all nearby target** I don't see any problem for cosmetics animation.
Low res/computer are gonna cry a little more on Halfus Wyrmbreaker but it's fine haha

**Comment by Dranah** [comment]
Confirmed the following issues:
1) Duration of spreaded dots is full time instead of remaining
2) Whole new pyroblast/frostfire bolt spell is launched to nearby targets instead of only transfering the DOT
3) Living Bomb can be spreaded to more than 3 targets (ignores the 3target limit)
4) Combustion spreaded to new targets does not do the same damage as the one on the original target. The copied DOT damage must match the original.

**Comment by Cenasty** [comment]
Any further developpment to this bug ?

Currently, we can reach 60k on a 6-7 mob pack just by casting a single pyroblast and spamming Impact on this target.

**Comment by Keader** [comment]
Sorry, i forgot about this one.
Back to work on it.

**Comment by Cenasty** [comment]
Impact can still spread more then 3 Living bombs and ignore Living Bomb's limit target.

https://puu.sh/DW0o6/8319ea8fa7.png

**Comment by Keader** [comment]
It's another problem, will be fixed soon @Cenasty

**Comment by Dranah** [comment]
1) DoT duration fixed.
2) The pyroblast is fixed, it only copies the dot now, however frostfire bolt still works the old way, launches an entire copy of the spell to all nearby targets. That needs fixing.
3) @Keader Can you reference the other thread for this living bomb issue?
4) Combustion damage on secondary targets is still way lower than the original.
