### ISSUE TITLE
[Spell] Ice Block - Spell ID 45438

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2426]
**Links:**

from WoWHead or our Armory

**What is happening:**

Using Ice Block while falling with speed (i.e unmounting from a flying mount going forward) will cancel your speed and you will fall verticaly instead of going a little forward.

**What should happen:**

Ice block shouldn't prevent you to go forward while falling and using it.

**Comment by sarahkay88** [comment]
Umm doesn't ice fall straight down 😂

**Comment by Keader** [comment]
Realy?
We have issues more important now, so i'm closing it since is a cosmetic bug and i realy not sure if is a real issue.
