### ISSUE TITLE
[Item] Keys to the hot rod - kezan

### ISSUE THREAD

**Issue by Guardian4Shadow** [WoWManiaUK/Blackwing-Lair#2427]
https://www.wowhead.com/item=46856/keys-to-the-hot-rod#comments

When you stay on car, you can't talk to npc (like npc for quest "Rolling with my Homies" 

If you see offy you can do it.

**Comment by Rushor** [comment]
maybe this was intended o retail on 4.x?

**Comment by gamer100** [comment]
@Rushor  
Still cant talk to npc whenyou are in the hot rod, you have to  get out  before  you  can interact
