### ISSUE TITLE
[Profession] [Alchemy] Mixology

### ISSUE THREAD

**Issue by Imba232** [WoWManiaUK/Blackwing-Lair#2429]
**Links:**

https://www.wowhead.com/spell=53042/mixology

**What is happening:**

It doesn't give increase duration or effect.

**What should happen:**

Mixology should increase the duration of flask from 1hr to 2hrs and the effect from 300 to 380.

**Comment by Rushor** [comment]
test

**Comment by Rushor** [comment]
In unit.cpp there is "Mixology - duration boost" section for 53042 @Keader

**Comment by Echinaceax** [comment]
tested just now, and i see no issue withe this on live 

![pot1](https://user-images.githubusercontent.com/39439201/67287138-d4198180-f4da-11e9-9dae-c0adc63e0424.jpg)
![pot 2](https://user-images.githubusercontent.com/39439201/67287141-d54aae80-f4da-11e9-82bd-d7fd435969ab.jpg)

Maybe a launcher issue @Imba232

**Comment by Rushor** [comment]
code seems fine for me aswell and works fine so far for my test aswell (the duraion part)

**Comment by Imba232** [comment]
Oh you tested 4 months after I posted this, that's great. 
Not that I care about your bugged server anymore but this is in the comments in the link that I provided "This is patently incorrect. All buff tool tips are not updated based talents or abilities, but they still have the increased effect. You can easily verify that a Cataclysm flask has an 80 point increased effect for Alchemists because of Mixology. For example, a  Rogue using  Flask of the Winds will receive a 380 Agility point increase rather than a 300 Agility point increase (399 Agility points after +5% from (Spell #86531))."
And it's supposed to increase the duration and effect only on flasks/elixirs YOU ARE ABLE TO MAKE, as an alchemist that is.
Goodluck.

**Comment by Rushor** [comment]
> and the only comment i see is that they say it should increase too 265 with the mixoliogy

that's right.

a possible fix in spellaura effetc is:

// Mixology - Effect value mod
    if (caster && caster->GetTypeId() == TYPEID_PLAYER)
    {
        if (GetSpellInfo()->SpellFamilyName == SPELLFAMILY_POTION && (
            sSpellMgr->IsSpellMemberOfSpellGroup(GetId(), SPELL_GROUP_ELIXIR_BATTLE) ||
            sSpellMgr->IsSpellMemberOfSpellGroup(GetId(), SPELL_GROUP_ELIXIR_GUARDIAN)))
        {
            if (caster->HasAura(53042) && caster->HasSpell(GetSpellInfo()->Effects[0].TriggerSpell))
            {
                switch (GetId())
                {
                    case 53760: // Flask of Endless Rage
                        amount += 64;
                        break;
                    case 53755: // Flask of the Frost Wyrm
                        amount += 47;
                        break;
                    case 53758: // Flask of Stoneblood
                        amount += 650;
                        break;
                    case 54212: // Flask of Pure Mojo
                        amount += 30;
                        break;
                    case 17628: // Flask of Supreme Power
                        amount += 23;
                        break;
                    case 17627: // Flask of Distilled Wisdom
                        amount += 20;
                        break;
                    case 28519: // Flask of Mighty Restoration
                        amount += 20;
                        break;
                    case 28540: // Flask of Pure Death
                        amount += 23;
                        break;
                    case 42735: // Flask of Chromatic Wonder
                        amount += 4;
                        break;
                    case 28521: // Flask of Blinding Light
                        amount += 23;
                        break;
                    case 28518: // Flask of Fortification
                        if (m_effIndex == EFFECT_0)
                            amount += 221;
                        else if (m_effIndex == EFFECT_1)
                            amount += 5;
                        break;
                    case 53752: // Lesser Flask of Toughness
                        amount += 32;
                        break;
                    case 62380: // Lesser Flask of Resistance
                        amount += 32;
                        break;
                    case 60341: // Elixir of Deadly Strikes
                        amount += 16;
                        break;
                    case 8212: // Elixir of Giant Growth
                        if (m_effIndex == EFFECT_0)
                            amount += 5;
                        else if (m_effIndex == EFFECT_1)
                            amount += 5;
                        break;
                    case 79469: // Flask of Steelskin
                    case 79470: // Flask of the Draconic Mind
                    case 79471: // Flask of the Winds
                    case 79472: // Flask of Titanic Strength
                    case 94160: // Flask of Flowing Water
                        amount += 80;
                        break;
                    case 79635: // Elixir of the Master
                    case 79468: // Ghost Elixir
                    case 79474: // Elixir of the Naga
                    case 79477: // Elixir of the Cobra
                    case 79481: // Impossible Accuracy
                    case 79632: // Mighty Speed
                        amount += 40;
                        break;
                    case 79480: // Elixir of Deep Earth
                        amount += 120;
                        break;
                    case 79631: // Prismatic Elixir
                        amount += 15;
                        break;
                    default:
                        amount *= 1.3f;
                        break;
                }
            }
        }
    }

    amount *= GetBase()->GetStackAmount();
    return amount;

**Comment by Echinaceax** [comment]
@Imba232 i am an alchemist thats my toon i got the SS from

**Comment by Rushor** [comment]
yes 225 it is, but with the aura it should be 225+40, the boost is not added so far

**Comment by Rushor** [comment]
okay i see. like imba said. the effect works.

example: Flask of the Frost Wyrm http://cata.cavernoftime.com/item=46376 http://cata.cavernoftime.com/spell=53755.

Spell: http://cata.cavernoftime.com/spell=53755

You need to have spell http://cata.cavernoftime.com/spell=53901 learned for this and you need to have aura http://cata.cavernoftime.com/spell=53042 active.

My base spellpower is 235. 

Now i use http://cata.cavernoftime.com/item=46376. > I get 407 spellpower

407 - 235 =172

172 - 125 = 47

47 is the increased effect. 

Effect is there, but it simply does not show up in the bar. That's cleint side issue and was there on retail as well at a specific time.

![I](https://i.imgur.com/uqm5KZt.jpg)
![I](https://i.imgur.com/4IW3pMl.jpg)
