### ISSUE TITLE
[Spell] Mobile banking guild perks 83958

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2431]
**Links:**
https://wow.gamepedia.com/Mobile_Banking
from WoWHead or our Armory

**What is happening:**
It dont spawn guild bank chest

**What should happen:**
It should spawn guild bank chest

**Comment by Rushor** [comment]
will fix that!

**Comment by Rushor** [comment]
![](https://i.imgur.com/vpYjOE0.png)

**Comment by Rushor** [comment]
the fix only works if caster is a player (sure thing) AND if you are in a guild.

**Comment by TheSale** [comment]
I need someone to test this for me
After reloging Mobile banking spell disappear from my action bar.
Also chest stay more than 5 min. But it disappear when logging off.

this is not urgent or that important, and now guild bank actually work, but this tweaking may be needed one day.
