### ISSUE TITLE
[NPC] Spiketooth <Slavedriver>-39590- Durotar

### ISSUE THREAD

**Issue by Ranger-Bill** [WoWManiaUK/Blackwing-Lair#2434]
**Links:**
https://www.wowhead.com/quest=25259/gaur-icehorn
https://www.wowhead.com/quest=25257/ghislania
https://www.wowhead.com/quest=25258/griswold-hanniston
from WoWHead or our Armory

**What is happening:**
You cant click the chat button when talking to the chained slave.

**What should happen:**
I should be able to tell the chained slave to start the fight to finish the quest.

**Comment by Rushor** [comment]
i thought i handeled that already some time ago

**Comment by Ranger-Bill** [comment]
Doesn't seem to work still. I cant select his chat to start the quest.

**Comment by Echinaceax** [comment]
@Rushor you did #1104

**Comment by Echinaceax** [comment]
> Doesn't seem to work still. I cant select his chat to start the quest.

If you search and the same issue is here, comment on old report please and we can reopen :)
dont open new report thank you

**Comment by Rushor** [comment]
![](https://i.imgur.com/dtTioTK.jpg)
![](https://i.imgur.com/Dkc5XLJ.jpg)
![](https://i.imgur.com/4Z3JZNM.jpg)

**Comment by Rushor** [comment]
yeah i open an issue for all 3 different quests :)
