### ISSUE TITLE
thunder Down Under

### ISSUE THREAD

**Issue by Ranger-Bill** [WoWManiaUK/Blackwing-Lair#2435]
**Links:**
https://www.wowhead.com/quest=25236/thunder-down-under

from WoWHead or our Armory

**What is happening:**
i have the quest item in my inventory and cant select the dead thunder lizards

**What should happen:**

i should be able to click on the drowned thunder lizards and raise them up.

**Comment by Echinaceax** [comment]
Already reported #188
