### ISSUE TITLE
[Spell] Glyph of Maul

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2438]
ID 54811

**How it works atm:** Hits an additional target for 100% of Maul damage
**How it should work:** Should only do 50% of the original maul damage as cleave.

**Comment by giles1508** [comment]
hmm,  when i was testing this it was hitting main target for 140 and second target for 70,   unless something with the maul fix has changed that

**Comment by Keader** [comment]
fixed.
