### ISSUE TITLE
[NPC] Erunak - (Ally) unlocks Zone Vashj'r 

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#244]
npc - https://www.wowhead.com/npc=36915/erunak-stonespeaker
you are required to speak with this npc to start the starting quest of Vashj'ie however he is no there so I am unable to quest in the area.
quest - https://www.wowhead.com/quest=14482/call-of-duty picked up from NPC -https://www.wowhead.com/npc=36799
![world of warcraft 20_12_2018 18_44_43](https://user-images.githubusercontent.com/42302580/50304471-f04a2d80-0487-11e9-8d39-4a0838901ad1.png)

**Comment by Dranah** [comment]
NPC is there but in wrong phase.
You should be able to see him with https://www.wowhead.com/quest=14482/call-of-duty in your log.

**Comment by zippoking** [comment]
Even with the Quest in your Quest Log, the NPC is not in your phase or you are not in his phase.

**How it is:**
![Erunak Stonespeaker - how it is](https://user-images.githubusercontent.com/18005338/59869531-cbca0200-9393-11e9-9571-7222ae23a1c8.png)

**How it should be:**
![Erunak Stonespeaker - how it should be](https://user-images.githubusercontent.com/18005338/59869532-cc629880-9393-11e9-937e-85cad59edcdb.png)

**Comment by Echinaceax** [comment]
> NPC is there but in wrong phase.
> You should be able to see him with https://www.wowhead.com/quest=14482/call-of-duty in your log.
#1106 i reported this when i tested as horde on alpha close server
