### ISSUE TITLE
[Quest] The Etymidian - ID 12548 - Sholazar Basin

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2445]
**Links:**
Quest: https://www.wowhead.com/quest=12548/the-etymidian

**What is happening:**
The Waygate is not working. If you are standing within the waygate it does not teleport you to Un'Goro Crater.
![The Etymidian - how it is](https://user-images.githubusercontent.com/18005338/59688516-23267180-91de-11e9-9a42-9800dc87bd8e.png)

**What should happen:**
For this quest you need to go through the Waygate in the southern end of Sholazar Basin and look for the weapon known as the Etymidian on the other side, which will be in Un'Goro Crater.
![The Etymidian - how it should be](https://user-images.githubusercontent.com/18005338/59688515-23267180-91de-11e9-92f3-7ec0bd084903.png)

**Comment by sarahkay88** [comment]
did you complete the pre quests? https://wowwiki.fandom.com/wiki/Quest%3AThe_Etymidian

**Comment by zippoking** [comment]
Yeah i did. 
Just to clarify: The Quest itself works, i went to Un'Goro Crater to myself and completed the quest.
The Waygate is just not working here.

Funny thing: From Un'Goro Crater to Sholazar Basin the waygate works. Just the other way around does not.

**Comment by sarahkay88** [comment]
@zippoking ty for the reply :)

**Comment by sarahkay88** [comment]
only waygate links I could find https://www.wowhead.com/object=322614/waygate and https://wowwiki.fandom.com/wiki/Waygate.

**Comment by Rushor** [comment]
This is the condition in order to be able to get the teleport http://cata.cavernoftime.com/?quest=12613

teleports fixed

![I](https://i.imgur.com/Wfvp71o.jpg)
![I](https://i.imgur.com/gi2I75s.jpg)
