### ISSUE TITLE
[QUEST] Into the Maw duplication - Phasing issue- Mount Hyjal

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#245]
Quest - https://www.wowhead.com/quest=25617/into-the-maw
NPC - https://www.wowhead.com/npc=39622
The quest duplicates so you cannot hand both in however this then keeps you phased so you are unable to hand in https://www.wowhead.com/quest=25630/the-fires-of-mount-hyjal. must complete the quest chain unphassed. currently waiting for phoenix t rephrase me has during phase I am unable to interact or see any NPC.

**Comment by sarahkay88** [comment]
![world of warcraft 20_12_2018 21_05_17](https://user-images.githubusercontent.com/42302580/50311035-ba16a900-049b-11e9-83f5-eb9a0720541d.png)
![world of warcraft 20_12_2018 21_08_58](https://user-images.githubusercontent.com/42302580/50311038-bb47d600-049b-11e9-9c30-26a38a371c72.png)

**Comment by sarahkay88** [comment]
![world of warcraft 20_12_2018 21_11_53](https://user-images.githubusercontent.com/42302580/50311097-edf1ce80-049b-11e9-8476-3acd63b2a15d.png)
what would have been the flight master but due to phase cannot be seen

**Comment by Dranah** [comment]
Not related.
