### ISSUE TITLE
[Item] Moonrest Gardens Plans

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Blackwing-Lair#2457]
Fixed droprate from 100 to 10

**Comment by Phoenix9867** [comment]
Hi (ingame Remoted here),
today i tried the quest, looted every dead person in the area twice, but nothing happend
there might be some issue again

**Comment by Echinaceax** [comment]
Thanks @Phoenix9867 
https://www.wowhead.com/quest=11999/rifle-the-bodies
https://www.wowhead.com/quest=12000/rifle-the-bodies

**Comment by Echinaceax** [comment]
> Fixed droprate from 100 to 10

Was set to 10% drop rate as stated be Kitz

![image](https://user-images.githubusercontent.com/39439201/117585111-ebe24600-b110-11eb-9890-568c4b74ee81.png)

**Comment by Echinaceax** [comment]
update info from player 

drop rate needs checking again

https://www.wowhead.com/quest=11999/rifle-the-bodies
https://www.wowhead.com/quest=12000/rifle-the-bodies

**Comment by Hillgnt** [comment]
Me, Storei, and my wife, Yllanda, both lvl 73 at the time, were trying to do the quest for quite some time, but got no drops from the mage hunter corpses lying around.
Estimate that we searched close to 100 corpses between us, but no drop. 
In the original quest you are supposed to get small pouches you can open, but we got nothing...
We play alliance, so quest id 12000.
