### ISSUE TITLE
[Dungeon] Not receiving rewards on disconnect/logout

### ISSUE THREAD

**Issue by Imba232** [WoWManiaUK/Blackwing-Lair#2459]
**Links:**

from WoWHead or our Armory

**What is happening:**

You happen to often get errors or some bugs that require you to relog and when you leave party you won't receive the valor or any justice/bags anymore.

**What should happen:**

You shouldn't leave the party on errors that cause you to d/c or other stuff.

**Comment by Kitzunu** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/2462

**Comment by Echinaceax** [comment]
@Kitzunu why close the original ?
could have added yours too this one
