### ISSUE TITLE
[Quest] Kill or Be Killed - Worgen Chain - Gilneas

### ISSUE THREAD

**Issue by Alestorwow** [WoWManiaUK/Blackwing-Lair#2460]
**Links:**

https://www.wowhead.com/quest=14336/kill-or-be-killed

**What is happening:**

After accepting the quest everything despawns and you cant continue the worgen quest chain just like the issue in Last chance at Humanity https://github.com/WoWManiaUK/Blackwing-Lair/issues/2220

**What should happen:**

**Comment by zippoking** [comment]
Confirmed. Another Phasing issue. All NPCs are gone.

![Kill or Be Killed - how it is 2](https://user-images.githubusercontent.com/18005338/59706569-00598480-9201-11e9-8df5-0eacb8b4384f.png)
![Kill or Be Killed - how it is 1](https://user-images.githubusercontent.com/18005338/59706571-00598480-9201-11e9-9292-9fec23393f60.png)

**Comment by Dranah** [comment]
@Rushor it's the same 105 phase

**Comment by Rushor** [comment]
Okay will check

**Comment by Rushor** [comment]
in which phase should the player be once finished the quest?

**Comment by Rushor** [comment]
fixed

![](https://i.imgur.com/XdPycco.jpg)

you may need to relog, bt phasing continues now with quest http://cata.cavernoftime.com/quest=14321 and https://www.wowhead.com/quest=14336/kill-or-be-killed.

You are in phase 182 then.

**Comment by Dranah** [comment]
Works, thank you.

**Comment by Rushor** [comment]
thank you too, i think one last quest has phasing issue too later in the chain - just report it and i will fix isntant :>
