### ISSUE TITLE
Lvl 60 pvp gear vendor for the Alliance (plate gear and mail gear) bugged. (Area 52) (issue 1)

### ISSUE THREAD

**Issue by all-names-seem-to-be-taken** [WoWManiaUK/Blackwing-Lair#2463]
**Links:**

from WoWHead or our Armory

**What is happening:**
The pvp gear vendor that sells mail/plate for the Alliance is gone. The Hordes is there and they have there plate/mail and cloth/leather.

**What should happen:**
The plate/mail vendor should be there but is either 1. Not in the game at all right now) 2. Under the ground and not availed for payers to reach) I'm not a coder or dev or anything like that so idk these are just my thoughts

**Comment by wow-mania** [comment]
WHat is the npc? PLease check wiki on how to log an issue.

**Comment by Echinaceax** [comment]
> WHat is the npc? PLease check wiki on how to log an issue.

https://www.wowhead.com/npc=54650/kezzik-the-striker

**Comment by Dyr303** [comment]
> > WHat is the npc? PLease check wiki on how to log an issue.
> 
> https://www.wowhead.com/npc=54650/kezzik-the-striker

The same NPC only sells weapon/offhand/relic
It doesn't sells other parts

**Comment by all-names-seem-to-be-taken** [comment]
Kezzik the striker sells 70 pvp gear/weapons-Big Zokk Torque-wrench sells 60 pvp weapons-Tini Smalls sells the Hordes cloth and leather pvp gear-Leeni "smiley" Smalls sells the Horde mail and plate- Krixel Pinchwhistle is suppose to be there and would sell the plate and mail 60 pvp gear. (Btw the guy 2 of you linked only sells 70 stuff and has always only sold 70 stuff not 60 I don't mean to sound mean/annoying just letting you know)

**Comment by all-names-seem-to-be-taken** [comment]
[image: Image result for Krixel Pinchwhistle]Kezzik the striker sells 70
pvp gear/weapons-Big Zokk Torque-wrench sells 60 pvp weapons-Tini Smalls
sells the Hordes cloth and leather pvp gear-Leeni "smiley" Smalls sells the
Horde mail and plate- Krixel Pinchwhistle is suppose to be there and would
sell the plate and mail 60 pvp gear. (Btw the guy 2 of you linked only
sells 70 stuff and has always only sold 70 stuff not 60 I don't mean to
sound mean/annoying just letting you know)  Picture of Krixel Pinchwhistle
above.

**Comment by Echinaceax** [comment]
ok, many un needed info here , please link the npc that you want fixing :) please

**Comment by Echinaceax** [comment]
@all-names-seem-to-be-taken can you please link the NPC that you want fixing please ?

**Comment by all-names-seem-to-be-taken** [comment]
Here is the wow head link to the bugged person
https://www.wowhead.com/npc=23396/krixel-pinchwhistle

**Comment by giles1508** [comment]
Please bear in mind that the wowhead link is up to date with current retail, and that npc and set of vendors has changed back in the day that npc is listed as selling all the main set pieces for arena seasons 1.2.3 which isn't currently in wowheads loot table as they have been removed over the years

**Comment by all-names-seem-to-be-taken** [comment]
giles1508 that same guy krixel pinch whistle has always sold the legacy 60
pvp gear and thats never changed including current retail. its been 10 days
now and the bug still has not been fixed even after i told u what guy was
suppose to be there selling said items.

**Comment by Rushor** [comment]
https://www.wowhead.com/npc=23396/krixel-pinchwhistle will add him and his item.

**Comment by Rushor** [comment]
added him.
