### ISSUE TITLE
[Racial] Tauren Cultivation

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2465]
**Links:**

https://www.wowhead.com/spell=20552/cultivation#comments

**What is happening:**
Cultivation does not work. 

**What should happen:**
Taurens should gather herbs extremely fast.

**Comment by Lerixo** [comment]
To make this clear, the 15 professionpoints work, but the 1.5 second casttime of herb gathering decrease, which the racial should give, does not apply. Please fix this and dont forget, as this was already 18 days ago.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/SvsCk0J.jpg)

fixed with next update
