### ISSUE TITLE
[Talent][Shaman] Feedback

### ISSUE THREAD

**Issue by Idkwhyme** [WoWManiaUK/Blackwing-Lair#2466]
**Links:**

http://cata.cavernoftime.com/spell=86185

**What is happening:**

Feedback talent is reducing the cooldown of elemental mastery in every offensive spell.

**What should happen:**

Should only reduce the cooldown when using Lightning Bolt and Chain lightning

**Comment by Echinaceax** [comment]
this one ?
https://www.wowhead.com/spell=87904/feedback

**Comment by Idkwhyme** [comment]
No, thats a spell used from an Elite from Throne of the Four Winds

**Comment by Echinaceax** [comment]
this one ?
https://cata-twinhead.twinstar.cz/?spell=86185

**Comment by Idkwhyme** [comment]
Yes i  think that can work, even tho seconds are off.
thank you

**Comment by Echinaceax** [comment]
what should the secs be ?
would be helpful for fixers :)

**Comment by Idkwhyme** [comment]
Should be 3s
