### ISSUE TITLE
[NPC] normal asaad - The Vortex Pinnacle

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2469]
**Links:**

https://www.wowhead.com/npc=43875/asaad  - boss
https://www.wowhead.com/item=52078/chaos-orb   -  chaos orb

**What is happening:**

normal version of this boss is dropping chaos orbs

**What should happen:**

should only drop from heroic

**Comment by Dyr303** [comment]
The whole dungeon drops heroic version of items too

**Comment by Echinaceax** [comment]
removed high prio now that the new report has been made :)
