### ISSUE TITLE
 [Zone/Raid] Karazhan - Deadwind Pass

### ISSUE THREAD

**Issue by Dyr303** [WoWManiaUK/Blackwing-Lair#2471]
**Links:**
https://www.wowhead.com/karazhan
**What is happening:**
The door linked to Prince Malchezaar after the chess event isn't working

**What should happen:**
The door should be able to open

**Comment by Rushor** [comment]
https://www.youtube.com/watch?v=f4Mc-NYPHaQ

**Comment by Rushor** [comment]
opened the doors, to bypass to the boss!

**Comment by Rushor** [comment]
![](https://i.imgur.com/xDnlLPH.jpg)

**Comment by Dyr303** [comment]
![abc](https://user-images.githubusercontent.com/51888234/59780567-cb2a6080-92ec-11e9-8691-4fb5051fdeea.PNG)
cant, after i go in the chess room the door that leads to Prince Malchezaar doesn't work.

**Comment by Echinaceax** [comment]
@Dyr303 dyr - was only fixed in dev 8 hours ago and report is not closed yet , means it fix is not on live yet.
will be implemented soon. if it still doesnt work after report closed then please add comment here again ok

**Comment by Dyr303** [comment]
my bad, didn't know, will do. Thanks alot :D
