### ISSUE TITLE
 [Zone/Raid] Magtheridon's Lair - Hellfire Peninsula

### ISSUE THREAD

**Issue by Dyr303** [WoWManiaUK/Blackwing-Lair#2472]
**Links:**
https://www.wowhead.com/npc=17257/magtheridon

**What is happening:**
After defeating all Hellfire Channeler, Magtheridon is still immune

**What should happen:**
After defeating all Hellfire Channeler, Magtheridon should break free and start combat with the raid party

**Comment by Rushor** [comment]
fixed

![](https://i.imgur.com/9TtZuVC.jpg)

**Comment by Dyr303** [comment]
![bdef](https://user-images.githubusercontent.com/51888234/59781624-c5ce1580-92ee-11e9-8d03-421361eb1f86.PNG)
is the fix live yet?

**Comment by giles1508** [comment]
Won't be live yet no
