### ISSUE TITLE
Grot Deathblow@ Head Enchant

### ISSUE THREAD

**Issue by Geniuskp** [WoWManiaUK/Blackwing-Lair#2473]
**Links:**
https://www.wowhead.com/npc=49387/grot-deathblow
**What is happening:**
The Npc does not sell u head enchant 
https://wow.gamepedia.com/Arcanum_of_the_Dragonmaw
**What should happen:**
It should sell u the head enchant
https://imgur.com/a/YAipPmF

**Comment by Rushor** [comment]
This item is a reputation reward; you must be Revered with Dragonmaw Clan to purchase it from Horde Grot Deathblow <Dragonmaw Clan Quartermaster> at Bloodgulch in Twilight Highlands for 150g.

**Comment by Rushor** [comment]
![](https://i.imgur.com/1w2C0KY.jpg)
