### ISSUE TITLE
[Talent][Warlock][Affliction] Soul Siphon

### ISSUE THREAD

**Issue by Demonologylock** [WoWManiaUK/Blackwing-Lair#2478]
**Links:** ID 17805

from WoWHead or our Armory

**What is happening:** Drain Life damage is getting increased only by 2 of the 3 dots(Agony/Doom, Corruption and Unstable Affliction), doesn't matter which combination.

**What should happen:** Talent should increase Drain Life damage from all 3 dots.

**Comment by Dranah** [comment]
Nearly sure it's same issue we had on LK with the drain effect increasing it's own damage, therefore getting 1 buff benefit even without dots on target. Will recheck tho

**Comment by Demonologylock** [comment]
Drain soul has the same issue but i forgot to add it
