### ISSUE TITLE
[Talent][Warlock][Affliction] Death's Embrace

### ISSUE THREAD

**Issue by Demonologylock** [WoWManiaUK/Blackwing-Lair#2479]
**Links:** ID 47200

from WoWHead or our Armory

**What is happening:** Death's Embrace talent doesn't increase the damage of shadow spells by 12% when target is at or below 25%.

**What should happen:** Death's Embrace talent should increase the damage of shadow spells by 12% when target is at or below 25%.

**Comment by Dranah** [comment]
This talent has 2 effects:
1) Should increase the HEALING done by Drain life (ID 689) when the WARLOCK is <25% health, by 3% of the warlock's total health.
This increase currently doesn't work at all.

2)Increases DAMAGE done by 12% for all of your shadow spells against a TARGET that is <25% health.
This damage boost effect now double dips (grants 24% damage) for most shadow spells after the last fix, i.eg. shadow bolt, corruption etc.
However damage boost effect is significantly weaker for drain life, which only gains a 3% increase.
(It might be related to the missing other effect of the talent added to the wrong place)
