### ISSUE TITLE
[Dungeon/ Loot]  Vortex pinnacle - (Normal)

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2481]
**Links:**

https://www.wowhead.com/the-vortex-pinnacle

**What is happening:**

Reports have been brought forward that the normal version of this instance is dropping heroic loot from each of the bosses in this instance,  

**What should happen:**

the bosses in this instance should only drop level 81 items   that are 318 item level ,   and not  level 85 items with   346 item level

 reported by @dyr303  yesterday 
https://github.com/WoWManiaUK/Blackwing-Lair/issues/2469#issuecomment-503837290

**Comment by Rushor** [comment]
fixing that

all bosses need ref tables

**Comment by Rushor** [comment]
fixed

![](https://i.imgur.com/VNRzlcA.jpg)

**Comment by giles1508** [comment]
@rushor that pic you linked is a heroic item? Was you in a heroic or a normal?  Cause the normal is supposed to drop the lower item level

**Comment by Echinaceax** [comment]
> @Rushor that pic you linked is a heroic item? Was you in a heroic or a normal? Cause the normal is supposed to drop the lower item level

chat says "Welcome to HC" :)

**Comment by giles1508** [comment]
But it's normal that needs fixing not heroic :)
