### ISSUE TITLE
[Profession] [Inscription] Runescroll of Fortitude II

### ISSUE THREAD

**Issue by Imba232** [WoWManiaUK/Blackwing-Lair#2483]
**Links:**

https://www.wowhead.com/item=62251/runescroll-of-fortitude-ii

**What is happening:**

Doesn't give stamina.

**What should happen:**

Should increase stamina of party and raid members by 468 for 1 hour.

**Comment by Rushor** [comment]
fixed here https://github.com/WoWManiaUK/Blackwing-Lair/issues/2747
