### ISSUE TITLE
[Quest] The King's Observatory - ID 14466 - npc phasing issue - Gilneas

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2484]
**Links:**
Quest: https://www.wowhead.com/quest=14466/the-kings-observatory
NPC: https://www.wowhead.com/npc=36606/queen-mia-greymane

**What is happening:**
As soon as you turn in the pre quest "To Greymane Manor" #301, all NPC#s phase away.
After that you can´t accept a new quest, because there is no NPC to talk to.
![The Kings Observatory - how it is](https://user-images.githubusercontent.com/18005338/59865464-59542480-9389-11e9-8404-1034875573b8.png)

**What should happen:**
After turning in the pre quest "To Greymane Manor", you should be able to accept the next quest "The King's Observatory".
![The Kings Observatory - how it should be](https://user-images.githubusercontent.com/18005338/59865463-59542480-9389-11e9-9ef8-a1661892714a.png)

**Comment by Echinaceax** [comment]
@rusher ive popped pending on this for now as a new full test is in progress

**Comment by Rushor** [comment]
you should be able to see them now

**Comment by Rushor** [comment]
till quest http://cata.cavernoftime.com/quest=24438 the phase should be stable now

**Comment by giles1508** [comment]
real question is,  how did you manage to get to this quest in the first place when the chain is broken before it ? :p

**Comment by zippoking** [comment]
A couple of days/weeks ago, you could do the quest chain till the one before this quest.
Then the quest before this one was fixed and i could finish it. But then the problem this issue is about, appeared.

**Comment by giles1508** [comment]
ahh right,  as im currently testing this with fresh toons and chain is broken before this :)

**Comment by Rushor** [comment]
Tested with Giles now and phasing works now, but the questorder needs fixing again. Will be done in a new report tomorrow :)

**Comment by Dranah** [comment]
Accepting this quest phases you out so that all NPCs disappear including the one who ends it.
Relogging however puts you back into the correct phase with the quest in your log so you will see NPCs again and be able to hand in.
Leaving it here for info in case players run into this.
