### ISSUE TITLE
[Spell] Seed of Corruption

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2488]
ID 27243

Does very low damage. It has 2 portions: dot and explosion. Explosion is more relevant, it is the AoE functionality.

1) Base damage of explosion is much lower than intended.
How it works atm: Currently base damage of explosion 760 damage
How it should work: Base damage should be around 2k based on spellwork
Note: For comparison, the lvl 80 wotlk base damage was 1750~.

2) SP coefficient of both explosion and DOT component is lower than intended.
How it works atm: Currently the coefficient for both each tick and the end explosion is 18,9%, a total of 132% for the entire spell.
How it should work: Cataclysm coefficient is meant to be 202,9% for the entire spell, which consists of 6 dot ticks and 1 explosion, making it 28,9% each.

Tests:
Warlock with 4186 SP, untalented
Intended damage on explosion ~ 3,2k
Actual damage on explosion ~ 1,6k
Warlock with 6497 SP, affly talents (+30% shadow)
Intended damage on explosion ~ 5k
Actual damage on explosion ~2,6k

3) Visual issue.
The tooltip is completely broken, it shows insanely high numbers for the DOT component (which you dont actually do) and much lower than intended for the explosion. Tooltip needs fixing too.

**Comment by Keader** [comment]
Fixed spell coeff.
Idk if will fix visual issue too, if not, nothing that i can do, tooltip come from dbc+clientside

**Comment by Dranah** [comment]
The explosion base damage still needs correcting.

**Comment by Keader** [comment]
Test now @Dranah

**Comment by Dranah** [comment]
Base damage is even lower than it was. Use the values I gave you ._.

**Comment by Dranah** [comment]
Base damage stays as-is.
Need a correction to the seed checking for its own damage to trigger. Rest is fixed.
