### ISSUE TITLE
[Quest / Quest order]   Escape by sea   ( worgen starting )  - Gilneas

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2489]
**Links:**

https://wow.gamepedia.com/Escape_By_Sea

**What is happening:**

quest is available too early 

**What should happen:**

quest should not be available to take until the following 2 are completed
https://wow.gamepedia.com/Not_Quite_Shipshape
https://wow.gamepedia.com/Washed_Up

**Comment by Rushor** [comment]
added condition that quest will only be shown if https://wow.gamepedia.com/Not_Quite_Shipshape
https://wow.gamepedia.com/Washed_Up is rewarded
