### ISSUE TITLE
[Quest]  Not Quite Shipshape - gilneas

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2490]
**Links:**

https://wow.gamepedia.com/Not_Quite_Shipshape

**What is happening:**

quest is not available to take 

**What should happen:**

quest is a vital part of getting to next step in the chain and needs to be added

**Comment by Rushor** [comment]
added. quest http://cata.cavernoftime.com/quest=14403 must be rewarded first in order to get that quest

**Comment by Rushor** [comment]
Tested together with Gil, all working now :)
