### ISSUE TITLE
[Quest] Adversarial Blood (11885)

### ISSUE THREAD

**Issue by Idkwhyme** [WoWManiaUK/Blackwing-Lair#2492]
**Links:**

https://www.wowhead.com/quest=11885/adversarial-blood

Sha'tari Skyguard Rep chain

**What is happening:**

You cant summon descendants even tho you have the necessary items.

**What should happen:**

You should be able to summon descendants with the use of 10 Time-Lost scrolls (https://www.wowhead.com/item=32620/time-lost-scroll)

**Comment by Rushor** [comment]
![](https://i.imgur.com/5UCvuuW.jpg)
![](https://i.imgur.com/3rUgx1z.jpg)
