### ISSUE TITLE
[Quest / Quest order]      worgen area -  gwen armstead chain Gilneas

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2494]
**Links:**

https://wow.gamepedia.com/Worgen_starting_experience    -   link to whole quest order  so you can freely click on each quest instead of having a gazillion links in this thread !

**What is happening:**

Gwen is supposed to give 3 quests,   that start off 3 seperate chains,  with 3 sperate new quest givers
but the 3 seperate quest givers currently have the quests unlocked and available to take before you even pick up the prequest

**What should happen:**

below is a rough guide of what should happen

1 -  hand in      [7] Evacuation   to gwen
2 - take these 3 from her  --    [7] Grandma Wahl ,  [7] The Hayward Brothers,  [7] The Crowley Orchard
3 -  complete the following 3 chains in any order you chose : -

               Granmma chain   =   [7] Grandma Wahl 
	                                        [7] Grandma's Lost It Alright
	                                        [7] I Can't Wear This 
	                                        [7] Grandma's Cat
                                                [7] Ready to Go  ( **optional** )
              
               Haywards chain   =   [7] Not Quite Shipshape  &  [7] Washed Up   (  these 2 should be available to take together )
                                                [7] Escape By Sea  ( **optional** )

               Crowley chain  =      [7] The Hungry Ettin
                                                [7] Horses for Duskhaven   ( **optional** )   

4  -   after then and only after all of the above quests are completed, (  note you dont have to do the quests )   you then get      [7] To Greymane Manor   from gwen

**Comment by Rushor** [comment]
all added as you listed it here

-- Grandma Wahl
-- ---- [7] Grandma's Lost It Alright 14399
-- ---- [7] I Can't Wear This 14400
-- ---- [7] Grandma's Cat 14401
-- --------[7] Ready to Go  ( **optional** ) 14402

-- [7] Not Quite Shipshape 14404  &  [7] Washed Up 14412   (  these 2 should be available to take together )
-- --- [7] Escape By Sea  ( **optional** ) 14405

-- [7] The Hungry Ettin 14416
-- --------[7] Horses for Duskhaven   ( **optional** ) 14463

**Comment by Rushor** [comment]
Tested together with Gil, all working now :)

**Comment by giles1508** [comment]
can confirm,  just finished this again on dev and working brilliantly

**Comment by giles1508** [comment]
@Rushor   something has regressed since we tested this,  just gone back through it and done everything but its not letting me take   [7] To Greymane Manor from gwen

**Comment by Rushor** [comment]
main quest http://cata.cavernoftime.com/quest=14397

**Comment by Rushor** [comment]
Thsi is strange - i tested it now with a new toon, completed all the quests and i could take it then https://i.imgur.com/AzdsKPt.jpg hmm
