### ISSUE TITLE
[Spell] Vampiric Touch 

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2495]
ID 34914

Spell does too low damage. Coefficient seems broken.

**How it should work:**
Each tick should receive 35,2% SP coefficient, a total of 176% for the spell.

How it works atm:
SP coefficient seems to be around 18% experimentally, total of 90% for the entire spell.

TEST1:
Shadow priest with 2218 spell power
Expected damage is ~1010 with the 15% mod from shadow talent
Actual damage is 569 per tick

TEST2: 
Shadow priest with 3163 SP
Expected damage is ~1390 per tick
Actual damage is 764

The spell currently performs weaker than SWP, which is not intended.

**Comment by Keader** [comment]
Fixed.
Use .reload spell_bonus_data or wait next restart.
