### ISSUE TITLE
[Quest]   Grandma's Cat

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2499]
**Links:**

https://wow.gamepedia.com/Grandma%27s_Cat

**What is happening:**

the cat and the npc that you have to kill are both present and you cannot kill anything 

**What should happen:**

you are supposed to walk up to the cat,  then a hostile npc steals the cat and then you have to kill him to get the cat from his corpse

quick video here

https://www.youtube.com/watch?v=BvYd2zITGhc

**Comment by zippoking** [comment]
Cat on the rock: https://www.wowhead.com/npc=36459/chance
Item: https://www.wowhead.com/item=49281/chance-the-cat
Looted from NPC: https://www.wowhead.com/npc=36461/lucius-the-cruel

**How it is:**
Lucius the cruel already spawned but is not attackable.
![Chance the cat - how it is 1](https://user-images.githubusercontent.com/18005338/59979070-15f4f280-95e3-11e9-9421-cb1d5d5b43ff.png)
![Chance the cat - how it is 2](https://user-images.githubusercontent.com/18005338/59979071-15f4f280-95e3-11e9-8bfe-be176680b66e.png)


**How it should be:**
Try to loot cat, npc spawns, kill him, then loot the item.
![Chance the cat - how it should be 1](https://user-images.githubusercontent.com/18005338/59979072-15f4f280-95e3-11e9-9373-1f898c28dd12.png)
![Chance the cat - how it should be 2](https://user-images.githubusercontent.com/18005338/59979073-15f4f280-95e3-11e9-80db-3aa7ae532a19.png)
![Chance the cat - how it should be 3](https://user-images.githubusercontent.com/18005338/59979069-15f4f280-95e3-11e9-8c5e-35901669dac7.png)

**Comment by Rushor** [comment]
http://cata.cavernoftime.com/quest=14401

**Comment by Rushor** [comment]
fix added

**Comment by Rushor** [comment]
![](https://i.imgur.com/v5hKHKn.jpg)
![](https://i.imgur.com/TgtlcAm.jpg)

**Comment by giles1508** [comment]
confirmed to be working on test server
