### ISSUE TITLE
[Quest] Unexpected Results -Eversong Woods

### ISSUE THREAD

**Issue by todd0168** [WoWManiaUK/Blackwing-Lair#250]
Quest Unexpected Results, given by Apprentice Mirveda in Eversong Woods

When you pick up the quest from the quest giver there are supposed to be 3 mobs spawned (from what I can tell). It looks like it's supposed to be 2 Angershades and Gharsul the Remorseless. But when the mobs spawn, two groups of mobs are spawning. So 2 Gharsuls and 4 Angershades are spawning.
 
Link to quest on Wowhead: https://www.wowhead.com/quest=8488/unexpected-results

**Comment by Dranah** [comment]
I presume then the quest is doable just slightly harder.

**Comment by Echinaceax** [comment]
> I presume then the quest is doable just slightly harder.

yes, correct

**Comment by Xman993** [comment]
[Apprentice Mirveda](https://www.wowhead.com/npc=15402/apprentice-mirveda) does not interact with you after the quest

**Comment by Dranah** [comment]
This quest sometimes does not grant credit.
The issue with NPC not interacting anymore prevents you from re-doing it. 
This can easily lead to the quest not being possible to do at all without a GM's help.
