### ISSUE TITLE
[Quest / Quest order]  King Genn Greymanes quests - worgen area Gilneas

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2501]
**Links:**

links below !

**What is happening:**

ok,  after you collect the quest  -   https://wow.gamepedia.com/The_King%27s_Observatory
you run upstairs to talk to the king to hand in ,   but when you talk to the king,   he has 2 quests to hand in and you can take the following quest also
which are 
https://wow.gamepedia.com/Alas,_Gilneas!
https://wow.gamepedia.com/Exodus

**What should happen:**

when first talking to the king you should only be able to hand in  [7] The King's Observatory
you should not be able to see the other 2 quests yet
the order is as follows

1.  -  accept  -  [7] The King's Observatory  -   from the queen downstairs
2.  -  hand in  -  [7] The King's Observatory  -  to the king upstairs
3.  -  accept  -  [7] Alas, Gilneas!  -  from the king upstairs
4.  - watch cutscene  
5.  -  hand in  -  [7] Alas, Gilneas!   -  to king  upstairs
6.  -   accept  -   [8] Exodus   -   from king upstairs
7.  -  hand in  -  [8] Exodus   -  to   liam greymane outside

**Comment by Rushor** [comment]
quest order added. 

note: Alas, Gilneas! is still autocomplete, we need that currently for the cinematic. but the quest order for all quests was added, mentioned in the issue :>
