### ISSUE TITLE
[Quest / Quest order]  Worgen area  -  prince liam greymane Gilneas

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2502]
**Links:**

https://wow.gamepedia.com/Worgen_starting_experience  -   quest order again :)   sorry

**What is happening:**

1.   after you take the quest    [8] Exodus     from **king greymane**  you walk down to the stables to get a carriage,  howevr there is no carriage there and you have to walk all the way to hand the quest in

2.   when you get to **prince liam greymane** everntually,  not only can you hand in  **[8] Exodus**   ,   but you can also take a quest which should not be available for another 3 quests down the line !  which is      **[8] Stormglen**

**What should happen:**

1.   upon leaving the manor,  there should be a carriage outside that you jump on to take you to next area
2.   you hand in the quest to  liam greymane 
3.   you then accept    **[8] Stranded at the Marsh**

so the quest     **[8] Stormglen**    should be removed until you completed     **[8] Introductions Are in Order**  ,    which is   directly after   **[8] Stranded at the Marsh**

video below of the carriage travel

https://www.youtube.com/watch?v=x9oL3GK1778

**Comment by Rushor** [comment]
okay just as info

1. 
once you acceptec the quest "Exodus" you get the phasing spell:
[17:01:09]id: 69484 [Phase - Quest Zone-Specific 11] effmask: 1 c
which puts you int phaseid 186.

Lower you can find the vehicle carriage then. It's a basic script for now, but you can mount it and it will transport you through the gates. The orc close to the questgiver will throw stones to you.

However the tiny horses in front of the carriage can not be added for now.

**Comment by Rushor** [comment]
okay added the script and prevquest so far

![](https://i.imgur.com/wDzdDuf.jpg)
![](https://i.imgur.com/YKzZI4Q.jpg)
