### ISSUE TITLE
[Quest]   Stranded in the Marsh - Gilneas

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2503]
**Links:**

https://wow.gamepedia.com/Stranded_at_the_Marsh

**What is happening:**

there is no quest location icon on map to let players know where to go

**What should happen:**

should be a number    1    on the map at the marsh telling players where the crash site is to rescue survivors

**Comment by Rushor** [comment]
http://cata.cavernoftime.com/quest=24468

**Comment by Rushor** [comment]
remember to delete cache and restart client before inspecting this

![I](https://i.imgur.com/JFHA4iz.jpg)
