### ISSUE TITLE
[Quest / Quest order]   Lorna crowley chain in stormglen - Gilneas

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2504]
**Links:**

https://wow.gamepedia.com/Worgen_starting_experience   --  as always the quest order :D 

**What is happening:**

the NPC **lorna crowley** is giving a quest too early in the chain  
when you first get to **stormglen** she should have 1 quest which is  -   **[8] Pieces of the Past**
but instead she also has    **[8] The Blackwald**    

**What should happen:**

quest order is as follows

1  -  accept  and complete   **[8] Pest Control**   -  from   the NPC called   **Gwen Armstead**   and the quest called    **[8] Pieces of the Past**   -  from  NPC called  **Lorna Crowley**
2  -  after completing both the previous quests you should then get only this  -   **[9] Queen-Sized Troubles**    -   from **Gwen Armstead**
3 -  after handing in   **[9] Queen-Sized Troubles**   to **Gwen**,  you then are able to accept   **8] The Blackwald**   from **Lorna Crowley**

picture below of the 2 NPC's

![WoWScrnShot_062219_010010](https://user-images.githubusercontent.com/50211643/59956595-2db86380-9489-11e9-8116-87bf37c0be78.jpg)

**Comment by Rushor** [comment]
Pest Controle http://cata.cavernoftime.com/quest=24484 Pieces of the Past http://cata.cavernoftime.com/quest=24495
then Queen-Sized Troubles http://cata.cavernoftime.com/quest=24501
then The Blackwald http://cata.cavernoftime.com/quest=24578 


alright all quest order added

**Comment by Rushor** [comment]
![](https://i.imgur.com/evKrTAR.jpg)
![](https://i.imgur.com/AuGtH3q.jpg)
![](https://i.imgur.com/vlhQ8zG.jpg)
