### ISSUE TITLE
[Quest][Mount Hyjal] Howling mad - ID 25270

### ISSUE THREAD

**Issue by Idkwhyme** [WoWManiaUK/Blackwing-Lair#2507]
**Links:**

https://www.wowhead.com/quest=25270/howling-mad

**What is happening:**

Npcs that we are supposed to kill are phased. (https://www.wowhead.com/npc=39445/lycanthoth-vandal)

**What should happen:**

Npcs should not be phased.

**Comment by giles1508** [comment]
ive completed this on 2 toons before,  and now its back to being phased wrong,  but this isnt the only issue,  that whole area is going to need work

**Comment by gamer100** [comment]
Still unphased  have  done it 3 times  from start, to make sure that i did not  get unphased by skipping quest you need  
![image](https://user-images.githubusercontent.com/33811022/62147158-4113e580-b2f7-11e9-9f66-190b5c9f8248.png)

**Comment by Rushor** [comment]
now in the same phase like the questgiver

![I](https://i.imgur.com/e72zLpZ.jpg)
