### ISSUE TITLE
[Priest] Mind Spike (issue 2)

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2508]
**Links:**

73510 spell ID

**What is happening:**
Damage formula is incorrect for 83.6%(of SP)*6966
Current avg dmg: ~4550

**What should happen:** 
Average damage should be around 7718 according to DrDamage with 6% dmg increase from Twin Disciplines talent (47588)

Edit: Switched to holy spec to have shadow spec dmg modifiers gone.

**Comment by Echinaceax** [comment]
Have you tested it with and without this particular addon?

try a different dmg/heal meter see if you get same results

**Comment by Dranah** [comment]
Intended coeff 83,6%
Current appears to be ~41,5%
