### ISSUE TITLE
[Priest][Holy][Talent] Heavenly Voice

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2509]
**Links:**

spell id 87431

**What is happening:**
The talent does not increase the healing of divine hymn by 50% (1/2) or 100% (2/2)

Healing stays the same with or without the talent. 

**What should happen:**
Talent should increase the healing of Divine Hymn by said percentages

**Comment by Echinaceax** [comment]
Have you tested it with and without this particular addon?

try a different dmg/heal meter see if you get same results
