### ISSUE TITLE
[Quest/Pala] Ways Of The Light - ID 10069 - Eversong Woods

### ISSUE THREAD

**Issue by realdude19** [WoWManiaUK/Blackwing-Lair#251]
When playing a Blood Elf Paladin and upon reaching level 3 you are able to acquire the quest "Ways Of The Light" Where you have two objectives:
- Learn Judgement 0/1
- Practice Judgement 0/1

However you are also able to train before accepting the quest which breaks the mechanics of the quest and there for you will not trigger the "Learn Judgment" portion of the quest and are not able to continue on to the next objective, making the quest incompletable.

This also has been reported before in issue: #97

**Comment by Echinaceax** [comment]
same on Bloodelf pala 
![seal](https://user-images.githubusercontent.com/39439201/54075162-474beb80-429c-11e9-86a9-8aa5bcd86069.jpg)

![seal learnt](https://user-images.githubusercontent.com/39439201/54075165-4e72f980-429c-11e9-97ca-28695a3b2c02.jpg)

- Learn Judgement 0/1 (not learnt) no quest credit
- Practice Judgement 0/1

**Comment by Dranah** [comment]
Quest ID 10069
I don't see how this is any priority... it's not a mandatory quest and doesn't have any important rewards.

**Comment by Echinaceax** [comment]
> I don't see how this is any priority... it's not a mandatory quest and doesn't have any important rewards.

I added "pro" to this as we was working with class quest startzone areas last week. i was going to make my own report until i saw it already reported so i added the "prio" as the startzones was whatt we all have been working on this week

**Comment by Echinaceax** [comment]
close this issue because duplicate was fixed #2403
