### ISSUE TITLE
[Priest][Holy][Talent] Test of Faith

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2510]
**Links:**

spell id 47560

**What is happening:**
Talent does not increase healing to targets under 50% hp by said percentages. 

Healing blow or above 50% HP does not change the numbers, while the talent is active.

**What should happen:**
Healing spells should increase healing by said percentages under 50% hp.

**Comment by Echinaceax** [comment]
what this also tested using drdamage ?
if yes 

try a different dmg/heal meter see if you get same results
