### ISSUE TITLE
[Priest] Smite 

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2511]
**Links:**

spell id 585

**What is happening:**
Damage is lower than intended according to DrDamage
Current average dmg: 6280

**What should happen:**
Expected average dmg should be 7408 for 6966 SP at 85.6% SP coefficient with 6% dmg increase from Twin Disciplines talent (47588)

**Comment by Echinaceax** [comment]
Have you tested it with and without this particular addon?

try a different dmg/heal meter see if you get same results

**Comment by Dranah** [comment]
Intended coeff is 85,6% as it states in the post.
Current coeff appears to be around 80%
Difference is minor, therefore no priority atm.
