### ISSUE TITLE
[Priest] Holy Fire

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2512]
**Links:**

spell id 14914

**What is happening:**
Damage is lower than intended, according to DrDamage.
Current average dmg: ~3440

**What should happen:**
Expected average dmg should be 9745 for 6966 SP at 132.8% SP coefficient with 6% dmg increase from Twin Disciplines talent (47588)

**Comment by Echinaceax** [comment]
Have you tested it with and without this particular addon?

try a different dmg/heal meter see if you get same results

**Comment by Dranah** [comment]
This report is valid but is a bit more complex as the spell has an instant damage and a DoT portion.
The 132,8% SP coefficient is shared among them.
**How it should work:** Approx 110,7% is meant to go into the instant damage and 22,1% is meant to go into the DoT damage ( 3,1% per tick).
**How it works atm:** Currently the instant damage receives about 32,5% and the dot gets about 20% ( 2,8% per tick).

**Comment by fuzzydunlop** [comment]
The DoT damage part still does too little compared to what it should do. While the Atonement healing from the DoT does work. (atonement heals the caster for 50% of the damage done to caster), but currently the healing and damage from the DoT part are equal. Meaning the DoT should roughly do double.

**Comment by Rushor** [comment]
> Meaning the DoT should roughly do double. 

@Keader

**Comment by Dranah** [comment]
Weird, it worked fine the last time I confirmed.
It does produce the wrong numbers now, seems the coefficient is down to 2,1% per tick on the DOT which is even lower than it was in the time of the original report.

The Atonement healing is not equal to the DOT but seems to calculate completely differently, with base values and no gear it's even higher than the actual damage of the DOT which shouldn't anyhow be possible. This does need to be re-checked but it seems like a new bug so i'll open a new report.

**Comment by Dranah** [comment]
Well I opened a separate issue for atonement. This way simply broken, the numbers don't match the original (before report) nor the fixed (after fixes), something fucked it up.
