### ISSUE TITLE
[Priest] Prayer of Mending

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2513]
**Links:**

spell id 33076

**What is happening:**
Healing is lower than intended, according to DrDamage
Current average per tick is ~3600

**What should happen:**
According to the tooltip and my current stats, healing per tick should be an average of 6276 on Holy spec for 6966 SP and 15% spec healing bonus +  6% healing increase from Twin Disciplines talent (47588)  with (1.59/5)*6966

**Comment by Echinaceax** [comment]
Have you tested it with and without this particular addon?

try a different dmg meter see if you get same results

**Comment by Keader** [comment]
@Dranah can you confirm what is spell coeff here?
In wotlk was ~80%
I found here about 31.8% in code, how much should be?

**Comment by Dranah** [comment]
It has a 159% coeff for 5 charges, so 31,8% per charge checks out.

However, this coefficient is not currently applied, it feels like the spell just does base healing of 2971 without talents all the time. Holy talents boost it to 3,6k base for Grotesquee

So yeah, Current coeff = 0
Intended coeff = 31,8 per tick
