### ISSUE TITLE
[Priest] Renew

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2515]
**Links:**

139

**What is happening:**
Healing per tick is lower than intended, according to DrDamage. 
Current healing per tick is 1297

**What should happen:**
(0.524/5)*6966 with 6% healing increase from Twin Disciplines talent (47588), should end up with ~2264 healing per tick.

Tested in shadow spec

**Comment by Dranah** [comment]
Does not get any coeff still.

**Comment by Keader** [comment]
It's not exactly a regression.
Last fix work and is needed, but i found a new core issue that suppress this fix, that's why looks like was not working before.

**Comment by Dranah** [comment]
Spell receives now 37,5% coefficient per tick, instead of the intended 13,1% per tick.
