### ISSUE TITLE
[Priest][Holy] Holy Word: Chastise

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2517]
**Links:**

spell id 88625
**What is happening:**
Damage done by this spell is lower than intended, according to DrDamage. 
Average is 4870

**What should happen:**
0.614*6966 + 15% dmg from Chakra + 6% dmg increase from Twin Disciplines talent (47588) should make an average of 6241

**Comment by Echinaceax** [comment]
Have you tested it with and without this particular addon?

try a different dmg/heal meter see if you get same results
