### ISSUE TITLE
[Spell] Arcane Barrage - The Vortex Pinnacle

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2518]
https://www.wowhead.com/spell=87854/arcane-barrage

used by https://www.wowhead.com/npc=45932/skyfall-star

Hits every party member instead of hitting just one at random.
This makes the stars very difficult to handle as their damage output it above the roof.

How it should work: Each barrage should only target 1 random enemy (includes pets, totems, etc).

**Comment by giles1508** [comment]
getting a little silly now this one :)  if u dont have huge aoe ur pretty much ended here
