### ISSUE TITLE
[Vote Points] lost when Inventory full

### ISSUE THREAD

**Issue by laso49** [WoWManiaUK/Blackwing-Lair#2519]
**What is happening:**
The first time I logged in after voting, I saw a message in chat telling me I was given 2 vote points.
My inventory was full at the time, and I was not given them.

**What should happen:**
The Vote points should either be mailed to me when inventory is full OR you should wait till I have logged in with inventory space before trying.

**Comment by Echinaceax** [comment]
Seems more of a suggestion than a reign server bug 

Maybe post here https://wow-reign.com/forum/
that way if there is something they can do to improve it they will

**Comment by wow-mania** [comment]
Will not change this. Just be careful.
