### ISSUE TITLE
[NPC] Thrall - phasing issue - Mount Hyjal

### ISSUE THREAD

**Issue by Healwho** [WoWManiaUK/Blackwing-Lair#252]
https://www.wowhead.com/npc=54313/thrall#map
![wowscrnshot_122118_004444](https://user-images.githubusercontent.com/45921854/50326756-ffe26a00-04b9-11e9-9515-693bd443e433.jpg)
Sent to speak with Thrall from SW and he is not in the Location marked on the map or with the location on wow-head in Hyjal

**Comment by Dranah** [comment]
https://www.wowhead.com/quest=29439/the-call-of-the-world-shaman

**Comment by Dranah** [comment]
NPC is there but phased.
