### ISSUE TITLE
[NPC] Vendor Rugok  -  not allowing 2 hour refund

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2521]
**Links:**

https://www.wowhead.com/npc=58155/rugok#sells:50-2

**What is happening:**

Anything bought from this vendor isnt allowing the items to have the 2 hour refund feature that was added in wotlk to items bought for tokens and badges etc,  which means that if you make a mistake,  you cannot exchange it,   and GM's are not instructed to exchange items

Its possible that when the code was changed to force the vendor to sell gear that the client isnt meant for to align it with our progression ideas it may have removed this feature,  either way this needs to be addressed, as 2200 valor is over 2 weeks worth of heroics and that's a long time to farm more valor for a mistake

**What should happen:**

Every single vendor in the game that sells gear for badges or currency etc like valor or justice should have this 2 hour refund available on every item

**Comment by giles1508** [comment]
added high prio simply because i found out the hard way with this today and it hurt !   and i don't want anyone else having this happen to them !

**Comment by Rushor** [comment]
![I](https://i.imgur.com/QW9BDm1.jpg)
![I](https://i.imgur.com/QQrMF0p.jpg)

refund works on dev. so this has been fixed?
