### ISSUE TITLE
[Quest] Cleansing the Afflicted - Darkshore

### ISSUE THREAD

**Issue by bazant30** [WoWManiaUK/Blackwing-Lair#2523]
Links:
https://www.wowhead.com/quest=13545/cleansing-the-afflicted

What is happening:
Fulborgs keep attacking you after blob is killed.

What should happen:
Fulborg should turn friendly and have some dialog. ("Thank you for saving me, stranger.")

**Comment by Rushor** [comment]
http://cata.cavernoftime.com/quest=13545
