### ISSUE TITLE
[General] Buffs disappear on logout/phasing

### ISSUE THREAD

**Issue by Imba232** [WoWManiaUK/Blackwing-Lair#2525]
**Links:**

**What is happening:**

Buffs from any other class or those applied by you like flasks/scrolls etc disappear when you logout or when you tp in and out of dungeon and you have to reapply them.

**What should happen:**

Buffs shouldn't disappear unless you die.

**Comment by sarahkay88** [comment]
@imba232 can you please provide me with more info
tested this on dev on my pally, used a flask and then got a priest and druid to buff me after relog I only lost one buff.

**Comment by Keader** [comment]
It's not correct.
