### ISSUE TITLE
[Item=68729] Elementium Lockbox

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2528]
**Links:**
https://www.wowhead.com/item=68729/elementium-lockbox
from WoWHead

**What is happening:**
Opening the lockbox with the Obsidium Skeleton Key, it give "empty slot". I tryied on 3 lockboxes and all 3 was empty.

**What should happen:**
The lockbox should contain several green items.

**Comment by kDracku** [comment]
Can confirm the lockboxes are empty

**Comment by Rushor** [comment]
![I](https://i.imgur.com/vsfsKvH.jpg)

will now always contain an item
