### ISSUE TITLE
IPV6

### ISSUE THREAD

**Issue by Healwho** [WoWManiaUK/Blackwing-Lair#253]
![wowscrnshot_122118_005714](https://user-images.githubusercontent.com/45921854/50327388-e1ca3900-04bc-11e9-9b28-b71624df8853.jpg)

The 128bit IPv6 is not opperating in game and takes away from Net sec and preformance.

**Comment by wow-mania** [comment]
This is a client issue and we cannot do anything about it. If it is a bug, which I am not sure it is, it was like this on retails and we cannot change the client executable.
