### ISSUE TITLE
[Spell] Lava Lash

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2530]
ID 60103

Spell calculates damage wrong.

**How it should work:**
Deals 260% of the offhand weapons damage, increased by 40% if enchanted with Flametongue. 

**How it works atm:** As it shows, the damage is way higher than intended (looks exactly double), and is completely ignoring whether the flametongue effect is applied or not. 
TEST:
Offhand Damage 440-785

Expected damage: Without flametongue 1144- 2041
Actual damage: Without Flametongue 2406-4066
Expected Damage: With Flametongue 1601- 2857
Actual Damage: With flametongue 2404-4205

PS: I think the offhand penalty 50% is not applied as it should be. It seems to calculate from raw weapon damage, rather than your offhand damage on the character sheet.

**Comment by TheSale** [comment]
https://www.youtube.com/watch?v=eEqMImbZkdM
here is dps and setup from retail
at 1:48 time of video he show off hand weapon that has 889-1652 around duble damage of your tested weapon
17:05 he start dps
his LL doing from 7k to 10k non crit

**Comment by Dranah** [comment]
My test was done with a naked shaman, no buffs, no glyphs, no talents, no other abilities used, nothing, so that those other mods would not affect my test. 
The person in the video has all of it running, so the two cannot be compared.

First, the offhand damage in my post is the actual character sheet offhand damage (past modifiers), not the one displayed on the weapon tooltip. The two are not the same.
I have tested with a naked shaman with base ~300 attack power, while the shaman on the video has 6k+ and further procs in combat. AP increases the offhand damage (adds onto weapon damage) largely. Mastery (+fire damage mod), talents (especially improved lava lash), buffs, glyph (of lava lash), you can tell how much the rest affects it, I have not used any of those.

My test was aimed at telling if the 260% weapon damage calculation is done right, ruling out all other factors. And it is not, it's either taking too much of the weapon damage, or the offhand penalty forgets to apply, either way it does 2 times the expected.

If I added gear, glyphs, talents, buffs and spells that the shaman in the video uses, my LL would hit easily 15k noncrit with a worse of weapon than his (as do shamans in current RDFs right now, critting up to 35k in way worse gear than this shaman).

**Comment by TheSale** [comment]
this morning I did test of 4milion damage on doll in sw
I had average damage of my lava lash 14k or 16k damage per hit with crit of at max 23k
http://prntscr.com/o6gy9u
here you can see that there are all buffs one me, flame shock, 5 searing totem stacks and my lava lash did 11k damage and did not consume stacks of searing totem

now it consume stacks but doing 30k damage non crit and over 70k crit damage
http://prntscr.com/o6h0qt

here is test with Imba shaman he unequiped 3 items to get  near my ilvl 319, but he had enchants and gems so he is also a bit better than my shaman and he hit 90k crit, on full gear he hit 100k crit
http://prntscr.com/o6gpkl

**Comment by Dranah** [comment]
The problem was always there. 
Your shaman is shit geared and wasn't supposed to do any more than 7k-8k per hit in the first place.
The parses you got (14-16k) is exactly double of the intended for your gear level.
The fix on improved lava lash went live meanwhile, which means it is now boosting the damage of lava lash greatly. Truthfully the fix shouldn't have gone live at all, as it wasn't confirmed yet, so something probably went sideways and now it gives too much damage, nonetheless, it doesn't belong to this thread.

This thread is about LL calculating double of the weapon damage intended, and i'd appreciate if you didn't make me explain it over and over again. It is a waste of time.

**Comment by TheSale** [comment]
in 9 am I am doing 16k at average damage that included crit of 22k and hit of 10k
and few hours after I am doing 70k crit and 38k hit
with same gear

in retail video that I linked earlier guy even said it is not best items but it will do the job
he said he did not had 1 single enhacment gear, and he did not even managed to find cloak, neck and shoulders he using that from healing spec, he has no enchants and no gems for enhancment gear.
and hands and bracers are green 306 ilvl


> The person in the video has all of it running, so the two cannot be compared.

you did not even watched video, I even have better items than he, he has 3 intelect items and 2 lower than mine, and we doing almost neck to neck damage, but I dont do double damage as you presented the issue. and he pull 24k crit LL http://prntscr.com/o7awyx

you dont have to explain to me anything, I am giving you all the proofs and you do with it what ever you want.

**Comment by Dranah** [comment]
Ignoring your comments would be rude, that's why I have to explain why your numbers are off.
Either way, the fix works, the offhand penalty now applies as intended.
