### ISSUE TITLE
[Spell] Frost Strike / Threat of Thassarian interaction

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2531]
ID 49143
ID 66192

Threat of Thassarian makes FS capable of doing damage with both the main hand and offhand weapon.
However the penalty to offhand damage does not properly apply it does the exact same damage as the main hand version.

**How it should work:** The offhand damage is normally 50% of a normal hit. With the talent Nerves of Cold steel (ID 50138) this can be increased to 62,5% of a normal hit. That's how frost strike-offhand should calculate too.

**Comment by giles1508** [comment]
hmm weird,  when i was in heroic earlier on skada the frost strike main hand was higher than off hand,  ill try again now when server is up,  i also need to report a few other things now working for frost

**Comment by Dranah** [comment]
Usually the DK has a higher level/damage main hand weapon equipped than offhand if his weapons arent identical (you are to put better damage in MH).
It needs to be tested with an identical MH and OH weapon.

**Comment by giles1508** [comment]
Yeah I got same in both,  I'll spend 5 mins on a dummy later to find out, not at home atm

**Comment by giles1508** [comment]
![WoWScrnShot_062519_211130](https://user-images.githubusercontent.com/50211643/60129852-dc141f80-978d-11e9-8ce0-126cb5e4fe26.jpg)

it is doing less dmg than the main hand,  but only slightly 
was less than 3 mins on dummy, but these were the stats with the exact same weapon in both hands

mainhand : 
minimum hit - 5.6k
maximum hit 14.4k  ( crit )
average hit 8.5k

off-hand: 
minimum hit 5.1k
maximum hit 14.0k ( crit )
average hit 7.8k  

so its defo not hitting the same,  it too close indeed,  but defo not hitting the same

**Comment by Dranah** [comment]
That's what I call RNG. It doesn't get the 50% penalty for sure. The rest is just details.
