### ISSUE TITLE
[Quest] To Greymane Manor - ID 14465 - npc doesn´t offer quest - Gilneas 

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2532]
**Links:**
Quest: https://www.wowhead.com/quest=14465/to-greymane-manor
NPC: https://www.wowhead.com/npc=36452/gwen-armstead

**What is happening:**
The NPC Gwen Armstead isn´t offering the quest anymore. I finished all quests to this point (except one: Grandma's Cat, which i believe is a side quest), so everything was in order and went perfect. Now i can´t continue, he is simply not offering the next quest.

Also this worked before. Couple of days/weeks ago he did offer the quest.

![To Greymane Manor - how it is](https://user-images.githubusercontent.com/18005338/59979509-2019ef80-95e9-11e9-8c95-01d269dab852.png)

**What should happen:**
He should offer the quest "To Graymane Manor".

**Comment by sarahkay88** [comment]
Grandma's quest is not the side one. Ready to go which follows grandma quest is the optional quest.
@giles can you confirm please

**Comment by giles1508** [comment]
Grandmas cat isnt a side quest,   its 100 % needed to complete the chain
and ive already got a report up about it,   im just waiting for rushor to fix then i can continue with my testing

**Comment by giles1508** [comment]
closing as gwen isnt supposed to give you the quest until you complete the grandmas cat one
