### ISSUE TITLE
[Spell] Firebolt - warlock imp

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2534]
ID 3110

Does too low damage, spell coefficient is wrong.

How it should work: should have 32,9% SP coeff

How it works atm: experimentally, sp coef is around 19,5%

**Comment by Dranah** [comment]
This needs to be readjusted. The coefficient is super high now, possibly due to the confusion on the fireball report.

**Comment by Keader** [comment]
Doubled?

**Comment by Dranah** [comment]
Corrected. Good now.
