### ISSUE TITLE
[Spell] Searing bolt 

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2536]
ID 3606
Cast by Searing totem.

The spell coefficient of this totem is out of the roof, it does a metric ton of damage.

How it should work: It has a spell coefficient of 400,8% however this is applied for the entire spell with its 24 ticks. That means 16,7% coeff per-tick,
How it works atm: Current experimental coefficient is about 41,5%, or 996% for the entire spell.

**Comment by giles1508** [comment]
thank you !
