### ISSUE TITLE
[Spell] Windfury Weapon

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2537]
ID 8232

The proc currently gives 2 extra attacks instead of 3.

**How it should work:** Should give 3 extra attacks

"Each hit has a 20% chance of triggering three extra attacks with 4430 bonus attack power"

**Comment by Slydee23** [comment]
can we get high prio :D ?

**Comment by Keader** [comment]
Fixed @Slydee23

**Comment by Slydee23** [comment]
Oh nice love you
