### ISSUE TITLE
[Quest] Bagging Bisp - Quest ID 27154

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2539]
**Links:** https://www.wowhead.com/quest=27154/bagging-bisp#comments

**What is happening:**

No dialogue possible to fulfil quest and fight him.
https://puu.sh/DJPOU/2cb1c051ae.jpg

**What should happen:**

https://puu.sh/DJPPL/341efcbf8b.png

Should 'propose' this dialogue in order to fight him.

**Comment by Rushor** [comment]
![](https://i.imgur.com/ssqmQPu.jpg)
![](https://i.imgur.com/AC2WdnC.jpg)
![](https://i.imgur.com/QlG4n0J.jpg)
