### ISSUE TITLE
Human Starter Zone (Paladin)

### ISSUE THREAD

**Issue by Tatoepaladin** [WoWManiaUK/Blackwing-Lair#2541]
**What is happening:**
You get to the quest for your class. But it still says you are in need of learning Judgement skill from the trainer.

**What should happen:**
Quest should recognize that the skill has been learned before/after accepting the quest.

**Comment by sarahkay88** [comment]
#669 I'll. Reopen the old report now.

**Comment by Echinaceax** [comment]
@Kitzunu this is a duplicate of #842
angel referenced hers because bagi had added his newest info to that report.
still a duplicate

**Comment by sarahkay88** [comment]
#669 human quest #842 dwarf quest
