### ISSUE TITLE
Human Starter Zone(Mage)

### ISSUE THREAD

**Issue by Tatoepaladin** [WoWManiaUK/Blackwing-Lair#2542]
**What is happening:**
You are able to complete the first quest "Killing the Worgs"
After that there are no more quests as a mage at level 4

**What should happen:**
Continue quest chain after the Worg Quest

**Comment by sarahkay88** [comment]
Not sure what's happened but this use to work

**Comment by Kitzunu** [comment]
@Rushor check AllowableClasses and Prev/NextQuestID most likely they are linking to wrong class quests.

**Comment by Rushor** [comment]
okay

**Comment by Rushor** [comment]
yep the AllowableClasses  was wrong. fixed

**Comment by Rushor** [comment]
![](https://i.imgur.com/Nmi4eVN.jpg)
