### ISSUE TITLE
Graveyards in Northern Stanglethorn Vale not working

### ISSUE THREAD

**Issue by Tatoepaladin** [WoWManiaUK/Blackwing-Lair#2543]
**Links:**
https://github.com/WoWManiaUK/Blackwing-Lair/issues/154
This is the previous issue that says "FIXED" It is not.
**What is happening:**
Dying in Northern Stranglethorn Vale and spawning at the Graveyard in Sentinel Hill, Westfall
Instead of a 30sec trip took me 15min to get back to my body.

**What should happen:**
Should spawn at the nearest Graveyard to run back.

**Comment by sarahkay88** [comment]
#1543
