### ISSUE TITLE
[Item] Darkmoon card : hurricane  (strength)

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2544]
**Links:**

https://www.wowhead.com/item=62049/darkmoon-card-hurricane    -  updated tooltip (  current one is 321 str with a 7000 nature proc
![WoWScrnShot_062319_230426](https://user-images.githubusercontent.com/50211643/59982499-5700fd00-960b-11e9-902c-0ebd1e2d326f.jpg)

**What is happening:**

card is not proccing the nature damage at all,   full heroic and not a single proc  :(

**What should happen:**

struggling to find the exact proc rate,  but before 4.2 the damage was able to crit and the base damage was as you can see in the following tooltip
https://wowwiki.fandom.com/wiki/Darkmoon_Card:_Hurricane

however in the patch notes you can see that it states in 4.2 the crit chance was removed and dmg was modified,  so now it does a flat 7k nature damage
if i can fidn the actual proc rate i will add it,   however,   it works on a basic of the faster you attack the more procs,  rather than a flat ( 2 procs per minute )   and this is why classes that duel weild take it more over classes that only use a 2 hander,  as it doesnt proc as much for them

**Comment by Rushor** [comment]
![](https://i.imgur.com/D4mk486.jpg)

**Comment by giles1508** [comment]
Awesome dude,  what was the proc chance did u manage to find it?

**Comment by TheSale** [comment]
I had hurricane agility version for 2 weeks or so, and I did not had issue with proc,
for my testing in 20 afk doll dps, my druid cat did around 11% damage with trinket comparing only to auto attack, with average of 7k damage, sometimes over 7k sometimes under, but at average was 7k.
if I added some spells and rotations, it might add more proc, but damage percentage would go down.

**Comment by giles1508** [comment]
Well it's a good job I made about the strength one then not the agility one :)

**Comment by Rushor** [comment]
procc chance is from dbc for now

**Comment by giles1508** [comment]
Is that 3 % per every attack, so I mean every single attack a melee can do should have a chance to proc, 3% seems rather low,  but same as anything would need testing,  I'll do a 5 minute white dmg test and a 5 minute full rotation test to see when it goes live
