### ISSUE TITLE
URGENT

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2545]
I can asume that discord and skype are muted
So I hope this message reach you @wow-mania @fvicaria 

Server is down, we need you

**Comment by Echinaceax** [comment]
Thanks 
i think jani will see ALL the PM soon

**Comment by TheSale** [comment]
I know he will see, I hoped that this could trigger some attention on mail or somewhere 
server is down almost 7 hours now

**Comment by Echinaceax** [comment]
no quicker than testers PM in discord it wont :) 
Yes its very unfortunate but if jani is asleep (timer is irrelevant)

it will be up soon
