### ISSUE TITLE
[Hunter] [Talent] Thrill of the Hunt

### ISSUE THREAD

**Issue by Imba232** [WoWManiaUK/Blackwing-Lair#2546]
**Links:**

http://cata-shoot.tauri.hu/?spell=34499

**What is happening:**

Arcane Shot, Explosive Shot and Black Arrow don't have a chance to regain 40% of the base focus cost of the shot.

**What should happen:**

Arcane Shot, Explosive Shot and Black Arrow should have a 15% chance to regain 40% of the base focus cost of the shot.

**Comment by Echinaceax** [comment]
@Keader - adding the link to duplicate here "for now" incase they dont reply before before to copy over fresh info
