### ISSUE TITLE
[Hunter] [Talent] Thrill of the Hunt

### ISSUE THREAD

**Issue by Imba232** [WoWManiaUK/Blackwing-Lair#2547]
**Links:**

http://cata-shoot.tauri.hu/?spell=34499

**What is happening:**

After further testing it seems that the talent only works for the Arcane Shot portion of the talent.
But for Arcane Shot it gives back 8 focus with the Efficency talent from MM which reduces Arcane Shot focus by 3. It gave back 10 without the talent. Now I'm not sure if it should always give 10 because Thrill of the Hunt says 40% of the base focus cost of the shot or if it should scale with the talent from mm.
After hundreds of Explosive Shots and Black Arrows I had no single TotH proc so we can assume it doesn't work for these 2. Should give 20 focus for ES and 14 focus for BA.

**What should happen:**

Arcane Shot, Explosive Shot and Black Arrow should have a 15% chance to regain 40% of the base focus cost of the shot.

**Comment by Imba232** [comment]
Even the 15% proc chance seems to be way lower because I'm only getting a proc from Arcane Shot once every 3-4 minutes/50-70 shots.

**Comment by Echinaceax** [comment]
ive asked imba to copy info over to there first report
