### ISSUE TITLE
[Hunter] [Spell] Steady and Cobra Shot

### ISSUE THREAD

**Issue by Imba232** [WoWManiaUK/Blackwing-Lair#2548]
**Links:**

Cobra Shot ID 77767
Steady Shot ID 56641

**What is happening:**

Cobra Shot and Steady Shot have a base cast time of 2.5 seconds.
https://imgur.com/a/X3jxmBr

**What should happen:**

Cobra Shot and Steady shot should have a base cast time of 2 seconds.

**Comment by Keader** [comment]
It's invalid i belive.
Since wotlk, all spells with SPELL_ATTR0_REQ_AMMO , has +500 ms to be launched.
And it's added after casttime mods, so is always there.

**Comment by Dranah** [comment]
There isn't even ammo on cataclysm anymore. Dafuq?
This is not invalid, just uses wotlk settings for some reason. Need to be updated to cata.
