### ISSUE TITLE
[Profession][Alchemy] Transmute: Living Elements

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2549]
**Links:**

https://www.wowhead.com/spell=78866/transmute-living-elements

**What is happening:**
This Daily Alchemy CD Covnerts 15 Volatile Life into an item called "random volatile element"
https://imgur.com/8nUzazZ

**What should happen:**
This should convert 15 volatile life into 14-16 volatile of earth, fire, water or air.

**Comment by Rushor** [comment]
http://i.imgur.com/aMXcH.jpg

yeah it should not give you the item "random volatile element"

**Comment by Rushor** [comment]
https://www.wowhead.com/item=54464/random-volatile-element#comments:id=1256770

**Comment by Rushor** [comment]
Effect 0: Id 157 (SPELL_EFFECT_CREATE_ITEM_2)

is the spelleffect that needs to be there for now. but i added the loot for it

**Comment by zippoking** [comment]
I just transmuted 15 volatile life and this is what i got:
![Transmute Volatile Elements - how it is](https://user-images.githubusercontent.com/18005338/60985288-8159f680-a33d-11e9-91bb-1b0c233a27e9.PNG)

So i still get the random volatile elements....they should not appear in my bag.

Quote from [wowwiki](https://wowwiki.fandom.com/wiki/Random_Volatile_Element):
> Random Volatile Element is not a real item, but a placeholder for [Transmute: Living Elements]. The actual result of the transmute will be Volatile ingredient.


But good thing is, that i also get another type of the volatile elements.

**Comment by Rushor** [comment]
Fully fixed now.

the result depends on the zone:

Mount Hyjal: Volatile Fire

Vashj'ir: Volatile Water

Deepholm: Volatile Earth

Uldum: Volatile Air

if you are in a different zone, you will get a random listed item amount.

![I](https://i.imgur.com/Vid6cCh.jpg)

**Comment by Echinaceax** [comment]
@Rushor 
Test on live just now, and even though it shows 14 in my log in my bag is only gave 13 


1. still giving Random violavile element

![still giving](https://user-images.githubusercontent.com/39439201/67681823-5fd55700-f98e-11e9-829d-d3927f018718.jpg)

14 and only give 13 

![14](https://user-images.githubusercontent.com/39439201/67681856-74195400-f98e-11e9-8919-ea7f58a7b1a8.jpg)
![only 13](https://user-images.githubusercontent.com/39439201/67681862-767bae00-f98e-11e9-9ba0-94ac85695609.jpg)

**Comment by Echinaceax** [comment]
anyother small issue too @Rushor - CD says midnight , but its 00.23 and still says it  

![cd mid](https://user-images.githubusercontent.com/39439201/67725380-786f5c80-f9e2-11e9-8d27-b36a20dde71d.jpg)

**Comment by Rushor** [comment]
The random item is Just there in order to remove a Server runtime error. Just delete it. Everything Else works

**Comment by Echinaceax** [comment]
Silly -1 viola though @Rushor 
 today same happend

15 made 
![15 fire](https://user-images.githubusercontent.com/39439201/67760871-64f3de00-fa42-11e9-85d3-4e9c3eac1d95.jpg)

and only given 14
![14 in bag](https://user-images.githubusercontent.com/39439201/67760902-7a690800-fa42-11e9-91b9-028a9b87e7e3.jpg)

**Comment by Rushor** [comment]
yeah that is related to the core change sadly
