### ISSUE TITLE
Spell Tool tip and functionality

### ISSUE THREAD

**Issue by Healwho** [WoWManiaUK/Blackwing-Lair#255]
![wowscrnshot_122118_014113](https://user-images.githubusercontent.com/45921854/50328570-a54d0c00-04c1-11e9-83e6-6636827cfe1e.jpg)

Penance is not hitting instantly as it reads and the tool tip states it should. Also, the math is incorrect. 0.97+0.97= 1.94

**Comment by Dranah** [comment]
It works fine.
Hits the target once when you begin channel and 2 more times at the 0,97 and 1,93sec mark.
Total of 3 hits as it should be.
https://imgur.com/sBfUH1L

As for the math, it's called rounding.
