### ISSUE TITLE
[Quest / Quest order ]   worgen starting zone  / battle for gileas section

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2554]
**Links:**

https://wow.gamepedia.com/Worgen_starting_experience  -  quest order as always :)

**What is happening:**

https://wow.gamepedia.com/Flank_the_Forsaken   is available to take early

**What should happen:**

https://wow.gamepedia.com/Flank_the_Forsaken   should only be available , 
 AFTER you hand in 
https://wow.gamepedia.com/Betrayal_at_Tempest%27s_Reach

**Comment by Rushor** [comment]
added

**Comment by giles1508** [comment]
What is happening:

[10] Last Meal +  [11] Slaves to No One  are available to take before you hand in  [10] Flank the Forsaken  

and   [11] Push Them Out   is available also,  which should only be available after 
	  [10] Liberation Day /   [10] Last Meal /   [11] Slaves to No One    have all been completed

  [10] Liberation Day /   [10] Last Meal /   [11] Slaves to No One  should all be active as soon as you hand in  [10] Flank the Forsaken ,    as you should be able to take all 3 same time

**Comment by Rushor** [comment]
all added

![](https://i.imgur.com/KH1e33g.jpg)
![](https://i.imgur.com/vlxxyuI.jpg)
![](https://i.imgur.com/Uzw6eEV.jpg)

**Comment by shadowfires** [comment]
**Flank the Forsaken**

**Link:**
https://wow.gamepedia.com/Flank_the_Forsaken

**What is happening:**
Not able to talk with Lord Hewell to obtain a ride.

**What should happen:**
After accepting the quest, the player is supposed to talk with Lord Hewell to obtain a ride to the Livery Outpost.
