### ISSUE TITLE
[item]  Emerald essence

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2555]
**Links:**

https://www.wowhead.com/item=37815/emerald-essence

**What is happening:**

this item is not despawning when you leave the instance and is allowing players to take it to main cities to spawn infitate amount of drakes in places,   which will lead to server lag and maybe drops in fps for players with lower spec pc's

**What should happen:**

item should vanish from bags upon leaving the instance

**Comment by Kitzunu** [comment]
Does this happen with the 2 other dragon items from Oculous as well?

**Comment by Rushor** [comment]
ITEM_EMERALD_ESSENCE                          = 37815,
    ITEM_AMBER_ESSENCE                            = 37859,
    ITEM_RUBY_ESSENCE                             = 37860,

**Comment by Rushor** [comment]
fixed

item removed once instances is left

**Comment by Rushor** [comment]
![](https://i.imgur.com/HNqW4fQ.jpg)
![](https://i.imgur.com/11BlMRW.jpg)
