### ISSUE TITLE
[NPC] Deep Murloc Drudge - Throne of the Tides

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2556]
NPC ID 39960

On normal mode of TOTT they currently give rep with Earthen Ring by default and with whatever tabard you have equipped otherwise. 
These are the small adds that Nazjar spawns in the gauntlet endlessly until you finish all the elite mobs. You can currently let them keep coming endlessly, allowing you to farm non stop rep.

How it should work:
These creatures should award no reputation.

**Comment by Rushor** [comment]
fixed
