### ISSUE TITLE
[Quest] Not Quite Shipshape - cosmetic issue - Gilneas

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2557]
https://www.wowhead.com/quest=14404/not-quite-shipshape

The objectives aren't glowing as they should when you're on the quest.
This makes them slightly more difficult to find, which can be a hassle to newer players.

https://www.wowhead.com/object=196810/shipwrights-tools
https://www.wowhead.com/object=196809/planks-of-wood
https://www.wowhead.com/object=196808/barrel-of-coal-tar

**Comment by Rushor** [comment]
also - gameobject is double spawned

**Comment by Rushor** [comment]
![](https://i.imgur.com/H6qj0C9.jpg)
