### ISSUE TITLE
[NPC=40936] Faceless Watcher - Throne of the Tide

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2558]
**Links:**
https://www.wowhead.com/npc=40936/faceless-watcher
from WoWHead

**What is happening:**
The Void Rip ability https://www.wowhead.com/spell=76604/void-rip trow you up over the hall's roof for a very long distance and time. If all the party is jumping, they reset their life making impossible to kill them and to reach the boss at the end of their hall. The two of them at the boss door trow you up again everytime you finally touch the ground. The only way to reach the boss is to have the right classes in the party to stun them repeatedly.

**What should happen:**
The void rip ability should last 3 seconds and should push you until the roof of the hall, not over it.

**Comment by Rushor** [comment]
fixed! with next update

![I](https://i.imgur.com/AkRjpXP.jpg)
