### ISSUE TITLE
[Quest] Gar'gol's Gotta Go - ID 25328 - Mount Hyjal

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2559]
**Links:**
Quest: https://www.wowhead.com/quest=25328/gargols-gotta-go
Object: https://www.wowhead.com/object=204580/gargols-personal-treasure-chest
Item: https://www.wowhead.com/item=52789/rusted-skull-key

**What is happening:**
When you accept the quest, there is no chest to loot the key from. 
![Gar'Gol's gotta go - how it is](https://user-images.githubusercontent.com/18005338/60172967-132a1580-980e-11e9-94e3-da4a707cffff.png)

**What should happen:**
When you accept the quest, you get access to the chest. From this chest you get the key to finish the quest.
![Gar'Gol's gotta go - how it should be](https://user-images.githubusercontent.com/18005338/60172965-132a1580-980e-11e9-85f7-00d811ba02ea.png)
![Gar'Gol's gotta go - how it should be 2](https://user-images.githubusercontent.com/18005338/60172968-13c2ac00-980e-11e9-97ca-6ed01f984eef.png)

**Comment by Rushor** [comment]
respawntimer is way too high. reduced to 5 min.
