### ISSUE TITLE
Spell Inner Fire

### ISSUE THREAD

**Issue by Healwho** [WoWManiaUK/Blackwing-Lair#256]
![wowscrnshot_122118_014917](https://user-images.githubusercontent.com/45921854/50328917-07f2d780-04c3-11e9-9ceb-b082f4922416.jpg)
![wowscrnshot_122118_014728](https://user-images.githubusercontent.com/45921854/50328922-0a553180-04c3-11e9-9828-dbf96f7b6798.jpg)

This spell is only giving 52.86% armor from items and 531 spell power not the 60% and 532

**Comment by Dranah** [comment]
7242 x 160% = 11587 
I don't see anything wrong with that. How did you get that 52,86%?

**Comment by Keader** [comment]
7242 * 1.60 = 11587.2 , this get a truncate to just integer part. Same to spell power.
