### ISSUE TITLE
[Priest][Discipline] Penance dmg

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2562]
**Links:**

spell id 47540

**What is happening:**
damage is roughly lower than what it should be based on the spell's coefficient
~4000 dmg/tick with 7628 spellpower

**What should happen:**
Damage should be ~4500/tick with (1.374*7628) / 3 according to DrDamage's tooltip 

https://imgur.com/653VbX3

**Comment by Keader** [comment]
Fixed heal too
