### ISSUE TITLE
Normal Cataclysm Dungeon Currency

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#2563]
**Links:**

from WoWHead or our Armory

**What is happening:**

Bosses and completing dungeon in normal mode don't award justice points.

**What should happen:**

All bosses from cataclysm dungeons should award 30 justice points on normal mode and completing the dungeon another 140 justice points.

**Comment by Rushor** [comment]
They reward it, but it's not displayed in the chat. Just cosmetic

https://github.com/WoWManiaUK/Blackwing-Lair/issues/2450#issuecomment-503345957

**Comment by Denrunmt** [comment]
Denrunmt:
> **Links:**
> 
> from WoWHead or our Armory
> 
> **What is happening:**
> 
> Bosses and completing dungeon in normal mode don't award justice points.
> 
> **What should happen:**
> 
> All bosses from cataclysm dungeons should award 30 justice points on normal mode and completing the dungeon another 140 justice points.

Rushor:
> They reward it, but it's not displayed in the chat. Just cosmetic
> 
> [#2450 (comment)](https://github.com/WoWManiaUK/Blackwing-Lair/issues/2450#issuecomment-503345957)


The problem is not only in the chat messages. I've done 3-4 Rdf Normals now and I have 0 Justice Points. I also have no currency tab yet. And It's not just me. Other people also are complaining about that. 

![Screenshot_1](https://user-images.githubusercontent.com/52254524/60213521-5adf8a00-986c-11e9-90ca-a85aebedf9fb.png)
![Screenshot_2](https://user-images.githubusercontent.com/52254524/60213533-603cd480-986c-11e9-9b4a-315bd902778a.png)
