### ISSUE TITLE
[Quest] Disclosure - ID 12710 - Zul'Drak

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2564]
**Links:**
Quest: https://www.wowhead.com/quest=12710/disclosure
NPC: https://www.wowhead.com/npc=28948/malmortis

**What is happening:**
At the very end of his tour he does not say his last line, which is 
*Malmortis says: Farewell.*
And it does not count towards the quest.
![Disclosure - how it is 1](https://user-images.githubusercontent.com/18005338/60202740-8c942900-984b-11e9-82c5-6932e70440ce.png)
![Disclosure - how it is 2](https://user-images.githubusercontent.com/18005338/60202741-8c942900-984b-11e9-9722-df7691161ad6.png)

**What should happen:**
You should follow Malmortis around and at the end his last text is 
*Malmortis says: Your service has been invaluable in fulfilling the master's plan. May you forever grow in power....*
*Malmortis says: Farewell.*

And then it counts towards the quest.
![Disclosure - how it should be](https://user-images.githubusercontent.com/18005338/60202739-8c942900-984b-11e9-8608-96f77bb79eaa.png)

**Comment by Rushor** [comment]
the targeteting is somehow messed up

**Comment by Rushor** [comment]
okay for some strange reason the questcredit must be rewarded at the start of the conversation, but that's blizzlike

![I](https://i.imgur.com/xQyvo8G.jpg)
