### ISSUE TITLE
[Quest] The Maelstrom - portal missing to go to the Maelstrom

### ISSUE THREAD

**Issue by HrPottemager** [WoWManiaUK/Blackwing-Lair#2565]
**Links:**
https://www.wowhead.com/quest=27203/the-maelstrom

**What is happening:**
After accepting the quest Farseer Krogar should open a portal to send you to the Maelstrom to help Thrall.
He never opens one.

**What should happen:**
Farseer Krogar opens a portal and we can step through this is the beginning quest for Deepholm

**Comment by Rushor** [comment]
for alliance the portal is there, need to remove. also add script for different portal teleport position.

maybe also add a gossip, so the portal can be resummoned

**Comment by Rushor** [comment]
![I](https://i.imgur.com/bZeoets.jpg)
![I](https://i.imgur.com/yqQYcUL.jpg)
![I](https://i.imgur.com/VeHWnEI.jpg)

**Comment by HrPottemager** [comment]
Works! +1
