### ISSUE TITLE
[Profession] Jewelcrafting

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2567]
**Links:**
https://www.wowhead.com/skill=2521/cataclysm-jewelcrafting
from WoWHead

**What is happening:**
There isn't any open report about the jewelcrafting skill, but it still have some serious issue that i want to summarise here. I hope some of those will soon be fixed because atm jewelcrafters aren't getting what they should get from their profession, and wasting materials that costs hours of farming.
- Prospecting
It gives "empty slot" 1/3 on obsidium and elementium ores causing a great waste of materials.
- Fire Prism
It gives "empty slot" often also causing a waste of materials.
- Daily Quests
Only 1/5 can be completed atm, causing a delay on learning new recipes. They cause a waste of materials too, if you try to complete the cutting ones if you don't know that they're not working.

Dear devs, when you're setting up your priorities, please give a chance to jewelcrafters! :)

**Comment by 3JIoudyx** [comment]
Indeed, when prospecting elementium ore, 2/4 attempts (stack) give no loot at all.

**Comment by TheSale** [comment]
bro you need to break down issues and everything to report separable...
spell prospecting
item fire prism
quest 1
quest2
quest3
quest4

**Comment by Echinaceax** [comment]
Seems like it regressed somehow 
report on elementium ores #1779 (regression)
report on fire prism #1872 
Report on JC daily 1 reported #1888

**Comment by Rushor** [comment]
refixed with next update
