### ISSUE TITLE
Normal Cataclysm Dungeon Currency #2

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#2568]
Denrunmt:

**Links:**

from WoWHead or our Armory

**What is happening:**

Bosses and completing dungeon in normal mode don't award justice points.

**What should happen:**

All bosses from cataclysm dungeons should award 30 justice points on normal mode and completing the dungeon another 140 justice points.

Rushor: 

They reward it, but it's not displayed in the chat. Just cosmetic

#2450 (comment)

Denrunmt:

The problem is not only in the chat messages. I've done 3-4 Rdf Normals now and I have 0 Justice Points. I also have no currency tab yet. And It's not just me. Other people also are complaining about that.

![Screenshot_1](https://user-images.githubusercontent.com/52254524/60266137-1dbcdb80-98f0-11e9-91a9-478add8de18e.png)
![Screenshot_3](https://user-images.githubusercontent.com/52254524/60266149-231a2600-98f0-11e9-9b70-a4fa3591fe2d.png)

**Comment by Rushor** [comment]
Yeah i thought that was tested already here https://github.com/WoWManiaUK/Blackwing-Lair/issues/2450#issuecomment-503345957

Will check.

**Comment by Denrunmt** [comment]
Okay. Please let me know when it gets fixed.

**Comment by fuzzydunlop** [comment]
Having the same problem.

**Comment by Shycazia** [comment]
Jeah me, too. I already spoke to a GM via an ingame Ticket. He told me to open a Bugreport but its already reported.
