### ISSUE TITLE
Spell Inner Will

### ISSUE THREAD

**Issue by Healwho** [WoWManiaUK/Blackwing-Lair#257]
![wowscrnshot_122118_020846](https://user-images.githubusercontent.com/45921854/50329505-949e9500-04c5-11e9-8e58-49a97f824835.jpg)

The 15% modifier is not granting 15% to any instant cast spell and varies from spell to spell greatly. Even considering any modifiers.

**Comment by Dranah** [comment]
Works properly to me, PW:Fortitude costs 4530 mana by default,, becomes 3850 with Inner Will.
4530 x 0,85 = 3850 sharp.
Same for every other instant spell I have.
