### ISSUE TITLE
[NPC] Quartermaster Ozorg missing in Archerus

### ISSUE THREAD

**Issue by fuzzydunlop** [WoWManiaUK/Blackwing-Lair#2572]
**Links:**  https://www.wowhead.com/npc=28512/quartermaster-ozorg

**What is happening:** The npc Ozorg, who sells the DK starter set is missing

**What should happen:** He should be inside Archerus Hold

**Comment by Rushor** [comment]
https://www.wowhead.com/npc=28512/quartermaster-ozorg#comments

**Comment by Rushor** [comment]
added in phase 169, i he should be there in other phases too, let me know

**Comment by Rushor** [comment]
![I](https://i.imgur.com/lkeOHma.jpg)
