### ISSUE TITLE
[Quest] Slowing the inevitable -  worgen - Gilneas

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2573]
**Links:**

https://www.youtube.com/watch?v=goCQ-Y_EEh0   -   video of the flight you take and npcs you kill
https://www.wowhead.com/quest=24920/slowing-the-inevitable   link to quest
https://wow.gamepedia.com/Slowing_the_Inevitable

**What is happening:**

there is no npcs or bat riders when u exit the building after talking to the king

**What should happen:**

there should be a bat rider and 2 npcs ,  you click the bat then u jump on it and follow a sequesnced flight over enemy forsaken and you use the spell the bat rider gives you to kill them

**Comment by Rushor** [comment]
can you tell me all the npcs that are spawned in the video
they are there, but i need them for adjusting the phase
as far i can see it's plaguesmith, invader and catapult

**Comment by giles1508** [comment]
yeah thats the only ones there,  just the invaders, the plaguesmiths and the catapults

**Comment by Rushor** [comment]
okay thanks!

**Comment by Rushor** [comment]
http://cata.cavernoftime.com/quest=24920

**Comment by Rushor** [comment]
nearly done!

**Comment by Rushor** [comment]
finally fixed

![I](https://i.imgur.com/mOveIAA.jpg)
![I](https://i.imgur.com/mOveIAA.jpg)

**Comment by giles1508** [comment]
working great @Rushor    good work !

**Comment by Rushor** [comment]
thanks :>
