### ISSUE TITLE
[Quest / Quest NPC ]   Flank the forsaken -  worgen

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2574]
**Links:**

https://wow.gamepedia.com/Flank_the_Forsaken   -  quest
https://www.youtube.com/watch?v=Ohr4wxhQVsA   -  video of horse ride pathing

**What is happening:**

not a major issue as you can walk to the next part ,  the the npc " lord hewell "  next to quest giver isnt allowing you a ride to next hub

**What should happen:**

you should be able to speak to npc to get a ride to next hub

**Comment by Rushor** [comment]
@Keader EVENT_PASSENGER_BOARDED

does not work for creatures with sai somehow. if that is fixed then we can fix those kind of issues :o

**Comment by Rushor** [comment]
http://cata.cavernoftime.com/quest=24677

**Comment by Rushor** [comment]
okay done. only difference is that you need to mount the horss by clicking on it once summoned.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/3mqdQxE.jpg)
![I](https://i.imgur.com/jMARl46.jpg)
![I](https://i.imgur.com/DPQvcfs.jpg)
![I](https://i.imgur.com/LDJPVSx.jpg)
