### ISSUE TITLE
[Quest / Quest mob ]  Push them out - worgen

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2575]
**Links:**

https://wow.gamepedia.com/Push_Them_Out

**What is happening:**

the npc  https://wow.gamepedia.com/Executor_Cornell   has a double spawn
all mobs in area seem to have too long of a respawn timer ,  mobs listed below : -

Mob Forsaken Infantry slain x4
Mob Executor Cornell slain
Mob Valnov the Mad slain

**What should happen:**

one of the spawns needs removing
spawn timers need reducing .  its ok for 1 player testing,  but when numerous players are questing there when its live can cause issues

**Comment by Rushor** [comment]
all creatures in that zone need reduce for spawntimer

**Comment by Rushor** [comment]
okay spawntimer for all creatures reduced to 200 seconds down from 7200 seconds.
