### ISSUE TITLE
[Quest=29346] [Daily] The rings the thing - Fishing - Thunderbluff

### ISSUE THREAD

**Issue by Touronmess** [WoWManiaUK/Blackwing-Lair#2576]
**Links:**
https://www.wowhead.com/quest=29346/the-rings-the-thing
https://www.wowhead.com/item=69956/blind-cavefish

**What is happening:**
Not getting the quest fish after 40 attempts when fishing at the [Pools of Vision]

**What should happen:**
A Blind cavefish should be fished up when fishing at the [Pools of Vision] (within 1-5 attempts i've read from the comments)

**Tags**
Daily
Major City

**Comment by Rushor** [comment]
![I](https://i.imgur.com/TxKMHRb.jpg)
