### ISSUE TITLE
[Quest] watershed patrol , Durotar

### ISSUE THREAD

**Issue by crishexxx** [WoWManiaUK/Blackwing-Lair#2578]
**Links:**https://www.wowhead.com/quest=25188/watershed-patrol

from WoWHead or our Armory

**What is happening:** the questchain is broken and cannot be completed

**What should happen:**you should look trough a scope for 4 npc needing quests done for them but they just dont show up and you cannot do the quest

**Comment by Rushor** [comment]
the npcs are there, but the killcredit is missing once you helped them

**Comment by Rushor** [comment]
connected with https://github.com/WoWManiaUK/Blackwing-Lair/issues/2616

**Comment by Rushor** [comment]
The quests you need to do to get credit for this:
Raggaran:
Raggaran's Rage - Kill 4 Razormane Quilboar and 4 Razormane Scouts
Raggaran's Fury - Kill 5 Razormane Dustrunners and 5 Razormane Battleguards.
(New version of Enroachment)

Grandmatron Tekla:
Spirits Be Praised - Escort Grandmatron Tekla to Raggaran

Misha Tor'kren:
Lost But Not Forgotten - Gather 250 crocolisk teeth. (They drop in batches of ~25 to ~40.)

Zen'taji:
Unbidden Visitors - Scare away 3 Wayward Plainstriders
That's the End of That Raptor - Kill Screamslash

**Comment by Rushor** [comment]
moreover the quests

    Spirits Be Praised
    Raggaran's Rage
    Lost But Not Forgotten
    Unbidden Visitors

should only be shown once quest "watershed patrol" is accepted

**Comment by Rushor** [comment]
![I](https://i.imgur.com/LPDXfAU.jpg)
