### ISSUE TITLE
Spell Power Word Fortitude

### ISSUE THREAD

**Issue by Healwho** [WoWManiaUK/Blackwing-Lair#258]
![wowscrnshot_122118_021410](https://user-images.githubusercontent.com/45921854/50329684-4e960100-04c6-11e9-83f0-77beed198c0f.jpg)
![wowscrnshot_122118_021402](https://user-images.githubusercontent.com/45921854/50329686-4fc72e00-04c6-11e9-83c7-a0cc731024f1.jpg)

Supposed to give 585 only giving 584. While this seems trivial: 25 people missing 1 stamina is a possible wipe situation. Either way should give more then it does.

**Comment by Keader** [comment]
Caused by Truncation error.
Cant be fixed right now, and is not a big deal in the end.
