### ISSUE TITLE
[Spell][Druid] Pounce - ID 9005 - not learnable at level 32

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2581]
**Links:**
Spell: https://cata-twinhead.twinstar.cz/?spell=9005
Spell: https://wowwiki.fandom.com/wiki/Pounce
Spell: http://cata.cavernoftime.com/spell=9005

**What is happening:**
My spellbook says, that i should go see my trainer to learn Pounce. At the trainer it says, that Pounce requires level 36.
![Pounce - how it is 1](https://user-images.githubusercontent.com/18005338/60355554-f0932a80-99ce-11e9-8114-61387be45e35.png)
![Pounce - how it is 2](https://user-images.githubusercontent.com/18005338/60355553-f0932a80-99ce-11e9-82c7-9e0022e8caff.png)

**What should happen:**
I should be able to learn Pounce from level 32 and above, not 36 according to research.

**Comment by Rushor** [comment]
level requirement reduced to 32

![I](https://i.imgur.com/oTWn5kT.jpg)
