### ISSUE TITLE
[Quest] Victory from within - ID 27612 - portals missing - Eastern Plaguelands

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2586]
**Links:**
Quest: https://www.wowhead.com/quest=27612/victory-from-within
Portal 1: https://www.wowhead.com/npc=46102/hall-of-arms-credit
Portal 2: https://www.wowhead.com/npc=46103/library-wing-credit

**What is happening:**
The portals in the two wings of the cathedral are missing. You can´t complete the quest.
![Victory from within - how it is](https://user-images.githubusercontent.com/18005338/60366431-d3b92000-99eb-11e9-972d-ad6eda306cd8.png)

**What should happen:**
You should be able to click the two portals in the cathedral.
![Victory from within - how it should be](https://user-images.githubusercontent.com/18005338/60366483-ee8b9480-99eb-11e9-9ff8-aaaa7bbcad09.png)
![Victory from within - how it should be 2](https://wow.zamimg.com/uploads/screenshots/normal/245851-victory-from-within.jpg)

**Comment by Rushor** [comment]
![I](https://i.imgur.com/8u40ZTn.jpg)
![I](https://i.imgur.com/tDHm4bl.jpg)
