### ISSUE TITLE
[ITEM] Body of Warlord Threshjin - Eastern Plaguelands

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2587]
**Links:**
Quest: https://www.wowhead.com/quest=27481/out-of-the-ziggurat
NPC: https://www.wowhead.com/npc=10822/warlord-threshjin
Item: https://www.wowhead.com/item=61315/body-of-warlord-threshjin

**What is happening:**
After you kill Warlord Threshjin, he is not dropping his body as a quest item to finish the quest.
![Out of the Ziggurat - how it is](https://user-images.githubusercontent.com/18005338/60368984-84c2b900-99f2-11e9-8608-d28ddfa29d1f.png)

**What should happen:**
After killing Warlord Threshjin, you should be able to loot him for his body and finish the quest.
![Out of the Ziggurat - how it should be](https://user-images.githubusercontent.com/18005338/60368982-842a2280-99f2-11e9-9b92-a82d3b90ef18.png)

**Comment by Rushor** [comment]
![I](https://i.imgur.com/EBnjgyr.jpg)
