### ISSUE TITLE
Mana Regen Discipline Priest

### ISSUE THREAD

**Issue by Healwho** [WoWManiaUK/Blackwing-Lair#259]
![wowscrnshot_122118_035557](https://user-images.githubusercontent.com/45921854/50333878-a50a3c00-04d4-11e9-9632-8ba6bcf6d3a5.jpg)

MP5 is 1901 as shown, and yet The absolute best I get is 1600.

**Comment by TheSale** [comment]
@Keader I dont know is this related with old report that I posted before, but please check it.
https://github.com/WoWManiaUK/Blackwing-Lair/issues/144

**Comment by Dranah** [comment]
I cannot find a problem with priests mana regen.
