### ISSUE TITLE
Shadow Labyrinth: Unkillable skeletons

### ISSUE THREAD

**Issue by Cespie** [WoWManiaUK/Blackwing-Lair#2590]
**What is happening:**

The skeletons which initially appear dead in Shadow Labyrinth (TBC) near the piles of skulls are aggroed by players (as they should), but cannot be targeted or otherwise damaged by aoe skills.

**What should happen:**

The skeletons should become targetable mobs when they are pulled.

**Comment by Kitzunu** [comment]
fixed `entry` = 18797;
