### ISSUE TITLE
Blackrock Depths: Grim Guzzler encounter

### ISSUE THREAD

**Issue by Cespie** [WoWManiaUK/Blackwing-Lair#2591]
**What is happening:**
When smashing the kegs in the Grim Guzzler (BRD - Vanilla) the bosses are correctly summoned, the dialogue works, and the summoned units attack correctly. However, 2 of the adds (not main boss) summoned never became targetable or otherwise possible to damage with aoe, making them essentially immortal enemies attacking the player relentlessly. It is unknown to me if this consistently affects the same units or if this specific outcome was random.

**What should happen:**
All units summoned by this encounter should be possible to kill.

**Comment by Rushor** [comment]
for me all of them are attackable.

which bosses exactly do you mean? I tested Blackbreath Crony and the Phalanx and they were all attackable for me.
