### ISSUE TITLE
[Quest] Breaking the Bonds - ID 25514 - Mount Hyjal

### ISSUE THREAD

**Issue by HrPottemager** [WoWManiaUK/Blackwing-Lair#2595]
Quest - https://www.wowhead.com/quest=25514/breaking-the-bonds
NPC - https://www.wowhead.com/npc=40341/tortolla

**What is happening:**
He gives the quest where you have to activate to rods next to him. You can interact with these but it is not possible to get credited for this.

**What should happen:**
interact with the rods and defend him while mobs spawn.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/fp2nvgs.jpg)
![I](https://i.imgur.com/fn1vh1l.jpg)
