### ISSUE TITLE
[Class]   primary stat only giving half stats for druids

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2596]
**Links:**

https://worldofwarcraft.fandom.com/et/wiki/Attributes   -    scroll down to the agility section and you will see this part   =  Rogues, shamans and druids in Cat Form and Bear Form gain 2 melee attack power per point of agility.

http://cata-shoot.tauri.hu/?spell=768   -   cat form link for ID
http://cata-shoot.tauri.hu/?spell=5487  -  bear form link for ID

https://us.battle.net/forums/en/wow/topic/2089200852  -   link for cat dps guide which shows primary stats and numeric value etc,   need to scroll down a small bit

**What is happening:**

currently druids are only getting 1 attack power from 1 point of agility in cat and bear form
every other melee class is getting 2 attack power per 1 point of thier primary stat

so warriors are getting 2 attack power from 1 strength   and shamans are getting 2 attack power from 1 agility
but feral druids are only getting 1

This is a huge deal in respec that ferals currently have half the power that other melee classes do,   thats a huge huge gimping of play
as you can see from below screenshot that my feral druid is getting less than 1 attack power per agility as i currently have 4519 agi and only 4509 attack power

![WoWScrnShot_062919_203122](https://user-images.githubusercontent.com/50211643/60389479-9327d800-9ab9-11e9-8153-b55afd117e49.jpg)

**What should happen:**

druids should be getting the same as other classes which is 2 attack power per 1 primary stat (   agi )  
as you can see below another agi class getting 2 ap from 1 agi in belowe screenshot

![WoWScrnShot_062919_220518](https://user-images.githubusercontent.com/50211643/60389501-04678b00-9aba-11e9-8a4f-56a87931db8a.jpg)

**Comment by Dranah** [comment]
https://us.battle.net/forums/en/wow/topic/2089200852 confirmed
"1 Agility = 2 Attack Power (3.63825 with talents and buff), 324.8536 Agility = 1% Critical Strike Chance"

**Comment by giles1508** [comment]
![WoWScrnShot_070119_174836](https://user-images.githubusercontent.com/50211643/60453583-6db9dc00-9c29-11e9-8202-bb8795fc7e11.jpg)

the fix at a glance seems ok,   im speaking to dranah about the numbers before we confirm,  the tooltips dont show the correct numbers,   but im guessing the fix was a background fix and didnt involve the tooltip in any way,   

![WoWScrnShot_070119_175710](https://user-images.githubusercontent.com/50211643/60453664-a78ae280-9c29-11e9-9898-cf707a2ab79d.jpg)

as you can see here,  the green numbers in the tooltip show current agi,  but the yellow text under doesnt show ,   but when u look down you can see the attack power is definatley increased,    

so its fixed ,  just not sure yet if its too much or if its all matching up,   please wait for full confirm from myself or dranah ,  ive pm'd her,  just waiting for her to come online,  as i think something is slightly off with the numbers  but we will see shortly

**Comment by Dranah** [comment]
The post fix conversion seems to be 1 agi = 3 AP, which means the fix added onto the other script instead of replacing it. 
I have tested this with feral spec taken with 0 talents spent, no buffs, no mods. I've 3361 agi, of which 10 is base agility that gives no AP. The remaining 3351 gives 10053 attack power, with the 25% from feral spec that is 12566. With the base 103 ap, it makes 12669 which is my displayed AP value.
