### ISSUE TITLE
[Quest] Children of Tortolla - ID 25519 - Mount Hyjal

### ISSUE THREAD

**Issue by HrPottemager** [WoWManiaUK/Blackwing-Lair#2597]
Quest - https://www.wowhead.com/quest=25519/children-of-tortolla
NPC - https://www.wowhead.com/npc=40341/tortolla

What is happening:
He gives the quest where you have to save his unborn children. The lake is full of eggs but no mobs so it is not possible to save his children.

What should happen:
Save 6 eggs under water.

**Comment by Rushor** [comment]
we are in phase 169 during that questchain.

creatures and spawnscript for Child of Tortolla added.

![I](https://i.imgur.com/Bh7L1Le.jpg)
![I](https://i.imgur.com/B6gwMPI.jpg)
![I](https://i.imgur.com/vgDmsE9.jpg)
