### ISSUE TITLE
[Quest] The Smallest Creatures

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2598]
**Links:**
https://www.wowhead.com/quest=10720/the-smallest-creatures#videos
**What is happening:**
The kegs cannot be poisoned. Player is unable to take on the form of the marmot to go around to poison the kegs.

**What should happen:**
Player should take on the form of the marmot the quest item provides in order to poison the kegs.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/D9s1K25.jpg)
