### ISSUE TITLE
Quest - Take Back What's Ours (issue 2) - Gilneas

### ISSUE THREAD

**Issue by shadowfires** [WoWManiaUK/Blackwing-Lair#2599]
**Links:**  
https://www.wowhead.com/quest=24646/take-back-whats-ours

**What is happening:**
Quest - Take Back What's Ours - Dark Rangers are not at the Woods' End Cabin.

**What should happen:**
When going to the Woods' End Cabin, the Dark Rangers should be present.  After finding them at the cabin, the player is to blow the Horn of Tal'doren so Tobias and his trackers appear and fight the Dark Rangers so the player can go into the cabin and retrieve an artifact and complete the quest.

**Comment by giles1508** [comment]
hmm ,  when i tested this,  the adds were all there it was just the worgen tody that didnt respond,   but anyways there is a report open for that,  ill close this and reference it to the other post just incase something has regressed

**Comment by giles1508** [comment]
nvm cant seem to find other post

**Comment by Echinaceax** [comment]
> nvm cant seem to find other post

this one #2552

**Comment by giles1508** [comment]
nah im sure rushor made another post about tobias not moving,  maybe he didnt

**Comment by giles1508** [comment]
either way i dont see how this has happened ive done this quest like 4 times now on dev and each time adds were there,  unless a fix hasnt been pushed live
who knows

**Comment by shadowfires** [comment]
I don't know if a fix has gone through or not, but the Dark Rangers are now present in the game.  Thank you all for looking at this!

**Comment by Rushor** [comment]
going to close this now. the cosmetic script will be added in a diffeent issue. thank you.
