### ISSUE TITLE
[Spell] Arcane missiles

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#26]
Spell ID 5143

How it should work:
Any offensive spell you cast has 40% chance to activate this ability.
When a fire or frost specced mage talents into 44445/44456 (Hot Streak) or 44546 (Brain Freeze), they should no longer be able to proc Arcane Missiles.

How it works right now:
The proc chance seems to be around 10-15% for Fireball and Arcane Explosion (rest untested)
The proc chance seems to be 50-55% for Arcane Blast without nether vortex.
Does not proc at all from non-damaging offensive abilities.
Keeps procing for fire and frost mages after having talented into above talents that should replace the proc.

**Comment by Keader** [comment]
Talk to me in Discord when you see this 💃

**Comment by Dranah** [comment]
Here it all the additional info I could dig up from cataclysm:

**- It has a 40% proc rate on any offensive spell that hits a target**
"The current proc of 100% is wrong. I had it confirmed by a CSR that it is, indeed, a 40% proc rate. The tooltip is wrong and will be fixed in a subsequent patch. (4.1.0)" - wowhead
This is also what the tooltip shows in game now.

**- It should proc of ANY offensive ability that hits a target. This does not necessarily mean DAMAGE a target!**
For example it should be able to proc off Polymorph 118, Slow 31589, even the automatically applied slow via 86181 (Nether Vortex talent effect)
This virtually gives a 80-85% proc chance on Arcane Blast casts for a mage that has the nether vortex talent, as both the damaging spellcast AND the slow it applies has a separate 40% chance to proc it.
"You're getting a proc from casting Arcane Blast, and if you use Arcane Missiles fast enough, you also gain a proc from the Slow applied by Arcane Blast. :) (patch 4.2.)" - wowhead
" It's proccing from pretty much everything, even polymorph. (patch 4.1)" - wowhead
There are comments from 4.0.1. that suggest it even procced off Slow fall and Remove curse, however it is likely to have been hotfixed on 4.1 by Blizzard as later on they speak of spells that hit a target.

**Comment by Keader** [comment]
Fix made, i will pass to janitor tomorrow morning

**Comment by Keader** [comment]
@Dranah when you have free time, test pls

**Comment by Dranah** [comment]
@Keader i'm still downloading the new client, wasn't able to connect yesterday anymore without it

**Comment by Keader** [comment]
Oks :)

**Comment by Dranah** [comment]
UPDATE:
- Polymorph can now proc Arcane missiles (fixed)

No change on the other problems.
- Proc chances still incorrect
- Arcane missiles keep procing after having talented into 44445/44456 (Hot Streak) or 44546 (Brain Freeze), which should prevent it from proccing and should proc a different effect.

**Comment by Dranah** [comment]
UPDATE:
- Proc chance is now correct 40% on casts that proc it
- Arcane missiles seems to be able to proc off spell 36032 (the damage buff triggered by casting Arcane blast), which is unintended - giving an increased procrate to arcane blast
- Arcane missiles seems not to be able to proc off the slow applied via Nether Vortex 86181, which it should proc off - takes away from the value of the talent
- Cannot test abilities like mirror image and flame orb yet due to those spells not working at all.

**Comment by Dranah** [comment]
- 36032 no longer procs the effect (fixed)
- Nether Vortex talent now properly procs it (fixed)
The spell is now working as intended as far as it can be tested (cannot test with abilities that don't work)
