### ISSUE TITLE
DK Starter questline broken

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Blackwing-Lair#260]
Death Knight starting zone phases to post-https://www.wowhead.com/quest=12757/scarlet-armies-approach zone randomly, even before said quest is completed. This causes previous quests to be uncompleteable and causes players to miss talent points. 

Also https://github.com/WoWManiaUK/Blackwing-Lair/issues/224 this quest can't be finished. 

Since either the phasing happens unnaturally, or the precious quests are uncomplete https://www.wowhead.com/quest=12779/an-end-to-all-things does not even appear. Since that doesn't appear, the questline can't be continued.

**Comment by Dranah** [comment]
I'll need to put these quest-chain reports into a comprehensible easy-look-through form for devs so they can fix stuff.

**Comment by Dranah** [comment]
Phasing is intended, but having the previous quests in your log still is not.
Quests are unlocked in wrong order, made detailed report for each.
I'll reference this report in the threads for giving you credit.
