### ISSUE TITLE
[Rogue/Talent] Blackjack

### ISSUE THREAD

**Issue by 3JIoudyx** [WoWManiaUK/Blackwing-Lair#2600]
**Links:**

Couldn't find this spell on Wowhead so http://cata.cavernoftime.com/spell=79125

**What is happening:**

Blackjack does nothing.

**What should happen:**

The target's damage should be reduced by 35/70% when Sap wears off.

**Comment by Rushor** [comment]
http://cata.cavernoftime.com/spell=6770

**Comment by Rushor** [comment]
fixed with next server update

![I](https://i.imgur.com/XJyXLpJ.jpg)
![I](https://i.imgur.com/z9x7p3z.jpg)
