### ISSUE TITLE
[Spell / passive]  [druid]  -  leather specialization ( cat form  )

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2604]
**Links:**

http://cata-shoot.tauri.hu/?spell=86530  -  link to spell
http://cata-shoot.tauri.hu/?spell=768   -  cat form ID

**What is happening:**

currently its not increasing the amount of agility in cat form by 5%   its giving the same amount as in human form,   from what i can see bear form and resto work,   but for some reason cat form doesnt get the 5%  stat increase for  agility while in cat form

below is a pic in human form

![WoWScrnShot_070119_174848](https://user-images.githubusercontent.com/50211643/60453459-23d0f600-9c29-11e9-803e-2669042e2ce8.jpg)

below is a pic with same agi in cat form, no 5% increase

![WoWScrnShot_070119_174836](https://user-images.githubusercontent.com/50211643/60453503-3ea36a80-9c29-11e9-91db-5c166930eddb.jpg)

**What should happen:**

cat form should benefit from 5% increased agility while wearing leather in all slots,   remember the player has to have leather in all 8 armor slots for this to work

**Comment by Rushor** [comment]
in core stands, that it depends on the talents that are active

**Comment by giles1508** [comment]
just spoke with dranah and she said it seems to be active without going into cat form so its not of great importance atm,  as it works,  ill close for now
