### ISSUE TITLE
[Quest] Prisoner of the Bladespire

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2605]
**Links:**

quest id 10724

**What is happening:**
Quest can be completed, however, the objective does not complete in the quest log, but only on the screen.

**What should happen:**
Quest objective should count to the quest in the quest log after completion.

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/qSo7GT6.jpg)

Remember to delete the cache before testing
