### ISSUE TITLE
[Quest] Showdown

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2608]
**Links:**

https://www.wowhead.com/quest=10742/showdown#videos
**What is happening:**
Goc cannot be summoned at the altar

**What should happen:**
Goc should be summoned with the quest item at the altar

**Comment by Rushor** [comment]
![I](https://i.imgur.com/LRvhnrK.jpg)
![I](https://i.imgur.com/EesLSaq.jpg)
