### ISSUE TITLE
[Quest] Hell's Shells - ID 25507- Mount Hyjal

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#261]
Quest - https://www.wowhead.com/quest=25507/hells-shells
NPC - https://www.wowhead.com/npc=39858

The turtle is meant to be moving but is only in one position. He doesn't interact with the meat that is use to distract him. there for I can not take the needed item to complete the quest.

**Comment by zippoking** [comment]
Item to lure: https://www.wowhead.com/item=54744/heap-of-core-hound-innards
Item to loot: https://www.wowhead.com/item=54745/nemesis-shell-fragment


**How it is:**
The turtle doesn´t move at all and the lure is not working.
![Hell's Shells - how it is](https://user-images.githubusercontent.com/18005338/60382350-23d2c980-9a62-11e9-80ff-43aed8cb099c.png)

**How it should be:**
First you put down the meat.
![Hell's Shells - how it should be 1](https://user-images.githubusercontent.com/18005338/60382351-23d2c980-9a62-11e9-9607-5556c5083198.png)

When the turtle comes closer to the meat, the turtle becomes friendly.
![Hell's Shells - how it should be 2](https://user-images.githubusercontent.com/18005338/60382352-23d2c980-9a62-11e9-97ab-b2b5f18c2bd3.png)

Finally you can "mine" her, to get the Nemesis shell Fragment.
![Hell's Shells - how it should be 3](https://user-images.githubusercontent.com/18005338/60382349-23d2c980-9a62-11e9-83d1-55b6602ca802.png)

**Comment by HrPottemager** [comment]
I can confirm this too. This is very important quest to complete or else the zone is phased so not to be able to start the Firelands quests

**Comment by Rushor** [comment]
![I](https://i.imgur.com/1mikrQF.jpg)
![I](https://i.imgur.com/ByG4tbx.jpg)

1. you use the quest item
2. turtle runs towards the Heap of Core Hound Innards and becomes freindly
3. if you stand still and click on the tutrtle you will get the questitem after few seconds
4. turtle will despwan together with Heap of Core Hound Innards fter 35 seconds.
