### ISSUE TITLE
Tol Barad/Spawn rates

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#2615]
**Links:**

from WoWHead or our Armory

**What is happening:**

Npcs re-spawns are way too lower than the usual. On quests like "Rattling their cages" (It's for an example) where you have to kill a certain number of mobs, the spawn rates are 2-3 hours long. On quests like "Claiming The Keep" (For an example) where you have to kill a boss/elite, the spawn rate is around 2-3 times a day. I don't know if the quest that i gave for an example in the last sentence is bugged, but I still haven't seen the boss/elite on that quest so I can kill him and finish it.
**What should happen:**

I don't have an exact idea how fast or long the spawn rates should be but I could guess like 2-3 minutes for mobs and 3-4 minutes for bosses/elites. You guys know the best but they definitely shouldn't be that long.

**Comment by Rushor** [comment]
reduced to 5 min. fix available with the next update

**Comment by Denrunmt** [comment]
Thanks for your attention to the issue and for the help for its resolving.
