### ISSUE TITLE
[Druid] Flight Form

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2618]
**Links:**

33943 / 40120

**What is happening:**
cannot be used if the druid jumps at the surface of the water

**What should happen:**
Flight form should be usable if the druid is at the surface of the water, and jumps to transform

**Comment by Rushor** [comment]
@Keader maybe this https://github.com/TrinityCore/TrinityCore/pull/21046 ?

**Comment by giles1508** [comment]
it does work,  you just gotta time it right

**Comment by Grotesqueee** [comment]
hasn't worked once, it shouldn't be like this.

**Comment by Tatoepaladin** [comment]
It's worked for me

**Comment by Tatoepaladin** [comment]
its a lag/timing issue not much devs can do about it

**Comment by Rushor** [comment]
okay then /closed. Diff get's better with server hardware update :)
