### ISSUE TITLE
[NPC] Tortolla 41504 - missing - Mount Hyjal

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#262]
NPC - TORTOLLA - https://www.wowhead.com/npc=41504
QUEST - https://www.wowhead.com/quest=25843/tortollas-revenge
PICKED UP - https://www.wowhead.com/npc=39858
The request requires you to speak with Tortolla however she doesn't speak with you therefore unable to complete the quest.
![world of warcraft 21_12_2018 13_56_02](https://user-images.githubusercontent.com/42302580/50345892-7c139680-0528-11e9-8e98-4ff91984645d.png)

**Comment by Dranah** [comment]
I don't think this is the Tortolla that you're meant to speak to.
The quest talks about one at the "Scorched Plain" which is clearly not in the middle of the lake you are.

This is a Tortolla at the lake: https://www.wowhead.com/npc=40341/
And this is another at the plain: https://www.wowhead.com/npc=41504/

**Comment by sarahkay88** [comment]
ho this may be right again the map wasn't really working so I was flying around looking for the npc. Maybe I came across the wrong dude with the same quest. I will go back and see if the other is there

**Comment by sarahkay88** [comment]
I tried to take the quest again to check this but it appears that I have been rephrase to the issue that phoenix previously sorted for me therefore I can no longer see any npcs
![world of warcraft 01_01_2019 15_50_18](https://user-images.githubusercontent.com/42302580/50574278-228b5180-0ddd-11e9-9543-942b480e08cb.png)
im currently lvl another toon so will probably come across this again at some point.

**Comment by Dranah** [comment]
The Tortolla you need for this is missing entirely.
