### ISSUE TITLE
[NPCs] Tol Barad Peninsula

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2620]
**What is happening:**

I think nearly all NPC aren't doing enough damage.
About 500 per blow (see screenshot)

Darkwood Lurker (spider) are doing about 4-5k per blow (withotu armor reduction)

**What should happen:**

NPC should hit harder, I think Lurker's actual damage are fine.

Screen of low damage : https://puu.sh/DNQfN/054c3d4d08.png
Screen of 'right' damage : https://puu.sh/DNQnj/39327010ba.png

**Comment by Rushor** [comment]
whole damage for all creatures in the zone increased.
