### ISSUE TITLE
[Spell/Paladin] Consecration (issue 2) 

### ISSUE THREAD

**Issue by Tatoepaladin** [WoWManiaUK/Blackwing-Lair#2621]
**Links:**
https://cata-twinhead.twinstar.cz/?spell=26573

**What is happening:**
https://www.dropbox.com/s/8swz3tgxerlquen/2019-07-02%2014-43-03.mp4?dl=0
It is acting like a pet and attacking nearby mobs outside the actual consecration zone.
The Damage is fine

**What should happen:**
Only deal dmg to those standing inside the consecrated ground.
The Damage is fine

**Comment by Rushor** [comment]
old issue https://github.com/WoWManiaUK/Blackwing-Lair/issues/691

**Comment by Keader** [comment]
Damage has 8 yards radius and i tested in game, it deal damage in targets inside 8 yards range.
But... i found a weird issue.
Damage aura and visual not have same timer.
Fixed that.
