### ISSUE TITLE
[Quest=26254] Some Spraining to Do - Deepholm

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2625]
**Links:**
https://www.wowhead.com/quest=26254/some-spraining-to-do
from WoWHead

**What is happening:**
You can't interact with Stormbeak, so you can't mount him.

**What should happen:**
After you accept the quest, just jump onto the bird mount Stormbeak right next to her.
https://www.youtube.com/watch?v=DsGAOAfHa2s

**Comment by Sammy974** [comment]
Still not working on 12/08/19 
@Echinaceax  can you assign it pls?

**Comment by Lurc1981** [comment]
![WoWScrnShot_090219_162205](https://user-images.githubusercontent.com/54812659/64133789-5371bb00-cd9e-11e9-8eb6-5f2e056fba5e.jpg)

So I happened across the Stormbeak that an be interacted with tracking across the map under the gunship. I followed him around and finally found a place I could be standing on the ground as he came around and I still got "You need to be closer to interact with this target" message. But this might be a more simple fix than previously thought?

**Comment by Rushor** [comment]
this is a hard script, transports are bad.

**Comment by Rushor** [comment]
alright fixed it as good as i could.

![I](https://i.imgur.com/Uk5wErv.jpg)
![I](https://i.imgur.com/jdAo169.jpg)

**Comment by Rushor** [comment]
just a side note - if the vehicle does not start his path, just fly away from the ship and fly again towards it - then click on stormbreak again and the event should start :)
