### ISSUE TITLE
[Spells Damage] Fire Mage

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2629]
**Links:**
https://fr.wowhead.com/spell=11366/explosion-pyrotechnique
https://fr.wowhead.com/spell=133/boule-de-feu

from WoWHead or our Armory

**What is happening:**

After (smalls) tryout to check my spell's damage, I found out that tooltip's damage and actual damage were different (compared to a shaman in this exemple)
So, first of here is a test with a shaman who tryed Lavaburst (Fire school of magic) on a dummy
https://puu.sh/DOijY/1d8e3bd511.png
Tooltip calls for 7464 damage (I assumed it was correct)
He did 5 lavaburst on a single dummy.
https://puu.sh/DOiku/55bff1e491.png
https://puu.sh/DOivp/63975aa732.png

With only hit (and not crit) the damage are really close to the tooltip's damage.

Here, about my pyroblast : 
https://puu.sh/DOilF/0ce341824b.png
Tooltip calls for 12738 damage (no crit)
You can see that even my maximum hit (who was a crit) didn't even reached the tooltip's damage.

Here is Fireball : 
https://puu.sh/DOimz/f42c2d44db.png
Calls for 10191 damage.

Again a difference between actual damage and tooltip's ones.
May you notice on last screen that Fireball average damage seems fine, but I did 2 crit 1 hit.
Minimal damage is 6.3k and maximum hit (crit) about 13.2k who isn't the 2x of tooltip's damage (typical critical hit)

**What should happen:**

I think Mage spells are a bit lowered in term of damage since tooltip's damage and actual's damage from Shaman with Lavaburst are quite close.
May you check a little further since you have access to more informations ?

**Comment by Thiay** [comment]
100% confirmed, tested on my 359 6360 spellpower mage, tootip on pyroblast says it should hit for an initial 14461 damage, while testing on the dummy it hits for an average of 6258 non crit. same goes for fireball which says 12404 hitting for an average of 7258 fire damage. I can post prints if needed but all evidance has already been posted up above.

**Comment by Thiay** [comment]
Furthermore, a crit which should mean double the spell initial damage on a fireball only goes up to 20k, 12x2 should be 24k, the wierd part is that it doesnt double its intial low damage 7k nor the damage said in the tooltip

**Comment by Cenasty** [comment]
I would add another issue I found, about frostfire bolt

I think it's dot is too much powered.
Initial hit is a bit low (actually close to... Scorch). About 5k with 5.5k spellpower 

But the tick with 3 stacks hit (no crit) about 8'5k and 17k on crit.

It's another problem, since the dot shouldn't even apply (only with glyph, but it applies the dot's glyph even if we don't have it) but I wanted to add it since it looks like another damage issue.

If need, I'll gladly provide other proof of damage with in-game content and situation. 

Like try living bomb out, try dot, blast wave et cætera

**Comment by Dranah** [comment]
Need to report each spell separately. Coefficients are broken for nearly all.

**Comment by Cenasty** [comment]
Do you want us to report each spell in a single Thread with Tooltip's Damage and actual damage ? (Just to see if I understood well)

**Comment by Rushor** [comment]
added spell power coefficient for all those spells:
(10,17,78,116,120,122,133,136,139,172,331,339,348,379,403,421,467,543,585,589,596,603,633,635,686,689,703,755,772,774,779,845,879,980,1064,1079,1120,1449,1463,1776,1822,1943,1949,1978,2050,2060,2061,2098,2120,2136,2645,2812,2818,2912,2944,2948,3110,3606,3607,3674,3716,5143,5176,5185,5308,5570,5672,5676,5857,6229,6262,6297,6343,6353,6360,6544,6572,6789,6807,7001,7268,7294,7712,7714,7814,8004,8034,8042,8050,8056,8092,8129,8188,8680,8921,8936,9007,10444,10577,11113,11366,12162,12294,12654,12809,13218,13376,13795,13797,13812,13813,13897,13907,14792,14914,15237,15407,16614,16827,17253,17484,17877,17962,18562,18790,18798,19236,19306,19434,19448,19750,20004,20006,20007,20154,20164,20167,20170,20187,20252,20424,20925,21992,22568,22703,23266,23455,23881,23922,24131,24275,25608,25742,25912,25914,25997,26170,26364,26573,27243,27285,27655,27813,28005,28176,28715,28788,28880,29722,30108,30283,30294,30451,30455,31024,31117,31661,31707,31803,31804,31935,32379,32546,32645,33110,33619,33745,33763,33778,34299,34428,34433,34861,34913,34914,35395,36946,37382,38395,38616,39373,40293,40972,41291,42208,42223,42231,43731,43733,44203,44425,44457,44461,44525,44572,44578,44614,45055,45284,45297,45429,45462,45477,45902,46579,46968,47632,47633,47666,47750,47897,47960,48045,48181,48438,48503,48721,48982,49143,49184,49821,49966,50256,50288,50401,50464,50536,50590,50796,50842,51460,51490,51505,51945,51963,52174,52212,52752,53301,53353,53595,53600,53733,54049,54158,54181,54755,54757,54968,55039,55050,55078,55095,55533,55756,56131,56160,56161,56903,57755,57984,58621,58879,59542,59543,59544,59545,59547,59548,59637,59638,59754,59913,60089,60203,60488,60526,61295,61391,61491,61840,63106,63468,63544,63675,64085,64382,64442,64569,64801,64844,64891,64930,67714,67760,69041,69729,69730,69733,69734,70691,70772,70809,70890,71023,71521,71757,71824,71838,71839,71878,71879,73510,73685,73921,74196,77451,77472,77478,77661,77758,77767,77799,78674,78777,79136,81269,81297,81751,82326,82327,82739,82928,83381,84721,85222,85455,85673,86452,86958,86961,88263,88466,88625,88684,88686,88767,90361,91394,92315,93402,94009,94447,95714,95725,98957,99002,99075,99092,99173,99240,108000,109822,109825);

If sth is missing/must be changed open a new report pls. Data based on own research.
