### ISSUE TITLE
[Paladin][Prot]Sacred Duty

### ISSUE THREAD

**Issue by Tatoepaladin** [WoWManiaUK/Blackwing-Lair#2633]
**Links:**
https://cata-twinhead.twinstar.cz/?spell=53710

**What is happening:**
https://www.dropbox.com/s/9aga17jx8ktacn3/2019-07-04%2006-45-46.mp4?dl=0
https://www.dropbox.com/s/n6hrz9l80fsg1ra/WoWScrnShot_070419_064736.jpg?dl=0

Casting Judgement does not proc this passive. 
Casting Avenger's Shield does.

**What should happen:**

Judgement and Avenger's Shield should both be proc'ing this whether it is currently proc'd or not.

**Comment by Dranah** [comment]
Now it can proc off both abilities.
However, the proc chances are off.
It should have 50% chance to proc off either abilities, currently procs with 100% chance on every judgement, and approx 80% of avengers.
