### ISSUE TITLE
[Paladin][Prot]Guarded by the Light

### ISSUE THREAD

**Issue by Tatoepaladin** [WoWManiaUK/Blackwing-Lair#2634]
**Links:**
https://cata-twinhead.twinstar.cz/?spell=85646

**What is happening:**
https://www.dropbox.com/s/7bfwkjfft7a6spq/2019-07-04%2007-12-31.mp4?dl=0
When casting Word of Glory on self, There is no overhealing shield.

**What should happen:**
Any and all overhealing by Word of Glory should create a shield on the paladin for the same amount overhealing lasting 6 seconds.

**Comment by Rushor** [comment]
Maybe fixed - check it out

**Comment by Sammy974** [comment]
Still not working.

**Comment by giles1508** [comment]
It's not fixed on live yet that's why,  only on dev, hence the fixed in dev label,  but janitor is working on dev atm so we cannot test to confirm

**Comment by giles1508** [comment]
confirmed working on test realm
