### ISSUE TITLE
[NPC=19622] Kael'thas Sunstrider (Boss) - The Eye - Burning Crusade

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2639]
**Links:**
https://www.wowhead.com/npc=19622/kaelthas-sunstrider
from WoWHead 

**What is happening:**
The encounter doesn't work at all. The memebers of his council can't be damaged in any way.

**What should happen:**
The council should be damaged and killed in order to kill Kael'thas.

*He is famous for dropping  Ashes of Al'ar, one of the most popular mounts in the game.*

**Comment by Rushor** [comment]
fixed the adds, the can be damaged now

![I](https://i.imgur.com/a09brKb.jpg)
