### ISSUE TITLE
[Druid] Rake (new issue)

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2640]
**Links:**

spell link 1822
**What is happening:**
Bleed ticks are twice as high as they should be according to the coefficient & without mangle debuff

https://imgur.com/UDBWsrj

**What should happen:**
Rake bleed ticks should not hit for this much.

**Comment by giles1508** [comment]
compensates for not having savage roar at the moment,  maybe both can be done the same time to balance.  1 nerf 1 fix

**Comment by Rushor** [comment]
@Keader do you changed sth there in the last time?

**Comment by TheSale** [comment]
why we dont get mangle to make 100k damage like lava lash on shamans, or dk DnD when did brutal damage the more mobs he has in dnd more damage he did  :D 
or 200k absorb shield NO cd like some class :D
but we get weakest ability that druid has to do only a bit more damage rofl :D

my dps in dungeons is 17k at most and overall is 14k
just moments ago we finished throne of tides and http://prntscr.com/ob9bia
10k dps overall
and on simc with my gear and stat I should have steady 20k dps as average player no buffs no flasks

as giles said let balance damage on druid, and improve what dont work, then if needed go and tune it down.

**Comment by Grotesqueee** [comment]
What are these comments? Ability has to be fixed like all others

**Comment by Sevenblade11** [comment]
Most are upset that a core component of ferals (Savage Roar) is not working, thus damage for ferals will be lower compared to other classes once Rake's damage is corrected. As such, it may behoove the developers to fix Savage Roar along side Rake's damage.
