### ISSUE TITLE
[Item] Mysterious Egg - ID 39878 - timer not running down

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2642]
**Links:**
Item: https://www.wowhead.com/item=39878/mysterious-egg

**What is happening:**
As written in the title, i farmed oracle reputation all the way to revered, only to find out, that the timer of the egg is not running down. Having the egg for a couple of days now in my inventory. But it still says 3 days.
![Mysterious Egg - how it is](https://user-images.githubusercontent.com/18005338/60740988-23599780-9f68-11e9-9bcc-12dd8f989f0b.png)

**What should happen:**
The timer should run down and then i should be able to loot the item.

**Comment by Rushor** [comment]
item overritten, so it counts realtime, not gametime

**Comment by zippoking** [comment]
The timer went up to 7 days now. But it should still be 3 days.

![Mysterious Egg - how it is 2](https://user-images.githubusercontent.com/18005338/61382769-adc9c180-a8ad-11e9-94ba-d7799d409d13.png)
![Mysterious Egg - how it is 3](https://user-images.githubusercontent.com/18005338/61382772-adc9c180-a8ad-11e9-9e3d-b96d9642d1ba.png)
