### ISSUE TITLE
[Spell] Druid Skull Bash

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2645]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/spell=106839/skull-bash
**What is happening:**
dont interupt players

**What should happen:**
should interrupt

**Comment by Dranah** [comment]
Adding here:
Charge effect doesn't work either.

Please report all issues with the same spell in one thread.

**Comment by Rushor** [comment]
correct id is: http://cata.cavernoftime.com/spell=80965

**Comment by Rushor** [comment]
interrupt and charge effect added! live with next server update

**Comment by Rushor** [comment]
envolved spellids 93983 93985
