### ISSUE TITLE
[spell] Druid Stampeding Roar / Feral Swiftness interaction

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2646]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/spell=77761/stampeding-roar
**What is happening:**
it give only 30% speed boost to ferals

**What should happen:**
it should give 60% speed boost

**Comment by giles1508** [comment]
Please note that this isn't just for feral druids,  it's for any spec druid that takes feral swiftness as their optional talent

**Comment by Dranah** [comment]
Effect does not stack with Feral Swiftness.
To my knowledge that is intended.
Please provide some proof that they should stack.

**Comment by Dranah** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/2652 same thing

**Comment by giles1508** [comment]
effect does not stack with feral swiftness indeed...  this only happened when it was changed to feline swiftness in MoP....   same for dash
