### ISSUE TITLE
[Spell] Druid dash (speed issue)

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2648]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/spell=1850/dash
**What is happening:**
it increase speed for only 40% in feral spec

**What should happen:**
it should increase 70% movement speed

**Comment by giles1508** [comment]
Please note that its not actually feral spec as such,  its when you take the " feral swiftness" talent in feral tree,  and you can take that in any spec as optional talent

**Comment by Dranah** [comment]
Does not stack with feral swiftness.
Do you have any proof that it should?

**Comment by Dranah** [comment]
PS it's literally same issue as the prowling one just testing with an extra modifier.
