### ISSUE TITLE
[spell] Druid dash (removing debuff issue)

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2649]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/spell=1850/dash
https://wowwiki.fandom.com/wiki/Feral_Swiftness
**What is happening:**
it dont remove movement impairing debuffs

**What should happen:**
it should remove movement debufs if feral swiftness talent is chosen

**Comment by Tatoepaladin** [comment]
only movement impairment debuffs

**Comment by giles1508** [comment]
From the 4.1 PTR: [quote] Stampeding Roar's duration has been increased to 8 seconds, up from 6. The movement speed effect has been increased to 60%, up from 40%.[/quote] [quote](Spell #24866) now also causes  Dash and  Stampeding Roar to have a 50/100% chance to instantly remove all movement impairing effects from the affected targets when used.[/quote]

**Comment by Rushor** [comment]
fixed, live with the next update!
