### ISSUE TITLE
[Quest] The Twilight Egg

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#265]
Quest - https://www.wowhead.com/quest=25644/the-twilight-egg
npc -https://www.wowhead.com/object=207359
Hand in NPC -https://www.wowhead.com/npc=40816
The issue is the area were is this quest is meant to be handed in is completely empty.
![world of warcraft 21_12_2018 14_16_07](https://user-images.githubusercontent.com/42302580/50346775-5c31a200-052b-11e9-81d3-4fc70280f1c7.png)

**Comment by Dranah** [comment]
Same issue as https://github.com/WoWManiaUK/Blackwing-Lair/issues/241
