### ISSUE TITLE
[spell] Druid prowl (speed reduction)

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2650]
**Links:**

from WoWHead or our Armory
https://wowwiki.fandom.com/wiki/Prowl_(druid_ability)
**What is happening:**
it reduce more than it should from 130% to 91%

**What should happen:**
it should reduce speed to 100%

**Comment by giles1508** [comment]
Please note that 130% speed is only with feral swiftness talent in the feral combat  tree

**Comment by Dranah** [comment]
Effect is multiplicative. It takes 0,3 x 130% = 39% off.
