### ISSUE TITLE
[spell] Druid Dash / Feral Swiftness interaction

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2651]
**Links:**

from WoWHead or our Armory
https://wowwiki.fandom.com/wiki/Prowl_(druid_ability)
https://www.wowhead.com/spell=1850/dash

**What is happening:**
it increase speed from 91% to 119%

**What should happen:**
it should be 70% bonus

**Comment by giles1508** [comment]
Please note this is for feral combat spec

**Comment by TheSale** [comment]
normal speed 100-prowls speed 30= 70 + dash 70 = 140
feral swiftness 130-prowls speed 30= 100 + dash 70 = 170

**Comment by Dranah** [comment]
The effects are multiplicating and do not stack
You have 70% speed when prowling, and with Dash it is 70 x 17 = 119%.
If you find proof that the effects should stack on cataclysm, leave it here (note: they dont stack on LK either)

**Comment by giles1508** [comment]
feral swiftness defo stacks,  im trying to find an article or something,   but it was never this slow for a feral dashing

**Comment by TheSale** [comment]
lets just break down for a sec,
I have feral swftness talent that give me speed of 130% 
and I activate dash that give me 70% movement speed.

I should have 200% movement speed

when I enter prowl, as tooltip say I lose 30% movement speed, but there is not sane reason to lose 81% movement speed

**Comment by giles1508** [comment]
oh no im wrong,  seems it was not in cata but MoP.....   wow,  in cata it didnt stack,  it only stacked when they changed the talent system in Mop 
https://us.battle.net/forums/en/wow/topic/3123319539  article from 2011 ( cata time )   so dash defo doesnt stack with is,   and prowl is indeed 91%  .... stupid memory jesus....

**Comment by TheSale** [comment]
roflmao guy just closed topic based on random people numbers on non confirmed topic on forum without any facts and proofs, and without relating to what patch they were talking and what changes and where ther were applied.
IF some things do not STACK they say so! like here http://prntscr.com/obcvle
toltip clearly say that feral swiftness and savage roar and dash are connected, and that they remove debuff from a target, but there is nothing that say that it dont stack with or that ignore or multiply movements speed

**Comment by giles1508** [comment]
Your free to find that " confirmed" proof yourself,  and I didn't just post the first forum post I found... I spent ages trying to prove you right as I was really hoping you was as I play a druid myself... Fact is it's not,  it stacked in mop when the talent was changed to feline swiftness,  your free to prove me wrong,  if you do then I will hold my hands up and say I was wrong

**Comment by TheSale** [comment]
I know I am free, but I am not paid for that and I dont have benefit for investing my personal time into fixing things. You just put disclamer, and say it work as intended, and say give us proof of issue and we will fix it....
well I can say fuck you, and go yourself and test and give proof that it actually works. 
example
Book of glyph mastery... I have killed near 6.000 npc in northrend and only 4 books dropped from 3 different npc, some mobs  I have killed over 600-700 times and they did not drop a book. People started to farm them when I provoked server, few books were found but people quit farming since it is nonsense.
server is near 3 months old, and some important glyphs are still not discovered, and some that are discovered are not available since I quited wow, and some other people might quited as well.

next example
druid damage was low, everyone denied and acted as damage was alright, and no body wanted to test,
people give more effort to prove I was wrong, than to find issue or to prove how much damage should be output.

now same story, we denie, you go and bust your ass to find what we need. You go and do OUR job! And we will close issue so you get upset and actually research since you care about issue. And we will give our best to prove you are wrong so you give up or push your limits to prove..

well that can work only 1 or 2 times then bye bye.

now it is funny how you guys think this is actually working as it should.
since for every other thing it work fine (OR IS IT) but for this particular problem it does not.

abilities usually are simple, and do as they say. heroism give 20% haste, flask give xxx amount of stat,  spell does xxx% weapon damage... and when you look at numbers they are how they suppose to be.

but in speed situation it is totally messed up!
first speed is attribute in percentages, not in normal number value.
and you CAN NOT percentage the percentage!

first speed is 100% if you are slowed by xx% you are not slowed by nn%
if I walk into frost trap I will lose 50% movement speed and I will have 50% movement speed
if I have 30% movement speed bonus from talent and I get into trap I will loose 50% movement speed
not 65% 
so 130%-50%=80% 
and not 130%-50%=65%

if I activate dash (and even if you say that dash does not stack)
I should have 170% movement speed, if I hit  trap and lose 50% movement speed
170%-50%=120% this is how it should be
170%-50%= 85% this is not how it should work

with prowl
100%-30%=70%
130%-30%=100% 
AND NOT 130%-30%=91%

with dash and prowl
170%-30%=140%
and not 170%-30%=119%

it is fucking common sense... if I lose prowl while dash is active, my speed should be increased for 30% not for 51%.......

now the funniest situation, I am prowling in bg, I activate dash so I can get in range to jump on a player, but someone activate frost trap, and I step in it.
so my speed drop from 170% to 119% to 59%........ so I lose 111% speed with 80% of slow....

also, 100% is considered normal speed, so with 30% talent buff, and you enter prowl, you lose 30% so with dash my speed should be 170% because there is no stacking, it give speed from normal 100%

WHY WOULD ANYONE ON THE WORLD spend 2 PRECIOUS TALENT POINTS FOR TALENT THAT FUCK YOU UP??????
you get 30% speed buff that increase all movement debuffs on you... 
if you are slowed by 50%, you are slowed 65%
if you are prowling you are slowed not 30% but 39%
and if you use dash or roar your movement speed is not stacked...

there is talent infected wounds that I did not take and for same 2 points I will slow oponents by 50% and reduce theyr attack speed by 20% 

bottom line is that, if speed was normal value of 100 math should be right BUT IT IS 100%
or that increasing or decreasing is only on base movement speed (and that effect should be applied into calculation only on base speed before movement buffs were implemented)

so what I am saying that value is in numbers and not in percentage, is if we take attack speed as example
Haste has numeric value and it is increased by percentage, you have buffs that increase your total haste, but when someone slow you for 10% attack speed, you lose 10% of your total haste which can be 8% of your attack speed or 12% of attack speed, depend how much haste you have.

with movement speed is different, you dont have numeric value, but it is percentage. If you look at all  buffs, enchants, trinkets, player buffs, zone buffs, etc every single value that increase movement speed is in percentage. And that made that some stuff is not stackable so you cant have insane movement speed, as you can have now in BfA where people can run faster than mounts, since movement speed is numeric value and you can have 550 movement speed same as you can have 800 haste, and run faster than people with epic mount speed.

that post on forum can be from some tester or dev from private server that had same issue as we do and he posted on blizzard forum to try to get answer as we looking for, nut that answer can be from previous expansion database, or w/e proof was not official and not confirmed.


I only wrote comment here, because I did not closed github, I thought it was for trinitycore github, and when I saw issue, I decided to post last comment.
I have quited wow and this is last post that you wil see from me.

**Comment by giles1508** [comment]
Take it up with blizzard then,  they made it that way.... Also if you have quit why do you care what happens? Fact remains that I did the research,  my research was backed up by another tester,  wow has been notorious over the years for spells making no sense for ages then all of a sudden improve.... And dash did in mop..... And so did stealth and many other speed increases and decreases.... We can't help that you can't accept your wrong,  we can't just make stuff up because you believe that's the case,   yes u did find issues with damage and yes people did think you was wrong,   and you proved right,  same thing goes here,  2 of us have explained how it is,  you disagree, if you dont like that then u can always give evidence,   but instead your groaning like a child who lost his dummy.... And again I don't understand why you care if you no longer want to play here?
