### ISSUE TITLE
[NPC] Spirit of Goldrinn - ID 39627 - npc missing (phasing) - Mount Hyjal

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2653]
**Links:**
NPC: https://www.wowhead.com/npc=39627/spirit-of-goldrinn
Quest: https://www.wowhead.com/quest=25280/the-shrine-reclaimed

**What is happening:**
After doing the quest [Lycanthoth the Corruptor](https://www.wowhead.com/quest=25273/lycanthoth-the-corruptor) (see #248), you are not able to see the Spritit of Goldrinn and accept his quest.
![Spirit of Goldrinn - how it is](https://user-images.githubusercontent.com/18005338/60754319-d0bbc200-9fdf-11e9-9f9f-d8e47ca94069.png)

**What should happen:**
The Spirit of Goldrinn should be avaibable after doing [Lycanthoth the Corruptor](https://www.wowhead.com/quest=25273/lycanthoth-the-corruptor) (see #248), and offer you the quest "The Shrine reclaimed".
![Spirit of Goldrinn - how it should be](https://user-images.githubusercontent.com/18005338/60754318-d0bbc200-9fdf-11e9-97ad-cde793a6db90.png)

**Comment by Rushor** [comment]
added. phasing will be done later with https://github.com/WoWManiaUK/Blackwing-Lair/issues/248
