### ISSUE TITLE
[Spell] Scorch - Spell ID 2948

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2655]
**Links:**

https://www.wowhead.com/spell=2948/scorch

**What is happening:**

Scorch is doing less damage then announced on Tooltip 
Tooltip says **4526** Damage (for 5437 Spellpower)
Damage on dummy without any buff : See following screenshot
https://puu.sh/DPn2p/aae1187c9b.png

**What should happen:**

Dr.Damage for Scorch says that Coeff is about 51.2% of Spellpower
(Proof : https://puu.sh/DPn3a/3204977f53.png

**Comment by Rushor** [comment]
bonus added, fixed with next server update
