### ISSUE TITLE
[Spell] Fireball - Spell ID 133

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2657]
**Links:**

https://www.wowhead.com/spell=18112/firebolt
It's BfA link, couldn't find the Firebolt ID in WoWhead database. I typed the one I got with Spell ID in game.

What is happening:

Firebolt is doing less damage then announced on Tooltip
Tooltip says 10100 Damage (for 5437 Spellpower)
Damage on dummy without any buff : See following screenshot
https://puu.sh/DPna7/458a2c0a59.png

What should happen:

Dr.Damage for Firebolt says that Coeff is about 123.6% of Spellpower
(Proof : https://puu.sh/DPnag/00a0cde1f1.png )

**Comment by Rushor** [comment]
bonus added, fixed with next server update

**Comment by Dranah** [comment]
Mages do not have a "firebolt" ability
what he means is "Fireball"
It seems you have added the coeff to warlock imp firebolt instead, which is now OP as fuck
Fireball is still doing too low.

ID 133 requires the correction.

**Comment by Rushor** [comment]
i know, i added it for 133 which has 1.124 direct bonus now. To which valueshould it be increased?

**Comment by Rushor** [comment]
ye changed to 1.236

**Comment by Dranah** [comment]
Good now.
