### ISSUE TITLE
[Spell/Racial] Cultivation - Spell ID 20552

### ISSUE THREAD

**Issue by Lerixo** [WoWManiaUK/Blackwing-Lair#2658]
**Links:**
https://www.wowhead.com/spell=20552/cultivation
from WoWHead or our Armory

**What is happening:**

No increase of herb gathering speed as Tauren.

**What should happen:**

Taurens should be able through "Cultivation" to gather herbs faster than other races.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/9dgs7FY.jpg)

it works

maybe individual charbug. pls contact a gamemaster for you issue thanks
