### ISSUE TITLE
[Ghost Form Flying] Mount Hyjal 

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#2659]
**Links:**
![Screenshot_1](https://user-images.githubusercontent.com/52254524/60755976-4a63a800-a000-11e9-8a08-1d1d19abeb3d.png)

from WoWHead or our Armory

**What is happening:**

Flying mount not appearing in ghost form in Mount Hyjal.

**What should happen:**

Characters should have flying mount after releasing in ghost form in Mount Hyjal/Twilight Highlands/Deepholm/Uldum.

**Comment by Rushor** [comment]
flying mount added. fix will be added with next server update

![I](https://i.imgur.com/ckXIGLg.jpg)

**Comment by Denrunmt** [comment]
Thanks!
