### ISSUE TITLE
[Spell] HUNTER - [T.N.T.]

### ISSUE THREAD

**Issue by Sessh097** [WoWManiaUK/Blackwing-Lair#2660]
**Links:**

http://cata-shoot.tauri.hu/?spell=56336

**What is happening:**

0 Proc Explosive Shots from Black Arrow and Immolation/Explosive Trap

**What should happen:**

When you deal periodic damage with your Immolation Trap, Explosive Trap or Black Arrow you have a 20% chance to trigger Lock and Load.

**Comment by sarahkay88** [comment]
#2150
