### ISSUE TITLE
[Quest]  Knee-Deep  - worgen area

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2663]
**Links:**

https://www.youtube.com/watch?v=OldY7IkaWdk   - video showing how it works
https://wow.gamepedia.com/Knee-Deep 

**What is happening:**

seems like phasing issue,  no rats in tunnel to scare off and no npc to hand in at the end

**What should happen:**

there should be rats in the tunnel that you scare off with the rats and then you should be able to hand it in at the other end

**Comment by Kitzunu** [comment]
dont have access to restart the server

**Comment by Rushor** [comment]
going to fix that with spell area + the script for the rats man

**Comment by Rushor** [comment]
phasing and far effect for rat added!

![I](https://i.imgur.com/pxDl5nA.jpg)
