### ISSUE TITLE
[Quest] Spy infestation

### ISSUE THREAD

**Issue by kallemeisner** [WoWManiaUK/Blackwing-Lair#2665]
**Links:**
https://www.wowhead.com/quest=26076/spy-infestation
from WoWHead or our Armory

**What is happening:**
Nothing 

**What should happen:**
There should be glowing lights showing where the Stealthed npcs are walking.

**Comment by Rushor** [comment]
The glowing can not be fixed right now, but i added the required creatures and a sneak effect. quest can now be done. live with next update.

![I](https://i.imgur.com/k80AmMU.jpg)
