### ISSUE TITLE
[Professioj] Alliance Side Engineering Vendor Bug

### ISSUE THREAD

**Issue by anduril2006** [WoWManiaUK/Blackwing-Lair#2667]
Alliance Engineering vendors do not  have the 359 helm recipes.

Checked from horde side it works for horde 359 helmet recipes can be learned from the vendor.  IT does not require any faction specilization or rep to buy . Vendor simply sells it for gold . But  it just doesn't exist for alliance.

**What should happen:**

It should be sold by  the vendors for gold. As it is on horde side so as retaillike.

**Comment by Rushor** [comment]
pls provide the item ids from http://cata.cavernoftime.com. Then i can fix it. Reopen the issue once you added the items links. Thanks.
