### ISSUE TITLE
[Quest]  Laid to rest  - worgen area

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2668]
**Links:**

https://www.youtube.com/watch?v=2XwDTTveeJs   - video of quest in action
https://wow.gamepedia.com/Laid_to_Rest   -  link to quest
https://www.wowhead.com/quest=24602/laid-to-rest   -  wowhead link for ID

**What is happening:**

no unearthed  momento to loot on the ground

**What should happen:**

there should be piles of earth you loot to collect unearthed momento

**Comment by Rushor** [comment]
added, and double spawn removed
