### ISSUE TITLE
[Quest]   Keel Harbor  - worgen area

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2670]
**Links:**

https://www.youtube.com/watch?v=g3DbQbt3cyU   -   video of quest in action 
https://www.wowhead.com/quest=24680/keel-harbor  -  wowhead link for ID

**What is happening:**

Mobs from previous quest still in phase,  they should be gone,  and there are no new NPC's in the phase to hand in quest

**What should happen:**

all previous mobs should be gone and new npcs in phase to hand in

**Comment by Rushor** [comment]
cannot fix the first thing, but you should be able to see the new creatures now!
