### ISSUE TITLE
[Quest/Quest order]   They have allies,  but so do we

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2671]
**Links:**

https://www.youtube.com/watch?v=PbDdl5vztB4  =  quest in action
https://wow.gamepedia.com/Worgen_starting_experience   -  quest order  

**What is happening:**

1 -    the 2 quests after the quest in title  are both available to take,  they need to be in correct order  ,  they are available before you even hand in previous
2  -  you cannot click the Glaive Thrower to start the quest in the video above

**What should happen:**

this should be the quest order (  as in hand in then next becomes available )  -  no 2 quests are up the same time

A [12] Keel Harbor    
A [12] They Have Allies, But So Do We
A [12] Endgame
A [12] Rut'theran Village
that order

and you should be able to click the glaive thrower to start the quest

**Comment by Rushor** [comment]
http://cata.cavernoftime.com/quest=24681
