### ISSUE TITLE
[NPC] Sand Pygmy Corpse - ID 45186 - missing - Uldum

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2672]
**Links:**
NPC: https://www.wowhead.com/npc=45186/sand-pygmy-corpse
Quest: https://www.wowhead.com/quest=27179/field-work

**What is happening:**
At the moment there is not Sand Pygmy corpse, only a sand pygmy, which doesn´t offer a quest.
By the way: the quest items for that quest are already dropping.
![sand pygmy corpse - how it is](https://user-images.githubusercontent.com/18005338/60766805-42af0c80-a0af-11e9-9e36-7bb2194a1930.png)

**What should happen:**
The npc "Sand Pygmy Corpse" should be available and offer the quest Field Work.
![sand pygmy corpse - how it should be](https://user-images.githubusercontent.com/18005338/60766804-42af0c80-a0af-11e9-8b7c-d00cfb449d7f.png)

**Comment by Rushor** [comment]
![I](https://i.imgur.com/FfheXC1.jpg)
![I](https://i.imgur.com/gMrncrz.jpg)

added with next update

**Comment by zippoking** [comment]
It looked like it was fixed, but i accidentally canceled the quest. Now i can´t accept it again, because the sand pygmy corpse is back.


![sand pygmy corpse - how it is 2](https://user-images.githubusercontent.com/18005338/61038033-8f0a8d00-a3cc-11e9-9b75-ea51fa5668dc.png)

**Comment by Echinaceax** [comment]
new update from GM @Rushor 

Phase issue but then when they phase player they can see him but cant click on him
