### ISSUE TITLE
[Quest] Do the world a favor - ID 27187 - missing (auto accept) - Uldum

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2673]
**Links:**
Quest: https://www.wowhead.com/quest=27187/do-the-world-a-favor
NPC: https://www.wowhead.com/npc=45202/mangy-hyena
NPC: https://www.wowhead.com/npc=45204/skarf

**What is happening:**
I killed several Hyenas but the quest did not pop up.

**What should happen:**
Once you kill a hyena or two in that area, you'll get the quest. The quest is auto completed after you're done.
![Do the world a favor - how it should be](https://user-images.githubusercontent.com/18005338/60766920-776f9380-a0b0-11e9-84ab-f06aa1904d6a.png)

**Comment by Rushor** [comment]
fixed with next update

![I](https://i.imgur.com/itxtgVB.jpg)
