### ISSUE TITLE
[Rogue] Leather Specialization - spell id 86092

### ISSUE THREAD

**Issue by fuzzydunlop** [WoWManiaUK/Blackwing-Lair#2676]
**Links:** https://www.wowhead.com/spell=86092/leather-specialization

from WoWHead or our Armory

**What is happening:** Nothing. Learned the spell from the trainer, but it did not 'register' or w/e. Resulting in the spellbook still saying: See your trainer. And missing a 5% bonus to total agility.

**What should happen:** You should be able to learn the spell, and then getting a 5% bonus to agility.

**Comment by Rushor** [comment]
fixed

https://i.imgur.com/xHHoEyx.jpg

Learning will register it now. If you go to the trainer next time (after the fix was updated on the server) you will ba able to learn the correct Leather Specialization spell you will need to register it.

also fixed for other classes.
