### ISSUE TITLE
[Profession] Engineering Alliance Side Vendor Bug 

### ISSUE THREAD

**Issue by anduril2006** [WoWManiaUK/Blackwing-Lair#2677]
http://cata.cavernoftime.com/item=59359
http://cata.cavernoftime.com/item=59448
http://cata.cavernoftime.com/item=59458
http://cata.cavernoftime.com/item=59456
http://cata.cavernoftime.com/item=59449
http://cata.cavernoftime.com/item=59455
**What is happening:**
Alliance Engineering Vendors do not sell the 359 helm recipes listed above. 

**What should happen:**

Vendor should simply  teach it with gold.

**Comment by Tatoepaladin** [comment]
Can you prove it was purchased with gold and not cogs?

**Comment by anduril2006** [comment]
Lol that question is a bit irrelevant isn't it ? 
U can simply click on the link or wowhead to see by clicking taught by / learned from sections and see who sells it with what ? Or do the same and ask horde players that how did they learn it .

**Comment by Rushor** [comment]
spells (81722, 81724, 81716, 81720, 81725, 81714, 81715);

**Comment by Rushor** [comment]
done

https://i.imgur.com/17SE3cZ.jpg

the other trainers are also included.

live with next serverupdate

affected npcs: 
1702);
3494);
5174);
5518);
8736);
10993);
11017);
11025);
11031);
11037);
16667);
16726);
17222);
17634);
17637);
18752);
19576);
25277);
26907);
26955);
26991);
28697);
33586);
33611);
33634);
33677);
52636);
52651);
55143);
64924);

**Comment by Rushor** [comment]
![I](https://i.imgur.com/17SE3cZ.jpg)
