### ISSUE TITLE
[Spell] Ret paladin Sanctity of Battle Talent

### ISSUE THREAD

**Issue by anduril2006** [WoWManiaUK/Blackwing-Lair#2678]
**Links:**
http://cata.cavernoftime.com/spell=25956

**What is happening:**

The talent on the above  stated, is just not working at all. 

**What should happen:**

When talent is taken as ret., Haste effects should lower the CD of CS and DS.

**Comment by Rosgath** [comment]
Can confirm.

**Comment by Keader** [comment]
Working for me.
Remember: talent enable % hast affect cooldown.
Is always about HAST as status. So if your items provide you 10% of hast, it will reduce 10% of 4.5 sec cooldown.
