### ISSUE TITLE
[Spell] Ret. Paladin 

### ISSUE THREAD

**Issue by anduril2006** [WoWManiaUK/Blackwing-Lair#2679]
**Links:**

http://cata.cavernoftime.com/spell=86172
**What is happening:**

Divine Purpose is being triggered by changing Aura or self buffs used such as Inquisition. Changing aura makes it pop %50-60 of the time especially out of combat. 

**What should happen:**

As it is stated, following attacks should trigger it with %15 chance, not self buffs or auras.

**Comment by Geniuskp** [comment]
https://imgur.com/a/uJC7IFB
"self buffs used such as Inquisition" -look in that ss

**Comment by anduril2006** [comment]
says this site can't be reached. Can u explain please or  comment if im mistaken at any point. 
both for aura and self cds.

**Comment by Geniuskp** [comment]
Divine purpose procs from inquisition.

**Comment by anduril2006** [comment]
ah thnx for correction, so it leaves only aura changing procs  i guess if its not intended aswell.
