### ISSUE TITLE
[Profession] Archaeology digsites in zones not suitable for player level

### ISSUE THREAD

**Issue by anduril2006** [WoWManiaUK/Blackwing-Lair#2680]
**Links:**

from WoWHead or our Armory

**What is happening:**
Spawn points just poping next to mountains or trees, that is impossible to reach.
Also i wonder if its tested or not that alliance can actually awaken the 359s i 've been farming  for 9 days, got many rares but epics. On horde side ppl got em like piece of candy in couple hours.  RNG should not be like that compared to horde side having couple epics in couple hours. There are several bugs that alliance has but not horde i ask this one to be controlled please. 

**What should happen:**

**Comment by Rushor** [comment]
Hey man, pls provide specific psitions for that, else i cannot fix that.

A screenshot, the areaname and the x and y position would help. will reopen the issue once you privided that data. Thanks!

**Comment by hediunchained** [comment]
there is one here : Felwood 37.8  62.6 that i encountered the other day 
![image](https://user-images.githubusercontent.com/36192411/62433334-46789200-b734-11e9-9745-433445e5af00.png)

**Comment by fuzzydunlop** [comment]
I get this quite often, the dig-site being on a almost vertical cliff so it's impossible to get it. It's not at one particular spot, it happens with a lot of the dig-sites. RNG-gods playing tricks on us.

**Comment by Echinaceax** [comment]
@Rushor think we need a full test ...i have Arch on my test toon, i will do a full test when i can

**Comment by Echinaceax** [comment]
update so far: i have done 7 sites so far ..none a problem as yet, 

side note: i do think tho that the low rocky zones could be an issue when not flying up on tall hills/mountains, definitely random tho 

players need to add zones and gps when the come across one

**Comment by hediunchained** [comment]
@Echinaceax i also found out that if you relog, the location of the artifact changes , so it means you can loot the before inaccessible location

**Comment by Rushor** [comment]
**Links:**
https://wow.gamepedia.com/Archaeology

**What is happening:**
Digsites are appearing in zones not suitable for player's level, meaning they cannot be dug until very high level.
e.g. at level 20, I received sites in Badlands (40+), EPL (45+), Azshara & Ungoro (50+) and even Twilight Highlands (80+)
![InkedWoWScrnShot_092119_171813a_LI](https://user-images.githubusercontent.com/46089380/65376214-46593500-dc95-11e9-82ad-a390815e4f89.jpg)
![InkedWoWScrnShot_092119_172146a_LI](https://user-images.githubusercontent.com/46089380/65376215-46593500-dc95-11e9-8a86-6960edace358.jpg)


**What should happen:**
https://wow.gamepedia.com/Archaeology
> As related by Ghostcrawler:[5]
Archaeological dig sites...
**Your dig sites appear in level-appropriate zones.** Players will not be able to survey in Outland, Northrend or any of the Cataclysm zones until they have reached the minimum level to enter those zones.

**Comment by Rushor** [comment]
moved to https://github.com/WoWManiaUK/Blackwing-Lair/issues/3012
