### ISSUE TITLE
[Quest] Subdue the Subduer - ID 111090

### ISSUE THREAD

**Issue by Lerixo** [WoWManiaUK/Blackwing-Lair#2681]
**Links:**
https://www.wowhead.com/quest=11090/subdue-the-subduer
from WoWHead or our Armory

**What is happening:**

The questitem kills the Questmob instantly in one tick of the channeling, without completing the quest.

**What should happen:**
The channeling should slowly weaken the mob with each tick, starting a dialogue, which after a interrogation completes the quest.

**Comment by Rushor** [comment]
http://cata.cavernoftime.com/quest=11090

**Comment by Rushor** [comment]
spellbonus for the item removed. killcredit added. live with next serverupdate

![I](https://i.imgur.com/dWruAcW.jpg)
![I](https://i.imgur.com/FRJqGUt.jpg)
