### ISSUE TITLE
[Paladin][Prot]Judgement of the Just

### ISSUE THREAD

**Issue by Tatoepaladin** [WoWManiaUK/Blackwing-Lair#2682]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/601

**What is happening:**
Still not working.
Nothing happens when casting judgement

**What should happen:**
A debuff on the target reducing melee and ranged attack speed by 20% for 20sec

**Comment by Keader** [comment]
Something or someone changed it.
Need be checked again.

**Comment by Keader** [comment]
![image](https://user-images.githubusercontent.com/7120913/60834232-95172880-a196-11e9-8e82-6524da2af8ea.png)

Tested now and is working.
