### ISSUE TITLE
[Quest/JC Daily] Nibbler! No! - ID 25105

### ISSUE THREAD

**Issue by Lerixo** [WoWManiaUK/Blackwing-Lair#2683]
**Links:**
https://www.wowhead.com/quest=25105/nibbler-no
from WoWHead or our Armory

**What is happening:**

If you cut the gems, only the  "object" part of the quest is complete, the "cutting" part remains uncomplete. Quest is not endable.

**What should happen:**

As you cut the three gems, both the object count and the crafting part should be counted. The
quest should be completeable.

**Notes**

As i have seen, which is another problem, there is only one Jewelcrafting daily, and there should be two, if we are speaking blizzlike. Not only this crafting daily does not work, so do all of the other Jewelcrafting dailies. Only the daily you have to hunt elementals for does work. But still. 2 dailies and working crafting dailies should be the way to go.

**Comment by Lerixo** [comment]
Other non working JC dailies are:
A Present for Lila - ID 25154
Ogrezonians in the Mood - ID 25161

All of them are the same as "Nibbler! No!", you have to cut three uncommon gems, and all result in the same bug.

**Comment by Rushor** [comment]
yes gonna fix all dailies.

**Comment by Rushor** [comment]
fixed, fix will be live with the next server update in some days.

![I](https://i.imgur.com/buOv2HZ.jpg)
