### ISSUE TITLE
[Talent/Hunter] Posthaste

### ISSUE THREAD

**Issue by jazielk** [WoWManiaUK/Blackwing-Lair#2684]
**Links:**
https://rpgworld.altervista.org/talentcata/eng/?HU
*it is the  second to last on the left talent

from WoWHead or our Armory

**What is happening:**
The talent Posthaste isn't increasing move speed after using Disengage

**What should happen:**
After using Disengage you should recieve some move speed for a few seconds.

**Comment by Rushor** [comment]
fixed. available with the next server update

![I](https://i.imgur.com/J2W1dfR.jpg)

**Comment by jazielk** [comment]
Great! Thank you!

**Comment by Keader** [comment]
Do not close issues.

**Comment by jazielk** [comment]
sorry first time using GitHub
