### ISSUE TITLE
[Quest]  Endgame   - worgen area

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2685]
**Links:**

https://www.youtube.com/watch?v=-O0offmuqV0   -  how the quest looks in action
https://www.wowhead.com/quest=26706/endgame   -  link to quest

**What is happening:**

you are able to accept the quest ,  however tobias is not signalling you to jump on the gryphons to fight the gunship

**What should happen:**

after a few seconds tobias mismantle signals you to jump on the gryphons next to him to fly to the horde gunship,  where you fight horde and plant explosives,   there is a few sequesnces to this quest,   will be a hard one !

**Comment by Rushor** [comment]
is set to autocomplete now, will fix the other quests now

**Comment by Rushor** [comment]
next quest - teleport added Admiral Nightwind

**Comment by Rushor** [comment]
All quests till http://cata.cavernoftime.com/quest=26385 can now be completed.
