### ISSUE TITLE
[Nagrand/Zul Drak Arena] Both arenas linked

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#2686]
**Links:**

from WoWHead or our Armory

**What is happening:**

If you do the Nagrand arena and you get to level 75, try to do Zul' Drak arena, both arenas somehow link. When you get the starting quest (The Champion's Call) from Shifty Vickers in Dalaran and return it to Gurgthock, the NPC called Wodin the Troll-Servant in Zul' Drak is supposed to give you the first arena quest, but he doesn't have any to give. Basically, if you do the quests in Nagrand arena, you get linked with Zul' Drak arena and can't do the quests there.

**What should happen:**

Players should be able to do both arenas without getting linked with each other.

**Comment by Echinaceax** [comment]
reported here #2339
