### ISSUE TITLE
[Quest] Kindness - ID 10804 - Shadowmoon Valley

### ISSUE THREAD

**Issue by HrPottemager** [WoWManiaUK/Blackwing-Lair#2689]
Quest - https://www.wowhead.com/quest=10804/kindness
NPC - https://www.wowhead.com/npc=22113/mordenai

What is happening:
After placing a carcass on the ground no drake eats the meal.

What should happen:
After looting Carcass' from Rocknail Flayers you place the carcass on the ground and a netherdrake will fly down and eat it. This has to be done 10 times in order to complete the quest.

**Comment by Rushor** [comment]
the movement generator is strange, they don't fly back.

added that which will fix the quest.

![I](https://i.imgur.com/9EJ6MQF.jpg)
