### ISSUE TITLE
[Quest] Thieving little pluckers - ID 28250- Uldum

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#269]
Quest- https://www.wowhead.com/quest=28250/thieving-little-pluckers
NPC -https://www.wowhead.com/npc=46603
ITEM -https://www.wowhead.com/item=63351/tahret-dynasty-mallet
**What is meant to happen** - u are meant to use the hammer to hit the puckers this then kills them and marks them off your list of 30 hit
**What is happening** - hammer causes no damage and doesn't register that you have hit them therefore you agro around 7-8 mobs that you must then try and kill ( has a mage this is hard - squashy clothie  )
 Making this quest impossible to complete because once killed it still doesn't count has part of the quest.

**Comment by Rushor** [comment]
https://i.imgur.com/7sSLX6d.jpg

whole script does not work.can you rewrite it in sai? on spellhit - give questcredit

**Comment by Bathelmo** [comment]
what? the script work just fine

**Comment by Bathelmo** [comment]
no i won't

**Comment by Bathelmo** [comment]
it works locally, but not on realm strange..

**Comment by Echinaceax** [comment]
![fix3](https://user-images.githubusercontent.com/39439201/62414877-b0544700-b621-11e9-87af-45f35712f7c4.jpg)
