### ISSUE TITLE
[Spell/Mage] Frostfire bolt spell coeff + Glyph dot coeff

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Blackwing-Lair#2691]
:)

**Comment by Dranah** [comment]
Well, that works. The debuff now displays "miss" on each tick and slows movement instead if you dont have the glyph.
The damage from the glyph dot however doesn't match.
It says 3% additional damage, but it does less, like 2,5% of my ~5k ffb shot over 8sec, and it doesn't scale with critting. Critting 10k still gives same damage as it did with 5k hit.

**Comment by Keader** [comment]
The ~2.5% of your test was about spell coeff.
The problem here is 3% damage boost is not added.
Fixing it.

**Comment by Keader** [comment]
ok, now will always do 3% of Damage * StackNumber
And will scale with crit.

**Comment by Dranah** [comment]
Now the damage is calculated properly to be 3% of any damage FFB lands, however it is 3% every TICK now instead of overall. It needs to be divided into 4 ticks.
