### ISSUE TITLE
northrend ores & hemps

### ISSUE THREAD

**Issue by nudelchris** [WoWManiaUK/Blackwing-Lair#2692]
northrend ores & hemps are pretty rare.
i farmed cobalt ore for like 1,5 hours on known farm routes & got round 80 ores.
im not the only one with this problem. wotlk recources are pretty rare & respawn time is extreme high

greetings :)

**Comment by Tatoepaladin** [comment]
I had no issue with farming cobalt. It seems the mountain range between grizzly and fjord is scarce but the route in grizzly and borean have plentiful spots

**Comment by Rushor** [comment]
Such kind of reports are not good. You need to specify which zones are bad for farming, then we can adjust the pools. Please be more detailed, then we can actualy fix the problem.
https://github.com/WoWManiaUK/Blackwing-Lair/blob/master/CONTRIBUTING.md

**Comment by nudelchris** [comment]
Ok im sorry, this is my first bugreport. its about howling fjord & zul'drak. 
im not the only one who got problems with this.

**Comment by nudelchris** [comment]
tested borean tundra. 
a little better, but respawn is like 30 min.
