### ISSUE TITLE
[Spell] [Druid]  rejuvenation

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2696]
**Links:**

http://cata-shoot.tauri.hu/?spell=774

**What is happening:**

with my current gear it is healing for 10k less than the tooltip on dr damage shows it should,   its supposed to heal for 3510 every 2.82 seconds,   but its currently healing for  2226,  thats quite alot,  works out about 10k less healing over the course of 1 spell,   when you take into account you can hot up loads of people  in a raid environement and 5 people in a 5 man instance,  thats 50k damage that you cannot heal because of missing values

**What should happen:**

should be healing for alot more !   im still new to testing spells with coeffs and the maths im still struggling with so i wont go into that,    but it should at my current gear and spell power  should be healing for 10k more baseline with 0 crits,  but its healing for about 11 k  not 21 k as dr damage tooltip states

**Comment by Dranah** [comment]
Confirmed, spell gets currently 0 coefficient.

How it should work:
The total effect should receive 53,6% SP coeff, that is 13,4% per tick.

**Comment by Rushor** [comment]
increased the direct bonus, please check that :o

**Comment by Keader** [comment]
Realy Rushor?

**Comment by Rushor** [comment]
there should be no direct bonus right?

**Comment by Keader** [comment]
Is not that, we already talked about you and spell fixes @Rushor

**Comment by Dranah** [comment]
There is no change.

**Comment by Rushor** [comment]
oh alright haha

**Comment by Keader** [comment]
Based in value added to DB, looks correct now Dranah, 13,4%

**Comment by giles1508** [comment]
just had a report from a player that since update rejuve has gone worse..  has this been pushed to live yet ?  if so it needs looking at again

**Comment by Dranah** [comment]
Still no coeff. Heals base amount with whatever SP.

**Comment by Keader** [comment]
Fixed.
