### ISSUE TITLE
[NPC] Lady La-La - ID 49913 - missing - Kelp'thar Forest

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2697]
**Links:**
NPC: https://www.wowhead.com/npc=49913/lady-la-la

**What is happening:**
The NPC Lady La-La is missing in the Kelp'thar Forest in Vashj'ir.
![Lady La-La - how it is](https://user-images.githubusercontent.com/18005338/60904216-f44a6b00-a272-11e9-8759-84db7c82941f.png)

**What should happen:**
She should be at one of her spawn positions in the Kelp'thar Forest in Vashj'ir.
![Lady La-La - how it should be](https://user-images.githubusercontent.com/18005338/60904217-f44a6b00-a272-11e9-9287-74cab85fb2e1.png)

**Comment by Rushor** [comment]
fixed

added here here:

![I](https://i.imgur.com/1jBMNkc.jpg)
