### ISSUE TITLE
[Instance][Event] Halls of Stone - Brann Bronzebeard - invisible mobs - Storm Peaks

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2698]
**Links:**
NPC: https://www.wowhead.com/npc=150865/brann-bronzebeard

**What is happening:**
When you start the event by talking to him in the Halls of Stone, he walks up to the console. Short after that he is attacked by one or maybe two invisible mobs. I healed him and then i was attacked by the invisible mobs.

Brann is attacked by something:
![Halls of stone - how it is 1](https://user-images.githubusercontent.com/18005338/60908587-873bd300-a27c-11e9-9394-8e2364fe8c02.png)

Then i am getting attacked by something:
![Halls of stone - how it is 2](https://user-images.githubusercontent.com/18005338/60908588-873bd300-a27c-11e9-8e6e-589d56157fbe.png)

Speach bubbles without an owner:
![Halls of stone - how it is 3](https://user-images.githubusercontent.com/18005338/60908589-87d46980-a27c-11e9-861d-5b4fc248fb19.png)

At the end of the event more speach bubbles without an owner:
![Halls of stone - how it is 4](https://user-images.githubusercontent.com/18005338/60908586-873bd300-a27c-11e9-9e96-9b5f7d1097d3.png)

**What should happen:**
All mobs should be visible and attackable by the player. The boss event should work as expected.

**Comment by Rushor** [comment]
A trigger is attacking him

**Comment by Rushor** [comment]
fixed, live with next serverupdate
