### ISSUE TITLE
[Quest] Warchief's Command: Outland! - Blasted Lands

### ISSUE THREAD

**Issue by Venom64bit** [WoWManiaUK/Blackwing-Lair#2699]
**Links:**

Quest: https://www.wowhead.com/quest=28705/warchiefs-command-outland

**What is happening:**
This quest is the same as Through the Dark Portal, but after completing it, it does not take you to the next step Arrival in Outland.

**What should happen:**
I should be able to take Arrival in Outland.

**Comment by Kitzunu** [comment]
Cannot reproduce this, after completing Warchiefs command outland! I can proceed to the next quest

**Comment by Venom64bit** [comment]
Tested with Goblin.

**Comment by Kitzunu** [comment]
Okay, will recheck :)

**Comment by Kitzunu** [comment]
Found the issue, fixed
