### ISSUE TITLE
[EVENT] Darkmoon Faire

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2700]
**Links:**
https://wowwiki.fandom.com/wiki/Darkmoon_Faire

**What is happening:**
The DMF is not running during the expected period. According to the calendar, it should be started on 30th june and ended on 6th july but the Mystic Mages didn't spawn and the portal was not where it was supposed to be (outside Thunder Bluff, in Horde side) during that week.

The TB Mystic Mage is always there, but he gives not teleport as reported here #358

**What should happen:**
DMF should start the first sunday of the month and least seven days. The DMF Mystic Mages are supposed to spawn during that period and grant a teleport to the location of **the portal** for the DMF island (and not directly to the DMF island).

When the Darkmoon Faire is running, you will find Darkmoon Faire Mystic Mages (Alliance/Horde) at the following locations.

> Alliance locations
> Darnassus: next to the portal to Rut'theran Village
> Exodar: outside the Bank
> Ironforge: outside the Auction House
> Stormwind City: outside the Auction House in the Trade District
> Horde locations
> Orgrimmar: next to the Flight Master
> Silvermoon City: at the entrance of the city
> Thunder Bluff: at the base of the central totem tower
> Undercity: in the Trade Quarter
> Neutral locations
> Dalaran: in the middle of Runeweaver Square
> Shattrath: outside the Auction House

I understand that there's a lot of work to do about the entire DMF, but atm it's crucial to get there in order to get the trinket of the inscription decks, at least.

**Comment by Rushor** [comment]
We will inspect after the majority of instances is done!

**Comment by Rushor** [comment]
the mages are already fixed. we start and deactivate the darkmoon faire manually each time.
