### ISSUE TITLE
Galaen's Fate

### ISSUE THREAD

**Issue by NoraDR** [WoWManiaUK/Blackwing-Lair#2701]
**Links:**
https://www.wowhead.com/quest=9579/galaens-fate

**What is happening:**
I've spent about 20 minutes here killing the enemies around here trying to get the quest item. I have space in my inventory and I've killed so many of them but it's not dropping. I have tried to abandon the quest and retake it multiple times even went off to do a dungeon and coming back it's still not dropped...

**What should happen:**
After you kill a few the item should drop :v.

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/60994433-cfc4c080-a350-11e9-8654-a3501900385d.png)

works, just has very low droprate
