### ISSUE TITLE
[NPC] Adarrah - ID 39883 - missing - Kelp'thar Forest

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2702]
**Links:**
NPC: https://www.wowhead.com/npc=39883/adarrah

**What is happening:**
Here´s the deal: It´s pretty difficult to get a heal relic for a druid. Either the quests are not working, or the whole area (Vashj'ir and Twilight Highlands) is buggy etc.

But i found this one [quest](https://www.wowhead.com/quest=25388/a-case-of-crabs), which is working, where i can get a good relic. The only problem is, that the NPC is not there to turn in the quest. According to the wowhead comments, a couple of pre-quests are required and all that stuff for the NPC to appear.

Since it will take a lot longer to fully fix the quest chain in Vashj'ir, could you please spawn the npc at his position, so that i and other players can turn in the quest and get this nice relic!
![adarrah - how it is](https://user-images.githubusercontent.com/18005338/60987685-6ccc2d00-a342-11e9-82c4-2aab4158500e.png)

**What should happen:**
Adarrah should be inside the Smuggler's Scar in the Kelp'thar Forest. (keep in mind, that you actually need other quests for her to appear, but lets just skip this step ;) )
![adarrah - how it should be](https://user-images.githubusercontent.com/18005338/60987684-6ccc2d00-a342-11e9-864f-6eee70a46181.png)

**Comment by Rushor** [comment]
added 

![I](https://i.imgur.com/4t3ASvE.jpg)

**Comment by zippoking** [comment]
Thank you so much!!!!
