### ISSUE TITLE
[Quest] Warchief's Command: Northrend! - Borean Tundra

### ISSUE THREAD

**Issue by Venom64bit** [WoWManiaUK/Blackwing-Lair#2704]
**Links:**

Quest: https://cata-twinhead.twinstar.cz/?quest=28711

**What is happening:**
(Like Warchief's Command:Outland!)
If you are Goblin you can't continue with the next quest which open all the rep chain.

**What should happen:**
(With Goblin) After completing that quest you can continue with the next step.

Tested with Goblin lvl 69.

**Comment by Rushor** [comment]
fixed with next update
