### ISSUE TITLE
Elementium Ore Twilight Highlands (52185)

### ISSUE THREAD

**Issue by nudelchris** [WoWManiaUK/Blackwing-Lair#2706]
elementium ore is pretty rare in twilight highlands.
the screenshot shows all found spawnpoints of it.

![WoWScrnShot_071119_002446](https://user-images.githubusercontent.com/52678929/61009265-6eade480-a372-11e9-9892-e7e8d55dc5ad.jpg)

thats what the official farming route is on retail.
- no pyrit too
- u cant enter the area around BoT because deathwing is there & kills everything
http://www.wowberufeguide.de/images/farmen/erze/schattenhochland.jpg

**Comment by zippoking** [comment]
Absolutely disagree with the elementium ore.
Maybe there a few spawnpoints, but the respawn timer is very short.

Pyrit, i could agree. i only found 1 Pyrit spawn point in twilight highlands so far. But also short respawn timer.

**Comment by nudelchris** [comment]
Thats true zippo. when only one person farms there is no problem, but even when there are two people who want to farm the same thing, there is a huge problem i think.
so maybe set the respawn a little down & give the players more options to farm seperate.

**Comment by Tatoepaladin** [comment]
Biggest issue is the area by BoT deathwing needs to leave

**Comment by Tatoepaladin** [comment]
But yes there are wuite a few nodes missing and none of the spots you posted are what i farmed in retail

**Comment by Rushor** [comment]
https://www.wowhead.com/object=202741/rich-elementium-vein

**Comment by Rushor** [comment]
ALRIGHT GUYS! I have just added a huge patch with spawn for Rich Elementium Vein in Deepholm  (756), Twilight Highlands  (536), Uldum  (270), Tol Barad Peninsula  (52), and Tol Barad  (48).

I added pooling for them, so in each zone there will only be around 100 spawnpoints at the same time. Let me know if the spawnrate has to be adjusted then!

**Comment by Rushor** [comment]
![I](https://i.imgur.com/ZZ9bJIm.jpg)
