### ISSUE TITLE
[Quest] Meat on the hook - Dragonblight

### ISSUE THREAD

**Issue by Venom64bit** [WoWManiaUK/Blackwing-Lair#2707]
**Links:**

Quest: https://www.wowhead.com/quest=12017/meat-on-the-hook
Target: https://www.wowhead.com/npc=26510/tuugwar 

**What is happening:**
When the mob spawn It is an invalid target.

**What should happen:**
It should be killable.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/Lfo5cqb.jpg)
![I](https://i.imgur.com/WKnkn6J.jpg)

Fixed. Make sure that you move around him a bit once he reaches the hook! :>
