### ISSUE TITLE
[NPC] Slate Quicksand - ID 44143 - quest interaction - Deepholm

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2708]
**Links:**
NPC: https://www.wowhead.com/npc=44143/slate-quicksand
Quest: https://www.wowhead.com/quest=26791/sprout-no-more
Quest: https://www.wowhead.com/quest=26792/fungal-monstrosities

**What is happening:**
He offers 2 quests, but as soon as you take one, you cant take the other.
![Salte Quicksand - how it is](https://user-images.githubusercontent.com/18005338/61047805-95a2ff80-a3e0-11e9-8847-bee766a90187.png)

**What should happen:**
You should be able to take both quests at the same time.
![Salte Quicksand - how it should be](https://user-images.githubusercontent.com/18005338/61047804-95a2ff80-a3e0-11e9-9e40-6d07efbf25c9.png)

![Salte Quicksand - how it should be 2](https://user-images.githubusercontent.com/18005338/61047806-95a2ff80-a3e0-11e9-9ef8-52199e0fc300.png)

**Comment by Rushor** [comment]
fixed with next update

![I](https://i.imgur.com/jJJPowc.jpg)
