### ISSUE TITLE
[Quest] Violent Gate - ID 26426 - Deepholm

### ISSUE THREAD

**Issue by Toorok** [WoWManiaUK/Blackwing-Lair#2709]
**Links:**
Quest: https://www.wowhead.com/quest=26426/violent-gale

**What is happening:**
We don't get credit for finding Felsen and the entrance to the Crumbling Depths.
![Felsen](https://user-images.githubusercontent.com/28814506/61052227-40b8b680-a3eb-11e9-9fa0-16cf6a98d224.PNG)

**What should happen:**
Credit should be given when standing close to Felsen and the entrance.

**Comment by Rushor** [comment]
fixed with next update

![I](https://i.imgur.com/LpVuXD5.jpg)
![I](https://i.imgur.com/AiLeuCw.jpg)

**Comment by Echinaceax** [comment]
still has issues #1995
