### ISSUE TITLE
[NPC/MOB] Riverbed Crocolisk - [needs work] Uldum

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#271]
NPC - https://www.wowhead.com/npc=45321/riverbed-crocolisk
The following quest - https://www.wowhead.com/quest=28200/the-element-of-supplies Given by https://www.wowhead.com/npc=48012 required you to obtain 20 hides from these mobs. However they cannot be aggroed and when attacked there health bar just resets
![world of warcraft 21_12_2018 17_08_47](https://user-images.githubusercontent.com/42302580/50354523-b8a0bb80-0543-11e9-98ae-3debd80d8f39.png)

**Comment by sarahkay88** [comment]
all the crocs  that I targeted did the same thing

**Comment by Kitzunu** [comment]
maybe fix in another issue, but I cannot reproduce anymore
