### ISSUE TITLE
Absorbs vs healing meters

### ISSUE THREAD

**Issue by TheRealLuxanna** [WoWManiaUK/Blackwing-Lair#2710]
**What is happening:**All absorb effects like Holy Paladin mastery 86474 ID , Power word: Shield 17 ID ,Divine Aegis 47515 ID , etc don't count as healing in any healing meters

**What should happen:** All absorb effects should count as healing in any healing meters

**Comment by Rushor** [comment]
Serverside issue or client side issue?

**Comment by TheRealLuxanna** [comment]
Serverside issue

**Comment by Tatoepaladin** [comment]
They are not counting in “healing meter” thats a 3rd party issue

**Comment by giles1508** [comment]
Won't be a 3rd party issue if the same addons work on other cata servers.. It means something on reign in core maybe isn't recognising absorbs as healing,  never the less it's not very important at the moment, it's only for epeen on meters,  if spells absorb then can wait

**Comment by Randomplayerx** [comment]
Absorbs are not recognized as healing aswell on other servers.

Because they are not heal=(heal is the number shown in green).

On addons like Recount you need special version or Skada.
