### ISSUE TITLE
[Class] Druid too speedy and pacified

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2714]
**What is happening:**
I can't attack with my druid in cat/bear form, a message appears on the screen saying "Can't attack while pacified"
![WoWScrnShot_071119_172912_2](https://user-images.githubusercontent.com/45459932/61074455-0fa2ab00-a418-11e9-9295-8d1bb4ce3584.jpg)
![WoWScrnShot_071119_175725_2](https://user-images.githubusercontent.com/45459932/61074518-3365f100-a418-11e9-8627-5216675649e8.jpg)

Moreover, when i walk in normal form, the speed is 100% and when i fly in flight form is over 480%
![WoWScrnShot_071119_175742_2](https://user-images.githubusercontent.com/45459932/61074756-bb4bfb00-a418-11e9-948c-42d967a04cb6.jpg)

Take a look to the discord world chat of wow-reign, i asked there if someone else got the same problem and it appears that other people have the same issue.
Rushor said it will be fixed soon, but better to keep here the info about this issue, because it's possible there's some other point that i didn't noticed.

**Comment by Rushor** [comment]
yes, also applied fix in a file now that it get's not forgotten. fix will be pushed tomorrow morning or this night.

**Comment by Rushor** [comment]
On live realm already
