### ISSUE TITLE
[Quest] WANTED: Uvuros, Scourge of Shadowmoon - 10647 - Shadowmoon Valley.

### ISSUE THREAD

**Issue by UnTizioSfaticato** [WoWManiaUK/Blackwing-Lair#2715]
**Links:**

quest - https://www.wowhead.com/quest=10647/wanted-uvuros-scourge-of-shadowmoon

**What is happening:**
The completed quest cannot be delivered

**What should happen:**

After completing the quest, an NPC should appear next to the signpost where you take the quest to deliver the quest

video: https://www.youtube.com/watch?v=T-Gd5tU6D5g

**Comment by Rushor** [comment]
the questgiver is in the tower 
![I](https://i.imgur.com/zY2XdfK.jpg)
