### ISSUE TITLE
[Npc] World Bosses (Loot)

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2716]
**What is happening:**
Last week i killed 2 world bosses with my guild and they did't drop anything.
Sadly i don't remeber the exact date of the kills, but i can tell you that:
Akma'hat > first time he dropped a 359 ilvl item: Belt of a Thousand Gaping Mouths. Second time he dropped only 2 green jc recipes and nothing else. Third time he dropped... nothing.
Mobus > first time he dropped a 359 ilvl item: Mobus's Dripping Halberd. Second time he dropped a 359 ilvl item: Drape of Inimitable Fate. Third time he dropped... nothing. 

**What should happen:**
Here the loot of Akma'hat > https://www.wowdb.com/npcs/50063-akmahat
Here the loot of Mobus > https://www.wowdb.com/npcs/50009-mobus

They're supposed to drop a 359 ilvl item at least, but according to some videos they're supposed to drop 2 epic items, some jc recipes and even a nice sum of gold.

![loot mobus](https://user-images.githubusercontent.com/45459932/61093423-c455c000-a44a-11e9-942c-3c5913256716.jpg)

https://www.youtube.com/watch?v=Hnd-ZDtpn9s
https://www.youtube.com/watch?v=kZwTY7b5Dcg

Atm i can report only these 2 bosses, but i'll add some comment if we kill some other world bosses and they give no loot.

**Comment by Rushor** [comment]
okay will make it like that: 1 recipe and 2 other items and gold

**Comment by Rushor** [comment]
Full list


    Garr - Everyone's favourite Molten Core boss, relocated to Mount Hyjal. Now with 99% less rage over the drops, guaranteed!
    Mobus <The Crushing Tide> - A huge whale shark in the Abyssal Depths of Vashj'ir. Probably wants to eat you.
    Xariona - A twilight dragon roaming the center of Deepholm. Sadly, it doesn't sparkle.
    Akma'hat <Dirge of the Eternal Sands> - A Tol'vir style colossus located in Uldum. Still no eye lasers... everything's better with eye lasers.
    Julak-Doom <The Eye of Zor> - A flesh giant, its mind taken over by a Merciless One, found wandering Twilight Highlands. You could chew through its 30 million hp, but a cork stopper would probably do the trick too.

**Comment by Rushor** [comment]
Akma'hat fixed

**Comment by Rushor** [comment]
Mobus fixed

**Comment by Rushor** [comment]
Xariona fixed

**Comment by Rushor** [comment]
Julak-Doom path and loot corrected

**Comment by Rushor** [comment]
okay all 4 bosses fixed so far, will handle the last garr in https://github.com/WoWManiaUK/Blackwing-Lair/issues/2373
