### ISSUE TITLE
[Quest] Secrets of the Tower quest bugged - 26290

### ISSUE THREAD

**Issue by ZeroAdios90** [WoWManiaUK/Blackwing-Lair#2717]
**links**
quest - https://www.wowhead.com/quest=26290/secrets-of-the-tower
item - https://www.wowhead.com/item=58112/potion-of-shrouding

![WoWScrnShot_071119_194845](https://user-images.githubusercontent.com/52804894/61094578-678be280-a415-11e9-96a0-fe00ce236fa9.jpg)

**whats happening**
- The potion the quest gives you doesn't make you go invisible. 
- Also the npc doesn't shoot the guards like she's supposed to.

**what should happen**
https://www.wowhead.com/quest=26290/secrets-of-the-tower#videos:id=84317

**Comment by sarahkay88** [comment]
#1479
