### ISSUE TITLE
[Druid][Balance] Shooting Stars

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2719]
**Links:**

talent id 93399

**What is happening:**
Starsurge (78674) consumes the Shooting Stars proc, if it occurs during the cast time of a Starsurge or during travel time. 

**What should happen:**
Starsurge (78674) should not consume a Shooting Stars proc, if the proc occurs while the Starsurge is being cast or during travel time.

**Comment by Dranah** [comment]
This is still happening during the cast time.
If the spell already travels, it no longer consumes, but the cooldown fails to reset.

**Comment by Keader** [comment]
And now?
