### ISSUE TITLE
[Item] Item Horn of Ramkahen -  Uldum

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#272]
Item - https://www.wowhead.com/item=62534/horn-of-ramkahen
For the quest - https://www.wowhead.com/quest=27839/ancient-weapons obtained from https://www.wowhead.com/npc=46134 when in the correct area this item should be used and it should call the following spell: https://www.wowhead.com/spell=87298. However when used the labours did not appear and no help was provided.

**Marked has low piro because I was able to complete the quest without the assistance of the item.**

**Comment by Rushor** [comment]
help is now given and the creatures will spawn once the item is used.

![I](https://i.imgur.com/ta1u9RI.jpg)
