### ISSUE TITLE
Alchemy Cauldron

### ISSUE THREAD

**Issue by dagget1337** [WoWManiaUK/Blackwing-Lair#2727]
**What is happening:**
The Alchemy Cauldrons which can be learned via scroll and skill 525 from the Guild vendor dont work after using them (They dont appear at all), besides the cauldron disappears from the inventory which i guess shouldnt be since the mats for 1 cauldron are quite hard to obtain (correct me if i´m wrong).

**What should happen:**
The Item shouldnt disappear (i guess) and a usable Cauldron should be spawned with their certain ammount of useability (7times and 20 times).

Link to Mentioned item: https://de.wowhead.com/item=65460/gro%C3%9Fer-schlachtzugskessel

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/JXGliZ3.jpg)

The flask iteself will be fixed later. need some corechecks for that.

**Comment by Rushor** [comment]
okay depending on which specc aura you have, you will get a buff

![I](https://i.imgur.com/YzXyvub.jpg)

live with next update
