### ISSUE TITLE
[Quest] Never Trust a Big Barb and a Smile - Misc

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Blackwing-Lair#2729]
http://cata.cavernoftime.com/quest=25165

The announcement for the quest is missing.

Clattering Scorpid is casting Envenom! Place yout totem down now!

should appear in the chat.

**Comment by Druhl** [comment]
Just an FYI:

In this area yesterday that announcement when in proximity to these quest mobs was going off even though I was not on and and not ever taken the quest.

I later took and did the quest and was able to complete it normally, including announcements.

Again, just an FYI, and not very important. Thanks for all your hard work!

Screenshot attached.
![WoWScrnShot_081219_155637](https://user-images.githubusercontent.com/19803911/63034579-93244180-be87-11e9-9b21-62404e576b09.jpg)
