### ISSUE TITLE
Molten Core Ragnaros event not starting

### ISSUE THREAD

**Issue by Floras5** [WoWManiaUK/Blackwing-Lair#2731]
**Links:**
https://de.wowhead.com/npc=11502/ragnaros

from WoWHead or our Armory

**What is happening:**

I killed every boss and the last one is standing at Ragnaros to spawn him but when i talked to him nothing is happening.

**What should happen:**
the npc shuld spawn Ragnaros

**Comment by Rushor** [comment]
![I](https://i.imgur.com/8WH7d1o.jpg)
![I](https://i.imgur.com/mZwM70H.jpg)


fixed with next update
