### ISSUE TITLE
Tempel of Ahn'Qiraj - Prophet Skeram is not attackable

### ISSUE THREAD

**Issue by Floras5** [WoWManiaUK/Blackwing-Lair#2732]
**Links:**
https://de.wowhead.com/npc=15263/der-prophet-skeram'

from WoWHead or our Armory

**What is happening:**

The first boss Prophet Skeram is not attackable

**What should happen:**

He should be ;)

**Comment by Rushor** [comment]
![I](https://i.imgur.com/zl2NJnr.jpg)

And the doors are also fixed now
