### ISSUE TITLE
[Quest] The Conquest Pit: Mad Furbolg Fighting - ID 12428 - Grizzly Hills

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2734]
**Links:**
https://www.wowhead.com/quest=12428/the-conquest-pit-mad-furbolg-fighting
from WoWHead

**What is happening:**
The enemy is unattackable, as happened for the first quest of the chain here #1784

**What should happen:**
The furbolg should be attackable in order to complete the quest. 
https://www.wowhead.com/npc=27716/torgg-thundertotem

**Comment by Rushor** [comment]
all pit creatures fixed
