### ISSUE TITLE
[Priest] Shadowy Apparitions

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2740]
**Links:**

78204 talent id 

**What is happening:**
Shadowy Apparitions walk to the target on the ground as a pet, instead of floating to the target through any texture.

**What should happen:**
Apparitions should float into the target,  not walk.

**Comment by Keader** [comment]
Not in cataclysm: https://www.youtube.com/watch?v=3kwoxgf1BQk
