### ISSUE TITLE
[Class/Talent] Rude Interruption - Warrior

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2742]
**Links:**
https://wow.gamepedia.com/Rude_Interruption

**What is happening:**
No buff is applyed after using Pummel.

**What should happen:**
Successfully interrupting a spell with Pummel should increase your damage by 5% for 15 sec.

**Comment by Eirolla** [comment]
![image](https://user-images.githubusercontent.com/26048748/62364642-c16e5c80-b52a-11e9-9fac-b27167c22973.png)
Fixed Confirmed.
