### ISSUE TITLE
[Spell/Protection] Seal of Insight - ID 20165 / 20167

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#2746]
**Links:**
https://wowwiki.fandom.com/wiki/Seal_of_Insight
**What is happening:**
Nothing happens , not a single heal during boss fight
http://tinypic.com/view.php?pic=2jcu6fd&s=9
**What should happen:**
As the spell says , should heal for a X amount while meele attacking.

**Comment by Rushor** [comment]
old issue https://github.com/WoWManiaUK/Blackwing-Lair/issues/644

**Comment by georgeapostolov** [comment]
Confirmed, I just entered with my paladin, not a single heal through all Hellfire Ramparts.,
