### ISSUE TITLE
[Item] Runescroll of Fortitude II

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#2747]
**Links:**
https://www.wowhead.com/spell=85785/runescroll-of-fortitude-ii
**What is happening:**
You dont get the buff after using it.
**What should happen:**
Runescroll of Fortitude II was applying Fortitude, which only provides 468 stamina
https://imgur.com/vMhkKWi

**Comment by Rushor** [comment]
[10:26:43]62251 - [Runescroll of Fortitude II]

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/ui5GCVB.jpg)
