### ISSUE TITLE
[Profession] Lightweave Embroidery

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2748]
**Links:** 

https://cata-twinhead.twinstar.cz/?spell=75172

**What is happening:**

Embroidery doesn't have any ICD (Internal CoolDown) and can proc everytime you uses a spell.

**What should happen:**

Lightweave Embroidery (like all embroidery, didn't checked them all) should gave 580 Int for 15 seconds on a 45 second ICD.

**Comment by Rushor** [comment]
yes will fix that

**Comment by Rushor** [comment]
icd added. live with next update

**Comment by Rushor** [comment]
okay pls retest this

**Comment by Echinaceax** [comment]
retested this and its procing contantly with every spell ...tested as priest and mind flay stay resetting 14s timer on buff and hasnt got a 45 sec CD

![CD broken](https://user-images.githubusercontent.com/39439201/65175316-f428d180-da52-11e9-8d8f-88c06cc23619.jpg)

**Comment by Rushor** [comment]
okay now it's fixed. had to check spell_proc
