### ISSUE TITLE
[Quest] A New Master - ID 25411 - Mount Hyjal

### ISSUE THREAD

**Issue by Myivo** [WoWManiaUK/Blackwing-Lair#2749]
**Links:**

https://www.wowhead.com/quest=25411/a-new-master

**What is happening:**

after killing a lord when I use  item nothing happens

**What should happen:**

Use the Bottled Bileberry Brew on the corpse of a Twilight Inferno Lord, then speak with him. His spirit should appear.

**Comment by zippoking** [comment]
Already reported: #1911

**Comment by Rushor** [comment]
duplicate
