### ISSUE TITLE
Experience gained for discovery of new area - Uldum

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#275]
The zone https://www.wowhead.com/uldum is not giving experience for discovery of new areas. not sure if this is what is meant to happen it is the only zone iv come across whilst levelling that didn't provide experience upon discovery.
![world of warcraft 21_12_2018 17_49_52](https://user-images.githubusercontent.com/42302580/50356263-46cb7080-0549-11e9-996c-27f4e0d106ce.png)

**Comment by wow-mania** [comment]
Works.
![image](https://user-images.githubusercontent.com/12248683/54618949-c343f180-4a5b-11e9-9040-13d783821ed5.png)
