### ISSUE TITLE
Herbs in Hyjal

### ISSUE THREAD

**Issue by NoraDR** [WoWManiaUK/Blackwing-Lair#2750]
I've been levelling herbalism and this herb in Hyjal has been taunting me, on the side of a cliff too high to harvest it from the bottom or the top. It's not impossible to get to but certainly very frustrating to get to.
![WoWScrnShot_071519_233330](https://user-images.githubusercontent.com/52752615/61297450-8fe05c00-a7dc-11e9-8bb6-228f161afff5.jpg)
![WoWScrnShot_071519_233333](https://user-images.githubusercontent.com/52752615/61297468-98389700-a7dc-11e9-8815-28ef60fb3c83.jpg)
I've also noticed that quite a few of the herbs can be harvested multiple times before disappearing, and it's always the same ones. There are too many for me to list here but if it helps all of them were in the firey areas of Hyjal and are all also Cinderblooms.

**Comment by Rushor** [comment]
Please tell me the NAME of all the herbs in that area. then i can fix it. Thank you. 
You can reopen and comment once it is done

**Comment by NoraDR** [comment]
As per my last message its the Cinderblooms in the fiery areas that can be harvested multiple times but not all of them.

**Comment by Rushor** [comment]
Will rework the spawn in a Different issue
