### ISSUE TITLE
[Stacking Buffs]

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2751]
**What is happening:**

Elixir such as Battle, Guardions or flasks, or even food does stack.

**What should happen:**

You only should get a single battle and guardian elixir at this time.
Check for food, flasks, scrolls etc plz

https://puu.sh/DTwKo/d953a77584.png

**Comment by Cenasty** [comment]
ID Github 19000 
Fixed in Dev
Pending

Still not Live I guess

**Comment by Rushor** [comment]
alright

it's more a db thing.

spellgroup added for those spells:

(1, 2367),
(1, 2374),
(1, 3160),
(1, 3164),
(1, 3166),
(1, 7844),
(1, 8212),
(1, 10667),
(1, 10669),
(1, 11328),
(1, 11334),
(1, 11390),
(1, 11396),
(1, 11405),
(1, 11406),
(1, 11474),
(1, 16322),
(1, 16323),
(1, 16329),
(1, 17038),
(1, 17535),
(1, 17537),
(1, 17538),
(1, 17539),
(1, 17624),
(1, 17626),
(1, 17627),
(1, 17628),
(1, 17629),
(1, 21920),
(1, 24363),
(1, 26276),
(1, 28486),
(1, 28488),
(1, 28490),
(1, 28491),
(1, 28493),
(1, 28497),
(1, 28501),
(1, 28503),
(1, 28509),
(1, 28518),
(1, 28519),
(1, 28520),
(1, 28521),
(1, 28540),
(1, 33720),
(1, 33721),
(1, 33726),
(1, 38954),
(1, 39627),
(1, 40567),
(1, 40568),
(1, 40572),
(1, 40573),
(1, 40575),
(1, 40576),
(1, 41608),
(1, 41609),
(1, 41610),
(1, 41611),
(1, 42735),
(1, 45373),
(1, 46837),
(1, 46839),
(1, 53746),
(1, 53747),
(1, 53748),
(1, 53749),
(1, 53752),
(1, 53755),
(1, 53758),
(1, 53760),
(1, 53764),
(1, 54212),
(1, 54452),
(1, 54494),
(1, 60340),
(1, 60341),
(1, 60344),
(1, 60345),
(1, 60346),
(1, 62380),
(1, 63729),
(1, 67016),
(1, 67017),
(1, 67018),
(1, 79468),
(1, 79469),
(1, 79470),
(1, 79471),
(1, 79472),
(1, 79474),
(1, 79477),
(1, 79481),
(1, 79632),
(1, 79635),
(1, 79637),
(1, 79638),
(1, 79639),
(1, 79640),
(1, 80532),
(1, 94160);

also:

spellgroup stacing roule added for all flasks.
