### ISSUE TITLE
[Dungeon/Queue] Dungeon queue system

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#2753]
**Links:**

from WoWHead or our Armory

**What is happening:**

So, the queue system atm is broken. For a few days now I and a lot of people get this problem. When I'm in queue as for example dps and in the queue there are heal,tank and 1 more dps with me, so we are waiting for 3rd dps, I suddenly go to solo queue... alone. This has happened like 10 times now and it's getting really annoying because other people get the same problem too and we can't queue for a dungeon. Once I went alone in a new queue (When I haven't even left the que before that and was waiting just for 1 dps to queue), I asked in world chat if people got the same solo que problem too. The answer was "Yes". 

**What should happen:**

Queue system should work normally and it shouldn't kick us in separate queues. I know it has something to do with which dungeon you are saved from, but the queue was almost full, so all the people that were in it should be able to do dungeons that I'm able to do too and not be kicked in separate queues.

**Comment by kDracku** [comment]
Maybe some of your party members are locked for some dungeons that you are not and viceversa

**Comment by Keader** [comment]
I cant reproduce.
To me always work fine.

**Comment by TheSale** [comment]
https://prnt.sc/poxa9g

some dungeon finder glitches
there are full teams across factions looking for dungeon but it dont pop up, but we have to look up and inv people to make group
and now it show me alone in rdf, but few more people are in queue

**Comment by Echinaceax** [comment]
@keader apparently this happens when a player selects more than one role :)

**Comment by Rushor** [comment]
moved to https://github.com/WoWManiaUK/Blackwing-Lair/issues/4011
