### ISSUE TITLE
[Profession/Crash] Fishing

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#2754]
**Links:**
![Screenshot_7](https://user-images.githubusercontent.com/52254524/61312961-23785380-a802-11e9-971f-fb6208849d5a.png)

from WoWHead or our Armory

**What is happening:**

Every time I use the spell Fishing, my game crashes. I fished Volatile Fire in Mount Hyjal with 1/525 fishing yesterday with no problems and today my game crashes whenever i try to fish. I saw an already closed issue about the same problem, saw the steps WoW-Mania gave to the guy, I did them but nothing changed. Also I don't have realmlist.wtf and I never needed to open the launcher as admin before. It worked without doing all these steps. I moved my game folder from (D:) to (C:), but this still didn't help. Tried to make the client folder NOT read only but it just doesn't work. My folder is still staying Read Only and I don't have an active antivirus at the moment. It wants subscribtion so the step with the antivirus can't be done aswell. Please Help.

Update: Found the realmlist.wtf and its not marked as Read Only. 
Update: Found out that the problem is with my rogue's fishing. When i fished yesterday with my death knight, it worked but today there is a problem with my rogue that keeps crashing me every time i try to fish on it. So probably the problem is with my rogue only. 
**What should happen:**

**Comment by Cenasty** [comment]
I'm the author of the 1st thread related to this issue. Can confirm, still crashing..

**Comment by Frostmanx** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/2551

**Comment by Cenasty** [comment]
Actually my game (and I think his too) is on 1.0.5 version, see following screenshot of my client before logging
https://puu.sh/DTAxz/e2abc069ba.png

But the thing you speaking of is the Game folder labelled Wow Reign 1.0.4 due to the initial version we downloaded
https://puu.sh/DTAxz/e2abc069ba.png (Error)
https://puu.sh/DTACz/6df8ecece1.png (GameFolder)

**Comment by Frostmanx** [comment]
@Cenasty its can't be under Program files.. it should be directly under the root folder 
![3334](https://user-images.githubusercontent.com/50195620/61320209-94316700-a826-11e9-9ed4-cae05f62e55c.PNG)
irectly under your root  eg

**Comment by Cenasty** [comment]
Well, now, new fact
On my first char it doesn't work but on an alt it work, I just managed to catch a fish.

**Comment by Denrunmt** [comment]
Gonna move the folder to C: My game is at 1.0.5 patch, but my wow folder says its at 1.0.4. Going to make screenshots after my RHC.

**Comment by Sammy974** [comment]
I can confirm this issue. It happens to a guid mate, i report for him because he's not able to write in english.
He has done all the recommended things. His client is 1.0.5 (he downloaded the entire client again) his realmlist have the "read only" unflagged, the folder is in C: and he starts the launcher as administrator. Maybe there is some conflict with something, because just before the crash he sees a visual strange thing like vertical bars on his toon. I will add a screen shot soon. He has no alts so he can't try with another toon of the same account.

**Comment by Denrunmt** [comment]
So, my game version is at 1.0.5 (screenshot below) and i think the reason why my folder is called "WoW-Reign 1.0.4" is because I downloaded the game client at that patch and I don't think the folder could automatically rename itself to "1.0.5" when the launcher is being updated.

![Screenshot_2](https://user-images.githubusercontent.com/52254524/61324695-b70a4e00-a81b-11e9-96ec-2bf489364662.png)

And I don't think its from the game not being in (C:), because it has always been in (D:) and I never had problems with fishing until today. 

Also tried with downloading the launcher again from https://wow-reign.com/start , but it's version is still called "1.0.4" as it shows on the screenshot below. 

![Screenshot_8](https://user-images.githubusercontent.com/52254524/61324884-1cf6d580-a81c-11e9-8aa9-0f3c8d5c2aa1.png)

**Comment by Sammy974** [comment]
Ok guys.. something very odd is happening! My guildmate is fishing in Valley of Wisdom in Orgrimmar and everyone around him have a client crash also if they're not fishing! I add the screenshot from him. I was close to him and i crashed with the same visual thing as he started to fish. We've tested it with several persons and everyone had a crash if my guildmate start fishing close to them.

![WoWScrnShot_071619_231214](https://user-images.githubusercontent.com/45459932/61330604-4c0f4600-a820-11e9-9c74-ad5f8e1fe150.jpg)

**Comment by Echinaceax** [comment]
please be careful on duplicate reports #2551

**Comment by Denrunmt** [comment]
@Echinaceax Sorry, didn't know that if you open an issue related to an issue that's closed it's still a duplicate. Going to comment on closed issues now if the problem that has been fixed appear again. Just thought you guys wouldn't see new comments since its closed already :D

**Comment by Echinaceax** [comment]
@Denrunmt thats, thats what we are here for ;)
you can comment on closed issues (then we re check if it regressed somehow)
