### ISSUE TITLE
[Class/Spell] Howling Blast - Death Knight

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2755]
**Links:**
https://www.wowhead.com/spell=49184/howling-blast

from WoWHead

**What is happening:**
Howling Blast do not affect the target if you're not directly in front of him.

**What should happen:**
Howling Blast should affect your target also if he's not directly in front of you.

**Comment by Keader** [comment]
![image](https://user-images.githubusercontent.com/7120913/61905435-77202680-aeff-11e9-98e9-8974452a86aa.png)

![image](https://user-images.githubusercontent.com/7120913/61905483-9323c800-aeff-11e9-9c9e-818f5f70c805.png)


Look that dummy, he is behind me, and still get the damage.
It always effect all targets in 10y radius.
