### ISSUE TITLE
[Class/Talent] Blood Parasite - Death Knight

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2756]
**Links:**
https://wowwiki.fandom.com/wiki/Blood_Parasite

**What is happening:**
Blood Parasites have a too low spawn rate and a too low heal. You never see more than 1 worm at time and the healing is inconsistent.

**What should happen:**
They should spawn more often considering that they have 10% chance on melee attacks and Heart Strike hits 3 targets. Their healing should scale with the DK's health.
I have found intresting this post in the official blizzard forum that explain the mechanics:
https://eu.battle.net/forums/en/wow/topic/1776521013

**Comment by Keader** [comment]
Fixed proc chance.
Blood Parasite heal issue fixed here: #2848
