### ISSUE TITLE
[Quest] At the Stonemother's Call - ID 26750 - Deepholm

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2757]
**Links:**
https://www.wowhead.com/quest=26750/at-the-stonemothers-call
from WoWHead or our Armory

**What is happening:**
The quest can't be completed because Therazane is not there.

**What should happen:**
You should be able to complete the quest talking to Therazane.

**Comment by Rushor** [comment]
if you are in phase 169, you will see here now

![I](https://i.imgur.com/MhsULri.jpg)

**Comment by Sammy974** [comment]
As it appears, she's there but you can't complete the quest anyway.
