### ISSUE TITLE
[Quest] Return to the Temple of Earth - ID 26255 - Deepholm

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2758]
**Links:**
https://www.wowhead.com/quest=26255/return-to-the-temple-of-earth
from WoWHead 

**What is happening:**
The quest can't be completed because Maruut Stonebinder is not where he's supposed to be.

**What should happen:**
You should be able to talk with Maruut Stonebinder in order to complete the quest.

**Comment by Rushor** [comment]
if you are in phase 169 you can see him now

![I](https://i.imgur.com/Nt5R5cb.jpg)
