### ISSUE TITLE
[Dungeon] Reputation

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#2762]
**Links:**

**What is happening:**
The mobs give me wrong reputation even with tabard on
https://imgur.com/n02i2tA
Same for Stonecore giving reputation with Hellscream Reach
**What should happen:**
Give reputation with faction that you have tabard on

**Comment by Rushor** [comment]
i the screen i see that you get rep for ramkahen. from which mob do you got that rep?

**Comment by Rushor** [comment]
all fixed already

![I](https://i.imgur.com/oMuT7ot.jpg)
