### ISSUE TITLE
[Priest] Shadow Word: Death self damage

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2764]
**Links:**

spell id 32379

**What is happening:**
After the recent fix, SWD does not damage the priest if used on targets below 25%, which is an issue for mana regen. 

**What should happen:**
SWD should damage the priest if used on targets under 25% hp as well

**Comment by Rushor** [comment]
we combine that in once issue. moved to #2763
