### ISSUE TITLE
[NPC] Muddied Water Elemental - Water Spout

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2766]
**Links:**

https://www.wowhead.com/npc=44011/muddied-water-elemental#comments
**What is happening:**
Water Spout throws you up to jesus

**What should happen:**
Water Spout should probably not kill you from fall damage

**Comment by Rushor** [comment]
next update fixed, also for several other creatures

![I](https://i.imgur.com/6nSjUrq.jpg)
