### ISSUE TITLE
[Quest] Aessina's Miracle - Mount Hyjal

### ISSUE THREAD

**Issue by Venom64bit** [WoWManiaUK/Blackwing-Lair#2768]
**Links:**

Quest: https://www.wowhead.com/quest=25372/
Giver: https://www.wowhead.com/npc=41381
Target: https://www.wowhead.com/npc=39858

**What is happening:**
The Archdruid Hamuul Runetotem are located in Sanctuary of Marlorne instead Grove of Aessina.

**What should happen:**
The Archdruid Hamuul Runetotem (as the quest says) should be in the Grove of Aessina .

The quest can be completable if you delivery it at Sanctuary of Marlone.

**Comment by Rushor** [comment]
fixed with next update

![I](https://i.imgur.com/AHueMuG.jpg)
