### ISSUE TITLE
[Quest] Apply and Flash Dry - ID 26411- Deepholm

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#277]
quest - https://www.wowhead.com/quest=26411/apply-and-flash-dry
NPC - https://www.wowhead.com/npc=42574
Item - https://www.wowhead.com/item=58502
You are to use the item on NPC - https://www.wowhead.com/npc=43036/flint-oremantle
But nothing happens.
![world of warcraft 21_12_2018 18_24_57](https://user-images.githubusercontent.com/42302580/50357545-2f42b680-054e-11e9-9ca9-82a70978fab7.png)
![world of warcraft 21_12_2018 18_24_59](https://user-images.githubusercontent.com/42302580/50357550-32d63d80-054e-11e9-8ccd-bfd403385172.png)

**Comment by gamer100** [comment]
The  quest is  still not  working the  same issue as described in this post

**Comment by sarahkay88** [comment]
#2945

**Comment by sarahkay88** [comment]
Reclose this the fix was added to the other report, I just linked them togther so when people check they can find the fix. Remember to keep old ones open and add info :)

**Comment by sarahkay88** [comment]
Reclose this the fix was added to the other report, I just linked them togther so when people check they can find the fix. Remember to keep old ones open and add info :)
