### ISSUE TITLE
[NPC] Muddied Water Elemental

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2772]
**Links:**

https://www.wowhead.com/npc=44011/muddied-water-elemental#drops

**What is happening:**

only drops max 2 volatile waters at a possible lower drop chance than it should

**What should happen:**
it should drop 1-3 volatiles at a 13% rate

**Comment by Rushor** [comment]
yes maxamount increased to 3 with next update.
