### ISSUE TITLE
[NPC] Tarvus the Vile / Twilight Highlands

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#2773]
**Links:**
Tarvus the Vile- name of npc
NPC ID: 50086
![Screenshot_1](https://user-images.githubusercontent.com/52254524/61393267-4cafe700-a8c9-11e9-85b3-d4589c066d6e.png)
![Screenshot_2](https://user-images.githubusercontent.com/52254524/61393278-52a5c800-a8c9-11e9-946a-601d555f9501.png)

from WoWHead or our Armory

**What is happening:**

The NPC spawns under the ground. No mines/caves where I could enter and look if it's inside them. Tried to pull it with my pet but it doesn't work.

**What should happen:**

The NPC should spawn on the ground so it could be killed/pulled by people.

**Comment by Rushor** [comment]
https://i.imgur.com/miYFlUc.jpg

here you need to enter 

![I](https://i.imgur.com/NlePUCk.jpg)
![I](https://i.imgur.com/miYFlUc.jpg)

**Comment by Denrunmt** [comment]
Oh, my bad then. Sorry!
