### ISSUE TITLE
[Pet/Hunter] Pet commands

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#2774]
**Links:**
![Screenshot_10](https://user-images.githubusercontent.com/52254524/61420058-843e8380-a909-11e9-9efb-a3d9dd938844.png)
![Screenshot_11](https://user-images.githubusercontent.com/52254524/61420074-9fa98e80-a909-11e9-8d8e-ec2ceafe5e40.png)
![Screenshot_12](https://user-images.githubusercontent.com/52254524/61420077-a20be880-a909-11e9-945e-6005462074a1.png)

from WoWHead or our Armory

**What is happening:**

Some of the pet commands dissapear from the pet bar every time I mount/dismount or relog. I put the commands on the bar again and again but they continue dissapearing.

**What should happen:**

The commands should stay on the pet bar unless I manually change or remove something from the it.

**Comment by Rushor** [comment]
added a save check that should always add the petbar if missing. let's try it out
