### ISSUE TITLE
[Dungeon] Temple of Ahn Qiraj 40 Door After Prophet Skeram closed.

### ISSUE THREAD

**Issue by dagget1337** [WoWManiaUK/Blackwing-Lair#2775]
**What is happening:**
The Classic raid dungeon Temple of Ahn Qiraj works until the Twins fine, i know they can only be killed if they´re both atleast 60yards apart but the real problem is: Upon dieing to reset them and re-enter the dungeon the entrance to the temple inside the dungeon seems to be shut closed even while the bosses should´ve reset by then.

**What should happen:**
The Door should be Open as soon as the Combat ends after every boss fight in this dungeon (dont know if this only affects the Twins) and the door to c-thun should open as soon as they´re dead (couldnt check on that since i couldnt kill them)

**Comment by Rushor** [comment]
you mean the door at the first boss?

**Comment by Rushor** [comment]
after a server restart the door is shut down
