### ISSUE TITLE
[Boss] Ozumat - double spawning - Throne of the Tides

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2776]
**Links:**
https://www.wowhead.com/npc=44566/ozumat
from WoWHead 

**What is happening:**
There are 2 Ozumat. The first is there from the beginning and he close the entrance of the last 2 bosses until you kill the first 2 upstairs. You can see the cinematic where he moves upstairs after killing the first boss. When you're doing the last encounter of the istance, he's still there, he invade the room with his big tentacle and he's targettable but not attackable. In the last phase of the encounter, you have 2 Ozumat: the first one and another one who's supposed do be attackable in the last phase in order to end the encounter. This is quite confusing, because you need to target the right Ozumat to attack him and the first one is big and take all the visibility.
![WoWScrnShot_071719_194201_2](https://user-images.githubusercontent.com/45459932/61452105-4a966880-a95b-11e9-839e-749c7960c6c4.jpg)

**What should happen:**
The first Ozumat should not be invading the room while you're doing the last encounter of the dungeon. Only one Ozumat should be targettable and attackable in order to end the encounter.

**Comment by Rushor** [comment]
50270

**Comment by Rushor** [comment]
the big once will now always be despawned once the with with Ozumat is started.
