### ISSUE TITLE
[NPC] Sister Svalna - Icecrown Citadel

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2777]
**Links:**
https://www.wowhead.com/npc=37126/sister-svalna
from WoWHead 

**What is happening:**
Testing in 10nm. She's not attackable, maybe because Crok and his army stuck in the hall and don't approach her.
https://www.wowhead.com/npc=37129/crok-scourgebane

**What should happen:**
Crok should approach Svalna after clearing the hall from the trash mobs, and she should become attackable.

**Comment by Rushor** [comment]
old raids? what are you doing in there :D

**Comment by Rushor** [comment]
attackable with next update 

![I](https://i.imgur.com/czVDRNq.jpg)

**Comment by Sammy974** [comment]
We' re a wotlk nostalgic guild xD

**Comment by Rushor** [comment]
oh man, then i need to fix wotlk stuff when i get time :D

**Comment by Sammy974** [comment]
You definitely do. Ulduar next time. ;)

**Comment by Rushor** [comment]
but please also focus on current dungeons aswell
