### ISSUE TITLE
[Boss] Valithria Dreamwalker - Icrown Citadel

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2778]
**Links:**
https://www.wowhead.com/npc=36789/valithria-dreamwalker
from WoWHead

**What is happening:**
Testing in 10nm. The blue circle around her doesn't disappear when the fight starts and there's some issue with portals: some of them doesn't allow you to enter.

**What should happen:**
The blue circle should disappear when the fight starts and all the portals should allow you to enter when they open.

**Comment by Rushor** [comment]
https://youtu.be/mauZX6xJBkg?t=6  The circle should not dissapear

will fix the spellclick of the portals.

**Comment by Sammy974** [comment]
> https://youtu.be/mauZX6xJBkg?t=6 The circle should not dissapear

You're right, my bad :)
