### ISSUE TITLE
[Boss] Sindragosa - Icecrown Citadel

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2779]
**Links:**
https://www.wowhead.com/npc=36853/sindragosa
from WoWHead

**What is happening:**
Tested in 10nm. She's not attackable and the fight can't be started.

**What should happen:**
Sindragosa should be attackable in order to start the fight.

**Comment by Rushor** [comment]
fixed with next update

![I](https://i.imgur.com/V6POuf9.jpg)
