### ISSUE TITLE
[Raid Event] Gauntlet Event - Icecrown Citadel

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2780]
**Links:**
I wasn't able to find any link related to this, sorry. :)

**What is happening:**
The event doesn't start when you enter the room. The door to Sindragosa's lair is open and you can easily walk trough the gauntlet with no waves coming.

**What should happen:**
As you arrive with the elevator and enter the room, several waves of mobs should come and you should not be able to reach Sindragosa's Lair until the event is over and the waves stop coming, because the door should be closed.

**Comment by Rushor** [comment]
takes too much time for now, we will look at this later
