### ISSUE TITLE
[Dungeon] Loot in Heroic Mode - Blackrock Caverns

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2782]
**Links:**
https://www.wowhead.com/blackrock-caverns
from WoWHead 

**What is happening:**
All the bosses in this dungeon aren't dropping money. The last boss, Ascendant Lord Obsidius, doesn't drop the chaos orb.
https://www.wowhead.com/npc=39705/ascendant-lord-obsidius#drops:mode=heroic

**What should happen:**
All the bosses should drop money and the last boss should drop a chaos orb in heroic mode.

**Comment by Sammy974** [comment]
Edit: Today the last boss dropped the chaos orb. So he doesn't drop it just "sometimes". Yesterday, for istance, he didn't drop it.

**Comment by Rushor** [comment]
yes chance must be increased to 100 percent

**Comment by Rushor** [comment]
![I](https://i.imgur.com/fP4yDC3.jpg)
![I](https://i.imgur.com/IpX95P3.jpg)

gold and orb added
