### ISSUE TITLE
[Object] Netherwing Egg - ID 32506

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2786]
**Links:**
https://www.wowhead.com/item=32506/netherwing-egg
from WoWHead

**What is happening:**
Some of them are not leaving the blue smoke after you gather them.

**What should happen:**
The eggs have a blue smoke around them, that should stay there after you gather them to indicate the respawn position.

**Comment by Sammy974** [comment]
Edit: the blue smoke seems to appear after some minute, btw i didn't found any smoke in some places of spawn that i know. I'll edit after more testing.

**Comment by Rushor** [comment]
smoke added alsways now 
![I](https://i.imgur.com/bzMMn9e.jpg)
