### ISSUE TITLE
[Item] Elementium Toolbox and Rigid Cogwheel

### ISSUE THREAD

**Issue by Sevenblade11** [WoWManiaUK/Blackwing-Lair#2787]
**What is happening:**
Currently, if one buys Rigid Cogwheel with an Elementium Toolbox equipped, the vendor will take the toolbox, and everything with it. These items will NOT be mailed back to the player, only the Rigid Cogwheel.
Steps to reproduce:
1: Equip an Elementium Toolbox and place some ores, engineering equipment, etc. Anything that you would wish to be removed!
2: Purchase Rigid Cogwheel. The NPC will take the equipped Toolbox, taking everything within it as well.
3: Done. Wait a few minutes and the Rigid Cogwheel will appear in the mail; however, everything else in the bag will not appear. 
**What should happen:**
Simple. The NPC should not take the toolbox. If needed, the NPC I used is Sovik in Orgrimmar.

**Comment by Rushor** [comment]
okay, added a fix where the item will now only be shown if the bag (
Elementium Toolbox) is actually empty.

**Comment by Rushor** [comment]
the item will now only be displayed at the vendor IF the bag (this case Elementium Toolbox) is empty. So the core will check if there is actually that kind of box in iventory and IF it's empty

**Comment by Rushor** [comment]
okay that addition is now done for Lure Master Tackle Box and Elementium Toolbox.
Remember: Both must be empty in inventory or bag slot, them the trade item will be shown.
