### ISSUE TITLE
[Raid Dungeon] Black Temple semi final Bosses appear 2x each

### ISSUE THREAD

**Issue by dagget1337** [WoWManiaUK/Blackwing-Lair#2788]
**What is happening:**
The last for Bosses (the 4 blood elfes) in Black temple appear 2times each and only the original ones can be killed while the other can only be hit until 1 hp then heal themselves up again.

**What should happen:**
The bosses should be unattackable at first until they´re finished with their dialogues, which makes them appear 2 times, the pre dialogue ones and the combat ready ones.

**Comment by Rushor** [comment]
pls next time tell me the exactly name and id, so i can faster fix everything @dagget1337

**Comment by Rushor** [comment]
hm cannot confirm that on dev 

![I](https://i.imgur.com/59nzsdI.jpg)

maybe just a temprary issue
