### ISSUE TITLE
[Spells] Ebon Plague Interactions

### ISSUE THREAD

**Issue by Z4but0m** [WoWManiaUK/Blackwing-Lair#2789]
**Links:**
https://cata-twinhead.twinstar.cz/?spell=51160
https://cata-twinhead.twinstar.cz/?spell=85948
https://cata-twinhead.twinstar.cz/?spell=50842

**What is happening:**
Pestilence & Festering Strike are not interacting with Ebon Plague. Pestilence does not spread Ebon Plague and Festering Strike does not increase Ebon Plague's duration.

**What should happen:**
Pestilence should be spreading Ebon Plague to other targets if the main target has the disease and Festering Strike should be increasing Ebon Plague's duration along with the other diseases.

**Comment by Keader** [comment]
Pestilense Description: 

> Description: Spreads existing **Blood Plague** and **Frost Fever** infections from your target to all other enemies within $a3 yards.  Diseases spread this way deal $s2% of normal damage.

Festering Strike description:

> Description: An instant attack that deals $m2% weapon damage plus $s1 and increases the duration of your **Blood Plague**, **Frost Fever**, and **Chains of Ice** effects on the target by up to $s3 sec.

None say that should affect Ebon Plague, not even in DBC has any evidence that should affect it.

**Comment by Z4but0m** [comment]
https://www.youtube.com/watch?v=K4OhUmw5zYE

In the video above you can see that the Deathknight is refreshing both baseline diseases, as well as Ebon Plague, with the use of Festering Strike. There is no glyph or outside function that would allow this, so it is absolutely affirmed that Festering Strike can and should refresh Ebon Plague.
As for Pestilence:
From the Ebon Plaguebringer talent itself, "Your Plague Strike, Icy Touch, Chains of Ice, and Outbreak abilities also infect their target with Ebon Plague". The wording of this talent suggests that as long as any target has any of these effects applied, Ebon Plague should be applied as well. So, in an AoE situation, if one target has Frost Fever and Ebon Plague applied and the Deathknight casts Pestilence, Frost Fever, and by extension Ebon Plague, will spread to all other targets.
