### ISSUE TITLE
[Quest] Twilight Shores - Missing (Unlocks Zone Twilight Highlands)

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#279]
**Missing chain quests** this is the opening quest chain for the area that many players will follow 
**Quest starts** - https://www.wowhead.com/quest=28716/heros-call-twilight-highlands -- **NPC**:https://www.wowhead.com/object=206111 **( can be completed) This then activates quest** https://www.wowhead.com/quest=26977/twilight-investigation **by NPC**: https://www.wowhead.com/npc=29611
**Instead** after the https://www.wowhead.com/quest=28716/heros-call-twilight-highlands --  **the quest** : https://www.wowhead.com/quest=28238/twilight-shores **should have been activated by NPC**: https://www.wowhead.com/npc=29611 **leading onto the quest** : https://www.wowhead.com/quest=28832/twilight-shores activated **by NPC**: https://www.wowhead.com/npc=44806 **and then finally quest:** https://www.wowhead.com/quest=28596/welcome-to-highbank **which is activated by** NPC:https://www.wowhead.com/npc=49022 opening the start area for questing

**Comment by Dranah** [comment]
Twilight investigation seems available without any prerequisites so it is unrelaed.
The real issue seems to be that https://www.wowhead.com/quest=28238/twilight-shores is not properly unlocked by the Hero's call quest.

**Comment by Rushor** [comment]
that is the current prevquest cata.cavernoftime.com/quest=27106

will change that
