### ISSUE TITLE
[Quest] Entrenched - ID26436 - Deepholme

### ISSUE THREAD

**Issue by Toorok** [WoWManiaUK/Blackwing-Lair#2791]
**Links:**
Wowhead: https://www.wowhead.com/quest=26436/entrenched

**What is happening:**

Kor the "Immovable" is missing. 
![Entranched](https://user-images.githubusercontent.com/28814506/61514372-41130c00-aa00-11e9-95e1-1324cb500148.PNG)

**What should happen:**

Kor should be stuck in the ground, so we can turn in the quest.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/9BqZvrF.jpg)

position fixed

**Comment by Toorok** [comment]
@Rushor fixed with next update?

**Comment by Rushor** [comment]
yes

**Comment by Sammy974** [comment]
@Rushor  I'm in front of him, i have the quest, but there's no question mark on him and the quest can't be delivered.

![WoWScrnShot_081219_181131_2](https://user-images.githubusercontent.com/45459932/62880117-ff3e6280-bd2c-11e9-9025-131737911cee.jpg)

**Comment by Sammy974** [comment]
Tested with a different toon, same thing. :(

![WoWScrnShot_081219_212402_2](https://user-images.githubusercontent.com/45459932/62892180-e7280c80-bd47-11e9-9898-037bf569bf97.jpg)

**Comment by Sammy974** [comment]
Ok, need to be at least neutral to speak with Kor. Otherwise he's unfriendly and you can't interact with him.
