### ISSUE TITLE
[Quest] Gorishi Grub

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Blackwing-Lair#2792]
https://www.wowhead.com/quest=13903/gorishi-grub

The Silithid Meat is not counting for quest

After getting  10 Silithid Meat the quest  must complete to feed the Venomhide Hatchling.
This  a daily  quest for Venomhide babytooth

**Comment by Rushor** [comment]
![I](https://i.imgur.com/0ewHQtR.jpg)

works on dev. maybe you are in a raid group http://cata.cavernoftime.com/npc=34320

do: /script LeaveParty();

https://github.com/WoWManiaUK/Blackwing-Lair/issues/2739

**Comment by gamer100** [comment]
I am not in raid group and up to date, got all 10 meat, quest did not complete restarted game  run launcher  and deleted cache

**Comment by gamer100** [comment]
I am stupid did it wrong

**Comment by Rushor** [comment]
np
