### ISSUE TITLE
[zone] zone Tanaris

### ISSUE THREAD

**Issue by quortonn** [WoWManiaUK/Blackwing-Lair#2793]
**Links:** https://www.wowhead.com/quest=25566/the-secrets-of-uldum

**What is happening:** Entering in the crypt teleports you at your current HS location

**What should happen:** just enter in the crypt and turn in the quest

**Comment by Rushor** [comment]
cannot reproduce that issue

https://i.imgur.com/dS1Ke7a.jpg

can you talk together with a gm and let them check your auras on your char? maybe that causes the teleport issue

**Comment by quortonn** [comment]
i had the issue with several toons, i'll try to talk with a gm today to
make him see this

Il giorno ven 19 lug 2019 alle ore 13:36 Rushor <notifications@github.com>
ha scritto:

**Comment by Xman993** [comment]
it happens to me.
more comming soon. :D

**Comment by Xman993** [comment]
is not just the quest, its the Uldum zone. when you go in the zone, you get teleported.

**Comment by Rushor** [comment]
ah yes because uldum :D whill make an exception for that

**Comment by Rushor** [comment]
At low level you no longer get teleported away from here. on all other zones in uldum at low level you get teleported. let me know if there are more areas like that.

![I](https://i.imgur.com/VWTsNv4.jpg)

Cheers.
