### ISSUE TITLE
[NPC/Raid] Majordomo Executus - ID 12018

### ISSUE THREAD

**Issue by Lerixo** [WoWManiaUK/Blackwing-Lair#2794]
**Links:**
https://www.wowhead.com/npc=12018/majordomo-executus
from WoWHead or our Armory

**What is happening:**
In Molten Core, after defeating all bosses, having Majordomo surrender and him ported into the middle to spawn the last boss Ragnaros, his dialogue option, which should spawn Ragnaros, wont lead to anything and the last boss wont spawn. 

**This makes dropping materials used for Legendary Weapons from Ragnaros impossible.**

**What should happen:**
After Majordomo Executus ported himself into Ragnaros' Lair, his dialogue options should spawn Ragnaros, making the raid fully completeable.

**Comment by Rushor** [comment]
okay yes! the gossip was wrong. fixed with next update

![I](https://i.imgur.com/E9spN8q.jpg)
![I](https://i.imgur.com/hWsoAQn.jpg)
![I](https://i.imgur.com/Kt267H8.jpg)
