### ISSUE TITLE
[Dungeon] Upper Blackrock Spire doors wont open

### ISSUE THREAD

**Issue by dagget1337** [WoWManiaUK/Blackwing-Lair#2795]
**What is happening:**
After Defeating th boss Warchief Rend Blackfist the dorrs from the arena and to Bwl wont open instead the fight keeps only looping while rend respawns everytime. NPC-Id: 10429 its not the boss thats bugged i guess, but just the doors.

**What should happen:**
The doors should open as soon as NPC-Id: 10429 Warchief Rend Blackfist died.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/36YBpon.jpg)
![I](https://i.imgur.com/iib3SJY.jpg)
![I](https://i.imgur.com/yAMLYaS.jpg)

**Comment by Rushor** [comment]
alright spawns works now and the dorr will be opnened once gyth is killed.
