### ISSUE TITLE
[Talent/Druid] Revitalize

### ISSUE THREAD

**Issue by Sevenblade11** [WoWManiaUK/Blackwing-Lair#2796]
**Links:**

http://www.cavernoftime.com/spell=48544

**What is happening:**
Currently, both the druid casting Rejuvenation / Lifebloom and party members do not get Replenishment to aid with mana regeneration.

**What should happen:**
When a druid with this talent casts Rejuvenation or Lifebloom, both the player and party / raid members should get a Replenishment buff.

**Comment by Sevenblade11** [comment]
It's still slightly bugged. The druid should get the buff without being in a group as well. Currently, Replenishment only comes up when the druid is in a group.

**Comment by Dranah** [comment]
Last tests show it does proc replenishment even when the druid is ungrouped, however it's not exactly procing as it should.

**How it should work**: The replenishment effect should proc whenever the druid **casts** lifebloom.
**How it works atm:** It doesn't proc off lifebloom spellcasts at all.
It seems to proc 2-3sec after applying a lifebloom from a tick of healing (2nd or 3rd tick) and is not able to refresh until it expired.

**Comment by Keader** [comment]
Is impossible make it proc on cast.
Only when tick (with this proc flag)
But you are right, cooldown was wrong.
12 Sec cooldown need be applied to instant mana regen, not for replenishment.
Fixed.
