### ISSUE TITLE
[Talent/Hunter] Thrill of the Hunt

### ISSUE THREAD

**Issue by Ataroox** [WoWManiaUK/Blackwing-Lair#2801]
**Links:**|

http://cata.cavernoftime.com/spell=34499

**What is happening:**
I testing it on dummy for a ~10 min and doesn't saw any proc.

**What should happen:**
Arcane Shot, Explosive Shot and Black Arrow should have a 15% chance to regain 40% of the base focus cost of the shot.

**Comment by Keader** [comment]
Duplicated of https://github.com/WoWManiaUK/Blackwing-Lair/issues/2546
Will be fixed this week.
