### ISSUE TITLE
[Quest] Black Heart of Flame - ID 25428 - spawned npc not attackable - Mount Hyjal

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2805]
**Links:**
Quest: https://www.wowhead.com/quest=25428/black-heart-of-flame
Item to spawn NPC: https://www.wowhead.com/item=53464/charred-branch
NPC: https://www.wowhead.com/npc=40107/tholembaar
Quest Item to loot : https://www.wowhead.com/item=53454/black-heart-of-tholembaar

**What is happening:**
You can spawn the NPC with the item, but the npc is not attackable. He doesn´t even have a  healthbar on top of him (see screenshot).
![Black Hearet of Flame - how it is](https://user-images.githubusercontent.com/18005338/61578779-08585d00-aafc-11e9-82cc-0c52fefac546.png)

**What should happen:**
The NPC should be attackable and drop the quest item after you spawn him with the provided item.
![Black Hearet of Flame - how it it should be 1](https://user-images.githubusercontent.com/18005338/61578780-08f0f380-aafc-11e9-96d6-81b6a4dfb1a8.png)
![Black Hearet of Flame - how it it should be 2](https://user-images.githubusercontent.com/18005338/61578778-08585d00-aafc-11e9-87f6-c68ea3d0cb1e.png)

**Comment by Rushor** [comment]
the summon is static, must eb removed

**Comment by Rushor** [comment]
![I](https://i.imgur.com/PlLegv4.jpg)
![I](https://i.imgur.com/RhWAzHT.jpg)

**Comment by zippoking** [comment]
Now i can´t use the item at all. Summoning is not possible. Not fixed for me.
I made sure to abandon the quest and re-accept it.

![Black Hearet of Flame - how it is 2](https://user-images.githubusercontent.com/18005338/61626312-492baf80-ac7d-11e9-81ef-1f445db0429a.png)
