### ISSUE TITLE
[Dungeon The Vortex Pinnacle] Rewards bugged

### ISSUE THREAD

**Issue by Ataroox** [WoWManiaUK/Blackwing-Lair#2806]
**What is happening:**
I only got 1x Justice Piont from first boss,and another problem is i did not get reward from RHC(Valor Points and Maniac)

**What should happen:**
I should get 75 Justice points and reward from doing RHC

**Comment by kDracku** [comment]
If the server restart/crash while doing RHC you will not get the valor after complete it.

**Comment by Rushor** [comment]
so no issue with the dungeon itself, generic issue
