### ISSUE TITLE
[Quest] Sea Legs - ID 24432 - spell reward buff missing - Vashj'ir

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2808]
**Links:**
Quest: https://www.wowhead.com/quest=24432/sea-legs
Spell: https://www.wowhead.com/spell=73701/sea-legs

**What is happening:**
After completing the quest Erunak Stonespeaker is casting the Spell on you, but you don´t really get it. Which means you can´t breath and walk/swim faster underwater.

As you can see on the screenshot, i am already on the following quest, but i don't have the Sea Legs Buff from the previous quest.
![Sea Legs - how it is](https://user-images.githubusercontent.com/18005338/61580328-0ea50400-ab11-11e9-9f5f-bb2a9049783b.png)

**What should happen:**
After completing the quest, you are granted the Sea Legs spell, which allows you to breath and walk/swim faster under water.
![Sea Legs - how it should be 1](https://user-images.githubusercontent.com/18005338/61580329-0ea50400-ab11-11e9-8228-d349ec1dc50a.png)
![Sea Legs - how it should be 2](https://user-images.githubusercontent.com/18005338/61580327-0ea50400-ab11-11e9-8b05-3ae16970abc0.png)

**Also: I don´t how it works after the spell is fixed, somebody needs to re-add it to my Warrior please!**

**Comment by Rushor** [comment]
i added the spellarea now in the whole zone. quest is not required. i mean, it's the very first quest. no big deal so..

fixed with next update

![I](https://i.imgur.com/Ox7y6ET.jpg)

**Comment by Rushor** [comment]
you will have 3 auras then

[12:28:15]id: 73701 [Sea Legs] effmask: 7 charges: 0 stack: 1 slot 1 duration: -1 maxduration: -1   caster: player guid: 281
[12:28:15]id: 74516 [Sea Legs] effmask: 1 charges: 0 stack: 1 slot 0 duration: -1 maxduration: -1   caster: player guid: 281
[12:28:15]id: 75966 [Sea Legs] effmask: 7 charges: 0 stack: 1 slot 2 duration: -1 maxduration: -1   caster: player guid: 281

74516 is for the visual, the other both for the effect
