### ISSUE TITLE
[Bank] Bags Slots

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2809]
**What is happening:**

The 4 first slots of my personal bank doesn't increase my bank number of slots, they just provide a single slot where I can put stuff.
The 3 remaining slot (5th, 6th, 7th) work as they should; putting a bag will increase the number of global slots

**What should happen:**

The 4 first slots shouldn't be occupied by anything else then bags, and when bags are put in, the number of slots have to increase

https://puu.sh/DVbnw/1c99fdf011.png

**Comment by Sammy974** [comment]
@Cenasty do you use ElvUi?

**Comment by Cenasty** [comment]
Yes

**Comment by Cenasty** [comment]
@Sammy974 Thanks for resolving !
