### ISSUE TITLE
[Quest] Burnin' at both ends - ID 28597- Twilight Highlands

### ISSUE THREAD

**Issue by ghost** [WoWManiaUK/Blackwing-Lair#281]
Quest - https://www.wowhead.com/quest=28597/burnin-at-both-ends
NPC - https://www.wowhead.com/npc=49020
Cannot ick up the required item for this quest.
Item - https://www.wowhead.com/npc=49020

**Comment by Dranah** [comment]
https://www.wowhead.com/item=64585/cannon-powder

**Comment by Eirolla** [comment]
02/08/19 issue still continues.

**Comment by jarvik76** [comment]
6th Oct:  still an issue

**Comment by Echinaceax** [comment]
fixed here #4429
