### ISSUE TITLE
[Grim Batol] Skinning

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2810]
**What is happening:**

Skinning the dragonskin doesn't provide any leather, scales etc..

**What should happen:**

When skinning it, they have to give stuff related to their level.
Here, a wowhead link about a dragonskin and what he should provide
https://fr.wowhead.com/npc=39855/prophète-de-la-nuée-azur#skinning

(I didn't research every single of them since I don't have all mobs name)

**Comment by Rushor** [comment]
fixed for all heroic creatures in all instances with next update

![I](https://i.imgur.com/JvpyKGG.jpg)
