### ISSUE TITLE
[Item] Tiny Treasure Chest loot

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2812]
**Links:**

https://www.wowhead.com/item=67539/tiny-treasure-chest#contains

**What is happening:**
does not drop gold and is often empty

**What should happen:**
should drop between 1.5 and 6 gold and should not be empty **so often**

**Comment by Rushor** [comment]
i cannot add the gold, but i will fix the loot

**Comment by Rushor** [comment]
will never be empty again and contains 2-3 items from each item group
