### ISSUE TITLE
[Grim Batol/Boss] Erudax

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2813]
**Links:**

https://fr.wowhead.com/npc=40484/erudax

**What is happening:**

Faceless Guardians doesn't equaly resist to crowd control, for exemple, 
I used Ring of Frost in their path, the left one (while being in the room facing entry stairs) got frozen, while the right one was 'Immune' when he walked on it.

**What should happen:**

I don't know if both should be immune or frozen, but I don't think one can be Immune while other gets frozen (and it didn't said 'Resisted' which could have been a frost school of magic resistance)

**Comment by wow-mania** [comment]
Unless you have more evidence we cannot work on "I think". 
Please find material to support it.

**Comment by Rushor** [comment]
yes they should be immune to 
SPELL_EFFECT_KNOCK_BACK, true);
MECHANIC_GRIP, true);
MECHANIC_STUN, true);
MECHANIC_FEAR, true);
MECHANIC_ROOT, true);
MECHANIC_FREEZE, true);
MECHANIC_POLYMORPH, true);
MECHANIC_HORROR, true);
MECHANIC_SAPPED, true);
MECHANIC_CHARM, true);
MECHANIC_DISORIENTED, true);

internal source

**Comment by Cenasty** [comment]
Sorry I thought I added the screenshot
Here is one of the faceless guardians frozen

https://puu.sh/DVaAD/3d752f46f2.png

**Comment by Rushor** [comment]
alright immunities added, fixed with next update
