### ISSUE TITLE
[Talent/Class] Hot Streak & Impact

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2814]
**What is happening:**

While you have a Hot Streak proc activ (meaning, free & castless Pyroblast), 
If you use Impact (Fire Blast with Talent ID 12357), 
With the actual bug of new Pyroblast fired
The Hot Streak buff is considered used and you can't use your proc.

**What should happen:**

First of all, Impact bug should be fixed (Thread ID 2425)
OR
Make that Pyroblast casted by that Impact bug abuse shouldn't trigger the Hot Streak buff given by Talent 44445 (Chance for Hot Streak to proc) OR 44448 (Double crit in a row grants a Hot Streak proc)

**Comment by Dranah** [comment]
Impact no longer fires an entire pyro on nearby targets.
Spreading the Pyro dot does not consume the Hot Streak proc anymore.
