### ISSUE TITLE
[Npc] Water Warden - Water Bubble - Halls of Origination heroic

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2815]
**Links:**
https://www.wowhead.com/npc=39802/water-warden
https://www.wowhead.com/npc=41257/water-bubble
from WoWHead

**What is happening:**
The npc casts the bubbles to all the players in the same time. With all the players bubbled is impossible to free someone from them. The boss can't be killed and the door to the boss can't be opened.

**What should happen:**
The npc should cast the bubble on 1-2 players at time, allowing the other players to free them. Once killed (as the last of the 4 small bosses), the door of the boss should open.

**Comment by Rushor** [comment]
will now only target one target, not all at once
