### ISSUE TITLE
[Zone/Raid] Onyxia's Lair 

### ISSUE THREAD

**Issue by Lerixo** [WoWManiaUK/Blackwing-Lair#2816]
**Links:**
https://www.wowhead.com/onyxias-lair
from WoWHead or our Armory

**What is happening:**
In the bossfight of Onyxia, in whelp phase, the adds arent damageable, making the fight impossible.

**What should happen:**

Adds should be clearable, making Onyxia switch phases, and making her killable/lootable.

**Comment by Rushor** [comment]
fixed with next update

![I](https://i.imgur.com/0s8kEKC.jpg)
