### ISSUE TITLE
[ITEM] Gnomish X-Ray Scope

### ISSUE THREAD

**Issue by Sessh097** [WoWManiaUK/Blackwing-Lair#2817]
**Links:**

https://www.wowhead.com/item=59594/gnomish-x-ray-scope

**What is happening:**

It's says sometimes to proc that attack power buff, but for every shot u gain the buff, it doesn't stack but u got it always.

**What should happen:**

Use: Attaches a permanent scope to a bow or gun that sometimes increases ranged attack power when dealing damage with ranged attacks.

**Comment by Rushor** [comment]
chance and cooldown added for lots of spellprocs

(91193, 91048, 92234, 92105, 91811, 92350, 92125, 91031, 92326, 92127, 92353, 91025, 92322, 91817, 92346, 91011, 92319, 92236, 92356, 91186, 92333, 75174, 75177, 92054, 90886, 92209, 92207, 92095, 92097, 90990, 90993, 91148, 91150, 91361, 91365, 90998, 91003, 91137, 91140, 92180, 92185, 90897, 92070, 92164, 91822, 92343, 92114, 109995, 92054, 91142, 91144, 95713);

with next update
