### ISSUE TITLE
[Quest] Pay it Forward - ID 25936 - Kelp'thar Forest

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2818]
**Links:**
Quest: https://www.wowhead.com/quest=25936/pay-it-forward
NPC: https://www.wowhead.com/npc=41672/drowning-warrior

**What is happening:**
The drowning warriors are missing. You can´t complete the quest.
![Pay it forward - how it is](https://user-images.githubusercontent.com/18005338/61629209-86e00680-ac84-11e9-9b26-2774a7c61543.png)

**What should happen:**
There should be a lot of drowning warriors in the water, which you need to rescue for the quest.
![Pay it forward - how it should be](https://user-images.githubusercontent.com/18005338/61629208-86477000-ac84-11e9-9df3-7806a0d20907.png)
![Drowning Warrior](https://wow.zamimg.com/uploads/screenshots/small/175702.jpg)

**Comment by Rushor** [comment]
fixed kredit and phasing with next update

![I](https://i.imgur.com/Ymqp60Q.jpg)
![I](https://i.imgur.com/igidufX.jpg)
