### ISSUE TITLE
[Dungeon] Throne of Tides - Lady Naz'Jar

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2819]
**Links:**

https://www.wowhead.com/npc=40586/lady-nazjar

**What is happening:**

Water Tornado are going way to slow, resulting in a big amount of tornados

**What should happen:**

Water Tornado's speed should be higher in order to hit walls faster and depop.

https://puu.sh/DW0w4/c60cf41f75.jpg

**Comment by Keader** [comment]
Note to self: Get sniff with 48571 :)

**Comment by Keader** [comment]
Tested speed value is blizzlike.
