### ISSUE TITLE
[Profession] Enchanting level

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2820]
**What is happening:**

Managed to get to lvl 545/545 in enchanting (535 should be maximum for Blood Elf, but when I did the Darkmoon Faire quest I got to lvl 545/545

https://puu.sh/DW5zf/33bdc587ab.png

**What should happen:**

535 should be the maximum for a Blood Elf, and 525 without this race

**Comment by Rushor** [comment]
well that is only cosmetic i think - closed for know
