### ISSUE TITLE
[Profession] Archaeology - Fossil Nodes

### ISSUE THREAD

**Issue by Lerixo** [WoWManiaUK/Blackwing-Lair#2821]
**Links:**
No Link needed.

**What is happening:**

If you gather fossil nodes through Archaeology, you can open them if you find them in an Arch area, but you wont recieve any fragments, thus making Fossil Nodes obsolete. Fossil atm is just a tax to spawn new, gatherable nodes.

**What should happen:**

Gathering Fossil fragments should work like every other "Race" in Archaeology. You should get fragments out of every find, an also get some Projects out of it.

**Comment by Sammy974** [comment]
#2166

**Comment by Rushor** [comment]
closed because duplicate
