### ISSUE TITLE
[Quest/Profession] Potion Master - ID 29067

### ISSUE THREAD

**Issue by Lerixo** [WoWManiaUK/Blackwing-Lair#2824]
**Links:**
Actual Wowhead link is a new Alchemy Quest, so i added this library:
https://cata-twinhead.twinstar.cz/?quest=29067

**What is happening:**
The quest cant be turned in: Have all materials, cant hit continue in the Quest window.

![image](https://user-images.githubusercontent.com/52600303/61705207-a55a0680-ad45-11e9-9759-8119f363addd.png)

**What should happen:**
Quest should be completeable, giving the players Alchemist profession a chance to proc extra potions while crafting.

**Notes**
I think this counts for all 3 specialisations of Alchemy. Currently no Specialisation is achieveable, which is a huge deal if you want to craft Potions, Flasks, or Transmutes in bulk.

**Comment by Echinaceax** [comment]
@Rushor @wow-mania - could have something to do with this fix #191

**Comment by Rushor** [comment]
![I](https://i.imgur.com/NKxzhf2.jpg)

retaking should fix it or just call a gm :)
