### ISSUE TITLE
[Grim Batol] General Umbriss - Ability

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2827]
**Links:**

https://fr.wowhead.com/npc=39625/général-umbriss

**What is happening:**

General Umbriss doesn't recast his spell 'Summon Skardyn' if one of the troggs is still alive (I.E Crowd control).

**What should happen:**

He should periodically call them, according to Dungeon Journal 

https://puu.sh/DWqKU/2097745cd1.png

**Comment by Rushor** [comment]
https://gotwarcraft.com/guide-to-heroic-grim-batol/

> Control the Malignant Trogg. The Trogg is the key. No more Malignant Troggs will spawn if the first one is alive.

Intended mechanic
