### ISSUE TITLE
[Resto/Shaman] Mastery

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#2828]
**What is happening:**
https://imgur.com/GXD1RmW ( min hp gain )
https://imgur.com/EJJQcai ( max hp gain )
**What should happen:**
Ancestraol Vigor should go around 20-30k hp gain

**Comment by Keader** [comment]
Wrong.
Resto shaman mastery potency DIRECT HEALS.
Ancestral Vigor is not a Direct heal.
