### ISSUE TITLE
[Quest] The Scent of Battle - ID 27811 - Twilight

### ISSUE THREAD

**Issue by ghost** [WoWManiaUK/Blackwing-Lair#283]
Quest - https://www.wowhead.com/quest=27811/the-scent-of-battle
NPC - https://www.wowhead.com/npc=46812
Can speak with the required NPC griffon - https://www.wowhead.com/npc=46968/mullan-gryphon however nothing happens because the item https://www.wowhead.com/item=62592/charred-highland-birch doesn't work.

**Comment by Druhl** [comment]
Confirmed, issue remains, as described at top.

**Comment by mfranca0009** [comment]
Reference video: https://www.youtube.com/watch?v=2L2dL0BJy80

**Comment by mfranca0009** [comment]
So far, fixed the normal Mullan Gryphons sitting around the area as well as the Mullan Gryphons bound by twilight binders.

Just need to fix the injured Mullan Gryphons, which will give quest credit and fly away if a healing spell is used or first aid (Embersilk Bandages or higher).

**Comment by mfranca0009** [comment]
All set, needs testing in PTR 👍 

### Mullan Gryphon standing around
Gossip to click on for the gryphon to smell quest item (charred highland birch) 

### Mullan Gryphon bound by twilight bindings
Each twilight binding needs to be destroyed (total of 4)

### Injured Mullan Gryphon
Requires a healing spell from the Holy School family or Nature School family. You can also use Embersilk Bandages, Dense Embersilk Bandages, or Heavy Embersilk Bandages.

**Comment by mfranca0009** [comment]
Hammer confirmed this fix, it's working as it should 👍
