### ISSUE TITLE
[Dungeon/mobs] Halls of Origination / Void Sentinel 

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#2830]
**Links:**
![Screenshot_9](https://user-images.githubusercontent.com/52254524/61754397-b9404f80-adbb-11e9-986f-c50540ef5954.png)

from WoWHead or our Armory

**What is happening:**

The mobs spawned from Chaos Portals from Setesh in Halls of Origination don't despawn after Setesh being killed. 

**What should happen:**

Mobs should despawn after boss is killed.

**Comment by Rushor** [comment]
an action now happen on evade and kill which will reset the portals and despawn the summoned added.

live with next update.
