### ISSUE TITLE
[Raid] Portal to The Frozen Throne - Icecrown Citadel

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2831]
**What is happening:**
When you take the portal to get to the Lich King you fall down and die.

**What should happen:**
You should appear on the platform of the Frozen Throne.

P.S.: Some player has been able to get up to the platform after log out and clear cache.

**Comment by Rushor** [comment]
teleport position adjusted

![I](https://i.imgur.com/Ski6KQ2.jpg)
