### ISSUE TITLE
[Item] Hope Ender - ID 30733

### ISSUE THREAD

**Issue by Lerixo** [WoWManiaUK/Blackwing-Lair#2832]
**Links:**
https://www.wowhead.com/item=30733/hope-ender
from WoWHead or our Armory

**What is happening:**
"Hope Ender"'s appearance isn't applieable to another sword through the Transmogrifier.

**What should happen:**

Like a normal sword, Hope Ender's appearance should be applieable on any other sword.

**Comment by Rushor** [comment]
client side issues - no fix from server side
