### ISSUE TITLE
[Boss] The Lich King - Icecrown Citadel (10nm)

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2833]
**Links:**
https://www.wowhead.com/npc=36597/the-lich-king
from WoWHead

**What is happening:**
Phase one: the boss is in "evade" if tanked close to the portal.
First interphase: it works fine.
Phase two: the boss stuck in evade in the middle of the platform. He can't be taunted or moved from his position. He does not call the valkyries. The other mechanics seems to be fine.

**What should happen:**
The boss should be attackable in all the platform.

P.S.: In wowhead the ability Summon Val'kyr is listed only in the 10hc, but he should do it in every difficulty... or not?
https://www.wowhead.com/spell=69037/summon-valkyr

**Comment by Rushor** [comment]
depending on the amount of players. the script was difficult in wotlk

**Comment by Rushor** [comment]
general gameobject issue
