### ISSUE TITLE
[Quest] A Distracting Scent - ID25215 - Shimmering Expanse

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2836]
**Links:**
https://www.wowhead.com/quest=25215/a-distracting-scent
from WoWHead

**What is happening:**
There are no Zin'jatar Raiders corpses outside the cave.

**What should happen:**
Drag 3 Dead Zin'jatar Raiders into the open water over Glimmerdeep Gorge to the south.
Just dive back into the water and you will see dead naga all over the place. Right clicking on one will attach a rope to the corpse enabling you to tow it away. Just tow the corpse due south over to the Glimmerdeep Gorge.

**Comment by Rushor** [comment]
all added. raiders are there, they will follow you and if you bring them to the area Glimmerdeep Gorge they will give credit and despawn

![I](https://i.imgur.com/IALTKzL.jpg)
![I](https://i.imgur.com/Bjb0GDa.jpg)
