### ISSUE TITLE
[Quest] Don't be Shellfish - ID 25219 - Shimmering Expanse

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2837]
**Links:**
https://www.wowhead.com/quest=25219/dont-be-shellfish
from WoWHead 

**What is happening:**
Snails are no lootable so the quest items can't be collected.

**What should happen:**
You should be able to loot the snails in order to get the quest items and complete the quest.

**Comment by Rushor** [comment]
fixed with next update

![I](https://i.imgur.com/a4JyRVc.jpg)
![I](https://i.imgur.com/vuzXLnr.jpg)
