### ISSUE TITLE
[Profession/Zones] The Herb Spawn Dilemma

### ISSUE THREAD

**Issue by Lerixo** [WoWManiaUK/Blackwing-Lair#2838]
**Links:**
No links needed.
from WoWHead or our Armory

**What is happening:**
After recent patching every Cataclysm zone feels empty in terms of Herb spawns. Ive traveled whole Hyjal for example: I found 7 Stormvein nodes, and ZERO Cinderbloom spawns. Deepholm exactly the same. No Cinder there too. You cant just gather anything right now. This is definetly **not blizzlike.** I mean how should one now stack up on Volatile Life, or for Potions any herb combinations needed? It's impossible for Scribes and Alchemists rn.

**What should happen:**

Herb nodes should have a normal spawnrate and quantity on each of the cataclysm Maps.

**Comment by Rushor** [comment]
yes we work always on it, it will be improved every update a bit. we need you feedback of course.

with next update every zone should have around 40-50 spawns active at same time. will even work more on it now with eirolla.

**Comment by Lerixo** [comment]
Alright! Sounds good. I'd say it would be a good idea to announce it on our discord, so people can test and give feedback :)

**Comment by Rushor** [comment]
alright

**Comment by Jimpaa** [comment]
@Rushor There is still no Cinderblooms in Mount hyjal. I have been looking for cinderblooms there and i cant find any. Deepholm got a few so does Twilight highlands but not much.
