### ISSUE TITLE
[Dungeon/Quest] [Soften them up] - Grim Batol

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#2839]
**Links:**
https://www.wowhead.com/quest=28852/soften-them-up
from WoWHead or our Armory

**What is happening:**

The quest doesn't count the slained mobs from the Red Drake. 

**What should happen:**

Quest should count the slained mobs from the Red Drake

**Comment by Rushor** [comment]
killcredit for troggs and minions added (only to those with scripts. may not all but it will be easy to get the quest completed.

![I](https://i.imgur.com/RyYWLJT.jpg)

**Comment by Denrunmt** [comment]
Cool
