### ISSUE TITLE
[NPC] Eoin Dunwald -46175-   (Missing) - Twilight Highlands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#284]
NPC - https://www.wowhead.com/npc=46175
quest - https://www.wowhead.com/quest=27644/eoin-dunwald
NPC - https://www.wowhead.com/npc=46177
Is not in the correct place/ missing

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/61536480-a977e280-aa2c-11e9-826d-4a06ea42df59.png)

**Comment by Druhl** [comment]
Still an issue, NPC not at location.

_Also:_
The "action line" in the quest details and in the objectives list is in French.

![WoWScrnShot_011320_170634](https://user-images.githubusercontent.com/19803911/72296200-14465700-3627-11ea-9280-d6d89293b578.jpg)

**Comment by Echinaceax** [comment]
Comfirmed not fixed i checked myself on live server

**Comment by Rushor** [comment]
available with next update
