### ISSUE TITLE
[NPC/Rare] Poseidus - ID 50005

### ISSUE THREAD

**Issue by Lerixo** [WoWManiaUK/Blackwing-Lair#2840]
**Links:**
https://www.wowhead.com/npc=50005/poseidus
from WoWHead or our Armory

**What is happening:**
Camping his spawns solo for what feels like days, it seems Poseidus isnt in the game.

**What should happen:**

Poseidus should have a spawn, and according spawning time.

**Comment by Rushor** [comment]
yes it was removed

**Comment by Rushor** [comment]
spawn, ai and 4 pool points with 110 hours respawntime added 

![I](https://i.imgur.com/vD8abbH.jpg)
![I](https://i.imgur.com/0A7Ei0s.jpg)

**Comment by Lerixo** [comment]
Nice.

**Comment by Rushor** [comment]
will be fixed with next update, that poseidus is visible
