### ISSUE TITLE
[Guild perk] Mobile Banking

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#2843]
**Links:**
https://www.wowhead.com/spell=83958/mobile-banking
![Screenshot_1](https://user-images.githubusercontent.com/52254524/61889662-7e9afc00-af0e-11e9-828b-fb50b7254ada.png)
![Screenshot_2](https://user-images.githubusercontent.com/52254524/61889667-8195ec80-af0e-11e9-95c5-258405f462de.png)
![Screenshot_3](https://user-images.githubusercontent.com/52254524/61889677-83f84680-af0e-11e9-8265-c03dfab9e8e9.png)

from WoWHead or our Armory

**What is happening:**

The guild perk "Mobile Banking" goes to the spell bar every time I log in my fresh character. It continues going there even when I've already removed it few times from the bar. This happens until the bar is full of spells, then it stops going there.

**What should happen:**

The guild perk "Mobile Banking" should go to the spell bar only 1 time when a new guild is joined (only if your bar still has some free space so the perk could get into some of the free squares of the bar) or a fresh character. Once it's removed from the spell bar, the perk shouldn't want to get into the spell bar again.

**Comment by Rushor** [comment]
this is too general could you inspect @Keader?

**Comment by Keader** [comment]
I cant reproduce.
Working fine here.
