### ISSUE TITLE
[Therazane] D'lom the Collector <Therazane Quartermaster>

### ISSUE THREAD

**Issue by Nirvanum** [WoWManiaUK/Blackwing-Lair#2844]
**Links from WoWHead or our Armory:**
https://www.wowhead.com/npc=45408/dlom-the-collector#comments

**What is happening:**
Completing _At the Stonemother's Call_ at Therazane and reaching _friendly reputation_, grants you access to D'lom the Collector Therazane Quartermaster. 
D'lom's shop stay close.
![Q](https://user-images.githubusercontent.com/52670055/61894705-4a750a80-af11-11e9-99d3-252fbbfd631e.jpg)

**What should happen:**
D'lom open the shop.

**Comment by Rushor** [comment]
fixed with next update

![I](https://i.imgur.com/sBZjGpL.jpg)
