### ISSUE TITLE
[DK/Spells] Blood Worms heal scale

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Blackwing-Lair#2848]
Fixed.
Accourding spell 81277 Blood Gorged (casted by blood worms)
Heal should scale 10% of worm health. It can scale each time that worm do a sucessfull melee attack (adding +10%)

> Description: The Bloodworm grows engorged with the blood leeched from its enemies, giving it an increasing chance to burst, healing nearby allies.
> 
> ToolTip: Engorged with blood.
> May burst, healing nearby allies for $s2% of its maximum health.
> 
> $s2% = 10%
> 
> Stackable up to 99

**Comment by Dranah** [comment]
The stacks are now added and everything scales (worm damage, health, healing per stack).
The only problem is that the healing burst happens on every single stack being added to the worm. Basically they heal on every attack.

**How it should work:** The healing should only occur when the worm bursts, approx between 8-10 stacks at random. The worm heals every target within 15 yards for the burst amount and despawns.

**How it works atm:** Every time the worm attacks and gains a stack of blood gorge, they heal for the correspondant amount. Keeps healing on every attack until it actually bursts and despawns at around 8-10stacks.
