### ISSUE TITLE
[NPC] Donnelly Dunwald - phasing issue - Twilight Highlands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#285]
NPC - https://www.wowhead.com/npc=46176
Quest - https://www.wowhead.com/quest=27643/donnelly-dunwald
NPC- https://www.wowhead.com/npc=46177
NPC is not in the required place.

**Comment by Eirolla** [comment]
(NPC: 27643) is phased.
![image](https://user-images.githubusercontent.com/26048748/62368034-0ba80b80-b534-11e9-9ae7-000b7a780abe.png)

**Comment by Rushor** [comment]
visble now
