### ISSUE TITLE
[Quest] A Blade Fit For A Champion

### ISSUE THREAD

**Issue by Austerror** [WoWManiaUK/Blackwing-Lair#2850]
**Links:**
https://www.wowhead.com/quest=13673/a-blade-fit-for-a-champion

**What is happening:**
Everything works up until the maiden appears (from kissing the frogs) but she does not give the blade.

**What should happen:**
Upon the maiden appearing and the player talking to her, she should give the Ashwood Brand https://www.wowhead.com/item=44981/ashwood-brand

**Comment by Rushor** [comment]
fixed. you have now a 10 percent chance that the frog transforms in the maiden. talk to her then after few seconds and you will get the item on gossip select.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/6UaNgfj.jpg)
![I](https://i.imgur.com/ySc1oyX.jpg)
