### ISSUE TITLE
[NPC] Earthcaller Yevaa - ID 42573 - quest interaction (issue 1)  - Deepholm

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2851]
**Links:**
NPC: https://www.wowhead.com/npc=42573/earthcaller-yevaa
Alliance Quest: https://www.wowhead.com/quest=27952/the-explorers
Horde Quest: https://www.wowhead.com/quest=27953/the-reliquary

**What is happening:**
She offers a horde quests for alliance and i believe alliance quest for horde players.
![Earthcaller Yevaa - how it is 1](https://user-images.githubusercontent.com/18005338/61947050-74c3d800-afa4-11e9-8a33-e39352aad03e.png)

**What should happen:**
She should not offer other faction quest.
![Earthcaller Yevaa - how it should be 1](https://user-images.githubusercontent.com/18005338/61947053-75f50500-afa4-11e9-82c1-c4c19d6d2e43.png)

![Earthcaller Yevaa - how it should be 4](https://user-images.githubusercontent.com/18005338/61947410-66c28700-afa5-11e9-9b43-e6c00002dbdb.png)

**Comment by Rushor** [comment]
team condition added

![I](https://i.imgur.com/xigki1J.jpg)
![I](https://i.imgur.com/1hk8t1o.jpg)
