### ISSUE TITLE
[NPC] Earthcaller Yevaa - ID 42573 - missing quest (issue 2) - Deepholm

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2852]
**Links:**
NPC: https://www.wowhead.com/npc=42573/earthcaller-yevaa
missing Quest: https://www.wowhead.com/quest=26409/wheres-goldmine

**What is happening:**
She is not offering the quest Where's Goldmine.
![Earthcaller Yevaa - how it is 1](https://user-images.githubusercontent.com/18005338/61947276-12b7a280-afa5-11e9-964a-eb96f075b605.png)

**What should happen:**
She should offer the Quest Where's Goldmine.
![Earthcaller Yevaa - how it should be 2](https://user-images.githubusercontent.com/18005338/61947272-10554880-afa5-11e9-8204-ae763d4ac75e.png)

![Earthcaller Yevaa - how it should be 3](https://user-images.githubusercontent.com/18005338/61947327-34188e80-afa5-11e9-83a5-912ec3c554a8.png)

**Comment by Rushor** [comment]
prev quest https://wowwiki.fandom.com/wiki/Quest:Where%27s_Goldmine%3F needed

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/63456944-48d72d80-c450-11e9-99b7-4bd1b5e0fa54.png)
