### ISSUE TITLE
[NPC] Captain Taylor - ID 39887 - missing (phasing) - Kelp'thar Forest

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2853]
**Links:**
NPC: https://www.wowhead.com/npc=39887/captain-taylor
Recovering Soldier: https://www.wowhead.com/npc=40664/recovering-soldier
Quest: https://www.wowhead.com/quest=25405/rest-for-the-weary

**What is happening:**
After turning in the quest [Pay it forward](https://www.wowhead.com/quest=25281/pay-it-forward) you don´t see new NPCs. You should be able to see Captain Taylor and Revovering Soldier, because you need the captain for the Quest "rest for the weary"
![Captain Taylor - how it is](https://user-images.githubusercontent.com/18005338/61953643-3c79c500-afb7-11e9-9462-f77229473284.png)

**What should happen:**
After turning in the quest [Pay it forward](https://www.wowhead.com/quest=25281/pay-it-forward) you should phase and see other NPCs. For reference: #2818 

Before turning in the quest:
![Captain Taylor - how it should be 1](https://user-images.githubusercontent.com/18005338/61953644-3c79c500-afb7-11e9-8bea-cc162061421e.png)

After turning in the quest:
![Captain Taylor - how it should be 2](https://user-images.githubusercontent.com/18005338/61953646-3d125b80-afb7-11e9-8c5c-8468c783ad5f.png)

Captain Tylor is available now:
![Captain Taylor - how it should be 3](https://user-images.githubusercontent.com/18005338/61953642-3c79c500-afb7-11e9-8ceb-86d5121e7ff5.png)

**Comment by Rushor** [comment]
![I](https://i.imgur.com/gtMConZ.jpg)
