### ISSUE TITLE
[Item] Fortune Cookie

### ISSUE THREAD

**Issue by patrico08** [WoWManiaUK/Blackwing-Lair#2855]
Link:
https://www.wowhead.com/item=62649/fortune-cookie

Whats wrong:
Atm, fortune cookie doesnt give any bonus, like str for my fury or mastery for protection, u dont get +90stamina and also, u dont get random fortune card on Use.

How it should be working:
On use, u should get +90 to ur higher stat, +90stamina and random fortune card in ur bag.

**Comment by Rushor** [comment]
card creation will be fixed later. stat part fixed now.

![I](https://i.imgur.com/T4Q3dhA.jpg)
![I](https://i.imgur.com/6lBZNcI.jpg)
