### ISSUE TITLE
[Dungeon] Vortex-Teleport - The Vortex Pinnacle

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2856]
**Links:**
https://www.wowhead.com/the-vortex-pinnacle
from WoWHead

**What is happening:**
The vortex that make you change platform are no working, so is impossible to continue the dungeon after the first boss.

**What should happen:**
The vortex should teleport you to the next platform.

**Comment by kDracku** [comment]
Can confirm , not working

**Comment by Rushor** [comment]
vehicle related issue. will be fixed tomorrow
