### ISSUE TITLE
X-53 Touring Rocket passenger seat

### ISSUE THREAD

**Issue by achyles22** [WoWManiaUK/Blackwing-Lair#2858]
**Links:**
https://www.wowhead.com/item=54860/x-53-touring-rocket

**What is happening:**
Passenger seat cannot be used from now (atleast on X-53 Touring Rocket from shop). I was using it yesterday (7/27/2019) and it was okay, so it has to be some patch that was deployed from yesterday onwards.

**What should happen:**
Party member should take passsenger seat when click on it and it is free.

**Comment by Sammy974** [comment]
Confirmed. Relogging-reloading-regrouping doesn't work.

**Comment by gamer100** [comment]
I have  checked  with  player. the arrow is there,to jump on, but is not working
