### ISSUE TITLE
[Boss] Ozumat - Not Coming - Throne of the Tides

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2866]
**What is happening:**
In the last phase, Ozumat doesn't come closer and he's not attackable.

**What should happen:**
Ozumat should come closer in order to be killed.

**Comment by fuzzydunlop** [comment]
Just tried it twice and can confirm this happening.

**Comment by Rushor** [comment]
fixed tomorrow with all other vehicle related issues
