### ISSUE TITLE
[Quest] Something brewed - ID 28409- Twilight Highlands

### ISSUE THREAD

**Issue by ghost** [WoWManiaUK/Blackwing-Lair#287]
quest - https://www.wowhead.com/quest=28409/something-brewed
NPC - https://www.wowhead.com/npc=48367
npc required to speak with - https://www.wowhead.com/npc=48758/hammelhand
You can speak with him but he doesn't have the dialog needed to complete the quest.

**Comment by Eirolla** [comment]
![image](https://user-images.githubusercontent.com/26048748/62368218-ad2f5d00-b534-11e9-8500-137dc481bf79.png)
(NPC: 48367) interaction is empty.

**Comment by Rushor** [comment]
@Bathelmo when do you finally wanna add your fixes?

**Comment by mfranca0009** [comment]
Needs testing in PTR for:

Quest being done by group
Quest being done solo
Quest being done by two players (at least) solo

**Comment by Echinaceax** [comment]
Update 
Something happened to the fix

**Comment by Echinaceax** [comment]
Better now ❤️ uploaded live tomorrow

![conf1](https://user-images.githubusercontent.com/39439201/90504608-a1b7cf80-e151-11ea-8faa-5b61b8415836.jpg)
