### ISSUE TITLE
[Quest] Rundown - Quest ID 25221 || Item 

### ISSUE THREAD

**Issue by fuzzydunlop** [WoWManiaUK/Blackwing-Lair#2871]
**Links:** 
quest: https://www.wowhead.com/quest=25221/rundown
Item: https://www.wowhead.com/item=54466/toshes-hunting-spears

**What is happening:** The item (Toshes Spears) you're given to impale the naga, will damage you instead (see screenshot below).

**What should happen:** you should be able to impale the naga and not kill yourself with it. (also be able to use from a mount/seahorse but as that isn't working yet either..^^) 

![Naamloos](https://user-images.githubusercontent.com/14002052/62004599-60f4af00-b127-11e9-815d-cf554f8f6aac.jpg)

**Comment by Rushor** [comment]
![I](https://i.imgur.com/arKZk7a.jpg)
![I](https://i.imgur.com/qsiVjaH.jpg)

text added and only targets the nagas now
