### ISSUE TITLE
[Zone] Vashj'ir - Dying (as horde) ghost in Northern Barrens

### ISSUE THREAD

**Issue by fuzzydunlop** [WoWManiaUK/Blackwing-Lair#2872]
**What is happening:** When you die in Vashj'ir as horde, you will get out as a ghost in Northern Barrens, next to crossroads.

**What should happen:**
You should release at the spirit healer in Shimmering expanse. (https://cata-twinhead.twinstar.cz/?npc=6491)

**Comment by Rushor** [comment]
okay should no longer be removed on ground only on map switch

![I](https://i.imgur.com/S2Df6pA.jpg)

**Comment by Rushor** [comment]
same happens with alliance (only teleport is changed to westfall)

**Comment by Rushor** [comment]
dying anywhere in vash will now teleport you correctly in the ghostzones

![I](https://i.imgur.com/AL15ip0.png)
![I](https://i.imgur.com/t9d4YjU.jpg)
