### ISSUE TITLE
[Quest] Signal the Attack - quest ID 

### ISSUE THREAD

**Issue by fuzzydunlop** [WoWManiaUK/Blackwing-Lair#2873]
**Links:**
https://www.wowhead.com/quest=27590/signal-the-attack
from WoWHead 

**What is happening:** Nothing, the item/quest is not registering that you are on top of one of the two towers, making it unable to complete

**What should happen:** When you use the item you can complete it (see video below)
https://www.youtube.com/watch?v=vL1UKQD3Wgw

**Comment by Rushor** [comment]
![I](https://i.imgur.com/9W3tl2G.jpg)

in phase 169
