### ISSUE TITLE
[Quest] Beer run - Twilight daily - ID 28864- Twilight Highlands

### ISSUE THREAD

**Issue by ghost** [WoWManiaUK/Blackwing-Lair#288]
Quest - https://www.wowhead.com/quest=28864/beer-run
npc - https://www.wowhead.com/npc=46591
The NPC required to speak with is npc - https://www.wowhead.com/npc=48758/hammelhand however he doesn't have the require speech bubble to speak with him to complete the quest.

**Comment by mfranca0009** [comment]
This quest is the exact same and replica of "Something Brewed"  ( #287 ), the only difference is its a daily quest. 

Will make changes necessary to fix shortly.

**Comment by mfranca0009** [comment]
Needs testing in PTR

**Comment by Echinaceax** [comment]
retested 

![conf3](https://user-images.githubusercontent.com/39439201/90506125-0e33ce00-e154-11ea-90f2-104615656a7c.jpg)
