### ISSUE TITLE
Arcane potency not working at all

### ISSUE THREAD

**Issue by Asherdoom** [WoWManiaUK/Blackwing-Lair#2880]
**Links:**

from WoWHead or our Armory
https://wowwiki.fandom.com/wiki/Arcane_Potency

**What is happening:**

The talent proc is not happening under any circumstance

**What should happen:**
after getting clearcast you should get arcane potency buff but this never happens. Tested into training dummy etc,,, nothing of nothing.

**Comment by Asherdoom** [comment]
check the image link with talent and clearcast proc. 

[https://imgur.com/a/amFBMgB](url)

**Comment by Sammy974** [comment]
I can confirm that.

**Comment by Sammy974** [comment]
#41

**Comment by Rushor** [comment]
so adding label class
