### ISSUE TITLE
[NPC/Rare] Armagedillo - NPC ID 50065

### ISSUE THREAD

**Issue by fuzzydunlop** [WoWManiaUK/Blackwing-Lair#2888]
**Links:**
Armagedillo: https://www.wowhead.com/npc=50065/armagedillo
Drop: https://www.wowhead.com/item=67243/armagedillos-tail

**What is happening:** This mobs seems to be missing. I've been checking his spawn location for several days, if not weeks now. Asking in the worldchat also leads to 0 responses if anyone has ever seen him.

**What should happen:** The mob should be near the bones near 45:42 in Uldum, as shown in the wowhead page.

**Comment by Rushor** [comment]
will be fixed all here https://github.com/WoWManiaUK/Blackwing-Lair/issues/2938
