### ISSUE TITLE
[Quest] Eye Spy-item missing - ID 28244- Twilight Highlands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#289]
Quest - https://www.wowhead.com/quest=28244/eye-spy
NPC - https://www.wowhead.com/npc=48010
item - https://www.wowhead.com/npc=47252/eye-of-twilights-vision
No  eye to peer into therefore cannot complete the quest

**Comment by Rushor** [comment]
cinematic, and quest kill credit and spawn must be added

**Comment by Rushor** [comment]
![](https://i.imgur.com/cGGqSh5.png)
![](https://i.imgur.com/Fhmltjr.jpg)
