### ISSUE TITLE
[Quest]- Scouting the sinkholes. [Location]- The geyser fields, Borean Tundra, Northrend

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Blackwing-Lair#2892]
**Links:** Quest: https://www.wowhead.com/quest=11684/scouting-the-sinkholes
Quest item: https://www.wowhead.com/item=34920/map-of-the-geyser-fields

**What is happening:** The position for taking the reading is a bit off, and it shows an error when trying to take the reading directly inside the sinkhole. After finding a suitable place where the reading can be taken just outside of the sinkhole, it shows the error -" you have no target".

**What should happen:**: the player should be able to use the quest item anywhere near or on the proximity of the sinkhole and it should  never show the error- " you have no target".

![WoWScrnShot_072919_172037](https://user-images.githubusercontent.com/43633844/62047128-4e619f00-b227-11e9-8844-e9149a60addb.jpg)

![WoWScrnShot_072919_173441](https://user-images.githubusercontent.com/43633844/62047134-51f52600-b227-11e9-8782-863f2295243b.jpg)

**Comment by festerhowl** [comment]
Edit: The reading can be taken if you stand very close to the ledge, after finding the suitable position. If u are even half a yard off of the ledge it will show the above mentioned error.

![WoWScrnShot_072919_174111](https://user-images.githubusercontent.com/43633844/62047450-29216080-b228-11e9-87cc-82194e67c8f8.jpg)

![WoWScrnShot_072919_174114](https://user-images.githubusercontent.com/43633844/62047467-2f174180-b228-11e9-9688-21fb4da71ca8.jpg)

![WoWScrnShot_072919_174117](https://user-images.githubusercontent.com/43633844/62047482-376f7c80-b228-11e9-8a2f-bdd6e025dc7d.jpg)

**Comment by Rushor** [comment]
range must be increasded to around 50 yards

**Comment by Rushor** [comment]
![I](https://i.imgur.com/84jen1r.jpg)
