### ISSUE TITLE
[Quest] Burn It Up... For the Horde!

### ISSUE THREAD

**Issue by Asherdoom** [WoWManiaUK/Blackwing-Lair#2893]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=10087/burn-it-up-for-the-horde
**What is happening:**

https://imgur.com/a/F0ZJYgD
no matter where you stand you cannot complete the quest.

**What should happen:**
you should be able to use torch quest item to burn the cannon down.

**Comment by Rushor** [comment]
okay fixed but remember that you need to stand here (very close to the big panzer)

![I](https://i.imgur.com/ed07sy9.jpg)
![I](https://i.imgur.com/MPfPf05.jpg)
