### ISSUE TITLE
Magister aledis floating in the air

### ISSUE THREAD

**Issue by Asherdoom** [WoWManiaUK/Blackwing-Lair#2895]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/npc=20159/magister-aledis
**What is happening:**

https://imgur.com/a/nPoYUGc

floaing in hellfire mid air lol this is awesome

**What should happen:**
look wowhead. he should patrol MAIN road and not float in the air.

**Comment by Rushor** [comment]
waypoints improved
