### ISSUE TITLE
Riding training not persisitng between spellbook, trainer, and player.

### ISSUE THREAD

**Issue by budthechud** [WoWManiaUK/Blackwing-Lair#2898]
**Links:**
Apprentice riding post 20 still needs to be bought from trainer: https://i.imgur.com/jlUBi9a.png
Apprentice riding not learned in spell book: https://i.imgur.com/cx4SzzJ.png
from WoWHead or our Armory
https://www.wowhead.com/spell=33388/apprentice-riding
**What is happening:**
Was awarded Apprentice Riding at 20.  Able to use mount fine but riding trainers are showing the only available skill to be purchased as Apprentice riding.  When I attempt to purchase the apprentice riding nothing happens.  Spell book also now shows, after relog and cache clear, that I do not have Apprentice at all.

**What should happen:**
Apprentice riding awarded at 20, next in line to be available at riding trainer, spell book reflecting apprentice riding learned.

**Comment by Rushor** [comment]
the spell not actually learned but only added until next relog. will fix that

**Comment by Rushor** [comment]
![I](https://i.imgur.com/nh7wKKM.jpg)
![I](https://i.imgur.com/0DnhIm6.jpg)

only works for the new created characters. The others may need to contact a gamemaster if the riding skill is missing 

(.cast 33389   on the player)

**Comment by budthechud** [comment]
Still appears I do not have apprentice: https://i.imgur.com/WZ8O7KV.png

**Comment by Rushor** [comment]
okay this is because of relog see https://github.com/WoWManiaUK/Blackwing-Lair/issues/2906
