### ISSUE TITLE
[Quest] Immolate and Arcane Missiles

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#29]
Quest ID 14274, 14281
Worgen warlock and mage starter quests.

Currently no credit is given for using Immolate on the target NPCs Bloodfang Worgen http://www.wowhead.com/npc=35118
Quests cannot be completed.

**Comment by fvicaria** [comment]
These quest ids are for Nova and Corruption

**Comment by fvicaria** [comment]
You are right. In any case, they are fixed now.
