### ISSUE TITLE
[NPC] Fanny Thundermar 48013 - missing - Twilight Highlands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#290]
NPC- https://www.wowhead.com/npc=48013
Quest - https://www.wowhead.com/quest=28369/my-sister-fanny
Obtained from - https://www.wowhead.com/npc=46591
NPC Fanny is not it the required location to complete this quest.

**Comment by Dranah** [comment]
NPC is there but looks like phasing issue.
You should be able to see her with https://www.wowhead.com/quest=28369/my-sister-fanny in your quest log.

**Comment by wow-mania** [comment]
As-is. NPC is visible only when appropriate quests are completed.
