### ISSUE TITLE
Living bomb and Impact talent.

### ISSUE THREAD

**Issue by Myivo** [WoWManiaUK/Blackwing-Lair#2900]
**Links:**
https://www.wowhead.com/spell=44457/living-bomb

**What is happening:**
After the spread via the Impact talent, it spread out the living bomb out of your main target

**What should happen:**
The living bomb should stay on the target that you are casted a fireblast (procced)

**Comment by Keader** [comment]
It's about max targets...
So, should spread for 2 more targets instead...
I will fix that.
