### ISSUE TITLE
[NPC]- Focus Wizard. [Location]- glittering strand, Dragonblight, Northrend.

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Blackwing-Lair#2903]
**Links:** NPC:  https://www.wowhead.com/npc=26816/focus-wizard

**What is happening:** The NPC's original state is dead and it is casting spells and attacking player while in that state. 
![WoWScrnShot_073019_070226](https://user-images.githubusercontent.com/43633844/62093754-19d9fb80-b298-11e9-8b01-185e3412ae83.jpg)

the player is able to attack and kill the npc, but is unable to loot it.
![WoWScrnShot_073019_070339](https://user-images.githubusercontent.com/43633844/62093833-5ad21000-b298-11e9-847d-9eaf0cfd032d.jpg)

**What should happen:** The npc's original state should be alive, and after it dies, the player should be able to loot the corpse.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/jOfxNvr.jpg)

alive again
