### ISSUE TITLE
Auction House is not working anywhere.

### ISSUE THREAD

**Issue by Fatality51** [WoWManiaUK/Blackwing-Lair#2905]
**Links:**

from WoWHead or our Armory

**What is happening:**

You can open the Auction up, but you can't purchase anything or cancel any of your own auctions.  This is for every auction for every player.  Everyone has been complaining in chat for hours, so I know it is wide spread.    Thank you

**What should happen:**

**Comment by Rushor** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/2257
