### ISSUE TITLE
Riding Trainer / druid trainer issue

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Blackwing-Lair#2906]
**Links:**

1.  Apprentice riding : https://www.wowhead.com/spell=33388/apprentice-riding
2. Journeyman riding:  https://www.wowhead.com/spell=33391/journeyman-riding
3. Expert riding:  https://www.wowhead.com/spell=34090/expert-riding

**What is happening:** I purchased riding training up to expert when i was in outland, as evident from the wind-rider that i am currently mounted on, but now when i am checking the trainers, it asks me to purchase all the training till expert once again, except for- " Flight master's license". This issue has persisted in all my characters and i ignored it previously thinking that i may have missed on the training.
![WoWScrnShot_073019_080425](https://user-images.githubusercontent.com/43633844/62096308-e18aeb00-b2a0-11e9-962c-2de6f36d183a.jpg)
![WoWScrnShot_073019_080434](https://user-images.githubusercontent.com/43633844/62096313-e3ed4500-b2a0-11e9-80a9-56ad1bfa1cc4.jpg)
![WoWScrnShot_073019_080436](https://user-images.githubusercontent.com/43633844/62096317-e780cc00-b2a0-11e9-9880-f929ba0382cd.jpg)

**What should happen:**

**Comment by Rushor** [comment]
okay fixed that.

https://i.imgur.com/ZYqNQPR.jpg

you know get those 3 spells as druid by default if you hit level 20, 40, 60. It will no longer be shown at the trainer

however after second relog the bug exists again :(

**Comment by Rushor** [comment]
also happens with the level 20 spells see https://github.com/WoWManiaUK/Blackwing-Lair/issues/2898

**Comment by Chicozoba** [comment]
I had this problem again with a reroll (Haroun) a few weeks ago.

**Comment by Echinaceax** [comment]
@Rushor any ETA on this ?

**Comment by Echinaceax** [comment]
new retest found new issue


- [ ] druid cant learn swift flight form lvl 60 (unavailble at druid trainer and grey out at riding trainer)
- [ ] druid cant learn swift flight form lvl 70 (cant click it)
https://wowwiki.fandom.com/wiki/Flight_Form
https://wowwiki.fandom.com/wiki/Swift_Flight_Form

![wont click](https://user-images.githubusercontent.com/39439201/64147717-8d37d580-ce21-11e9-977f-8782bfd9a058.jpg)


- [ ] cant learn Journeyman riding from druid trainer hence they cant learn https://www.wowhead.com/spell=33391/journeyman-riding

![can get](https://user-images.githubusercontent.com/39439201/64147768-c5d7af00-ce21-11e9-9a91-2935cf503166.jpg)

**Comment by Wojtek92** [comment]
have strange situation, I've already bought expert riding, then i had to bought it again before i could buy frost weather flying 
now when i want to buy artisian riding, again have to buy journeyman, expert and ther probably will be avialable artisian please help me I do not want to pay 3rd time 225+45g for same skill

my nick is Vanael

**Comment by Echinaceax** [comment]
@Wojtek92 its been an annoying bug this one for many, including my own druid.
i tested this a few days ago on DEV again, and what i found there was: the druids cant buy from the druid trainer the first 3 as it should be, therefor they have to buy from riding trainer, i relegged a few times to see if i unleaned them and the spells stayed, i didnt lose them. 

Now the question is, is it the same on live ? 
can you explain step by step what you do , which trainer, what race you are etc..
that way i can retest it

**Comment by Wojtek92** [comment]
@Echinaceax so from beginning,
- I've received voucher for apprentice reading - free of charge
- then I wanted to buy journeyman reading - i couldn't, had to buy firstly apprentice and then it was possible to buy journeyman
-next i wanted to buy expert - it was almost free of charge - with fly form druid was added
-then i wanted to buy kalimdor cold weather flying (this one for nothrend) I couldn't - had to buy again journeyman and expert! (I really do not remember if i should buy apprentice or not)
- now when i want to buy artisan once again have to buy all previous already bought skills :(

**Comment by Echinaceax** [comment]
@Wojtek92 which trainer was it ?

**Comment by Echinaceax** [comment]
update : 
Been retested by Chicozoba and confirms this issue is fixed 

WHOOO HOOO

**Comment by Rushor** [comment]
Nice

**Comment by Kuro2004** [comment]
Just had this happen to me. Already had Apprentice and Journeyman riding and went to train Expert and Flight master's license to find out that previous requirements were back.

**Comment by Echinaceax** [comment]
@Rushor indeed this needs sorting once and for all, i'll retest this when i can

**Comment by Echinaceax** [comment]
Retested @rushor and i cant get it to bug, 

1. Ive lvled 60 bought Apprentice Riding
2. lvled 70  bought Journeyman Riding 
3. relogged 3 times 

It wont bug atm, so im not sure what the issue can be now, launcher issue maybe, one player did say yesterday in game that it was a visual bug and that they could still use flight form regardless of the riding training saying they didnt have it anymore, so im not sure

**Comment by Echinaceax** [comment]
### Make sure your patched to 1.0.5 and using the launcher (righ click on the launcher.exe run as admin)
