### ISSUE TITLE
[Quest]- As Hyjal Burns [Location]- Moonglade

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Blackwing-Lair#2907]
**Links:** quest: https://www.wowhead.com/quest=25316/as-hyjal-burns
NPC:  https://www.wowhead.com/npc=39140/aronus

**What is happening:** Unable to mount Aronus after clicking on him. Repeated clicking spawns a large number of Aronus' but he just stays there.

**What should happen:** Should be able to mount Aronus after clicking once, and then he will give the player a ride to Mount Hyjal.

**Comment by Rushor** [comment]
will be fixed today

**Comment by Echinaceax** [comment]
Mounted without issue

![mounted fine](https://user-images.githubusercontent.com/39439201/65969252-c1280a00-e464-11e9-8345-71ce771cacd5.jpg)
