### ISSUE TITLE
[Dungeon/Boss] Dragha Shadowburner - Grim Batol

### ISSUE THREAD

**Issue by Sessh097** [WoWManiaUK/Blackwing-Lair#2908]
**Links:**

![WoWScrnShot_072819_015812](https://user-images.githubusercontent.com/51090018/62111368-50b80d80-b2a8-11e9-87f5-ad52312d014a.jpg)

**What is happening:**

Valiona doesn't join the fight when drahga is low life 

**What should happen:**

Valiona joins the fight when Drahga Shadowburner reaches 30% remaining health. She will fight with Drahga until she reaches 20% remaining health. when she ejects Drahga and leaves him to face the players alone.

**Comment by kDracku** [comment]
Can confirm

**Comment by Rushor** [comment]
vehicle issue. will be fixed today
