### ISSUE TITLE
Mobile Banking is crashing.

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#2909]
**Links:**

https://wow.gamepedia.com/Mobile_Banking

**What is happening:**

Mobile Banking is crashing client.

**What should happen:**

it should not crash

**Comment by Rushor** [comment]
try on dev. for me working again

(only works if you are in a guild)

**Comment by Eirolla** [comment]
I am playing in the live server and my guildmates are talking about mobile banking crash. when you try to use it, the client having a crash.

**Comment by Echinaceax** [comment]
@Rushor - fixed :) in dev 
![fixed bank](https://user-images.githubusercontent.com/39439201/62152899-c00f1b00-b303-11e9-9f4f-f4f1e90e29c4.jpg)
.

**Comment by Echinaceax** [comment]
@Rushor - indeed it does :)

![fixedd bank](https://user-images.githubusercontent.com/39439201/62153592-352f2000-b305-11e9-9ba7-62fde68a1282.jpg)
