### ISSUE TITLE
[Quest] Find Fanny - ID 28378 - Twilight Highlands

### ISSUE THREAD

**Issue by ghost** [WoWManiaUK/Blackwing-Lair#291]
Quest - https://www.wowhead.com/quest=28378/find-fanny
NPC -https://www.wowhead.com/npc=46591
missing NPC- https://www.wowhead.com/npc=48013/fanny-thundermar
Missing NPC fanny cannot be found in the cave to complete the quest.

**Comment by Dranah** [comment]
The fanny in this quest is an objective https://www.wowhead.com/npc=48489/find-fanny-quest-tracker
The quest cannot be completed.

**Comment by mfranca0009** [comment]
NPC is on PTR with entry id 48499 within the cave.

Should she have text dialog with Keegan Firebeard?

Also, she isn't located in the place the video is displaying. She is located on the ledge and not on the back of the cave.

https://www.wowhead.com/quest=28378/find-fanny#videos:id=116135

https://www.wowhead.com/npc=48364/keegan-firebeard

**Comment by Echinaceax** [comment]
Old tester report, tester isnt here anymore

**Comment by mfranca0009** [comment]
All set, needs testing in PTR 👍

**Comment by mfranca0009** [comment]
Confirmed by Consta
