### ISSUE TITLE
[Mage] Blink not working properly

### ISSUE THREAD

**Issue by Asherdoom** [WoWManiaUK/Blackwing-Lair#2912]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/spell=1953/blink
**What is happening:**

when you use blink in mid air or for example near an world object you blink but in the very same place

**What should happen:**

Blink should tele u 25 feet ahead no matter if you are mid air or struck in object

**Comment by Keader** [comment]
Will not be fixed for now...
Blink system is a big hack system, try fix it will break more stuffs.
