### ISSUE TITLE
[Quest] Gunship Down - ID 26245 - Deepholm

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2915]
**Links:**
https://www.wowhead.com/quest=26245/gunship-down
from WoWHead

**What is happening:**
There are no clues where they are supposed to be.

**What should happen:**
Position of the 3 clues:
Unexploded Artillery Shell - on the ground near the southern part of the wreck (56.7, 76.4).
Slain Cannoneer - on the ground between the two halves of the wreck (56.1, 74.2).
Captain Skullshatter - inside the quarters on the northern part of the wreck (53.5, 73.8)

**Comment by Rushor** [comment]
added the 3 npcs and spellclicking them will reward the questcredit

![I](https://i.imgur.com/i74KG1K.jpg)
![I](https://i.imgur.com/173kcNe.jpg)
![I](https://i.imgur.com/XxECd1A.jpg)
