### ISSUE TITLE
Missing Justice Points, again.

### ISSUE THREAD

**Issue by Shycazia** [WoWManiaUK/Blackwing-Lair#2916]
**Links:**

from WoWHead or our Armory

**What is happening:**
Bosses and completing dungeon in normal mode don't award justice points.

**What should happen:**
completing a normal dungeon should give all players in the party 140 justice points

Sorry for reposting this, but the other threads are closed so maybe the bug shows just again and need a fix again.

**Comment by Rushor** [comment]
only happens if you don't have the currerny before

**Comment by Shycazia** [comment]
ok, but i do have some of the Cooking currency points.

**Comment by Rushor** [comment]
from which quest?

**Comment by Shycazia** [comment]
from the Cooking Daily in OG.

**Comment by Kitzunu** [comment]
I do not know anything about if it is awarding or not.

But what I do know, is that when a quest that rewards JP/VP is completed (in this issue) it is not sending the neccessary packet to show in chat that you get the currency.

Dont have a sniffer and cant check packet logs from server side, so can't say which packet is missing

**Comment by Rushor** [comment]
duplicate here https://github.com/WoWManiaUK/Blackwing-Lair/issues/2450
