### ISSUE TITLE
Flight path infinite loop

### ISSUE THREAD

**Issue by JohnnyMudd** [WoWManiaUK/Blackwing-Lair#2917]
**Links:**

from WoWHead or our Armory

**What is happening:**
I attempted to take a flight path from Light's Hope Chapel in Eastern Plaguelands to Fuselight in the Badlands when the flight stopped in Stormwind. I was running around at a normal pace on a flightless version of the flight path hippogryph and unable to interact with anything or any NPC. I tried relogging to fix this issue and the flight path immediately resumed but I was headed back to Eastern Plaguelands in a direct line just passing through any objects in my way. Upon reaching Light's Hope Chapel, the flight path just restarts and loops the same bug.

**What should happen:**
My character (Steel) be removed from the flight path in whichever method possible

**Comment by Rushor** [comment]
this seems to be a spcific single charbug, please contact a gamemaster for that. thanks
