### ISSUE TITLE
[Talent] DK - Runic Corruption

### ISSUE THREAD

**Issue by Z4but0m** [WoWManiaUK/Blackwing-Lair#2918]
**Links:**
https://cata-twinhead.twinstar.cz/?spell=51462

**What is happening:**
Runic Corruption is not reducing the cost of Death Coil by 6 despite Death Coil stating the cost has been reduced to 34.

**What should happen:**
Death Coil should be cast-able at 34 Runic Power.

**Comment by Keader** [comment]
![image](https://user-images.githubusercontent.com/7120913/62174967-33b82480-b312-11e9-8d7d-3981f66042a7.png)

With 34 runic power i'm still able to use death coil.
This issue is invalid.

**Comment by Z4but0m** [comment]
Did you cast it at all?

**Comment by Keader** [comment]
hmm, i'm able to cast, but give message: "you not enoght runic power"
confirmed the bug, fixing it.
