### ISSUE TITLE
[Quest] Words and Music by - ID 28413- Twilight Highlands

### ISSUE THREAD

**Issue by ghost** [WoWManiaUK/Blackwing-Lair#292]
Quest - https://www.wowhead.com/quest=28413/words-and-music-by
NPC - https://www.wowhead.com/npc=48366Cannot speak with Russell to complete the quest

**Comment by mfranca0009** [comment]
Working on this currently, I've fixed the database side, just need to create its C++ script.

**Comment by mfranca0009** [comment]
All set, needs testing in PTR 👍 

Should have all available variations of the song corresponding to the gossip options that you select from the three menus that you will go through when selecting the rhyming words.

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 
https://gyazo.com/92e0de93d30f306acc095c8676cc8fe1
