### ISSUE TITLE
Quest 27651 Doing it like a Dunwald is't starting

### ISSUE THREAD

**Issue by Floras5** [WoWManiaUK/Blackwing-Lair#2920]
**Links:**
quest https://www.wowhead.com/quest=27651/doing-it-like-a-dunwald
npc to talk too https://www.wowhead.com/npc=46628/flynn-dunwald

**What is happening:**

When you've got the q you have to Talk to one of the brothers to start the event to kill that giant in front of them. but you cant talk to one to start the event so you're unable to attack the q mob.

**What should happen:**
you should be able to talk to one so you can kill the q mob

**Comment by Rushor** [comment]
46624

**Comment by Rushor** [comment]
questscript added

![I](https://i.imgur.com/4KzsAeF.jpg)
![I](https://i.imgur.com/i5YT0q1.jpg)

**Comment by Deathghat** [comment]
This fix is broken again
