### ISSUE TITLE
[Talent/Spell] DK - Summon Gargoyle

### ISSUE THREAD

**Issue by Z4but0m** [WoWManiaUK/Blackwing-Lair#2922]
**Links:**
https://cata-twinhead.twinstar.cz/?spell=49206

**What is happening:**
The damage from Summon Gargoyle is exceedingly low, unmodified by the Deathknight's attack power.

**What should happen:**
The Gargoyle's damage should be far higher.

**Comment by Z4but0m** [comment]
![image](https://user-images.githubusercontent.com/52716599/62383037-e8259680-b51c-11e9-8980-407f36d1a6ad.png)

**Comment by Keader** [comment]
How much it should get of dk attack power?

**Comment by Z4but0m** [comment]
The issue still persists. unless the fix hasn't been pushed onto the game yet.
