### ISSUE TITLE
[NPC] Moanah Stormhoof <The Earthen Ring>- Vashj'ir

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#2924]
**Links:**
![Screenshot_2](https://user-images.githubusercontent.com/52254524/62223107-142a0600-b3bd-11e9-8ae1-4e0558b7bfce.png)
![Screenshot_3](https://user-images.githubusercontent.com/52254524/62223113-1724f680-b3bd-11e9-94c5-a1083268f890.png)

from WoWHead or our Armory
https://www.wowhead.com/npc=41248/moanah-stormhoof#starts

**What is happening:**

The NPC isn't on the place it should be. On 1st screenshot the NPC is shown and its location in the background. In the 2nd screenshot I am staying on the place where the NPC should be, but there is nobody there. 

**What should happen:**

The NPC should be on the place where I am staying. (2nd Screenshot)

**Comment by Rushor** [comment]
added

![I](https://i.imgur.com/mYQEhzD.jpg)
