### ISSUE TITLE
[quest] Tears of Stone

### ISSUE THREAD

**Issue by Wojtek92** [WoWManiaUK/Blackwing-Lair#2925]
**Links:**
https://www.wowhead.com/quest=25237/tears-of-stone 
from WoWHead or our Armory
https://www.wowhead.com/quest=25237/tears-of-stone
**What is happening:**
There is no stone tears to gather in location from wowhead 

**What should happen:**
There should be small stone tears to gather.

**Comment by Echinaceax** [comment]
![tears](https://user-images.githubusercontent.com/39439201/62230660-936e0880-b3c2-11e9-9e3e-ef98eaa0d119.jpg)

![tears complete](https://user-images.githubusercontent.com/39439201/62230667-97018f80-b3c2-11e9-8d2d-9ff047f54c78.jpg)
