### ISSUE TITLE
[quest] forces of nature: whisps

### ISSUE THREAD

**Issue by Wojtek92** [WoWManiaUK/Blackwing-Lair#2926]
**Links:**
https://www.wowhead.com/quest=25407/forces-of-nature-wisps
from WoWHead or our Armory
https://www.wowhead.com/quest=25407/forces-of-nature-wisps
**What is happening:**
After using Tessina's Wisp Call, near whisps, they don't rally

**What should happen:**
after using tessina's whisp call they should rally

**Comment by Echinaceax** [comment]
Tested in dev 
quest item works but not quest credit 

![wisps](https://user-images.githubusercontent.com/39439201/62230072-55bcb000-b3c1-11e9-94aa-5dae4b7821c3.jpg)

**Comment by Rushor** [comment]
credit added

![I](https://i.imgur.com/8s5cIOI.jpg)

**Comment by Wojtek92** [comment]
other quest like this:
Forces of Nature: something, have same problem

**Comment by Wojtek92** [comment]
Forces of Nature: Hippogryphs, 
Forces of Nature: Treants
Forces of Nature: Dragonkins

**Comment by Rushor** [comment]
will fix them

**Comment by Echinaceax** [comment]
im on test @Rushor
