### ISSUE TITLE
[Dungeon/Crash] Shadowfang Keep crashes people after it's finished

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#2927]
**Links:**

from WoWHead or our Armory

**What is happening:**

So I've noticed that every time Shadowfang Keep Heroic is finished and I leave the party I disconnect from the server as soon as i leave. That happens only with this dungeon and it happens absolutely every time.

**What should happen:**

Leaving the party after finishing Shadowfang Keep Heroic shouldn't disconnect people from the server.

**Comment by Echinaceax** [comment]
is only you crashing or others too?

**Comment by kDracku** [comment]
Can confirm and its not only shadowfang keep , not only me but others in party too

**Comment by Denrunmt** [comment]
I've noticed only Shadowfang Keep does that but if you get it from other dungeons too, it's possible. And yes, it does crash all the people.

**Comment by Rushor** [comment]
assigning you @Keader

**Comment by Keader** [comment]
i cant reproduce folks :/
Any steps?

**Comment by Echinaceax** [comment]
Not sure this happens to everyone, ive done SFK and never crashed,
I think its more to do with the #1616  and #4192 that it being a dungeon issue @Keader

**Comment by Echinaceax** [comment]
### update
not seen any client crash issues recently by anyone so im guessing it was fiixed when the group lag issue was fixed
