### ISSUE TITLE
[Spell] Warrior - Bloodthirst

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2928]
**Links:**

https://fr.wowhead.com/spell=23881/sanguinaire

**What is happening:**

Way excessive irrelevant amount of damage
https://puu.sh/DXIyF/f59c1cbd66.png

**What should happen:**

The correct damage 
https://puu.sh/DXIDm/8e52be04f8.png

About 8k like in this screen maybe more, maybe less, but not 110k as I already saw

**Comment by Cenasty** [comment]
https://puu.sh/DZEHA/745699c275.png

Taken the 31/07/2019 at 19.09 Realm Time

**Comment by kDracku** [comment]
Damn warrs they reported only the healing :))

**Comment by Eirolla** [comment]
![image](https://user-images.githubusercontent.com/26048748/62319258-3f3c5480-b4a6-11e9-81ce-1f787359a7bd.png)
