### ISSUE TITLE
[QUEST][Vashj'ir Starter: A Personal Summons 

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#2929]
**Links:**
https://www.wowhead.com/quest=28790/a-personal-summons

**What is happening:**
Quest is not in Blackwing Lair at the moment. 

**What should happen:**
The quest should be on Warchief's Command Board.

**Comment by Rushor** [comment]
added
![I](https://i.imgur.com/5S9TL0S.jpg)
