### ISSUE TITLE
[quest] forces of nature: hippogryphs

### ISSUE THREAD

**Issue by Wojtek92** [WoWManiaUK/Blackwing-Lair#2930]
Links:
https://www.wowhead.com/quest=25409/forces-of-nature-hippogryphs
from WoWHead or our Armory
https://www.wowhead.com/quest=25409/forces-of-nature-hippogryphs
What is happening:
After using Tessina's Wisp Call, near npcs, they don't rally

What should happen:
after using tessina's  call they should rally

**Comment by Rushor** [comment]
![I](https://i.imgur.com/MrFyTKd.jpg)

fixed with next update
