### ISSUE TITLE
[quest] forces of nature: treants

### ISSUE THREAD

**Issue by Wojtek92** [WoWManiaUK/Blackwing-Lair#2931]
Links:
https://www.wowhead.com/quest=25410/forces-of-nature-treants
from WoWHead or our Armory
https://www.wowhead.com/quest=25410/forces-of-nature-treants
What is happening:
After using Tessina's Wisp Call, near npcs, they don't rally

What should happen:
after using tessina's  call they should rally

**Comment by Rushor** [comment]
![I](https://i.imgur.com/9x4TZiY.jpg)

fixed with next update
