### ISSUE TITLE
[quest] Forces of Nature: Faerie Dragons

### ISSUE THREAD

**Issue by Wojtek92** [WoWManiaUK/Blackwing-Lair#2932]
Links:
https://www.wowhead.com/quest=25468/forces-of-nature-faerie-dragons
from WoWHead or our Armory
https://www.wowhead.com/quest=25468/forces-of-nature-faerie-dragons
What is happening:
After using Tessina's Wisp Call, near npcs, they don't rally

What should happen:
after using tessina's call they should rally

**Comment by Rushor** [comment]
fixed with next update

![I](https://i.imgur.com/i5VpLXy.jpg)

**Comment by Bathelmo** [comment]
?

**Comment by Bathelmo** [comment]
you cannot unsign me man, not cool i have fixed it 30 minutes ago.

**Comment by Rushor** [comment]
and i fixed it in the second it was reported - well then we have 2 fixes

**Comment by Bathelmo** [comment]
All I have to say is that i was already assigned to this bug.

**Comment by Rushor** [comment]
yeah no trouble man, need to assign issues to myself now

**Comment by Rushor** [comment]
will use my script, no need to actually add a spellscript to that, however the credit goes to you
