### ISSUE TITLE
[quest] Forces of Nature: Mountain Giants

### ISSUE THREAD

**Issue by Wojtek92** [WoWManiaUK/Blackwing-Lair#2933]
Links:
https://www.wowhead.com/quest=25469/forces-of-nature-mountain-giants
from WoWHead or our Armory
https://www.wowhead.com/quest=25469/forces-of-nature-mountain-giants
What is happening:
After using Tessina's Wisp Call, near npcs, they don't rally

What should happen:
after using tessina's call they should rally

**Comment by Rushor** [comment]
added

**Comment by Bathelmo** [comment]
all forces of nature quests should work, the spell is targeting by aoe now
