### ISSUE TITLE
[QUEST]Vashj'ir Starter: The Eye of the Storm - 28805- 

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#2934]
**Links:**

https://www.wowhead.com/quest=28805/the-eye-of-the-storm

**What is happening:**
You should click to Waters of Farseeing. After that game is being the black screen for a while and quest is not being completed.

**What should happen:**

You should click to little water. After that game should show us a cinematic and complete the quest.

**Comment by Echinaceax** [comment]
confirmed missing cinematic - just black screen
![eye of storm](https://user-images.githubusercontent.com/39439201/62246634-57e43600-b3e4-11e9-81f0-003e2f378e20.jpg)

**Comment by Rushor** [comment]
![I](https://i.imgur.com/qMJ4Kko.jpg)

credit added cinematic will be added later
