### ISSUE TITLE
[quest] Ogre abduction

### ISSUE THREAD

**Issue by Wojtek92** [WoWManiaUK/Blackwing-Lair#2935]
**Links:**
https://www.wowhead.com/quest=25403/ogre-abduction
from WoWHead or our Armory
https://www.wowhead.com/quest=25403/ogre-abduction
**What is happening:**
after using q item, soul is not captured 

**What should happen:**
after using q item soul should become captured

**Comment by Rushor** [comment]
killcredit and scrink script added

![I](https://i.imgur.com/S34B481.jpg)

**Comment by gamer100** [comment]
Still not  working the  catched npc  is not responding
