### ISSUE TITLE
[QUEST] Vashj'ir : Rest For the Weary Phased out NPC (issue 2)

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#2936]
**Links:**
https://www.wowhead.com/quest=25941/rest-for-the-weary

**What is happening:**

https://www.wowhead.com/npc=41711/legionnaire-nazgrim is not there. 

**What should happen:**

https://www.wowhead.com/npc=41711/legionnaire-nazgrim  He should pop up after complete "Pay it foward"

**Comment by Echinaceax** [comment]
confirmed 

![no here](https://user-images.githubusercontent.com/39439201/62248821-4e110180-b3e9-11e9-9f13-a33a2df18afa.jpg)

**Comment by Rushor** [comment]
added 
![I](https://i.imgur.com/KiGUGFw.jpg)

questchain and quests from him itself must be fixed in a different issue.
