### ISSUE TITLE
[SPELL] Vashj'ir: Sea Legs

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#2937]
**Links:**
https://www.wowhead.com/spell=73701/sea-legs

**What is happening:**

When you hit to the ground, passive is being inactive and we can't run on the ground.

**What should happen:**

The passive should not be broken when you hit the ground. We should run freely on the ground.

**Comment by Echinaceax** [comment]
confirmed and doesnt grant unwater breathing as it should 

![no breathing](https://user-images.githubusercontent.com/39439201/62250871-65062280-b3ee-11e9-8eb3-88ce918d90e8.jpg)

**Comment by Rushor** [comment]
i may can fix that since i added the spell in that area, will check tomorrow :)

**Comment by Rushor** [comment]
okay should no longer be removed on ground only on map switch

![I](https://i.imgur.com/S2Df6pA.jpg)
