### ISSUE TITLE
[NPC] Wotlk/Cataclysm Rare Npc's

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#2938]
**Links:**
https://github.com/Jimmerz28/WoW-Addons/blob/a7077aa735df2688e6a72ea59f0d9f1939906e32/WTF/Account/JIMMERZ28/Deathwing/Zerkratzen/SavedVariables/_NPCScan.lua
from WoWHead or our Armory

**What is happening:**

So me and a lot of people noticed that a lot of Cataclysm rare NPC's/ World's bosses are missing. Some of them we searched for days, some of them we know they are missing from players that already tried to look for them. I can give the names of some, but most of them are in the link above. 
- Armagedillo(ID-50065)
- Blazewing (ID-50057) 
- Aeonaxx (ID-50062)
- Mobus (ID- 50009) 
- Burgy Blackheart (ID-50052) 
- Captain Florence (ID-51071) 
- Shok'sharak (ID-50050)

**What should happen:**

The NPCs in the link above and the ones that I have listed should be able to spawn.

**Comment by Rushor** [comment]
those rares are missing

50052,
50057,
50062,
50064,
50065,
50409,
50410,
51079,
62346,
50050);

**Comment by Rushor** [comment]
List with all

[50052] = "Burgy Blackheart",
		[50053] = "Thartuk the Exile",
		[50085] = "Overlord Sunderfury",
		[50086] = "Tarvus the Vile",
		[50056] = "Garr",
		[50057] = "Blazewing",
		[50089] = "Julak-Doom",
		[50059] = "Golgarok",
		[50060] = "Terborus",
		[50061] = "Xariona",
		[50062] = "Aeonaxx",
		[50063] = "Akma'hat",
		[50064] = "Cyrus the Black",
		[50065] = "Armagedillo",
		[50005] = "Poseidus",
		[50409] = "Mysterious Camel Figurine",
		[50410] = "Mysterious Camel Figurine",
		[32491] = "Time-Lost Proto Drake",
		[50009] = "Mobus",
		[18684] = "Bro'Gaz the Clanless",
		[51079] = "Captain Foulwind",
		[62346] = "Galleon",
		[49822] = "Jadefang",
		[50050] = "Shok'sharak",
		[49913] = "Lady LaLa",

**Comment by fuzzydunlop** [comment]
https://www.wowhead.com/npc=50051/ghostcrawler
Ghostcrawler seems to be missing in the list.

**Comment by sarahkay88** [comment]
[50005] = "Poseidus",
[49822] = "Jadefang",
[50053] = "Thartuk the Exile",
[50059] = "Golgarok",
[50060] = "Terborus"
are all in the game - I killed and looted these all today :)

**Comment by Rushor** [comment]
okay according to that https://www.wowhead.com/npc=50005/poseidus#comments:id=1490336 respawntimer should be sth like 74 hours

**Comment by sarahkay88** [comment]
yes he has long spawn time n 6 locations - very rare but he in deff in game I already got my mount from him :)

**Comment by Priestelar** [comment]
Yes poseidus has blizzlike respawn time, I got it during the week too.

**Comment by Rushor** [comment]
almost done! this will be a huge fix. will add more infos in a post

**Comment by Rushor** [comment]
LOL this is a good one

https://www.wowhead.com/npc=3868/blood-seeker#comments
This bat appears for a few seconds/minutes instead of Aeonaxx, and shares a spawn timer with him. This mob is easily the biggest troll in World of Warcraft.

Will add that feature xD

**Comment by Rushor** [comment]
Add done. Post tomorrow. This was huge work :o

**Comment by Rushor** [comment]
Hunting time!

With the next update all High End Rare Spawns fitting to patch 4.0.3.13277 will be added to the game. In the following some information about them.

The small zonebosses:
Jadefang,Shok'sharak,Ghostcrawler,Burgy Blackheart,Thartuk the Exile,Blazewing,Terrorpene,Golgarok,Terborus,Cyrus the Black,Armagedillo,Overlord Sunderfury,Tarvus the Vile,Karoma,Sambas,Captain Foulwind,Madexx
and the BIG worldbosses:
Poseidus,Mobus,Garr,Xariona,Aeonaxx,Akma'hat,Julak-Doom
will all the added to the game. 

We have added propper abilities, adjusted Meleedamage, Golddrops, Itemsdrops (epics, mounts and recipes) to those bosses. Please keep in mind that almost all bosses have propper pathing and pooling now.
They will spawn and run in different places like back in the days on retail. The respawntimer is variable. The small rare spawns will have a respawntimer of 8 hours, while the big world bosses (maximum of 2 active spawns on the world at the same time) will have a respawntimer up to 3 days.

You can find a detailed guide here: https://www.mmo-champion.com/content/2120-Cataclysm-Rare-and-Rare-Elite-The-MMO-Report-Comics

We wish all players and pets a happy hunting time!
