### ISSUE TITLE
[Spell/Paladin] Censure (Dot) damage

### ISSUE THREAD

**Issue by georgeapostolov** [WoWManiaUK/Blackwing-Lair#2939]
http://www.worldoflogs.com/ranking/eu-us/throne-of-the-4-winds/dps/
http://www.worldoflogs.com/ranking/eu-us/blackwing-descent/dps/
http://www.worldoflogs.com/ranking/eu-us/bastion-of-twilight/dps/
http://www.worldoflogs.com/ranking/eu-us/baradin-hold/dps/
http://www.worldoflogs.com/ranking/eu-us/firelands/dps/
http://www.worldoflogs.com/ranking/eu-us/dragon-soul/dps/

**What is happening:**
Censure (Dot) damage is doing incredibly more damage on Wow-Reign, compared to Retail. It's maybe stacking bug or duration bug, but **it shouldn't be main source of damage**.

**What should happen:**
You can easily view that Censure is between 8% and 11% of total damage, depending on gear and boss fight.

**Comment by Absaggio** [comment]
According to DrDamage the damage is ok

**Comment by Keader** [comment]
@Dranah

**Comment by georgeapostolov** [comment]
![image](https://user-images.githubusercontent.com/5627962/62489802-63fb3980-b7d0-11e9-9d5e-7bff38c66273.png)
![image](https://user-images.githubusercontent.com/5627962/62489859-8ab97000-b7d0-11e9-93fa-38ed88a678ba.png)
![image](https://user-images.githubusercontent.com/5627962/62489892-a1f85d80-b7d0-11e9-8b15-c4f1f8b93679.png)
examlple damage from boss fights and overall 29.5% damage from Censure only. Can you confirm it's ok, 2-3 times more than retail?

**Comment by kDracku** [comment]
Hello , the problem with censure is that he spreads to nearby targets and it should not. Me as prot paladin i spread all the dot to all nearby adds

**Comment by FixMySpells** [comment]
Well there's another Issue with the spell....

What is happening : Divine Storm and Holy Wrath apply a stack of censure ( Dot) to all nearby targets, and  that should not happen.

what should happen : Divine Storm and Holy Wrath should only apply censure to the primary target (the target you are facing)

**Comment by Dranah** [comment]
Coefficient is under fixing, it is too high.
Hammer of the Righteous is intended to apply a stack to all targets hit.
Other than that, only single target attacks should proc it, Divine storm and Holy wrath should not.
Fix in progress by Keader.

**Comment by APTX4869s** [comment]
@Dranah  I do agree with you about Divine Storm and Holy wrath shouldn't proc Censure.
but " Hammer of the Righteous is intended to apply a stack to all targets hit. " 

https://www.youtube.com/watch?v=vedVM9zDiqE 

at 6:03 you can clearly see that he used exorcism on target B ( not main target ) which applied a stack of censure on it ( works fine ) then he used Avenger's Shield  which didn't apply any stack of censure on both targets A and B ( in wow reigns avenger's shield applies a stack of censure to any target it hits ) after that he used Hammer of the Righteous which it hit both targets A and B but the damage of censure was the same 354-355( that stack came from exorcism )that means it wasn't getting any stack from Hammer of the Righteous  and if u keep watching the video around 6:25 you will see that censure expired from target B and it is still on target A with 5 stacks.
