### ISSUE TITLE
[NPC] Colin Thundermar 48364 - Missing - Twilight Highlands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#294]
Quest - https://www.wowhead.com/quest=28377/rescue-at-glopguts-hollow
NPC- https://www.wowhead.com/npc=48364
Missing NPC-https://www.wowhead.com/npc=48472
Quest cannot be handed in due to missing NPC.

**Comment by wow-mania** [comment]
NPC is there.
![image](https://user-images.githubusercontent.com/12248683/54619477-917f5a80-4a5c-11e9-82ad-bbd6859fbecb.png)

**Comment by TheSale** [comment]
http://prntscr.com/nx4yxi
I dont see npc, there
but judging by the colors, is there some kind phase that cause issues here?
