### ISSUE TITLE
[Spell/Pet/Glyph] DK - Raise Dead

### ISSUE THREAD

**Issue by Z4but0m** [WoWManiaUK/Blackwing-Lair#2942]
**Links:**
https://cata-twinhead.twinstar.cz/?item=43549
https://cata-twinhead.twinstar.cz/?spell=46585
https://cata-twinhead.twinstar.cz/?spell=52143
https://cata-twinhead.twinstar.cz/?spell=62137

**What is happening:**
The pet ghoul is dying far too quickly and too frequently than they should, rendering them almost useless in situations where enemies deal large amounts of AoE damage due to the fact that they seem to lack the passive ability Avoidance.

**What should happen:**
Ghouls must have the passive ability, Avoidance, in order to actually survive.

**Comment by Rushor** [comment]
this can be ported from wotlk i think

**Comment by Keader** [comment]
Fixed avoidance.
Glyph is working already.
