### ISSUE TITLE
[QUEST] Deepholm: Apply and Flash Dry

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#2945]
**Links:**

https://www.wowhead.com/quest=26411/apply-and-flash-dry

**What is happening:**

Quest item is not working on NPC.

**What should happen:**

After you use the quest item on wounded NPC, it should be completed.

**Comment by Rushor** [comment]
added

![I](https://i.imgur.com/6umAeTq.jpg)

**Comment by Eirolla** [comment]
#277 duplicate post.

**Comment by Echinaceax** [comment]
> #277 duplicate post.

yes but rusher added new fix to this one too now 9 hours ago

**Comment by sarahkay88** [comment]
I. Losed the other one keep this one open till javbi as implemented the fix

**Comment by Rushor** [comment]
oh okay sorry guys. didn't checked just instantly fixed. hope this is no trouble for you all. peace and love :>
