### ISSUE TITLE
[QUEST]Deepholm: Earthcaller Yevaa (Quest Chain Bug)

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#2946]
**Links:**

https://www.wowhead.com/npc=42573/earthcaller-yevaa

**What is happening:**

She's giving both faction quests to players.

**What should happen:**
https://www.wowhead.com/quest=27952/the-explorers must be given only to Alliance
https://www.wowhead.com/quest=27953/the-reliquary must be given only to Horde

**Comment by Rushor** [comment]
duplicate https://github.com/WoWManiaUK/Blackwing-Lair/issues/2851
