### ISSUE TITLE
[QUEST]Deepholm: Fly Over

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#2947]
**Links:**

https://www.wowhead.com/quest=27008/fly-over

**What is happening:**

Quest is not completing when you land on Master's Gate stairs. 

**What should happen:**

Quest is must be completed after you be close or land close to Master's Gate.
Proof: https://www.youtube.com/watch?v=00HAkqZqpFk

**Comment by Rushor** [comment]
duplicate

https://github.com/WoWManiaUK/Blackwing-Lair/issues/2851

**Comment by Eirolla** [comment]
#276 Duplicated issue.
