### ISSUE TITLE
[QUEST] Deepholm: Resonating Blow

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#2948]
**Links:**

https://www.wowhead.com/quest=26659/resonating-blow

**What is happening:**

When you use quest item, quest part is completing but the elite mob is not coming down.

**What should happen:**

When you use quest item on stone, it should call down the elite mob.

**Comment by Rushor** [comment]
spawned and can be killed

![I](https://i.imgur.com/wW50Szu.jpg)

**Comment by Rushor** [comment]
refixed with next update
