### ISSUE TITLE
[Pest Control] Gilneas - Vilebrood Skitterer **no spawns**

### ISSUE THREAD

**Issue by AlyssaK** [WoWManiaUK/Blackwing-Lair#2949]
**Links:**

https://www.wowhead.com/npc=36813/vilebrood-skitterer
https://www.wowhead.com/quest=24484/pest-control

**What is happening:**

Two were spawned when I walked in. Haven't spawned since.

**What should happen:**

There should be like multiple spawn points going every couple minutes of these things.

**Comment by Rushor** [comment]
There are 18 spawns for them. Please talk with a GM and make sure that you are in phase 186. Thanks.
