### ISSUE TITLE
[Quest] Through Fire and Flames - ID 13878- Northern Barrens

### ISSUE THREAD

**Issue by realdude19** [WoWManiaUK/Blackwing-Lair#295]
The quest is to break the chains that are holding the wolfs in the stables, but the chains are not there.
The quest can not be completed without the chains or something to interact with.
Quest number [13878]

**Comment by Dranah** [comment]
https://www.wowhead.com/quest=13878/through-fire-and-flames

**Comment by dandancanfly** [comment]
The chains are there for me, and right clicking them uses it, but no fire appears and no wolves are freed.

**Comment by Saintres** [comment]
No chains for me, no chance to free any wolves
Not possible to complete quest

**Comment by Xman993** [comment]
no fire too, just a infernal
![image](https://user-images.githubusercontent.com/6819293/56220695-2891ff00-6069-11e9-949d-1958da543078.png)

**Comment by Eirolla** [comment]
![image](https://user-images.githubusercontent.com/26048748/62368995-d94bdd80-b536-11e9-9d21-0b6d98cbc1f1.png)
wolf chains are (I cant find object id) not triggering when you interact with them. it should +1 for the quest.

**Comment by Bathelmo** [comment]
I don't understand it anyone can make it simpler for me please? too many posts, too many :D

**Comment by Echinaceax** [comment]
@Bathelmo 
quest is to Break the chains to free the wolves from the burning stables.
- but there is no chains 
so cant free wolves

**Comment by Echinaceax** [comment]
confirmed fixed in dev 

![freed](https://user-images.githubusercontent.com/39439201/80891732-46f38880-8cc6-11ea-9f21-46da0e7ad97f.jpg)
