### ISSUE TITLE
[Item/NPC] Recipe: Agile Shadowsprint Diamond - Marith Lazuria

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#2950]
**Links:**
http://cata-shoot.tauri.hu/?item=68778
https://www.wowhead.com/npc=50482/marith-lazuria
from WoWHead or our Armory

**What is happening:**

The recipe is currently missing from the vendor Marith Lazuria <Jewelcrafting Supplies> in Orgrimmar.

**What should happen:**

The NPC should sell the recipe for 4 Illustrious Jewelcrafting's Tokens. Please check if its missing from other vendors too (Dalaran, Shattrath City).

**Comment by Rushor** [comment]
no it's a world drop https://de.wowhead.com/item=68781/vorlage-agiler-irrlichtdiamant#comments:id=1291755:reply=214969
