### ISSUE TITLE
[Achievement] Straw That Broke the Camel's Back (ID-5294) - Halls of Origination

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#2951]
**Links:**
![Screenshot_3](https://user-images.githubusercontent.com/52254524/62341873-813cb900-b4ed-11e9-8d04-c84b81ca0aa4.png)
![Screenshot_5](https://user-images.githubusercontent.com/52254524/62341751-1b503180-b4ed-11e9-99b3-f13553420652.png)
https://www.wowhead.com/achievement=5294/straw-that-broke-the-camels-back
from WoWHead or our Armory

**What is happening:**

Achievement doesn't pop up after killing Earthrager Ptah while being on a camel in Halls of Origination. First screenshot shows that the boss is killed and I'm still on the camel but no achievement is earned.

**What should happen:**

Halls of Origination should reward you with this achievement if you kill Earthrager Ptah while being on a camel.

**Comment by Rushor** [comment]
on hc, if you are on camel on kill you will get credit now. does not work in nh

![I](https://i.imgur.com/Y38G67V.jpg)
![I](https://i.imgur.com/MpSAkeU.jpg)
