### ISSUE TITLE
[Boss] Ammunae - Bloodpetals spawn - Halls of Origination

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2952]
**Links:**
https://www.wowhead.com/npc=39731/ammunae
from WoWHead

**What is happening:**
If Ammunae is not the last boss killed, every npc in the dungeon (friendly or enemy) get a copy of himself as a bloodpetal sprout. This is the scenary in the elementals chamber after killed him.
![WoWScrnShot_080219_004641_2](https://user-images.githubusercontent.com/45459932/62361034-72b8c680-b51a-11e9-9f91-1e40517ec22c.jpg)

**What should happen:**
Bloodpetal Sprouts should not spawn in the dungeon after Ammunae is killed.

**Comment by Rushor** [comment]
hoe to reproduce this?

**Comment by Rushor** [comment]
they will always morpg to the pillagers again

**Comment by Sammy974** [comment]
If you want to reproduce this, just kill Ammunae first, then take a look around in the dungeon. It's funny, actually, because every boss got a flower on their feet. 

![WoWScrnShot_081119_182128_2](https://user-images.githubusercontent.com/45459932/62837852-a8755200-bc74-11e9-9b7e-bd0e5a11ef3a.jpg)
