### ISSUE TITLE
[QUEST] Deepholm: The Axe of Earthly Sundering

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#2955]
**Links:**

https://www.wowhead.com/quest=27932/the-axe-of-earthly-sundering
https://www.youtube.com/watch?v=xxVjGJrEMsw

**What is happening:**

Quest item is doing nothing on target NPC.

**What should happen:**

When you use it on Emerald Colossus, it should change to "Sundered Emerald Colossus".

**Comment by sarahkay88** [comment]
#1991
