### ISSUE TITLE
[Dungeon] Trash mobs - Loot table Hc

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2956]
**Link**
https://wowwiki.fandom.com/wiki/Trash_mob
Example: https://www.wowhead.com/npc=39803/air-warden#drops:mode=heroic
https://www.wowhead.com/npc=40715/lifewarden-nymph#drops:mode=heroic

**What is happening:**
In every hc dungeon, trash mobs only drop gold. 

**What should happen:**
Trash mobs should drop gold + consumables + some cloth if humanoid + grey items + green items for disenchant + some rare drop + some epic world drop :)

**Comment by Rushor** [comment]
well thank you but this is way too general. you need to help me.

i need a list ov every creatures from the instances. better you make one report/instance

do it like in https://github.com/WoWManiaUK/Blackwing-Lair/issues/2190 but with every mob

**Comment by Sammy974** [comment]
no prob :) i'll do it

**Comment by Sammy974** [comment]
@Rushor done for every hc dungeon available. Take a look and let me know if it's fine.
