### ISSUE TITLE
[NPC] Rare NPC - Hemathion - Blade's Edge Mountains 

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#2957]
**Links:**
https://www.wowhead.com/npc=18692/hemathion
![Screenshot_7](https://user-images.githubusercontent.com/52254524/62384942-55a4e780-b55c-11e9-8eb3-46335d547da1.png)
![Screenshot_8](https://user-images.githubusercontent.com/52254524/62384946-576eab00-b55c-11e9-84ea-3f37a68a53f6.png)
![Screenshot_9](https://user-images.githubusercontent.com/52254524/62384949-59386e80-b55c-11e9-85b4-97eea7675561.png)

from WoWHead or our Armory

**What is happening:**

I think the NPC is underground, I don't see any caves in the area and as far as i see on the screenshots in Wowhead, the NPC shouldn't be in a cave.

**What should happen:**

The NPC should be visable on the ground after finding it.

**Comment by Rushor** [comment]
waypoints added, so he will no longer drop below ground

![I](https://i.imgur.com/PfKxVY6.jpg)
