### ISSUE TITLE
[quest] Get Zherin! 

### ISSUE THREAD

**Issue by Wojtek92** [WoWManiaUK/Blackwing-Lair#2958]
**Links:**
https://www.wowhead.com/quest=25756/get-zherin
from WoWHead or our Armory
https://www.wowhead.com/quest=25756/get-zherin
**What is happening:**
There is no way to get an item - horde proposal 

**What should happen:**

Trackmaster should drop horde proposal

**Comment by Rushor** [comment]
http://cata.cavernoftime.com/item=55808
