### ISSUE TITLE
[quest] the ancient brazier

### ISSUE THREAD

**Issue by Wojtek92** [WoWManiaUK/Blackwing-Lair#2959]
**Links:**
https://www.wowhead.com/quest=25762/the-ancient-brazier
from WoWHead or our Armory
https://www.wowhead.com/quest=25762/the-ancient-brazier
**What is happening:**
I'm standing near ancient brazier and cannot ignite it by q item 

**What should happen:**
q item should works

**Comment by sarahkay88** [comment]
item already reported #2036
