### ISSUE TITLE
[NPC] Deepholm: Needlerock Mystic

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#2964]
**Links:**

https://www.wowhead.com/npc=43995/needlerock-mystic

**What is happening:**

Unable to interact/fight with NPC.
![image](https://user-images.githubusercontent.com/26048748/62394940-6f9ff380-b577-11e9-99cd-f32822667224.png)

**What should happen:**

We could fight with them.

**Comment by Rushor** [comment]
fightable

![I](https://i.imgur.com/AeoF6z8.jpg)
