### ISSUE TITLE
[Mage][Talent] Impact

### ISSUE THREAD

**Issue by wojen616** [WoWManiaUK/Blackwing-Lair#2966]
**Links:**
This is actually quite hard to find the info about it - it was a bug back in the 4.2(or Zanda rise) (same issue as with losing living bomb on your targeted mob)

**What is happening:**
Once you kill the mob with procced Fire blast (impact talent) dot spread don't occure

**What should happen:**
Spread should occure before the dmg on the target.

**Comment by Cenasty** [comment]
I think loosing Living Bomb on main target has been fixed these last days, but in case, here you go

Cataclysm Patch 4.2.0 (2011-06-28): When  [Impact] spreads Living Bomb, it will only be spread to two additional targets. The net effect is that if the mage's most recent Living Bomb target is the same as their Impact target, that target will no longer lose the Living Bomb effect. If Living Bomb is active on multiple targets when the Impact effect is cast, Living Bomb will remain active on the most recent Living Bomb target, and will be added to two other nearby targets. 

https://wow.gamepedia.com/Living_Bomb

**Comment by Keader** [comment]
Not possible spread, since main target will be dead... (without dots)

**Comment by wojen616** [comment]
So its bugged Sir. 
> WoW Icon update.png Patch 1.12.0 (2006-08-22): The effect of this talent will now still be placed on the victim if the caster is killed before their spell reaches the target. 
https://wow.gamepedia.com/Impact_(mage_talent)
