### ISSUE TITLE
[NPC] Position

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2968]
**What is happening:**

Basicly, every NPC try to face you when you are in combat when them.

**What should happen:**

NPC shouldn't care if they are in front of you, in your back or on your side.
When you have their agro, they just go at your melee range and hit regardless of your position.

Plus, they always are at maximum melee hit range. If you move forward them, they will just go backward. 
If a NPC have 8m radius melee range. If you stand in that range whether 8m or 1m, they shouldn't move.

**Comment by Rushor** [comment]
really general - could you inspect @Keader ?

**Comment by Sammy974** [comment]
Same issue here #2823

**Comment by Rushor** [comment]
alright issue moved to https://github.com/WoWManiaUK/Blackwing-Lair/issues/2823
