### ISSUE TITLE
[Transmog/Cosmetics] Teebu's Blazing Longsword

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2969]
**Links:**

https://fr.wowhead.com/item=1728/epée-longue-flamboyante-de-teebu
https://fr.wowhead.com/item=13033/lame-de-zélote

**What is happening:**

I'am trying to use blizzlike bug for transmog to mog a One Hand into a Main Hand.

But before I try to access this one, I noticed that Teebu's Blazing Longsword (which is OneHand type) can't be used to be transmogged into a Zealot Blade (OneHand type)

**What should happen:**

Since they are both one handed type, transmog should work

**Comment by Rushor** [comment]
not fixable currently
