### ISSUE TITLE
[Quest] I Can't Wear This - ID 14400 - Blocks worgen start chain

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#297]
Quest - https://www.wowhead.com/quest=14400/i-cant-wear-this
NPC- https://www.wowhead.com/npc=36458
You are to collect granny's cloths of the washing line. However they cannot be targeted to be collected.
![world of warcraft 28_12_2018 15_11_47](https://user-images.githubusercontent.com/42302580/50519512-39673680-0ab3-11e9-9146-58750ea89895.png)
Which prevents you from completing the rest of granny's quest chain

**Comment by Saintres** [comment]
I trying to do the same quest and i cant pick up any cloth for Grandma either 
2019 02 03 time 12.10 pm

**Comment by TheBolshe** [comment]
Object ID : https://www.wowhead.com/object=196472/grandmas-good-clothes
Container ID : https://www.wowhead.com/item=49279/grandmas-good-clothes

**Comment by UnknownCombine** [comment]
I trying to do the same quest and i can't pick up any cloth for Grandma either
2019 21 05 time 07:18 pm (Argentina hour).

**Comment by giles1508** [comment]
@Rushor    need to remove the fix confirmed label,  im on my reporting toon and i still cannot collect any clothes from the washing line

![WoWScrnShot_062119_083640](https://user-images.githubusercontent.com/50211643/59906096-bee2f800-93ff-11e9-9b4a-a32f73e56fdb.jpg)

**Comment by Echinaceax** [comment]
> @Rushor need to remove the fix confirmed label, im on my reporting toon and i still cannot collect any clothes from the washing line
> 
> ![WoWScrnShot_062119_083640](https://user-images.githubusercontent.com/50211643/59906096-bee2f800-93ff-11e9-9b4a-a32f73e56fdb.jpg)

Ive removed it for now for you, could be that server needs restart :)
confirm again after one of the dev server restarts please
