### ISSUE TITLE
[Quest] The Univited Guest- kezan

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Blackwing-Lair#2971]
https://www.wowhead.com/quest=14116/the-uninvited-guest
npc missing
https://www.wowhead.com/npc=35222/trade-prince-gallyw

You are send to go up to balcony to talk with trade  price gallawixx. but the npc is not there to complete the  quest. This prevent you  to take the follow up

When you  come upstirs you need to  deliver the  quest  to the Trade prince, after that he give you the  next one

https://www.wowhead.com/quest=14120/a-bazillion-macaroons

https://www.youtube.com/watch?v=e5XOxh0yrM8

**Comment by Rushor** [comment]
the zone name is KEZAN
