### ISSUE TITLE
[NPC] Trade Prince Galliwix - kezan

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Blackwing-Lair#2972]
https://www.wowhead.com/npc=35222/trade-prince-gallywix
missing for quest
https://www.wowhead.com/quest=14120/a-bazillion-macaroons

Cant take  quest npc is missing

Npc  gives you after  complete

https://www.wowhead.com/quest=14120/a-bazillion-macaroons

**Comment by Rushor** [comment]
the zone name is KEZAN

**Comment by Echinaceax** [comment]
> the zone name is KEZAN

My bad @Rushor :)
