### ISSUE TITLE
[Quest] 447 - kezan

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Blackwing-Lair#2973]
https://www.wowhead.com/quest=14125/447

![image](https://user-images.githubusercontent.com/33811022/62413176-226e6100-b60d-11e9-97ba-45ae590a00de.png)

You  can't  finish the  quest, when you  go outside the last one is in another  phase

![image](https://user-images.githubusercontent.com/33811022/62413274-e7206200-b60d-11e9-82d0-57de5afffc99.png)

https://www.wowhead.com/npc=37598/gasbot

When you  clicked on the  bot then a bot  enter the house  and  blow it up

https://www.youtube.com/watch?v=ilqpZ6sveeE

Cause of the ohase  you  cant complete the   q  and  deliver then reward npc is also  in the rong phase
https://www.wowhead.com/npc=37602/claims-adjuster

correct phase

![image](https://user-images.githubusercontent.com/33811022/62413484-a590b680-b60f-11e9-9790-3dca62ca337b.png)

**Comment by Rushor** [comment]
basic script added in order to make it complete
