### ISSUE TITLE
{Quest] life savings- kezan 14126

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Blackwing-Lair#2974]
https://www.wowhead.com/quest=14126/life-savings
is  given by the  npc Sassy Hardwrench
https://www.wowhead.com/npc=34668/sassy-hardwrench

You cant take the  quest  cause the Quest giver is out of  phase 
After summon to correct phase  and the  quest work  fine except the  ride you  dont get
The  cinamatic  work only  on the  end of that you are stuck in  a black screen and it look like  a  grapgic crash in game.relogging deleting cache  unstuck even summon  by  a  gm dont get you out of it

![image](https://user-images.githubusercontent.com/33811022/62413809-af1c1d80-b613-11e9-9685-2f6f91e2bda0.png)
 

https://www.youtube.com/watch?v=mECdOLXkEs4

**Comment by Rushor** [comment]
ID - 91847 Life Savings: Quest Complete

that id is responsible for it

**Comment by Rushor** [comment]
okay i will fix the screen effect and the movie, but we need to wait for the further questchain. that will be done later.

**Comment by Rushor** [comment]
https://i.imgur.com/oy3a3C0.jpg
https://i.imgur.com/jVFbaij.jpg
https://i.imgur.com/PPh8gc6.png

**Comment by gamer100** [comment]
Just  did  the  quest, You  cant get  on board of the  ship,  Gm set me on the  ship and the cinematic begin, after that you are still in kezan
