### ISSUE TITLE
[NPC] The Black Temple Halls of Pain Hostile NPCs not attackable

### ISSUE THREAD

**Issue by dagget1337** [WoWManiaUK/Blackwing-Lair#2976]
**What is happening:**
In the Dungeon The Black Temple there is a Hall, Halls of Pain with lots of bloodorcs, some of them are targetable and some not, those who cant be targeted are hostile and attack when getting too close but cant die by any spell or melee attack (melee attack isnt even possible)
since they cant be targeted i cant tell which npcs they are, only that they´re blood orcs and greenish glowing Wolfs. they keep you in combat until you die, or leave the dungeon.

**What should happen:**:
They should be either: not there, or playing dead like some other corpses around and they shouldnt be able to attack.

![WoWScrnShot_080319_215027](https://user-images.githubusercontent.com/51065101/62416371-c4a43e00-b639-11e9-9333-0cd166340c03.jpg)
![WoWScrnShot_080319_214816](https://user-images.githubusercontent.com/51065101/62416375-cd950f80-b639-11e9-8445-f90e54f3d4f0.jpg)
![WoWScrnShot_080319_214823](https://user-images.githubusercontent.com/51065101/62416378-f4534600-b639-11e9-9538-0f38d3eed613.jpg)

**Comment by Rushor** [comment]
always tell me the correct name of the creatures in english please :)

**Comment by dagget1337** [comment]
Well, like i said, its not possible to target them (and its not the big one i got as target on the screenshots, i just forgot that i had him in focus).

**Comment by Echinaceax** [comment]
@dagget1337 Rusher still needs NPC name and link,  greenish wolves doesnt really help him :)

**Comment by Kitzunu** [comment]
Fixed for the orcs and the wolfes

entries 23237, 23236, 23232
