### ISSUE TITLE
[Loot] Trash Mobs - Blackrock Caverns hc

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2978]
The following trash mobs in BC hc aren't dropping items:

Bellows Slave https://www.wowhead.com/npc=40084/bellows-slave#drops:mode=heroic
Conflagration https://www.wowhead.com/npc=39994/conflagration#drops:mode=heroic
Crazed Mage https://www.wowhead.com/npc=39982/crazed-mage#drops:mode=heroic
Defiled Earth Rager https://www.wowhead.com/npc=40023/defiled-earth-rager#drops:mode=heroic
Evolved Twilight Zealot https://www.wowhead.com/npc=39987/evolved-twilight-zealot#drops:mode=heroic
Incendiary Spark https://www.wowhead.com/npc=40021/incendiary-spark#drops:mode=heroic
Mad Prisoner https://www.wowhead.com/npc=39985/mad-prisoner#drops:mode=heroic
Runty https://www.wowhead.com/npc=40015/runty#drops:mode=heroic
Twilight Element Warden https://www.wowhead.com/npc=40017/twilight-element-warden#drops:mode=heroic
Twilight Flame Caller https://www.wowhead.com/npc=39708/twilight-flame-caller#drops:mode=heroic
Twilight Obsidian Borer https://www.wowhead.com/npc=40019/twilight-obsidian-borer#drops:mode=heroic
Twilight Sadist https://www.wowhead.com/npc=39980/twilight-sadist#drops:mode=heroic
Twilight Torturer https://www.wowhead.com/npc=39978/twilight-torturer#drops:mode=heroic
Twilight Zealot https://www.wowhead.com/npc=39990/twilight-zealot#drops:mode=heroic
Twilight Zealot https://www.wowhead.com/npc=50284/twilight-zealot#drops:mode=heroic

**Comment by Rushor** [comment]
gold and items added.

![I](https://i.imgur.com/MgHppoL.jpg)

**Comment by Sammy974** [comment]
@Rushor pls check it in the live realm if you can. They only drop green items and gold. I never have seen cloth, gray items or consumables. I will check better and let you know for sure.

**Comment by Sammy974** [comment]
I blame my auto loot :) it's fine
