### ISSUE TITLE
[Quest] The Hungry Ettin - ID 14416 - Blocks worgen start chain II Gilneas

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#298]
Quest - https://www.wowhead.com/quest=14416/the-hungry-ettin
NPC - https://www.wowhead.com/npc=36457
You can mount the first horse, but then you are meant to use the horse to round up the remaining horses to complete the quest. 
However the spell: https://www.wowhead.com/spell=68903/round-up-horse is not working has intended and the horses do not follow. on the mini map it shows them once rounded up but the refuse to follow making the quest incompletable .
![world of warcraft 28_12_2018 15_16_53](https://user-images.githubusercontent.com/42302580/50519821-a7602d80-0ab4-11e9-9777-6623db5bbf25.png)
![world of warcraft 28_12_2018 15_21_14_li](https://user-images.githubusercontent.com/42302580/50519828-ac24e180-0ab4-11e9-9c94-0b0e8b3891a3.jpg)
unable to complete start zone without all quest completed

**Comment by Rushor** [comment]
todo:

add rope and followai
add despawn on spellhit
spellclick condition
despawn and credit near questgiver

![](https://i.imgur.com/FlCNw6v.jpg)
![](https://i.imgur.com/aHME0f3.jpg)
![](https://i.imgur.com/eIjAEkQ.jpg)

Once you leave your vehicle near questgiver all credits will be added.

Note: the horses are a bit slow due to beeing a vehicle, but that's ok

**Comment by giles1508** [comment]
@rushor  did you test to see if you can turn quest giver into a horse like I could? After that I was unable to get credit

**Comment by Rushor** [comment]
you can turn the questgiver in a horse? :O

**Comment by giles1508** [comment]
Yeah and the Ettin giant dude :)

**Comment by Rushor** [comment]
fix updated, so the spell will only target horses

**Comment by Rushor** [comment]
tested together with you and yeah this can be released now :>
