### ISSUE TITLE
Tauren racial cultivation

### ISSUE THREAD

**Issue by achyles22** [WoWManiaUK/Blackwing-Lair#2983]
**Links:**
https://www.wowhead.com/spell=20552/cultivation

**What is happening:**
Tauren racial cultivation doesn't work with herbalism rank level 2 (Journeyman) and higher. Only working with herbalism rank level 1 (Apprentice).

**What should happen:**
Herbalism gathering skill "Herb gathering" should be 0,5sec instead of 2sec.

**Comment by Keader** [comment]
Fixed.
Rushor only fixed rank 1, shame !

**Comment by Rushor** [comment]
oh sorry :(
