### ISSUE TITLE
[Priest] dispel magic

### ISSUE THREAD

**Issue by hediunchained** [WoWManiaUK/Blackwing-Lair#2987]
**Links:** https://cata-twinhead.twinstar.cz/?spell=527

**What is happening:** when dispel magic is used, it only removes one harmful spell on friendly targets

**What should happen:** it should remove 2 harmful spells

**Comment by Keader** [comment]
i cant reproduce.
With friendly targets is removing both debuffs here.

**Comment by hediunchained** [comment]
@Keader actualy the bug is found when you have the same debuff 2 or more times in seperate icons like this 
![image](https://user-images.githubusercontent.com/36192411/62872054-f0e84a80-bd1c-11e9-9f3b-ed6050054002.png)
it dispels only one spell at a time

**Comment by Dranah** [comment]
I can confirm this. If there are 2 identical effects, it fails to remove both.

**Comment by Keader** [comment]
Fixed.
