### ISSUE TITLE
[npc/vendor] Capital City Quartermasters (horde side) 16 slot bag missing

### ISSUE THREAD

**Issue by fuzzydunlop** [WoWManiaUK/Blackwing-Lair#2988]
**Links:**
NPCs:
https://www.wowhead.com/npc=50488/stone-guard-nargol Orc
https://www.wowhead.com/npc=50477/champion-uruzin Troll
https://www.wowhead.com/npc=50323/frizzo-villamar Goblin
https://www.wowhead.com/npc=50483/brave-tuho Tauren

**What is happening:**
Only the undercity quartermaster sells his 16 slot bag. All the other quartermasters don't sell it.
Since I don't have an alliance toon, I don't know if its similar there.

**What should happen:**
They should all sell one unique BoP 16 slot bag:
https://www.wowhead.com/item=67533/orgrimmar-satchel orc
https://www.wowhead.com/item=67536/darkspear-satchel troll
https://www.wowhead.com/item=67525/bilgewater-satchel goblin
https://www.wowhead.com/item=67534/thunder-bluff-satchel tauren

**Comment by Sammy974** [comment]
You can easily buy a 16 slot bag to any general good vendor or bag vendor in orgrimmar and other places...

**Comment by sarahkay88** [comment]
These are rep bags do you have the required rep?

**Comment by Sammy974** [comment]
@sarahkay88  you need rep to buy it, but you're supposed to see the bags anyway in the vendor list. This happens with the dragonmaw quartermaster as well. You can see the items if you don't have rep but you can't see the enchant. All items are supposed to be visible, the rep only affect the fact that you can buy them or not.

**Comment by sarahkay88** [comment]
I think that's how it was fixed. So that they only became visable with the right rep. U will have to check with who fixed it just to be sure

**Comment by sarahkay88** [comment]
Now my question is, is the undercity vendor now selling its bag with out the required rep or is it just visable? Because if u can buy it without rep then it needs reporting

**Comment by Echinaceax** [comment]
As far as i know @Sammy974 rusher set all rep bacgs to only show when player has required rep

**Comment by fuzzydunlop** [comment]
Perhaps too late for my response but: none of them show it (don't know if they will only show once you have the required rep). However, you can see (and buy) the Undercity one, with friendly rep (while it should be revered). This led me to think none of the others sell the bags. When I posted this, I did not have the required rep for any of the bags but i did expect to see them in the vendors inventory. 
@Sammy974 as far as "other bags being available at other vendors" thats hardly relevant here.

**Comment by Echinaceax** [comment]
@fuzzydunlop its ok to still respond :)

yes i know and Undercity has been reported also now to only show when you have required replike the others :)
