### ISSUE TITLE
[Item] Exodar Satchel -67527-

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#2989]
**Links:**
https://www.wowhead.com/item=67527/exodar-satchel
https://www.wowhead.com/npc=50306/kadu

**What is happening:**

Can buy this sactchel without having required rep

**What should happen:**

shouldn't be available without rep

**Comment by Rushor** [comment]
item will now only be shown if rep is reverted or exalted.

**Comment by Echinaceax** [comment]
needs revered @Rushor :)
