### ISSUE TITLE
Worgen Start Area Gilneas - Priority

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#299]
**link:**
Zone ID - 4714 https://www.wowhead.com/gilneas

**What happens:**
The player is unable to complete all the quest in this area due to previously reported bug (#300 #298 #297 #673). There for is unable to progress to the next zone. Due to being unable to complete all zone areas the gates surrounding the zone do not open allowing the player to pass through. 

This then makes them trapped unless they are teleported out or use the mall zone. 
if you earth stone home without setting your hearthstone in this area you are then unable to re-enter via the gate. **I did this trying to see if I could find an alternative route n my earth stone was set to the city and now I'm trapped there.** 

**What should happen:**
To be able to progress the player must  be able to  complete all the quest in the area, the surrounding gates must then open allowing the player to pass through. if the quest cannot be fixed then you may have to do something with the gates.

**Comment by Dranah** [comment]
Quests MUST be completed in order for players to leave the zone, I'm pretty sure if any quest cannot be fixed, it will be set to autocomplete to allow progress, opening the gates early would cause more trouble than good.

**Comment by Echinaceax** [comment]
This is HUGE priority when it stops Worgens from progressing after lvl10

**Comment by sarahkay88** [comment]
#300 #298 #297 #673

**Comment by sarahkay88** [comment]
also this one guyx  #301 sorry I missed it

**Comment by sarahkay88** [comment]
just wanted to add that iv noticed the gates are kind of double spawned. so if u click to open one there is still a gate closed. not sure if this is suppose to be this way.

**Comment by Echinaceax** [comment]
new report by pitmaster #1385

**Comment by sarahkay88** [comment]
#118 Found this whilst labelling old reports

**Comment by sarahkay88** [comment]
#1858

**Comment by sarahkay88** [comment]
#2009

**Comment by sarahkay88** [comment]
#2053  linking due to issue found when tp out of start zone in an attempt to continue to level.

**Comment by Kitzunu** [comment]
Will close this as the gates are fixed. https://github.com/WoWManiaUK/Blackwing-Lair/issues/2009

If there are other worgen issues open new issues
