### ISSUE TITLE
[Spell] Hand of Light - Ret Paladin Mastery

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#2990]
ID 86474

The damage scaling is completely off.
Each point of mastery should grant 2,1% extra damage on Crusader strike ( ID 35395), Divine Storm (ID 53385) and templar's verdict (ID 85256).

TEST1 - Crusader strike
Fully naked (shitty low weapon, relative high portion of damage comes from AP)
Mastery=8
**Intended numbers:** CS 566 damage => Hand 95 damage (16,8%)
**Actual numbers:** CS 566 damage => Hand 281 damage (49,6%)
With Akirus (high level weapon) and otherwise naked (low AP, most of damage is the weapon)
Mastery=9,27
**Intended numbers:** CS 4324 damage => Hand 843 damage (19,5%)
**Actual numbers:** CS 4324 damage => Hand 990 damage (22,8%)
With Akirus (high level weapon) and some extra gear (high AP)
Mastery=10,87
**Intended numbers:** CS 5898 damage => Hand 1344 damage (22,8%)
**Actual Numbers:** CS 5898 damage => Hand 1937 damage (32,8%)

What this shows me is that the equipped weapon's damage affects the mastery less dramatically (probably the weapon damage itself scales right), while the attack power based melee damage (which adds onto the equipped weapon's damage) is scaling much stronger than intended.
Similar results with DS below.

TEST2 - Divine Storm
Fully naked, shitty weapon
Mastery=8
**Intended:** DS 159 damage => Hand 26 damage (16,8%)
**Actual:** DS 159 damage => Hand 109 damage (68,5%)
With Akirus and otherwise naked
Mastery=9,27
**Intended:** DS 2307 damage => Hand 449 damage (19,5%)
**Actual:** DS 2307 damage => Hand 607 damage (26,3%)
With Akirus and some extra gear
**Intended:** DS 3153 damage => Hand 718 damage (22,8%)
**Actual:** DS 3153 damage => Hand 1333 damage (42,2%)

**Comment by Keader** [comment]
Was scaling with damage mods hehe.
Fixed.
