### ISSUE TITLE
[Raid Dungeon/ NPC]Temple of Ahn´Qiraj Boss "Ouro" won´t spawn

### ISSUE THREAD

**Issue by dagget1337** [WoWManiaUK/Blackwing-Lair#2991]
**What is happening:**
The semi Final Boss Ouro From Ahn Qiraj 40, Temple of Ahn´Qiraj, is just a pile of Rubble which cant be targetet and damaged only by Retribution Aura or such (He disappeares/dies after a while). 

**What should happen:**
The Boss should be Visible and Attackable, if he has certain spells he should be able to use them too.

Npc info:
https://de.wowhead.com/npc=15517/ouro

If this helps (Spawn ID): Ouro = 15517

**Comment by Rushor** [comment]
spawned and can be killed now with next update :)
