### ISSUE TITLE
[Raid/NPC] Serpentshrine Cavern - Lady Vashj

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#2992]
**Links:**
![Screenshot_5](https://user-images.githubusercontent.com/52254524/62473677-f3d9bd00-b7a9-11e9-8550-8ff828b81503.png)
![Screenshot_3](https://user-images.githubusercontent.com/52254524/62474568-d73e8480-b7ab-11e9-8e4f-202be07f7468.png)
![Screenshot4](https://user-images.githubusercontent.com/52254524/62475193-3e106d80-b7ad-11e9-8066-e62b77d22584.jpg)

from WoWHead or our Armory
https://www.youtube.com/watch?v=9Foi3KJ3mM8
https://www.wowhead.com/npc=21212/lady-vashj
Wowhead has a 10 min video how it should work, the Youtube link is 5 min video. Both videos are with the same mechanics. In the 5 min video the guy explains the mechanics and how the boss should be defeated and the 10 min video is just for comparison for the mechanics.

**What is happening:**

So If we compare the first screenshot to the videos I put links of, when Lady Vashj is in phase, she should be in the center of the circle and not move. All of the generators (the blue things) should have a line attached to her. In this case she moves around and goes to whoever has aggro of her and only one of the generator is attached to her. Another problem is that in the videos the guys kill mobs called "Tainted Elemental" and these elementals give you an item called Tainted Core which is needed to stop one generator (the item is shown in the second screenshot). You need 4 Tainted Cores to stop all 4 generators. The cores mustn't be stacked, each Tainted Core must be used in a generator before another core is looted (Better explained in the 5 min video). The last problem is that the generators can't be clicked so you can use a Tainted Core to stop each generator. 

**What should happen:**

Lady Vashj should work as the both videos I put links of.

**Comment by Rushor** [comment]
already fixed https://github.com/WoWManiaUK/Blackwing-Lair/issues/3424
