### ISSUE TITLE
[Mount] Subdued Seahorse  (Poseidus Mount)

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#2993]
**Links:**
https://www.wowhead.com/spell=98718/subdued-seahorse#comments:id=1377008
from WoWHead or our Armory

**What is happening:**

The speed of the mount in Vashj'ir is lower than 270% (more like 180-200%) and it's speed in other areas is like 5%. Using it in other areas is like swimming without the mount.

**What should happen:**

The mount should have 270% speed in Vashj'ir and 108% speed in other areas.

**Comment by Echinaceax** [comment]
odd this ID in dev says wrong ID , need correct ID please if you could look on the item (using addon IDTip)

**Comment by Rushor** [comment]
this is more spell and general mechanic related, will asign yu @Keader :)

**Comment by Keader** [comment]
Same of https://github.com/WoWManiaUK/Blackwing-Lair/issues/3785
