### ISSUE TITLE
[Dungeon/NPC] Old Hillsbrad Foothills - Epoch Hunter

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#2996]
**Links:**
Don't have screenshot because it dissapeared 1-2 minutes after I was trying to attack him..
from WoWHead or our Armory
https://www.youtube.com/watch?v=N6QzpEkS3tU
https://www.wowhead.com/old-hillsbrad-foothills

**What is happening:**

Epoch Hunter can't be attacked. It's the last boss so the dungeon can't be finished without him.

**What should happen:**

Epoch Hunter should be attackable.

**Comment by georgeapostolov** [comment]
It's maybe a new bug, I have Heroic and Non-Heroic achievements, killed Epoch Hunter every time.

**Comment by Denrunmt** [comment]
Yeah, it could be.

**Comment by Rushor** [comment]
okay flags adjusted, so that he can be killed again.
