### ISSUE TITLE
[Zone] Eversong Woods/Ghostlands

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#2999]
**What is happening:**
The problem is you cant use the fly mounts in those zones
https://imgur.com/RYOZrK3
https://imgur.com/7AS78El
https://imgur.com/tKNNxWK
P.S : I have all riding skills
**What should happen:**
You should fly in this zones

**Comment by sarahkay88** [comment]
https://wowwiki.fandom.com/wiki/Flight_Master%27s_License

**Comment by Sammy974** [comment]
If i remeber well, those zones were no-fly zones in retail too.

**Comment by sarahkay88** [comment]
Yup it's suppose to be this way

**Comment by sarahkay88** [comment]
https://wow.gamepedia.com/Flight_Master%27s_License

**Comment by sarahkay88** [comment]
@Sammy974 hey can you contact me on discord please its angel
