### ISSUE TITLE
[Spell] Wild Mushroom: Detonate ID:88751

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Blackwing-Lair#3]
![image](https://user-images.githubusercontent.com/14857593/36740608-2dbe6a88-1bf8-11e8-931d-e270723bf3ef.png)

**How it works:** 
- The spell doesn't work.

**How it should work:**
- Should Detonates all of your Wild Mushrooms, dealing 1 Nature damage to all nearby targets within 6 yards.

**Comment by fvicaria** [comment]
I need the exact spell id and the context of the use, quest, item etc
