### ISSUE TITLE
[NPC] Spirit Healer Missing - Stagecoach Crash Site  - Gilneas

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#300]
The grave yard at stagecoach crash site has no spirit to ress you. unable to find zone id
![world of warcraft 28_12_2018 16_07_21](https://user-images.githubusercontent.com/42302580/50520977-35d7ad80-0abb-11e9-95ab-729502714de3.png)

**Comment by sarahkay88** [comment]
has far has I could find yes the only grave yard in this questing area has the area is small. but like you say running back wasn't an issue.

**Comment by Rushor** [comment]
added in phase 186
![I](https://i.imgur.com/xwY245E.jpg)
