### ISSUE TITLE
[NPC] Mylune - ID 39930 - quest interaction - Mount Hyjal

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#3000]
**Links:**
NPC: https://www.wowhead.com/npc=39930/mylune

**What is happening:**
After #239 its not possible to accept the quest from her. If you right click nothing happens.
![Save the animals](https://user-images.githubusercontent.com/18005338/62535186-166fe280-b84b-11e9-863f-58ed09179579.png)

**What should happen:**
You should be able to accept the quest from her.

**Comment by Rushor** [comment]
gossip interaction fixed again
