### ISSUE TITLE
Paladin's spell ( Holy Wrath as Damage) ID : 2812

### ISSUE THREAD

**Issue by Zul7030** [WoWManiaUK/Blackwing-Lair#3001]
![WoWScrnShot_080619_171433](https://user-images.githubusercontent.com/53161918/62543320-c440b880-b86e-11e9-836f-258c290bfce8.jpg)

**what is happening :Holy Wrath's damage is not divided among the nearby mobs as the spell says**

**What should happen :Holy wrath's Damage must be divided among the mobs:**

**Comment by APTX4869s** [comment]
The damage isn't divided, still doing the same damage to all targets in live server.
