### ISSUE TITLE
[quest] Rifle the bodies

### ISSUE THREAD

**Issue by Wojtek92** [WoWManiaUK/Blackwing-Lair#3002]
**Links:**
https://www.wowhead.com/quest=12000/rifle-the-bodies
https://www.wowhead.com/item=35783/moonrest-gardens-plans

**What is happening:**
there is no drop q item from dead bodies  

**What should happen:**
q item should been picked up from dead bodies

**Comment by Echinaceax** [comment]
the item is reported #2457
seems its regressed somehow thanks @Wojtek92

**Comment by Kitzunu** [comment]
Item Moonrest Gardens Plans has a 10% drop chance from item Mage Hunter Personal Effects
 http://cata.cavernoftime.com/item=35783

**Comment by rzenne** [comment]
This quest seems to be having the same problem again

**Comment by Echinaceax** [comment]
reopening this one #2457
