### ISSUE TITLE
[Talent/Holy Paladin] Speed of Light

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#3007]
**What is happening:**
Its not giving move speed , dunno about haste maybe dosent give the haste also
https://imgur.com/tfu1Lfd
https://imgur.com/bE8kgsR
https://imgur.com/vcrr5cR
**What should happen:**
After casting Divine Protection it should give 60% move speed for 4 seconds

**Comment by Sammy974** [comment]
Still not giving the 60% movement speed after casting Divine Protection.
The 3% haste is fine.

https://wow.gamepedia.com/Speed_of_Light_(paladin_talent)

**Comment by Keader** [comment]
Fixed.
I forgot to send part of fix.
