### ISSUE TITLE
[Quest] To Greymane Manor - 14465- Gilneas

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#301]
Quest - https://www.wowhead.com/quest=14465/to-greymane-manor
NPC - https://www.wowhead.com/npc=36452
Location - Gilneas
NPC - https://www.wowhead.com/npc=36606 is not in the correct place so unable to hand in quest
![world of warcraft 28_12_2018 16_19_12](https://user-images.githubusercontent.com/42302580/50521339-193c7500-0abd-11e9-97c3-c9af21c99be7.png)
She should be just stood on the stairs.

**Comment by Dranah** [comment]
This might be just phasing issue since you still have "I can't wear this" in your log.
There is a general problem with quest orders and phasing in cata zones so if you have to skip or ask for interference by phoenix, chances are some follow-ups will get screwed up too.

**Comment by sarahkay88** [comment]
ha maybe I didn't get any assistance I died and when I ran back to my corpse the top gates were open so I could access the manor.

**Comment by Dranah** [comment]
Well we'll get back to this one if the prequests are fixed, and see if the NPC is still not visible.

**Comment by Echinaceax** [comment]
notice its link "now" to main issue finally 
hopefully it will be sorted really soon @sarahkay88

**Comment by Frostmanx** [comment]
I have completed the full quest chain upto https://www.wowhead.com/quest=14465/to-greymane-manor 
and I have the same problem and cannot see the npc=36606 who is in (Phase-184) to hand in the quest!

![WoWScrnShot_052819_200153](https://user-images.githubusercontent.com/50195620/58487717-b6dbc380-8185-11e9-851a-08b39dfc9637.jpg)

**Comment by Dranah** [comment]
So this is the roadblock now?

**Comment by Frostmanx** [comment]
Yup right now this is it :)

**Comment by Dranah** [comment]
Confirmed, phasing issue. She is there in phase 184, I have no idea what phase the player is in at this point, can you do a .gps Frostmanx?

**Comment by Dranah** [comment]
NPC ID https://www.wowhead.com/npc=36606/queen-mia-greymane

**Comment by Frostmanx** [comment]
I already completed this quest using (gm on) to see if the rest works, now I am further away.

**Comment by Dranah** [comment]
Silly you indeed. Now I have to go through the worgen chain >.>

**Comment by Rushor** [comment]
please someone could tell me the phase id of the player then - thank you. Call me on discord then <3

**Comment by Rushor** [comment]
fixed that so far - everything else with pahsing in a new issue then please :)
