### ISSUE TITLE
[Object] Bitterblossom

### ISSUE THREAD

**Issue by georgeapostolov** [WoWManiaUK/Blackwing-Lair#3010]
https://www.wowhead.com/quest=25297/from-the-mouth-of-madness

**What is happening:**
Bitterblossom is phasing out when you approach Shrine of Goldrinn.

**What should happen:**
Bitterblossom should not be phasing out.

![image](https://user-images.githubusercontent.com/5627962/62675936-c2cbd900-b9b1-11e9-8155-5efad5b5aa75.png)

![image](https://user-images.githubusercontent.com/5627962/62675960-ceb79b00-b9b1-11e9-80c5-4fb0d550156c.png)

**Comment by Rushor** [comment]
issue moved to https://github.com/WoWManiaUK/Blackwing-Lair/issues/2846
