### ISSUE TITLE
[Profession] Archaeology - Misc Issues

### ISSUE THREAD

**Issue by Z4but0m** [WoWManiaUK/Blackwing-Lair#3012]
- [x] [Profession] Archaeology - Vrykul Digsites

**Links:**
https://cata-twinhead.twinstar.cz/?item=64395
https://cata-twinhead.twinstar.cz/?item=36054

**What is happening:**
It seems as though the Vrykul digsites are not dropping keystones but instead Vizier gloves.

**What should happen:**

Vrykul digsites should be dropping keystones.

- [x] [Profession] Archaeology - Solved statistic (Bloodelf male)

Speaking with the members of my guild, we have verified that the appearance of rare / epic pieces, for some races, takes place every n attempts.
For example with the Trolls.
There are 2 rare pieces and one epic piece.
We noticed that the first rare piece appears around the 20th attempt and the second at 40 °. In fact, continuing, almost all have found the sword (the epic piece) around the 60th.
(I was able to see for myself. I was at a friend's house and he released the Sword at exactly 60!)
I also found the first piece at 20 ° and the second at 40 ° (approximately).
I managed to solve 203 pieces and the sword hasn't come out yet; this means around 160 common consecutive pieces.
With the Dwarves the subject is the same, the difference is that the rare pieces are 3 so the epic piece reaches around 80 ° (in fact with the dwarves we find a little more than 20 between one and the other).
With the Dwarves I came to 171. About 100 consecutive common pieces.

Why am I reporting the problem as Bloodelf male?
Because, since there is a problem with fishing (already reported) that I have skilled thanks to the Potion of Illusion (really !!) and that now I find myself with 693/715 (at 521 the next increase was +172!) , I think there may also be a problem with Archeology.
Or at least I hope so, otherwise it means I'm very unlucky.
But really so much!!

- [x] [Currency]Fossil Archaeology Fragment
**Links:**
https://www.wowhead.com/currency=393/fossil-archaeology-fragment

**What is happening:**
fossil fragments dont drop from survey.well the survey works but if u pick it up u get no fragments.

**What should happen:**
u shoud get fossil fragments from survey
@Rushor this https://www.wowhead.com/currency=393/fossil-archaeology-fragment, when you dig fossil sites, and you find the https://www.wowhead.com/object=206836/fossil-archaeology-find and use it, nothing is looted as it should give you 4-9 archaeology fragment just like all the other archaeology races.

this video timestamp explain it further https://youtu.be/Ikqtg8tWAu8?t=3

- [x] [profession] Archaeology - missing nerubian crafting
**Links:**

https://www.wowhead.com/currency=400/nerubian-archaeology-fragment#projects

**What is happening:**

when you collect nerubian fragments its not showing up in your archaeology profession window to show wht you will be crafting next

**What should happen:**

the very first time you collect any fragment your archaeology window should show you what your able to craft  before you collect enough fragments,  this should show up on the very first time you loot a fragment of each race

- [ ] [Profession] Archaeology digsites in zones not suitable for player level
**Links:**
https://wow.gamepedia.com/Archaeology

**What is happening:**
Digsites are appearing in zones not suitable for player's level, meaning they cannot be dug until very high level.
e.g. at level 20, I received sites in Badlands (40+), EPL (45+), Azshara & Ungoro (50+) and even Twilight Highlands (80+)
![InkedWoWScrnShot_092119_171813a_LI](https://user-images.githubusercontent.com/46089380/65376214-46593500-dc95-11e9-82ad-a390815e4f89.jpg)
![InkedWoWScrnShot_092119_172146a_LI](https://user-images.githubusercontent.com/46089380/65376215-46593500-dc95-11e9-8a86-6960edace358.jpg)

**What should happen:**
https://wow.gamepedia.com/Archaeology
> As related by Ghostcrawler:[5]
Archaeological dig sites...
**Your dig sites appear in level-appropriate zones.** Players will not be able to survey in Outland, Northrend or any of the Cataclysm zones until they have reached the minimum level to enter those zones.

**Comment by Rushor** [comment]
can you give me some more infos on that? which object should drop that?

**Comment by Z4but0m** [comment]
https://www.wowhead.com/currency=399/vrykul-archaeology-fragment

Whenever you unearth a Vrykul arch fragment (refer to the wowhead link above), theres a chance for them to drop Vrykul Rune Sticks.

**Comment by Nirvanum** [comment]
@Rushor 
Okay, you want to compact Archeology problems, but at least do it with argued problems. Not that I open a 3d to see it closed immediately without anyone discussing it.
Please open it again and wait before moving it here.

**Comment by TheSale** [comment]
can we get fix on this?

**Comment by sarahkay88** [comment]
Not that I open a 3d to see it closed immediately without anyone discussing it.
Please open it again and wait before moving it here. --- so what is it u are asking for? for rushor to keep you issue open 1hr/2hrs before he closes it? its not like he was ignoring you hr just moved them all into one report.

**Comment by Rushor** [comment]
i only move all of them to once central report. this is a big problem i know and thank you for your reports.

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/issues/23702

**Comment by Rushor** [comment]
Fossil Archaeology Find will contain Fossil Archaeology Fragments with the next update https://i.imgur.com/aFDprAb.jpg

The zone rescrition will be done later.

**Comment by Rushor** [comment]
[Profession] Archaeology - Vrykul Digsites also fixed. they drop http://cata.cavernoftime.com/item=64395 now.
![I](https://i.imgur.com/efDzSTh.jpg)
