### ISSUE TITLE
[Talent/Resto Shaman] Ancenstral Healing

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#3015]
**Links:**

https://imgur.com/WzygWn1

**What is happening:**
https://imgur.com/4fGQ5MI ( Min. HP gain )
https://imgur.com/OA8g4td { Max HP gain )
Not giving the hp bonus of 10% not even 5% and also it resets if you are healing more 
**What should happen:**
It should give 5% of theyr HP to a maxium of 10% ( 10% from 100+k its around 10k hp not 1.300 or 132 )

**Comment by Keader** [comment]
Wrong.
Spell should add in your health = 5/10% of amount healed, with cap in 10% of your max health.
It was "working before".
Problem was:
In rank 1 - it was considering 5% of your max health, and need be always 10%.
Looks like Health need accumulate, until 10% max health cap, and it was reseting.

**Comment by kDracku** [comment]
But it says it increases 5% of my healing done to an ally up to a 10% , sometimes my greater healing is over 75k and my taget gets max 1.300 hp gain
