### ISSUE TITLE
[Quest] The Ultrasafe Personnel Launcher - ID 25839- Dun Morogh

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#302]
Quest - https://www.wowhead.com/quest=25839/the-ultrasafe-personnel-launcher
NPC - https://www.wowhead.com/npc=41363
The launcher is meant to launch you to the next area to hand in the quest however it doesn't work.

![world of warcraft 29_12_2018 13_56_13](https://user-images.githubusercontent.com/42302580/50539083-118ad800-0b72-11e9-94b5-413f0856c2b3.png)

**Comment by Dranah** [comment]
Can you hand in the quest if you walk over there?

**Comment by sarahkay88** [comment]
TBH I never checked the map wasn't working but I can go back and try later and let you know,

**Comment by sarahkay88** [comment]
So I checked. you can run to required area. but because the quest requires you to use the launcher it doesn't activate the quest has being completed
![world of warcraft 29_12_2018 23_22_00](https://user-images.githubusercontent.com/42302580/50574198-4d74a600-0ddb-11e9-8129-4ec5c5465fd2.png)
NPC -https://www.wowhead.com/npc=41298

**Comment by sarahkay88** [comment]
So I checked you can walk there but because the quest requires you to use the launcher it doesn't activate the quest has completed. 
![world of warcraft 01_01_2019 15_37_04](https://user-images.githubusercontent.com/42302580/50574219-cffd6580-0ddb-11e9-8b4b-8bce631d6e89.png)
NPC -https://www.wowhead.com/npc=41298

**Comment by bagi84** [comment]
Yep can confirm quest doesn't work also checked area your meant to land and cannot complete quest

**Comment by Rushor** [comment]
fixed,

you get credit, you get lift off

![I](https://i.imgur.com/dcSDwFE.jpg)
![I](https://i.imgur.com/Pv0LfBJ.png)
