### ISSUE TITLE
[Glyph] Death Knight - Path of Frost

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#3023]
**Links:**
https://wow.gamepedia.com/Glyph_of_Path_of_Frost

**What is happening:**
Activating Path of Frost with this glyph and jumping down from high distance, you take the same amount of dmg than not activating it. It simply doesn't work at all. Tested in various situations and distances.

**What should happen:**
With this gliph, activating Path of Frost should allow you to fall from a greater distance without taking damage.

**Comment by kDracku** [comment]
Can confirm
