### ISSUE TITLE
[NPC] Whip lasher 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3026]
**Links:**
https://www.wowhead.com/npc=13022/whip-lasher

![infinate npc for herbing](https://user-images.githubusercontent.com/39439201/62823218-34ad4980-bb8f-11e9-9082-2bc451f9b439.jpg)

few mins later 

![endless whip lahters](https://user-images.githubusercontent.com/39439201/62823417-d08b8500-bb90-11e9-85ac-13b7d61dc57c.jpg)

**What is happening:**
- Infinate spawns

**What should happen:**
- Shouldnt spawn this many 

**reproduce**

stand on the green thing 

![stand here](https://user-images.githubusercontent.com/39439201/62823222-4ee72780-bb8f-11e9-89c8-97627df988f0.jpg)

**Comment by Eirolla** [comment]
@Echinaceax @Bathelmo there has plenty of them at this area. not only that green spot.

**Comment by Eirolla** [comment]
![6s8DxGOeHK](https://user-images.githubusercontent.com/26048748/62826080-35a99f80-bbbe-11e9-8ae4-20caf2478616.gif)
![gkdVyRtuam](https://user-images.githubusercontent.com/26048748/62826081-35a99f80-bbbe-11e9-86e6-fc0ad1d56520.gif)

**Comment by Rushor** [comment]
can you do .gps on one of the spawns? on dev i cannot repoduce this

**Comment by Rushor** [comment]
okay spawnamount reduced

**Comment by Echinaceax** [comment]
> can you do .gps on one of the spawns? on dev i cannot repoduce this

@Rushor sorry didnt see your question.

**Comment by Rushor** [comment]
okay refixed them https://i.imgur.com/D7jLGr3.jpg (by janitor)
