### ISSUE TITLE
[Profession] Technique: Glyph of Colossus Smash missing - Inscription

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#3027]
**Links:**
https://www.wowhead.com/item=68810/technique-glyph-of-colossus-smash
https://www.wowhead.com/npc=50248/una-kobuna
from WoWHead or our Armory

**What is happening:**
Una Kobuna doesn't sell this recipe, then the glyph is not available in game. 

**What should happen:**
Una Kobuna should sell the recipe in order to get the glyph. This glyph is very useful for warriors.

**Comment by Rushor** [comment]
item added
