### ISSUE TITLE
[DUNGEON] Shadowfang Keep: Teleporter Issue

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3029]
**Links:**

https://www.wowhead.com/npc=51400/haunted-stable-hand
![image](https://user-images.githubusercontent.com/26048748/62826680-43642280-bbc8-11e9-842c-078282f44e7f.png)

**What is happening:**

After killing the first boss of the instance, you can teleport directly to the second boss.

**What should happen:**

Teleporter should active second boss room teleport after killing the second boss.

**Comment by Rushor** [comment]
okay teleport now really works once the seconds boss is killed and all teleports will work now.
