### ISSUE TITLE
[Quest] Playing Dirty -  ID 27082 - Silverpine forest 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#303]
[Quest] playing dirty is not dropping the "quest item"
i have killed 28 and not one drop - Cant progress as this was the first quest in this area.

https://www.wowhead.com/quest=27082/playing-dirty

![im in right place](https://user-images.githubusercontent.com/39439201/50542502-1a55cb00-0bbf-11e9-9e20-db3f3a75aa21.jpg)

![playing dirty](https://user-images.githubusercontent.com/39439201/50542456-f5148d00-0bbd-11e9-916d-9680e3afa8cd.jpg)
![28 killed an still no quest item](https://user-images.githubusercontent.com/39439201/50542461-0198e580-0bbe-11e9-80aa-a37ae2cc3ba6.jpg)
![playing dirty quest](https://user-images.githubusercontent.com/39439201/50542464-05c50300-0bbe-11e9-8230-45beb4de5a73.jpg)

**Comment by Dranah** [comment]
https://www.wowhead.com/item=60793/diseased-organ

**Comment by Echinaceax** [comment]
sorry i missed that SS, 
![diseased organ](https://user-images.githubusercontent.com/39439201/50575813-6a25d380-0e05-11e9-9e52-8056c3c205fc.jpg)
