### ISSUE TITLE
[DUNGEON] Shadowfang Keep: Last Boss Pulling Issue

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3030]
**Links:**

https://www.wowhead.com/npc=46964/lord-godfrey
![image](https://user-images.githubusercontent.com/26048748/62826713-ca18ff80-bbc8-11e9-83b8-245c9698581b.png)

**What is happening:**

Lord Godfrey can be pulled to before to the last room. (Can skip adds on last room.)

**What should happen:**

Lord Godfrey should reset when players out of the last room.

**Comment by Rushor** [comment]
if too far away (50 xards fro  homespot) it will reset now
