### ISSUE TITLE
[Guild] View: Professions

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#3031]
**What is happening:**
The professions aren't displayed in the guild window. 
![WoWScrnShot_081119_002617_2](https://user-images.githubusercontent.com/45459932/62827432-e750cc80-bbce-11e9-9ad6-c545a10a845d.jpg)

**What should happen:**
In that window, you should be able to see the professions of every component of the guild.

**Comment by Echinaceax** [comment]
@Sammy974 what addons are you using? Try disabling addons and see if its the same

**Comment by Sammy974** [comment]
I'm using ElvUI, but it's not displaying using the default blizzard UI as well.

![WoWScrnShot_081119_195804_2](https://user-images.githubusercontent.com/45459932/62837702-c8a41180-bc72-11e9-8c3a-94a9414c2441.jpg)

**Comment by Kitzunu** [comment]
Reason https://github.com/WoWManiaUK/Blackwing-Lair/issues/3165

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/71203863-1d017280-229f-11ea-8dab-bcc22e95621a.png)

Works. Fixed from the issue I mentioned above

**Comment by Rushor** [comment]
epic :o
