### ISSUE TITLE
[Profession] Enginnering

### ISSUE THREAD

**Issue by Rozjebavac** [WoWManiaUK/Blackwing-Lair#3034]
**Links**
There is a link where you can see those tinkets https://wow.gamepedia.com/Tinker_(engineering)

**What is happening:**
![WoWScrnShot_081119_130505](https://user-images.githubusercontent.com/53995281/62833077-05ebad80-bc39-11e9-9c92-f0ee85a809ec.jpg)
You do not get cata tinkets that should be automaticly learned when you reach some point of skill in Enginnering.

**What should happen:**
![WoWScrnShot_081119_131223](https://user-images.githubusercontent.com/53995281/62833146-fa4cb680-bc39-11e9-9144-f7cd0350c31f.jpg)

**Comment by Echinaceax** [comment]
i see this is already reported and linked #2416
I'll close this as we dont wan to be working on duplicates 
(sometimes key workings dont show so be careful on duplicates) 

@Rushor - see which you find more info on
