### ISSUE TITLE
[DUNGEON] Deadmines: Teleport bug.

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3035]
**Links:**

No link.

**What is happening:**

After killing Helix Gearbreaker, you can teleport to the next area of dung (wide ship room).

**What should happen:**

You should not pass that area without killing Foe Reaper 5000.

A screenshot will be uploaded soon.

**Comment by Rushor** [comment]
object 208002

**Comment by Rushor** [comment]
problem is that the last gossip does not check the endboss for teleport, but instead only checks the death of ToeReaper. will change that.
