### ISSUE TITLE
[Quest] Twilight Documents - ID 28815 - Stonecore

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#3036]
**Links:**
https://www.wowhead.com/quest=28815/twilight-documents
from WoWHead

**What is happening:**
The document appears in the ground only for a moment and it can't be collected.

**What should happen:**
You should be able to collect the document from the ground right before the first boss in order to complete the quest.

**Comment by Rushor** [comment]
this is wonky because milhouse get knocked back.

will add a static spawn here: 

![I](https://i.imgur.com/d8N1rYV.jpg)
