### ISSUE TITLE
[NPC/Daily] Alegorn <Cooking Trainer> (issue 3)

### ISSUE THREAD

**Issue by Chicozoba** [WoWManiaUK/Blackwing-Lair#3040]
Links:

https://www.wowhead.com/npc=4210/alegorn

What is happening:

The cooking quests are not available with this cooking master.

What should happen:

One of the daily quests should be available.

**Comment by Echinaceax** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/1011#issuecomment-477812516

@Rushor you worked on this months ago , but i think you missed the update i posted :)
