### ISSUE TITLE
[Quest] Elemental Energy - ID 27136 - Deepholm

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#3041]
**Links:**
https://www.wowhead.com/quest=27136/elemental-energy
https://www.wowhead.com/item=60835/depleted-totem
from WoWHead or our Armory

**What is happening:**
Killing Energized Geodes or Lodestone Elementals near the Depleted Totem doesn't charge the totem. The progress of the quest isn't counted.

**What should happen:**
Killing Energized Geodes or Lodestone Elementals near the Depleted Totem should charge the Depleted Totem giving a progress to the quest.

**Comment by Sammy974** [comment]
P.S.: There are 2 Seer Kormo giving the same quest xD

**Comment by Randomplayerx** [comment]
Still not working & Every NPC is like doubled-trippeled spawned, same problems like Hyjal.

**Comment by Rushor** [comment]
duplicates removed and credit added.

place the totem, kill the questcreatures within 30 yards range, get credit.
you can only spawn one totem within 30 yards range.

![I](https://i.imgur.com/ojjPrNW.jpg)
![I](https://i.imgur.com/lVCXnFr.jpg)
