### ISSUE TITLE
[Quest] At the Stonemother's Call (issue2) - Deepholm

### ISSUE THREAD

**Issue by Chicozoba** [WoWManiaUK/Blackwing-Lair#3042]
Links:

https://www.wowhead.com/quest=26750/at-the-stonemothers-call

What is happening:
![image](https://user-images.githubusercontent.com/50930065/62875410-445d9700-bd23-11e9-84a7-f02f4ca29497.png)

You can't give back the quest to Therazane.

What should happen:

You should be able to give the quest back to Therazane to unlock Therazane's reputation.

**Comment by Sammy974** [comment]
Duplicate #2757
It was supposed to be fixed, btw.

**Comment by Sammy974** [comment]
N.B.: To talk with Therazane you need to be friendly with her faction. I was able to talk with her after reached the required reputation.

**Comment by Chicozoba** [comment]
You're right Sammy, but in order to be friendly with Therazane, you need to complete this quest ;)

**Comment by Sammy974** [comment]
"I was able to talk with her after reached the required reputation" then nope. You have other ways to get the reputation you need. Once you're friendly, you can talk with her.

**Comment by Echinaceax** [comment]
@Sammy974 
so no issue here then?

**Comment by Kitzunu** [comment]
fixed

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/63304600-dd704d00-c2e3-11e9-92b4-cb1e9b03d0d7.png)
