### ISSUE TITLE
[Spell] Shooting Stars proc

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#3044]
ID 93399

Effect does not proc off the instant damage portion of Moonfire, currently.

**How it should work:** It should proc off any damage dealt by Moonfire or Insect swarm, including the instant damage portion of Moonfire.

**How it works atm:** Properly procs off DoT ticks from Moonfire or Insect, but does not proc off the instant damage of Moonfire.

PS: it was changed later on MOP so that the talent only procs off periodic damage, but on cataclysm it should be triggered by the direct damage of Moonfire aswell.

**Comment by Dranah** [comment]
Additionally, the effect should proc also when Moonfire is morphed into Sunfire, and it currently does not.

**Comment by Keader** [comment]
It should only proc with dot.
Added sunfire possibility of proc.

**Comment by Sammy974** [comment]
@Keader  pls check on it, because now there is no proc at all.
Here you can see the ticks of the abilities, the talent didn't proc once in all the record time.

![WoWScrnShot_082719_171642](https://user-images.githubusercontent.com/45459932/63789523-d5be3300-c8f7-11e9-86a1-ed4c4d6a3946.jpg)
