### ISSUE TITLE
[Spell] Swift Flight Form unlearns riding skills

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#3045]
Spell ID 40120

**How it works atm:**
The spell is learnable without requiring you to have already learned Artisan Riding skill (300), which is not intended.
Once learned, the spell cannot be used however, since you don't have the required riding skill.
The real issue is, however, if you learn it before learning the flying skill, upon next relog, your character unlearns all the previous riding skills it had, and you have to re-learn them again.
Note: you do not unlearn the regular flight form anymore, that was fixed, it's the riding skills your character forgets (apprentice, journeyman etc)

**How it should work:**
The spell should require at trainer that you already have Artisan Riding (300) purchased in order to learn. 
Then, if you learn it, you should be able to use it and you should never by any means lose your riding skills you already learnt.

STEPS TO REPRO:
1) Learn ground mount skills 
![WoWScrnShot_081219_184411](https://user-images.githubusercontent.com/31132743/62881962-3adb2b80-bd31-11e9-9f44-3a27d15484d9.jpg)
2) Learn reg flight form (this one is free), teaching you the expert skill as intended now (was fixed before)
![WoWScrnShot_081219_184506](https://user-images.githubusercontent.com/31132743/62882051-5d6d4480-bd31-11e9-8d8c-164a129f5d90.jpg)
3) Learn Swift flight form which has no requirements at all 
![WoWScrnShot_081219_184555](https://user-images.githubusercontent.com/31132743/62882090-6f4ee780-bd31-11e9-94ea-133f16c9070a.jpg)
4) Riding trainer in dal, before relog (only have artisan left to learn):
![WoWScrnShot_081219_184638](https://user-images.githubusercontent.com/31132743/62882157-91486a00-bd31-11e9-8c37-e0288f2ecd4f.jpg)
5) Riding trainer in dal, after relog (need to re-learn all the skills, LOL):
![WoWScrnShot_081219_184720](https://user-images.githubusercontent.com/31132743/62882202-a7562a80-bd31-11e9-8204-e923b2c8e350.jpg)

**Comment by Keader** [comment]
Now will need riding 300 to learn Swift Flight Form, like wotlk.
