### ISSUE TITLE
[Talent/Spell] Unholy DK - Ebon Plaguebringer

### ISSUE THREAD

**Issue by Z4but0m** [WoWManiaUK/Blackwing-Lair#3048]
**Links:**
https://cata-twinhead.twinstar.cz/?spell=51160

**What is happening:**
The 30% increased disease damage is not being added to the Deathknight's diseases, and the 8% increased magical damage is not being added to the Deathknight's other abilities which use shadow/frost or other forms of magic damage.
(Evidence in the pictures below)

**What should happen:**
Ebon Plaguebringer should be increasing the damage of diseases by 30% and the damage dealt by all other sources of magic, including the deathknights own magic damage by 8%.

**Comment by Z4but0m** [comment]
![IceTouchEbon](https://user-images.githubusercontent.com/52716599/62913416-f4e68d80-bd59-11e9-8a53-6716c37b51ca.png)

![PlaguestrikeEbon](https://user-images.githubusercontent.com/52716599/62913429-fdd75f00-bd59-11e9-93b3-78f593510683.png)

This is how much damage these abilities should be doing with the added bonus damage from Ebon Plague (Tested with no gear, Normal level 40 Zweihander from Orgrimmar.)

**Comment by Z4but0m** [comment]
![Wow_2019-08-12_23-31-35](https://user-images.githubusercontent.com/52716599/62913476-3119ee00-bd5a-11e9-86a1-35651186f845.png)

However, this is how much damage these abilities do. 
(Tested with no gear, Normal level 40 Zweihander from Orgrimmar.)

**Comment by Dranah** [comment]
The talent properly increases their damage.
The attack power scaling of the diseases seems wrong, which is why their damage is below the intended. Will open a report for both diseases to get their AP coefficient fixed.

**Comment by Z4but0m** [comment]
![IceTouchNoEbon](https://user-images.githubusercontent.com/52716599/62956103-475a9500-bdc0-11e9-99df-a3b0a657481f.png)
![PlaguestrikeNoEbon](https://user-images.githubusercontent.com/52716599/62956104-488bc200-bdc0-11e9-8584-6c0070c0dd47.png)

I also did tests with these two diseases without the Ebon Plague talent in the same environment (No gear, level 40 white sword)
The damage is supposed to increase with the ebon plague talent but it does not.
