### ISSUE TITLE
[Spell] Warrior Shouts

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#3049]
**What is happening:**
https://imgur.com/KWkMuR6
https://imgur.com/NIG03me
You can have both shouts from a single warrior 
**What should happen:**
You can have only one shout per warrior

**Comment by Kitzunu** [comment]
What are the spell ID's?

**Comment by kDracku** [comment]
Commanding Shout : 47440
Battle Shout : 47436

**Comment by Kitzunu** [comment]
Does it have dofferent ranks? Or always the same

**Comment by kDracku** [comment]
I dont have a warrior , but i guess they have ranks so i put the hightest rank of them
