### ISSUE TITLE
[NPC] lanthan Perilon - Aggression Quest - Sunstrider Isle

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#305]
[NPC] lanthan Perilon quest completed but the window stays open when completed the quest, i received quest reward but window stayed open after.
had to click it off manually by the **(x)**

www.wowhead.com/npc=15281/lanthan-perilon
www.wowhead.com/quest=8334/aggression

![quest comple and reward given but window stays open](https://user-images.githubusercontent.com/39439201/50543022-55113080-0bca-11e9-92d2-a28d430af279.jpg)

**Comment by Kitzunu** [comment]
works
