### ISSUE TITLE
[Class/Talent] Cruelty - Protection Warrior

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#3050]
**Links:**
https://wowwiki.fandom.com/wiki/Cruelty_(removed_warrior_talent)

**What is happening:**
The talent does not encreases the critical strike chance of Shield Slam.

**What should happen:**
The talent should increase the critical strike chance of Bloodthirst, Mortal Strike and Shield Slam by 10%

![WoWScrnShot_081319_125240_2](https://user-images.githubusercontent.com/45459932/62938165-c22aac80-bdce-11e9-94e9-5436370ed93e.jpg)

![WoWScrnShot_081319_125248_2](https://user-images.githubusercontent.com/45459932/62938169-c5be3380-bdce-11e9-9f50-13a59c259c65.jpg)

**Comment by Keader** [comment]
Working fine.
It's addon bug, not game one.
