### ISSUE TITLE
[Spell] Blood Plague

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#3056]
ID 59879

**How it should work:** DOT should receive 6,7% attack power coefficient per tick.
**How it works atm:** Only receives 6,25% attack power coefficient per tick.

**Comment by Ovahlord** [comment]
Actually the correct formular would be more 6,325% AP.
The entire formular looks like this: 
${$m1*1.15+$AP*0.055*1.15} 
This means, the default value is getting multiplied by 1.15 (15% bonus)
Then you add the AP * 0.055 * 1.15.

So from a real standpoint, the actual AP coefficient should be 6,325% while there should also be a 15% baseline damage bonus for Blood Plague

**Comment by Keader** [comment]
Just to remember:
```cpp
    void CalculateAmount(AuraEffect const* /*aurEff*/, int32 &amount, bool & /*canBeRecalculated*/)
    {
        // Formular: ${$m1*1.15+$AP*0.055*1.15}
        AddPct(amount, 15);
        amount += GetTarget()->GetTotalAttackPowerValue(BASE_ATTACK) * 0.055f * 1.15f;
    }
```

**Comment by Z4but0m** [comment]
Ovahlord, are you accounting for the talent Virulence?

**Comment by Ovahlord** [comment]
@Z4but0m additional damage bonus effetcs such as talents and the mastery shadow damage bonus are independend from the default amount calculation.
The order is like this:  basevalue + coefficient + flat bonus * percent bonus.
Talents and mastery fall under flat / percent bonuses so they are applied after the coefficient part
