### ISSUE TITLE
[Dungeon] Magister's Terrace (Heroic)

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#3057]
**Links:**
![Screenshot_10](https://user-images.githubusercontent.com/52254524/62954490-2d3ca900-bdf8-11e9-9a81-23976885d3dd.png)

from WoWHead or our Armory
https://www.wowhead.com/magisters-terrace
https://www.wowhead.com/quest=29686/a-radical-notion
**What is happening:**

Can't enter Magister's Terrace on heroic difficulty due to "low level".

**What should happen:**

Got 85 level and did the quest "A Radical Notion" so I should be able to enter on heroic difficulty.

**Comment by Echinaceax** [comment]
@Rushor confirmed tested in dev yesterday we was both lvl85
