### ISSUE TITLE
[Spell] Unholy DK - Scourge Strike (Shadow)

### ISSUE THREAD

**Issue by Z4but0m** [WoWManiaUK/Blackwing-Lair#3058]
**Links**
https://cata-twinhead.twinstar.cz/?spell=55090

**What is happening:**
The overall damage of scourge strike seems to be far lower than it is. The direct cause of this, I am not certain, but I will provide some information below.

**What should happen:**
Scourge Strike's damage should be higher overall.

**Comment by Z4but0m** [comment]
![](https://puu.sh/E4KDg.png)

![](https://puu.sh/E4KCX.png)

**Comment by Z4but0m** [comment]
![](https://puu.sh/E4KEP.png)
Statistics done during the tests. Level 85 dummy, with Zin'Rohk equipped.

**Comment by Dranah** [comment]
The addon calculates the full damage of the ability, adding up both the physical and shadow damage portion with the full potency of modifiers it believes you have. On recount they are shown separate.

I could not find an issue with the physical portion, here's the math broken down to your stats:
4767-5715 melee damage x 1,45 = 6912-8286 + 906 = 7818-9192 damage for the physical portion before armor mitigation.
Your target dummy has approx 30% armor, pushing it down to 5,4k- 6,4k damage range.
You have only done 1 cast and it is at the lower range, should you do more, you'd probably get it averaged out around 5,9k.

However, there is indeed a problem with the Scourge Strike (shadow) portion of the spell.
I cannot really tell based on your screens how many diseases you had on the target, but in my tests with FF, BP and Ebon plague up (3 diseases total), the spell is still calculating damage as if I only had two.
This needs fixing.

**How it should work:** Scourge strike (shadow) should consider Ebon Plague as a disease on the target when calculating damage. 

**How it works atm:** SS (shadow) only considers your 2 dots as diseases when calculating damage despite Ebon plague also being present.

**Comment by fuzzydunlop** [comment]
I am uncertain if this counts as a disease as well, but I've got 1 point in Scarlet Fever talent, so cause another disease/plague. In total I have 4 active diseases/plagues.
