### ISSUE TITLE
[Spell/Warlock] Soul Harvest 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#306]
[Spell] Soul Harvest - Warlock spell 

![soul harvest](https://user-images.githubusercontent.com/39439201/50549075-078ed500-0c57-11e9-9cb4-7a7409f3865d.jpg)

![soul harvest spell](https://user-images.githubusercontent.com/39439201/50549043-9818e580-0c56-11e9-9656-55987cf8d5f9.jpg)

Regenerates life but doesn't give 3 soul shards 

![soul havest doesnt give 3 souls](https://user-images.githubusercontent.com/39439201/50549114-5a688c80-0c57-11e9-9de0-e92c083ba7f7.jpg)

**Comment by Keader** [comment]
Fixed on dev

**Comment by Echinaceax** [comment]
Thank you

**Comment by Dranah** [comment]
Still does not work to me

**Comment by Keader** [comment]
@Dranah Tested and working fine.
Remember, Dev realm is: dev.wow-mania.com
You are testing in "live" cata server

**Comment by Dranah** [comment]
Cannot connect to dev realm. At all.

**Comment by Dranah** [comment]
The spell now regens soul shards however too fast. It should regen 3 shards over 9sec = 1 shard every 3sec.
Currently, it regens 1 shard /sec which means you need to maintain channel only for 3seconds to regain all souls shards.

**Comment by Keader** [comment]
Fixed.
