### ISSUE TITLE
[Quest] Don't. Stop. Moving. - ID 26656 - Deepholm

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#3060]
**Links:**
https://www.wowhead.com/quest=26656/dont-stop-moving
https://www.wowhead.com/npc=42466/terrath-the-steady
from WoWHead or our Armory

**What is happening:**
You can't talk with Terrath.

**What should happen:**
You should talk with Terrath and escort Opalescent Guardians to safety.

![WoWScrnShot_081319_224109_2](https://user-images.githubusercontent.com/45459932/62975890-bdd8b080-be1b-11e9-9c84-dfb8ac7a1c4d.jpg)

**Comment by kDracku** [comment]
#3005
