### ISSUE TITLE
[Priest][Shadow] Twisted Faith

### ISSUE THREAD

**Issue by Noristel** [WoWManiaUK/Blackwing-Lair#3061]
**ID:** 47577

**What is happening:** This talent takes character's base spirit in the calculation of spirit to hit rating instead of only the spirit gained by items (gear) or effects (buffs), both ranks.

**What should happen:** The talent should only use the spirit gained from items or effects as tooltip states whenb calculating hit rating gain, not characters base spirit.

**Comment by Keader** [comment]
Fixed.
