### ISSUE TITLE
[GENERAL][DUNGEON] Random Heroic Valor point Weekly Reset not working

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3064]
**What is happening:**

Random heroic dungeon finder's rewards are not been reset for 9 days.

**What should happen:**

Random heroic dungeon finder's rewards must be reset every week. (Wednesday to Wednesday on blizzard)

**Comment by Eirolla** [comment]
Today (16.09.19 - Friday) Valor was been reset. But I think it must reset every Wednesday.

**Comment by Echinaceax** [comment]
> Today (16.09.19 - Friday) Valor was been reset. But I think it must reset every Wednesday like Blizzard.

Ive removed the high prio now as its only a tweek this needs (for now its fridays)

**Comment by Eirolla** [comment]
Last reset date was 16/august/2019, today (23/august/2019) Valor cap has not been reset.

**Comment by Slydee23** [comment]
Complete broken now resets everyday

**Comment by wow-mania** [comment]
Resets only Wednesdays at 6am. Works fine.

**Comment by Slydee23** [comment]
got no reset today. My last reset was 02.10.2019 around 9 am server time

**Comment by Echinaceax** [comment]
This need fixing @Rushor - please confirm

**Comment by Slydee23** [comment]
http://prntscr.com/pgug43

**Comment by Slydee23** [comment]
any progress cause tomorrow should be reset day

**Comment by Keader** [comment]
I tested with Janitor and may we find the reason.
But in any case, i implemented a new command for GMs.
Now, even if automatic reset not work, GMs can manually reset it.

**Comment by Rushor** [comment]
epic move keader!
