### ISSUE TITLE
[NPC] Kezzik the Striker (issue 2) - area 52 Netherstorm

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#3066]
**Links:**

http://cata-shoot.tauri.hu/?npc=54650#sells:300+1

**What is happening:**

At the moment, Kezzik the Striker only sells weapons.

**What should happen:**

Kezzik the Striker should sell all the gear from BC, Gladiator, Merciless and Vengefull.
From Weapons, to set and hors-sets

http://cata-shoot.tauri.hu/?npc=54650#sells:300+1

**Comment by Echinaceax** [comment]
https://wow.gamepedia.com/Kezzik_the_Striker

**Comment by mfranca0009** [comment]
There are MULTIPLE versions of this NPC, need to know which one I'm fixing and/or if all of them need to be fixed.. @Echinaceax 

http://cata.cavernoftime.com/?search=Kezzik+the+striker
https://cata-twinhead.twinstar.cz/?search=kezzik+the+striker

**Comment by Echinaceax** [comment]
this one @mfranca0009 https://cata-twinhead.twinstar.cz/?npc=54650

i will double check when PTR is up

**Comment by Echinaceax** [comment]
as a mage i see all sets 
 Gladiator, Merciless and Vengefull.

![glad](https://user-images.githubusercontent.com/39439201/107856516-f0a4a000-6e28-11eb-8929-0a2af31b1576.jpg)
![merc](https://user-images.githubusercontent.com/39439201/107856518-f306fa00-6e28-11eb-8c0e-82d976f4d310.jpg)
![veng](https://user-images.githubusercontent.com/39439201/107856519-f4382700-6e28-11eb-8512-c138310e6b4f.jpg)

need to know class @Cenasty was using ..though i think they was a clothie when they playered here
