### ISSUE TITLE
[Dungeon] Issue upon entering an instance/dungeon

### ISSUE THREAD

**Issue by Z4but0m** [WoWManiaUK/Blackwing-Lair#3069]
**Links:**
N/A.

**What is happening:**
After accepting a dungeon queue for Stonecore, my client crashed. After relogging, I was in Dalaran (The current location of my Hearthstone) without a group and unable to see whispers from any group members or see whispers I sent to them. To them I am either dead or offline when I was walking around in Dalaran/Orgrimmar. Relogging seems to have no effect on this bizarre state; even multiple attempts to relog did nothing to fix this issue.

**What should happen:**
N/A.

**Comment by Z4but0m** [comment]
![unknown (1)](https://user-images.githubusercontent.com/52716599/63205314-99294680-c070-11e9-8447-5964d65e5fb7.png)

**Comment by kDracku** [comment]
Can confirm and its not only stonecore , it can happen anywhere. My guldie DC in middle of a rhc an get the same result. He was offline/dead on the party screen but he was in Ogrimmar online. - https://imgur.com/zKVopSa

**Comment by Echinaceax** [comment]
Update, We did stonecore many times recently 
could be fixed now with the newest client release 1.1.0 
_so make sure you Download the newest client_ 

i will close this as i see no issue with this now
