### ISSUE TITLE
[Guild] Guild disappear

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#307]
I am GM of guild ``Sensation`` and I got invite to another guild, while I was in my own guild.
I declined but then I appear guildless, I no longer have guild menu and guild banner, when I want to go to guild vault it say I am not in guild and when try open guild menu it open Guild finder
![screenshot_14](https://user-images.githubusercontent.com/20323863/50549014-1d4fca80-0c56-11e9-8752-f41bba2fca39.png)
![screenshot_15](https://user-images.githubusercontent.com/20323863/50549015-204abb00-0c56-11e9-852f-6a98b8cce18b.png)

when I relog it go back to normal, however, when I got invited to another guild again it show same issue.
![screenshot_16](https://user-images.githubusercontent.com/20323863/50549028-58ea9480-0c56-11e9-96d0-9147cab51dc6.png)

**Comment by Dranah** [comment]
If this is steadily reproduced, it is high prio.

**Comment by sarahkay88** [comment]
reopening this just happened to me and when i declined i got removed from the guild i am in

**Comment by Echinaceax** [comment]
@Dranah @Rushor 
x2 of our guild member just got this same issue

**Comment by sarahkay88** [comment]
> @Dranah @Rushor
> x2 of our guild member just got this same issue

yup everyone online in the guild has same issue

**Comment by Kitzunu** [comment]
Fixed
