### ISSUE TITLE
[DUNGEON] Throne of the Tides: Commander Ulthok Spawn

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3071]
**Links:**

https://www.wowhead.com/npc=40765/commander-ulthok  --> "link1"
https://www.wowhead.com/npc=40586/lady-nazjar --> "link2"

**What is happening:**

So, yesterday I was in the group of ToTT, while we going for Lady Nazjar(Link2), Commander Ulthok spawned from nowhere. 

**What should happen:**

Commander Ulthok should not spawn before Lady Nazjar's death(more specifically after getting console's credits).

![image](https://user-images.githubusercontent.com/26048748/63209153-00351280-c0e6-11e9-9f46-62d8a6a9baf6.png)
Are they twins ?!? :p

**Comment by Eirolla** [comment]
It must be investigated how it got spawn cuz of he should not spawn before console's credits.

**Comment by kDracku** [comment]
It happens only on normal version

**Comment by Echinaceax** [comment]
already reported here #1903
