### ISSUE TITLE
[quest] tipping the balance (issue 1) - Uldum

### ISSUE THREAD

**Issue by Wojtek92** [WoWManiaUK/Blackwing-Lair#3074]
**Links:**
https://www.wowhead.com/quest=27431/tipping-the-balance
from WoWHead or our Armory
https://www.wowhead.com/quest=27431/tipping-the-balance
**What is happening:**
harrison jones doesn't go down to the chamber

**What should happen:**
he should go down to met him there

**Comment by Echinaceax** [comment]
Quest is doable tho (npc is in the wrong place atm) outside the tomb

and the next pick up also ok https://www.wowhead.com/quest=27624/after-the-fall

![image](https://user-images.githubusercontent.com/39439201/120660606-cafadf80-c487-11eb-9295-35b082b4596f.png)
