### ISSUE TITLE
[quest] from the mouth of madness

### ISSUE THREAD

**Issue by Wojtek92** [WoWManiaUK/Blackwing-Lair#3077]
**Links:**
https://www.wowhead.com/quest=25297/from-the-mouth-of-madness
from WoWHead or our Armory
https://www.wowhead.com/quest=25297/from-the-mouth-of-madness
**What is happening:**

bitterblosson is out of phase

**What should happen:**
it shouldn't be

**Comment by Echinaceax** [comment]
this item has been reported here  https://github.com/WoWManiaUK/Blackwing-Lair/issues/2846#issuecomment-520255824
