### ISSUE TITLE
[BOSS] Magmaw - Blackwing Descent

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3080]
**Links:**
https://www.wowhead.com/npc=41570/magmaw

**What is happening:**
There is quite a few issues with this boss,
1) he is missing is head
2) mangle https://www.wowhead.com/spell=89773 this is picking the tanks up, but when it releases them it throws them into the lava and they die from the damage.
3) players cannot jump on to the head - vehicle bug - this prevented melee players from pinning pin the head down (using chains).
4) pillar of flame https://www.wowhead.com/spell=78006  there was no de-buff ( parasitic infection) on the party when casting the spell it was fast. 
5)Parasite could do with being checked there healing seams to much and they are very fast and cannot be slowed before reaching raid party, preventing the possibility of being able to AOE them down the pillars can be targeted and there is also an ignition targetable.

**What should happen:**

1) he should have his head.
2) Basically the tank will be on Magmaw's head, you will be able to tab target to Magmaw's head specifically, and continue attacking it for increased damage. You will be taking damage and need heals, but you will be released when your dps use the chains to hit Magmaw's head on the spike. tank should be placed back on the ledge and not into the lava
3) When "Magmaw slumps forward, exposing his pincers!",  melee players pin the head down (using chains) quickly. To do this, click Magmaw as if entering a vehicle. One action will be available, which causes a targeting circle to appear on the ground below the cursor (currently this cannot be done). Target the spike in the middle of the floor to attach the chain to the spike and pull Magmaw down onto it.
When the head is pinned down, you see "Magmaw becomes impaled on the spike, exposing his head!" and Phase 2 begins
4) there should be a de-buff  so players can slow them down and use AOE to kill them before the reach the party.

**Comment by Eirolla** [comment]
![image](https://user-images.githubusercontent.com/26048748/63226822-ce0bd980-c1e7-11e9-9744-011e3d252a1f.png)
Headless!

**Comment by Echinaceax** [comment]
@Rushor - list not fix

2. mangle https://www.wowhead.com/spell=89773 this is picking the tanks up, but when it releases them it throws them into the lava and they die from the damage.

2a when the two melee jump on the Magmaw and do their thing, when they leave the "vechicle" they still fall into the lava, giving a slow pain death :)

3. Magma Spit https://www.wowhead.com/spell=215754/magma-spit?dd=3
OP dmg gave 244k to each player

**Comment by Keader** [comment]
Fixed.
