### ISSUE TITLE
[Boss] Omnotron Defense System - Blackwing Descent

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3081]
**Links:**
https://www.wowhead.com/npc=42180/toxitron#comments

**What is happening:**
Nothing worked with this fight
1) the mobs healed faster than we could do damage
2) only two were killable with GM commands
3) they never moved
4)tank and spank didn't do any ability's even when we tried to kill them before using GM commands
5) **it stops the progression of the raid** because the gates wouldn't open without gm on

**What should happen:**
When the fight starts, only one mob will be active, and three stone golems will be frozen near it.  Like most council fights, there is a shared HP pool. you start by attacking the active one and when it reaches 50% energy a second one becomes active with 100% energy when this one hits 50% it will activate a shield and the next one become targetable shutting the first one down. and so on until the end of the fight
the activation is random, but it will always be one of the two that is is inactive

Golems have 100 Energy when first activated, and the way the Energy works is the same for all of them:
100 Energy= Golem just activated
50 Energy= Next Golem is activated
45ish Energy= Golem puts up his Shield
25ish Energy = Golem's shield falls
0 Energy = Golem is shut down, becomes stone and untargetable.
 (Zero energy on your current target means 50 energy on the other active golem, so a new golem will be active).
**Magmatron: abilities** -
Incineration Security Measure: Basic fire AOE. 
Acquiring Target: Picks a target, with a giant red laser to let you know who it is. After a few seconds, Magmatron Turns and blasts a cone of Fire AOE at the target. 
Barrier: This is his Shield, absorbs damage then nukes the raid if it takes too much.
https://www.wowhead.com/spell=78740 -activated
https://www.wowhead.com/spell=78726 -inactive
https://www.wowhead.com/spell=79023 -security measures
https://www.wowhead.com/spell=78746 shutting down
**Arcanotron: Abilities** -
Power Generator: Puts this down on the ground. Anyone in it gets a damage buff and mana regen buff. Don't let the boss stand in it. Think Steelbreaker from Ulduar. The fight being long, these are essential to healers getting mana back. 
Arcane Annihlator: Fast basic cast on anyone. Can be interrupted but is fast enough to be difficult to do so.
Power Conversion: This is his Shield. Each attack gives him a buff increasing his damage. Spell Stealabl
https://www.wowhead.com/spell=78740 - activated
https://www.wowhead.com/spell=79710  -arcane anhillitaor 
https://www.wowhead.com/spell=78726  - inactive
https://www.wowhead.com/spell=78746 -shutting down
**Toxitron abilities:**
Poison Cloud: anyone in it takes 50 percent damage, including the boss
Poison Protocol:  summons three slimes. These seek out random targets, and if they hit them, explode for massive damage. This can include Melee and the offtank, If it hits a target, it leaves a poison pool on the ground.  The adds don't have much HP and are pretty slow.
Poison Soaked Shell: This is his Shield.Each time you attack you get a stacking dot. However each stack causes you to inflict extra damage.
 https://www.wowhead.com/spell=78740 -activates
https://www.wowhead.com/spell=80157 -chemical boss
https://www.wowhead.com/spell=78726 -inactive
https://www.wowhead.com/spell=80053 -posion protocol
https://www.wowhead.com/spell=78746 -shutting down
**Electron abilties**
Single Target Ability - (Electrical Discharge) - Randomly targets a raid member and zaps them with a chain lightning for ~30k damage and jumps to up to three targets for +20% damage each jump. 
AoE Ability - (Lightning Conductor) - This is an ability that looks like an Ele Shaman's Thunderstorm. It will be cast on a random raid member... Including both tanks and any DPS. . It hits everyone within range for ~20k damage per second.
Shield Ability - (Unstable Shield) - This is his shield ability, and if too much damage is done to him while this is active it will do an empowered Electrical Discharge type thing. It's a raid wiper if this hurts anyone. It's ~60k damage per second to anyone in range.
https://www.wowhead.com/spell=78740 -activate
https://www.wowhead.com/spell=79879 -electrical discharge
https://www.wowhead.com/spell=78726 -inactive
https://www.wowhead.com/spell=79888 -lighnigh conductor
https://www.wowhead.com/spell=78746 - shutting down

**Comment by Echinaceax** [comment]
**Omnotron Defense System**
Still bugged 

1. we get too the last 2 golams down to 25-30% and they just dead without going down to 0% 
https://www.wowhead.com/npc=42166/arcanotron
https://www.wowhead.com/npc=42179/electron

2. no achv given either 

![achv bwd](https://user-images.githubusercontent.com/39439201/74094993-8efd7780-4aea-11ea-87b6-8da5d62507e0.jpg)

3.  Aquiring target works but the Flame thrower doesnt

![flamethrower](https://user-images.githubusercontent.com/39439201/74095019-f74c5900-4aea-11ea-984b-ae8a88031d44.jpg)

4. https://www.wowhead.com/spell=79710/arcane-annihilator?dd=3
OP dmg 

![arc](https://user-images.githubusercontent.com/39439201/74095157-1f3cbc00-4aed-11ea-9e04-b44727fb725a.jpg)


![power gen](https://user-images.githubusercontent.com/39439201/74095066-a5f09980-4aeb-11ea-857f-16d045cf6778.jpg)

https://www.youtube.com/watch?v=XFibqDGTezg

**Comment by Keader** [comment]
Fixed.

Only left the 6º issue.
Is not with me, is with rushor.

**Comment by Echinaceax** [comment]
@Rushor - Need to fix number 6 from my list
### Omnotron drops 4 items instead of two
