### ISSUE TITLE
[BOSS]  Atramedes - Blackwing Desecent

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3083]
**Links:**

https://www.wowhead.com/npc=41442/atramedes
**What is happening:**
This boss never spawned

**What should happen:**
The boss needs adding to the raid.

**Comment by sarahkay88** [comment]
Fix in #4174

**Comment by Keader** [comment]
better here lol

**Comment by Keader** [comment]
It's not in live yet, should not be closed
