### ISSUE TITLE
[Raid] Blackwing Descent - trash loot + Gold + Rep + Damage + Difficulty Check 

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3086]
**Links:**

https://www.wowhead.com/blackwing-descent#drops

**What is happening:**

just making a report for BOE drops within this raid and the % of drop rates, practically every trash mob dropped a BOE ITEM. Any guild running this raid will be geared after a first run through at this rate. This needs checking and amending before release

sorry didn't know how else to report it without doing each item individually - all loot drops are on the link.

**Comment by Sammy974** [comment]
Maybe you can add "trash loot" in the title, or it's too generic

**Comment by Rushor** [comment]
remember: do it like on bot release.

**Comment by Rushor** [comment]
added that
