### ISSUE TITLE
[Raid] The Bastion of twilight - trash drop

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3087]
**Links:**

https://www.wowhead.com/the-bastion-of-twilight

**What is happening:**
The loot drop from trash in this raid is to hight, practically every pack of mobs dropped a boe items, loot table and % drops need checking otherwise people will just farm trash, loot can be found on the link

**Comment by Echinaceax** [comment]
new report coming

**Comment by Xman993** [comment]
#3328
