### ISSUE TITLE
[Cinematic] Stuck

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#3090]
**Links:**
https://www.wowhead.com/quest=25272/lycanthoth-the-corruptor
**What is happening:**
After you kill Lycanthoth you get a cinematic and you are stuck into it till you ALT + F4
https://imgur.com/IRgBjFL
**What should happen:**
After cinematic all should go to normal

**Comment by Echinaceax** [comment]
report here #248
