### ISSUE TITLE
[NPC] Foreman Kaleiki -Dragonblight-

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#3091]
**Links:**
https://www.wowhead.com/npc=27238/foreman-kaleiki
**What is happening:**
Target its not attackble
https://imgur.com/JyOuMUN
**What should happen:**
Kill Foreman get the reward

**Comment by Kitzunu** [comment]
fixed

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/63304023-da745d00-c2e1-11e9-83d8-eab01d56a28e.png)
