### ISSUE TITLE
[RAID] Bastion of Twilight, Halfus Wyrmbreaker Fight: Time Warden (Drake) Time Dilation

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3094]
**Links:**

https://www.wowhead.com/npc=44600/  --> Halfus 
https://www.wowhead.com/npc=44797/time-warden
https://www.wowhead.com/spell=83601 -->Time Dilation

**What is happening:**

It should be tested, probably it's not being cast to Halfus.

**What should happen:**

It should be cast on Halfus when Time Warden Unchained.

**Comment by sarahkay88** [comment]
https://wow.gamepedia.com/Time_Warden#Abilities incorrect that ability isn't casted on  halfus its cast on Proto-Behemoth
Dragon's Vengeance  curses Halfus as it dies, causing Halfus to take 100% increased damage. This effect stacks.

**Comment by sarahkay88** [comment]
https://wow.gamepedia.com/Time_Warden#Abilities the spell linked doesn't get casted on the boss it get casted on his Halfus's Proto-Behemoth.
the ability Dragon's Vengeance is what he cast to curses Halfus as it dies, causing Halfus to take 100% increased damage. This effect stacks.
