### ISSUE TITLE
[NPC] Wooly Rhino Calf - Borean Tundra

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#3095]
**Links:**
https://www.wowhead.com/npc=25488/wooly-rhino-calf

![InkedScreenshot_14_LI](https://user-images.githubusercontent.com/52254524/63230381-79328800-c214-11e9-93c7-6faea0429a20.jpg)
![Screenshot_11](https://user-images.githubusercontent.com/52254524/63230383-7d5ea580-c214-11e9-9470-7a75b0c66786.png)
![Screenshot_13](https://user-images.githubusercontent.com/52254524/63230385-80599600-c214-11e9-8900-1dfcb40f3c1d.png)

**What is happening:**

The small Wooly Rhino Calf NPCs are dead in a group and sliding along the floor. First screenshot shows the areas where they spawn. They drop Rhino Meat which is used for cooking daily quests in Dalaran. 

**What should happen:**

The NPCs should be targetable and attackable.

**Comment by Echinaceax** [comment]
confirmed 
![woly confirmed](https://user-images.githubusercontent.com/39439201/63230601-34f0b900-c20f-11e9-9fac-18177d4086a6.jpg)

**Comment by Kitzunu** [comment]
Boy do I love this wonderful bug xD

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/63302391-40aab100-c2dd-11e9-9120-ce6e95e3328d.png)
