### ISSUE TITLE
[RAID] Bastion of Twilight, Halfus Wyrmbreaker Fight: Time Warden (Drake) Dragon's Vengeance

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3096]
**Links:**

https://www.wowhead.com/npc=44600/ --> Halfus
https://www.wowhead.com/npc=44797/time-warden
https://www.wowhead.com/spell=87683 --> Dragon's Vengeance

**What is happening:**

It needs to be tested, it is probably not happening.

**What should happen:**

When Time Warden killed, this effect must be on Halfus.

**Comment by Echinaceax** [comment]
team is retesting
