### ISSUE TITLE
[RAID] Bastion of Twilight, Halfus Wyrmbreaker Fight: Storm Rider (Drake) Cyclone Winds

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3097]
**Links:**

https://www.wowhead.com/spell=83612  -->Cyclone Winds
https://www.wowhead.com/npc=44600/  -->halfus
https://www.wowhead.com/npc=44650/storm-rider

**What is happening:**

Needs to be tested.

**What should happen:**

When the dragon unchained, it should be on Halfus.

**Comment by Echinaceax** [comment]
team is retesting
