### ISSUE TITLE
[RAID] Bastion of Twilight, Halfus Wyrmbreaker Fight: Storm Rider (Drake) Dragon's Vengeance

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3098]
Links:

https://www.wowhead.com/npc=44600/ --> Halfus
https://www.wowhead.com/npc=44650/storm-rider
https://www.wowhead.com/spell=87683 --> Dragon's Vengeance

What is happening:

It needs to be tested, it is probably not happening.

What should happen:

When Storm Rider killed, this effect must be on Halfus.

**Comment by Echinaceax** [comment]
team is retesting
