### ISSUE TITLE
[Quest] Learning the Word

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#31]
QuestID 14279
Worgen priest starter quest

No credit is given for using Flash heal on target NPCs.

**Comment by fvicaria** [comment]
Can you send me the NPC id that you have to heal please.

**Comment by Dranah** [comment]
http://www.wowhead.com/npc=47091
Btw the quest name was changed in Mists of Pandaria. Learning the Word does not exist on cata.
Also this quest still doesn't work.

**Comment by Dranah** [comment]
Works as intended now.
