### ISSUE TITLE
[NPC] Daschla - missing -  Silverpine Forest

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#310]
[Quest] unyielding-servitors is missing the NPCs in Silverpine Forest
https://www.wowhead.com/quest=27475/unyielding-servitors

![missing npc](https://user-images.githubusercontent.com/39439201/50549663-24c8a100-0c61-11e9-86a4-cb108ec56b89.jpg)

![missing npcs for quest](https://user-images.githubusercontent.com/39439201/50549673-4d509b00-0c61-11e9-9a1a-06dcdab2ac1c.jpg)

PS - if its a "faze thing" then the other reports of mine need to be fixed first or i cant progress in the undead questing areas

**Comment by Echinaceax** [comment]
funny thing is, is i am getting the quest item drops without having the quest. and they stack in 6s 

![havent the quest](https://user-images.githubusercontent.com/39439201/50550006-f1d5db80-0c67-11e9-856a-381c79f0f778.jpg)

![dropping quest items](https://user-images.githubusercontent.com/39439201/50550008-f601f900-0c67-11e9-9438-cdd126bfd569.jpg)

**Comment by Dranah** [comment]
Wait let me get this right.
There are no NPCs but you are getting the items to drop?
Is the quest possible to complete? If not, why is it not possible to complete given that you can acquire the quest items?

**Comment by Echinaceax** [comment]
not able to complete, don't have quest ..the kills from them mobs just continue to drop the quest item.
i searched on wowhead the item and that told me where the NPC should be ...no NPC found at the location.

**Comment by Dranah** [comment]
so the problem is the missing quest giver "Daschla"?

**Comment by Echinaceax** [comment]
correct yes

**Comment by Dranah** [comment]
https://www.wowhead.com/npc=45626/daschla
