### ISSUE TITLE
[RAID] Bastion of Twilight, Halfus Wyrmbreaker Fight: Slate Dragon (Drake) Stone Touch

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3100]
**Links:**
https://www.wowhead.com/spell=83603
https://www.wowhead.com/npc=44600/ --> Halfus 
https://www.wowhead.com/npc=44652/slate-dragon

**What is happening:**

Needs to be tested.

**What should happen:**

It should casted on Halfus when Slate Dragon Unchained.

**Comment by Echinaceax** [comment]
team is retesting
