### ISSUE TITLE
[RAID] Bastion of Twilight, Halfus Wyrmbreaker Fight: Orphaned Emerald Whelps (Drake) Dragon's Vengeance

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3101]
**Links:**
https://www.wowhead.com/npc=44641/orphaned-emerald-whelp
https://www.wowhead.com/spell=87683
https://www.wowhead.com/npc=44600/  ---> Halfus

What is happening:

It needs to be tested, it is probably not happening.

What should happen:

When Orphaned Emerald Whelps killed(Complete 1 group casts only 1 stack to the boss), this effect must be on Halfus.

**Comment by Echinaceax** [comment]
team is retesting
