### ISSUE TITLE
[RAID] Bastion of Twilight, Halfus Wyrmbreaker Fight: Orphaned Emerald Whelps (Drake) Atrophic Poison

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3102]
**Links:**

https://www.wowhead.com/spell=83609
https://www.wowhead.com/npc=44600/ --> Halfus
https://www.wowhead.com/npc=44641/orphaned-emerald-whelp

**What is happening:**

It needs to be tested.

**What should happen:**

The whole group should cast it to only 1 time to Halfus, it should be cast when they unchained.

**Comment by Echinaceax** [comment]
team is retesting
