### ISSUE TITLE
[RAID] Bastion of Twilight, Halfus Wyrmbreaker Fight: Nether Scion (Drake) Nether Blindness

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3104]
**Links:**

https://www.wowhead.com/npc=44600/ -->Halfus
https://www.wowhead.com/spell=83611/nether-blindness
https://www.wowhead.com/npc=44645/ --> Nether Scion

**What is happening:**

It's probably not working.

**What should happen:**

It is should be cast to Halfus when Nether Scion unchained.

**Comment by Echinaceax** [comment]
team is retesting
