### ISSUE TITLE
[RAID] Bastion of Twilight, Halfus Wyrmbreaker Fight: Proto-Behemoth -> Scorching Breath

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3106]
**Links:**
https://www.wowhead.com/npc=44687/proto-behemoth
https://www.wowhead.com/spell=83707
https://www.wowhead.com/npc=44641/orphaned-emerald-whelp

**What is happening:**

It needs to be tested.

**What should happen:**

Activates with Orphaned Emerald Whelps Awakened.

Explaining: Awaken state is 3/5 activated dragons every week.
Explaining: Slumber state is 2/5 of deactivated dragons every week.

**Comment by Echinaceax** [comment]
team is retesting
