### ISSUE TITLE
[RAID] Bastion of Twilight, Halfus Wyrmbreaker Fight: Proto-Behemoth -> Fireball Barrage

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3107]
**Links:**

https://www.wowhead.com/spell=83706
https://www.wowhead.com/npc=44687/proto-behemoth
https://www.wowhead.com/npc=44797/time-warden

**What is happening:**

It needs to be tested.

**What should happen:**

This spell active while Time Warden Awakens.

Explaining: Awaken state is 3/5 activated dragons every week.

Explaining: Slumber state is 2/5 of deactivated dragons every week.

**Comment by Eirolla** [comment]
The Situation is unknown, The encounter spells must be mechanically ordered. On normal10 man, Every week randomizing 3/5 of drakes. this week, Time warden was not there.

**Comment by Echinaceax** [comment]
team is retesting - these reports are spectation only
