### ISSUE TITLE
[RAID] Bastion of Twilight, Halfus Wyrmbreaker Fight: Halfus Wyrmbreaker -> Frenzied Assault

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3108]
**Links:**
https://www.wowhead.com/npc=44600/ ->Halfus
https://www.wowhead.com/spell=83693 --> Frenzied Assault

**What is happening:**

It needs to be tested.

**What should happen:**

Activates when Nether Scion Awakens.
Deactivates When Nether Scion Slumbers.

Explaining: Awaken state is 3/5 activated dragons every week.
Explaining: Slumber state is 2/5 of deactivated dragons every week.

**Comment by Echinaceax** [comment]
team is retesting - these reports are spectation only
