### ISSUE TITLE
[RAID] Bastion of Twilight, Halfus Wyrmbreaker Fight: Halfus Wyrmbreaker -> Malevolent Strike

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3109]
**Links:**

https://www.wowhead.com/npc=44600/ --> Halfus
https://www.wowhead.com/npc=44652/slate-dragon
https://www.wowhead.com/spell=39171/malevolent-strikes
https://www.wowhead.com/spell=83908/malevolent-strikes (effect on tanks)

**What is happening:**

It needs to be tested.

**What should happen:**

Activates when Slate Dragon Awakens.
Deactivates When Slate Dragon Slumbers.

Explaining: Awaken state is 3/5 activated dragons every week.
Explaining: Slumber state is 2/5 of deactivated dragons every week.

**Comment by Echinaceax** [comment]
team is retesting - these reports are spectation only
