### ISSUE TITLE
[RAID] Bastion of Twilight, Halfus Wyrmbreaker Fight: Halfus Wyrmbreaker -> Furious Roar

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3110]
**Links:**
https://www.wowhead.com/npc=44600/ --> halfus
https://www.wowhead.com/spell=83710/furious-roar

**What is happening:**

More tests needed

**What should happen:**

Furious Roar – When Halfus reaches 50% remaining health, he periodically emits a Furious Roar. This terrible roar inflicts 8000 Physical damage to all players and knocks them to the ground, stunning them for 2 sec. Halfus roars three times in rapid succession. (Players can interrupt this spell if it is interrupted on the first cast, the boss should not cast 2 times more.

**Comment by Echinaceax** [comment]
team is retesting - these reports are spectation only
