### ISSUE TITLE
[RAID] Bastion of Twilight, Halfus Wyrmbreaker Fight: Halfus Wyrmbreaker -> Shadow Nova

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3111]
**Links:**
https://www.wowhead.com/npc=44600/ -> Halfus
https://www.wowhead.com/spell=83703 -> Shadow Nova
https://www.wowhead.com/spell=83952 -> Shadow Wrapped (i think its effect graphics)

**What is happening:**

Tests needed.

**What should happen:**

Activates when Storm Rider Awakens.
Deactivates when Storm Rider Slumber.

**Comment by Keader** [comment]
@Eirolla Please merge all issues related with same boss.

**Comment by Echinaceax** [comment]
@Keader  i merged all now
