### ISSUE TITLE
[Rogue/Class] Stealth Bug

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#3112]
**What is happening:**

In happened in Grim Batol for this issue, but it could appears in other too, I don't know what causes it.

When you randomly walks, you get unstealthed.

https://puu.sh/E6MWv/a01aa6fac8.png 
In the middle on this screen should be an dragon skin mob, alone. Between rocks and elemental.

https://puu.sh/E6MWR/8bc8de98e6.jpg
On the bridge, whether before or after, well in this area, you get unstealthed aswell as rogue.

There is plenty of places like this in this dungeon, mostly around packs of mobs, like near broken bridges with packs of Water Elemental and Fire Elemental

**Comment by kDracku** [comment]
Happens with aquatic form the same , you get in normal form for no reason.

**Comment by Echinaceax** [comment]
> Happens with aquatic form the same , you get in normal form for no reason.
> Edit : You go in normal form if u thouch the ground

I can confirm that, i reported it here for the druid #2008

**Comment by Kitzunu** [comment]
Check the Combat log to see if something hit you for some reason

**Comment by Cenasty** [comment]
https://puu.sh/E71It/69c1d26437.png

https://puu.sh/E71Pj/ec29cabe6f.png

https://puu.sh/E71ZR/44ff78cd90.png 
https://puu.sh/E720j/eab133e0a7.png
These screen are linked spot fades.
It's the first spot I spoke about in the original message. Right in front of the mob, I got unstealthed.

For now, it only look like an automatic fades, without any random thing hitting me.

**Comment by Sammy974** [comment]
I can confirm that, it happens to 2 rogues of my guild in the same spot of GB. 
(Taisha is my toon, btw xD)

**Comment by Kitzunu** [comment]
I cannor reproduce this, I need reproduction steps otherwise I dont know

**Comment by Cenasty** [comment]
The moment I encounter nearly every single times is when you are leaving forgemaster throngus room (with lava) toward Dragha.

When you walk the stairs down, there is a pack of mobs on the left, a dragonskin in the middle and troggs on the right, digging the rocks. 

Walk stealth toward dragonskin like you would sap him. 

When I am very close to be able to sap it and or nearly be in melee range I got unstealthed and get into combat since i'am close to him.

**Comment by Cenasty** [comment]
An other spot is near the first pack. 

After drakes (who are still bugged but that's another day problem) there is a dragonskin pack, then humanoid with elementals with a broken bridge right next to it.

In this location, you can loose stealth too, 
It is more random to be honest, looks like walking of the broken bridge pillar unstealth you. 
Can happen between 1st and 3rd pack AFTER drakes location.
Mostly between the humanoid - elmental and the pack after it.

**Comment by Keader** [comment]
Cant reproduce.
Please re-open it when you have a reproduce steps.
Without it, i cant fix.
