### ISSUE TITLE
[RAID] Bastion of Twilight, Halfus Wyrmbreaker Fight: Randomized Drakes Every Week

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3114]
**Links:**

https://www.wowhead.com/npc=44641/orphaned-emerald-whelp
https://www.wowhead.com/npc=44645/
https://www.wowhead.com/npc=44797/time-warden
https://www.wowhead.com/npc=44650/storm-rider
https://www.wowhead.com/npc=44652/slate-dragon

**What is happening:**

Should be tested, probably 5 drakes are up the same time. 
Halfus and his dragon have all "awakened" effects from 5/5 dragons.

**What should happen:**

Every week, 3 different drakes should be awakened for the encounter. 
Every week, 2 different drakes should be slumbered for the encounter.

**Comment by Eirolla** [comment]
![image](https://user-images.githubusercontent.com/26048748/63262587-074b5480-c28f-11e9-936a-81dc81646ebd.png)

**Comment by Echinaceax** [comment]
Speculation - just test how many drakes are up on first raid
