### ISSUE TITLE
[RAID] Bastion of Twilight: Halfus Wyrmbreaker -> Boss Encounter Mechanics Part-1

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3115]
**Links:**
--Halfus and Spells --
https://www.wowhead.com/npc=44600/
https://www.wowhead.com/spell=83952
https://www.wowhead.com/spell=83703
https://www.wowhead.com/spell=39171/malevolent-strikes
https://www.wowhead.com/spell=83908/malevolent-strikes
https://www.wowhead.com/spell=83710/furious-roar
https://www.wowhead.com/spell=83693

--Proto-Behe and spells--
https://www.wowhead.com/npc=44687/proto-behemoth
https://www.wowhead.com/spell=83706
https://www.wowhead.com/spell=83707
https://www.wowhead.com/spell=86058

--Nether Scion and Spells--
https://www.wowhead.com/npc=44645/
https://www.wowhead.com/spell=83611/nether-blindness
https://www.wowhead.com/spell=87683

--Orphaned Emerald Whelp and Spells--
https://www.wowhead.com/npc=44641/orphaned-emerald-whelp
https://www.wowhead.com/spell=83609
https://www.wowhead.com/spell=87683

--Slate Dragon and Spells--
https://www.wowhead.com/npc=44652/slate-dragon
https://www.wowhead.com/spell=83603
https://www.wowhead.com/spell=87683

--Storm Rider and Spells--
https://www.wowhead.com/npc=44650/storm-rider
https://www.wowhead.com/spell=83612
https://www.wowhead.com/spell=87683

--Time Warden and Spells--
https://www.wowhead.com/npc=44797/time-warden
https://www.wowhead.com/spell=83601
https://www.wowhead.com/spell=87683

(links are added for schema)
**What is happening:**

Fight starts with all of 

Shadow Nova -> 83703 https://www.wowhead.com/spell=83703

Malevolent Strike -> 39171 https://www.wowhead.com/spell=39171/malevolent-strikes

Frenzied Assault -> 83693 https://www.wowhead.com/spell=83693

these spells. 

**What should happen:**

Shadow Nova -> 83703 https://www.wowhead.com/spell=83703 Activates when Storm Rider Awakens

Malevolent Strike -> 39171 https://www.wowhead.com/spell=39171/malevolent-strikes ->
Activates when Slate Dragon Awakens

Frenzied Assault -> 83693 https://www.wowhead.com/spell=83693 -> Activates when Nether Scion Awakens

**Comment by Eirolla** [comment]
Debuff's are will be investigated.

**Comment by Eirolla** [comment]
It's not needed to be open.

**Comment by Echinaceax** [comment]
@Keader  asked for merge - 
#3094
#3096
#3097
#3098
#3099
#3100
#3101
#3102
#3103
#3104
#3105
#3106
#3107
#3108
#3109
#3110
#3111
#3114

**Comment by Echinaceax** [comment]
team is retesting - these reports are spectation only

**Comment by sarahkay88** [comment]
https://wow.gamepedia.com/Halfus_Wyrmbreaker
