### ISSUE TITLE
[Quest] Coastal Delicacies - ID 28146 - Hillsbrad Foothills

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#312]
[Quest] Coastal Delicacies is meant to supply a hungry spider to feed on the murloc's but its not given.
as shown in video here
https://www.youtube.com/watch?v=upGIXZyv1fI

I abandoned the quest two times see if it was just a bug but still no pet spider given 

![coastal del](https://user-images.githubusercontent.com/39439201/50551251-04f3a600-0c7e-11e9-8689-0fab68db23db.jpg)

![i get no spider](https://user-images.githubusercontent.com/39439201/50551254-0c1ab400-0c7e-11e9-92e4-6fb61d95a05a.jpg)

**Comment by Dranah** [comment]
Have you tried with your felguard dismissed?
Just curious if it'd work.

**Comment by Echinaceax** [comment]
i did think it was a pet issue , so i tested it with the felguard on passive not dismissed

**Comment by Bathelmo** [comment]
@Echinaceax  can you elaborate?

**Comment by Echinaceax** [comment]
@Bathelmo 
[Quest] Coastal Delicacies is meant to supply a hungry spider to feed on the murloc's but its not given.
as shown in video here
https://www.youtube.com/watch?v=upGIXZyv1fI

**Comment by mfranca0009** [comment]
Potential spells used for this quest
-------------------------------------------------------------
https://www.wowhead.com/spell=88762/hungry-mine-creeper
https://www.wowhead.com/spell=88894/coastal-delicacies-credit
https://www.wowhead.com/spell=52930/feed
https://www.wowhead.com/spell=83621/spider-slay
https://www.wowhead.com/spell=88151/spider-bite

Will get something working for this soon.

**Comment by mfranca0009** [comment]
Fixes in database are done, just need to clean up the scripts I added.

**Comment by mfranca0009** [comment]
All set, needs testing in PTR 👍 

Hunters should not have a problem when they have a pet out and the spider being summoned. I've also made it much more responsive when there are murlocs around and dead in a 25 yard distance (blizzard seemed to have problems with this in Cataclysm). There is also a safety catch, the spider will not feed off a murloc and despawn it until the player has looted the corpse.

Murlocs do get despawned after the spider feeds, this prevents the spider from continuing to try and feed off the same murloc.

**Comment by Echinaceax** [comment]
confirmed fixed in PTR

![image](https://user-images.githubusercontent.com/39439201/103111238-345e0300-464b-11eb-8ef2-bb553152438c.png)
