### ISSUE TITLE
[QUEST] Deepholm: Quest Order: Upper World Pillar Fragment (part1)

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3122]
**Links:**
![image](https://user-images.githubusercontent.com/26048748/63546939-9ed0d180-c533-11e9-8428-6b788640d34a.png)

https://www.wowhead.com/quest=26247/diplomacy-first
https://www.wowhead.com/npc=42684/stormcaller-mylra

https://www.wowhead.com/quest=26248/all-our-friends-are-dead
https://www.wowhead.com/quest=26249/the-admirals-cabin
https://www.wowhead.com/quest=26251
https://www.wowhead.com/quest=26427
https://www.wowhead.com/quest=26250
https://www.wowhead.com/quest=26254
https://www.wowhead.com/quest=26255/return-to-the-temple-of-earth
https://www.wowhead.com/quest=26258
https://www.wowhead.com/quest=26256/bleed-the-bloodshaper
https://www.wowhead.com/quest=26261/question-the-slaves
https://www.wowhead.com/quest=26260/the-forgemasters-log
https://www.wowhead.com/quest=27007/silvermarsh-rendezvous
https://www.wowhead.com/quest=27010/quicksilver-submersion
https://www.wowhead.com/quest=27061/the-twilight-overlook
https://www.wowhead.com/quest=26766/big-game-big-bait
https://www.wowhead.com/quest=26768/to-catch-a-dragon
https://www.wowhead.com/quest=28866/into-the-stonecore
https://www.wowhead.com/quest=26771/testing-the-trap
https://www.wowhead.com/quest=26857/abyssions-minions
https://www.wowhead.com/quest=26876/the-world-pillar-fragment

**Current situation of this post:**

NO ONE COMMENTS-EDIT THIS TOPIC FOR NOW.
Testing with: Holytester (dev)
Stuck at: "Diplomacy First" -> QID 26247
Problem: I made 2 new comments for the fix. I will wait for the fix for continue test.

**What should happen:**

When you complete: "Diplomacy First" -> QID 26247
You unlock 2 quests: 
1-> "All our friends are dead" -> 26248
2-> "The admiral's Cabin" -> 26249
########
When you complete: "All our friends are dead" -> 26248
You unlock: 
1-> "Take no Prisoners" -> 26251
########
When you complete: "The Admiral's Cabin" -> 26249
You unlock: 
1-> "Without a Captain or Crew" -> 26427
########
When you complete: "Take no Prisoners" -> 26251 
You unlock: 
1-> "On second Thought, Take One Prisoner(26250)"
########
**When you complete: "On second Thought, Take One Prisoner(26250)"**
You unlock: 
 "Some Spraining to Do" -> 26254 (bugged) #2625
########
When you complete: "Some Spraining to Do(26254)
You unlock: 
1->Return to the Temple of Earth -> 26255
########
When you complete: "Return to the Temple of Earth 26255"
You unlock: 
1-> Deathwing's Fall -> 26258
########
When you complete: "Deathwing's Fall -> 26258" 
You unlock: 
1-> Bleed the Bloodshaper -> 26256
########
When you complete: "Bleed the Bloodshaper -> 26256"
You unlock: 
1-> Question the Slaves -> 26261 #3154
########
When you complete: "Question the Slaves -> 26261"  #3154
You unlock: 
1-> The Forgemaster's Log -> 26260 #3155
########
When you complete: "The Forgemaster's Log -> 26260 "  #3155
You unlock: 
1-> Silvermarsh Rendezvous -> 27007
########
When you complete: "Silvermarsh Rendezvous -> 27007"
You unlock: 
1-> Quicksilver Submersion -> 27010 #3156
########
When you complete: " Quicksilver Submersion -> 27010"  #3156
You unlock: 
1-> The Twilight Overlook -> 27061
########
**When you complete: "The Twilight Overlook -> 27061" 
You unlock 3 quests: 
1->Big Game, Big Bait -> 26766  (you cant get 26766 and 26768 same time, its a bug)
2->To Catch a Dragon -> 26768
3-> Into the Stonecore -> 28866**
########
When you complete: "Big Game, Big Bait 26766 "+ "To Catch a Dragon 26768"
You unlock: 
1-> Testing the Trap -> 26771
########
When you complete: "Testing the Trap -> 26771" 
You unlock: 
1-> Abyssion's Minions -> 26857
########
When you complete: "Abyssion's Minions -> 26857"
You unlock: 
1-> The World Pillar Fragment -> 26876  (bugged quest)
########
When you complete: The Middle Fragment (27938) + The World Pillar Fragment -> 26876 (bugged quest) #3123
You unlock: 
1-> The Very Earth Beneath Our Feet (26326)
----Part1 was done---

**Comment by Eirolla** [comment]
#3123 - #2625

**Comment by Eirolla** [comment]
![image](https://user-images.githubusercontent.com/26048748/63547404-c5433c80-c534-11e9-938a-093c3ff113f0.png)
After you complete "Diplomacy First" -> QID 26247
You unlocking 2 questlines:
1-> "All our friends are dead" -> 26248
2-> "The admiral's Cabin" -> 26249

**Comment by Eirolla** [comment]
![image](https://user-images.githubusercontent.com/26048748/63547578-21a65c00-c535-11e9-836b-4fd2b82784e8.png)
After you complete "The Twilight Overlook -> 27061"
You unlocking 3 quests:
1->Big Game, Big Bait -> 26766 (you cant get 26766 and 26768 same time, its a bug)
2->To Catch a Dragon -> 26768
3-> Into the Stonecore -> 28866

I should not get "Into the Stonecore -> 28866" while I didn't do "The Twilight Overlook -> 27061"

**Comment by Kitzunu** [comment]
Last minute fixes, and this is all complete!
