### ISSUE TITLE
[QUEST-ITEM] Deepholm: Earthen Ring Banner

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3123]
**Links:**

https://www.wowhead.com/quest=26876/the-world-pillar-fragment
https://www.wowhead.com/item=60810

**What is happening:**

When you try to use quest item on a specific position, nothing happens.

**What should happen:**

Abyssion must approach when we use the quest item.

**Comment by Chicozoba** [comment]
If I can add a comment, you can't even USE the item, wrong position it says ("require Center of Abyssion's Lair").

**Comment by Bathelmo** [comment]
currently just does nothing, item is clickable whenever you get closer the midpoint of the circular area.

**Comment by Rushor** [comment]
final fix for this, bit huge event

**Comment by Rushor** [comment]
whole event fixed. took 2 hours lol

![I](https://i.imgur.com/qFWpmBX.jpg)
![I](https://i.imgur.com/1Xj7Dbk.jpg)
![I](https://i.imgur.com/UM6kZ78.jpg)

**Comment by polymorphism98** [comment]
@Echinaceax - This seems to be bugged once again. The event starts fine and the boss is attackable. But somewhere during the fight, I believe at about 50% and 25% of his health, he bugs out and flies off to disappear. I think 50% and 25% are the same times when he pops up his bubble too. Hence making it impossible to kill.

**Comment by Echinaceax** [comment]
> @Echinaceax - This seems to be bugged once again. The event starts fine and the boss is attackable. But somewhere during the fight, I believe at about 50% and 25% of his health, he bugs out and flies off to disappear. I think 50% and 25% are the same times when he pops up his bubble too. Hence making it impossible to kill.

@polymorphism98 i just completed this without issue, Maybe its a low damage issue, worked fine for me

![no issue](https://user-images.githubusercontent.com/39439201/84590371-2fb3c900-ae36-11ea-9664-ca37ca0de914.jpg)

"require Center of Abyssion's Lair"

![center](https://user-images.githubusercontent.com/39439201/84590404-87523480-ae36-11ea-8815-168cdc863995.jpg)
