### ISSUE TITLE
[QUEST] Deepholm: Quest Order: Middle World Pillar Fragment (part2)

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3124]
**Links:**
![image](https://user-images.githubusercontent.com/26048748/63351407-d8ed7800-c367-11e9-86d9-e5c866846013.png)

https://www.wowhead.com/quest=27938/the-middle-fragment#comments:id=1627941

**Current situation of this post:**

NO ONE TOUCH THIS POST.
Testing with: Holytested (dev)
Stuck at: Keep Them off the Front (26755)
Waiting for help.

**What should happen:**

**You Start with-> Where's Goldmine? (26409) #2852 (alert, it MUST be fixed asap or revert Quest order fix on this quest.** @Kitzunu 

When you complete: Where's Goldmine? (26409)
You unlock 2 Quests:
1->Something that Burns (27135) #797  **1 and 2 should be able to add quest same time from NPC.** 
2->Explosive Bonding Compound (26410)
###########
After you Complete (27135+26410)
You unlock: 
Apply and Flash Dry (26411)
###########
After you complete: Apply and Flash Dry (26411)
You unlock: 
Take Him to the Earthcaller (26413)
###########
After you complete: Take Him to the Earthcaller (26413) #2954
You unlock:
To Stonehearth's Aid (26484)
###########
After you complete: To Stonehearth's Aid (26484)
You unlock: 
The Quaking Fields (27931) 
###########
After you complete: The Quaking Fields (27931) 
You unlock 2 quests:
1-> Elemental Ore (27933)
2-> The Axe of Earthly Sundering (27932) #1991
###########
After you Complete: 
1-> Elemental Ore (27933)
2-> The Axe of Earthly Sundering (27932) #1991
You unlock:
One With the Ground (27934) #2961
###########
After you Complete:  One With the Ground (27934) #2961
You unlock: Bring Down the Avalanche( has 2 version 27935-27936) (bugged probably)
###########
After you complete: Bring Down the Avalanche( has 2 version 27935-27936) (bugged probably)
You unlock: 
1-> Stonefather's Boon (26499) **1 and 2 should be able to add quest same time** 
2-> We're Surrounded (26500)
###########
After you complete: We're Surrounded (26500)
You unlock:
Thunder Stones (26502)
###########
After you complete: Thunder Stones (26502)
You unlock: Fixer Upper (26564)
###########
After you complete: Stonefather's Boon (26499) #3020
You unlock: Sealing the Way (26501) #3022
###########
After you complete: Sealing the Way (26501) #3022
You unlock: Shatter Them! (26537)
###########
After you complete: Sealing the Way (26501)+Thunder Stones (26502)
You unlock: Battlefront Triage(26591) #3144
###########
After you complete: Thunder Stones (26502)
You unlock: Fixer Upper(26564)
###########
After you complete: Fixer Upper(26564) + Battlefront Triage(26591) + Shatter Them! (26537)
You unlock: Troggzor the Earthinator (26625)
###########
After you complete: Troggzor the Earthinator (26625)
You unlock: Rush Delivery (27126)
###########
After you complete: Rush Delivery (27126)
You unlock: Close Escort (26632) (bugged) #1992
###########
After you complete: Close Escort (26632) (bugged) #1992
You unlock: Keep Them off the Front (26755) (bugged) 
###########
After you complete: Keep Them off the Front (26755) (bugged)  #2962
You unlock: Reactivate the Constructs (26762)
###########
After you complete: Reactivate the Constructs (26762) #2963
You unlock: Down Into the Chasm (26834)
###########
After you complete: Down Into the Chasm (26834)
You unlock:
1->Fungal Monstrosities(26792)(Bugged) #1994 **1 and 2 should be able to add quest same time**
2->Sprout No More(26791)(Bugged) #1994
###########
After you complete: Fungal Monstrosities(26792)(Bugged) + Sprout No More(26791)(Bugged)
You unlock: A Slight Problem(26835)
###########
After you complete: A Slight Problem(26835)
You unlock: Rescue the Stonefather... and Flint (26836)
###########
After you complete: Rescue the Stonefather... and Flint (26836)
You unlock: The Hero Returns (27937)
###########
After you complete: The Hero Returns (27937)
You unlock: The Middle Fragment (27938)
###########
After you complete: The Middle Fragment (27938) + The World Pillar Fragment -> 26876 (bugged quest)
You unlock: The Very Earth Beneath Our Feet (26326)

----Schema is done------

**Comment by Eirolla** [comment]
![image](https://user-images.githubusercontent.com/26048748/63384934-9d26d280-c3a8-11e9-8fe8-d8d9b7e9ea94.png)
not fixed one, (glad to not for this one) Where's Goldmine? (26409) since this quest is not obtainable, np

**Comment by Eirolla** [comment]
![image](https://user-images.githubusercontent.com/26048748/63385110-fa228880-c3a8-11e9-9c5e-1526155bc60e.png)
I can't get both of these quests same time

**Comment by Eirolla** [comment]
"1 and 2 should be able to add quest same time" note added as bold on group quests.

**Comment by Kitzunu** [comment]
Cool, thats an easy fix.

Will make sure it is done before school

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/63407350-98840d80-c3ec-11e9-9939-d2d26ce2fad5.png)

Also fixed an issue that I missed where "We're Surrounded" didn't listen to the PreviousQuestID rule

**Comment by Kitzunu** [comment]
works
![image](https://user-images.githubusercontent.com/24550914/63407439-cec18d00-c3ec-11e9-930a-a1f39812fbde.png)

**Comment by Eirolla** [comment]
thanks

**Comment by Randomplayerx** [comment]
"Something that burns" still not working, tbh I'm too lazy to report bugs that been reported 2-4 months ago and still aren't fixed.
~
