### ISSUE TITLE
[QUEST] Deepholm: Quest Order: Bottom World Pillar Fragment (Part-3)

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3125]
**Links:**
![image](https://user-images.githubusercontent.com/26048748/63367268-1b24b280-c384-11e9-9aed-8ba10d26bcd4.png)
(HOLY SHET)
https://www.wowhead.com/quest=26326/the-very-earth-beneath-our-feet#comments:id=1627949

**Current situation of this post:**

NO ONE TOUCH THIS POST UNTIL COMPLETED.
I will update the Quest Order Schema after I complete tests of Part-1(#3122) and Part2 (#3124).

**What should happen:**

When you complete: The Middle Fragment (27938) + The World Pillar Fragment (26876)
Quest Unlocked:  The Very Earth Beneath Our Feet (26326)
##########
When you complete: The Very Earth Beneath Our Feet (26326)
Quest Unlocked: 
1-> Crumbling Defenses (26312) (these 3 quests should be able to get same time)
2-> On Even Ground (26314)
3-> Core of Our Troubles (26313)
##########
When you complete: Crumbling Defenses (26312) + On Even Ground (26314) + Core of Our Troubles (26313)
Quest Unlocked: Imposing Confrontation (26315)
##########
When you complete: Imposing Confrontation (26315)
Quest Unlocked: Rocky Relations (26328)
##########
When you complete: Rocky Relations (26328)
Quest Unlocked: 
1-> Unsolid Ground (26377) 
2-> Hatred Runs Deep (26376)
3-> Loose Stones (26375)
##########
When you complete: Unsolid Ground (26377) + Hatred Runs Deep (26376)
Quest Unlocked: Violent Gale (26426)
##########
When you complete: Violent Gale (26426)
Quest Unlocked: Depth of the Depths (26869)
##########
When you complete: Depth of the Depths (26869)
Quest Unlocked: A Rock Amongst Many (26871)

**Comment by Kitzunu** [comment]
fixed
