### ISSUE TITLE
[Spell/Warlock] Pet Ability "Shadow Bite" #54049

### ISSUE THREAD

**Issue by jahbansen** [WoWManiaUK/Blackwing-Lair#3126]
So the Shadow Bite ability of the Felhunter does way to less dmg. The WoWhead tooltip of the petspell isnt on our clientversion anymore. So here a screenshot of mine ingame:

![ability tooltip](https://user-images.githubusercontent.com/54234847/63372819-30e7a700-c387-11e9-8dc4-c8624e03773a.png)

The issue is, even the tooltip itself says a minimum dmg of 4258 should be dealt, with not a single DoT spell applied, it only does around 400-500 with DoTs. Somehow the basedmg is low and the DoT multiplier arent adding any dmg.

ability links:

- https://www.wowhead.com/spell=54049/shadow-bite

**Comment by jahbansen** [comment]
When will the fix apply, does it need a serverrestart to work? i just tested it at the training dummy in og and "shadowbite" still doesn´t do the dmg it should be doing.
![shadowbite dmg meter](https://user-images.githubusercontent.com/54234847/63898200-303eb880-c9f8-11e9-8bfd-4f2c4998aa88.PNG)

**Comment by Keader** [comment]
It's fixed in PTR.
You need wait until next update to get it in live server

**Comment by jahbansen** [comment]
ok thank you!
