### ISSUE TITLE
[NPC] Steeg Haskell <Guild Vendor> - issue2 -Ironforge

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3127]
**Links:**
https://www.wowhead.com/npc=51495/steeg-haskell
https://www.wowhead.com/guild-achievements

https://www.wowhead.com/item=63352/shroud-of-cooperation
https://www.wowhead.com/item=63206/wrap-of-unity
https://www.wowhead.com/item=122260/worn-stoneskin-gargoyle-cape&bonus=0
https://www.wowhead.com/item=122261/inherited-cape-of-the-black-baron&bonus=0
https://www.wowhead.com/item=122262/ancient-bloodmoon-cloak&bonus=0
https://www.wowhead.com/item=122266/ripped-sandstorm-cloak&bonus=0
https://www.wowhead.com/item=122249/preened-tribal-war-feathers&bonus=0
https://www.wowhead.com/item=122248/stained-shadowcraft-cap&bonus=0
https://www.wowhead.com/item=122247/mystical-coif-of-elements&bonus=0
https://www.wowhead.com/item=122245/polished-helm-of-valor&bonus=0
https://www.wowhead.com/item=122246/tarnished-raging-berserkers-helm&bonus=0

**What is happening:**
- Items are availible without guild  requirements
- missing other items (mounts and pets and Guild Vault Voucher (7th Slot)

**What should happen:**
Items should not be availible without guild  requirements

**Comment by Kitzunu** [comment]
Same here, you will only be able to access the vendor and the items when you ahve the required Guild Reputation + Guild Achievement

**Comment by Echinaceax** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/3129#issuecomment-552163372
