### ISSUE TITLE
[NPC] Mirla Silverblaze <Guild Vendor>- Missing - Dalaran 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3128]
**Links:**
https://www.wowhead.com/npc=51512/mirla-silverblaze

**Whats happening**
- Npc missing

**What should happen:**
she should be at her location

https://www.wowhead.com/npc=51512/mirla-silverblaze#comments:id=1186241
![dala vendor](https://user-images.githubusercontent.com/39439201/63390879-dbc08b00-c3b0-11e9-9e94-46e091ae5ab6.jpg)

**Comment by Kitzunu** [comment]
It is partially fixed, it is missing the "horde specific" items and "horde specific" restrictions, so atm it is really only good for alliance.

but when I have fixed all Horde Restrictions I will add the missing items and restrictions to this NPC

**Comment by Kitzunu** [comment]
To clearify, I only added the NPC

All items and restrictions I will work on here https://github.com/WoWManiaUK/Blackwing-Lair/issues/3132

**Comment by Echinaceax** [comment]
Not exactly @Kitzunu 
i see not many restrictions set on her as Ally :)

**Comment by Echinaceax** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/3129#issuecomment-552163372
