### ISSUE TITLE
[NPC] Riha <Guild Vendor>- Shattrath 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3129]
**Links:**

https://www.wowhead.com/npc=52268/riha
https://www.wowhead.com/guild-achievements

https://www.wowhead.com/item=122245/polished-helm-of-valor&bonus=0

https://www.wowhead.com/item=63352/shroud-of-cooperation
https://www.wowhead.com/item=63206/wrap-of-unity
https://www.wowhead.com/item=122249/preened-tribal-war-feathers&bonus=0
https://www.wowhead.com/item=122248/stained-shadowcraft-cap&bonus=0
https://www.wowhead.com/item=122247/mystical-coif-of-elements&bonus=0
https://www.wowhead.com/item=122245/polished-helm-of-valor&bonus=0
https://www.wowhead.com/item=122246/tarnished-raging-berserkers-helm&bonus=0
https://www.wowhead.com/item=122260/worn-stoneskin-gargoyle-cape&bonus=0
https://www.wowhead.com/item=122261/inherited-cape-of-the-black-baron&bonus=0
https://www.wowhead.com/item=122262/ancient-bloodmoon-cloak&bonus=0
https://www.wowhead.com/item=122266/ripped-sandstorm-cloak&bonus=0
https://www.wowhead.com/item=122250/tattered-dreadmist-mask&bonus=0
https://www.wowhead.com/item=62286/guild-vault-voucher-7th-slot
https://www.wowhead.com/item=65361/guild-page https://www.wowhead.com/item=65363/guild-herald
https://www.wowhead.com/item=63398/armadillo-pup

mounts and pets 

**What is happening:**
- Items are availible without guild requirements
- lots of items missing (mounts and pets)

**What should happen:**
Items should not be availible without guild  requirements

**Comment by Rushor** [comment]
listed items are from mop or higher expansion.


will adjust this to the cata versio

**Comment by Echinaceax** [comment]
still an issue @Rushor

**Comment by Rushor** [comment]
which items should not be available? i need a cata list with the needed rep (not > mop)

**Comment by Echinaceax** [comment]
ok i will get info soon

**Comment by Rushor** [comment]
i need a list

(itemid - repvalue that is needed)

**Comment by Echinaceax** [comment]
@Rushor here you go 
note: Guild achievement and rep required not just rep setting (so all vendors need same fix)

----------------

- [ ] Dark pheonix requirement is https://www.wowhead.com/achievement=4988/guild-glory-of-the-cataclysm-raider
https://www.wowhead.com/item=63125/reins-of-the-dark-phoenix

- [ ] Lil' Tarecgosa requirement is https://www.wowhead.com/achievement=5840/dragonwrath-tarecgosas-rest-guild-edition
https://www.wowhead.com/item=71033/lil-tarecgosa

- [ ] Banner of Cooperation (ally) requirement is https://www.wowhead.com/achievement=4860/working-as-a-team
https://www.wowhead.com/item=63359/banner-of-cooperation

- [ ] Banner of Cooperation (horde) requirement is https://www.wowhead.com/achievement=4860/working-as-a-team
https://www.wowhead.com/item=64400/banner-of-cooperation

- [ ] Guild Vault Voucher (8th Slot) requirement is https://www.wowhead.com/achievement=5158/stay-classy
https://www.wowhead.com/item=62287/guild-vault-voucher-8th-slot

- [ ] Armadillo Pup requirement is https://www.wowhead.com/achievement=5144/critter-kill-squad
https://www.wowhead.com/item=63398/armadillo-pup

- [ ] Guild Vault Voucher (7th Slot) requirement is https://www.wowhead.com/achievement=4943/guild-level-5
https://www.wowhead.com/item=62286/guild-vault-voucher-7th-slot

- [ ] Dark Phoenix Hatchling requirement is https://www.wowhead.com/achievement=5812/united-nations
https://www.wowhead.com/item=63138/dark-phoenix-hatchling

- [ ] Standard of Unity (ally) requirement is https://www.wowhead.com/achievement=5143/guild-cataclysm-dungeon-hero
https://www.wowhead.com/item=64398/standard-of-unity

- [ ] Standard of Unity (horde) requirement is https://www.wowhead.com/achievement=5143/guild-cataclysm-dungeon-hero
https://www.wowhead.com/item=64401/standard-of-unity

- [ ] Reins of the Golden King requirement is https://www.wowhead.com/achievement=4912/guild-level-25
https://www.wowhead.com/item=62298/reins-of-the-golden-king

- [ ] Guild Herald (ally) requirement is https://www.wowhead.com/achievement=5201/profit-sharing
https://www.wowhead.com/item=65363/guild-herald

- [ ] Guild Herald (horde) requirement is https://www.wowhead.com/achievement=5201/profit-sharing
https://www.wowhead.com/item=65364/guild-herald

- [ ] Battle Standard of Coordination (ally) requirement is https://www.wowhead.com/achievement=5422/a-daily-routine
https://www.wowhead.com/item=64399/battle-standard-of-coordination

- [ ] Battle Standard of Coordination (horde) requirement is https://www.wowhead.com/achievement=5422/a-daily-routine
https://www.wowhead.com/item=64402/battle-standard-of-coordination

- [ ] Guild Page (ally) requirement is https://www.wowhead.com/achievement=5031/horde-slayer
https://www.wowhead.com/item=65361/guild-page

- [ ] Guild Page (horde) requirement is https://www.wowhead.com/achievement=5179/alliance-slayer
https://www.wowhead.com/item=65362/guild-page

- [ ] Cloak of Coordination (horde) requirement is https://www.wowhead.com/achievement=5035/master-crafter
https://www.wowhead.com/item=65274/cloak-of-coordination

- [ ] Cloak of Coordination (ally) requirement is https://www.wowhead.com/achievement=5035/master-crafter
https://www.wowhead.com/item=65360/cloak-of-coordination


- [ ] Recipe: Seafood Magnifique Feast requirement is https://www.wowhead.com/achievement=5036/thats-a-lot-of-bait
https://www.wowhead.com/item=62800/recipe-seafood-magnifique-feast

- [ ] Shroud of Cooperation (ally) requirement is https://www.wowhead.com/achievement=4989/a-class-act
https://www.wowhead.com/item=63352/shroud-of-cooperation

- [ ] Shroud of Cooperation (horde) requirement is https://www.wowhead.com/achievement=4989/a-class-act
https://www.wowhead.com/item=63353/shroud-of-cooperation

- [ ] Reins of the Kor'kron Annihilator requirement is https://www.wowhead.com/achievement=5492/guild-level-25
https://www.wowhead.com/item=67107/reins-of-the-korkron-annihilator

- [ ] Recipe: Cauldron of Battle requirement is https://www.wowhead.com/achievement=5465/mix-master
https://www.wowhead.com/item=65435/recipe-cauldron-of-battle

- [ ] Recipe: Big Cauldron of Battle requirement is https://www.wowhead.com/achievement=5024/better-leveling-through-chemistry
https://www.wowhead.com/item=65498/recipe-big-cauldron-of-battle



these require (patch 6.0.2.1) (patch 6.1.0)

https://www.wowhead.com/item=116666/blacksteel-battleboar  
https://www.wowhead.com/item=122251/polished-legplates-of-valor&bonus=0 
https://www.wowhead.com/item=122252/tarnished-leggings-of-destruction&bonus=0
https://www.wowhead.com/item=122253/mystical-kilt-of-elements&bonus=0
https://www.wowhead.com/item=122254/stained-shadowcraft-pants&bonus=0
https://www.wowhead.com/item=122255/preened-wildfeather-leggings&bonus=0
https://www.wowhead.com/item=122256/tattered-dreadmist-leggings&bonus=0
https://www.wowhead.com/item=122264/burnished-legplates-of-might&bonus=0
