### ISSUE TITLE
[Quest] Return to Andormu (given from Erozion) - Old Hillsbrad Foothills

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#3130]
**Links:**
https://tbc-twinhead.twinstar.cz/?quest=10285
https://www.wowhead.com/quest=10285/return-to-andormu
https://www.youtube.com/watch?v=jiTHFKo4CKU&t=1126s  -  A link of a YouTube video that shows that quests that have to be completed to get to the quest "Return to Andormu". At 25:00 minute of the video the guys takes the quest "Return to Andormu" from Erozion after completing all other quests that I've listed down below.

**What is happening:**

I did all 5 quests to get to the quest - "Return to Andormu" but it's currently missing from the NPC Erozion inside of Old Hillsbrad Foothills. It's needed to enter the dungeon "The Black Morass".

**What should happen:**

Erozion should give the quest "Return to Andormu" after the following quests are completed:
1. "To The Master's Lair" - https://www.wowhead.com/quest=10279/to-the-masters-lair
2. "The Caverns of Time" - https://www.wowhead.com/quest=10277/the-caverns-of-time
3. "Old Hillsbrad" - https://www.wowhead.com/quest=10282/old-hillsbrad
4. "Taretha's Diversion" - https://www.wowhead.com/quest=29598/tarethas-diversion
5. "Escape from Durnholde" - https://www.wowhead.com/quest=29599/escape-from-durnholde

**Comment by Kitzunu** [comment]
that quest was removed in 4.3.0

![image](https://user-images.githubusercontent.com/24550914/63409459-835dad80-c3f1-11e9-8dea-ec5ec450589f.png)

**Comment by Kitzunu** [comment]
Fixed the quest line to work together here https://github.com/WoWManiaUK/Blackwing-Lair/issues/3133
