### ISSUE TITLE
[NPC] Lillehoff <The Sons of Hodir Quartermaster> - Storm Peaks

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#3131]
**Links:**
![Screenshot_13](https://user-images.githubusercontent.com/52254524/63398310-d7f32f80-c3d5-11e9-8de8-71706979bd7a.png)
https://wotlk-twinhead.twinstar.cz/?npc=32540
https://www.wowhead.com/npc=32540/lillehoff
**What is happening:**

The NPC is missing from the area.

**What should happen:**

The NPC should be in the area.

**Comment by Kitzunu** [comment]
This is due to that you have not completed quest 12924 (Forging an Alliance)
