### ISSUE TITLE
Fire mage / Combustion - Spell ID : 11129

### ISSUE THREAD

**Issue by FixMySpells** [WoWManiaUK/Blackwing-Lair#3134]
**What is happening: Combustion has an issue, spreading its damage by " impact " does not deal the same damage on the primary target

For example: -
 Mob X suffers 4000 damage from Combustion per tick, when the caster spread its damage to nearby targets by " impact" the damage that got spread is not the same on the primary target, (it deal less damage )

**What should happen: all nearby targets ( within 12 yards ) should suffer the same damage as the original one after spreading its damage

![Combustion's damage](https://user-images.githubusercontent.com/53161918/63455334-a58d1500-c45d-11e9-91a0-85075a0e8724.png)

**Comment by Cenasty** [comment]
Issue already reported in issue 2425, still no progression yet. (I believe it's WiP)
#2425 

Issue n°4 of Dranah listing I made with him.

**Comment by Keader** [comment]
Its fixed in ptr
