### ISSUE TITLE
[Spell/Warlock] Demon Soul

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#3136]
**What is happening:**
After using Demon Soul warlock casts forked lighting doing insane damage
https://imgur.com/tSUPeN2
https://imgur.com/TkbSjb3
Here you see the warlock targeting the pet and only the pet , after using Demon Soul the warlock casts forked lighting while targeting hes pet doing insane damage
https://imgur.com/sli73hP
https://imgur.com/Im8wzAp
This thing only works with voidwalker pet
**What should happen:**
All threat generating by you transferred to your voidwalker for 15 sec

**Comment by Cenasty** [comment]
So this spell (here in screenshot) doesn't works as intended.

https://puu.sh/E7W5a/70e160421c.png

Imp : Works fine, buff is here.
Voidvalker : Cast a 'Forked Lightning' dealing massive damage in front of the caster instead.
Succubus : Gives a 'Barleybrew Gold' instead.  ( https://puu.sh/E7W7O/3e9e1bf228.png )
Felhunter : Works fine, buff is here.
Felguard : Pop a bubble instead.
