### ISSUE TITLE
[NPC] Wind Tunnel - Lost City of the Tol'vir 

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3138]
**Links:**

https://www.wowhead.com/npc=48092/wind-tunnel

**What is happening:**
Npc is inactive and prevents players from reaching the last boss

**What should happen:**
Players jump in the wind tunnel and are thrown to the last boss, they become active after killing the first 4 boss's

**Comment by sarahkay88** [comment]
@wow-mania the wind tunnels don't spawn at all now so still no way of reaching last boss for normal players

**Comment by Echinaceax** [comment]
@Rushor can we get this fixed asap, jani wants to open it on live wednesday :)

**Comment by Keader** [comment]
Test now.
Remember:

GENERAL_HUSAM, LOCKMAW_AND_AUGH, HIGH_PROPHET_BARIM need be death to wind appear.

**Comment by Echinaceax** [comment]
@Keader it spawns again now but still isnt active - your meant to stand in it/click it and it throws group up to  https://www.wowhead.com/npc=44819/siamat

cant get up to last boss without this wind tunnel

**Comment by Keader** [comment]
I tested in my copy of wow mania and Was working.
Let me check why ptr is not

**Comment by Echinaceax** [comment]
> I tested in my copy of wow mania and Was working.
> Let me check why ptr is not

strange, thanks keader

**Comment by Keader** [comment]
yeah, janitor break it.
fixed now.
