### ISSUE TITLE
[Dungeon/Crowd Control] Halls of Origination

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#3139]
**Links:**

https://www.wowhead.com/npc=48139/temple-swiftstalker
https://www.wowhead.com/npc=48143/temple-fireshaper
https://www.wowhead.com/npc=48140/temple-runecaster
https://www.wowhead.com/npc=48141/temple-shadowlancer
All 4 are humanoid
https://www.wowhead.com/npc=40450/dustbone-horror
https://www.wowhead.com/npc=40311/dustbone-tormentor - These two are Undeads
https://www.wowhead.com/npc=40715/lifewarden-nymph
https://www.wowhead.com/npc=39373/sun-touched-speaker
https://www.wowhead.com/npc=39366/sun-touched-servant#comments

**What is happening:**

All of these mobs are currently immune to crowd control 

https://puu.sh/E7WOy/e1cc51c2e8.png
https://puu.sh/E7XXE/afed432a70.png
https://puu.sh/E7XYN/fa327b663c.png
https://puu.sh/E7Y5L/e63e7693fa.png
https://puu.sh/E7Y8w/94381ec145.png

**What should happen:**

Monster should be controlled following their classification 

Sap for Humanoid, Beast, Dragonskin, Demons,
Soul Shackle for Undead 
etc..

Proof : This following video show the mob getting CC'ed
https://www.youtube.com/watch?v=_rGCm2Dtikg

**Comment by Kitzunu** [comment]
(48139, 48143, 48140, 48141) now only have immune to 
524288 - MECHANIC_SHACKLE
8388608 - MECHANIC_HORROR

(40450, 40311) now only have immune to
16 - MECHANIC_FEAR
128 - MECHANIC_PACIFY
536870912 - MECHANIC_SAPPED

If I missed anything tell me

**Comment by Kitzunu** [comment]
I forgot to send this file to Janitor, so it isn't on live yet.

will be next update, sorry for incovenience
