### ISSUE TITLE
[Quest] A fighting chance - ID 28495 - Hillsbrad Foothills

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#314]
[Quest] A fighting chance, the quest item isnt working, 
it makes the sound but visually no hearts like in the video 

Video - https://www.youtube.com/watch?v=-kKYa6CT2n4
Quest - https://www.wowhead.com/quest=28495/a-fighting-chance

**From the video** 

![as seen on video](https://user-images.githubusercontent.com/39439201/50553376-de496580-0ca5-11e9-86a5-d908ab6b8ff1.jpg)

![video guy has 3](https://user-images.githubusercontent.com/39439201/50553418-9bd45880-0ca6-11e9-9df4-465519d45367.jpg)

> **From me** 

![quest](https://user-images.githubusercontent.com/39439201/50553383-f3be8f80-0ca5-11e9-9527-db88c45f3f2a.jpg)
![quest item](https://user-images.githubusercontent.com/39439201/50553386-f7521680-0ca5-11e9-9984-cafb05711d13.jpg)

![quest item not working](https://user-images.githubusercontent.com/39439201/50553445-25842600-0ca7-11e9-914f-a1ab45d2b9b3.jpg)
![0 saved](https://user-images.githubusercontent.com/39439201/50553447-287f1680-0ca7-11e9-81e1-b05b102ef5fc.jpg)

**Comment by Bathelmo** [comment]
@Echinaceax  Can you elborate?

**Comment by Echinaceax** [comment]
@Bathelmo 
Save 10 Hill Fawns. 
https://www.wowhead.com/quest=28495/a-fighting-chance
quest item not doing as it should 

![image](https://user-images.githubusercontent.com/39439201/64475311-6f4fd500-d181-11e9-9ae0-a9989d8904b1.png)

see video
https://www.youtube.com/watch?v=-kKYa6CT2n4

**Comment by Bathelmo** [comment]
so it's like the heart visuals? but as far as the quest credit goes its alright?

**Comment by Echinaceax** [comment]
> so it's like the heart visuals? but as far as the quest credit goes its alright?

no cant complete the quest, the quest doesnt give quest credit 

![image](https://user-images.githubusercontent.com/39439201/64478899-bf459080-d1af-11e9-9a65-69ff71dc89e4.png)

**Comment by Bathelmo** [comment]
lol okay, will check

**Comment by mfranca0009** [comment]
All set, needs testing in PTR 👍 

Made a change to the quest item spell, so that the player can select the Hill Fawn, instead of simply using the quest item and it automatically casts on a Hill Fawn implicitly. This prevents casting the spell multiple times and it lands on the same Hill Fawn.

Spell requires a Hill Fawn targeted, the hearts now appear after this change.

Quest credit is now given when Hill Fawn is hit with the quest item spell.

**Comment by Echinaceax** [comment]
confirmed fixed in PTR

![image](https://user-images.githubusercontent.com/39439201/103111148-0fb55b80-464a-11eb-87c7-d3b47db83464.png)

note: pathing in a new report soon
