### ISSUE TITLE
[Dungeon] Shadowfang Keep hc - Reputations

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#3140]
**Links:**
https://www.wowhead.com/shadowfang-keep
from WoWHead

**What is happening:**
Noone of the 5 bosses of Shadowfang Keep hc is giving reputation. 
The trash mobs are giving reputation as it should be.

**What should happen:**
Killing a boss in hc mode you should gain reputation with the faction of the tabard you're wearing.

List of the bosses:
https://www.wowhead.com/npc=46962/baron-ashbury
https://www.wowhead.com/npc=3887/baron-silverlaine
https://www.wowhead.com/npc=4278/commander-springvale
https://www.wowhead.com/npc=46963/lord-walden
https://www.wowhead.com/npc=46964/lord-godfrey

Old report about reputation issues (only trash mobs) #1980

**Comment by sarahkay88** [comment]
more info? which rep is it suppose to give?

**Comment by Rushor** [comment]
already fixed

https://i.imgur.com/GLbxMDQ.jpg
