### ISSUE TITLE
[Achievement] You'll feel right as Rain - Cooking

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#3142]
**Links:**
![InkedScreenshot_15_LI](https://user-images.githubusercontent.com/52254524/63536382-29a5d200-c51c-11e9-8607-5ff590fb8979.jpg)

from WoWHead or our Armory
https://cata-twinhead.twinstar.cz/index.php?achievement=5779
https://www.wowhead.com/achievement=5779/youll-feel-right-as-rain
**What is happening:**

I don't get the achievement even after having 101 stacks of the Satisfied buff.

**What should happen:**

I should get the achievement after getting 91 stacks of the Satisfied buff.

**Comment by sarahkay88** [comment]
tested on dev I ate 110 cookies n no achievement granted :)

**Comment by Echinaceax** [comment]
Added to main report #4505
