### ISSUE TITLE
[Mail] items mailed between alts arrived with 0/0 durability (visual bug)

### ISSUE THREAD

**Issue by Druhl** [WoWManiaUK/Blackwing-Lair#3143]
Sent a few items between alts (green gear, some mats, a fishing pole) and all items with durability got set to 0/0. They definitely weren't before.

![WoWScrnShot_082219_144201](https://user-images.githubusercontent.com/19803911/63541348-e29fe880-c4eb-11e9-8c73-0ffd9e0e7993.jpg)
![WoWScrnShot_082219_144202](https://user-images.githubusercontent.com/19803911/63541350-e29fe880-c4eb-11e9-981c-498ec80f8903.jpg)
![WoWScrnShot_082219_144205](https://user-images.githubusercontent.com/19803911/63541351-e29fe880-c4eb-11e9-8e16-98b0ee27ed6e.jpg)
![WoWScrnShot_082219_144214](https://user-images.githubusercontent.com/19803911/63541352-e29fe880-c4eb-11e9-9ed0-5254a8503977.jpg)
![WoWScrnShot_082219_144159](https://user-images.githubusercontent.com/19803911/63541353-e29fe880-c4eb-11e9-832c-96f3a658405a.jpg)
![WoWScrnShot_082219_144200](https://user-images.githubusercontent.com/19803911/63541354-e3387f00-c4eb-11e9-9a42-f7fc34d8f1b0.jpg)

**Comment by Kitzunu** [comment]
Only visual, shows correctly after you pick up the item

**Comment by Druhl** [comment]
Confirmed, items were okay when picked up.

**Comment by Ovahlord** [comment]
https://eu.battle.net/forums/en/wow/topic/3056495855
This is a clientside 4.3.4 bug and is unfixable.
