### ISSUE TITLE
[Quest item] Deepholm: Deepvein's Patch Kit

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3144]
**Links:**
https://www.wowhead.com/item=58965/deepveins-patch-kit
https://www.wowhead.com/quest=26591/battlefront-triage

**What is happening:**

You cant heal anything with quest item.

**What should happen:**

You should able to heal NPCs for quest credits.

**Comment by sarahkay88** [comment]
Is healing players instead of npc for upto 15k heals

**Comment by Rushor** [comment]
can now only be used in 10 ards range to the questcreature. + credit will be given.
