### ISSUE TITLE
[Object] Lavascale Catfish - Missing

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#3145]
**Links:**
https://www.wowhead.com/item=53068/lavascale-catfish
from WoWHead

**What is happening:**
Fishing in the required zones, you never get this fish. You get low level fishes instead.

**What should happen:**
Fishing in Cataclysm zones, you should get this fish, very important for cooking because is a reagent for powerful recipes.
https://www.wowhead.com/spell=88024/lavascale-fillet
https://www.wowhead.com/spell=88025/lavascale-minestrone
https://www.wowhead.com/spell=88036/seafood-magnifique-feast

**Comment by Echinaceax** [comment]
tested and none fished for me in deepholm, should (28%) from deepholm
https://cata-twinhead.twinstar.cz/?item=53068

**Comment by Rushor** [comment]
added with 25 percent chance in those zones: 5042, 5034, 1581, 4926, 4945, 4950, 5035, 5396
