### ISSUE TITLE
[Dungeon/currency] Halls of Origination

### ISSUE THREAD

**Issue by fuzzydunlop** [WoWManiaUK/Blackwing-Lair#3146]
**What is happening:** The 4 bosses on the second level do not give any JP when killed in heroic mode.

**What should happen:** They should give 75/77 JP when killed

**Comment by Ovahlord** [comment]
That's wrong. They are suposed to give 70. 77 Is  what you get when you have the guild perk bonus.

**Comment by Echinaceax** [comment]
![jp cata](https://user-images.githubusercontent.com/39439201/63635925-8d3d1600-c668-11e9-9c96-64794be72e45.jpg)

**Comment by Eirolla** [comment]
https://www.wowhead.com/npc=39731/ammunae
https://www.wowhead.com/npc=39587/isiset
https://www.wowhead.com/npc=39378/rajh
https://www.wowhead.com/npc=39732/setesh

**Comment by Ovahlord** [comment]
That list of Justice Points gains is not correct as it is a post 4.3 patch version.
I have a made documentation about justice point handlings a while ago that contains all 4.3 data.

> Justice Points
> Justice Points are rewarded from certain quests, random dungeon runs and from defeating older or non-heroic Cataclysm dungeons.
> 
> Level 84 Cataclysm Dungeons award 35 Justice Points per boss kill.
> Level 85 Cataclysm Heroic Dungeons award 70 Justice Points per boss kill.
> Random WotLK Normal Dungeons award 12 Justice Points per day.
> Random WotLK Heroic Dungeons award 24 Justice Points up to 7 times per week.
> Random Cataclysm Normal Dungeons award 150 Justice Points up to 7 times per week.
> Random Cataclysm Heroic Dungeons award 150 Justice Points when the player has reached his weekly Valor Points cap.
> 
> Justice Points have a total cap of 4000. Every Justice Point beyond that cap will be converted into 47s and 50c per point.
>

**Comment by Kitzunu** [comment]
Thank you @Ovahlord <3
