### ISSUE TITLE
[loot / mobs] killed mobs jump up to high position out of reach, can't loot

### ISSUE THREAD

**Issue by Druhl** [WoWManiaUK/Blackwing-Lair#3148]
**What should be happening:**
killed mobs lay on ground to be looted

**What is happening:**
though fought at ground level, after death they shoot up into the sky well beyond the height a player can loot them

I experienced this 2 or 3 times.

This was in Loch Modan, where I did notice a lot of mobs spawning by "dropping in from the sky" as I grew near them, perhaps these two things are related.

![WoWScrnShot_082319_175940](https://user-images.githubusercontent.com/19803911/63638176-c074aa80-c652-11e9-9ebe-cdf51dfe8743.jpg)

**Comment by Echinaceax** [comment]
@Druhl need list of NPC names and links

**Comment by Druhl** [comment]
The mobs in this case were Loch Buzzards.

https://www.wowhead.com/npc=44184/loch-buzzard

**Comment by sarahkay88** [comment]
i cannot reporduce this everyone i killed fell to the ground.
