### ISSUE TITLE
[Quest/Item] Helcular's rod giveth - ID 28331 - Hillsbrad Foothills

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#315]
[Quest] helcular's rod giveth.

Quest - https://www.wowhead.com/quest=28331/helculars-rod-giveth

**The quest item given is meant to empower the Dark ranger as seen in the video**
 
Video - https://www.youtube.com/watch?v=Lf4m9RiovZ4

**But it empowers me** 

![dark ranger](https://user-images.githubusercontent.com/39439201/50566974-e35af300-0d3f-11e9-987c-8c8746fca131.jpg)

![helculars rod](https://user-images.githubusercontent.com/39439201/50567001-3c2a8b80-0d40-11e9-994a-f18926e9df95.jpg)

![helculars ire](https://user-images.githubusercontent.com/39439201/50567065-e99d9f00-0d40-11e9-9f1f-a69ccf194b10.jpg)

![rod empowerment](https://user-images.githubusercontent.com/39439201/50566916-4304ce80-0d3f-11e9-9552-e630b07e7b44.jpg)

![it empowers me instead](https://user-images.githubusercontent.com/39439201/50566913-37190c80-0d3f-11e9-8341-b3d31668fa8f.jpg)

**Comment by Dranah** [comment]
Is this really an issue with the quest or just the item?
As in, the quest is possible to complete?

**Comment by Echinaceax** [comment]
No, cant complete it. the dark ranger needs the buff 
its the quest item with the problem

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/63637910-5ffd6180-c682-11e9-8f18-408e348f060c.png)

fixed in the other duplicate report #340
