### ISSUE TITLE
Quests in Lor'Danel and Ruins of Auberdine not working

### ISSUE THREAD

**Issue by gonimajuan** [WoWManiaUK/Blackwing-Lair#3152]
from WoWHead or our Armory

**What is happening: The quests "Against the Wind" and "Coaxing the Spirits" aren't working. In "Against the Wind", i try destroying the bracelets in Auberdine Moonwell, but it still says "Auberdine Moonwell required". And in "Coaxing the Spirits", when i'm near a body i need to coax, i right click and there's only a small text with no dialogue option. Already relogged, abandoned quests and disabled add-ons.

**What should happen: Whenever i right click a bracelet while i'm in the auberdine moonwell, they should be destroyed. And, when i right click a body to coax their spirit, a dialogue option should appear so i can finish the quest.

**Comment by Echinaceax** [comment]
reported here #1060 #707 #710
