### ISSUE TITLE
[QUEST]Deepholm: Question the Slaves

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3154]
**Links:**

https://www.wowhead.com/quest=26261/question-the-slaves
https://www.wowhead.com/npc=44772/slave-conversation-credit

**What is happening:**

No credits after "freeing slave".

**What should happen:**

After freeing a slave, we should be complete 1 of credit.

**Comment by Rushor** [comment]
fixed https://i.imgur.com/a5KK26X.jpg
