### ISSUE TITLE
[QUEST] Deepholm: Quicksilver Submersion

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3156]
**Links:**

https://www.wowhead.com/quest=27010/quicksilver-submersion

**What is happening:**

no dialogue starts when I approach.

**What should happen:**

With https://www.wowhead.com/item=60809 buff, https://www.wowhead.com/npc=44875/millhouse-manastorm should start a dialogue when I approach

**Comment by Rushor** [comment]
you get the credit now

![I](https://i.imgur.com/sa2hqVk.jpg)
