### ISSUE TITLE
[Guild] Rank Permissions

### ISSUE THREAD

**Issue by Denrunmt** [WoWManiaUK/Blackwing-Lair#3159]
**Links:**
![Screenshot_26](https://user-images.githubusercontent.com/52254524/63643187-bd6dce80-c6d3-11e9-9d24-f75fb2a202f6.png)
![Screenshot_17](https://user-images.githubusercontent.com/52254524/63643209-366d2600-c6d4-11e9-82b5-d833e8aeb1c8.png)
![Screenshot_25](https://user-images.githubusercontent.com/52254524/63643211-3c630700-c6d4-11e9-9f82-cf20b2e28f13.png)

from WoWHead or our Armory

**What is happening:**

All guild ranks can see and type in the officer chat even though they don't have the permission to do that. The empty space between the guildies marked in the first screenshot is another proof for #3150. There is an guildie online that joined us 4 hrs ago but he is nameless/rankless/zoneless. 

**What should happen:**

Only the guild ranks that have "Officerchat Listen" and "Officerchat Speak" marked/checked in the Rank Permissions should have the permission to see or speak in the officer chat.

**Comment by Echinaceax** [comment]
Update:
I have tested the officer chat with a trial rank and eirolla couldnt see or type on officer chat 

![officer chat](https://user-images.githubusercontent.com/39439201/63650320-acf83b00-c749-11e9-833c-21648fcaead8.jpg)

**Comment by kDracku** [comment]
Funny , cuz in my guild this thing works ok.

**Comment by Echinaceax** [comment]
works on dev and our tester guild too @kDracku. its very odd 
Could be addons or something

**Comment by Echinaceax** [comment]
if anyone else has the issue make a comment and we will reopen it

**Comment by Echinaceax** [comment]
same happened again after 

1, demoted players to a different rank
2. deleted ranks we didnt need
3. sever crashed and rank reset to default 
4. Guild rank possions reset to default
5. Guildmaster has no permissions in guildbank tabs 
6. cant demote or premote

**Comment by Echinaceax** [comment]
moved to here #3150
