### ISSUE TITLE
 DK Spell "Rune Strike" is not working in Blood Presence

### ISSUE THREAD

**Issue by Shycazia** [WoWManiaUK/Blackwing-Lair#3160]
What is happening: 
The spell in my actionbar is glowing, but i cant use it. 

What should happen:
Rune Strike should be able to be used at all times in blood presence and not only after parrying/dodging.

![InkedWoWScrnShot_082519_024324_LI](https://user-images.githubusercontent.com/50558628/63644264-5a853300-c6e5-11e9-8b88-97f3647a9820.jpg)

**Comment by Sammy974** [comment]
Atm, it's not working at all in blood presence. Not after parrying/dodging, not anytime.

**Comment by kDracku** [comment]
I have the problem , if you die you cannot use anymore the Rune Strike . If you relog the rune strike works perfect
