### ISSUE TITLE
[Quest] Darkmoon Faire - 29509 - Putting the Crunch in the Frog

### ISSUE THREAD

**Issue by Druhl** [WoWManiaUK/Blackwing-Lair#3161]
https://www.wowhead.com/quest=29509/putting-the-crunch-in-the-frog

What should happen:
Quest item given is "breaded" by use of flour player provides, then modified quest object is "used" to "throw" 5 times into pot beside quest giver NPC, to complete the quest.

What does happen:
Quest item is successfully modified by the flour into the "throwable / usable" quest item, but clicking on item to "use" only produces the throwing animation, count does not increment and quest can not be completed. Further, modified quest item disappears after the one use, should last for 5 uses.

![WoWScrnShot_082519_150030](https://user-images.githubusercontent.com/19803911/63654680-af5b9480-c74b-11e9-8f6d-7c72b700634d.jpg)
![WoWScrnShot_082519_150037](https://user-images.githubusercontent.com/19803911/63654681-b387b200-c74b-11e9-8d8d-5d283f1b2728.jpg)
![WoWScrnShot_082519_150154](https://user-images.githubusercontent.com/19803911/63654682-b7b3cf80-c74b-11e9-911d-36444d7dde76.jpg)
![WoWScrnShot_082519_150155](https://user-images.githubusercontent.com/19803911/63654684-c00c0a80-c74b-11e9-8fa4-5d0ca25c81a5.jpg)
![WoWScrnShot_082519_150222](https://user-images.githubusercontent.com/19803911/63654686-c39f9180-c74b-11e9-91ab-986644ac7ab0.jpg)

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/hZTOnbe.jpg)
