### ISSUE TITLE
[Quest] Darkmoon Faire - 29513 - Spoilin' for Salty Sea Dogs

### ISSUE THREAD

**Issue by Druhl** [WoWManiaUK/Blackwing-Lair#3162]
https://www.wowhead.com/quest=29513/spoilin-for-salty-sea-dogs

What should happen:
Quest object fish should be caught at some low-to-medium drop rate

What does happen:
Quest object fish seem to never be caught (30-40 casts at +100 fishing skill).
Further, there were skill-ups on many casts that produced NO fish whatsoever.

**Comment by Rushor** [comment]
fishing loot to area 5861 ( Darkmoon Island) added. 60 percent chance to get it now.
