### ISSUE TITLE
[Quest] Darkmoon Faire - 30543 - Putting the Carnies Back Together Again

### ISSUE THREAD

**Issue by Druhl** [WoWManiaUK/Blackwing-Lair#3163]
https://www.wowhead.com/quest=30543/dnt-putting-the-carnies-back-together-again-tracker

(This quest is discontinued on retail, I hope this is still the right quest number)

What should happen:
Target NPCs are interacted with allowing player to click "bandage" 4 different times to advance to completion of quest

What does happen:
Animations of the bandaging appear correct, but counter does not increment, quest can not be completed.
![WoWScrnShot_082519_150350](https://user-images.githubusercontent.com/19803911/63655144-60fdc400-c752-11e9-9c4d-72d1c880bcd8.jpg)
![WoWScrnShot_082519_150352](https://user-images.githubusercontent.com/19803911/63655145-6ce98600-c752-11e9-8c89-a357c0a6ebe8.jpg)
![WoWScrnShot_082519_150354](https://user-images.githubusercontent.com/19803911/63655147-6f4be000-c752-11e9-816c-d2ec4d5d41d7.jpg)

**Comment by sarahkay88** [comment]
https://www.wowhead.com/quest=29512/deprecated-putting-the-carnies-back-together-again#comments

**Comment by sarahkay88** [comment]
I think this is because they are already full health and don't require healthing

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/NWABc2Z.jpg)

hp animation will be added in the future.
