### ISSUE TITLE
[Quest] Glorious Harvest - ID 28114 - Hillsbrad Foothills

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#317]
Quest - https://www.wowhead.com/quest=28114/glorious-harvest
Video - https://www.youtube.com/watch?v=arYq6ATLwk8

**Cant complete as eggs are attacked but dont add to kills still  0/60**

![0-60](https://user-images.githubusercontent.com/39439201/50569394-1b742d00-0d64-11e9-8e1c-eea026fe4067.jpg)

![full health egg](https://user-images.githubusercontent.com/39439201/50569378-dcde7280-0d63-11e9-9fef-23f99847a2dd.jpg)
![eggs killed are not working](https://user-images.githubusercontent.com/39439201/50569379-e071f980-0d63-11e9-92e7-19a3099f8434.jpg)
![attacked egg](https://user-images.githubusercontent.com/39439201/50569380-e7007100-0d63-11e9-85a1-86544fad5a5d.jpg)

**Comment by Dranah** [comment]
You're supposed to loot them, not just kill them.
Is the loot missing?
And where are the bears?

**Comment by Echinaceax** [comment]
no loot and bears are stood on the eggs , but in the video the eggs are on the bears back. but eggs was under the bears feet on all the eggs for that quest

**Comment by Dranah** [comment]
Confirmed, once you kill eggs they are not lootable.

**Comment by Rushor** [comment]
loot to the eggs added
