### ISSUE TITLE
[Quest] Conquer Echeyakee 

### ISSUE THREAD

**Issue by Malfaeous** [WoWManiaUK/Blackwing-Lair#3184]
**Links:**
https://classic.wowhead.com/quest=881/echeyakee
from WoWHead or our Armory

**What is happening:**

Keeps coming up coming up with "Requires Echeyakee's Lair" when I use the horn of Echeyakee even when in the right place 

**What should happen:**

Description
Whitemist, Echeyakee in the Tauren tongue, is the king of the savannah cats. He hunts with such stealth, they say he's like a thin, white mist on the earth. And he kills so fast his prey have no time for fear, or pain.

The Tauren say he is both mercy and death.

You will learn if that's true, for I now set you on the path to hunt Echeyakee. His lair is northeast of the Crossroads, among the bones of giant Kodo

Go. Blow this horn when you reach his lair. Blow the horn, and he will come.

Progress
The great cat calls to you, <name>.
Completion
You've beaten Echeyakee, and though his days of hunting are over... his spirit is with you.  He will show you the strength found in subtlety, and the honor in mercy.

Your path is still long, <class>.  Let's hope you stride it well.
Rewards
You will receive: 0
Gains
Upon completion of this quest you will gain:
1,450 experience
150 reputation with Orgrimmar

**Note** even after looking this up to make sure I was in the right place, I abandoned the quest twice, and reacquired the quest again, following the instructions again it still came up with the same result.

**Comment by Echinaceax** [comment]
Already reported here #961
