### ISSUE TITLE
[Glyph] of Shadow Word: Death - Priest

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#3187]
**Links:**
https://cata-twinhead.twinstar.cz/?item=42414

**What is happening:**
When you cast Shadow Word: Death with this glyph, at the right conditions, the cooldown of the ability is not reset.

**What should happen:**
If your Shadow Word: Death fails to kill the target at or below 25% health, your Shadow Word: Death's cooldown is instantly reset. This effect cannot occur more often than once every 6sec.
You should be able to cast 2 Shadow Word: Death in a row before his 6sec cd.

**Comment by hediunchained** [comment]
it works and you can cast two SwD in a sequence
but the problem is that the first one doesnt cause a Global CD so it looks like it didint reset, you can test it with the masochism talent and it gives mana each time its used

**Comment by Sammy974** [comment]
A friend tested it and he's sure it doesn't work. I'll ask him to test it better, thanx for the comment ;)
