### ISSUE TITLE
[Quest] Traitors Among Us - Dustwallow Marsh

### ISSUE THREAD

**Issue by Juggermott** [WoWManiaUK/Blackwing-Lair#3188]
**Links:**
From youtube, a video of the quest: 
https://www.youtube.com/watch?v=DHzve5DxV6s

from WoWHead or our Armory:
https://www.wowhead.com/quest=27210/traitors-among-us

**What is happening:**
Cannot interact with "Deserter Agitator"s to expose them.

**What should happen:**
When clicking on them to speak with them, there should be a chat option. "Your propaganda won't work on me. Spout your treasonous filth elsewhere, traitor!"

The deserter then responds with a /yell "If you think you can stop us, you're mistaken, 'friend'." Then a fight ensues between you and said deserter.

**Comment by Echinaceax** [comment]
Already reported #1795
sometimes the reports are wording differenly so be careful not to do duplicates please

**Comment by Juggermott** [comment]
Apologies. I only reported what I can across. Shame on me, I should've checked first.

Sent from Yahoo Mail on Android 
 
  On Fri, Aug 30, 2019 at 1:16, Echinaceax<notifications@github.com> wrote:   
Already reported #1795
sometimes the reports are wording differenly so be careful not to do duplicates please

**Comment by Echinaceax** [comment]
> Apologies. I only reported what I can across. Shame on me, I should've checked first. 

thats ok, no harm done :)
