### ISSUE TITLE
[Companion] Argent Gruntling - Argent Tournament

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#3192]
**Links:**
https://www.wowhead.com/spell=62746/argent-gruntling
https://wowwiki.fandom.com/wiki/Argent_Gruntling

**What is happening:**
The vendor function doesn't work.

![20190831_005045](https://user-images.githubusercontent.com/45459932/64055624-ef78a800-cb8d-11e9-84b6-8b4ab40b5016.jpg)

**What should happen:**
Interacting with him, he should open the vendor window.
This is very useful, because it allows you to have a vendor everywhere.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/EcRUYhj.jpg)

added
