### ISSUE TITLE
[Worgen] Two Forms

### ISSUE THREAD

**Issue by Amaterasuu** [WoWManiaUK/Blackwing-Lair#3194]
**Link**
https://www.wowhead.com/spell=68996/two-forms

**What is happening:**
As a Worgen Druid I've not been able to use Two Forms -  I just get the error that "You cannot transform right now" I've no idea what other information to give you on this - 

**What should happen:**
Should transform into Human from Worgen and Vice versa :)

**Comment by Keader** [comment]
Working fine to me.
Cant reproduce.

**Comment by Druhl** [comment]
I can't transform either, Worgen Priest.

Have never been able to since getting the ability, always the "you cannot transform right now" message, unaffected by level, location, combat in/out, relogging, etc.

![WoWScrnShot_101619_212134](https://user-images.githubusercontent.com/19803911/66970317-1108f280-f05b-11e9-96b2-46107899e4ef.jpg)

**Comment by Druhl** [comment]
@Echinaceax Just wondering - do the other contributors to this issue see my reply even though it was closed, or only now that I tagged you? i.e. if I do encounter an issue that got marked closed how should I alert people?

**Comment by Echinaceax** [comment]
> @Echinaceax Just wondering - do the other contributors to this issue see my reply even though it was closed, or only now that I tagged you? i.e. if I do encounter an issue that got marked closed how should I alert people?

@Druhl 
Ive re opened this for you, because it does still need fixing, the trouble Keader (our coder) is having is reproducing this issue so ... if you can give here the steps to how you "trigger" this to happen it would help a great deal for the coder. thanks

**Comment by sarahkay88** [comment]
OK I'm level 50 stood in the inn in Stormwind and I get the same message.  you cannot transform right now.

**Comment by Echinaceax** [comment]
Can you SS the spell Ids from game @sarahkay88 please ?

**Comment by Echinaceax** [comment]
@sarahkay88 and are the link and the spell IDs ingame the same ?

**Comment by sarahkay88** [comment]
no but I can tell you it  id:68996, my pc stopped doing ss for some reason

**Comment by sarahkay88** [comment]
so guys I have a theory, to get this spell you have to drink from 3 wells in quest https://www.wowhead.com/quest=24593/neither-human-nor-beast.
maybe its actually something to do with the way this quest works.
I did this quest and completed it. but maybe there was a buff I was suppose to receive that I didnt. maybe the issue likes with the quest and not the spell

**Comment by sarahkay88** [comment]
after watching the video in the link I notice one difference. on the video when you drink from the wells the light goes on the wells. but on our realm when you drink from the wells the light goes on the player... maybe this is what's causing it

**Comment by Echinaceax** [comment]
Ah, nice catch angel :)

**Comment by Druhl** [comment]
I did the wells quest a week or so ago but I believe (90% sure) I too experienced the light on the player rather than the well. The three wells did each advance the three different quest criteria, following which the quest was completable and the ability was rewarded, seemingly as normal - it just doesn't work.

**Comment by Keader** [comment]
Not related with quest.
But i did a little fix, should work now.

**Comment by sarahkay88** [comment]
ok made a new toon and levelled it from start to this point and after this quest the spell twoform does indeed work and turned me bk into a feamle human... can test with an already 85 but cant see why it would. ty @Keader 
can I also say that the graphic for when she turn back to worgen looks cool lol

**Comment by Druhl** [comment]
Mine is working as well now.

Thank you!
