### ISSUE TITLE
[Spell][Palladin] Touched by the light

### ISSUE THREAD

**Issue by KrinkHorde** [WoWManiaUK/Blackwing-Lair#3199]
**Links:**
https://wowwiki.fandom.com/wiki/Touched_by_the_Light
**What is happening:**
Spell does not give you the hit it should. The increase in spell power from str works same with stamina increase
**What should happen:**
Spell should increase your spell hit by 8%

**Comment by Keader** [comment]
Fixed.
But 8% hit will not appear in character interface. But will take account to decide if a spell hit or miss.

**Comment by KrinkHorde** [comment]
Every serwer i played hit was also shown in the character ui ;)

**Comment by Keader** [comment]
Fixed visual issue.

**Comment by KrinkHorde** [comment]
when will fix hit main serwer ? / i'm testing Vengeance at the moment something is fucked up bcs AP gain is decreasing with every attack that prevents from stacking ap in longer fights anyway i need more tests to post anything :)

**Comment by Keader** [comment]
i realy dont know when next update will be.

**Comment by Echinaceax** [comment]
wednesady i think guys
