### ISSUE TITLE
[Spell] Eclipse (Solar) on level 1 druids

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#32]
spell ID 48517

New bug, wasn't happening few days ago.
What happens: You receive this buff from lvl 1 as druid upon each wrath you cast, increasing your nature damage by 25% (it's not visual bug, wrath damage increases).

How it should work: Eclipse mechanism should never activate below lvl 10 as you don't have a specialization or an eclipse bar yet.

**Comment by fvicaria** [comment]
As far as I can see this one is AS-IS.
You get when you cast some spells.
2912, 5176, 78674 - Starfire, Wrath, and Starsurge

**Comment by Dranah** [comment]
Looks fine now.
