### ISSUE TITLE
[Palladin][Spell][NPC] Guardian of Ancient Kings 

### ISSUE THREAD

**Issue by KrinkHorde** [WoWManiaUK/Blackwing-Lair#3200]
**Links:**
https://www.wowhead.com/spell=86659/guardian-of-ancient-kings
**What is happening:**
All of the angel skills works ok BUT he is targetable and got 12k hp, can be killed with one shot by mobs and even aoe spells works on it / In retri spec in moment of summoning it's not on assist mode , while you CC one target with repetance and summon angel while fighting 2nd target angel goes for CCed one( repetance need only one hit to break so it's esp painfull in pvp scenario) not to mention using it while in dunegon group.
**What should happen:**
Angel should not be targetable and be alive through full durotation of spell / be on assist mode while summoned. This ability is worthless bcs angel die in an instant while summoned in combat where mobs use aoe abilites or can agro to angel :)

**Comment by kDracku** [comment]
Can confirm
