### ISSUE TITLE
[Boss] Husam - Lost City of the Tol'vir (HC)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3207]
**Links:**
https://www.wowhead.com/npc=44577/general-husam

![husam](https://user-images.githubusercontent.com/39439201/64238425-ae222880-cefe-11e9-9638-fe42225d232a.jpg)

**What is happening:**
- Only drops one justice point 

**What should happen:**
- Should drop 70 (75 guild rep) 

![hc](https://user-images.githubusercontent.com/39439201/64240232-dfe8be80-cf01-11e9-8e94-70b208a89723.jpg)

**Comment by Rushor** [comment]
remember that you need to have at least 1 justive point already in order to display it right. see https://github.com/WoWManiaUK/Blackwing-Lair/issues/2916
