### ISSUE TITLE
[Boss] High Prophet Barim - Lost City of the Tol'vir (HC)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3208]
**Links:**

https://www.wowhead.com/npc=43612/high-prophet-barim

**What is happening:**
- Doesnt drop any justice points

**What should happen:**
- should drop 70 (75 guild rep)

![hc](https://user-images.githubusercontent.com/39439201/64240200-d0697580-cf01-11e9-97e1-01b635ffc4d6.jpg)

**Comment by Rushor** [comment]
![I](https://i.imgur.com/S2Ffmfw.jpg)
