### ISSUE TITLE
[Boss] lockmaw / Augh - Lost City of the Tol'vir (HC)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3209]
**Links:**

https://www.wowhead.com/npc=43614/lockmaw
https://www.wowhead.com/npc=49045/augh

**What is happening**:
- Doesnt drop any justice points

**What should happen:**

- should drop 70 (75 guild rep)

![hc](https://user-images.githubusercontent.com/39439201/64240130-b6c82e00-cf01-11e9-91c4-fd35ad0e3e63.jpg)

**Comment by Rushor** [comment]
remember that you need to have at least 1 justive point already in order to display it right. see https://github.com/WoWManiaUK/Blackwing-Lair/issues/2916
