### ISSUE TITLE
[NPC] Sraaz -  Ironforge

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#321]
NPC - https://www.wowhead.com/npc=9099/sraaz
this is the pie vendor in Ironfordge that can be located walking around the centre, however he does not sell the item https://www.wowhead.com/item=8950/homemade-cherry-pie has he should. You cannot trade items you want to sell either.
![world of warcraft 01_01_2019 16_16_21](https://user-images.githubusercontent.com/42302580/50574471-1608f800-0de1-11e9-8394-37a677e5ab2a.png)

**Comment by Saintres** [comment]
This NPC is not fixed

**Comment by Echinaceax** [comment]
@Saintres 
it in the next set of fixes for this week 
when quests are added to PTR then this will be closed issues. 

@Kitzunu can we confirm its been sent too PTR?
as this was close before saaint told me about it

**Comment by Kitzunu** [comment]
This works on dev.

Janitor might have forgot to send the file

**Comment by Kitzunu** [comment]
Well some kind of regression is made here.
It does not work on Dev and not PTR anymore

**Comment by Echinaceax** [comment]
still doesnt work - still no pies :)

![stillll no](https://user-images.githubusercontent.com/39439201/56068019-94304f80-5d7d-11e9-8244-9e84bec1b7c3.jpg)

**Comment by Kitzunu** [comment]
Well. Now this pie lover is selling his pies.

Fixed on dev. 
DELETING CACHE IS A MUST!

**Comment by sarahkay88** [comment]
@Kitzunu  - not selling again lol
![World of Warcraft 18_04_2019 22_59_18](https://user-images.githubusercontent.com/42302580/56393957-c33b3b00-622d-11e9-8993-775e4c1ce60e.png)

**Comment by Echinaceax** [comment]
Grrrrrrr
@Kitzunu it was fixed ...reverted is too then it seems

**Comment by Kitzunu** [comment]
Isnt reverted, its something new which I cant figure out atm

**Comment by Rushor** [comment]
hmm really strange, not fixed yet

**Comment by Echinaceax** [comment]
@Kitzunu - still nothing for sale

**Comment by Echinaceax** [comment]
@wow-mania - thank you :)
