### ISSUE TITLE
[Boss] Siamat - Lost City of the Tol'vir (HC)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3210]
**Links:**

https://www.wowhead.com/npc=44819/siamat

**What is happening:**
- Doesnt drop justice points

**What should happen:**
- should drop 70 (75 guild rep)

![hc](https://user-images.githubusercontent.com/39439201/64240111-ab750280-cf01-11e9-915b-336d6ecb49a0.jpg)

**Comment by Rushor** [comment]
remember that you need to have at least 1 justive point already in order to display it right. see https://github.com/WoWManiaUK/Blackwing-Lair/issues/2916
