### ISSUE TITLE
[NPC] Georgia <Bat Handler>

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3217]
**Links:**
https://classic.wowhead.com/npc=12636/georgia

![bathandler with gryphin](https://user-images.githubusercontent.com/39439201/64332852-9bc6ee00-cfd5-11e9-8011-e9c357c82719.jpg)

**What is happening:**
- <Bat Handler> Gives a gryphon not a bat 

**What should happen:**
- im sure that a bat mount should be given not a gryphon as horde

**Comment by Rushor** [comment]
i think that is dbc related

**Comment by Kitzunu** [comment]
Invalid, due to this being an argent place, they only use Argent Gryphons.

This is how it works in retail too and no changelog anywhere stating otherwise.
