### ISSUE TITLE
[General] Stuck on flying mount

### ISSUE THREAD

**Issue by BartDirven** [WoWManiaUK/Blackwing-Lair#3219]
**What is happening:**
When taking the flight path from Eastern Plaguelands (Light's Shield Tower) to The Badlands (Fuselight), the hippogryph suddenly teleported to the location of my hearthstone (i.e. Felwood). I'm now stuck on the flying mount and unable to interact with anything. The same happened to my friend Grobbekuiken. Re-logging doesn't work and puts us back in Felwood on the hippogryphs.

I've checked, and we both have the most up-to-date version of the launcher.

**What should happen:**
The flight path should work just fine. And we'd like our characters to be reset to somewhere, because we cannot do anything now.

**Comment by Echinaceax** [comment]
Already reported here #3216
