### ISSUE TITLE
[Quest] Gothik the Harvester - DK chain order issue I. - Plaguelands: The Scarlet Enclave

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#322]
https://www.wowhead.com/quest=12697/gothik-the-harvester

Should have the following prerequisites:
https://www.wowhead.com/quest=12687/into-the-realm-of-shadows
https://www.wowhead.com/quest=12678/if-chaos-drives-let-suffering-hold-the-reins
https://www.wowhead.com/quest=12679/tonight-we-dine-in-havenshire
https://www.wowhead.com/quest=12733/deaths-challenge

1) Currently you can obtain this quest without completing all the four above ones, which means you are able to accidentally skip multiple mandatory quests. 
The prerequisites for unlocking need to be fixed to ensure the DK does not get phased away before handing in all the needed quests.

2) Cosmetic issue, but this quest need to be started by Prince Valanar (ID 28377), not Gothik himself, as it sends you to speak to Gothik.

**Comment by Kitzunu** [comment]
Fixed, now requires all 4 quests to be completed.

Also starts from Valanar
