### ISSUE TITLE
[Object] Guild Vault Voucher 7th Slot - Guild Vendor Goram

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#3220]
**Links:**
https://www.wowhead.com/item=62286/guild-vault-voucher-7th-slot
from WoWHead
https://it.wowhead.com/npc=46572/goram
#1263

**What is happening:**
Goram is not selling the object neither if you have the required guild status. Tested with guild master.

**What should happen:**
Goram should sell the guild rewards according to the guild level/achivements.

Same problem with Kim Horn #1246
Both Larissia (Silvermoon) and Riha (Shatthrath) are fine.

**Comment by Kitzunu** [comment]
conditions are fucked for most of the vendors....

@Rushor Maybe you can redo them and teach me how I should make them, cuz atm they work that you only can see an item if you are that rep and got the achieve, but not if you are higher rep...

**Comment by Rushor** [comment]
you just need to add the numbers  
16 = Friendly
 32 = Honored
 64 = Revered
128 = Exalted

so 
16 = Friendly +
 32 = Honored +
 64 = Revered +
128 = Exalted = 240

fixed it already
