### ISSUE TITLE
[Quest] [Therazane's Mercy] 

### ISSUE THREAD

**Issue by popepope** [WoWManiaUK/Blackwing-Lair#3224]
**Links:**

from WoWHead or our Armory

**What is happening:**
There is no NPCs.

**What should happen:**

Defeat Boldrich Stonerender and High Priestess Lorthuna

**Comment by Rushor** [comment]
http://cata.cavernoftime.com/quest=26832

**Comment by Rushor** [comment]
all npcs added

**Comment by Rushor** [comment]
![I](https://i.imgur.com/ReD76ao.jpg)
