### ISSUE TITLE
[Quest] Impatience 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3226]
**Links:**
quest https://www.wowhead.com/quest=27488/impatience
quest back https://www.wowhead.com/npc=45729/tarenar-sunstrike

**What is happening:**
- cant hand quest back npc missing

**What should happen:**
Tarenar Sunstrike should be there to hand quest back

side note: needed for the series

![image](https://user-images.githubusercontent.com/39439201/64448131-42e27d00-d0dd-11e9-93eb-12b6b0868804.png)

**Comment by Rushor** [comment]
added on a few more spots as can be ssen in https://www.wowhead.com/npc=45729/tarenar-sunstrike#comments
