### ISSUE TITLE
[Item/object] Windswept Balloon

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3227]
**Links:**
https://www.wowhead.com/object=209058/windswept-balloon

**What is happening:**
Balloons are clickable without having the quest

**What should happen:**
should be clickable with quest required
horde https://www.wowhead.com/quest=29401/blown-away
ally https://www.wowhead.com/quest=29412/blown-away

**Comment by Rushor** [comment]
condition that you need the quest added
