### ISSUE TITLE
[Quest] Drag 'em Down and Hook 'em High - duplicate quest diffent names

### ISSUE THREAD

**Issue by popepope** [WoWManiaUK/Blackwing-Lair#3229]
**link**
https://www.wowhead.com/quest=27929/drag-em-down
https://www.wowhead.com/npc=46313/narkrall-rakeclaw

https://www.wowhead.com/quest=28874/hook-em-high
https://www.wowhead.com/npc=46318/harkkan (daily) 

**whats happening** 
- duplicate quests different names and different quest givers 
- one a daily one a quest

just checking if this is correct to be like this

**Comment by Rushor** [comment]
hm yes, the both quests should be there https://www.youtube.com/watch?v=TDuG45MBDWI and https://www.youtube.com/watch?v=5FC7-_ZoHZ0
