### ISSUE TITLE
[Quest] Behind Scarlet Lines - DK chain order II. Plaguelands: The Scarlet Enclave

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#323]
https://www.wowhead.com/quest=12723/behind-scarlet-lines
This quest currently gets unlocked together with the Crypt quests after handing in https://www.wowhead.com/quest=12714/the-will-of-the-lich-king which is the root of all subsequent phase issues reported by slaniaxx earlier https://github.com/WoWManiaUK/Blackwing-Lair/issues/260

How it should work:
This quest should be unlocked only after handing in https://www.wowhead.com/quest=12720/how-to-win-friends-and-influence-enemies as a prerequisite.

**Comment by Kitzunu** [comment]
Fixed
