### ISSUE TITLE
[NPC] Boss Freya Hard Mode - Crash Server few time.

### ISSUE THREAD

**Issue by Bloodborne93** [WoWManiaUK/Blackwing-Lair#3232]
**Links:**
https://it.wowhead.com/npc=32906/freya

from WoWHead

**What is happening:**
After we have killed Freya, the server crashed few times and more, i speaking with the GM with it so i post it right now. We Apologies about that because we didn't know that bug. Hope it's a help for you.

**What should happen:**
The Server mustn't crash after the kill.

**Comment by Kitzunu** [comment]
From previous issues just like this one, I know that this is most likely way too little info.

Get us reproduction steps such as what classes and specs did the players in the raid play, did you do something out of the ordinary before the kill etc.

**Comment by Bloodborne93** [comment]
We killed Thorim first, so we rush into the Conservatory of Life while walking, never taked the portal. Buff up and then starts Freya Hard Mode, we have wipped one time, so release and coming again, after this,we have done her and then the server crashed. Classes were: Blood Death Knight, Warrior Fury, Druid Resto and Balance, Death Knight Blood Dps, Mage Arcane and Priest Discipline.

**Comment by Echinaceax** [comment]
>Classes were: Blood Death Knight, Warrior Fury, Druid Resto and Balance, Death Knight Blood Dps, Mage Arcane and Priest Discipline.

you had 7 players in there (multibox) ?

**Comment by Bloodborne93** [comment]
nope, all players, no multibox

**Comment by Echinaceax** [comment]
1. Blood Death Knight, 
2. Warrior Fury, 
3. Druid Resto
4. druid Balance, 
5. Death Knight Blood Dps, 
6. Mage Arcane  
7 Priest Discipline. 

is 7 :)

**Comment by Bloodborne93** [comment]
![Party](https://user-images.githubusercontent.com/52720024/64493717-ef5e6380-d283-11e9-9423-fde1bd284522.jpg)
Here :) All Players here :)

**Comment by Rushor** [comment]
also crashed during the fight not only on kill

**Comment by Keader** [comment]
@fvicaria in this case, is better close Ulduar until be fixed.
It cause server freeze

**Comment by Keader** [comment]
I closed Ulduar for now, since freya causes freeze.
When we find the reason and fix it, we open it again.

**Comment by Echinaceax** [comment]
ok reopening this 

tested for other reason and saw how it crashed the server 

repro

1. Valk was on Freya , I was on Adds
2.  she yelled **His hold on me dissipates. I can see clearly once more. Thank you, heros.** and then Freya went friendly
3. Loot Chest dropped but couldnt loot it (server crashed just before or the looting of the chest crashed server)

chest is reported not lootable here  #3241

this is the part where it crashed after achv 

![ulduar faya](https://user-images.githubusercontent.com/39439201/100642774-81df9c80-3339-11eb-89c6-7bbd57adf8ae.jpg)

personally both me and Valk think the fraya's gift (loot chest) was the problem https://www.wowhead.com/object=194324/freyas-gift

**Comment by mfranca0009** [comment]
Issue resolved with a temporary fix that technically does the same thing as the previous approach, instead of despawning the elders they kill themselves if Freya has been killed and the elders are still alive.

If the real cause of the problem (grid issue) is resolved later, then the temporary fix can be reverted.
