### ISSUE TITLE
[NPC] Boss Hodir - Ulduar

### ISSUE THREAD

**Issue by Bloodborne93** [WoWManiaUK/Blackwing-Lair#3235]
**Links:**
https://it.wowhead.com/npc=32845/hodir

from WoWHead

**What is happening:**
Starting the fight, the boss don't move, he is stucking in his position, but he do some mechanics, like Flash Freeze and Frozen blow(but never hits a tank or others player).

**What should happen:**
After pulling Hodir must runs to the top aggro and engage the boss fight with hitting him with melee damage and Frozen Blow.

**Comment by Rushor** [comment]
attackable now https://i.imgur.com/VrLl7cd.jpg set aggressive
