### ISSUE TITLE
[NPC] Winter Jormungar from Ulduar.

### ISSUE THREAD

**Issue by Bloodborne93** [WoWManiaUK/Blackwing-Lair#3237]
**Links:**
https://www.wowhead.com/npc=34137/winter-jormungar#drops

from WoWHead

**What is happening:**
After they spawn from Snow Mounds, we can't target them and kill. No life bars show in the screen.
![Jormungarbug](https://user-images.githubusercontent.com/52720024/64491839-19585b80-d26d-11e9-90d1-44aa3f4045e3.jpg)

**What should happen:**
We must target and kill them.

**Comment by Rushor** [comment]
attackable in all modes now
