### ISSUE TITLE
[Spell] Flash Freeze, Boss Ulduar- Hodir .

### ISSUE THREAD

**Issue by Bloodborne93** [WoWManiaUK/Blackwing-Lair#3239]
**Links:**
https://www.wowhead.com/spell=61968/flash-freeze
from WoWHead 

**What is happening:**
after the spell was casted, it was impossible to target the ice blocks, because they got no life bars.
![Flash Freeze](https://user-images.githubusercontent.com/52720024/64491989-f333bb00-d26e-11e9-8dcd-3c5423ee5c8d.jpg)

**What should happen:**
We must target and kill them.

**Comment by Rushor** [comment]
unattackable and unselectable flag is now always removed on spawn
