### ISSUE TITLE
[Quest] How to Win Friends and Influence Enemies - DK chain order III. - Plaguelands: The Scarlet Enclave

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#324]
https://www.wowhead.com/quest=12720/how-to-win-friends-and-influence-enemies

This quest should have two prerequisites:
https://www.wowhead.com/quest=12719/nowhere-to-run-and-nowhere-to-hide
and https://www.wowhead.com/quest=12722/lambs-to-the-slaughter

1) Currently, it can be obtained as soon as you handed in the first one, which means you may accidentally skip the other mandatory quest. Root of phasing issues. missing talent points, you know the rest.

2) https://www.wowhead.com/item=39371/keleseths-persuader does not work, when the proc would occur, it gives an error "Can't do that while confused" as on my SS.
https://imgur.com/Otr1zSj
Credits to Slaniaxx by previous report https://github.com/WoWManiaUK/Blackwing-Lair/issues/224

**Comment by Kitzunu** [comment]
Quest order fixed
Please open a new ticket for the quest issue.

**Comment by Dranah** [comment]
Uhh, missing one prerequisite, sorry forgot from the report:
https://www.wowhead.com/quest=12716/the-plaguebringers-request

Add this too please thanks.

**Comment by Dranah** [comment]
Ok jani took care of this
