### ISSUE TITLE
[Raid/Ulduar] Freya's Gift.

### ISSUE THREAD

**Issue by Bloodborne93** [WoWManiaUK/Blackwing-Lair#3241]
**Links:**
https://www.wowhead.com/object=194324/freyas-gift
from WoWHead 

**What is happening:**
After killing her, we can't open the Cache.
![Freyacassa](https://user-images.githubusercontent.com/52720024/64492196-e5336980-d271-11e9-96a4-1cf7c83c4408.jpg)

**What should happen:**
We can open it and drop the rewards

**Comment by Rushor** [comment]
lootable now and gold added

**Comment by Bloodborne93** [comment]
Thank you man!
