### ISSUE TITLE
26953- zenkiki-the-druid- Western Plaguelands

### ISSUE THREAD

**Issue by Bathelmo** [WoWManiaUK/Blackwing-Lair#3243]
Quest - https://www.wowhead.com/quest=26953/zenkiki-the-druid

Druid helper isnt assigned
Quest not complitable without

**Comment by Kitzunu** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/375

**Comment by Echinaceax** [comment]
already reported as kitzunu linked above @Bathelmo
