### ISSUE TITLE
[Quest] Just the Tip (npc missing 45180) (issue 2) - Uldum

### ISSUE THREAD

**Issue by Lurc1981** [WoWManiaUK/Blackwing-Lair#3244]
**Links:**
https://www.wowhead.com/quest=27176/just-the-tip
https://www.wowhead.com/npc=45180/harrison-jones

**What is happening:**
You are given the Elaborate Disc. Sultan Oogah is available to kill, and does in fact drop the second piece necessary to create the Shaft of the Stars. There is no access to turn in the quest at Doctor Jones.

**What should happen:**
Doctor Jones doesn't move to the correct location to trigger the ability to turn this quest in. Possibly related to:
wowhead.com/quest=27431/tipping-the-balance
and Harrison Jones not moving like he's supposed to when interacted with to the location I am standing at that has an interactable Pygmy that you cannot actually interact with.

![WoWScrnShot_090919_165016](https://user-images.githubusercontent.com/54812659/64569140-2daa6000-d322-11e9-9dd6-fd6fc7855e01.jpg)

**Comment by mfranca0009** [comment]
NPC added, fixed.

The dead pygmy is from this quest: https://www.wowhead.com/quest=27141/premature-explosionation

When the explosion goes off, the chests that you hide in are thrown over to that location, knocking the pygmy out cold and killing it. When you get out of the chest, the NPC should be standing there after the cut-scene is finished.

premature explosionation quest is currently broken, will be fixed later.
