### ISSUE TITLE
[Boss/Raid] Kalecgos - Sunwell Plateau

### ISSUE THREAD

**Issue by Venom64bit** [WoWManiaUK/Blackwing-Lair#3248]
**Links:**
Boss: https://www.wowhead.com/npc=24850/kalecgos
Boss2: https://www.wowhead.com/npc=24892/sathrovarr-the-corruptor
**What is happening:**
The fight doesn't end when it should. The Bosses become immune at 1% without the end of the fight.

**What should happen:**
The Fight should end when both Kalecgos (Blue Dragon) and Sathrovarr (the Demon present in the other realm) reach 1% of life and become immune.

**Comment by Rushor** [comment]
alright both should be attackable now and the fight should end once both get to 1 % life
