### ISSUE TITLE
[Quest] A Special Surprise - DK chain order IV. - Plaguelands: The Scarlet Enclave

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#325]
https://www.wowhead.com/quest=12739/a-special-surprise

This quest should have https://www.wowhead.com/quest=12738/a-cry-for-vengeance as prerequisite.

Currently, it is unlocked too early after handing in How to Win Friends and Influence enemies.
Completing quests in wrong order leads to some quests being skipped and becoming unavailable once the player is phased to the next phase.

**Comment by Echinaceax** [comment]
Still issue with this @Rushor 
npc isnt giving "Cry for Vengeance"

**Comment by Frostmanx** [comment]
The NPC  Gives the quest " Cry For Vengeance" but after completing it you cannot obtain the quest
"A Special Surprise "

**Comment by Echinaceax** [comment]
> The NPC Gives the quest " Cry For Vengeance" but after completing it you cannot obtain the quest
> "A Special Surprise "

new report then :)

**Comment by Dranah** [comment]
He does. You must have missed one of the previous quests.

**Comment by Frostmanx** [comment]
@Dranah I am 100% sure I did the quest line in order. Maybe they fixed it after I got stuck and now its not obtainable unless I make a Dk from start again ?

**Comment by Dranah** [comment]
Maybe. But you dont need to remake, just make a ticket when a GM is online and he'll fix it for you.

**Comment by Frostmanx** [comment]
@Dranah  yup got it fixed from a GM :)

**Comment by Frostmanx** [comment]
@Dranah  Tested this in dev again and I have completed the full chain up to "Cry for vengeance" and "A Special Surprise" is not given to me. This is the same problem I faced in Live as well :)

![WoWScrnShot_052119_182321](https://user-images.githubusercontent.com/50195620/58097818-dad35e00-7bf5-11e9-9828-3cc33de19c0c.jpg)

**Comment by Frostmanx** [comment]
@Dranah Also The next quest depends on your race as well for example 

If you are human you are given - https://www.wowhead.com/quest=12742/a-special-surprise
If you are Tuarn   you are given - https://www.wowhead.com/quest=12739/a-special-surprise
If you are Orc      you are given - https://www.wowhead.com/quest=12748/a-special-surprise

and etc! Did you test it on a human Dk ?

**Comment by wow-mania** [comment]
fixed

**Comment by Dranah** [comment]
Oh ya, that could have been the issue!
Possibly kitzu only fixed my quest that I had, and forgot the others (my bad tbh, I should have listed ALL the quest IDs)
But this means the fix need confirming on every single race individually.

**Comment by Frostmanx** [comment]
Yeah Janitor fixed all the quest IDs just need to to confirm it on every single race as you said :)
