### ISSUE TITLE
[Profession -  Alchemy][Battle Elixirs] Elixir of Lion's Strength  

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#3255]
**Links:**

[**Elixir of Lion's Strength**](https://www.wowhead.com/spell=2329/elixir-of-lions-strength)

On the elixir it says [**Use: Increases your strenght by 6 for 2 hours**](https://user-images.githubusercontent.com/6819293/64731154-e8805c80-d4e0-11e9-90af-1ede2c2989ba.png) which is correct (in cata [**Elixir of Lion's Strength**](https://www.wowhead.com/spell=2329/elixir-of-lions-strength) got a buff, from 4str. 1h duration, to 6str. nerfed after stats squish to 2 str.)

The buff after consume gives me only 4 str for 1h, [**img**](https://user-images.githubusercontent.com/6819293/64732080-9cceb280-d4e2-11e9-9d39-3144b275dc34.png)

The buff need to give you 6str for 2h.

**Comment by Rushor** [comment]
@Xman993 could you give me a list with all spells then pls?

**Comment by Xman993** [comment]
@Rushor  Sure, you neeed just the id?

**Comment by Rushor** [comment]
the increased effect is because of: https://github.com/WoWManiaUK/Blackwing-Lair/issues/2429

It actually works, but the tooltip is not updated, like i said in the other issue.

If you have other source for that and if i missunderstood, just pm me in discord and we will reopen thanks :)

**Comment by Rushor** [comment]
See also: This elixir grants 42 health with Mixology. https://www.wowhead.com/item=2458/elixir-of-minor-fortitude#comments
