### ISSUE TITLE
[Shaman - Spell] Cleanse Spirit

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#3260]
**Links:**
[Cleanse Spirit](https://www.wowhead.com/spell=51886/cleanse-spirit#changelog)

**What is happening:**

you can spam it whether you have curse or not.

**What should happen:**

It should not be able to be used when you dont have a curse on you.

**Comment by Bezkosa** [comment]
Hello. So i just tested the sham dispel spell and its not working. I was not able to dispel anything. Tried on a lot of spells and i cant dispel them. Can you please fix this issue because i need that spell a lot. Thanks in advance. This is Bezkosa Resto Sham.

**Comment by Echinaceax** [comment]
@Keader From my research **before patch 4.1** cleanse removes 1 curse 1 harmful spell from player Xman mentions it here #4318

![before 4](https://user-images.githubusercontent.com/39439201/82653334-53ad3180-9c1f-11ea-963f-c678db5e5769.jpg)

And at patch 4.1 it changes, we are not at 4.1 yet are we?

![4](https://user-images.githubusercontent.com/39439201/82653409-74758700-9c1f-11ea-88a2-4358c8c00a3c.jpg)

So If Bezkosa says they are unable to dispel spell at all now then something is wrong, can you look again into it please

**Comment by Thelonnious** [comment]
If the player have a talent into [Improved Cleanse Spirit](https://cata-twinhead.twinstar.cz/?spell=77130) "Empowers your Cleanse Spirit spell to also remove a magic effect from a friendly target." 
 else remove only curse.

**Comment by Thelonnious** [comment]
@Bezkosa  whats school are the spells you test them?

**Comment by Phoenix9867** [comment]
Remoted <- Restro Specc:
Talents: Improved Cleanse Spirit 1/1
Cleansing Waters 1/2

Curse dispelling works fine, disease are not disepellable, magic effects i dont know right now, i dont have an npc to harm me

in ele spec cleanse spirit also dispells curses fine on my shaman
