### ISSUE TITLE
[NPC's] Vendors at the mall 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3262]
**What is happening:**
- None of the Sale currency vendors have hover over currency 
_Hard for new players to see what name currency is needed as its only a small item no discription_

**vendors**
george
joe
karl
terence
kara

**What should happen:**
should display currency name when hover over the currency needed

**Comment by Rushor** [comment]
clientside issue - i think that cannot be fixed because it's a custom curreny item :(

**Comment by Echinaceax** [comment]
im 99% sure they work on mania though (same vendors)
