### ISSUE TITLE
[NPC] Rockjaw Invader / Coldridge Defender -  Dun Morogh

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3271]
**Links:**

npc https://www.wowhead.com/npc=37070/rockjaw-invader
quest https://www.wowhead.com/quest=24469/hold-the-line

**What is happening:**
- Amount is low 
- Too many guards too little quest mobs 
_the guards are killing the ones that do spawn near_

**What should happen:**
20 Rockjaw invaders should be here

![image](https://user-images.githubusercontent.com/39439201/64846313-abb18400-d60c-11e9-9345-710925a9be30.png)

https://www.wowhead.com/quest=24469/hold-the-line#videos:id=64051

**Comment by Rushor** [comment]
thing is on retail they should not kill each other. only "fake" hitting them

**Comment by Rushor** [comment]
okay first will add some few spawns, then add the fake combat state

**Comment by Rushor** [comment]
they no longer kill each other, but you can kill them as player/pet

![I](https://i.imgur.com/Fg7bcAu.jpg)
