### ISSUE TITLE
[Item] Coldridge Mountaineer's Pouch

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3272]
**Links:**
https://www.wowhead.com/item=57542/coldridge-mountaineers-pouch
quest reward https://wow.gamepedia.com/Coldridge_Mountaineer%27s_Pouch_(quest_reward)

reward bag https://www.wowhead.com/item=57540/coldridge-mountaineers-pouch

![image](https://user-images.githubusercontent.com/39439201/64851891-9a6e7480-d618-11e9-96dc-3d5e655bc3ca.png)

no equip as you can see
no recieved message in chat screen

![image](https://user-images.githubusercontent.com/39439201/64852420-a3137a80-d619-11e9-920b-f34d9524b3e0.png)

**What is happening:**
- just disapeared

**What should happen:**
- it should have bag inside
_bags are important at low level_

**edited by echinacea**
wrong explaination meant reward bag was empty

**Comment by Kitzunu** [comment]
The reward is a bag which contains a bag in it. Recheck to see that it isnt in your inventory

**Comment by Echinaceax** [comment]
its not thats why i reported it lol @Kitzunu

**Comment by Rushor** [comment]
when i get the item, it's added directly to my bag slot

**Comment by Echinaceax** [comment]
> when i get the item, it's added directly to my bag slot

odd , mine didnt on live or on dev @Rushor

**Comment by Rushor** [comment]
okay understood. will now contain items

![I](https://i.imgur.com/jy8uvSG.jpg)
