### ISSUE TITLE
[Quest] A Cry for Vengeance! - DK chain order VI.- Plaguelands: The Scarlet Enclave

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#328]
https://www.wowhead.com/quest=12738/a-cry-for-vengeance

This quest should require both https://www.wowhead.com/quest=12727/bloody-breakout and
https://www.wowhead.com/quest=12724/the-path-of-the-righteous-crusader as prerequisites to be unlocked.

Currently, it can be unlocked with only the first completed, allowing you to accidentally skip the other mandatory quest and screw up phasing etc as per slaniaxx reports https://github.com/WoWManiaUK/Blackwing-Lair/issues/260

**Comment by Kitzunu** [comment]
Fixed
