### ISSUE TITLE
[Talent] Find Weakness - spellID 91023 - Rogue

### ISSUE THREAD

**Issue by Dubgles** [WoWManiaUK/Blackwing-Lair#3281]
**Links:**
https://www.wowhead.com/spell=91023/find-weakness
Find Weakness talent  

**What is happening:**
The debuff Find Weakness only applies when using Ambush(SpellID 8676).

**What should happen:**
The debuff Find Weakness should apply when using 
   -Ambush(SpellID 8676).
   -Garrote(SpellID 703).
   -Cheap Shot(SpellID 1833).

**Comment by Dubgles** [comment]
Sorry to disappoint you but you fixed it and broke it, now hemorrhage also applies Find Weakness which it shouldn't do...

**Comment by Keader** [comment]
i will take a look

**Comment by Keader** [comment]
It's not a regression, is a exception.
Blizzard normally control each spell with a flag.
hemorrhage has 2 flags, and 1 flag is shared with garrote .-.
So i made a new little script to prevent it proc with hemorrhage

**Comment by Rushor** [comment]
nice :>
