### ISSUE TITLE
Fire mage - Living bomb (Spell ID 44457) - should not trigger Ignite

### ISSUE THREAD

**Issue by Zul7030** [WoWManiaUK/Blackwing-Lair#3282]
**what is happening : Living bomb ( Explosion ) triggers ignite and that shouldn't happen  **

**What should happen: Living bomb (dots) is working fine, but the explosion triggers ignite and that should not happen **

Living bomb spell ID = 44457
Ignite spell ID =12846

**Comment by Keader** [comment]
WTF?!
From where you getting those bugs?

**Comment by Keader** [comment]
This is still wrong.
Patch 4.1 remove DOT procs of ignite.
Living bomb has 2 effects:

Effect 1 - DOT
Effect 2 (Explosion) - Direct fire damage.
Direct fire damage still can proc ignite.

**Comment by FixMySpells** [comment]
as I mentioned on flame orb issue that on patch 4.1 living bomb and flame ord do no trigger ignite.

this is a video from retail : https://www.youtube.com/watch?v=BL4qBoxDcEg ( jump to 15:16 and wait for the explosion)
as it appears in the video, dots deal 5908 and the explosion hit 17944(crit) ,although the explosion it's a crit, there's no ignite provided 

despite it's not written directly about this in this guide ( link below) or in the patch notes (4.1), the video proves it living bomb explosion do not cause ignite.
the reason why Blizzard removed ignite from both ( flame orb and living bomb) to limit the chances of getting ignite munching 

http://www.tauri-veins.tk/fire-mage-wow-pve-dps-rotation-cooldowns-abilities (please check 4.2.2 )

**Comment by Keader** [comment]
Oh shit.
Nice exceptions blizzard o.o
