### ISSUE TITLE
Fire mage - Flame orb ( Spell ID 82731) should not Trigger Ignite

### ISSUE THREAD

**Issue by Zul7030** [WoWManiaUK/Blackwing-Lair#3284]
**what is happening : when flame orb hits a crit as ticks or explosion it triggers Ignite which that shouldn't happen ( flame orb explodes due to a talent called : Fire Power)

**What should happen: flame orb should never trigger ignite **

"Flame orb Spell ID = 82731
Ignite spell ID =12846
Fire power Spell ID =  54734

**Comment by Keader** [comment]
Wrong...
Spell that do damage is: 82739 Flame Orb (Level 85)
and it has attribute SPELL_ATTR2_TRIGGERED_CAN_TRIGGER_PROC
that means: can proc other talents.

**Comment by FixMySpells** [comment]
it can trigger impact, not ignite

according to patch 4.1, flame orb do not trigger ignite
 Link to the patch : https://www.wowhead.com/patchnotes=4.1.0#mage
although it's not written that both spells do not trigger ignite but you can see it here : 
http://www.tauri-veins.tk/fire-mage-wow-pve-dps-rotation-cooldowns-abilities ( jump to 4.2.2 section)
