### ISSUE TITLE
[Quest] An End to All Things - missing (wrong NPC ID for Lich King) - blocks DK chain - Plaguelands: The Scarlet Enclave

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#329]
https://www.wowhead.com/quest=12779/an-end-to-all-things

Should be unlocked by https://www.wowhead.com/quest=12778/the-scarlet-apocalypse
But after handing in, it does not offer the new quest and you can't finish the chain.

EDIT: this is caused by wrong NPC ID lich king in Death's breach
The NPC ID belonging to this quest phase is https://www.wowhead.com/npc=25462/the-lich-king
but instead, ID 29110 is currently spawned in this phase too. 
ID 29110 should be present in the next phase, who offers the quest after handing in this one and getting phased again.

Spawning the correct NPC with GM command allows you to pick up and hand in the quest.
Now, if the quest is added manually and attempted to complete, you run across the following issue
- Scarlet Ballistae and Scarlet Crusaders / Tirisfal Crusaders are shooting through walls/line of sight

https://www.wowhead.com/spell=53117/ballista-assault
https://www.wowhead.com/spell=53345/arrow-assault

**Comment by Frostmanx** [comment]
I can't seem to turn in https://www.wowhead.com/quest=12778/the-scarlet-apocalypse to Lich King and he is under the texture where he is supposed to be and he is clickable but can not turn in the quest!

![WoWScrnShot_051919_195208](https://user-images.githubusercontent.com/50195620/57983450-a0d84f80-7a6f-11e9-8f1b-a72dc97bb25d.jpg)

**Comment by wow-mania** [comment]
The quest of this issue is delivered at the Archerus.

**Comment by Frostmanx** [comment]
@wow-mania Nope still can't complete it 
![WoWScrnShot_051919_223912](https://user-images.githubusercontent.com/50195620/57985539-f66c2680-7a86-11e9-8a5d-3032b45c820f.jpg)

**Comment by Dranah** [comment]
It isn't, but the issue is known.
The NPC ids are messed up. Kitzu fixed one, broke the other. This is still under work. I'll open a new thread for those.

**Comment by Dranah** [comment]
Now you can pick up the quest but cannot hand it in.
Lich King has ID 29110 this ID currently cannot end the quest.
Need to make him able to end the quest.

**Comment by Frostmanx** [comment]
@Dranah Yeah that's the same problem I had! also if you re-log it fixes LIch King NPC back to the original place and not under the texture as shown in the SS

**Comment by Frostmanx** [comment]
Fixed Confirmed! Now you can hand in the quest and obtain the next one
![WoWScrnShot_052119_202057](https://user-images.githubusercontent.com/50195620/58111959-18dd7b80-7c10-11e9-9235-69f54bf2aaa0.jpg)
