### ISSUE TITLE
Paladin: Retribution's mastery " Hand of Light "

### ISSUE THREAD

**Issue by APTX4869s** [WoWManiaUK/Blackwing-Lair#3290]
Hand of Light Spell ID 86474

Inquisition Spell ID 84963
![Inquisition](https://user-images.githubusercontent.com/55243287/64906464-2a372000-d6f8-11e9-92b9-91a7434cfab5.png)

**What is happening:**
Inquisition doesn't increase Hand of light's damage.
my mastery is 50% as u can see from the picture below
![mastery 50%](https://user-images.githubusercontent.com/55243287/64906361-bc3e2900-d6f6-11e9-918d-7a76f9d9fb87.png)
hand of light's damage without inquisition ( no buffs only elixir to make my mastery 50% so I can make it easier to calculate ) 
![hand without inquisition](https://user-images.githubusercontent.com/55243287/64906368-e394f600-d6f6-11e9-9693-c211d9981df4.png)
this time I used inquisition ( same dummy no buffs no extra things ) the damage was still 50% of Crusader strike
![Hand with inquisition](https://user-images.githubusercontent.com/55243287/64906421-6ae26980-d6f7-11e9-96f9-0af81960ed18.png)

Inquisition increases the damage of holy damage spells which it's all the spells exclude Crusader Strike and Templar's Verdict.
Hand of light takes the % damage of Crusader Strike and Templar's Verdict as " Holy Damage " ( % of the mastery you have, for example my mastery is 50% with elixir as you can see from the picture )

**What should happen:**

Inquisition should increase the damage of Hand of Light by 30% whenever it's up

**Comment by Keader** [comment]
Any proof that should affect?
Hand of Light has SPELL_ATTR6_NO_DONE_PCT_DAMAGE_MODS that means, cant be affected by % mods like Inquisition

**Comment by Dranah** [comment]
It's a fixed damage that takes no other mods. Works as intended.

**Comment by APTX4869s** [comment]
First of all what do you mean by "cant be affected by % mods like Inquisition (because spell that procs Hand of Light is already affected by it)"
Do you mean that Crusader strike, Divine Storm and templar's Verdict actually gets 30% more damage from inquisition?
I went to search in Battle.net forums to get more info about this but didn't find any and same things go to other forums, but while I was searching I found words from this site says
"However  [Inquisition] does increase the holy damage done by Mastery without affecting any physical damage done by the base attack." 
source: https://wow.gamepedia.com/Mastery:_Hand_of_Light
in same time I found someone already reported the same problem in another cata private server 
https://project-nightfall.org/bugtracker/issue/520/Paladin%3A%20Hand%20of%20Light%20%28Retribution%20Mastery%29
you can read it for more info.
my proof will be in this video after 3 hours of searching and calculating 
https://www.youtube.com/watch?v=n2LRt5ZqZws  
make the speed 0.50% or 0.25% to see the numbers
at 6:38 you can see him used Crusader strike that hit for 8149 while hand of light  3189 ( without inquisition ) after I calculated I found that his mastery is 39.13% 
at 7:19,I took this because it's after burst so the numbers won't be huge ( doesn't matter because hand of light will take % of it but I didn't want the numbers to be huge ), he hit crusader strike for 7998 while hand of light 4070 ( with inquisition ) 
let's calculate, 7998 × 39.13% (0.3913 ) < his mastery >  =3129.6
3129.6 × 0.30% ( inquisition 30% ) = 938.88
3129.6 ( his mastery without inquisition ) + 938.88 ( inquisition ) = 4068.48 in that video hand of light was 4070.
Dranah when I was in Grim batol , last boss , when you stand in that circle you get bonus damage from it I remember my hand of light max hit for 75k while neither my crusader strike nor Templar's Verdict hit 150k, my TV hit for 75k too ! ( in that time my mastery was 50% ) sadly I didn't take screenshots to proof this. ( you can test it if you have retri paladin )
Still not sure how it happened but for some reason my mastery went to 100% ( didn't test it again )
so my point from this, Hand of light isn't working as intended

**Comment by APTX4869s** [comment]
Forgot to mention how I calculated mastery :-
3189 ÷ 8149 × 100 = 39.13
