### ISSUE TITLE
[We're Here To Do One Thing, Maybe Two] Quest Bugged

### ISSUE THREAD

**Issue by Icyytouch** [WoWManiaUK/Blackwing-Lair#3292]
**Whats happening** 
This quest starts from board in ogrimmar, its pre-requisite is actually given by the board then we talk with an orc in Silverwind Refuge in ashenvale. After this he gives this bugged quest, in which we're to take a wagon to fold but nothing happens when we click on wagon. I'd like to report it.
Thanks

Regards,
Icytouch

**Comment by Echinaceax** [comment]
https://www.wowhead.com/quest=25945/were-here-to-do-one-thing-maybe-two

**Comment by Echinaceax** [comment]
reported here #1288
