### ISSUE TITLE
[Item] Gnomish Gravity Well - Engineering

### ISSUE THREAD

**Issue by Venom64bit** [WoWManiaUK/Blackwing-Lair#3297]
**Links:**
Item: https://www.wowhead.com/item=40727/gnomish-gravity-well

**What is happening:**
When use notify me that I am in the wrong zone.

**What should happen:**
Usable multiple times in rapid succession until it overheats for a vertical jump effect. 
However, it CANNOT be used...
  -In Combat
  -In non-flying zones.
   -In Battlegrounds
   -In Instances
   -In Arenas

Youtube Video: https://www.youtube.com/watch?v=ECEqWY43Xjs
The video shows an item that has the exact same effect, but updated to a more recent patch.

**Comment by Rushor** [comment]
should not only be usable in outland. currently it is only usable in outland

**Comment by Rushor** [comment]
will combine this since it's too hard for now.

**Comment by Rushor** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/3295
