### ISSUE TITLE
[Ashes to Ashes] Quest bugged - Stonetalon Mountains

### ISSUE THREAD

**Issue by Icyytouch** [WoWManiaUK/Blackwing-Lair#3300]
**Links:**

https://www.wowhead.com/quest=26010/ashes-to-ashes
https://www.wowhead.com/item=56473/kromgar-flame-thrower
**What is happening:**
Camps aren't burning

**What should happen:**
Camps should burn

**Comment by Echinaceax** [comment]
item reported here #1829

**Comment by BlaineP126** [comment]
i dont know which is the Bug, the tents burn but instantly respawn again without it being processed on the quest, it still says 0/8 but the tents to burn

**Comment by Echinaceax** [comment]
Yes its reported here #1829 but not fixed yet

**Comment by BlaineP126** [comment]
no worries, i just couldnt put my finger on what the bug actually is, the tents or flamethrower :)

**Comment by Echinaceax** [comment]
anytime @BlaineP126 :)
