### ISSUE TITLE
[Putting Their Heads Together] quest bugg desolace

### ISSUE THREAD

**Issue by Icyytouch** [WoWManiaUK/Blackwing-Lair#3303]
**Links:**
https://www.wowhead.com/quest=14227/putting-their-heads-together

**What is happening:**
I have to collect 100 skulls from a place that gives 6 at most clearing the area, 1 skull per stack of heads.

**What should happen:**
By retail questline the stack should give a random number up-to 25-30 skulls per stack. Doing this quest is impossible with these odds. plz fix it

**Comment by Echinaceax** [comment]
Already reported #546
