### ISSUE TITLE
[NPC] Goblin Operator 

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#3307]
**Links:**

[**Goblin Operator**](https://www.wowhead.com/npc=33407/goblin-operator)

**What is happening:**

[**Goblin Operator**](https://www.wowhead.com/npc=33407/goblin-operator) is invulnerable

![image](https://user-images.githubusercontent.com/6819293/64913705-2a114180-d745-11e9-9be3-4b13e4462818.png)

![image](https://user-images.githubusercontent.com/6819293/64913725-8d02d880-d745-11e9-9d6d-56be0e7a763f.png)

P.S 
after killing [**Ashenvale Wrecker**](https://www.wowhead.com/npc=33283/), [**Goblin Operator**](https://www.wowhead.com/npc=33407/goblin-operator) are dropped and they attack you.

**Comment by Echinaceax** [comment]
related too #1746
