### ISSUE TITLE
[Quest] In a Bind - Ashenvale

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#3308]
**Links:**

[**In a Bind**](https://www.wowhead.com/quest=13982/in-a-bind)

**What is happening:**

Nothing

**What should happen:**

[**Kaliva**](https://www.wowhead.com/npc=34602/kaliva) should spawn run towards you, and attack you.

[**Video**](https://youtu.be/MGVGXZU-0_U)

NPC missing:

- [**Alenndaar Lapidaar**](https://www.wowhead.com/npc=8308/alenndaar-lapidaar)
- [**Harlown Darkweave**](https://www.wowhead.com/npc=6731/harlown-darkweave)

**Comment by Rushor** [comment]
fixed with next update

![I](https://i.imgur.com/5LzR5CM.jpg)

**Comment by Xman993** [comment]
@Rushor  can you add the 2 npc's too?

**Comment by Rushor** [comment]
yes they are visible then aswell
