### ISSUE TITLE
[quest] Astranaar's Burning! -  ID 13849 - (issue 2) Ashenvale

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#3310]
**Links:**

[**Astranaar's Burning!**](https://www.wowhead.com/quest=13849/astranaars-burning)

**What is happening:**

The quest works you ca finish it. But here are some things that shouldn't be.
- you can't put out some fire
-  fire only appears when you are on the quest
-  [**Watch Wind Rider**](https://www.wowhead.com/npc=34160) only appears when you are on the quest (need for #2117 )

**What should happen:**

- all fire must be extinguished
- fire and [**Watch Wind Rider**](https://www.wowhead.com/npc=34160)  need to be always there

**Comment by Rushor** [comment]
source that fire should always be there https://www.wowhead.com/quest=13849/astranaars-burning#videos:id=47714

**Comment by Rushor** [comment]
always visible now

![I](https://i.imgur.com/XpMtGiH.jpg)
