### ISSUE TITLE
[NPC] Mrs. Gant  <Cooking Trainer & Supplies> - Booty Bay

### ISSUE THREAD

**Issue by Venom64bit** [WoWManiaUK/Blackwing-Lair#3315]
**Links:**

NPC: https://cata-twinhead.twinstar.cz/?npc=54232

**What is happening:**
She is only a Vendor.

**What should happen:**
She should be a Vendor and a Trainer.

**Comment by Rushor** [comment]
https://i.imgur.com/6q7sYZq.jpg

fixed with next update
