### ISSUE TITLE
[NPC] <Druid Trainer> (issue3) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3316]
**Links:**
issue 1
https://www.wowhead.com/npc=44395/celestine-of-the-harvest
- [x] Meant to be human 

Stormwind has a worgen 

**What is happening:**
- Is a Worgen and not human as stated both on wowhead and twinhead(cata)

**What should happen:**
Should be a human

- [ ] issue 2

need to add to druid trainers

Apprentice riding : https://www.wowhead.com/spell=33388/apprentice-riding
Journeyman riding: https://www.wowhead.com/spell=33391/journeyman-riding
Expert riding: https://www.wowhead.com/spell=34090/expert-riding

**Comment by Kitzunu** [comment]
https://www.wowhead.com/npc=44395/celestine-of-the-harvest#comments:id=1183676

**Comment by Echinaceax** [comment]
then just the 2nd issue needs fixing @Kitzunu

**Comment by Kitzunu** [comment]
Why should a class trainer teach riding skills? Do you have proof of it being like that in Retail 4.3.4?

**Comment by Echinaceax** [comment]
yes your proof you gave lol https://github.com/WoWManiaUK/Blackwing-Lair/issues/2083 @Kitzunu

**Comment by Echinaceax** [comment]
the issue here there has been to many reports about this messed up unlearning issue that all are confusing coders @Rushor has tried, and i think @Keader has. 

just need this #2906 fixing and this is the reason (my druid learnt from trainer before someone messed it up) and she still has her orginally trainer flights and flight form without any issue. 

never druids however are having these issues now since they are not learnt from druid trainer anymore. the not saving was a seperate issue which was fixed in a previous issue

**Comment by Kitzunu** [comment]
Druid trainer should not teach riding skills.

A druid need to learn Journeyman and Apprentice from a riding trainer. The only riding skill they do not need to learn is Expert Riding since that skill comes with learning Flying form.

**Comment by Echinaceax** [comment]
still confused i see :)

**Comment by Echinaceax** [comment]
will up date soon
