### ISSUE TITLE
[NPC] Bobber Spazzspark <Fishing Supplies> - Stranglethorn

### ISSUE THREAD

**Issue by Venom64bit** [WoWManiaUK/Blackwing-Lair#3317]
**Links:**

NPC: https://cata-twinhead.twinstar.cz/?npc=44192

**What is happening:**
He isn't interactable.

**What should happen:**
He is a Fishing Vendor.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/5EmruWE.jpg)

fixed with next update
