### ISSUE TITLE
[The Bait for Lar'korwi] Quest BUgged - Un'Goro Crater

### ISSUE THREAD

**Issue by Icyytouch** [WoWManiaUK/Blackwing-Lair#3319]
**Links:**

https://classic.wowhead.com/quest=4292/the-bait-for-larkorwi

**What is happening:**
Wouldn't let me place the meat on the rock.. 

**What should happen:**
should let me place the meat on rock so the dinosaur appears nad fight

**Comment by Rushor** [comment]
duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/516
