### ISSUE TITLE
[General] Wow-Reign Mallstone

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3320]
**Links:**
![mallstone](https://user-images.githubusercontent.com/39439201/64926012-d6f8c680-d7f8-11e9-91a0-51d7554ea692.jpg)

**What is happening:**
- resets CD on relog 
was mentioned here #2112  29th May 

**What should happen:**
should have a 1 hour cd and not be affected by relog

**Comment by hediunchained** [comment]
i am sorry but how is this high priority, like its not even game breaking and there are things far worse still not fixed

**Comment by Sevenblade11** [comment]
At least fix heroic lockouts  & vp resets before placing these little things on high prio...

**Comment by Echinaceax** [comment]
note: Game breaking when used to gank - kill - and instant port out lol

**Comment by Echinaceax** [comment]
Not fixed

**Comment by mfranca0009** [comment]
All set 👍 , had to:

- Edit item script to return the proper value (marking it as the item was used by player)
- Change spell cooldown in item template to 60 minutes (3600000 miliseconds)
- Add the flagCustom value of 1 (shows live cooldown tracker on item after use)
- Add spell attribute to make cooldown continue while player is logged out

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 

![NICE](https://user-images.githubusercontent.com/39439201/105475463-b0c22100-5c9f-11eb-801d-e2d38c77e98e.jpg)
![item not ready yet](https://user-images.githubusercontent.com/39439201/105475081-44dfb880-5c9f-11eb-8756-e74231f10131.jpg)
![mallstone timer](https://user-images.githubusercontent.com/39439201/105475100-49a46c80-5c9f-11eb-98f5-646e3a0919c7.jpg)
