### ISSUE TITLE
"Return to Alysra" - Mount Hyjal

### ISSUE THREAD

**Issue by Yummy559** [WoWManiaUK/Blackwing-Lair#3321]
**Links:**
https://www.wowhead.com/quest=25424/return-to-alysra

**What is happening:**
The Dragon, Alysra, is bugged. I am supposed to return to her to turn in a quest, however, she is red and an enemy, meaning that I cannot turn in the quest. This quest is also part of the Mount Hyjal quest chain, so this quest is rendering me from completing any other quests.

**What should happen:**

The dragon Alysra should be green, a friend, so that I can turn in my quest.

**Comment by Rushor** [comment]
This happens if you do the quest: http://cata.cavernoftime.com/quest=29437

**Comment by Rushor** [comment]
now. you can see only the gossip while you are on that quest.

credit upon kill is also given and the creature will restore it's faction upon reset/evade.

![I](https://i.imgur.com/Rh4F9u7.jpg)
![I](https://i.imgur.com/aE5vsxf.jpg)
