### ISSUE TITLE
Fire Mage Combustion SpellID 11129 - damage (Dot) is not correct

### ISSUE THREAD

**Issue by Zul7030** [WoWManiaUK/Blackwing-Lair#3325]
According to this report : https://github.com/WoWManiaUK/Blackwing-Lair/issues/84
and this : https://www.mmo-champion.com/threads/804052-Fire-4-3-Compendium ( Jump to how to combustion, you can see the correct calculations)

**What is happening: Combustion's (dot) is not dealing the right damage

According to the calculations, Combustion should take the divided amount ( By 3) of Living bomb(dot) and Pyroblast(dot)…... and 1/2 of ignite

A simple brief how combustion works
Mastery is included in these calculations ( it's 35%)
A tick of living bomb deals 3612 , this number will be divided by 3 ( 3612/3 =1204)
A tick of pyroblast (dot) deals 2269, this number will be divided by 3 ( 2269/3 =756)
A tick of Ignite deals 3086, this number will be divided by 2 ( 3086/2 =1543)
The sum of these numbers will be your combustion ( 3612+2269+1543 = 7424)

Examples: ( or let's call it .....proofs)
***************************************************************************************************
First...... living Bomb (dot) ( note: I casted combustion only with 1 dot which is Living bomb (dot))

https://www3.0zz0.com/2019/09/16/19/295645088.jpg   
as it shown above, the dots deal 3612 .. so the amount for combustion should be 3612/3 = 1204

however,combustion damage that taken from Living bomb (dot) (which it's 676)
https://www3.0zz0.com/2019/09/16/19/485235931.jpg   
****************************************************************************************************
Second Pyroblast (dot) ( note: I casted combustion only with 1 dot which is Pyroblast (dot)

https://www3.0zz0.com/2019/09/16/19/561144130.jpg
as it shown above, the dots deal 2269, so combustion should be 2269/3 =756

however, combustion damage that taken from pyroblast (dot) ( which it's 643)
https://www3.0zz0.com/2019/09/16/19/330784646.jpg
**************************************************************************************************** 
Third, Ignite ( note: I casted combustion only with 1 dot which it's ignite)

https://www3.0zz0.com/2019/09/16/19/362964243.jpg
as it shown above, ignite deals 3086, so combustion should be  3086/2 = 1543

however, it deals more damage, (2172)
https://www3.0zz0.com/2019/09/16/19/909685167.jpg
******************************************************************************************************
I did another test, this time all dots together
Pyroblast (dot) https://www3.0zz0.com/2019/09/16/19/843309049.jpg

ingite  https://www3.0zz0.com/2019/09/16/19/447084886.jpg

Living Bomb (dot) https://www3.0zz0.com/2019/09/16/19/307174441.jpg

Combustion (dot) https://www3.0zz0.com/2019/09/16/19/956337422.jpg

according to the calculations , Combustion damage should be:
(2269/3)+(8062/2)+(3612/3) =5991

well, but it deals 4838

Sorry for making it too long, but I had to explain it like this

**Comment by Zul7030** [comment]
I have re-uploaded the screenshots, hope it works now

**Comment by Zul7030** [comment]
It seems that I made it… complicated 😆 
let me simplify it 😀 

**what should happen:** 
(Ignite (dot) tick damage )÷ 2

(Living bomb (dot) tick damage) ÷3

(Pyroblast (dot) tick damage) ÷3

the sum of these dots should give you the correct dots of Combustion


![Combustion dot](https://user-images.githubusercontent.com/53161918/65391291-978e2500-dd78-11e9-9490-570ef078d2f1.png)


https://www.mmo-champion.com/threads/804052-Fire-4-3-Compendium
https://github.com/WoWManiaUK/Blackwing-Lair/issues/84

**Comment by Zul7030** [comment]
Kindly re-open this report, I have test this spell again after the update, and still not working correctly 
instead, it's doing more damage than should be

**Comment by Keader** [comment]
Holy . .
Take a look today

**Comment by Zul7030** [comment]
It seems the portion taken from Ignite is wrong

What is happening: it devides the whole ignite damage by 2

What should happen : Ignite's tick should be devided by 2

Kindly check pyroblast and living bomb part as well, their portion doing slightly less damage

**Comment by Slydee23** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/55513205/66221229-de601100-e6ce-11e9-9465-e430bf3c97f8.jpg)
Thats a Single Target Combust from Today. Its Bugged 100% 80k Dps

**Comment by Zul7030** [comment]
yea it's still not fixed

**what is happening** : the ignite part of combustion is totally missed up,

**what should happen**: the value of ignite's tick should be devided by 2

**Comment by APTX4869s** [comment]
a quick info that none mentioned it here, it may help with something.
if you use combustion on dummy then you put your mouse on the de buff ( on dummy ) it show that it should hit for like 3500 per tick but when you see it in recount it's 6000 per tick. according to 
my previous experience in fire mages I feel like the 3500 should be the right number ( that shows on the dummy )
( the numbers above this just an example )
this is my try in actual numbers in wow reign
combustion on dummy says it should hit for 6095 per tick

![Combustion dummy](https://user-images.githubusercontent.com/55243287/66270689-68db7880-e867-11e9-8c18-7a823cbcb410.png)

but in recount it shows 9144 
![Combustion recount](https://user-images.githubusercontent.com/55243287/66270697-7ee93900-e867-11e9-8049-bd019cd77320.png)

I hope this helps with something ^^

**Comment by Keader** [comment]
Guys i need confirm 1 thing...
In Living bomb, Pyroblast... i need get the total amount of dot and /3 or, the tick amount / 3?

**Comment by Keader** [comment]
ok, fixed i belive.
is on ptr (should be in live tomorrow)

**Comment by Zul7030** [comment]
well, still not fixed 😄 
I test it on a boss that gives extra damage ( 3rd boss in Blackrock Caverns), I reached 81k ignite per tick,
by ignoring pyroblast and living bomb portions, I should get 40.5k per tick, but I had 16-18k

is it possible to test this issue with you in dev realm? so we don't have to wait for the next updates to test it.

![Ignite damage](https://user-images.githubusercontent.com/53161918/67026426-c5b51980-f118-11e9-9cd5-30b06b496352.jpg)

![Combustion damage](https://user-images.githubusercontent.com/53161918/67026429-c948a080-f118-11e9-9a9e-bcae7f0fa7fb.jpg)

**Comment by Zul7030** [comment]
Any updates on this issue ? Fire mages are unplayable atm

**Comment by Echinaceax** [comment]
Still needs looking into @Keader

**Comment by Keader** [comment]
Core was calculating wrong value of Dots.
Was getting me base value, not current damage one.
Now is fixed.
