### ISSUE TITLE
Stacking Stamina buffs ( Blood pact + Scroll of Fortitude )

### ISSUE THREAD

**Issue by APTX4869s** [WoWManiaUK/Blackwing-Lair#3326]
![Imp stamina buff](https://user-images.githubusercontent.com/55243287/64977070-bea1ae00-d8c3-11e9-81d4-fc45e4798592.png)

![scroll id](https://user-images.githubusercontent.com/55243287/64977076-c2353500-d8c3-11e9-82d7-0229c50321cc.png)

my HP without Scroll of Fortitude is 123k ( with Blood pact which it is pet's buff )
![without scroll](https://user-images.githubusercontent.com/55243287/64977126-dd07a980-d8c3-11e9-9ad2-91673b4c9db2.png)

my HP with Scroll of Fortitude 130k ( with blood pact )
![Stacked imp + scroll](https://user-images.githubusercontent.com/55243287/64977277-2526cc00-d8c4-11e9-8859-5ef20d83850b.png)

**What is happening:**
Blood pact and Scroll of Fortitude stack.

**What should happen:**
Blood pact and Scroll of Fortitude should not stack and it should only take the highest buff which it will be Blood pact.
it's same problem as but different buffs.
https://github.com/WoWManiaUK/Blackwing-Lair/issues/3171

**Comment by Rushor** [comment]
okay stacking rule added
