### ISSUE TITLE
Stacking Battle effects ( Elixirs + Scrolls )

### ISSUE THREAD

**Issue by ghost** [WoWManiaUK/Blackwing-Lair#3327]
![scroll](https://user-images.githubusercontent.com/55243287/64978116-d712c800-d8c5-11e9-8d13-90303d18dbb9.png)
![Elixir](https://user-images.githubusercontent.com/55243287/64978123-da0db880-d8c5-11e9-9dab-ee5f07bea317.png)

as you can see I stacked both of them on me 
![stacked elixir and scroll](https://user-images.githubusercontent.com/55243287/64978149-e98d0180-d8c5-11e9-991e-eaee954903da.png)

**What is happening:**
Elixirs being stacked with Scrolls even though the scroll says counts as battle elixir
it happens to all elixirs and scrolls not only haste and strength.

**What should happen:**

the second effect that being used should replace the first one
for example if you used elixir of mastery and then used scroll of strength, the scroll should remove the elixir of mastery and takes its place.

**Comment by Rushor** [comment]
are you sure about this?

**Comment by Zul7030** [comment]
I dont think this is a class issue .. this is stacking battle elixir (scroll from inscription and elixir from alchemy)

**Comment by APTX4869s** [comment]
"This means if you currently have the effect of one battle elixir, and you consume another battle elixir, the new effect will replace the old one. You can only have one battle and one guardian elixir active at one time."
source : https://wowwiki.fandom.com/wiki/Elixir
both Elixir and the Scroll counts as Battle elixir,

**Comment by Rushor** [comment]
okay thanks

**Comment by APTX4869s** [comment]
Any news? I can stack all the scrolls + 1 elixir
![stacking scrolls](https://user-images.githubusercontent.com/55243287/66309346-769e0600-e91a-11e9-82bc-f208aea129e6.png)

Agility Scroll Spell ID 89343                     Item ID 63303              
Armor Scroll Spell ID 89344                     Item ID 63308
Stamina Scroll Spell ID 89345                  Item ID 63306
Strength Scroll Spell ID 89346                 Item ID 63304
Intellect Scroll Spell ID 89347                  Item ID 63305

**Comment by Keader** [comment]
@APTX4869s Battle Elixir and Guardian Elixir can stack?

**Comment by Keader** [comment]
Based in wiki, they can stack (1 guardian elixir + 1 battle elixir)
So, all battle elixir is fixed.
Need fix guardians now.

**Comment by Rushor** [comment]
Guardian elixirs do not stack with other guardian elixirs and battle elixirs do not stack with other battle elixirs.
https://wowwiki.fandom.com/wiki/Elixir
