### ISSUE TITLE
[Raid] The Bastion of twilight  - Trash NPC

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#3328]
### FIRST OF ALL, U CAN PICKPOCKET FROM ALL! 
(drops only gold but still it's not allowed)

### TRASH NPC TEST - WITH LOVE <3

- [x] **TRASH NPC FIRST LAYER LINKS**: 

	- [**Twilight Shadow Knight**](https://www.wowhead.com/npc=45261) - ID 45261
	- [**Twilight Soul Blade**](https://www.wowhead.com/npc=45265/) - ID 45265
	- [**Twilight Dark Mender**](https://www.wowhead.com/npc=45266/) - ID 45266
	- [**Twilight Phase-Twister**](https://www.wowhead.com/npc=45267) - ID 45267
	- [**Twilight Crossfire**](https://www.wowhead.com/npc=45264) - ID 45264

- [ ] **TRASH NPC FIRST LAYER SPEEL'S**: 
	
	- [**Twilight Shadow Knight**](https://www.wowhead.com/npc=45261) 
		- N10, H10, N25, H25 (Raid Difficulty)
			- [Devastate](https://www.wowhead.com/spell=78660) - ID 78660 (don't cast the spell)
			- [Dismantle](https://www.wowhead.com/spell=84832) - ID 84832 (don't cast the spell)
			- [Shield Mastery](https://www.wowhead.com/spell=84827) - ID 78660 (is casted but don't work)
			- [Sunder Armor](https://www.wowhead.com/spell=76622) - ID 78660 (don't cast the spell)

	
	- [**Twilight Soul Blade**](https://www.wowhead.com/npc=45265/)
		- N10, H10 (Raid Difficulty)
			- [Blade Barrier](https://www.wowhead.com/spell=84567) - ID 84567 (don't cast the spell)
			- [Dark Pool](https://www.wowhead.com/spell=84853) - ID 84853 (don't cast the spell)
			- [Soul Blade](https://www.wowhead.com/spell=84849/) - ID 84849 (works)
			- [Soul Blade](https://www.wowhead.com/spell=84850) - ID 84850 (works, not sure if should has to do both at the same time or just refresh the duration "image")
		- N25, H25 (Raid Difficulty)
			- [Blade Barrier](https://www.wowhead.com/spell=84567) - ID 84567 (don't cast the spell)
			- [Dark Pool](https://www.wowhead.com/spell=84853) - ID 84853 (don't cast the spell)
			- [Soul Blade](https://www.wowhead.com/spell=84849/) - ID 84849 (works)
			- [Soul Blade](https://www.wowhead.com/spell=84850) - ID 84850 (works, not sure if should has to do both at the same time or just refresh the duration [image](https://user-images.githubusercontent.com/6819293/64985131-7b940a80-d8c4-11e9-988c-509514b5712c.png))
			- [Shadow Bolt](https://www.wowhead.com/spell=95440) - ID 95440 (don't cast the spell)

	- [**Twilight Dark Mender**](https://www.wowhead.com/npc=45266/)
		- N10, H10, N25, H25 (Raid Difficulty)
			- [Dark Mending](https://www.wowhead.com/spell=84855) - ID 84855 (don't cast the spell, should use it on the lowest hp npc )
			- [Hungering Shadows](https://www.wowhead.com/spell=84856) -  ID 84856 (don't cast the spell)
		

	- [**Twilight Phase-Twister**](https://www.wowhead.com/npc=45267)
		- N10, H10 (Raid Difficulty)
			- [Twist Phase](https://www.wowhead.com/spell=84838) - ID 84838 (don't cast the spell)
		- N25, H25 (Raid Difficulty)
			- [Twist Phase](https://www.wowhead.com/spell=84838) - ID 84838 (don't cast the spell)
			- [Shadow Bolt](https://www.wowhead.com/spell=95440) - ID 95440 (don't cast the spell)

	- [**Twilight Crossfire**](https://www.wowhead.com/npc=45264) - (Need to attack with ranged weapon not Melee,if it is far, not to run toward you )
		- N10, H10 (Raid Difficulty)
			- [Multi-Shot](https://www.wowhead.com/spell=84836) - ID 84836 (don't cast the spell)
			- [Rapid Fire](https://www.wowhead.com/spell=36828) - ID 36828 (don't cast the spell)
			- [Shoot](https://www.wowhead.com/spell=84837) - ID 84837 (don't cast the spell)
			- [Wyvern Sting](https://www.wowhead.com/spell=90488) - ID 90488 (don't cast the spell)
		- N25, H25 (Raid Difficulty)
			- [Multi-Shot](https://www.wowhead.com/spell=84836) - ID 84836 (don't cast the spell)
			- [Rapid Fire](https://www.wowhead.com/spell=36828) - ID 36828 (don't cast the spell)
			- [Shoot](https://www.wowhead.com/spell=84837) - ID 84837 (don't cast the spell)
			- [Wyvern Sting](https://www.wowhead.com/spell=90488) - ID 90488 (don't cast the spell)
			- [Wyvern Sting](https://www.wowhead.com/spell=24336) - ID 24336 (don't cast the spell)

- [x] **TRASH NPC SECOND LAYER LINKS**: 

	- [**Chosen Warrior**](https://www.wowhead.com/npc=46951) - ID 46951 
	- [**Twilight Elementalist**](https://www.wowhead.com/npc=47152) - ID 47152
	- [**Elemental Firelord**](https://www.wowhead.com/npc=47081) - ID  47081
	- [**Wind Breaker**](https://www.wowhead.com/npc=47151) - ID 47151
	- [**Earth Ravager**](https://www.wowhead.com/npc=47150) - ID 47150
	- [**Twilight Brute**](https://www.wowhead.com/npc=47161) - ID 47161
	- [**Azureborne Destroyer**](https://www.wowhead.com/npc=47087) - ID 47161
	- [**Crimsonborne Firestarter**](https://www.wowhead.com/npc=47086) - ID 47086
	- [**Evolved Drakonaar**](https://www.wowhead.com/npc=49813) - ID 49813
	- [**Bound Deluge**](https://www.wowhead.com/npc=49825) - ID 49825
	- [**Bound Zephyr**](https://www.wowhead.com/npc=49821) - ID 49821
	- [**Bound Rumbler**](https://www.wowhead.com/npc=49826) - ID 49826
	- [**Bound Inferno**](https://www.wowhead.com/npc=49817) - ID 49817
	- [**Faceless Guardian**](https://www.wowhead.com/npc=45676/) - ID 45676 
	- [**wilight Shadow Mender**](https://www.wowhead.com/npc=45699) - ID 45699 
	- [**Twilight Portal Shaper**](https://www.wowhead.com/npc=45700/) - ID 45700
	- [**Twilight-Shifter**](https://www.wowhead.com/npc=45687) - ID 45687

- [ ] **TRASH NPC SECOND LAYER SPEEL'S:**

	- [**Chosen Warrior**](https://www.wowhead.com/npc=46951) 
		- N10, H10, N25, H25 (Raid Difficulty)
			- [Hamstring](https://www.wowhead.com/spell=87704) - ID 87704 (don't cast the spell)

	- [**Twilight Elementalist**](https://www.wowhead.com/npc=47152) 
		- N10, H10, N25, H25 (Raid Difficulty)
			- [Empower Elemental](https://www.wowhead.com/spell=88065) - ID 88065 (don't cast the spell)
			- [Frostfire Bolt](https://www.wowhead.com/spell=88079) - ID 88079 (don't cast the spell)
			
			
	- [**Elemental Firelord**](https://www.wowhead.com/npc=47081)	
		- N10, H10, N25, H25 (Raid Difficulty)
			- [Molten Burst](https://www.wowhead.com/spell=87898) - ID 87898 (don't cast the spell)
			- [Volcanic Wrath](https://www.wowhead.com/spell=87903) - ID 87903 (don't cast the spell)

	- [**Wind Breaker**](https://www.wowhead.com/npc=47151)
		- N10, H10, N25, H25 (Raid Difficulty)
			- [Gale Wind](https://www.wowhead.com/spell=87870/) - ID 87870 (don't cast the spell)
			- [Violent Gale Storm](https://www.wowhead.com/spell=87875) - ID 87875 (don't cast the spell)

	- [**Earth Ravager**](https://www.wowhead.com/npc=47150) 
		- N10, H10, N25, H25 (Raid Difficulty)
			- [Petrify Skin](https://www.wowhead.com/spell=87917) - ID 87917 (don't cast the spell)
			- [Tremors](https://www.wowhead.com/spell=87920/) - ID 87920 (don't cast the spell)
			
			
	- [**Twilight Brute**](https://www.wowhead.com/npc=47161)
		- N10, H10, N25, H25 (Raid Difficulty)
			- [Whirling Blades](ww.wowhead.com/spell=88133) - ID 88133 (don't cast the spell)
			
			
	- [**Azureborne Destroyer**](https://www.wowhead.com/npc=47087)		
		- N10, H10, N25, H25 (Raid Difficulty)
			- [Arcane Infused Fists](https://www.wowhead.com/spell=88204) - ID 88204 (don't cast the spell)
			- [Stasis Strike](https://www.wowhead.com/spell=88178) - ID 88178 (don't cast the spell)
			

	- [**Crimsonborne Firestarter**](https://www.wowhead.com/npc=47086)
		- N10, H10, N25, H25 (Raid Difficulty)
			- [Burning Twilight](https://www.wowhead.com/spell=88219) - ID 88219 (don't cast the spell)
			- [Crimson Flames](https://www.wowhead.com/spell=88226) - ID 88226 (don't cast the spell)
		
		
	- [**Evolved Drakonaar**](https://www.wowhead.com/npc=49813)
		- N10, H10, N25 (Raid Difficulty)
			- [Blade Tempest](https://www.wowhead.com/spell=93373/) - ID 93373 (don't cast the spell)
			- [Cleave](https://www.wowhead.com/spell=40504/) - ID 40504 (don't cast the spell)
		- H25 (Raid Difficulty)
			- [Blade Tempest](https://www.wowhead.com/spell=93373/) - ID 93373 (don't cast the spell)
			- [Cleave](https://www.wowhead.com/spell=40504/) - ID 40504 (don't cast the spell)
			- [Twilight Rupture](https://www.wowhead.com/spell=93377)  - ID  93377 (don't cast the spell)
			
			
	- [**Bound Deluge**](https://www.wowhead.com/npc=49825)
		- N10, H10, N25, H25 (Raid Difficulty)
			- [Cold-Touched](https://www.wowhead.com/spell=93381) - ID 93381 (don't cast the spell)
			- [Frost Whirl](https://www.wowhead.com/spell=93331) - ID 93331 (don't cast the spell)
			- [Frost Whirl](https://www.wowhead.com/spell=93340) - ID 93340 (don't cast the spell)
			- [Icy Shroud](https://www.wowhead.com/spell=93335) - ID 93335 (works!)

	- [**Bound Zephyr**](https://www.wowhead.com/npc=49821)
		- N10, H10, N25, H25 (Raid Difficulty)
			- [Lightning Shock](https://www.wowhead.com/spell=93278) - ID 93278 (don't cast the spell)
			- [Rending Gale](https://www.wowhead.com/spell=93277) - ID 93277 (don't cast the spell)
			- [Vaporize](https://www.wowhead.com/spell=93306) - ID 93306 (don't cast the spell)

	- [**Bound Rumbler**](https://www.wowhead.com/npc=49826)
		- N10, H10, N25, H25 (Raid Difficulty)
			- [Entomb](https://www.wowhead.com/spell=93327) - ID 93327 (don't cast the spell)
			- [Shockwave](https://www.wowhead.com/spell=93325) - ID 93325 (don't cast the spell)
			

	- [**Bound Inferno**](https://www.wowhead.com/npc=49817)
		- N10, H10, N25, H25 (Raid Difficulty)
			- [Flamestrike](https://www.wowhead.com/spell=93362) - ID 93362 (don't cast the spell)
			- [Ward of Combustion](https://www.wowhead.com/spell=93336) - ID 93336 (don't cast the spell)

	-[**Faceless Guardian**](https://www.wowhead.com/npc=45676/) 
		- N10, H10, N25, H25 (Raid Difficulty)
			-Its like a Traning Dummy (they do not move or attack )

	- [**Twilight Shadow Mender**](https://www.wowhead.com/npc=45699)
		- N10, N25, H25 (Raid Difficulty) 
			- [Mind Sear](https://www.wowhead.com/spell=85643) - ID 85643 (don't cast the spell)
			- [Shadow Mending](https://www.wowhead.com/spell=85575) - ID 85575 (don't cast the spell)
			- [Umbral Flames](https://www.wowhead.com/spell=85664) - ID  85664(don't cast the spell)
		- H10
			- [Mind Sear](https://www.wowhead.com/spell=85643) - ID 85643 (don't cast the spell)
			- [Shadow Mending](https://www.wowhead.com/spell=85575) - ID 85575 (don't cast the spell)

	- [**Twilight Portal Shaper**](https://www.wowhead.com/npc=45700/)
		- N10, H10, N25, H25 (Raid Difficulty)
			- [Shadow Bolt](https://www.wowhead.com/spell=85544) - ID 85544 (don't cast the spell)
			- [Shape Portal](https://www.wowhead.com/spell=85529/) - ID 85529 (don't cast the spell)

	- [**Twilight-Shifter**](https://www.wowhead.com/npc=45687)
		- N10, H10 (Raid Difficulty)
			- [Shifted Reality](https://www.wowhead.com/spell=85564) - ID 85564 (don't cast the spell)
			- [Twilight Shift](https://www.wowhead.com/spell=85556) - ID 85556 (don't cast the spell)
		- N25, H25 (Raid Difficulty)
			- [Twilight Shift](https://www.wowhead.com/spell=85556) - ID 85556 (don't cast the spell)

**Comment by Rushor** [comment]
okay all ai added for a lot of those creatures. please report the loot stuff in a second issues - thanks :>

**Comment by Xman993** [comment]
i couldn't find the loot from Chosen Warrior. if anyone can find it, add it. 😃

**Comment by Echinaceax** [comment]
> i couldn't find the loot from Chosen Warrior. if anyone can find it, add it. 😃

no loots from them apparently

**Comment by Xman993** [comment]
@Rushor  Make sure they dont spam Shadow Bolt - ID 95440 because it does a ton of dmg

**Comment by Xman993** [comment]
----------------------------------------------------------------------------------------------
- [**Twilight Dark Mender**](https://www.wowhead.com/npc=45266/) - ID 45266
- [**Twilight Phase-Twister**](https://www.wowhead.com/npc=45267) - ID 45267
- [**Tremors**](https://www.wowhead.com/npc=47180) - ID 47180
- [**Wind Breaker**](https://www.wowhead.com/npc=47151) - ID 47151
- [**Faceless Guardian**](https://www.wowhead.com/npc=45676/) - ID 45676 
-----------------------------------------------------------------------------------------------
 
- [ ] [**Twilight Dark Mender**](https://www.wowhead.com/npc=45266/) 
          - cast, but dont attack.

- [ ]  [**Twilight Phase-Twister**](https://www.wowhead.com/npc=45267)
          - don't cast, dont attack.
          - still have focus on me after im in stealth, but not in combat.

![image](https://user-images.githubusercontent.com/6819293/65066751-48658000-d985-11e9-96c9-11fab14b78b6.png)

- [ ] [**Tremors**](https://www.wowhead.com/npc=47180) 
          - spawn randomly (it's a infernal)
![image](https://user-images.githubusercontent.com/6819293/65068795-9d0afa00-d989-11e9-8aca-251344170822.png)

- [ ] [**Wind Breaker**](https://www.wowhead.com/npc=47151) 
          - spam [Gale Wind](https://www.wowhead.com/spell=87870) throwing me all over the map


- [ ] [**Faceless Guardian**](https://www.wowhead.com/npc=45676/)
          - cast [Pooled Blood](https://www.wowhead.com/spell=85412/) and then they disappear
          - when you kill them, they appear



![image](https://user-images.githubusercontent.com/6819293/65069763-a9905200-d98b-11e9-820f-df9762ff1cb9.png)

**Comment by Xman993** [comment]
drop report is here #3331 as you ask for.

**Comment by Xman993** [comment]
Re-test of Trash here #3332 3332

**Comment by Rushor** [comment]
okay thanks so this is marked as fixed. rest will be ahndled here https://github.com/WoWManiaUK/Blackwing-Lair/issues/3332
