### ISSUE TITLE
[NPC] Avalanchion <Elemental Lord> (double spawn) - deepholm

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3329]
**Links:**

https://www.wowhead.com/quest=27935/bring-down-the-avalanche

**What is happening:**
- double spawn

**What should happen:**
- should be only id 27935

reported by GM from player

**Comment by Rushor** [comment]
doublespawn removed!

**Comment by Echinaceax** [comment]
**Update**

GM noticed that the NPC spawned atm isnt correct for this quest 
https://www.wowhead.com/quest=27935/bring-down-the-avalanche from 2 ingame players tickets having the same issue 

the npc spawn is 44372 and it should be `27935`

@mfranca0009 
npc needs changing  to id 27935 
seems rushor could have removed the wrong npc :)

**Comment by Echinaceax** [comment]
I will retest this when PTR is up
Seems players are having issues finding this npc spawned according from 2 ingame players 

will reopen if i find an issue

I see him spawned inside the cave up top on the ledge

![image](https://user-images.githubusercontent.com/39439201/134043818-07dd7c53-86e4-4180-a6a3-dcb285051ec8.png)

my guess is if the players cant see him on the ledge its a phasing issue 
(there are some issues with phasing in Deepholm still)
