### ISSUE TITLE
[Quest] Light of Dawn - ID 12801 - Blocks DK Chain

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#333]
https://www.wowhead.com/quest=12801

This quest has multiple issues but overall is non-completable because you get no credit at the end.

In more detail (worth a read):

- I began the event at 10:46 as per the screenshot https://imgur.com/mITrhKR
- The event properly started and progressed with dialogue and fight until at 10:53 Highlord Tirion Fordring appeared, ended the fight and yelled "Bring them before the chapel!" https://imgur.com/fRWv5cw
- Now, at this point the progress got stuck and NOTHING happened until 11:03, the whole event went for a 10minute coffee break.
- Note, Tirion despawned long ago, and at 11:03, the dialogue continued with him missing and only Mograine talking. https://imgur.com/s7iniR0
- At 11:06, past the touching talk between Alexandros and his son, the Lich King appeared and began casting his spell to murder Tirion (who wasn't even present but it's irrelevant).
- At this point an army of the light should spawn (now friendly to you) and try defend Tirion, whom the Lich King kills yelling "APOCALYPSE". Instead, a couple of elite mobs from the previous fight respawned and began fighting with Mograine and Koltira. I love how Thassarian watched the whole thing kneeling and not giving a damn https://imgur.com/zeaYrQL
- So everyone is sparkling in light as the Ashbringer is cleansed even though Tirion and his blade is nowhere, and the LK is talking to himself, when suddenly, you (the player) get oneshot killed out of nowhere.
- A valkyr comes and rezzes you, the event completes, Mograine and Tirion unites and you get no credit.
Oh and you're killed again (oneshot) https://imgur.com/EYjV9gN
- Mograine then resets to his starting state where he is, offering you to restart the event, but won't actually do it if you talk to him.

**Comment by Dranah** [comment]
Works now with the condition that you stay close to Mograine at all times.

**Comment by Dranah** [comment]
There are some conditions that cause the quest to bug and make player lose credit in the end
1) There is an issue with Darion Mograine getting knocked outside the chapel area by the defenders , leading to several glitches and possible loss of credit after.
2) There is an issue with Darion Mograine fighting the corpses of the defenders beyond tirion's speech and players need to take caution to not get oneshot by spells that the npcs use (there isn't meant to be ongoing fight anymore)
Dead players cannot get credit,and running back often takes longer than the event to finish, screwing up players.

These are no priority atm but I expect alot of future tickets that GMs need to deal with, so it should be fixed sometime.

**Comment by Kitzunu** [comment]
This must be bugged in WotLK the same way then because if I remember correctly Janitor copied the script from there

**Comment by Rushor** [comment]
> Works now with the condition that you stay close to Mograine at all times.

Going to fix that now. The creature should no longer despawn at beeing too far away from player.

**Comment by Kitzunu** [comment]
@Rushor That is an issue on WotLK as well which has been ignored, so if you could fix there too would be cool xd :P
