### ISSUE TITLE
[Quest] It's Never Over - ID 26616 - Redridge

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Blackwing-Lair#3330]
**Links:**
Quest - https://www.wowhead.com/quest=26616/its-never-over
Npc - https://www.wowhead.com/npc=43458/john-j-keeshan

(May be related to https://github.com/WoWManiaUK/Blackwing-Lair/issues/230 )

**What is happening:**
The boat does appear and you can ride it, but the NPC (John j Keeshan) at the other side in Everstill Camp is not present (or not phased correctly).
The quest is not marked as complete in the log when you exit the boat, and no place to turn this in.

This locks out the 5 remaining quests in the chain, and 8 more in the follow-up chain in the Redridge area.

https://youtu.be/ZHBdIxcUv90

EDIT on retry with GM Zinius:  NPC not phased.  Can see ? mark on map once manually set as completed by GM, but no NPC to interact with. 

**What should happen:**
The quest is marked as complete in the log once the ride is complete, and can be turned into the NPC.

**Comment by Rushor** [comment]
Will fix

**Comment by Rushor** [comment]
those are missing

(43458, 43508, 43462, 43459, 43461);

completition added 

![I](https://i.imgur.com/86bSefU.jpg)

questender are new quests added 

![I](https://i.imgur.com/p9ZennD.jpg)
