### ISSUE TITLE
[Raid] The Bastion of twilight - Trash  NPC Drop

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#3331]
### THE DROP IS BROKEN
   - Every third npc drop a epic item
   - Humanoids dont drop gold

- [ ] **TRASH NPC FIRST LAYER DROPS**: 

	- [**Twilight Shadow Knight**](https://www.wowhead.com/npc=45261) - [10N](https://www.wowhead.com/npc=45261/twilight-shadow-knight#drops:mode=n10) - [10H](https://www.wowhead.com/npc=45261/twilight-shadow-knight#drops:mode=h10) - [25N](https://www.wowhead.com/npc=45261/twilight-shadow-knight#drops:mode=n25) - [25H](https://www.wowhead.com/npc=45261/twilight-shadow-knight#drops:mode=h25) 
	- [**Twilight Soul Blade**](https://www.wowhead.com/npc=45265/) - [10N](https://www.wowhead.com/npc=45265/twilight-soul-blade#drops:mode=n10) - [10H](https://www.wowhead.com/npc=45265/twilight-soul-blade#drops:mode=h10) - [25N](https://www.wowhead.com/npc=45265/twilight-soul-blade#drops:mode=n25) - [25H](https://www.wowhead.com/npc=45265/twilight-soul-blade#drops:mode=h25) 
	- [**Twilight Dark Mender**](https://www.wowhead.com/npc=45266/) - [10N](https://www.wowhead.com/npc=45266/twilight-dark-mender#drops:mode=n10) - [10H](https://www.wowhead.com/npc=45266/twilight-dark-mender#drops:mode=h10) - [25N](https://www.wowhead.com/npc=45266/twilight-dark-mender#drops:mode=n25) - [25H](https://www.wowhead.com/npc=45266/twilight-dark-mender#drops:mode=h25) 
	- [**Twilight Phase-Twister**](https://www.wowhead.com/npc=45267) - [10N](https://www.wowhead.com/npc=45267/twilight-phase-twister#drops:mode=n10) - [10H](https://www.wowhead.com/npc=45267/twilight-phase-twister#drops:mode=h10) - [25N](https://www.wowhead.com/npc=45267/twilight-phase-twister#drops:mode=n25) - [25H](https://www.wowhead.com/npc=45267/twilight-phase-twister#drops:mode=h25) 	
	- [**Twilight Crossfire**](https://www.wowhead.com/npc=45264) - [10N](https://www.wowhead.com/npc=45264/twilight-crossfire#drops:mode=n10) - [10H](https://www.wowhead.com/npc=45264/twilight-crossfire#drops:mode=h10) - [25N](https://www.wowhead.com/npc=45264/twilight-crossfire#drops:mode=n25) - [25H](https://www.wowhead.com/npc=45264/twilight-crossfire#drops:mode=h25)

- [ ] **TRASH NPC SECOND LAYER DROPS**:

	- [**Chosen Warrior**](https://www.wowhead.com/npc=46951) - NA/NA (i couldn't find them) :(
	- [**Twilight Elementalist**](https://www.wowhead.com/npc=47152) - [10N](https://www.wowhead.com/npc=47152#drops:mode=n10) - [10H](https://www.wowhead.com/npc=47152#drops:mode=h10) - [25N](https://www.wowhead.com/npc=47152#drops:mode=n25) - [25H](https://www.wowhead.com/npc=47152#drops:mode=h25) 
	- [**Elemental Firelord**](https://www.wowhead.com/npc=47081) - [10N](https://www.wowhead.com/npc=47081#drops:mode=n10) - [10H](https://www.wowhead.com/npc=47081#drops:mode=h10) - [25N](https://www.wowhead.com/npc=47081#drops:mode=n25) - [25H](https://www.wowhead.com/npc=47081#drops:mode=h25) 
	- [**Wind Breaker**](https://www.wowhead.com/npc=47151) - [10N](https://www.wowhead.com/npc=47151#drops:mode=n10) - [10H](https://www.wowhead.com/npc=47151#drops:mode=h10) - [25N](https://www.wowhead.com/npc=47151#drops:mode=n25) - [25H](https://www.wowhead.com/npc=47151#drops:mode=h25) 
	- [**Earth Ravager**](https://www.wowhead.com/npc=47150) - [10N](https://www.wowhead.com/npc=47150#drops:mode=n10) - [10H](https://www.wowhead.com/npc=47150#drops:mode=h10) - [25N](https://www.wowhead.com/npc=47150#drops:mode=n25) - [25H](https://www.wowhead.com/npc=47150#drops:mode=h25) 
	- [**Twilight Brute**](https://www.wowhead.com/npc=47161) - [10N](https://www.wowhead.com/npc=47161#drops:mode=n10) - [10H](https://www.wowhead.com/npc=47161#drops:mode=h10) - [25N](https://www.wowhead.com/npc=47161#drops:mode=n25) - [25H](https://www.wowhead.com/npc=47161#drops:mode=h25) 
	- [**Azureborne Destroyer**](https://www.wowhead.com/npc=47087) - [10N](https://www.wowhead.com/npc=47087#drops:mode=n10) - [10H](https://www.wowhead.com/npc=47087#drops:mode=h10) - [25N](https://www.wowhead.com/npc=47087#drops:mode=n25) - [25H](https://www.wowhead.com/npc=47087#drops:mode=h25) 
	- [**Crimsonborne Firestarter**](https://www.wowhead.com/npc=47086) - [10N](https://www.wowhead.com/npc=47086#drops:mode=n10) - [10H](https://www.wowhead.com/npc=47086#drops:mode=h10) - [25N](https://www.wowhead.com/npc=47086#drops:mode=n25) - [25H](https://www.wowhead.com/npc=47086#drops:mode=h25) 
	- [**Evolved Drakonaar**](https://www.wowhead.com/npc=49813) - [10N](https://www.wowhead.com/npc=49813#drops:mode=n10) - [10H](https://www.wowhead.com/npc=49813#drops:mode=h10) - [25N](https://www.wowhead.com/npc=49813#drops:mode=n25) - [25H](https://www.wowhead.com/npc=49813#drops:mode=h25) 
	- [**Bound Deluge**](https://www.wowhead.com/npc=49825) - [10N](https://www.wowhead.com/npc=49825#drops:mode=n10) - [10H](https://www.wowhead.com/npc=49825#drops:mode=h10) - [25N](https://www.wowhead.com/npc=49825#drops:mode=n25) - [25H](https://www.wowhead.com/npc=49825#drops:mode=h25) 
	- [**Bound Zephyr**](https://www.wowhead.com/npc=49821) - [10N](https://www.wowhead.com/npc=4982#drops:mode=n10) - [10H](https://www.wowhead.com/npc=4982#drops:mode=h10) - [25N](https://www.wowhead.com/npc=4982#drops:mode=n25) - [25H](https://www.wowhead.com/npc=4982#drops:mode=h25) 
	- [**Bound Rumbler**](https://www.wowhead.com/npc=49826) - [10N](https://www.wowhead.com/npc=49826#drops:mode=n10) - [10H](https://www.wowhead.com/npc=49826#drops:mode=h10) - [25N](https://www.wowhead.com/npc=49826#drops:mode=n25) - [25H](https://www.wowhead.com/npc=49826#drops:mode=h25) 
	- [**Bound Inferno**](https://www.wowhead.com/npc=49817) - [10N](https://www.wowhead.com/npc=49817#drops:mode=n10) - [10H](https://www.wowhead.com/npc=49817#drops:mode=h10) - [25N](https://www.wowhead.com/npc=49817#drops:mode=n25) - [25H](https://www.wowhead.com/npc=49817#drops:mode=h25) 
	- [**Faceless Guardian**](https://www.wowhead.com/npc=45676/) -  [10N](https://www.wowhead.com/npc=45676/#drops:mode=n10) - [10H](https://www.wowhead.com/npc=45676/#drops:mode=h10) - [25N](https://www.wowhead.com/npc=45676/#drops:mode=n25) - [25H](https://www.wowhead.com/npc=45676/#drops:mode=h25) 
	- [**wilight Shadow Mender**](https://www.wowhead.com/npc=45699) -[10N](https://www.wowhead.com/npc=45699/#drops:mode=n10) - [10H](https://www.wowhead.com/npc=45699/#drops:mode=h10) - [25N](https://www.wowhead.com/npc=45699/#drops:mode=n25) - [25H](https://www.wowhead.com/npc=45699/#drops:mode=h25)  
	- [**Twilight Portal Shaper**](https://www.wowhead.com/npc=45700/) - [10N](https://www.wowhead.com/npc=45700/#drops:mode=n10) - [10H](https://www.wowhead.com/npc=45700/#drops:mode=h10) - [25N](https://www.wowhead.com/npc=45700/#drops:mode=n25) - [25H](https://www.wowhead.com/npc=45700/#drops:mode=h25) 
	- [**Twilight-Shifter**](https://www.wowhead.com/npc=45687) - [10N](https://www.wowhead.com/npc=45687#drops:mode=n10) - [10H](https://www.wowhead.com/npc=45687#drops:mode=h10) - [25N](https://www.wowhead.com/npc=45687#drops:mode=n25) - [25H](https://www.wowhead.com/npc=45687#drops:mode=h25)

**Comment by Rushor** [comment]
okay all creatures now drop some items and give gold. boss gold and loot will be fixed later before release

**Comment by Rushor** [comment]
![I](https://i.imgur.com/eHEwuQt.jpg)
