### ISSUE TITLE
[Raid] The Bastion of twilight - Trash NPC issue 2

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#3332]
### FIRST OF ALL 

- **TRASH DONT SCALE**
     - damage don't scale with raid raid difficulty
     - auto attack damage is low. (400 on 25n, naked char on all diffuculty )

- **MISSING SCRIPT'S**

     - first missing script is at the start of the second floor on the stairs [Video](https://youtu.be/FPpkBEnSrbY?t=339)
        - [**Chosen Warrior**](https://www.wowhead.com/npc=46951) - ID 46951
        - [**Chosen Seer**](https://www.wowhead.com/npc=46952) - ID 46952
[**Chosen Warrior**](https://www.wowhead.com/npc=46951) and [**Chosen Seer**](https://www.wowhead.com/npc=46952) should run toward you on the stairs after killing the first 3 npc's
    - Second script missing is at the middle of the room after finishing the first script (killing the npc's)
        - The others need to run on the middle of the room and cho'gall need to run back
        - [**Azureborne Destroyer**](https://www.wowhead.com/npc=47087) - ID 47161
        - [**Crimsonborne Firestarter**](https://www.wowhead.com/npc=47086) - ID 47086
        - [**Twilight Brute**](https://www.wowhead.com/npc=47161) - ID 47161
        - [**Elemental Firelord**](https://www.wowhead.com/npc=47081) - ID  47081
        - [**Wind Breaker**](https://www.wowhead.com/npc=47151) - ID 47151
        - [**Earth Ravager**](https://www.wowhead.com/npc=47150) - ID 47150
        - [**Twilight Elementalist**](https://www.wowhead.com/npc=47152) - ID 47152
        - [**Cho'Gall**](https://www.wowhead.com/npc=46965) - ID 46965

----------------------------------------------------------------------------------------------
- [**Twilight Dark Mender**](https://www.wowhead.com/npc=45266/) - ID 45266
- [**Twilight Phase-Twister**](https://www.wowhead.com/npc=45267) - ID 45267
- [**Tremors**](https://www.wowhead.com/npc=47180) - ID 47180
- [**Wind Breaker**](https://www.wowhead.com/npc=47151) - ID 47151
- [**Faceless Guardian**](https://www.wowhead.com/npc=45676/) - ID 45676 
-----------------------------------------------------------------------------------------------
 
- [ ] [**Twilight Dark Mender**](https://www.wowhead.com/npc=45266/) 
     - cast, but dont attack.

- [ ]  [**Twilight Phase-Twister**](https://www.wowhead.com/npc=45267)
     - don't cast, dont attack.
     - still have focus on me after im in stealth, but not in combat.

![image](https://user-images.githubusercontent.com/6819293/65066751-48658000-d985-11e9-96c9-11fab14b78b6.png)

- [ ] [**Tremors**](https://www.wowhead.com/npc=47180) 
     - spawn randomly (it's a infernal)
![image](https://user-images.githubusercontent.com/6819293/65068795-9d0afa00-d989-11e9-8aca-251344170822.png)

- [ ] [**Wind Breaker**](https://www.wowhead.com/npc=47151) 
     - spam [Gale Wind](https://www.wowhead.com/spell=87870) throwing me all over the map

- [ ] [**Faceless Guardian**](https://www.wowhead.com/npc=45676/)
     - cast [Pooled Blood](https://www.wowhead.com/spell=85412/) and then they disappear
     - when you kill them, they appear

![image](https://user-images.githubusercontent.com/6819293/65069763-a9905200-d98b-11e9-820f-df9762ff1cb9.png)

**Comment by Rushor** [comment]
Thank you

**Comment by Rushor** [comment]
also missing difficulty entries and immune masks

**Comment by Rushor** [comment]
@Xman993 how should the Faceless Guardian behave exactly. can you explain me so i can code it?

**Comment by Rushor** [comment]
okay fixed everything else so far. events will be done later.
