### ISSUE TITLE
[Quest/NPC] Favored Skull (issue2)

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Blackwing-Lair#3333]
**Links:**
Alliance: https://www.wowhead.com/quest=26323/favored-skull
Horde:  https://www.wowhead.com/quest=26745/favored-skull
NPC:  https://www.wowhead.com/npc=42736/lashtail-hatchling#starts

**What is happening:**
On Alliance side, the NPC above is offering to start both of the above faction's quests, it should only offer the Alliance-aligned version 26323.
Unable to test behaviour on Horde side as this is first toon.

**What should happen:**
NPC should offer only the Alliance-aligned version of the quest when playing an Alliance character.

**Comment by Rushor** [comment]
faction conditions added
