### ISSUE TITLE
[Quest/Daily] Magnets, How Do They Work? - ID 27992 - Tol Barad Peninsula

### ISSUE THREAD

**Issue by fuzzydunlop** [WoWManiaUK/Blackwing-Lair#3334]
**Links:**
https://www.wowhead.com/quest=27992/magnets-how-do-they-work

**What is happening:** Not much. The quest item doesn't seem to work.

**What should happen:** You should be able to get the iron scraps by using the given item near siege engines and catapults

**Comment by Echinaceax** [comment]
reported here #1790
