### ISSUE TITLE
[Paladin] Talent -  [Sanctity of Battle] - ID : 25956

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3336]
**Links:**
https://wowwiki.fandom.com/wiki/Sanctity_of_Battle
https://wow.gamepedia.com/Sanctity_of_Battle

from WoWHead or our Armory

**What is happening:**

Haste debuff increases the duration of the abilities Crusader Strike and divine storm but haste does not scale down the cooldowns
tested with bloodlust and equipping/unequipping haste gear
 
**What should happen:**

Crusader Strike and Divine Storm should get lower CD with more haste

**Comment by Echinaceax** [comment]
@Slydee23 any reason you closed this ?

**Comment by Slydee23** [comment]
I thought i was wrong but i did some more test : 

it works with bloodlust and other temporary haste buffs but my base haste doesnt decrease the cooldown at all  i did reforging all to haste no change. maybe need further testing.

**Comment by Slydee23** [comment]
any news ?

**Comment by Keader** [comment]
I tested myself now.
Is working fine.
Base cooldown is 4500 ms (4.5 sec)
With 799 of hast (all provided by items), cooldown become: 4112
with item+potion of speed: 3966
With BL + items: 3163
So... it's scaling with hast.

**Comment by APTX4869s** [comment]
" Haste debuff increases the duration of the abilities Crusader Strike and divine storm" 
![Crusader Strike 7 secs](https://user-images.githubusercontent.com/55243287/65542360-12de0b00-df20-11e9-9ce6-4a00c2b269fc.png)

Go to The Vortex Pinnacle
Second Boss " Altairus "
when you get the red buff use Crusader Strike
Crusader strike goes to 9 secs and that shouldn't happen.
I guess it goes for to all debuffs that effect haste not only this one.

**Comment by Keader** [comment]
Now, client is calculating it, so i'm sure that is correct values.
In other hand, yes, debuffs that reduce your haste, affect this talent too.
Was missing send correct aura to client, he handle with everything xD

**Comment by APTX4869s** [comment]
@Keader, "In other hand, yes, debuffs that reduce your haste, affect this talent too."

in this video from retail
https://www.youtube.com/watch?v=c33xZyegihI&list=PLA6734C822B3E79D1&index=19&t=0s
at 11:20 you can see his Crusader strike went to 4.5 secs not 9 ( you can either watch from his addon or his ActionBars )
prefer you start watching from 11: 15 so you can see that he was spamming Crusader strike then he got the haste debuff Crusader strike went to 4.5.
So Crusader Strike shouldn't go more than 4.5 even with haste debuffs

**Comment by Keader** [comment]
It's handled by clientside @APTX4869s.
So even if i want, i cant fix, since i cant change game files.
And is working exactly like blizzard did
