### ISSUE TITLE
Warrior Arms: Wrecking Crew

### ISSUE THREAD

**Issue by APTX4869s** [WoWManiaUK/Blackwing-Lair#3338]
![Wrecking Crew](https://user-images.githubusercontent.com/55243287/65259907-8940ce80-db16-11e9-9693-187ad3188685.png)

**What is happening:**
Every crit from Mortal Strike, Colossus Smash, Overpower, Heroic Strike, Cleave, Thunder clap, Heroic Throw and Execute has 100% chance to enrage you

**What should happen:**
Only Mortal Strike crits should enrage you

**Comment by Rushor** [comment]
ID - 46867 Wrecking Crew (Rank 1)
