### ISSUE TITLE
[Unholy DK] -  [Raise Dead]  (issue 2) - ID : 46584

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3340]
**Links:**
https://www.wowhead.com/spell=46584/raise-dead

from WoWHead or our Armory

**What is happening:**

Ghoul (pet) randomly disappears after summon (cant get new one for 2 minutes then) , dies in every aoe stops moving or cant handle ground heigth difference.

I noticed that the ghoul always change the name after summon a new one this should not happen. after you spec to unholy you always should summon the same ghoul with 

**What should happen:**

Pet should not disappear at any time. 
Pet should get high Damage Reduction for every AOE Damage. Avoidance? aroun 80-99% idk

**Comment by Keader** [comment]
I belive that you are missing this talent:

![image](https://user-images.githubusercontent.com/7120913/65389488-3ab94d00-dd2d-11e9-89ca-01e8a030a22c.png)


Btw, i found something wrong.
Pet health is very low.
Fixed it.

**Comment by Slydee23** [comment]
you mean me with the missing talent ?
