### ISSUE TITLE
[Quest] I Ain't Sayin' You a Gourd-Digger...

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Blackwing-Lair#3342]
**Links:**
https://www.wowhead.com/quest=26956/i-aint-sayin-you-a-gourd-digger
specificically the "corn" part of the quest, that summons
https://www.wowhead.com/npc=44489/corn-stalker

**What is happening:**
Whilst the apple and pumpkin parts of this quest work fine, the "corn" object appears to be missing, so there is nothing for the player to click.  Hence the mob linked above is not spawned.

**What should happen:**
The corn item should be present and interactive, summoning the Corn Stalker mob.

**Comment by jarvik76** [comment]
Apoologies, this looks like it is not a bug - it's just the corn is very very hard to see when it is on the ground.

**Comment by Echinaceax** [comment]
tested and is fine :)

**Comment by Rushor** [comment]
thanks
