### ISSUE TITLE
[NPC] Makrinni Razorclaw -  Azshara

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3346]
**Links:**
https://classic.wowhead.com/npc=6350/makrinni-razorclaw

**What is happening:**
- loot table wrong :)

**What should happen:**
should only give 
https://classic.wowhead.com/item=7973/big-mouth-clam
https://classic.wowhead.com/item=8959/raw-spinefin-halibut

**Comment by Rushor** [comment]
should drop some more https://www.wowhead.com/npc=6350/makrinni-razorclaw#drops:mode= but no epic items
