### ISSUE TITLE
[Profession] Tailoring Passiv -  [Northern Cloth Scavenging] - ID : 59390

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3350]
**Links:**
https://www.wowhead.com/spell=59390/cloth-scavenging

from WoWHead or our Armory

**What is happening:**

before i learned the passive : 1-3 drops per mob around 100 frostweave cloth per 15 min 
after i learned the passive it was the the same.

without :
round 1 : 91 
round 2 : 104
round 3 : 98

with :  
round 1 : 101
round 2 : 89
round 3 : 94

at all 6 farm rounds it was 1-3 cloth per mob (drop rate at all seems a bit low)

**What should happen:**
 

the passive should definitely increase the amount to minimum 2-6 frostweave cloth

**Comment by Echinaceax** [comment]
@Slydee23 i didnt seem to have a huge issue with frostweave tbh i farmed here and was getting 2s 3s and 7s 

![cloth extras](https://user-images.githubusercontent.com/39439201/66715055-22ce6980-edbf-11e9-9a88-a22521ae8f49.jpg)

but having issues with Cata cloth #3603 drops tho

**Comment by Slydee23** [comment]
the thing is i farmed the first hours without this passive (cause i forgot it exist) and it was the exact same amount the mobs dropped

**Comment by Echinaceax** [comment]
@Slydee23 same here, i only got **Cloth Scavenging** later too 
i will double check again and add SS from ingame

**Comment by Rushor** [comment]
okay added the loot again with condition to have aura http://cata.cavernoftime.com/spell=59390 active in order to see that loot. if it needs adjustment let me know. :)
