### ISSUE TITLE
[Currency Item] justice points 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3351]
**What is happening:**
- Reset day is random Thursays / Fridays and rarely Wednesdays
_players cant rely on set day as they are so random (would be nice to have a set day)_

**What should happen:**
Should be Wednesday same as Blizz

**Comment by Rushor** [comment]
can you pls check?

localTm.tm_wday = getIntConfig(CONFIG_CURRENCY_RESET_DAY);
localTm.tm_hour = getIntConfig(CONFIG_CURRENCY_RESET_HOUR);

it's a config thingi :>

**Comment by Slydee23** [comment]
Reset was today at 9 am and no random resets over the last day so it looks good now

**Comment by Echinaceax** [comment]
i can close this then @Slydee23 
reopen if needed thanks :)
