### ISSUE TITLE
[Quest] Buy Us Some Time / Traveling on Our Stomachs cancel each other (Ally) - Vashj'ir 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3356]
**Links:**
https://www.wowhead.com/quest=25357/buy-us-some-time
https://www.wowhead.com/quest=25546/traveling-on-our-stomachs

**What is happening:**
- Canceling each other 

**What should happen:**

**Comment by Kitzunu** [comment]
```sql
UPDATE `quest_template_addon` SET `ExlusiveGroup` = 0 WHERE `ID` IN (25357,25546);
```

**Comment by Rushor** [comment]
thx kitz
