### ISSUE TITLE
[Quest Item] Elven Gem 4492

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#336]
Quest - https://www.wowhead.com/quest=26051/sunken-treasure
NPC - https://www.wowhead.com/npc=2774
You are to equip the item https://www.wowhead.com/item=4491/goggles-of-gem-hunting and swim into the sea to collect https://www.wowhead.com/item=4491/goggles-of-gem-hunting.
These are meant to be displayed like mining nods or herbs on your map.
The issue is there is only one Gem located that I can fine. No other Gems around to collect. The quest requires you to collect 10 of these with a spawn time of 2/3 minutes ( self calculated). the quest is completable but take a while.

**Comment by sarahkay88** [comment]
![world of warcraft 02_01_2019 18_03_45_li](https://user-images.githubusercontent.com/42302580/50605392-17f2ba00-0eba-11e9-8440-1ce4b182a821.jpg)
![world of warcraft 02_01_2019 18_05_06_li](https://user-images.githubusercontent.com/42302580/50605433-2e007a80-0eba-11e9-988c-a6b11a1cc8eb.jpg)
![world of warcraft 02_01_2019 18_03_57_li](https://user-images.githubusercontent.com/42302580/50605465-407ab400-0eba-11e9-8a59-e87118eca1f7.jpg)

**Comment by Echinaceax** [comment]
I am on this quest on Horde side and the gems are spaced out, but they are around.
being undead i have the breathing buff so i was able to swim around more 

![gem1](https://user-images.githubusercontent.com/39439201/50617372-2908ee80-0eed-11e9-85c0-c18f46aede41.jpg)
![gem2](https://user-images.githubusercontent.com/39439201/50617374-2b6b4880-0eed-11e9-932d-cd8f89c3cc09.jpg)
![gem3](https://user-images.githubusercontent.com/39439201/50617375-2c9c7580-0eed-11e9-98fc-11956a39b335.jpg)

**Comment by sarahkay88** [comment]
Ho dam I spent 20/30 getting the same one. I swam around the area I circled red but couldn't see any. Maybe I'm just blind I swamp around the crash area.

**Comment by sarahkay88** [comment]
Hio u went a lot further out than me. Maybe that was my mistake. But wow head shows they should be located in the area I was at haha. My fault for trusting it lol. If that's the case this can be closed then.

**Comment by Echinaceax** [comment]
yeah thats what i think too

**Comment by sarahkay88** [comment]
I'm on my phone at the moment not sure how to close them on this but will close it when I get on pc.. 20/30 min of my life I'll never get bk lol

**Comment by Echinaceax** [comment]
ha ha ....yeah

![swim buff helped a lot](https://user-images.githubusercontent.com/39439201/50617838-7ab27880-0eef-11e9-98c9-27ad6e7a9bd2.jpg)
 
though i think my breathing swim buff helped a lot, or i wouldnt have swam so far out either tbh :)

**Comment by sarahkay88** [comment]
Haha joys of being a lock. Still got a few quest in that area before I move on. If u finish the area first let me know saves my time n I can go to highlands

**Comment by Echinaceax** [comment]
sure ofc i will
