### ISSUE TITLE
[NPC] Gimme Shelter!  Kelp'thar Forest

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3360]
**Links:**

https://www.wowhead.com/quest=25587/gimme-shelter
https://www.wowhead.com/npc=39667/adarrah

**What is happening:**
- Quest missing 

**What should happen:**
she should give this above quest and new quest 
https://www.wowhead.com/quest=25598/aint-too-proud-to-beg

**Comment by Rushor** [comment]
works fine https://i.imgur.com/IbDarYT.jpg

but you first need to complete https://www.wowhead.com/quest=27685/good-deed-left-undone

also phasing issue fixed.

**Comment by Echinaceax** [comment]
great - npc for pick up of the needed quest was missing :)
thanks @Rushor
