### ISSUE TITLE
[NPC] Toshe Chaosrender <The Earthen Ring> (position) - Vashj'ir

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3362]
**Links:**

https://www.wowhead.com/npc=45462/toshe-chaosrender

![question mark hidden](https://user-images.githubusercontent.com/39439201/65296225-12cabd80-db64-11e9-9bd1-2d42cfc5102e.jpg)

**What is happening:**
- needs move away from wood cant see his (!)

**Comment by Rushor** [comment]
moved

![I](https://i.imgur.com/pfZiRGW.jpg)
