### ISSUE TITLE
[NPC] Budd (missing) - Kelp'thar Forest

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3363]
**Links:**

https://www.wowhead.com/npc=46338/budd

**What is happening:**
- Missing 

**What should happen:**
starts 4 quests
https://www.wowhead.com/quest=25657/dah-nunt-dah-nunt
https://www.wowhead.com/quest=25670/dun-dun-dun-dun-dun-dun
https://www.wowhead.com/quest=25651/oh-the-insanity
https://www.wowhead.com/quest=27699/shark-weak

**Comment by Rushor** [comment]
added

![I](https://i.imgur.com/hpl9FIQ.png)
