### ISSUE TITLE
[Event] - Coren Direbrew (missing) -  Brewfest

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3365]
**Links:**
https://www.wowhead.com/quest=25483/world-event-dungeon-coren-direbrew

http://prntscr.com/p8q4k9

from WoWHead or our Armory

**What is happening:**

Cant enter the queue via DB while event is active

**What should happen:**

there should be a option to join the Coren Direbrew Event Dungeon, im not 100% sure if it was 4.0.6.

**Comment by Rushor** [comment]
is the event in gernal even active?

**Comment by Echinaceax** [comment]
> is the event in gernal even active?

doesnt look like it no @Rushor

**Comment by Slydee23** [comment]
no i just could access the menu trough /run LFDQueueFrame_SetType(287)

**Comment by Rushor** [comment]
will give it to you man :>

![I](https://i.imgur.com/5w4Rdnn.jpg)

Anyway the creature is there if you go in normally. The DB handling has to be fixed in opcodes somehow.

**Comment by Slydee23** [comment]
any News ? and this is for sure the Wotlk version of the boss

**Comment by Slydee23** [comment]
event is soon over

**Comment by Rushor** [comment]
@Slydee23 yeah we don't get the db thing fixed, is the arch anyway possible if you join that instance manually?

**Comment by Rushor** [comment]
general dungeon opcode missing - it's not related to that single boss. will be fixed in future with other eventscripts

**Comment by Echinaceax** [comment]
@Rushor your ss is of the lvl 80 Coren Direbrew

Hes not here for the Brewfest event, reopening this now, so we can get the npc added hopefully before Event starts in October :)

**Comment by Echinaceax** [comment]
> /run LFDQueueFrame_SetType(287)

correct me if im wrong but shouldnt the command be RDF and not RFD @Slydee23 ?

**Comment by Echinaceax** [comment]
in PTR i started the event and it was listed for me there 

![brewfest event](https://user-images.githubusercontent.com/39439201/88349524-a951a780-cd50-11ea-8232-210e0b295766.jpg)
