### ISSUE TITLE
[Quest] Breaking Through ID:11898 - Borean Tundra

### ISSUE THREAD

**Issue by Venom64bit** [WoWManiaUK/Blackwing-Lair#3366]
**Links:**

QLink: https://www.wowhead.com/quest=11898/breaking-through

**What is happening:**
If you use the teleport for the upper side (Above the entrance teleport) you are instant redirect to the entrance teleport.

**What should happen:**
You can get the teleport for the second floor and kill Prince Valanar.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/ZdFYMwI.jpg)

fixed with next update
