### ISSUE TITLE
[Quest] Neutralizing the Cauldrons - Borean Tundra

### ISSUE THREAD

**Issue by Venom64bit** [WoWManiaUK/Blackwing-Lair#3367]
**Links:**

QLink: https://www.wowhead.com/quest=11647/neutralizing-the-cauldrons

**What is happening:**
You can't use the quest item on the Cauldrons. (Requires En'kilah Cauldron)

**What should happen:**
You have to use the quest item on the Cauldron for neutralizing it.

**Comment by Rushor** [comment]
fixed with next update

![I](https://i.imgur.com/LxpHqYQ.jpg)
