### ISSUE TITLE
[PvP ] Wintergrasp - Doesnt start 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3368]
**What is happening:**
- Battle doesnt start 
- You get teleported out 
- No message for "not enough players" 
- get a blank join screen, when you click it, it doesnt join you to group  #1975

_Only message we get is "let the battle begin!" then teleported out_

Note: _Reported by players on live, and tested by me and Rusher on DEV_

**Comment by Rushor** [comment]
issues combined. https://github.com/WoWManiaUK/Blackwing-Lair/issues/3341. It's the same reason.
