### ISSUE TITLE
Fire mage - Ignite ( SpellID 12846)  does not stack

### ISSUE THREAD

**Issue by Zul7030** [WoWManiaUK/Blackwing-Lair#3369]
**What is happening: 

ignite does not stack, it's getting replaced instead

https://us.battle.net/forums/en/wow/topic/4038617617

this is a video from retail proves that ignite does stack
https://www.youtube.com/watch?v=s_QLH57bnQc …. check from 8:50 till 9:00, the addon Combustion Healper shows  that ignite was 22577 … you can't get that much ignite if it does not stack

**What should happen:** Ignite (dot) should stack

**Comment by dxbali** [comment]
I can confirm that .. it does not stack

**Comment by APTX4869s** [comment]
I've noticed that there is something wrong in ignite, makes sense now.

**Comment by Keader** [comment]
Has a Max value for stack?

**Comment by Zul7030** [comment]
here's a video from retail , fighting Alysrazor
https://www.youtube.com/watch?v=OOo-9p_-AXc 
At 2:17 you can see the highest stack the player  could reach was ( 378.8K)

To be honest, the max value is unknown, but still (378.8K) is fine, because it's impossible to get it without Alysrazor's buff

![Ignite max](https://user-images.githubusercontent.com/53161918/65387312-33a73480-dd57-11e9-81ab-21e0ccb079e6.png)

**Comment by Keader** [comment]
Fixed, ty man :)
