### ISSUE TITLE
[Quest] Finding the Phylactery

### ISSUE THREAD

**Issue by Juggermott** [WoWManiaUK/Blackwing-Lair#3370]
**Links:**
https://www.wowhead.com/quest=11956/finding-the-phylactery
from WoWHead or our Armory

**What is happening:**
Cannot interact with Death Knights' mount, "Dusk" to be lead to the phylactery's location.

**What should happen:**
Upon traveling back to Death's Stand camp, you should be able to interact with an Acherus Death Charger that is standing there in order to be transported to the location of the phylactery.

**Comment by Rushor** [comment]
you can now interract with dusk if you have the quest active

![I](https://i.imgur.com/io5VtYe.jpg)
![I](https://i.imgur.com/lbqnjTM.jpg)
![I](https://i.imgur.com/9zbaiCy.jpg)
