### ISSUE TITLE
The only homes we have - 27804 - Twilight Highlands

### ISSUE THREAD

**Issue by mattm72980** [WoWManiaUK/Blackwing-Lair#3371]
**Links:**
https://www.wowhead.com/quest=27804/the-only-homes-we-have
**What is happening:**

when you throw water on the fire it goes out, but it doesn't count towards the quest. 
Also, the villagers are supposed to replenish the water to you, but you have to return to the well to get more.

**What should happen:**

when you put out a fire, it should count towards the progress in the quest.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/J2D73vP.jpg)

fixed with next update
