### ISSUE TITLE
[Warrior] Deep wounds - Missing scaling with attackpower

### ISSUE THREAD

**Issue by cocojumbo1** [WoWManiaUK/Blackwing-Lair#3372]
**Links:**
![image](https://user-images.githubusercontent.com/55558456/65373875-739ce780-dc83-11e9-8454-fc327c7231a5.png)

from WoWHead or our Armory

**What is happening:**
Deep wounds does 48% of our average weapon dmg

**What should happen:**

Deep wounds needs to scale with atack power,so it needs to do dmg on equiped weapon that means it should snapshot current procs such as trinkets and other dmg increasing talents

**Comment by Keader** [comment]
@Dranah can confirm it?

**Comment by cocojumbo1** [comment]
i can show...if i for example equip weapon for lvl 60 it will do bleeds for like 16...I can show u some pictures from other servers?

**Comment by cocojumbo1** [comment]
![image](https://user-images.githubusercontent.com/55558456/65540744-49118f80-df0c-11e9-9e45-ce63c779be67.png)
see how deep wounds do diffirent dmg?they scale with current attack power and tallent buffs and its doing 122 ticks on a lvl 66 character

**Comment by cocojumbo1** [comment]
![image](https://user-images.githubusercontent.com/55558456/65541040-d3f28a00-df0c-11e9-8766-cac763e85728.png)
this is taken on reign...its always a same dmg and it ticks for 174 on a lvl 85 toon

**Comment by Keader** [comment]
Dranah said in discord (after my question https://github.com/WoWManiaUK/Blackwing-Lair/issues/3372#issuecomment-534560019)
![image](https://user-images.githubusercontent.com/7120913/66921773-39adcf80-effc-11e9-9424-4efad485545b.png)
If you have any proof (blizzlike one) let me know and i will re-open and fix it (if is the case)
