### ISSUE TITLE
[Quest/daily] Teach A Man To Fish.... Or Steal (Ally)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3374]
**Links:**
https://www.wowhead.com/quest=28137/teach-a-man-to-fish-or-steal

![steal fish](https://user-images.githubusercontent.com/39439201/65374413-e0b37b80-dc89-11e9-928a-8262d15e88cf.jpg)
![21 22](https://user-images.githubusercontent.com/39439201/65374415-e315d580-dc89-11e9-8772-e26ebcfa6620.jpg)

**What is happening:**
- Can only get 21/22 fish 
- but quest says its complete (but cant hand back) 

**What should happen:**
_You must steal 22 Rustberg Seabass from Rustberg Village. The fish can be found on string stands at the docks, round back of the village. Rustberg Village is due north of base camp, on the right side._

**Comment by Echinaceax** [comment]
same issue as this @Rushor https://github.com/WoWManiaUK/Blackwing-Lair/issues/1804#issuecomment-533255447

**Comment by Rushor** [comment]
hm i don't now the reason for that issue. it works fine in dev. 

![I](https://i.imgur.com/b4MRrkg.jpg)

**Comment by Echinaceax** [comment]
hmm, odd. i will retest tomorrow @rusher

**Comment by Rushor** [comment]
kay

**Comment by Echinaceax** [comment]
@Rushor retested now seems its ok today. 
Still some issues though i think its coz you can loot the https://www.wowhead.com/npc=47642/rustberg-fisherman 
and the fish that hangs on rack too, coz its leaving extra fish after you have 22/22 


![image](https://user-images.githubusercontent.com/39439201/65431849-69612180-de1a-11e9-9839-ad20751a5ec9.png)

2 left over in bags https://www.wowhead.com/item=63047/rustberg-seabass
