### ISSUE TITLE
[Profession] Archaeology digsites in zones not suitable for player level

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Blackwing-Lair#3376]
**Links:**
https://wow.gamepedia.com/Archaeology

**What is happening:**
Digsites are appearing in zones not suitable for player's level, meaning they cannot be dug until very high level.
e.g. at level 20, I received sites in Badlands (40+), EPL (45+), Azshara & Ungoro (50+) and even Twilight Highlands (80+)
![InkedWoWScrnShot_092119_171813a_LI](https://user-images.githubusercontent.com/46089380/65376214-46593500-dc95-11e9-82ad-a390815e4f89.jpg)
![InkedWoWScrnShot_092119_172146a_LI](https://user-images.githubusercontent.com/46089380/65376215-46593500-dc95-11e9-8a86-6960edace358.jpg)

**What should happen:**
https://wow.gamepedia.com/Archaeology
> As related by Ghostcrawler:[5]
Archaeological dig sites...
**Your dig sites appear in level-appropriate zones.** Players will not be able to survey in Outland, Northrend or any of the Cataclysm zones until they have reached the minimum level to enter those zones.

**Comment by Rushor** [comment]
duplicate https://github.com/WoWManiaUK/Blackwing-Lair/issues/2680
