### ISSUE TITLE
[Quest] Prisoners of War

### ISSUE THREAD

**Issue by fllo55555** [WoWManiaUK/Blackwing-Lair#3377]
**Links:**
https://www.wowhead.com/quest=26646/prisoners-of-war
from WoWHead or our Armory

**What is happening:**
At secound quest after i get the key whem in trying to open the cages is not working and is not counting as quest completed.

**What should happen:**
After i got the key from the cave go to the position 69.42  / 59.58 open a cage with prisoners and the quest should be done. + Jorgensen missing

**Comment by Rushor** [comment]
fixed with next update

![I](https://i.imgur.com/u1X8vjL.jpg)
