### ISSUE TITLE
[Class] Mind Flay does not benefit from Vampiric Embrace

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Blackwing-Lair#3379]
**Links:**
Spell ID 15286
https://wowwiki.fandom.com/wiki/Vampiric_Embrace

**What is happening:**
The shadowpriest is not healed when said shadowpriest casts Mind Flay while buffed by Vampiric Embrace.

**What should happen:**
Mind Flay is a single target spell, and should benefit of 6% healing from Vampiric Embrace.

I did find this in my research, which may or may not be related, it seems to explain the symptoms:
https://github.com/TrinityCore/TrinityCore/issues/18250

**Comment by Rushor** [comment]
The issue is still there. Please recheck :)

**Comment by Echinaceax** [comment]
@Rushor just tested this ..it shows in combat log but numbers are wrong defo
![vampric combats log](https://user-images.githubusercontent.com/39439201/66254744-0d33c100-e77b-11e9-82c6-77b6fc2e8cd1.jpg)

**Comment by jarvik76** [comment]
I also think Mind Spike is not benefitting either.  Spell ID 73510.  If a separate ticket should be made for that, am happy to do that.
![WoWScrnShot_100619_003730a](https://user-images.githubusercontent.com/46089380/66262143-edc88280-e7d2-11e9-85d1-ddf93b8e73c0.jpg)

**Comment by Echinaceax** [comment]
yes please @jarvik76 if you could make new report for mind spike that would be great :)

**Comment by Keader** [comment]
Just tested now
![image](https://user-images.githubusercontent.com/7120913/66268805-6d784080-e817-11e9-89bd-606f4074289c.png)

As you can see in SS
Damage = 2091
Self heal = 6% of damage -> 2091 * 0.06 = 125.46 (my priest heal)
Party Heal = 3% of damage -> 2091 * 0.03 = 62.73 (druid heal)
Everything is working fine with values.
Even in comment https://github.com/WoWManiaUK/Blackwing-Lair/issues/3379#issuecomment-538644989
Combatlog shows 623 of shadow damage, 623*0.06= 37.38
So is correct too.
But, i fixed mind spike, was not proccing with mind spike.
