### ISSUE TITLE
[Quest] Myzrael's tale: Duplication - Arathi Highlands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#338]
Quest - https://www.wowhead.com/quest=26346/myzraels-tale
NPC -https://www.wowhead.com/object=2702
Quest duplication, doesn't prevent you from handing in or collecting the other quest.
![world of warcraft 02_01_2019 19_52_26_li](https://user-images.githubusercontent.com/42302580/50609692-598a6180-0ec8-11e9-9b83-72355321346b.jpg)

**Comment by Echinaceax** [comment]
Yes i got the same on horde side too :)
