### ISSUE TITLE
[Quest] Lifting the Veil - 27770 - Badlands

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Blackwing-Lair#3381]
**Links:**
https://www.wowhead.com/quest=27770/lifting-the-veil
https://www.wowhead.com/npc=46654/rhea

**What is happening:**
The event does not trigger, and the quest does not complete

**What should happen:**
A black dragon underneath the red magic shield appears behind you.
See https://youtu.be/rFnVSGl6JHo

**Comment by Echinaceax** [comment]
Already reported here #2060
