### ISSUE TITLE
[Spiritual Training: Mercy is for the weak] Hyjal bug quest

### ISSUE THREAD

**Issue by Icyytouch** [WoWManiaUK/Blackwing-Lair#3382]
**Links:**

from WoWHead or our Armory

**What is happening:**
Adds won't show up at the place quest shows

**What should happen:**
Adds should show up there

**Comment by Rushor** [comment]
http://cata.cavernoftime.com/quest=25309

**Comment by Rushor** [comment]
creatures added with next update

![I](https://i.imgur.com/NG7i4xO.jpg)

**Comment by Icyytouch** [comment]
Thnx
