### ISSUE TITLE
[Server Crash] Force Grip Abillity

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#3384]
**Links:**
https://www.wowhead.com/spell=79351/force-grip
https://www.wowhead.com/npc=42333/high-priestess-azil
**What is happening:**
If you let the final boss from Stonecore performing Force Grip to full ,  it sometimes crashes the server , lets say like 3 of 5 it crashes the server
**What should happen:**
Well its not suppose to crash the server

**Comment by Echinaceax** [comment]
not fixed still, confirmed by Dracku @Keader
