### ISSUE TITLE
[Dungeon] Stratholme

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#3385]
**Links:**
https://classic.wowhead.com/item=12382/key-to-the-city
**What is happening:**
I dont know if the problem is the key or the doors , but i clear all trash in there got the key and still the door is closed.
https://imgur.com/Qyeyp5V
**What should happen:**
By using key you can advance into the dungeon

**Comment by Echinaceax** [comment]
i got info from GM here #2173

**Comment by Rushor** [comment]
well duplicate then https://github.com/WoWManiaUK/Blackwing-Lair/issues/2173 will fix that
