### ISSUE TITLE
[Item] Crate of Tasty Meat - ID 65513

### ISSUE THREAD

**Issue by Nacho-k** [WoWManiaUK/Blackwing-Lair#3388]
**Links:**
Item: https://www.wowhead.com/item=65513/crate-of-tasty-meat

**What is happening:**
  It gives nothing

**What should happen:**
  It should give 2-10 items of cataclysm meat and a poor quality item
https://www.wowhead.com/item=65513/crate-of-tasty-meat#contains

**Comment by Rushor** [comment]
![I](https://i.imgur.com/5VAkU19.jpg)

fixed with next update
