### ISSUE TITLE
[Quest] Devastation - 27930 - Badlands

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Blackwing-Lair#3389]
**Links:**
https://www.wowhead.com/quest=27930/devastation#comments
https://www.wowhead.com/object=206504/rheas-final-note

**What is happening:**
Since the preceding 3 quests are bugged ([Quest] The Day that Deathwing Came - 27713 - Badlands #449), this has perhaps never been picked up.

Even though the question completion ? mark shows on map, Rhea is not present at the coordinates.  Therefore her script does not run, the video is missing, and she doesn't leave the "final note" item that the player uses to turn in the quest. 

**What should happen:**
A video plays, Rhea leaves a note that is used for quest turn in.

**Comment by Rushor** [comment]
fixed with next update

![I](https://i.imgur.com/fo4AXuf.jpg)
