### ISSUE TITLE
[Item] Fortune Cookie

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3392]
**Links:**

https://www.wowhead.com/item=62649/fortune-cookie
Recipe of https://www.wowhead.com/item=65432/recipe-fortune-cookie
**What is happening:**
- Doesnt give food buff 

**What should happen:**
Use: Restores 8832 health and 8832 mana over 30 sec.  Must remain seated while eating.  **_If you spend at least 10 seconds eating you will become well fed and gain 13 Stamina and 13 in another useful stat for 1 hour._**

Reported by Vortex to GM 

Confirmed by me

**Comment by Rushor** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/2855 link here :>
