### ISSUE TITLE
[Item/Currency] Vial Pricing Bug

### ISSUE THREAD

**Issue by Lurc1981** [WoWManiaUK/Blackwing-Lair#3393]
**Links:**

Not really a link to this available on Wowhead with cataclysm stack prices

**What is happening:**

Vendor lists price as 90c for a stack of 5 Vials but charges 4s 50c for a stack of 5 vials

**What should happen:**

Price really should be 5 vials for 90c. At the price of 4s 50c it is priced out of new players ranges as it shouldn't be.

**Comment by Rushor** [comment]
can you add links and screenshot?

**Comment by Lurc1981** [comment]
I cannot find a link that shows the Cata pricing on this item as shown in these next two pictures. Sorry.

![Before purchase of vials](https://user-images.githubusercontent.com/54812659/65462290-16d43500-de1b-11e9-933b-8396d45618df.jpg)

Vendor window shows 5 Crystal Vials for 90c

![After purchase of vials](https://user-images.githubusercontent.com/54812659/65462314-30757c80-de1b-11e9-83a1-441784ea686e.jpg)

After Purchase of one unit it costs 4s 50c for the item instead of 90c

**Comment by Lurc1981** [comment]
Note to add, it does the same thing for the cracked vials as well.

**Comment by Sammy974** [comment]
https://cata-twinhead.twinstar.cz/?item=3371

It sais 1s in twinhead

**Comment by Lurc1981** [comment]
![WoWScrnShot_092319_163506](https://user-images.githubusercontent.com/54812659/65464743-36ba2780-de20-11e9-978c-8eae60a36fa4.jpg)

Even at a different vendor it's listed for 90c for a stack of 5. You'd either have to unstack the items and sell for 90c a piece (Which wasn't the way it was done when this was live) or change the pricing to be for the stack of 5 instead of individually.

**Comment by Echinaceax** [comment]
@Rushor ive looked at twinhead (they are not updated)
so for now go with wowhead prices until i can look more into it https://classic.wowhead.com/npc=4226/ulthir

**Comment by Rushor** [comment]
well this is made in dbc files for cata and cannot be changed. on retail currently the price is also low
https://www.wowhead.com/item=3371/crystal-vial

putting won-fix to that for now. sorry

**Comment by Kitzunu** [comment]
Just to update you all so you are aware, this issue is fixed here https://github.com/WoWManiaUK/Blackwing-Lair/issues/4003 :)
