### ISSUE TITLE
[Quest] Druid of the Claw

### ISSUE THREAD

**Issue by Lurc1981** [WoWManiaUK/Blackwing-Lair#3394]
**Links:**

https://classic.wowhead.com/quest=2561/druid-of-the-claw

**What is happening:**

Obtain the shaman's belt from the spirit of Oben Rageclaw, but his physical form doesn't spawn in the bottom of the cavern.

**What should happen:**

Once you obtain the item from Oben Rageclaw, it should trigger his physical form to spawn in the bottom of the cavern to be killed, and then use the item on his corpse prior to turning in back at the spirit of Oben Rageclaw.

**Comment by Rushor** [comment]
the quest has a bit changed in cata https://www.wowhead.com/quest=2561/druid-of-the-claw#videos:id=99185

**Comment by Rushor** [comment]
this works all fine. rageclaw is behind the door and can be killed and item can be used on him. invalid report 

![I](https://i.imgur.com/dQrtCoB.jpg)
![I](https://i.imgur.com/436E15c.jpg)
![I](https://i.imgur.com/WKEnBva.jpg)
