### ISSUE TITLE
[Quest] An Ounce of Prevention -  Darkshore

### ISSUE THREAD

**Issue by Lurc1981** [WoWManiaUK/Blackwing-Lair#3395]
**Links:**

https://www.wowhead.com/quest=13925/an-ounce-of-prevention

**What is happening:**

Using the item provided (Lifebringer Sapling) on any of the mentioned mobs send the three orbs spinning at them and spawns the Devouring Presence but doesn't actively interact with the mobs at all or give credit.

**What should happen:**

Devouring presence should interact with the mobs in the way a spawned pet/npc would and then gives credit for 'testing' the Lifebringer Sapling.

**Comment by Rushor** [comment]
Test the Lifebringer Sapling on any nearby healthy Grizzled Thistle Bear, Whitetail Stag, or Moonstalker Matriarch/Sire.

**Comment by Rushor** [comment]
credits should given on 2165 34318 2071 2237

**Comment by Rushor** [comment]
okay you can now use the spell in 30 yards range to Grizzled Thistle Bear, Whitetail Stag, Moonstalker Matriarch or Moonstalker Sire and get the credit

![I](https://i.imgur.com/jWAaEY1.jpg)
