### ISSUE TITLE
[Quest] The scent of lar'korwi - 24732 - Un'goro Crater

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Blackwing-Lair#3396]
**Links:**
https://www.wowhead.com/quest=4291/the-scent-of-larkorwi
https://classic.wowhead.com/npc=9683/larkorwi-mate

**What is happening:**
I have found several clusters of the dinosaur eggs, but none of them seem to trigger the spawn of the lar'korwi mate

**What should happen:**
From wowhead comment:
Ravasaur Mates only spawn when u run across eggs. Do it and one will come rushing at you. After that, my experience was I had to find a new pile of eggs to repeat. I only got one Mate from 1 egg nest.

**Comment by Rushor** [comment]
cata quest is http://cata.cavernoftime.com/quest=24732
