### ISSUE TITLE
[NPC] Garona Halforcen is missing

### ISSUE THREAD

**Issue by rexxo** [WoWManiaUK/Blackwing-Lair#3397]
https://www.wowhead.com/npc=46323/garona-halforcen

The NPC is missing from where it should be. It should be at loc 53.3 42.6 but it's completely missing.

The NPC starts and ends 2 quests:
https://www.wowhead.com/quest=27947/a-vision-of-twilight
https://www.wowhead.com/quest=27955/eye-spy

**Comment by Rushor** [comment]
![I](https://i.imgur.com/pUvfuir.jpg)

visible now
