### ISSUE TITLE
[Spell] Sinister Strike 

### ISSUE THREAD

**Issue by Anthonhed** [WoWManiaUK/Blackwing-Lair#34]
[Sinister Strike](http://wow-mania.com/armory/?spell=1752) does not deal any damage when using it nor does it award a combo point on the target. It should add one combo point per use and deal dmg.

https://youtu.be/QSsN5wzWjEg

**Comment by Dranah** [comment]
This was probably tested before the fix on Energy bars which prevented SS from being cast at all.
But now it can be properly cast, does damage and adds combo point.

**Comment by Revner17** [comment]
It does appear Sinister Strike does do damage but there is no visibility when combo points are earned, usually it shows as a side ticker on the attacked NPC with red bullets. See attached images. 
![ss without combo points](https://user-images.githubusercontent.com/47263920/52248683-95488a80-28bd-11e9-8888-1e6e471bdd4c.PNG)
![sinister strike with visible combo points](https://user-images.githubusercontent.com/47263920/52248686-97124e00-28bd-11e9-88de-166ffaec0629.PNG)
![capture2](https://user-images.githubusercontent.com/47263920/52248689-98dc1180-28bd-11e9-9e13-f6b9db1cc6bf.PNG)

**Comment by Revner17** [comment]
Combo Points are awarded at level 3 when Eviscerate is learned.
