### ISSUE TITLE
[NPC] <Alchemy Supplies>

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3400]
**Links:**
https://classic.wowhead.com/npc=4610/algernon
- [x] Missing supplies

https://classic.wowhead.com/item=13477/recipe-superior-mana-potion

-------------------------------------
https://classic.wowhead.com/npc=4226/ulthir

- [x] missing supplies

https://classic.wowhead.com/item=13477/recipe-superior-mana-potion
https://classic.wowhead.com/item=5643/recipe-great-rage-potion
https://classic.wowhead.com/item=5642/recipe-free-action-potion

-----------------------
 https://cata-twinhead.twinstar.cz/?npc=1313
- [x] missing supplies
https://cata-twinhead.twinstar.cz/?item=9301
------------------

NPC missing 
- [ ] Nandar Branson <Alchemy Supplies> https://cata-twinhead.twinstar.cz/?npc=2380
- [ ] Bliztik <Alchemy Supplies>https://cata-twinhead.twinstar.cz/?npc=2481

**Comment by Rushor** [comment]
okay fixed

![I](https://i.imgur.com/gmIwzNo.jpg)

the other aswell

**Comment by Echinaceax** [comment]
@Rushor havent finished checking all yet tho :P

**Comment by Rushor** [comment]
okay sure yo, just add and i continue fixing them :>

**Comment by Echinaceax** [comment]
ok all done i think @Rushor :)

**Comment by Rushor** [comment]
alright added the one missing item

the two missing creatures are intended removed as can be seen in one of the commets of them:

Crazyorc on 2010/12/13 (Patch 4.0.3)
He's gone, as in Blizz neglected to copy him over for Cataclysm. At this time all you can do is hope they add him back in a upcoming patch.

https://www.wowhead.com/npc=2481/bliztik#comments:id=1207338

https://wow.gamepedia.com/Nandar_Branson

Patch 4.0.3a (2010-11-23): Removed.
