### ISSUE TITLE
[Object/Dungeon] Door Blackrock Depths 

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#3401]
**Links:**
https://imgur.com/BQLykJL
https://imgur.com/SlsMmTi
**What is happening:**
After you kill the first wave in the Ring of Law nothing happens after and you are stuck there.
**What should happen:**
After serveral waves the boss should apper and kill it

**Comment by Rushor** [comment]
duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/910
