### ISSUE TITLE
[Boss] Nightbane - Karazhan

### ISSUE THREAD

**Issue by Venom64bit** [WoWManiaUK/Blackwing-Lair#3402]
**Links:**

NPC:https://www.wowhead.com/npc=17225/nightbane

**What is happening:**
The Urn in the room isn't interactable.

**What should happen:**
After you complete the Chain Quest you can summon the boss Nightbane in Master Terrance at Karazhan by using the urn in the area.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/RlqrDJr.jpg)

with next update
