### ISSUE TITLE
[Quest] The Endless Flow

### ISSUE THREAD

**Issue by fllo55555** [WoWManiaUK/Blackwing-Lair#3403]
**Links:**
https://www.wowhead.com/quest=27161/the-endless-flow
from WoWHead or our Armory

**What is happening:**
Stickbone Berseker are mising and not spawning + quest item when is used on Scourge Bone Animus nothing happent

**What should happen:**

In front of that building should be spawned mobs (stickbone bersekers) have to be killed with quest item and then use again quest item on Scourge Bone Animus

**Comment by Echinaceax** [comment]
Already reported here #368
but thank you
