### ISSUE TITLE
[QUEST] Those That Couldn't Let Go

### ISSUE THREAD

**Issue by fllo55555** [WoWManiaUK/Blackwing-Lair#3404]
**Links:**
https://www.wowhead.com/quest=27168/those-that-couldnt-let-go
from WoWHead or our Armory

**What is happening:**
Using the quest item on mobs wont turn them from friendly target to enemy so they can be killed

**What should happen:**
Use the quest item on mob will turn him into enemy target being able to be killed for quest count

**Comment by Rushor** [comment]
duplicate https://github.com/WoWManiaUK/Blackwing-Lair/issues/372
