### ISSUE TITLE
[QUEST] Ambushed!

### ISSUE THREAD

**Issue by fllo55555** [WoWManiaUK/Blackwing-Lair#3405]
**Links:**
https://www.wowhead.com/quest=27171/ambushed
from WoWHead or our Armory

**What is happening:**

Mobs are missing

**What should happen:**

Mobs should be spawned into the grave with drop of quest items

**Comment by Rushor** [comment]
duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/373

pls check the github https://github.com/WoWManiaUK/Blackwing-Lair/search?q=search&unscoped_q=search in the repo before posting new bugs thanks @fllo55555
