### ISSUE TITLE
[NPC] Brashtide Raider <The Brashtide Crew>

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3406]
**Links:**

https://www.wowhead.com/npc=43716/brashtide-raider

![brashtide raider1](https://user-images.githubusercontent.com/39439201/65545759-4f0c6e00-df16-11e9-8a78-37949a6502ee.jpg)
![gps](https://user-images.githubusercontent.com/39439201/65545762-516ec800-df16-11e9-9ba5-c5f744f14b8e.jpg)
and 
![gps2](https://user-images.githubusercontent.com/39439201/65547553-f8089800-df19-11e9-9a9b-6daacdccf310.jpg)

**What is happening:**
- 4 inside each other  

**What should happen:**
- Need spacing

**Comment by Rushor** [comment]
also will add a fake combat between them and the booty bay goblins, to look better
