### ISSUE TITLE
[Item] Barrel of Gunpowder - Vashj'ir 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3407]
**Links:**

https://www.wowhead.com/item=62228/barrel-of-gunpowder
https://www.wowhead.com/quest=25651/oh-the-insanity

**What is happening:**
- drops too many after 50/50

**What should happen:**
_Collect 50 Pilfered Cannonballs from Gurboggle's Ledge and from Gilblin Hoarders. Use the Cannonballs to create a Barrel of Gunpowder._

**Comment by Rushor** [comment]
i think that happens to all kind of such quests, it's not gamebreaking, but cannot be fixed eitherway :(

https://i.imgur.com/w7iOpgx.jpg

**Comment by Kitzunu** [comment]
isnt that because the quest doesnt have QuestRequired = 1 in loot template?
