### ISSUE TITLE
[Item] Booby-Trapped Bait - Vashj'ir 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3408]
**Links:**

https://www.wowhead.com/item=55190/booby-trapped-bait
https://www.wowhead.com/quest=25657/dah-nunt-dah-nunt

**What is happening:**
- Cant lay bait 

**What should happen:**
_Budd wants you to use the Booby-Trapped Bait at the Rusty Harpoon Gun in the Skeletal Reef._

**Comment by Rushor** [comment]
movie is missing but credit is given now.

![I](https://i.imgur.com/Vq4OaTi.jpg)
