### ISSUE TITLE
[Item] Gnaws' Tooth - Vashj'ir 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3409]
**Links:**

https://www.wowhead.com/item=55212/gnaws-tooth
https://www.wowhead.com/quest=27699/shark-weak

**What is happening:**
- Missing 

**What should happen:**
_Collect 5 of Gnaws' teeth from the Skeletal Reef._

**Comment by Rushor** [comment]
fixed. in phase 169 

![I](https://i.imgur.com/rUzAuq7.jpg)
