### ISSUE TITLE
[Spell/Warlock] Soul burn - not consumed when used

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#341]
Just checking something

**Is this correct?** 
- This combo pop doesn't seem right at low level (OP)
- Just seems far to OP to me - 4 instant soul fire on each combo pop 
- CD of the soul burn only 45 secs 

- Wowhead says this it a pvp talent not a spell in the spellbook
https://www.wowhead.com/spell=213398/soulburn

![soulburn](https://user-images.githubusercontent.com/39439201/50618752-33c78180-0ef5-11e9-9154-fd5a15d2f2eb.jpg)
![soulfire](https://user-images.githubusercontent.com/39439201/50618756-35914500-0ef5-11e9-9bb2-49c47db01619.jpg)

![seems for to op to me](https://user-images.githubusercontent.com/39439201/50618851-a89abb80-0ef5-11e9-9b6e-e0f0c73662aa.jpg)

![soul burn](https://user-images.githubusercontent.com/39439201/50618721-11356880-0ef5-11e9-842f-fb508fa0e59a.jpg)
![soul fire](https://user-images.githubusercontent.com/39439201/50618725-15fa1c80-0ef5-11e9-908b-d4f42048148f.jpg)

**Edited to add more info**
- I did do another search adding "soul burn cata" and yes it does have it as a spell now.
- Still seems very OP to me.
  https://cata-twinhead.twinstar.cz/?spell=74434

![soul burn cata](https://user-images.githubusercontent.com/39439201/50619199-1cd65e80-0ef8-11e9-9879-b99d4a534eaa.jpg)

**Comment by Dranah** [comment]
Soulburn only affects your next spellcast. So every 45sec, you can use this ability to empower ONE spell, if it is soul fire, that will give you an instant cast soul fire. One, every 45sec.
Is the effect not consumed when using an instant soul fire? So that it allows you to cast 4 in a row?

**Comment by Dranah** [comment]
Confirmed, ability is not consumed on use. You can cast as many spells with the boost as the 15sec duration - and your soul shards - allow.

**Comment by Echinaceax** [comment]
> Is the effect not consumed when using an instant soul fire? So that it allows you to cast 4 in a row?

yes

And if the mobs are higher then i can get up to 6 soul fire of in one pop

**Comment by Keader** [comment]
Is not just it.
Has effects missing in Soulburn, like Seed of corruption one.
I need sometimee to fix all, i will take a look tomorrow xD

**Comment by Keader** [comment]
Fixed.

**Comment by Dranah** [comment]
- All effects of Soulburn now work as intended
- Soulburn effect is consumed when used.
