### ISSUE TITLE
[Item] Budd's Chain - Vashj'ir 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3410]
**Links:**
https://www.wowhead.com/item=55220/budds-chain

![rushy gun](https://user-images.githubusercontent.com/39439201/65552641-38214800-df25-11e9-9743-3903815e7d87.jpg)
![rusty gun 2](https://user-images.githubusercontent.com/39439201/65552644-3b1c3880-df25-11e9-91b1-3797d82623d9.jpg)

**What is happening:**
- Cant use the item 
- Could be the Rusty harpoon gun though thats not working 

**What should happen:**
_Use Budd's Chain on the Rusty Harpoon Gun in The Skeletal Reef. Fire the Harpoon when Gnaws is in position over the gun._

**Comment by Rushor** [comment]
the movie will be missing. too complicated, but will add the credit for now on use.

![I](https://i.imgur.com/PcMi2i2.jpg)
