### ISSUE TITLE
[Object] The Pewter Prophet - Vashj'ir 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3411]
**Links:**

https://www.wowhead.com/npc=41192/the-pewter-prophet
https://www.wowhead.com/item=55806/the-pewter-pounder
https://www.wowhead.com/quest=25743/decisions-decisions
quest giver https://www.wowhead.com/npc=46458/budd
quest back https://www.wowhead.com/npc=46463/budd

**What is happening:**
- Cant destroy The Pewter Prophet
- cant speak with budd (46463) after auto complete budd wrong phase

![budd phase](https://user-images.githubusercontent.com/39439201/65553982-90a61480-df28-11e9-8286-cad7c9a6083d.jpg)

**What should happen:**
_You must use The Pewter Pounder to destroy The Pewter Prophet._

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/C4HXS66.jpg)
![I](https://i.imgur.com/f6W0bhE.jpg)
![I](https://i.imgur.com/H8YCsFW.jpg)
