### ISSUE TITLE
Pets dont get DMG-Reduction (AoE)

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3412]
**Links:**

from WoWHead or our Armory

**What is happening:**

Hunter Pets, Unholy Pet, Enhancer Wolfes, all of them dont get Damage reduction for AoE.

**What should happen:**

dmg should be lowered by 80-99% for AoE

**Comment by Rushor** [comment]
ID - 32233 Avoidance (Passive)

**Comment by Rushor** [comment]
okay added for all kind of summon pets by player. If some pets are missing let me know.

fixed with next update

**Comment by Rushor** [comment]
fixed for all kind of pets

enum PetEntries
{
    // Warlock Pet/Minions
    ENTRY_IMP                       = 416,
    ENTRY_VOIDWALKER                = 1860,
    ENTRY_SUCCUBUS                  = 1863,
    ENTRY_FELHUNTER                 = 417,
    ENTRY_FELGUARD                  = 17252,
    ENTRY_INFERNAL                  = 89,
    ENTRY_EBON_IMP                  = 50675,
    ENTRY_DOOMGUARD                 = 11859,

    // Mage Pet
    ENTRY_WATER_ELEMENTAL           = 510,
    ENTRY_WATER_ELEMENTAL_P         = 37994,
    ENTRY_MIRROR_IMAGE              = 31216,

    // Druid Minion
    ENTRY_TREANT                    = 1964,    

    // Shaman Minions
    ENTRY_EARTH_ELEMENTAL           = 15352,
    ENTRY_FIRE_ELEMENTAL            = 15438,
    ENTRY_SPIRIT_WOLF               = 29264,

    // Death Knight Pet/Minions
    ENTRY_GHOUL                     = 26125,
    ENTRY_BLOODWORM                 = 28017,
    ENTRY_RUNIC_WEAPON              = 27893,
    ENTRY_GARGOYLE                  = 27829,    
    ENTRY_ARMY_OF_THE_DEAD_GHOUL    = 24207,
    
    // Priest Pet
    ENTRY_SHADOWFIEND               = 19668,

    // Hunter Trap Adds
    ENTRY_VENOMOUS_SNAKE            = 19833,
    ENTRY_VIPER                     = 19921,

    // Paladin
    ENTRY_PALADIN_MELEE_GUARDIAN    = 46506
};

**Comment by Slydee23** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/55513205/66778967-69aa8500-eecd-11e9-88f8-5aedeed41cd1.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/55513205/66778969-69aa8500-eecd-11e9-972b-aebc63af93bc.jpg)
