### ISSUE TITLE
[NPC/Mining] Gloom'rel - Blackrock Depths

### ISSUE THREAD

**Issue by Venom64bit** [WoWManiaUK/Blackwing-Lair#3415]
**Links:**
NPC: https://classic.wowhead.com/npc=9037/gloomrel
QLink: https://classic.wowhead.com/quest=4083/the-spectral-chalice
NPC Train: https://wowwiki.fandom.com/wiki/Smelt_Dark_Iron
NPC-Wiki: https://wowwiki.fandom.com/wiki/Gloom%27rel

**What is happening:**
The NPC is hostile.

**What should happen:**
He must offers the mining quest to learn how to smelt Dark Iron.

**Comment by Rushor** [comment]
hm i think the object https://classic.wowhead.com/object=164869/spectral-chalice must provide that quest

**Comment by Rushor** [comment]
kay added


![I](https://i.imgur.com/sEAJYQN.jpg)

**Comment by Venom64bit** [comment]
The quest works, but it doesn't teach you the Smelting of the Dark Iron.
https://wowwiki.fandom.com/wiki/Smelt_Dark_Iron

**Comment by Echinaceax** [comment]
@Venom64bit so the object is fixed but the completed quest is bugged correct ?

**Comment by Rushor** [comment]
will work sth different out then with gossips
