### ISSUE TITLE
[Quest] Threat from the Water - Darkshore

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3418]
**Links:**
https://www.wowhead.com/quest=13522/threat-from-the-water

**What is happening:**
- Didnt add to quest log when accepted it 

**What should happen:**
_Should go in log_

**Comment by Rushor** [comment]
well it adds to the log https://i.imgur.com/unuGwo2.jpg

just the points on the map are missing, that will be fixed in future, not now for many quests :>
