### ISSUE TITLE
[Spell] Unholy Deathknight, Pet , Ghoul Transformation

### ISSUE THREAD

**Issue by Shoogii** [WoWManiaUK/Blackwing-Lair#3419]
**Links:**

https://wowwiki.fandom.com/wiki/Shadow_Infusion
https://cata-twinhead.twinstar.cz/?spell=63560

What is  happining
If the ghoul has 5  stacks of shadow infusion (so u can normaly transform him ) and u wait for to long to transform him by Dark Tranformation ( like 7 to 10 sec something like that)  or the ghoul simply dies, then the ghoul will stay at 5 stacks and Dark Transformation will be un-castable until the previous 5 stacks of Shadow Infusion have dropped off. ( even if u summon a new one he keep the stacks)

 I know that this got allready reported but isnt fixed at all
**What should happen.

U should always can cast Dark Transformatioin as long as there are five stacks of Shadow Infusion.

**Comment by Rushor** [comment]
Old report was: https://github.com/WoWManiaUK/Blackwing-Lair/issues/3065

**Comment by Keader** [comment]
I cant reproduce your issue.
I'm always able to cast Dark Transformation, if ghoul has 5 stacks.

**Comment by Shoogii** [comment]
Hey i found a way how u can reproduce it.
Just Stack it to 5 like normally, so u can transform him.
Than just wait like 10 sec´s and refresh the buff with a deathcoil on  Targets or on the ghoul itself
After the first 30 sec from the "original buff" u cannot transform him anymore 
Its like the refresh buffs dont count .
For example if u make the last trash group before a boss and u start stacking and wanna keep the transformation up for the boss and throw a few deathcoils on ur ghoul to refresh u cannto transform him after the 30 sec

**Comment by Keader** [comment]
Now i can reproduce.
Fixed.

**Comment by Shoogii** [comment]
U make me Happy <3
