### ISSUE TITLE
[Item/Drop] Witherbark Tusk / Witherbark Medicine pouch - Arathi Highlands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#342]
**Crush the witherbark** 
Quest - https://www.wowhead.com/quest=26429/crush-the-witherbark

- Is dropping the quest items for an Ally quest

**Worth Its Weight in Gold**
Quest - https://www.wowhead.com/quest=26035/worth-its-weight-in-gold
 
Quest item - https://www.wowhead.com/item=4503/witherbark-tusk
Quest item - https://www.wowhead.com/item=4522/witherbark-medicine-pouch

![witherbark tusk](https://user-images.githubusercontent.com/39439201/50623810-ced25280-0f19-11e9-8cf5-9d7019e793f4.jpg)

![witherbark medichine pouch](https://user-images.githubusercontent.com/39439201/50624002-d4309c80-0f1b-11e9-8dae-9b903ffe0fac.jpg)

- As far as ive seen Horde doesnt get that quest.
- So no need for items drop.

**Comment by Dranah** [comment]
Is it also dropping horde version tho? Like quest is completable just drops an extra item?
