### ISSUE TITLE
[Quest] The Devourer of Darkshore - Darkshore

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3421]
**Links:**
https://www.wowhead.com/quest=13891/the-devourer-of-darkshore
https://www.wowhead.com/item=46370/lifebringer-sapling

![water hole](https://user-images.githubusercontent.com/39439201/65645083-72a6e580-dff6-11e9-8321-d3a714a54617.jpg)

**What is happening:**
- Quest item not working 

**What should happen:**
_Use the Lifebringer Sapling on the shore of the shallow lake south of the Grove of the Ancients to destroy the Devouring Artifact and its guardian._
https://www.wowhead.com/quest=13891/the-devourer-of-darkshore#videos:id=33033

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/uPoK0om.jpg)
![I](https://i.imgur.com/duHseES.jpg)
![I](https://i.imgur.com/QaZd6id.jpg)
