### ISSUE TITLE
[Raid] Sunwell Plateau

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#3422]
**Links:**
https://www.wowhead.com/sunwell-plateau
**What is happening:**
First problem is at first boss (https://www.wowhead.com/npc=24850/kalecgos) you will get stuck inside and the boss will reset
Second problem is at third boss (https://www.wowhead.com/npc=25038/felmyst) in last phase will spawn 1000000000 zombies and the fps will drop to 0 then you will die + you cannot pass the fire wall to continue the raid if you want to skip
Last problem is at last boss (https://www.wowhead.com/npc=25315/kiljaeden) during some abillities that he does ( dunno wich one ) all party/raid will get 24/7 client crash
**What should happen:**
They should work

**Comment by Rushor** [comment]
okay just anote: http://www.buffed.de/World-of-Warcraft-Spiel-42971/Guides/WoW-Guide-Das-Sonnenbrunnenplateau-791221/2/

You need to kill/banish Sathrovarr first in order to make the encounter finish

**Comment by Rushor** [comment]
tested with dracku.

kalecgos oks so far. felmyst zombie removed. kiljaeden crash reason are the player copies. disabled them for now.
