### ISSUE TITLE
[Raid] Eye of Eternity

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#3423]
**Links:**
https://www.wowhead.com/the-eye-of-eternity
**What is happening:**
The problem is in last phase when you need to defeat (https://www.wowhead.com/npc=28859/malygos) while you are on a dragon. The problem is you start with 0 energy and you cannot attack him at all https://imgur.com/OLoEn25 --- https://www.wowhead.com/npc=30161/wyrmrest-skytalon
**What should happen:**
Dragons should start with 100 energy then regenerating it after using skills

**Comment by Rushor** [comment]
comined. generic issue https://github.com/WoWManiaUK/Blackwing-Lair/issues/3238
