### ISSUE TITLE
[Raid] Serpentshrine Cavern

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#3424]
**Links:**
https://www.wowhead.com/serpentshrine-cavern
**What is happening:**
The problem is at last boss (https://www.wowhead.com/npc=21212/lady-vashj) in phase 2 the Tained Elementals dont drop the key (https://www.wowhead.com/npc=22009/tainted-elemental)
**What should happen:**
In phase 2, she will become invincible. Enchanted Elementals constantly and walk towards Vashj - you must kill these or they give Vashj a permanent size and damage increase, which stacks to problematic levels even at level 85. You will not be able to kill them all unless you have superior AoE abilities, so just focus on getting as many down as possible so she does not have an unmanageable amount of stacks. We usually end up with about 50 or so (99 is the max).
Vashj is invincible in this phase until you disable her shield generators using four Tainted Cores looted from Tainted Elementals. These elementals spawn at the edge of the arena and do not climb the stairs, so they are difficult to see. Scan the horizon for the toxic projectiles they lob onto the main stage. They despawn quickly, so you must be fast, and be sure to have loot on free for all.
Two adds will occasionally spawn throughout this phase. The problematic ones, Coilfang Striders constantly cast a very disrupting Point Blank AoE Fear (like a priest's psychic scream except faster than usual) and must be rooted, kited, or killed (preferably at range). It will help to have ranged dps for both the Enchanted Elementals and the Striders. It is absolutely crucial that you progress to phase 3 (by using the 4th core) when no adds are up or about to spawn, as the AoE fear will easily wipe you against an overpowered Vashj in phase 3.

**Comment by Rushor** [comment]
the items drop from http://cata.cavernoftime.com/npc=22009 core only. there are two kinds of elementals. one that move and the other that stay on the ground. those who don't move drop the items.

anyway fixed the interaction with the regenerators aswell now.

![I](https://i.imgur.com/SrS8aNb.jpg)
