### ISSUE TITLE
Can enter dungeons while boss encounter is running.

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3425]
**Links:**

from WoWHead or our Armory

**What is happening:**

Players are able to enter Dungeons while the others fight the boss.

Cant test it with raids but this would make every raid esay by just running in again xD so its rlly gamebreaking

**What should happen:**

they shouldnt be able to enter the dungeon while a boss gets fighted

**Comment by Keader** [comment]
Fixed;
