### ISSUE TITLE
[Dungeon/NPC] Ley-Guardian Eregos -The Oculus-

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#3426]
**Links:**
https://www.wowhead.com/the-oculus
https://www.wowhead.com/npc=27656/ley-guardian-eregos
**What is happening:**
After fighting him a while the boss will dissaper and you cannot complete the dungeon
https://imgur.com/9t35bVM
**What should happen:**
Well he should not dissaper

**Comment by Rushor** [comment]
this happens because of npc_ruby_emerald_amber_drake. once they are summoned the boss despawn. will remove that.

btw he has that planar shift abaility as intended
