### ISSUE TITLE
[Dungeon/NPC] Ancient Stone Keeper -Uldaman-

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#3427]
**Links:**
https://classic.wowhead.com/uldaman
https://classic.wowhead.com/npc=7206/ancient-stone-keeper
**What is happening:**
The Stone Keepers are not attackble so you cant finish the dungeon.
https://imgur.com/UPsYJB2
https://imgur.com/JYtXwYY
**What should happen:**
After killing all Stone Keepers a boss should apper and after killing it the doors should open

**Comment by Rushor** [comment]
this create http://cata.cavernoftime.com/npc=4857 not ancient stone keeper

**Comment by Rushor** [comment]
flags are wrong. i'm on it

**Comment by kDracku** [comment]
sorry , i think this one https://classic.wowhead.com/npc=4857/stone-keeper

**Comment by Rushor** [comment]
first step 

![I](https://i.imgur.com/ZcCdKdE.jpg)

the end boss is an other room. but also fixed 

![I](https://i.imgur.com/p7e2WCr.jpg)
