### ISSUE TITLE
[Dungeon/NPC] Naralex -Wailing Caverns-

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#3428]
**Links:**
https://classic.wowhead.com/npc=3679/naralex
https://classic.wowhead.com/wailing-caverns
**What is happening:**
You cant start the event https://imgur.com/4Yn2HMO
**What should happen:**
After starting the event serveral waves of mobs should spawn and after a boss will apper

**Comment by Rushor** [comment]
if ((instance->GetBossState(DATA_LORD_COBRAHN) == DONE) && (instance->GetBossState(DATA_LORD_PYTHAS) == DONE) &&
                (instance->GetBossState(DATA_LADY_ANACONDRA) == DONE) && (instance->GetBossState(DATA_LORD_SERPENTIS) == DONE))

all those bosses must be killed first in order to get Muyoh start the event

**Comment by kDracku** [comment]
I killed all the bosses , talked with the NPC near the etrance and when we reach Naralex the event dosent start

**Comment by Rushor** [comment]
yeah i see now too. update script is fucked and again 12 years old haha

**Comment by Rushor** [comment]
fixed with next update:

![I](https://i.imgur.com/nGm5am6.jpg)
![I](https://i.imgur.com/jg8540S.jpg)
![I](https://i.imgur.com/QFgN2UZ.png)
![I](https://i.imgur.com/GJ74LGy.png)
![I](https://i.imgur.com/WRrw4dw.png)
![I](https://i.imgur.com/i60mmib.png)
