### ISSUE TITLE
Wrong Bonuses with haste buffs ( Mind Quickening )

### ISSUE THREAD

**Issue by APTX4869s** [WoWManiaUK/Blackwing-Lair#3429]
![Mind Quickening](https://user-images.githubusercontent.com/55243287/65691075-4ab09400-e081-11e9-9d2a-50a29bb5a76e.png)
![Judgments of the pure](https://user-images.githubusercontent.com/55243287/65691162-6ddb4380-e081-11e9-9ccf-be09d115c70c.png)

I tested haste buff and figured out that it doesn't give 5% haste, it gives more.
I used Judgement with talent " Judgments of the Pure " which made my haste 26.08% ( with no extra buffs )
![Judgment's haste](https://user-images.githubusercontent.com/55243287/65691354-bbf04700-e081-11e9-8bd5-c9fb2ed03ad2.png)

After that I tested it with Shadow Priest ( Mind Quickening buff ) it boosted my haste to 32.38% ( with only Judgment buff )
![Judgment + shadow haste](https://user-images.githubusercontent.com/55243287/65691526-0b367780-e082-11e9-8a08-e5901d38813c.png)

it increased 6.3% haste

32.38 - 26.08 =6.3%

I only tested with Shadow priest so I don't know if it's the same with Balance druid and Shaman's totem.

**What is happening:**
the more haste you have the more benefit you will get from haste buffs

**What should happen:**

it should only increase 5% of your haste, doesn't matter how much haste you have.

**Comment by Rushor** [comment]
some new spell stuff for you @Keader <3

**Comment by APTX4869s** [comment]
I've noticed also talent" Judgment of the Pure" gives more haste
without gear holy paladin my minimum haste was 3% ( 3% from talent Speed of Light )
I used Judgment my haste went to 12.27%
it gave me 9.27% ( it should give only 9% )
I wanted to open a new report about it and also about stacking haste buff ( shadow priest and shaman totem get stacked ) but it seems they are all related to each other ( haste calculations seem to be wrong )
should I open a new report about them? or they are linked?

**Comment by Warpten** [comment]
Haste percentage auras stack multiplicatively. Maths.

**Comment by Keader** [comment]
Is exactly what warpten said.
In your first case: 1.2608 (26.08% ) * 1.05 (5%) = 1.3238 (32.38%)
No bug here :)
