### ISSUE TITLE
Stacking haste buffs ( Mind Quickening + Wrath of Air Totem )

### ISSUE THREAD

**Issue by APTX4869s** [WoWManiaUK/Blackwing-Lair#3430]
![Wrath of Air Totem](https://user-images.githubusercontent.com/55243287/65705115-d7b31780-e098-11e9-95a2-b2fd4d7ac241.png)

![Mind Quickening](https://user-images.githubusercontent.com/55243287/65705124-dda8f880-e098-11e9-80cc-dce94b66c547.png)

my normal haste is 15.67% ( without any buff )
![haste with no buffs](https://user-images.githubusercontent.com/55243287/65705164-f1545f00-e098-11e9-85a2-20b0f1b777f3.png)

with Shadow priest ( Mind Quickening ) 21.45% ( shadow priest's buff only )
![with shadow priest only](https://user-images.githubusercontent.com/55243287/65705339-4db77e80-e099-11e9-853d-3016e1715dff.png)
with both Shadow priest ( Mind Quickening ) and Shaman's totem ( Wrath of Air ) 27.52%
![Shadow priest and totem haste](https://user-images.githubusercontent.com/55243287/65705454-89eadf00-e099-11e9-98f5-3d74660cc4c1.png)

**What is happening:**
both shaman's totem ( Wrath of Air ) and Shadow priest's buff ( Mind Quickening ) stack which you get additional 5% haste

**What should happen:**
you should get only 5% haste and the haste buff shouldn't stack.

**Comment by APTX4869s** [comment]
![Moonkin Aura](https://user-images.githubusercontent.com/55243287/65707014-b0f6e000-e09c-11e9-92b9-13c1bf91b3d9.png)

tested it with Moonkin Aura too it gave another 5% haste ( my haste with all 3 haste buffs 33.90% with no extra buffs )
![Boomkin buff](https://user-images.githubusercontent.com/55243287/65707027-b9e7b180-e09c-11e9-8535-e5a77bece257.png)

**Comment by Kitzunu** [comment]
```sql
SET @group := 
DELETE FROM `spell_group` WHERE `id` = @group;
INSERT INTO `spell_group` (`id`, `spell_id`) VALUES
(@group, 2895),
(@group, 49868);
DELETE FROM `spell_group_stack_rules` WHERE `group_id` = @group;
INSERT INTO `spell_group_stack_rules` (`group_id`, `stack_rule`) VALUE
(@group, 1);
```

**Comment by Rushor** [comment]
thanks you @Kitzunu !

**Comment by Rushor** [comment]
okay applied on dev pls test :>

**Comment by Keader** [comment]
@Rushor you forgot to put tag.

**Comment by Rushor** [comment]
oh sorry

**Comment by Randomplayerx** [comment]
Not only haste but also other buffs should stack.

Also for example if you put Mark of the wild and than put Blessing of the Kings it cancel the mark.

One more thing in different servers it show only 1 buff each time.

For example if you have Paladin buff Might than add Blood dk 5o group with his Might talent it disappear same for Shaman enhancement if paladin buff them.

This the list:
https://www.wowhead.com/forums&topic=169946

**Comment by Keader** [comment]
@Randomplayerx need open 1 issue per problem.
