### ISSUE TITLE
Shaman -  [Rolling Thunder] - ID : 88764

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3431]
**Links:**
https://wow.gamepedia.com/Rolling_Thunder
from WoWHead or our Armory

**What is happening:**

Spell is not giving correct amount of mana. Elemental should never get oom with spamming chain lightning

**What should happen:**

**Comment by kDracku** [comment]
You wont get oom if there are more than 5-6 mobs to spam chain lightning since itsa 60% chance to recover 2% of mana. The probem comes at spammning it at 2 mobs

**Comment by Keader** [comment]
I dont unerstand what is the issue here.
Amount returned is correct, what is wrong?

**Comment by Slydee23** [comment]
y im really sure the amount is not correct. cause i also get oom on 5 targets with glyph etc and enough crit.

**Comment by xenosDow** [comment]
Did some testing, the problem isnt that it gives the wrong mana return value ( it does ), the problem is that the mastery skill Elemental overload doesnt really work With Elemental Focus and Rolling Thunder, it doesnt trigger any of them

**Comment by Slydee23** [comment]
rlly need a fix here cant raid with that problem for sure
