### ISSUE TITLE
[quest] Anything but water

### ISSUE THREAD

**Issue by Wojtek92** [WoWManiaUK/Blackwing-Lair#3433]
**Links:**
https://www.wowhead.com/quest=27647/anything-but-water
from WoWHead or our Armory
https://www.wowhead.com/quest=27647/anything-but-water
**What is happening:**
there is no barrel 

**What should happen:**
there should be ale - to pick it up

**Comment by Rushor** [comment]
added, and questender added

![I](https://i.imgur.com/N9em7Pl.jpg)
