### ISSUE TITLE
[quest] Shining through the dark

### ISSUE THREAD

**Issue by Wojtek92** [WoWManiaUK/Blackwing-Lair#3434]
**Links:**
https://www.wowhead.com/quest=28175/shining-through-the-dark
from WoWHead or our Armory
https://www.wowhead.com/quest=28175/shining-through-the-dark
**What is happening:**
there is no possibility to use q item in proper place

**What should happen:**
there should be possibility to use it

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/Nk69Hv7.jpg)
