### ISSUE TITLE
[quest] Rescue at glopgut's hollow

### ISSUE THREAD

**Issue by Wojtek92** [WoWManiaUK/Blackwing-Lair#3435]
**Links:**
https://www.wowhead.com/quest=28377/rescue-at-glopguts-hollow
from WoWHead or our Armory
https://www.wowhead.com/quest=28377/rescue-at-glopguts-hollow
**What is happening:**

there is no Collin there

**What should happen:**

there should be a npc to complete q

**Comment by Rushor** [comment]
added

![I](https://i.imgur.com/wTcUx5Z.jpg)

**Comment by Echinaceax** [comment]
https://www.wowhead.com/npc=48472/colin-thundermar
