### ISSUE TITLE
[quest] Find Fanny

### ISSUE THREAD

**Issue by Wojtek92** [WoWManiaUK/Blackwing-Lair#3436]
**Links:**
https://www.wowhead.com/quest=28378/find-fanny
from WoWHead or our Armory
https://www.wowhead.com/quest=28378/find-fanny
**What is happening:**

there is no Fanny

**What should happen:**
there should be a npc to complete q

**Comment by Kitzunu** [comment]
duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/291
