### ISSUE TITLE
[quest] Something brewed

### ISSUE THREAD

**Issue by Wojtek92** [WoWManiaUK/Blackwing-Lair#3437]
**Links:**
https://www.wowhead.com/quest=28409/something-brewed
from WoWHead or our Armory
https://www.wowhead.com/quest=28409/something-brewed
**What is happening:**
there should be an event performed with caravan 
nothing is happening

**What should happen:**

there should be an event performed with caravan

**Comment by Kitzunu** [comment]
duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/287

**Comment by Rushor** [comment]
thanks kitz :> love you

**Comment by Kitzunu** [comment]
@Rushor ♥️
