### ISSUE TITLE
[quest] Sifting Through The Wreckage

### ISSUE THREAD

**Issue by Wojtek92** [WoWManiaUK/Blackwing-Lair#3438]
**Links:**
https://www.wowhead.com/quest=27642/sifting-through-the-wreckage
from WoWHead or our Armory
https://www.wowhead.com/quest=27642/sifting-through-the-wreckage
**What is happening:**
there is no q credit form finding victims

**What should happen:**
there should be q credit

**Comment by Rushor** [comment]
fixed with next update

![I](https://i.imgur.com/qf1pSlA.jpg)
