### ISSUE TITLE
[quest] Bird Down! Bird Down!

### ISSUE THREAD

**Issue by Wojtek92** [WoWManiaUK/Blackwing-Lair#3439]
**Links:**
https://www.wowhead.com/quest=27514/bird-down-bird-down
from WoWHead or our Armory
https://www.wowhead.com/quest=27514/bird-down-bird-down
**What is happening:**
there is no NPC

**What should happen:**
there should be an npc to complete q and take another one

**Comment by Rushor** [comment]
fixed with next update

![I](https://i.imgur.com/JoX9egY.jpg)
