### ISSUE TITLE
[quest] Victors' Point

### ISSUE THREAD

**Issue by Wojtek92** [WoWManiaUK/Blackwing-Lair#3440]
**Links:**
https://www.wowhead.com/quest=28248/victors-point
from WoWHead or our Armory
https://www.wowhead.com/quest=28248/victors-point
**What is happening:**
there is no victor

**What should happen:**

there should be an npc

**Comment by Rushor** [comment]
availablable in phase 169 now.

![I](https://i.imgur.com/OJdGALF.jpg)
