### ISSUE TITLE
vip xp 

### ISSUE THREAD

**Issue by mattm72980** [WoWManiaUK/Blackwing-Lair#3442]
**Links:**

from WoWHead or our Armory

xp rates after .vip xp 6 only going to 3x 

![WoWScrnShot_092719_092024](https://user-images.githubusercontent.com/55311798/65785229-c1dd3b00-e108-11e9-8496-bd46ccc53487.jpg)
![WoWScrnShot_092719_092033](https://user-images.githubusercontent.com/55311798/65785235-c73a8580-e108-11e9-9f31-2d72356dbdbf.jpg)

**What should happen:**

should recieve 6x (16,200xp for that quest)

**Comment by Rushor** [comment]
if (m_hasVip)
    SetIndividualXpRate(xp_rate);

works fine so far. make sure you have .vip xp 6 retyped on char change

**Comment by Echinaceax** [comment]
New info regarding this issue @Rushor confirmed from a different player ingame to the GM 

Platers quest was 5900 and vip give only x3 which they recieved 18585 and not 35400 
player has 1 loom and no raf (info from GM) 

Has something regressed maybe ?

**Comment by Echinaceax** [comment]
Ok new update on this issue 
**how it works** explained 

1. server is x2 default 
2. At x1 is half the quest reward ofc

so xp 6 is set right acording to checks
