### ISSUE TITLE
Portal in Cenarion Hold, Silithus

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Blackwing-Lair#3443]
**Links:**
https://www.wowhead.com/quest=28867/nethergarde-needs-you

**What is happening:**
The Alliance portal in Cenarion Hold, Silithus, used in the quest Nethergarde Needs You, transports the player into the middle of the Horde stronghold Dreadmaul Hold, rather than Nethergarde Keep.
This is instant death for player.

**What should happen:**
The portal should transport to the Alliance stronghold of Nethergarde Keep instead.

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/r1GNqZQ.jpg)
