### ISSUE TITLE
[GO] Stratholme Endboss

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Blackwing-Lair#3444]
The Gate to the endboss does not open.

**Comment by kDracku** [comment]
The event at last boss dosent start 
https://imgur.com/NbkgC10

**Comment by Rushor** [comment]
fixed

door opens and boss spawns

![I](https://i.imgur.com/8hlGyb0.jpg)
![I](https://i.imgur.com/SZCMlXo.png)
