### ISSUE TITLE
[NPC] Harrison Jones - issue 3 - ( missing) Uldum

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3445]
**Links:**

https://www.wowhead.com/npc=48082/harrison-jones

**What is happening:**
- Missing
- Cant turn in quest

**What should happen:**
NPC should be in location to hand back https://www.wowhead.com/quest=27905/tailgunner

**Comment by Rushor** [comment]
added

![I](https://i.imgur.com/KYE7gc5.jpg)
