### ISSUE TITLE
[Object/Dungeon] Door Blackrock Spire

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#3447]
**Links:**
https://imgur.com/e9Cxqdy
**What is happening:**
After you clear stadium 2 times (and thats really strange too) the door to Blackwing Lair or progressing into dungeon is closed
**What should happen:**
After you clear the stadium the door should be open

**Comment by Rushor** [comment]
done

https://i.imgur.com/LOt16dy.jpg
