### ISSUE TITLE
[Spell] Runic Empowerment - Death Knight

### ISSUE THREAD

**Issue by Venom64bit** [WoWManiaUK/Blackwing-Lair#3449]
**Links:**

Spell: https://cata-twinhead.twinstar.cz/?spell=81229

The bug is hardly visible, but the screen clearly shows it. In the case of DK Blood (RuneStrike), DK Frost (Frost Strike) and DK Unholy (Death Coil) you get the Death runes (visibly too many because they should only give 1 but it seems to give 4 as well), but they are not usable.

In the first screen I used the spec blood and in rotation the rune strike:

![Test DK BUG](https://user-images.githubusercontent.com/16047071/65840198-2b7e6480-e316-11e9-8dda-9787bfa7f9e1.jpg)

In the second screen I always used the spec blood and in rotation the death coil:
![Test DK Bug 2](https://user-images.githubusercontent.com/16047071/65840202-3638f980-e316-11e9-89d7-3efcea9299a0.jpg)

In both cases I had the runes death (yellow square) but I didn't leave the Death Strike (blue square and purple runes) and it signaled me that I didn't have enough runes (green square).

I talked to different DKs and the bug seems to be present mainly in the Blood, in Frost it is more difficult to meet a dead time for the passive Blood of the North and in the Unholy (when the talent Runic Corruption is not present) a dead time does not often occur for passive Reaping.

**Comment by Slydee23** [comment]
High Prio pls and add it to important class fixxes

**Comment by kDracku** [comment]
Happend to me , with all runes up you cant use any abillities

**Comment by Keader** [comment]
try now please. (in ptr)

**Comment by Randomplayerx** [comment]
Unholy spec have Runic Corruption which replace Runic Empowered system.

**Comment by Bloodborne93** [comment]
@Keader i tested it in ptr, it works well, but some times refresh two runes instead of one.

**Comment by Keader** [comment]
I need a reproduce case

**Comment by kDracku** [comment]
Ok found the problem for blood dks , if you have all runes on cooldown then use rune strike all runes gettin reset and you cant use them
