### ISSUE TITLE
[Quest] Escape from Silverbrook - ID 12308 Grizzly Hills

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Blackwing-Lair#3450]
**Links:**
https://www.wowhead.com/quest=12308/escape-from-silverbrook

**What is happening:**
Once you reach Silverpine, you exit the vehicle (horse!) automatically, but the completion mark is not given.

**What should happen:**
Once you reach Silverpine, you exit the vehicle (horse!) automatically, and the completion mark is given.

**Comment by Rushor** [comment]
fixed with next update. you need to redo the quest then

![I](https://i.imgur.com/7aWt5Mf.jpg)
