### ISSUE TITLE
[Spell] Mage portals / Teleports (wrong lvl requirement) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3456]
**Links:**
https://wow.gamepedia.com/Portal_(spell)
https://cata-twinhead.twinstar.cz/?spell=10059
https://cata-twinhead.twinstar.cz/?spell=11416

https://us.battle.net/forums/en/wow/topic/2580698723

infact all major cities are not meant 85 as seen in SS.
there are stages, Tol Barad is 85 only as far as i can see

**What is happening:**
- Wrong lvl requirements

![mage portals missing](https://user-images.githubusercontent.com/39439201/65955198-e5292280-e447-11e9-82b9-78ef47fa48d1.jpg)

no changes in patch notes only added Tol Barad

![patchnotes mage](https://user-images.githubusercontent.com/39439201/65955476-82845680-e448-11e9-9e8a-e1a6237da984.jpg)

**What should happen:**
- Main cities are given at 24 / 42
i will add all correct lvls soon if you need @Keader ?

Reported by GM, tested and confirmed by me in dev

**Comment by Kitzunu** [comment]
UPDATE `npc_trainer` SET `ReqLevel` = 42 WHERE `SpellID` IN (32266, 10059, 11416, 11419);

**Comment by Rushor** [comment]
affected creatures:

2485,
2489,
2492,
4165,
5957,
5958,
16654,
16755,
19340,
20791,
27703,
27705,
29156,
45139,
47253);

**Comment by Rushor** [comment]
all spells like 3565 need also be fixed

**Comment by Rushor** [comment]
alliance side seem to be broken only

fixed for averything

![I](https://i.imgur.com/DOScfNh.jpg)
![I](https://i.imgur.com/ZtP845s.jpg)
![I](https://i.imgur.com/LZpyblH.jpg)

**Comment by Echinaceax** [comment]
Thank you @Kitzunu and @Rushor :)
