### ISSUE TITLE
[spell/warlock] Immolate/Unstable Affliction

### ISSUE THREAD

**Issue by Steffiden** [WoWManiaUK/Blackwing-Lair#3457]
**What is happening:**

You are able to cast both immolate (SpellID: 348)  and unstable affliction (SpellID: 30108) on one target (see image).

**What should happen:**

Only one unstable affliction or immolate per warlock should be able to be active on any one target.

![UA - Immolate](https://user-images.githubusercontent.com/55976671/65957844-389e6f00-e44e-11e9-9074-8bfd96b4ba0a.PNG)

**Comment by Keader** [comment]
cool
Fixed.
