### ISSUE TITLE
[General][Rogue] Few bugs.

### ISSUE THREAD

**Issue by Randomplayerx** [WoWManiaUK/Blackwing-Lair#3458]
Ok let's start with General I am at Cataclysm zone [Mount Hyjal] atm.
and there is alot of problems with Phrasing like in Mount Hyjal.
quest like "From the Mouth of Madness" the herbs cannot be obtained.
first I done 2/3 herbs, than one herb had Phrasing issue, I re-take the quest
Now none of them are pickable.

1. There is huge problem with NPC spawns in Hyjal.
"Twillight Predators" are like doesn't disappear when they're reaching their final path.
And you have like 70 of them all over the place.
"The Manipulator" has 3 spawned clones in it poisiton, which killing me in 4 seconds.
same goes for "Scalding Rock Elemental" which I calculated like 50 of them in starter zone.
"Twillight Flamecaller" same issue, seems like doubled the amount of NPC the zone should have.
They're not moving and I got attacked by 5 of them together, which their Fireball hits for 6k on 15k health.
I would say the damage calculators for NPCs are bit incorrect aswell, on other servers the NPCs doesn't drop you half your HP in one ability.

Now let's talk about Rogue.

2. Blade Flurry sometimes doesn't attack the nearest enemy [If attacking 2-3 NPCs at once]
probably radius issue or heights issue.

Also the ability doesn't seems work with "Killing Spree" ability.

Also Blade Flurry [according to other servers] should first prioritize lowest health NPCs.
Let's say I'm attacking NPC and cleaving 2x NPC - one with 80% health and one with 100% health.
the Blade Flurry suppost to select 80% health.
Right now it's like "jumping" between the other NPCs it cleaves.

3. https://www.google.co.il/search?safe=active&source=hp&ei=pkeTXf7lIuGEmwWB5rrABQ&q=a+more+powerful+spell+is+already+active&oq=a+more+powerful+spell+is&gs_l=psy-ab.3.0.0j0i22i30.216.2580..3284...0.0..0.185.3115.0j24......0....1..gws-wiz.......0i131j0i22i10i30.lKr51X6Oti8

Other issue is with Recuperate / Slice and Dice but I believe that issue is happen on other classes aswell, since I'm playing rogue, I can't check on other Classes.

But If there is stronger buff applied, you can't put a weaker one.
If I have 5 combo points Recuperate with 22 seconds remained.
I can't put new Recuperate with less than 22 seconds It should gives me red titles in middle of the screen.
Same goes for Slice and Dice.
And there more bunch of mechanics for other classes that work that same way.

4. And last for now is Vanish.
Vanishing against NPCs doesn't work properly. It keeps the Aggro on you and doesn't break-casts.

**Comment by Rushor** [comment]
hey, pls post the issues in seperate one - it is better for us. The hyjal issues were already reported. we will fix that next week. 

and pls search for the spellissues here https://github.com/WoWManiaUK/Blackwing-Lair/search?q=rogue&type=Issues before reporting. thank you

pls open up seperate issues for each bug - thanks!

**Comment by Echinaceax** [comment]
@Rushor done the npc in single reports now
