### ISSUE TITLE
[Spell] curse of tongues - ID 199890 (Warlock)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#346]
Spell - https://www.wowhead.com/search?q=curse+of+tongues

- doesn't increase cast time by 30%
- Looking at wowhead it says that its a npc ability / pvp talent 

Spell -  https://www.wowhead.com/spell=199890/curse-of-tongues

![curse of tonques](https://user-images.githubusercontent.com/39439201/50632297-b11be200-0f47-11e9-9fa3-f9095ba5caa7.jpg)

**Comment by sarahkay88** [comment]
Can you only cast this on your self. Just wondering if it got confused with th one in wolk. The one in wolk reduces cast time and warlocks often use it on the sindy fight for when she is about to drag the raid it.. Try using it on a casting mob to check? There's two cure of tounges has far has I read. One to speed up casting and one to reduce it.

**Comment by Echinaceax** [comment]
ah thanks , yes i'll test that :)

**Comment by Dranah** [comment]
The purpose of Curse of Tongues is to make the enemy less effective at casting. This only affects spells with a cast time.
Increases cast time = reduces casting speed, these terms are synonyms, a longer cast time means slower cast speed.
Is this not working as intended or just confusion by wording?

**Comment by Echinaceax** [comment]
> Is this not working as intended or just confusion by wording?

- I tested on casters just now in Hinterlands and yes Slowed their cast and / failed cast etc...
- Think the report can be closed now thanks :)

**Comment by Keader** [comment]
Tested and working.
