### ISSUE TITLE
[Quest] This Can Only Mean One Thing...(missing) - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3464]
**Links:**
https://www.wowhead.com/quest=28732/this-can-only-mean-one-thing
https://www.wowhead.com/npc=49444/finkle-einhorn

**What is happening:**
- Quest missing from NPC (for questorder report)

**What should happen:**
Quest should be here

note: seems like you go dungeon 
https://www.youtube.com/watch?v=-dAZh3fyWHI

and cant pick up next https://www.wowhead.com/quest=28735/to-the-chamber-of-incineration

**Comment by Rushor** [comment]
the quest is actually there.

credit will be given now upon clicking on the mole machine next to him.

As the objective says: Take Finkle's Mole Machine to Blackrock Mountain. 

![I](https://i.imgur.com/eI85vmr.jpg)
