### ISSUE TITLE
[NPC] Twilight Proveditor (doubles) - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3465]
**Links:**

https://www.wowhead.com/npc=39436/twilight-proveditor

**What is happening:**
- nps inside each other

**What should happen:**
- Need spacing

**Comment by Randomplayerx** [comment]
Everything in Mount Hyjal is broken.
Every NPC is like double spawned.
Phrasing not working and quest lines too, I done 89 quests out of 270 of hyjal [according to Zygor]. There is alot things to fix.

thanks for the report.

**Comment by Rushor** [comment]
yes that whole zone is my next todo.

**Comment by Rushor** [comment]
https://www.youtube.com/watch?v=3DWBiHIyPaU

that's how it should work

**Comment by Rushor** [comment]
okay so the creatures must move around along a path containing 

hostile: 39438, 39436(Leader), 3 * 39431 (slaves)

even on retail this quest was tricky.

to add 39436 on reset - movefollow 39438
39436 on death - move random to 39431  and despawn

39436 wp final reached - despawn self + all others in range
