### ISSUE TITLE
[Spell] Atonement healing is off

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#3466]
ID 81749
Atonement doesn't seem to scale properly with the base value of the Smite and Holy Fire damage.

**How it works atm:**
Testing with no gear,buffs or talents that would affect its healing, atonement isn't healing for 100% of the damage dealt, but around 110% for smite, 106,6% for Holy Fire, and 252% for Holy Fire (DOT).
Cutting in half when it affects the priest, the spell heals for 55% of smite, 53% of HF, and 125% of HF (dot).
As the caster gains spell power, the differences reduce, so it's safe to assume it is the base damage that scales wrongly.

This worked as intended when Keader fixed it and I tested a few months ago, something must have broken it in the process.

![WoWScrnShot_100119_220135](https://user-images.githubusercontent.com/31132743/65996222-4f1ce880-e497-11e9-941c-ed1735c5a942.jpg)

**How it should work:** Atonement should heal for 100% of damage dealt (50% if it affects the priest) and that healing then scales further with talents and effects.

**Comment by Randomplayerx** [comment]
Scales with Grace too.
