### ISSUE TITLE
[Quest][Vashjir] Captain Taylor

### ISSUE THREAD

**Issue by Randomplayerx** [WoWManiaUK/Blackwing-Lair#3467]
https://www.wowhead.com/quest=25545/to-arms

NPC Questline is broken.

Buy Us Some Time - work
Traveling on Our Stomachs - work
To Arms! - not working
Stormwind Elite Aquatic and Land Forces - work
On Our Own Terms - not working
All or Nothing - not working

**Comment by Rushor** [comment]
yes already reported. 

https://github.com/WoWManiaUK/Blackwing-Lair/issues/3063
https://github.com/WoWManiaUK/Blackwing-Lair/issues/3352

pls check the isue on github before reporting :) this saves us some time. thanks

**Comment by Deathghat** [comment]
Still broken 9/21/2021

**Comment by Echinaceax** [comment]
We know @Deathghat 
Thats why Rushor tagged it above 
#3063
#3352
