### ISSUE TITLE
[Quest][Vashjir] Moanah Stormhoof

### ISSUE THREAD

**Issue by Randomplayerx** [WoWManiaUK/Blackwing-Lair#3468]
https://www.wowhead.com/quest=25477/better-late-than-dead

Questline not working.

1. Better Late Than Dead - not working
2. The Abyssal Ride - Can't do 1st to open this one

**Comment by Rushor** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/3117

**Comment by Randomplayerx** [comment]
@Rushor I don't want to open new Issue but you can't cancel Stealth[buff] by right clicking it on Buff List [Top Right] near Mini map.
