### ISSUE TITLE
[NPC] Spirit of Lo'Gosh - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3469]
**Links:**

https://www.wowhead.com/npc=39622/spirit-of-logosh

**What is happening:**
- Gave me the quest https://www.wowhead.com/quest=25623/into-the-maw

**What should happen:**
From what i can see the quest shouldnt be given by this wolf.
 is given by https://www.wowhead.com/npc=39433/ian-duran

**Comment by Rushor** [comment]
I just completed Corruption of Lycanthoth and was riding back on Lo'Gosh when someone knocked at my door. I came back just in time to see that Lo'Gosh had a quest to offer, before he despawned.

that is intended they say in wowhead comments https://www.wowhead.com/npc=39622/spirit-of-logosh#comments:id=1387275
