### ISSUE TITLE
[NPC/Raid] Trial of The Grand Crusade - Boss Icehowl

### ISSUE THREAD

**Issue by Bloodborne93** [WoWManiaUK/Blackwing-Lair#3470]
**Links:**
https://www.wowhead.com/npc=34797/icehowl

**What is happening:**
After he doing Massive Crash, he jumps two times, then you can't attack him, only who was already hitting him with melee attacks, you can't use abilities or other spells.
![Icehowl bug](https://user-images.githubusercontent.com/52720024/66004333-cf981500-e4a8-11e9-9ec9-5d07def75976.jpg)

**What should happen:**
We can continue to attack him during the fight.

**Comment by Rushor** [comment]
wotlk scripts added for him - thx to keader
