### ISSUE TITLE
[NPC] Choluna <Druid of the Talon> - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3471]
**Links:**

https://www.wowhead.com/npc=41005/choluna

![needs moving](https://user-images.githubusercontent.com/39439201/66006324-9662a380-e4ae-11e9-92a4-7409fd260b9c.jpg)

**What is happening:**
- She meant to be sitting
 
![sitting](https://user-images.githubusercontent.com/39439201/66007227-d4ad9200-e4b1-11e9-81bf-01da1dd52d27.jpg)

**Comment by Rushor** [comment]
done

![I](https://i.imgur.com/UCZPp8T.jpg)
