### ISSUE TITLE
[Profession] Archaeology - Solved statistic (Bloodelf male)

### ISSUE THREAD

**Issue by Nirvanum** [WoWManiaUK/Blackwing-Lair#3473]
Speaking with the members of my guild, we have verified that the appearance of rare / epic pieces, for some races, takes place every n attempts.
For example with the Trolls.
There are 2 rare pieces and one epic piece.
We noticed that the first rare piece appears around the 20th attempt and the second at 40 °. In fact, continuing, almost all have found the sword (the epic piece) around the 60th.
(I was able to see for myself. I was at a friend's house and he released the Sword at exactly 60!)
I also found the first piece at 20 ° and the second at 40 ° (approximately).
I managed to solve 203 pieces and the sword hasn't come out yet; this means around 160 common consecutive pieces.
With the Dwarves the subject is the same, the difference is that the rare pieces are 3 so the epic piece reaches around 80 ° (in fact with the dwarves we find a little more than 20 between one and the other).
With the Dwarves I came to 171. About 100 consecutive common pieces.

Why am I reporting the problem as Bloodelf male?
Because, since there is a problem with fishing (already reported) that I have skilled thanks to the Potion of Illusion (really !!) and that now I find myself with 693/715 (at 521 the next increase was +172!) , I think there may also be a problem with Archeology.
Or at least I hope so, otherwise it means I'm very unlucky.
But really so much!!

**Comment by Rushor** [comment]
moved to https://github.com/WoWManiaUK/Blackwing-Lair/issues/3012

**Comment by Nirvanum** [comment]
It must be argued before it is closed
