### ISSUE TITLE
[NPC] Sethria (missing) - Mount Hyjal 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3474]
**Links:**
https://www.wowhead.com/npc=41255/sethria

![not here](https://user-images.githubusercontent.com/39439201/66008203-aa5dd380-e4b5-11e9-9e0b-f8689d786221.jpg)

**What is happening:**
- nps missing

**What should happen:**
should be at the location for quest https://www.wowhead.com/quest=25776/sethrias-demise

**Comment by Rushor** [comment]
spawns for the whole area are missing

**Comment by Rushor** [comment]
added

![I](https://i.imgur.com/PF99E4P.jpg)
![I](https://i.imgur.com/oyUskAs.jpg)
