### ISSUE TITLE
[NPC] An Ancient Reborn - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3475]
**Links:**

https://www.wowhead.com/quest=25807/an-ancient-reborn

![no egg](https://user-images.githubusercontent.com/39439201/66008688-c793a180-e4b7-11e9-828c-b3e043d79fd2.jpg)

**What is happening:**
- no Aviana's Egg

**What should happen:**
_Use the Herald's Incense before Aviana's Egg at the Shrine of Aviana._

**Comment by Rushor** [comment]
okay egg is visible now as soon as you accept quest 25807. once 25807 is completed the egg will be invisible and Aviana will be visible. 

only testable with gm off :)

![I](https://i.imgur.com/GHPx5dO.jpg)
![I](https://i.imgur.com/oDu7ENs.jpg)
