### ISSUE TITLE
Thorns [Druid]

### ISSUE THREAD

**Issue by Javalapa** [WoWManiaUK/Blackwing-Lair#3477]
**What is happening:**

When casting Thorns, the buff does not apply to the target at all, and deals no damage.

**What should happen:**

Casting Thorns should apply the Thorns buff to the target

**Comment by Keader** [comment]
Working fine to me.

![image](https://user-images.githubusercontent.com/7120913/66272391-98768a80-e83f-11e9-958b-0374e22b7b69.png)

**Comment by Echinaceax** [comment]
@Javalapa the buff applies to self and when attacked while buff is up attacter takes damage
