### ISSUE TITLE
[NPC] Spirit healer - Scarlet Monastery - Tirisfal Glades

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#348]
- spirit healer is on the wrong side of the wall.

NPC Spirit healer - https://www.wowhead.com/npc=6491/spirit-healer.

![scarley mon healer](https://user-images.githubusercontent.com/39439201/50648663-1ab5e380-0f7c-11e9-8956-6e6eead7f7de.jpg)

![spirit healer is on the wrong side of the wall](https://user-images.githubusercontent.com/39439201/50648820-7f713e00-0f7c-11e9-90bb-6728132ea9be.jpg)

![scarlet mon](https://user-images.githubusercontent.com/39439201/50648775-5badf800-0f7c-11e9-8725-58bd00e59501.jpg)

**Comment by Echinaceax** [comment]
another spirit healer missing 
![hinterlands healer](https://user-images.githubusercontent.com/39439201/50678555-88efba00-0fff-11e9-869e-82a0361f9a46.jpg)
![no spirit healer - hinterlands](https://user-images.githubusercontent.com/39439201/50678560-8c834100-0fff-11e9-9320-0248ac697705.jpg)

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/XcnS9xh.jpg)
