### ISSUE TITLE
[NPC] Aviana - (missing) - Mount Hyjal 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3482]
**Links:**

https://www.wowhead.com/npc=41308/aviana

**What is happening:**
- NPC missing for quest back

**What should happen:**
should be at the location for quest back https://www.wowhead.com/quest=25832/return-to-aviana

**Comment by Rushor** [comment]
added

![I](https://i.imgur.com/oe59U42.jpg)
