### ISSUE TITLE
[Rogue][Combat] Bandit's Guile /w Redirect

### ISSUE THREAD

**Issue by Randomplayerx** [WoWManiaUK/Blackwing-Lair#3483]
**What is happening:**
Bandit's Guile reseting from green/yellow/red to nothing.

**What should happen:**
If redirect is used it should remain the stage you are green/yellow/red continue it to next stage.

**Comment by Kitzunu** [comment]
Any source? All I can find is that Redirect should only move Combo Points, not stacks of Bandit's Guile

**Comment by Randomplayerx** [comment]
https://youtu.be/SJfUj9UCKuU

Im on phone no battery later ill search other sources or Ill maybe record myself from Twinstar itself.

**Comment by Kitzunu** [comment]
Twinstar is another server, might not be correct. Need retail proof from cata

**Comment by Randomplayerx** [comment]
@Kitzunu It would be nice next time that If you claim it *might* not be correct, than bring a counterproof. Because I brought my source, Yeah from "Twinstar" a private server, but with good devs [damn I feel like I do promotion but I saw another issues giving links from their site] Anyway they won't fix something it's not blizzlike.

Anyway, since the our best sources we have are Videos and WoLs but even them are sometimes crap and outdated earlier patchs 4.0.1-4.2 and not 4.3.4. wowwiki, wowhead and blizzard forums are sometimes bad aswell.

Anyway the video here is from Mar 2012 which is possibility still Cata cause MoP released at Sept 2012, and also the video abilities and damage still look Cata to me.
Here we go: https://www.youtube.com/watch?v=vUjpEkLchp0
Redirect used at 0:56-0:58 the was on Yellow stage and it went to Red.
and again at 04:07-04:08

next evidence is here
https://www.mmo-champion.com/threads/1244452-Let-s-improve-Bandit-s-Guile
but as I said I don't like forums ;)

next one is here
http://www.tauri-veins.com/combat-rogue-wow-pve-dps-rotation-cooldowns-abilities#redirect

**Comment by Keader** [comment]
You know that's in spell description right?
Fixed.
