### ISSUE TITLE
[NPC] Scalding Rock Elemental ( Too many spawns) - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3484]
**Links:**
https://www.wowhead.com/npc=40229/scalding-rock-elemental

![too many](https://user-images.githubusercontent.com/39439201/66065349-79c67a00-e547-11e9-8c3a-2746f5b7bb70.jpg)

**What is happening:**
Shouldnt be this many

**What should happen:**

**Comment by Randomplayerx** [comment]
Not only them. Every NPC I saw is like x2 x3 spawned at every specific spot(s).

**Comment by Echinaceax** [comment]
we know, we need 1 report each npc ..

**Comment by Echinaceax** [comment]
@Rushor all done ..left 29 ish as started on the link
