### ISSUE TITLE
[NPC] Niden (missing) - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3485]
**Links:**

https://www.wowhead.com/npc=41507/niden

**What is happening:**
- npc missing 

**What should happen:**
for quests 
https://www.wowhead.com/quest=25881/lost-wardens
https://www.wowhead.com/quest=25886/pressing-the-advantage

**Comment by Rushor** [comment]
quests i will check aswell.

**Comment by Echinaceax** [comment]
and https://www.wowhead.com/quest=25899/breakthrough

**Comment by Rushor** [comment]
https://www.wowhead.com/quest=25881/lost-wardens

The wardens do not give you the dialog option to rescue them.
https://www.youtube.com/watch?v=zseigULCQtY

**Comment by Rushor** [comment]
creature is added to the game. will fix the quests now

**Comment by Rushor** [comment]
creature is in phase 169 now.

**Comment by Rushor** [comment]
https://i.imgur.com/8DepVBU.jpg lost-wardens fixed.

**Comment by Rushor** [comment]
follow up quests also fixed
