### ISSUE TITLE
[NPC] Twilight Recruit - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3486]
**Links:**

npc - https://www.wowhead.com/npc=39619/twilight-recruit
quest - https://www.wowhead.com/quest=25274/signed-in-blood

**What is happening:**
- the npc dont get lured 
- no dialog 

**What should happen:**
_Lure a Twilight Recruit away from the group and take his Twilight Recruitment Papers._

Quest is fine everything else is ok :)

**Comment by Rushor** [comment]
all done

https://i.imgur.com/nBD8yom.jpg
https://i.imgur.com/xrvhWXR.jpg
https://i.imgur.com/t1p87sP.jpg
