### ISSUE TITLE
[NPC] Condenna the Pitiless (missing) - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3487]
**Links:**
https://www.wowhead.com/npc=39442/condenna-the-pitiless

**What is happening:**
- Npc missing for quest back

**What should happen:**
- Should be at location for https://www.wowhead.com/quest=25276/your-new-identity

side note: shes needed for next questline
https://www.wowhead.com/quest=25224/in-bloom
https://www.wowhead.com/quest=25223/trial-by-fire
https://www.wowhead.com/quest=25291/twilight-training

**Comment by Rushor** [comment]
added https://i.imgur.com/6I25QrL.jpg
