### ISSUE TITLE
[NPC] The Manipulator (triple spawn) - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3488]
**Links:**

https://www.wowhead.com/npc=39756/the-manipulator

![3](https://user-images.githubusercontent.com/39439201/66072060-9c12c480-e554-11e9-9c00-09bad16f0988.jpg)

**What is happening:**
- Triple spawned

**What should happen:**
- Should be only 1

**Comment by Rushor** [comment]
triple spawns removed https://i.imgur.com/gY77m1i.jpg
