### ISSUE TITLE
[General] Buffs

### ISSUE THREAD

**Issue by Randomplayerx** [WoWManiaUK/Blackwing-Lair#3494]
Ok, I open this issue it's basically same as I wrote on other Issue that someone opened about Haste stacking.

How should work:
Mark of the wild and than put Blessing of the Kings it cancel the mark and vice versa.

Right now on server:
https://ibb.co/DKzqt3H - wrong in two ways.

~1st - it probably give double stats [didn't checked]~
2nd - it require 2 times [two globals] to dispel/purge, in PvP matters it's a huge gamebreaker.

2. In different servers "talents buffs"=[talents that work like buffs and help to the group] also remove each other.
Explanation:
If you blood dk with Abomination's Might talent, Invite Enhancement shaman with Unleashed Rage talent to group one of the buff is "canceling" the other. You don't see both in the Buff List.

In additional if you add Paladin and he buff with Blessing of Might the buff is what you see in the Buff while talents are "hidden". Because Buff > Talent.
If they remove the buff or enemy dispelling, the Talent is back to Buff List.
Also, If the Dk and the Shaman are moving from each other [dk <----> shaman] and they're far enough from each other [out of the Talent range] their own talent is back to the Buff List.

This the list of all Raid buffs classified and catagorized by the effect they do.
https://www.wowhead.com/forums&topic=169946

**Comment by Echinaceax** [comment]
@Randomplayerx can you do The buffs in single reports please, our devs work from Single Spell reports. 
i see from here you already mentioned this issue https://github.com/WoWManiaUK/Blackwing-Lair/issues/3430#issuecomment-537046448

Duplated reports are not helpful just more work and double fixes. thanks

**Comment by Randomplayerx** [comment]
@echinaceax the issue 3430 was talking about Haste
this issue is talking about all the buffs and how they suppost to work, bit different.

I'm not going to seperate this issue into 3-4-5 or more small issues.

**Comment by Echinaceax** [comment]
then im sorry that how we work here, will wait until someone else does then. 
please take the time to read https://github.com/WoWManiaUK/Blackwing-Lair/wiki/How-to-Properly-Report-an-Issue

thank you

**Comment by Randomplayerx** [comment]
@Echinaceax no problems, have nice day/night.

**Comment by kDracku** [comment]
They dont give double stats , its more for pvp with purge matters

**Comment by Randomplayerx** [comment]
@kDracku can you post screenshots here if you checked it,
anyway I editted the 1# message cause I believe you, I did not checked myself. ;p

**Comment by kDracku** [comment]
i tested before , not having a ss atm but i will provide one tomorrow

**Comment by Keader** [comment]
Fixed the case of Kings + Mark of the Wild.
Other cases, you need open a report for each.
Ty.
