### ISSUE TITLE
[Item] Flame Blossom - (missing) - Mount Hyjal 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3496]
**Links:**

https://www.wowhead.com/item=52537/flame-blossom

**What is happening:**
- Missing 

**What should happen:**
_Obtain 5 Flame Blossoms._
for quest https://www.wowhead.com/quest=25224/in-bloom

**Comment by Rushor** [comment]
spawns added (around 100)
