### ISSUE TITLE
[NPC] Instructor Cargall - (missing) - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3497]
**Links:**

https://www.wowhead.com/npc=39451/instructor-cargall

**What is happening:**
- Npc missing 

**What should happen:**
Should be at the location for quest
https://www.wowhead.com/quest=25330/waste-of-flesh

**Comment by Rushor** [comment]
fixed https://i.imgur.com/ePDZ64G.jpg
