### ISSUE TITLE
[Object] Darkwhisper Lodestone (missing) - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3498]
**Links:**

https://www.wowhead.com/object=202952/darkwhisper-lodestone

**What is happening:**
- Object missing

**What should happen:**
Should be here for quest https://www.wowhead.com/quest=25509/physical-training-forced-labor

**Comment by Rushor** [comment]
around 40 objects added https://i.imgur.com/MbKzKdK.jpg
