### ISSUE TITLE
[Quest] Breaking the Line

### ISSUE THREAD

**Issue by Zunrin** [WoWManiaUK/Blackwing-Lair#35]
**How it should work:**
You should talk to Jornun who will give you a ride to Spitescale Cove

**How it currently works:**
You cannot interact with Jornun. You can still complete the quest if you walk to Spitescale Cove.

Links:
http://www.wowhead.com/npc=38989/jornun
http://www.wowhead.com/quest=25035/breaking-the-line

**Comment by Zunrin** [comment]
Jornun has now disappeared (I guess he's phased but I don't have GM powers so I can't check)

**Comment by fvicaria** [comment]
You do not need Jornun at all for this quest.
I have just re-done it with GM off and it works fine.

**Comment by Zunrin** [comment]
Changing the label to "Won't fix" then...
(Do note that there's no quest marker for that quest, and the quest text tells you to speak to Jornun to get a ride to Spitescale Cove so finding Morakki will be tricky for people who are playing as a troll on cataclysm for the first time)

**Comment by fvicaria** [comment]
Watch the video. You do not have to do anything. The quest is auto-completed and you just need to go to the NPC at the island to handle it.
