### ISSUE TITLE
[Quest] All That Skitters - ID 26523- The Hinterlands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#350]
Quest - https://www.wowhead.com/quest=26523/all-that-skitters
NPC -https://www.wowhead.com/npc=43156
Unable to collect spindling's, you can target them and kill them but cannot collect them whilst alive. Unable to complete quest.
![world of warcraft 03_01_2019 18_25_45](https://user-images.githubusercontent.com/42302580/50656275-843cee80-0f8a-11e9-87aa-7687e613a134.png)

**Comment by sarahkay88** [comment]
this quest also leads on to the following quest:
**Ally quest** - https://www.wowhead.com/quest=26524/dark-vessels 
**Horde quest** - https://www.wowhead.com/quest=26368/venomous-secrets
and I can loot the items needed for the horde quest even tho I'm alliance. but no ally quest items dropped for the one linked in this comment
![world of warcraft 03_01_2019 19_14_34](https://user-images.githubusercontent.com/42302580/50657267-eb0fd700-0f8d-11e9-92a9-f1c865bdefbf.png)

**Comment by Rushor** [comment]
fixed it like that you can loot the little spiders in order to get the questitem
