### ISSUE TITLE
[NPC] Failed Supplicant - Mount Hyjal 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3501]
**Links:**
https://www.wowhead.com/npc=39752/failed-supplicant

**What is happening:**
- Inactive 
- The dont move when you attack them 

**What should happen:**
https://www.wowhead.com/quest=25309/spiritual-training-mercy-is-for-the-weak#videos:id=72571

**Comment by Rushor** [comment]
https://www.youtube.com/watch?v=PPQn78Jn7LA

**Comment by Rushor** [comment]
fixed aggro and text (gm off haha)

**Comment by Rushor** [comment]
https://i.imgur.com/kiPuwlm.jpg
