### ISSUE TITLE
[NPC] Instructor Devoran (missing) - Mount Hyal 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3502]
**Links:**

https://www.wowhead.com/npc=39406/instructor-devoran

**What is happening:**
- hes missing 

![his missing](https://user-images.githubusercontent.com/39439201/66085631-0dad3b80-e572-11e9-9a32-6b4ec74b63e7.jpg)

**What should happen:**
Need him for quest
https://www.wowhead.com/quest=25294/walking-the-dog
https://www.wowhead.com/quest=25494/a-champions-collar
https://www.wowhead.com/quest=25496/grudge-match

**Comment by Rushor** [comment]
added https://i.imgur.com/moFGNO5.jpg
