### ISSUE TITLE
[Quest] Grudge Match - Mount Hyjal 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3505]
**Links:**

https://www.wowhead.com/quest=25496/grudge-match
https://www.wowhead.com/npc=40409/grommko

**What is happening:**
- the zone is deserted 
- Gromm'ko missing
- Other NPCs are missing there too

**What should happen:**
https://www.wowhead.com/quest=25496/grudge-match#videos:id=72578

**Comment by Rushor** [comment]
https://i.imgur.com/YEuYKhI.jpg

added him and other npcs

**Comment by Rushor** [comment]
all fixed now https://i.imgur.com/Baq4U1x.png https://i.imgur.com/AAz4XR3.png https://i.imgur.com/DQ4o4BD.png
