### ISSUE TITLE
[NPC] Commander Jarod Shadowsong (missing) - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3507]
**Links:**

https://www.wowhead.com/npc=40772/commander-jarod-shadowsong

**What is happening:**
- Not here 

**What should happen:**
Need him for quest back 
https://www.wowhead.com/quest=25531/twilight-riot
And new quests

**Comment by Rushor** [comment]
fixed https://i.imgur.com/2yd4SSL.jpg
