### ISSUE TITLE
[NPC] Twilight Enforcer /Twilight Stormwaker (missing) - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3508]
**Links:**
https://www.wowhead.com/npc=40563/twilight-enforcer
https://www.wowhead.com/npc=40573/twilight-stormwaker

**What is happening:**
- missing 

**What should happen:**
needed for quest 
https://www.wowhead.com/quest=25608/slash-and-burn

**Comment by Rushor** [comment]
spawns for both added https://i.imgur.com/9vPgmr1.jpg so that quest can be completed for now
