### ISSUE TITLE
[NPC] King Moltron/Tortolla/Magma giant (missing) - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3509]
**Links:**
https://www.wowhead.com/npc=40998/king-moltron
https://www.wowhead.com/npc=40464/magma-giant
https://www.wowhead.com/npc=41504/tortolla

**What is happening:**
- All missing 

**What should happen:**
Need for quest https://www.wowhead.com/quest=25550/magma-monarch

**Comment by Echinaceax** [comment]
note: quest item https://www.wowhead.com/item=55179/drums-of-the-turtle-god isnt summoning

**Comment by Rushor** [comment]
spawns added. questitem will be fixed later

https://i.imgur.com/bCSTIlV.jpg
