### ISSUE TITLE
[NPC] Aronus (missing) - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3510]
**Links:**

https://www.wowhead.com/npc=39140/aronus

**What is happening:**
- missing

**What should happen:**
need for quest back https://www.wowhead.com/quest=25644/the-twilight-egg

and new quests 
https://www.wowhead.com/quest=25552/brood-of-evil
https://www.wowhead.com/quest=25553/death-to-the-broodmother

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/kbk5jkJ.jpg)
