### ISSUE TITLE
[NPC] Cenarius (missing) - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3512]
**Links:**

https://www.wowhead.com/npc=40773/cenarius

**What is happening:**
- Missing

**What should happen:**
needed for quests
https://www.wowhead.com/quest=25554/secrets-of-the-flame
https://www.wowhead.com/quest=25555/the-gatekeeper
https://www.wowhead.com/quest=25551/the-firelord

**Comment by Rushor** [comment]
fixed but needs test on dev

**Comment by Rushor** [comment]
added

![I](https://i.imgur.com/7sKL5af.jpg)

**Comment by Echinaceax** [comment]
@Rushor - After you complete these two quests
1. https://www.wowhead.com/quest=25554/secrets-of-the-flame
2. https://www.wowhead.com/quest=25555/the-gatekeeper

Still issue with this one
3. https://www.wowhead.com/quest=25551/the-firelord after accepting this quest Cenarius is meant to be at map location to start his event but He isnt. 
https://www.wowhead.com/npc=40773/cenarius

See video 
https://www.wowhead.com/quest=25551/the-firelord#videos:id=3212

**Comment by Rushor** [comment]
well i only added spawn for him

**Comment by Echinaceax** [comment]
@Rushor So you want me to make a new report for 3. https://www.wowhead.com/quest=25551/the-firelord ?
