### ISSUE TITLE
[Quest] The Gatekeeper - Mount Hyjal 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3513]
**Links:**

https://www.wowhead.com/quest=25555/the-gatekeeper

**What is happening:**
- Nothing happens
After using the horn, nobody comes

**What should happen:**
_Use the Horn of Cenarius to help you slay Azralon the Gatekeeper._
https://www.wowhead.com/quest=25555/the-gatekeeper#videos:id=72495

**Comment by Rushor** [comment]
druids and Goldrinn is missing

**Comment by Rushor** [comment]
spawns and help added

![I](https://i.imgur.com/EWvKVBK.jpg)
![I](https://i.imgur.com/Tlohlvq.jpg)
![I](https://i.imgur.com/MkV3sO0.jpg)
