### ISSUE TITLE
[glyph/priest] Glyph of Dispel Magic

### ISSUE THREAD

**Issue by Steffiden** [WoWManiaUK/Blackwing-Lair#3514]
**Links:**

Item ID Dispel magic (spell): 527
Item ID Glyph: 55677

**What is happening:**

Whenever you use Dispel magic, you are healed, regardless of whether you dispel an effect.

**What should happen:**

The Glyphed spell should heal you for 3% of max health, ONLY WHEN you successfully dispel a magical effect.

**Comment by Kitzunu** [comment]
Nice catch!
