### ISSUE TITLE
[Jewelcrafting] Fire Prism

### ISSUE THREAD

**Issue by xenosDow** [WoWManiaUK/Blackwing-Lair#3515]
**Links:**
https://www.wowhead.com/item=52304

**What is happening:**
When you loot Fire Prism it is sometimes empty. Opened it 5 times so far and 2/5 it was empty

**What should happen:**
It should contain rare cataclysm gems and a chance for chimera's eye

**Comment by Echinaceax** [comment]
Ive reopened this #1872
