### ISSUE TITLE
[General] Heirlooms

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3520]
**Links:**
![stripped](https://user-images.githubusercontent.com/39439201/66243406-cc00ca00-e704-11e9-9e74-6d7749852eed.jpg)

**What is happening:**
- Heirlooms are automatically removed and sent to mailbox when you hit 81
- So leaves you chestless, shoulderless and ringless, without giving you the chance to replace them before their stripped off your char

**What should happen:**
- Surely it shouldnt auto remove (ofc reduce stats) but not auto removal

**Comment by Ovahlord** [comment]
That's actually blizzlike. Once you wear items that you can only wear up to a specific level they will get removed from your character and sent to you via mail to avoid them getting lost if you have a full inventory for example.

**Comment by Slydee23** [comment]
Yeah its Blizzlike  :D

**Comment by Echinaceax** [comment]
Thanks guys :)
it removed as soon as i hit 81 without relog, thats why i wondered, as it was reported as a quest bug ealier that caused it, so wanted it recorded here that is wasnt a quest that cause it. 
(just cant find the report atm)

Thanks for info
