### ISSUE TITLE
[NPC] Doomguard Destroyer - 41470 - Blasted lands

### ISSUE THREAD

**Issue by Nacho-k** [WoWManiaUK/Blackwing-Lair#3521]
**Links:**

https://www.wowhead.com/npc=41470/doomguard-destroyer#abilities

**What is happening:**

Doomguard Destroyer's rain of chaos spell is hitting for almost 7k damage, meaning an instant death for level 55-60 players

**What should happen:**

Should hit for way less damage, i dont if the numbers in wowhead are right
https://www.wowhead.com/spell=84502/rain-of-chaos

**Comment by jarvik76** [comment]
Likely related to the fix in #3529

**Comment by Rushor** [comment]
yes https://github.com/WoWManiaUK/Blackwing-Lair/issues/3529 will fix that
