### ISSUE TITLE
[NPC] Rockslice flayer (doubles) - Deepholm

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3523]
**Links:**
https://www.wowhead.com/npc=42606/rockslice-flayer

![flayer doubles](https://user-images.githubusercontent.com/39439201/66254806-da3dfd00-e77b-11e9-8574-dcc50cdf78c7.jpg)

**What is happening:**
- Doubles 

**What should happen:**
Shouldnt be stacked

**Comment by Rushor** [comment]
doubles removed
