### ISSUE TITLE
[NPC] Bound Water Elemental x4 - Deepholm

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3525]
**Links:**
https://www.wowhead.com/npc=44886/bound-water-elemental

![ele deep](https://user-images.githubusercontent.com/39439201/66257491-3d3e8c80-e79a-11e9-8ee0-9fec3607d5f5.jpg)

**What is happening:**
- There is x4

**What should happen:**
- Should be one

**Comment by Rushor** [comment]
removed doubles.
