### ISSUE TITLE
[NPC] Garm Bonehew <Food & Drink>

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3526]
**Links:**

https://www.wowhead.com/npc=49763/garm-bonehew

![sells](https://user-images.githubusercontent.com/39439201/66258787-9bbf3700-e7a9-11e9-9a9b-9f4c45989a75.jpg)

![soldout](https://user-images.githubusercontent.com/39439201/66258757-5d297c80-e7a9-11e9-8462-0f89d922a172.jpg)

1. https://www.wowhead.com/item=58256/sparkling-oasis-water
2. https://www.wowhead.com/item=58275/hardtack
3. https://www.wowhead.com/item=58260/pine-nut-bread
4. https://www.wowhead.com/item=58274/fresh-water

**What is happening:**
4 of the 6 items are "sold out" when you click on them lol 

**What should happen:**
He should sell all

**Comment by Rushor** [comment]
fixed
