### ISSUE TITLE
[NPC] Troggzor x2 - Deepholm 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3527]
**Links:**

https://www.wowhead.com/npc=43456/troggzor-the-earthinator

![troggzor](https://user-images.githubusercontent.com/39439201/66258981-f8bbec80-e7ab-11e9-9c73-bbe8141df9a7.jpg)

**What is happening:**
- Double

**What should happen:**
should be only one for the quest 
https://www.wowhead.com/quest=26625/troggzor-the-earthinator

**Comment by Rushor** [comment]
removed
