### ISSUE TITLE
[NPC] Stone Trogg Ambusher x4s - Deepholm

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3528]
**Links:**
https://www.wowhead.com/npc=43134/stone-trogg-ambusher

![stone trogg ambusher](https://user-images.githubusercontent.com/39439201/66258889-b34aef80-e7aa-11e9-97b4-9315046dd929.jpg)

**What is happening:**
- 2 sets of doubles

**What should happen:**
- shouldnt be doubles

**Comment by Rushor** [comment]
only 2 now. 2 time doubles removed. also sparring added.

**Comment by Randomplayerx** [comment]
Deepholm condition is worse than Mount Hyjal and Vashijr, there NPC missing while some NPCs have x3/x4 spawns and do extra damage.

Just fly around and look.

**Comment by Rushor** [comment]
yes i know. will fix all that
