### ISSUE TITLE
Paladin Retribution : Divine Storm and Censure

### ISSUE THREAD

**Issue by APTX4869s** [WoWManiaUK/Blackwing-Lair#3534]
![Divine Storm](https://user-images.githubusercontent.com/55243287/66269545-ad144c00-e85a-11e9-97ad-b9957458c512.png)

![Censure](https://user-images.githubusercontent.com/55243287/66269548-b0a7d300-e85a-11e9-8e3b-771c2e498f74.png)

if the encounter goes for long time ( specially in raids ) you can actually get 5 stacks of censure to all targets which it's just op and that shouldn't happen.
Dranah confirmed it in this report https://github.com/WoWManiaUK/Blackwing-Lair/issues/2939

**What is happening:**
Divine Storm applies a stack of censure to all targets

**What should happen:**
Divine Storm Shouldn't apply any stack of censure

**Comment by Keader** [comment]
Was proccing with hand of light now o.o

**Comment by Randomplayerx** [comment]
Nice report! I'm imagining doing divine storm on 10+ targets and get them all with Censure x5 stack
This make Seal of Righteousness so useless.
