### ISSUE TITLE
[Quest] Kavem the Callous - Uldum

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Blackwing-Lair#3537]
**Links:**
Quest: https://www.wowhead.com/quest=28105/kavem-the-callous
NPC:  https://www.wowhead.com/npc=47567/kavem-the-callous
Item:  https://www.wowhead.com/item=62817/neferset-key

**What is happening:**
Kavem does not drop the required quest item.
![WoWScrnShot_100619_142738a](https://user-images.githubusercontent.com/46089380/66269928-50a73180-e846-11e9-805c-3b2e5168354e.png)

**What should happen:**
Kavem drops https://www.wowhead.com/item=62817/neferset-key

**Comment by jarvik76** [comment]
Hmm.  it dropped the 4th time I killed him.  Wowhead comments make no mention that it is not a 100% drop rate when on quest.  
94% drop rate on wowhead but that could be due to kills outside of quest?

**Comment by Priestelar** [comment]
I got the drop first time, will check when levelling in the zone again - did not seem to be bugged.
