### ISSUE TITLE
[NPC] Spirit healer - Shadra'Alor - The Hinterlands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#354]
- spirit healer missing
spirit healer zone list - https://www.wowhead.com/npc=6491/spirit-healer

![hinterlands healer](https://user-images.githubusercontent.com/39439201/50678744-83df3a80-1000-11e9-8c29-10dca138a959.jpg)
![no spirit healer - hinterlands](https://user-images.githubusercontent.com/39439201/50678764-935e8380-1000-11e9-88f3-78e0ca4c8ee6.jpg)

**Comment by Echinaceax** [comment]
@Kitzunu - no creature found

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/55981330-b00cf600-5c96-11e9-9aa2-267c353cf994.png)

**Comment by Echinaceax** [comment]
@Kitzunu - i saw now thanks
