### ISSUE TITLE
[Quest] Escape from the Lost City - 28112 - Uldum

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Blackwing-Lair#3540]
**Links:**
https://www.wowhead.com/quest=28112/escape-from-the-lost-city

**What is happening:**
Cutscene is missing, and thus the player is not ported to Ramkahen at the finish of that cutscene.

**What should happen:**
Cutscene should play, and on finishing the player should the ported to Ramkahen. 
See playthrough here:
https://www.youtube.com/watch?v=nG5C9LkdBjw
Transcript & portal location notes here:
https://wow.gamepedia.com/Escape_From_the_Lost_City

**Comment by Echinaceax** [comment]
reported here #1909
