### ISSUE TITLE
[NPC/Quest] - Riverbed Crocolisk - 45321 - Uldum

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Blackwing-Lair#3541]
**Links:**
https://www.wowhead.com/quest=28200/the-element-of-supplies 
NPC - https://www.wowhead.com/npc=45321/riverbed-crocolisk

**What is happening:**
Drop rate of the quest item from mob seems unexpetedly low.
Quest requires you to obtain 20 hides from these mobs. According to wowheead comments they are a 100% drop for 2-3 each.
However it seems to be only about 33% rate.  Maybe the 44% quoted on wowhead?   Note these were commonly farmed for leather, so that 44% is misleading)

**What should happen:**
NPC should drop the quest items at 100% rate.

**Comment by Kitzunu** [comment]
```sql
UPDATE `creature_loot_template` SET `Chance` = 100, `MinCount` = 2, `MaxCount` = 3 WHERE `item` = 63256 AND `entry` = 45321;

**Comment by Rushor** [comment]
added. thank you very much @Kitzunu
