### ISSUE TITLE
[Spell] Smoke Bomb - Adding immunity to all boss creatures

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Blackwing-Lair#3547]
http://cata.cavernoftime.com/?spell=88611

**Comment by Rushor** [comment]
added for all creatures with boss_ script

**Comment by Randomplayerx** [comment]
Idk what the report on, but Bomb Smoke vs NPCs [Mobs] should stop casting [if they casting] and force them to get closer to melee-range or the minimum range it require inside the bomb-smoke to cast their abilities again.
