### ISSUE TITLE
Holy Paladin: Beacon of Light

### ISSUE THREAD

**Issue by APTX4869s** [WoWManiaUK/Blackwing-Lair#3550]
![Beacon of Light](https://user-images.githubusercontent.com/55243287/66274765-fe403200-e892-11e9-85cc-a4724bce950f.png)

if you heal a target that has Beacon of Light on there is another number comes with it sometimes 2k sometimes 4k as the picture shows.
I used Holy Light which healed 9k and 2k from Beacon of Light.
![Beacon 2 heals](https://user-images.githubusercontent.com/55243287/66274801-35aede80-e893-11e9-85cb-f0146951eb73.png)

**What is happening:**
healing a target that you put beacon of light on give you additional 2k or 4k heal

**What should happen:**
Healing a target that has Beacon of Light on shouldn't give you additional heals

**Comment by Slydee23** [comment]
y you get double hits like normal heal and beacon but you should nonly get 1
