### ISSUE TITLE
Holy Paladin: Wrong Beacon Proc with other paladins

### ISSUE THREAD

**Issue by APTX4869s** [WoWManiaUK/Blackwing-Lair#3551]
![Beacon of Light](https://user-images.githubusercontent.com/55243287/66275164-04d0a880-e897-11e9-9230-db77cec99a90.png)

If you put Beacon of Light on Protection Paladin and he uses Word of Glory he also heals 50% as Beacon of Light 
if Word of Glory heals him for 20k he will get another 10k as Beacon of Light

Beacon of Light is linked to all paladins in the group

**What is happening:**
if there are 2 paladins in the group 1 holy that used Beacon of Light on any target and the other one is protection or retribution, whenever the protection or the retribution paladin heals any target, the target with Beacon of Light also get healed
**What should happen:**
the target that has beacon of light on should only get healed as " Beacon of Light " from the Holy paladin who used it on him.

**Comment by APTX4869s** [comment]
![Stark heal](https://user-images.githubusercontent.com/55243287/66277030-c7c1e180-e8a9-11e9-96c2-47da76ef4a5d.png)

this picture explains the report.
Stark is the prot paladin 
Trixie is the Holy paladin

**Comment by Keader** [comment]
lul i lost hours to find what is the issue.]
Fixed
