### ISSUE TITLE
[NPC] Sharphorn Stag (skinning)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3553]
**Links:**

https://www.wowhead.com/npc=40193/sharphorn-stag

![sharphorn stag](https://user-images.githubusercontent.com/39439201/66279148-d0b5b180-e8af-11e9-96ee-220e5947a03b.jpg)

**What is happening:**
- at yellow you dont always get skill up
- Skips 4 skills at a time on some cases

**What should happen:**
You should always get skill up on yellow

**Comment by Slydee23** [comment]
is yellow at skinning really 100% ? cause all i know is  
red = 100% skill up 
yellow = high chance skill up 
green = low chance skill up
grey = no skill up

**Comment by Rushor** [comment]
how Slydee23 says. 

https://wow.gamepedia.com/index.php?title=Skinning&type=revision&diff=2810760&oldid=2596548

Any skinnable corpse will have a color code on the "Skinnable" property when you move your pointer over it:

    Red: Not skinnable.
    Orange: Difficult to skin; certain chance of increasing Skinning skill level.
    Yellow: Moderately difficult to skin; moderate chance of increasing Skinning skill level.
    Green: Easy to skin; low chance of increasing Skinning skill level.
    Gray: Very easy to skin; no chance of increasing Skinning skill level.

**Comment by Echinaceax** [comment]
thanks @Slydee23
