### ISSUE TITLE
"Life of the Party" Quest in Goblin Start Zone

### ISSUE THREAD

**Issue by Po0dog** [WoWManiaUK/Blackwing-Lair#3554]
**Links:**
from WoWHead or our Armory
https://www.wowhead.com/quest=14153/life-of-the-party
**What is happening:**
Your character is supposed to automatically equip an outfit (but that doesn't happen) and attend a party. The NPCs you supposed to entertain at the party are supposed to give you hints on how to entertain them (they speak) like they're hungry or thirsty or bored and you use a skill on your action bar to fulfill their request but nothing like this happens. Its like the quest provides zero progression. Now its seems my character can't advance and leave the start zone. She's stuck! 

**What should happen:**

1. She should equip an outfit.
2. using a special action bar, entertain guests upon seeing visual hints (chatting) from the NPCs involved in the quest.

**Comment by Rushor** [comment]
will fix this in my next session https://github.com/WoWManiaUK/Blackwing-Lair/issues/149
