### ISSUE TITLE
[Quest] The Drakkensryd

### ISSUE THREAD

**Issue by xenosDow** [WoWManiaUK/Blackwing-Lair#3556]
**Links:**
https://www.wowhead.com/quest=12886

**What is happening:**
When you use the chain you mount the drake but you are like 200 yards below the drake so you cant attack the rider or mount the next drake

**What should happen:**
You should be sat on the drake behind the rider instead of below

**Comment by Echinaceax** [comment]
Was reported here #811 and fixed 
i will reopen the other report 
thanks @xenosDow
