### ISSUE TITLE
[Zone/Npc] Felwood

### ISSUE THREAD

**Issue by xenosDow** [WoWManiaUK/Blackwing-Lair#3558]
**Links:**
https://www.wowhead.com/felwood

**What is happening:**
Most (if not all) mobs in Felwood have to much hit points. They all have close to 4k which is almost if not double their normal health pool.

**Comment by Rushor** [comment]
some proof https://www.youtube.com/watch?v=S91rcQ9N_2w

**Comment by Rushor** [comment]
okay all creatures in felwood have healthmodifier back to normal (1) again.

![I](https://i.imgur.com/bYrV4j0.jpg)
