### ISSUE TITLE
Kezan Quests "The Great Bank Heist" and "Robbing Hoods"

### ISSUE THREAD

**Issue by Po0dog** [WoWManiaUK/Blackwing-Lair#3563]
**Links:**
from WoWHead or our Armory
https://www.wowhead.com/quest=14122/the-great-bank-heist
https://www.wowhead.com/quest=14121/robbing-hoods
**What is happening:**
1. The Great Bank Heist - when you enter the bank, there's no indication whatsoever about what you're supposed to do. 
2. Robbing Hoods - supposed to use Hod Rod to run down looters, but the quest item is missing from my inventory. Quest item ID: 46856

**What should happen:**
1. toggle objects in the bank to begin a mini game (according to a YouTube video)
2. run looters down with Hot Rod, an item that you equip.

**Comment by Rushor** [comment]
Both quests i fixed today in other report. Fix will be applied on live realm this wednesday

**Comment by Echinaceax** [comment]
#2316
