### ISSUE TITLE
Kezan Quest Life Savings

### ISSUE THREAD

**Issue by Po0dog** [WoWManiaUK/Blackwing-Lair#3564]
**Links:**
from WoWHead or our Armory

https://www.wowhead.com/quest=14126/life-savings

**What is happening:**
Supposed to head to the port and speak to Trade Prince Gallywix, but he wasn't there on the dock, Went back to the KTC Headquarters and found him in the position where he was before the quest began. Spoke to him, a cinematic runs, and then I was back at the KTC Headquarters and my screen was all black except for the UI elements. So, I never left the start zone.

**What should happen:**

You're supposed to head to the port where you meet Trade Prince Gallywix on the dock, He'll put on the boat and a cinematic runs. Afterwards, you should be on The Lost Isle and the quest will be completed.

**Comment by gamer100** [comment]
Fixed in dev
