### ISSUE TITLE
[Quest/Goblin] Don't go into the light 

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Blackwing-Lair#3565]
https://www.wowhead.com/quest=14239/dont-go-into-the-light
https://www.wowhead.com/npc=36608/doc-zapnozzle
https://www.youtube.com/watch?v=Z35Vg_h_w5A

When you  Finish the  quest Life savings
https://www.wowhead.com/quest=14126/life-savings
You receive  automatic  the  quest Don't  go into the light

You don't get teleported to the location and the  quest is not added.
Npc Doc zapnozzle not in game

**What should happen:**

**Comment by Rushor** [comment]
i will teleport the player to orgrimmar for now, until https://github.com/WoWManiaUK/Blackwing-Lair/issues/3566 and everything else is fixed okay?

**Comment by Rushor** [comment]
![I](https://i.imgur.com/jOgqjOh.jpg)

okay people will get ported here https://i.imgur.com/jOgqjOh.jpg once quest "Life Savings" is finished with next update.
