### ISSUE TITLE
[Quest] Lycanthoth the Corruptor - ID 25272 (Horde) - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3567]
**Links:**
https://www.wowhead.com/quest=25272/lycanthoth-the-corruptor
https://www.wowhead.com/item=52682/lycanthoths-incense

![no summon](https://user-images.githubusercontent.com/39439201/66388306-15cc0780-e9c6-11e9-94cd-c120c5bc9777.jpg)

**What is happening:**
- he is already visible
- Didnt need to use quest item to summon him

**What should happen:**
_Use Lycanthoth's Incense within the Maw of Lycanthoth in Hyjal to summon and kill Lycanthoth._

**Comment by Rushor** [comment]
removed
