### ISSUE TITLE
[NPC] Spirit of Lo'Gosh - (Horde) - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3568]
**Links:**

https://www.wowhead.com/npc=39622/spirit-of-logosh

![missing](https://user-images.githubusercontent.com/39439201/66388908-698b2080-e9c7-11e9-9f38-62d3d1c8465d.jpg)

**What is happening:**
- Missing

**What should happen:**
Should be here for quest back https://www.wowhead.com/quest=25272/lycanthoth-the-corruptor

**Comment by Rushor** [comment]
By Neocross (438 –  2·8)  on 2015/08/31 (Patch 6.2.2) |   |  
-- | -- | --


When you kill Lycanthoth, do not move. Don't mount up or leave the cave. The spirit of Goldrinn will spawn and you can turn in the quest where a cutscene will pop up.

so Spirit of Lo'Gosh should spawn once Lycanthoth is killed. it is only a temp summon, not a static spawn.

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/sYaZ8EI.jpg)
