### ISSUE TITLE
[Quest] The Shrine Reclaimed - (missing) - Mount Hyjal 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3569]
**Links:**

https://www.wowhead.com/quest=25279/the-shrine-reclaimed

**What is happening:**
- Quest missing

**What should happen:**
_NPC should offer quest_

**Comment by Echinaceax** [comment]
New info @Rushor re phased myself so its visible for me know :)

**Comment by Rushor** [comment]
![I](https://i.imgur.com/09qVXwg.jpg)

attention now player!

the wolf "spirit of Lo'Gosh" will have the quest avialable once the bad wolf inside the cave was killed.
