### ISSUE TITLE
[Quest] Rejuvenating Touch (Part 2 of 2) ID: 27067

### ISSUE THREAD

**Issue by realdude19** [WoWManiaUK/Blackwing-Lair#357]
Tauren Druid starter quest.
Quest ID 27067

Quests don't grant credit for using Rejuvenation on the Wounded Braves (45199) and thus cannot be completed.

https://wow.gamepedia.com/Rejuvenating_Touch_(tauren)

Same as: https://github.com/WoWManiaUK/Blackwing-Lair/issues/17

**Comment by mfranca0009** [comment]
This issue still exists, just previously tested while playing on a live with a friend. @Echinaceax

**Comment by golosomie** [comment]
pending for .bq command

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
confirmed fix in ptr 

![image](https://user-images.githubusercontent.com/39439201/119257912-b7b65d00-bbc7-11eb-82de-9b009d7f813d.png)
