### ISSUE TITLE
[Quest] Cleaning House - 25277 - (horde) missing - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3570]
**Links:**

https://www.wowhead.com/quest=25277/cleaning-house
https://www.wowhead.com/npc=39432/takrik-ragehowl

**What is happening:**
- Quest missing

**What should happen:**
_Should offer quest_

**Comment by Rushor** [comment]
https://wowwiki.fandom.com/wiki/Quest:Cleaning_House
Previous
The Shrine Reclaimed

http://cata.cavernoftime.com/quest=25277

works fine

![I](https://i.imgur.com/HwjWpoZ.jpg)

**Comment by Echinaceax** [comment]
not for me it doesnt 
![not for me](https://user-images.githubusercontent.com/39439201/66394074-63e80780-e9d4-11e9-8b13-cfd3d157eea5.jpg)

**Comment by Echinaceax** [comment]
.app to you fixed my phasing issue @Rushor :)

**Comment by Rushor** [comment]
need to refix that for alliance and horde
