### ISSUE TITLE
[Quest] The Nordrassil Summit (autocompleted) - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3572]
**Links:**

The Nordrassil Summit

**What is happening:**
- auto completed

**What should happen:**
https://www.wowhead.com/quest=29326/the-nordrassil-summit#videos:id=87886

**Comment by Rushor** [comment]
moved to https://github.com/WoWManiaUK/Blackwing-Lair/issues/3354
