### ISSUE TITLE
Druid Swipe (Cat Form)

### ISSUE THREAD

**Issue by adel4241** [WoWManiaUK/Blackwing-Lair#3574]
https://www.wowhead.com/spell=106785/swipe

**What is happening:** when we are use this spell on more then 2 Mob u will get 1 or 2 Combo point

**What should happen:** this spell should only do damge not give the Combo 

Royal  of Test team

**Comment by Rushor** [comment]
ID - 62078 Swipe (Cat Form)

**Comment by Keader** [comment]
Is correct.
Who is adding the combo points is the talent Blood Frenzy/Primal Fury

"Your critical strikes from Cat Form abilities that add combo points  have a X% chance to add an additional combo point."
