### ISSUE TITLE
[PvP] Tol Barad / Baradin Hold PvP (Horde)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3578]
> The second quest hub is in Tol Barad in the PvP area of Tol Barad located at [51.2, 49.3]. These quests are available to the winning side as soon as the battle is over, but 15 minutes before the next battle begins, the quest-giver NPCs and all quest mobs will disappear, and whichever of the three quest areas had been unlocked will be closed again, preventing completion of any further objectives. There will be a five-minute warning to players in the zone before this occurs. However, any completed quests may still be turned in at the faction base camps on Tol Barad Peninsula at any time.

These three quests are always available:

https://www.wowhead.com/npc=48069/commander-zanoth

https://www.wowhead.com/quest=28657/a-huge-problem
https://www.wowhead.com/quest=28658/swamp-bait
https://www.wowhead.com/quest=28659/the-leftovers

> Then, one of these three sets are available at a time, based on which quest area is unlocked for this possession of the island:

https://www.wowhead.com/npc=48071/private-garnoth

https://www.wowhead.com/quest=28660/clearing-the-depths
https://www.wowhead.com/quest=28662/learning-from-the-past
https://www.wowhead.com/quest=28661/the-imprisoned-archmage

https://www.wowhead.com/npc=48070/drillmaster-razgoth

https://www.wowhead.com/quest=28665/cursed-shackles
https://www.wowhead.com/quest=28663/d-block
https://www.wowhead.com/quest=28664/svarnos

https://www.wowhead.com/npc=48062/staff-sergeant-lazgar

https://www.wowhead.com/quest=28670/food-from-below
https://www.wowhead.com/quest=28668/prison-revolt
https://www.wowhead.com/quest=28669/the-warden

> These sets are not exclusive with each other on a given day, and because the unlocked area rotates after every battle, it is possible for an attentive player to complete all 12 quests in a day by returning after each battle - assuming their faction continues winning, and the random sequence of areas unlocked works out in their favor.

@Rushor as the battle is broken set the ones that are randomly given to how you want for now as long as players get extra i think they will be happy

**Comment by Rushor** [comment]
![I](https://i.imgur.com/ZX5VXob.jpg)

added both spawns (both quest giver only) for defender and attacker team
