### ISSUE TITLE
[Glyph] Mage (Arcane) - Glyph of Mirror Image

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#3584]
**Links:**
https://cata-twinhead.twinstar.cz/?item=45739

**What is happening:**
The arcane blast of the copies do too low dmg. Tested with 2 mages: the fire with the same glyph do 40k dmg of mirror images (fireball), the arcane do in the same time 4k (arcane blast)

**What should happen:**
The copies should do the right amount of dmg, either if they're casting fireball or arcane blast.

**Comment by Rushor** [comment]
How much damage should they do?

**Comment by Echinaceax** [comment]
when i get them to cast instead of standing there i will tell you lol 
mirrors are broken atm i will SS when i can
