### ISSUE TITLE
[Item] Tahret Dynasty Mallet 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3585]
**Links:**
https://www.wowhead.com/item=63351/tahret-dynasty-mallet
https://www.wowhead.com/quest=28250/thieving-little-pluckers

reported to GM ingame

**What is happening:**
Tahret Dynasty Mallet quest item is usable on attackable npc's other than the pygmies at the Tahret Grounds. They found out when they tried to use the hammer on a cursed engineer at the Tomb of the sun king and it killed the npc instantly.

**What should happen:**
Quest item should only work on quest npc listed for the quest 
https://www.wowhead.com/quest=28250/thieving-little-pluckers

**Comment by Rushor** [comment]
fixed!

![I](https://i.imgur.com/pPIg6vC.jpg)

only works on the pluckers now and much animations fixed
