### ISSUE TITLE
[RAID] Ascendant Council combat bug - Bastion of Twilight

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#3586]
**Links:**
https://wow.gamepedia.com/Ascendant_Council

**What is happening:**
After a wipe in phase 2 (Terrastra/Arion) the players are unable to enter the raid. Maybe there's some combat problem with the previous 2 bosses (Ignatius/Feludius) because when you try to enter it says "Unable to zone in while a encounter is in progress". Some of the 4 bosses remains in combat after the wipe.

**What should happen:**
All the bosses should reset after a wipe and you should be able to enter the raid.

**Comment by Rushor** [comment]
i will despawn all temp summons. could not reproduce the issue sadly

**Comment by Rushor** [comment]
all temp summons will all despawn on wipe now.

**Comment by Sammy974** [comment]
Still not working. Impossible to continue the raid after a wipe at Council because it's not possible to enter the zone.

**Comment by Rushor** [comment]
any chance to reproduce this?

**Comment by Slydee23** [comment]
which phase you wiped ? cause it did not happened every wipe at council

**Comment by Priestelar** [comment]
Happened now again in my raid, i have it on video if needed.

We made it to the 2nd phase with the air and earth boss and then we all died and now we cant re enter, even calling a GM doesn't work.

**Comment by Priestelar** [comment]
Bosses are not INSTANTLY respawning after they kill the group they stay despawned for a while after a few minutes - this COULD be the cause of the problem, we were otherwise not able to reproduce the original problem. But this is a problem none the less.

**Comment by Rushor** [comment]
well the delayed respawn is a feature for all bosses so far. i think that is blizzlike

**Comment by Priestelar** [comment]
yes but i mean the delay is so long that sometimes when we come back inside the instance to the boss room then the boss hasn't even respawned yet

**Comment by Sammy974** [comment]
If it can help, this problem come out if the raid wipes at second phase after the first disperse spell of Arion.
@Rushor check if there's something wrong in the behaviour of the bosses after the disperse ;) 
https://www.wowhead.com/spell=83087/disperse

**Comment by Priestelar** [comment]
@Sammy974 we will try to recreate it and see if the its that spell causing the issue

**Comment by Keader** [comment]
I made a little protection.
Since we cant reproduce, boss will always check if has someone in instance, if has not, will reset.
So, if bug on wipe, tell to everyone use release and stay outside of instance 10 sec.

**Comment by Rushor** [comment]
thank you very much!!!!!!!
