### ISSUE TITLE
I Think She's Hungry

### ISSUE THREAD

**Issue by Po0dog** [WoWManiaUK/Blackwing-Lair#3587]
**Links:**
from WoWHead or our Armory

https://wow.gamepedia.com/I_Think_She%27s_Hungry_(Horde)

**What is happening:**

The quest gives you a pet baby lash tail. You're supposed to take it out to have feed it on 40 murlocs in Nothern Stranglethorn Vale. She attacks the murlocs but she's not feeding. The quest count doesn't go up.

**What should happen:**

When she attacks the murlocs she's suppose to bite into them and you should see quest count go up until she's fed on 40 murclocs.

**Comment by Echinaceax** [comment]
Already reported here #1546
but thank you
