### ISSUE TITLE
Engineering - Synapse Springs do nothing.

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3589]
**Links:**
http://cata.cavernoftime.com/spell=82175
http://cata.cavernoftime.com/spell=82174
from WoWHead or our Armory

**What is happening:**

I enchanted my Gloves with Synapse Springs, after i use them i do not get the buff but i get cooldown on it.

**What should happen:**

i should get http://cata.cavernoftime.com/spell=82174

**Comment by Rushor** [comment]
aaaand fixed

![I](https://i.imgur.com/9rBkEE1.jpg)
