### ISSUE TITLE
[quest] Verog the Dervish

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#3590]
**Links:**

from WoWHead or our Armory
wowhead.com/quest=851/verog-the-dervish
https://www.wowhead.com/npc=34846/wyneth
**What is happening:**
Wyneth is nowhere to be found and he need to be killed to spawn Veog

**What should happen:**
after Wyneth is killed it should spawn verog whos yelling and you pawn him

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/hglD2NC.jpg)
![I](https://i.imgur.com/D8O0q0s.jpg)

**Comment by TheSale** [comment]
nice rushor,
sry for other quests that were open but I have posted, I saw 2 were not on github so I just were posting every issu I saw on my way :D

**Comment by Rushor** [comment]
kay np man. i continue with fixing hc loots now
