### ISSUE TITLE
[quest]  [Through Fire and Flames]

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#3591]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=13878/through-fire-and-flames
**What is happening:**
there are wolfs, but there is no fire, there are no chains, and when I click on spikes, nothing happen.

**What should happen:**

wolfs should be free after clicking on bone spikes

**Comment by Rushor** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/295

search pls in github here before reporting bugs. i was already reported.
