### ISSUE TITLE
[quest]  [The Baron's Demands]

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#3592]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=14046/the-barons-demands
**What is happening:**
it is autocompleted quest after you interact with him and free him, but after I click complete quest it dont finalize and quest stand there in log as completed asking me to complete it.
tried several times, reloging and stuff, never completed it.

**What should happen:**

click on complete quest should be self explanatory

**Comment by Rushor** [comment]
one mssing complete thing was missing.

fixed with next update

![I](https://i.imgur.com/9lTZ0Ml.jpg)
