### ISSUE TITLE
[racial spell] Pack-hobgoblin

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#3594]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/spell=69046/pack-hobgoblin
**What is happening:**
it is part of goblin racial, but it cant be obtained without lost isles, so there should be some fix till that is done or just leave it till lost isles are open for questing.
Current goblins should have that racial since it is theirs, and they wont go back to lost isles I believe.

**What should happen:**

**Comment by Rushor** [comment]
Goblins will get this spell nextupdate on login if they don't already have it. This stays active till all Lost Islands are fixed.

![I](https://i.imgur.com/yN1Zgyx.jpg)
