### ISSUE TITLE
[quest]  [Mutiny, Mon!]

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#3595]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=14063/mutiny-mon
**What is happening:**
under deck there is nothing, 1 killable npc, and 2 afk npc,
cant activate item provided

**What should happen:**
under deck item should be activated and npc shoud appear to help you to fight

**Comment by Rushor** [comment]
already reported. do not duplicate our work pls https://github.com/WoWManiaUK/Blackwing-Lair/issues/1159
