### ISSUE TITLE
[Priest] [Equip] [Tier 11] - 4 Pieces Set Bonus Not Working

### ISSUE THREAD

**Issue by Taggat29** [WoWManiaUK/Blackwing-Lair#3598]
**Twinhead Link:**
spell=89911

**What is happening:**
As a Holy Priest, wearing 4 pieces of the T11 set, **I'm not** getting the 540 Spirit bonus while being in Chakra State.

**What should happen:**
As you can see from the pictures I've uploaded, Character should get a 540 Spirit bonus when Chakra State is active.

![Spirit Chakra](https://user-images.githubusercontent.com/52217123/66613731-bf79e700-ebc6-11e9-8fa6-b65fc182e63a.png)

![Spirit no Chakra](https://user-images.githubusercontent.com/52217123/66614347-01a42800-ebc9-11e9-90ed-220e5e86e598.png)

**Comment by Rushor** [comment]
ID - 89912 Chakra Flow

**Comment by Rushor** [comment]
yes fixing right now

**Comment by Rushor** [comment]
aand fixed. add and remove if set aura is on player and chakra is active.
