### ISSUE TITLE
[Quest] Territorial Fetish

### ISSUE THREAD

**Issue by Zunrin** [WoWManiaUK/Blackwing-Lair#36]
**How it should work:**
You should only be able to use the item (territorial fetish) on a spitescale flag.

**How it currently works:**
You can use the item anywhere and it counts toward the quest.

Links:
http://www.wowhead.com/quest=24813/territorial-fetish
http://www.wowhead.com/item=52065/territorial-fetish
http://www.wowhead.com/npc=38560/spitescale-flag-bunny

**Comment by Zunrin** [comment]
The item can now only be placed on the flags as expected.
However, it can be placed over and over on the same one, making the quest easier than normal.

**Comment by fvicaria** [comment]
Also works perfectly. Not a tweak. It's fixed.

**Comment by Zunrin** [comment]
I know there's a cooldown on the mask, I'm saying there should be a cooldown on the actual flag (probably about 5 mins) to stop a player using the mask on the same flag every 4s. Also I just noticed the flags seem to get you stuck in combat.
