### ISSUE TITLE
[Quest] Latent Disease - ID 26934 - Tirisfal Glades

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#360]
Quest - https://www.wowhead.com/quest=26934/latent-disease
Quest item - https://www.wowhead.com/item=60679/plague-tangle

- Quest item not loot able as shown in video
- Quest not completable 

![deseased bears](https://user-images.githubusercontent.com/39439201/50687569-1cd27d80-1022-11e9-970a-8eab17ef29ec.jpg)

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/XlXKRJD.jpg)
