### ISSUE TITLE
[Raid] Trash mobs and bosses spawn - Bastion of Twilight

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#3600]
**Links:**
https://wow.gamepedia.com/Bastion_of_Twilight
https://wow.gamepedia.com/Valiona_and_Theralion

**What is happening:**
Trash mobs and a boss respawned after killed in the same id. Entering the raid the day after we've done the first 2 encounters (Halfus and Valiona and Theralion), we found all the trash mobs up and Theralion up (without Valiona!) 

**What should happen:**
Once killed, trash mobs and bosses should not respawn in the same id.

**Comment by Rushor** [comment]
for all adjusted, like in icc.

**Comment by Sammy974** [comment]
To be more specific: trash mobs respawn must be "linked" to the boss. For example: if a group kills the first boss but not the second boss but they killed all the trash mobs before the second boss, next time they enter the raid they must find again the trash mobs before the second boss but not all the trash mobs before the first boss. Example #2: If you wipe at the council and decide to come back the day after to finish the raid, you'll find all clear until Valiona and Theralion, but you'll find the dragonkin in the hall and the elementals in the council room although you killed them the day before, because you didn't kill the council boss.

**Comment by Rushor** [comment]
yes that feature will be added in future. is that working already in some raids?

can be done with linked respawn, but that rquires a lot of work. buguse disabled for now with static respawn timer.

**Comment by Sammy974** [comment]
Yeah i think it's working as intended in some other raid, but i'll check and let you know because i'm not 100% sure.

If it's too hard to fix properly, a 12/24 h respawn timer should be fine :)

**Comment by Rushor** [comment]
okay will do 24 hours then

**Comment by Sammy974** [comment]
That's fine, it will avoid the respawn in the same day and it's pretty good

**Comment by Slydee23** [comment]
looks like ppl now farm more bosses than they should in one ID.
