### ISSUE TITLE
[Item] Cloth Scavenging / Embersilk Cloth (issue 2)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3603]
**Links:**
https://www.wowhead.com/spell=59390/cloth-scavenging
https://www.wow-professions.com/farming/embersilk-cloth-farming

**What is happening:**
- Embersilk Cloth with Cloth Scavenging isnt working as it should
- It isnt giving extra as it states from link
- normal drops without the extra are low to, 1s and 2s in Hyjal and 1s 2s and 4s in twilight Highlands

**What should happen:**
https://www.wow-professions.com/farming/embersilk-cloth-farming

> _[Cloth Scavenging] also works on Cataclysm mobs. You can learn this skill by completing the Cloth Scavenging quest, which is given by Charles Worth at Dalaran (Northrend). This NPC exists in Broken Isles Dalaran too, but he won't teach you Northrend Tailoring.
> 
> With [Cloth Scavenging] tailors will get a lot more cloth than non-tailors._

Edited: definately no extras giving from [Cloth Scavenging] as it should in Cata

**Comment by Slydee23** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/3350

**Comment by Echinaceax** [comment]
yes we mean the same thing, yes its works for cata too indeed :) or meant too lol

i will close mine and Rushor can fix yours :)

**Comment by Rushor** [comment]
like the other issue. added the same loot table again, but with the conditions to only see the second loot table if aura http://cata.cavernoftime.com/spell=59390 is active.
