### ISSUE TITLE
[NPC] Raging Firestorm (double spawn)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3604]
**Links:**
https://www.wowhead.com/npc=39939/raging-firestorm

![raging firestorm](https://user-images.githubusercontent.com/39439201/66715162-447c2080-edc0-11e9-8a92-2e06bdd79895.jpg)

**What is happening:**
- Double spawn
- Or need spacing
- Also their dmg is low

![low dmg strorm](https://user-images.githubusercontent.com/39439201/66715251-37abfc80-edc1-11e9-9a58-8ec06a1f1bb3.jpg)

**Comment by Rushor** [comment]
all spawnplace reworked
