### ISSUE TITLE
[BoT] ChoGall uses  Summon Corrupting Adherent not often enough

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3606]
**Links:**

https://www.wowhead.com/spell=81628/summon-corrupting-adherent#used-by-npc

from WoWHead or our Armory

**What is happening:**

**What should happen:**

Chogall should use  way more the spell Summon Corrupting Adherent

**Comment by APTX4869s** [comment]
I can confirm that
this video from retail
https://www.youtube.com/watch?v=9V4y5XZthrg
u can see that he summoned the add before 2 mins
at 1:00 to 1:06 ( he used Fury of cho'gall after few secs he summoned the add )
what is happened here: cho'gall summons the add after 2 mins when you start the encounter which it makes the fight so easy
we actually can run 1 tank 1 healer 8 dps to burn Cho'gall from 100% to 25% in less than 2 mins

**Comment by APTX4869s** [comment]
Also kindly check if Fury of Cho'gall's de buff that increases the damage taken actually works. ( not sure if it's working or not )
I tanked him so easily with 4 stacks of fury of cho'gall and could actually take more

**Comment by Sammy974** [comment]
I can confirm too.
Maybe the corruption is not working as intended too, it should grow up faster expecially in the last phase. I don't have numbers to prove it, just an impression.

**Comment by Rushor** [comment]
so what timer would you suggest for Summon Corrupting Adherent 

after what time after combat start it should be handled?
after what time should it be repeated?

**Comment by Bloodborne93** [comment]
When you start the boss, after 1 minute and 20 sec he must summon the Add, the second is at 2 minute and 40 sec and the other spawn at 4 minute and 10 sec, the first at left, second right and third left and so on.

**Comment by APTX4869s** [comment]
@Bloodborne93  
We need a source about it, such as a video or a link.
I only saw that video which it may be wrong ( but it's from retail ).
This is a raid not RHC whic means we need to be careful with the sources ^^ (  I'm not trying to say yours isn't right, I would take it as a final solution if we didn't get any other words. )

**Comment by Bloodborne93** [comment]
@APTX4869s  here we go man: https://www.youtube.com/watch?v=eWHNzND_wY8 look that :D

**Comment by Rushor** [comment]
timer adjusted to 1min + 20s with nextupdate

**Comment by Bloodborne93** [comment]
@Rushor  you are so fast man!!! :D

**Comment by Sammy974** [comment]
@APTX4869s 
We saw more than 1 video and the timing seems to be around 1,20 min.
We can still check it in fight, but i think this timing is good enought.
Thanks Rushor ^^

**Comment by APTX4869s** [comment]
@Sammy974  yep that seem fine to me too 1:20 better than 2 min

**Comment by Sammy974** [comment]
@APTX4869s  about Fury of Cho'gall

> Also kindly check if Fury of Cho'gall's de buff that increases the damage taken actually works. ( not sure if it's working or not )
> I tanked him so easily with 4 stacks of fury of cho'gall and could actually take more

Consider that we all have a good gear for this fight. We checked on it watching a video of our fight and the damage of Fury of Cho'gall seems to be right. It does 20k shadow + 20k physical as intended but it's less with shields and reductions so it's quite bearable at our ilv. This fight is supposed to be done at 346 ilv, we're all 359 more or less.

**Comment by APTX4869s** [comment]
@Sammy974 
I'll give it more tests for both main and alt runs next id, if it was bugged I'll open a report about it with few ss showing that ( as I said before I'm not sure it it works or not )
