### ISSUE TITLE
Warlock t11 4p not working.

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3607]
**Links:**

http://www.cavernoftime.com/spell=89935

from WoWHead or our Armory

**What is happening:**

the 4p bonus is not proccing after 5 mill dmg test

**What should happen:**

**Comment by jahbansen** [comment]
The 4 uses of fel flame wasnt a procc
![warlock t11](https://user-images.githubusercontent.com/54234847/66716547-2538bf80-edcf-11e9-9604-0eaa09be2751.PNG)

**Comment by Rushor** [comment]
Must be handled on spell proc i guess

**Comment by jahbansen** [comment]
yes absulutely! immolate or unstable affliction should be able to trigger the procc. Its a 2% chance, but should after all procc during a 6min dmg encounter. I was casting Immolate 23 times, only the initial casts count, one immolate does tick ar last 6 times and those initial cast and ticks should be able to trigger the 4P.

**Comment by jahbansen** [comment]
I just was testing it and it works! it does procc! But weird that when i was testing only with Unstable affliction it procced more often then as I was using the whole dmg rotation. 
I did a more in depth dmg test over 15min and got 5 proccs from my 4p, that made a 1.8% dmg difference. Seems like it proccs a bit to little...

**Comment by Keader** [comment]
Welcome to probability xD
