### ISSUE TITLE
Quest Unavailable: Extinguishing Hope

### ISSUE THREAD

**Issue by Tigerief** [WoWManiaUK/Blackwing-Lair#3608]
**Links:**
https://www.wowhead.com/quest=26391/extinguishing-hope
from WoWHead
**What is happening:**
Quest is currently unavailable from quest giver.

**What should happen:**
Quest giver should grant quest allowing players to go into the field in order to put out fires.

**Comment by Rushor** [comment]
https://wowwiki.fandom.com/wiki/Quest:Extinguishing_Hope

you first need to do that quest http://cata.cavernoftime.com/quest=28821 in order to get the mentioned quest :)

**Comment by Tigerief** [comment]
I am aware of the quest pre requisite rushor :P but its still not available, I did every quest in Elwynn Forest and this quest is STILL not available
![WoWScrnShot_101419_000014](https://user-images.githubusercontent.com/16594771/66723136-db26fc80-ee15-11e9-8ca9-4de1fb3de008.jpg)
