### ISSUE TITLE
Quest: Pie for Billy <Elwynn Forest>

### ISSUE THREAD

**Issue by Tigerief** [WoWManiaUK/Blackwing-Lair#3609]
**Links:**
https://classic.wowhead.com/quest=86/pie-for-billy
from WoWHead or our Armory

**What is happening:**
Quest item drop rate is extremely low causing you to need to commit mass genocide on the Stonetusk boars in order to make a pie

Workaround: Kill around x5 times the boars.

**What should happen:**
Item should be a 100% drop on stonetusk boars.

**Comment by Rushor** [comment]
fixed with next update

**Comment by Tigerief** [comment]
stunning! :)
