### ISSUE TITLE
[Item] Side of Bear Meat - ID 60851 - Western Plaguelands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#361]
https://www.wowhead.com/item=60851/side-of-bear-meat#objective-of

Quest - https://www.wowhead.com/quest=27167/a-mighty-hunger

- Item is dropping without any quest for it 

![bear meat](https://user-images.githubusercontent.com/39439201/50688123-602deb80-1024-11e9-8b88-e04ea09f4924.jpg)

**Comment by Dranah** [comment]
Objective for https://www.wowhead.com/quest=27167/a-mighty-hunger
Is this quest unavailable, or the only issue is the quest item dropping without quest too?

**Comment by Dranah** [comment]
It's alliance side, but the quest giver NPC is missing, opening separate report for that. The quest itself is probably fine, the item is not supposed to drop without the quest. That's a tweaking issue.

**Comment by Echinaceax** [comment]
@Kitzunu - still dropping 

![stillll](https://user-images.githubusercontent.com/39439201/56082672-d6a86980-5e1b-11e9-9827-4460969807e9.jpg)

**Comment by Kitzunu** [comment]
Fixed

**Comment by Echinaceax** [comment]
@Kitzunu - main issue fixed :)

new issue -
-  they drop gems 

![new issss](https://user-images.githubusercontent.com/39439201/56082792-5c78e480-5e1d-11e9-8056-7235b1dc42f0.jpg)
