### ISSUE TITLE
[spell][priest] Lightwell

### ISSUE THREAD

**Issue by hediunchained** [WoWManiaUK/Blackwing-Lair#3610]
**Links:** https://cata-twinhead.twinstar.cz/?spell=724

**What is happening:** the well is a textureless cube

![image](https://user-images.githubusercontent.com/36192411/66721901-ce9ba780-ee07-11e9-897d-c1780e37d9fb.png)

**What should happen:** the normal well texture

**Comment by Rushor** [comment]
model fixed with next update

**Comment by hediunchained** [comment]
still a cube without model even after the update

**Comment by Rushor** [comment]
okay the corescript was overwriting the model. readded the model on spawn 

![I](https://i.imgur.com/cz0P1nE.jpg)
