### ISSUE TITLE
[Core] Character stuck - Teleport to Graveyard

### ISSUE THREAD

**Issue by Tigerief** [WoWManiaUK/Blackwing-Lair#3611]
**What is happening:**
Character will be tpd to hearthstone location, however if hearthstone is on cd, character will be killed instead.

**What should happen:**
Character should either be tpd to the area that they started the game at ie the lvl 1 spot or to their hearthstone depending on how you guys want the server to be working.

**Comment by Echinaceax** [comment]
Confirmed by me @Rushor :)

![unstuck option](https://user-images.githubusercontent.com/39439201/66722006-10791d80-ee09-11e9-8bf9-d22a3e3e7ac2.jpg)

Killed me in Dala and dindnt port me to graveyard :)

**Comment by APTX4869s** [comment]
But I think that how it should work
![CD stuck](https://user-images.githubusercontent.com/55243287/66722033-2b07c280-ee1a-11e9-9b63-eb76e24561c0.png)

when you die you can release as spirit.

**Comment by Echinaceax** [comment]
@APTX4869s 
if you slide down a cliff for instance and dont die but cant get back up it shouldnt insta kill you when you stand though :)

Mania you go to lvl1 zone

**Comment by APTX4869s** [comment]
@Echinaceax 
 if we gonna get tped to our hs then that's great. I wouldn't mind with that feature.

**Comment by Echinaceax** [comment]
not want i mean @APTX4869s 
that HS only works if your HS isnt on CD :)

**Comment by Rushor** [comment]
will make it like in wow mania then. teleport to the start loacation.

**Comment by Rushor** [comment]
fixed with next update
