### ISSUE TITLE
[Quest] Further concerns - Elwynn Forest

### ISSUE THREAD

**Issue by Tigerief** [WoWManiaUK/Blackwing-Lair#3612]
**Links:**
https://classic.wowhead.com/quest=35/further-concerns

**What is happening:**
Quest can be accepted from npc and then he makes you walk yourself to Guard Thomas.

**What should happen:**
Quest Giver should have chat option to ride a horse towards Guard Thomas to make me feel like a lvl 20 player for a solid minute.

**Comment by Rushor** [comment]
ID - 78852 Call Stormwind Charger

**Comment by Rushor** [comment]
fixed with next update

![I](https://i.imgur.com/WVDXxfN.jpg)
