### ISSUE TITLE
[Quest] Franks and Beans - Redridge mountain

### ISSUE THREAD

**Issue by Tigerief** [WoWManiaUK/Blackwing-Lair#3613]
**Links:**
https://www.wowhead.com/quest=26506/franks-and-beans
**What is happening:**
Item drop rate from Goretusks is also very low

**What should happen:**
Should be 100% drop rate on all 3 mobs

**Comment by Rushor** [comment]
Thanks will Adjust that.
Can you may combine All those Kind of report to one? :)

**Comment by Rushor** [comment]
chance adjusted with nextupdate

**Comment by Tigerief** [comment]
> Thanks will Adjust that.
> Can you may combine All those Kind of report to one? :)

What do you mean combine to one? do 1 big report of several quests?

**Comment by Rushor** [comment]
one report per quest is fine. i mean combien all kind of wrong quest item drops to one. 
the other require one ticket / issue :)
