### ISSUE TITLE
Hunter -  [Deterrence] - ID : 19263 : You should not be able to Attack

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3614]
**Links:**
http://www.cavernoftime.com/spell=19263

**What is happening:**

When Deterrence is Active you can Attack and use Abillities,

**What should happen:**

You should not be able to use Abilities or Attack at all.

**Comment by Rushor** [comment]
setting pacified should fix that

**Comment by Rushor** [comment]
all visual and damage reduce also fixed!

![I](https://i.imgur.com/yGouRXo.jpg)
