### ISSUE TITLE
[NPC] Exiled Mage

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3618]
**Links:**

https://www.wowhead.com/npc=47552/exiled-mage

![mage tol](https://user-images.githubusercontent.com/39439201/66770958-2c3bfc80-eeb9-11e9-8a19-f4fa253f625e.jpg)

**What is happening:**
- very low dmg

**Comment by Rushor** [comment]
in futre you can combine all kind of those reports to one :)

**Comment by Echinaceax** [comment]
> in futre you can combine all kind of those reports to one :)

Its hard to know, we was always told to make single reports :)
but yes ofc i will in the future @Rushor

**Comment by Rushor** [comment]
thank you <3
