### ISSUE TITLE
[Flight Path] Aerie Peak - Hinterlands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#362]
NPC - https://www.wowhead.com/npc=8018/guthrum-thunderfist
The Flight path at **Aerie Peak** [unable to find map location ID] in hinterlands doesn't work. Iv secured the location however you cannot fly to or from this location to any previous or new flightpaths secured, and when you click to see the actual flight path doesn't register the flight location.
![world of warcraft 04_01_2019 12_22_28_li](https://user-images.githubusercontent.com/42302580/50688427-62d91280-101d-11e9-9f70-0eabf597a782.jpg)
![world of warcraft 04_01_2019 12_22_36](https://user-images.githubusercontent.com/42302580/50688433-666c9980-101d-11e9-91f0-a0357016d2c9.png)

**Comment by sarahkay88** [comment]
I ran to the next flight location on my map to see if this was a visual bug and still it doesn't show from different flight locations.
![world of warcraft 04_01_2019 12_27_03_li](https://user-images.githubusercontent.com/42302580/50688507-a92e7180-101d-11e9-9272-0fc02ac710b9.jpg)

**Comment by Echinaceax** [comment]
yes on horde..there are only 2 flight paths showing on map, so didnt go to Aerie Peak myself

**Comment by sarahkay88** [comment]
Aerie peak is ally :)

**Comment by Echinaceax** [comment]
Ah - that makes sense that its not seen for me on map  :)

**Comment by sarahkay88** [comment]
Maybe it's just my flight paths but I still can't see the flight path, or fly too or from the location last checked yesterday.

**Comment by Dranah** [comment]
[https://imgur.com/xiHikUy](url)
