### ISSUE TITLE
[Quest] The Imprisoned Archmage - Tol Barad

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3623]
**Links:**
https://www.wowhead.com/quest=28118/the-imprisoned-archmage

![gate locked](https://user-images.githubusercontent.com/39439201/66771680-35c66400-eebb-11e9-9677-1fe28bd489be.jpg)

**What is happening:**
- Ally have control of Baradin Hold, but the gate to this quest is locked
so cant complete the quest

**What should happen:**
_You must kill Archmage Galus and return with his Staff from the Cursed Depths, just east of Baradin Hold._

**Comment by Rushor** [comment]
it is random which block is active, but i will open them all in order to do the quests.
