### ISSUE TITLE
[Spell] Warlock Shadowburn - No soulshards

### ISSUE THREAD

**Issue by Tigerief** [WoWManiaUK/Blackwing-Lair#3624]
**Links:**

https://classic.wowhead.com/spell=17877/shadowburn

**What is happening:**
Ability just functions as a damage spell usable on < 20% hp targetss

**What should happen:**
The effect of killing the target with the spell or the 5 sec debuff grants NO soulshards at all

**Comment by Rushor** [comment]
http://cata.cavernoftime.com/spell=17877

**Comment by Rushor** [comment]
i have a fix for that

**Comment by Rushor** [comment]
![I](https://i.imgur.com/IHarAEK.jpg)

fixed only works on isHonorOrXPTarget and if target is killed by death.

**Comment by Tigerief** [comment]
yes it is supposed to work like that :) ty Rush
