### ISSUE TITLE
[Core] Shift + left clicking does not always display player's information

### ISSUE THREAD

**Issue by Tigerief** [WoWManiaUK/Blackwing-Lair#3625]
**What is happening:**
![WoWScrnShot_101519_114217](https://user-images.githubusercontent.com/16594771/66820678-749efd00-ef41-11e9-9da6-c5b71297c53c.jpg)
It usually shows 0 Players found when the player is STILL online. Sometimes it does work on players but not always
![WoWScrnShot_101519_114725](https://user-images.githubusercontent.com/16594771/66820784-9a2c0680-ef41-11e9-9bfe-d6212af59351.jpg)
It appears that it is only working on players in your guild.

**What should happen:**
The above displayed information must be displayed instead of 0 Players found on players not in your guild

**Comment by Rushor** [comment]
this is faction related i guess because of crossfaction chat. intended :>

**Comment by Tigerief** [comment]
omg! that explains why didnt think of it
