### ISSUE TITLE
[Object] I want to learn smelting Dark Iron.

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Blackwing-Lair#3626]
Spectral Chalice will now have a gossip to learn Smelt Dark Iron once quest http://cata.cavernoftime.com/quest=4083 is rewarded.

**Comment by Rushor** [comment]
okay fixed with next update
![I](https://i.imgur.com/0AujOjJ.jpg) on quest reward
if quest is already rewarded, gossip for learning is added 

![I](https://i.imgur.com/chzZdNU.jpg)

**Comment by Echinaceax** [comment]
@Rushor has this fix fixed this too then #3415 ?

**Comment by Rushor** [comment]
Yes thanks. Closed the other issue :)
