### ISSUE TITLE
[Quest] To New Thalanaar - 25479 - Dustwallow Marsh

### ISSUE THREAD

**Issue by Druhl** [WoWManiaUK/Blackwing-Lair#3628]
https://www.wowhead.com/quest=25479/to-new-thalanaar

What should be happening:
- should be able to interact with flightmaster at Mudsprocket to get free trip to New Thalanaar in east Feralas (not a regular flight point)

What is happening:
- this option is not offered

Also:
- after making my own way to New Thalanaar to target NPC of quest (https://www.wowhead.com/npc=39946/caryssia-moonhunter), she won't accept my quest for completion; has grey question mark only, "Complete Quest" button non-functional

**Comment by Rushor** [comment]
already fixed on live
