### ISSUE TITLE
[NPC] - Deepmoss Webspinner - spawn out of area

### ISSUE THREAD

**Issue by Druhl** [WoWManiaUK/Blackwing-Lair#3630]
https://www.wowhead.com/npc=4006/deepmoss-webspinner

This is very low priority, but FYI there is one on Fizzle & Pozzik's Speedbarge in Thousand Needles.

![WoWScrnShot_101519_115219](https://user-images.githubusercontent.com/19803911/66871568-ea22c180-ef71-11e9-8cd5-d7f02f7f91a5.jpg)

**Comment by Druhl** [comment]
Also, generally - do you want this type of thing reported? I've seen other similar things, but know there are much more important issues.

**Comment by Echinaceax** [comment]
Still needs report yes thank you @Druhl

**Comment by Rushor** [comment]
@Druhl you can combine all those kind of report to one single report :)

f.ex. creatures xy missplaced at position yx :)

fixed that issue now
