### ISSUE TITLE
[Raid] Bastion of Twilight - Teleport

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#3631]
**What is happening:**
The teleport to the bosses zones is not working.

**What should happen:**
After you kill a boss, you should be able to teleport directly close to the next boss from the portals in the hall right after the entrance. It would be nice to fix them because if you wipe during the Cho'gall encounter, you need to walk at least for 4 minutes to reach again his room.

**Comment by Rushor** [comment]
do you now the name for those objects?

**Comment by Sammy974** [comment]
Nope atm, i need to enter bot to tell you... I will check

**Comment by Rushor** [comment]
okay
i need a screenshot of that and maybe a vid that shows me how it works

**Comment by Sammy974** [comment]
I'm trying to get some info, but it's not easy. To remember how the original portals worked is hard as well :) so... We can do it this way: 
As you enter the zone, there are 4 portals spawned and not clickable on the 4 corner of the big hall at the entrance. You need to kill Halfus and Valy+Thera in order to make the portals become clickable. If you click on the portals (or just one or two, as you want) you'll be teleported in the Valy+Thera room. That's all. It would make us save some time we spend walking if we wipe at Council or Cho'gall encounters.
Sadly the name and id of the portals isn't in the NPC and object list in wowhead. Next time i enter the zone i will take a screenshot and try to discover something more about them ;)

**Comment by Rushor** [comment]
teleport fixed now.
https://i.imgur.com/tVLJk5Q.jpg

based on which boss was killed, you will get ported to it's hall.

**Comment by Sammy974** [comment]
Great! Thank you ^^
