### ISSUE TITLE
[Server/Feature] New command to reset players instance cooldown

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Blackwing-Lair#3639]
Implemented a command (GMS) to force server reset players instance cooldown.

> .instance resetglobalcooldown

Tip: Reset all cooldown related with Dungeon/Raids

**Comment by Echinaceax** [comment]
@Keader GM info given 
He said that command used worked and showed on screen as command working, but players ID locks didnt get reset

Also: One player deleted cache and retested it for GM and still no reset

**Comment by Slydee23** [comment]
are you sure :D ?

**Comment by Keader** [comment]
We found a problem here haha.
My command is working only for online players ✌️ 
I will try fix to work for all server and janitor can send to live realm tomorrow.
