### ISSUE TITLE
[NPC] Innkeeper Roman Gamer/Garner - ID 47857 - Western Plaguelands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#364]
https://www.wowhead.com/npc=47857/roman-garner

- Doesn't open supply window
- Also noticed, the NPC name on my SS is Roman Gamer and wowhead hes named Roman-Garner.
- Name could be just the writing merging ofc

![innkeeper roman gamer](https://user-images.githubusercontent.com/39439201/50689275-493dc800-1029-11e9-9301-6269e3851f4a.jpg)

**Comment by Kitzunu** [comment]
This NPC does not sell things
![image](https://user-images.githubusercontent.com/24550914/55888310-70b7aa00-5baf-11e9-8cc7-0ce65e26fcc9.png)

The name is correct, however there was a double spawn which I fixed

**Comment by Echinaceax** [comment]
@Kitzunu - no creature found with name or with ID 
server restart maybe ?

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/55980945-e5fdaa80-5c95-11e9-83b1-993fab8b74e7.png)

**Comment by Echinaceax** [comment]
@Kitzunu i re edited it too "Doesn't open supply window"
