### ISSUE TITLE
[Spell/Hunter] Camouflage - Spell ID: 51753

### ISSUE THREAD

**Issue by dxbali** [WoWManiaUK/Blackwing-Lair#3640]
**What is happening:**
The character and its pet gain camouflage effect, however, it is canceled when the character move. When stationary the character and its pet do not gain stealth effect.

**What should happen:**
Both the character and pet should be in stealth mode when stationary. Camouflage should not be canceled if the character is moving

**Comment by Rushor** [comment]
ID - 51753 Camouflage
Interrupt Flags: 0x00000002, AuraIF 0x000A0403, ChannelIF 0x00000000

**Comment by dxbali** [comment]
I'm sorry it seems stealth works fine. but only the problem resides with camouflage being canceled when moving

**Comment by Rushor** [comment]
yes man, and those flags seem to trigger that behaviour :>

**Comment by dxbali** [comment]
Its not fixed correctly... now we get stealth wither we are stationary or not ... we should get stealth only when stationary

**Comment by dxbali** [comment]
We are not going further if every spell takes 2 reports to get it fixed. You can test it before applying the fix

**Comment by Keader** [comment]
Is scripted based on sniffs (copy of Blizzard packets).
