### ISSUE TITLE
[NPC] Howling Riftdweller (spacing) - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3642]
**Links:**

https://www.wowhead.com/npc=39844/howling-riftdweller

![howling](https://user-images.githubusercontent.com/39439201/66949340-a1910400-f056-11e9-8e3b-71e36a553a0d.jpg)

**What is happening:**
- Need spacing only (31) needed

**Comment by Rushor** [comment]
all done
