### ISSUE TITLE
[NPC] Leyden Copperkleist (phasing) - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3643]
**Links:**
https://www.wowhead.com/npc=39846/leyden-copperkleist

![leyden](https://user-images.githubusercontent.com/39439201/66950278-5677f080-f058-11e9-8516-a4403750a9fe.jpg)

**What is happening:*
- Meant to be 3 but not all seen at the same time
- can see 2 atm 

**What should happen:**
one missing plus phasing

**Comment by Rushor** [comment]
also aggro text added. only one should be there. the other spawns from wowhead are wrong.


By EleanorKT (322 – 1·3) on 2010/12/25 (Patch 4.0.3)
This guy is a clear reference to the Leyden Jar, a bottle used to store electricity (and the ancestor of the capacitor).
