### ISSUE TITLE
[NPC] Shivan Destroyer (low dmg) - Tol barad

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3645]
**Links:**
2 different names for same ID 
https://www.wowhead.com/npc=47540/shivarra-destroyer
https://cata-twinhead.twinstar.cz/?npc=47540#abilities

![shivan](https://user-images.githubusercontent.com/39439201/66963304-a31cf500-f073-11e9-98e8-af0ef006f052.jpg)

**What is happening:**
-  name are different from wowhead and twinhead
- low dmg

**Comment by Rushor** [comment]
dot damage is now like the periodic damage 

![I](https://i.imgur.com/hTeidiP.jpg)
