### ISSUE TITLE
[NPC] Cell Watcher (0 dmg) - Tol Barad

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3647]
**Links:**

https://www.wowhead.com/npc=109935/cell-watcher#abilities

![cell watcher](https://user-images.githubusercontent.com/39439201/66963734-b11f4580-f074-11e9-8fee-47729812af2b.jpg)

**What is happening:**
- 0 dmg

**Comment by Rushor** [comment]
http://cata.cavernoftime.com/npc=47542

**Comment by Rushor** [comment]
the spell that does no damage is wrong added - need to remove

**Comment by Rushor** [comment]
![I](https://i.imgur.com/dE9MhZY.jpg)
