### ISSUE TITLE
[Enginnering] Grounded Plasma Shield - Tinker

### ISSUE THREAD

**Issue by Venom64bit** [WoWManiaUK/Blackwing-Lair#3655]
**Links:**

https://www.wowhead.com/spell=84427/grounded-plasma-shield

**What is happening:**
do nothing

**What should happen:**
Active a shield that absorbs 18000 damage

**Comment by Rushor** [comment]
it should have more effects

SPELL_PLASMA_SHIELD_ABSORB  = 82627,
    SPELL_PLASMA_PAINFUL_SHOCK  = 82407,
    SPELL_PLASMA_SHIELD_MAGNETIZED = 82403,
    SPELL_PLASMA_SHIELD_REVERSE_SHIELD = 82406,

https://www.wowhead.com/spell=84427/grounded-plasma-shield#comments


Bind this to Icebound Fortitude for DK tanks. Then, you either get the shield, nothing happens(you'll be immune if it tries to stun you) or essentially the IBF gets negated for the purposes of incoming melee.

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/BhB9c2I.jpg)
