### ISSUE TITLE
[NPC] Twilight Slave (Triples / spacing) - Mount Hyjal 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3657]
**Links:**

https://www.wowhead.com/npc=39431/twilight-slave

![twilight slaves](https://user-images.githubusercontent.com/39439201/67019238-9ee8ea00-f0fc-11e9-8bd7-b3b6873fa18c.jpg)

**What is happening:**
- Triples / spacing

**Comment by Rushor** [comment]
ah yeah that is actually intended. should always be 3. but because of the follow animation they stuck inside each other. not a real issue :> this affects all creatures with core followig sadly

**Comment by Kitzunu** [comment]
I don't know if the core script has anything else but the following formation, but if not, wouldn't it just be possible to remove core script and make a creature_formation instead? O.o
