### ISSUE TITLE
Shaman - Spirit Wolves - Spirit Hunt - ID : 58877 not working.

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3658]
**Links:**
http://cata.cavernoftime.com/spell=58877

other proof
https://www.wowhead.com/spell=58877/spirit-hunt#changelog
http://prntscr.com/pkrj6m
from WoWHead or our Armory

**What is happening:**

My Spirit wolves dont heal me for 150% of damage done

**What should happen:**

my spirit wolves should heal me for 150% dmg done as mentioned in the link via Spirit Hunt (58877)

**Comment by Rushor** [comment]
![I](https://i.imgur.com/ECOqCQc.jpg)

done

also: if Glyph of Feral Spirit is on player he will get 40 % more heal.

**Comment by Slydee23** [comment]
why 40% ? glyph only gives 30% AP to Wolves
