### ISSUE TITLE
[NPC] Benjamin Henderson

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#366]
NPC - https://www.wowhead.com/npc=47717/benjamin-henderson#comments Can be used but just wanted to highlight that he is displayed has dead.

![world of warcraft 04_01_2019 13_24_19](https://user-images.githubusercontent.com/42302580/50690197-5efcbe80-1024-11e9-83de-e1e794d05d4c.png)
 And that there is 2 of them. both vendor highlighted on the mini map are the same vendor a few feet apart

**Comment by Rushor** [comment]
remove one creature there, remove dead flag
