### ISSUE TITLE
[Hunter/Talent] Toxicology | Talent ID: 9464

### ISSUE THREAD

**Issue by dxbali** [WoWManiaUK/Blackwing-Lair#3661]
**What is happening:**
Toxicology is not working properly as the attachment shows

![Arrow1](https://user-images.githubusercontent.com/53133852/67113596-fb2a3780-f1ea-11e9-834b-2456589dcad1.jpg)
![Arrow2](https://user-images.githubusercontent.com/53133852/67113685-2c0a6c80-f1eb-11e9-8f22-79313400183b.jpg)

**What should happen:**
The periodic damage crit should be increased by 100%.

![Toxic](https://user-images.githubusercontent.com/53133852/67113772-61af5580-f1eb-11e9-8d44-348874ead522.jpg)

**Comment by Slydee23** [comment]
Apply Aura: Modifies Critical Strike Damage (15)
Value: 100%

 for me it looks right 

2k non crit 
6k crit 
means 200% Crit dmg

**Comment by dxbali** [comment]
What you're saying is kinda true, so let's leave it for @Keader  to confirm if it is working right or not

**Comment by Slydee23** [comment]
yeah im not 100% sure better he check again

**Comment by Keader** [comment]
Working correctly.
