### ISSUE TITLE
[Hunter\Spell] Explosive shot | Spell ID: 53301

### ISSUE THREAD

**Issue by dxbali** [WoWManiaUK/Blackwing-Lair#3662]
**What is happening:**
The crit damage of Explosive shot (The instant + DoT) are doing way more damage than should be.

![Arrow3](https://user-images.githubusercontent.com/53133852/67114000-eac68c80-f1eb-11e9-9c73-b9f1aae6e685.jpg)

**What should happen:**
The Explosive damage and DoT(Damage over time) crit should be 100% of the normal damage

**Comment by Slydee23** [comment]
can confirm the Crits are like 300% Dmg

**Comment by Keader** [comment]
Fixed.
