### ISSUE TITLE
[Dungeon] Blackfathom Deeps  - Ashenvale 

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#3663]
**Links:**

[Blackfathom Deeps](https://www.wowhead.com/quest=26897) - Quest ID: 26897
[Sentinel Aluwyn](https://www.wowhead.com/npc=33260/sentinel-aluwyn) - NPC ID: 33260
[Altar of the Deeps](https://vanilla-twinhead.twinstar.cz/?object=103016) - Ovject ID: 103016

**What is happening:**

[Sentinel Aluwyn](https://www.wowhead.com/npc=33260/sentinel-aluwyn) - Missing!
[Altar of the Deeps](https://vanilla-twinhead.twinstar.cz/?object=103016)  - Don't work!
**What should happen:**

[Sentinel Aluwyn](https://www.wowhead.com/npc=33260/sentinel-aluwyn), 
should be at the beginning like this.
![image](https://user-images.githubusercontent.com/6819293/67132339-e65c9c80-f208-11e9-89e3-d876e833252d.png)

[Altar of the Deeps](https://vanilla-twinhead.twinstar.cz/?object=103016) 

 - (Alliance)
 - The Altar's changed location warps you to Darnassus. As well as giving you the Blessing of  Blackfathom for a hour.

- (Horde)
- just gives you the debuff but doesn't teleport you away.

**Comment by Rushor** [comment]
- Altar of the Deeps will give buff
- Morridune will spawn and offer Alliance players teleport to Darnassus
- teleport poss corrected.

http://wowwiki.wikia.com/wiki/Morridune
http://www.wowhead.com/npc=6729/morridune#comments
http://www.wowhead.com/npc=6729/morridune#screenshots:id=156418
http://www.gitrknowswow.com/2008/05/28/the-blackfathom-deeps-alliance-quests/

**Comment by Rushor** [comment]
She is inside Blackfathom Deeps Dungeon as you enter along with 3 other quest givers.

These Npc's are :

1) Sentinel Aluwyn

2) Sentinel - Trainee Issara

3) Relwyn Shadestar

4) Ashelan Northwood

Note : These quests did not count towards the Ashenvale Quests Achievement .

Majestica - Kul Tiras

**Comment by Rushor** [comment]
object and teleport fixed.

spaws will be fixed later.

**Comment by Rushor** [comment]
Links:
https://www.youtube.com/watch?v=2gIOf4h_KQY
from WoWHead or our Armory

**What is happening:**¨

https://www.wowhead.com/npc=33261/sentinel-trainee-issara should spawn and give
https://www.wowhead.com/quest=26885/knowledge-in-the-deeps

https://www.wowhead.com/npc=33258/relwyn-shadestar should spawn and give
https://www.wowhead.com/quest=26884/researching-the-corruption

https://www.wowhead.com/npc=75607/ashelan-northwood Should spawn and give
https://www.wowhead.com/search?q=in+search+of+thaelrid

https://www.wowhead.com/npc=4787/scout-thaelrid Should give the quest
https://www.wowhead.com/quest=26882/blackfathom-villainy

What should happen:

Missing npcs for some quests in the dungeon .
Scout Thaelrid is there but not giving a quest.

**Comment by Rushor** [comment]
**Links:**
https://www.wowhead.com/quest=824/jeneu-of-the-earthen-ring
https://www.wowhead.com/npc=12736/jeneu-sancrea
from WoWHead or our Armory

**What is happening:**
You have been asked to bring an item to Je'neu Sancrea who is standing in the Blackfathom Deeps. He isn't there.


**What should happen:**
The npc must placed.

Pitsecond: ORC warlock

**Comment by Rushor** [comment]
**Links:**
https://www.wowhead.com/quest=26897/blackfathom-deeps
https://www.wowhead.com/npc=3845/shindrell-swiftfire
https://www.wowhead.com/npc=34122/commander-grimfang
from WoWHead or our Armory

**What is happening:**
The quest is handed to me by Commander Grimfang, it is an alliance quest. He should be handed by Shindrell Swiftfire. 


**What should happen:**

Repair.

Pitsecond: ORC warlock

**Comment by Jimpaa** [comment]
My findings in Blackfathom deeps was alliance only. I went to same entrance on dev as horde and no npc was there but cant confirm on live since i dont have a horde toon. 

Below is the npc and quests that i found horde is missing.

 https://www.wowhead.com/npc=12736/jeneu-sancrea should spawn and give 
https://www.wowhead.com/quest=26888/nightmare-of-the-deeps
https://www.wowhead.com/quest=26891/amongst-the-ruins

https://www.wowhead.com/npc=74409/zeya should be there and give the quest
https://www.wowhead.com/quest=26892/deep-in-the-deeps

**Comment by Rushor** [comment]
https://www.wowhead.com/npc=75607/ashelan-northwood Should spawn and give
https://www.wowhead.com/search?q=in+search+of+thaelrid

is added in patch 6.x  - we do not need to add him

**Comment by Rushor** [comment]
all added https://i.imgur.com/5D1d83I.png https://i.imgur.com/X3Ypqz6.jpg
