### ISSUE TITLE
[Item] Fandral's Flamescythe 

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#3664]
**Links:**

[Fandral's Flamescythe ](https://www.wowhead.com/item=171648/fandrals-flamescythe) - Item ID: 171648
[Druid of the Flames](https://www.wowhead.com/spell=99245/druid-of-the-flames)  -  Spell ID: 99245

[Fandral's Flamescythe ](https://www.wowhead.com/item=171648/fandrals-flamescythe) gives you the [Druid of the Flames](https://www.wowhead.com/spell=99245/druid-of-the-flames) but don't turn your cat form in the flame on. heroic version too

**Comment by Priestelar** [comment]
@Rushor low prio, this is an item released in 4.2 with firelands https://www.wowhead.com/item=69897/fandrals-flamescythe

**Comment by Rushor** [comment]
uuuh fixed. this is BOOM

be in catform > use item > boom transform

![I](https://i.imgur.com/rdVqlDX.jpg)
