### ISSUE TITLE
[Spell] Ghost Wolf - Shaman

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#3665]
**Links:**

[Ghost Wolf](https://classic.wowhead.com/spell=2645/ghost-wolf)

**What is happening:**

you can use it  "inside"

**What should happen:**

Can only be used outdoors

![image](https://user-images.githubusercontent.com/6819293/67133181-06da2600-f20c-11e9-8ec0-8dfc05abda02.png)

**Comment by dxbali** [comment]
Can you provide proof to what you are claiming???

**Comment by Echinaceax** [comment]
yes here https://classic.wowhead.com/spell=2645/ghost-wolf

![yes here](https://user-images.githubusercontent.com/39439201/67133534-8d433780-f20d-11e9-86f9-a932e078a3f9.jpg)

**Comment by dxbali** [comment]
And who says this applies to cata

**Comment by Xman993** [comment]
@dxbali because is a "travel form" and on all expansions applies

**Comment by Echinaceax** [comment]
https://cata-twinhead.twinstar.cz/?spell=45528 cata

**Comment by Echinaceax** [comment]
He knows to do research his one of your server testers ;)

**Comment by Nacho-k** [comment]
I dont know if this matters, but i saw a comment in wowhead that says this "Currently on the Beta of Cataclysm, Ghost Wolf is usable indoors as well as outdoors", it probably didnt get to the actual expasion but its worth checking it out.

**Comment by Nacho-k** [comment]
From: https://wowwiki.fandom.com/wiki/Ghost_Wolf
Patch 4.0.1 (12-Oct-2010): Can now be used indoors.

**Comment by Slydee23** [comment]
https://www.wowhead.com/spell=2645/ghost-wolf

**Comment by Xman993** [comment]
people can make mistakes, so don't be salty. <3

**Comment by Echinaceax** [comment]
> Wrath-Logo-Small/Cataclysm-Logo-Small Patch 4.0.1 (12-Oct-2010): Can now be used indoors.

Is good enough for me @Nacho-k @Slydee23 

Thank you all for your research too

**Comment by Slydee23** [comment]
@Xman993  not salty at all :D shit happens just dont want more work for kaedar if not necessary
