### ISSUE TITLE
[General] Character stuck on flightpath mount

### ISSUE THREAD

**Issue by Ashwarwell** [WoWManiaUK/Blackwing-Lair#3667]
Same problem as described before but on a different path. I believe it may occur at every path that includes Ghostlands but i didn't check it. Check the links below for screenshots.

https://gyazo.com/a2b67facdb94829db25f4639f2787022

https://gyazo.com/5e5b28aad110c20ebf5464779a9c7f54

**Comment by Rushor** [comment]
moved to https://github.com/WoWManiaUK/Blackwing-Lair/issues/3660
