### ISSUE TITLE
Tormented Dead / Wailing Dead (low HP) - Twilight Highlands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3668]
**Links:**
https://github.com/WoWManiaUK/Blackwing-Lair/issues/1869#issuecomment-530489910

> Everyone uses this area to farm xp because they ghosts are super easy to kill and give an easy 11k xp per kill making farming 83-85 pretty quick with the messed up respawn timers.

@Rushor 
comfirmed about the low HP on those mobs 

https://cata-twinhead.twinstar.cz/?npc=47824
![tormented dead](https://user-images.githubusercontent.com/39439201/64724481-dc8d9e00-d4d2-11e9-9c6e-aee2fb1008bb.jpg)

https://cata-twinhead.twinstar.cz/?npc=47823
![wailing dead](https://user-images.githubusercontent.com/39439201/64724644-2aa2a180-d4d3-11e9-911a-891ec9cc9d1e.jpg)

**Comment by Rushor** [comment]
will remove XP gain from them on kill. thanks.
