### ISSUE TITLE
[SPELL] pally aura

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3669]
**Links:**
crusader aura -https://cata-twinhead.twinstar.cz/?spell=32223
pursuit of justice - https://cata-twinhead.twinstar.cz/?spell=26023

**What is happening:**

retro pallys with pursuit of justice talent gain 15% movement speed. if they use crusader aura ( which give 20% movement speed whilst mounted) this over rides it (as it should). however the issue lays that when players remove the aura the talent doesnt revert back to there 15% movement speed without players having to relog

**What should happen:**
Talent should revert back after aura is removed. players shouldn't need to relog

**Comment by Nacho-k** [comment]
Thanks for posting it, didnt know if i should do it now or wait for keader to respond on the other post.

**Comment by sarahkay88** [comment]
nps

**Comment by Keader** [comment]
Same issue of #3666
