### ISSUE TITLE
[Quest] Brute Strength - Horde version - Missing prerequisite - Western Plaguelands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#367]
Quest - https://www.wowhead.com/quest=27117/brute-strength

Objective - https://www.wowhead.com/npc=44317/the-ravenian
Objective - https://www.wowhead.com/npc=44318/rattlegore

**Ally quest**
https://www.wowhead.com/quest=27163/brute-strength

**Ally Quest** 
https://www.wowhead.com/quest=27163/brute-strength

- Both are Alliance quest (quest chain)  
- i could pick "The Ravenian" quest up and now i cant hand it back in, 
- An Elite kills me.

![cant hand it in](https://user-images.githubusercontent.com/39439201/50693223-a68c4600-1036-11e9-8c31-d1373929ca30.jpg)
 
![brute stregth](https://user-images.githubusercontent.com/39439201/50693382-113d8180-1037-11e9-9021-b78e785e99eb.jpg)

**Comment by Echinaceax** [comment]
Edited to add more info
- Angel (ally Contributor) updated me that the Ally start of chain quest is not completable.
Quest - https://www.wowhead.com/quest=27161/the-endless-flow

**Series**
1. | The Endless Flow 
2. Scholomancer
3. Brute Strength
4. Araj the Summoner
5. Victory, For Now
Go Fletch!

**Comment by Echinaceax** [comment]
- Horde, i have got the quest back from both NPCs 
- Koltira Deathweaver
-  NPC Koltira Deathweaver is in both location as seen in SS
https://www.wowhead.com/npc=44452/koltira-deathweaver

![quest back](https://user-images.githubusercontent.com/39439201/50694535-69c24e00-103a-11e9-9131-a1c57d85fe47.jpg)

**Comment by Dranah** [comment]
SUMMARY:

https://www.wowhead.com/quest=27117/brute-strength
Should have prerequisite: https://www.wowhead.com/quest=26922/the-endless-flow
