### ISSUE TITLE
[Horde] Using Enchanted Conch Crashing the Server !

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3672]
**Links:**
https://www.wowhead.com/item=56227/enchanted-conch

https://www.wowhead.com/quest=25936/pay-it-forward
from WoWHead or our Armory

**What is happening:**

using the item seems to crash the server you can look in #world in DIscord 

only on Horde side !
**What should happen:**

**Comment by Rushor** [comment]
was missing conditions
