### ISSUE TITLE
[Quest][Npc][Item][Core] Uldum quest order and more

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3673]
Quest order list: https://wow.gamepedia.com/Uldum_quests
1 – [Quest] [Npc] Easy Money  https://www.wowhead.com/quest=27003/easy-money#comments – None of the npcs related to the Caravan are currently spawned. Only really important one is the camel known as Lady since she is the one that progresses the quest’s cutscene but I have played on servers where they did not use the cutscene and upon clicking on lady the screen will fade to black and you will appear in the Lost City of Tolvir. Video of the quest here: https://youtu.be/A7OvUTKukIs 
^ Also see #1073

2 – [Quest] Traitors! https://www.wowhead.com/quest=27922/traitors - There should be a plant here that can be clicked in order to view the cutscene that completes this quest, atm there is nothing. Video of the quest here: https://youtu.be/4r3cpu64cHI See image below for the plant im refering too.
![197101-traitors-click-this-plant-to-hide](https://user-images.githubusercontent.com/16594771/67157176-dcca5600-f328-11e9-98a1-406a2230e44c.jpg)

^ Also see #1908
3 – [Quest] Smoke in their eyes! Quest is doable, however there are too few bales of hay as shown in this video: https://www.youtube.com/watch?v=dS-AVKxNllQ 
^ Also see #3538 

3 – [Quest] [Npc] Neferset Sentinel https://www.wowhead.com/npc=47306/neferset-sentinel#drops the quest associated to them: Budd’s plan https://www.wowhead.com/quest=27924/budds-plan is doable however there are only 3 guards in the area and also only about 2-3 armour pieces and there should be more Hay, Mobs and Armour pieces on the other sides of the area as shown in the screenshot below.
![WoWScrnShot_101819_193754_LI](https://user-images.githubusercontent.com/16594771/67157230-aa6d2880-f329-11e9-9173-aed59ef7ec23.jpg)

4 – [Quest] Escape from the lost city https://www.wowhead.com/quest=28112/escape-from-the-lost-city Quest should only be available after all the previous quests have been completed (see Quest order list) once accepting the quest a cutscene will play out and the player will be teleported to Ramkahen. Cutscene is shown in this video: https://www.youtube.com/watch?v=xvOGBcANHGA
^ Also see #3540

5 – [Quest] That gleam in his eye https://www.wowhead.com/quest=27899/that-gleam-in-his-eye quest should only be available after the quest with Harrison Jones: Do the Honors. https://www.wowhead.com/quest=27669/do-the-honors Adarrah is already offering the player this quest from when you can enter the zone.

6 – [Quest] Impending Retribution https://www.wowhead.com/quest=28134/impending-retribution - this quest should have a talk interaction available with the 3 npcs that it sends you too, however it does not.
^ Also see #2001

7 – [Quest] Venomous antidote https://www.wowhead.com/quest=28145/venomblood-antidote quest requires you to kill scorpions and use the item on their corpses, the quest item can just be used freely even while mounted in the air and you will collect blood samples.

8 – [Npc] Warlord Ihsenn https://www.wowhead.com/npc=47755/warlord-ihsenn#drops npc is not spawned with his mount :( 
^ Also see #3839 

9 – [Quest] Thieving little pluckers https://www.wowhead.com/quest=28250/thieving-little-pluckers quest works and is very much doable but, there are too few mobs spawned, HOWEVER this could be because the Ramkahen field workers are killing the mobs – they should not do damage with their attacks to them much like the Hyjal Wardens.

10 – [Quest] [Npc] Take it to em! https://www.wowhead.com/quest=27993/take-it-to-em At the moment there is nothing at the Tomb and Harrison Jones should be there thus the quest cannot be completed. Completing these quests will unlock all the ones around the Obelisk of the Sun however all of them are available by default (See Quest order list section). 
^ Also see #2005
IMPORTANT SIDE NOTE: Harrison Jones has several different phases, completing the quests will cause him to change phases and will become visible and the different locations based on which quest the player is on.
Also there are a lot of smoke textures coming out from the spot where Harrison should be and these textures should not be there at Khartut's tomb
11 – [Core] Above obelisk of the sun, the mobs tend to fall through the ground here.
![WoWScrnShot_101819_205409](https://user-images.githubusercontent.com/16594771/67157243-c5d83380-f329-11e9-9552-19c84db05aca.jpg)
![WoWScrnShot_101819_210038](https://user-images.githubusercontent.com/16594771/67157245-cbce1480-f329-11e9-9c0b-d34df2c3ee19.jpg)

12 – [Quest] Field work https://www.wowhead.com/quest=27179/field-work mobs don’t drop the quest item 100% of the time and there should be lootable quest items on the floor yet there is not. Quest can also not be turned in.

13 – [Quest] [Npc] Just the Tip, Elaborate disc https://www.wowhead.com/quest=27176/just-the-tip “Npc” is not available. Video of the quest + item is here https://www.wowhead.com/quest=27176/just-the-tip
^ Also see #3244

14 – [Core] these statues will attack you but there are not supposed to be mobs xD
![WoWScrnShot_101819_211304](https://user-images.githubusercontent.com/16594771/67157247-d7214000-f329-11e9-8f89-83fa9a129f12.jpg)

15 – [Core] there are several imps here but they should not be visible to players
![WoWScrnShot_101819_210919](https://user-images.githubusercontent.com/16594771/67157248-db4d5d80-f329-11e9-8580-d2919b145e5b.jpg)

16 – [Quest] By the Light of the Stars https://www.wowhead.com/quest=27549/by-the-light-of-the-stars Equipting the goggles does not show you lootable stars to complete the quest.
^ Also see #3075

17 – [Quest] Tipping the Balance https://www.wowhead.com/quest=27431/tipping-the-balance Quest is currently undoable, there should be a chat option with Harrison jones and then a cutscene, video of this here: https://youtu.be/9iWJkEZpTCU 
^ Also see #3074

18 – [Npc] Colossus of the sun AND moon duplicates are spawned beneath the ground. 
![WoWScrnShot_101819_222149](https://user-images.githubusercontent.com/16594771/67157252-f15b1e00-f329-11e9-8b9a-e1227884ad74.jpg)
^See 3792

19 – [Quest] [Item] The sceptre of Orsis – Quest item takes about 1-2 minutes to respawn, although its fine for someone playing alone, I know on a popular server this quest becomes really aggravating since you have competition and this quest is mandatory in order to unlock the rest of the zone. I suggest trimming it down.

20 – [Quest] Send word to Pharos https://www.wowhead.com/quest=27628/send-word-to-phaoris quest hand in does not have its cutscene implemented video of the cutscene here: https://www.youtube.com/watch?v=qcCx8pOugIY

21 – [Npc] Prince of Nadun in Ramkahen https://wow.gamepedia.com/Prince_Nadun This npc unlocks most of the other quests in the rest of the zone. More specifically the Vote quests.
The quest givers who you hand in the Vote quests (See Quest Order list) should only hand out their quests after you hand in their specific vote quest.

22 – [Npc] [Quest] Salhet https://www.wowhead.com/quest=28198/the-weakest-link Salhet’s location is not correct and there are other npcs supposed to be with him as seen in video: https://youtu.be/ujj74Pls0ZE

23 – [Quest] The element of supplies https://www.wowhead.com/quest=28200/the-element-of-supplies quest item drop rate is not 100% its very low actually. There are also not many crocodiles, the whole river should be crawling with them. This video should give some indication as there are usually in the middle and on the sides of the river https://youtu.be/KRorlm-wetg
^ Also see #3541 

24 – [Profession] There are very few Whiptails along the Vir’naal river when they should be teaming with them. https://www.wowhead.com/object=202752/whiptail

25 – [Quest] [Npc] Ancient Weapons https://www.wowhead.com/quest=27839/ancient-weapons#videos:id=72147 the mobs are currently spawning weirdly as you can see in this screenshot. Quest item is working! Video here for more visual clarity: https://youtu.be/vPBLY1sdtPc

26 – [Quest] [Npc] Shaping up https://www.wowhead.com/quest=28210/shaping-up upon entering the area, Salhet is supposed to spawn and he becomes a guardian for you to help fight the mobs. You can see in the screenshot on wow head and in this video how Salhet fights with the player https://youtu.be/qEPki5v1VCY  for your ease, I didn’t find any mentioning of Salhet having any abilities, it is described here https://wowwiki.fandom.com/wiki/Salhet that he only auto attacks but has a high miss chance. 
^ This quest cannot be turned in since Salhet as the guardian also becomes the turn in for the quest.
^ Also see #2198

27 – [Npc] These statues are also attacking players
![WoWScrnShot_101919_225747](https://user-images.githubusercontent.com/16594771/67157264-2e271500-f32a-11e9-9a26-20137ea83204.jpg)

28 – [Npc] Immortal Colossus, this mob’s ability does a TON of damage that it 1 shots anything.
![WoWScrnShot_102019_083052](https://user-images.githubusercontent.com/16594771/67157266-32533280-f32a-11e9-9a1c-c71996b773c7.jpg)

29 – [Quest] They don’t know what they’ve got here https://www.wowhead.com/quest=27901/they-dont-know-what-theyve-got-here the chests don’t need a key to be unlocked.

30 – [Quest] Ignition https://www.wowhead.com/quest=27903/ignition at the moment, using the quest item does not do anything. See video of the quest here: https://youtu.be/FCCENmrnYHo
^ Also see #2163 
NOTED THAT 30 IS LISTED AS FIXED
31 – [Quest] [Item] https://www.wowhead.com/item=62483/a-i-d-a-communicator#dropped-by I could not get this to drop, also I could not find any of the Expedition members listed as one of the mobs that drop it.

Conclusion: 35/105 quests are completable from what I could fine, I checked every section and these were all I could find, I didn’t really bother with the A.I.D.A terminal. A player can maybe JUST barely reach lvl 84 or just have to grind a ton still for like 20% of the exp needed to get to lvl 84.
![WoWScrnShot_102019_092344](https://user-images.githubusercontent.com/16594771/67157271-4860f300-f32a-11e9-898f-0da1071c1564.jpg)

IMPORTANT NOTE: most of the mobs in this zone are doing little to no damage, even mobs that should be “hard bosses” as elite mobs did about 100-500 damage with their abilities and players have almost 50k hp at this stage. I think most mobs should be tested/checked to see if their damage is valid cause I had the easiest time in this zone killing mobs.
In my honest opinion the zone is not too bad at the moment, Deepholm should take priority over this zone for now. Most of the quests are available before they should be and for that the Quest order list should be followed.
I could not find any rare spawns whilst I was in this zone, uncertain if they are available at the moment.
This concludes my report of Uldum, if you have any questions/concerns please ask me :)

**Comment by Priestelar** [comment]
23 - https://github.com/WoWManiaUK/Blackwing-Lair/issues/3541#issuecomment-538758451

**Comment by Priestelar** [comment]
Update:
18 - FIXED see #3792
23 - FIXED see #3541

**Comment by Echinaceax** [comment]
### New info on recently added NPC 

@Rushor 
quest giver https://www.wowhead.com/npc=47159/commander-schnottz
quest giver https://www.wowhead.com/npc=47670/belloc-brightblade

#2196 

https://github.com/WoWManiaUK/Blackwing-Lair/issues/4111
https://github.com/WoWManiaUK/Blackwing-Lair/issues/4117
https://github.com/WoWManiaUK/Blackwing-Lair/issues/4118

https://github.com/WoWManiaUK/Blackwing-Lair/issues/268#issuecomment-568199891 (this is wrong quest order too) 

### Hotfix 
_(2010-12-15): Players are no longer able to receive Efficient Excavations before completing N [83] Do the Honors._ #3092


these are from Schnottz's Landing listed here only obtainable via the https://wow.gamepedia.com/Efficient_Excavations quest drop fixed here #4100

https://wow.gamepedia.com/Uldum_quests  (Schnottz's Landing quest order)

![schnottz landing2 quests](https://user-images.githubusercontent.com/39439201/71310827-0848ea00-2419-11ea-916b-93434b79680f.jpg)

Quest order of these are messed up too

**Comment by Echinaceax** [comment]
### Also noticed **Priestelar** only listed up to **_"Shaping up"_** on this questline report.
 many more are missing from this list 

Salhet's Secret
Salhet the Tactician
Return to Camp
The High Priest's Vote
Trespassers in the Water
Stopping the Spread
The Defilers' Ritual #3076 
The Root of the Corruption
The Vizier's Vote
Tanotep's Son
Neferset Prison
The Pit of Scales
The High Council's Decision
Nahom Must Hold
The Secret of Nahom
Punish the Trespassers
The Cypher of Keset
The Defense of Nahom
The Curse of the Tombs
Artificial Intelligence
A Disarming Distraction #4296
Core Access Codes
Hacking the Wibson #1906
Gnomebliteration #4296
The Push Westward
Lieutenants of Darkness
Bleeding the Enemy
Salhet's Gambit
The Fall of Neferset City
Premature Explosionation #2005
field works #3093
Just the Tip #3244
On to Something
The Thrill of Discovery
Be Prepared #2336
By the Light of the Stars #3075 
Tipping the Balance #3074 
After the Fall #4050
Just a Fancy Cockroach
Do the Honors #3092
I've Got This Guy
They Don't Know What They've Got Here
Ignition #2163
Tailgunner! #2165
Eastern Hospitality
A Favor for the Furrier
The Desert Fox #4117 
Fashionism #2414
Idolatry #2159
Angered Spirits 
Gobbles! #4111
Make Yourself Useful #4118 
Crisis Management #268
Battlezone #4774
Missed Me By Zhat Much!
Lockdown! #4101
The Great Escape
Sending a Message #4101
Firing Squad #4101
Meet Me In Vir'sar
Friend of a Friend
Two Tents
Master Trapper
Unlimited Potential
Camel Tow
Reduced Productivity
Missing Pieces
Stirred the Hornet's Nest
Myzerian's Head
Shroud of the Makers
Schnottz So Fast
Bad Datas
I'll Do It By Hand
Sullah's Gift **(quest giver missing #4703 and quest back npc missing #4704**
Fire From the Sky #4704
See You on the Other Side! #4704
Fortune and Glory #4706 
Harrison Jones and the Temple of Uldum #4706
Put That Baby in the Cradle! #4707
Three if by Air #4708
The Coffer of Promise #4705 
The Heart of the Matter **(Brann Bronzebeard missing)** start quest for #2359 )
Penetrating Their Defenses #2359
Doing it the Hard Way #4709

**Comment by Echinaceax** [comment]
Made new quest order report  here #4711
