### ISSUE TITLE
[NPC] Painmaster Thundrak - Ashenvale

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#3676]
**Links:**

[Painmaster Thundrak](https://www.wowhead.com/npc=39096/painmaster-thundrak) - NPC ID: 39096
 [Enrage](https://www.wowhead.com/spell=33958/enrage) - Spell ID: 33958

**What is happening:**

- Does not use Spells

**What should happen:**
- Should use: [Enrage](https://www.wowhead.com/spell=33958/enrage)

**Relate to #3675**

**Comment by Rushor** [comment]
yeah he should get the enrage spell already at around 80 % HP
