### ISSUE TITLE
Tier 11 Holy Paladin 4p not working

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3677]
**Links:**
http://www.cavernoftime.com/spell=90313
http://www.cavernoftime.com/item=60362
from WoWHead or our Armory

**What is happening:**

does not giving any spirit 

**What should happen:**

should provide 540 Spirit for 6 sec after you cast Holy Shock

**Comment by Rushor** [comment]
added

![I](https://i.imgur.com/XvW4Ekq.jpg)
