### ISSUE TITLE
[Item] Battered Steam Tonk Controller - Crashing the server

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3681]
**Links:**

https://www.wowhead.com/item=31666/battered-steam-tonk-controller

**What is happening:**
crashed the server

**What should happen:**
tested in DEV by me
couldnt reproduce at first

**Comment by Xman993** [comment]
Battered Steam Tonk Controller crash the server only when try to pull commander ulthok

**Comment by Echinaceax** [comment]
confirmed by both me and Xman993 

![confirmed](https://user-images.githubusercontent.com/39439201/67235491-78ea7f00-f447-11e9-8b04-f65ad388a6d4.jpg)

**Comment by Rushor** [comment]
no longer usuable in that instance.

**Comment by Echinaceax** [comment]
with test other bosses in other instances just to make sure. thanks @Rushor :)

**Comment by Rushor** [comment]
if it happens ot other toys or bosses let me know
