### ISSUE TITLE
Shadowfiend bug (issue 2) 

### ISSUE THREAD

**Issue by adel4241** [WoWManiaUK/Blackwing-Lair#3683]
https://www.wowhead.com/spell=34433/shadowfiend

**What is happening:** this pet come only for 4 sec and he didint do good dps and u dont have any action bar of him and ur mana didint come back complatly its bug ..... 

**What should happen:** when ur use it the pet should come up and start damage to ur target and his dps its very low and u must saw his Action BAR and with this action bar u must can Control it like hunter pet , and this pet should stay for 15 sec on ur target after he should gone 
and when ur use him ur mana should get back like 70k  or 80k mana in all talent even holy and disc
to be honest when he is atack to ur target ur mana should get back so if ur use it and ur enemy its die and this pet didint any attack to anyone u didint get any mana

**Comment by Echinaceax** [comment]
Video indeed shows the pet bar @Keader 
https://www.youtube.com/watch?v=dcN0S9NhtC4
https://www.youtube.com/watch?v=e_njOgFkFRY
https://www.youtube.com/watch?v=3CMjXeqaFx8

**Comment by Xman993** [comment]
I tested it. 
- Mana Restor is OK.
- Time is OK
- HP is Ok
- DMG scall with gear and its OK.
the only missing part is the petbar and the spell's

**Comment by sarahkay88** [comment]
oops sorry didn't mean to close

**Comment by Echinaceax** [comment]
Confirmed as @Xman993 

![SF log](https://user-images.githubusercontent.com/39439201/67247460-ba882380-f461-11e9-9095-c3b8784bfe5a.jpg)

**Comment by adel4241** [comment]
Need fix pet bar then only

در تاریخ سه‌شنبه ۲۲ اکتبر ۲۰۱۹،‏ ۱:۵۰ Echinaceax <notifications@github.com>
نوشت:
