### ISSUE TITLE
[Mining] Mines Disappear

### ISSUE THREAD

**Issue by Ashwarwell** [WoWManiaUK/Blackwing-Lair#3684]
I can see them from The Infeno but when zone changes to Whistling Grove they disappear. (Hyjal)

Map Location: https://gyazo.com/9d3df6fd5e51a1a8e77d7e14e9db3d32
1. The Inferno: https://gyazo.com/6be22e43489fc174b26255311936d05d
1. Whistling Grove: https://gyazo.com/714f3bc170b632cbe782df6c2c774834
2. The Inferno: https://gyazo.com/a1edc4d4a966b4b584c161bc69f70471
2. Whistling Grove: https://gyazo.com/f417b4a73050dcc0a7954d7af018bcd8

Edit: Same happens when zone changes to Ashen Lake either.

The Inferno: https://gyazo.com/c603ca1abc8ff93136d2c245841eb5bd
Ashen Lake: https://gyazo.com/0cd9b46d22428e5647c22cd8d079165d

Edit 2

Map Location: https://gyazo.com/4fc63b22ad6e0859b45f66411fcea7ad
Mount Hyjal: https://gyazo.com/a69d17692d8408e88ccf987b2c1dc0d2
Shrine of Goldrinn: https://gyazo.com/bc1ce604d1eb93cc46e47b43a44b4e4d

Edit 3: Mobs also disappear.

Map Location: https://gyazo.com/1cd0f734785db9a335c13bba03436c51
Maw of Lycanthoth: https://gyazo.com/9322c626dd552178c9c2962baf73c5ff
Shrine of Goldrinn: https://gyazo.com/f17786392f7a9cf9e47d10227b7b7a43

**Comment by Echinaceax** [comment]
i believe its a Phasing issue, atm Hyjal is being worked on with phasing, quests and spawns 

@rushor i would see after hyjal is fix, if there is still an issue 
i will test in dev if you need

**Comment by Echinaceax** [comment]
Test complete, yes phasing issue only, once Hyjal is fix this wont be an issue 

![m1](https://user-images.githubusercontent.com/39439201/67274721-5006d000-f4c1-11e9-97e2-7c60546e2cd3.jpg)
![m2](https://user-images.githubusercontent.com/39439201/67274726-51d09380-f4c1-11e9-8bfe-fb18c6ab90fa.jpg)
![m3](https://user-images.githubusercontent.com/39439201/67274728-539a5700-f4c1-11e9-8ba7-7136104d9586.jpg)
