### ISSUE TITLE
[Quest][NPC] Can You Smell What the Lok'tar is Cooking? 

### ISSUE THREAD

**Issue by Kishilu** [WoWManiaUK/Blackwing-Lair#3687]
**Links:**
https://www.wowhead.com/quest=28344/can-you-smell-what-the-loktar-is-cooking
https://www.wowhead.com/npc=48218/kingslayer-orkus

**What is happening:** 
![WoWScrnShot_102219_210243](https://user-images.githubusercontent.com/56876656/67312499-488df980-f4b6-11e9-9440-5b1e8792cb65.jpg)

- NPC missing
- Unable to complete quest

**What should happen:** [https://www.youtube.com/watch?v=OoxLmWMSNwY](url)

- Kingslayer Orcus should appear around the area in the screenshot above and as shown in the video, allowing for the player to interact with the NPC and complete the quest.

**Comment by Rushor** [comment]
added near the ground

![I](https://i.imgur.com/cLFQXdA.jpg)
