### ISSUE TITLE
[Quest] Eyes on the Prizes - 29517 - Darkmoon Faire

### ISSUE THREAD

**Issue by Druhl** [WoWManiaUK/Blackwing-Lair#3689]
Profession quest - Leatherworking
https://www.wowhead.com/quest=29517/eyes-on-the-prizes

What should happen:
- player uses trade objects to create 5 quest items enabling quest completion

What is happening:
- quest giver NPC {https://www.wowhead.com/npc=14841/rinling) is not offering quest

**Comment by Druhl** [comment]
Update: this appears to be a faction issue.

I was offered this quest and able to complete it normally on a Horde character with Leatherworking, just not on my Alliance one (char name Asana).

**Comment by Rushor** [comment]
Pls guys remembert his if you start doing quest on Darkmoon Faire:
If your Darkmoon Faire profession quest is not showing as available, check your profession level for your Original (Vanilla 1-300) tier. If it is not at least 75 points, your profession quest will not show up, no matter how many points you have in other expansion pack tiers of your profession.
