### ISSUE TITLE
[Priest] [Equip] [Tier 11] - 4 Pieces Set Bonus Not Working (Discipline)

### ISSUE THREAD

**Issue by Venom64bit** [WoWManiaUK/Blackwing-Lair#3690]
**Links:**
https://www.wowhead.com/spell=47540/penance

What is happening:
As a DisciplinePriest, wearing 4 pieces of the T11 set, I'm not getting the 540 Spirit bonus while use Penance.

What should happen:
Do nothing.

**Comment by Rushor** [comment]
oh yes sorry. that was a missing one from https://github.com/WoWManiaUK/Blackwing-Lair/issues/3598 i forgot to save. sorry.
