### ISSUE TITLE
[NPC] Sharon Boomgetter - 48948 - Burning Steppes - not offering taxi

### ISSUE THREAD

**Issue by Druhl** [WoWManiaUK/Blackwing-Lair#3692]
https://www.wowhead.com/npc=48948/sharon-boomgetter

What should happen:

- This NPC offers a taxi ride to Bogpaddle in Swamp of Sorrows.

What does happen:

- Even though my character has the quest that leads to this NPC, there is no taxi ride option offered and the taxi itself (Bogpaddle Bullet) is non-interactive.

![WoWScrnShot_102219_203013](https://user-images.githubusercontent.com/19803911/67345921-c8de4a00-f50a-11e9-9fa0-e714a22f158d.jpg)

**Comment by Rushor** [comment]
https://www.youtube.com/watch?v=nNpiv2qoejY

**Comment by Rushor** [comment]
https://www.wowhead.com/quest=28569/the-bogpaddle-bullet

**Comment by Rushor** [comment]
gossip path and all added

![I](https://i.imgur.com/125ATsa.jpg)
![I](https://i.imgur.com/UTOFOn8.jpg)
