### ISSUE TITLE
[NPC] Lantresor of the Blade - ID 480512 - Horde 

### ISSUE THREAD

**Issue by Nacho-k** [WoWManiaUK/Blackwing-Lair#3693]
**Links:**
https://www.wowhead.com/npc=18261/lantresor-of-the-blade#starts
https://www.wowhead.com/quest=9927/ruthless-cunning
https://www.wowhead.com/quest=9931/returning-the-favor
https://www.wowhead.com/quest=9932/body-of-evidence
https://www.wowhead.com/quest=9934/message-to-garadar#comments
**What is happening:**

Doesnt provide the quest ruthless cunning blocking off the other quests. I dont know if the same happens for the alliance.

**What should happen:**

He should give the quest ruthless cunning Followed by Returning the Favor + Body of Evidence and finally Message to Garadar

**Comment by Rushor** [comment]
the req. for the quest are strange. It has to be fixed like that:

https://github.com/Aokromes/TrinityCore/commit/2be839936d4a2edaf3adbea376cc026fed795c8b

**Comment by Rushor** [comment]
Quest Ruthless Cunning requires quest Diplomatic Measures (Horde) rewarded OR
Quest Ruthless Cunning requires quest Diplomatic Measures (Alliance) rewarded
