### ISSUE TITLE
[Daily/Fishing] Moat Monster!

### ISSUE THREAD

**Issue by Kishilu** [WoWManiaUK/Blackwing-Lair#3694]
**Links:**
https://www.wowhead.com/quest=29361/moat-monster
https://www.wowhead.com/item=69998/alliance-decoy-kit

**What is happening:** 
![Untitled](https://user-images.githubusercontent.com/56876656/67385963-f2b66180-f548-11e9-9ec4-d4a1502896d0.png)

- Quest item Alliance Decoy Kit not working; item not summoning Moat Monster (tested at several spots).

- Unable to complete quest.

**What should happen:**

- Moat Monster should appear around here, but more certainly in the region in the bottom rectangle: 
![WoWScrnShot_102319_144101](https://user-images.githubusercontent.com/56876656/67386294-8a1bb480-f549-11e9-918d-2c2ab41a9560.jpg)
![237704-moat-monster-location](https://user-images.githubusercontent.com/56876656/67386392-b8998f80-f549-11e9-8574-da1ea1924d25.jpg)
https://www.youtube.com/watch?v=avF3LzgwEt4

**Comment by Rushor** [comment]
some texts need to be added here too

**Comment by Rushor** [comment]
326582 - [[DND] Moat Monster Spawn Loc X:1761.280029 

```
DELETE FROM `gameobject_template` WHERE `entry` = 301110;
INSERT INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `data0`, `data1`) VALUES 
(301110, 8, 0, 'Ruins of Lordaeron Moat', 1725, 20);
```

**Comment by Rushor** [comment]
fixed

https://gyazo.com/011a82d435d10b9d5b7b16b6cc052520
