### ISSUE TITLE
[Barber] Crashing client (all barbers)

### ISSUE THREAD

**Issue by Kishilu** [WoWManiaUK/Blackwing-Lair#3695]
**Links:** https://wowwiki.fandom.com/wiki/Barbershop

**Tested only for female Blood Elves but may happen to other races**

**What is happening:**

- Game crashing the client when selecting a certain Piercing.

- Instant crash upon reaching said Piercing; client crashes before the accessory is shown.

![barber crash](https://user-images.githubusercontent.com/56876656/67389304-34e2a180-f54f-11e9-9f32-b272dfc1af62.PNG)

**What should happen:**
Piercing should be normally viewed and purchased without crashing the client.

**Comment by Rushor** [comment]
works fine for me 

![I](https://i.imgur.com/wdgk23m.jpg)

i think you need to repait your client or download it new from the website 

https://wow-reign.com/start

I really cannot reproduce that issue

**Comment by Kitzunu** [comment]
I can confirm this.
It is due to missing textures in the client
