### ISSUE TITLE
Shoulder-Mounted Drake-Dropper usable on Bosses.

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3698]
**Links:**
http://prntscr.com/pn4j30

https://www.wowhead.com/item=63393/shoulder-mounted-drake-dropper
https://www.wowhead.com/quest=28280/tear-them-from-the-sky

from WoWHead or our Armory

**What is happening:**

someone used the item on a boss and did a lot of dmg

**What should happen:**

ony usable for the quest

**Comment by Slydee23** [comment]
#3699  Done

**Comment by Druhl** [comment]
Not sure this item is fixed as intended.

I was doing this quest (28280), accidentally tagged the elite "Torth" (https://www.wowhead.com/npc=46337/torth) and fired the Drake-Dropper and it killed **_me_**.  lol

Is this intended?

![WoWScrnShot_011820_202615](https://user-images.githubusercontent.com/19803911/72672967-2e21d880-3a31-11ea-80ea-49348646adb1.jpg)

- tagging @Echinaceax
