### ISSUE TITLE
[Quest] Val'kyr Incursion - ID 27201 - Western Plaguelands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#370]
Quest - https://www.wowhead.com/quest=27201/valkyr-incursion
NPC - https://www.wowhead.com/npc=44453
Kill NPC - https://www.wowhead.com/npc=45239/lesser-valkyr
Your required to kill the lesser Val'kyrs however they are not there. This maybe be cause this is the second quest in a 4parts chain quest. However I was not supplied with the first quest in this chain.
Quest not received - https://www.wowhead.com/quest=27205/the-depravity-of-the-forsaken

**Comment by Dranah** [comment]
Could be phasing issue.

**Comment by sarahkay88** [comment]
yes possibly because the val'kyrs are meant to be flying/floating

**Comment by Dranah** [comment]
Nope they are entirely missing it seems.

**Comment by Rushor** [comment]
hovering and flying and spawns added
