### ISSUE TITLE
[Quest] At the Stonemother's Call - Deepholm

### ISSUE THREAD

**Issue by Chicozoba** [WoWManiaUK/Blackwing-Lair#3700]
**Links:**

https://www.wowhead.com/quest=26752/audience-with-the-stonemother

**What is happening:**

 I can take the quest, but can't launch Therazane's speech in order to complete the quest.

**What should happen:**

Therazane should start talking with another npc.

**Comment by Rushor** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/2826

**Comment by Chicozoba** [comment]
It doesn't work for me... So I don't think it's fixed

**Comment by Echinaceax** [comment]
Ah i see what happend here @Chicozoba , Rushor linked #2826 and closed this one. the other one is still open :)
