### ISSUE TITLE
[Quest] World In Stone - Deepholm

### ISSUE THREAD

**Issue by Chicozoba** [WoWManiaUK/Blackwing-Lair#3701]
**Links:**

https://www.wowhead.com/quest=26833/word-in-stone

**What is happening:**

I can take the quest from Therazane but I can't give it back to the NPC.

**What should happen:**

I should be able to speak or give the quest back to Maruut Stonebinder.

![image](https://user-images.githubusercontent.com/50930065/67412790-37c9aa80-f5c0-11e9-8248-47c9f5e7531b.png)

**Comment by Rushor** [comment]
fixed with next update

![I](https://i.imgur.com/GbdwT6H.jpg)
