### ISSUE TITLE
[Quest] Writing the Future - 29515 - Darkmoon Faire

### ISSUE THREAD

**Issue by Druhl** [WoWManiaUK/Blackwing-Lair#3705]
Profession quest - Inscription
https://www.wowhead.com/quest=29515/writing-the-future

What should happen:

- player uses trade objects to create quest items enabling quest completion

What is happening:

- quest giver NPC {https://www.wowhead.com/npc=14822/sayge) is not offering quest, at least to my Horde char (Makkar)

**Comment by Rushor** [comment]
Pls guys remembert his if you start doing quest on Darkmoon Faire:
If your Darkmoon Faire profession quest is not showing as available, check your profession level for your Original (Vanilla 1-300) tier. If it is not at least 75 points, your profession quest will not show up, no matter how many points you have in other expansion pack tiers of your profession.
