### ISSUE TITLE
[Stonecore] Tabard of Ramkahen - reputation

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3706]
**Links:**
https://www.wowhead.com/item=65904/tabard-of-ramkahen
https://www.wowhead.com/the-stonecore

**What is happening:**
When in stonecore players are not receiving reputation for ramkahen even though they have the tabard equipped.
This was given to me to test. I wore the tabard and entered Stonecore and as the ss below show I didn't receive the correct rep for the dungeon, 

**What should happen:**
all reputation in a level 85 dungeon should be applied to the tabard reputation worn, players should not be receiving reputation other than the one they have a tabard equipped for. 

![WoWScrnShot_102319_175030](https://user-images.githubusercontent.com/42302580/67416497-d6eda280-f5be-11e9-81d1-c3718a0cc5bf.jpg)
![WoWScrnShot_102319_175037](https://user-images.githubusercontent.com/42302580/67416505-d94ffc80-f5be-11e9-9d66-3b48d51b79bd.jpg)
![WoWScrnShot_102319_175041](https://user-images.githubusercontent.com/42302580/67416509-db19c000-f5be-11e9-8a25-2915ec38f233.jpg)
![WoWScrnShot_102319_175054](https://user-images.githubusercontent.com/42302580/67416517-dd7c1a00-f5be-11e9-9376-117caf83d1e3.jpg)
![WoWScrnShot_102319_175057](https://user-images.githubusercontent.com/42302580/67416531-e371fb00-f5be-11e9-91b7-019b15d22613.jpg)

**Comment by sarahkay88** [comment]
tested in other level 85 dungeons and that tabard seams fine - so only stone core seams effected at them moment

**Comment by sarahkay88** [comment]
#3703

**Comment by Echinaceax** [comment]
@Keader The could be due to the recent fix that took place in Stoncore ;)

**Comment by Rushor** [comment]
normal rep from the dungeon removed. by default the dungeon should give rep in hc for earthern ring

nh - no rep 
![I](https://i.imgur.com/WypTzVb.jpg)
hc with tabard 
![I](https://i.imgur.com/oDuqlk2.jpg)
hc without tabard 
![I](https://i.imgur.com/iPz6eiJ.jpg )

**Comment by sarahkay88** [comment]
@Rushor  the 3rd ss shouldn't have ramkaen's rep on it, if u don't have the tabard equipped

**Comment by Echinaceax** [comment]
revert this fix then @Rushor please :)

**Comment by sarahkay88** [comment]
I think @Rushor  fix was correct - this dungeon isn't 85 therefore tabards shouldn't work.

**Comment by sarahkay88** [comment]
I never checked the level of the dungeon when I made my report. which is my mistake sorry
