### ISSUE TITLE
[Quest] Herbs For Healing - 29514 - Darkmoon Faire

### ISSUE THREAD

**Issue by Druhl** [WoWManiaUK/Blackwing-Lair#3707]
Profession quest - Herbalism
https://www.wowhead.com/quest=29514/herbs-for-healing

What should happen:

- player harvests (as per herbalism skill) some number of quest object herbs in area around quest giver, enabling quest completion

What is happening:

- quest giver NPC {https://classic.wowhead.com/npc=14833/chronos) is not offering quest, at least to my Horde char (Makkar)

**Comment by Rushor** [comment]
Pls guys remembert his if you start doing quest on Darkmoon Faire:

If your Darkmoon Faire profession quest is not showing as available, check your profession level for your Original (Vanilla 1-300) tier. If it is not at least 75 points, your profession quest will not show up, no matter how many points you have in other expansion pack tiers of your profession.

https://www.wowhead.com/quest=29514/herbs-for-healing#comments

Anyway i have fixed the respawntimer for the gameobjects (Darkblossoms aswell now)
