### ISSUE TITLE
[Dungeon] Lost city of the tol'vir - reputation

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3708]
**Links:**
https://www.wowhead.com/lost-city-of-the-tolvir
https://www.wowhead.com/faction=1173/ramkahen
**What is happening:**
This dungeon is giving base rep with no tabard to Rahmaken
**What should happen:**
Should only give this rep once a tabard is equipped

![WoWScrnShot_102319_192801](https://user-images.githubusercontent.com/42302580/67423452-37cfa780-f5cc-11e9-89cc-b749595f947a.jpg)

**Comment by Rushor** [comment]
https://www.wowhead.com/npc=44577/general-husam

**Comment by Rushor** [comment]
in order to clarify:

you get rep from every dungeon by default - the tabard only changes the faction where you will get rep with
