### ISSUE TITLE
[Event] Hallow's end  - not active

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3709]
**Links:**

https://www.wowhead.com/hallows-end

**What is happening:**
Event isn't active you cant queue for dungeon 
you can complete any of the quests https://www.wowhead.com/hallows-end#quests because they are not on the live realm. no buckets or trick 'o'o treat active at all.

**What should happen:**

Event should be made actibve for players

https://cdn.discordapp.com/attachments/583592560220438558/636658339408773140/WoWScrnShot_102319_211140.jpg
https://cdn.discordapp.com/attachments/583592560220438558/636658438893469697/WoWScrnShot_102319_211209.jpg

**Comment by sarahkay88** [comment]
there is less than a week of this event left for players to be able to complete it

**Comment by sarahkay88** [comment]
#1589

**Comment by Rushor** [comment]
i added the timer, if that does not activate it, it must be done i a different way @wow-mania
