### ISSUE TITLE
[Event] Darkmoon faire 

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3710]
**Links:**
https://www.wowhead.com/darkmoon-faire

**What is happening:**
Darkmoon fair is constantly active, people are using this to farm trinkets and professions.

**What should happen:**
it should only be active one week per month

**Comment by Rushor** [comment]
and the npcs that are spawned for it should all despawn in the open world if the event is not active?

**Comment by sarahkay88** [comment]
yes all NPC should deactivate as they haven't come to town yet. it should only active on the first Sunday of the month and for one week only

**Comment by Rushor** [comment]
only active one week now

**Comment by Rushor** [comment]
also:

all those guids:

307954,
312055,
314040,
314353,
314484,
535,
296252,
310945,
375666);

need to be added to the darkmoon event (3). Those guids are the portal mages that teleport you to the place of the darkmoon portal. I have done that now.
