### ISSUE TITLE
[Item] Sack o' Tokens - Darkmoon

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3712]
**Links:**

https://www.wowhead.com/item=78908/sack-o-tokens
https://www.wowhead.com/npc=55266/zina-sharpworth

**What is happening:**
- Empty

**Comment by Kitzunu** [comment]
```sql
DELETE FROM `item_loot_template` WHERE `entry` = 78905;
INSERT INTO `item_loot_template` (`Entry`, `item`, `Reference`, `Chance`, `LootMode`, `GroupMode`, `MinCount`, `MaxCount`) VALUES
(78905, 71083, 0, 100, 1, 1, 20, 20);

**Comment by Rushor** [comment]
all those are empty
FROM `item_loot_template` WHERE `entry` IN
(78907, 78905, 78902, 78903, 78910, 78909, 78908, 78906, 78904, 78898, 78899, 78897, 78900, 78901); 

will fix all now.

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/Del2qXk.jpg)

anyway thanks kitz <3
