### ISSUE TITLE
[Event] Darkmoon Fair - Item Saspaeilla Sinker

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3713]
**Links:**
https://www.wowhead.com/item=74822/sasparilla-sinker
https://cata-twinhead.twinstar.cz/?npc=14844
https://www.wowhead.com/achievement=6026/fairegoers-feast
**What is happening:**
Item is not solt by the vendor so unable to get the achievement
**What should happen:**
should be able to obtain item to finish of the achievement

**Comment by Rushor** [comment]
added

![I](https://i.imgur.com/cCHzcI8.jpg)
