### ISSUE TITLE
[NPC] Catrina (Stormwind) (missing) - Day of the dead.

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3714]
**Links:**

https://cata-twinhead.twinstar.cz/?npc=34383

**What is happening:**
- Npc missing

**What should happen:**
_She should be here at location to dance with_

**Comment by Rushor** [comment]
added and assigned to the event

![I](https://i.imgur.com/LhoPI2w.jpg)
