### ISSUE TITLE
[Rogue Human] Stuck after 3rd quest

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3715]
**Links:**
https://classic.wowhead.com/npc=915/jorik-kerridan#ends
from WoWHead or our Armory

**What is happening:**
When u get to the class trainer as Human Rogue you dont get any more quests. 
This is the guy that should give you a followup quest.
https://imgur.com/a/uBFAOCM

This is the quest you turn in at the class trainer
https://imgur.com/a/CxhOh34
Class quest for rogue is missing.
Tried it on dev dosnt work there either.

**What should happen:**
He should give a followup quest so you can continue question. 

This is the quest you should get:
https://www.wow-freakz.com/quest_helper.php?quest=26915&name=the-deepest-cut

**Comment by Kitzunu** [comment]
@Rushor i believe the quest order for the rogue human startingzone is correct, maybe the actual quests in quest_template are wrong and has restricted to other classes? 
I could potentially check it later today

**Comment by Rushor** [comment]
i already did. most quests are fucked up.

the AllowableClasses and AllowableRaces are mostly wrong. some mixed with worgen. already fixed it. will check the other quests now.

**Comment by Rushor** [comment]
fixed till report to goldshire.

https://i.imgur.com/4k4IwXt.jpg

will check the other quests now.

![I](https://i.imgur.com/4k4IwXt.jpg)

**Comment by sarahkay88** [comment]
I wait this has a full report just give me a sec to find it, kitz did a fix on it

**Comment by Rushor** [comment]
but i fixed it already :D

**Comment by Kitzunu** [comment]
yeah, that is what I thought @Rushor 
Guess I dont need to check it when I get home then :P

**Comment by sarahkay88** [comment]
#841

**Comment by Rushor** [comment]
okay so the chaning was fixed but the access to the class/race had to be added

**Comment by Rushor** [comment]
okay i tested EVERY freaking class quest in that zone till "report to goldshire" now. and it's all working now <3

**Comment by Kitzunu** [comment]
<3
