### ISSUE TITLE
[NPC] sweeping of the winds (low dmg) - Uldum

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3716]
**Links:**

https://www.wowhead.com/npc=51672/sweeping-winds

![sweeping of the winds](https://user-images.githubusercontent.com/39439201/67498344-8f7b1b00-f67f-11e9-92b2-fe8ec30ceb04.jpg)

**What is happening:**
- low dmg

**Comment by Rushor** [comment]
should we maybe increase the meleedamage of all level 80 - 85 cata zones? 
you can talk with me in discord about it - thank you <3
