### ISSUE TITLE
[Quest] Those That Couldn't Let Go ID 27168- Western Plaguelands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#372]
Quest - https://www.wowhead.com/quest=27168/those-that-couldnt-let-go
NPC - https://www.wowhead.com/npc=11053
Item - https://www.wowhead.com/item=60861/holy-thurible
The item appears to work. but then it doesn't turn any of the spirits to enemy mobs in order to complete the quest. Incompletable.

**Comment by Saintres** [comment]
Still not working this quest.
Tryed it 13-02-2019
It's still as Sarahkay say

**Comment by Tatoepaladin** [comment]
just tried it still doesnt work 23-6-2019

**Comment by jarvik76** [comment]
Confirming not working as at 19th sept 2019

**Comment by Rushor** [comment]
okay fixed. some are friendly and some turn devil

![I](https://i.imgur.com/fwn7PPq.jpg)
![I](https://i.imgur.com/MCVMVWT.jpg)
