### ISSUE TITLE
[Event] Sack 'o' tokens & pouch 'o' tokens - Darkmoon Fair

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3720]
**Links:**
https://www.wowhead.com/item=78909/sack-o-tokens
https://www.wowhead.com/item=78897/pouch-o-tokens 
npc - https://www.wowhead.com/npc=55266/zina-sharpworth
npc - https://www.wowhead.com/npc=55264/sazz-coincatcher
NPC -https://www.wowhead.com/npc=55339/trixi-sharpworth

**What is happening:**
each NPC is selling these sack and pouches for different prices
**Zina** currently sells them for pouch 60s and sack 1g 92s
**sazz** sells the pouch twice and for two different amounts - 1 pouch at **2s** and the second pouch at **60**s. she also sells the sacks twice and at different amount 1 sack at **6s 40c** and the other sack of **1g 92s**
**trixi** sells the puch for **2s** and sack for **6s 40c**

**What should happen:**
**The prices of the same item on different npcs should be the same for the player** - according to my links sacks should be 50c and sacks 1g 92 s
**but I need to find more research as I believe the price depended on you level so the lower level you were the less they cost.**

**Comment by Rushor** [comment]
level depending gold amount cannot be done currently, but they will have same price now from both npcs.
