### ISSUE TITLE
[NPC] Aimee - darkmoon fair

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3722]
**Links:**
https://www.wowhead.com/npc=29548/aimee

**What is happening:**
only sells 9 items

**What should happen:**
Aimee should sell 10 items she is missing berry pie slices from her sll page https://www.wowhead.com/item=42432/berry-pie-slice

**Comment by Rushor** [comment]
added the missing item

**Comment by Rushor** [comment]
![I](https://i.imgur.com/eFsxA4P.jpg)
