### ISSUE TITLE
[NPC] Lhara - Darkmoon Fair

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3724]
**Links:**

https://wowwiki.fandom.com/wiki/Lhara

**What is happening:**

Still sell some of the previouse patch  item
item https://www.wowhead.com/item=46812/northrend-mystery-gem-pouch

**What should happen:**
item should have been removed from her sell page in patch 4.3.0 
she should only sell mounts and pets.

**Comment by Rushor** [comment]
removed
