### ISSUE TITLE
[Item] Pit fighter trinket -Darkmoon Fair

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3725]
**Links:**
https://www.wowhead.com/item=74035/master-pit-fighter
https://www.wowhead.com/quest=29761/master-pit-fighter
https://www.wowhead.com/npc=55402
chest - https://www.wowhead.com/object=209620/darkmoon-treasure-chest
chest loot -ttps://www.wowhead.com/object=209620/darkmoon-treasure-chest
**What is happening:**

Players cannot obtain the item as it is located in the arena chest. currently the arena isn't accessible to players. The gates do not open when clicked.

**What should happen:**
Players should loot the chest inside the arena that has a 95% chance of containing one of these items. when 12 are collected they should then hand them in to the npc or wear it. The chest should also contain several different loot as show in the link.

**Comment by Rushor** [comment]
yes. the gate should actually port the player inside the Deathmatch area or outide.

There sould be some announces by Korgol Crushskull from time to time aswell.

**Comment by Rushor** [comment]
added the event. will a vid now

![I](https://i.imgur.com/P4RNiva.jpg)

**Comment by Rushor** [comment]
https://youtu.be/kclXJEcMHvw First fixed Darkmoon Fair quest. More will follow in a few days

**Comment by Slydee23** [comment]
sry for ruining it xD

**Comment by Rushor** [comment]
npnp haha. nevertheless it's a nice event

**Comment by Kitzunu** [comment]
@Rushor Quest missing Completion Text
```
Well met, <class>.

Gaining but one trinket is not enough to make you a Master Pit Fighter.

Now is the time to truly prove your steel.

**Comment by Rushor** [comment]
can you send me the fix in discord? :>

**Comment by Echinaceax** [comment]
this event is still bug. event not  starting

![pit message](https://user-images.githubusercontent.com/39439201/68240163-a705bc80-000c-11ea-9fba-cd314a919940.jpg)

**Comment by Echinaceax** [comment]
Later patch, chest shouldnt be spawning until 4.3 (dragon soul ) https://wowpedia.fandom.com/wiki/Darkmoon_Treasure_Chest

- [x] chest object deactivation https://www.wowhead.com/object=209620/darkmoon-treasure-chest#comments
