### ISSUE TITLE
[Quest] Fizzy Fusion - missing - darkmoon fair

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3727]
**Links:**
https://www.wowhead.com/quest=29506/a-fizzy-fusion
https://www.wowhead.com/npc=14844

**What is happening:**
alchemist quest is missing

**What should happen:**

Alchemist quest needs adding

**Comment by Rushor** [comment]
I believe your Classic skill needs to be 75 for the quest to appear

Just wanted to confirm this. Classic alchemy was at 0 and leveled it to 75, the quest appeared.

https://www.wowhead.com/quest=29506/a-fizzy-fusion#comments

You need to have 75 points in Alchemy - then the quest will appear. Not a bug :)

![I](https://i.imgur.com/VD1LhAC.jpg)
