### ISSUE TITLE
[Quest] Deepholm On Even Ground

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3728]
https://www.wowhead.com/quest=26314/on-even-ground

**What is happening:**

Elementium Grapple Line doesn't knock down Servant of Therazane when pulled.

**What should happen:**

Elementium Grapple Line should knock down Servant of Therazane when pulled.

**Comment by Rushor** [comment]
the zone needs respawn and some Servant of Therazane need to be spawned

**Comment by Rushor** [comment]
zone reworked and credit added. the creatures are in phase 237.

![I](https://i.imgur.com/RYcZfdm.jpg)
![I](https://i.imgur.com/iylmQzG.jpg)
