### ISSUE TITLE
[Quest] Crumbling Defenses Quest - Deepholm

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3729]
https://www.wowhead.com/quest=26312/crumbling-defenses

**What is happening:**

Saving the objective related NPCs doesn't complete the objectives.

**What should happen:**

Killing all enemies in combat with Tawn Winterbluff, Stormcaller Mylra and Hargoth Dimblaze should complete their objectives.

**Comment by Rushor** [comment]
sparring added. on evade they will say the text and give credit. also added some missing auras for the creaures.

![I](https://i.imgur.com/UMdh1R5.jpg)
![I](https://i.imgur.com/ptpaw8U.jpg)
![I](https://i.imgur.com/8GaZlHF.jpg)
