### ISSUE TITLE
[Quest] Ambushed ID 27171 - Western Plaguelands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#373]
Quest - https://www.wowhead.com/quest=27171/ambushed
NPC - https://www.wowhead.com/object=205258
Item - https://www.wowhead.com/item=60863 **4 needed**
Item - https://www.wowhead.com/item=60864 **4 needed**
Upon collecting this quest spirit are meant to appear in the crypt that you kill to collect the required items. However these spirits do not spawn. Making the quest incompletable.
![world of warcraft 04_01_2019 15_52_44](https://user-images.githubusercontent.com/42302580/50697737-ff5ddd80-103a-11e9-9cce-70bc7c82cac9.png)

**Comment by Saintres** [comment]
Tryed to do this quest 13-02-2019.
Still not working, just as Sarahkay88 said.

**Comment by zippoking** [comment]
confirmed

**Comment by Tatoepaladin** [comment]
Still not working 23-6-2019

**Comment by Fritzjof** [comment]
Still not working. 
Date: 7/16/2019

**Comment by Echinaceax** [comment]
@Fritzjof true if you dont see this fixed in dev 
![fixed](https://user-images.githubusercontent.com/39439201/61534298-83077680-aa2f-11e9-85c4-fcb0622cab42.jpg)

its not been looked at yet

**Comment by jarvik76** [comment]
Confirmed still issue at 19th Sept

**Comment by Rushor** [comment]
well loot and creatures added now in phase 169

![I](https://i.imgur.com/6W9UBbR.jpg)
![I](https://i.imgur.com/OnXGO6d.jpg)
