### ISSUE TITLE
[Quest] Imposing Confrontation Quest - Deepholm

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3730]
https://www.wowhead.com/quest=26315/imposing-confrontation

**What is happening:**

Reading the Earthen Ring Proclamation does nothing.

**What should happen:**

Reading the Earthen Ring Proclamation should trigger a conversation with Boden the Imposing and complete the objective.

**Comment by Rushor** [comment]
i have a script for that. needs compiling

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/5cwBukb.jpg)
![I](https://i.imgur.com/MYzWkM0.jpg)
![I](https://i.imgur.com/PkiJ1ti.jpg)
![I](https://i.imgur.com/eB305RC.jpg)
