### ISSUE TITLE
[Quest] Loose Stones Quest

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3731]
https://www.wowhead.com/quest=26375/loose-stones

**What is happening:**

Delicate Chain Smasher doesn't work properly.

**What should happen:**

Delicate Chain Smasher should only be usable near Quartz Rockling NPCs and should release them, completing the objective.

**Comment by Rushor** [comment]
zonespawns reworked. spell condition added. run away action for rocklings added.

![I](https://i.imgur.com/KrcdCpJ.jpg)
