### ISSUE TITLE
[Quest] Unsolid Ground - Deepholm

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3732]
https://www.wowhead.com/quest=26377/unsolid-ground

**What is happening:**

After acquiring and combining 6 Jade Crystal Clusters into a Jade Crystal Composite, you can use the Jade Crystal Composite to do nothing.

**What should happen:**

The Jade Crystal Composite should summon an Agitated Tunneler for you to fight.

**Comment by Rushor** [comment]
spawn of worm and credit and texts added.

![I](https://i.imgur.com/UOeM4gC.jpg)
