### ISSUE TITLE
Bastion of Twilight Bosses wrong amount of Valor Points

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3733]
**Links:**
https://worldofwarcraft.fandom.com/et/wiki/Valor_point

from WoWHead or our Armory

**What is happening:**

Currently only rewarding with 35 VP per Boss kill

**What should happen:**

10 player Cataclysm raid boss — 115 Valor Points VP. There are nine bosses per week, counting Baradin Hold.

The Current Tier raid always should reward 115 VP per Kill

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/QCAIA0A.jpg)

**Comment by Ovahlord** [comment]
That's actually wrong. As of Patch 4.3 4.0 raid bosses grant 35 Valor points on 10 player mode and 45 on 25 player mode. Firelands bosses grant 50 Valor points on all difficulties and Dragon Soul bosses 100 per kill. The blog entry of Blizzard was during the PTR time and got changed completely during that time.

**Comment by sarahkay88** [comment]
@Ovahlord can u link ur evidence please?

**Comment by sarahkay88** [comment]
@Rushor  https://wowwiki.fandom.com/wiki/Valor_point 
currency at the bootom of the page
The number of Valor Points awarded for killing a boss on Heroic difficulty in The Bastion of Twilight, Blackwing Descent, and Throne of the Four winds is 35 in 10-player mode, and 45 in 25-player mode.

**Comment by Ovahlord** [comment]
My evidence? 4.3.4 sniff values which means I have official numbers. Also you can simply proof it to yourself by just looking for 4.3.4 boss kills which all show that Dragon Soul for example rewards 100 Valor points on all difficulties. You can trust me, I did my homework on that.

**Comment by sarahkay88** [comment]
@Rushor u may have to take another look at this

**Comment by bagi84** [comment]
https://worldofwarcraft.fandom.com/et/wiki/Valor_point the complete figures for every raids valour points as of patch 4.3 … theres no way you should be getting 115 vp per boss for a normal year 11 raid

**Comment by sarahkay88** [comment]
https://worldofwarcraft.fandom.com/et/wiki/Valor_point
its in the section named read from

Expansion | Size | Difficulty | Reward
-- | -- | -- | --
Cataclysm | 10-man raid | Tier 12 (Firelands)Normal & Heroic | 120 Valor Points per boss
Cataclysm | 25-man raid | Tier 12 (Firelands)Normal & Heroic | 140 Valor Points per boss
Cataclysm | 10-man raid | Tier 11Normal & Heroic | 35 Valor Points per boss
Cataclysm | 25-man raid | Tier 11Normal & Heroic | 45 Valor Points per boss

**Comment by Rushor** [comment]
Thanks @Ovahlord.

I have one question. Could You may help me to Understand how vehicles with seats work in Cata? Can i contact you in Discord somehow?

**Comment by Rushor** [comment]
okay 10 mode = 35, 25 mode = 45

**Comment by Rushor** [comment]
okay refixed that. thanks all, espcially ovahlord.

**Comment by Lokir92** [comment]
Hey there. The server core is on 4.3.4, thats right, but we are currently in patch 4.0.4 as far as content goes. So it should reward valor points like it does in 4.0.4 and that was 90 VP per boss kill.
This got lowered in the next content patches, so that people just dont farm old content to get the "current" VP's. My prove are these videos from Paragon:
https://youtu.be/GxPFelqptbc?t=637
https://youtu.be/MmcO4G6I0jA?t=643
In 4.2 (Firelands) you will recieve less VP from bot/bwd/totfw.
In that regard, in Firelands itself you will get 140VP per boss (due to it having fewer bosses).
like in this: https://youtu.be/10dxem4fCsE?t=546

**Comment by sarahkay88** [comment]
People keep throwing different values out 😂

**Comment by Lokir92** [comment]
Well, it is 90VP for 25 man and 70VP in 10 men:
https://youtu.be/HfN3NCHbihY?t=650

i really dont know, why you guys post numbers from 4.3.4 when we are in content area of 4.0.4

**Comment by sarahkay88** [comment]
- that is true but as I said everyone is throwing out different numbers hence why rushor needs to have a look at it. 115 was the original report.

**Comment by Ovahlord** [comment]
You're playing 4.0 content, that's right but you play with the patch 4.3 balance. This means bosses are significantly easier and classes have received massive buffs

**Comment by Rushor** [comment]
soo, any suggestion for the final numbers?

**Comment by Slydee23** [comment]
@Lokir92 Thx for the correct amount i only was sure 35 is wrong cause we are 4.0.6 progress  and so bot is current tier and should reward more.

**Comment by Echinaceax** [comment]
Found this to be incorrect @Rushor
it is meant to be 35 normal and 45 hc

https://worldofwarcraft.fandom.com/et/wiki/Valor_point

revert this fix rushor
