### ISSUE TITLE
[Quest] Pebble - Deepholm

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3735]
https://www.wowhead.com/quest=28869/pebble

https://www.wowhead.com/npc=43116/pebble

Pebble doesn't appear while standing on the ground in the Shuddering Spires, making the entire quest chain impossible to complete.

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/MBzo3S2.jpg)

but the follow up quests need to be fixed aswell later.

**Comment by parnik217** [comment]
Hello, NPCs are not showing up in quest 28869 Pebble

**Comment by Echinaceax** [comment]
it wont until other fixes are done to questline @parnik217 
full quest order report here https://github.com/WoWManiaUK/Blackwing-Lair/issues/4905
