### ISSUE TITLE
[Event] Pilgrims Bounty - first report

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3737]
**Links:**
Alliance quest -https://www.wowhead.com/quest=14022/pilgrims-bounty
Horde quest - https://www.wowhead.com/quest=14036/pilgrims-bounty

**What is happening:**
**This festival should be activated on the 25th of November and last 1 week - ending on the 1st of December**
These quest should be available for fraction specific npc commoners in a various locations.
after checking  these are the issues with the following npc:
**ALLIANCE**

 1.  **Night Elf commoners** https://www.wowhead.com/npc=19173 - didn't spawn in Darnaruss therefore players cannot pick up the above quest.
 2. **Draeni commoners** https://www.wowhead.com/npc=19171 - the commoners spawned but didn't provide quest in Exodus.
3. **Human commoners** https://www.wowhead.com/npc=18927 - did not spawn in stormwind to provide players with the above quest.
4.**Dwarf commoners** - https://www.wowhead.com/npc=19148 - did not spawn in iron forge to provide players with quest.
5. **Gnome commoners** https://www.wowhead.com/npc=19172 - did not spawn in iron forge to provide players with quest.
6. **NPC Gregory Tabor** https://www.wowhead.com/npc=34675 - is also missing so even if player obtained above quest they wouldn't be able to pick it up.

**Horde**
1. **Orc commoner**  https://www.wowhead.com/npc=19175 - didn't spawn at his location in ogrimmar to provide orcs with the above quest.
2.**Tauren commoner**r https://www.wowhead.com/npc=19176 - didn't spawn in ogrimmar or thunder bluff  to provide taurne's with the above quest
3. **Troll commoner** https://www.wowhead.com/npc=19177 didn't spawn in ogrimmar to provide trolls with the above quest.
4. **Forsaken commoner** https://www.wowhead.com/npc=19178 didn't spawn in under city to provide above quest. 
5. **NPC Miles Standish** https://www.wowhead.com/npc=34677 is missing so even if the above quest could be obtains players wouldnt be able to hand in the quest.

**Goblin Commoners** https://www.wowhead.com/npc=20102 provied quest in a variety of locations for both horde and alliance players
**here is what was noted:**

1. **the cape of stranglethorn**: https://www.wowhead.com/the-cape-of-stranglethorn  
a) as an alliance i can see the horde quest (i should only see alliance as i tested as ally).
b) didn't provide alliance version of quest (needs adding)

2. **North Barrens** (Rachet) https://www.wowhead.com/northern-barrens
a)  can see horde quest
b) alliance version needs adding

3. **Tanaris** https://www.wowhead.com/quest=14036/pilgrims-bounty
a) can see horde quest
b) alliance needs adding

4. **Nether storm** https://www.wowhead.com/netherstorm
a) can see horde quest
b) alliance needs adding

5**. Winter spring** https://www.wowhead.com/quest=14036/pilgrims-bounty
a)  https://www.wowhead.com/npc=20102 commkoners didnt spawn
b) couldn't check quest

6. The Storm peaks https://www.wowhead.com/the-storm-peaks
a) same as number 5

7) Shattrath City https://www.wowhead.com/shattrath-city
a) provided both fraction quest - should only be able to see ally version.

**Comment by Rushor** [comment]
okay i cannot provide much screenshots here, but i have added all so far https://i.imgur.com/WUhuDsW.jpg https://i.imgur.com/NymtF5B.jpg 

alli 
![I](https://i.imgur.com/GoikqK3.jpg)
horde 
![I](https://i.imgur.com/OpkMw3d.jpg)

**Comment by Echinaceax** [comment]
this looks awesome @Rushor
