### ISSUE TITLE
[Spell][Talent] Heroic fury not doing anything.

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3738]
**Links:**
https://wowwiki.fandom.com/wiki/Heroic_Fury

**What is happening:**
Using the ability does NOTHING

**What should happen:**
Should remove roots, not sure about slows but most importantly it should REFRESH CD of intercept. At the moment neither of these works. Pretty relevant talent for fury warriors and always taken.

**Comment by Rushor** [comment]
RemoveSpellCooldown is actually added in the core :o
