### ISSUE TITLE
[Dungeon] The blood furnace

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3739]
**Links:**
https://www.wowhead.com/the-blood-furnace
second boss - https://www.wowhead.com/npc=17380/broggok
final boss - https://www.wowhead.com/npc=17377/kelidan-the-breaker

**What is happening:**
These bosses can only be aggroed they cannot be targeted to be killed and ended uo just following me around the place. I could not hearth stone out because they interrupt my cast, cannot use mall stone whilst in combat and cant exit via entrance because the gates close. leaving players trapped.
I had to alt f4

**What should happen:**
Players should be able to target and kill the bosses to progress and leave the dungeon

**Comment by sarahkay88** [comment]
![WoWScrnShot_102619_014516](https://user-images.githubusercontent.com/42302580/67611740-381a9f00-f794-11e9-9222-228002f42c42.jpg)
![WoWScrnShot_102619_014856](https://user-images.githubusercontent.com/42302580/67611741-394bcc00-f794-11e9-83eb-5f3fa4b2a6fa.jpg)
the second boss just followed me all the way to the last boss lol

**Comment by Kitzunu** [comment]
```sql
UPDATE `creature_template` SET `unit_flags`=`unit_flags`&~33555200 WHERE `entry` IN (17380, 17377);

**Comment by Rushor** [comment]
perfect, thanks kitz <3
