### ISSUE TITLE
[Quest] A New Era for the Plaguelands- ID 26999 - Western Plagueland

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#374]
Quest - https://www.wowhead.com/quest=26999/a-new-era-for-the-plaguelands
NPC -https://www.wowhead.com/npc=44454
Quest items needed:
Item 1- https://www.wowhead.com/item=60760 **requires 4**
Item 2- https://www.wowhead.com/item=60761 **requires 4**
Item 3- https://www.wowhead.com/item=60762 **Requires 4** (can be collected)
Item 4- https://www.wowhead.com/item=60763 **requires 4**
This is parts of a 6 series/chain quest
These items are suppose to have a 79% drop rate. I spent a good 5-10minutes killing the mobs but they did not drop apart from item 3, which dropped from the first 4 bears I killed.
 Quest incompletable.

**Comment by sarahkay88** [comment]
**This prevents you from being able to pick up and complete the following quests:**
https://www.wowhead.com/quest=26935/northridge-lumber-mill
https://www.wowhead.com/quest=27000/learning-the-ropes
https://www.wowhead.com/quest=27001/this-means-war-wild-arachnid-roundup
https://www.wowhead.com/quest=27002/an-audience-with-the-highlord

**Comment by Echinaceax** [comment]
Same for Horde

**Comment by Saintres** [comment]
Tryed to do this quest 13-02-2019  and its still not working

**Comment by Echinaceax** [comment]
> Tryed to do this quest 13-02-2019 and its still not working

Yes you will find many of the quest reported from Western plaguelands have already been listed 

you found one that i was meant to have report but somehow didn't, so its good your back tracking after me (horde) and Angel (ally)  

(they wont be fixed yet) dont worry
