### ISSUE TITLE
[NPC] Spinescale Basilisk - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3740]
**Links:**

https://www.wowhead.com/npc=39658/spinescale-basilisk

**What is happening:**

- low population 

**What should happen:**
more need adding :)_

**Comment by Rushor** [comment]
will respawn the entire zone  4991

**Comment by Rushor** [comment]
added 

![I](https://i.imgur.com/nW6AXV9.jpg)

**Comment by Hespericless** [comment]
Some of the basilisks are unskinnable while others are

**Comment by Echinaceax** [comment]
i see you made a new report for this 2nd issue, thanks #3911
