### ISSUE TITLE
[NPC] Twilight Scorchlord - Mount Hyjal 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3741]
**Links:**

https://www.wowhead.com/npc=41500/twilight-scorchlord

![twilight scorchlord](https://user-images.githubusercontent.com/39439201/67612689-d151b180-f7a4-11e9-93ad-13fc29e54189.jpg)

**What is happening:**
- low dmg

**Comment by Rushor** [comment]
bigger damage spell used now + texts added

![I](https://i.imgur.com/4hAubkR.jpg)
![I](https://i.imgur.com/7nZHPus.jpg)
