### ISSUE TITLE
[NPC] twilight field captain - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3742]
**Links:**

https://www.wowhead.com/npc=41502/twilight-field-captain

![twight field captain](https://user-images.githubusercontent.com/39439201/67612711-30172b00-f7a5-11e9-9b89-2ae86b2ac36b.jpg)

**What is happening:**
- low dmg

**Comment by Rushor** [comment]
more dmg now

![I](https://i.imgur.com/3KWmxDv.jpg)
