### ISSUE TITLE
[NPC] Horrorguard - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3743]
**Links:**

https://www.wowhead.com/npc=39724/horrorguard

![horrorguard](https://user-images.githubusercontent.com/39439201/67612725-81bfb580-f7a5-11e9-8bde-a5e9ee195807.jpg)

**What is happening:**
- low dmg

**Comment by Rushor** [comment]
meleedamage increased
