### ISSUE TITLE
[NPC] Jaspertip Borer - Deepholm

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3744]
**Links:**

https://www.wowhead.com/npc=42524/jaspertip-borer

![jaspertip borer](https://user-images.githubusercontent.com/39439201/67612750-d5ca9a00-f7a5-11e9-9741-0ec7a1a863b9.jpg)

**What is happening:**
- doubles

**What should happen:**
- need spacing or remove double

**Comment by Rushor** [comment]
aaand fixed

![I](https://i.imgur.com/ZFSWCFn.jpg)
