### ISSUE TITLE
[NPC] Jaspertip ravager - Deepholm

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3745]
**Links:**

https://www.wowhead.com/npc=42525/jaspertip-ravager

![jaspertip ravager](https://user-images.githubusercontent.com/39439201/67612762-20e4ad00-f7a6-11e9-9def-34659668c938.jpg)

**What is happening:**
- Doubles

**What should happen:**
_need spacing or remove doubles_

**Comment by Rushor** [comment]
reduced + fly for the bats added

![I](https://i.imgur.com/nwYxnfY.jpg)
