### ISSUE TITLE
[Raid] Bastion of Twilight - Cho'gall (issue 3) Conversion broken

### ISSUE THREAD

**Issue by Batraneluu** [WoWManiaUK/Blackwing-Lair#3746]
**Links:** 
0. https://www.wowhead.com/npc=43324/chogall#abilities
1. https://www.wowhead.com/spell=91303/conversion
2. https://www.wowhead.com/spell=81628/summon-corrupting-adherent#used-by-npc

from WoWHead or our Armory

**What is happening:**
1. When Cho'gall converts people you can't interrupt them anymore and after you become converted you see the other player which was converted with you as enemy. Also if you damage the boss with AoE Damage you also damage the players that are channeling in Conversion.
2. The adds that spawn can no longer be interrupted and do more damage than before.

**What should happen:**

1.You should be able to interrupt players on conversion
2. You should be able to interrupt the channeling spell of those adds.

**Comment by Rushor** [comment]
so issie is that boss and adds are not interruptable?

**Comment by Batraneluu** [comment]
Problem is you cannot interrupt your raid members when cho'gall casts Conversion also when they are converted if you use AoE DPS you damage those players too, and Phase 2 adds are not interruptable.

**Comment by Rushor** [comment]
is this happening since X Faction?

**Comment by Batraneluu** [comment]
I think so, i know it worked better couple weeks ago.

**Comment by adel4241** [comment]
we was full Horde group and still it was bug ( this bug happen it for only 2 week / at start it was fix but now get bug )

**Comment by adel4241** [comment]
> 
> 
> so issie is that boss and adds are not interruptable?

this add  [Corrupting Adherent] should be interruptable

**Comment by Echinaceax** [comment]
@Rushor as stated above the was a full horde group in too, so not Xfaction related

**Comment by Rushor** [comment]
see https://github.com/WoWManiaUK/Blackwing-Lair/issues/3910 it is all related. i will try fixing the interrupt of adds now.

**Comment by Rushor** [comment]
MECHANIC_INTERRUPT for adds removed

**Comment by Echinaceax** [comment]
> is this happening since X Faction?

Yes was noticed while Xfaction was active

then when Xfaction was removed for 2 months it worked as intended

now we noticed it broken again now Xfaction is active again 🤦
