### ISSUE TITLE
[Object] Shipwreck Debris spawns - Darkmoon 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3747]
**Links:**

https://www.wowhead.com/object=210216/shipwreck-debris#comments

![spawns of deb](https://user-images.githubusercontent.com/39439201/67636043-a498b980-f8cc-11e9-8fd6-6c3a568fe262.jpg)

**What is happening:**
- only 3 object spawns in dev
- only 2 active
- 0 Darkmoon Daggermaw spawns

**What should happen:**
- [x] _need the darkmoon Island Shipwreck Debris active while Darkmoon event is active_
- [x] _set to disappear when Darkmoon is not active_

**note: zone amounts vary**
 Darkmoon Island  (672)
 Nagrand  (3)
 Shadowmoon Valley  (2)

etc...

**Comment by Rushor** [comment]
the item was added in wod https://wow.gamepedia.com/Darkmoon_Daggermaw

**Comment by Echinaceax** [comment]
so just the Shipwreck Debris then :)

**Comment by Rushor** [comment]
The location is the shores around Darkmoon Island during Darkmoon Faire, which is the easiest place to reach for anyone under level 70 trying to get the Sea Turtle.

https://www.wowhead.com/object=210216/shipwreck-debris#comments

will fix the spawns for Darkmoon Faire first now.

**Comment by Rushor** [comment]
Fathom Eel Swarm and Shipwreck Debris must have a pool then aswell. so either a Fathom Eel Swarm or a Shipwreck Debris will spawn at the place.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/jlY5xQF.jpg)
![I](https://i.imgur.com/vj3qQZq.jpg)

spawn in tol barad and darkmmon island added
