### ISSUE TITLE
[Dungeon] Stratholme

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3748]
**Links:**
https://www.wowhead.com/guides/dungeon-entrances-wow-eastern-kingdoms#stratholme

from WoWHead or our Armory

**What is happening:**
After Killing Ramstein the door for the ghouls should open but its closed
Remstain dead
https://imgur.com/a/pF9NrUN

Doors closed with ghouls
https://imgur.com/a/7E8Z2FJ

Even after killing last boss 
https://imgur.com/a/jH6teAe

All doors are still close and you cant leave the dungeon. 
https://imgur.com/a/xPKgCwk

**What should happen:**
The ghouls should spawn before you even can enter the last boss. 
The gate on last picture should be open so you can run out and reset if needed.

**Comment by Echinaceax** [comment]
@Rushor not sure if this is the door, many door issues there #2173

**Comment by Jimpaa** [comment]
You get this quest inside the dungeon 
https://classic.wowhead.com/quest=5214/the-great-fras-siabi#comments

The mailbox is empty when you click on it and the Curior dosnt drop the items either.
https://imgur.com/a/THDDLW3
https://imgur.com/a/a2QBHDM

Also the way up to the boss Willey the mobs should shoot with the cannons and that dosnt happen.
https://imgur.com/a/8iUCHFT

The last thing is the backdoor to Stratholme does not work. 
You can see it open when you click on it but there is another door there that does not open
https://imgur.com/a/Yv4pwWn

**Comment by Rushor** [comment]
okay, will fix them, curier was fixed in wotlk. need to copy that fix.
the door issue here is a different. thanks for report

**Comment by Nacho-k** [comment]
The backdoor can be opened, but theres around 5-6 of them stacked, the same happens with the door to the scholomance

**Comment by Rushor** [comment]
okay i just found out that the portal should not work https://eu.battle.net/forums/en/wow/topic/2350975164

**Comment by Rushor** [comment]
The portal was a rev to Naxxrams. I will not fix that for now. only the zombies and the attack.

The portal at ramstein was originally the gateway to naxxramas (Who should not be flying yet). For some reason that idea was scrapped and naxxramas was sent flying, taking the portal connection along with it.

Else issues i gonna fix now.

**Comment by Rushor** [comment]
okay multiple doots at entrance removed

**Comment by Rushor** [comment]
cannonballs fixed

![I](https://i.imgur.com/KSJxjJW.jpg)
![I](https://i.imgur.com/aEa1sl7.jpg)
