### ISSUE TITLE
[General] Rep Tabard/ Dungeon rep lelated issues

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3749]
**Links:**

- [x] getting rep with hellscream's reach while wearing an earthen ring tabard
https://www.wowhead.com/item=65905/tabard-of-the-earthen-ring

**_tested in SFK_** 

no issue on Ally
![er](https://user-images.githubusercontent.com/39439201/67642801-d54e1280-f90f-11e9-8899-17c7d282572a.jpg)

Horde toons get different rep when wearing the tabard 

![Image1](https://user-images.githubusercontent.com/39439201/67643278-ffa2ce80-f915-11e9-988b-8773edd20d67.jpg)

And got both rep killing mindless horror in SKF (HC) 
![horror](https://user-images.githubusercontent.com/39439201/67643441-e7cc4a00-f917-11e9-8405-097732f91b44.jpg)

-------

- [x] You are getting reputation from normal with Therazane. I even used tabard of Ramkahen #3703
https://www.wowhead.com/item=65904/tabard-of-ramkahen
-------
- [x] You can never use that item (error msg) cant equip
https://www.wowhead.com/item=65909/tabard-of-the-dragonmaw-clan

i mod rep to friendly, but cant equip
![dragonmaw clan](https://user-images.githubusercontent.com/39439201/67643302-41cc1000-f916-11e9-955f-013f21c0a75d.jpg)

-----

- [ ]
- [ ]

**What is happening:**
- Wrong rep

**Comment by Echinaceax** [comment]
tested earthen ring tabard
![image](https://user-images.githubusercontent.com/39439201/67642795-c8312380-f90f-11e9-9e19-01668e4a0aee.png)

**Comment by Rushor** [comment]
>You can never use that item (error msg) cant equip
>https://www.wowhead.com/item=65909/tabard-of-the-dragonmaw-clan

Because it's an horde side only item. It's indended to be like that :) On horde side i can use it.

**Comment by Echinaceax** [comment]
what rep is for SFK @Rushor - Shouldnt been earthern ring surely?

**Comment by Rushor** [comment]
It gaves rep for the Expedition faction
