### ISSUE TITLE
[Dungeon] Sunken Temple "The Temple of Hakkar"

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3750]
**Links:**
https://www.wowhead.com/sunken-temple

from WoWHead or our Armory

**What is happening:**

The boss that is supposed to be summon dont appear when you click on the pile of skulls.
https://imgur.com/a/tcBM6lY
For that reason you cant complete the quest
https://www.wowhead.com/quest=27633/the-blood-god-hakkar

The Boss Jammal´an the Prophet does a constant Yelling 
https://imgur.com/a/6q3jb8f

You get a quest from the last boss that you cant start by clicking on it.
https://classic.wowhead.com/item=10454/essence-of-eranikus#dropped-by

Low drop rate of cloth "Mageweave"

**What should happen:**

**Comment by Rushor** [comment]
https://www.wowhead.com/item=10454/essence-of-eranikus#comments

the item should be removed from the game since cata

**Comment by Rushor** [comment]
https://www.youtube.com/watch?v=i9vlUAweVJY

**Comment by Rushor** [comment]
cd added for the first yell of Boss Jammal´an the Prophet

**Comment by Rushor** [comment]
and boss added once you klicked on the object

![I](https://i.imgur.com/pQTyksT.jpg)
