### ISSUE TITLE
[Dungeon] Maraudon

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3751]
**Links:**
https://www.wowhead.com/maraudon

from WoWHead or our Armory

**What is happening:**
Tinkerer Gizlock Missing 
https://imgur.com/a/gE4WNmB

Putridus shadowstalker are not in stealth as they should be. Even tried without cat form
https://imgur.com/a/9uuWky9

Maraudon: Earthsong Falls Location entrence dont work. Cant click on it. 
https://imgur.com/a/t9VjQX7

**What should happen:**

**Comment by Jimpaa** [comment]
In this dungeon the quest is discovered Not sure how that works. The quest you should get is https://www.wowhead.com/quest=27698/servants-of-theradras

**Comment by Jimpaa** [comment]
Purple room you should discover Corruption in maraudon https://www.wowhead.com/quest=27697/corruption-in-maraudon

**Comment by Jimpaa** [comment]
maraudon earthsong falls you should discover https://www.wowhead.com/quest=27692/princess-theradras

**Comment by Rushor** [comment]
http://cata.cavernoftime.com/npc=13601#drop is there - updated his AI

**Comment by Rushor** [comment]
whole zone with all spawns and paths reworked

**Comment by Rushor** [comment]
will add quests now

**Comment by Rushor** [comment]
i will script it like that: if you enter orange or  Purple Entrance the quests will be added.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/nj6Ci8z.jpg)

* Maraudon - Putridus shadowstalker are now using their sneak ability.
* Maraudon - Portal to Inner Maraudon can now be used to teleport players.
* Maraudon - The quests - Servants of Theradras, Corruption in Maraudon & Princess Theradras will now be added to the player within entering the instance.

Cheers.
