### ISSUE TITLE
[Glyph][Spell][Talent] Shadow Word: Death bugged interaction

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3752]
**Links:**
https://cata-twinhead.twinstar.cz/?item=42414

**What is happening:**
when you use the 2 shadow words of death you dont get the mana back for the first cast thanks to a talent that grants you a lot of mana if you dont kill something with this ability.
Mind you if you wait for a second or 2 before casting the 2nd death you do gain both mana instances but this is not practical since the game just considers it that you casted it 2 seperate times instead of spamming it 2 times like you normally would.

**What should happen:**
You should gain mana both times when you use the abilities instantly

**Comment by Priestelar** [comment]
ty sry i will do so in future, i couldnt come up with the name either xD
Also another issue i have been experiencing is if you use shadow word death and it does NOT kill the target but you then kill the target with any other ability you also dont get mana from Masochism, is this now also resolved?

**Comment by Keader** [comment]
Yes, mashochism effect was delayed by 1 sec.
now will occour instant, avoid issues with desync  xD
