### ISSUE TITLE
[Dungeon] Shadow Labyrinth

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3754]
**Links:**
https://www.wowhead.com/shadow-labyrinth

from WoWHead or our Armory

**What is happening:**
The boss Grandmaster on heroic dropps normal loot.
https://imgur.com/a/gmqbDZr

Cant remember if there should be this amount of trash in this spot but it looks alot.
https://imgur.com/a/WGcYPoo

**What should happen:**

The boss should drop lvl 70 items not 68.

**Comment by Rushor** [comment]
the loottable on wowhead is simply wrong i guess

https://www.wowhead.com/npc=18732/grandmaster-vorpil#drops:mode=heroic

shows blue and epic loot

but if you click on it 
https://www.wowhead.com/item=27897/breastplate-of-many-graces&bonus=4091
https://www.wowhead.com/item=27897/breastplate-of-many-graces&bonus=4091

it's all the same. There are no heroic version of those items.

as is.

Cheers.
