### ISSUE TITLE
[Event] Pilgrims bounty issue 2 - Missing NPC - Alliance test.

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3755]
**What is happening:**
1 ) ![WoWScrnShot_102819_155901](https://user-images.githubusercontent.com/42302580/67697064-dc246600-f99f-11e9-9816-a77c7c2c6437.jpg)
The feast tables only spawned in exodar. It should spawn in all of the major city - Shattrath City, Dun Morogh, Elwynn Forest, Darkshore and Darnassus - https://www.wowhead.com/npc=32823/bountiful-table
 
2) NPC - **Bountiful Table Hostess** - https://www.wowhead.com/npc=34653 is also missing along with the feast tables above preventing players from picking up the quest https://www.wowhead.com/quest=14064/sharing-a-bountiful-feast

3) NPC -**Edward Winslow** https://www.wowhead.com/npc=34644 is missing from dun morogh preventing players from picking up the following quest  https://www.wowhead.com/quest=14028/cranberry-chutney 

4) NPC **Gregory Tabor** https://www.wowhead.com/npc=34675 Is missing from his location in Elwynn forest preventing players from picking up the following quest https://www.wowhead.com/quest=14035/slow-roasted-turkey and quest https://www.wowhead.com/quest=14023/spice-bread-stuffing

5) NPC  **Isaac Allerton**missing from his location in darnassus preventing players from picking up the following quest https://www.wowhead.com/quest=14033/candied-sweet-potatoes

6) NPC **Jasper Moore** https://www.wowhead.com/npc=34744 is missing from his location in elwynn forest preventing players from collecting  the following quest https://www.wowhead.com/quest=14024/pumpkin-pie,  https://www.wowhead.com/quest=14030/theyre-ravenous-in-darnassus and https://www.wowhead.com/quest=14055/she-says-potato

7) NPC  **Ellen Moore** https://www.wowhead.com/npc=34710 missing from her location in elwynn forest preventing players picking up the following quest https://www.wowhead.com/quest=14053/were-out-of-cranberry-chutney-again

8) NPC **Caitrin Ironkettle** https://www.wowhead.com/npc=34708 Missing from her location in Dun Morogh preventing players drom picking up the following quests https://www.wowhead.com/quest=14048/cant-get-enough-turkey and https://www.wowhead.com/quest=14051/dont-forget-the-stuffing

9) NPC **Mary Allerton** https://www.wowhead.com/npc=34711 is missing from her location in darnassus preventing players picking up the following quest https://www.wowhead.com/quest=14054/easy-as-pie

_horde test to follow...._

**Comment by Rushor** [comment]
https://i.imgur.com/ayetg9z.jpg https://i.imgur.com/JqOiaSY.jpg

all done. i did the whole questchain and could add/complete all quests in a row. should all be fine now.
