### ISSUE TITLE
[Quest] By the Light of the Stars

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3757]
wowhead.com/quest=27549/by-the-light-of-the-stars

**What is happening:**

Sapphire Spectacles quest item doesn't reveal suspended starlight when worn.

**What should happen:**

Wearing Sapphire Spectacles should reveal that there are small yellow orbs floating around, and then you right click to loot them.

**Comment by Priestelar** [comment]
@Echinaceax dupplicate see #3075 and #3673
