### ISSUE TITLE
[NPC] Nordrassil Druid - ( doubles) - Mount Hyjal 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3758]
**Links:**

https://www.wowhead.com/npc=38952/nordrassil-druid

![lol 3 sets of doubles](https://user-images.githubusercontent.com/39439201/67760100-f2363300-fa40-11e9-8cc4-8ef2d8a7a0b7.jpg)

**What is happening:**
- Since some phasing has been fixed i noticed doubles where there wasnt before
on my horde toon

i will see from my Ally and see if same 

edit - yes same on ally 
![ally x3](https://user-images.githubusercontent.com/39439201/67760742-252cf680-fa42-11e9-98da-3335b1fe8106.jpg)

**Comment by Rushor** [comment]
removed the doubles :)

**Comment by Rushor** [comment]
![I](https://i.imgur.com/euyleOs.jpg)
