### ISSUE TITLE
[Quest] Petrified Delicacies - Deepholm

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3759]
https://www.wowhead.com/quest=26507/petrified-delicacies

Pebble doesn't accompany me when in the quest area, so I cannot turn the quest in.
Also petrified bats on the ground cannot be interacted with, but you can still loot them from killing basilisks.

**Comment by Rushor** [comment]
static spawn for peeple added. and the bats can give loot now.

https://i.imgur.com/9ax4Bjv.jpg
