### ISSUE TITLE
[Dungeon] Sethekk halls

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3761]
**Links:**
https://www.wowhead.com/sethekk-halls

from WoWHead or our Armory

**What is happening:**
The boss https://www.wowhead.com/npc=18472/darkweaver-syth#drops is double spawning adds on normal https://imgur.com/a/ljIU2dM

Npc for quests missing "will be added"

**What should happen:**
The boss should only spawn 4 adds at a time.

**Comment by Rushor** [comment]
those two creatures are missing 54840, 54847
