### ISSUE TITLE
[Event] Pilgrims Bounty issue 3- missing NPC - Horde test

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3762]
1) https://www.wowhead.com/npc=32823/bountiful-table
![WoWScrnShot_102919_143444](https://user-images.githubusercontent.com/42302580/67781843-dd1ccc80-fa5f-11e9-82bc-7a0a332a3847.jpg) only spawned in silver moon - should be spawned outside each major horde city,

2) NPC **Bountiful Feast Hostess** https://www.wowhead.com/npc=34654 -also didnt spawn at the above locations along with the tabels.

3) NPC **Miles Standish** https://www.wowhead.com/npc=34677 didnt spawn in his required location prevent the pick up ofthe following quests  https://www.wowhead.com/quest=14047/slow-roasted-turkey, https://www.wowhead.com/quest=14037/spice-bread-stuffing

4) NPC **Francis Eaton** https://www.wowhead.com/npc=34679 didnt spawn at her location preventing the pick up of the following quests:
https://www.wowhead.com/quest=14044/undersupplied-in-the-undercity
https://www.wowhead.com/quest=14041/cranberry-chutney

5) NPC **William Mullins** https://www.wowhead.com/npc=34768 Didnt spawn at his location preventing the pick of the following quests:
 https://www.wowhead.com/quest=14040/pumpkin-pie
https://www.wowhead.com/quest=14058/she-says-potato

6) NPC **Dokin Farplain**  https://www.wowhead.com/npc=34678 did not spawn in his location preventing the pick up of the following quest:
https://www.wowhead.com/quest=14043/candied-sweet-potatoes

7) NPC **Mahara Goldwheat** https://www.wowhead.com/npc=34714 didnt spawn at her location preventing the pick up of the following quest:
https://www.wowhead.com/quest=14060/easy-as-pie

8) NPC **Ondani Greatmil**l https://www.wowhead.com/npc=34713 didnt spawn at his location preventing pick up of the following quests:
https://www.wowhead.com/quest=14061/cant-get-enough-turkey
https://www.wowhead.com/quest=14062/dont-forget-the-stuffing

9) NPC **Roberta Carter** https://www.wowhead.com/npc=34712 didnt spawn at his location preventing the pick up of the following quest:
https://www.wowhead.com/quest=14059/were-out-of-cranberry-chutney-again

**Comment by Rushor** [comment]
all added for horde aswell 
![I](https://i.imgur.com/EyKQBEC.jpg) 
![I](https://i.imgur.com/w1fUwsd.jpg)

i could easy complete the questchain now.
