### ISSUE TITLE
[Dungeon] Stratholme quests

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3763]
**Links:**
Main gate
https://www.youtube.com/watch?v=9OIcBvC7orw&t=91s
Service entrence
https://www.youtube.com/watch?v=TKqksw8Po7g

from WoWHead or our Armory

**What is happening:**
Stratholme Main gate
https://www.wowhead.com/npc=45323/packmaster-stonebruiser Should spawn and give the quest 
https://www.wowhead.com/quest=27192/the-great-fras-siabi

https://www.wowhead.com/npc=16115/crusade-commander-eligor-dawnbringer Should also spawn inside and give 3 quests.
https://www.wowhead.com/quest=27208/the-dreadlord-balnazzar
https://www.wowhead.com/quest=27305/of-love-and-family
https://www.wowhead.com/quest=27223/retribution

https://www.wowhead.com/npc=45201/master-craftsman-wilhelm should also spawn inside and give
https://www.wowhead.com/quest=27185/cutting-the-competition

Stratholme Service entrence in the chapel
https://www.wowhead.com/npc=45323/packmaster-stonebruiser Should spawn and give
https://www.wowhead.com/quest=27352/liquid-gold

https://www.wowhead.com/npc=45330/archmage-angela-dosantos should spawn and give
https://www.wowhead.com/quest=27359/argent-reinforcements

https://www.wowhead.com/npc=45206/crusade-commander-korfax should spawn and give
https://www.wowhead.com/quest=27228/man-against-abomination

https://www.wowhead.com/npc=45329/crusade-commander-eligor-dawnbringer should spawn and give 
https://www.wowhead.com/quest=27227/lord-aurius-rivendare

https://www.wowhead.com/npc=45331/master-craftsman-wilhelm should spawn and give
https://www.wowhead.com/quest=27230/weapons-for-war

**What should happen:**

They all should spawn in the begining of the dungeon and give the quests for the specifik dungeon

**Comment by Priestelar** [comment]
Also check if quest https://wow.gamepedia.com/Annals_of_the_Silver_Hand_(quest) is working since its a quest from outside sending you into Stratholme

**Comment by Rushor** [comment]
also made the quest repeatable now.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/r8cRRRe.jpg)
![I](https://i.imgur.com/R1oHjEC.jpg)
![I](https://i.imgur.com/Ufsu54u.jpg)
![I](https://i.imgur.com/DxZguK1.jpg)

Made the quest repeatable.
* Stratholme - The Unforgiven has been added to the instance.
* Stratholme - The questgivers: 'Crusade Commander Eligor Dawnbringer','Master Craftsman Wilhelm','Crusade Commander Korfax','Packmaster Stonebruiser','Archmage Angela Dosantos' have all been added to the game and all their scripts have been implemented. They will spawn at various places depending on which bosses have been killed.
