### ISSUE TITLE
[Dungeon][TBC] The Mechanar door bug

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3764]
This door should open after killing the first boss but it does not making the instance undoable.
![WoWScrnShot_102819_213919](https://user-images.githubusercontent.com/16594771/67794215-fa17c680-fa84-11e9-92fe-809f58fe2991.jpg)

**Comment by Nacho-k** [comment]
Did you kill both of the gatekeepers? because i remember doing this dungeon just fine.

**Comment by sarahkay88** [comment]
U get an item of the gate keepers. U have to combine both items to get through the door.

**Comment by Priestelar** [comment]
i dont remember them dropping anything like that, will check now again

**Comment by sarahkay88** [comment]
Crystal fordge key.. Once combined loot the creat bear the door. After the loot the cog wheel should activated to open the gate.

**Comment by Nacho-k** [comment]
Just killing the gatekeepers is enough for the gate to open, but they drop a jagged blue crystal and jagged red crystal,
https://www.wowhead.com/item=30436/jagged-blue-crystal
https://www.wowhead.com/item=30437/jagged-red-crystal
After combining them it should give you a Crystal combine
https://www.wowhead.com/spell=36565/crystal-combine
if you combine them it gives you nothing and says something like "item not found"

**Comment by Nacho-k** [comment]
Just checked and the Cache of the Legion Key was supposed to open a chest, but in cataclysm the key requirement for the chest was removed

**Comment by Priestelar** [comment]
these items are not available at the moment
![WoWScrnShot_102919_202900](https://user-images.githubusercontent.com/16594771/67797705-e40d0480-fa8a-11e9-83da-8ca539e3c702.jpg)

**Comment by sarahkay88** [comment]
Gates should open to allow players to progress

**Comment by Priestelar** [comment]
Horde players say it is working, but might only be alliance bug.

**Comment by Priestelar** [comment]
Just killing the gatekeepers is enough for the gate to open, but they drop a jagged blue crystal and jagged red crystal,
https://www.wowhead.com/item=30436/jagged-blue-crystal
https://www.wowhead.com/item=30437/jagged-red-crystal
After combining them it should give you a Cache of the Legion Key
https://www.wowhead.com/item=30438/cache-of-the-legion-key
Spell: https://www.wowhead.com/spell=36565/crystal-combine
if you combine them it gives you nothing and says something like "item not found"

**Comment by Kitzunu** [comment]
I have a fix for this... Will send to somebody to apply.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/Z4EyKAr.jpg)
![I](https://i.imgur.com/1QpPmaB.jpg)

lol this was never an issue.

you need to kill DATA_GATEWATCHER_IRON_HAND and DATA_GATEWATCHER_GYROKILL in order to open the gates. anyway codestyle fix from kitz applied :)

Cheers.
