### ISSUE TITLE
[Dungeon] Scholomance Quests

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3765]
**Links:**
https://www.youtube.com/watch?v=j7d31aHvEkA
from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/npc=45109/weldon-barov should spawn and give
https://www.wowhead.com/quest=27143/barov-family-fortune
https://www.wowhead.com/quest=27145/plagued-hatchlings-for-now

https://www.wowhead.com/npc=88318/alexi-barov should spawn and give 
https://www.wowhead.com/quest=27140/alexis-gambit
https://www.wowhead.com/quest=27142/the-lich-ras-frostwhisper

https://classic.wowhead.com/npc=11216/eva-sarkhoff should spawn and give 
https://classic.wowhead.com/quest=5382/doctor-theolen-krastinov-the-butcher
https://classic.wowhead.com/quest=5384/kirtonos-the-herald

https://classic.wowhead.com/npc=11217/lucien-sarkhoff should spawn and give 
https://www.wowhead.com/quest=27148/schools-out-forever

**What should happen:**

They should spawn and give out the quest that is intended

**Comment by Priestelar** [comment]
Also check https://wow.gamepedia.com/Aberrations_of_Bone This quest sends you from light's hope chapel into the Scholomance dungeon to kill Rattlegore. NOTE this is a repeatable quest

**Comment by Rushor** [comment]
![I](https://i.imgur.com/dEr4Ga6.jpg)
![I](https://i.imgur.com/8TLhUoM.jpg)

* Scholomance - The loottables for all bosses in Scholomance have been reworked and should now always contain 1-2 blue items.
* Scholomance - All spawns for Weldon Barov, Alexi Barov, Eva Sarkhoff & Lucien Sarkhoff have been added to the instance with the fitting quests. All quests can now be done and are scripted.
* Scholomance - The introevent for Kirtonos the Herald has been fixed.
* Scholomance - All doors in the instance can now be opened by the players.

Cheers.

**Comment by Rushor** [comment]
also made the quest repeatable now.
