### ISSUE TITLE
[General] Herb spawns in the air - add GPS to report

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3766]
**What is happening:**
- Herb spawns are terrible 

Deepholm herbs 
![herb1](https://user-images.githubusercontent.com/39439201/67799488-b83b5000-fa85-11e9-932d-7ec117c118b0.jpg)

here is mine so far 
![herb2](https://user-images.githubusercontent.com/39439201/67799497-be313100-fa85-11e9-9205-4f55a755faf5.jpg)
![herb3](https://user-images.githubusercontent.com/39439201/67799502-bffaf480-fa85-11e9-9d67-e477fcf549b8.jpg)
![herb4](https://user-images.githubusercontent.com/39439201/67799503-c12c2180-fa85-11e9-8f41-998e472ea000.jpg)
![herb5](https://user-images.githubusercontent.com/39439201/67799513-c5583f00-fa85-11e9-8361-9c294fe1bddf.jpg)
![herb6](https://user-images.githubusercontent.com/39439201/67799515-c6896c00-fa85-11e9-9f56-a476fdac578f.jpg)
![herb7](https://user-images.githubusercontent.com/39439201/67799517-c7220280-fa85-11e9-9e71-a024f77e0493.jpg)
![herb8](https://user-images.githubusercontent.com/39439201/67800486-993dbd80-fa87-11e9-851a-d293a9a57b45.jpg)
![herb9](https://user-images.githubusercontent.com/39439201/67800488-99d65400-fa87-11e9-9933-784f98c07702.jpg)
![herb10](https://user-images.githubusercontent.com/39439201/67800671-f3d71980-fa87-11e9-89c3-bed34d627afb.jpg)
![herb11](https://user-images.githubusercontent.com/39439201/67801296-2d5c5480-fa89-11e9-9a5f-b85c7fb35ca9.jpg)
![herb12](https://user-images.githubusercontent.com/39439201/67801396-6399d400-fa89-11e9-9dc6-04a1e2434b3c.jpg)
![herb13](https://user-images.githubusercontent.com/39439201/67801531-a0fe6180-fa89-11e9-99cf-8995423b1ca1.jpg)

**Comment by Slydee23** [comment]
Done

**Comment by Rushor** [comment]
202747 
202750
