### ISSUE TITLE
[Dungeon][TBC] The Sethekk Halls 2 players bug

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3767]
We tried to enter the instance together but its not possible, it will always say: "an encounter is in progress" whenever one player enters the 2nd player cannot, we tried to alternate and reset the instance several times but nothing worked.

Tested on alliance

![WoWScrnShot_102919_213736](https://user-images.githubusercontent.com/16594771/67802974-d197c880-fa94-11e9-8401-970ea41b4847.jpg)

**Comment by Kitzunu** [comment]
This only happens for sethekk halls?

**Comment by Priestelar** [comment]
@Kitzunu yeah its still an issue and it only happens in this dungeon 
![WoWScrnShot_113019_164217](https://user-images.githubusercontent.com/16594771/69902292-72c7b680-1394-11ea-89fa-3ffb4f76dab1.jpg) 
We can each enter separately but not together

**Comment by Rushor** [comment]
even more strange! :o is the dungeonfinder working on it?

**Comment by Rushor** [comment]
reason was a instance bossstate

![I](https://i.imgur.com/cGyeQ2x.jpg)

fixed and cheers.
