### ISSUE TITLE
[Dungeon] Zul´Farrak Quests

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3768]
**Links:**
https://www.youtube.com/watch?v=g-kIg-wowlw
from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/npc=40712/mazogas-spirit should spawn and give
https://www.wowhead.com/quest=27068/chief-ukorz-sandscalp
https://www.wowhead.com/quest=27071/wrath-of-the-sandfury

https://www.wowhead.com/npc=7407/chief-engineer-bilgewhizzle should spawn and give
https://www.wowhead.com/quest=27070/a-fools-errand

https://www.wowhead.com/npc=44929/tranrek Should spawn and give
https://www.wowhead.com/quest=27076/breaking-and-entering

**What should happen:**

They should be spawned inside the dungeon and giving out the quests.

**Comment by Rushor** [comment]
* Zul''Farrak - Mazoga's Spirit, Chief Engineer Bilgewhizzle & Tran'rek have been added to the instance and now provide all their quests.
