### ISSUE TITLE
[Dungeon] Razorfen downs

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3769]
**Links:**
https://www.youtube.com/watch?v=5yOYbrnvvW8

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/npc=44837/koristrasza Should also give the quest 
https://www.wowhead.com/quest=27009/the-coldbringer

https://classic.wowhead.com/npc=8516/belnistrasz gives the quest called 
https://classic.wowhead.com/quest=3525/extinguishing-the-idol#comments 
The escort quest does not work he wont move.

https://www.wowhead.com/quest=27029/cure-the-scourge 
Does not drop any Withered tusk from any mobs in the dungeon.

The mob drops lower lvl greens then the dungeon should
https://imgur.com/a/8l4LcfL
https://imgur.com/a/i9mZQcA

**What should happen:**

Should give the 3rd quest for the dungeon currently only giving 2 quests.

The boars should drop the quest item but it does not.

**Comment by Rushor** [comment]
hmm wtf is wrog with this quest :O

**Comment by Rushor** [comment]
this is the real quest http://cata.cavernoftime.com/quest=27022

**Comment by Rushor** [comment]
itemdrops added, questevent added

![I](https://i.imgur.com/Hdt1ObO.jpg)

Cheers.
