### ISSUE TITLE
[Quest] Gahrron's Withering Cauldron - missing prerequisites - Western Plaguelands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#377]
Quest - https://www.wowhead.com/quest=27053/gahrrons-withering-cauldron

- This quest is missing from Horde side
- will miss the series 

**Series**
**1. Gahrron's Withering Cauldron**
2. Return to the Stead
3. Desperate Acts
4. Students of Krastinov

![gahrron s withering cauldron](https://user-images.githubusercontent.com/39439201/50702745-1bb94480-1052-11e9-8e7f-9ca3245ca8cc.jpg)

**Comment by sarahkay88** [comment]
I will add that this is available for alliance. the quest should be viewable to us both ally n horde but only ally cant see and accept.

**Comment by Dranah** [comment]
https://www.wowhead.com/npc=44454/field-agent-kaartish
Please next time, include the NPC ID for the quest giver that should offer the quest.
You're getting lazy with these reports ma'ams.

On-topic: I believe this quest has a prerequisite that isn't shown directly on wowhead. Comments confirm that https://www.wowhead.com/quest=27002/an-audience-with-the-highlord should be complete before this one is available.

"By Mazzacr (4,324 –  14·36)  on 2011/03/27 (Patch 4.0.6) |   |  
-- | -- | --
It's not listed but it seems I had a prerequisite for this either An Audience with the Highlord or The Long Trip Home."

The audience quest is at the end of chain started by "A New Era For the Plaguelands" which I see you haven't completed yet.
I'm not sure if Alliance can pick up the quest without a prerequisite or @sarahkay88 simply completed the other chain already.
Can you confirm?

**Comment by sarahkay88** [comment]
Didn't do the prequest

**Comment by Dranah** [comment]
Ok so alliance is missing prerequisites. That's not a life breaking issue. 
The only question remains if the quest properly unlocks for Horde after Audience is completed or not.

**Comment by sarahkay88** [comment]
That quest is to do with the era issue.

**Comment by Dranah** [comment]
Ok, so apparently the quest has a level requirement of lvl 36 which is why @Echinaceax couldn't pick it up.
However, the missing prerequisite IS an issue, and for both sides.
This quest chain should not unlock before handing in https://www.wowhead.com/quest=27002/an-audience-with-the-highlord

**Comment by Echinaceax** [comment]
- Tested my Dranah 
- Needed lvl36 upwards

**Confirmed** 

![i can now](https://user-images.githubusercontent.com/39439201/50721428-c3b92700-10bf-11e9-948d-55b645263554.jpg)

**Comment by Echinaceax** [comment]
**Quest it completed** 

- Had to kill cauldron-lord-soulwrath first
- Then the cauldron is Available to complete 

https://www.wowhead.com/npc=11078/https://www.wowhead.com/npc=11078/cauldron-lord-soulwrath

- Needed his key Gahrron's Withering Cauldron Key first. 

https://www.wowhead.com/item=13196/gahrrons-withering-cauldron-key

**Comment by Echinaceax** [comment]
- Desperate Acts collected (horde)

**Comment by Dranah** [comment]
This quest is simply available too early, for both factions it appears instantly, while it should only be available once you hand in Audience with the Highlord. I tested that myself. The prerequisite chain happens to be broken (because of Era quest) but that's unrelated.
The quest itself is doable, only missing prerequisite https://www.wowhead.com/quest=27002/an-audience-with-the-highlord
PS: I'll clean up this thread cause it's getting messy and flooded with guesses and half-informations. Please do not overwrite a title i've put without consulting on discord first. Discord is the place to discuss, github threads should be clean and easy to look through
