### ISSUE TITLE
[Dungeon] Razorfen Kraul

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3770]
**Links:**
https://www.youtube.com/watch?v=qdYW_qzHIBM

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/npc=44402/auld-stonespire Should spawn and give
https://www.wowhead.com/quest=26906/agamaggan
https://www.wowhead.com/quest=26901/going-going-guano
https://www.wowhead.com/quest=26907/take-them-down

https://www.wowhead.com/npc=44415/spirit-of-agamaggan is not at the spot so you can turn in the quest.
https://imgur.com/a/osctGgO

The follow up quest is called
https://www.wowhead.com/npc=44415/spirit-of-agamaggan

The green loot from mobs seems abit low aswell but not that bad.
https://imgur.com/a/SCST04p

**What should happen:**

**Comment by Rushor** [comment]
Both creatures added. All quests are working.

![I](https://i.imgur.com/9FTcdHT.jpg)

Cheers.
