### ISSUE TITLE
[Dungeon] Dire maul: Warpwood Quarter EAST

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3771]
**Links:**
https://www.youtube.com/watch?v=5dsZRZ3C2Ak

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/npc=44971/ambassador-daggthol Is missing and should give quests
https://www.wowhead.com/quest=27108/lethtendriss-web
https://www.wowhead.com/quest=27107/pusillin-the-thief
Proof of missing npc https://imgur.com/a/rr52PIx

https://www.wowhead.com/npc=14354/pusillin Is skipping a few spots where u have to talk to him. 
He jumps from entrence to the other side instant and not running around like hes suppose to.
https://imgur.com/a/iQ9SeQP

And this is how it looks before jump 
https://imgur.com/a/7TFJNv8

**What should happen:**

There should be a npc that gives 2 extra quest besides the ones that is inside already. 

Pusillin Should go from A - B and not jumping from A-D

**Comment by Rushor** [comment]
his first option should be Game? Are you crazy?

**Comment by Rushor** [comment]
questgiver added. path for pussilin corrected

![I](https://i.imgur.com/7QB72VF.jpg)
![I](https://i.imgur.com/KUsW6BS.jpg)

Cheers.
