### ISSUE TITLE
[Dungeon] Dire Maul NORTH

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3772]
**Links:**
https://www.youtube.com/watch?v=yFAEbbo3VlA

from WoWHead or our Armory

**What is happening:**
After 3rd boss most of the mobs are Untargetable and you can run almost past the rest of the dungeon without killing anything. 

https://imgur.com/a/ZGCChg0
https://imgur.com/a/hSwde3F
https://imgur.com/a/7lDfVfa

And then there is one mob i can target compere to the rest of the ogres.
https://imgur.com/a/NwWmYOx

https://www.wowhead.com/quest=27118/a-broken-trap is auto complete but it dosnt turn blue as it should so something dosnt work with it. See SS
https://imgur.com/a/paoDSiv

**What should happen:**
You should be able to kill all the mobs :)

The quest should say something and it should turn blue so you can trap the boss that spawns.

**Comment by Rushor** [comment]
note to self: do not forget: https://github.com/WoWManiaUK/Blackwing-Lair/issues/3663

**Comment by Rushor** [comment]
untargetable issue already fixed.

will fix the trap now

**Comment by Rushor** [comment]
okay once you completed the quest a trap will spawn.

as soon as Guard Slip'kik rus over it he will get frozen. you cannot kill him then. this is blizzlike. it#s an option to skip that boss.

![I](https://i.imgur.com/0mILuJw.jpg)
![I](https://i.imgur.com/JmzBA9c.jpg)
