### ISSUE TITLE
[Dungeon] Blackfathom Deeps 

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3773]
**Links:**
https://www.youtube.com/watch?v=2gIOf4h_KQY
from WoWHead or our Armory

**What is happening:**¨

https://www.wowhead.com/npc=33261/sentinel-trainee-issara should spawn and give
https://www.wowhead.com/quest=26885/knowledge-in-the-deeps

https://www.wowhead.com/npc=33258/relwyn-shadestar should spawn and give
https://www.wowhead.com/quest=26884/researching-the-corruption

https://www.wowhead.com/npc=75607/ashelan-northwood Should spawn and give
https://www.wowhead.com/search?q=in+search+of+thaelrid

https://www.wowhead.com/npc=4787/scout-thaelrid Should give the quest
https://www.wowhead.com/quest=26882/blackfathom-villainy

**What should happen:**

Missing npcs for some quests in the dungeon .
Scout Thaelrid is there but not giving a quest.

**Comment by Rushor** [comment]
move to https://github.com/WoWManiaUK/Blackwing-Lair/issues/3663
