### ISSUE TITLE
[Proffession][Archeology] Altar of zul unlootable section

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3774]
http://www.wowdigs.com/eastern/the_hinterlands_alter_of_zul_digsite_wowdigs.html
This digsite is a bit bigger than it should be, and my one relic has spawned up this cliff in a section that i cannot stand on, the next section i could stand on is outside of the digsite and this bug is causing me to forever have a "dead" digsite on my Eastern Kingdoms continent as there is no way for digsites to change untill they are completed. 

Here is a screenshot of the bug:
![WoWScrnShot_103019_211830](https://user-images.githubusercontent.com/16594771/67892194-d9bb3b00-fb5c-11e9-97c3-9ad2c37073fd.jpg)

This relic should spawn closer down the cliff to be lootable

**Comment by Rushor** [comment]
Can you take a look at this @Keader? 

I think  function

GetNearestSite 

has to be changed here :o

**Comment by Priestelar** [comment]
will take a look in dev :)
