### ISSUE TITLE
[Spell/DK] 98966 Item - Death Knight T12 Blood 4P Bonus not implemented

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Blackwing-Lair#3779]
98966 Item - Death Knight T12 Blood 4P Bonus is not implemented

**Comment by mfranca0009** [comment]
This is all set, once Dancing Rune Weapon buff (parry increase) has expired, which is the same time the rune weapon summon despawns, it will give you 15% parry increase for 12 seconds.

https://www.wowhead.com/spell=98966/item-death-knight-t12-blood-4p-bonus

The aura being given to the player should be: Flaming Rune Weapon (Spell ID 101162).

**Comment by golosomie** [comment]
@mfranca0009 Confirmed fixed on PTR.
