### ISSUE TITLE
[NPC] Cheerful Human Spirit - (Day of the dead) - Stormwind 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3780]
**Links:**

https://www.wowhead.com/npc=34435/cheerful-human-spirit
https://wowwiki.fandom.com/wiki/Ghostly_Cooking_Fire
**What is happening:**
- npc missing
- ghostly cooking fire also missing

**What should happen:**
_This NPC can be found in Stormwind City while the day of the dead event is active_
https://www.wowhead.com/quest=14166/the-grateful-dead

**Comment by Rushor** [comment]
all added https://i.imgur.com/AhgDyza.jpg

**Comment by Echinaceax** [comment]
NPC cant be seen by players
