### ISSUE TITLE
[Death Knight] Raise Dead (issue 3)

### ISSUE THREAD

**Issue by Batraneluu** [WoWManiaUK/Blackwing-Lair#3781]
**Links:** 
http://cata.cavernoftime.com/spell=46584

from WoWHead or our Armory

**What is happening:**
The ghoul is doing 115-130 damage per hit

**What should happen:**
Ghoul should take a percentage of your strength before summoned and increase his damage done.
I think it should also have an ability named (Claw)
![WoWScrnShot_110119_165335](https://user-images.githubusercontent.com/53946478/68034185-e3ae7c80-fcc9-11e9-93c6-22c3aeb621da.jpg)
![WoWScrnShot_110119_165333](https://user-images.githubusercontent.com/53946478/68034208-f5901f80-fcc9-11e9-99ee-7d9d1b10f824.jpg)

**Comment by sarahkay88** [comment]
![WoWScrnShot_111619_131949](https://user-images.githubusercontent.com/42302580/68993846-56942780-0874-11ea-9fe7-60056753371d.jpg) - it does have claw

![dk pet](https://user-images.githubusercontent.com/42302580/68993852-64e24380-0874-11ea-9934-72792046374c.jpg)

**Comment by Batraneluu** [comment]
You forgot i was in frost spec not unholy

**Comment by Shoogii** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/3870  
yes allready reported here^^ , maybe post ur screenshots as prove
