### ISSUE TITLE
[NPC] Cheerful Goblin Spirit - (Day of the dead ) - Durotar

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3782]
**Links:**
https://www.wowhead.com/npc=46901/cheerful-goblin-spirit
https://wowwiki.fandom.com/wiki/Cheerful_Goblin_Spirit

**What is happening:**
- missing 

**What should happen:**
_This NPC can be found in Durotar while the day of the dead event is active_
https://www.wowhead.com/quest=14166/the-grateful-dead

**Comment by Rushor** [comment]
added https://i.imgur.com/Y9NQN4Y.jpg
