### ISSUE TITLE
[Quest] The Black Knight of Silverpine? - ID 13634 - Silverpine Forest

### ISSUE THREAD

**Issue by karteil** [WoWManiaUK/Blackwing-Lair#3784]
**Links:**
https://www.wowhead.com/quest=13634/the-black-knight-of-silverpine

**What is happening:**
Clicking in the Dusty Journal object (ID 194341) doesn't give the quest item Dusty Journal (ID 45062 )

**What should happen:**
It just should give the quest item [Dusty Journal](https://www.wowhead.com/item=45062/dusty-journal)

Thank you for the work

**Comment by Rushor** [comment]
fixed with next update
