### ISSUE TITLE
[Mount][Zone] Vashjir Abyssal seahorse movespeed bug

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3785]
https://www.wowhead.com/item=54465/vashjir-seahorse#reward-from-q

The mount states that it should be granting 450% movespeed in vashjir however i am only getting my normal mount flyspeed underwater.
As seen in this screenshot here the movespeed values are not correct, defeating the purpose of this mount.

![WoWScrnShot_110219_003039](https://user-images.githubusercontent.com/16594771/68060305-67875980-fd08-11e9-9a87-f2fefaca4191.jpg)

**Comment by Rushor** [comment]
can you show me a video of the speed?

**Comment by Rushor** [comment]
Will assign it to you Keader since this is more a spell thing. Please also remember that disable of anticheat

**Comment by Keader** [comment]
Carbonite "Bug"
It calculate your speed mod, based in cells change (based in your position)
But you're not in ground, you're in water, that use MOVE_SWIM instead MOVE_RUN. Where MOVE_SWIM < MOVE_RUN.
Mount add 450% in your swin rate, and it's working fine.

**Comment by Priestelar** [comment]
how could carbonite do this to me? i feel so betrayed!
