### ISSUE TITLE
Stable Master

### ISSUE THREAD

**Issue by Po0dog** [WoWManiaUK/Blackwing-Lair#3786]
**Links:**

from WoWHead or our Armory

**What is happening:**
Whenever I use a stable master in Orgrimar or Under City, my game crashes. It happens when I move the pet over to the NPC. I made a screen shot of the error message: 
[https://i.imgur.com/ICgN4Zu.png](url)

**What should happen:**
Pet should go into an available slot. Then you close the menu.

**Comment by Rushor** [comment]
works fine for me.

![I](https://i.imgur.com/ooGWCJx.jpg)

Please make sure that you use the client form website and have it up to date. https://wow-reign.com/start

**Comment by Po0dog** [comment]
The client is from you're website and its version 1.0.5
