### ISSUE TITLE
[Spell/Hunter] Focus Fire - Animation

### ISSUE THREAD

**Issue by Batraneluu** [WoWManiaUK/Blackwing-Lair#3789]
**Links:**

from WoWHead or our Armory
http://cata.cavernoftime.com/spell=82692
**What is happening:**
When your pet gets 5 stacks of Frenzy your spell doesn't light up ( animation missing)

**What should happen:**

When your pet gets 5 stacks of Frenzy your spell should light up ( animation missing)
https://youtu.be/9znbWaJRB1Q?t=795

**Comment by Rushor** [comment]
SPELL_HUNTER_FOCUS_FIRE                         = 82692,
    SPELL_HUNTER_PET_FRENZY                         = 19615,
