### ISSUE TITLE
[NPC] Mount Hyjal

### ISSUE THREAD

**Issue by Batraneluu** [WoWManiaUK/Blackwing-Lair#3790]
**Links:**
https://wow.gamepedia.com/Yargra_Blackscar
from WoWHead or our Armory

**What is happening:**
Position of the NPC can't be reached.
![WoWScrnShot_110219_175841](https://user-images.githubusercontent.com/53946478/68073623-b5e53880-fd9a-11e9-8914-c80c2ec420ac.jpg)
**What should happen:**

You should be able to speak with the NPC since quests are available on it.

**Comment by Priestelar** [comment]
I saw this last week, thought she was only stuck there temporarily fighting one mob, did not think it would persist.

**Comment by Echinaceax** [comment]
i also seen this but for me after i killed the npc it was killing she came down

**Comment by Rushor** [comment]
Can someone Show me a Video with this guy maybe?

**Comment by Priestelar** [comment]
https://www.youtube.com/watch?v=dlSepwujb10

I was not able to find her in the same position as on live but when i got here she was also fight waaaay up there where the dark iron laborer is. she should NOT be engaging in combat

**Comment by Rushor** [comment]
passive now - will no longer engage combat

**Comment by Echinaceax** [comment]
@Batraneluu please dont close your own reports, when fixed in dev labeles are added the owner will close then when hes added the fix to the live server
