### ISSUE TITLE
[Quest/Uldum] Colossal Guardians

### ISSUE THREAD

**Issue by Batraneluu** [WoWManiaUK/Blackwing-Lair#3792]
**Links:**
https://www.wowhead.com/quest=27623/colossal-guardians
from WoWHead or our Armory

**What is happening:**
There is a copy of every Colossal Guardian underground.
![WoWScrnShot_110319_022710](https://user-images.githubusercontent.com/53946478/68078619-780c0280-fde2-11e9-940e-83a8ce0800be.jpg)
![WoWScrnShot_110319_022813](https://user-images.githubusercontent.com/53946478/68078620-7b9f8980-fde2-11e9-96f9-0b375617b759.jpg)

**What should happen:**

https://www.youtube.com/watch?v=124QXHSOsyw

**Comment by Priestelar** [comment]
@Echinaceax dupplicate see #3673

**Comment by Rushor** [comment]
ahh thank you. i fixed it now (this bug at least) only one creature active now.

**Comment by Echinaceax** [comment]
@Batraneluu please dont close your own reports after fixed labels have been added.
the own closes when he has added to the live server
