### ISSUE TITLE
[Item] Drums of Forgotten Kings 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3794]
**Links:**

https://www.wowhead.com/item=49633/drums-of-forgotten-kings

**What is happening:**
- This can currently be cast on low players after inv to group 
tested in dev

**What should happen:**
_this should only be able to be applied to 70 up not a level 10 - 20 toon_

**Comment by Rushor** [comment]
the other 3 drums can be used at any level but only effect players up to level 79

**Comment by Rushor** [comment]
Does NOT work for party member lower than level 60

By foxdodo (1,348 – 7·12) on 2011/10/05 (Patch 4.2.2)

https://www.wowhead.com/item=49633/drums-of-forgotten-kings#comments

will add that conditions

**Comment by Rushor** [comment]
only targets level 60 and higher now.

![I](https://i.imgur.com/xMNCsZn.jpg)
![I](https://i.imgur.com/muDxuQY.jpg)
