### ISSUE TITLE
[Item] Drums of the Wild

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3795]
**Links:**
https://cata-twinhead.twinstar.cz/?item=49634
https://www.wowhead.com/item=49634/drums-of-the-wild

**What is happening:**
- This can currently be cast on low players after inv to group tested on lvl 10
i was lvl 85 and other was lvl 10 and they also got the healing effect 2000
tested in dev

**What should happen:**
_this should only be able to be applied to 70 up not a level 10 - 20 toon_

**Comment by Rushor** [comment]
drums of the wild can be used by players of at least level 70 and effect players of level 70 - 79 

saro explained me that. fixed it like that. tested with priestelar
