### ISSUE TITLE
[Leatherwork/ raid buffs] 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3796]
**Links:**

https://www.wowhead.com/item=29529/drums-of-battle
https://www.wowhead.com/spell=35478/drums-of-restoration
https://www.wowhead.com/item=29528/drums-of-war

**What is happening:**
- what we notice while testing something else is that if a player boosts their leatherworking then they can used these items no matter what lvl they are

(we tested on a lvl 10 toon) 

**what should happen**
_these should only be able to be applied to 70 up not a level 10 - 20 toon_

**Comment by Rushor** [comment]
Will add conditions to it

**Comment by Saronitian** [comment]
what? no no no. those drums can be used at any level and the buff also effects all levels - up to level 80. the only ones that should not be able to get the buff are characters from level 81-85

the requirement of this item is not levelbut leatherworking skill (wich already has a requirement)

**Comment by Echinaceax** [comment]
i thought thats what you meant when we tested last night @Saronitian

**Comment by Rushor** [comment]
no, the condition to not target level 80 and higher is missing

**Comment by Rushor** [comment]
i'm tired

**Comment by Rushor** [comment]
alright the spells will no longer affect targets level 80 and 80 +

**Comment by Rushor** [comment]
![I](https://i.imgur.com/8XZiwgU.jpg)
![I](https://i.imgur.com/eOnGLiG.jpg)
