### ISSUE TITLE
Heroic Bastion of Twilight not giving ID ! 

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3797]
**Links:**

from WoWHead or our Armory

**What is happening:**

Currently Bastion of Twilight Heroic is not giving any Lockout so you can do it infinitly ! 

**What should happen:**

Heroic should give Lockout and should share Lockout with Normal

**Comment by Rushor** [comment]
alright fixed. all bosses in all ids give lockout on kill now.
