### ISSUE TITLE
[Fishing / Daily] Thunder Bluff - 29348 -The Race to Restock

### ISSUE THREAD

**Issue by karteil** [WoWManiaUK/Blackwing-Lair#3798]
**Links:**
https://www.wowhead.com/quest=29348/the-race-to-restock

**What is happening:**
After having fished something like 250 fish in Stonebull Lake, I didn't get any quest item 

**What should happen:**
Fishing in Stonebull Lake should give 2 Randy Smallfish (ID = 69964) and 2 Amorous Mud Snapper (ID = 69967)

**Comment by Rushor** [comment]
added with 40 percent fish chance
