### ISSUE TITLE
[Fishing / Daily] Dalaran - Jewel Of The Sewers

### ISSUE THREAD

**Issue by karteil** [WoWManiaUK/Blackwing-Lair#3799]
**Links:**
https://www.wowhead.com/quest=13832/jewel-of-the-sewers

**What is happening:**
Fishing in the Dalaran sewers doesn't give the Corroded Jewelry (ID = 45903). 

**What should happen:**
Fishing in the sewers should give the quest item (ID = 45903).

**Comment by Rushor** [comment]
added with 30 percent chance to the zone :)

**Comment by Echinaceax** [comment]
Still an issue 
reported from other tester 
fished 40mins no drop...

reopening this @Rushor :)

**Comment by Echinaceax** [comment]
adding to main report

**Comment by Echinaceax** [comment]
fixed and confirmed fixed in dev
