### ISSUE TITLE
[Fishing / Daily] Orgrimmar - A Golden Opportunity

### ISSUE THREAD

**Issue by karteil** [WoWManiaUK/Blackwing-Lair#3800]
**Links:**

https://www.wowhead.com/quest=26572/a-golden-opportunity

**What is happening:**
After obtaining Drowned Thunder Lizard Tail (ID = 58958), I clicked to a Golden Stonefish (ID = 43331) and used the object but I was instant killed. 

**What should happen:**
Using the Drowned Thunder Lizard Tail (ID = 58958) to a Golden Stonefish (ID = 43331) should just drop the quest item (ID = 58960)

**Comment by Echinaceax** [comment]
quest item reported here https://github.com/WoWManiaUK/Blackwing-Lair/issues/1765
