### ISSUE TITLE
[Fishing / Daily] Orgrimmar - A Staggering Effort

### ISSUE THREAD

**Issue by karteil** [WoWManiaUK/Blackwing-Lair#3801]
**Links:**
https://www.wowhead.com/quest=26557/a-staggering-effort

The quest require to get a Stag Eye (ID = 58949) from a Weakened Mosshoof Stag and use it to our fishing pole, go to Orgrimmar at the Valley of Wisdom and start to fish to get the Sardy Carp (ID = 58946)

**What is happening:**
After applying the Stag Eye to the fishing pole, it's impossible to get the quest item

**What should happen:**
After applying the Stag Eye it should be possible to get Sardy Carp

**Comment by Rushor** [comment]
fish added with 50 % chance
