### ISSUE TITLE
[BoT] Chogall - Conversion broken.

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3803]
**Links:**

from WoWHead or our Armory

**What is happening:**

Currently when a player gets the Conversion Debuff from Chogall he is not targetable and/or interruptable

**What should happen:**

Player should be set in enemy state and we shout be able to get him out

**Comment by Slydee23** [comment]
since xfaction btw

**Comment by Rushor** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/3746 yes
