### ISSUE TITLE
[Bastion of Twilight] Theralion and Valiona Heroic Difficulty

### ISSUE THREAD

**Issue by Batraneluu** [WoWManiaUK/Blackwing-Lair#3805]
**Links:**
from WoWHead or our Armory
https://wowwiki.fandom.com/wiki/Theralion_and_Valiona

**What is happening:**
Twilight Zone -> Not doing any damage at all

**What should happen:**
Twilight Zone -> On 10 man heroic should do 5000 damage every 2 seconds.

**Comment by Priestelar** [comment]
Batra what ability isn't doing damage?

**Comment by Batraneluu** [comment]
Twilight Zone read Dungeon jurnal for correct damage http://cata.cavernoftime.com/spell=86214

**Comment by Rushor** [comment]
Will assign this to you @Keader - hope you can help me :>

**Comment by Slydee23** [comment]
if this fix gets live the boss is not killable anymore cause 

https://github.com/WoWManiaUK/Blackwing-Lair/issues/3804
