### ISSUE TITLE
Ascendant Council Heroic P1 debuff

### ISSUE THREAD

**Issue by Lokir92** [WoWManiaUK/Blackwing-Lair#3806]
**Links:**

from WoWHead or our Armory

https://www.wowhead.com/spell=92075/gravity-core
https://www.wowhead.com/spell=92067/static-overload

**What is happening:**

Static overload and gravity Core are applied to one player each. Both are shown as permanent, however Gravity Core is removed, when the player runs past any other player (even if they are not debuffed by static overload).

**What should happen:**

Gravity Core and Static Overload are both supposed to be only removed, when the two affected players are within 5 yards of each other.

**Comment by Slydee23** [comment]
can confirm that

**Comment by Rushor** [comment]
Will assign this to you @Keader - hope you can help me :>

**Comment by Keader** [comment]
@Lokir92 

If i have gravity core, i need go run to other gravity core or other static overload?

**Comment by Lokir92** [comment]
Yeah, that's how it's supposed to work.
