### ISSUE TITLE
[Dungeon] Lost City of the Tol'vir Heroic - Siamat

### ISSUE THREAD

**Issue by Batraneluu** [WoWManiaUK/Blackwing-Lair#3807]
**Links:**
https://www.wowhead.com/lost-city-of-the-tolvir
https://www.wowhead.com/npc=44819/siamat
from WoWHead or our Armory
![WoWScrnShot_110319_195354](https://user-images.githubusercontent.com/53946478/68089800-26f91e80-fe75-11e9-868f-0d8f801bd787.jpg)

**What is happening:**
Pets are falling under map texture and cannot attack at all.
Tried to dismiss & call again , not working.
**What should happen:**
Pets should be able to walk and attack on the map texture.

**Comment by Rushor** [comment]
fix inc. related to the mmps

**Comment by Rushor** [comment]
![I](https://i.imgur.com/jVZbc59.jpg)

fixed.

**Comment by Echinaceax** [comment]
@Batraneluu please dont close your own reports after fixed labels have been added.
the own closes when he has added to the live server
