### ISSUE TITLE
[Spell / Shaman] Fire Nova 

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#3808]
**Links:**

[ Fire Nova ](https://www.wowhead.com/spell=1535/)

**What is happening:**

you can spawn the spell with no target.

**What should happen:**

you need to be able to use it only with fire shok dot on

**Comment by Slydee23** [comment]
cant proof you are wrong but it works like it should you can use it but it wont do any dmg cause it dont have any fireshocks to ignite on it

**Comment by Slydee23** [comment]
yeah but as far as i remember this is supposed to work like that i try to find some proof

**Comment by Keader** [comment]
Nice high priority label.
