### ISSUE TITLE
[Quest/Daily] Time for Slime - ID 29322 - Undercity

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#381]
Quest - https://www.wowhead.com/quest=29322/time-for-slime
Quest item - https://www.wowhead.com/item=69911/squirming-slime-mold

- squirming-slime-mold is not collectable
- Cant complete quest

![slime](https://user-images.githubusercontent.com/39439201/50720565-c449c180-10af-11e9-839b-da9f81a8eefa.jpg)

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/1Bj6iy7.jpg)
![I](https://i.imgur.com/SWfeVES.jpg)

**Comment by rzenne** [comment]
not working for me. I can't catch them

**Comment by Echinaceax** [comment]
thanks @rzenne for feedback , i will test myself on dev and then on live see if both are same 

this maybe a silly question @rzenne but ... are you clicking on them or are you trying to use fishing rod?

i use ctrl V to show the name plates its easier to see them, then just click until you see the loot icon


### Test update

On PTR (dev) working
 
https://gyazo.com/9e36b718a6d6cece62d92826d4b27d50

![10 dev](https://user-images.githubusercontent.com/39439201/87769636-39a65e80-c81e-11ea-8937-a396baa67e7c.jpg)

Test on live (working too)
https://gyazo.com/be6c784818503b31957842846a9a45fb

![10 live](https://user-images.githubusercontent.com/39439201/87770246-10d29900-c81f-11ea-8a3d-b83d28b8241b.jpg)

**Comment by rzenne** [comment]
Yup I was clicking on bubbles.  With Ctrl-V I can see them now. ty
