### ISSUE TITLE
[Dungeon] The Bastion of Twilight - Halfus Normal/Heroic 

### ISSUE THREAD

**Issue by Lokir92** [WoWManiaUK/Blackwing-Lair#3813]
**Links:**

from WoWHead or our Armory

https://www.wowhead.com/npc=44600/halfus-wyrmbreaker

**What is happening:**

As a guardian druid (can only confirm for that class/spec, dunno about others) your aoe melee attacks (e.g swipe or trash) dont hit the drakes (Stormrider, Timewarden etc) on Halfus Wyrmbreaker fight in BoT. Only the small whelplings are getting hit.
A footage from Reign:
 https://www.youtube.com/watch?v=VB7eOE2pBLM&list=PLRYxzHB6o5cjwsGzg1TVhXjuLw3d3AVqF&index=6&t=0s

It seems like their hitbox is far too large, so they are "out of range" for the mentioned attacks (even if they target you as the tank). This occurs in various other fights on mobs with a bigger hitbox too.

**What should happen:**

All enemys in melee range should be hit by aoe melee attacks.

**Comment by Rushor** [comment]
meleedistance can be changed i guess

**Comment by Keader** [comment]
I made a workaround, will work for instances creatures
