### ISSUE TITLE
Soul Leech [Warlock Talent]

### ISSUE THREAD

**Issue by Javalapa** [WoWManiaUK/Blackwing-Lair#3817]
**What is happening:**

Shadow Burn, Chaos Bolt, and Soul Fire are healing 4% total health and applying the Replenishment buff.

**What should happen:**

These 3 spells should also restore 4% mana along with the health and applying the Replenishment buff

**Comment by mfranca0009** [comment]
All set, should restore mana properly for rank 1 and 2 Soul Leech talent. 👍

**Comment by golosomie** [comment]
@mfranca0009 Confirmed fixed on PTR. Both ranks work as expected.
