### ISSUE TITLE
Aimed Shot/Auto Attack Interaction

### ISSUE THREAD

**Issue by Javalapa** [WoWManiaUK/Blackwing-Lair#3818]
**What is happening:**

When starting off combat with a pre-casted Aimed Shot, it causes you to be unable to Auto Shoot your bow/gun on your target unless you manually fix it, either with Feign Death, right clicking another enemy, etc. 

**What should happen:**

Aimed Shot should not jeopardise your auto attacks when pre-casting it to initiate a pull 

Again this is ONLY when casting Aimed Shot to start a fight

**Comment by Echinaceax** [comment]
not sure what you mean 
Seems fine to me , Aim shot then my auto shot works fine 

video of your encounter woulds help 
closeing for now
