### ISSUE TITLE
Enduring Winter [Mage Talent

### ISSUE THREAD

**Issue by Javalapa** [WoWManiaUK/Blackwing-Lair#3819]
**What is happening:**

Replenishment is not being triggered from the effects of the talent

**What should happen:**

Frostbolt should give you and party/raid members a 33/66/100% chance to apply the Replenishment buff

**Comment by Echinaceax** [comment]
can you provide some links ?

**Comment by Keader** [comment]
fixed

**Comment by golosomie** [comment]
@Keader couldn't get this to work. are you sure this is on PTR?

**Comment by Keader** [comment]
yes, i tested my self, idk if janitor reverted it
