### ISSUE TITLE
[Item] A message in a bottle - [Fishing]

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3821]
https://www.wowhead.com/item=6307/message-in-a-bottle#contains

Opening this item will often contain NOTHING ,_, im looking for a message from my dream man, this is not fair

Item should contain scrolls or a recipe as well as a diary note entry.

**Comment by Rushor** [comment]
Items added :)

**Comment by Priestelar** [comment]
rushor you are precious! x)
