### ISSUE TITLE
[Item #47499] Flask of the North

### ISSUE THREAD

**Issue by Lurc1981** [WoWManiaUK/Blackwing-Lair#3823]
**Links:**

https://www.wow-mania.com/armory/?item=47499
(This is a link to wow-mania's armory because there is no longer an available link to this item on wow-head.)

**What is happening:**

This item only ever adds 40 Strength no matter what spec, gear or highest attribute is.

**What should happen:**

When applied it is supposed to add 40 Strength, Intellect or Agility based on the characters highest of these three attributes. 

![Before Flask](https://user-images.githubusercontent.com/54812659/68246279-14e6bf80-ffde-11e9-9726-7dd6e23dce58.jpg)

![Flask Applied](https://user-images.githubusercontent.com/54812659/68246293-1b753700-ffde-11e9-8621-697bfc0902f3.jpg)

**Comment by Lurc1981** [comment]
![Flask Tooltip](https://user-images.githubusercontent.com/54812659/68246392-4cee0280-ffde-11e9-826b-26a4fe51dfa8.jpg)

**Comment by Rushor** [comment]
it used old mechanic for calculation

**Comment by Rushor** [comment]
fixed with next update https://i.imgur.com/Pc1nmKN.jpg https://i.imgur.com/zlcriN7.jpg
