### ISSUE TITLE
[Hunter/Spell] Aspect of the Hawk -(Detterence turning off aspect)

### ISSUE THREAD

**Issue by Batraneluu** [WoWManiaUK/Blackwing-Lair#3826]
**Links:**

from WoWHead or our Armory
http://cata.cavernoftime.com/spell=13165
**What is happening:**
Sometimes when you start combat the Aspect turns off and you need to activate it again.
**What should happen:**
Aspect shouldn't turn off by itself.

**Comment by Slydee23** [comment]
never happend to me but what i can say is that Deterrence - 19263 is removing your Aspect what it should not

**Comment by Batraneluu** [comment]
Yea was detterence that kept turning off  the Aspect of the Hawk.
Thank you @Slydee23
