### ISSUE TITLE
[Quest] - Saving the Young

### ISSUE THREAD

**Issue by Batraneluu** [WoWManiaUK/Blackwing-Lair#3828]
- What should happen:
You should use the whistle so nearby Lost Bloodtalon Raptors follow you.

- What's happening:
Nothing happens when you use the whistle.

Link to the quest:
http://www.wowhead.com/quest=24623/saving-the-young

**Comment by Echinaceax** [comment]
im guessing you figured it out like i did :)
https://github.com/WoWManiaUK/Blackwing-Lair/issues?utf8=%E2%9C%93&q=Saving+the+Young
