### ISSUE TITLE
[Item] Sealed Crate - [Fishing]

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3829]
https://www.wowhead.com/item=78930/sealed-crate#contains

Fished up in the darkmoon faire, often when you open the crate there will be NOTHING inside. Myself, echi and angel had a good go at it and you could sometimes even get 2 or 3 empty crates in a row

**Comment by Rushor** [comment]
ref table is missing here i guess

**Comment by Rushor** [comment]
now always contains 3-4 random group itemlists https://i.imgur.com/PBSARWf.jpg
