### ISSUE TITLE
[Quest] Araj the Summoner - Alliance - missing prerequisite - Western Plaguelands

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#383]
https://www.wowhead.com/quest=27164/araj-the-summoner for alliance
Should be unlocked by handing in
https://www.wowhead.com/quest=27161/the-endless-flow

Currently available without prerequisite for alliance.
Works fine on horde side.

**Comment by Echinaceax** [comment]
This is the series of the reports with horde having ally quest line 

**Series**

**The Endless Flow**
Scholomancer
**Brute Strength**
**Araj the Summoner**
Victory, For Now
Go Fletch!

these should be all referenced with each other IMO

**Comment by Dranah** [comment]
Wrong. The same chain exists for both alliance and horde, just with different quest givers and IDs.
