### ISSUE TITLE
[Spell] Soulburn consumes charge after spell hits, not after spell cast.

### ISSUE THREAD

**Issue by Hartwall** [WoWManiaUK/Blackwing-Lair#3830]
**What is happening:**

Casting soulburn when a projectile that can be affected soulburn can result in soulburn being consumed by the said spell.
Mainly annoying when casting soulfire then using soulburn to throw another soulfire instantly. Instead of the new soulfire being an instant, the first soulfire that was in the air consumes the charge.

**What should happen:**

Soulburn should affect the next spell cast, not the next spell to hit.

**How to replicate:**

Cast soulfire, then cast soulburn while the soulfire projectile is still in the air.

**Comment by Nacho-k** [comment]
Can be abused to empower multiple spells with only 1 soulburn. ie: you can use 2 instant soul fires

**Comment by Nacho-k** [comment]
Soulburn is still being consumed by soulfires casted before activating soulburn
