### ISSUE TITLE
Fathom Eel Swarm missing in Uldum

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3831]
**Links:**
https://www.wowhead.com/object=202780/fathom-eel-swarm

from WoWHead or our Armory

**What is happening:**

Currently all spawnpoints of them are missing in Uldum. The one in Twilighthighlands are there.

Checked on Dev aswell.

**What should happen:**

**Comment by Rushor** [comment]
will add some spawns for uldum

**Comment by Slydee23** [comment]
added them you just need to adjust Respawn Time

**Comment by Rushor** [comment]
okay all added. i will make it like that, that always 9 spawns are active at the same time (pooling)

**Comment by Rushor** [comment]
pooling added aswell. thank you very much!
