### ISSUE TITLE
[Jewel Crafting] Daily

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3832]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=25155/ogrezonians-in-the-mood

**What is happening:**
When you do the daily you dont get the quest complete since it wont make the cut that is needed for quest complete.
https://imgur.com/a/C9xzoVU
https://imgur.com/a/5ARNQUV

**What should happen:**

You should get the cut version aswell when you are creating the item. 

This quest worked before the update on server a few days ago.

**Comment by Jimpaa** [comment]
Same with the quest https://www.wowhead.com/quest=25154/a-present-for-lila

https://imgur.com/a/V1UwgWm

**Comment by Echinaceax** [comment]
Needs seperate report @Jimpaa please :)
