### ISSUE TITLE
[Jewel Crafting] Daily - The Latest Fashion!

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3833]
**Links:**

https://www.wowhead.com/quest=25157/the-latest-fashion

from WoWHead or our Armory

**What is happening:**
 
Using the item is currently not giving Quest progress.

The quest worked before the update a few days ago.

**What should happen:**

U should get Quest progress after using the item on any other Npc/Player

**Comment by Rushor** [comment]
all fixed together with https://github.com/WoWManiaUK/Blackwing-Lair/issues/3832. sorry for that
