### ISSUE TITLE
Cloak of Shadows doesn't seem to prevent fire damage

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3834]
spell ID: 31224 

**What is happening:**

I'm taking and dying to fire damage while cloak of shadows is on.

**What should happen:**

I shouldn't be taking fire damage with cloak of shadows on.

**Comment by Keader** [comment]
Cant reproduce.
Any specific spell?
Tested with shaman lava burst, and working fine.

**Comment by questbugreporter** [comment]
@Keader https://www.wowhead.com/spell=75238/supernova
https://www.wowhead.com/spell=76355/blessing-of-the-sun
Also today got hit by a frostbolt, either from a mage or from her water elemental.
