### ISSUE TITLE
[Quest / The Storm Peaks] The Hero's Arms (Drop chance)

### ISSUE THREAD

**Issue by Batraneluu** [WoWManiaUK/Blackwing-Lair#3835]
**Links:**

from WoWHead or our Armory
http://cata.cavernoftime.com/quest=13049
**What is happening:**

The items never drop from the adds, killed like 50 of them.

**What should happen:**

https://www.youtube.com/watch?v=4ztUvZDXPFM

EDIT: Finally completed the quest but you need to kill over 100 to get the items , if you can increase the drop chance at least would be appreciated.

**Comment by Echinaceax** [comment]
they are really low drop rate 7.92%
https://www.wowhead.com/item=42782/stormhoofs-spear
https://www.wowhead.com/item=42783/stormhoofs-mail

ofc @rushor will check it for you @Batraneluu

**Comment by Rushor** [comment]
according to https://www.wowhead.com/quest=13049/the-heros-arms#videos:id=74639 i will change it to 40 percent
