### ISSUE TITLE
[Quest/The Storm Peaks] Emergency Measures ( Drop chance )

### ISSUE THREAD

**Issue by Batraneluu** [WoWManiaUK/Blackwing-Lair#3836]
**Links:**

from WoWHead or our Armory
http://cata.cavernoftime.com/quest=13000
**What is happening:**
Drop chance is very low.

**What should happen:**

Increase drop chance for item quest drop.

**Comment by Echinaceax** [comment]
23.27% https://www.wowhead.com/item=42510/worg-fur

@Rushor will check ofc

**Comment by Rushor** [comment]
chance is shown wrong. It is calculated by the guys who killed the creature while not beeing on quest.

according to https://www.wowhead.com/quest=13000/emergency-measures#videos:id=74605 changed to 50 percent.
