### ISSUE TITLE
[Jewel Crafting] A Present for Lila

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3837]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=25154/a-present-for-lila

**What is happening:**
You are not getting the cut part of the daily.
https://imgur.com/a/V1UwgWm

**What should happen:**

You should get the cut aswell as the item when you are doing the daily

**Comment by Rushor** [comment]
Already reported yesterday. It's all fixed next update agaon
