### ISSUE TITLE
[Dungeon] Stonecore Flayer - Heroic Stonecore

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3838]
**Links:**
https://www.wowhead.com/the-stonecore
from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/npc=42808/stonecore-flayer 
These adds are lvl 82 Elites on heroic but they should be 85.
So atm they are really easy to kill on heroic
https://imgur.com/a/1cxtzse

**What should happen:**

These adds should be 85 Elites

**Comment by Rushor** [comment]
level adjusted
