### ISSUE TITLE
[Quest/Daily] Like Pike? -29320- Tirisfal Glades

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#384]
Quest - https://www.wowhead.com/item=69909/corpse-fed-pike
Quest item - https://www.wowhead.com/item=69907/corpse-worm

**A few possible issues**

- Fished for 20 mins, no drop (5% drop/ fish rate)
- Lore of corpse worm (10mins) but the lore is still on after timer has gone.
- Is the lore still active even though timer left?
- Timer on lore is 1 hour not 10 mins.
- Not completable as you need the quest item to feed the fish to complete the quest 
**(5% drop) is very odd for a lvl1 fishing daily.**

**5% drop / fish rate**

![5](https://user-images.githubusercontent.com/39439201/50720914-e6930d80-10b6-11e9-956f-f13736eb4192.jpg)

**worm buff 10 mins**

![10mins](https://user-images.githubusercontent.com/39439201/50720880-f9f1a900-10b5-11e9-84a2-d227e267cfa2.jpg)

**Buff was on** 

![had worm buff](https://user-images.githubusercontent.com/39439201/50720884-17267780-10b6-11e9-99ae-b0a77fe96939.jpg)

**Lore still on even after worm buff ended,** also asked to replace the buff (that wasn't on) 

![lore still on when time has gone](https://user-images.githubusercontent.com/39439201/50720892-5228ab00-10b6-11e9-9762-834f83cf2bed.jpg)

**1 hour lore not 10 mins**

![timer is 1 hour not 10 mins](https://user-images.githubusercontent.com/39439201/50720957-98cad500-10b7-11e9-887d-5fb67e796b6c.jpg)

**Asked to replace** 

![asked](https://user-images.githubusercontent.com/39439201/50720902-9e73eb00-10b6-11e9-9b24-064e16a7357a.jpg)

**Comment by Rushor** [comment]
dropchance set to 6 percent for better fishing :)
