### ISSUE TITLE
[Dungeon] Black Morass (portals)

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3840]
https://wow.gamepedia.com/Opening_the_Dark_Portal
^ as stated in the section under walkthrough: Once a given portal has been shut or enough time has passed, a consecutive portal will be opened in a different zone. At the moment, this process does NOT happen and a second portal only opens after a lot of time passes... this makes running the place time consuming as hell. Took me and a friend almost 30 minutes to clear the place just because of waiting so long for portals to spawn

**Comment by Rushor** [comment]
yes the timer calculation is an issue here. same was on wotlk

**Comment by Rushor** [comment]
Scripts/TheBlackMorass: Update Timer for portalspawn

* after portal 7 there will be no longer a waittime of 120000 milliseconds
* only after portal 6 and 12 there will be a 120000 milliseconds waittimer because of the bossspawn (this is blizzlike)
