### ISSUE TITLE
[Item] Battle Standard of Coordination (not working)

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3842]
https://www.wowhead.com/item=64399/battle-standard-of-coordination#reward-from-a

Using this item should grant a buff that increases rep gain, exp gain and honor gain by 15% currently does not grant any buff

Could not confirm on dev due to rep requirement but confirmed it on live

![WoWScrnShot_110719_173336](https://user-images.githubusercontent.com/16594771/68403458-a47aa280-0185-11ea-8c0f-bf2470c14814.jpg)
You can see in the top right section i am not getting the buff

**Comment by Echinaceax** [comment]
i will confirm this when i can :)

**Comment by Rushor** [comment]
fixed  https://i.imgur.com/xxx4F14.jpg (all other Standards aswell)

**Comment by Priestelar** [comment]
@Rushor im not noticing a change in rep gain with the buff the standard gives,

![image](https://user-images.githubusercontent.com/16594771/68759930-56e4b680-0619-11ea-8374-37c6a0b8f88c.png)

I usually get 17 rep per mob anyways

**Comment by Priestelar** [comment]
Standard still doesn't grant any bonus in rep
