### ISSUE TITLE
[Quest] Deepholm, Part 1: Upper World Pillar Fragment 

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3843]
Quest order list for the zone must be followed as per this list: https://wow.gamepedia.com/Deepholm_quests
Only refering to first section in the quest list under the Upper World Pillar Fragment section.

1 - Quest – Deepholm Realm of Earth https://www.wowhead.com/quest=27123/deepholm-realm-of-earth aggra should give the player a ride from the maelstrom – Recommend either creating a portal to deepholm or to teleport the player to deepholm when they accept this quest, whichever is easier to script.
![WoWScrnShot_110619_133704](https://user-images.githubusercontent.com/16594771/68412476-f4149a80-0194-11ea-80ec-20ff58c6c660.jpg)

2 – Quest – Where’s goldmine? https://www.wowhead.com/quest=26409/wheres-goldmine quest should only be available after completing Upper world pillar fragment (see quest order list)
^ See number 16.

3 – Quest – Elemental energy https://www.wowhead.com/quest=27136/elemental-energy players need to place the quest item near the 2 mobs(ID: 43254 and 43258) and kill them for credit.
^ See #3041

4 – Quest – Captain’s log https://www.wowhead.com/quest=26246/captains-log#see-also object is currently not granting the quest.
![WoWScrnShot_110619_135611](https://user-images.githubusercontent.com/16594771/68412652-46ee5200-0195-11ea-9d99-c7a8176dabd4.jpg)

5 – Quest - Diplomacy first https://www.wowhead.com/quest=26247/diplomacy-first should only be available after completing all the previous quests (see quest order list).

**IMPORTANT NOTE:** lots of dev’s on private servers struggle to script the ship where the following quests take place on, if it is too difficult to script then I recommend making these quests auto complete upon accepting the quests so that they don’t take too much of your time up :) It is always something that can be changed later.

6 – Quest – All our friends are dead https://www.wowhead.com/quest=26248/all-our-friends-are-dead mobs(ID: 42681) spawned when using this quest item will fall through the ship.
![WoWScrnShot_110619_135936](https://user-images.githubusercontent.com/16594771/68412732-67b6a780-0195-11ea-8b5e-3ab6955c7bbe.jpg)
As you see in this screenshot, the mob will fall through the floor to the deck below.

7 – Quest ITEM – 58798 https://www.wowhead.com/item=58798/bottle-of-whiskey#contained-in-object should be down below the deck. Currently on ship on the one life boat, but should also appear below deck.

8 – Quest – Some spraining to do https://www.wowhead.com/quest=26254/some-spraining-to-do quest requires a lot of scripting for a cutscene, recommend making this quest auto hand in to save time.
^See #2625

9 – Quest – Question the slaves https://www.wowhead.com/quest=26261/question-the-slaves using the quest item(ID 60739) on the chains by the slaves should grant quest credit. The messages the npcs say after being freed can be added later in the touch up report.
^ See #3154

10 – Quest – Quicksilver submersion https://www.wowhead.com/quest=27010/quicksilver-submersion players must optain quest item(ID 60809) and use the item to view a cutscene. Recommend using the quest item to grant quest credit.
^ See #3156

11 – Npc/item/quest – Npc 44936 should drop quest item (ID 60809) 100% of the time to help ensure players don’t miss the quest chain associated to it, this will be needed if quest mentioned in number 10 of the report is made auto hand in on quest item use.

12 – Quest/Item – Twilight research https://www.wowhead.com/quest=27100/twilight-research quest item(ID 60816) should be 100% drop rate from npc 43158. 

13 – Quest – Big game, Big bait https://www.wowhead.com/quest=26766/big-game-big-bait quest item does not work when used on dead crocolisks(ID 43981) thus quest cannot be done.
^ See #1990

14 – Quest/Item – Block the gates! https://www.wowhead.com/quest=26861/block-the-gates quest item(ID 60501) can be used anywhere and using it near the gate does not grant quest credit.

15 – Quest/Item – The world pillar fragment https://www.wowhead.com/quest=26876/the-world-pillar-fragment using quest item(ID 60810) does not do anything so the quest cannot be completed.
^ See #3123

16 – Once the quest mentioned in number 15 has been completed, the quest(ID 26409) as mentioned in number 2 should become available.

This concludes the first quest chain in Deepholm, if you have any questions or need any help please ask :)

**Comment by Kitzunu** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/3122

**Comment by Echinaceax** [comment]
he knows @Kitzunu he is redoing it coz rushor asked

**Comment by Rushor** [comment]
very first stuff done https://gyazo.com/ba8f213cffc5db6b361e8fb4f96d1a61 https://i.imgur.com/CVHNBsL.jpg https://i.imgur.com/wEe9VIA.jpg

**Comment by Rushor** [comment]
gates fixed https://i.imgur.com/dIzg7KL.jpg https://i.imgur.com/IMjxnU3.jpg

**Comment by Rushor** [comment]
all fixed here. will make a complete check tomorrow morning again with fresh char.

**Comment by Rushor** [comment]
what needs fixing:
- goldmine quest condition again
- randommov boat npcs
- feldspar wp

**Comment by Rushor** [comment]
i could easily finsih all quests https://i.imgur.com/MJPpLbX.jpg

all remaining issues resolved.
