### ISSUE TITLE
[NPC] Bleeding Hollow Riding Worg - Hellfire

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#3844]
**Links:**
[Bleeding Hollow Riding Worg](https://www.wowhead.com/npc=19640/bleeding-hollow-riding-worg) - ID 19640

**What is happening:**

- Dont drop agro on you !

- Follow you everywhere

**What should happen:**

- Drop Agro
- Reset position.

**Comment by Rushor** [comment]
ai and so eveading and reset added
