### ISSUE TITLE
Unholy Frenzy - 49016 stacks with Heroism etc. 

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3845]
**Links:**
http://www.cavernoftime.com/spell=49016

from WoWHead or our Armory

**What is happening:**

currently stacks with Heroism and other simliar buffs

**What should happen:**

should not stack
![Screenshot_1](https://user-images.githubusercontent.com/55513205/68423341-35f80d80-01a2-11ea-9dd6-b59b4505c598.jpg)

**Comment by Kitzunu** [comment]
```sql
SET @group_id := XXX -- use lowest available entry higher than 1000

DELETE FROM `spell_group` WHERE spell_id IN (49016, 32182, 2825, 80353)
INSERT INTO `spell_group` (`id`, `spell_id`) VALUES
(@group_id, 49016), -- Unholy Frenzy
(@group_id, 32182), -- Heroism
(@group_id, 2825), -- Bloodlust
(@group_id, 80353); -- Timewarp

DELETE FROM `spell_group_stack_rules` WHERE `group_id` = @group_id;
INSERT INTO `spell_group_stack_rules` (`group_id`, `stack_rule`) VALUES
(@group_id, 1); -- Auras from group can't stack with each other

**Comment by Keader** [comment]
Already has a group with those Spells Kitzunu
And in that group, rule was wrong.
anyway, fixed.
