### ISSUE TITLE
[NPC] Sea pony 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3847]
**Links:**
https://www.wowhead.com/item=73953/sea-pony#contained-in-object
https://www.wowhead.com/item=73953/sea-pony#comments

**What is happening:**
- [x] Pet drop chance is far to often 
- [x] Sea pony is meant to have a cute water bubble (missing)

**Comment by Rushor** [comment]
pet drop chance is 0.01 in the object :O

**Comment by Rushor** [comment]
ah now i see. the chance in fishing_loot_template was way too high. changed to 0.01 aswell now.

**Comment by Rushor** [comment]
ols bubble should look likse this https://www.wowhead.com/item=73953/sea-pony#screenshots:id=306183 (cata version)

**Comment by Rushor** [comment]
bubble time added lol https://i.imgur.com/GyeaA8Z.png

**Comment by Echinaceax** [comment]
Much better ❤️ 

![love it](https://user-images.githubusercontent.com/39439201/68480001-fd087900-0233-11ea-95a8-c6a3f0486e22.jpg)

**Comment by Priestelar** [comment]
:OOO omg it looks amazing! well done rushor! ❤️
