### ISSUE TITLE
Missing Cogwheels at Engineering & Supplies Vendor

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3848]
**Links:**
https://cata-twinhead.twinstar.cz/?item=59489
https://cata-twinhead.twinstar.cz/?item=59493

from WoWHead or our Armory

**What is happening:**

Currently all 6 Vendors seems to miss the 2 Cogwheels 

**What should happen:**

6 different Vendors Should sell all Cogwheels

**Comment by Rushor** [comment]
just for info for others: you need empty bags as payment in order to see it
