### ISSUE TITLE
Flame-Scarred Junkbox is always EMPTY

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3849]
https://www.wowhead.com/item=63349/flame-scarred-junkbox
These are even supposed to drop epic weapons.

**Comment by Rushor** [comment]
should always contain sth now.

**Comment by questbugreporter** [comment]
@Rushor Does this mean that the epics will become available on the next update?

**Comment by sarahkay88** [comment]
@questbugreporter  https://www.wowhead.com/item=63349/flame-scarred-junkbox#contains - items that should be found in the one you linked

**Comment by questbugreporter** [comment]
Those aren't all the items that are supposed to be contained in it.

**Comment by sarahkay88** [comment]
Ummm kay that's what the link says

**Comment by questbugreporter** [comment]
Wowhead either has wrong info because they only have 102866 samples or because the loot has changed in the last 9 years, which doesn't seem unreasonable since they've removed thrown weapons.
Either way those boxes had a low chance of containing these ilvl 359 epics:
Krol Decapitator / 68161
Spinerender / 68162
The Twilight Blade / 68163

**Comment by Nacho-k** [comment]
https://cata-twinhead.twinstar.cz/?item=63349

**Comment by sarahkay88** [comment]
https://www.wowhead.com/item=68163/the-twilight-blade#comments 

  | By Vager (460 –  9·4)  on 2010/12/29 (Patch 4.0.3)I successfully looted this from a Flame-Scarred Junkbox which I pick pocketed off a mob. 

if u link all missing items n tag rushor im sure he will add them :)

**Comment by Rushor** [comment]
yes gimme all ids and contact me on discord again. then i will add

**Comment by questbugreporter** [comment]
Alright I did some research, so here's what I think they used to contain:

6 to 16 silver (always)

| ID  | Name | Chance |
| ------------- | ------------- | ------------- |
| 63300 | Rogue's Draught | 16%
| 68047 | Scavenged Dragon Horn | 1.5%
| 67348 | Bleached Jawbone | 1.5% 
| 62323 | Deathwing Scale Fragment | 1.5% 
| 67319 | Preserved Ogre Eye | 1.5% 
| 67335 | Silver Charm Bracelet | 1.5% 
| 52190 | Inferno Ruby | 0.1%
| 52191 | Ocean Sapphire | 0.1% 
| 52192 | Dream Emerald | 0.1%
| 52193 | Ember Topaz | 0.1%
| 52194 | Demonseye | 0.1%
| 52195 | Amberjewel | 0.1%
| 68161 | Krol Decapitator | 0.05% 
| 68162 | Spinerender | 0.05% 
| 68163 | The Twilight Blade | 0.05%

**Comment by Rushor** [comment]
money and those items also added https://i.imgur.com/rGq6g1A.jpg

**Comment by questbugreporter** [comment]
Flame-Scarred Junkboxes now contain items WAY too often, the only guaranteed result is supposed to be the gold. I opened 115 boxes and got all this stuff: 
![image](https://user-images.githubusercontent.com/56992013/68759109-c2c61f80-0617-11ea-98f9-854c99e76b3e.png)

**Comment by Echinaceax** [comment]
i looked on the loot table and there are no gems meant to be in them according to wowhead 
https://www.wowhead.com/item=63349/flame-scarred-junkbox#contains patch 4.0.1 

and if you look at this link https://cata-twinhead.twinstar.cz/?item=63349 at the 0% it means those item are not meant to be in them @Rushor

**Comment by Rushor** [comment]
will change that!

**Comment by Rushor** [comment]
chance decreased to 1 % that it contains such epic items. but still the money drop is 100%

**Comment by Echinaceax** [comment]
@Rushor 
out of 8 boxes i only got silver nothing else 

as we are using cavernoftime as amory here we need it setting again 
http://cata.cavernoftime.com/item=63349#contains

![8 boxes](https://user-images.githubusercontent.com/39439201/74052996-3ee3bf80-49db-11ea-9d9b-63d5f025cfb7.jpg)
