### ISSUE TITLE
[NPC] Durnt Brightfalcon - Western Plaguelands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#385]
NPC https://www.wowhead.com/npc=45012/durnt-brightfalcon

- For Ally Quest 
- But Horde can see the yellow **(!)** but cant take the quest.
- Just needs a tweak

![ally yellow thing](https://user-images.githubusercontent.com/39439201/50722390-ae97c480-10ce-11e9-908d-e3634c305700.jpg)

**Comment by mfranca0009** [comment]
Needs testing on PTR

**Comment by Echinaceax** [comment]
confirmed fixed 

![fixed4](https://user-images.githubusercontent.com/39439201/85942618-a8cd1900-b92a-11ea-8007-45f4208f683f.jpg)
