### ISSUE TITLE
Most cataclysm pick pocket-able NPCs are missing a pick pocket loot table

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3850]
Only exceptions I've found so far are tol barad and tol barad peninsula NPCs.

**Comment by Rushor** [comment]
i need more help for this report. you need to post EVERY creature id where loot is missing. and then i would suggest to open one ticket for each zone. so i get a better overview. thanks.

**Comment by questbugreporter** [comment]
I'm about 99% certain that all humanoids in deepholm, hyjal, vashj'i, uldum and twilight highlands have no loot tables for pick pocketing.
Getting the ID of every single one seems impossible to me.
I would suggest fixing this one so that lockboxes can be farmed reasonably well, like in the original game: Stone Trogg Digger - 43174

**Comment by Rushor** [comment]
> Getting the ID of every single one seems impossible to me.

why should it then be possible for me? this is huge work and i need help for it. I exactly need to know the items they should contain and the chances. My fixes does not come from nowwhere lol.
