### ISSUE TITLE
[GO] Shipwreck Debris - Pooling on Darkmoon Isle

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Blackwing-Lair#3851]
http://cata.cavernoftime.com/object=210216

Need more spawnpoints and pooling. Thanks to Slydee <3

**Comment by Rushor** [comment]
okay done - there are now 26 spawns in total and 10 spawns active at the same time (pooling)

**Comment by Priestelar** [comment]
incredible! gj rushor! :)

**Comment by Rushor** [comment]
ty :>
