### ISSUE TITLE
[Quest][Npc] Archmage Alturus quest giver bug 

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3852]
https://www.wowhead.com/npc=17613/archmage-alturus

Quest giver(ID 17613) does not allow players to take both quests when first talking to him, this is a bug happening with some npcs where if they have 2 quests available and 1 quest is taken the other one becomes unavailable and is skipped.
![WoWScrnShot_110819_163459](https://user-images.githubusercontent.com/16594771/68486689-482d8680-024a-11ea-9314-b8be257ec92f.jpg)
![WoWScrnShot_110819_163503](https://user-images.githubusercontent.com/16594771/68486692-495eb380-024a-11ea-91bf-921772767140.jpg)

Both quests should be available

**Comment by Kitzunu** [comment]
```sql
UPDATE `quest_template_addon` SET `ExclusiveGroup` = 0 WHERE `id` IN (9824, 9825);

**Comment by Rushor** [comment]
ty for your help!
