### ISSUE TITLE
[Quest][Npc] Trade Baron Silversnap quest giver bug

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3853]
https://wow.gamepedia.com/Trade_Baron_Silversnap

Quest giver(ID 45786) does not allow players to take both quests when first talking to him, this is a bug happening with some npcs where if they have 2 quests available and 1 quest is taken the other one becomes unavailable and is skipped.

![WoWScrnShot_110819_171137](https://user-images.githubusercontent.com/16594771/68487199-57610400-024b-11ea-8263-017f31de4333.jpg)
![WoWScrnShot_110819_171141](https://user-images.githubusercontent.com/16594771/68487201-57f99a80-024b-11ea-9fa4-71b584a85f94.jpg)

Both quests should be available from the npc

**Comment by Kitzunu** [comment]
```sql
UPDATE `quest_template_addon` SET `Exclusivegroup` = 0 WHERE `id` IN (27536, 27656);

**Comment by Rushor** [comment]
thx for you help!
