### ISSUE TITLE
[Quest][Npc] Crazy Larry quest giver bug

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3854]
https://www.wowhead.com/quest=27597/crazy-larry

Quest giver(ID 27597) does not allow players to take both quests when first talking to him, this is a bug happening with some npcs where if they have 2 quests available and 1 quest is taken the other one becomes unavailable and is skipped.

![WoWScrnShot_110819_171933](https://user-images.githubusercontent.com/16594771/68487730-45339580-024c-11ea-9b84-4fa803535d39.jpg)

![WoWScrnShot_110819_171929](https://user-images.githubusercontent.com/16594771/68487726-449aff00-024c-11ea-9b9e-6b75b29d92e8.jpg)

Both quests should be available from the npc

**Comment by Kitzunu** [comment]
easy fix
```sql
UPDATE `quest_template_addon` SET `ExclusiveGroup` = 1 WHERE `id` IN (27598, 27599);

**Comment by Rushor** [comment]
thx for the help @Kitzunu 

@Priestelar if you encounter same issue somewhere else you can use the fix from @Kitzunu and give me in discord or post here aswell. Thanks all for the contribution!

**Comment by Kitzunu** [comment]
Just have to make sure the quest order says you should be allowed to complete both, sometimes its Quest A or Quest B

But in this case, and many others it is Quest A and Quest B :p
