### ISSUE TITLE
[NPC Spell] Worgen Taint strange interaction with Worgen Race

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3855]
**Links:**

Spell :
https://www.wowhead.com/spell=85244/worgen-taint
Npc : 
https://www.wowhead.com/npc=920/nightbane-tainted-one

**What is happening:**

if you get the debuff as female worgen and wait till it ends your model gets changed back but the gender model seems to be fucked.

https://imgur.com/X7hcAxE

**What should happen:**

**Comment by Rushor** [comment]
hm relation with https://github.com/WoWManiaUK/Blackwing-Lair/issues/3021 maybe @Keader ?

**Comment by Slydee23** [comment]
deleting cache fixxed the problem i mentioned but still im not sure if its a server problem

**Comment by Rushor** [comment]
does it happen again. can you retry?

**Comment by Keader** [comment]
yes, @Rushor , they are related

**Comment by Echinaceax** [comment]
will add to one report
