### ISSUE TITLE
[Quest] Into the Soulgrinder - Blade Edge mountain (undoable)

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3856]
https://www.wowhead.com/quest=11000/into-the-soulgrinder

https://www.wowhead.com/npc=22910/skulloc-soulgrinder#drops

After using the quest item, the npc will eventually spawn after his ritual completes, however he is flagged as untargetable and unkillable by the players. Needs to be killed to collect quest item(ID 32383)

**Comment by Rushor** [comment]
they are attackable now https://i.imgur.com/jTPtNH2.jpg https://i.imgur.com/7ujutTe.jpg
