### ISSUE TITLE
[Core][Object] Blackrock Cavern - Portal not working

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3857]
![WoWScrnShot_110819_200820](https://user-images.githubusercontent.com/16594771/68500756-22fa4180-0265-11ea-8665-3b12b50aa773.jpg)
These portals in the dungeon do not work, and make wiping cause the group to take SUPER long to get back to the boss that the group was at.

Edit: could not find information link on the portals for more information about them online

**Comment by Rushor** [comment]
can you do command:

.gobj near

close to the objects and list the results here?

**Comment by Priestelar** [comment]
225986 (Entry: 207331) - [Finkle's Helm X:237.445999 Y:1121.579956 Z:205.796997 MapId:645]  
^ This was what i got by the portal left from the dungeon entrance

The second portal doesnt show any results, just states: Found nearby gameobjects (distance 10.000000): 0

Not sure if the Finkle's Helm is the portal because FH is usually what enables the players to receive the quests throughout the dungeon without having to speak with the quest giver each time.

Should work like the Stonecore dungeon teleporter

**Comment by Rushor** [comment]
fixed this :)

you now get ported to the last boss you killed in orther to speedthings up

![I](https://i.imgur.com/f9llI39.jpg)
![I](https://i.imgur.com/pTb07KI.jpg)
![I](https://i.imgur.com/l9rH7YF.jpg)

**Comment by Rushor** [comment]
works for all other bosses aswell.

**Comment by Priestelar** [comment]
omg perfect!!!!!!! ty so much rushor this will be awesome! ❤️
