### ISSUE TITLE
[NPC] Krixel Pinchwhistle

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#3858]
**Links:**

[Krixel Pinchwhistle](https://www.wowhead.com/npc=23396/krixel-pinchwhistle#sells)

**What is happening:**

Give you wrong items

**What should happen:**

Need to give you lvl 60 pvp gear.

**Comment by Echinaceax** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/2463

**Comment by Xman993** [comment]
he is there but gives you wrog items @Echinaceax

**Comment by Rushor** [comment]
hmm
which price should the items have?

**Comment by Xman993** [comment]
@Rushor  lvl 60 pvp gear "Replica Knight"

**Comment by Rushor** [comment]
i see

https://www.wowhead.com/npc=23396/krixel-pinchwhistle#sells:50-2

can you pls LIST me ALL ids of the items AND the price they should have? so what they should cost like 200 honor points or sth

**Comment by Rushor** [comment]
hm with the fix i cannot even interact with him. can you try it? fix is in dev..
