### ISSUE TITLE
[Npc][Cata] Battered red drake not working - 

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3859]
These drakes do not work at the moment, theres a low chance of them actually doing the right thing. These drakes fly through the dungeon and you can spam their ability to damage the trash throughout the dungeon making it a lot easier, taking the dragon is a deathsentence at the moment, since you will start flying out of the dungeon and then you will eventually need to close the game in order to get off the dragon and then you will be ported to westfal or the barrens.

https://www.wowhead.com/npc=39294/battered-red-drake#abilities
![WoWScrnShot_110819_204106](https://user-images.githubusercontent.com/16594771/68502437-0eb84380-0269-11ea-9c2b-3f8d4e3b79be.jpg)
![WoWScrnShot_110819_204517](https://user-images.githubusercontent.com/16594771/68502439-11b33400-0269-11ea-8d11-7c8c2ba8bfc5.jpg)
![WoWScrnShot_110819_204552](https://user-images.githubusercontent.com/16594771/68502441-124bca80-0269-11ea-9798-d797e09eddcc.jpg)

**Comment by Rushor** [comment]
back in the days i added a fix for that - but it got reverted. will refix it now.

**Comment by Rushor** [comment]
fix readded https://i.imgur.com/RBt94PL.jpg

**Comment by Priestelar** [comment]
perfect! ty rush, yeah i recall them working before

**Comment by Rushor** [comment]
it now uses pathing again  - and not hardcoded point movement like before. :>

**Comment by Priestelar** [comment]
haha as long as I dont end up in an unkown zone again its much better than currently :P
