### ISSUE TITLE
Elementium Lockboxes missing gold loot

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3860]
https://www.wowhead.com/item=68729/elementium-lockbox

These lockboxes are supposed  to always contain 25-35 gold.
In addition, they're supposed to have a chance (can't find a number) to contain another Elementium Lockbox. Proof video from 2011: 
https://www.youtube.com/watch?v=DRvntvbgHf0
This might already be happening on reign, but it hasn't happened to me or my rogue guild member.

**Comment by Rushor** [comment]
fixed https://i.imgur.com/Ciskf00.jpg
