### ISSUE TITLE
[Npc][Boss] Amanitar abilities cause fps lag into pc crash - Wotlk dungeon

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3862]
https://www.wowhead.com/npc=30258/amanitar#abilities

I think its his poison bolt volley spams green textures on the floor and he does this continuesly and it will make a player's fps continue to drop untill you get around 0 frames per second and crash your pc if the boss doesn't kill you.

Npc ID: 30258
![WoWScrnShot_110919_175402](https://user-images.githubusercontent.com/16594771/68531559-3c11f980-031c-11ea-8713-725247e95d6e.jpg)

I took this screenshot but this was when I no longer got any frames

**Comment by Rushor** [comment]
Will quick fix that :)

**Comment by Rushor** [comment]
imer adjusted for him - check it out :)
