### ISSUE TITLE
[Quest]The Exorcism of Colonel Jules - Hellfire

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#3864]
**Links:**

[The Exorcism of Colonel Jules ](https://www.wowhead.com/quest=10935/the-exorcism-of-colonel-jules)

**What is happening:**

spawn to many [Darkness Released](https://www.wowhead.com/npc=22507/darkness-released)

**What should happen:**

need to spawn less and to fly around, attacking the player with the beam not with auto.

**Comment by Rushor** [comment]
https://i.imgur.com/7uAyfAH.jpg

less spawns now!
