### ISSUE TITLE
[Raid/Bastion of Twilight] Valiona & Theralion 10 man heroic

### ISSUE THREAD

**Issue by Batraneluu** [WoWManiaUK/Blackwing-Lair#3865]
**Links:**

from WoWHead or our Armory
https://wowwiki.fandom.com/wiki/Theralion_and_Valiona
**What is happening:**
The bosses don't share their health.

**What should happen:**

The bosses should share their health.
![WoWScrnShot_110919_202324](https://user-images.githubusercontent.com/53946478/68533294-69b46e00-032f-11ea-8102-517b8704dfa6.jpg)

**Comment by Slydee23** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/55513205/68544958-bef08e00-03c8-11ea-8eb2-16065115da26.jpg)


they do

**Comment by Batraneluu** [comment]
There is a problem with tanking them even at the start of the encounter first 5 seconds boss is EVADING, also when dazzling destruction pops up and u move the boss has a chance to EVADE and will make the boss health regenerate about 25% or more.
Also if tank goes to other realm and no one is taking the boss EVADE pops again and as you see in my screenshot , one of them goes to 50 - 75 % and one remains to its current health.

**Comment by Keader** [comment]
I need a reproduce case.
I cant reproduce it.

**Comment by Batraneluu** [comment]
Reproduce = start fight , go with valiona or theralion near a wall and you will see one of them start EVADING and regain health.
Or second option, start fight tanking the boss , then you go to the other realm, then boss will EVADE and regain health.
Hint: only one of those 2 bosses will regain health after evading and when you kill one of them the other one should also die but that seems to be a BUG here.

**Comment by Rushor** [comment]
Maybe remove vmaps then in that dungeon to fix that issue with the wall?

**Comment by APTX4869s** [comment]
Still happening and it's annoying
Even in Council sometimes it happens if you took the boss near the walls or tanking him on the stairs. ( mostly in phase 3 when you won't have enough space you need to take the boss near the stairs )

![val thera def hp](https://user-images.githubusercontent.com/57665529/69433137-7df76280-0d54-11ea-8ffc-aa80facedf9e.png)

**Comment by Rushor** [comment]
do they evade near the stairs?

**Comment by Batraneluu** [comment]
Near walls mostly

**Comment by questbugreporter** [comment]
Caused by this https://github.com/WoWManiaUK/Blackwing-Lair/issues/2823
Really needs to be fixed, nobody enjoys playing tank on reign atm

**Comment by Rushor** [comment]
well then /close cause the reason is https://github.com/WoWManiaUK/Blackwing-Lair/issues/2823

will try to fix that right now.
