### ISSUE TITLE
[Dungeon/Rep] Throne of the Tides

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3868]
**Links:**

https://www.wowhead.com/throne-of-the-tides

https://www.engadget.com/2010/12/07/a-cataclysm-101-guide-for-reputation-rewards/?guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAABsjXR1XGruXcT-6w0pBpp1oXtD-dAALvjNedJ0Fe1tAbiDaGnzrz1v9KamnSoGd9cGeRzSQCUdDs-TAn7XOAb2RXaZx5QWLb_K0DCR2zGNEM1hXmo3H-ujHyU0s4rb_RTcrHFX8YcenzAmCVcy-R19S5PNSJgqkwlPWrSfi6RlD&guccounter=2

**What is happening:**
- While in Throne of the Tides last night we noticed that it is giving wrong rep
- I wore earthern ring tabard and angel was wearing Stormwind tabard 
but we all got Ramkahen rep 

**What should happen:**
- _Throne of the Tides should give earthern ring rep by default_ 
- _While wearing a chosen tabard it should give for the tabard and not any other_

**Comment by Rushor** [comment]
okay adjusted them all - pls check :)

**Comment by Echinaceax** [comment]
Still same issue @Rushor 
using different tabard still not getting tabard rep

**Comment by Rushor** [comment]
okay fixed. creature with CREATURE_FLAG_EXTRA_NO_XP_AT_KILL flag will no not get rep even with tabard on in the instances. please just gimme a list of the creatures and i will add it :)

**Comment by Rushor** [comment]
![I](https://i.imgur.com/kEef8oX.jpg)
