### ISSUE TITLE
[NPC] Laziphus - stabel master - critical erro - Gadgetzan

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3869]
**Links:**

from npc https://www.wowhead.com/npc=9985/laziphus

**What is happening:**
When trying to stable or unable stable a pet this npc causes players to get a critical error

**What should happen:**
players should be able to stable or unstable pets without error

**Comment by Rushor** [comment]
i gues client issue - works fine for https://i.imgur.com/4tZFJnj.jpg  https://i.imgur.com/q7wzhJG.jpg https://i.imgur.com/POg1yKs.jpg
