### ISSUE TITLE
[Quest] Supporting the troops - ID 27085 - Western Plaguelands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#387]
Quest - https://www.wowhead.com/quest=27085/supporting-the-troops
NPC - https://www.wowhead.com/npc=44462/jearl-donald

**Objective for supporting the troops**
- "slay the human soldiers that are fighting with our deathguards."

- Well the issue is that they are inactive mobs. 
- They are just standing there they are not fighting
- Ive killed a few (no kills added) Just to test
- Quest is not completable (Horde)

![defender kills](https://user-images.githubusercontent.com/39439201/50722716-78107880-10d3-11e9-8cf2-a6bcdd4373ec.jpg)
![no kills added](https://user-images.githubusercontent.com/39439201/50722722-89598500-10d3-11e9-82cd-54e93c547bb7.jpg)

**Comment by Rushor** [comment]
creatures added, killcrdit added

![I](https://i.imgur.com/Wm38KVj.jpg)
