### ISSUE TITLE
[Unholy/Ghoul] Spellpower instead of Attack power

### ISSUE THREAD

**Issue by Batraneluu** [WoWManiaUK/Blackwing-Lair#3870]
**Links:**

from WoWHead or our Armory
http://cata.cavernoftime.com/spell=17473
**What is happening:**
The ghoul gets Spell Power instead of Attack Power.
**What should happen:**
Ghoul should get Attack Power instead of Spell Power.

Replicate: Cast Horn of Winter watch pet stats.

**Comment by Shoogii** [comment]
http://cata-shoot.tauri.hu/?spell=58721 
the ghoul should get 40% strength through the glpyh

**Comment by Echinaceax** [comment]
Adding here for SS #3781
