### ISSUE TITLE
[Guild Spell] Have group will travel

### ISSUE THREAD

**Issue by Batraneluu** [WoWManiaUK/Blackwing-Lair#3871]
**Links:**

from WoWHead or our Armory

http://cata.cavernoftime.com/spell=83967

**What is happening:**
You can summon only 1 player by targeting his name.
**What should happen:**
You should be able to summon all your party / raid.

**Comment by Rushor** [comment]
have a script for that, if you don't want it :)

**Comment by Rushor** [comment]
added a short fix for it
