### ISSUE TITLE
[Guild/Perk] Chug-a-lug

### ISSUE THREAD

**Issue by Batraneluu** [WoWManiaUK/Blackwing-Lair#3873]
**Links:**

from WoWHead or our Armory
http://cata.cavernoftime.com/spell=83961
**What is happening:**
The duration of cauldron buffs doesn't change

**What should happen:**

Duration should be x2

![WoWScrnShot_111019_212303](https://user-images.githubusercontent.com/53946478/68549443-92f0ff00-0400-11ea-8de7-01b784bfcb56.jpg)

**Comment by Rushor** [comment]
92679 spell_guild_flask_of_battle

**Comment by Rushor** [comment]
duration is depending on guild status now (Chug-A-Lug Rank 1 / Chug-A-Lug Rank 2)

https://i.imgur.com/NMXCs00.jpg  https://i.imgur.com/KQpkgjx.jpg

**Comment by Batraneluu** [comment]
Is this fix live? Cause i tried yesterday another cauldron flask with Chug-A-Lug Rank 2 and still got 60 minutes duration.

**Comment by Echinaceax** [comment]
This will be on this weeks update 
@Batraneluu when janitor adds this too his "live" done list. he will close it :)

Tuesday/Wednesday
