### ISSUE TITLE
[NPC] Vaultkeeper Razid - storage unit

### ISSUE THREAD

**Issue by ghost** [WoWManiaUK/Blackwing-Lair#3875]
**Links:**

https://wow.gamepedia.com/Vaultkeeper_Razhid

**What is happening:**
doesn't allow players to store items

**What should happen:**

should allow players to store sole bound items

**Comment by Echinaceax** [comment]
update on this 
Works as far as i saw ...
ive used the one in the Reign Mall 

![working](https://user-images.githubusercontent.com/39439201/89081204-2b625180-d38b-11ea-8ec6-9d3b87bd6f27.jpg)
