### ISSUE TITLE
RHC rewards and daily quest limit interaction

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3876]
**What is happening:**

Completing a Random Cataclysm Heroic dungeon does not award gold, MP, valor or justice points if the partaking character has completed 25 daily quests on the same day.

**What should happen:**

There should be no interaction between dailies and DF at all.

**Comment by Rushor** [comment]
void Player::RewardQuest(Quest const* quest, uint32 reward, Object* questGiver, bool announce, bool lfgreward)

the lfg quests should now be completable several times over and over again - pls test it :)

**Comment by questbugreporter** [comment]
@Rushor the fix didn't work for this

**Comment by questbugreporter** [comment]
Actually it might have done something,  I received the gold, the mp and JP as if I had already done 7/7 weekly dungeons. 
Note I haven't done any (0/7) dungeons after the reset.

**Comment by Echinaceax** [comment]
@Rushor - reopening this 
not fix, reported by GM from a player ingame

**Comment by Rushor** [comment]
the quests were not triggered as repeatable. added that now. pls test :)

**Comment by Rushor** [comment]
questids: ('28905', '28906', '28907', '28908');
