### ISSUE TITLE
Creatures 51983 (Deadwind Widow) misplaced at Swamp of Sorrows 48, 55

### ISSUE THREAD

**Issue by Druhl** [WoWManiaUK/Blackwing-Lair#3878]
https://www.wowhead.com/npc=51983/deadwind-widow

There are two sitting right on top of the flightmaster in Stonard, Swamp of Sorrows. They immediately attack any player landing there. No AFK flying!  lol

When killed they respawn.

![WoWScrnShot_111119_100846](https://user-images.githubusercontent.com/19803911/68597916-c74dd500-046b-11ea-8d74-01c4ca4e38d7.jpg)
![WoWScrnShot_111119_100845](https://user-images.githubusercontent.com/19803911/68597937-cd43b600-046b-11ea-927b-b35a0b5dc3cf.jpg)

**Comment by Rushor** [comment]
removed
