### ISSUE TITLE
[Quest] Umbrafen Eel Filets - Zangarmarsh

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#3879]
**Links:**

[Umbrafen Eel Filets](https://www.wowhead.com/quest=9780/umbrafen-eel-filets)
[Eel Filet](https://www.wowhead.com/item=24374/eel-filet)

**What is happening:**

[Eel Filet](https://www.wowhead.com/item=24374/eel-filet) dont drop

**What should happen:**

[Eel Filet](https://www.wowhead.com/item=24374/eel-filet) need to drop

**Comment by Rushor** [comment]
chance increased
