### ISSUE TITLE
[NPC] Fiona - phasing issue - Eastern Plaguelands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#388]
Missing**NPC** -https://www.wowhead.com/npc=45417
**Quest** - https://www.wowhead.com/quest=27683/into-the-woods
**picked up from** - https://www.wowhead.com/npc=10840/ https://www.wowhead.com/npc=44456
Unable to complete/hand in quest due to NPC missing or not in correct place.

**Comment by sarahkay88** [comment]
same issue for the **quest**: https://www.wowhead.com/quest=28578/heros-call-eastern-plaguelands
**picked up from** - https://www.wowhead.com/object=207320
this prevents you from collecting and completing the following quests:
https://www.wowhead.com/quest=27367
https://www.wowhead.com/quest=27368

**Comment by sarahkay88** [comment]
found another quest that also relates to this issue.
Quest: visitors: https://www.wowhead.com/quest=27684/visitors

**Comment by Echinaceax** [comment]
Same for horde

Quest - https://www.wowhead.com/quest=27684/visitors

- Cant complete - missing npc

**Comment by Dranah** [comment]
NPC missing in position 
Map: 0 (Eastern Kingdoms) Zone: 139 (Eastern Plaguelands) Area: 2619 (Thondroril River)
X: 1916.449951 Y: -2651.120117 Z: 60.703098 Orientation: 1.291540
