### ISSUE TITLE
[Object] Cobalt Deposit - Various locations

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#3880]
**Links:**

Object - https://www.wowhead.com/object=189978/cobalt-deposit
Object - https://www.wowhead.com/object=189979/rich-cobalt-deposit

from WoWHead or our Armory

**What is happening:**
In regards to the spawn of cobalt deposits and rich cobalt deposits after checking various areas a 
Very low amount of spawn points actually spawning in the location mentioned below - spend over an hour in Borean Tundra and Howling fjord mining today and onlt found maybe 20-25 nodes between the two areas .

**What should happen:**
There should be a lot more spawns of both objects in the areas of northrend for example:-

Cobalt deposit
This object can be found in Zul'Drak  (221), Howling Fjord  (179), Borean Tundra  (168), Dragonblight  (147), Grizzly Hills  (123), Utgarde Keep , The Storm Peaks  (16), and Crystalsong Forest  (11).

Rich cobalt Deposit
This object can be found in Zul'Drak  (204), Howling Fjord  (159), Borean Tundra  (150), Dragonblight  (129), Grizzly Hills  (108), The Storm Peaks  (9), Crystalsong Forest  (8), and Utgarde Keep .

![zuldrak_cobalt](https://user-images.githubusercontent.com/45798884/68626204-b71d1080-04d2-11ea-952c-a0406ad68212.png)

Heres an example of Zul'draks spawn locations but in live theres maybe 10-20 nodes available to players in there area

**Comment by Slydee23** [comment]
ill talk with rushor maybe i take this task

**Comment by sarahkay88** [comment]
@Slydee23 it's already been done

**Comment by Slydee23** [comment]
@sarahkay88 good :D

**Comment by Rushor** [comment]
well there is pooling for them select * from pool_gameobject where guid IN (select guid from gameobject where id=189978)

but anyway, you need to open up a single report for each zone. else this is too huge for me. slydee and me are working on it internally
