### ISSUE TITLE
[Dungeon] Shadowfang Keep - Level requirement 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3886]
**Links:**

https://classic.wowhead.com/shadowfang-keep

reported from an ingame player too a GM

![sfk](https://user-images.githubusercontent.com/39439201/68699357-2baf8800-0583-11ea-85e4-9c223c4c2997.jpg)

tested with a level 20 and 80 test char (GM off)

**What is happening:**
- Level requirements wrong 
- players are getting a lvl requirement message 

**What should happen:**
its a level 20 dungeon

**Comment by Ovahlord** [comment]
The level messages and dbc based. Only because the dungeon is unlocked via dungeon finder at level 20 does not means it's locked until level 20. Level 11 is indeed correct. False positive report

**Comment by Echinaceax** [comment]
Ok, thanks @Ovahlord 
so its meant to be this way ?

**Comment by Ovahlord** [comment]
Yes. This is one if the few things that are clearly defined inside of the client

**Comment by Rushor** [comment]
the requirment for 85 (hc) was missing for some reason. added that now
