### ISSUE TITLE
Protection Paladin: Talent Vindication

### ISSUE THREAD

**Issue by APTX4869s** [WoWManiaUK/Blackwing-Lair#3888]
![Vindication](https://user-images.githubusercontent.com/57665529/68714123-b65eaa00-05b8-11ea-9a0e-391b5f5758d3.png)

**What is happening:**
each attack\spell applies Vindication on target
1- Judgment spell ID 20271
2- Avenger's Shield ID 31935
3- Holy Wrath ID 2812
4- Exorcism ID 879
5- Shield of the Righteous ID 53600
6- Hammer of Wrath ID 24275
tested with these spells

**What should happen:**
Only Crusader strike ( ID 35395) and Hammer of the Righteous ( ID 53595 ) should apply it

**Comment by mfranca0009** [comment]
All set 👍

**Comment by HrafnValknutt** [comment]
Fixed in Dev confirmed. ^^
