### ISSUE TITLE
Holy Paladin: Eternal Glory

### ISSUE THREAD

**Issue by APTX4869s** [WoWManiaUK/Blackwing-Lair#3890]
![Eternal Glory talent ID](https://user-images.githubusercontent.com/57665529/68715241-fa52ae80-05ba-11ea-931a-0d8b93f757c9.png)

![Hidden Eternal Glory](https://user-images.githubusercontent.com/57665529/68715243-fde63580-05ba-11ea-93ff-886af5a27991.png)

**What is happening:**
Eternal Glory( spell ID 88676 ) doesn't have cooldown
![Eternal glory 0 cd](https://user-images.githubusercontent.com/57665529/68715339-3259f180-05bb-11ea-825f-8c0969f36af4.png)

**What should happen:**
Eternal Glory( spell ID 88676 ) should've 15 sec cooldown

**Comment by mfranca0009** [comment]
Should be all set 👍 removed the triggered attribute which was causing it to ignore cooldowns.

**Comment by HrafnValknutt** [comment]
Fixed in Dev confirmed.
