### ISSUE TITLE
[Daily][Quest][Item] Hitting a Walleye - Drop chance low

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3898]
https://www.wowhead.com/quest=26414/hitting-a-walleye#comments

Quest item ID: 58503

Fishing this item takes a really long time since the drop chance seems to be bugged. It is supposed to be 100% from 75 fishing skill onwards when on this quest.

**Comment by Rushor** [comment]
increased

**Comment by sarahkay88** [comment]
is this fix live? - if so its wrong 25% drop chance
https://github.com/WoWManiaUK/Blackwing-Lair/issues/3898

**Comment by bagi84** [comment]
i did it this morning around 0800 server time and the the drop rate was fine caught 8 in less than 20 casts …. https://www.wowhead.com/item=58503/hardened-walleye even states 25% drop chance

**Comment by Echinaceax** [comment]
You need to revert this fix @Rushor 25% drop not 100%
https://github.com/WoWManiaUK/Blackwing-Lair/issues/3898

**Comment by Rushor** [comment]
reverted to 25, thank you!
