### ISSUE TITLE
[Item][Quest] Orders from Lady Vashj - Item doesn't grant quest

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3899]
https://www.wowhead.com/quest=9764/orders-from-lady-vashj

Item ID: 24367

Item cannot be used to obtain the quest, cannot be added to quest log even via a GM.

**Comment by Rushor** [comment]
the quest was removed in cata https://www.wowhead.com/quest=9764/orders-from-lady-vashj

will remove the item drop
