### ISSUE TITLE
[Quests] Ashes to Ashes / The Farmers' Militia closing each other - Western Plaguelands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#390]
NPC https://www.wowhead.com/npc=44452/koltira-deathweaver

**Having some issues with koltira-deathweaver**

- After giving back "the battle resumes"
- NPC has 2 more quests "Ashes to Ashes" and "The Farmers' Militia"
- I picked up Ashes to Ashes, and i clicked to get "The Farmers' Militia" but it had vanished.
- So As we have problems with Ashes to Ashes i abandon it.
- Now i could choose  The Farmers' Militia
https://www.wowhead.com/quest=27084/the-farmers-militia

- It seems you can take one or the other, not both as individual quests.

![ashes taken](https://user-images.githubusercontent.com/39439201/50725821-45cb3f00-1104-11e9-870a-090ead0f0a60.jpg)

**then i abandoned ashes to ashes**

![the tw quests](https://user-images.githubusercontent.com/39439201/50725825-62677700-1104-11e9-9bd1-63e7ad70cd67.jpg)

**Now ive taken the farmers militia. the ashes to ashed quest isnt there**

![the farmers](https://user-images.githubusercontent.com/39439201/50725845-a65a7c00-1104-11e9-85d4-750e0721bd35.jpg)

- will add more if theres any problems with this quest

**Comment by Dranah** [comment]
Confirmed, the two quests are currently exclusive to obtain and completing one will close the other, making you unable to complete it.
Both should be available at the same time and both should be a prerequisite of the follow up "Lindsay Ravensun revealed"

**Comment by Kitzunu** [comment]
I take it from this that the horde part of this quest is broken.

It will now follow the quest line shown here https://wow.gamepedia.com/The_Farmers%27_Militia

Quest: The Battle Resumes! will be closed if you pick up either Ashes to Ashes or Supporting the Troops
