### ISSUE TITLE
[Item] Bouguet of red rose - Shadowfang Keep

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3900]
**Links:**
https://classic.wowhead.com/item=22206/bouquet-of-red-roses?classicRedirect 
https://classic.wowhead.com/item=3424/bouquet-of-black-roses
**What is happening:**

Dropping from last boss in hc of shadowfang keep

**What should happen:**
shouldn't drop unless event for love is in the air is active

**Comment by Priestelar** [comment]
Same is happening on ripsnarl in deadmines HC https://www.wowhead.com/npc=47626/admiral-ripsnarl

**Comment by Rushor** [comment]
condition added that it only drops during love is in the air event!
