### ISSUE TITLE
[Hunter/Talent]Hunter Toxicology incorrect crit multiplier

### ISSUE THREAD

**Issue by ztrkeiko** [WoWManiaUK/Blackwing-Lair#3901]
Just want to point out issue #3661 was closed as working correctly when it isn't.

The base critical damage for serpent sting is 150%
Edit: Applies to Black Arrow too (150% base critical damage)
The mistake you made is assuming that Toxicology (2/2) multiplies that 150% by 2.
Whereas it should be 1+0.5*2 = 2

https://cata-twinhead.twinstar.cz/?issue=2619

Also, as another reference, shadow priests get a spell called Shadow Power (ID: 87327) that increases critical damage of shadow spells by 100% which if working correctly will be 150%->200% critical damage.
Edit 2:
All classes that can do non-damage roles have this kind of spell:
(Since Mage and Warlock are damage only, their spell have 199.5% instead of 150%).
Balance Druid has Moonfury (ID: 16913)
As stated above: Shadow Priest has Shadow Power (ID: 87327)
Elemental Shaman has Elemental Fury (ID: 60188)

**Comment by Keader** [comment]
Ranged crit = 100% of damage
BaseDamage = 874 (my hunter)
But spells with SPELLMOD_CRIT_DAMAGE_BONUS (like Toxilogy) add 100% into original damage
So the formula becomes:

FinalCritDamage = 874 [base]  + ( 874 [base] * 2 [Toxilogy 2/2] ) = 2622
Is working exactly like ANY talent with SPELLMOD_CRIT_DAMAGE_BONUS
Nothing is wrong.

**Comment by ztrkeiko** [comment]
"Invalid", Keader, you're one stubborn "dev"
Here's retail evidence of a Survival Hunter:
https://www.youtube.com/watch?v=rZYmURRKHdE
His Serpent Sting and Black Arrow crits are doing around 209% of hit damage (nowhere near 300%)
The reason for 209% is 200% from Toxicology * 3% from meta gem (2 * 1.03 = 2.06)
It's not exactly 209% because of hit damage being truncated I assume.
