### ISSUE TITLE
game crashing

### ISSUE THREAD

**Issue by WarUnlocked** [WoWManiaUK/Blackwing-Lair#3903]
**Links:**

from WoWHead or our Armory

**What is happening:**
and when I went to some kind of destroyed temple an error message popped up, and every time I try to connect with this character the game gives the same error message, and the game doesn't show HUD, so I can't do anything, please help me

![Capturar](https://user-images.githubusercontent.com/57774327/68896683-c38bae00-070a-11ea-99b2-721d253662d7.PNG)
**What should happen:**

**Comment by Rushor** [comment]
Please update you client with the launcher form the website

https://wow-reign.com/forum/viewforum.php?f=16&sid=4b39195e4a331d694aac5d804160983a
https://wow-reign.com/start
