### ISSUE TITLE
[Spell] Earth shield - shammy

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3904]
**Links:**

https://www.wowhead.com/spell=974/earth-shield

**What is happening:**
unsure on this one so it may not be valid. but at level 85 without no gear at all I can go toe to toe with a mob in uldum and take no damage because the shield out heals the damage

![shammy 2](https://user-images.githubusercontent.com/42302580/68959268-9fd96e00-07c5-11ea-9629-c3f385efcd23.jpg)
![shammy 1](https://user-images.githubusercontent.com/42302580/68959282-a49e2200-07c5-11ea-81ea-d7b81ab05f64.jpg)

![WoWScrnShot_111519_163523](https://user-images.githubusercontent.com/42302580/68959471-02cb0500-07c6-11ea-8b8f-02fcf326d0f0.jpg)

**Comment by Ovahlord** [comment]
That's not a earth shield issue, that's a npc damage issue. Npcs at this stage should hit within the 3k damage range, not 500

**Comment by sarahkay88** [comment]
it was tested with both this and rare npc same both happened, but I will go test on a different toon and get back to you.

**Comment by bagi84** [comment]
i agrre the Npc  damage is low to what it should be but after testing it on a full geared 85 shammy earth shield is healing for 20k normal and 30k crit procs which is the same amount as greater healing wave … so there's defo a issue with the scaling of heals from earth shield as they shouldn't be as high as a casted  large heal.

**Comment by Keader** [comment]
wrong spell_bonus_data entry o.o
