### ISSUE TITLE
[Spell] Killing Spree vs cho'gall adds

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3905]
Used killing spree (51690) close to the middle of the cho'gall boss fight chamber and I fell through the floor, into Sinestra's lair below.

![image](https://user-images.githubusercontent.com/56992013/68969146-f017f680-07ec-11ea-8639-ce07263bf1b1.png)

**Comment by Rushor** [comment]
maybe mmaps/vmaps related?

**Comment by Slydee23** [comment]
its ther trapdoor that should just break later

**Comment by Keader** [comment]
Deep core issue, i will not take a look into this now :/
