### ISSUE TITLE
[GO] Uldum Spawns for Whiptail and Cinderbloom

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Blackwing-Lair#3906]
http://cata.cavernoftime.com/object=202752
http://cata.cavernoftime.com/object=202747

Pooling and spawnpoints needs to be redone.

**Comment by Slydee23** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/55513205/68989499-38183700-0848-11ea-9cf7-89175c158aac.jpg)

Routing looks good now. now i check  if they are 2 much or not

**Comment by Slydee23** [comment]
need a small nerf for Whiptail here.

from 70 to 50 pls

**Comment by Echinaceax** [comment]
I agree with @Slydee23 , i seen last night to many spawn

**Comment by Rushor** [comment]
reduced to 50 :)
