### ISSUE TITLE
[NPC] Argent Tournament Quartermaster 

### ISSUE THREAD

**Issue by karteil** [WoWManiaUK/Blackwing-Lair#3907]
**Links:**
https://www.wowhead.com/npc=33556/doru-thunderhorn
https://www.wowhead.com/npc=33557/trellis-morningsun
https://www.wowhead.com/npc=33553/freka-bloodaxe 
https://www.wowhead.com/npc=33555/eliza-killian
https://www.wowhead.com/npc=33554/samamba

**What is happening:**
They don't sell argent tournaments items 

**What should happen:**
They should sell items if the player became champion of their respective city. 
I have tried Doru Thunderhorn (Thunder Bluff) because I'm tauren, and get the Champion and Exalted Champion of Thunder Bluff achievement 

![WoWScrnShot_111519_223211](https://user-images.githubusercontent.com/18135968/68977652-062bb400-07f9-11ea-82f0-3bbdfd5e1a32.jpg)

Supposing that it could be only a problem of the tauren npc, I became Exalted Champion of Silvermoon too but the bug expands to Silvermoon npc too

![WoWScrnShot_111519_224401](https://user-images.githubusercontent.com/18135968/68977833-72a6b300-07f9-11ea-972c-9e6c776a8bc1.jpg)

I suppose the problem concerns all quartermaster npc. I suppose it's only a problem of npc flag and not missing vendor item table but, if you need a bug report for every single npc with their item, I will gladly make it.

Again, thank you for your hard work

**Comment by Rushor** [comment]
This is a really good report

**Comment by Nacho-k** [comment]
Probably also happens with Dame Evniki Kapsalis
https://cata-twinhead.twinstar.cz/?npc=34885
You can buy from her after earning the achievement Exalted Argent Champion of the Alliance or Exalted Argent Champion of the Horde

**Comment by Rushor** [comment]
okay yes - there is a achievement check for it that does not work. will replace i with a questcheck instead. 
for example: http://cata.cavernoftime.com/quest=13728

**Comment by Rushor** [comment]
okay fixed. once quests like http://cata.cavernoftime.com/quest=13725 is rewarded (depending on faction) you will see the vendors then. https://i.imgur.com/lXjOsNc.jpg
