### ISSUE TITLE
[NPC] Cult Assassin - Argent Tournament 

### ISSUE THREAD

**Issue by karteil** [WoWManiaUK/Blackwing-Lair#3908]
**Links:**
https://www.wowhead.com/quest=14016/the-black-knights-curse

**What is happening:**
The [Cult Assassin](https://www.wowhead.com/npc=35127/cult-assassin) npc does not attack player

**What should happen:**
The quest require to go to the grave of Black Knight, wait that Cult Saboteur talk to Cult Assassin and then Cult Assassin should attack the player   

![WoWScrnShot_111619_000118](https://user-images.githubusercontent.com/18135968/68982159-29a92b80-0806-11ea-8ca2-be3313ba42c3.jpg)

I suppose script assign wrong faction to the Cult Assassin after the disappearance of Cult Saboteur

**Comment by Rushor** [comment]
done https://i.imgur.com/HsFMXuw.jpg
