### ISSUE TITLE
"Guild" level 17 instant mail issue

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3909]
**Links:**

from WoWHead or our Armory

**What is happening:**
When you return a mail from a guild mate it is not instant even tho you have the guild lvl 17 with the instant mail between guild mates.

If you are just sending a mail its instant but not when u are returning it :)
**What should happen:**

The return should be instant.

**Comment by Rushor** [comment]
try now
