### ISSUE TITLE
[Xfaction] Pets and Mind Controle Effects

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3910]
**Links:**
**Warlock** Felguard
https://wow.gamepedia.com/Felguard_(warlock_minion)
https://cata-twinhead.twinstar.cz/?spell=30146

**Druid** Force of Nature
https://wow.gamepedia.com/Force_of_Nature
https://cata-twinhead.twinstar.cz/?spell=33831

**What is happening:**
- Since xfaction
 we have noticed that Horde/ally pets summoned attack each other, resulting in lost dps

**What should happen:**
_Should attack target not each other_ 

**What is happening:**
1. When Cho'gall converts people you can't interrupt them anymore and after you become converted you see the other player which was converted with you as enemy. Also if you damage the boss with AoE Damage you also damage the players that are channeling in Conversion.

**What should happen:**

1.You should be able to interrupt players on conversion

**Comment by Rushor** [comment]
will combine this issue since they are all related :)

**Comment by wow-mania** [comment]
We will not fix any issue with xfaction since this is not a natural state of the game and fixing it may cause other problems later on when we remove it.
