### ISSUE TITLE
[Profession] Skinning - Spinescale Basilisk

### ISSUE THREAD

**Issue by Hespericless** [WoWManiaUK/Blackwing-Lair#3911]
**Links:**

https://www.wowhead.com/npc=39658/spinescale-basilisk

**What is happening:**

Some of the mobs are not skinnable while some are.

**What should happen:**

Every Spinescale Basillisk should be skinnable.

**Comment by Rushor** [comment]
done https://i.imgur.com/fpsPG4t.jpg
