### ISSUE TITLE
[Quest] Twilight Territory - Mount Hyjal

### ISSUE THREAD

**Issue by Hespericless** [WoWManiaUK/Blackwing-Lair#3912]
**Links:**
https://www.wowhead.com/quest=25311/twilight-territory
Quest ID: 25311
**What is happening:**
Not every Horrorguard counts toward the quest.

**What should happen:**
Every Horrorguard should give quest credit.

**Comment by Echinaceax** [comment]
https://www.wowhead.com/npc=39724/horrorguard

**Comment by Rushor** [comment]
for us https://www.wowhead.com/npc=48725 need to be removed

**Comment by Rushor** [comment]
done https://i.imgur.com/UMiWXwQ.jpg
