### ISSUE TITLE
[Profession] - Skinning - Prof Xp Gain

### ISSUE THREAD

**Issue by Hespericless** [WoWManiaUK/Blackwing-Lair#3913]
**What is happening:**
When Skinning orange mobs you're not getting skill up sometimes.

**What should happen:**
Orange should always give skill up.
orange = 100% skill up
yellow = high chance skill up
green = low chance skill up
grey = no skill up

**Comment by Hespericless** [comment]
Not sure if this is happening with other professions as well.

**Comment by sarahkay88** [comment]
https://www.wowhead.com/skinning#comment
https://www.wowhead.com/skill=2561/cataclysm-skinning
https://wow.gamepedia.com/Skinning

**Comment by Rushor** [comment]
UpdateGatherSkill

**Comment by Rushor** [comment]
This is spell related - i will give it to keader

**Comment by mfranca0009** [comment]
Seems to be fixed now after I made multiple skinning changes 👍
