### ISSUE TITLE
[NPC] Ancestral Guardians - loot

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3914]
**Links:**
https://www.wowhead.com/npc=48518/ancestral-guardian#drops:200+16-19+1
https://www.wowhead.com/item=67146/woundsplicer-handwraps

**What is happening:**
Whilst killing the above NPC in the chambers of the moon uldum this item dropped
item lvl  359 epic

**What should happen:**
cant find it on the npc loot table.

**Comment by Nacho-k** [comment]
It's a world drop, should drop from every mob in cataclysm zones

**Comment by sarahkay88** [comment]
your right @Nacho-k  thanks for the info :) much appreciated.
