### ISSUE TITLE
[Npc] Narkrall Rakeclaw missing from live - Twilight Highlands 

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3915]
https://www.wowhead.com/npc=48257/narkrall-rakeclaw
https://www.wowhead.com/quest=28282/narkrall-the-drake-tamer

Npc ID: 48257

This quest was working untill a few days ago, for whatever reason, this npc was removed and replaced with the corpse of npc ID 47618, whilest these are the same mob, the change in IDs makes this quest no longer completable.

NOTE: npc 48257 is still on dev and must just be readded to live.

![WoWScrnShot_111619_180920](https://user-images.githubusercontent.com/16594771/68996945-8c073800-08a9-11ea-9ac7-b8f0748963c9.jpg)

**Comment by Echinaceax** [comment]
i can confirm the IDs where different and the npc thats there is down on the ground fighting

**Comment by Rushor** [comment]
video here: https://www.youtube.com/watch?v=ok7J85D-Bqw

an event must be scripted

**Comment by Priestelar** [comment]
Npc is back to where he was now before this issue was made

**Comment by Rushor** [comment]
i haven't changed anything lol :D

**Comment by Priestelar** [comment]
@Rushor I found the issue on this, I think the npc has an unreasonable long respawn timer and thats what is causing the problem of the "missing" npc. I did the quest early this morning and its several hours later and the mob hasnt respawned yet.

**Comment by Rushor** [comment]
yeah well the npc should not have any static spawn. it should spawn every time you klick on the gossip (if he is not already there)

**Comment by Priestelar** [comment]
Ah thats true, but at the same time, we must remember there is not a gossip spawning option available at the moment, so the only people that are able to complete the quest are the ones that can get a kill when the mob is spawned

**Comment by Druhl** [comment]
Not sure what the latest status is supposed to be on this NPC, but for me on this quest (28282) there was no gossip option for https://www.wowhead.com/npc=48173/colin-thundermar to "assist" as I think there should be.

The target NPC is flying up on a drake. If the quest gossip were correct etc. I suspect he would come down to fight on the ground, or something. As it was, I was able to range him from below (he never came down, just took hits) until he was dead and I was then able to hand in and complete the quest. Wouldn't be possible to do this workaround if a melee class of course.

![WoWScrnShot_011820_204700](https://user-images.githubusercontent.com/19803911/72673177-c1104200-3a34-11ea-95cc-f255cefff973.jpg)

**Comment by Rushor** [comment]
fixed, can be summoned with gossip now 

https://i.imgur.com/r3pavJl.jpg
https://i.imgur.com/46oZtZN.jpg
