### ISSUE TITLE
Valiona and Theralion seem to roll loot independently (10 Man)

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3916]
I don't really know all the facts about 10m loot, but I've only seen a boss drop the same it twice in  this fight. I've killed them maybe 6 times on this server and 3 of them they both dropped the same item.

**Comment by sarahkay88** [comment]
other don't agree so if you are thinking so they have different loot tables then you may also want to consider fixing the in game  dungeon journal .

![WoWScrnShot_111719_031440](https://user-images.githubusercontent.com/42302580/69002512-b0ced000-08e8-11ea-8f15-64db120d5b47.jpg)
![WoWScrnShot_111719_031429](https://user-images.githubusercontent.com/42302580/69002514-b9270b00-08e8-11ea-80f1-c6f9ed454053.jpg)

**Comment by sarahkay88** [comment]
https://www.wowhead.com/npc=45992/valiona
https://www.wowhead.com/npc=45993/theralion
https://cata-twinhead.twinstar.cz/?npc=45992
https://cata-twinhead.twinstar.cz/?npc=45993
good luck with this one.

**Comment by questbugreporter** [comment]
The issue is different from what I posted here, I will open a new one.

**Comment by sarahkay88** [comment]
Do not close the report add your information to this one

**Comment by sarahkay88** [comment]
#3918

**Comment by Rushor** [comment]
yes the loot table need to be adjusted

**Comment by Rushor** [comment]
Drops from the Valiona and Theralion encounter in Bastion of Twilight.
https://www.wowhead.com/item=59512/valionas-medallion#comments

this seems to be shared.

however i will change the drop now like this:

items are grouped by mode and creature like this:

59517,
59518,
59515,
63532,
63533,
63531,

59512,
59516,
59519,
63536,
63534,
63535,

65107,
65106,
65109,
65095,
65094,
65096,

65112,
65108,
65105,
65091,
65093,
65092,

**Comment by Echinaceax** [comment]
i dont understand why the change then ...what was fixed?
why fix something that isnt broken lol

from all links from atlas loot and the link you provided @Rushor 
https://www.wowhead.com/item=59512/valionas-medallion#comments

and the links you gave us in dev to use also say the same info
https://wowwiki.fandom.com/wiki/Theralion_and_Valiona

> however i will change the drop now like this:

makes no sense to change thing that are not "blizzlike"

**Comment by sarahkay88** [comment]
Could have just changed it to the random drop was more spontaneous so minimise same drops happening

**Comment by Rushor** [comment]
Currently it is possible to get 6 times the same item in 25.

This was changed now

**Comment by Echinaceax** [comment]
this report is about the 10 man last thurday, not a 25 man

**Comment by Rushor** [comment]
okay removed my changes. it works good like it is as said in discord

**Comment by Echinaceax** [comment]
@Rushor still has the same item issue we have done 2-3 BoT raids with guild and same loot double every time 

![double items](https://user-images.githubusercontent.com/39439201/74116866-b4a38300-4bb5-11ea-934b-6042219a4b9c.jpg)

Any way you can alter the spontiniousness of the drop behavour ?
https://github.com/WoWManiaUK/Blackwing-Lair/issues/3916#issuecomment-554763136
