### ISSUE TITLE
Valiona and Theralion have the wrong drop tables

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3918]
https://www.wowhead.com/npc=45992/valiona
https://www.wowhead.com/npc=45993/theralion
Wowhead data is incorrect for some reason.

http://cata.cavernoftime.com/npc=45993
http://cata.cavernoftime.com/npc=45992
https://cata-twinhead.twinstar.cz/?npc=45992
https://cata-twinhead.twinstar.cz/?npc=45993
These websites show that Valiona and Theralion drop completely different items and after watching a few 25 man kills from 2011-2012 I believe that they are correct.

Currently on reign it is possible to get Theralion loot from Valiona and vice versa.

**Comment by sarahkay88** [comment]
> _Currently on reign it is possible to get Theralion loot from Valiona and vice versa._
Currently on reign it is possible to get Theralion loot from Valiona and vice versa. - this link de-proves that argument since 1 dragon drops both loot - therefore isn't solid proff. that this shouldn't happen

**Comment by sarahkay88** [comment]
_Currently on reign it is possible to get Theralion loot from Valiona and vice versa._
http://cata.cavernoftime.com/npc=45993 - your own link de-proves the validity of what your saying. since the table of this one boss on the link drops both its item and the other dragons
