### ISSUE TITLE
[Quest] My Heart is in Your Hands - Grizzly Hills

### ISSUE THREAD

**Issue by karteil** [WoWManiaUK/Blackwing-Lair#3919]
**Links:**
https://www.wowhead.com/quest=12802/my-heart-is-in-your-hands

**What is happening:**
Drinking the elixir [Drakuru's Elixir](https://www.wowhead.com/item=35797/drakurus-elixir) does not make appear [Image of Drakuru](https://www.wowhead.com/npc=26701/image-of-drakuru)

**What should happen:**
Quest require to collect 5 [Desperate Mojo](https://www.wowhead.com/item=36743/desperate-mojo) from some nearly trolls. The drop is ok, after getting 5 mojo, I tried to summon Image of Drakuru in the Drakuru Brazier at [45, 28] but he doesn't show himself.

**Comment by Rushor** [comment]
fixed https://i.imgur.com/sJ9zxmW.jpg
