### ISSUE TITLE
[Quest] Betrayal - Grizzly Hills

### ISSUE THREAD

**Issue by karteil** [WoWManiaUK/Blackwing-Lair#3920]
**Links:**
https://www.wowhead.com/quest=12713/betrayal

**What is happening:**
It's impossible to get item [Drakuru's Skull](https://www.wowhead.com/item=40425/drakurus-skull) contained in gameobject [Drakuru's Skull](https://www.wowhead.com/object=191458/drakurus-skull)

**What should happen:**
After a long fight against Drakuru, he become green and appear Mr. Lich King, then he talk to Drakuru about this and that (I don't know how to get the dialogues), then Mr. Lich King should kill Dracuru and instead of drakuru corpse, it should appear [Drakuru's Skull](https://www.wowhead.com/object=191458/drakurus-skull) gameobject

**Comment by Rushor** [comment]
fixed https://i.imgur.com/InRKh9k.jpg https://i.imgur.com/dz6loa0.jpg

**Comment by Rushor** [comment]
and the other script also still works https://i.imgur.com/CCRPPDs.jpg
