### ISSUE TITLE
[Raid][Drop] Chogall 25 man mode dropping too few items - Bastion of Twilight

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3921]
We did a 25 man raid today and ONLY 4 items dropped when we killed Chogall the final boss.

![WoWScrnShot_111719_183731](https://user-images.githubusercontent.com/16594771/69011141-f84c6f00-096f-11ea-9b35-5915a0391103.jpg)

Tested it on dev and the same happened there, only 4 items dropped
![WoWScrnShot_111719_185433](https://user-images.githubusercontent.com/16594771/69011145-03070400-0970-11ea-9ba7-8586ce612b67.jpg)

**Comment by Rushor** [comment]
10 man :

Normal Boss : 2 Items
Token Boss : 3 Items

25 Man :

Normal Boss  : 5 Items 
Token Boss : 6-7 Items

**Comment by Rushor** [comment]
10 man mode https://i.imgur.com/Ya2nQ6d.jpg
25 man mode https://i.imgur.com/g167Ipc.jpg

**Comment by Echinaceax** [comment]
full check happening here #3921
