### ISSUE TITLE
[Druid / Feral] Ferocious Bite wrong energy consumption amount

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3923]
22568 Ferocious Bite 

**What should happen:**

"Consumes up to 35 additional energy to increase damage by up to 100%"

**What is happening:**

Only consumes up to 25 energy instead.

**Comment by ztrkeiko** [comment]
Your tooltip shows pre-4.2 patch change, in Patch 4.2 Ferocious Bite got changed:
Ferocious Bite damage has been increased by 15%. In addition, its base cost has been reduced to 25 energy and it can use up to 25 energy, for up to a 100% damage increase.

**Comment by questbugreporter** [comment]
Interesting

**Comment by Keader** [comment]
Dbc data: Power POWER_ENERGY, **Cost 25** in 4.3.4
