### ISSUE TITLE
[Paladin] Hand of Protection strange interaction with other forbearance causing spells

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3925]
1022 Hand of Protection
642 Divine Shield
633 Lay on Hands
25771 Forbearance

**What is happening:**

Using Hand of Protection on another character (NOT MYSELF) prevents me from using Divine Shield and from using Lay on Hands on myself or anyone else. This lasts until the end of combat.
If I use Hand of Protection on myself, I can use divine shield normally one minute later, after the Forbearance debuff expires and Lay on Hands can be used on any target not suffering from Forbearance.

**What should happen:**

Unless I'm missing something obvious,  Hand of Protection should not be causing this interaction at all.

**How to replicate:**

While in a raid or party, use Hands of Protection on a party or raid member other than yourself.
This must be done during combat. 
I have seen this happen in the Bastion of Twilight raid and Blackrock Caverns dungeon instances.

**Comment by APTX4869s** [comment]
I can confirm this
it's so annoying in PvP too. If I want to use Hand of Protection on my arena partner it makes me unable to use Divine Shield on myself which it's a big disadvantage to any paladin player in arenas.

**Comment by sarahkay88** [comment]
https://wow.gamepedia.com/Hand_of_Protection
https://wow.gamepedia.com/Divine_Shield
It should. Only affect the player that has the forbearance debuff.
