### ISSUE TITLE
[Daily][Quest] Tol Barad quests at baradin hold not granting any gold

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3926]
I noticed that after earning around 400 gold from my dailies I stopped getting any more from them. I was unable to receive ANY more gold from my daily quests for the day.

At first I thought i was wrong but then I tested it out for myself on Live
![WoWScrnShot_111819_134118](https://user-images.githubusercontent.com/16594771/69050075-ed461d00-0a09-11ea-9fd6-11140cabcb36.jpg)

After handing in a quest:
![WoWScrnShot_111819_134130](https://user-images.githubusercontent.com/16594771/69050112-02bb4700-0a0a-11ea-8c06-c15aaae34183.jpg)

^ my gold stayed the same even though I earned 18

Not sure if it was because I did a whole bunch of dailies in that day already but as far as I am aware there shouldnt be a cap on how much gold you can earn, the reason for that is why there is a cap on how many dailies can be done.

**Comment by Priestelar** [comment]
Tested further, the issue is tied to dailies in Tol Barad and not daily quests as a whole.
![WoWScrnShot_111819_135210](https://user-images.githubusercontent.com/16594771/69050494-d522cd80-0a0a-11ea-8d2e-ea90b443ad72.jpg)

**Comment by Priestelar** [comment]
After even further testing on dev I found the problem. The quests from this section in Tol Barad do NOT give any gold to the player, despite the gold received section displays gold being earned.
![Capture](https://user-images.githubusercontent.com/16594771/69053314-d1467980-0a11-11ea-9b29-b3122d7c3c1f.PNG)

![WoWScrnShot_111819_143832](https://user-images.githubusercontent.com/16594771/69053336-dc99a500-0a11-11ea-9d8c-12b0f52390ba.jpg)
![WoWScrnShot_111819_143844](https://user-images.githubusercontent.com/16594771/69053341-df949580-0a11-11ea-89ba-fb5f2cf168d5.jpg)

**Comment by Rushor** [comment]
all ids 

28117,
28118,
28120,
28165,
28185,
28186,
28668,
28669,
28670,
28122,
28162,
28163,
28657,
28658,
28659,
28663,
28664,
28665,
28660,
28661,
28662,
28188,
28223,
28232,

**Comment by Rushor** [comment]
bonusmoney for maxlevel was missing - added it!
