### ISSUE TITLE
[Daily][Quest] Tol barad peninsula - Quest givers bug

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3927]
https://www.wowhead.com/tol-barad-peninsula#quests

As stated on wow head, only 6 quests should be given out a day by the npcs. 

However, the Horde have 7 quests available each day
![WoWScrnShot_111819_144914](https://user-images.githubusercontent.com/16594771/69053868-07382d80-0a13-11ea-90f7-4fac35220a40.jpg)

Whilest the Alliance only have 5 quests available each day

![WoWScrnShot_111819_144745](https://user-images.githubusercontent.com/16594771/69053880-0acbb480-0a13-11ea-8b50-0b5108eb5f82.jpg)

**Comment by Rushor** [comment]
problem found! the pooling was changed with a different pool_template. will restructure that!

**Comment by Rushor** [comment]
pooling adjusted
