### ISSUE TITLE
Jewel Crafting "Prospecting"

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3929]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/item=53038/obsidium-ore#prospecting
https://www.wowhead.com/item=52185/elementium-ore#prospecting
**What is happening:**
When you Prospect Obsidium ore it seems like the % on what you get a reversed So you get more rare gems then common.

When you prospect Elementium ore It seems fine But might check the % on the drops there aswell when you prospect the ores.

**What should happen:**

When you prospect Obsidium ore it should not be garuanteed a rare gem like it is now since its 1.2% chance of getting a rare gem.

**Comment by Rushor** [comment]
will check that

**Comment by Rushor** [comment]
adjusted it know

**Comment by Priestelar** [comment]
I love how this report spawned out of me casually telling Jimpaa that I don't think obsidian prospecting sounds right 😂

**Comment by Echinaceax** [comment]
> I love how this report spawned out of me casually telling Jimpaa that I don't think obsidian prospecting sounds right 😂

Team work lol
