### ISSUE TITLE
[Flight Path] Camp Mojache - Feralas

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#393]
https://www.wowhead.com/npc=39898/shyn

![fp feralas](https://user-images.githubusercontent.com/39439201/50734841-829b4280-11a5-11e9-8d5f-97e5119a1036.jpg)

**Comment by Echinaceax** [comment]
Both me and Dranah tested this FP yesterday and wasnt active 

- After connecting Stonemaul hold FP and Camp Ataya in Feralas it is connecting to other locations now
- Still has map bugs though 

![map bugs](https://user-images.githubusercontent.com/39439201/50736801-1a0e8e80-11c2-11e9-9e98-faf5047d97d0.jpg)

**Comment by Dranah** [comment]
The npc isn't inactive, the flight path appears to be. So she doesn't have anything to say until you have connecting flight paths, normally she should say "You don't have any flight paths connected to this one".
You can use her to fly elsewhere, but from other FPs, you cannot see this one as an option.

**Comment by Echinaceax** [comment]
**more info**

- Exactly 

cant see this flight for other Feralas PF either 

![fp fer](https://user-images.githubusercontent.com/39439201/50739057-be043400-11da-11e9-9b22-92011735f9c2.jpg)

**Comment by Rushor** [comment]
moved to https://github.com/WoWManiaUK/Blackwing-Lair/issues/3660
