### ISSUE TITLE
[BOSS] Argaloth - Baradin Hold 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3930]
**Links:**
https://www.wowhead.com/npc=47120/argaloth#abilities:mode=n10

**What is happening:**
- No rep given 

**What should happen:**
- Should give rep with and without tabard

Normal
250 reputation with Baradin's Wardens https://www.wowhead.com/faction=1177/baradins-wardens
250 reputation with Hellscream's Reach https://www.wowhead.com/faction=1178/hellscreams-reach

or tabard rep

**Comment by Rushor** [comment]
https://youtu.be/LLp-65thHnw?t=291 some more proof

**Comment by Rushor** [comment]
Award Reputation - Boss Kill

but better creature_on_kill

**Comment by Rushor** [comment]
https://i.imgur.com/EqiMc6J.jpg done

**Comment by Echinaceax** [comment]
@Rushor your SS only shows one rep :)

should give both 

**Gains**
After killing this NPC you will gain:
Normal
250 reputation with Baradin's Wardens
250 reputation with Hellscream's Reach

**Comment by questbugreporter** [comment]
Hellscream's Reach is the horde equivalent of Baradin's Wardens, you cannot get both at the same time.

**Comment by Rushor** [comment]
yes she asked because of xfaction behaviour. we will see how it goes

**Comment by Echinaceax** [comment]
@questbugreporter Yes i know

Exactly @Rushor, but we talked in DEV channel so GitH didnt see the question :)

**Comment by Echinaceax** [comment]
Update: correct rep are given to Horde/Ally now 
thanks @Rushor
