### ISSUE TITLE
[Spell] Glyph of Bloodletting does nothing

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3931]
http://cata.cavernoftime.com/spell=54815

There's an old closed issue that says it's been fixed, but this isn't the case for me.
My character is a level 85 tauren druid if it makes any difference.

**Comment by Rushor** [comment]
@Keader https://github.com/WoWManiaUK/Blackwing-Lair/issues/1963

**Comment by Keader** [comment]
Recorded in PTR now: https://youtu.be/PbyAeohxTIs
It's working fine.
If is not working for you, please talk to a GM, is your character bug

**Comment by questbugreporter** [comment]
Sorry I was testing with the wrong bleeding spell, my mistake.
