### ISSUE TITLE
[Spell] Innervate 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3932]
**Links:**

https://vanilla-wow.fandom.com/wiki/Innervate
https://wow.gamepedia.com/Innervate

**What is happening:**
- Innervate doesnt seem to be giving correct amount 
can you check please 

**What should happen:**

> Causes the target to regenerate 10% of the caster's maximum mana over 10 sec. If cast on self, the caster will regenerate an additional 10% of maximum mana over 10 sec.

its only changed in 4.2.0 (as far as i can see) 

>  Patch 4.2.0 (2011-06-28): Now grants an ally target 5% of his or her maximum mana over 10 seconds, but still grants 20% of the druid's maximum mana over 10 seconds when self-cast.

Side note 

> Innervate adds only 20 mana to each tick, regardless of base mana. Target should give 5% in 10s (0.5% / s) and if the druid fits it, it should add 20% in 10s (2% / s).

translated from https://cata-twinhead.twinstar.cz/?issue=398  bug report :)

**Comment by Keader** [comment]
Everything looks working fine here.
