### ISSUE TITLE
[NPC] Disciple of Hate - Baradin Hold

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3934]
**Links:**

https://www.wowhead.com/npc=56350/disciple-of-hate

**What is happening:**
- Npc was only added in patch 4.3.0.1

**What should happen:**
Remove or leave is fine, so up to you @Rushor :)

**Comment by Rushor** [comment]
will remove them - we removed some other pre 4.3.0 patch npcs aswell

**Comment by Rushor** [comment]
removed
