### ISSUE TITLE
[NPC] Spider - ID 14881

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3935]
**Links:**

npc https://classic.wowhead.com/npc=14881/spider

rep https://www.wowhead.com/faction=1012/ashtongue-deathsworn

![spider rep](https://user-images.githubusercontent.com/39439201/69153335-572ff680-0ade-11ea-9350-b80ea780003d.jpg)

**What is happening:**
- lvl 1 spider giving Ashtongue Deathsworn rep

**What should happen:**
_Spider not meant to give anything_

Reported via discord

**Comment by APTX4869s** [comment]
Same thing for Fire Beetle in Mount Hyjal, near Firelands where Garr stands, it gives rep for Thrallmar 
![Fire beetle](https://user-images.githubusercontent.com/57665529/69164414-68dac380-0b09-11ea-8bb5-5f41d3df1442.png)

**Comment by APTX4869s** [comment]
in same place you can find Ash Lizard, it has 100% chance to drop this blade.
![Ash Lizard](https://user-images.githubusercontent.com/57665529/69164713-ea325600-0b09-11ea-87a5-30bf642e9959.png)

**Comment by Echinaceax** [comment]
@APTX4869s can you make new report for it please?

**Comment by Rushor** [comment]
removed
