### ISSUE TITLE
[NPC] Fire Beetle - Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3936]
**Links:**

https://www.wowhead.com/npc=61328/fire-beetle
![thralimar rep](https://user-images.githubusercontent.com/39439201/69166335-59e91680-0af3-11ea-951f-105f5334c327.jpg)

**What is happening:**
- Giving rep 

**What should happen:**
Shouldnt give rep 

reported by @APTX4869s

**Comment by Rushor** [comment]
removed
