### ISSUE TITLE
[NPC] Ash Lizard - Mount Hyjal

### ISSUE THREAD

**Issue by APTX4869s** [WoWManiaUK/Blackwing-Lair#3937]
![Ash lizardoooooo](https://user-images.githubusercontent.com/57665529/69166984-9590da00-0b0d-11ea-8121-bb4a38d0d7c6.png)

https://www.wowhead.com/npc=62364/ash-lizard
https://classic.wowhead.com/item=15217/widow-blade
**What is happening:**
Ash Lizard has 100% chance to drop that blade

**What should happen:**
shouldn't drop that blade

**Comment by Echinaceax** [comment]
@Rushor Confirmed 

![lizzards 100](https://user-images.githubusercontent.com/39439201/69168489-10022f80-0af7-11ea-8fd8-8de336eb95a3.jpg)

**Comment by Rushor** [comment]
Oh shit

**Comment by Echinaceax** [comment]
lol i know :P

**Comment by Rushor** [comment]
oh there are some more drops from critters. will remove them all.

**Comment by Rushor** [comment]
removed
