### ISSUE TITLE
[Quest][Npc] Aggra giving unavailable quests

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3940]
https://www.wowhead.com/quest=29338/into-unrelenting-flame
https://www.wowhead.com/quest=29329/elemental-bonds-patience

Npc: https://www.wowhead.com/npc=53738/aggra
Both of these quests are part of the: Call of the world shaman quest chain made available in patch 4.2

**Comment by Rushor** [comment]
removed
