### ISSUE TITLE
[NPC/Deadmins] Molten Slag damage

### ISSUE THREAD

**Issue by Batraneluu** [WoWManiaUK/Blackwing-Lair#3941]
**Links:**
https://www.wowhead.com/npc=49229/molten-slag
from WoWHead or our Armory

**What is happening:**
Their damage is absolute madness.

**What should happen:**
Reduce their damage done!

![WoWScrnShot_111919_233559](https://user-images.githubusercontent.com/53946478/69188656-a2212c80-0b25-11ea-95d4-72d7eae539ed.jpg)

**Comment by Rushor** [comment]
dmg reduced https://i.imgur.com/ExtKmto.jpg
