### ISSUE TITLE
[Vendor] Ibdil the Mender

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3942]
https://www.wowhead.com/npc=45407/ibdil-the-mender

This npc acts as a repair vendor however he shouldnt be selling anything as stated in his wowhead link as well as at the wiki page: https://wowwiki.fandom.com/wiki/Ibdil_the_Mender

At the moment he sells: https://www.wowhead.com/item=62321/lesser-inscription-of-unbreakable-quartz this is a mistake.

**Comment by Rushor** [comment]
removed

**Comment by Rushor** [comment]
refixed like priestelar said https://i.imgur.com/7z8VU2M.jpg (random vendor now)
