### ISSUE TITLE
[NPC] Stefan Vadu - Zul'Drak

### ISSUE THREAD

**Issue by karteil** [WoWManiaUK/Blackwing-Lair#3943]
**Links:**
https://www.wowhead.com/npc=28518/stefan-vadu

This npc give a nice quest chain that end with the quest Betrayal fixed just some few days ago (thank you again). In this chain quest the player disguises himself in a ugly Scourge guy, using the item [Ensorcelled Choker](https://www.wowhead.com/item=38699/ensorcelled-choker). If the player lost this item, the npc Stefan Vadu have a dialogue "I've lost my ensorcelled choker!" that should give the item 

**What is happening:**
Actually click in the dialogue doesn't give the [Ensorcelled Choker](https://www.wowhead.com/item=38699/ensorcelled-choker)

**What should happen:**
The dialogue should give the item

**Comment by Rushor** [comment]
fixed https://i.imgur.com/ltq8uWU.jpg
