### ISSUE TITLE
[NPC] Drakkari Guardian

### ISSUE THREAD

**Issue by karteil** [WoWManiaUK/Blackwing-Lair#3944]
**Links:**
https://www.wowhead.com/npc=26620/drakkari-guardian

Those npc are untargettable in normal mode inside Drak'Tharon Keep. I need to farm them for Enduring Mojo. 

**What is happening:**
Npc are untargettable. 

**What should happen:**
They should be targetable like any other npc inside dungen

**Comment by Rushor** [comment]
they are like in hc mode now.
