### ISSUE TITLE
Prospecting Elementium Ore often returns nothing

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3945]
https://www.wowhead.com/item=52185/elementium-ore#comments

Literally deleting my ore, it worked properly before the last update too.

**Comment by Rushor** [comment]
always the same. some people say it's too much - some people say it's too less lol

**Comment by Rushor** [comment]
will make it like that: 100 percent chance to get 1-2 of the lower stones. additional 25 chance to get 1-2 of the better stones.

**Comment by Rushor** [comment]
all done https://i.imgur.com/PL93OqL.jpg https://i.imgur.com/diifaWS.jpg https://i.imgur.com/hyvq5PK.jpg https://i.imgur.com/Jps4FDZ.jpg
