### ISSUE TITLE
[Quest] Learn to Ride in Elwynn Forest (remove) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3946]
**Links:**

https://www.wowhead.com/quest=14079/learn-to-ride-in-elwynn-forest
https://www.wowhead.com/item=46875/riding-training-pamphlet

**What is happening:**
- Allies are still getting this at lvl 20 in the mail 
- Unclickable item

can be removed all lvl20 riding quests theyre not needed as the free mount and riding are auto given
https://www.wowhead.com/quest=32665/learn-to-ride

![learn to ride](https://user-images.githubusercontent.com/39439201/69257826-fbd43600-0bbb-11ea-8d2e-8e5039acaa8f.jpg)

**Comment by Rushor** [comment]
removed :)
