### ISSUE TITLE
[Item][Spell] The Twilight blade - proc chance too low

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3947]
Someone brought it too my attention that this weapon has a very infrequent drop chance and that it should be much higher.
![image](https://user-images.githubusercontent.com/16594771/69259365-d00a7d80-0bc6-11ea-8163-5a777b34d63e.png)

I tested it out on dev for a few minutes and even with Slice and Dice(attack speed steroid up) procs were very infrequent even whilest dual wielding this weapon. 

The proc chance should be higher and can stack up to 3 times, I did EVENTUALLY get 2 stacks but the proc chance feels extremely low. The player told me that this proc should be much higher as on retail.

Whilest researching for this item's proc chance I could not find any stats to suggest what the proc chance should be but alot of players on wowhead comments would talk about how the good it is when they have 3 procs up all the time.

http://cata.cavernoftime.com/item=68163#contained-in-item
http://cata.cavernoftime.com/spell=95678
^ Spell name is The Deepest Night

**Comment by Rushor** [comment]
yeah the spell is http://cata.cavernoftime.com/spell=95678 but where is the proc mechanic added?

**Comment by Rushor** [comment]
ah nvm i think that is one of those items where proc handling is done in item_template 68163
