### ISSUE TITLE
"Dungeon" Utgarde Keep "Alliance"

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3948]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://www.wowhead.com/npc=24111/defender-mordun#comments 
Does not spawn inside the dungeon for alliance and there for cant get any quests. 
We should get 
https://www.wowhead.com/quest=29803/ears-of-the-lich-king
https://www.wowhead.com/quest=29763/stealing-their-thunder
https://www.wowhead.com/quest=29764/disarmament

All alliance sees is a horde player that we can kill. Most likely the Quest giver for horde

**What should happen:**
The quest giver should spawn inside the dungeon to provide the quests needed for the dungeon.

**Comment by Rushor** [comment]
added him https://i.imgur.com/7RWQwRD.jpg
