### ISSUE TITLE
[Xfaction] PVP attacks in dungeons

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3949]
Seems some players find it amusing to abuse Xfaction when asked to regroup coz of bugs

> Just leave and gg

he said haha then attacks us for honor points

![shitty player](https://user-images.githubusercontent.com/39439201/69275175-2cc46300-0bdc-11ea-9cad-753ffb878576.jpg)

**What is happening:**
- healer left so we had to disband group
Horde player clearly thought free  honor points

**What should happen:**
Should set pvp off inside dungeons if you can :)

**Comment by Rushor** [comment]
okay did a pvp off on enter dungeon instance map. hope it helps

**Comment by Echinaceax** [comment]
Nice job @Rushor
