### ISSUE TITLE
[NPC] Thunk's Wyvern <Flight Master> - Desolace

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#395]
https://www.wowhead.com/npc=35556/thunks-wyvern

- Problem with mobs to close to Flight path 
- X4 Starving bonepaw attack as you when you land
- Bonepaws need moving from Flight point 

![bonepaw](https://user-images.githubusercontent.com/39439201/50735350-ff321f00-11ad-11e9-9cc4-76b72c65aefb.jpg)

**Comment by Dranah** [comment]
This is the location
Map: 1 (Kalimdor) Zone: 405 (Desolace) Area: 4925 (Thunk's Abode)
X: -534.471436 Y: 1066.171265 Z: 89.900383 Orientation: 5.772579

Problematic mob: Starving Bonepaw NPC ID = 4689
