### ISSUE TITLE
[Profession] [Alchemy] Mixology

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3950]
https://www.wowhead.com/spell=53042/mixology

It doesn't increase the duration of flasks and elixirs that I can craft.
Flask of the wind gives me 330 agility when it should be at least 380.
My character is a level 85 tauren feral druid and alchemy is his second profession.
My other profession is engineering.
Two of my horde guild members claim it doesn't work for them either.
I have talked with an alliance alchemist that claims it works normally for him on two different characters.

**Comment by Echinaceax** [comment]
Was looked at here #2429

**Comment by questbugreporter** [comment]
I think it's either Horde only or something to do with herbalism.

**Comment by Rushor** [comment]
Do you just watched the buff or the real amount in Character window?

**Comment by questbugreporter** [comment]
Both

**Comment by Slydee23** [comment]
and duration is still 1h

**Comment by Rushor** [comment]
Okay strange. Have to Check it on dev again. With which item do you tried it?

**Comment by questbugreporter** [comment]
flask of the wind 58087
elixir of deep earth 58093
prismatic elixir 58143

**Comment by Rushor** [comment]
hm duration works for me if i have learned it https://i.imgur.com/aZgcnSV.jpg

**Comment by Rushor** [comment]
fixed now https://i.imgur.com/BUEl4Iu.jpg https://i.imgur.com/wXfhE97.jpg

The buss status is wrong but the actualy value on character is correct now. the spell was missing for some items.

**Comment by questbugreporter** [comment]
which ones work on live?

**Comment by Rushor** [comment]
Almost all. Wait will. Give you the list

**Comment by Rushor** [comment]
@questbugreporter 

those are working:
SPELL_MIXOLOGY                      = 53042,
    // Flasks
    SPELL_FLASK_OF_THE_FROST_WYRM       = 53755,
    SPELL_FLASK_OF_STONEBLOOD           = 53758,
    SPELL_FLASK_OF_ENDLESS_RAGE         = 53760,
    SPELL_FLASK_OF_PURE_MOJO            = 54212,
    SPELL_LESSER_FLASK_OF_RESISTANCE    = 62380,
    SPELL_LESSER_FLASK_OF_TOUGHNESS     = 53752,
    SPELL_FLASK_OF_BLINDING_LIGHT       = 28521,
    SPELL_FLASK_OF_CHROMATIC_WONDER     = 42735,
    SPELL_FLASK_OF_FORTIFICATION        = 28518,
    SPELL_FLASK_OF_MIGHTY_RESTORATION   = 28519,
    SPELL_FLASK_OF_PURE_DEATH           = 28540,
    SPELL_FLASK_OF_RELENTLESS_ASSAULT   = 28520,
    SPELL_FLASK_OF_CHROMATIC_RESISTANCE = 17629,
    SPELL_FLASK_OF_DISTILLED_WISDOM     = 17627,
    SPELL_FLASK_OF_SUPREME_POWER        = 17628,
    SPELL_FLASK_OF_THE_TITANS           = 17626,
    // Elixirs
    SPELL_ELIXIR_OF_MIGHTY_AGILITY      = 28497,
    SPELL_ELIXIR_OF_ACCURACY            = 60340,
    SPELL_ELIXIR_OF_DEADLY_STRIKES      = 60341,
    SPELL_ELIXIR_OF_MIGHTY_DEFENSE      = 60343,
    SPELL_ELIXIR_OF_EXPERTISE           = 60344,
    SPELL_ELIXIR_OF_ARMOR_PIERCING      = 60345,
    SPELL_ELIXIR_OF_LIGHTNING_SPEED     = 60346,
    SPELL_ELIXIR_OF_MIGHTY_FORTITUDE    = 53751,
    SPELL_ELIXIR_OF_MIGHTY_MAGEBLOOD    = 53764,
    SPELL_ELIXIR_OF_MIGHTY_STRENGTH     = 53748,
    SPELL_ELIXIR_OF_MIGHTY_TOUGHTS      = 60347,
    SPELL_ELIXIR_OF_PROTECTION          = 53763,
    SPELL_ELIXIR_OF_SPIRIT              = 53747,
    SPELL_GURUS_ELIXIR                  = 53749,
    SPELL_SHADOWPOWER_ELIXIR            = 33721,
    SPELL_WRATH_ELIXIR                  = 53746,
    SPELL_ELIXIR_OF_EMPOWERMENT         = 28514,
    SPELL_ELIXIR_OF_MAJOR_MAGEBLOOD     = 28509,
    SPELL_ELIXIR_OF_MAJOR_SHADOW_POWER  = 28503,
    SPELL_ELIXIR_OF_MAJOR_DEFENSE       = 28502,
    SPELL_FEL_STRENGTH_ELIXIR           = 38954,
    SPELL_ELIXIR_OF_IRONSKIN            = 39628,
    SPELL_ELIXIR_OF_MAJOR_AGILITY       = 54494,
    SPELL_ELIXIR_OF_DRAENIC_WISDOM      = 39627,
    SPELL_ELIXIR_OF_MAJOR_FIREPOWER     = 28501,
    SPELL_ELIXIR_OF_MAJOR_FROST_POWER   = 28493,
    SPELL_EARTHEN_ELIXIR                = 39626,
    SPELL_ELIXIR_OF_MASTERY             = 33726,
    SPELL_ELIXIR_OF_HEALING_POWER       = 28491,
    SPELL_ELIXIR_OF_MAJOR_FORTITUDE     = 39625,
    SPELL_ELIXIR_OF_MAJOR_STRENGTH      = 28490,
    SPELL_ADEPTS_ELIXIR                 = 54452,
    SPELL_ONSLAUGHT_ELIXIR              = 33720,
    SPELL_MIGHTY_TROLLS_BLOOD_ELIXIR    = 24361,
    SPELL_GREATER_ARCANE_ELIXIR         = 17539,
    SPELL_ELIXIR_OF_THE_MONGOOSE        = 17538,
    SPELL_ELIXIR_OF_BRUTE_FORCE         = 17537,
    SPELL_ELIXIR_OF_SAGES               = 17535,
    SPELL_ELIXIR_OF_SUPERIOR_DEFENSE    = 11348,
    SPELL_ELIXIR_OF_DEMONSLAYING        = 11406,
    SPELL_ELIXIR_OF_GREATER_FIREPOWER   = 26276,
    SPELL_ELIXIR_OF_SHADOW_POWER        = 11474,
    SPELL_MAGEBLOOD_ELIXIR              = 24363,
    SPELL_ELIXIR_OF_GIANTS              = 11405,
    SPELL_ELIXIR_OF_GREATER_AGILITY     = 11334,
    SPELL_ARCANE_ELIXIR                 = 11390,
    SPELL_ELIXIR_OF_GREATER_INTELLECT   = 11396,
    SPELL_ELIXIR_OF_GREATER_DEFENSE     = 11349,
    SPELL_ELIXIR_OF_FROST_POWER         = 21920,
    SPELL_ELIXIR_OF_AGILITY             = 11328,
    SPELL_MAJOR_TROLLS_BLLOOD_ELIXIR    =  3223,
    SPELL_ELIXIR_OF_FORTITUDE           =  3593,
    SPELL_ELIXIR_OF_OGRES_STRENGTH      =  3164,
    SPELL_ELIXIR_OF_FIREPOWER           =  7844,
    SPELL_ELIXIR_OF_LESSER_AGILITY      =  3160,
    SPELL_ELIXIR_OF_DEFENSE             =  3220,
    SPELL_STRONG_TROLLS_BLOOD_ELIXIR    =  3222,
    SPELL_ELIXIR_OF_MINOR_ACCURACY      = 63729,
    SPELL_ELIXIR_OF_WISDOM              =  3166,
    SPELL_ELIXIR_OF_GIANTH_GROWTH       =  8212,
    SPELL_ELIXIR_OF_MINOR_AGILITY       =  2374,
    SPELL_ELIXIR_OF_MINOR_FORTITUDE     =  2378,
    SPELL_WEAK_TROLLS_BLOOD_ELIXIR      =  3219,
    SPELL_ELIXIR_OF_LIONS_STRENGTH      =  2367,
    SPELL_ELIXIR_OF_MINOR_DEFENSE       =   673

**Comment by Rushor** [comment]
and those are the oncs that are fixed with next update:

case 79469: // Flask of Steelskin
                    case 79470: // Flask of the Draconic Mind
                    case 79471: // Flask of the Winds
                    case 79472: // Flask of Titanic Strength
                    case 94160: // Flask of Flowing Water
                        amount += 80;
                        break;
                    case 79635: // Elixir of the Master
                    case 79468: // Ghost Elixir
                    case 79474: // Elixir of the Naga
                    case 79477: // Elixir of the Cobra
                    case 79481: // Impossible Accuracy
                    case 79632: // Mighty Speed
                        amount += 40;
                        break;
                    case 79480: // Elixir of Deep Earth
                        amount += 120;
                        break;
                    case 79631: // Prismatic Elixir
                        amount += 15;
                        break;

**Comment by questbugreporter** [comment]
Those don't work for me either, I'm pretty sure my alchemist doesn't even have the mixology ability somehow.

**Comment by Rushor** [comment]
then contact a gamemaster and let him check if you have this aura active 53042

this seems to be an idividual char bug then. it works for me.

make sure that you have the ability to craft the item aswell. only then it works.

**Comment by Priestelar** [comment]
I had to buy the mixology ability a few days ago, from the dalaran alchemy teacher.

**Comment by questbugreporter** [comment]
@Priestelar Worked, thanks. BUT it is not supposed to work like this in cataclysm, you're supposed to get it automatically just by learning the profession.

**Comment by sarahkay88** [comment]
@questbugreporter  that requires a separate report, this report was for 

> It doesn't increase the duration of flasks and elixirs that I can craft.
https://wow.gamepedia.com/Mixology
