### ISSUE TITLE
[NPC] Julak-Doom loot bug

### ISSUE THREAD

**Issue by Chicozoba** [WoWManiaUK/Blackwing-Lair#3951]
**Links:**

Julak-Doom on WowHead : https://www.wowhead.com/npc=50089/julak-doom

His "special" loot : https://www.wowhead.com/item=69844/vitreous-beak-of-julak-doom

**What is happening:**

We killed 10 times the WB Julak-Doom with Echie, and he didn't drop the loot (that has 94% of drop rate).

**What should happen:**

It should drop the dagger most of the time (94% of the time actually).

We didn't check the other WBs (They also have this kind of special loot) but I talked with a player (Who told to me about this bug) and he said the others were most likely bugged too as their special loot never dropped.

**Comment by Rushor** [comment]
https://i.imgur.com/CLXrUgF.jpg 94 percent chance added.
