### ISSUE TITLE
King Bangalash spawn place

### ISSUE THREAD

**Issue by Nexenwon** [WoWManiaUK/Blackwing-Lair#3952]
**Links:** https://wowwiki.fandom.com/wiki/King_Bangalash

from WoWHead or our Armory

**What is happening:** King Bangalash spawns at 48.87 / 57.52 cords

**What should happen:** He should be spawning on 48.00 / 59.00

**Comment by Rushor** [comment]
http://cata.cavernoftime.com/npc=731

**Comment by Rushor** [comment]
is on top now https://i.imgur.com/irwzm0R.jpg

**Comment by Rushor** [comment]
Do Not close. We need to push it with next update to live realm
