### ISSUE TITLE
[Npc] Blazewing - Missing rare npc in Hyjal

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3953]
https://www.wowhead.com/npc=50057/blazewing

I frequently check rare npc spawns and I have never been able to find this one. Went on dev and the .go creature 50057 indicated no creatures found leading me to believe this mob is not in the game at the moment.
![WoWScrnShot_112119_175558](https://user-images.githubusercontent.com/16594771/69354739-48d20e00-0c89-11ea-848f-d4a3437d787e.jpg)

He drops 1 item only: https://www.wowhead.com/item=67236/blazewings-furious-kilt

**Comment by Priestelar** [comment]
See also #2938

**Comment by jburkiett** [comment]
Interesting on my local it is spawned however it is phased into the Hyjal questline.  If we need the npcs added then I might have to write a query to add them.  Are the NPCs just missing from the DB completely or just the spawn points ?

**Comment by Priestelar** [comment]
@jburkiett  They are completely missing since I could not find them with the commands on dev

**Comment by Rushor** [comment]
@jburkiett you need to get the tc db

**Comment by Rushor** [comment]
will set spawntimer to 400000 /60 minutes

**Comment by Rushor** [comment]
okay will set respawntimer to 6 hours


By Eldarias (7,269 –  1·16·62)  on 2010/12/05 (Patch 4.0.3) |   |  
-- | -- | --


info here:

Respawn time is over 5 hours, seems to have a 100% chance of dropping [Blazewing's Furious Kilt]

https://www.wowhead.com/npc=50057/blazewing#comments:id=1207149

will also add pooling to him.

**Comment by Rushor** [comment]
and you cannot simply spawn them. they need pooling pathing and loot. i have a fix for that now. will apply soon.

**Comment by Rushor** [comment]
added with 2 variable spawnpoints.
loot is there aswell.

![I](https://i.imgur.com/qCxLpLD.jpg)
