### ISSUE TITLE
"Fishing" Volatile fire pool Hyjal

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3955]
**Links:**

from WoWHead or our Armory

**What is happening:**
https://imgur.com/a/EMub9k2
Cant reach one of the Pools when im trying to get some volatile fire. 
And also is the spawn timer on the pools lowered? 
it takes some time for it to respawn.
Are there only meant to be 2 pools around firelands?

**What should happen:**

You should be able to reach the pool from the rocks unless there is a item that makes you cast twice as long =)

**Comment by Rushor** [comment]
will change the position

**Comment by Slydee23** [comment]
yes its only meant to be 2 active at the same time and yeah respawn time is that high also

**Comment by Rushor** [comment]
moved it 

![I](https://i.imgur.com/V7LtVDm.jpg)
