### ISSUE TITLE
[NPC] Casandra Downs <Alchemy & Inscription Supplies> missing

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3957]
**Links:**

https://www.wowhead.com/npc=49703/casandra-downs

**What is happening:**
- NPC missing

**What should happen:**
- She should be at location

note: _She is only seen via GM on in dev too, i checked_
infact all profession vendors here can only been seen in dev with GM on 

None showing on live for Ally side
(Horde vendor is though)

**Comment by jburkiett** [comment]
Looked into this actually from what I can see the reason you cant see the NPC is due to that fact Players are phased in this area until they complete the Twilight Highlands Intro Quest line.

**Comment by Echinaceax** [comment]
Thank you @jburkiett i knew it was phasing, i just reported for now. as Horde has no phasing issues but Ally does even though the Twighlight zone is bugged for a lot of quests for each faction

**Comment by Echinaceax** [comment]
Update: yes GM phase me for test and yes there are there now
Thank you @jburkiett 

Still odd though that only ally have phasing issues with these vendors

**Comment by Rushor** [comment]
yes can confirm - they have no aura and are in normal phase 169
