### ISSUE TITLE
[NPC] Riding Trainers (doubles)

### ISSUE THREAD

**Issue by Nexenwon** [WoWManiaUK/Blackwing-Lair#3958]
Went to train riding and saw that there is double avaible. When u train with one other one is gone. 
![Untitled](https://user-images.githubusercontent.com/58032108/69415193-787a2800-0d14-11ea-83a1-3a576cefc3f9.png)

https://www.wowhead.com/npc=43693/darlene-stokx

**Comment by Rushor** [comment]
duplicate removed

![I](https://i.imgur.com/uBrZGGS.jpg)
