### ISSUE TITLE
[Classic][Gameobject] World Wide Mining/Herb nodes

### ISSUE THREAD

**Issue by Lurc1981** [WoWManiaUK/Blackwing-Lair#3961]
**Links:**

There are no real links to show or prove what I am stating

**What is happening:**

These nodes are too consistent and spawn much to quickly. Rares are always located in the same spawn location. This is currently hampering any opportunity to farm materials for any sort of profit and is also slowing (If not completely removing the usefulness) the AH. 

**What should happen:**

Each one has many spawnable loactions for these items. It should be on a rotating list of Active spawns vs zone maximum spawn locations. Each zone should have a maximum active spawns and then when one is 'picked/mined' it should trigger a spawn timer for the next node location at random. 

As this function is currently working, I can stand in front of one herb type I am trying to farm and wait between 20-30 seconds and it will respawn while I am standing there doing nothing.

**Comment by Rushor** [comment]
when i got time i will add pooling for each Mining/Herb node for each zone - so that they do not respawn in same place

**Comment by Rushor** [comment]
for tbc, wotlk it is fine
slydee is working on cata right now
for classic we need to fix it

**Comment by Rushor** [comment]
https://wowwiki.fandom.com/wiki/List_of_mining_nodes 
https://wow.gamepedia.com/Herb

**Comment by Rushor** [comment]
item   object
2447    1618,
765     1617,
22710   181166,
2449    1619,
785     1620,
2450    1621,
3820    2045,
2453    1622,
3369    1628,
3355    1623,
3356    1624,

3357,   2041,
3818,   2042,
3821,   2046,
3358,   2043,
3819,   2044,
4625,   2866,
8831,   142140
8838,   142142, 176636,
8839,   142143
8845,   142144
8846,   142145, 176637,
13464,  176583, 176638,
13463,  176584, 176639,
13465,  176586,
13466,  176587,
13467,  176588,
13468,  176589,

**Comment by Rushor** [comment]
With the next update all Herbs in the Classic zones will be pooled, which means that they no longer respawn in the same place, but instead have a static spawnamount out of a bigger pooled area. We may add more objects to the pool in the future. More infos here: https://github.com/WoWManiaUK/Blackwing-Lair/issues/3961 https://i.imgur.com/AyyrSIP.jpg
