### ISSUE TITLE
Char's model stuck

### ISSUE THREAD

**Issue by Chicozoba** [WoWManiaUK/Blackwing-Lair#3962]
**Links:**

Helix : https://www.wowhead.com/npc=47296/helix-gearbreaker#drops:mode=heroic
Lumbering Oaf : https://www.wowhead.com/npc=47297/lumbering-oaf

**What is happening:**

We killed the boss' add Lumbering Oaf right after the grabbed me and my char stayed in the NPC's hands on the floor (No SS :/) and after relog my char's model got stuck
![WoWScrnShot_112219_173101](https://user-images.githubusercontent.com/50930065/69443725-489c4600-0d4f-11ea-884f-04dac85088ac.jpg)
.
**What should happen:**

I don't really know how the game should behave but I'd say I should have left the boss hands after he dies and my model should have come back to normal.

**Comment by Echinaceax** [comment]
this is same issue as Panzer has with gnome https://github.com/WoWManiaUK/Blackwing-Lair/issues/1544

**Comment by Rushor** [comment]
this aura makes the issue 

ID - 88277 Ride Oaf

The aura will now always be removed once the Oaf is killed from all players in the dungeon. should solbe the problem then.
