### ISSUE TITLE
[NPC] Jessica Sellers - Dalaran

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3963]
**Links:**
https://www.wowhead.com/npc=33027/jessica-sellers#sells:0+2
https://www.wowhead.com/item=43126/ink-of-the-sea

**What is happening:**
- missing item
- Wrong item in its place

**What should happen:**
- shouldnt have this one https://www.wowhead.com/item=37101/ivory-ink
Should have this instead https://www.wowhead.com/item=43126/ink-of-the-sea

**Comment by Kitzunu** [comment]
fixed
