### ISSUE TITLE
[Daily][Quest] Stockup up - Darnassus Fishing

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3964]
https://www.wowhead.com/quest=29323/stocking-up

This quest item is not dropping at all, I tried about 20-30 casts and did not get 1 of them.

Item ID: https://www.wowhead.com/item=69912/lake-whitefish#fished-in
Item is said to have a 21% droprate while fishing in darnassus. Either I am the unluckies man alive or this item is not in the game.

**Comment by Rushor** [comment]
item dropp added with a 25 percent chance to get in area darnassus.
