### ISSUE TITLE
[Quest] The King's Observatory - id 14466 - Gilneas

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#3965]
**Links:**

from WoWHead or our Armory
Previous Quest - https://www.wowhead.com/quest=14465/to-greymane-manor
Quest - https://www.wowhead.com/quest=14466/the-kings-observatory
Next quest - https://www.wowhead.com/quest=14467/alas-gilneas
Npc -https://www.wowhead.com/npc=36743 - King Genn Greymane

**What is happening:**

When you climb to tower behind the manor to hand in the quest NPC King Genn Greymane isn't there you need to complete to log out and back in to make him appear .

**What should happen:**
The Npc Should be visible and interactive when you climb up the tower to the observatory
 to hand in to the quest and and once completed give you the next quest in the questline

**Comment by sarahkay88** [comment]
#2484

**Comment by sarahkay88** [comment]
#2501

**Comment by Rushor** [comment]
Okay i think spell area is duplicates here which creates issues

**Comment by Rushor** [comment]
i'm able to see them always now

![I](https://i.imgur.com/ymKrN0P.jpg)
![I](https://i.imgur.com/gFVj8PK.jpg)
![I](https://i.imgur.com/ajf8uej.jpg)

those two auras are needed for the quests. and i added them now (only once) in the chain. pls check :)

[21:00:29]id: 68483 [Phase - Quest Zone-Specific 08] effmask: 1 charges: 0 stack: 1 slot 0 duration: -1 maxduration: -1   caster: player guid: 1733
[21:00:29]id: 69484 [Phase - Quest Zone-Specific 11] effmask: 1 charges: 0

**Comment by sarahkay88** [comment]
works now good job @Rushor
