### ISSUE TITLE
[NPC] Kor'kron Overseer (Undercity)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3966]
**Links:**

Guard https://wow.gamepedia.com/Kor%27kron_Overseer_(Undercity)
Archaeology info https://wow.gamepedia.com/Adam_Hossack

![Archaeology missing](https://user-images.githubusercontent.com/39439201/69460349-354fa180-0d74-11ea-81e6-558cc8be5ed3.jpg)

**What is happening:**
- Archaeology guidence from Guards are missing

**What should happen:**
- guards should have Archaeology info to guide player to Adam Hossack

**Comment by Rushor** [comment]
thanks for report but we will move them all to this report now. https://github.com/WoWManiaUK/Blackwing-Lair/issues/1134
