### ISSUE TITLE
[NPC] Honor vendor missing weapons

### ISSUE THREAD

**Issue by Hartwall** [WoWManiaUK/Blackwing-Lair#3967]
**Links:**

http://cata.cavernoftime.com/?search=vicious+gladiator

**What is happening:**

The horde honor pvp gear vendor is missing all the weapons to be purchased.

**What should happen:**

There should be more than 4 pages of items on the vendor.

**Comment by Rushor** [comment]
we are not yet at that point of release. once more instances wth higher itemlevel are released, those wepsons will be added to the vendor aswell. It's a progressive server.

**Comment by Rushor** [comment]
see here https://github.com/WoWManiaUK/Blackwing-Lair/issues/1971

**Comment by Hartwall** [comment]
@Rushor There are weapons that should be purchasable by honor already? Or are you saying there was a period in cata where a vendor didnt sell any weapons?

**Comment by Echinaceax** [comment]
@Rushor The link the player linked is S9 i will check the vendor and let you know

**Comment by Rushor** [comment]
Thank you for research echi!
