### ISSUE TITLE
[NPC] [Vendor] Guild vendor selling items that have not been unlocked by the guild

### ISSUE THREAD

**Issue by Hartwall** [WoWManiaUK/Blackwing-Lair#3968]
**Links:**

http://cata.cavernoftime.com/npc=46572

**What is happening:**

![image](https://user-images.githubusercontent.com/18264581/69465206-2d4e2c80-0d89-11ea-930b-4e167cfed8aa.png)

**What should happen:**

Our guild doesnt have half the achievements yet I can buy all these items.

**Comment by Lurc1981** [comment]
But I've noticed that you can't buy other things. Namely, the helms last I checked.

**Comment by Rushor** [comment]
select * FROM `conditions` WHERE (`Sourcegroup`='46572') and sourceentry=63125

negativeoption=0
achivementcheck > value2 =1

**Comment by Echinaceax** [comment]
duplicate @Rushor #1263

**Comment by Rushor** [comment]
Okay, the conditions are there But they need to be adjusted to work.
Some checks for other archievements in General aswell

**Comment by Rushor** [comment]
okay fixed all.

the guild now need the the archivement and the propper rep with the guild. (also fixed the error that you no longer see the items if the rep was increased)

![I](https://i.imgur.com/4GpiMMr.jpg)
![I](https://i.imgur.com/2r50WA9.jpg)
