### ISSUE TITLE
[Item] Trinket: License to Slay

### ISSUE THREAD

**Issue by APTX4869s** [WoWManiaUK/Blackwing-Lair#3969]
![License to Slay](https://user-images.githubusercontent.com/57665529/69480958-07c33080-0e26-11ea-9cbe-068fb18305fc.png)

https://www.youtube.com/watch?v=c33xZyegihI&t=45s

at 0:45
he got 6 stacks easily under 2 seconds
**What is happening:**
License to Slay gives you a stack for only white melee attacks ( auto attacks ) 

**What should happen:**
each melee attack ( not only white auto attacks ) should give you a stack of it ( in the video I linked Divine Storm gave him 4 stacks because it hit 4 targets, just to make sure about this point. )

**Comment by questbugreporter** [comment]
If this item is bugged then someone should also test these ones since the effect is almost identical:

https://www.wowhead.com/item=56394/tias-grace
https://www.wowhead.com/item=58181/fluid-death

**Comment by Batraneluu** [comment]
He got 2 stacks with meele attacks and 4 from Divine Storm wich hitted 4 adds

**Comment by Rushor** [comment]
http://cata.cavernoftime.com/item=58180

**Comment by Rushor** [comment]
okay this got two entries in spell proc will remove the old system and let stay the new one which proccs on 
Melee attack hit successful
and
Successful attack by Spell that use melee weapon.

also there is an internal cooldown which i will remove.

source:

https://www.wowhead.com/item=58180/license-to-slay#comments:id=1339331
The proc on this trinket doesn't seem to have an internal cooldown, and gives 1 stack per enemy hit. So when you have it at 10 stacks the duration will continue to refresh itself back to 15 second as long as you keep hitting things.

**Comment by Rushor** [comment]
Killing Spree and Fan of Knives will closely stack the full proc in a very short time as long as both hit 100% successfully. The internal cooldown is very short

https://www.wowhead.com/item=56394/tias-grace
https://www.wowhead.com/item=58181/fluid-death

for those two i will add 1 sec coldown

**Comment by Rushor** [comment]
https://www.wowhead.com/item=58181/fluid-death#comments:id=1426451

all done.

**Comment by questbugreporter** [comment]
@Rushor You can see this guy in the video getting way more than one stack of Fluid Death per second: https://www.youtube.com/watch?v=frYT_QO2lGg

**Comment by Ovahlord** [comment]
As of patch 4.0.6 blizzard has added a internal 2 second cooldown to all stacking trinket procs. That's because people were stacking the procs like crazy and became too strong in a too short amount of time.

**Comment by Rushor** [comment]
thank you!

**Comment by questbugreporter** [comment]
And yet the evidence from 4.2 and 4.3 proves otherwise, can you provide some source?

**Comment by Rushor** [comment]
well we are at 4.0.x right now, soo

Ovahlord has a big knowledge about cata - i trust him

**Comment by questbugreporter** [comment]
https://worldofwarcraft.com/en-us/news/2166872/patch-4-0-6-official-notes
Where is it?

**Comment by Rushor** [comment]
not everything is in patchnodes, but the comments also say there is a small cooldown.

**Comment by APTX4869s** [comment]
@Rushor I'd like to see that comment, so a picture , ss , of it will be great.

**Comment by questbugreporter** [comment]
Do you believe that blizzard would nerf 346 and 359 ilvl trinkets in 4.0, but then buff them in 4.2, when they were supposed to get outclassed by loot found in firelands content?

**Comment by APTX4869s** [comment]
First of all, if he wants to jump into any report he must bring proof. even tho he's a tester or a dev ,I don't know, he MUST bring proof like videos or sources like we all do.
I read the whole " item " in patch notes 4.0.6, I didn't see any direct word says that the trinkets should have icd.
Sorry to disappoint you
https://www.youtube.com/watch?v=BQ44XwwVMlg
read the title and see his items.
he will start hitting the dummy at 4:55
but focus at 5:05 look how fast he will get from 6 stacks to 7 stacks less than 1 second
I don't see where is the " internal 2 second cooldown "
we are talking about retribution paladin, not the fastest class to get stacks. ^^
I'll wait for your sources maybe there is something wrong.

**Comment by Rushor** [comment]
i will let this be discussded in dev-test group aswell

**Comment by Ovahlord** [comment]
Blizzard used to ninja nerf trinket proc ICDs without documenting them. Many trinkets shared a 2 second icd during 4.0.6 times while it got later on reduced to less than 1 second on 4.2. I'm currently digging into several data to get the 'official' number at last.

**Comment by Rushor** [comment]
thank you

**Comment by Ovahlord** [comment]
Sooo, I'm referencing 7.3.5 data but these numbers are official and I doubt that they have changed them at all after MoP came. License to slay indeed got its ICD removed so yeah. On top of that since @Keader  that sucker leeched my proc data you can apply several cooldown corrections while you're at it:

```
UPDATE `spell_proc` SET `Cooldown`= 0 WHERE `SpellId` IN (92086, 92090, 92105, 91339, 91811);
UPDATE `spell_proc` SET `Cooldown`= 500 WHERE `SpellId` IN (90943, 90986);
UPDATE `spell_proc` SET `Cooldown`= 50000 WHERE `SpellId` IN (91814, 91193, 90848);
UPDATE `spell_proc` SET `Cooldown`= 100000 WHERE `SpellId` IN (91025, 92322, 91080, 90892, 95878);
UPDATE `spell_proc` SET `Cooldown`= 0, `ProcsPerMinute`= 0.92 WHERE `SpellId` IN (92175, 91144);
UPDATE `spell_proc` SET `Cooldown`= 0, `ProcsPerMinute`= 0.85 WHERE `SpellId`= 90899;
```

**Comment by Rushor** [comment]
@Ovahlord can you may join us in discord? I would love to learn sth from you (concerning vehicle handling) I like you.

**Comment by APTX4869s** [comment]
I really don't get it, if you gonna take tester's or dev's words without even they bring proofs on a normal player who opens reports then why the fuck you ask us to make reports? if all our proofs and time will be gone like this because a tester or a dev said invalid without bringing a proof then there is no point of me as a normal player in this server to make reports ....
first of all, I don't blame you trusting your testers or dev, but don't take me as a new player to cata
I played cata more than 5 years, I started in retail from the beginning till MoP. then I kept jumping from pserver to other ( all of them were cata ) 
so your words " I trust him because he has cata knowledge " doesn't seem fair to me I also hava cata knowledge if that what u meant.
also I don't know what @Ovahlord  meant by "  On top of that since @Keader that sucker leeched my proc data" if you mean these reports about trinkets https://github.com/WoWManiaUK/Blackwing-Lair/issues/3173   and the Firelands ones 
then I really wonder why Eye of Unmaking procs outside of combat without hitting anything? ( I was spamming Divine Storm outside combat )
in case if you don't know what Eye of Unmaking is
![Eye of Unmaking](https://user-images.githubusercontent.com/57665529/69748327-83dcb180-1161-11ea-80dd-3c21ccf5b052.png)
then I hope I get my answer  about it :) ( with blizzlike data or whatever u link )
![Nice trinket](https://user-images.githubusercontent.com/57665529/69748374-9bb43580-1161-11ea-8d5d-0f42b81473a8.png)

this ss is taken from reign's dev realm ..

oh yeah Rushor it seems you didn't read what Ovahlord wrote " License to slay indeed got its ICD removed so yeah "
agreeing with a dev or a tester  without reading what he wrote ROFL.

**Comment by Rushor** [comment]
I had no time to apply the new changes yet. Will do now. Will be applied with next update.
Pls no drama. Got Enough of that today irl...

**Comment by APTX4869s** [comment]
the thing is this isn't first time happening here, to me atleast, each time a tester jumps in a report they take his words even thought they don't bring a single proof.
so in the end we need to spend time till we find a proof like a video or it will be invalid forever ..

**Comment by Rushor** [comment]
okay then i will go in front. i apologise for that. we try to do it better next time okay? :)

**Comment by APTX4869s** [comment]
don't get me wrong I don't want apologize, I want proof from the testers for what they claim ..
since you will apply the fix in next patch let's just end this convo here because it's taking wrong path 
Thanks for your hard work Rushor.

**Comment by Rushor** [comment]
Thanks to ovahlord
