### ISSUE TITLE
[NPC] Zaeldarr the Outcast- (double spawned) - Eastern Plaguelands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#397]
NPC -https://www.wowhead.com/npc=12250/zaeldarr-the-outcast
Quest -https://www.wowhead.com/quest=6021/zaeldarr-the-outcast 
NPC picked up from - https://www.wowhead.com/npc=45500
Just informing you this NPC has doubled spawned. not so much an issue quest is to completable.

**Comment by Echinaceax** [comment]
Same for horde 

![zaeldarr the outcast 2](https://user-images.githubusercontent.com/39439201/50966103-3406e480-14d4-11e9-8203-839b4e3d1bc2.jpg)

**Comment by Rushor** [comment]
double removed
