### ISSUE TITLE
[Quest/Borean Tundra] Magic Carpet Ride

### ISSUE THREAD

**Issue by Batraneluu** [WoWManiaUK/Blackwing-Lair#3970]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=11636/magic-carpet-ride
**What is happening:**

Quest can't be turned in.

**What should happen:**
https://www.youtube.com/watch?v=qi5rc6GW5wc

**Comment by Rushor** [comment]
works for me 

![I](https://i.imgur.com/EkmbYmK.jpg)

maybe as a gm i sth with your questlog was wrong

**Comment by Echinaceax** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/5056#issuecomment-772458730 noticed some people fly there on their own mounts :) this could be the reason
