### ISSUE TITLE
[Race change] Bug found on race change

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#3974]
**Links:**

https://www.wowhead.com/spell=87840/running-wild

**What is happening:**
so I did a race change from worgen to nigh elf, and realised I can still use the above spell.
when use a ghost of a worgen starts to carry me around.

![worgen bug](https://user-images.githubusercontent.com/42302580/69486056-647f1500-0e3f-11ea-835b-ef714d1ba974.jpg)

**What should happen:**
Shouldn't be able to use other races passives after a race change.

**Comment by Rushor** [comment]
epic!
