### ISSUE TITLE
[Item] Charred Basilisk Meat - Mount Hyjal

### ISSUE THREAD

**Issue by Batraneluu** [WoWManiaUK/Blackwing-Lair#3976]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/item=52708/charred-basilisk-meat
**What is happening:**

Feeding the pet doesn't do anything

**What should happen:**

https://youtu.be/XW3tyUW8RG4?t=64

**Comment by Rushor** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/3504
