### ISSUE TITLE
Holy Paladin: Last Word

### ISSUE THREAD

**Issue by APTX4869s** [WoWManiaUK/Blackwing-Lair#3977]
![Last Word](https://user-images.githubusercontent.com/57665529/69486869-44188000-0e6a-11ea-9656-32800b42e787.png)

I'm sure this talent isn't working.
I noticed in dungeons and duels that I'm not getting that much crit behind this talent so I went to test it by mounting, flying then dismounting to get my hp to 35% or less then use word of glory. 
I did it 8 times in row only once I critted, my normal crit is 14.69% ( as holy paladin )
In duels, it was hardly critting even though my normal crit ( as a retri ) was 12% + 60% from this talent + 15 % from talent Rule of Law 
![Rule of Law](https://user-images.githubusercontent.com/57665529/69486970-8098ab80-0e6b-11ea-9f3f-2890c1bbd81b.png)

**What is happening:**
Last of Word isn't working as intended

**What should happen:**
Last word should increase the critical chance of word of glory on targets that 35% hp or below.

**Comment by Keader** [comment]
Fixed.
Yeap, was not working at all
