### ISSUE TITLE
[Talent] Protector of the Innocent - Paladin

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3978]
Spell ID: 20140
![image](https://user-images.githubusercontent.com/56992013/69487089-d2860500-0e5c-11ea-9e0b-3c313477fce5.png)

**What is happening:**

Healing any target other than yourself with a spell heals you. This affects all healing*, except healing over time.
This means that healing 6 other people with Light of Dawn (85222) will cause this talent to heal you 6 times.
Even worse, using Holy Radiance can proc this talent one time for every friendly character that is in range, potentially allowing you to pull some incredibly high self healing numbers in situations where raid members stack on top of each other.

What should happen:

Successfully casting any targeted paladin healing spell on a target other than yourself should proc the talent once, regardless of how many characters the spell heals.

Below is a list of targeted paladin healing spells in case it is needed:

Holy Light 635
Holy Shock 20473
Flash of Light 19750
Word of Glory 85673
Divine Light 82326
Holy Radiance 82327
Lay on Hands 633

*Not sure if the healing caused by beacon of light can proc this and I cannot find two other people to help me test at this moment.

**Comment by Keader** [comment]
Fixed, will proc only once now

**Comment by golosomie** [comment]
@Keader 
Multiple procs confirmed fixed on PTR.
Doesn't proc on Holy Shock though. Not sure if it should - gotta research that one.

**Comment by Echinaceax** [comment]
found some info on comments (only white comments so not sure)
https://www.wowhead.com/spell=94289/protector-of-the-innocent#comments

![image](https://user-images.githubusercontent.com/39439201/115579553-927fb780-a2c6-11eb-9341-a36d5b4391b5.png)


will look more when i have time before next update
