### ISSUE TITLE
[Quest] Just a drop in the Bucket - ID 27454

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#398]
Quest - https://www.wowhead.com/quest=27454/just-a-drop-in-the-bucket
NPC - https://www.wowhead.com/npc=11035
Put on the disguise but cannot had the quest in.
![world of warcraft 06_01_2019 12_02_04](https://user-images.githubusercontent.com/42302580/50735724-3a7f1e80-11ab-11e9-86ff-4cf56809eafc.png)
quest incompletable.

**Comment by sarahkay88** [comment]
my bad this quest auto completed its self so didn't actually need to use the cauldron.

**Comment by Echinaceax** [comment]
- Ah were as Horde quest was auto given when completed the other quest
Earlier quest - https://www.wowhead.com/quest=27453/catalysm

- than i got this quest 
Quest - https://www.wowhead.com/quest=27454/just-a-drop-in-the-bucket

- But horde cant complete coz of missing drop from #432
