### ISSUE TITLE
[Dungeon] Dire maul west door wont open

### ISSUE THREAD

**Issue by Szymo1337** [WoWManiaUK/Blackwing-Lair#3981]
**Links:**
https://classic.wowhead.com/dire-maul

**What is happening:**
We took quest from the npc near the entrance we did all objectives. We killed 3 of the bosses (everyone before the door) and the door wont open

**What should happen:**
We should be able to get past this door. We have the key even though the wiki says it is a trophy but we still cant unlock it

**Comment by Rushor** [comment]
okay warwood boss door open fixed. 

but the crystals need to be fixed aswell.

**Comment by Rushor** [comment]
okay all done. The door after the tree boss will be opened on kill. 

and the blue big circle door to NPC_IMMOLTHAR will be removed(opened) once all the big blue crystals are deactivated. You will be able to deactivate the crystals once the NPC_ARCANE_ABERRATION around them are killed.

![I](https://i.imgur.com/40bcx1z.jpg)
![I](https://i.imgur.com/Q1c0Loq.jpg)
![I](https://i.imgur.com/u5QFM2C.jpg)

**Comment by Rushor** [comment]
eh no pls do not close this. it will be closed once the fix is live on the server.
