### ISSUE TITLE
[Rare][Npc] Mysterious Camel Figurine - Phased event

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3982]
This wowhead guide https://www.wowhead.com/guides/grey-riding-camel-mount contains a LOT of information and statistics on this topic however I will add a breakdown here of information given from the guide of things to take note of:

There are two different camel figurines with differing NPC IDs, though they are identical in appearance. They will be referred to as "real" (NPC ID 50409) and "fake" (NPC ID 50410) figurines.
A real figurine will teleport you to Dormus' location upon clicking, while the fake will crumble and give you  Crumbled Statue Remnants (Item ID 67444).
There are 50 possible spawn points for Mysterious Camel Figurine scattered around Uldum.

Mysterious Camel Figurine (NPC ID 50409)  has 50 possible spawn points. Keep in mind that all of these spawn points are shared with the "fake" figurine, Mysterious Camel Figurine (NPC ID 50410).

There is a 5% chance for a "real" figurine to spawn, meaning that the remaining 95% of the time, the "fake" figurine will spawn.

The figurines share a 2-8 hour spawn timer. Whenever a fake figurine is clicked and looted, it will despawn within a few minutes. This will in turn reset the spawn timer, meaning that once you've clicked it, another figurine spawn 2-8 hours from then.

Spawnpoints: 
![2](https://user-images.githubusercontent.com/16594771/69498699-7de19900-0ef3-11ea-8501-e0629c9b27da.PNG)

In the guide provided I got this code for the spawn points:
/way Uldum 50.47 31.54
/way Uldum 52.23 28.04
/way Uldum 45.24 16.04
/way Uldum 34.32 19.63
/way Uldum 34.38 21.27
/way Uldum 33.68 25.38
/way Uldum 33.23 28.09
/way Uldum 29.90 24.90
/way Uldum 29.85 20.45
/way Uldum 31.96 45.29
/way Uldum 32.73 47.63
/way Uldum 25.40 51.07
/way Uldum 24.44 59.96
/way Uldum 22.09 64.06
/way Uldum 25.59 65.89
/way Uldum 26.27 65.09
/way Uldum 28.51 63.74
/way Uldum 30.61, 60.50
/way Uldum 30.42, 62.67
/way Uldum 30.99, 66.37
/way Uldum 30.98, 67.52
/way Uldum 31.50, 69.26
/way Uldum 33.21, 72.04
/way Uldum 33.27, 67.78
/way Uldum 33.20, 62.83
/way Uldum 33.08, 60.13
/way Uldum 37.13 64.08
/way Uldum 38.28 60.70
/way Uldum 38.49 54.93
/way Uldum 40.84 49.75
/way Uldum 39.97 45.00
/way Uldum 40.10 43.40
/way Uldum 40.16 38.41
/way Uldum 46.25 44.58
/way Uldum 48.17 46.40
/way Uldum 51.80 49.34
/way Uldum 51.03 50.80
/way Uldum 50.48 50.65
/way Uldum 51.47 51.16
/way Uldum 52.14 51.21
/way Uldum 51.92 70.81
/way Uldum 50.42 72.22
/way Uldum 50.24 73.67
/way Uldum 49.13 75.91
/way Uldum 47.28 76.69
/way Uldum 51.14 79.79
/way Uldum 73.44 73.61
/way Uldum 69.87 58.13
/way Uldum 72.02 43.88
/way Uldum 64.66 30.27

Not sure if that would help :)

When finding the real one:
When the player clicks on the "real" Mysterious Camel Figurine (NPC ID 50409) it will then cast https://www.wowhead.com/spell=93473/sandstorm on the player, this will teleport the player to location: Feralas 68.9, 73.3
After the player is teleported they will receive a debuff http://cata.cavernoftime.com/spell=93269 this debuff is what allows players to SEE the mob that drops the mount. With this buff, the player matches his phase.
Players should NOT be able to see this rare npc without this debuff granted from the sandstorm spell.

Dormus ID 50245: https://www.wowhead.com/npc=50245/dormus-the-camel-hoarder#drops
This mob has no abilities however does spawn in with a camel in his hand as per this aura spell http://cata.cavernoftime.com/spell=93237 not sure if its this, but I assume so.
Dormus drops the mount: https://www.wowhead.com/item=63046/reins-of-the-grey-riding-camel 100% of the time and grants the players the Feat of Strength achievement  https://www.wowhead.com/achievement=5767/scourer-of-the-eternal-sands#comments as well as the title https://www.wowhead.com/title=258/the-camel-hoarder 
According to the wowhead guide, the Feat of Strength achievement and title should be account wide but I was unable to confirm if this was a change made later on in wows life - I searched the web but could not find anything suggesting it.

**Comment by Rushor** [comment]
Also Mysterious Camel Figurine will be added with the next update which will contain an epic BOSS spawn of Dormus the Camel-Hoarder which will reward you the MOUNT [Reins of the Grey Riding Camel] and the Feat of Strength [Scourer of the Eternal Sands] https://i.imgur.com/6J7RxPv.png

https://i.imgur.com/euVYV4A.jpg
https://i.imgur.com/JHvLANu.jpg

You can find all you need to know about the spawn behaviour and the mechanics here https://www.wowhead.com/guides/grey-riding-camel-mount
