### ISSUE TITLE
[Dungeon] Dire maul north enemies are not atacking

### ISSUE THREAD

**Issue by Szymo1337** [WoWManiaUK/Blackwing-Lair#3983]
**Links:**
https://classic.wowhead.com/guides/dire-maul-north-tribute-run-classic-dungeon-strategy

**What is happening:**
First of all i think that the courtyard door does not require the key(im not sure about that one) What i am sure of is that every generic ogre(Not bosses) is not atacking nor can be atacked. They just stand around

**What should happen:*
They should atack ofcourse. I think that it is caused by the quest that lets you get a ogre disguise  but thats just an idea

**Comment by Rushor** [comment]
attackable now https://i.imgur.com/SlyeWyB.jpg
