### ISSUE TITLE
Aristaleon Sunweaver <Cloth Trader> - Twilight Highlands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3985]
**Links:**

https://www.wowhead.com/npc=50433/aristaleon-sunweaver

![Aristaleon Sunweaver2](https://user-images.githubusercontent.com/39439201/69562296-26a0fe80-0faf-11ea-9616-305a19d18d08.jpg)

**What is happening:**
- The npc is in the wall and you cant interact with it
- /target works to locate him, but cant open his trade window

**What should happen:**
_- He need repositioning so players can interact with him
infact all the crafting vendors should be inside the building not outside, coz the leatherworking is also not in correct location_

**Comment by Rushor** [comment]
removed wrong enemy spawns in front of the hut and added civil flags for them

**Comment by Echinaceax** [comment]
Main issues isnt fixed :)

- The npc is in the wall and you cant interact with it
- /target works to locate him, but cant open his trade window

**Comment by mfranca0009** [comment]
All set, including the leatherworking supplies vendors.

**Comment by golosomie** [comment]
@mfranca0009 Aristaleon Sunweaver's position seems good now. But Hortak Kenzo (Tailoring Supplies Vendor, NPC 50456) is now stuck in the wall.
![grafik](https://user-images.githubusercontent.com/51303221/107854856-10cf6180-6e1f-11eb-8a58-1969fb04d50a.png)

**Comment by mfranca0009** [comment]
@golosomie  I didn't have name plates on so never saw that NPC 😂 

Could you open a new report for that NPC and I will fix it shortly? 

Marking as fix confirmed, original issue resolved.
