### ISSUE TITLE
[Core] Vashjir portal - Sending people to wrong/Inconveniant location

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#3987]
https://www.youtube.com/watch?v=au62ckAWWe0

As shown in the video above, the portal is SUPPOSED to send players to the Silver tide hollow, where the Quartermaster for the Earthen Ring is located as shown here in this image:
![Pshhh](https://user-images.githubusercontent.com/16594771/69612535-87c0e480-1038-11ea-8470-9d001deae7ab.PNG)
At the moment it sends people to the BOTTOM of the ocean at this location in this image.
![example](https://user-images.githubusercontent.com/16594771/69612626-bfc82780-1038-11ea-82a9-1e1464441935.PNG)
The problems with this is it causes the players to have to spend a TON of time swimming to get to the surface in order to fly to whatever section they need to be. Because the seahorse mount quest is not available at the moment players are greatly inconvenianced when they need to go to vashjir for whatever reason like Rare hunting or Herbalism.

A lot of other servers make the location of the portal here at the Sandy Beach near 57.7. 19.0 Because it lets players mount up to fly to whatever section they need to be and its by the flightmasters :) I recommend either this or the blizzlike silver tide hollow - however it is ALSO deep under water and would cause the same problem.
![WoWScrnShot_112619_103919](https://user-images.githubusercontent.com/16594771/69612876-3e24c980-1039-11ea-88d1-a198ddd72685.jpg)

**Comment by sarahkay88** [comment]
This could be to do with the opening quests? Not sure they have been fixed yet

**Comment by sarahkay88** [comment]
https://eu.battle.net/forums/en/wow/topic/17612811254. Read through the comments

**Comment by Priestelar** [comment]
Yeah all the portals are currently usable before their quests are completed but that will still take a long time to be fixed especially since vashjir will most likely be the last cata zone to be fixed. I suggested this report as a temporary solution

**Comment by sarahkay88** [comment]
But you can fly To vash from sw to were u r suggesting to put the portol. No point in fixing something that will need changing later.

**Comment by Priestelar** [comment]
yes but thats why I said either there or silver tide hollow. Since the flightpath takes long as it flies you to ironforge first and only then to vashjir. The current location is wrong either way

**Comment by Priestelar** [comment]
And I don't think the horde even has a flightpath to there

**Comment by sarahkay88** [comment]
Tbh the bug is that the portol is active too soon, therefore rather than moving it, just deactivate it u till it's suppose to be active. Flight path takes all of five mins.

**Comment by Priestelar** [comment]
yes but they still wont have a flightpath from orgrimmar, theyd need to go to the eastern kingdoms first to even fly to that flight path is what i mean. 
That and if we disabled all the portals before the quests were available then NONE would be active yet since all of the starting quest lines are not working at the moment, only mount hyjal.

**Comment by sarahkay88** [comment]
How is that valid they don't have a undercity do they, its a different zone location

**Comment by sarahkay88** [comment]
https://wow.gamepedia.com/Vashj%27ir#How_to_get_to_Vashj.27ir
This how to get there for both fractions without portol.

**Comment by Rushor** [comment]
can you please summary what to fix now :)

**Comment by sarahkay88** [comment]
@Rushor he's asking you move the portol to a more convenient place, the portol shouldn't actually be active before the start chain is completed. Players can fly there so it's upto u, either move for convince or deactivate until fix

**Comment by Priestelar** [comment]
@sarahkay88 Im saying that it is not valid to say that a flightpath is an alternative, becuase the alliance has a flightpath because vashjir is in the eastern kingdoms. For the horde to make use of their flightpath to vashjir they must first take a zepplin to eastern kingdoms and then take an even longer flightpath than the alliance to get to vashjir. Thats why im saying that it is irrelevant to say the alliance can just use the flightpath instead of the portal. 
That doesnt change what this report is about, that the portal is currently sending players to an inconveniant location deep underwater where they need to spend several minutes swimming upwards.
Wether they unlock the portal with the quest chain or not doesn't matter, the problem is still that the portal is sending them to a wrong and inconveniant location. 

Disabling the portals till their quest chains are completed is not an option yet since players cannot complete all the quest chains for the Cataclysm zones for example: the starting quest chain in Stormwind to get to twilight highlands is not doable thus their portal would never unlock.

**Comment by Priestelar** [comment]
> https://wow.gamepedia.com/Vashj%27ir#How_to_get_to_Vashj.27ir
> This how to get there for both fractions without portol.

Players can fly there yes but it is a very timeconsuming and inconveniant process.  as per the link you provided it is unreasonable to say players can fly there.
Here is a quote from the post you linked: Players will fly over the fatigue waters between the continents and it will take 280% flying skill to reach Vashj'ir before dying to fatigue.
Only long time players even have 280% flying unlocked therefore it doesnt count as an alternative way to reach the zone yet. 
This report is about the location of where the portal sends you. Not the attunement quest to unlock the portal or the alternatives to reach the location.

**Comment by sarahkay88** [comment]
How is it not valid, if an horde was in dalaran they couldn't just fly to vash they would still have to go to ogrimmar (if portol was working) or undercity like other players, moving the portol to were u want only makes it convinent and isn't how its suppose to be. Once the zone is fixed it would then need removing. Pure laziness, but I summarised what u asked for rushor so he can decide at this point we r just flooding the threat. The bug lies with the portol being in the wrong stone because its active to soon and the start quest cannot be completed.

**Comment by Priestelar** [comment]
Its not about moving it to where I want. I specifically listed the blizzlike location of where the portal must take you and mentioned what the location is that other servers use. It has nothing to do with laziness or what I want. I mentioned the bug of the portal sending you to the wrong location and that is what this entire thread is about. Nothing about what I want, me being lazy or how to unlock the portals. The fact remains that the portals are currently open and that they send people to the wrong location.
There is no removing needed to be done just changing the teleport location.
This is why I gave rushor 2 options so that he can decide which he wants

**Comment by sarahkay88** [comment]
The portol location moves as you unlock the zone...😂 😂

**Comment by Echinaceax** [comment]
I have read whats been said here, 
And though its inconvieniant for "some" atm we all know that all zones will be fix in due time, 

I do however agree with Sarahkey88 "why change something that will have to be changed again later" our coders have other more prios to fix atm, if players have completed the chainquest as required then its easy to get around Vashj with the seahorse. the bg command was added to help players, this should be suffisant for now IMO

> That doesnt change what this report is about, that the portal is currently sending players to an inconveniant location

As for Horde getting there via Undercity they "can" use their Mallstone to access Undercity quicker.

@Rushor IMO there is nothing to fix here atm, as its not gamebreaking. i would focus on other importand fixes.

**Comment by Priestelar** [comment]
@Echinaceax I did not know that the BQ works on the seahorse quests, meaning that players can then get access to the mount since I just used it to get it, that changes the purpose of this report. it can be closed as it doesnt matter then.
