### ISSUE TITLE
[Class/Mage] Fire - Improved Hot Streak

### ISSUE THREAD

**Issue by Batraneluu** [WoWManiaUK/Blackwing-Lair#3988]
**Links:**

from WoWHead or our Armory
http://cata.cavernoftime.com/spell=44446
**What is happening:**
If you cast pyroblast and get the Hot Streak buff, when the pyroblast lands on the target you also lose your Hot Streak buff.

**What should happen:**
You should be able to use your Hot Streak even after your pyroblast landed.

Replicate:
After 1 critical , cast fireball then rapidly after pyroblast , if your fireballs crits you get your Hot Streak and after your pyroblast lands you will lose your Hot Streak.

**Comment by Ovahlord** [comment]
Hold on a second

> Description: Your Fire spells no longer trigger Arcane Missiles.  Instead, any time you score 2 non-periodic critical strikes in a row with your Fireball, Frostfire Bolt, Scorch, or Pyroblast spells, you have a chance the next Pyroblast spell cast within $48108d will be instant cast.

If you read the description you see, that it's suposed to only count for the very next Pyroblast cast. It's actually not even meant to remain active until the spell has hit the target but instead the buff should get consumed after the cast already. 
The Improved Hot Streak talent does not change this. It's only changes the proc conditions but the buff removal is intentional and correct.

**Comment by Rushor** [comment]
Thank you @Ovahlord I remember that in wotlk aswell :o

**Comment by questbugreporter** [comment]
>  It's actually not even meant to remain active until the spell has hit the target but instead the buff should get consumed after the cast already.

@Ovahlord That is literally what the poster is saying.
@Rushor Please reopen this.

**Comment by Rushor** [comment]
So what? Hot Streak get's removed after pyroblast landed. 

what should be fixed then?

**Comment by questbugreporter** [comment]
Should be removed on cast instead of on hit.

**Comment by questbugreporter** [comment]
To be more accurate, it should be removed when you instantly cast Pyroblast by using the Hot Streak, not if you finish casting a non-instant one.

**Comment by Ovahlord** [comment]
That shouldn't be a problem to handle, because the instant one has a completely different spell id.
