### ISSUE TITLE
[Item] Haunted War Drum

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3989]
**Links:**
Profession: Archaeology
https://www.wowhead.com/item=69777/haunted-war-drum

**What is happening:**
- doesnt play any music 

**What should happen:**
 _Place and listen to a Haunted War Drum._

**Comment by jburkiett** [comment]
Done when fix applied

**Comment by Rushor** [comment]
some correction made - works all fine now
