### ISSUE TITLE
[Quest/Item] Dark Heart/Horn of Hatetalon - ID 25340/9530 - Feralas

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#399]
Quest - https://www.wowhead.com/quest=25340/dark-heart
Quest item - https://www.wowhead.com/item=9528
Video - https://www.wowhead.com/quest=25340/dark-heart#videos:id=67372

- Quest item not working
- Cant be completed = need to summon her 

![not working](https://user-images.githubusercontent.com/39439201/50735729-a9607580-11b3-11e9-9d5b-7213dd7aeaf7.jpg)

![image2](https://user-images.githubusercontent.com/39439201/50735738-d6148d00-11b3-11e9-96be-407c611854e0.jpg)

**Comment by glcabatuan** [comment]
**Quest:** http://cata.cavernoftime.com/quest=25340
**NPC/s:** http://cata.cavernoftime.com/npc=8075
**Item/s:**  http://cata.cavernoftime.com/item=9530
**Object/s:** http://cata.cavernoftime.com/object=207949
**Spell/s:** http://cata.cavernoftime.com/spell=11840

**Current State:** 
Even if the character is in the center of the http://cata.cavernoftime.com/object=207949 and use the
http://cata.cavernoftime.com/item=9530 to cast http://cata.cavernoftime.com/spell=11840   , 
http://cata.cavernoftime.com/npc=8075 won't show up.


**Expected State:** 
http://cata.cavernoftime.com/npc=8075 should show up once the http://cata.cavernoftime.com/item=9530 has been triggered.

As shown here: https://youtu.be/tYsywrcNhGQ?t=67

**Comment by Rushor** [comment]
fixed https://i.imgur.com/0n0vosZ.jpg
