### ISSUE TITLE
{Quest} Conversing with the depths - Dragonblight

### ISSUE THREAD

**Issue by Kuro2004** [WoWManiaUK/Blackwing-Lair#3990]
While I was doing the quest: **Conversing with the depths** I stood around too long and missed the chance to jump in the water.
After the quest failed, I abandoned and re acquired the quest I could not interact with the pearl again.
Tried abandon and re acquire multiple times, even jumping into the water. Tried .bq 12032 and nothing worked.

**Comment by Rushor** [comment]
http://cata.cavernoftime.com/quest=12032

**Comment by Rushor** [comment]
object will now reset again properly after 1.5 minutes.
