### ISSUE TITLE
[Item] Gnomish X-Ray Scope missing ICD

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3991]
https://www.wowhead.com/item=59594
The buff granted by the scope has a 100% uptime for hunters. Wowhead comments claim that there is an internal cooldown.
I didn't test this myself, might be invalid.

**Comment by Rushor** [comment]
By mass13 (197 –  2)  on 2010/12/12 (Patch 4.0.3) |   |  
-- | -- | --


did some testing with it..the proc is every 1m more or less..sometimes procced after 1m 20secs..some others after 45-50secs..

https://www.wowhead.com/item=59594/gnomish-x-ray-scope#comments:id=1225866

yes has no cooldown currently will fix that.

**Comment by Rushor** [comment]
added the 45 sec cd to it.
