### ISSUE TITLE
[Guild] Rank problem

### ISSUE THREAD

**Issue by Chicozoba** [WoWManiaUK/Blackwing-Lair#3992]
**What is happening:**

Ranks where modified in my guild and it f*cked up everything, change the ranks to all members/officers. The rank assigned by the guild master are different that the rank promotion the member actually receive. And now, i don't have permissions on the guild bank as guild master (can't see the tabs, deposite or withdraw items)
**What should happen:**

The correct rank should be assigned, and guild master is supposed to have all the rights for the guild bank.

**Comment by Chicozoba** [comment]
Update about the bug : Changing the rank make the members disappear in the list

![image](https://user-images.githubusercontent.com/50930065/70000322-195db400-155b-11ea-8b20-d0fe7cac85ec.png)
 The blanks on top of the list are members

**Comment by Kitzunu** [comment]
Is this still an issue after https://github.com/WoWManiaUK/Blackwing-Lair/issues/4097 ?

**Comment by Echinaceax** [comment]
Hmm, havent checked since #4097
can later tho @Kitzunu i can ask one of my guildies to login to test

**Comment by Echinaceax** [comment]
@Kitzunu feed back from "renewed Hope" guild 

> So far ive noticed the ranks, got reseted. When my guild was formed, ive been also making Individual ranks with different permissions. So thats definitly NOT working as it should. 
> **_Empty Guild Vault appeared also but that seems to be only a visual issue, the items themself didnt vanished away but it looked like that Guild vault is empty.. so when i moved one item to another place from that one Guild Tab all items appeared again, whats Kinda weird._**
> Also the Acitivty list from the players (See offline members) seemed buggy, there are spaces between names and i do blelieve that are characters which are already deleted.
> Some players also who got rights to do something  cannot do it

**Comment by Kitzunu** [comment]
That has nothing to do with this open issue at hand.

And as he said, that is a visual issue, which I would believe is Client. But do not quote me on that, could also be that it is the server not updating it correctly. I have no idea

**Comment by Echinaceax** [comment]
@Kitzunu this is the full info tested by the guild (i just didnt quote all lol)

> So far ive noticed the ranks, got reseted. When my guild was formed, ive been also making Individual ranks with different permissions. So thats definitly NOT working as it should. 
> Empty Guild Vault appeared also but that seems to be only a visual issue, the items themself didnt vanished away but it looked like that Guild vault is empty.. so when i moved one item to another place from that one Guild Tab all items appeared again, whats Kinda weird.
> Also the Acitivty list from the players (See offline members) seemed buggy, there are spaces between names and i do blelieve that are characters which are already deleted.
> Some players also who got rights to do something  cannot do it

**Comment by Chicozoba** [comment]
@Kitzunu Promoting and deranking seems to work now, they don't disapear. But I still can't see the characters that disapeared before the fix in the list.

**Comment by Chicozoba** [comment]
Another update, promoting and demoting does seem to work. We managed to make players reappear in the list but the GM has no control on the ranks (lower or raise ranks).

**Comment by MzMalice** [comment]
I'm having a similar issue. As Guild Master I can still get into the guild vault, however none of my members are able to. Having the same issue as some members aren't on the roster and making new ranks aren't working. Now I can't buy another guild vault tab even though I had over 500 gold in the bank (I was attempting to buy the 3rd tab).

**Comment by Echinaceax** [comment]
moved to here #3150
