### ISSUE TITLE
[NPC] Skymistress Gloaming <Dragonhawk Master> fast travel from silvermoon city to Booty Bay, Stranglethorn doesn't work.

### ISSUE THREAD

**Issue by fyllex2** [WoWManiaUK/Blackwing-Lair#3994]
Links:

https://www.youtube.com/watch?v=cuC4q6duoZ4&feature=youtu.be

What is happening:

During fast travel from silvermoon city to Booty Bay, Stranglethorn I got teleported back to silvermoon city inn keeper still mounted. The mount kept going, now flying into textures and leaving the map at some point. After some time you get dismounted outside of playable map and fall to death.

What should happen:

You shouldn't supoused to be teleported mid flight.

**Comment by Kitzunu** [comment]
not possible to watch the video, and please use the template for future reports.

**Comment by Rushor** [comment]
similar issue here https://github.com/TrinityCore/TrinityCore/issues/17082

i guess your client is wrong. try to download fresh from the website (or ask in discord how to do it)

anyway works on my side

![I](https://i.imgur.com/GRBOxkF.jpg)
![I](https://i.imgur.com/6nJ6Vbz.jpg)
![I](https://i.imgur.com/cmhZhBy.jpg)

**Comment by Nacho-k** [comment]
i know why this happens, the games teleports you to your hearthstone location if you enter a cataclysm zone when youre not high enough level.

**Comment by Rushor** [comment]
good catch! your level needs to be higher then. try to use the teleporter in the mage quater of silvermoon city
