### ISSUE TITLE
Baradin Hold "Door´s Not Open"

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3996]
**Links:**

from WoWHead or our Armory
https://imgur.com/a/JQgGvlX
**What is happening:**

After removing the timer on Baradin hold door´s dont seem to open so we cant do the raid unless we get one from opposite faction to kill everyone at door and hope that someone can summon people xD

**What should happen:**

**Comment by Rushor** [comment]
alsways open now asl long as battle is not fully enabled yet https://i.imgur.com/6rjP7Yu.jpg

will try to push the update faster this wekk again.

**Comment by Echinaceax** [comment]
@rushor did this go live ?
Coz yesterday the door was still closed (no battle timer now remember you disabiled it)

workaround was that player from group left raid to kill us all and then we could enter via the death spirit

**Comment by sarahkay88** [comment]
#4029
