### ISSUE TITLE
[Achievement] Pilgrim's Peril - Pilgrim's Bounty

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3997]
**Links:**
https://www.wowhead.com/achievement=3581/pilgrims-peril
https://wow.gamepedia.com/Pilgrim%27s_Peril_(Alliance)

![peril](https://user-images.githubusercontent.com/39439201/69755232-11b39f00-1158-11ea-8e38-e78214230d94.jpg)

**What is happening:**
- Eating at the table doesnt give credit

**What should happen:**
_While wearing either a Pilgrim's Dress, Robe, or Attire, take a seat at each enemy capital's Bountiful Table._

**Comment by Rushor** [comment]
okay i cannot find a solution to this - could we forceadd the achiev once the player enters the vehicle/chair 

there is simply no way the vehicle recognises the player in undercity

**Comment by Rushor** [comment]
@Echinaceax

**Comment by Echinaceax** [comment]
@Rushor not sure because the tables are in the correct place as seen via SS links for UC
The event is only on a few more days so maybe you'll have too add it

**Comment by Rushor** [comment]
boom! fixed https://i.imgur.com/Yfswezr.jpg

i hope as hotfix. will tlak wih jani.
