### ISSUE TITLE
[NPC] Alnar whitebough - Pilgrim's Bounty

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3998]
**Links:**

https://wotlk.evowow.com/?npc=34785

![Alnar whitebough](https://user-images.githubusercontent.com/39439201/69755640-eda48d80-1158-11ea-9366-46c892454d18.jpg)

**What is happening:**
- inactive

**What should happen:**
_need for cooking for lvls while in that zone_

**Comment by Rushor** [comment]
added https://i.imgur.com/Gd2JKB2.jpg
