### ISSUE TITLE
[Daily][Quest][Fishing] No Dumping Allowed (26556) Not Working

### ISSUE THREAD

**Issue by Velara** [WoWManiaUK/Blackwing-Lair#3999]
**Links:**

Quest ID: https://www.wowhead.com/quest=26556/no-dumping-allowed
Objective quest item that can't be caught: https://www.wowhead.com/item=58945/toxic-puddlefish

**What is happening:**

The quest item (fish) can't be caught while on the daily. It should be a reasonable drop rate while fishing (around 16%) but at over 20 catches with nothing, it appears to be bugged like all the others have been (many have been fixed as they are reported though).

**What should happen:**

You should be able to catch the item while on the daily quest.

**Comment by Rushor** [comment]
added. if you find more bugged dailies, pls let us know and create a report. thanks.
