### ISSUE TITLE
[Quest/Item] Sealing the dream - ID 25250 - Feralas

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#400]
Quest - https://www.wowhead.com/quest=25250/sealing-the-dream
Quest item - https://www.wowhead.com/item=52576/ysondres-tear

- Item not working
- Cant complete = need to seal the portal

![no seal](https://user-images.githubusercontent.com/39439201/50736118-71f4c780-11b9-11e9-8f78-c4c6e4c65317.jpg)

**Comment by glcabatuan** [comment]
**Quest:** http://cata.cavernoftime.com/quest=25398
**NPC/s:** http://cata.cavernoftime.com/npc=39834
**Item/s:** http://cata.cavernoftime.com/item=52576
**Object/s:** 
**Spell/s:** http://cata.cavernoftime.com/spell=74409

**Current State:** 
The http://cata.cavernoftime.com/npc=39834 don't react once the http://cata.cavernoftime.com/spell=74409 of the http://cata.cavernoftime.com/item=52576 is casted.


**Expected State:** 
The http://cata.cavernoftime.com/spell=74409 should seal the http://cata.cavernoftime.com/npc=39834

As shown in the video: https://youtu.be/JzTlJKC5ROY?t=95
