### ISSUE TITLE
[Event][Achievement] Pilgrim's Paunch not Awarding Credit at Undercity (Horde)

### ISSUE THREAD

**Issue by Velara** [WoWManiaUK/Blackwing-Lair#4000]
**Links:**

Achievement: https://www.wowhead.com/achievement=3557/pilgrims-paunch
Buff: https://www.wowhead.com/spell=61849/the-spirit-of-sharing

**What is happening:**

Unable to get credit for acquiring the Spirit of Sharing buff at Undercity, and therefore can't get Pilgrim's Paunch achievement. You can get the buff just fine like at the other major cities, however, Undercity is not giving credit. Perhaps because it's technically inside a different zone, Ruins of Lordaeron?

**What should happen:**

Acquiring the Spirit of Sharing buff from the tables inside the Ruins of Lordaeron should award Undercity credit for the Pilgrim's Paunch achievement for the Horde.

**Comment by Rushor** [comment]
yes that zone breaks some achievemts i guess

**Comment by Rushor** [comment]
boom ! fixed with next update https://i.imgur.com/w8B2trC.jpg

maybe hotfix

**Comment by Nacho-k** [comment]
The event ends the first, so please a hotfix lol

**Comment by Velara** [comment]
Yes a quick fix on this would be appreciated by everyone that is interested in achievements (most I guess), since the event is once-a-year and ends in few days :)
