### ISSUE TITLE
[Daily][Fishing] Fish Head (29317) Unable to Fish Up Item

### ISSUE THREAD

**Issue by Velara** [WoWManiaUK/Blackwing-Lair#4001]
**Links:**

Quest: https://www.wowhead.com/quest=29317/fish-head
Objective Item: https://www.wowhead.com/item=69901/severed-abomination-head

**What is happening:**

You cannot obtain the quest item while on the daily, like many of the other fishing daily quests that have been reported.

**What should happen:**

You should be able to fish up the quest item while on the quest. The drop rate should be around 5-10%.

**Comment by Rushor** [comment]
Will fix now

**Comment by Rushor** [comment]
done
