### ISSUE TITLE
Dungeon Finder - "Random Hour of Twilight Heroic" option

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#4002]
![image](https://user-images.githubusercontent.com/56992013/69770348-5871bb00-1191-11ea-9a8e-e15bbe0a4cb6.png)

This option should be removed until that content becomes available, just like the "Random Rise of the Zandalari Heroic" option.
This becomes very annoying after your character reaches 353 ilvl as it becomes the default option.
A low priority issue in my opinion, but still an issue.

**Comment by Kitzunu** [comment]
I have removed it from lfg, will send to dev later today

**Comment by Kitzunu** [comment]
For reference: this is supposed to be released patch 4.3.0

**Comment by Kitzunu** [comment]
I can't fix it, doesn't seem to be DB related

**Comment by Rushor** [comment]
can you remove the changed you did then aka revert @Kitzunu

**Comment by Rushor** [comment]
isn't this dbc related?

**Comment by Kitzunu** [comment]
Already did

**Comment by Rushor** [comment]
can you take a look @Keader ? :o

**Comment by wow-mania** [comment]
duplicate

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/70646583-818d5380-1c47-11ea-8b88-4826f8bf4f1d.png)

So thanks to Priestelar that gave me the idea to up the ilvl requirement :)
So now this option will be of no trouble for anyone.

Not to self:
When this patch comes, the ilvl requirement should be **353**
