### ISSUE TITLE
[Core][Vendors] Items Sold by Default as Multiples Charges You Incorrectly

### ISSUE THREAD

**Issue by Velara** [WoWManiaUK/Blackwing-Lair#4003]
**Links:**

N/A

**What is happening:**

When you buy items from vendors that are sold as multiples, for example, a 5-stack of Autumnal Herbs from the Pilgrim's Bounty vendors, you should be charged the listed amount for that entire 5-stack. Instead, you are charged that price for EACH item incorrectly. In that example, you are being charged 5 times as much as you should be.

I saw someone mention this bug on the forum the other day (they mentioned milk but it seems to be all items that are sold as multiples) so here it is posted in the tracker so it can hopefully be fixed.

**What should happen:**

Items that are sold as multiples by default should be charged the listed price for that default stack; not per item. For example, going back to our Autumnal Herbs example, buying out the listed 5-stack (one right-click) should cost 9 copper; instead, it costs 45 copper because it's charging you the 5-stack price for each individual item.

**Comment by Rushor** [comment]
Fixed by TC Help.

The price matches to the amount now correctly :) thank you @Kitzunu
