### ISSUE TITLE
Forgemaster throngus cannot be disarmed

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#4005]
https://www.wowhead.com/npc=40177/forgemaster-throngus#comments

Forgemaster throngus cannot be disarmed. Tested with rogue spell dismantle (51722). Warriors have told me it doesn't work for them either.

Wowhead comments confirm that it should work against his dual blades phase.
I used dismantle against him successfully countless times during 4.0.x in 2010-11.

**Comment by Kitzunu** [comment]
fixed
