### ISSUE TITLE
[Event] Winter Veil - alliance test

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#4006]
**unable to test pvp achievements 

**Links:**

1) https://classic.wowhead.com/quest=7063/the-feast-of-winter-veil quest auto completes - players should first read the book in their inventory before quest completes - (minor issue)

2) cant complete quest https://classic.wowhead.com/quest=7043/youre-a-mean-one - Abominable Greench, didn't spawn https://www.wowhead.com/npc=54499/the-abominable-greench and needs adding to the game. also prevent players from collecting this achievement https://www.wowhead.com/achievement=273/on-metzen#comments

3) npc https://classic.wowhead.com/npc=15664/metzen-the-reindeer needs adding for the above reason aswell

4) https://classic.wowhead.com/spell=26157/px-238-winter-wondervolt - transform players into a gnome elf green or red suit
 A) A off Patch 3.3.0 (08-Dec-2009): Alliance players will now always have red outfits, and Horde players will now always have green outfits.) - https://wowwiki.fandom.com/wiki/PX-238_Winter_Wondervolt - my ally toon is getting both coloured outfits
b) sexing is wrong it made my female a male (minor issue again) - dalaran, shattrah  and exodar only - others turn me into a female. ***this maybe because they turning me into a gnome with a green outfit rather than red.**

5) https://classic.wowhead.com/spell=26157/px-238-winter-wondervolt in tanaris is inactive - should do as above

6) quest https://classic.wowhead.com/quest=7045/a-smokywood-pastures-thank-you can not be obtained due to issue 2 and prevents players from getting this achievement https://www.wowhead.com/achievement=279/simply-abominable

all presents r missing:
1) https://classic.wowhead.com/quest=8767/a-gently-shaken-gift#comments
2) https://classic.wowhead.com/quest=8803/a-festive-gift
3) https://www.wowhead.com/quest=13203/a-winter-veil-gift
4) https://classic.wowhead.com/quest=8744/a-carefully-wrapped-present
5)https://classic.wowhead.com/item=21310/gaily-wrapped-present 

**achievements**

1) https://www.wowhead.com/achievement=1255/scrooge - snowball isn't registered cant get achievement - same for horde
2https://www.wowhead.com/achievement=4437/bb-king - u can shoot them but doesn't register for achievement

**Comment by Rushor** [comment]
@sarahkay88 can you do the horde report aswell this week? :>

**Comment by sarahkay88** [comment]
I will try but atm we have the sickness bug in the house

**Comment by Rushor** [comment]
okay will cast /Greater Heal on all of you :>

**Comment by Echinaceax** [comment]
> @sarahkay88 can you do the horde report aswell this week? :>

horde one here @Rushor #4041

**Comment by Rushor** [comment]
https://classic.wowhead.com/quest=7063/the-feast-of-winter-veil quest auto completes - players should first read the book in their inventory before quest completes - (minor issue)

> cannot be fixed

**Comment by Rushor** [comment]
remember: https://github.com/TrinityCore/TrinityCore/search?utf8=%E2%9C%93&q=PX-238+Winter+Wondervolt&type=

**Comment by Rushor** [comment]
tanaris transform and gender transform selection fixed https://i.imgur.com/KFHrMOg.jpg

**Comment by Rushor** [comment]
scrooge fixed https://i.imgur.com/Vx6j0xL.jpg

**Comment by Rushor** [comment]
presents adde https://i.imgur.com/kyLWQb7.jpg

**Comment by Rushor** [comment]
okay everything done now except the https://www.wowhead.com/npc=54499/the-abominable-greench

will fix this later in a new issue today..

**Comment by Rushor** [comment]
![I](https://i.imgur.com/3ijqGrP.jpg added now.
