### ISSUE TITLE
[Item] Sealed Crates are empty

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#4007]
https://www.wowhead.com/item=67597/sealed-crate#contains
http://cata.cavernoftime.com/item=67597#contains

Note: this is a different item than the one in https://github.com/WoWManiaUK/Blackwing-Lair/issues/3829

**Comment by Rushor** [comment]
okay, blizz again :D

**Comment by Rushor** [comment]
will always contain sth now

![I](https://i.imgur.com/b51c5uG.jpg)
