### ISSUE TITLE
"dungeon Finder" timer bug or something

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#4009]
**Links:**

from WoWHead or our Armory

**What is happening:**

https://imgur.com/a/wKs2EsU 
The photo above is taking after being offline doing some other stuff so i wasnt even online during these 3 hours. 

I woke up the day after and it looks like this. So the timer keeps going even tho i wasnt even in que before logging out 
https://imgur.com/a/z8PT99Y

I have been unaura by GM i even deleted my cashe.

**What should happen:**

**Comment by Rushor** [comment]
moved to https://github.com/WoWManiaUK/Blackwing-Lair/issues/4011
