### ISSUE TITLE
[Item] Bag of Shiny Things 

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Blackwing-Lair#4012]
http://cata.cavernoftime.com/item=67414

does not contain always sth.

**Comment by Rushor** [comment]
added those items https://www.wowhead.com/item=67414/bag-of-shiny-things#contains

with ref table and adjusted percentage.

**Comment by Velara** [comment]
I was going to report this but it seems you beat me to it 👍 
Note that a lot of the items from the various categories can be awarded simultaneously if you're lucky enough. For example, you could get a fishing hat and a recipe at once. I believe you always get a grey item regardless, from one of the many available, in addition to whatever else rolls.
From what I recall the fishing rods are pretty rare, somewhere in the 0.5% rarity.

**Comment by Rushor** [comment]
ye, i added two ref tables for that
5 percent drop to get one of the grey items
and 100 percent drop to get 3 of the normal items + (0.5 - 1 percent chance to get one of those epic items like the hat etc.)
