### ISSUE TITLE
[Fishing] Algaefin Rockfish Schools

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#4013]
From 4.3 hotfixes: https://worldofwarcraft.com/en-us/news/4023884/patch-4-3-hotfixes

Algaefin Rockfish no longer swim in schools, and schools of Deepsea Sagefish have taken their place along many coastlines.

I can still find these schools on reign, one example is at 68.8, 59.1 in twilight highlands.

**Comment by Rushor** [comment]
but we are not on that patch. it will be added once we are technically in patch 4.3.

if there is more we ne to adjust let us now.
