### ISSUE TITLE
[Quest][Object] A Little Dash of Seasoning (9275) - Missing Objective Object and Quest Log Entry

### ISSUE THREAD

**Issue by Velara** [WoWManiaUK/Blackwing-Lair#4014]
**Links:**

Quest: https://www.wowhead.com/quest=9275/a-little-dash-of-seasoning
Missing objective object: https://www.wowhead.com/object=181251/smoked-meat-rack

**What is happening:**

There is a missing quest objective for this quest at location (63, 75) approx in Ghostlands. It looks like a different object is in its place.
Also, the objective is missing from the quest log and thus you cannot complete the quest.
Additionally, you can interact with completed objective objects again and consume a charge of the poison you are given.

**What should happen:**

There should be a Smoked Meat Rack object at this location and it should be in the quest log too as one of the 3 objectives necessary to complete the quest.
Additionally, once you have interacted with and consumed a charge of the poison you are given, you should no longer be able to interact with the same object again.

**Comment by Rushor** [comment]
no it could not be fixed better for now. 

see https://github.com/WoWManiaUK/Blackwing-Lair/issues/766

**Comment by Velara** [comment]
Ah I see. Sorry I didn't see that there had already been an issue on this. I think I was taking notes on reporting a number of issues at the time and forgot to double-check this one in advance :(
