### ISSUE TITLE
[NPC]  Crystalweb Cavern/Storm Peaks.

### ISSUE THREAD

**Issue by Nexenwon** [WoWManiaUK/Blackwing-Lair#4017]
**Links:**
https://wow.gamepedia.com/Injured_Goblin_Miner

from WoWHead or our Armory

**What is happening:**
There is 2 npc with same name. They give same quests.
![Untitled](https://user-images.githubusercontent.com/58032108/69892928-3c922480-130b-11ea-9200-dbeac8e16333.png)
**What should happen:**
There whould be only one npc there.

**Comment by sarahkay88** [comment]
#220 fix done for a different reason and at this time there was only one of these npcs.

**Comment by Rushor** [comment]
hmm nope, there should be serveral, all should have individual waypoints. will fix that <3

**Comment by Rushor** [comment]
individual path points and everything added

![I](https://i.imgur.com/exJkX6l.png)
![I](https://i.imgur.com/exJkX6l.png)
