### ISSUE TITLE
[Daily][Fishing] A Furious Catch (26588)

### ISSUE THREAD

**Issue by Velara** [WoWManiaUK/Blackwing-Lair#4019]
**Links:**

Quest: https://www.wowhead.com/quest=26588/a-furious-catch
Fish: https://www.wowhead.com/item=58951/giant-furious-pike

**What is happening:**

Cannot catch the fish (Giant Furious Pike) while on the daily, despite 50+ attempts, including 5 "bugged" bobbers that could not be looted - presumably those were instances where the fish was caught but it was unlootable because it's not implemented correctly.

**What should happen:**

You should be able to loot the fish while fishing when on the daily. The catch rate at the Southfury River should be around 10%.

**Comment by Rushor** [comment]
@Velara can you pls list me ALL fishing dailies. i think it's better to fix the all at once. it's actually fast done within 3 minutes. so..

**Comment by Velara** [comment]
**Horde**
Orgrimmar:
Clammy Hands (26543) [Works]
No Dumping Allowed (26556) [Broken but Reported as Fixed in Dev on Closed Issue #3999]
A Staggering Effort (26557) [Works]
A Furious Catch (26588) [Broken - Reported Issue #4019]
A Golden Opportunity (26572) [Works based on Closed Issue #1765]

Thunder Bluff:
Pond Predators (29345) [Works based on Closed Issue #2065]
The Ring's The Thing (29346) [Works]
The Race To Restock (29348) [Works based on Closed Issue #3798]
Craving Crayfish (29349) [Works]
Shiny Baubles (29354) [Works]

Undercity:
Fish Head (29317) [Broken but Reported as Fixed in Dev on Issue #4001]
Tadpole Terror (29319) [Unsure but based on Closed Issue #1014 I think it's working]
Like Pike? (29320) [Works]
Time For Slime (29322) [Works]
Moat Monster! (29361) [Works]

**Alliance**
I'm not playing Alliance so haven't tested anything here personally. If someone from Alliance side could comment here that would be great. The name of the dailies can be found from the achievements:

Fish or Cut Bait: Darnassus
Fish or Cut Bait: Stormwind
Fish or Cut Bait: Ironforge

A quick skim of the issues seems like a number of them have been reported and fixed already, which is nice.

**Comment by Rushor** [comment]
oh perfect thank you very much

**Comment by Rushor** [comment]
okay horde fixed:

alli list is:

http://cata.cavernoftime.com/quest=29321
http://cata.cavernoftime.com/quest=26414
http://cata.cavernoftime.com/quest=26420
http://cata.cavernoftime.com/quest=26442
http://cata.cavernoftime.com/quest=26488
http://cata.cavernoftime.com/quest=26536
http://cata.cavernoftime.com/quest=29323
http://cata.cavernoftime.com/quest=29324
http://cata.cavernoftime.com/quest=29325
http://cata.cavernoftime.com/quest=29342
http://cata.cavernoftime.com/quest=29343
http://cata.cavernoftime.com/quest=29344
http://cata.cavernoftime.com/quest=29347
http://cata.cavernoftime.com/quest=29350
http://cata.cavernoftime.com/quest=29359

**Comment by Rushor** [comment]
oka all tested and fixed so far even alli.

only this is http://cata.cavernoftime.com/quest=29350 is that quest working?

**Comment by Echinaceax** [comment]
@Rushor - yes works on dev 
> only this is http://cata.cavernoftime.com/quest=29350 is that quest working?

![on dev working](https://user-images.githubusercontent.com/39439201/69919886-0c20c680-1482-11ea-807f-07b0ed533da6.jpg)

**Comment by Velara** [comment]
For what it's worth, I still wasn't able to catch it at the area directly outside of Orgrimmar's west gate (Northern Barrens - Southfury River) after another 50 or so catches. But the minute I step south a bit into Durotar's Southfury River, caught it within a few casts. Was this added to the drop table for only Durotar's Southfury River zone or was I just really (REALLY) unlucky? :)

**Comment by Echinaceax** [comment]
@Velara my test was from Ally anf Ironforge 

who is the quest giver for horde?

**Comment by Velara** [comment]
It seems Tadpole Terror isn't working. Tried for quite some time at the pond in various locations around it. Not a single catch. And the drop rate is meant to be quite high - and you need 8.

Tadpole Terror (ID 29319)

I thought these were all meant to have been fixed by now :(

I can make a separate issue if you want but I figured since you already asked for the daily list here, and it seems it's just this one straggler, I'd simply comment it here and hopefully you can squeeze it in with the next update.

**Comment by Echinaceax** [comment]
@Rushor Ally does work

**Comment by Echinaceax** [comment]
> It seems Tadpole Terror isn't working. Tried for quite some time at the pond in various locations around it. Not a single catch. And the drop rate is meant to be quite high - and you need 8.
> 
> Tadpole Terror (ID 29319)
> 
> I thought these were all meant to have been fixed by now :(
> 
> I can make a separate issue if you want but I figured since you already asked for the daily list here, and it seems it's just this one straggler, I'd simply comment it here and hopefully you can squeeze it in with the next update.

reported here #4563

**Comment by Echinaceax** [comment]
confirmed fixed 

![image](https://user-images.githubusercontent.com/39439201/119269026-e1867880-bbf5-11eb-86e1-c4a216f3c294.png)
