### ISSUE TITLE
"Quest" Dustwallow Marsh - Tabethas-farm -11212

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#4022]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=11212/tabethas-farm

**What is happening:**
Missing the quest from the NPC

**What should happen:**

he should give the quest that is needed.

**Comment by Echinaceax** [comment]
added to new list for .bq

**Comment by Rushor** [comment]
added and from list removed

https://i.imgur.com/Ypa1KQD.jpg

**Comment by Echinaceax** [comment]
@Rushor btw @Jimpaa is doing a full questorder report after ;)
