### ISSUE TITLE
"Quest" Dustwallow Marsh - Traitors among us  - 27210

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#4023]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=27210/traitors-among-us

**What is happening:**
Calia Hastings do not give the quest 

**What should happen:**

She should give the quest so u can get 27211
But she do give the third quest in the chain 27212 and u can complete that with .bq

**Comment by Echinaceax** [comment]
Not sure what happened coz it was available before #1795

**Comment by Rushor** [comment]
is avilable after https://www.wowhead.com/quest=28552/heros-call-dustwallow-marsh is done https://i.imgur.com/N2ay9Ri.jpg

i guess that's blizzlike :)
