### ISSUE TITLE
"Quest" Dustwallow Marsh - End of the deserters - 27213

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#4024]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=27213/the-end-of-the-deserters

**What is happening:**
The mob do not spawn there for cant complete it.

**What should happen:**

**Comment by Echinaceax** [comment]
added to new list for .bq will be live soon

**Comment by Rushor** [comment]
fixed and removed from list :) 27213

![I](https://i.imgur.com/xYGmk71.jpg)
