### ISSUE TITLE
"Quest" Dustwallow Marsh - Recovering the cargo - 27237

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#4025]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=27237/recover-the-cargo
**What is happening:**
The cargo that you need to use the item on is not spawning.

**What should happen:**

There should be some cargo just under the water that you can use a quest item on.

**Comment by Echinaceax** [comment]
added to new list for .bq will be live soon

**Comment by Rushor** [comment]
okay fixed. there is a small chance that either a mulroc spawns or you get the questitem.

![I](https://i.imgur.com/6xJ6Or3.jpg)

also added a few more spawns to it.
