### ISSUE TITLE
"Quest" Dustwallow Marsh - Survey Alcaz Island - 27239

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#4026]
**Links:**

from WoWHead or our Armory
https://wowwiki.fandom.com/wiki/Quest:Survey_Alcaz_Island
**What is happening:**
When you talk to the npc that is suppose to send you on a gryphon there is no option to do that. 

**What should happen:**

She should give you the option to fly away on a gryphon so you can complete the quest.

**Comment by Echinaceax** [comment]
added to new list for .bq will be live soon

**Comment by Rushor** [comment]
added it and removed from list 

![I](https://i.imgur.com/ULCzqrw.jpg)
