### ISSUE TITLE
"Quest" Dustwallow Marsh - Marsh Frog Legs - 27183

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#4027]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=27183/marsh-frog-legs
**What is happening:**
He did not give the quest 

https://imgur.com/a/R8cBvlR
**What should happen:**

He should give the quest Marsh Frog Legs

**Comment by Echinaceax** [comment]
added to new list for .bq will be live soon

**Comment by Rushor** [comment]
okay it has prev quest http://cata.cavernoftime.com/quest=27182 set which makes no scence to alliance player

**Comment by Rushor** [comment]
avialable now and removed from list

![I](https://i.imgur.com/ggU1G68.jpg)
