### ISSUE TITLE
[Raid] Baradin Hold Door

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#4029]
I recall that the battle has been disabled however the door is still closed by default so players cannot enter
![image](https://user-images.githubusercontent.com/16594771/69911662-8a9c4a80-1427-11ea-9f46-4bc16d75d268.png)

**Comment by Rushor** [comment]
okay will remove the whole door then :o

**Comment by sarahkay88** [comment]
#3996

**Comment by Rushor** [comment]
okay whole object removed now.
