### ISSUE TITLE
RDF Mount Drops Loot System

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#4030]
If an epic mount drops in RDF, players that don't have artisan riding (34091) can't roll need on the mount, even though they can still use it.
Tested in Vortex Pinnacle Heroic.
I couldn't get a screenshot because I have the skill.

**Comment by Echinaceax** [comment]
https://www.wowhead.com/spell=34091/artisan-riding

**Comment by questbugreporter** [comment]
they can't use it, invalid

**Comment by Echinaceax** [comment]
Is this really a bug though?
i had the same in Stratholme mount i didnt have epic flight and couldnt "need on it"

**Comment by questbugreporter** [comment]
see above

**Comment by Echinaceax** [comment]
i saw at the same time you closed it @questbugreporter :)
