### ISSUE TITLE
[Core][Quest][Item] Hellfire peninsula zone checkup - Alliance

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#4035]
![image](https://user-images.githubusercontent.com/16594771/70034490-f1516d80-15b9-11ea-9872-7f709c94fabc.png)

The zone is in a very good condition, the only quest not working is https://www.wowhead.com/quest=10078/laying-waste-to-the-unwanted althought this is a minor fix, it is low priority at the moment and should just be added to the .bq 

also see #763

**Comment by Rushor** [comment]
not need anymore for list, has been fixed now.

![I](https://i.imgur.com/UupuQ1p.jpg)
![I](https://i.imgur.com/4Qv9YUQ.jpg)
