### ISSUE TITLE
Raid lock issue

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#4039]
On sunday, we killed 2/4 bosses in Bastion of Twilight.
Today, we also killed 2/4 bosses in Bastion of Twilight, but on different characters.
We tried to swap out two characters in today's group after killing Valiona and Theralion for the ones that got locked on Sunday and they couldn't enter the instance.
All dungeon and raid locks show like this after relogging: 
![image](https://user-images.githubusercontent.com/56992013/70093411-01ecfc80-1629-11ea-8561-4d40185f5b98.png)

Bosses that have been defeated show as available, might be related or a seperate issue, I do not know.

People that have killed the same bosses in different groups should be able to raid with each other.

**Comment by Rushor** [comment]
moved to https://github.com/WoWManiaUK/Blackwing-Lair/issues/3615
