### ISSUE TITLE
 [NPC/Mobs] Dire Maul - (low priority) - Feralas

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#404]
Map - https://www.wowhead.com/feralas#map

- Missing mobs at Eldreth Row hallways

![missing mobs at d](https://user-images.githubusercontent.com/39439201/50737770-45e34180-11cd-11e9-8a37-65105b1a65d9.jpg)

**Comment by Rushor** [comment]
added several spawns and randommovement https://i.imgur.com/8phcAd3.jpg
