### ISSUE TITLE
[Event] Winter Veil - Horde test 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4041]
### **Havent tested pvp stuff**
https://wow.gamepedia.com/Feast_of_Winter_Veil

**Quests/Dailies**

1a. https://classic.wowhead.com/quest=6983/youre-a-mean-one
Everything is missing from the cave, so cant steal required item,  cant complete.
and no metzen  https://classic.wowhead.com/npc=15664/metzen-the-reindeer

![your a mean one](https://user-images.githubusercontent.com/39439201/70109254-a2ecaf00-164b-11ea-8105-dd4e1672920b.jpg)

1b. Stolen present quest reward was empty 

![stolen present](https://user-images.githubusercontent.com/39439201/70109713-06c3a780-164d-11ea-9865-2fec49974dee.jpg)

2. https://wow.gamepedia.com/The_Reason_for_the_Season there are x2 npc
https://wow.gamepedia.com/Sagorne_Creststrider (9550)

![Sagorne Creststrider 9550](https://user-images.githubusercontent.com/39439201/70110172-68384600-164e-11ea-95cb-6597e9b29e80.jpg)

3.https://classic.wowhead.com/quest=7061/the-feast-of-winter-veil auto completes 
3b https://classic.wowhead.com/npc=3057/cairne-bloodhoof is missing so cant hand quest back

4. https://classic.wowhead.com/quest=6984/a-smokywood-pastures-thank-you quest missing
completed after .quest add,

4b gives wrong rep, is what is meant https://wow.gamepedia.com/Steamwheedle_Cartel and i got 

![rep recieved](https://user-images.githubusercontent.com/39439201/70111007-3d9bbc80-1651-11ea-98ae-54355bd9c048.jpg)

**Achievement**
5. https://www.wowhead.com/achievement=4437/bb-king only one works

 ![BB KING](https://user-images.githubusercontent.com/39439201/70112683-696d7100-1656-11ea-897f-d51c69a24738.jpg)

BROKEN
https://www.wowhead.com/npc=42928/muradin-bronzebeard
https://classic.wowhead.com/npc=7999/tyrande-whisperwind
https://www.wowhead.com/npc=17468/prophet-velen

6. https://www.wowhead.com/achievement=5854/a-caroling-we-will-go only two work 

![caroling2](https://user-images.githubusercontent.com/39439201/70113154-5fe50880-1658-11ea-81cf-5dfbc946c08f.jpg)

6b. https://www.wowhead.com/item=70923/gaudy-winter-veil-sweater 
side note "Gaudy Winter Veil Sweater" was only added in 4.2.0 so not sure if the above Achv should be here yet 

**Vendors**
7. https://wow.gamepedia.com/Gaudy_Winter_Veil_Sweater not selling the sweaters

8. Additional Notes
https://classic.wowhead.com/quest=6984/a-smokywood-pastures-thank-you
When you complete the quest (LOOK AT 4.) , Great-father Winter sends you a pattern, plan, recipe, schematic or formula if you are a Leatherworker, Tailor, Blacksmith, Alchemist, Engineer or Enchanter.

![santa mail](https://user-images.githubusercontent.com/39439201/70258104-e51d0a00-178b-11ea-8df5-124fa3265745.jpg)

8B. i recieved the gift on auto completing via command, but the mail gift only had crap in, not a recipe 

recived in gift was 

![crap recieved](https://user-images.githubusercontent.com/39439201/70258146-f9f99d80-178b-11ea-8900-c78869df6339.jpg)

here is list lootstable
https://wow.gamepedia.com/Smokywood_Pastures_Special_Gift

8c. _You will also receive a  [Winter Veil Disguise Kit] in the mail from Santa, within 24 hours of turning in the quest._ https://classic.wowhead.com/quest=6984/a-smokywood-pastures-thank-you

Didnt receive https://classic.wowhead.com/item=17712/winter-veil-disguise-kit

**Comment by sarahkay88** [comment]
Nice job @Echinaceax  ty for this :)

**Comment by Rushor** [comment]
thank you very much. will fix the event tomorrow :)

**Comment by Rushor** [comment]
3.https://classic.wowhead.com/quest=7061/the-feast-of-winter-veil auto completes
cannot be fixed right now

**Comment by Rushor** [comment]
1b. Stolen present quest reward was empty fixed https://i.imgur.com/oAGWHPr.jpg

**Comment by Rushor** [comment]
event also started no, available with update

**Comment by Rushor** [comment]
3b https://classic.wowhead.com/npc=3057/cairne-bloodhoof is missing so cant hand quest back

updated questender

**Comment by Rushor** [comment]
bb king fixed https://i.imgur.com/qaQXDow.jpg

**Comment by Rushor** [comment]
bb king fixed for horde aswell https://i.imgur.com/p3Ssoyy.jpg

**Comment by Echinaceax** [comment]
> bb king fixed for horde aswell https://i.imgur.com/p3Ssoyy.jpg

this is the horde test report @Rushor, did you mean Ally?

**Comment by Rushor** [comment]
both

**Comment by Rushor** [comment]
scrooge alos fixed horde https://i.imgur.com/LRry6wI.jpg

**Comment by Rushor** [comment]
https://i.imgur.com/VwaPG7T.jpg

**Comment by Rushor** [comment]
7. https://wow.gamepedia.com/Gaudy_Winter_Veil_Sweater not selling the sweaters vendor added

**Comment by Rushor** [comment]
okay everything done now except the https://www.wowhead.com/npc=54499/the-abominable-greench

will fix this later in a new issue today..

**Comment by Rushor** [comment]
Winter Veil Disguise Kit added to a vendor instead 13420 and 13433

**Comment by Echinaceax** [comment]
@Rushor and 1a fixed?

also can you check that 1a is repeatable (just show Mania had an issue with it :)
https://github.com/WoWManiaUK/Redemption/issues/3832#event-2889311215

https://wow-reign.com/page/armory

**Comment by Rushor** [comment]
@Echinaceax - yes has repeatbale flag

**Comment by Echinaceax** [comment]
> @Rushor and 1a fixed?
> [#4041 (comment)](https://github.com/WoWManiaUK/Blackwing-Lair/issues/4041#issue-532410493)

**Comment by Rushor** [comment]
![I](https://i.imgur.com/3ijqGrP.jpg added now.
