### ISSUE TITLE
[Core] Party loot on quest items - not working correctly

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#4042]
At the moment if a 2 or more players are in a group setting and both players are required to loot quest items from a mob they SHOULD both be able to loot a quest item when one drops. At the moment, it is first come first served. 

Random quest example: Kill 5 mobs and collect 5 heads. If player A and player B are both on the quest and kill a mob then if player A or player B loot the head from the corpse, then the other player cannot do so. 

This is not a correct feature as it shouldn't be like this because quest items have a different looting system than normal items as said in this quote from wowwiki: 
Each member may loot the quest item off the corpse. The other loot on the corpse is subject to the party loot setting. 2) In other quests which require collecting several items of a type (harpy feathers for example), the quest items will drop on some mobs and be looted in the normal way, except that if the current looter can't collect the items (not on quest, already has full set) then the quest loot is FFA for those members who can still pick up the quest items. Other items on the corpse are governed by the party loot setting.

https://wowwiki.fandom.com/wiki/Loot#Looting_while_in_a_party for more detail see the Quest loot section.

At the moment it is possible if both players manage to loot 1 mob at the exact same time then they can both collect a quest item. But this proves that the party quest loot system is not working correctly.

**Comment by questbugreporter** [comment]
> At the moment if a 2 or more players are in a group setting and both players are required to loot quest items from a mob they SHOULD both be able to loot a quest item when one drops. At the moment, it is first come first served.

Random quest example: Kill 5 mobs and collect 5 heads. If player A and player B are both on the quest and kill a mob then if player A or player B loot the head from the corpse, then the other player cannot do so.

This is not how it worked in cataclysm, you must be thinking of a later expansion.
Everyone would group for the ghost/demon/prison, leftovers and problim quests in tol barad and then leave the group to do the crocs solo.
Whoever loots the quest item first gets it, that's how it's supposed to be.

**Comment by Priestelar** [comment]
I hear what you're saying but I couldnt find something stating that things did NOT work like this in cata. that and it worked like I mentioned on other servers, thats why I am also not sure which is right and which is wrong.

**Comment by questbugreporter** [comment]
From your own post: 

>  In other quests which require collecting several items of a type (harpy feathers for example), the quest items will drop on some mobs and be looted in the normal way, except that if the current looter can't collect the items (not on quest, already has full set) then the quest loot is FFA for those members who can still pick up the quest items. Other items on the corpse are governed by the party loot setting.

Wiki wording is kinda weird, but I think it means the same thing that I'm saying.

**Comment by sarahkay88** [comment]
@questbugreporter   is correct in what he says
also a better way to think of it - why would one mob with 1 head - drop his head twice.

**Comment by questbugreporter** [comment]
The entire post isn't invalid, there are other issues in it.

**Comment by Kitzunu** [comment]
This report needs to be tidied up, it is very hard atm to understand what is valid and what is not.
Would appreciate if 1 person (Perhaps the original author) adds a comment with a new How it works, How it should work with the valid points :)

Thank you,
Regards

**Comment by Kitzunu** [comment]
Open a new issue if there is anything here that is actually a bug.
