### ISSUE TITLE
Alliance: Worgen Race / Emote Bug

### ISSUE THREAD

**Issue by DarkicecKelthuss** [WoWManiaUK/Blackwing-Lair#4045]
https://www.wowhead.com/worgen

**What Happens:**
Hello,

whenever you use any Emote on Worgens( regardless of whether Form you Use: Gilnean or the Worgen Form) like /hi, /roar, /lol, regardless what you do (They are doing the Emote but without any sound). Tested on my Mage Kelthuss , and my brother tried it on his Worgen Hunter Mikx.

**What should happen:**
It should do the Emote with Sound.

Tip: Maybe ask the Community if this problem also occurs on Goblins (also Cata implemented Race).

Thank you! :)

**Comment by Rushor** [comment]
hmm this works on my client. which client do you used?

**Comment by sarahkay88** [comment]
tested worgen on live n dev and its silent - make animation only but no sounds
also tested my gobbo dk on dev because I don't have one on live n that again is silent

**Comment by sarahkay88** [comment]
doesn't appear to be just worgens and gobbos currently none r working

**Comment by Rushor** [comment]
moved to https://github.com/WoWManiaUK/Blackwing-Lair/issues/4047
