### ISSUE TITLE
[Dungeon] Blackrock Caverns Reputation

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#4048]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/blackrock-caverns
**What is happening:**
On heroic as Alliance when you kill mobs you get rep with Baradin´s Warden when you dont use tabard. If you use tabard you do get rep with the tabard.

On heroic as Horde It does not matter if you have a Tabard or not you still only get rep with Hellscream´s Reach 
https://imgur.com/a/OgFhbRN I did have Mount hyjal tabard on me and still got Hellscream rep.

Im not 100% sure if thats correct or not. 

We did not get rep for bosses either. 

**What should happen:**

As horde you should get the rep you have tabard with. 
Without tabard im not sure what you should get.

**Comment by Rushor** [comment]
changed the faction to a nutral one. without tabard you will get rep at http://cata.cavernoftime.com/faction=1135

with tabard, you get rep fitting to your tabard. In nh you will not get any rep. This is the only way we can fix that issue. :)

![I](https://i.imgur.com/QtJwwte.jpg)

Cheers.
