### ISSUE TITLE
[NPC] Mind control against an npc

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#4049]
**Links:**
https://classic.wowhead.com/spell=605/mind-control

**What is happening:**

so there has been a few reports that the flight master npc's in outlands have been moved out of their position without any reason.
However I think MC on a priest may play apart in this.
ATM if you mc the opposite fraction NPC and run them into a building ect they do not reset their position until server restarts or a GM resets them.  players can use their abilities to drop threat and the npc says were it was mc to.

**What should happen:**
after mc the npc is should reset to its original position or cause aggro to the player and run to attack them
 

![WoWScrnShot_120519_190909](https://user-images.githubusercontent.com/42302580/70265702-dc7c0200-1792-11ea-9700-bc97a9ea3756.jpg)

**Comment by sarahkay88** [comment]
also noted that every so often honor hold gets attacked by inferno raid which fears all the npc's after the effect they also don't reset their position which is why the npc's often are out of place behind the inn

**Comment by Rushor** [comment]
this is a very old issues, will temp fix that by adding mc immune flag to the flight masters

**Comment by Rushor** [comment]
All flight masters are now immune to mind controle effects.
