### ISSUE TITLE
[Quest] After the  Fall

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Blackwing-Lair#4050]
https://www.wowhead.com/quest=27624/after-the-fall

https://www.youtube.com/watch?v=dPID96o_10M

You have to  collect  4 orbs in Chamber of Stars in Uldum
There is  only one orb  you  can pick up
Orb of the North Star the other  3  don't  spawn

**What should happen:**

**Comment by Rushor** [comment]
added the orbs
