### ISSUE TITLE
[Spell] DK - Runic Empowerment

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#4051]
![image](https://user-images.githubusercontent.com/56992013/70294893-c3546f00-17ed-11ea-81de-52348a74208b.png)

Tested as a Blood Death Knight (using Rune Strike) and found two or maybe even three issues:

1. Runic Empowerment can refresh more than one rune.
2. It can refresh runes that are already regenerating. It should only refresh fully depleted runes. Explanation from an old mmo-champion thread:

> *Note* It says fully depleted rune. This means you have to have *both* of your runes of that type on cooldown, or it will not choose that rune. This is how it happens:
U = ready unholy rune
u = unholy rune on cooldown
F = ready frost rune
f = frost rune on cooldown
B = ready blood rune
b = blood rune on cooldown

>You have 100 runic, and no runes on cooldown: BBFFUU
You cast 2 death coils. You cannot get any procs: BBFFUU
You death strike once: BBFfUu
You cast 2 death coils. You cannot get any procs: BBFfUu
You cast 2 death strikes in a row: BBffuu
You cast 2 death coils. You can now get procs:
One proc on frost rune: BBFfuu
One proc on unholy rune: BBffUu
One proc on each. Note that it has to be one of each, since getting two of one is not possible: BBFfUu

https://www.mmo-champion.com/threads/781142-Please-help-me-understand-Runic-Empowerment-Runic-Corruption

3. It seems to always refresh blood runes over frost or unholy ones instead of a random rune, BUT I kind of remember this being an actual feature so it might not be a bug. Can't find anything that confirms it. As long as the previous issue is fixed, this shouldn't matter that much anyway.

**Comment by questbugreporter** [comment]
While in blood spec:

RE still procs on blood runes that are regenerating.
RE no longer procs on any frost or unholy runes at all, ONLY blood runes.

While in frost spec:

The proc chance doesn't seem to be 45% but waaaay lower, I cannot even test it at this state.

**Comment by Keader** [comment]
https://youtu.be/qFM4dunEyXo
Working fine to me.

**Comment by questbugreporter** [comment]
You're right about frost, I was testing with low hit rating vs the level 88 dummy.
BUT STILL while in blood spec:

RE still procs on blood runes that are regenerating.
RE no longer procs on any frost or unholy runes at all, ONLY blood runes.

**Comment by Keader** [comment]
I tested ALL conditions and ALL conditions is working for me.
I just not recorded videos for ALL.

**Comment by questbugreporter** [comment]
Well then I just recorded a video that proves that regenerating blood runes can be refreshed by RE so you're wrong I suppose.
https://streamable.com/cim8j

**Comment by questbugreporter** [comment]
Also you can see that it only procs on blood runes.
(Yes I know it's a small sample but I've tested hundreds of times at this point)

**Comment by questbugreporter** [comment]
@Keader and here is a 5 minute video of the same character getting 0 procs while keeping both blood runes off cooldown and all frost and unholy runes depleted before using rune strike.
https://streamable.com/xfo0k

**Comment by Echinaceax** [comment]
@questbugreporter Test in progress later today

**Comment by Echinaceax** [comment]
no new info on this @Keader - tester that was on this left

**Comment by golosomie** [comment]
@Keader 

If both runes are on cooldown, one is regenerating while the other is "fully depleted" (not yet regenerating). The spell should only regenerate the rune that is fully depleted. Right now, one of both is picked randomly.

Seen for frost runes: https://gyazo.com/0aaad8b0060abad6d2dd6eb467e7ae13
Unholy runes: https://gyazo.com/97b0f660b3855d9d004c59bfe8e28c4d
Same thing can happen for Blood Runes and Death Runes (in frost dk)

**Comment by Keader** [comment]
test now pls.
it should priorize the rune with higher cooldown (inside of that type)

**Comment by golosomie** [comment]
@Keader 
Confirmed fixed on PTR.
