### ISSUE TITLE
[Quest] Closure is only Natural

### ISSUE THREAD

**Issue by glcabatuan** [WoWManiaUK/Blackwing-Lair#4054]
**Links:**

from WoWHead or our Armory

**What is happening:**
Demons Gates are not responding to Gnarl's bough

**What should happen:**
It should close the gate after 5 seconds

**Comment by Rushor** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/2126

pls use the search function before reporting thanks
