### ISSUE TITLE
[Quest] Go with the Flow - Ashenvale

### ISSUE THREAD

**Issue by glcabatuan** [WoWManiaUK/Blackwing-Lair#4055]
**Links:**

from WoWHead or our Armory

**What is happening:**
Sabina Pilgrim (NPC) isn't existing on its targetted location

**What should happen:**

She should exist at along with the 3 earthen ring members

**Comment by Rushor** [comment]
![I](https://i.imgur.com/lBpukxo.jpg)

added here. live with next update
