### ISSUE TITLE
[Quest] He who would be forgiven - Ashenvale

### ISSUE THREAD

**Issue by glcabatuan** [WoWManiaUK/Blackwing-Lair#4056]
**Links:**

from WoWHead or our Armory

**What is happening:**
Avrus IllWhisper (NPC) isn't existing in the location

**What should happen:**
He should be in the moonwell on Raynewood Tower

**Comment by Rushor** [comment]
added the creature. live with next serverupdate.
![I](https://i.imgur.com/dxEn4ac.jpg)

**Comment by glcabatuan** [comment]
wow. very fast. i am willing to help to find some bugs

**Comment by Rushor** [comment]
thank you, if you like you can add the ids from quests objects etc. 

good database is http://cata.cavernoftime.com/?quest=27697

then we can fix even faster
