### ISSUE TITLE
[Quest] Hot Lava

### ISSUE THREAD

**Issue by glcabatuan** [WoWManiaUK/Blackwing-Lair#4057]
**Links:**
https://www.wowhead.com/quest=13880/hot-lava
from WoWHead or our Armory

**What is happening:**
The fissures are not reacting once the gift of earth finished channeling

**What should happen:**

It should be filled earth thing once finished channeling

**Comment by Rushor** [comment]
already reported https://github.com/WoWManiaUK/Blackwing-Lair/issues/1019

pls use search function before open new issues. thanks
