### ISSUE TITLE
[Quest] Return Fire

### ISSUE THREAD

**Issue by glcabatuan** [WoWManiaUK/Blackwing-Lair#4058]
**Links:**
https://www.wowhead.com/quest=13853/return-fire
from WoWHead or our Armory

**What is happening:**
Can't ride the thrower

**What should happen:**

You could ride by right clicking the thrower

**Comment by Rushor** [comment]
already reported https://github.com/WoWManiaUK/Blackwing-Lair/issues/2117

**Comment by mizsh** [comment]
hi, any updates on this? thanks

**Comment by kay-glitch** [comment]
Still an issue where you can't ride any of the throwers located in Astranaar.

**Comment by Echinaceax** [comment]
this is a duplicate report and was closed @kay-glitch 

here is the open report - and not fixed yet #2117
