### ISSUE TITLE
[Quest] They took our gnomes

### ISSUE THREAD

**Issue by glcabatuan** [WoWManiaUK/Blackwing-Lair#4059]
**Links:**
https://www.wowhead.com/quest=13913/they-took-our-gnomes#comments
from WoWHead or our Armory

**What is happening:**
Thundrak and the gnomes are not in the wagon in its pointed location

**What should happen:**

They should be existing on the wagon

**Comment by Rushor** [comment]
already reported https://github.com/WoWManiaUK/Blackwing-Lair/issues/3675
