### ISSUE TITLE
[Quest] King of the Foulweald {13989}

### ISSUE THREAD

**Issue by glcabatuan** [WoWManiaUK/Blackwing-Lair#4060]
**Links:**
https://www.wowhead.com/quest=13989/king-of-the-foulweald
from WoWHead or our Armory

**What is happening:**
Chief Murgut isn't appearing even the flag is planted at the mould and waited for at least 5 minutes

**What should happen:**
It should have shown at least in a minute or so

**Comment by Echinaceax** [comment]
reported here already, but thanks #1773
