### ISSUE TITLE
Paladin Retribution: Pursuit of Justice

### ISSUE THREAD

**Issue by APTX4869s** [WoWManiaUK/Blackwing-Lair#4061]
![Pursuit of Justice](https://user-images.githubusercontent.com/57665529/70354284-986b2900-1888-11ea-8f8c-7aa34aecfe32.png)

**What is happening:**
the first part doesn't work, stun, fear and immobilize effect doesn't give a holy power

**What should happen:**

Stun, fear and immobilize effect should give you a holy power 
it has 8 seconds icd.
Cataclysm Patch 4.0.3a (2010-11-23): Now has an 8-second internal cooldown, shared with  [Blessed Life].

https://wow.gamepedia.com/Pursuit_of_Justice

**Comment by Rushor** [comment]
// Pursuit of Justice
                case 26022:
                case 26023:
                    if (procSpell && procSpell->GetAllEffectsMechanicMask() & 
                        ((1<<MECHANIC_STUN) | (1<<MECHANIC_FEAR) | (1<<MECHANIC_ROOT)))
                        this->CastSpell(this, 89024);
                    break;

handleauraproc

may need convert to spellscript

**Comment by questbugreporter** [comment]
This still doesn't work.

**Comment by questbugreporter** [comment]
Also there seems to be some interaction with crusader aura now, preventing this talent from giving movement speed.

**Comment by questbugreporter** [comment]
Apparently the talent works, BUT if you become affected by crusader aura it stops working until you change specs.

**Comment by APTX4869s** [comment]
Well, as I said in discord, this report has nothing to do with https://github.com/WoWManiaUK/Blackwing-Lair/issues/3666
