### ISSUE TITLE
[Quest] Battle for crusaders pinnacle [WOTLK] [Id 13141]

### ISSUE THREAD

**Issue by Szymo1337** [WoWManiaUK/Blackwing-Lair#4062]
**Links:**
https://www.wowhead.com/quest=13141/the-battle-for-crusaders-pinnacle

**What is happening:**
The pile of skulls just isnt there. I searched everywhere in case it was moved. But cant find it. It looks like the object just doesnt spawn 

**What should happen:**
It should be there ofcourse.

**Comment by Rushor** [comment]
https://i.imgur.com/0R80xMu.jpg

will be there in phase 169 now.

**Comment by gorgar19** [comment]
looks like the bone pile is missing again

**Comment by Echinaceax** [comment]
> looks like the bone pile is missing again

yes the report is still opened here @gorgar19 #4593
