### ISSUE TITLE
(Quest) Totem Modification (Part 3 of 5) - Shimmering Expanse

### ISSUE THREAD

**Issue by Kuro2004** [WoWManiaUK/Blackwing-Lair#4063]
**Links:**
https://www.wowhead.com/quest=25217/totem-modification

**What is happening:**

When accepting the quest you do not receive the items needed to complete the quest. I have plenty of space in bags (30/74) and doing .bq 25217 doesn't work.

**What should happen:**

Upon accepting the quest you should receive 2 items (https://www.wowhead.com/item=54217
https://www.wowhead.com/item=54216 )
but you do not. Rendering the quest line uncompleted.

**Comment by Echinaceax** [comment]
@Kuro2004 thank you for reporting
The reason that this isnt set to the .bq command is because there was no report 
(only reported broken quests/items can be added manually to the command) 

Either Rushor will fix or i will add too the commands list

**Comment by Rushor** [comment]
all fixed. https://i.imgur.com/MotMYm9.jpg
