### ISSUE TITLE
[NPC] Fanny Thundermar 48530 - missing - Twilight Highlands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4064]
**Links:**

https://www.wowhead.com/npc=48530/fanny-thundermar

**What is happening:**
NPC missing

**What should happen:**
Should be here for quest back 
https://www.wowhead.com/quest=28407/the-bachelorette

Reported by ingame player

**Comment by Rushor** [comment]
added https://i.imgur.com/LQYV0hC.jpg
