### ISSUE TITLE
Non-Targeted area of effect spells and Enemies with large hitboxes

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#4067]
**What is happening:**

When using spells non-targeted area of effect spells such as Blood Boil or Demoralizing Roar you cannot hit large enemies while being inside range for melee auto-attacks. Instead you have to move closer to the center of their models.

![image](https://user-images.githubusercontent.com/56992013/70383617-700f2780-1979-11ea-8da3-87af3792d538.png)

**What should happen:**

The hitbox for aoe spells should be as large or of a similar size as the targeting range.

Very easy to confirm this by using a feral bear druid against Pit Lord Argaloth in Baradin Hold.

**Comment by Keader** [comment]
I made a workaround for it.
This issue exists since 2011 on core, and no one know how proper fix.
I added hitbox in AOE calculation, but ONLY FOR BOSSES.
It should helps to PVE behavior, without fuck pvp.

**Comment by questbugreporter** [comment]
@Keader this workaround apparently also works against players, making us take damage from stuff we're nowhere near.
Really bad in the valiona  and theralion fight with engulfing flames debuff for example.
