### ISSUE TITLE
[Deephoolm] Gorged Gyreworm mining Volatile Earth/Elementium Ore

### ISSUE THREAD

**Issue by Nexenwon** [WoWManiaUK/Blackwing-Lair#4068]
**Links:**
https://wowwiki.fandom.com/wiki/Gorged_Gyreworm

**What is happening:**
Gorged_Gyreworm as on picture should drop Volatile Earth when mined but they drop some gray items
![Untitled](https://user-images.githubusercontent.com/58032108/70393491-bea8da00-19ea-11ea-89f3-76daf46d8abc.png)

![Untitled](https://user-images.githubusercontent.com/58032108/70393525-41319980-19eb-11ea-96b9-684a004223af.png)

![Untitled](https://user-images.githubusercontent.com/58032108/70393529-527aa600-19eb-11ea-9b22-6c26bccff155.png)

**What should happen:**
![Untitled](https://user-images.githubusercontent.com/58032108/70393575-ad140200-19eb-11ea-99e0-2dee5494278c.png)

https://www.youtube.com/watch?v=XTsHqErPpDY

**Comment by Rushor** [comment]
fixed https://i.imgur.com/ouqBmNo.jpg
