### ISSUE TITLE
[Quest] Villains/Heroes/Marauders of Darrowshire - Interaction - Eastern Plaguelands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#407]
NPC - https://www.wowhead.com/npc=10667/chromie

- Chromie has 3 quests to give 
- Only can choose 1 
- The others disappear 

Quest - https://www.wowhead.com/quest=27387/villains-of-darrowshire
Quest - https://www.wowhead.com/quest=27388/heroes-of-darrowshire
Quest - https://www.wowhead.com/quest=27389/marauders-of-darrowshire

![chromie quest](https://user-images.githubusercontent.com/39439201/50740237-979ac480-11eb-11e9-912e-92a2c6c838f2.jpg)

![chromie2](https://user-images.githubusercontent.com/39439201/50740248-d6307f00-11eb-11e9-938b-36dd9fb7759a.jpg)

**Comment by Kitzunu** [comment]
You can only choose to do 1 of the quests. The other 2 will closed.
![image](https://user-images.githubusercontent.com/24550914/56082410-e70b1500-5e18-11e9-849e-211d9b073582.png)

**Comment by Kitzunu** [comment]
My bad, after more research I have come to find you need to do all 3 quests to be able to open part 2.

Have you tried doing 1 quest at a time?

**Comment by Echinaceax** [comment]
> Have you tried doing 1 quest at a time?

No, i didnt try 1 by one, can try that tho
