### ISSUE TITLE
Death Knight Rune System and Haste

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#4071]
Haste should be increasing rune regeneration (Runes/time), but it is instead reducing cooldowns.

How it should work:

Cooldown = BaseCooldown / (1 + Haste)

How it works right now: 

Cooldown = BaseCooldown * (1 -  Haste)

Here's a visualised comparison of the cooldown in seconds:
![image](https://user-images.githubusercontent.com/56992013/70464989-aad3a580-1ac8-11ea-9204-a7ae349fd49c.png)

This can easily be confirmed by testing against Altairus in the Vortex Pinnacle.

**Comment by Ovahlord** [comment]
@Keader  u sucker: https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/0cdddca21022aee007fbc248e93bb8db32221678

![WoWScrnShot_121019_152448](https://user-images.githubusercontent.com/18347559/70537795-57616600-1b61-11ea-98df-ce0c50a71b5e.jpg)

**Comment by Rushor** [comment]
nice project. are you german?

**Comment by Keader** [comment]
ty sucker
