### ISSUE TITLE
[Quest] Blessings from Above {Qid: 14359}- Desolace

### ISSUE THREAD

**Issue by glcabatuan** [WoWManiaUK/Blackwing-Lair#4072]
### Ally quest
**Links:**
**Quest:**  http://cata.cavernoftime.com/quest=14359
**NPC/s:**  http://cata.cavernoftime.com/npc=35581
**Item/s:** http://cata.cavernoftime.com/item=48857
**Spell/s:**  http://cata.cavernoftime.com/spell=67733
from WoWHead or our Armory

**What is happening:**
Even the 10 satyr's fleshes were collected, still the brazier don't react with the sacrfice. Quest couldn't be completed

![image](https://user-images.githubusercontent.com/27143135/70476782-65d46100-1b12-11ea-8bed-7201746128e6.png)

**What should happen:**
The NPC should once the spell from the Item is used. See video below.

Expected Result Video: https://www.youtube.com/watch?v=EANJJpUbJhg

**Comment by Echinaceax** [comment]
Added to .bq list (not on live yet)

**Comment by Rushor** [comment]
yes using 10 http://cata.cavernoftime.com/item=48857 should trigger some spell action

**Comment by Rushor** [comment]
fixed https://i.imgur.com/el35H5z.jpg

**Comment by glcabatuan** [comment]
> fixed https://i.imgur.com/el35H5z.jpg
Great!
