### ISSUE TITLE
[Quest] Satyrical Offerings {Qid: 14217} - Desolace

### ISSUE THREAD

**Issue by glcabatuan** [WoWManiaUK/Blackwing-Lair#4073]
### Horde

**Links:**
**Quest:**  http://cata.cavernoftime.com/quest=14217
**NPC/s:**  http://cata.cavernoftime.com/npc=35581
**Item/s:**   http://cata.cavernoftime.com/item=48857
**Spell/s:**  http://cata.cavernoftime.com/spell=67733
from WoWHead or our Armory

**What is happening:**
The same as Blessings from Above [quest: 14359]. The brazier don't react for quest completion

**What should happen:**
Once 10 satyr fleshes were collected , the quest should be marked completed and receive a buff for desolace. See video Below:

Expected Result Video: https://www.youtube.com/watch?v=ea4nJshIEAw

**Comment by Echinaceax** [comment]
Added to .bq list (not on live yet)

**Comment by Rushor** [comment]
done https://i.imgur.com/5xz7tbC.jpg
