### ISSUE TITLE
[Quest] To The Hilt !  {Qid: 14357} - Desolace

### ISSUE THREAD

**Issue by glcabatuan** [WoWManiaUK/Blackwing-Lair#4074]
### Ally
**Links:**
**Quest:** http://cata.cavernoftime.com/quest=14357
**NPC/s:**  http://cata.cavernoftime.com/npc=35620
**Item/s:** http://cata.cavernoftime.com/item=48943
**Spell/s:**  http://cata.cavernoftime.com/spell=67785
from WoWHead or our Armory

**What is happening:**
 The handmaiden NPC won't react even 20 blades have been collected and used.
![image](https://user-images.githubusercontent.com/27143135/70479739-fc0b8580-1b18-11ea-99cf-187fd099023d.png)

**What should happen:**

The handmaiden should accept the offering once the satyr blade's spell been casted. It should complete the quest.

Expected Result Video: https://www.youtube.com/watch?v=An8Fi6fmfRc

**Comment by Echinaceax** [comment]
Added to .bq list (not on live yet)

**Comment by Rushor** [comment]
fixed https://i.imgur.com/yRUlsfT.jpg
