### ISSUE TITLE
[Quest] Portals of the Legion {Qid: 14374} - Desolace

### ISSUE THREAD

**Issue by glcabatuan** [WoWManiaUK/Blackwing-Lair#4077]
**Links:**
**Quest:**  http://cata.cavernoftime.com/quest=14374
**NPC/s:** 
**Item/s:** http://cata.cavernoftime.com/item=14547
**object/s:** http://cata.cavernoftime.com/object=177365
**Spell/s:**  http://cata.cavernoftime.com/spell=18762
from WoWHead or our Armory

**What is happening:**
The demon portals are non-reactive to the spell nor mouse over. 

**What should happen:**

Once right clicked the portal, a demon guardian will show to protect it. You need to kill the guardian to successfully banish a portal.

Expected Result: https://www.youtube.com/watch?v=n6cItcyfDqI

**Comment by Echinaceax** [comment]
Added to .bq list (not on live yet)

**Comment by Kitzunu** [comment]
Really nice reports, they are all appreciated :)

Thank you.

**Comment by Rushor** [comment]
Will fix in 2 hours

**Comment by Rushor** [comment]
all done https://i.imgur.com/1R0OUSF.jpg

**Comment by Rushor** [comment]
@glcabatuan Issue fixed. feel free to donate a bit in the shop in order to keep the gm and dev service running. Thank you (https://wow-reign.com/account/donate it's totally voluntary)

**Comment by glcabatuan** [comment]
Yeah, Master @Rushor . I will. I really appreciate all of wow-reigns team efforts.

**Comment by Rushor** [comment]
thank you very much mate!
