### ISSUE TITLE
[Quest] To New Thalanaar {Qid:25481} - Feralas

### ISSUE THREAD

**Issue by glcabatuan** [WoWManiaUK/Blackwing-Lair#4078]
**Links:**
**Quest:** http://cata.cavernoftime.com/quest=25481
**NPC/s:**  http://cata.cavernoftime.com/npc=40367
**Item/s:** 
**Object/s:** 
**Spell/s:** 

from WoWHead or our Armory

**What is happening:**
Due to the fact that the flight master http://cata.cavernoftime.com/npc=40367 can't detect flight path, you can't borrow a hippogryph from her as stated in #1826 bug report.
It's the same situation as issued in #3628 from dustwallow marsh.

**What should happen:**

http://cata.cavernoftime.com/npc=40367 should lend a auto-pilot hippogryph to scout thousand needles and travel to feralas

As shown in: https://www.youtube.com/watch?v=kALTbQJHWuI

**Comment by Rushor** [comment]
thanks i will move this to https://github.com/WoWManiaUK/Blackwing-Lair/issues/4078 since it's is a general issue. we need to figure out what the real issue is with all those creatures

**Comment by rzenne** [comment]
Don't think it is fixed yet

**Comment by rzenne** [comment]
This is being looked at on #4336
