### ISSUE TITLE
[Quest]  Burnout! {Qid: 28387} - Felwood

### ISSUE THREAD

**Issue by glcabatuan** [WoWManiaUK/Blackwing-Lair#4079]
**Links:**
**Quest:**  http://cata.cavernoftime.com/quest=28387
**NPC/s:**  http://cata.cavernoftime.com/npc=48317
**Item/s:**  http://cata.cavernoftime.com/item=64301
**Object/s:** 
**Spell/s:**  http://cata.cavernoftime.com/spell=89892

from WoWHead or our Armory

**What is happening:**
The sprite/toon for the http://cata.cavernoftime.com/item=64301 is different from the original. Yet ,
I tried to ignite it but failed. I don't know where to position myself.  

**What should happen:**

At least throw the http://cata.cavernoftime.com/item=64301 when you are within the area
of the  http://cata.cavernoftime.com/npc=48317

As shown in: https://youtu.be/QNv4Izp1mHI?t=28

**Comment by Rushor** [comment]
all fixed https://i.imgur.com/hqwglXZ.jpg https://i.imgur.com/azcvv57.jpg
