### ISSUE TITLE
[Quest] Pamela's Doll / I'm Not Supposed to Tell You this - Interaction -  Eastern Plaguelands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#408]
Quest https://www.wowhead.com/npc=10926/pamela-redpath

- NPC has 2 Quests
- Can only chose one 
- Other disappears

![one or the other](https://user-images.githubusercontent.com/39439201/50740614-455ca200-11f1-11e9-8b35-4586dadd5c85.jpg)

- After completing "Pamela doll" ...the other quest wasnt available again 

Next quest is totally different one 

Quest - https://www.wowhead.com/quest=27385/uncle-carlin

- Not all 4 quests then ?

https://www.wowhead.com/npc=10926/pamela-redpath

**Comment by sarahkay88** [comment]
same for alliance, it skipped the quest: https://www.wowhead.com/quest=27392 and went straight to the quest: https://www.wowhead.com/quest=27385

**Comment by Dranah** [comment]
https://www.wowhead.com/quest=27384/pamelas-doll
https://www.wowhead.com/quest=27392/im-not-supposed-to-tell-you-this
