### ISSUE TITLE
[Spell][Pet] Fel Intelligence - Mana restore not working

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#4080]
In game the buff granted by Felhunter - Fel Intelligenceis stating it grants 0 mana restored every 5 sec. I can't see it working on the combat log either making me think its not working at all.

http://cata.cavernoftime.com/spell=54424
https://wowwiki.fandom.com/wiki/Fel_Intelligence

**Comment by Kitzunu** [comment]
Who even uses mana in cata? I hear you just hit people with your staff!

haha, jokes aside. Thanks for the catch!
