### ISSUE TITLE
Hook 'em High/ Drag 'em Down (issue2)

### ISSUE THREAD

**Issue by Kuro2004** [WoWManiaUK/Blackwing-Lair#4081]
**Links:**
https://www.wowhead.com/quest=28874/hook-em-high
https://www.wowhead.com/quest=27929/drag-em-down

**What is happening:**
Neither quest will work correctly not allowing you to complete them.
I tried to cast and kill the riders w/o using the items and it did not allow completion.

**What should happen:**
You should be able to use the items:
https://www.wowhead.com/item=62775/barbed-fleshhook  (Hook 'em High item)
https://www.wowhead.com/item=62775/barbed-fleshhook (Drag 'em Down item)
and they grab the gryphon riders so you can kill them. 
https://www.wowhead.com/npc=46321/thundermar-gryphon-rider

**Comment by Echinaceax** [comment]
Item reported already #1864
but thanks
