### ISSUE TITLE
[Quest] Seeds of Discord - 25308

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#4085]
**Links:**
https://www.wowhead.com/quest=25308/seeds-of-discord

**What is happening:**

No dialog option when talking to the Karr'gonn

**What should happen:**

https://www.youtube.com/watch?v=LDfGZb71LvI

**Comment by Rushor** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/2767
