### ISSUE TITLE
[Dungeon Finder] Reque issue + Party invite to continue dungeon issue

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#4088]
In the scenario when a player leaves/dcs from your dungeon group and is either vote kicked from the party or leaves the party then there are 2 options to readd a player to the dungeon. 

There are 2 issues with the 2 available options

1 - Reque with the dungeon finder option - I feel like this doesn't work correctly, When we lost 1 dps today and requed into the dungeon, not sure if the search option actually accepts players already in the dungeon que. I asked players in my guild to join rhc que when one dps dcd but no one was able to join our dungeon despite several of them whom were eligible for the dungeon did not get into the dungeon.

2 - Invite a player to the party - When you do manually invite a player to your party, the whole group will then not get valor on the last boss. This should only happen to the player who gets the group invite since they didnt get the "random" heroic dungeon bonus. But at the moment the whole dungeon group loses their end of dungeon valor and maniac point rewards :(

**Comment by Rushor** [comment]
moved all to https://github.com/WoWManiaUK/Blackwing-Lair/issues/4011
