### ISSUE TITLE
Paladin Retribution: Guardian of Ancient Kings

### ISSUE THREAD

**Issue by APTX4869s** [WoWManiaUK/Blackwing-Lair#4089]
![GAK miss](https://user-images.githubusercontent.com/57665529/70839066-83f8d480-1e24-11ea-9a46-00dc8eefee0f.png)

**What is happening:**
Guardian of Ancient Kings has a chance to miss even if you are hit and expertise capped

**What should happen:**
Guardian of Ancient Kings shouldn't miss if you are hit and expertise capped

 "Patch 4.1.0 (26-Apr-2011): Casting Guardian of Ancient Kings no longer resets the auto-attack swing timer.; The Retribution version of Guardian of Ancient Kings now benefits from the paladin’s hit and expertise."

https://wowwiki.fandom.com/wiki/Guardian_of_Ancient_Kings_(retribution)

**Comment by stromser** [comment]
i see there are a few problems with it

**Comment by Echinaceax** [comment]
Test in progress later today

**Comment by APTX4869s** [comment]
I hope this confirms it 
![GAK miss](https://user-images.githubusercontent.com/57665529/71357917-9d2a1f80-25a0-11ea-9007-ac5a8b699dde.png)

I even changed few gems to make my hit chance more than 8% ( before mine was 8.04% when I opened this report )
8% hit 
26 exp

**Comment by mfranca0009** [comment]
https://wowwiki-archive.fandom.com/wiki/Guardian_of_Ancient_Kings_(retribution)

The Retribution version of the Guardian of Ancient Kings wields [Decimation] in both hands.
World of Warcraft: Cataclysm Patch 4.2.0 (2011-06-28): Guardian of Ancient Kings uses the new Assist pet stance functionality.

From screenshot, it also looks like he's only using one weapon and not two. Needs to have Decimation weapon in both hands (main and offhand).

**UPDATE**
I can't find any sign of this NPC dual-wielding, so keeping the 1 2h weapon as is.

**Comment by Keader** [comment]
Fixed.
Now it will get paladin stats
