### ISSUE TITLE
Acherus Portal Broken - Eastern Plaguelands

### ISSUE THREAD

**Issue by tillouz** [WoWManiaUK/Blackwing-Lair#409]
When arriving at the Azeroth equivalent of Acherus, the quest [The Battle for the Ebon Hold](https://www.wowhead.com/quest=13166/the-battle-for-the-ebon-hold) is not completable because the portal to the upper floor of Acherus does not function. In addition, the portals to Orgrimmar and presumably Stormwind are unusable. 
The flight path in Acherus cannot be used, but jumping down and resurrecting will allow you to access the rest of the world and interaction with Horde factions is possible and normal.

**Comment by tillouz** [comment]
A small side note:
Since it is possible to access the world, it is possible to reach level 60 (even before you leave the instanced version of Acherus) and so you can learn Azeroth flying and fly up from the lower floor. If you do so, be aware that for as long as you have the quest "Warchief's Blessing" (or the Alliance equivalent) you will be pacified and interaction with Horde or Alliance factions will be limited until you either complete or abandon the quest.

**Comment by Dranah** [comment]
Confirmed, the teleporter post "Taking Back Acherus" phase does not work, however this is not yet the "Azeroth world". You're still phased out for questing during these quests and the teleporter is only broken in these phases, it works as intended once you completed the chain and get back to the clean Ebon hold area.

Note: DKs should not be able to access the world before completing their chain. Jumping off should not be possible afaik.

**Comment by Frostmanx** [comment]
The portals work as Intended now and the quest " The Battle for the Ebon Hold" can be completed.
