### ISSUE TITLE
Paladin: Judgment of Truth

### ISSUE THREAD

**Issue by APTX4869s** [WoWManiaUK/Blackwing-Lair#4090]
![Judgement ID](https://user-images.githubusercontent.com/57665529/70839279-6710d100-1e25-11ea-95b7-e48238198e55.png)

![Seal of Truth](https://user-images.githubusercontent.com/57665529/70839348-ca026800-1e25-11ea-9e25-5748f8b45080.png)

![Censure](https://user-images.githubusercontent.com/57665529/70839354-cb339500-1e25-11ea-8e58-691ebaf66a94.png)

https://www.wowhead.com/spell=31804/judgment-of-truth

**What is happening:**
Judgment of Truth's damage always the same, doesn't increase with each stack of censure

**What should happen:**
Judgment of Truth's damage should increase with each stack of censure

"Cataclysm Patch 4.3.0 (2011-11-29): When Judged, now benefits from a multiplier of 20% per stack of Censure, up from 10%."
https://wow.gamepedia.com/Seal_of_Truth

**Comment by questbugreporter** [comment]
I can confirm that judgement does the same damage with or without any stacks of censure being present on the victim.

**Comment by Echinaceax** [comment]
Thanks @questbugreporter we will get this tested

**Comment by APTX4869s** [comment]
5 days testing a 1 button  ?
use Seal of Truth
cast judgment on dummy
then cast it again 5 times
you will see that it does the same damage.
just make sure that nothing procs like trinkets and enchants.

**Comment by APTX4869s** [comment]
1- Use Seal of Truth
2- cast judgment on any target
3- see that Judgment will apply a stack of censure but the next judgment will do the same damage as without any stack of censure ( you can use judgment with 0 stacks of censure then apply 5 stacks of it and use again, see that Judgment of truth's damage is the same as 0 stacks )
I can bring other proves if you want, such as video from retail, showing that it should increase the damage of Judgment of truth with each stack of censure, if needed.

**Comment by Keader** [comment]
fixed

**Comment by golosomie** [comment]
@Echinaceax confirmed fixed on PTR
