### ISSUE TITLE
[Quest][Proffession] Forged documents - Quest is not repeatable

### ISSUE THREAD

**Issue by Priestelar** [WoWManiaUK/Blackwing-Lair#4091]
![image](https://user-images.githubusercontent.com/16594771/70849109-d5d04780-1e82-11ea-9cb9-0631c8fd5256.png)

This is an item that can only be made once a day via Inscription however at the moment the quest cannot be repeated yet it is a repeatable quest that can be turned in every day to receive some gold.

Alliance version:
item - http://www.cavernoftime.com/item=62056#starts
quest - http://www.cavernoftime.com/quest=27675

Horde version:
item - http://www.cavernoftime.com/item=63276#objective-of
quest - http://www.cavernoftime.com/quest=27686

**Comment by Rushor** [comment]
done
