### ISSUE TITLE
Thorium Brotherhood repeatable quests not existing

### ISSUE THREAD

**Issue by Sniperforwin** [WoWManiaUK/Blackwing-Lair#4098]
Repeatable quests for thorium brotherhood, which are the main source of reputation for that faction, don't exist at all on this server.

These quests include at least:

Handed by Lokthos Darkbargainer:
Favor Amongst the Brotherhood, Fiery Core
Favor Amongst the Brotherhood, Lava Core
Favor Amongst the Brotherhood, Blood of the Mountain
Favor Amongst the Brotherhood, Dark Iron Ore
Favor Amongst the Brotherhood, Core Leather

Handed by Master Smith Burninate:
Gaining acceptance
Gaining even more Acceptance

Please fix these so that this rep grind is doable.

**Comment by Echinaceax** [comment]
https://classic.wowhead.com/guides/classic-wow-thorium-brotherhood-reputation#rewards-by-reputation

**Comment by Sniperforwin** [comment]
Please note that the rep amounts for classic wow aren't necessarily correct for Cataclysm, however. 
https://ptr.wowhead.com/faction=59/thorium-brotherhood#comments
These quests should also be available from neutral reputation onwards.

![Capture](https://user-images.githubusercontent.com/58986432/71018688-9ebb9980-2101-11ea-8c7b-7d5877a827c2.PNG)

**Comment by Echinaceax** [comment]
@Sniperforwin thanks for added info (Patch 4.2.2)
we are not there yet will close for now until patch is at (Patch 4.2.2)

**Comment by Sniperforwin** [comment]
I know but these changes were made for Cata pre-patch (4.0) as far as I know. But I trust that the cataclysm data you guys use for developping this server is correct.

**Comment by Echinaceax** [comment]
Exactly, we see what rushor can find out for you ok @Sniperforwin

**Comment by Sniperforwin** [comment]
Of course. Just wanted to point out that information about these quests on classic.wowhead doesn't necessarily apply for Cataclysm.

**Comment by Rushor** [comment]
yes the conditions is wrong

Your reputation with Thorium Brotherhood must be at least Honored

**Comment by Rushor** [comment]
done https://i.imgur.com/rn8xi4S.jpg
