### ISSUE TITLE
Schnottz Air Officer (issue1) - Uldum

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4099]
**Links:**

quest item: https://wow-reign.com/page/armory
npc: https://wow-reign.com/page/armory or https://www.wowhead.com/npc=46993/schnottz-air-officer as armory didnt give ID for this npc

![q item uldum](https://user-images.githubusercontent.com/39439201/71013143-7d05e680-20f0-11ea-9ace-fdd9b149379f.jpg)

**What is happening:**
- Quest item is dropping 100%

**What should happen:**
should only drop if on the quest https://www.wowhead.com/quest=27901/they-dont-know-what-theyve-got-here

note i checked the armory for this quest but the quest rewards are saying different 
https://wow-reign.com/page/armory

so you can chose which is correct @Rushor 
but the issue reported is that the item is dropping 100% without any quest

**Comment by Rushor** [comment]
condition:
Only show loot if player has quest - They Don't Know What They've Got Here - taken

added
