### ISSUE TITLE
[Spell] Arcane Potency

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#41]
Spell ID 31571
Arcane mage talent

Effect does not work. No crit buff is gained when Clearcasting is procced or Presence of Mind is activated.

How it should work:
Every time the mage gains Clearcasting or Presence of Mind, it should grant an extra 15% crit chance to the next spell cast afterwards.

**Comment by Keader** [comment]
Will be ready to test tomorrow morning :)

**Comment by Dranah** [comment]
UPDATE:
- The Arcane Potency buff is procced now, but rather than at the moment of **gaining** Clearcasting, it procs when you **consume** Clearcasting instead. Should be the other way around. (need fix)
- The Arcane Potency buff, when procced, affects your regular direct damage spells properly, but does not affect Arcane Missiles. Does not boost its crit, neither gets consumed by it. (need fix)

The way it should work in synergy with Arcane Missiles is as follows:
1. After you receive a Clearcasting and Arcane Potency buff, and then cast Arcane Missiles, ALL five ticks of the spell are affected by the +15% crit and it consumes 1 stack of Arcane potency (upon being cast!). (Will not consume Clearcasting though - this is currently working fine)
2. If the Arcane Potency / Clearcasting is procced by an Arcane Missile tick, the 15% crit will affect the remaining ticks for that channel, and not result in a stack being lost. The next 2 SPELLCASTS will use the 2 stacks of Arcane Potency you gained.

It's very important that all five ticks are checked for the extra 15% crit and also that it checks for removing a stack when you CAST a spell, not when it lands or when it is finished channeling.

**Comment by Keader** [comment]
Well Dranah, it will stay how isi.
If you got some prof that it should proc with arcane missiles, send a PM in discord and i will look.

**Comment by Dranah** [comment]
We literally linked a video in the Cata channel, from 4.3 where you can see the proc being consumed by Arcane Missiles. What more proof do you want? o_O

**Comment by Asherdoom** [comment]
to me it still not work at all i tested in duel witha  friend of mine and nothing happened not even to the target dummy. 2 points wasted.
