### ISSUE TITLE
[Spell] Death and Decay

### ISSUE THREAD

**Issue by tillouz** [WoWManiaUK/Blackwing-Lair#410]
Death and Decay can be cast normally, and will give enemies standing in it the debuff which indicates they are taking damage, but will not actually deal any damage.
To replicate: cast Death and Decay on any enemy mobs. They will not attack you, despite the debuff.

**Comment by Dranah** [comment]
https://www.wowhead.com/spell=43265/death-and-decay

Does not deal any damage.

**Comment by Dranah** [comment]
Deals damage as intended now.
