### ISSUE TITLE
[Item] Efficient Excavation (item doesn't drop) - Uldum

### ISSUE THREAD

**Issue by Mellowish4767** [WoWManiaUK/Blackwing-Lair#4100]
https://www.wowhead.com/item=62768/efficient-excavations

The above item doesn't drop which leads to a quest chain 

Schnottz Air Officer should drop the item.

**Comment by Echinaceax** [comment]
npc https://www.wowhead.com/npc=46993/schnottz-air-officer

**Comment by Rushor** [comment]
added

**Comment by Echinaceax** [comment]
Info about this @Rushor 

> Hotfix (2010-12-15): Players are no longer able to receive Efficient Excavations before completing N [83] Do the Honors.

![hotfix info](https://user-images.githubusercontent.com/39439201/71311014-5eb72800-241b-11ea-9d39-fedae53dc251.jpg)

So make sure its set to only drop when players have completed _Do the Honors_ http://cata.cavernoftime.com/quest=27669
