### ISSUE TITLE
NPC Commander Schnottz (missing) - Uldum

### ISSUE THREAD

**Issue by Mellowish4767** [WoWManiaUK/Blackwing-Lair#4101]
https://www.wowhead.com/npc=47972/commander-schnottz

He should not available in Schnottz landing

He should be there as a chain quest is linked to him

https://www.wowhead.com/quest=28193/lockdown
https://www.wowhead.com/quest=28195/sending-a-message
https://wow.gamepedia.com/Firing_Squad

This is the list of quests which NPC is related with.

**Comment by Rushor** [comment]
what he means: the creature is not there

**Comment by Echinaceax** [comment]
> what he means: the creature is not there

Yes i though that too @Rushor 
need to check quest order too

**Comment by Rushor** [comment]
added https://i.imgur.com/sp4BCVV.jpg

for the questchain or questbugs open new issues then pls :)
