### ISSUE TITLE
Focused Insight [Shaman Talent]

### ISSUE THREAD

**Issue by Javalapa** [WoWManiaUK/Blackwing-Lair#4107]
**What is happening:**

There are a few bugs with this talent:
1. It is not buffing Healing Rain, which was made possible in patch 4.1
2. You do not receive the buff if your shock misses
3. It is not proccing off of using Earth Shock; Flame and Frost work 

**What should happen:**

Using ANY shock should reduce the mana cost of your next spell by 75% of the cost of the shock, AND increase its healing by 30%

http://cata.cavernoftime.com/spell=77800

**Comment by questbugreporter** [comment]
https://web.archive.org/web/20110811014838/http://elitistjerks.com/f79/t121202-resto_raiding_4_1_updating_4_2_a/

A few quotes from this EJ archived thread:

>You can now use Focused Insight shocks with Healing Rain.

>Again, this is a strong talent, as 2 points will get you near or over the hit cap for purges, dispels, Focused Insight shocks, and Telluric Currents Lightning Bolts. Read later sections for insight on this talent. **Since 4.1 Focused Insight also procs on missed shocks**, and Wind Shear cannot miss anymore, so this will mostly be for Telluric Currents builds.

**Comment by mfranca0009** [comment]
In progress:

- [x] Focused Insight procs even on miss.
- [x] Focused Insight procs off of ANY shock spell (Earth Shock, Flame Shock, Frost Shock).
- [x] Focused Insight should buff Healing Rain.

**Comment by mfranca0009** [comment]
All set 👍 needs testing.

**Comment by golosomie** [comment]
@mfranca0009 Confirmed fixed on PTR.
