### ISSUE TITLE
[Spell] Death Strike and miss/dodge/parry interaction

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#4109]
**Links:**
https://worldofwarcraft.com/en-us/news/3964563/4-3-hour-of-twilight-patch-notes#deathknights
https://www.wowhead.com/spell=49998/death-strike

What should happen:

> Death Strike now heals the death knight whether or not the attack misses, or is dodged/parried. As a result of this change, Death Strike no longer refunds its rune cost if it fails to hit the target, as the death knight will still receive the healing effect.

What happens:

Death Strike refunds its rune cost if it fails to hit the target and doesn't heal the death knight.

**Comment by mfranca0009** [comment]
Rune cost isn't being refunded, or at least its not saying the rune cost is being refunded in combat log, but I can confirm that its only healing on hit.

**Comment by mfranca0009** [comment]
Should be all set, needs testing 👍

**Comment by HrafnValknutt** [comment]
Fix in Dev confirmed. :)
