### ISSUE TITLE
Acherus faction portals broken

### ISSUE THREAD

**Issue by tillouz** [WoWManiaUK/Blackwing-Lair#411]
When trying to use the Orgrimmar portal in Acherus, even with the quest "Warchief's Blessing" (wherein you need to use the Org portal and talk to Thrall / Garrosh), it does nothing.
Since as I mentioned in the [Acherus Portal Broken](https://github.com/WoWManiaUK/Blackwing-Lair/issues/409) you can, in fact, access the world and learn to fly in Azeroth, it is possible to actually traverse the way to Orgrimmar or Stormwind yourself, but for as long as you did not complete the quest, you will be pacified and will not be able to attack, cast spells (including Death Gate) or interact with NPCs normally. Specifically, you will not be able to talk or interact with Orgrimmar NPCs (Silvermoon, Forsaken, Darkspear, Thunder Bluff and Bilgewater NPCs will interact normally with you).
Edit: even after completing the quest, you are still pacified and cannot interact correctly with Orgrimmar NPCs.

**Comment by Frostmanx** [comment]
Portals are fixed and can be used while having the quest  "Warchief's Blessing"(or the alliance version of it ) and the Pacify debuff goes off after 2-3 mins when the quest is completed.
