### ISSUE TITLE
Paladin / Death Knight dodge chance from Agility

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#4110]
**Links:**

https://wow.gamepedia.com/Patch_4.2.0

**What should happen:**

> Death knights, paladins, and warriors no longer receive any bonus to their chance to dodge from Agility. Their base chance to dodge is now a fixed 5%.

**What is happening:**

Agility increases my dodge chance as a death knight and as a paladin, and the base chance is less than 5%.

I don't have a warrior to test it on.

**Comment by mfranca0009** [comment]
All set for Paladins, DKs, and Warriors. Just check with a level 1 for each class with no gear on 👍 

Paladin - 5.23%
Warrior - 5.00%
Death Knight - 5.12%

5 percent base non-diminishing, 0.23 / 0.12 percent from diminishing.

**Comment by HrafnValknutt** [comment]
Fixed in Dev confirmed. Absolutely works like a charm :)
