### ISSUE TITLE
[NPC] Commander Schnottz 47159 missing

### ISSUE THREAD

**Issue by Mellowish4767** [WoWManiaUK/Blackwing-Lair#4111]
Don't know how to link npc with above id. The above id is mentioned by Zinius.

Commander Schnottz is present but doesnt have quests. It seems to be of a different id. The current one is also phased.

He should have quests starting Gobbles! id27950

**Comment by Echinaceax** [comment]
https://www.wowhead.com/npc=47159/commander-schnottz for the quest https://www.wowhead.com/quest=27950/gobbles

**Comment by Rushor** [comment]
okay i'm at famaily now. added him, pls test if correct phase

guid 89758

**Comment by Echinaceax** [comment]
Correct now @Rushor the Gobbles quest comes after the completion of the other 3 quests he starts with now 

![gobbles next](https://user-images.githubusercontent.com/39439201/71309944-396fed00-240e-11ea-87a4-8f0adb1e7020.jpg)

**Comment by Echinaceax** [comment]
note@ that in order to get the quests you must get the https://www.wowhead.com/item=62768/efficient-excavations drop that starts the quest line
