### ISSUE TITLE
[Quest] Close Escort - Deepholm

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#4112]
**Links:**
https://www.wowhead.com/quest=26632/close-escort#videos

**What is happening:**

Peak Grindstone doesn't giving you the option to escort the catapult.

**What should happen:**

Peak Grindstone have a talking option to make the catapult start moving and then you should be able to escort it to its destination.

**Comment by Rushor** [comment]
... https://github.com/WoWManiaUK/Blackwing-Lair/issues/1992
