### ISSUE TITLE
Disconnecting/logging out removes you from party groups

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#4114]
Been happening since the last update.

**Comment by Rushor** [comment]
This is keader

**Comment by questbugreporter** [comment]
Doesn't seem to happen in raids

**Comment by Keader** [comment]
It always happened to me

**Comment by questbugreporter** [comment]
@Keader Not sure what you mean. If you mean that this happened before the update, it didn't.
I also don't understand why the high prio tag was removed. Whenever someone gets a crash, disconnect or just relogs to fix some bug, they get removed from the dungeon group. This ruins the run for the dced player and, very often, the remaining four players.

**Comment by dxbali** [comment]
I can confirm that this is a bug and shouldn't happen and it should be fixed asap along with other bugs that are causing lag for party/raid members that are not in the same zone

**Comment by Keader** [comment]
Fixed, now people will stay on groups when logout.
