### ISSUE TITLE
Summoned Guardians

### ISSUE THREAD

**Issue by Javalapa** [WoWManiaUK/Blackwing-Lair#4116]
**What is happening:**

Summoned Guardians such as Fire Elemental Totem, Doomguard, Ebon Imp, etc., deal far less damage than they should, and some don't even use their intended spells, specifically the Doomguard using melee attacks for 48 damage instead of its spells.

**What should happen:**

Summoned Guardians should use their intended spells and be used as strong strong DPS cooldowns

**Comment by Demoniakk** [comment]
https://youtu.be/vOlY7okAvCs?t=351 - Doombolt still not there!

**Comment by mfranca0009** [comment]
#3685
#2305 
#2195 
#2172 

All currently open issues related to class spell summons or pets above. Since this is more of a generic issue related to most of the pets that are in their own issue, closing this one out.
