### ISSUE TITLE
Poseidus Loot

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#4119]
**Links:**
https://www.wowhead.com/npc=50005/poseidus

**What is happening:**

After the update that made Poseidus give out VP, I have killed him  3 times and he didn't drop any epic items (apart from the mount).

**What should happen:**

Some wowhead comments mention that he's supposed to drop a guaranteed BoE world drop epic.
This is how it worked on Reign before.

**Comment by Rushor** [comment]
fixed https://i.imgur.com/N3ZgxZt.jpg
