### ISSUE TITLE
[Spell] Main Gauche procs don't trigger  Blade Flurry

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#4124]
**Links:**
http://cata.cavernoftime.com/spell=13877
https://www.wowhead.com/spell=13877/blade-flurry#changelog
https://www.wowhead.com/spell=76806/mastery-main-gauche

Hits from the combat rogue mastery, Main Gauche, do not cause Blade Flurry to deal damage to a nearby enemy.

**Comment by Keader** [comment]
fixed folks
