### ISSUE TITLE
[Spell] "Nothing to dispel"

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#4126]
**Links:**
https://www.wowhead.com/news=151398/changes-to-dispels-in-cataclysm

**What is happening:**

You cannot cast dispelling spells on targets with no valid debuffs.

**What should happen:**

>In Cataclysm we are raising the mana costs, making it possible to waste mana by casting a dispel when there is nothing to dispel

You should be able to waste dispels by using them on non-afflicted targets.

Affected Spells:

Paladin: 4987 and 53551
Druid: 2782 and 88423
Shaman: 51886 and 77130
Priest: 527, 518 and possibly 32375 and 33167 (I don't know much about priests)

I have only tested paladin and druid, others I just assume work the same way.

**Comment by Hespericless** [comment]
I can confirm this applies to every dispel except for priest's Mass Dispell.

**Comment by mfranca0009** [comment]
Removed the check for "allowable" dispel scenarios. This should make it where the dispel will be cast even if there isn't a debuff present on the target and it will cast as normal; wasting mana.

It should not provide the "Nothing to Dispel" error message anymore.

![image](https://user-images.githubusercontent.com/26092980/107886748-002af400-6ed0-11eb-92ee-52a02d9d2c35.png)

**Comment by golosomie** [comment]
@mfranca0009 Confirmed fixed on PTR for Cleanse Spirit, Remove Corruption, Remove Curse, Cleanse, Curse Disease and Dispel magic.
