### ISSUE TITLE
[Quest] Dissension Amongst the Ranks .... {Qid:10776}  - Shadowmoon Valley

### ISSUE THREAD

**Issue by glcabatuan** [WoWManiaUK/Blackwing-Lair#4128]
**Quest:** http://cata.cavernoftime.com/quest=10776
**NPC/s:**  http://cata.cavernoftime.com/npc=22051
**Item/s:**  http://cata.cavernoftime.com/item=31279
**Object/s:** 
**Spell/s:** 

**Current State:** 
Eventhough the http://cata.cavernoftime.com/item=31279 is worn and kills a http://cata.cavernoftime.com/npc=22051, no kill credits for the quest.

**Expected State:** 

Killing http://cata.cavernoftime.com/npc=22051 while wearing http://cata.cavernoftime.com/item=31279 should credit as a kill count for the quest

As shown in :  https://www.youtube.com/watch?v=QwoJUHqh8K0&t=440s

**Comment by Rushor** [comment]
fixed https://i.imgur.com/b41kkva.jpg
