### ISSUE TITLE
[Quest] Divination: Gorefiend's Truncheon {Qid:10636} - Shadowmoon Valley

### ISSUE THREAD

**Issue by glcabatuan** [WoWManiaUK/Blackwing-Lair#4129]
**Quest:** http://cata.cavernoftime.com/quest=10636
**NPC/s:** http://cata.cavernoftime.com/npc=21784
**Item/s:** http://cata.cavernoftime.com/item=30800
**Object/s:** 
**Spell/s:** 

**Current State:** 
I have traversed the entire path for hours such as the image below
[`https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwjewqr8mdPmAhWSd94KHaCGDgwQjRx6BAgBEAQ&url=http%3A%2F%2Fgranstonsguide.com%2Fquests.php%3Fz%3DShadowmoon%2520Valley%26s%3Dalpha%26e%3Dshadowmoon_valley%2Fquests%2F490.jpg&psig=AOvVaw0YmlYOXZ4cNxJwvSBl3cEi&ust=1577445879203120`](url)

But unfortunately, no http://cata.cavernoftime.com/npc=21784 patrolling around

**Expected State:** 
The  http://cata.cavernoftime.com/npc=21784 should exist patrolling the path shown above with which been killed loots the http://cata.cavernoftime.com/item=30800

As shown in: https://youtu.be/ixjLdun9xUg?t=89

**Comment by Rushor** [comment]
fixed https://i.imgur.com/HqrZTzn.jpg
