### ISSUE TITLE
[Quest] Homing Robot OOX-22/FE - ID 8705 -  Feralas

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#413]
- Dropped quest

- Drop - https://www.wowhead.com/item=8705/oox-22-fe-distress-beacon
Quest - https://www.wowhead.com/quest=2766/find-oox-22-fe
NPC - https://www.wowhead.com/npc=7807/homing-robot-oox-22-fe

- Completed but ...

- Then this quest is to rescue him, but he doesn't move to rocket himself to Booty-Bay
- Cant complete

Quest - https://www.wowhead.com/quest=25476/rescue-oox-22-fe
Video - https://www.wowhead.com/quest=25476/rescue-oox-22-fe#videos:id=3121

**Comment by BlueDragonKing7** [comment]
Tried to do this quest, still not working

**Comment by glcabatuan** [comment]
**Quest:**  http://cata.cavernoftime.com/quest=25476
**NPC/s:** http://cata.cavernoftime.com/npc=7807
**Item/s:** 
**Object/s:** 
**Spell/s:** 

**Current State:** 
The http://cata.cavernoftime.com/npc=7807 don't bother to move.

**Expected State:** 

The http://cata.cavernoftime.com/npc=7807 should automatically walk outside the cavern

As shown in : https://www.youtube.com/watch?v=U23z47OVL80

**Comment by Rushor** [comment]
all fixed https://i.imgur.com/tZfZcND.jpg

http://cata.cavernoftime.com/quest=25476
