### ISSUE TITLE
[Quest] Of Thistleheads and Eggs {Qid: 10547 } -Shadowmoon Valley 

### ISSUE THREAD

**Issue by glcabatuan** [WoWManiaUK/Blackwing-Lair#4130]
**Quest:**  http://cata.cavernoftime.com/quest=10547
**NPC/s:** 
**Item/s:**  http://cata.cavernoftime.com/item=30500
**Object/s:**  http://cata.cavernoftime.com/object=184796
**Spell/s:** 

**Current State:** 
The http://cata.cavernoftime.com/object=184796 can be seen but non-interactive. Can't be picked up  to achieve http://cata.cavernoftime.com/item=30500

**Expected State:** 
http://cata.cavernoftime.com/object=184796 could be interacted with and collect http://cata.cavernoftime.com/item=30500

As shown in : https://youtu.be/GZz6CyM0mU4?t=21

**Comment by Rushor** [comment]
fixed https://i.imgur.com/NpQz7CH.jpg
