### ISSUE TITLE
[Quest] The Deadliest Trap Ever Laid {Qid:11101} - Shadowmoon Valley

### ISSUE THREAD

**Issue by glcabatuan** [WoWManiaUK/Blackwing-Lair#4131]
**Quest:**  http://cata.cavernoftime.com/quest=11101
**NPC/s:**  http://cata.cavernoftime.com/npc=23139
**Item/s:**  http://cata.cavernoftime.com/item=32853
**Object/s:** 
**Spell/s:** 

**Current State:** 
Now, the quest for atttacking and defeating the dragonmaw clan is doable. But, once I get the
http://cata.cavernoftime.com/item=32853 and try to submit (complete) it with http://cata.cavernoftime.com/npc=23139 , the complete button is not clickable

**Expected State:** 
Should be clickable to hand in the  http://cata.cavernoftime.com/item=32853 to complete the daily quest.

As shown in: https://youtu.be/Z7cLrigx_3Y?t=285

**Comment by Rushor** [comment]
fixed https://i.imgur.com/kEX7pHD.jpg
