### ISSUE TITLE
Darkened Creation - Debilitating Beam - The Bastion of Twilight

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#4132]
**Links:**
https://www.wowhead.com/npc=44045/darkened-creation
https://www.wowhead.com/spell=82411/debilitating-beam
**What is happening:**

These mobs cannot be interrupted.

**What should happen:**

This spell should be interruptible like the dungeon journal says:
![image](https://user-images.githubusercontent.com/56992013/71549749-40c56680-29cb-11ea-91fb-0d01696063ca.png)

**Comment by Hespericless** [comment]
@Keader Still uninterruptible on dev realm

**Comment by mfranca0009** [comment]
All set, should be working 👍

**Comment by Echinaceax** [comment]
confirmed fix is ptr 

interupted the casting of Debilitating Beam

![image](https://user-images.githubusercontent.com/39439201/107153648-f143bf00-696e-11eb-9c80-9e5717dce3a7.png)

and interupted the actual beam too 

![inter](https://user-images.githubusercontent.com/39439201/107153716-3ff15900-696f-11eb-91d0-ad15dbf0dacb.jpg)
