### ISSUE TITLE
[NPC] Onslaught Commander Iustus - 27334 - Dragonblight - incorrect health

### ISSUE THREAD

**Issue by Druhl** [WoWManiaUK/Blackwing-Lair#4134]
https://www.wowhead.com/npc=27334/onslaught-commander-iustus

I one-shotted him with an at-level character. I waited for him to respawn to be sure. He has only 2 HP.

![WoWScrnShot_123119_142606](https://user-images.githubusercontent.com/19803911/71631910-8192ca80-2bd9-11ea-81d5-758e15c5b6bd.jpg)

**What should happen**
He should have (Health: 8,200)

**Comment by Rushor** [comment]
hp fixed https://i.imgur.com/Bqel0ZN.jpg
