### ISSUE TITLE
[Quest]  We Call Him Steelfeather {Qid: 11418}  (issue 2) - Howling Fjord

### ISSUE THREAD

**Issue by glcabatuan** [WoWManiaUK/Blackwing-Lair#4135]
**Quest:**  http://cata.cavernoftime.com/quest=11418
**NPC/s:**  http://cata.cavernoftime.com/npc=24514
**Item/s:**  http://cata.cavernoftime.com/item=34026
**Object/s:** 
**Spell/s:**  http://cata.cavernoftime.com/spell=43969

**Current State:** 

Quest Update from #1364 .   http://cata.cavernoftime.com/npc=24514 is not existing anymore. Waited for an hour circling around the camp but still no sign of it. 

**Expected State:** 
http://cata.cavernoftime.com/npc=24514 should be seen circling around mid air within the camp

As shown in: https://www.youtube.com/watch?v=hJSdJmEf-Lo

**Comment by Echinaceax** [comment]
Steelweather is here, i had a GM check it 

![steelfeather is here](https://user-images.githubusercontent.com/39439201/71644235-4a99e300-2cc5-11ea-8fb0-f9a8b50b12c7.jpg)

was at 62,34  16.31 a few mins ago

**Comment by Rushor** [comment]
issue was: creature always despawns at waypoint 5.

now: creature will always repeat path. if someone uses questitem on him > credit will be given > creature will despawn.

That's how it must work.

https://i.imgur.com/JuRdUrP.jpg
https://i.imgur.com/bzh7QyI.jpg
