### ISSUE TITLE
[Quest] It's All Fun And Games - 12892 - Icecrown

### ISSUE THREAD

**Issue by Druhl** [WoWManiaUK/Blackwing-Lair#4143]
https://www.wowhead.com/quest=12892/its-all-fun-and-games

**What should happen:**
Provided item (https://www.wowhead.com/item=41265/eyesore-blaster) is used to attack "The Ocular" (https://www.wowhead.com/npc=29747/the-ocular", repeating until destroyed

**What does happen:**
Each use of Eyesore Blaster removes about 10% of The Ocular's health, but it resets immediately to full health after each use. Quest can not be completed.

**Comment by Rushor** [comment]
reggen issue fixed with next updae
