### ISSUE TITLE
[Quest] Get The Message - 13314 - Icecrown

### ISSUE THREAD

**Issue by Druhl** [WoWManiaUK/Blackwing-Lair#4145]
https://www.wowhead.com/quest=13314/get-the-message

_also daily:_
https://www.wowhead.com/quest=13333/capture-more-dispatches

**What should happen:**
Player uses quest-issued item (https://www.wowhead.com/item=44222/dart-gun) to kill flying mobs (https://www.wowhead.com/npc=32201/orgrims-hammer-scout) whose corpses drop to ground so he can loot 6x (https://www.wowhead.com/item=44220/orgrims-hammer-dispatch).

**What does happen:**
Killed quest mobs remain at height they were killed, so looting them necessitates an aerial dismounting for the player and usually a fatal fall. Other than this, with required number of quest objectives collected, quest can be completed and handed in normally.

![WoWScrnShot_010320_161024](https://user-images.githubusercontent.com/19803911/71769021-d7bd8180-2ee9-11ea-90df-6c576e26f6e0.jpg)

![WoWScrnShot_010320_161036](https://user-images.githubusercontent.com/19803911/71769024-dbe99f00-2ee9-11ea-875e-e27b11759e16.jpg)

**Comment by Rushor** [comment]
item will be added instant on kill now https://i.imgur.com/t5HY47Y.jpg

effective workaround
