### ISSUE TITLE
Bellies Await (Q-Id 25540) -  Shimmering Expanse

### ISSUE THREAD

**Issue by DarkicecKelthuss** [WoWManiaUK/Blackwing-Lair#4149]
**Links:**

from WoWHead or our Armory

**What is happening:**

Vashj Ir Quest: https://www.wowhead.com/quest=25540/bellies-await

After finishing the PreQuest Odor Coater with the BQ Command, it leads up to this one.
After visiting the Cave and looking twice for the Quest Giver called Wavespeaker Valoren, he just isnt there.
Please Fix THis

**What should happen:**

https://www.wowhead.com/quest=25540/bellies-await#videos:id=87786
The Quest Giver is not inside the Cave.

Thanks

**Comment by Echinaceax** [comment]
Confirmed npc missing

**Comment by Echinaceax** [comment]
@Rushor did you send fix to jani?
still not on live
