### ISSUE TITLE
[NPC] Ysondre - missing from The Emerald Summit - Feralas

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#415]
- NPC is missing 
Quest - https://www.wowhead.com/quest=25378/ysondres-call
npc - https://www.wowhead.com/npc=39407/ysondre

**Comment by Dranah** [comment]
Confirmed, NPC missing.
The prerequisite works as intended, you need to complete the dryad quest before accepting this one.
Ysondre is currently only spawned at Dreamer's Rest, she's missing from the "Emerald Summit"
