### ISSUE TITLE
[General/Worgen] Mallstone issue

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4156]
**What is happening:**
Worgens are becoming bugged again due to x4 XP weekends, this means they lvl to fast , get their Mallstone and go to the mall for a look or skip questline, which then bugs the worgen and requires GMs help to phase them back 

**What should happen:**
Dont give Worgens the Mallstone (same as DKs) 

1. they can get one from the Innkeeper just like DKs in main city
2. set to recieve at lvl 20 

this will cause less worgen issues

**Comment by Kitzunu** [comment]
Does this need doing to Goblins as well?

**Comment by Echinaceax** [comment]
@Kitzunu Goblins is sorted thanks :)
Rushor set Goblins to get auto tele to ORG after they complete the first part of their start questline

**Comment by Rushor** [comment]
both - worgen and goblin get it with level 20 now

**Comment by Rushor** [comment]
@Echinaceax
