### ISSUE TITLE
Dalaran forges not functional

### ISSUE THREAD

**Issue by Druhl** [WoWManiaUK/Blackwing-Lair#4158]
**What is happening:**
The forge in the "Tanks for Everything" shop and in the "Forge of Fate" next to it are not working as forges. When attempting to smelt ore, I get the "Requires Forge" on-screen error.

**What should be happening:**
These should work as forges.

![WoWScrnShot_010720_210401](https://user-images.githubusercontent.com/19803911/71944414-ae268380-3191-11ea-96f5-68a606cede39.jpg)

![WoWScrnShot_010720_210503](https://user-images.githubusercontent.com/19803911/71944425-b7175500-3191-11ea-99fb-91dc1caf1d23.jpg)

**Comment by Echinaceax** [comment]
@Rushor - i confirm no forges working
i did also check on Minia where i use too forge and it was next door here (42,75, 26,17)

![should be here](https://user-images.githubusercontent.com/39439201/71988198-bc2ae180-322f-11ea-9aca-dc5e93b21525.jpg)

but this is also not working here on Reign
