### ISSUE TITLE
[NPC] Brashtide Raider - 0 HP and dont die - Bootybay

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4159]
**Links:**
https://www.wowhead.com/npc=43716/brashtide-raider

![brashtide raider](https://user-images.githubusercontent.com/39439201/72003112-03719c00-3249-11ea-9d35-526b616ce15b.jpg)

**What is happening:**
- They get to 0% hp and still dont die

**What should happen:**
Should die when no hp :)

**Comment by Rushor** [comment]
well no i added that https://i.imgur.com/Z94RaId.jpg
so the both creatures does not kill each other and instead only the player can kill them :)

the hp thing is a visual bug
