### ISSUE TITLE
Quest: From the Mouth of Madness (ID: 25297) Zone: Mount Hyjal

### ISSUE THREAD

**Issue by DarkicecKelthuss** [WoWManiaUK/Blackwing-Lair#4160]
https://www.wowhead.com/quest=25297/from-the-mouth-of-madness

from WoWHead or our Armory

I think its rather an Issue with Phasing then actually a bugged quest:
>How can i tell it:
Easily, cuz when you stand at Gar`gol`s Hovel or at the Maw of Lycanthooth you see the Bitterblossoms by the coast of the small Island, at the Shrine of Goldrinn. Problem is as soon as you fly over the river to the Shrine, the Blossoms disappear.

**What should happen:**
Here is a video :) https://www.wowhead.com/quest=25297/from-the-mouth-of-madness#videos:id=73093
Pictures; AT phazing Sone you can see the blossom
https://gyazo.com/5042673d7945e2e02dddd6b5886080b5

and within the Zone you cant
https://gyazo.com/cf3c3b0c396b715eeb45873eb279ed56

Please fix this Issue.

Thanks 👍

**Comment by Echinaceax** [comment]
reported here on main phase report #2846 
but thanks @DarkicecKelthuss
