### ISSUE TITLE
Quest: Seeds of Discord (Mount Hyjal) (ID: 25308)

### ISSUE THREAD

**Issue by DarkicecKelthuss** [WoWManiaUK/Blackwing-Lair#4161]
**Links:**
https://www.wowhead.com/quest=25308/seeds-of-discord
from WoWHead or our Armory

**What is happening:**
You go (disguised) to Karr'gonn, but cant talk to him.

**What should happen:**
Here a Video:
You have the Disguise on, but cant speak to Karr'gonn the Ogre.
https://www.wowhead.com/quest=25308/seeds-of-discord#videos:id=72599

**Comment by Echinaceax** [comment]
Reported here #2767
