### ISSUE TITLE
Quest: Graduation Speech Mount Hyjal (ID:25315)

### ISSUE THREAD

**Issue by DarkicecKelthuss** [WoWManiaUK/Blackwing-Lair#4162]
**Links:**
https://www.wowhead.com/quest=25315/graduation-speech
from WoWHead or our Armory

**What is happening:**
The  Initiation Podium is missing infront of Commander Jarod.
It is normally between him and the Publicum.

**What should happen:**
Here a video what should happen.
https://www.wowhead.com/quest=25315/graduation-speech#videos:id=65068

**Comment by Echinaceax** [comment]
reported here #3506
but thanks @DarkicecKelthuss
