### ISSUE TITLE
[NPC] Whitetail Stag (Skinning issue)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4163]
**Links:**

https://www.wowhead.com/npc=140735/whitetail-stag#skinning

![not skinable](https://user-images.githubusercontent.com/39439201/72094126-025a7080-3316-11ea-8cd9-0543ca392380.jpg)

**What is happening:**
- Unable to skin this beast
- no lvl no skinnable icon or skinable info on mouseover

**What should happen:**
Should be skinnable

side note:
Added in patch 8.0.1.26530

**Comment by Rushor** [comment]
loot and icon added :)
