### ISSUE TITLE
[NPC] Consumed Thistle Bear (skinning issue) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4164]
**Links:**
https://www.wowhead.com/npc=34302/consumed-thistle-bear#skinning

**What is happening:**
- Unable to skin this beast
- no lvl no skinnable icon or skinable info on mouseover

**What should happen:**
Should be skinnable

**Comment by Rushor** [comment]
https://i.imgur.com/MAfdqbo.jpg skinning option and loot added
