### ISSUE TITLE
[Quest] [Looks Like a Tauren Pirate to Me] qid 26630 Booty Bay

### ISSUE THREAD

**Issue by Phoenixion** [WoWManiaUK/Blackwing-Lair#4166]
**Links:**
quest:
https://www.wowhead.com/quest=26630/looks-like-a-tauren-pirate-to-me

npc:
https://www.wowhead.com/npc=2487

**What is happening:**
1. When speaking to Narrk the goblin, there's no option to ask him the Oversized Pirate Hat.
2. When speaking to Bossy the cow, there's no option to "ask" her the Cow Head.

**What should happen:**
Those options should've been available from the respective NPCs when you talked to them after accepting the quest.

**Comment by Echinaceax** [comment]
reported already here #720
