### ISSUE TITLE
[NPC] King Crawler (not skinnable)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4167]
**Links:**

https://www.wowhead.com/npc=51714/king-crawler#skinning

**What is happening:**
- missing skinning ability

**What should happen:**
Should be skinnable (needed to test something and noticed it)

**Comment by Kitzunu** [comment]
@Echinaceax Please test again :)

**Comment by Echinaceax** [comment]
ok , logging in :P

**Comment by Kitzunu** [comment]
Appreciated!

**Comment by Echinaceax** [comment]
confirmed fix @Kitzunu, thanks :)

**Comment by Kitzunu** [comment]
skinning_loot_template
---
```sql
SELECT entry, item, chance, mincount, maxcount FROM `skinning_loot_template` WHERE `entry` = 51714
```
| entry | item | chance | mincount | maxcount | 
| ---: | ---: | ---: | ---: | ---: | 
| 51714 | 52982 | 30 | 1 | 6 | 

For anyone who is interesting in the rates
