### ISSUE TITLE
[Spell] Glyph of Invisibility - no effect

### ISSUE THREAD

**Issue by Druhl** [WoWManiaUK/Blackwing-Lair#4175]
http://cata.cavernoftime.com/item=42748

**What should happen:**
Player run speed should get 40% buff when invisible

**What does happen:**
No buff.

Screenshots show run speed (via a speed meter) visible and invisible, no change.

![WoWScrnShot_012020_130247a](https://user-images.githubusercontent.com/19803911/72748898-81f20600-3b86-11ea-9754-b4d5e67c0ad9.jpg)

![WoWScrnShot_012020_130253b](https://user-images.githubusercontent.com/19803911/72748904-88807d80-3b86-11ea-9803-917fe863f8ea.jpg)

![WoWScrnShot_012020_130300c](https://user-images.githubusercontent.com/19803911/72748908-8cac9b00-3b86-11ea-8468-dcea88064928.jpg)

![WoWScrnShot_012020_130304d](https://user-images.githubusercontent.com/19803911/72748917-8fa78b80-3b86-11ea-8fda-f8d8b2d57fde.jpg)

**Comment by Myst** [comment]
I have the fix, where to post it?

**Comment by Echinaceax** [comment]
Hi @Myst do you have discord?

**Comment by mfranca0009** [comment]
All set, Glyph of Invisibility will add the 40% movement speed buff and when invisibility expires (no longer invisible) then the 40% movement speed increase will be removed.

**Comment by Echinaceax** [comment]
from what i see @mfranca0009 
no change 

no invis 108%

![rs1](https://user-images.githubusercontent.com/39439201/107885416-85c39980-6efa-11eb-9bcf-6001f2f13591.jpg)

with invis and glyph still 108%

![rs2](https://user-images.githubusercontent.com/39439201/107885430-95db7900-6efa-11eb-8739-825dafa2a3f6.jpg)

**Comment by Echinaceax** [comment]
confirmed fixed in PTR using new fresh mage

![image](https://user-images.githubusercontent.com/39439201/107886242-e81e9900-6efe-11eb-8acd-50d022fa2d2b.png)
