### ISSUE TITLE
[Quest] Gunk in the Trunk - 14209 - Azshara

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4182]
**Links:**

https://www.wowhead.com/quest=14209/gunk-in-the-trunk

**What is happening:**
- Cant Inspect Clubnik's Dozer

**What should happen:**
_Inspect Clubnik's Dozer and collect a sample of the Ectosplatter that's gumming up the engine._
https://www.wowhead.com/quest=14209/gunk-in-the-trunk#videos:id=35974

Reported from GM from ingame ticket
confirmed in dev by me

**Comment by Rushor** [comment]
added a spawn for npc 35558 , so you can kill and get the questitem
