### ISSUE TITLE
Quest:  A Prayer and a Wing #25664

### ISSUE THREAD

**Issue by eabyss-source** [WoWManiaUK/Blackwing-Lair#4186]
Quest requirement> Use an Item to summon an NPC at a specific location. 
Gameobject (Nest) disappears due to zoning issues. 
You can see the NPCS/Quest Objectives/Gameobjects whilst being in the zone "Shrine of Aviana" as soon as you leave the zone they all disappear. 
Quest Objective is outside of the Zone (Rim of the World)

https://gyazo.com/9055260ef594566051f3b2d851eddb9f

**Comment by eabyss-source** [comment]
- Quest> Scrambling for Eggs #25656 is also affected by this.

**Comment by Echinaceax** [comment]
all these have been added to main report as it is only a phasing issue #2846
