### ISSUE TITLE
Minor, Quest - "An Ancient Enemy"

### ISSUE THREAD

**Issue by Hobart2967** [WoWManiaUK/Blackwing-Lair#4187]
**Links:**
https://www.wowhead.com/quest=24814/an-ancient-enemy
from WoWHead or our Armory

**What is happening:**
When completing the scenery where Voljin and the Hero should kill the "Boss", Vol'Jin is not reset to a "Non-Speakable" NPC. Instead, you can talk to him and say "I am ready". This, as a consequence, has the result that Vol'Jin moves forward like 10 meters everytime you talk to him. Until he's standing in the sea :D :D :D

The quest itself is completable though.

**What should happen:**
After the fight, he should not be having an option saying "I'm ready"

**Comment by Hobart2967** [comment]
And I think the quest itself including the whole cutscenes and stuff is completely different

**Comment by Echinaceax** [comment]
its reported here already @Hobart2967 #1514
