### ISSUE TITLE
Unoperable Quest: Cleaning up the coastline

### ISSUE THREAD

**Issue by Hobart2967** [WoWManiaUK/Blackwing-Lair#4188]
**Links:**
https://www.wowhead.com/quest=25170/cleaning-up-the-coastline
from WoWHead or our Armory

**What is happening:**
Accepting the quest works, but when accepting, the NPC giving the quest should hand out a Totem. This is not happening. The totem is required to gain the "Crawler Mucus" (https://www.wowhead.com/item=4888/crawler-mucus).

The trigger to set the totem seems to work though. But with no totem, no mucus' :)

**What should happen:**
The totem should be hand out.

**Comment by Echinaceax** [comment]
this isnt the one with the totem, this quest is just kill and loot 
https://www.wowhead.com/quest=25170/cleaning-up-the-coastline#videos:id=35424
