### ISSUE TITLE
[NPC] Faldren Tillsdale / Jamus'Vaz        <Valorous Quartermaster>

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4189]
**Links:**

http://cata.cavernoftime.com/npc=44245#.
https://www.wowhead.com/item=58482/treads-of-fleeting-joy

item http://cata.cavernoftime.com/item=58482

**What is happening:**
Its been brought to my attention that this NPC is missing from stormwind, i have confirmed him missing on DEV, But the thing is: cata.cavernoftime and atlasloot both say should be from _Faldren Tillsdale <Valorous Quartermaster>_ 

but Our vendor is _Toren Landow <Legacy Justice Quartermaster>_ and this vendor isnt showing up on cata.cavernoftime site at all...so as we are using cata.cavernoftime as the Reign armory, which is the correct info for this issue ? 

Our vendor for (valor points) instead of Justice points

![same item here](https://user-images.githubusercontent.com/39439201/73593514-8367ea80-4505-11ea-8265-88814d3c8404.jpg)

atlasloot for (Justice points)

![atlasloot](https://user-images.githubusercontent.com/39439201/73593553-c3c76880-4505-11ea-86f6-f7c5196125fa.jpg)

And cata.cavernoftime for (gold)

![gold](https://user-images.githubusercontent.com/39439201/73593651-b3fc5400-4506-11ea-8430-f78d238a0e8b.jpg)

We are patch 4.0.3 so wowhead is correct right?
I know the vendor _Faldren Tillsdale <Valorous Quartermaster>_ also sells HC 372 Gear so is that why the vendor isnt here maybe?

Reported by Mikx

**Comment by Echinaceax** [comment]
More info 

i just spawned  _Faldren Tillsdale_ to check his gear for sale and its 384 and 397 lol

**Comment by Rushor** [comment]
Yep we removed him cuz of item Level but i will check again

**Comment by Rushor** [comment]
yes let him despawned

look here: 
https://www.wowhead.com/item=59318/sark-of-the-unwatched
https://www.wowhead.com/item=59506/crushing-weight

those are items from current higest raid instance on realm. would not be good to just sell them :)

**Comment by Echinaceax** [comment]
> those are items from current higest raid instance on realm. would not be good to just sell them :)

exactly its why i said **_i just spawned Faldren Tillsdale to check his gear for sale and its 384 and 397 lol_**
