### ISSUE TITLE
[NPC] Chris Moller <Pie Vendor>

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4190]
**Links:**
No info from http://cata.cavernoftime.com/
https://www.wowhead.com/npc=44125/chris-moller
https://cata-twinhead.twinstar.cz/xkjqzjlx.html?npc=44125

**What is happening:**
- doesnt sell anything 

**What should happen:**
should sell stuff

**Comment by Rushor** [comment]
done https://i.imgur.com/GMqSIcg.jpg
