### ISSUE TITLE
[General] Hearthstone issue (Stuck in empty Gilneas) 

### ISSUE THREAD

**Issue by focarol** [WoWManiaUK/Blackwing-Lair#4194]
Hello, i hope i do this right here.

My lvl 18 Hunter "Ezzra" is stucked in Gilneas.
Because i used the Heartstone and got back to Gilneas.
I cannot walk out of Gilneas - Wall is closed.
I guess committing suicide in the sea or using Heartstone again is not useful.

I think it is a Phasing-Issue.
From the story aspect - i was in Darnassus and i have to get back there.

Please - can a GM just port my Character back to Darnassus?

- Name: Ezzra
- Class: Hunter
- lvl: 18
- Position: Boat in Gilneas

best regards
Ezzra

**Comment by Echinaceax** [comment]
@focarol
Unfortunately GMs do not help in this matter anymore, Reason being there is an announcement in discord about it, 

I tested this a few days ago fully and there is no bug within the worgen zone. you chosing not to finish your questline first before moving is actually not a bug.

**Comment by focarol** [comment]
Hello Echinaceax

I fully understand, if you won't help. Because there might be a lot of abuse in case of GM-Power.

If you can just tell me how to fix it by myself, i will do it.

I explain shortly a bit better the issue:

My Quest status for "Battle for Gilneas City" is:
[10] The Howling Oak
https://wow.gamepedia.com/The_Howling_Oak_(quest)

i was questing all the beginner-quests in Teldrassil to farm already reputation for Darnassus.

and then i thought to port back with hearthstone to Darnassus-City but i stranded in Gilneas. It seemed my hearthstone was bound there somehow.

I have no idea about Mall-Stone i have only Hearthstone in my pockets.


When you can help me to bound my hearthstone to Darnassus - i can port by myself.

sorry for my bad english - not my mother language.

**Comment by Echinaceax** [comment]
> questing all the beginner-quests in Teldrassil to farm already reputation for Darnassus.

yes, but how where you in Teldrassil if you hadnt completed the startzone?

**Comment by Echinaceax** [comment]
Yes i have read up where you are

**Comment by Echinaceax** [comment]
Tested and cant reproduce the bug

@focarol make sure your using the Reign launcher that came with your Download
Delete cache and reset your Innkeeper 

GM has ported you to https://www.wowhead.com/npc=35840/gwen-armstead

**Comment by focarol** [comment]
Hello Echinaceax

at first, thank you that you keep on finding a solution. Your time you spend is highly appreciated.
I'm actually not at home, so i cannot be helpful from my side.

I think my whole issue isn't really a BUG.
It was just unpleasant, that my Hearthstone was somehow still bound to Gilneas. Because my quest-Status is "The Howling Oak". That's why is Gilneas completely empty because the whole Story for the Worgen continues in Darnassus.

to your numbers:

1.
The "wow.exe" from WoW-Reign gave me a weird error message from the start. Like if i really want to open this .exe File.
I found this suspicious.
With 'RetroWoW' , 'WoW-Mania' an other clients i didn't had that message.
Have i got an corrupted Download?

2.
Thanks for the Teleport - but how does it help me now, standing in Gilneas at Gewn Armstead?

I guess reseting 'Cache' means deleting the Cache-folder in the wow directory.
But how do i reset my Hearthstone?

Do i have to cancel the quest "The Howling Oak" - will i be ported back to gilneas then?

<br>
<br>
Just to mention it here (you might relocate that):
i had a real big BUG in my playthrough so far:

i got the quest:
"The Battle for Gilneas City"
and i somehow got directly to the status of:
"Slowing the Inevitable".

I watche a Let's Play on YouTube and i saw that i missed a bigger story part.
Two Quests were skipped completely:
"The Hunt For Sylvanas" and "Vengeance or Survival"

**Comment by focarol** [comment]
Ahhh....sorry
i got it
Gwen Armstead is already in Darnassus
There i will reset/bound my Hearthstone to her.

Thank you so much. I assume - This will help.

I really like questing.
This is my first time playing Cataclysm at all - i stopped WoW at TBC in 2007.

**Comment by Echinaceax** [comment]
> The "wow.exe" from WoW-Reign gave me a weird error message from the start. Like if i really want to open this .exe File.
> I found this suspicious.
> With 'RetroWoW' , 'WoW-Mania' an other clients i didn't had that message.
> Have i got an corrupted Download?

yes seems like it 
Try using the repair.exe in you Wow Reign folder 1st :)
if not then just run the launcher.exe as admin

**Comment by Echinaceax** [comment]
> The Battle for Gilneas City

the The Battle for Gilneas City was set to auto complete due to item Expoit :)

**Comment by focarol** [comment]
Thank you very much Echinaceax
So i can play further once i go home from work.

i assumed that it was intended what happened with the quest "The Battle for Gilneas City".
good to know the reason now.

you are right this auto-complete quest has no connection to my initial problem.
Now i know to use the Hearthstone wisely - still checking were it is allocated.

i enabled the option for "low quests" - because my goal is to make all available quests. If this server would be crossfaction i would also do the horde-quest :)

**Comment by Echinaceax** [comment]
Your welcome @focarol :)
