### ISSUE TITLE
The Ancients' Ire

### ISSUE THREAD

**Issue by focarol** [WoWManiaUK/Blackwing-Lair#4197]
**Links:**
https://www.wowhead.com/quest=13514/the-ancients-ire#comments

**What is happening:**

It isn't possible to jump on this "Vengeful Protectors" (These walking trees)

**What should happen:**

Destroying shacks and Trolls on the back of these tree-war-machines.

<br>
**Additional**
<br>
I killed enough Trolls, but i cannot destroy the huts without this Vengeful Protector.
It seems there is more buggy on this questline. When i walked through the aisle to the small pit where the quests starts the trolls should be in fight with the nightelves. I guess so.
When i gone through there, the trolls were standing in groups on one position.

**Comment by Echinaceax** [comment]
Already reported here #1046

@focarol i would search the quest name / object name in search bar before writting your report, that way your not wasting your time for it to be closed as a duplicate report.

**Comment by focarol** [comment]
i still don't know how to finish the quest
i used: ".bq 13514"
but then it comes msg that quest isn't flagged as buggy

i tried - still, i cant jump on this tree

**Comment by Echinaceax** [comment]
Sorry didnt see your comment @focarol 
i helped yoou in discord now tho :)
