### ISSUE TITLE
[Item] Severed Arm - Dalaran 

### ISSUE THREAD

**Issue by Nellieb1y** [WoWManiaUK/Blackwing-Lair#4198]
**Links:**

https://www.wowhead.com/quest=13836/disarmed

**What is happening:**

Fished for well over an hour one day, and still trying.    Now trying other places.  The bloated slippery eel never comes.   There is an associated object to discover, a chest inside a cell nearby with bent bars.   But that also cannot be opened and the key never drops.     However, I do get camped by Manabonk and constantly sheeped... and sometimes he comes close and hits me.   First I have been attacked in WOW by a friendly green,    I had to turn the sound down and the camera away.  

**What should happen:**

The bloated slippery eel should be catchable in a reasonable amount of time with an appropriate fishing skill level.... mine is 450.   The chest should be openable somehow.   And most of all, make Manabonk killable.  That would be satisfying.

**Comment by Echinaceax** [comment]
https://www.wowhead.com/item=45323/severed-arm

**Comment by Echinaceax** [comment]
@Nellieb1y Manabonk will be fixed on live soon :)  https://github.com/WoWManiaUK/Blackwing-Lair/issues/1225#issuecomment-582442270

**Comment by Echinaceax** [comment]
Need rechecking @Rushor Still not dropping and ive fished her for a while

**Comment by Echinaceax** [comment]
gps @mfranca0009 

![image](https://user-images.githubusercontent.com/39439201/113555732-b02cfb80-95fb-11eb-8199-c545e27eb5c9.png)

**Comment by Echinaceax** [comment]
adding to main report #5181

**Comment by Echinaceax** [comment]
fixed and confirmed fixed in dev
