### ISSUE TITLE
[Spell] Victory Rush

### ISSUE THREAD

**Issue by Uncle1** [WoWManiaUK/Blackwing-Lair#42]
Spell=34428

The spell dont consume the effect, that means that the warrior can heal themselves an ammount of 20% life each second (global ability coldown). Also if u miss the hit (dodge, parry, evasion too) u still getting the healing.

How it should work:
Strikes the target, causing (200% of Attack power) damage and healing you for 20% of your maximum health. And if u miss u can try again till u hit, but u wont get the healing if u dont make any damage.
Only usable within 20 sec after you kill an enemy that yields experience or honor.

**Comment by Keader** [comment]
Fixed.
Test after next restart.

**Comment by Keader** [comment]
Fix confirmed in dev.
