### ISSUE TITLE
[Quest] Righteous Indignation - ID 27479- Eastern Plaguelands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#420]
Quest - https://www.wowhead.com/quest=27479/righteous-indignation
NPC - https://www.wowhead.com/npc=45736
Item - https://www.wowhead.com/item=61313
Killed the required mobs for this item however none seamed to be dropping, therefore unable to complete this quest.

**Comment by Echinaceax** [comment]
Same for Horde

- Not  dropping
