### ISSUE TITLE
[BOSS/Spell] Lightning blast - The Bastian of Twilight

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4202]
**Links:**

https://wow.gamepedia.com/Ascendant_Council

![lightning blast](https://user-images.githubusercontent.com/39439201/74115497-c5e99100-4baf-11ea-9aaf-c459947b5f3a.jpg)

**What is happening:**
- Lightning blast is hitting the whole raid

**What should happen:**
while it should only target the one who's tanking Arion

**Comment by Hespericless** [comment]
@Keader The boss isn't casting Lightning Blast after Disperse.

**Comment by Keader** [comment]
I found a core issue, so i remade the fix, using other approach.

**Comment by Hespericless** [comment]
The spell is now correctly hitting only the tank. Only issue found was a visual bug where it seems as it's hitting the whole raid but it isn't.
