### ISSUE TITLE
[Quest] Suspicious Hoofprints (Quest Double Ups) - Dustwallow Marsh 

### ISSUE THREAD

**Issue by Alethalen** [WoWManiaUK/Blackwing-Lair#4204]
**Links:**
https://classic.wowhead.com/quest=1284/suspicious-hoofprints
https://classic.wowhead.com/quest=1252

from WoWHead or our Armory

**What is happening:**

Double up Quests

**What should happen:**

Double ups on
QID:
1284
1252

Will add as they are found!

**Comment by Echinaceax** [comment]
Thank you @Alethalen 
Each quest need seperate report please so can you make https://classic.wowhead.com/quest=1252 a seperate one

**Comment by Kadajj** [comment]
Quest ID invalid though.

Suspicious Hoofprints: -ally: 27262
                                     -horde: 27259

Lieutenant Paval Reethe: -ally: 27264
                                        -horde: 27260

![WoWScrnShot_041220_120225](https://user-images.githubusercontent.com/38867875/79067187-9a6d4a80-7cb5-11ea-94bb-5386cc263d12.jpg)
![WoWScrnShot_041220_120359](https://user-images.githubusercontent.com/38867875/79067206-b5d85580-7cb5-11ea-91d4-a0635d2d19c1.jpg)

**Comment by Thelonnious** [comment]
I need more info here.

**Comment by Echinaceax** [comment]
@Xman993 From what ive read its giving both same quests but by 2 different npcs

i'll log dev and get info soon

**Comment by mfranca0009** [comment]
### Classic Quest IDs
**Alliance:** https://classic.wowhead.com/quest=1284/suspicious-hoofprints
**Horde:** https://classic.wowhead.com/quest=1268/suspicious-hoofprints

### Modern Quest IDs (After Classic)
**Alliance:** https://www.wowhead.com/quest=27262/suspicious-hoofprints
**Horde:** https://www.wowhead.com/quest=27259/suspicious-hoofprints

**Comment by mfranca0009** [comment]
Seems in the database, the classic quest IDs are stated as DEPRECATED, which means they should be disabled and they were not.

The Modern Quest IDs should now also have their proper "allowable factions" set so that Alliance should receive the Alliance quest and Horde should receive the Horde quest as it should be.

Needs testing in PTR 👍

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 

both factions
