### ISSUE TITLE
[Quest/Item] Mountain Giant Muisek - Feralas

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#421]
- Quest item not working
- Cant complete

Quest item - https://www.wowhead.com/item=9621/mountain-giant-muisek-vessel
Quest - https://www.wowhead.com/quest=25346/mountain-giant-muisek

- Quest item not dropping 
Quest item - https://www.wowhead.com/item=9597/mountain-giant-muisek

**Comment by Rushor** [comment]
you need to kill the giants and then use the questitem on them, then it will work now :>

also the dead creature must be targeted.
