### ISSUE TITLE
[Quest/Mobs] by Krom'Gar Fortress, Stonetalon Mountains

### ISSUE THREAD

**Issue by Addahx** [WoWManiaUK/Blackwing-Lair#4211]
Gnomebots are aggro'ing too many Horde units in the area, resulting in a very poor Questing experience.

When the Gnomes are attacked by Horde units, players lose the loot and quest rewards. This is the same as anywhere, and on retail.

The problem is, this zones density, aggro range, or lack of unit movement is resulting in excessive inter-fighting between faction units. This makes the relevant Quest impossible to complete.

https://www.wowhead.com/storyline/stonetalon-mountains-horde-518

**Comment by Addahx** [comment]
Second example:
https://prnt.sc/r0tcpe
https://prnt.sc/r0texg
3 quest enemies dying to 3 guards, and they are big boys so not many of them in the area.
Vast majority of the time, the friendly units win and kill your quest target.
The units do not walk around, they just spawn and instantly start fighting.

**Comment by Echinaceax** [comment]
Confirmed by Asper
