### ISSUE TITLE
[Quest] Get Koalbeard

### ISSUE THREAD

**Issue by Addahx** [WoWManiaUK/Blackwing-Lair#4213]
**Links:**
https://prnt.sc/r0yeeg

from WoWHead or our Armory
https://www.wowhead.com/quest=25757/get-koalbeard

**What is happening:**
Killed the target enemy, Koalbeard, but no loot dropped, meaning no Alliance Report

**What should happen:**

Alliance report should drop from NPC on death

**Comment by Echinaceax** [comment]
Already reported here #2017
but thanks @Addahx
