### ISSUE TITLE
[NPC] Gorka (missing) - Ashenvale

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4214]
**Links:**

npc http://cata.cavernoftime.com/npc=33421

**What is happening:**
- missing npc cant hand quest back 

**What should happen:**
needed for quest back (got wood?) http://cata.cavernoftime.com/quest=13628

note:
Got wood is on .BQ command, but cant hand it in

**Comment by Rushor** [comment]
phasing adjusted
