### ISSUE TITLE
[Objects] Quest Objects Drops

### ISSUE THREAD

**Issue by Nellieb1y** [WoWManiaUK/Blackwing-Lair#4216]
**Whats happening**

Amongst the quest objects that come to us as dropped, the following are unresponsive when clicked.

Enchanted Thorium Platemail 18770
Assassin's Contract

**What should happen**
They ought to start a quest, or not be in the game.

**Comment by Echinaceax** [comment]
http://cata.cavernoftime.com/item=18770
http://cata.cavernoftime.com/item=3668

**Comment by Rushor** [comment]
https://www.wowhead.com/item=18770/torn-scroll
https://www.wowhead.com/item=3668/assassins-contract

will be removed from drop
