### ISSUE TITLE
[PvP Daily] Cursed Shackles Horde

### ISSUE THREAD

**Issue by Zim504** [WoWManiaUK/Blackwing-Lair#4217]
**Links:**

https://www.wowhead.com/quest=28186/cursed-shackles

**What is happening:**

The Gate to D-Block is closed so you can't enter to finish quest

**What should happen:**

It should be open to the winners of Tol Barad

**Comment by Rushor** [comment]
for me it is open

**Comment by Echinaceax** [comment]
only your horde toon @Rushor ?

**Comment by Echinaceax** [comment]
hordes cant complete this due to the battle being bugged (only allies can) until the battle is fixed
