### ISSUE TITLE
[Quest] Duskwing Oh How i hate thee - ID 27524- Eastern Plaguelands

### ISSUE THREAD

**Issue by ghost** [WoWManiaUK/Blackwing-Lair#422]
Quest -https://www.wowhead.com/quest=27523/duskwing-oh-how-i-hate-thee
NPC - https://www.wowhead.com/npc=45816
Item to use - https://www.wowhead.com/item=61334
Item required - https://www.wowhead.com/item=15850
I can locate the bat for this quest. however he isn't flying has he his meant to, and cannot be targeted with any spell has it says he is out of range, even though I'm stood in front of him. Trued using the flare and still cannot kill him. Quest incompletable.
![world of warcraft 07_01_2019 15_15_19](https://user-images.githubusercontent.com/42302580/50776042-d5e9bf80-128f-11e9-90af-65f4344166e5.png)

**Comment by Echinaceax** [comment]
Same for horde 

![duskwing](https://user-images.githubusercontent.com/39439201/50841321-c2f4ef00-1364-11e9-82a0-ca1079592f8e.jpg)

**Comment by Saintres** [comment]
tryed to do this quest today 2019-02-17.
Still not working

**Comment by Echinaceax** [comment]
> tryed to do this quest today 2019-02-17.
> Still not working

Once the quests are reported it will take many months for fixes to happen :)

**Comment by Dranah** [comment]
The NPC is actually flying, that's why he's out of range. It's a visual bug, he visibly falls down but he's actually high up. His altitude need to be reduced so that players can get him in attack range. Currently he's about 50 yards up.

**Comment by c2juk2000** [comment]
still bugged for horde.
![WoWScrnShot_060219_172236](https://user-images.githubusercontent.com/42567442/58764092-0d1c7e00-855b-11e9-8621-80f8c31a1b75.jpg)

**Comment by rzenne** [comment]
.BQ 27524 doesn't work even if you are standing right beside it.

**Comment by Echinaceax** [comment]
> .BQ 27524 doesn't work even if you are standing right beside it.

not all broken quests are on the .bq list @rzenne thats why that part didnt work 

and this report hasnt been fixed yet :)

**Comment by mfranca0009** [comment]
Potential Fix in Eastern Plagueland SQL file

`(@CGUID+1301, 11897, 0, 1, 1, 2808.731, -4062.556, 158.8493, 3.058988, 120, 0, 0), -- Duskwing (Area: Plaguewood)`

**TO**

`(@CGUID+1301, 11897, 0, 1, 1, 2808.731, -4062.556, 158.8493, 3.058988, 120, 0, 2), -- Duskwing (Area: Plaguewood)`

Movement Type set to 2

**Comment by mfranca0009** [comment]
All set, needs testing in PTR 👍

**Comment by Echinaceax** [comment]
fix confirmed in PTR
