### ISSUE TITLE
JC Dailies Blocked, no Proto Dragon Bones dropping

### ISSUE THREAD

**Issue by Nellieb1y** [WoWManiaUK/Blackwing-Lair#4220]
**Links:**

https://www.wowhead.com/quest=12961/shipment-intricate-bone-figurine
https://www.wowhead.com/item=42106/proto-dragon-bone#dropped-by:0+3-9+1

**What is happening:**
Proto Dragon Bones simply do not drop in Northrend... tried several places, spent about two hours.   

**What should happen:**

Drop rate as described in Wowhead, so that someone doing the work can complete the daily quest and do other dailies.

**Comment by Rushor** [comment]
will drop with 33 percent chance from those creatures now:

23680,
23688,
23689,
23750,
24072,
24083,
24160,
28378,
28389,
28467,
29590,
29753,
29755,
30055,
