### ISSUE TITLE
Frozen Orbs: Price Wrong, please set to gold

### ISSUE THREAD

**Issue by Nellieb1y** [WoWManiaUK/Blackwing-Lair#4221]
**Links:**

https://www.wowhead.com/item=43102/frozen-orb

**What is happening:**

According to Wowhead, these are sold by two vendors in Dalaran for 75g.  But the price at Magistrix Lambriesse <Legacy Justice Quartermaster> is in points.... please fix so that it can be bought for gold, and folks can  level their professions and make armour.

Our server doesn't yet have the population to team up for old dungeons.

Thanks !

**What should happen:**

**Comment by Echinaceax** [comment]
In Cata @Nellieb1y it is Points
https://cata-twinhead.twinstar.cz/?item=43102#sold-by

**Comment by Echinaceax** [comment]
### New evidence for Nellie 

I checked and is all as it should be, 110 JP per Orb is not a lot to earn via normal mode dungeons, Justice points is correct in CATA  

As i said wowhead infomation is outdate and **some** infos there are incorrect for CATA 
We are not inchange of wrong info given by other sites so Changing to Gold to help players is for personal interest and not Blizlike so as far as i have found the info corrently ingame is correct for this issue 

![magistrix](https://user-images.githubusercontent.com/39439201/77438672-673a4880-6de6-11ea-9ce7-9e087a76fe79.jpg)
