### ISSUE TITLE
[BOSS] Atramedes (issue3) - Blackwing Descent

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4223]
**Resonating Clash** - http://cata.cavernoftime.com/spell=78168
 – _The sound resonating from the Ancient Dwarven Shield interrupts Atramedes' casting.While Airborne, Atramedes switches the target of his Roaring Flame Breath to the player who used the Ancient Dwarven Shield._

![Atramedes sound phase](https://user-images.githubusercontent.com/39439201/74598700-60e1df80-5076-11ea-84b8-2a84c3a15a46.jpg)

- [ ] **Ancient Dwarven Shield** http://cata.cavernoftime.com/?search=Ancient+Dwarven+Shield
_Not working, Which then targets the whole raid and not just the one person that clicks on the Ancient Dwarven Shield_

- [ ] **Sonic Breath** - http://cata.cavernoftime.com/spell=78100
_Whole raid targeted instead of one_ 

![sonic breath targets](https://user-images.githubusercontent.com/39439201/74598702-6b03de00-5076-11ea-8610-0b88f7a65441.jpg)

![tracking](https://user-images.githubusercontent.com/39439201/74598703-71925580-5076-11ea-926a-8e4a7346a60e.jpg)

- [ ] **Roaring flame breath** http://cata.cavernoftime.com/spell=78353

![fire2](https://user-images.githubusercontent.com/39439201/74603688-87c00600-50b6-11ea-8d52-b4bb5fdcef16.jpg)

_How it should work_

1. Need the Ancient Dwarven Shield working this is very important for this phase to remove the "sound stacks"

2. Sonic breath must only target one player not all of us

3. Roaring flame breath should follow 1 person around the room, but not fill the room like this

Video of how https://www.youtube.com/watch?v=LtG8bre4XlE

**Comment by Keader** [comment]
Fixed.

Sonic breath only target 1 player.
Dwarven shields now remove sound bar and correct shield will be destroied.
Roaring Flame, when you use the shield, will target the shield and after target player who clicks on it.
