### ISSUE TITLE
[BOSS] Chimaeron - Blackwing Descent

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4224]
**Links:**

- [ ] Break http://cata.cavernoftime.com/spell=82881
_– Chimaeron attacks viciously, breaking through his target's defenses and increasing their Physical damage taken by 25% and reducing healing done by 15% for 1 min. This effect stacks._

![break](https://user-images.githubusercontent.com/39439201/74605227-78e14f80-50c6-11ea-80ab-78abb9417116.jpg)

**What is happening:**
The Break is added as a buff and not a debuff, the tank can right click and remove it himself

**What should happen:**
_This should be a debuff and not removable_

**Comment by Keader** [comment]
try now dear
