### ISSUE TITLE
[Item] Crusader's Torch - Eastern Plaguelands

### ISSUE THREAD

**Issue by ghost** [WoWManiaUK/Blackwing-Lair#423]
Quest - https://www.wowhead.com/quest=27528/scourged-mass
NPC - https://www.wowhead.com/npc=45831
Item - https://www.wowhead.com/item=61369
You are to use the item to burn the corpse but once used it then become buff/debuff on my character. Market as low prio because it still works has intended on the mobs.
![world of warcraft 07_01_2019 16_05_04_li](https://user-images.githubusercontent.com/42302580/50778793-bace7e00-1296-11e9-97fa-f52bcf1df8f9.jpg)

**Comment by Dranah** [comment]
Applies the effect "Burn Corpse" spell ID=85555 to player.

**Comment by Echinaceax** [comment]
Also Torch gives quest credit on Alive "Overstuffed Golems" too

![overstuffed golem](https://user-images.githubusercontent.com/39439201/69083206-f2bf5980-0a41-11ea-8d59-d3ba263670f1.jpg)


should be corpses

**Comment by mfranca0009** [comment]
Quest Item (spell) now only targets Overwhelmed Golems when they're dead and the burn effect is not applied on the player casting the spell.

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 

![image](https://user-images.githubusercontent.com/39439201/103227366-77132a00-492e-11eb-907d-f896f9f2f3e5.png)
