### ISSUE TITLE
[Xfaction] Alliance Lootmaster - Baradin Hold

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4233]
**What happened**

While in Baradin hold tonight we noticed that Alliance Lootmaster Cant see Horde loot 

**Work around** 
Horde was given lootmaster so he could recieve his loot 

**What should happen**
Xfaction lootmaster should see both faction loots

**Comment by Rushor** [comment]
sould we make it like that that all people can see all loot always?

**Comment by Echinaceax** [comment]
> sould we make it like that that all people can see all loot always?

We should while Xfaction Baradin hold

**Comment by Echinaceax** [comment]
this can be closed 
Wont be an issue soon

**Comment by Echinaceax** [comment]
update

fixed this issue with the recent fix here #4651
