### ISSUE TITLE
[Profession Dailies] Jewelcrafting 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4235]
**Links:**

### For both horde and Alliance

https://wow.gamepedia.com/Jewelcrafting_quests
Alliance Npc http://cata.cavernoftime.com/npc=50480
Horde Npc http://cata.cavernoftime.com/npc=50482

Ally screenshot https://gyazo.com/69ec023250339b87597e7e512d04daac
horde screenshot  https://gyazo.com/564c5737fa9fb93d1a36716ff3a4deb7

**What is happening:**
Atm she is allowing players to pick up the dailies from low level Jewelcrafting  (see SS )
i am a lvl 1 in Jewelcrafting and i could complete the quest even though its meant for JC 475

**What should happen:**

> Alliance **Isabel Jones** (Stormwind)/ Horde **Marith Lazuria** (Orgrimmar), the Jewelcrafting trainer in each faction's main city, gives you your daily quests once you reach Jewelcrafting 475.

Jewelcrafting level requirement is 475

**Note** this is a level 85 item and should not be avalible without the correct requirements, this currency token is for high end recipes.
http://cata.cavernoftime.com/item=52446

**Comment by mfranca0009** [comment]
All set 👍
