### ISSUE TITLE
[Profession] Archaeology survey

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Blackwing-Lair#4237]
**Links:**

from WoWHead or our Armory

**What is happening:**

while surveying in various sites, the archaeology fragments sometimes appear at the steep slopes of a cliff where it is impossible to get a footing. The only workaround thus far seems to be to just wait for the fragment position to reset and then try again. Since there are only 4 survey sites per continent it becomes a bit painful when you have to fly around the continent only to find out that the fragment you are currently trying to get cannot be accessed.

**Places i have encountered this issue:**
1. Quel'Lithien lodge digsite(Eastern Plaguelands).
2. Hammertoe's Digsite(Badlands).
3. Thandol Span (Wetlands).
4. Andorhal fossil bank[west of chillwind camp](Western Plaguelands).
5. Hellfire Citadel Digsite(Hellfire Peninsula).
6. Hellfire Basin Digsite(Hellfire Peninsula)
7. East Auchindoun Digsite(Terrokar Forest).
8. Boha'mu ruins digsite(Zangarmarsh).

This list is not complete and therefore the issue may be prevalent in other continents i have not visited yet. 

_Note: Due to the randomness of the fragment locations, sometimes they may spawn in places players are able to reach, thereby making it impossible for me to say if the places i didn't encounter the issue are necessarily working fully_

**What should happen:**

Fragments should appear only in places where the player can reach.

**Comment by Chicozoba** [comment]
I think this has been reported already (I can't find the previous report), but if I remember Rushor couldn't do anything about it.

**Comment by Echinaceax** [comment]
it was and i cant fine the report from before either (named differently) im guessing

**Comment by Echinaceax** [comment]
adding to other report, closing this one #5023
