### ISSUE TITLE
[Boss] Nefarian (issue2) - Blackwing Descent

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4239]
**Links:**
Video https://www.youtube.com/watch?v=DOADoiTyDug
Boss http://cata.cavernoftime.com/npc=41376

- [x] **Stage two: Curse you, Mortals** 
The lava phase is delayed by 5secs (i think) this is important to jump on platform asap and with this delay we are in the lava and taking damage.

![lava too slow](https://user-images.githubusercontent.com/39439201/75483167-9061e780-59a6-11ea-8c3e-6045541916a9.jpg)

- [ ] Blast nova http://cata.cavernoftime.com/spell=30613
This is meant to be interuptable but its not if this spell cant be interupted its an instant wipe

![stage2b](https://user-images.githubusercontent.com/39439201/75483479-36aded00-59a7-11ea-80e5-fbfb5771a503.jpg)

- [ ] **Animated Bone Warriors - Empowering Strikes** http://cata.cavernoftime.com/spell=79329
they should get stack of that every time they hit a target, stacking effect (they dont atm)
https://www.wowhead.com/npc=41918/animated-bone-warrior#abilities:mode=n10

And should be doing 10,178 - 11,550

![empowering strikes](https://user-images.githubusercontent.com/39439201/75485897-da010100-59ab-11ea-8f80-0be895709d30.jpg)

**Comment by Hespericless** [comment]
I'd like to add that after killing the mobs casting blast nova, Nefarian's not flying down, so melees can't hit him during Phase 3

**Comment by Keader** [comment]
I tested in ptr, and everything posted here works.

**Comment by Echinaceax** [comment]
All 4 works as it should @keader ?

Blast nova http://cata.cavernoftime.com/spell=30613
This is meant to be interuptable but its not if this spell cant be interupted its an instant wipe

The old guild Lunaria tested this and they said the inerupt doesnt work hmmm

**Comment by Keader** [comment]
@Echinaceax i tested with counter spell (mage) and is working fine lol

**Comment by Echinaceax** [comment]
@Keader  only with mage ?
So not with all interupt spells ?

need all classes that have interepts to be tested lol 
thats the issue keader not all interepts spells are working as they should

ive asked for a list that dont work

**Comment by Keader** [comment]
All interrupts.
Anyway, i added a extra protection, so any type of interrupt, should make this npc stop cast

**Comment by Echinaceax** [comment]
> All interrupts.
> Anyway, i added a extra protection, so any type of interrupt, should make this npc stop cast

Paradox guild are giving feedback on this @Keader here is what still isnt working 

NPC chromatic prototype https://www.wowhead.com/npc=41948/chromatic-prototype#abilities:mode=n10

**Interupts confirmed NOT working**

- [ ] Arcane Torrent https://cata-twinhead.twinstar.cz/?spell=50613
- [ ] DK - Strangulate http://cata.cavernoftime.com/spell=47476
- [ ] DK - Mindfreeze http://cata.cavernoftime.com/spell=47528
- [ ] Rogue - kick https://classic.wowhead.com/spell=1766/kick
- [ ] warrior - Pummel https://cata-twinhead.twinstar.cz/?spell=6552
- [ ] pala - Rebuke https://cata-twinhead.twinstar.cz/?spell=96231

### Also calmwind noticed that melee attacks on that 2nd phase on the platforms dont work 

_says "out of range" or "facing wrong direction"_




**Interupts confirmed working** 

- [x] Mage -  counterspell https://classic.wowhead.com/spell=2139/counterspell
- [x] Bear - Skull Bash https://cata-twinhead.twinstar.cz/?spell=80964
- [x] cat - Skull Bash https://cata-twinhead.twinstar.cz/?spell=80965
- [x] Balance - solar beam https://cata-twinhead.twinstar.cz/?spell=78675
- [x] pala  - Avengers shield https://cata-twinhead.twinstar.cz/?spell=31935
- [x] hunter -  Silencing shot https://cata-twinhead.twinstar.cz/?spell=34490
- [x] warlock - spell lock https://cata-twinhead.twinstar.cz/?spell=19647
- [x] Shammy - wind shear https://cata-twinhead.twinstar.cz/?spell=57994
- [x] Spriest - Silence https://cata-twinhead.twinstar.cz/?spell=15487

**Comment by Keader** [comment]
The only real bugged here is Strangulate.
Fixed.

**Comment by Echinaceax** [comment]
> The only real bugged here is Strangulate.
> Fixed.

lets hope https://github.com/WoWManiaUK/Blackwing-Lair/issues/4523 this issue was the cause of it. thanks @Keader :)
