### ISSUE TITLE
[NPC] Megs Dreadshredder - phasing issue - Tanaris

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#424]
npc - https://www.wowhead.com/npc=38534/megs-dreadshredder

- Cant hand in 
Quest - https://www.wowhead.com/quest=28509/warchiefs-command-tanaris

**Edited to add more info**

-Found NPC Megs Dreadshredder at Dunemaul compound in Tanaris and not Gradgetzan
https://www.wowhead.com/npc=38849/megs-dreadshredder

- Her Quests are silver for me 

![silver](https://user-images.githubusercontent.com/39439201/50781418-9fb73a80-12a5-11e9-85d1-09052afc632b.jpg)

**Comment by Dranah** [comment]
Another NPC that changes locations over the quest chain.
She's there, but phased out in the starting position.
