### ISSUE TITLE
[Boss] Slabhide - Skinning requirement wrong - Stonecore

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4240]
**Links:**
http://cata.cavernoftime.com/npc=43214 (nm)
http://cata.cavernoftime.com/npc=49538 (hc)

**What is happening:**
- Says requires skinning 535

**What should happen:**
Should be 525 in this patch

**Comment by Hespericless** [comment]
Not sure about that. If I remember correctly, bosses required a higher level to be skinned and there are items and enchantments that boost your skinning level in order to skin them.

**Comment by Echinaceax** [comment]
the thing is Hesp, that i have full 525 in Skinning and skinnable mobs/bosses shouldnt require a highter lvl (535) patch issue maybe, thats why im checking this out 

skinning info here https://www.wowhead.com/npc=43214/slabhide#skinning

**Comment by Chicozoba** [comment]
I don't know for skinning but for jewelcrafting, you can reach 535 skill with Draenei (if I remember). Maybe it can be the same with a precise race for skinning

**Comment by Echinaceax** [comment]
Not sure Haroum, i reached 585 in fishing while fishing when the Darkmoon was active, so who knows, but it needs checking

**Comment by Chicozoba** [comment]
Yep but that was a bug. I've skilled fishing beyond 525 in SW canals too but this is fixed now

**Comment by Echinaceax** [comment]
### Update on new info 

From what i have found (thanks guys) is that Worgens have a racial same as you say with Draenei
so i searched "wow 535 skinning requirements" etc.. and found same as Hesp did regarding the same link he shared above (thx hesp)

![Inkedskinning past ur level_LI](https://user-images.githubusercontent.com/39439201/75609359-27928080-5b08-11ea-8525-6ef95a17328a.jpg)
