### ISSUE TITLE
[BOSS] Atramedes - BWD 

### ISSUE THREAD

**Issue by eabyss-source** [WoWManiaUK/Blackwing-Lair#4241]
**What is happening:**
Atramedes is "flying" but at ground level thus allowing melee players to continue dpsing.

**What should happen:**
When the Ground Phase ends, Atramades should take off and remain in the air for 40 seconds: this is the Air Phase during which the raid will be on the move almost constantly to avoid abilities.

After 40 seconds, Atramedes will land and the Ground Phase will resume.

**Comment by Echinaceax** [comment]
confirmed he Atramedes is only in the air for 5 secs then he lands, this shouldnt happend he should be airborne while this phase is on

![Inkedsmall flight_LI](https://user-images.githubusercontent.com/39439201/75615706-c5597000-5b47-11ea-9347-61ff5cb3a8ed.jpg)

**Comment by Keader** [comment]
Missing core implementation, nothing that i can do.
