### ISSUE TITLE
[Mobs]  issue - Blackwing Descent 

### ISSUE THREAD

**Issue by eabyss-source** [WoWManiaUK/Blackwing-Lair#4242]
https://www.wowhead.com/blackwing-descent#npcs

**What is happening:**
All "Trash" mobs in the BWD raid, do about 500 damage per melee swing. They also do not use their supposed abilities. 

**What should happen:**
Damage should be way higher and should use their scripted abilities.

**Comment by eabyss-source** [comment]
This is allowing people to Farm the Trash drops solo

**Comment by Echinaceax** [comment]
Link the npc for testing please @eabyss-source

**Comment by eabyss-source** [comment]
Link is above, look at the NPCS its for all of them

**Comment by Echinaceax** [comment]
@Rushor Confirmed in dev, Soloing for 17g per kill 

![bwd 1](https://user-images.githubusercontent.com/39439201/75612621-a21dc900-5b25-11ea-8c30-813bf7dc6d50.png)

**Comment by eabyss-source** [comment]
@Rushor the problem isn't the gold, but the item drops that could be gained from it

**Comment by Echinaceax** [comment]
i added it more info if you just give me a chance @eabyss-source

**Comment by Echinaceax** [comment]
### LIST OF NPCs 
- [ ] Drakonid Slayer
http://cata.cavernoftime.com/npc=42802




### NOT FINISHED

**Comment by Echinaceax** [comment]
Fixed in other report by @Rushor
