### ISSUE TITLE
[RAID] Nefarian spawned mobs

### ISSUE THREAD

**Issue by eabyss-source** [WoWManiaUK/Blackwing-Lair#4243]
https://www.wowhead.com/npc=41918/animated-bone-warrior

**What is happening:**
Base melee damage is also low

**What should happen:**
Should have a higher base damage

**Comment by Echinaceax** [comment]
link the npc for testing @eabyss-source

**Comment by eabyss-source** [comment]
Literally linked the NPC above, please read the report

**Comment by Echinaceax** [comment]
thank you @eabyss-source
