### ISSUE TITLE
[Spell] Fury of Angerforge Proc 

### ISSUE THREAD

**Issue by eabyss-source** [WoWManiaUK/Blackwing-Lair#4245]
https://www.wowhead.com/item=59461/fury-of-angerforge
**What is happening:**
Fury of Angerforge should only be able to be "used" when the stack has reached 5, currently you are able to use it whenever you want, even without stacks.

**What should happen:**
Should only be useable once the player has reached 5 stacks.

**Comment by mfranca0009** [comment]
- [x] Require a stack of 5 raw fury to use item.
- [x] Consume (remove) the stack of 5 raw fury when used.

**Comment by golosomie** [comment]
@mfranca0009 Confirmed fixed on PTR.
