### ISSUE TITLE
[Quest/Item] Butcherbot - ID 52715 - Tanaris

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#425]
NPC - https://www.wowhead.com/npc=39178/driz-plunkbow
Quest item - https://www.wowhead.com/item=52715/butcherbot-control-gizmo
Quest - https://www.wowhead.com/quest=25112/butcherbot

Quest loot item - https://www.wowhead.com/npc=39702/tanaris-basilisk-kill-credit-bunny

- Quest item not working
- Quest drop not working either
- Cant complete

**Comment by Rushor** [comment]
funny guy. https://www.wowhead.com/npc=39696/butcherbot#comments

will make fun to fix that haha

**Comment by Rushor** [comment]
wubwub

![](https://i.imgur.com/ZwWN1ib.jpg)
