### ISSUE TITLE
[NPC] Faldren Tillsdale / Jamus'Vaz  (issue 2) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4254]
**Links:**

Jamus'Vaz <Valorous Quartermaster> - http://cata.cavernoftime.com/npc=46556
Faldren Tillsdale <Valorous Quartermaster> - http://cata.cavernoftime.com/npc=44245

**What is happening:**
- These vendors are deactivated due to wrong patch items But
As we are currently running  BWD and BoT (hc mode) the items such as **Gauntlets of the Forlorn Conqueror** will be dropping eg: http://cata.cavernoftime.com/item=67429#sold-by  it only makes sence that the gear is obtainable to spend on the HC gear tokens they get dropped using the 

![item1](https://user-images.githubusercontent.com/39439201/75908137-deb13380-5e49-11ea-927f-8edd515d8544.png)

**What should happen:**
Vendor has to be spawned with ability to spend/exchange the 372 token drops

_Gauntlets of the Forlorn Conqueror_ or any other of the drops requirements shown via the Reign cavenoftime armory 

Note: if im wrong on this can someone comment, thanks :)

**Comment by Echinaceax** [comment]
confirmed by tester @Chicozoba

**Comment by Echinaceax** [comment]
Not fixed in dev @wow-mania

**Comment by Rushor** [comment]
i copied all the items from toren-landow with itemlevel 359s and 372s to the both npcs from the ticket and removed everything else from them

**Comment by Rushor** [comment]
valot items from 58154, 58155 https://www.wowhead.com/npc=58155/rugok https://www.wowhead.com/npc=58154/toren-landow removed now since all those items are now given from the quatermasters
