### ISSUE TITLE
[Profession] Northrend Mining

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Blackwing-Lair#4255]
**What is happening:**
abnormally low number of cobalt, saronite and titanium veins in the following zones:
1. Borean Tundra.
2. Sholazar Basin.
3. Dragonblight.
4. Crystalsong Forest.
5. Icecrown.
6. Wintergrasp.
7. Storm Peaks.
8. Zul'drak.
9. Grizzly hills.
10. Howling Fjord.

There is nothing specific about these zones to report, but just the fact that the nodes are extremely scarce and do not respawn for days on end, in each and every one of these zones. If one has the patience to go through every inch of the area and spend hours doing several laps of the place, they may level up their profession at the cost of their last few brain cells. It is actually that bad. 

Pretty sure this issue is not new to the devs, since i noticed that the last person who opened this issue in 2019, got his thread closed as he could not provide a detailed zone by zone report. I am not sure if this has mostly been forgotten or there is still some internal work going on to fix this. 
 
From my understanding, after spending the last 3 days trying to get 10 stacks each of cobalt and saronite ores by exploring every zone in northrend, i found that the detailed report that the previous guy failed to provide is that every single zone in northrend needs to be fixed.

**Comment by Echinaceax** [comment]
this is the report Fester was refering to #3880
Bagi is no longer part of the test team so @Slydee23 took over, but now 1 by 1 report was ever done as far as i can see.

I totally agree that all nodes need a revamp, i seen for myself that Northern nodes are very limited on Reign where as on Mania nodes are much better @Rushor 

Suggestion: Cant we just import map nodes frrom Mania for all zones up to Northern @Rushor ?

**Comment by Echinaceax** [comment]
all fixed here on next update https://github.com/WoWManiaUK/Blackwing-Lair/issues/4788
