### ISSUE TITLE
[NPC] Twilight Pyremaw- Deepholm

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4257]
**Links:**
https://www.wowhead.com/npc=44189/twilight-pyremaw#abilities
https://www.wow-freakz.com/npc_finder.php?npc=44189

Ability https://www.wowhead.com/spell=86819/twilight-breath

![twilight pyremaw](https://user-images.githubusercontent.com/39439201/75928725-4d54b800-5e6f-11ea-8b47-4c3c5746518e.png)

**What is happening:**
- These dont have aggro range
- They dont attack with Twilight Breath either

**What should happen:**
_they should use ability when in aggro range_

**Comment by Rushor** [comment]
there is also this kind of creature: https://www.wowhead.com/npc=42824/twilight-pyremaw#abilities

**Comment by Echinaceax** [comment]
yes i was told you use only cavenoftime for links as its our new Armory but its odd not a lot of info regarding these issues so had to get from wowhead and Freakz but very unreliable so had to link what i could find :)

Thanks for other link @Rushor
