### ISSUE TITLE
[Dailies] Tol Barad 

### ISSUE THREAD

**Issue by mourshied** [WoWManiaUK/Blackwing-Lair#4258]
on tolbarad player can save quest to alt and do more quest in 1 day

**Whats happening**
There is an bug on tol-barad quest line u can save quest to alt and do them every day.

**Comment by Echinaceax** [comment]
https://wow.gamepedia.com/Tol_Barad_quests

Thank you @mourshied 

Can you help with the steps to reproduce this bug for the test team please?

Eg: 1. pick up quest that are availible then? 

We need to know how you pick them all up and then do them each day regardless of if they are availible or not via the

**Comment by Echinaceax** [comment]
Fixed from internal Github, thank you @mourshied
