### ISSUE TITLE
Minigob Manabunk spamming mailbox, stalking me

### ISSUE THREAD

**Issue by Nellieb1y** [WoWManiaUK/Blackwing-Lair#4259]
**Links:**

https://cdn.discordapp.com/attachments/533728620112510986/685754200290099213/spammer.jpg
https://cdn.discordapp.com/attachments/533728620112510986/685754585058508830/creepyDalaranPerv.jpg

**What is happening:**
It is not appreciated that an NPC is programmed to perv, stalk, and spam me ingame.   Levelling from 68-80 should have been an enjoyable experience, but it was ruined on my 3 toons that levelled to 80 because on is constantly accosted in Dalaran by Minigob Manabunk.      

The character is intrusive, offensive, and is an unpleasant reminder of how a few really rotten men in RL can behave.

**What should happen:**

Remove the creepy character from the game entirely.  An NPC should not be camping, stalking, spamming, perving or anything that drives people, particularly women, away from a server.  IT was explained to me in Discord that it was happening because of low server population... perhaps, but that negates my concerns, and doesn't make the problem go away.. it just makes people go away.

**Comment by Echinaceax** [comment]
Old report fix #1225

New info from Nellie is that its when players hit 80 they recieve a mail on the lines of 

> the text of the mail from the stalker NPC is something like, now you're 80 and you can do it to others, and the attachment is a copy of the offending magic wand or whatever

will see if i can reproduce

**Comment by Rushor** [comment]
creature removed for now.
