### ISSUE TITLE
[Item] Argent-lightwell-charm - Eastern Plaguelands

### ISSUE THREAD

**Issue by ghost** [WoWManiaUK/Blackwing-Lair#426]
Quest - https://www.wowhead.com/quest=27530/the-corpsebeasts
NPC - https://www.wowhead.com/npc=45831
Item - https://www.wowhead.com/item=61375
After Locating the mob required the items were placed they did not destroy the corpse. However they acted has pets and began to attack mobs and follow me around. Unable to complete quest. Also to add to this the mobs surrounding the body should be casting purple beams to reanimate the corpse but they are not.
![world of warcraft 07_01_2019 16_26_31](https://user-images.githubusercontent.com/42302580/50779964-a9d33c00-1299-11e9-950d-37318556dd58.png)
Also to add to this they were originally placed around the corpse but every time I moved so did the lights.
**what should happen**
Item should destroy the corpse. Shouldn't act as pets and shouldn't aggro surround mobs.

**Comment by sarahkay88** [comment]
![world of warcraft 07_01_2019 16_26_50](https://user-images.githubusercontent.com/42302580/50780046-d9824400-1299-11e9-9cfd-7c3c82e9899b.png)
Aggroed the boss whilst I sat down and started to kill it.

**Comment by Echinaceax** [comment]
- Same on horde 

![1](https://user-images.githubusercontent.com/39439201/50976216-b781ff00-14ef-11e9-86dd-56396c79c091.jpg)

**Comment by Echinaceax** [comment]
is this on live @Xman993 ?
jani closes when on live only

**Comment by Thelonnious** [comment]
yes, its on live. quest and animation works.
