### ISSUE TITLE
[Spell] Draenei Racial - Heroic Presence

### ISSUE THREAD

**Issue by Koharuwaifu** [WoWManiaUK/Blackwing-Lair#4261]
Links: https://www.wowhead.com/spell=6562/heroic-presence

**What is happening:** Heroic Presence is not applying the 1% hit
![WoWScrnShot_030820_124928](https://user-images.githubusercontent.com/50305786/76168259-c2184280-614c-11ea-81ba-cfde7773df37.jpg)

![WoWScrnShot_030820_130058](https://user-images.githubusercontent.com/50305786/76168246-a876fb00-614c-11ea-9e2b-80ed57a1d681.jpg)

**What should happen:** For a draenei spell caster the hit cap should be 1640 but the racial it's not being added at all, even when it shows in the spellbook
![WoWScrnShot_030820_124905](https://user-images.githubusercontent.com/50305786/76168275-01469380-614d-11ea-9a29-15e9beb21dcd.jpg)

The bug is not only visual, i did some testing on a raiding dummy
![WoWScrnShot_030820_124727](https://user-images.githubusercontent.com/50305786/76168294-3eab2100-614d-11ea-88d4-b8468e19532a.jpg)

And it seems like the bug applies to both melee and spell hit
![WoWScrnShot_030820_125630](https://user-images.githubusercontent.com/50305786/76169261-23441400-6155-11ea-9876-9b522eb7a884.jpg)

**Comment by Hespericless** [comment]
Applying the aura manually doesn't give the 1% hit buff either.

**Comment by Keader** [comment]
fixed

**Comment by HrafnValknutt** [comment]
![WoWScrnShot_011121_202920](https://user-images.githubusercontent.com/72864958/104217345-55e12c00-544c-11eb-9f93-56bce257a14e.jpg)


Fixed in Dev confirmed.
