### ISSUE TITLE
[Raid/Loot] Blackwing Descent - Nefarian loot (10man normal)

### ISSUE THREAD

**Issue by Hespericless** [WoWManiaUK/Blackwing-Lair#4262]
**Links:**
http://cata.cavernoftime.com/npc=41376

**What is happening:**
Nefarian isn't dropping any head token. Tested in dev realm twice.
http://cata.cavernoftime.com/item=63682
http://cata.cavernoftime.com/item=63683
http://cata.cavernoftime.com/item=63684
**What should happen:**
The head token should always drop along with other 2 random drops from the loot table. This should be a guaranteed drop just like Cho'gall's shoulder token.

Nefarian is currently imposible to kill on live realm ( #4239 ), so this isn't a huge issue.

**Comment by Echinaceax** [comment]
I have reasearched this myself too and as far as i can see its never been 100% @Hespericless 
40% at best unfortunately covensoftime is not listing % 


However i did find from my other source i use and it says 30 - 40%

![40%](https://user-images.githubusercontent.com/39439201/76265684-8a50ee00-6265-11ea-9261-4148e42b406a.jpg)

can you look around a bit more to get the 100% definate proof of this that would be great 
i will label this pending

**Comment by Chicozoba** [comment]
@Echinaceax The drop rate of the token is 33% of each, but they don't share the rates with other loots. They are labeled as "Drop" on WowHead, and the others loots are "Boss drop". Which means, they're not drops for Nef, but for the raid (https://www.wowhead.com/npc=41376/nefarian#drops). That's why the rates aren't shared.

**Comment by Hespericless** [comment]
As Rushor commented in https://github.com/WoWManiaUK/Blackwing-Lair/issues/3921#issuecomment-554772824 , token bosses drop one extra item, that being said token (each one has around 33% drop chance because they're guaranteed and the game just rolls 1/3 to drop it). 
In the following retail videos you can see clearly that all kills dropped a token + 2 items from the loot table:
- https://www.youtube.com/watch?v=u6Azt2B6tBc
- https://www.youtube.com/watch?v=FIc62AyTwE4
- https://www.youtube.com/watch?v=TqKwhA8q_uw
- https://www.youtube.com/watch?v=AoecE9zcMlc

**Comment by Echinaceax** [comment]
@Chicozoba Agreed, 
ive been looking more too, and Hesp linked me what Rushor said here https://github.com/WoWManiaUK/Blackwing-Lair/issues/3921#issuecomment-554772824

@Rushor Can you check the drop are correct % for this one should be same as chog'all

**Comment by Echinaceax** [comment]
nice edited there @Hespericless

**Comment by Echinaceax** [comment]
More info coming now https://github.com/WoWManiaUK/Blackwing-Lair/issues/4239 has been fix
will update tis soon

**Comment by Echinaceax** [comment]
full check happening here #5296

**Comment by Echinaceax** [comment]
Full check happending here #3921
