### ISSUE TITLE
[General] VIP - vip revive 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4267]
![10 min](https://user-images.githubusercontent.com/39439201/76530990-cdcd7700-6474-11ea-89a4-c53fa03e7814.jpg)

**What is happening:**
- vip revive is still coming with a 10min timer

**What should happen:**
_VIP revive is meant to come with a 5 mins timer_

**Comment by Rushor** [comment]
will stay 10 for now
