### ISSUE TITLE
[Item] Priceless Rockjaw Artifact 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4269]
**Links:**

Item http://cata.cavernoftime.com/item=49751
quest http://cata.cavernoftime.com/quest=24486

**What is happening:**
- This item is dropping without having the quest 

**What should happen:**
need the quest before item should drop

**Comment by golosomie** [comment]
Just tested this on PTR as well as on live. 0/6 drops without the quest, 5/5 drops with the quest. seems like this has been fixed at some point

**Comment by Echinaceax** [comment]
thanks @golosomie can close this then :)
