### ISSUE TITLE
Quest: "The-Amulet-of-Sevine"

### ISSUE THREAD

**Issue by focarol** [WoWManiaUK/Blackwing-Lair#4270]
**Links:**

https://www.wowhead.com/quest=25698/the-amulet-of-sevine

**What is happening:**

The Gnom in the Cave gives you the Quest to get three Amulets.
These are seperated Quests - Two of them are possible to accomplish.
The Murloc doesn't have the Dialog-Option to hand out the Amulet of Sevine.

**What should happen:**

The Murloc hands out the Amulet of Sevine after talking to him.

**Comment by Echinaceax** [comment]
Confirmed 
npc Salt-Flop http://cata.cavernoftime.com/npc=41265

- Missing dialog 

![salt flop](https://user-images.githubusercontent.com/39439201/76769987-83face80-679d-11ea-9e7d-e9c5d1fd59f9.jpg)


Should have dialog 

![missing](https://user-images.githubusercontent.com/39439201/76770025-937a1780-679d-11ea-82f5-61d6a018fc95.jpg)

**Comment by mfranca0009** [comment]
Will look into this, seems like an easy fix.

**Comment by mfranca0009** [comment]
Horde: https://www.wowhead.com/quest=25698/the-amulet-of-sevine
Alliance: https://www.wowhead.com/quest=26168/the-amulet-of-sevine

This quest is given from two different NPCs depending on what faction you're playing. Important part to properly handle conditions; Will fix this issue for both quests.

**Comment by mfranca0009** [comment]
Fixed for Alliance and Horde quest, needs testing in PTR

**Comment by Echinaceax** [comment]
Confirmed Fixed in PTR 

horde
![fixed12](https://user-images.githubusercontent.com/39439201/88904441-619db500-d255-11ea-92b7-145e919a83a5.jpg)


Ally
![ally fixed](https://user-images.githubusercontent.com/39439201/88904555-82660a80-d255-11ea-9e0a-d8fe12f6c142.jpg)

**Comment by Echinaceax** [comment]
Update
Something happened to the fix

**Comment by Echinaceax** [comment]
better now ❤️  updated on live tomorrow 

![conf4](https://user-images.githubusercontent.com/39439201/90506403-80a4ae00-e154-11ea-8865-afd62b161dbe.jpg)
