### ISSUE TITLE
Dungeon: Stratholme - Lord Aurius Rivendare

### ISSUE THREAD

**Issue by focarol** [WoWManiaUK/Blackwing-Lair#4273]
**What is happening:**

The End-Boss of Strathlome Undead-side is killed by the first strike.

**What should happen:**

It should be a longer fight, to kill this Boss.
(Notice: 'Classes with Pets': don't let your pet kill the Boss - you don't get the loot.)

**Comment by Echinaceax** [comment]
http://cata.cavernoftime.com/quest=27227

**Comment by Echinaceax** [comment]
@Rushor Confirmed Lord Aurius Rivendare only has 30HP 

![30 hp](https://user-images.githubusercontent.com/39439201/76761667-2449f680-6790-11ea-9b8f-9165303d4da5.jpg)


Thanks @focarol :)

**Comment by golosomie** [comment]
@Echinaceax 
Confirmed fixed in PTR.
