### ISSUE TITLE
Hunter Looting (maybe all 'Classes with Pet')

### ISSUE THREAD

**Issue by focarol** [WoWManiaUK/Blackwing-Lair#4274]
**What is happening:**

As a Hunter - when my pet kills a mob --> i cannot loot the corpse.
I noticed it first, that it hurts, when i killed Lord Aurius Rivendare, which is killed by one hit actually.

**What should happen:**

It should be possible that i can loot a mob-corpse even my Pet killed the mob.
Because the Hunter is the Beastmaster and in unity with its Pet. :-)

**Comment by Echinaceax** [comment]
@focarol Ive confirmed Lord Aurius Rivendare bug from your or report (boss only had 30hp) 

As for this pet bug 
cant go off a 1shot kill because even as BM hunter the hunter must get a shot on the target to be able to loot

**Comment by focarol** [comment]
Do i understand you correct:
The Hunter has to have at least one little damagae on the mob to get the loot?
Because this is what actually happens.
(With Lord Aurius Rivendare, i just saw how painful it is, my pet was killing him with one strike)

**Comment by Echinaceax** [comment]
Yes, you cant just set your pet to attack and you go grab a coffee @focarol :)
I have a hunter too, Ive always know throught playing wow that the hunter whether BM or not must still have some dmg on the target or it wont count.

eg: its like another person/player tagged the target before you, can not be looted (kind of) 
only wording i have atm (i just woken up) lol

**Comment by focarol** [comment]
copy that.
So i cannot let it do all the work :D 

yeah...i had a long break from 2007 to 2019 starting WoW again. Get confused sometimes.

thx a lot for your work.
