### ISSUE TITLE
Visual Bug: Worgen

### ISSUE THREAD

**Issue by focarol** [WoWManiaUK/Blackwing-Lair#4276]
**What is happening:**

when you get "sheeped" as a Worgen and you get back to your original Form --> you will have a white mane.
Also the ability "running wild" like going on all four and running as fast as a ground mount --> will have a visual bug. Appears a bit like a Skettis is running with the Worgen on its arm.
I trty to make screenshots once i have it again.

**Comment by Echinaceax** [comment]
@focarol Main report reported here #3021

i will close this one and it will be fixed from the other report when DEVs can get to it 
Thanks
