### ISSUE TITLE
Quest A mighty Hunger (issue2) - Western Plaguelands

### ISSUE THREAD

**Issue by focarol** [WoWManiaUK/Blackwing-Lair#4279]
**Links:**

https://www.wowhead.com/quest=27167/a-mighty-hunger

**What is happening:**

the Bears (i killed over 60...poor bears) doesn't drop the needed item.
My RNG cannot be so bad.

**What should happen:**

they should drop that "Side of BearMeat"

**Comment by Echinaceax** [comment]
Quest item was dropping without the quest before in an earlier report #361
Naughty :P

**Comment by focarol** [comment]
but now nothing is dropping anymore

**Comment by Kadajj** [comment]
![WoWScrnShot_041220_103852](https://user-images.githubusercontent.com/38867875/79066803-8a07a080-7cb2-11ea-99fe-b817bf0716a6.jpg)

**Comment by Thelonnious** [comment]
duplicate #4345

**Comment by Echinaceax** [comment]
> duplicate #4345

yes you fixed the wrong one :) this was a duplicate :P
np @Xman993

**Comment by Scythre** [comment]
This is still happeneing no sides of bear meat drop

**Comment by Echinaceax** [comment]
i will take a look at this @Scythre 

update - this is a duplicate report that was closed 

here is the other #4345 and that isnt on live yet @scythre, on next server update
