### ISSUE TITLE
[Quest] Defenders of Darrowshire/Scourged Mass / Add 'em to the Pile - Interaction - Eastern Plaguelands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#428]
Quest - https://www.wowhead.com/quest=27529/defenders-of-darrowshire
NPC - https://www.wowhead.com/npc=45831
Did not receive this quest or it was missing. however I did receive the first and last quest in the series which were
https://www.wowhead.com/quest=27528
https://www.wowhead.com/quest=27530

**Comment by Echinaceax** [comment]
- On Horde i can collect "Defenders of Darrowshire"
- but lose the other 2 

![kevin frost](https://user-images.githubusercontent.com/39439201/50967027-30289180-14d7-11e9-90dd-c46c3d16259c.jpg)

**Comment by Dranah** [comment]
These quests are available at the same time and much like similar quest pairs, they cancel each other when you take one. All of them should be possible to take at the same time and all of them should be a prerequisite for "The Corpsebeasts"
