### ISSUE TITLE
Quest "The endless Flow"

### ISSUE THREAD

**Issue by focarol** [WoWManiaUK/Blackwing-Lair#4281]
**Links:**

https://www.wowhead.com/quest=27161/the-endless-flow

**What is happening:**

**What should happen:**

**Comment by focarol** [comment]
Links:

https://www.wowhead.com/quest=27161/the-endless-flow

What is happening:

Nothing happens when throwing the Grenade on the "bony" stuff.
There is a Rocket Chicken in the bony stuff....i saw this failure alrewady in the Blasted Lands within a quest.
No running Skelletons to stop.

What should happen:

Stopping the flow of Skelletons with the grenade destroying the stuff.

**Comment by Rushor** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/3682
