### ISSUE TITLE
Quest "Zenkiki the Druid"

### ISSUE THREAD

**Issue by focarol** [WoWManiaUK/Blackwing-Lair#4283]
**Links:**

https://www.wowhead.com/quest=26953/zenkiki-the-druid

**What is happening:**

I think he is supposed to follow the Player and kill some mobs together.
Nothing happens with that troll.

**What should happen:**

Killing Spree with the troll

**Comment by Rushor** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/375
