### ISSUE TITLE
Quest "Zenkiki and the Cultists"

### ISSUE THREAD

**Issue by focarol** [WoWManiaUK/Blackwing-Lair#4284]
**Links:**

https://www.wowhead.com/quest=26955/zenkiki-and-the-cultists

**What is happening:**

Nothing happens with that Troll.
The cages can be opened but they dont go out.
I guess Znkiki has to get them out.

**What should happen:**

Again Killing Spree with the Troll as companion i guess. But no Troll with the Player and no chance to get the Bears out of the cages.

**Comment by Rushor** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/376
