### ISSUE TITLE
Quest "Learning the Ropes"

### ISSUE THREAD

**Issue by focarol** [WoWManiaUK/Blackwing-Lair#4285]
**Links:**

https://www.wowhead.com/quest=27000/learning-the-ropes

**What is happening:**

Not possible to mount one of these Heartglen Horses.

**What should happen:**

Mount a horse to scare the spiders away.

**Comment by Rushor** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/2056

please use the search field before opening new issues :) https://github.com/WoWManiaUK/Blackwing-Lair/search?q=search&unscoped_q=search
