### ISSUE TITLE
Quest "The Good People of Hearthglen"

### ISSUE THREAD

**Issue by focarol** [WoWManiaUK/Blackwing-Lair#4287]
**Links:**

https://www.wowhead.com/quest=27153/the-good-people-of-hearthglen

**What is happening:**

The NPC dont react to the Quest. It is possible to talk to them but they should react to the Quest.

**What should happen:**

Let them Talk - they have something to say to bring the player forward in this Western Plaquland.....i found a bunch of quest here not working....i go to bed now.

**Comment by Rushor** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/378
