### ISSUE TITLE
[NPC] Slipstream - Throne of the Four Winds

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4290]
**Links:**

https://www.wowhead.com/npc=47066/slipstream

**What is happening:**
- Some glitches with the Slipstream where you slip through and end up in a loop 

https://gyazo.com/7c973f96c799c480981053d6f196f16d

**What should happen:**
_players shouldnt slip through to lower than the horizontal Slipstream_

https://gyazo.com/e1f39f8403a2ab1468092735be66678d

**Comment by Keader** [comment]
fixed.
