### ISSUE TITLE
[Boss] Magmaw - Magma Spit - (10man) - Blackwing Descent

### ISSUE THREAD

**Issue by Hespericless** [WoWManiaUK/Blackwing-Lair#4292]
**Links:**
http://cata.cavernoftime.com/spell=78068
https://www.youtube.com/watch?v=E_f-j6LAfxo (how it should behave)

**What is happening:**
 Magma Spit is hitting everyone on the raid, this makes it very difficult to progress.

**What should happen:**
Magma Spit should only target 3 people per cast.

**Comment by Echinaceax** [comment]
@Hespericless didnt keader fix Magmaw before?
ive been looking for the old report but i can find it

**Comment by Hespericless** [comment]
@Echinaceax I can't find it either but that report was regarding Lava Worm Wrangling, this is an issue on another of the boss' spells

**Comment by Echinaceax** [comment]
yes but i added to that report magma spit too im 90% sure i did lol

It was the main report from Angel, but i cant find it

**Comment by Keader** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/4484
