### ISSUE TITLE
[Quest] Uldum - 27778 - Hacking the Wibson

### ISSUE THREAD

**Issue by Demoniakk** [WoWManiaUK/Blackwing-Lair#4298]
**Links:**
Quest: https://www.wowhead.com/quest=27778/hacking-the-wibson
from WoWHead or our Armory

**What is happening:**
You can pick up the Maintenance Axe, but can't do anything to Wibson Mainframe

**What should happen:**
Well, you should be able to interact with Wibson Mainframe with your trusty Maintenance Axe

**Comment by Echinaceax** [comment]
Quest item/object reported here #1906
