### ISSUE TITLE
"You Are Rakh'likh, demon" 

### ISSUE THREAD

**Issue by Zprotic6** [WoWManiaUK/Blackwing-Lair#4299]
There is no NPC or pink portal at Rise of The Defiler that can teleport me up there so i can continue quest.

QuestID: 26171

**Comment by Echinaceax** [comment]
Horde http://cata.cavernoftime.com/quest=25701
Ally http://cata.cavernoftime.com/quest=26171

**Comment by mfranca0009** [comment]
Correct NPCs for this quest:
https://www.wowhead.com/npc=41279/loramus-thalipedes
https://www.wowhead.com/npc=41280/razelikh-the-defiler
https://www.wowhead.com/npc=41292/loramus-the-defiled

Two different entries for loramus and razelikh, but these are the correct ones. Will need to work on text lines and interaction of the battle.

**Comment by mfranca0009** [comment]
All fixed 👍 

https://gist.github.com/mfranca0009/79f6738a415dfa2313530e605a5f3343

**Comment by Echinaceax** [comment]
Confirmed fixed on dev
