### ISSUE TITLE
[Spell] Charge

### ISSUE THREAD

**Issue by Uncle1** [WoWManiaUK/Blackwing-Lair#43]
Spell=100

When Charge is casted it is supposed to stun the target for 1.5 seconds, this propperty is dont even working but u still charging the target and generating 15 rage.

How it should work:
Charge an enemy, generate 15 Rage, and stun it for 1.5 seconds. Cannot be ussed on combat.

**Comment by Keader** [comment]
Fixed.

**Comment by Keader** [comment]
Fix confirmed in dev.
