### ISSUE TITLE
[Quest] The baroness' Missive  - ID 27551 - missing- Eastern Plaguelands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#430]
Quest - https://www.wowhead.com/quest=27551/the-baroness-missive
NPC - https://www.wowhead.com/item=61378/the-baroness-missive
Did not receive this quest or it was missing.
Also leads on to two further quest:
https://www.wowhead.com/quest=27526-NPC -https://www.wowhead.com/npc=45729
https://www.wowhead.com/quest=27527 -NPC- https://www.wowhead.com/npc=45730

**Comment by Dranah** [comment]
Has some prerequisites. Need to look into it.

**Comment by sarahkay88** [comment]
Tbh there is quite a few quest missing these few I found when researching the achievement for completing 70 quest.

**Comment by Echinaceax** [comment]
i just got the Quest , it is a mob drop 

![missive drop](https://user-images.githubusercontent.com/39439201/50968250-c316fb00-14da-11e9-95f4-251e504f94cf.jpg)

**Comment by Rushor** [comment]
added a spawnpoint for him, where the questmark is.
