### ISSUE TITLE
[General] Raid browser (visual locks)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4302]
- [ ] Visual Locks missing

**What is happening:**
- Raidbrowser is listing the raids we havent opened yet

**What should happen:**
_These needs locks adding and turning grey_
- Dragon soul 
- Firelands

![raidfinder](https://user-images.githubusercontent.com/39439201/77574433-451df480-6ed2-11ea-805d-49cb41243a77.jpg)

![list checked](https://user-images.githubusercontent.com/39439201/77574973-181e1180-6ed3-11ea-9b95-6d8a20b1276d.jpg)

i did get the message but still should be grey
![req](https://user-images.githubusercontent.com/39439201/77575875-726ba200-6ed4-11ea-8201-3374521d5464.jpg)

**Comment by Demoniakk** [comment]
Just a quick question:
You do understand that Raid Finder was added only in patch 4.3 with Dragon Soul and only Dragon Soul was available for it and not a single other raid from Cataclysm expansion even was in there ?...

**Comment by Echinaceax** [comment]
Good to know @Demoniakk yes i renamed the title **Raid browser**

https://wow.gamepedia.com/Raid_Browser (3.3)
https://wow.gamepedia.com/Raid_Finder  (4.3)



We are 4.0.3 atm so the raid browser closed raids should be grey with locks

**Comment by Demoniakk** [comment]
Not just that - all the raids listed in Raid "Browser" above should not even exist in it. Only Dragon Soul was introduced to Raid Finder difficulty and was given a separate raid difficulty with lower ilvl loot than even normal difficulty.

**Comment by golosomie** [comment]
> Not just that - all the raids listed in Raid "Browser" above should not even exist in it. Only Dragon Soul was introduced to Raid Finder difficulty and was given a separate raid difficulty with lower ilvl loot than even normal difficulty.

That's just wrong, you're talking about Raid Finder which is not same as the "Other Raids" browser which is supposed to help people finding players to group up. This issue is about the latter

**Comment by golosomie** [comment]
can confirm that people listing with the Raid Browser function don't appear in the search for other people. 

I don't think we need to disable searching for groups for Firelands or Dragon Soul because you can't enter them using the Raid Browser (it's not creating and porting the groups like the dungeonfinder / raidfinder)

**Comment by golosomie** [comment]
@Echinaceax set to low priority because it's not really a required feature at the moment

**Comment by Echinaceax** [comment]
i will make new report for the other issue @golosomie

**Comment by Echinaceax** [comment]
issue not valid for visual padlocks
closing this
