### ISSUE TITLE
[NPC] T'Shu (missing) - The Underbog

### ISSUE THREAD

**Issue by oaktree0** [WoWManiaUK/Blackwing-Lair#4305]
**Links:**
https://www.wowhead.com/npc=54674/tshu#starts
https://www.wowhead.com/quest=29691/bring-me-a-shrubbery
https://www.wowhead.com/quest=29567/stalk-the-stalker
https://www.wowhead.com/quest=29692/bring-me-another-shrubbery

from WoWHead or our Armory

**What is happening:**
 T'shu isn't in The Underbog the following quests are unattainable.  Bring Me A Shrubbery (Q ID: 29691), Stalk The Stalker (Q ID: 29567), Bring Me Another Shrubbery (Q ID: 29692)

**What should happen:**

T'shu should be in The Underbog and not just another random NPC in Sporeggar.

**Comment by Echinaceax** [comment]
ive looked into this for you @oaktree0 and this NPC was only added in Added in patch 4.3.0.
We are only at 4.0.3 atm, so when we get to that patch it will be added

**Comment by oaktree0** [comment]
T'shu is still bugged in Sporeggar as you cannot turn in Sanguine Hibiscus to him for sporeggar rep

**Comment by Echinaceax** [comment]
we are looking into this more @oaktree0 
we will add new info when we have it thanks

**Comment by Echinaceax** [comment]
Confirmed that the npc for patch 4.3 is missing 

![t'shu underbog](https://user-images.githubusercontent.com/39439201/77850876-bb25a280-71d5-11ea-8d2c-4b962f23db37.jpg)
![missing tshu](https://user-images.githubusercontent.com/39439201/77850877-bd87fc80-71d5-11ea-8429-a6504509417e.jpg)

**Comment by Echinaceax** [comment]
Will be on live in next update
![tshu dev](https://user-images.githubusercontent.com/39439201/77852056-d3e58680-71dc-11ea-9723-9b466e7a5ee8.jpg)

**Comment by Echinaceax** [comment]
@Rushor did you send fix to jani?
still not on live
