### ISSUE TITLE
Blacksmithing - Vicious Set buged?

### ISSUE THREAD

**Issue by Zprotic6** [WoWManiaUK/Blackwing-Lair#4308]
I bought recepie from Kaita Deepforge. "Plans: Vicious Pyrium Gauntlets" and their ilvl is 377. When I made them I got this "Bloodied Pyrium Gauntlets" ilvl 339. I bought other Vicious pieces from her and all of those also became "Bloodied" rank and not "Vicious".

**Comment by Echinaceax** [comment]
This was downgrades to fit to current patch @Zprotic6
