### ISSUE TITLE
[Quest] 25841 | Strike from Above - Dun Morogh

### ISSUE THREAD

**Issue by iTz-AddriX** [WoWManiaUK/Blackwing-Lair#4310]
**Links:** https://www.wowhead.com/quest=25841/strike-from-above

**What is happening:** The animation from the item "Signal Flare" works just fine.

**What should happen:** When using the item "Signal Flare" it should call in an Air-Strike on the buildings needed for to complete the quest.

**Comment by Kadajj** [comment]
![WoWScrnShot_041120_191406](https://user-images.githubusercontent.com/38867875/79051543-b24abd00-7c28-11ea-8d22-52f76e46a53c.jpg)



Buildings already on fire and the flare wont summon the Air-Strike!

**Comment by mfranca0009** [comment]
Duplicate of #827
