### ISSUE TITLE
[Quest] 25792 | Pushing Forward - Dun Morogh

### ISSUE THREAD

**Issue by iTz-AddriX** [WoWManiaUK/Blackwing-Lair#4311]
**Links:** https://www.wowhead.com/quest=25792/pushing-forward

**What is happening:** Animation works only when using item.

**What should happen:** When using the item "Rune of Fire" it supposed to burn the Totems down.

**Comment by Kadajj** [comment]
item works! it's not burning the Construction Totem. 

![WoWScrnShot_041120_190314](https://user-images.githubusercontent.com/38867875/79051269-32702300-7c27-11ea-8796-9f0c1fce78e5.jpg)

**Comment by rzenne** [comment]
Tried to do the quest today. Still not working

**Comment by mfranca0009** [comment]
Duplicate of #824
