### ISSUE TITLE
[Quest] 313 | Forced to Watch from Afar - Dun Morogh

### ISSUE THREAD

**Issue by iTz-AddriX** [WoWManiaUK/Blackwing-Lair#4312]
**Links:** https://www.wowhead.com/quest=313/forced-to-watch-from-afar

**What is happening:** The Dwarfs are there that you need to rescue.

**What should happen:** The Dwarfs need an option to pick to get them out of there before they eaten.

**Comment by Kadajj** [comment]
It seems that most of the quest reported have a dialogue issue, this one included. respawned the NPC still not working.

![WoWScrnShot_041120_185804](https://user-images.githubusercontent.com/38867875/79051161-8c241d80-7c26-11ea-96be-166350c4d171.jpg)

**Comment by Echinaceax** [comment]
Reported already here #823
