### ISSUE TITLE
[Talent] Mana Feed - Warlock - Demonology

### ISSUE THREAD

**Issue by Demoniakk** [WoWManiaUK/Blackwing-Lair#4313]
**Links:**
Talent itself: http://cata.cavernoftime.com/spell=32554
Links to all demon basic abilities:
Imp Firebolt: http://cata.cavernoftime.com/spell=3110
Succubus Lash of Pain: http://cata.cavernoftime.com/spell=7814
Voidwalker Torment: http://cata.cavernoftime.com/spell=3716
Felhunter Shadow Bite: http://cata.cavernoftime.com/spell=54049
Felguard Legion Strike: http://cata.cavernoftime.com/spell=30213

**What is happening:**
This talent regenerates mana from any ability damage that your demon deals instead of criticals, regenerates only 1% mana and doesn't regenerate mana on criticals at all.

**What should happen:**
Should regenerate mana from basic ability criticals only. (attacks listed above)

**Comment by Keader** [comment]
Fixed
