### ISSUE TITLE
[Spell] Polymorph - Mage

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#4314]
**Links:**

[Polymorph](https://wowhead.com/spell=118/polymorph)

**What is happening:**

[Polymorph](https://wowhead.com/spell=118/polymorph) dont break on dmg.

**What should happen:**

pvp tested 

[Polymorph](https://wowhead.com/spell=118/polymorph) need to break on dmg
![poly_doesnt_break](https://user-images.githubusercontent.com/6819293/77933578-42931480-72af-11ea-8e68-bccf064dde61.jpg)

**Comment by Echinaceax** [comment]
confirmed poly doesnt "always" beak on dmg 

![poly3](https://user-images.githubusercontent.com/39439201/77946725-17b2bb80-72c3-11ea-81a8-fd48698372e1.jpg)
![poly4](https://user-images.githubusercontent.com/39439201/77946736-197c7f00-72c3-11ea-9fa4-b3ae2406543f.jpg)

**Comment by Keader** [comment]
Fixed.
