### ISSUE TITLE
[Spell] Hex 

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#4315]
**Links:**

[Hex](https://www.wowhead.com/spell=51514/hex)
**What is happening:**

[Hex](https://www.wowhead.com/spell=51514/hex) dont break on dmg.

**What should happen:**

[Hex](https://www.wowhead.com/spell=51514/hex)  need to break on dmg

**Comment by Hespericless** [comment]
Hex should have a chance to break on damage. Right now, it's doesn't ever break. The chance is either missing or it's way too low.

**Comment by Keader** [comment]
10% of target max health is needed as damage to break it.
fixed
