### ISSUE TITLE
[Spell] Exhaustion - Shaman

### ISSUE THREAD

**Issue by Thelonnious** [WoWManiaUK/Blackwing-Lair#4317]
**Links:**

[Exhaustion](https://www.wowhead.com/spell=57723)

**What is happening:**

Breaks on death

**What should happen:**

Persists through death

**Comment by Kadajj** [comment]
![WoWScrnShot_041120_221818](https://user-images.githubusercontent.com/38867875/79055132-699ffd80-7c42-11ea-970e-5ae2f22bb467.jpg)
![WoWScrnShot_041120_221837](https://user-images.githubusercontent.com/38867875/79055135-6d338480-7c42-11ea-9274-9d5cc6f9e5cf.jpg)

**Comment by Keader** [comment]
It's invalid o.o
This effect should be removed on death (same of wotlk)

**Comment by Thelonnious** [comment]
@Keader 

![image](https://user-images.githubusercontent.com/6819293/82158089-f19ea600-9885-11ea-83eb-e97895f545a6.png) 

Persists through death the only changelog is 

![image](https://user-images.githubusercontent.com/6819293/82158174-81445480-9886-11ea-8177-cdb013e1e539.png)

**Comment by Echinaceax** [comment]
@Xman993 is correct timer shouldnt disappear on death or log out 
or this would be available to use after every wipe :)

tester even shows his confirmed SS above

**Comment by Keader** [comment]
fixed
