### ISSUE TITLE
[Quest] 76 | The Jasperlode Mine - Elwynn Forest

### ISSUE THREAD

**Issue by iTz-AddriX** [WoWManiaUK/Blackwing-Lair#4319]
**Links:** https://classic.wowhead.com/quest=76/the-jasperlode-mine

**What is happening:** There is no mobs at the mine, nor can you complete quest. Ran through whole mine.

**What should happen:** Add NPC [476](https://classic.wowhead.com/npc=476/kobold-geomancer) - _Kobold Geomancer_ outside and inside mine. Also after running and exploring through mine you should get quest complete.

**Proof:** ![WoWScrnShot_033020_162328](https://user-images.githubusercontent.com/62844627/77958811-9c8ddd00-72a3-11ea-8e52-53a321494dd2.jpg)

**Comment by Echinaceax** [comment]
@iTz-AddriX i found no issue completing this quest 

![coords](https://user-images.githubusercontent.com/39439201/77961551-4a1be300-72da-11ea-9483-8d1927236152.jpg)

![no issue here for completing](https://user-images.githubusercontent.com/39439201/77961545-46885c00-72da-11ea-91d9-6ab22d4aa6a3.jpg)

only issue found was that there was only 4 Kobold Geomancer 
can you make new report for the npc low spawns there should be 22 not 4

so for this issue it will close as no issue
