### ISSUE TITLE
[NPC] 476 | Add More - Elwynn Forest

### ISSUE THREAD

**Issue by iTz-AddriX** [WoWManiaUK/Blackwing-Lair#4320]
**Links:** 
Add NPC [476](https://classic.wowhead.com/npc=476/kobold-geomancer) - _Kobold Geomancer_ outside and inside The Jasperlode Mine.

**What is happening:**
There is only 5 spawned.

**What should happen:**
There should be 22.

**Comment by iTz-AddriX** [comment]
False report everything is there.

**Comment by Echinaceax** [comment]
not really false report imo, there are only 5 spawned :)

![5](https://user-images.githubusercontent.com/39439201/77963057-fe1e6d80-72dc-11ea-91a8-d17e77b99ea0.jpg)

but as these are not a part of a quest no prio
