### ISSUE TITLE
Zul'Gurub not working

### ISSUE THREAD

**Issue by Adelrico** [WoWManiaUK/Blackwing-Lair#4323]
**Links:**

from WoWHead or our Armory

**What is happening:**
When I try to enter Zul'Gurub, I get a message that "the map cannot be opened at this moment" when I walk trough the portal.

This happened on 3 or 4 different days, with a raid reset in between.
I am in a raid group.

**What should happen:**
I should be able to enter Zul'Gurub after a loading screen.

**Comment by Demoniakk** [comment]
Zul'gurub in Cataclysm got locked out until patch 4.1, where it got revamped for a 5man heroic dungeon... Starting with patch 4.0.1, Zul'Gurub and Zul'Aman were both locked for that reason and not available to players till 4.1

**Comment by Echinaceax** [comment]
We are currently on 4.0.3 
Server hasnt opened Zul'Gurub yet @Demoniakk is correct

**Comment by Danie123** [comment]
Same Here There is no Mobs Npc bosses inside.

**Comment by Echinaceax** [comment]
@Danie123 This report was about access to it,  so as it is locked for now this report doesnt need reopening :)

> What is happening:
> When I try to enter Zul'Gurub, I get a message that "the map cannot be opened at this moment" when I walk trough the portal.

make a full report for dev test please @Danie123  :)
