### ISSUE TITLE
[Models?] Worgen Metamorphosis

### ISSUE THREAD

**Issue by Demoniakk** [WoWManiaUK/Blackwing-Lair#4325]
**Links:**
![image](https://user-images.githubusercontent.com/62444568/78038931-1e4e3b00-7376-11ea-824b-d38dc9868f54.png)
As you can see, after using Metamorphosis on a worgen warlock (dunno about others) your model just gets bugged out. With it, whenever I change form back to human, it crashes game...

![image](https://user-images.githubusercontent.com/62444568/78039262-9157b180-7376-11ea-93ca-688d5e44975c.png)

a little more of crap..

**Comment by Echinaceax** [comment]
Seen other spells do this too @Demoniakk 
reported here too #3021

**Comment by Kadajj** [comment]
![WoWScrnShot_041120_221445](https://user-images.githubusercontent.com/38867875/79055067-e2528a00-7c41-11ea-959c-db407168663a.jpg)

**Comment by Myst** [comment]
I have the fix, where do I upload the patch? How I am getting paid?

**Comment by Echinaceax** [comment]
> I have the fix, where do I upload the patch? How I am getting paid?

Please contack janitor either by email or in discord 
thanks @Myst

**Comment by Myst** [comment]
No one answer the mail, lol.

**Comment by Echinaceax** [comment]
@myst can you contact janitor on discord

**Comment by Myst** [comment]
Sorry don't have discord, I don't use it I hope we can talk using whatsapp or by email.

**Comment by Myst** [comment]
Fixed

**Comment by Echinaceax** [comment]
@Myst only janitor closes the fixed in dev ones when he has added to live 
reopen and re-add fixed in dev lables again for janitor to close thanks
