### ISSUE TITLE
[Quest] Dark Tidings (Ominous Letter drop) - 9587/9588/29532 - Hellfire Citadel:Ramparts

### ISSUE THREAD

**Issue by Demoniakk** [WoWManiaUK/Blackwing-Lair#4326]
**Links:**
Link for it's removal patch: https://wow.gamepedia.com/Dark_Tidings
Quests themselves: https://www.wowhead.com/quest=9587/dark-tidings
https://www.wowhead.com/quest=9588/dark-tidings
https://www.wowhead.com/quest=29532/dark-tidings
Items that still drop: https://www.wowhead.com/item=23892/ominous-letter
https://www.wowhead.com/item=23890/ominous-letter
from WoWHead or our Armory

**What is happening:**
The item drops, yet it was removed from loot tables in patch 4.3.0 along with it's quest. (this may lead to some "questions" in future about the item that gives no quests)

**What should happen:**
Either item/drop should be fixed and a proper quest given through use of the item or just remove the item from Nazan and Vazruden loot tables.

**Comment by mfranca0009** [comment]
Those letters drop from:
https://www.wowhead.com/npc=17537/vazruden

This should be fixed now; needs testing in PTR 👍
