### ISSUE TITLE
[Quest] Clear the High Road - Southern Barrens

### ISSUE THREAD

**Issue by Calmwindx** [WoWManiaUK/Blackwing-Lair#4328]
https://cata.cavernoftime.com/quest=24504

**What is happening:**
- There are no mobs to kill for this quest, so the quest cannot be completed.

**What should happen:**
There should be High Road Scout's east of Nura pathfinder along The High Road.

**Comment by Kadajj** [comment]
High Road Scout NPC (ID: 37159) missing. Added in PTR and quest doable. 

37159 need to have movetype set with NODEL.

![WoWScrnShot_041220_105915](https://user-images.githubusercontent.com/38867875/79066060-ca642000-7cac-11ea-90f4-23826e1eebd7.jpg)


Also Tunawa Stillwind (ID:37137) missing. Spawned in PTR and quest completed and also offer the next quest in the chain.

![WoWScrnShot_041220_105814](https://user-images.githubusercontent.com/38867875/79066082-e5cf2b00-7cac-11ea-8886-5bdb38ef9b7d.jpg)

![WoWScrnShot_041220_110111](https://user-images.githubusercontent.com/38867875/79066088-ee276600-7cac-11ea-9907-a5597b40431e.jpg)

**Comment by Danie123** [comment]
Npc's is there but cant be killed its a friendly target now.
![image](https://user-images.githubusercontent.com/5410898/81621409-9df80c80-93ee-11ea-8c41-3adace8a848a.png)

**Comment by Echinaceax** [comment]
confirmed fix for the High Road Scout 

![high road](https://user-images.githubusercontent.com/39439201/81625497-6e9acd00-93f9-11ea-9f04-7f55866eddfe.jpg)

But cant hand back in missing **Tunawa Stillwind** https://cata.cavernoftime.com/npc=37137
new report here #4496
