### ISSUE TITLE
[Quest] 26232 | Lou's Parting Thoughts - (issue3) - Westfall

### ISSUE THREAD

**Issue by iTz-AddriX** [WoWManiaUK/Blackwing-Lair#4329]
**Links:** https://www.wowhead.com/quest=26232/lous-parting-thoughts

**What is happening:** The [Thugs](https://www.wowhead.com/npc=42387/thug) attack you, but you cannot attack them back. Quest auto completes before they attack you.

**What should happen:** After you kill the [Thugs](https://www.wowhead.com/npc=42387/thug) that's when quest should complete.

**Proof:** ![WoWScrnShot_040220_104835](https://user-images.githubusercontent.com/62844627/78263673-45b91b00-74d0-11ea-901f-e50abe954726.jpg)

**Comment by Echinaceax** [comment]
Your not meant to attack thugs, this quest is _**Eavesdrop on the Thugs out behind the farmhouse at Furlbrow's Pumpkin Farm in Westfall.**_

so no idea where fighting thugs came into this 

note: i dont think you have the Reign client
