### ISSUE TITLE
[Quest] An ancient enemy (Quest ID: 24814) Durotar

### ISSUE THREAD

**Issue by realdude19** [WoWManiaUK/Blackwing-Lair#433]
**[Quest] An ancient enemy (Part 2 of 2) 
Quest ID 24814**

**WoW Head Link:** [https://www.wowhead.com/quest=24814/an-ancient-enemy](https://www.wowhead.com/quest=24814/an-ancient-enemy)

**Quest Objectives are to:**
- Speak with [[Vol'jin]](https://www.wowhead.com/npc=38225/voljin) at Spitescale Cove (@ Cord: 60.6, 16.0)
- [[Zar'jira]](https://www.wowhead.com/npc=38306/zarjira) slain

You can slay [[Zar'jira]](https://www.wowhead.com/npc=38306/zarjira) However you can not get to [[Vol'jin]](https://www.wowhead.com/npc=38225/voljin) bercause he is not where he needs to be, he is instead in the cave at the bottom but up on a ruin that has no ramp or way of accessing the area he is located at. 

The quest specificaly says and I quote:

_"Meet with [[Vol'jin]](https://www.wowhead.com/npc=38225/voljin), up da ramp to da northeast. Let him know when you are ready ta join da battle."_

When you speak to him he assists you in killing [[Zar'jira]](https://www.wowhead.com/npc=38306/zarjira)

The Quest can not be completed unless you can speak to [[Vol'jin]](https://www.wowhead.com/npc=38225/voljin).
To fix the problem:
- [[Vol'jin]](https://www.wowhead.com/npc=38225/voljin) needs to have his spawn location moved to (60.6, 16.0) That should be at the top of the hill and between the two other NPC's waiting in front of [[Zar'jira]](https://www.wowhead.com/npc=38306/zarjira).
- Kill [[Vol'jin]](https://www.wowhead.com/npc=38225/voljin), and verify he spawns in the new location.

**Until the quest is fixed it should be marked as bugged for testing as you can not progress out of the starting area without it.**

**Here are a couple screenshots to ilistrate the problem:**

![2019-01-09 03_07_46-world of warcraft](https://user-images.githubusercontent.com/46016748/50896406-c36da400-13bd-11e9-9913-2434df49eead.png)
![2019-01-09 03_08_54-world of warcraft](https://user-images.githubusercontent.com/46016748/50896412-c6689480-13bd-11e9-91c7-7d6ce856f8b7.png)

**Comment by realdude19** [comment]
Edited to add Cords for the location of broken NPC (60.6, 16.0)

**Comment by sarahkay88** [comment]
#37

**Comment by Rushor** [comment]
current report is https://github.com/WoWManiaUK/Blackwing-Lair/issues/1514
