### ISSUE TITLE
[Item] Ettin Control Orb - Redridge Mountains

### ISSUE THREAD

**Issue by iTz-AddriX** [WoWManiaUK/Blackwing-Lair#4332]
**Links:** 
- [Quest](https://www.wowhead.com/quest=26520/saving-foreman-oslow)
- [Item](https://www.wowhead.com/item=58895/ettin-control-orb)
- [Monster](https://www.wowhead.com/npc=43094/canyon-ettin)

 
**What is happening:** When trying to use [Ettin Control Orb](https://www.wowhead.com/item=58895/ettin-control-orb) on [Canyon Ettin](https://www.wowhead.com/npc=43094/canyon-ettin) it does nothing.

**What should happen:** When you use [Ettin Control Orb](https://www.wowhead.com/item=58895/ettin-control-orb) on [Canyon Ettin](https://www.wowhead.com/npc=43094/canyon-ettin) it supposed to make it you pet basically, and follow you down the road back to Oslow to remove the big rock off of him.

**Proof:**
![WoWScrnShot_040220_164245](https://user-images.githubusercontent.com/62844627/78299544-1e7c4100-7504-11ea-9d43-593161b7b066.jpg)

**Comment by Echinaceax** [comment]
Already reported here @iTz-AddriX #233

**Comment by iTz-AddriX** [comment]
Ok, sorry about that. Will definitely look before posting, I was just posting everything as I found something wrong with quests in all areas.

**Comment by Echinaceax** [comment]
> Ok, sorry about that. Will definitely look before posting, I was just posting everything as I found something wrong with quests in all areas.

Yes always check quest name / item / npc name most are reported from startzone from our old testers :)

**Comment by rzenne** [comment]
Tried today. Still not working

**Comment by Echinaceax** [comment]
this is a duplicate report @rzenne so was closed for that reason 
here is the open / not fixed yet report #233
