### ISSUE TITLE
[NPC] Montarr - (give both faction quests) - Thousand Needles

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4338]
**Links:**

npc http://cata.cavernoftime.com/npc=45271
horde quest http://cata.cavernoftime.com/quest=25874
ally quest http://cata.cavernoftime.com/quest=25873

![both quests](https://user-images.githubusercontent.com/39439201/78411482-19a4b380-7610-11ea-8e0c-01d82ccc4b50.jpg)

**What is happening:**
- npc give both quests

**What should happen:**
_npc shouldnt give both quests_

**Comment by mfranca0009** [comment]
Needs testing in PTR

**Comment by Echinaceax** [comment]
confirmed fixed in dev 👍
