### ISSUE TITLE
[Item Interaction] Receive Mail "Jartsam" riding trainer

### ISSUE THREAD

**Issue by gantor2** [WoWManiaUK/Blackwing-Lair#434]
Issue was noticed promptly after reaching level 20.
I have a mail notification from "Jartsam" and it will not display. When the mailbox is interacted with.
I searched the related issue's first and have not found any related to mail.
This is my first bug post so please let me know how to improve them.
Thank you.

**Comment by gantor2** [comment]
Update.
After traveling across towns and multiple use of mailboxes i have received the mail.
It is unclear why it worked now. 12 hours later after first receiving the notification

**Comment by Echinaceax** [comment]
> It is unclear why it worked now. 12 hours later after first receiving the notification
 After going to other mailboxes ..was it the first that you tried again or a different one?

**Comment by gantor2** [comment]
sadly i cannot recall

**Comment by Kitzunu** [comment]
works.
