### ISSUE TITLE
[Spell] Freezing trap (PvP issue) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4343]
**Links:**

http://cata.cavernoftime.com/spell=27753

![freeze trap](https://user-images.githubusercontent.com/39439201/78466572-c5c6c700-7702-11ea-83f5-a63ab26306e0.jpg)

**What is happening:**
- In PVP trap duration is only 6 secs instead of up to 1.30

**What should happen:**
_Duration needs increasing 1.30 in pvp too_

reported to me by Nub

**Comment by Demoniakk** [comment]
same answer as in Wyvern sting post

**Comment by Echinaceax** [comment]
Thank you for your reply @Demoniakk 

> reported to me by Nub

This test i did with the player that reported this to me, Showed the numbers was alway 6secs never any other number, it was never randomly low it was always 6s, which needs checking by keader

Thanks again for your link

**Comment by mfranca0009** [comment]
This is not an issue, its the same response for Entangling Root issue.
#4346 

**First hit on same target:**  8 seconds
**Second hit on same target:**  3 seconds
**Third hit on same target:** 1 / 2 seconds

Diminishing effect is part of Freezing Trap cause its an immobilizing spell; working as intended.
