### ISSUE TITLE
[Spell] Wyvern Sting (PvP issue)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4344]
**Links:**

http://cata.cavernoftime.com/spell=24131

![wyvern2](https://user-images.githubusercontent.com/39439201/78466743-12130680-7705-11ea-918f-4e73fe56c3f0.jpg)

**What is happening:**
In PVP sleep duration is only 6 secs instead of to 30

**What should happen:**
Duration needs increasing 30 for pvp too

reported to me by Nub

**Comment by Demoniakk** [comment]
instead of fooling around and thinking that a 30second stun in PVP is something how it's supposed to be, learn your game and stuff... and what Diminishing Returns is:
https://wow.gamepedia.com/Diminishing_returns

**Comment by Echinaceax** [comment]
Thank you for your reply @Demoniakk 

> reported to me by Nub

This test i did with the player that reported this to me, Showed the numbers was alway 6secs never any other number, it was never randomly low it was always 6s, which needs checking by keader

Thanks again for your link
