### ISSUE TITLE
[NPC] Shaggy Black Bear - (issue2) - Western Plaguelands

### ISSUE THREAD

**Issue by iTz-AddriX** [WoWManiaUK/Blackwing-Lair#4345]
**Links:** 
Quest - http://cata.cavernoftime.com/quest=27167
NPC - http://cata.cavernoftime.com/npc=44473

**What is happening:** The [Shaggy Black Bear](http://cata.cavernoftime.com/npc=44473) does not drop Sides of Bear Meat. I have killed over 50+ of them.

**What should happen:** Make NPC drop the corresponding item to be able to complete quest.

**Comment by Kadajj** [comment]
No drop of Side of Bear Meat (ID:60851)

![WoWScrnShot_041220_103852](https://user-images.githubusercontent.com/38867875/79065662-077ae300-7caa-11ea-9460-8dee082a2e13.jpg)

**Comment by Danie123** [comment]
Quest is working
![image](https://user-images.githubusercontent.com/5410898/81620935-6472d180-93ed-11ea-938d-8f8fbd61e53c.png)
![image](https://user-images.githubusercontent.com/5410898/81620947-6a68b280-93ed-11ea-8eb5-a28663fdaa53.png)
