### ISSUE TITLE
[Quest] Loyal Companions , The Storm Peaks

### ISSUE THREAD

**Issue by BurningXz** [WoWManiaUK/Blackwing-Lair#4347]
Link: https://www.wowhead.com/quest=12865/loyal-companions

**What is happening: when i bringed the meat to the eagles, i target them and click on the item (Fresh Ice Rhino Meat) , and no respond from them.

**What should happen: when you bring the meat to eagle they should "eat" the meat. 
and then quest complete

https://www.youtube.com/watch?v=utwOFNNm7fc

**Comment by Echinaceax** [comment]
#3518

Going to retest this

**Comment by mfranca0009** [comment]
Duplicate report, original report is here: #3518
