### ISSUE TITLE
[Profession] Arathi Highlands - Herbalism

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#4349]
Herb, little to non existent.
---------------------------------------------

Spawn rate;

[Bruiseweed](https://cata-twinhead.twinstar.cz/?object=1622/) x18
[Fadeleaf](https://cata-twinhead.twinstar.cz/?object=2042) x36
[Goldthorn](https://cata-twinhead.twinstar.cz/?object=2046) x73
[Grave Moss](https://cata-twinhead.twinstar.cz/?object=1628) x7
[Khadgar's Whisker](https://cata-twinhead.twinstar.cz/?object=2043) x68
[Kingsblood](https://cata-twinhead.twinstar.cz/?object=1624) x55
[Liferoot](https://cata-twinhead.twinstar.cz/?object=2041) x 35
[Wild Steelbloom](https://cata-twinhead.twinstar.cz/?object=1623) x78

**Comment by Echinaceax** [comment]
Yes herbs need a makeover :)
i noticed that too

**Comment by Echinaceax** [comment]
adding to main herb report
