### ISSUE TITLE
[Talent] Vengeance (Protection Warrior)

### ISSUE THREAD

**Issue by gantor2** [WoWManiaUK/Blackwing-Lair#435]
- The described buff from the passive talent Vengeance is not triggering upon taking damage from enemies.
Vengeance - ID 93098

**Comment by Keader** [comment]
Fixed.

**Comment by Dranah** [comment]
Vengeance paladin ID 84839
Vengeance warrior ID 93098
Vengeance druid ID 84840
Vengeance DK ID 93099

The effect now triggers (at least for paladins,dks and warriors), but does not work as intended.
**How it works atm:**
- Effect does not decay. Stays on the AP value you received from the last attack forever. Is not removed when you leave combat or relog.
- Effect does not stack. It simply overwrites to 5% of the next attack on each incoming damage source.
- Effect does not proc off spell damage taken, only melee.
- Druids' vengeance does not proc at all
- The 4.3.0 patch fix to bump up the proc to 33% of incoming damage (on pull and always checking last 2seconds of damage taken) is not working

**How it should work:**
- Effect must decay. While there's no fix duration set, it should not last forever. It should be losing 10% of it's current value every second. Relogging should remove the effect too.
- Effect must stack. Each attack should add the 5% AP calculated from its damage to the already existing vengeance buff, up to 10% of the player's max health.
- Effect must proc off all type of incoming damage, not only physical attacks.
- Druids must receive the vengeance effect while in bear form. Effect must decay like the others, and be immediately removed if the druid switches to cat form.
- The 4.3.0 patch fix means that the very first application of Vengeance must take 33% of the incoming damage as AP (still capped to 10% of max health though). Any damage taken afterwards will add 5% of the incoming damage as extra AP. Total AP is checked to be a minimum of 33% of total incoming damage in last 2seconds and a maximum of 10% of the player's max health.

Sources:
https://us.battle.net/forums/en/wow/topic/2140264146
_"Vengeance is a new mechanic given to all Tanks as one of their talent tree specialization bonuses. It takes 5% of incoming damage from each individual hit and turns it into attack power. In a long-duration encounter this will basically ensure you as a tank pull your weight on the meters (just a bit). It has a slight decay factor to it but nothing much to worry about, you can still stack it up pretty easily, of course only up to 10% of your total Health however.

Duration? This is a question that I've seen a lot. Vengeance has no fixed "duration." It'll just show up as a buff whenever you take any damage. Vengeance currently loses 10% of its value every second when you are not being attacked, and 5% a second if you are being attacked (even if you avoid or absorb the damage). Obviously if you take damage then Vengeance won’t fall off at all. The design of this ability isn't made with Heroics in mind, it'll really pull its weight in Raids, where its made for.

Here's an example of how a 100 Attack Power Vengeance decays:
100 - 95 - 90 - 85 - 80 - 75 - 70 - 65 - 60 - 55 - 50 - 45 - 40 - 35 - 30 - 25 - 20 - 15 - 10 - 5 - 0."_

Cataclysm Patch 4.0.3a (2010-11-23): Druid: Vengeance is no longer cleared on exiting Bear Form, and instead is cleared upon entering Cat Form. 
 Patch 4.3.0 (2011-11-29): Vengeance has been redesigned slightly. It no longer ramps up slowly at the beginning of a fight. Instead, the first melee attack taken by the tank generates Vengeance equal to 33% of the damage taken by that attack. In addition, as it updates periodically during the fight, it's always set to at least 33% of the damage taken by the tank in the last 2 seconds. It still climbs from that point at the rate it did previously, still decays when damage is not taken, and still cannot exceed a maximum based on the health and Stamina of the tank. 

Patch 4.3.2 (2012-01-31): Vengeance is no longer triggered by receiving damage from other players.

**Comment by Dranah** [comment]
Looks good now.
