### ISSUE TITLE
Area 52 Vendor

### ISSUE THREAD

**Issue by Wopr1xz** [WoWManiaUK/Blackwing-Lair#4350]
**Links:**

**What is happening:**
So the problem is as Alliance u can buy lvl 60 gear wiht gold but for Horde is for Conquest Point

**What should happen:**

It should be both set to gold , Thank you

Wopr1xz

**Comment by Echinaceax** [comment]
Ok confirmed @Rushor Alliance is set with gold for all 
Horde has conquest points that wrong definately 

Note - our armory cavenoftimes has no info on this lvl60 gear so ive linked this 
https://cata-twinhead.twinstar.cz/?npc=54648

![leeni](https://user-images.githubusercontent.com/39439201/78733255-3826e980-7945-11ea-8b81-24f88d7ea787.jpg)

**Comment by Myst** [comment]
I have the fix

**Comment by Echinaceax** [comment]
Thanks @Myst  but our dev already fixed just waiting for it to be added to dev
