### ISSUE TITLE
[Quest] Sludge Beast! ID: 29089 - Northern Barrens

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4354]
**Links:**

quest http://cata.cavernoftime.com/quest=29089
npc https://www.wowhead.com/npc=52165/sludge-beast

clicked
![pile of sludge](https://user-images.githubusercontent.com/39439201/78902980-d49ed800-7a7a-11ea-85fe-035a5b5f6a53.jpg)

 no sludge beast came
![no monster sludge](https://user-images.githubusercontent.com/39439201/78903036-e5e7e480-7a7a-11ea-995a-2c9697d7a982.jpg)

**What is happening:**
- Clicked the pile of sludge no sludge beast appeared 
- see video

**What should happen:**
Investigate the Sludge Beast's resting place and kill whatever comes out.
https://www.wowhead.com/quest=29089/sludge-beast#videos:id=38162

note: the prequest for this is here #1204 and is on the .bq command list so once you do the .bq command for prequest its auto completed then your are offered this quest "Sludge Beast!" after it

**Comment by mfranca0009** [comment]
All set, fixed in Dev 👍

**Comment by Constant20** [comment]
Confirmed fixed in PTR

**Comment by Echinaceax** [comment]
confirmed fixed in Ptr 

![confirmed3](https://user-images.githubusercontent.com/39439201/98223052-e03f7800-1f51-11eb-8e1b-97bdef2162dd.jpg)
