### ISSUE TITLE
[Quest/item] Natural Oil (not dropping) - Ashenvale

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4359]
**Links:**

item http://cata.cavernoftime.com/item=45071
quest http://cata.cavernoftime.com/quest=13651 

**What is happening:**
- quest item not dropping 
Could be due to low spawns (should be 81) #4360

**What should happen:**
_Gorka at Warsong Labor Camp wants you to collect 5 Natural Oil from the Rotting Slimes in Ashenvale._

**Comment by Kadajj** [comment]
![WoWScrnShot_041120_152553](https://user-images.githubusercontent.com/38867875/79046421-c1ba0e00-7c08-11ea-8726-5b16222d7ba1.jpg)

**Comment by Echinaceax** [comment]
comfired and completed

![oil drop](https://user-images.githubusercontent.com/39439201/79614364-a8c9c500-8100-11ea-9318-9f652db3588f.jpg)
![5 5](https://user-images.githubusercontent.com/39439201/79614370-ab2c1f00-8100-11ea-9bfc-a43b36f3947b.jpg)
