### ISSUE TITLE
[NPC] Crusader Kevin Frost - Eastern Plaguelands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#436]
npc - https://www.wowhead.com/npc=45831/crusader-kevin-frost

- I reported this NPC separately because we are seeing a pattern with the NPC that is adding to the issues with related quest/questlines so is bugging other quests
- Cant hand quest in also as NPC isnt in the location that is says 

Defenders of Darrowshire-  https://github.com/WoWManiaUK/Blackwing-Lair/issues/428

- Completed but cant hand in.
The baroness' Missive - https://github.com/WoWManiaUK/Blackwing-Lair/issues/430

**Comment by Dranah** [comment]
This NPC is present on correct position and offers all the quests he should.
I do not see the issue here.
