### ISSUE TITLE
[NPC] Rotting Slime (low spawn) - Ashenvale 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4360]
**Links:**

https://classic.wowhead.com/npc=3928/rotting-slime

![slimes](https://user-images.githubusercontent.com/39439201/78998218-6c1e2c80-7b48-11ea-862c-3cea260dd9aa.jpg)

**What is happening:**
- low spawn
could be affecting the loot for other quest #4359

**What should happen:**
_This NPC can be found in Ashenvale  (81)._

**Comment by Xman993** [comment]
the spawn is correct. 81 are just position where the npc can be.
