### ISSUE TITLE
[NPC] Kadrak 33837 (missing) - Ashenvale 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4363]
**Links:**

https://www.wowhead.com/npc=33837/kadrak

**What is happening:**
- npc missing

**What should happen:**
_needed for quest delivery_ https://www.wowhead.com/quest=13712/to-the-rescue

**Comment by Kadajj** [comment]
Works and Scripted. Npc 33837 needs to be added on live.
