### ISSUE TITLE
[General] game markers (Crumbling Depths) - Deepholm

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4364]
**Links:**
npc https://cata-twinhead.twinstar.cz/?npc=44258
video of movement https://www.youtube.com/watch?v=yq3kv6w3BDQ

**on live** 

![crumbling depths](https://user-images.githubusercontent.com/39439201/79047493-3300bd80-7c17-11ea-841b-b5ef77bf0aed.jpg)

my ingame video of agressive markers :) 
https://gyazo.com/f08d4d863a0049bf828d72f18c53732d

**What is happening:**
- Markers are visible to none gm / devs on live and in dev server
- Agressive markers

i believe these markers are movement/directional/effect  markers ...ofc im not a developer so im not 100% sure :)

**Comment by Xman993** [comment]
The infernals are Falling Rubble Bunny id 48543. Visual npc. 
they need to be flagged and get the  Falling Rubble effect.
