### ISSUE TITLE
[Spell] Wild Mushroom (Moving)

### ISSUE THREAD

**Issue by Sevenblade11** [WoWManiaUK/Blackwing-Lair#4365]
**Links:**

http://www.cavernoftime.com/spell=88747

**What is happening:**
A weird, yet funny / minor bug. When a druid (tested it with Restoration Spec) places down Wild Mushrooms and a mage roots them using Frost Nova, the Wild Mushrooms take offense and they start chasing and attacking anyone who dare hits them. 

**What should happen:**
Obviously, the Wild Mushrooms should not move or deal auto attack damage.

**Comment by Myst** [comment]
I have the fix, where to post it?

**Comment by mfranca0009** [comment]
All set 👍  Wild Mushroom should not move from position it was cast to, it will not melee attack anymore either.

Fungus Growth will not melee attack anymore as well.

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 

![image](https://user-images.githubusercontent.com/39439201/107361675-08ea8700-6ad8-11eb-95de-33656fe8e1e6.png)
