### ISSUE TITLE
[Mining] Pyrite Deposit - Uldum

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#4372]
[Pyrite Deposit](https://www.wowhead.com/object=202737) not existing.

**Comment by Echinaceax** [comment]
there are actually some in Uldum and Tol Barad but yes not really seen any in Twilight

**Comment by Echinaceax** [comment]
no change as far as i can see (in uldum) @Xman993 
so cant confirm
