### ISSUE TITLE
Overloaded Harvest Animation Fix 

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#4373]
[Overloaded Harvest](https://www.wowhead.com/npc=42381) Animation Fix  now Unbound Energy.

![image](https://wow.zamimg.com/uploads/screenshots/normal/806260-overloaded-harvest-golem.jpg)

**Comment by Echinaceax** [comment]
![fixed](https://user-images.githubusercontent.com/39439201/79840809-bad48d80-83b6-11ea-95b2-51754b00af49.jpg)
