### ISSUE TITLE
[NPC] Unbound Cyclone 

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#4374]
**Links:**
[Unbound Cyclone](https://www.wowhead.com/npc=832)

**What is happening:**

[Unbound Cyclone](https://www.wowhead.com/npc=832) dose not use [Unbound Cyclone Aura](https://www.wowhead.com/spell=76080/unbound-cyclone)

**What should happen:**

[Unbound Cyclone](https://www.wowhead.com/npc=832) need to use [Unbound Cyclone Aura](https://www.wowhead.com/spell=76080/unbound-cyclone)

**Comment by Echinaceax** [comment]
Not fixed again now (i will retest after dev server restart)

**Comment by Echinaceax** [comment]
### Update:

Confirmed fixed BUT

![confirmed1](https://user-images.githubusercontent.com/39439201/79975104-b7b2cd80-849a-11ea-8005-d23fcd46314a.jpg)


Fall damage is way to high :)

![fall dmg high](https://user-images.githubusercontent.com/39439201/79975016-9520b480-849a-11ea-9215-59f591fbdd23.jpg)

Knock back, not fall damage as far as i can see 

![Knock back not fall damage](https://user-images.githubusercontent.com/39439201/79976009-35c3a400-849c-11ea-94ae-19b29822990a.jpg)

**Comment by Thelonnious** [comment]
@Echinaceax  fall damage is hp% based, more hp = more dmg. . the Cyclone's knock us 50yd. if you get knock up 50yd u take damage equally  to %hp,

**Comment by Echinaceax** [comment]
yes i know the first time it almost killed me (so i did have to mod hp) after :P @Xman993 
when dev is up again i will retest ;)
but atleast they work again now

_note to self - cyclones work so stay away from there lol_
