### ISSUE TITLE
Voting system bug

### ISSUE THREAD

**Issue by janevsky** [WoWManiaUK/Blackwing-Lair#4377]
**What is happening:**
Hello, i want to report that i use the vote daily and i'm getting only 3 points from all sites.
Some of the sites not working, and those are:

https://gamestop100.com/
https://gtop100.com/

The max vote points i can get is 3 per day. I didn't see a bug report here so i'm making this.

Thank you,
Regards.

**Comment by Echinaceax** [comment]
As this is a 3rd part issue its not Wow-Reign responability for this 

This platform is for ingame bugs only, please PM a test team member or Janitor for this 
thanks @janevsky

**Comment by janevsky** [comment]
Oh, i didn't know, will do. Thanks
