### ISSUE TITLE
-

### ISSUE THREAD

**Issue by rzenne** [WoWManiaUK/Blackwing-Lair#4382]
**Links:**https://www.wowhead.com/quest=26215/meet-two-shoed-lou

from WoWHead or our Armory

**What is happening:**
You go to front of house and NPC is missing

**What should happen:**
Two shoed lou should have spawned in front of house
**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
Was reported and fix before #158

will post this to old report and reopen that one 
thanks @rzenne
