### ISSUE TITLE
[NPC] High Examiner Tae'thelan Bloodwatcher (low priority) - Badlands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#439]
High Examiner Tae'thelan Bloodwatcher gives 2 quest

npc - https://www.wowhead.com/npc=46757/high-examiner-taethelan-bloodwatcher
Quest - https://www.wowhead.com/quest=27884/the-sentinels-pawn
Quest - https://www.wowhead.com/quest=27883/the-wardens-pawn

- Can only take one of the two 
- Checking if this is correct 

![2 quests](https://user-images.githubusercontent.com/39439201/50978710-42b1c380-14f5-11e9-9c57-204e14a9650d.jpg)

**Side note**

- npc is hovering off the ground 

![floating](https://user-images.githubusercontent.com/39439201/51038555-d4800600-15b3-11e9-8025-bbf4aeca5b95.jpg)

**Comment by sarahkay88** [comment]
this is the same for alliance different NPC so make a different report

**Comment by sarahkay88** [comment]
both can now be collected at the same time
