### ISSUE TITLE
[Quest] [Surveying equipment] [Redridge Mountains]

### ISSUE THREAD

**Issue by rzenne** [WoWManiaUK/Blackwing-Lair#4391]
https://www.wowhead.com/quest=26569/surveying-equipment

from WoWHead or our Armory

**What is happening:**
The  Blackrock trackers when killed are not dropping the required quest item.

**What should happen:**
https://www.youtube.com/watch?v=5l4a3m_zEss
**Is it crashing the server?:**
no
**Other Information:**

**Comment by Echinaceax** [comment]
Confirmed fixed

![confirmed](https://user-images.githubusercontent.com/39439201/80286316-02e30f80-872b-11ea-9eae-fdc99a54e5ca.jpg)

![5 5](https://user-images.githubusercontent.com/39439201/80286317-070f2d00-872b-11ea-9023-ed4a3911a4ce.jpg)

**Comment by rzenne** [comment]
Tried to do quest again today and didn't work for me

**Comment by Thelonnious** [comment]
@rzenne  In dev, not on live.

**Comment by Echinaceax** [comment]
On next server update it will (fixed in dev/ptr) only atm @rzenne
