### ISSUE TITLE
-

### ISSUE THREAD

**Issue by rzenne** [WoWManiaUK/Blackwing-Lair#4392]
https://www.wowhead.com/quest=26607/they-drew-first-blood

from WoWHead or our Armory

**What is happening:**
After collecting the quest items from the cave in Render's rock you go to Colonel Troteman who tells you to Take this bundle of Keeshan's possessions and head back to the Lakeshire inn basement. 
When you get to the basement of the Inn the group of 4 NPC including John J. Keeshan are not present.

**What should happen:**
https://www.youtube.com/watch?v=JrH4GmF46xU
**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
Npc added on next update #4231
