### ISSUE TITLE
[Quest] In the Hands of the Perverse - Ashenvale

### ISSUE THREAD

**Issue by mizsh** [WoWManiaUK/Blackwing-Lair#4394]
Quest: https://www.wowhead.com/quest=13922/in-the-hands-of-the-perverse

**What is happening:**
1. Killing the Felmusk Felsworn / Felmusk Satyr / Felmusk Rogue  does not drop Fallen Moonstone.

**What should happen:**
1. Killing the Felmusk Felsworn / Felmusk Satyr / Felmusk Rogue  will drop Fallen Moonstone.

**Comment by Echinaceax** [comment]
fixed in dev confirmed 

![fixed](https://user-images.githubusercontent.com/39439201/80704027-253aab80-8ae4-11ea-8260-8213c5bea2d8.jpg)
