### ISSUE TITLE
[quest] [armed and ready]  - duskwood

### ISSUE THREAD

**Issue by rzenne** [WoWManiaUK/Blackwing-Lair#4397]
https://classic.wowhead.com/quest=325/armed-and-ready

from WoWHead or our Armory

**What is happening:**
When you get to the camp site Sven Yorgen is not there.

**What should happen:**
https://www.youtube.com/watch?v=fq9QvVIANGA
**Is it crashing the server?:**

**Other Information:**

Think this might be a quest that just needs to be removed.

**Comment by Thelonnious** [comment]
removed in cata after the map change
