### ISSUE TITLE
[Spell] Teleport: Shattrath

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4399]
**Links:**

http://cata.cavernoftime.com/spell=35715

**What is happening:**
- I learnt the Shattrath teleport ages ago without any issue but ...After learning the Tol Barad teleport last night it seems like its not allowing Shattrath portal to stay 

- Ive tested and re tested this on live (losing 7g at time) to retrain it.

**What should happen:**
teleports should store /save still even when you learn the very last teleport for cata

**Is it crashing the server?:**
no

**Other Information:**
when i logged in today i saw this 

![unlearned portal](https://user-images.githubusercontent.com/39439201/80095621-84d70b00-8568-11ea-86fb-39ecf3662905.jpg)

so i relearned it 

![shat portal 7g](https://user-images.githubusercontent.com/39439201/80095661-94eeea80-8568-11ea-8e69-aaec8d58130b.jpg)

![learnt](https://user-images.githubusercontent.com/39439201/80095749-b94ac700-8568-11ea-87a9-220f9fa4debe.jpg)

![in the bar](https://user-images.githubusercontent.com/39439201/80095689-9e785280-8568-11ea-8c3a-38e087bad0df.jpg)

relogged and it unlearned again 

![unlearn after log out](https://user-images.githubusercontent.com/39439201/80095760-bd76e480-8568-11ea-8d34-578ecf687d45.jpg)

**Comment by Zprotic6** [comment]
i dont have that problem as mage

**Comment by Echinaceax** [comment]
Thanks @Zprotic6 
needs more investigation :)

**Comment by alimaskoski** [comment]
I have the same problem on character Ralshu.

**Comment by Echinaceax** [comment]
Thanks for confirming this @Acko2

**Comment by mfranca0009** [comment]
Can we get a tester to re-test and confirm this, still has the pending label and it would be a good idea for a tester to confirm if the problem exists still or not. @Echinaceax

**Comment by Echinaceax** [comment]
its still doing it on live @mfranca0009 
a few days/week ago someone also ask why it was doing it 

i told them yes its a bug and dont waste anymore gold on relearning it,

**Comment by mfranca0009** [comment]
This has been fixed 👍
