### ISSUE TITLE
[Quest] Lazy peons - 37446- Valley of Trials 

### ISSUE THREAD

**Issue by Uncle1** [WoWManiaUK/Blackwing-Lair#44]
quest=25134
In this quest You have to wake up some npcs around of the valley of trials (Orcs starting zone), the npcs are supposed to be sleeping but all of them are alredy awoken, that means u cant do the quest.

How should it works:
The peons have to be sleeping for using [Foreman's Blackjack (item=16114)] on them, when you use it on the sleeping peons they will wake up and add 1 quest objective.

**Comment by Echinaceax** [comment]
Same issue applies 
i have spent the last 25 mins running around and 2 are sleeping and 13 working.

- Needs more lazy ones :)
