### ISSUE TITLE
[Quest] The Endless Flow - Western Plaguelands

### ISSUE THREAD

**Issue by mizsh** [WoWManiaUK/Blackwing-Lair#4405]
Quest:  https://www.wowhead.com/quest=27161/the-endless-flow

**What is happening:**
1. The quest item does not work on the Scourge Bone Animus.
2. The mobs needed for the quest are not spawned at all.

**What should happen:**
1. The quest item should work on the Scourge Bone Animus.
2. The mobs needed for the quest should spawn.

**Comment by Echinaceax** [comment]
@mizsh this is already reported on an on the .BQ command (atm) 
type .bq 27161 ingame chat

**Comment by Echinaceax** [comment]
not fully fixed 

- [x] The mobs needed for the quest should spawn. (fixed)
- [ ] The quest item should work on the Scourge Bone Animus. (not fixed)

will fix here #368
