### ISSUE TITLE
[Quest/item] Mistmantles family ring - Duskwood - Mistmantle's Revenge

### ISSUE THREAD

**Issue by gantor2** [WoWManiaUK/Blackwing-Lair#441]
- The item given in the quest does not summon the creature needed to be killed.
- Item Mistmantle Family Ring - ID 59363
- NPC Stalvan Mistmantle - ID 315

https://www.wowhead.com/item=3629/mistmantle-family-ring
https://wow.gamepedia.com/Mistmantle%27s_Revenge

**Comment by gantor2** [comment]
The item given in the quest does not summon the creature needed to be killed.

**Comment by gantor2** [comment]
https://wow.gamepedia.com/Mistmantle%27s_Revenge

**Comment by Saintres** [comment]
Quest still not working

**Comment by jarvik76** [comment]
Still not working as at 18th Sept

**Comment by Echinaceax** [comment]
@jarvik76 they know
unfortunately other prios atm are being done ..they will get to them all eventually

**Comment by Rushor** [comment]
spawn and killcredit fixed with next update

![I](https://i.imgur.com/Cx7Tanj.jpg)
![I](https://i.imgur.com/Cx7Tanj.jpg)
