### ISSUE TITLE
[Quest] The Corpsebeasts - Eastern Plaguelands

### ISSUE THREAD

**Issue by mizsh** [WoWManiaUK/Blackwing-Lair#4410]
Quest: https://www.wowhead.com/quest=27530/the-corpsebeasts

**What is happening:**
1. The Plague Reanimator is not doing anything to the corpse.
2. Activating the Argent Lightwell Charm will only attack the Plague Reanimator.

**What should happen:**
1. The Plague Animator should try reanimate the corpse.
2. Activating the Argent Lightwell Charm should destroy the corpse.

**Comment by Echinaceax** [comment]
placed 3 and 4 to complete the quest

![3 4](https://user-images.githubusercontent.com/39439201/80702957-2cf95080-8ae2-11ea-9ca9-b487448c9b9e.jpg)
