### ISSUE TITLE
[Quest] Frederick's Fish Fancy - Eastern Plaguelands

### ISSUE THREAD

**Issue by mizsh** [WoWManiaUK/Blackwing-Lair#4411]
Quest: https://www.wowhead.com/quest=27450/fredericks-fish-fancy

**What is happening:**
1. There is no indicator that these fishes can be triggered.

**What should happen:**
1. There should be an indicator for these fishes to be credited in the quest.

**Comment by Echinaceax** [comment]
thanks @mizsh type .bq 27450

**Comment by Danie123** [comment]
![1](https://user-images.githubusercontent.com/5410898/80954120-09dde200-8dfd-11ea-93bd-8c8d27717c1a.png)
Collected
![2](https://user-images.githubusercontent.com/5410898/80954151-19f5c180-8dfd-11ea-8708-3881106fb762.png)
Collected
![3](https://user-images.githubusercontent.com/5410898/80954167-24b05680-8dfd-11ea-97fd-7e7078b46136.png)
Collected
![4](https://user-images.githubusercontent.com/5410898/80954267-5a553f80-8dfd-11ea-99b8-3047204fc830.png)
Completed
