### ISSUE TITLE
[Worgen] RDF (phasing issue)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4421]
**What is happening:**
- Worgens are getting phasing bug after they have joined RDF 
_worgen must finish the questline before moving from their startzone (we know this)_
This new issue was just reported to a GM ingame

**What should happen:**
Restrict worgens to be locked from quing for RDF until out of startzone
_we restricted the Mall stone for the same reason_ #4156
this gives the worgen a chance to complete all their important quest

level 19 and still only at Battle for Gilneas City questline 

![lvl 19](https://user-images.githubusercontent.com/39439201/80379299-2da1a500-889e-11ea-9218-9a0accf869d5.jpg)

(still 20 quests left to do before that zone is completed and the Worgen can leave) 

https://wow.gamepedia.com/Worgen_starting_experience

**Other Information:**
1. This will save the worgens getting bugged/phased out
2. Less tickets for GMs

**Comment by Thelonnious** [comment]
@Echinaceax  if they left worgen zone, they need to get all racial spells instantly.

**Comment by gamer100** [comment]
They need to fix the chain for that so block rdf till 20 same as mall stone. Giving all instant when leave area is no option. Finish the chain for that

**Comment by Echinaceax** [comment]
> if they left worgen zone, they need to get all racial spells instantly.

Its not racials,  They are joining dungeon que at 15 (after speed lvling from x4) when they are only half way through the questline @Xman993 which is causing worgens to be out of **phase 186**  when they are ported back to where they where when they leave the finished dungeon.

which means they cant see npcs anymore, so they are making tickets for GMs to help them over and over

@gamer100 lvl 20 is to early as you see from the SS the player is at lvl19 and has 20 more quests to complete still, so i would say if a lvl restriction has to be added it must be bigger than 20, more like 23/25 ish

**Comment by Lumber-Jack-2** [comment]
Will fix that

**Comment by Lumber-Jack-2** [comment]
okay fixed, you can now only join lfg if you have quest 28517 (The Howling Oak for Worgen) if you are a worgen - finished.

**Comment by Echinaceax** [comment]
lovely thx rushor your awsome ❤️

**Comment by Danie123** [comment]
Thanks still busy testing something else while i am in the zone i can just test this aswell.

**Comment by Echinaceax** [comment]
on dev ofc @Danie123 ?

if you can confirm fix and add the confirmed fixed in dev label that will be great thx :)

**Comment by Danie123** [comment]
Yes

**Comment by Lumber-Jack-2** [comment]
fix also on dev now, all applied
