### ISSUE TITLE
[Worgen] Shapeshift

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Blackwing-Lair#4422]
![image](https://user-images.githubusercontent.com/33811022/80433283-c3691e80-88f6-11ea-917a-6cc62ccdd996.png)

You  need to relog  to  fix the char

**Comment by gamer100** [comment]
Worgen Druid  
When  you  do  out  of  cat form the worgen appearance is  wrong

![image](https://user-images.githubusercontent.com/33811022/80433132-63727800-88f6-11ea-82c0-428025c45429.png)


![image](https://user-images.githubusercontent.com/33811022/80433100-4b025d80-88f6-11ea-8eb6-0cb068c59526.png)

**Comment by Echinaceax** [comment]
there is a lot of issues regarding worgen when changing forms 
#4325 #4396 #3021 

i wonder if Mania has any issues with Worgens?
and is there a way to copy over the worgen data from there to here maybe?

**Comment by Danie123** [comment]
This bug is Client side not server side. Tested played around mine is fine.

**Comment by Danie123** [comment]
![Cat form](https://user-images.githubusercontent.com/5410898/80492709-b4b95080-8964-11ea-8b72-f12756f602f5.png)
![worgen form](https://user-images.githubusercontent.com/5410898/80492765-c7338a00-8964-11ea-9c01-555608df98d0.png)

**Comment by Echinaceax** [comment]
@Danie123 have not patched to reign yet :)

**Comment by Danie123** [comment]
Patching now and will retest

**Comment by Echinaceax** [comment]
thanks @Danie123

**Comment by Danie123** [comment]
I've Tested on the new Patch as well 1.1.0 and still works 100% no bugs.

Can we Close or someone else want to test?

**Comment by Echinaceax** [comment]
gamer100 will retest fron the new client now to check @Danie123 will update soon

**Comment by Echinaceax** [comment]
Tested myself too and no issues at all 

at lvl8 https://gyazo.com/4600cd1f5a04ec6775a34a5704f7e949
at lvl17 https://gyazo.com/941d18017c770af0f7e9b2b68a6a22e5

gamer100 is doing new install
