### ISSUE TITLE
[Quest] You are Rakh'likh, Demon - (Horde) - Blasted Lands

### ISSUE THREAD

**Issue by mizsh** [WoWManiaUK/Blackwing-Lair#4425]
Quest: http://cata.cavernoftime.com/quest=26171

**What is happening:**
1. There is no object to summon Rakh'likh.

**What should happen:**
1. There should be an object to summon Rakh'likh in order to kill him.

**Comment by Echinaceax** [comment]
being fixed on this report thanks #4299
