### ISSUE TITLE
[Quest]  Burnin' at Both Ends 

### ISSUE THREAD

**Issue by Thelonnious** [WoWManiaUK/Blackwing-Lair#4429]
**Links:**
[ Burnin' at Both Ends](https://www.wowhead.com/quest=28597/burnin-at-both-ends)

**What is happening:**

Cannon Powder Barrel dont drop Cannon Powder 

**What should happen:**

Cannon Powder Barrel need to drop Cannon Powder 

**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
#281 was reported here 
i will close the other one if you fixed this now @Xman993

**Comment by Echinaceax** [comment]
confirmed fixed in dev 

![confirmed4](https://user-images.githubusercontent.com/39439201/80703694-8ada6800-8ae3-11ea-8b0a-cc2ca11c4f5b.jpg)
