### ISSUE TITLE
[Ques/item] Soothing Spirits- Quest ID 26777 - Duskwood

### ISSUE THREAD

**Issue by gantor2** [WoWManiaUK/Blackwing-Lair#443]
- The item [Holy Censer] 60225 is not affecting the forlorn spirits when clicked.
Forlorn Spirit - ID 43923

https://wow.gamepedia.com/Soothing_Spirits

**Comment by gantor2** [comment]
https://wow.gamepedia.com/Soothing_Spirits

**Comment by Dranah** [comment]
Please use Wowhead links only.
https://www.wowhead.com/quest=26777/soothing-spirits

**Comment by Xman993** [comment]
The item [Holy Censer](https://www.wowhead.com/item=60225/holy-censer)  does not animate correctly too. 

**Correnct Animation**
![Opera Snapshot_2019-04-02_130650_www wowhead com](https://user-images.githubusercontent.com/6819293/55398443-d4572d00-5548-11e9-9e43-83c71b81e3dd.png)

**PTR Animation**

![Untitled](https://user-images.githubusercontent.com/6819293/55398577-2dbf5c00-5549-11e9-8256-ba64a94eaa7f.png)

**PS**
The item does not animate every time.

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/Y47EdBl.jpg)
![I](https://i.imgur.com/I69ujy1.jpg)
