### ISSUE TITLE
[Worgen] Mage portal / group summon guild perk (phasing issue)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4431]
**Links:**

https://wow.gamepedia.com/Worgen_starting_experience

**What is happening:**
- worgens are leaving startzone by other means again 
this time mage portal/ summoning stone to SW / guild perk

**What should happen:**
Set "do not meet the requirements" same fix as this please #4421

1. mage portals 
2. group summon (guild perk) https://wow.gamepedia.com/Have_Group,_Will_Travel

### Naughty worgens will try any way they can to escape  lol

  🤢   🤢   🤢

**Comment by Lumber-Jack-2** [comment]
group summon (guild perk) https://wow.gamepedia.com/Have_Group,_Will_Travel

will no longer select player targets that are race worgen and have quest "The Howling Oak for Worgen " not completed.

**Comment by Lumber-Jack-2** [comment]
for the portal issue i need clear reproduction case with spellids (wowhead) :)

**Comment by Thelonnious** [comment]
@Rushor don't bother blocking all for worges because on retail when they leave gilneas get all worgen racial spells automatically dont have to do the quest line.

**Comment by Echinaceax** [comment]
@Xman993 it has been told by the GMs ingame to do this 

When players are porting/summoning worgens out of startzone when they havent completed the questline is causing Massive issues and extra work for them,

I was told by GM to report it and get is sorted

when worgens lvl x2 they are leveling to fast here @Xman993 which is causing them to think its fine to leave, we are not retail xp1 are we ?


### Worgens MUST complete https://wow.gamepedia.com/The_Howling_Oak_(quest) before escaping the startzone !!!!!

**Comment by Echinaceax** [comment]
will this fix also work with dungeon main city summoning stones and warlock sommoning ritual @rushor?

**Comment by Echinaceax** [comment]
Confirmed
play gets the summon screen then loading screen then back to worgen start :) 

![group summon](https://user-images.githubusercontent.com/39439201/81619825-bd8d3600-93ea-11ea-8a9d-620db90ec52a.jpg)
