### ISSUE TITLE
[Quest] [Nobody to Blame but Myself] [Eastern Plaguelands]

### ISSUE THREAD

**Issue by rzenne** [WoWManiaUK/Blackwing-Lair#4433]
https://www.wowhead.com/quest=27489/nobody-to-blame-but-myself

from WoWHead or our Armory

**What is happening:**
Due to problems with the quest "traveling companion" reported here #4428 
Fiona's Caravan is not present.

**What should happen:**
https://www.youtube.com/watch?v=Me8-_RwO6DM
**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
opened one main report here #5082
