### ISSUE TITLE
[General] game markers  (issue8) - Gilneas

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4434]
![game markers4](https://user-images.githubusercontent.com/39439201/80803940-00ae0480-8bb4-11ea-96b7-6dbc80654d1b.jpg)

![green markers](https://user-images.githubusercontent.com/39439201/80862681-526b9300-8c77-11ea-8542-6966290dee89.jpg)

**What is happening:**
- Player can see game marker

![38344 plaue cloud bunny](https://user-images.githubusercontent.com/39439201/80862682-5bf4fb00-8c77-11ea-873f-636e2de3bfcf.jpg)

**Comment by Thelonnious** [comment]
@Echinaceax can you  give me the id?

**Comment by Echinaceax** [comment]
> @Echinaceax can you give me the id?

38344 plague cloud bunny
