### ISSUE TITLE
Taryssa Lazuria / Farrah Facet <Jewelcrafting Supplies> patch 4.3

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4435]
**Links:**

Horde - https://www.wowhead.com/npc=57922/taryssa-lazuria
Ally - https://www.wowhead.com/npc=56925/farrah-facet

**What is happening:**
- selling recipes we cant get mats for yet 
_wasting tokens on recipes we cant use_

**What should happen:**
_should be removed as the mats needed are not obtainable yet_

**Other Information:**

> Sells the Epic Gem recipes (5 tokens each) and  Tome of Burning Jewels (4 tokens each) added in 4.3.

**Comment by mfranca0009** [comment]
All set 👍 hidden NPCs till Firelands is released.
