### ISSUE TITLE
[Quest] Faces of Evil ID - 26521 - The Hinterlands

### ISSUE THREAD

**Issue by Danie123** [WoWManiaUK/Blackwing-Lair#4439]
**Links:**

https://www.wowhead.com/quest=26521/faces-of-evil

**What is happening:**
When using quest item 58209 - Tiki Torch it does not destroy game object its. quest can't be completed.

**What should happen:**
When you use item 58209 - Tiki Torch it should destroy game object Tiki Mask

**Is it crashing the server?:**
No
**Other Information:**
Quest is located in The Hitherlands

**Comment by Echinaceax** [comment]
Always check the reports before making new , reported here #349
