### ISSUE TITLE
[Quest]-A Curse We Cannot Lift -Id 26720 Duskwood

### ISSUE THREAD

**Issue by gantor2** [WoWManiaUK/Blackwing-Lair#444]
- The quest requires you to track down a worgen, fight him to a weakend state then apply item #60206 (Harris's Ampule) to the target. 
- The target is non attackble lurking above as you enter the barn. 
Lurking Worgen - ID  43814

https://wow.gamepedia.com/A_Curse_We_Cannot_Lift

![capture](https://user-images.githubusercontent.com/46546885/50983275-27cb5900-14cd-11e9-846a-e705782fde9f.PNG)

**Comment by gantor2** [comment]
https://wow.gamepedia.com/A_Curse_We_Cannot_Lift

**Comment by mfranca0009** [comment]
He has a unit flag that labels him as "immune to PC (Player Characters)" which is causing him to not be attackable. Once this flag is removed, you are able to throw the potion at him when weak but it does nothing. Will continue to look into this.

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 

note: dont forget to weaken him first or the quest item cant be used

![compl](https://user-images.githubusercontent.com/39439201/104207128-861ad180-5430-11eb-813b-ce33aad5bd99.jpg)
