### ISSUE TITLE
[Quest] Summit of Fate ID - 26517 - The Hinterlands

### ISSUE THREAD

**Issue by Danie123** [WoWManiaUK/Blackwing-Lair#4440]
**Links:**
https://www.youtube.com/watch?v=jogNMlK-j50
https://www.wowhead.com/quest=26517/summit-of-fate

**What is happening:**
NPC - Sacrificed Vilebranch ID - 42857 is not lootable

**What should happen:**
You should be able to loot these corpses to find loot inside to complete quest. Quest item is Spider Idol - ID 58228

**Is it crashing the server?:**
No

**Other Information:**
Quest is located in The Hitherlands.

**Comment by Echinaceax** [comment]
Are you ally or horde @Danie123 ?
coz ally one is reported here #349

**Comment by Echinaceax** [comment]
reported here @Danie123 #351
