### ISSUE TITLE
[General] Al'Akir Platform - Throne of the Four Winds 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4444]
**Links:**

![floor](https://user-images.githubusercontent.com/39439201/80923607-0149c500-8d85-11ea-9385-7e81c470c25e.jpg)

**What is happening:**
- When players die on the last boss, their corpse falls through the platform on outer ring
_See on the Screenshot where arrow are_ 

- fell through the floor after battle res 

![fell though](https://user-images.githubusercontent.com/39439201/80964283-e0c74c80-8e10-11ea-8745-38a31c3b3e73.jpg)

![r11](https://user-images.githubusercontent.com/39439201/80964844-d6f21900-8e11-11ea-809d-0701c441ef75.jpg)

**What should happen:**
- _Dead player should be **on** platform not under it_
- _Res player should have a stable platform to stand on_

**Comment by Lumber-Jack-2** [comment]
if you die here https://i.imgur.com/BDrRaSQ.jpg you are pprted on death a bit higher, then you land on the platform again after that.

**Comment by Echinaceax** [comment]
Fix confirmed in dev

![rev1](https://user-images.githubusercontent.com/39439201/81206771-dea9ed00-8fcc-11ea-9e4d-f40b1883fda3.jpg)
