### ISSUE TITLE
[BOSS] Al'Akir (Loot on HC Mode) - Throne of the Four Winds

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4445]
**Links:**

![loot3](https://user-images.githubusercontent.com/39439201/80924243-17a55000-8d88-11ea-9ee5-06d316b078cc.jpg)

**What is happening:**
- loot table incorrect
- dropping 1 bop too much

**What should happen:**
10man and heroic - 1 tier token and 2 items (1 shoulders of the forlorn and 1 bop)
25man and hc - 3 tier tokens, 2 shoulders of the forlorn and 4 bop

**other info**
25man is fine

**Comment by Danie123** [comment]
This should be the loot.

The loot/player ratio is equal on normal non-end bosses. On end bosses it's 0,3/player (2 drops + 1 token) on 10man, 0,32/player (5 drops + 3 tokens) on 25.
On heroic token dropping bosses it's 0,3/player (2 drops + 1 token) on 10man, 0,36/player (6 drops + 3 tokens) on 25 - on bosses that don't drop tokens 0,2/player (2 drops) on 10man, and 0,24/player (6 drops) on 25man.

**Comment by Danie123** [comment]
Eg

10Man Normal - 1 Token + 2 Drops
10Man heroic - 1 Token + 2 Drops
25Man Normal - 3 Tokens + 5 Drops
25Man Heroic - 3 Tokens + 6 Drops

**Comment by Echinaceax** [comment]
and always on hc for the _shoulders of the forlorn_ of the 2 or 6 drops

10man 1 _shoulders of the forlorn_ + 1 item
25man 2 _shoulders of the forlorn_ + 4 items

correct?

**Comment by Danie123** [comment]
> 
> 
> Eg
> 
> 10Man Normal - 1 Token + 2 Drops
> 10Man heroic - 1 Token + 2 Drops
> 25Man Normal - 3 Tokens + 5 Drops
> 25Man Heroic - 3 Tokens + 6 Drops

Tokens is Head token or Shoulder Token. Like above mentioned drops.

**Comment by Keader** [comment]
check now please

**Comment by Echinaceax** [comment]
does dev server need restart @Keader ?

Coz its the same on token boss (end boss) 
4 instead of 3 10man hc 

![4items](https://user-images.githubusercontent.com/39439201/81583996-72573100-93b2-11ea-9f2f-e049328bdb5b.jpg)

here is 25man hc 

![6](https://user-images.githubusercontent.com/39439201/81586792-62d9e700-93b6-11ea-8227-b77892242b0f.jpg)

**Comment by Danie123** [comment]
10M Normal
Drops 1 Token - Correct
Drops 1 Item must drop 2

10M Heroic
Drop Token - Correct
Drop Item - Correct

25M Normal
Drops 2 Tokens must drop 3
Drops 2 Items must drop 5

25M Heroic
Drops 2 Tokens must drop 3
Drops 4 Items must drop 6
