### ISSUE TITLE
[NPC] Innkeeper Shul'kar - (Fixed) - Badlands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#445]
- The inn in "new kargath" isn't giving "rested" zzz

https://www.wowhead.com/npc=9356/innkeeper-shulkar

**Edited to add** 
- Fixed

**Comment by Dranah** [comment]
Was this worked on or simply the problem is gone or what?

**Comment by Echinaceax** [comment]
no idea tbh
