### ISSUE TITLE
[Quest] The Embalmer's Revenge - ID 26727-Duskwood

### ISSUE THREAD

**Issue by gantor2** [WoWManiaUK/Blackwing-Lair#446]
- The creature required to kill "Stitches" will not spawn.
Stitches - ID 43862

https://wow.gamepedia.com/The_Embalmer%27s_Revenge

**Comment by gantor2** [comment]
https://wow.gamepedia.com/The_Embalmer%27s_Revenge

**Comment by Saintres** [comment]
Stitches is still not showing up when i got the quest

**Comment by jarvik76** [comment]
Still not working as at Sept 18th

**Comment by Echinaceax** [comment]
@jarvik76 they know 
unfortunately other prios atm are being done ..they will get to them

**Comment by Rushor** [comment]
By Kanariya (56,604 –  9·54·531)  on 2010/12/27 (Patch 4.0.3) |   |  
-- | -- | --
After six years of rofl-stomping afk lowbies along the road to Darkshire, he's now just a level 23 elite with about 1/4th of his original hp. Duskwood has lost much of its epicness.

just spawn on quest accept needed

**Comment by Rushor** [comment]
![I](https://i.imgur.com/B82vdOx.jpg)
