### ISSUE TITLE
[Quest] War Dance - Mulgore

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4460]
**Links:**

Quest - https://www.wowhead.com/quest=24540/war-dance
npc - https://www.wowhead.com/npc=36931/orno-grimtotem

**What is happening:**
- NPC missing
- village empty

**What should happen:**

**Is it crashing the server?:**

**Other Information:**
- Defeat _Orno Grimtotem at Stonetalon Pass._
- _Should be other npcs there too_ 

https://www.wowhead.com/quest=24540/war-dance#videos:id=4415

**Other info**
Reported by an ingame player

**Comment by mfranca0009** [comment]
### These are the enemy mobs that should be fighting in that area:

**Grimtotem Defender** - https://www.wowhead.com/npc=37178/grimtotem-defender

### These are the friendly mobs fighting with the Grimtotem Defenders:

**Thunder Bluff Brave** - https://www.wowhead.com/npc=37175/thunder-bluff-brave

### One kodo located by a hut:
**Grimtotem Pack Kodo** - https://www.wowhead.com/npc=37185/grimtotem-pack-kodo

### When Orno Grimtotem is almost dead, Baine Bloodhoof appears and they both have a short conversation scene:
**Baine Bloodhoof** - https://www.wowhead.com/npc=36648/baine-bloodhoof

### Then there is two of these mobs that spawn in when Baine spawns in: 
**Grimtotem Ambusher** - https://www.wowhead.com/npc=37062/grimtotem-ambusher

Baine kills Orno, player does not.

### Screenshots:
https://www.wowhead.com/npc=37178/grimtotem-defender#screenshots:id=244989
https://www.wowhead.com/npc=37062/grimtotem-ambusher#screenshots:id=257498

**Comment by mfranca0009** [comment]
### UPDATE

**Done So Far**

- Added Grimtotem Defenders
- Added Thunder Bluff Braves
- Added Grimtotem Pack Kodo
- Added Orno Grimtotem
- Made Grimtotem Defenders have a 2h ready emote and melee-ready byte value
- Added creature texts for Orno Grimtotem and Baine Bloodhoof

**Remaining Work**

- Scripting (texts sent at proper time, skills being utilized by Baine, Baine spawning in, Grimtotem Ambushers spawning in) 
- Make sure this scene only occurs when a player is on the quest

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 

![fixed2](https://user-images.githubusercontent.com/39439201/104570367-1f74fe00-5652-11eb-9ae7-5e4929ae658d.jpg)
