### ISSUE TITLE
[ACHIVEMENTS]  Ghosts in the Dark

### ISSUE THREAD

**Issue by baalvi** [WoWManiaUK/Blackwing-Lair#4466]
Achivements: Ghosts in the Dark
Link: https://www.wowhead.com/achievement=5453/ghosts-in-the-dark**

**What is happening:**
when i want jump to water and nothing happened

**What should happen:**
when work to will jump to water tp underground kill a boss and drop for q and achivements

**Comment by Echinaceax** [comment]
Added to main report #4505
