### ISSUE TITLE
[INSTANCE] Zul'Aman -(normal mode)

### ISSUE THREAD

**Issue by Danie123** [WoWManiaUK/Blackwing-Lair#4469]
### On DEV 

**Links:**
https://www.wowhead.com/zulaman
from WoWHead or our Armory

**What is happening:**
There is not any NPC in the instance. Cant test it at all.

**What should happen:**
There should be bosses, Npc's, quest givers. Cannot test anything.

**Is it crashing the server?:**
No

**Other Information:**

**Comment by Echinaceax** [comment]
- [ ] Akil'zon <Eagle Avatar> https://www.wowhead.com/npc=23574/akilzon
- [ ] Nalorakk <Bear Avatar> https://www.wowhead.com/npc=23576/nalorakk
- [ ] Jan'alai <Dragonhawk Avatar> https://www.wowhead.com/npc=23578/janalai
- [ ] Halazzi <Lynx Avatar> https://www.wowhead.com/npc=23577/halazzi
- [ ] Hex Lord Malacrass https://www.wowhead.com/npc=24239/hex-lord-malacrass
- [ ] Daakara <The Invincible> https://www.wowhead.com/npc=23863/daakara

**Comment by Echinaceax** [comment]
this needs closing, i thought you meant HC :)
Zul normal mode in cata doesnt exist was removed from cata, only HC mode now 

https://wow.gamepedia.com/Zul%27Aman_(instance)

![zul2](https://user-images.githubusercontent.com/39439201/89404184-da02eb00-d719-11ea-806f-4716439d17a9.jpg)
![zul1](https://user-images.githubusercontent.com/39439201/89404191-dbccae80-d719-11ea-8b0b-975582c10613.jpg)
