### ISSUE TITLE
[NPC/Questgiver] Marble Slab - Badlands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#447]
Quest giver - https://www.wowhead.com/object=206336/marble-slab
Quest - https://www.wowhead.com/quest=27886/the-sentinels-game

- Slab gives duplicate Quests 

![dupe quests](https://user-images.githubusercontent.com/39439201/50984480-4ef04d80-1502-11e9-87f3-b17156be3b3f.jpg)

**Comment by Dranah** [comment]
Is not really duplicate, one of the ally version, other is the horde. This is a problem with the quests missing faction requirements.

**Comment by Kitzunu** [comment]
Delete cache and check now, hopefully it is fixed :D

**Comment by Echinaceax** [comment]
"deleted cache" yes
@Kitzunu - doesnt give any quests now 

![slab](https://user-images.githubusercontent.com/39439201/56080574-13b43200-5e03-11e9-8fb4-71b5d66f3eae.jpg)

**Comment by Kitzunu** [comment]
I think I might know the issue, I will try to fix it later today :)
