### ISSUE TITLE
[Quest] Head Games  - Drak'tharon Keep

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4470]
**Links:**
quest - https://www.wowhead.com/quest=13129/head-games

**What is happening:**
- [x] Remove prerequisite quest, "Search and Rescue"
- [x] Add new "Kurzel" NPC that was added in Cataclysm (4.3.0)

**What should happen:**
Per Cataclysm changes, there shouldn't be a prerequisite for this quest since the new Kurzel NPC that was added offers the quest at the beginning of the dungeon, or you can pick it up from the old Kurzel NPC after saving it from a spider web from "Search and Rescue" if you missed picking it up at the beginning of the dungeon.

**Other Information:**
Reported by ingame player

**Comment by golosomie** [comment]
Can confirm.

**Comment by mfranca0009** [comment]
Per WoWhead, https://www.wowhead.com/quest=13129/head-games

Kurzel and Mack Fearsen are quest enders for this quest. Looking into what the appropriate text should be if this is not it.

**Comment by mfranca0009** [comment]
This is not an issue, per this video for Drak'Tharon Keep, you can see the player completes the quest and gets the description that is shown above at or around 5:58:
https://www.youtube.com/watch?v=TcbF0wpGePw

**Comment by golosomie** [comment]
Either Kurzel should be made a quest ender or the quest text should be changed. Right now they don't match.

**Comment by golosomie** [comment]
@mfranca0009 Turn-in location changed in cata. Note that wowhead lists 2 seperate versions of Kurzel:
Wotlk version: You get this quest from the [NPC that was freed from the spiderwebs](https://www.wowhead.com/npc=26664/kurzel) after the first boss. You turn it in in Grizzly Hills.
Cata version: You get this quest from [another version of Kurzel](https://www.wowhead.com/npc=55677/kurzel) that is chilling at the start of the instance, and turn it in at the same NPC.

**Comment by mfranca0009** [comment]
Video is from 2015 though, wouldn't this mean that this is after the Cataclysm change if there was one? @golosomie

**Comment by golosomie** [comment]
@mfranca0009 Exactly. the video shows the cata version of the quest, while we have the WotLK version currently

**Comment by mfranca0009** [comment]
I've updated the report for the correct issue, and it should be fixed 👍

**Comment by golosomie** [comment]
Confirmed fixed on dev

**Comment by mfranca0009** [comment]
Fixed in live 👍
