### ISSUE TITLE
[Quest] [ The Walking Nightmare] [Darkshore]

### ISSUE THREAD

**Issue by rzenne** [WoWManiaUK/Blackwing-Lair#4471]
https://www.wowhead.com/quest=13587/the-waking-nightmare

from WoWHead or our Armory

**What is happening:**
After talking with Thessera and starting the quest the Nightmare Guardian is not appearing so you can obtain the Emerald Scroll.

**What should happen:**
https://www.wowhead.com/quest=13587/the-waking-nightmare#videos:id=32970
**Is it crashing the server?:**

**Other Information:**

**Comment by rzenne** [comment]
abandon the quest. went back worked fine. I kept touching the portal and then guardian will not appear.

**Comment by Echinaceax** [comment]
ok thanks for updating @rzenne :)
