### ISSUE TITLE
[Quest/Item] A Dish Best Served Huge (ID: 26602) - The Cape of Stranglethorn

### ISSUE THREAD

**Issue by polymorphism98** [WoWManiaUK/Blackwing-Lair#4476]
**Links:** https://www.wowhead.com/quest=26602/a-dish-best-served-huge

**What is happening:** 
1. Acquire the quest and go to 49, 81.
2. There is a wrecked boat at that location.
3. The boat should be interactable and you should be able to use the[ quest item](https://www.wowhead.com/item=59054/giant-crate-of-giant-food) on it.

**What should happen:**
1. The boat is not interactable and the quest item doesn't get used there, preventing from advancing in the quest.

**Is it crashing the server?:** No

**Other Information:** Example: https://www.youtube.com/watch?v=QDbvhHD7V8s

**Comment by Echinaceax** [comment]
Reported here already #1549
thanks from reporting though
