### ISSUE TITLE
[QUEST] [Silverpine Forest] The Warchief Cometh

### ISSUE THREAD

**Issue by Marc-Andre-Grondin** [WoWManiaUK/Blackwing-Lair#4478]
**Links:**

WowHead : https://www.wowhead.com/quest=26965/the-warchief-cometh

**What is happening:**

After you accept the quest from the NPC, nothing is happening.

**What should happen:**

From what I gather, a discussion between multiple parties of NPCs.

update by Echi

- [x] Lady Sylvanas Windrunner mounted horse (fixed) 
- [x] Val'kyr's missing https://wowwiki-archive.fandom.com/wiki/Val%27kyr
- [x] resurrection of their dead enemies (fallen human) too (forsaken trooper) 
- [x] Portals from Orgrimmar arrive with Hellscream (missing)
- [x] Garrosh Hellscream missing
- [x] missing Voice with text https://wowwiki-archive.fandom.com/wiki/Quest:The_Warchief_Cometh
- [x] Agatha Res spell
- [x] Quest credit

**Comment by Echinaceax** [comment]
Confirmed 
Alot wrong with this actually, full event missing


![image](https://user-images.githubusercontent.com/39439201/112477641-83632380-8d73-11eb-8865-63e80f4ba8c9.png)


- [x] Lady Sylvanas Windrunner mounted horse (fixed) 
- [x] Val'kyr's missing https://wowwiki-archive.fandom.com/wiki/Val%27kyr
- [x] resurrection of their dead enemies (fallen human) too (forsaken trooper) 
- [x] Portals from Orgrimmar arrive with Hellscream (missing)
- [x] Garrosh Hellscream missing
- [x] missing Voice with text https://wowwiki-archive.fandom.com/wiki/Quest:The_Warchief_Cometh
- [x] Agatha Res spell
- [x] Quest credit


Agatha
https://wowwiki-archive.fandom.com/wiki/Agatha

Arthura
https://wowwiki-archive.fandom.com/wiki/Arthura

Daschla
https://wowwiki-archive.fandom.com/wiki/Daschla

**how it should be** 
https://www.wowhead.com/quest=26965/the-warchief-cometh#videos:id=37356

![missing ](https://user-images.githubusercontent.com/39439201/112478657-80b4fe00-8d74-11eb-908c-6ecf8ae21e25.jpg)

**Comment by Echinaceax** [comment]
bq next update

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
All confirmed fixed in ptr 😄
