### ISSUE TITLE
[Quest/NPCs] Looks Like a Tauren Pirate to Me (Quest ID: 26630) - The Stranglethorn Vale

### ISSUE THREAD

**Issue by polymorphism98** [WoWManiaUK/Blackwing-Lair#4479]
**Links:** https://www.wowhead.com/quest=26630/looks-like-a-tauren-pirate-to-me

**What is happening:**
1. Acquire the quest from [Fleet Master Seahorn](https://www.wowhead.com/npc=2487/fleet-master-seahorn)
2. Go to [Bossy](https://www.wowhead.com/npc=43505) and talk to her. She has no options to interact with.
3. Go to [Narkk ](https://www.wowhead.com/npc=2663/narkk)and talk to him. He has no options to interact with.
4. Without steps 2 and 3, the quest is not complete able.

**What should happen:** Bossy and Narkk should interact and provide the required quest items: [Cow Head](https://www.wowhead.com/item=59147) and the [Hat](https://www.wowhead.com/item=59148/oversized-pirate-hat), to complete the quest.

**Is it crashing the server?:** No

**Other Information:**  https://www.youtube.com/watch?v=aiIw9L9UaU8

Note: This quest is needed to complete another quest: https://www.wowhead.com/quest=26629/seeing-where-your-loyalties-lie (You cannot complete this quest without completing the parent quest.)

**Comment by rzenne** [comment]
already reported #720
