### ISSUE TITLE
[Quest/NPC] Zen'Kiki, the Druid (Quest ID: 26953) - Western Plaguelands

### ISSUE THREAD

**Issue by polymorphism98** [WoWManiaUK/Blackwing-Lair#4481]
**Links:** https://www.wowhead.com/quest=26953/zenkiki-the-druid

**What is happening:**
1. NPC [Zen'Kiki ](https://www.wowhead.com/npc=44863/zenkiki) doesn't follow the player, once the quest is acquired.
2. I tried talking to him after getting the quest, but no option to interact.

**What should happen:** Zen'kiki should follow you around as you kill the beasts around, to complete the quest.

**Is it crashing the server?:** No

**Other Information:** https://www.youtube.com/watch?v=fmz0XttNr5Y

**Comment by Echinaceax** [comment]
already reported #375
and on the .bq command
