### ISSUE TITLE
[Quest/NPC] Zen'Kiki and the Cultists (Quest ID: 26955) - Western Plaguelands

### ISSUE THREAD

**Issue by polymorphism98** [WoWManiaUK/Blackwing-Lair#4482]
**Links:** https://www.wowhead.com/quest=26955/zenkiki-and-the-cultists

**What is happening:**

1. NPC Zen'Kiki doesn't follow the player, once the quest is acquired.
2. I tried talking to him after getting the quest, but no option to interact.

**What should happen:** Zen'kiki should follow you around as you go to the quest location, and heal the NPC [Captive Plaguebear](https://www.wowhead.com/npc=44902/captive-plaguebear)

Is it crashing the server?: No

Other Information: https://www.youtube.com/watch?v=FnZ9ceCvLsA

**Comment by Echinaceax** [comment]
already reported #376 
and is on the .bq command
