### ISSUE TITLE
[Boss] Magmaw (25man) - Blackwing Descent

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4484]
**Links:**

magma spit http://cata.cavernoftime.com/spell=99867

![magma spit2](https://user-images.githubusercontent.com/39439201/81456736-cf28d080-9193-11ea-8106-1eaa587ba390.jpg)

http://cata.cavernoftime.com/spell=99867

**What is happening:**
- Magma spit definately to high dmg 
_No healing through that dmg_ 
- Raiders where stacked correctly 

**What should happen:**
https://www.wowhead.com/npc=41570/magmaw#videos:id=250

**more infomation** 
one still open here for 10man #4292, same issue on 25man

**Comment by Echinaceax** [comment]
Tested 

- No issue found, dmg is fine 

note:
- Players need to be geared (not green or pvp geared) 
- Not low than 25 people, 
- Good strong healers though the stack phase (magna spit)

**Comment by Calmwindx** [comment]
Magmaw is still hitting people more than once with his magma. It appears to hit multiple times because it is hitting people close to you in the raid.
https://imgur.com/a/c77KIsM

**Comment by Echinaceax** [comment]
all is good with 2nd tactic GM said :)

@keader can you check the amount of people it hits please,  should be 8 random players on 25man
http://cata.cavernoftime.com/spell=99867

**Comment by Keader** [comment]
```cpp
Trinity::Containers::RandomResize(targets, GetCaster()->GetMap()->Is25ManRaid() ? 8 : 3);
```
Already is 8 targets in 25 man and 3 targets in 10 man
