### ISSUE TITLE
[Quest ] [To Stonard] [Swamp of Sorrows]

### ISSUE THREAD

**Issue by rzenne** [WoWManiaUK/Blackwing-Lair#4486]
https://www.wowhead.com/quest=27871/to-stonard

http://cata.cavernoftime.com/quest=27871

from WoWHead or our Armory

**What is happening:**
This quest is for horde players but is being giving to ally players

**What should happen:**
Should only be given to horde players
**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
Is it the same npc thats giving it to Ally @rzenne 
https://www.wowhead.com/npc=46071/lord-itharius

**Comment by rzenne** [comment]
Yes it is the same npc

**Comment by Echinaceax** [comment]
Thanks @rzenne :)

**Comment by mfranca0009** [comment]
Issue should be fixed, needs testing 👍

**Comment by Echinaceax** [comment]
confirmed fixed in ptr 👍
