### ISSUE TITLE
[Quest] High Priestress Jeklik

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Blackwing-Lair#4488]
https://www.wowhead.com/quest=26553/high-priestess-jeklik

https://www.youtube.com/watch?v=4Aux_5aVSJM
https://classic.wowhead.com/npc=14517/high-priestess-jeklik

In  this  quest  you have  to  destroy the  corps of the  npc High Priestress Jeklik
The  npc is  missing

![image](https://user-images.githubusercontent.com/33811022/81488153-7de91180-9265-11ea-8fe5-5ccce15d485e.png)

**Comment by Thelonnious** [comment]
Duplicate #4418
