### ISSUE TITLE
[Archivement] The Camel hoarder

### ISSUE THREAD

**Issue by dagget1337** [WoWManiaUK/Blackwing-Lair#4491]
**What is happening:**
So i´ve had the luck that i found a camel statue which teleported me to Feralas where i kill that elite guy who drops the Grey camel mount, which upon use gives the Archivement Scourer of the Eternal Sands [Archivement id: 5767], Which also gives the Title "The Camel Hoarder".
Everything works, except the Title, i didnt receive it even though it says so in the archivement

**What should happen:**
Upon receiving the Archivement [id: 5767] the Character should receive an Title as Reward.

**Is it crashing the server?:**
no

**Other Information:**
Character i receive the Title on [Trixie, lvl 85, Horde, Paladin]

**Comment by Echinaceax** [comment]
Confirmed by GM from Ticket
GM checked this and Trixie does have the **Scourer of the Eternal Sands achivement**
https://www.wowhead.com/achievement=5767/scourer-of-the-eternal-sands

**Comment by Echinaceax** [comment]
Added to main report #4505

**Comment by mfranca0009** [comment]
Should be all set and marked on main report 👍

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR

![image](https://user-images.githubusercontent.com/39439201/126990033-ed37707c-0133-4e1f-bbeb-948eed31f238.png)

**Comment by mfranca0009** [comment]
Fixed in live 👍
