### ISSUE TITLE
Northrend - Sholazar Basin  [Song of Wind and Water] - Oracles Daily quest. 

### ISSUE THREAD

**Issue by deni6** [WoWManiaUK/Blackwing-Lair#4494]
https://www.wowhead.com/quest=12726/song-of-wind-and-water

This quest is daily for reputation with Oracle, 
when you use https://www.wowhead.com/item=39571/drums-of-the-tempest
you gain the form of Haiphoon during this form you need to attack the Storm Revenant 
once the revenant is on low HP you use your 3th skill to devour it then you get form of Revenant and killing Agueous spirits. 
The problem here is that the spell while in form does like 10+20dmg therefore you can`t kill anything and devour it. The quest require the mobs to be devoured.

Please take a look Oracles reputation gives egg (dragon mount).

Thanks.

**Comment by Lumber-Jack-2** [comment]
should trigger more damage now.
