### ISSUE TITLE
[NPC] Tunawa Stillwind (missing) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4496]
**Links:**

npc https://cata.cavernoftime.com/npc=37137
for quest back https://cata.cavernoftime.com/quest=24504

**What is happening:**
- npc miss for quest back

**What should happen**
_Npc need spawning_

_Patrol the trail east and kill any high road scouts you find along the way, then speak to Tunawa Stillwind just up the path._

**Comment by mfranca0009** [comment]
Needs testing in PTR 👍

**Comment by Echinaceax** [comment]
confirmed fixed 

![fixed7](https://user-images.githubusercontent.com/39439201/85997367-b3aaab00-ba09-11ea-82ae-cf167b881641.jpg)

**Comment by rzenne** [comment]
Holgom is there, but Tunawa Stillwind is not.

**Comment by mfranca0009** [comment]
The fix was never posted to the live realm yet, is it missing on test realm? @rzenne

**Comment by Echinaceax** [comment]
@rzenne hasnt gone live yet :)
on next server update ..when janitor does it 

@mfranca0009 no, Ive confirmed fixed on PTR :)
