### ISSUE TITLE
[Raid]  Insane Client Crashes - Throne of the Four Winds

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4498]
**What is happening:**
- 20 - 25 CLIENT CRASHES

**What should happen:**
no client crashes please 

**Is it crashing the server?:**
no

**Other Information:**
- this could be due to the group fps/lag/phasing issue https://github.com/WoWManiaUK/Blackwing-Lair/issues/4192#issuecomment-602485720
- Or too many people on the slipstream, when jumping platforms eg: https://gyazo.com/e1f39f8403a2ab1468092735be66678d

5 went on Rohash slipsteam 
5 went on Anshal slipsteam

i think its the distancing coz this issue is  all over the server https://github.com/WoWManiaUK/Blackwing-Lair/issues/4192#issuecomment-602485720 this has to be fixed, phasing when players are to far away from each other

**Comment by wow-mania** [comment]
Not a server crash.

**Comment by Echinaceax** [comment]
not a server crash , a client crash :)

**Comment by Keader** [comment]
Test if fixed please (if caused by lag issue)

**Comment by Echinaceax** [comment]
Push it to live @Keader please https://github.com/WoWManiaUK/Blackwing-Lair/issues/4192#issuecomment-628355772
then the Paradox guild can confirm it on next run :)

**Comment by Echinaceax** [comment]
lag issue was fixed by this fix #4192

Confirmed by Paradox guild, no more lag issue or crashes now :)
thanks @Keader
