### ISSUE TITLE
[Raid] Lootmaster issue - Throne of the Four Winds

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4499]
**What is happening:**
- As lootmaster the loot master couldnt give items to rollers 
- BoP items also didnt have the tradeable 2 hour window 

**What should happen:**
the lootmaster should be able to loot all items and the give to the roll winners 
items should have a tradeable timer of 2 hours so that items can be trade with that raid group

**Other Information:**

**Comment by Echinaceax** [comment]
No issue tested on Dev 

![loot works fine](https://user-images.githubusercontent.com/39439201/82048419-f3653f80-96b4-11ea-9295-7a8299b7cda2.jpg)

Tested a different lootmaster

![keaders test](https://user-images.githubusercontent.com/39439201/82048825-98801800-96b5-11ea-8dcd-31d51f2d638d.jpg)

and 2hour timer 

![1](https://user-images.githubusercontent.com/39439201/82049457-a1251e00-96b6-11ea-92ca-dff223541f40.jpg)

**update**
We did after more test reproduce this issue

**Comment by Keader** [comment]
fixed.
Only happens in alkair.
