### ISSUE TITLE
[Npc/items]- All Hatefury Group Listed below- Desolace

### ISSUE THREAD

**Issue by gantor2** [WoWManiaUK/Blackwing-Lair#450]
- The Npc's listed below are missing multiple quest item drops from their loot tables, they are as follows. 

Satyr Saber ID #48943     https://www.wowhead.com/item=48943/satyr-saber
Satyr Flesh ID #48857   https://www.wowhead.com/item=48857/satyr-flesh

Killed 100, disabled addons, killed some more to confirm.

Haterfury Rogue - ID 4670
Hatefury Trickster - ID 4671
Hatefury Felsworn - ID 4672
Hatefury Betrayer - ID 4673
Hatefury Shadowstalker - ID 4674 
Hatefury Hellcaller - ID 4675

**Comment by Dranah** [comment]
Which quest is this related to?

**Comment by Dranah** [comment]
Desolace is not a starting zone.

**Comment by Echinaceax** [comment]
@Rushor - this quest offers both Horde and Ally quests too :)
