### ISSUE TITLE
[Worgen DKs] Cant join RDF 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4501]
**What is happening:**
### they get the message "you do not meet the requirements"
- worgen DKs cant join RDF he did all his questline in DK startzone 
_I believe the recent fix for naughty worgens leaving Gilneas has interfered with the DK worgen_

**What should happen:**
DK worgen should not be affected by the recent fix for the other worgen classes  that require to have completed **"The Howling Oak for Worgen"** https://github.com/WoWManiaUK/Blackwing-Lair/issues/4431#issuecomment-621776312

**Is it crashing the server?:**
no

**Other Information:**
Another DK has confirmed they have the same issue in discord

**Comment by Echinaceax** [comment]
@Rushor Seen your comment in dev chat 
here is the last quest they need https://www.wowhead.com/quest=13166/the-battle-for-the-ebon-hold for the requirement

**Comment by Echinaceax** [comment]
any update on this @Rushor ?

**Comment by Lumber-Jack-2** [comment]
if player has not rewarded the quest 28517 and player is worgen and player is not deathknight > lfg fails

all else cases for worgen > lfg will work
