### ISSUE TITLE
[Quest] [They grow up so fast] [Winterspring]

### ISSUE THREAD

**Issue by rzenne** [WoWManiaUK/Blackwing-Lair#4503]
**Links:**
https://www.wowhead.com/quest=29034/they-grow-up-so-fast
from WoWHead or our Armory

**What is happening:**
After receiving baby cub it is not giving out daily quests for you to collect the whiskers

**What should happen:**

**Is it crashing the server?:**

**Other Information:**

Was closed as fixed but think it stopped working and needs to be looked at again.

**Comment by Echinaceax** [comment]
i replied on original #3775
