### ISSUE TITLE
[Quest] Ix'lar the Underlord (27487)

### ISSUE THREAD

**Issue by Ubertje** [WoWManiaUK/Blackwing-Lair#4509]
I have accepted the quest and done the requirements for it.
Upon returning to the Eastwall Tower, the person to turn in the questgiver is not there

https://www.wowhead.com/quest=27487/ixlar-the-underlord

This is my first report. Hopefully did it right

**Comment by rzenne** [comment]
You need to fly to Thondroril river to find her and turn in quest.  The marker needs to be moved.

**Comment by Echinaceax** [comment]
is this quest doable ?

video shows the questback is at the tower https://www.youtube.com/watch?v=0p3abXbwBNE

she should be at the tower https://www.wowhead.com/npc=45417/fiona

**Comment by Echinaceax** [comment]
tested and doable yes = npc is in wrong location 
![shes here](https://user-images.githubusercontent.com/39439201/107535743-51ca3a80-6bc1-11eb-866c-29857133fcb1.jpg)

![fiona ](https://user-images.githubusercontent.com/39439201/107535720-4a0a9600-6bc1-11eb-9449-631b7204e414.jpg)

**Comment by Echinaceax** [comment]
opened one main report here #5082
