### ISSUE TITLE
[Quest] Ten Pounds of Flesh - ID 14358 - Desolace

### ISSUE THREAD

**Issue by gantor2** [WoWManiaUK/Blackwing-Lair#451]
- Currently from the statue "Elune's Brazier" you can pick up  4 versions of the same quest. 

- Both Horde and Alliance versions of this quest duplicated on one character from one faction.

https://www.wowhead.com/search?q=Ten+Pounds+of+Flesh

**Comment by Dranah** [comment]
Does it have any consequences like interfere with the quest (or its follow ups) being completed?

**Comment by Dranah** [comment]
Will look at it later.

**Comment by Dranah** [comment]
Desolace is not a start zone.

**Comment by glcabatuan** [comment]
**Quest:**  http://cata.cavernoftime.com/quest=14358
**NPC/s:**  http://cata.cavernoftime.com/npc=35581
**Item/s:**  http://cata.cavernoftime.com/item=48857
**Spell/s:**  http://cata.cavernoftime.com/spell=67733

Still, the brazier won't react even if 10 fleshes have been collected and used. 

*Additionally, Quest is duplicated as well. see image below:

![image](https://user-images.githubusercontent.com/27143135/70479005-69b6b200-1b17-11ea-8db6-f3418c1061f9.png)

**Comment by Echinaceax** [comment]
already added to .bq

**Comment by mfranca0009** [comment]
Quest log showing only 1 quest (not duplicating) and you are able to complete objective from using the item (stack of 10 Satyr Flesh):

![image](https://user-images.githubusercontent.com/26092980/103180636-84181680-4865-11eb-8367-e46913580e98.png)

![image](https://user-images.githubusercontent.com/26092980/103180640-91cd9c00-4865-11eb-94ca-f75696efca43.png)

![image](https://user-images.githubusercontent.com/26092980/103180643-972ae680-4865-11eb-9f94-f2355674be01.png)

![image](https://user-images.githubusercontent.com/26092980/103180647-9a25d700-4865-11eb-8190-07c23938abe7.png)

The buff is also applied on quest turn-in. I'm not sure what changed but it is currently functioning on PTR as it should.

**Comment by Echinaceax** [comment]
tested again on live as requested , still bugged :P @mfranca0009 

**Currently from the statue "Elune's Brazier" you can pick up 4 versions of the same quest.
Both Horde and Alliance versions of this quest duplicated on one character from one faction.**

could pick x2 tho not x4 

![image](https://user-images.githubusercontent.com/39439201/103181463-826c4400-48a1-11eb-8501-7553afb82b3c.png)

and deliver seperately ally and horde quest for double rewards

**Comment by mfranca0009** [comment]
This should be fixed now, the `Ten Pounds of Flesh` quest should only available for the proper faction (horde for horde quest or vice versa).
