### ISSUE TITLE
[Quest] The Princess Unleashed - Arathi Highlands

### ISSUE THREAD

**Issue by Valik84** [WoWManiaUK/Blackwing-Lair#4516]
**Links:**
The Princess Unleashed Quest
from WoWHead or our Armory

**What is happening:**
When you use the stone to summon the Princess it won't summon her no matter how many times you try says you need the stone to summon her when the stone is right in front of you 

**What should happen:**
when you click on the stone to summon the princess it should summon her so you can kill her to complete the quest

**Is it crashing the server?:**
no
**Other Information:**

I hope that this will help

**Comment by Echinaceax** [comment]
I was sure this was reported before hmm, cant see it though 
quest http://cata.cavernoftime.com/quest=26912
quest item http://cata.cavernoftime.com/item=4472

i can confirm from my own tests months ago this isnt working

**Comment by Echinaceax** [comment]
reported here #339 for horde side and Ally
