### ISSUE TITLE
[Quest] [Healing in a flash]

### ISSUE THREAD

**Issue by rzenne** [WoWManiaUK/Blackwing-Lair#4519]
**Links:**
http://cata.cavernoftime.com/quest=27066
from WoWHead or our Armory

**What is happening:**
when you try using Flash Heal on the wounded braves their health goes up but you don't receive credit for it.

**What should happen:**

**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
Confirmed in dev
no quest credit

**Comment by mfranca0009** [comment]
Wrong Spell ID in DB, wasn't triggering quest credit.

**Comment by Echinaceax** [comment]
confirmed fixed in PTR

![confirmed fixed](https://user-images.githubusercontent.com/39439201/88475877-2d17b980-cf34-11ea-96de-c1a58a7e59f3.jpg)
