### ISSUE TITLE
Shamman dispell

### ISSUE THREAD

**Issue by Lakilazo** [WoWManiaUK/Blackwing-Lair#4521]
https://www.wowhead.com/npc=47120/argaloth#comments
Shammans cant dispell consuming darkness on Argaloth in Baradin Hold. There were 2 shammans healing, one is draenei and one was dwarf. Also I have talent for cleanse spirit so I can dispell magic and curse. Thank you very much for looking into this trouble. 
Here is the link of the spell
https://www.wowhead.com/spell=51886/cleanse-spirit
Cheers!

**Comment by Echinaceax** [comment]
thanks @Lakilazo 
Remoted will confirm if they also have issue with this 

waiting feedback

**Comment by Echinaceax** [comment]
### Update from dev 

Tested on draenei (cleanse spirit) doesnt work (see my video)
https://gyazo.com/14e118b4cb3482287a742d7c7cd9963a

Cleanse spirit should remove **consuming darkness** from the player as  it's a **magical debuff**

![cleanse spirit](https://user-images.githubusercontent.com/39439201/82734638-8a1ca680-9d1c-11ea-892f-a9b78d107986.jpg)

**More info**
could be coz of recent fix #4318
waiting feedback from player - Remoted for their class test

**Comment by Phoenix9867** [comment]
I'll update this post when tested, please wait till this evening when i find a ground to join BH, i also will record it with shadow play. (Remoted)

**Comment by Keader** [comment]
fixed
