### ISSUE TITLE
[Quest] It‘s Goat Time, Baby - Badlands

### ISSUE THREAD

**Issue by Asklaba** [WoWManiaUK/Blackwing-Lair#4524]
https://www.wowhead.com/quest=27776/its-goat-time-baby

The quest tells u to kick 12 goats off the cliff with the Billy Goat Blaster but actually the goats seem to not respawn, so basically u see zero goats around the zone which makes the quest impossible to do.

the issue is, that there isn‘t a single goat and u need to kick 12 off in total
Its not crashing the server xd

**Comment by Echinaceax** [comment]
Confirmed 
Should be aleast 12x npc=46393 missing

**Comment by mfranca0009** [comment]
Quest item used was kicking the goats off of the cliff but never despawning them. The goats were far away from the mountain on the ground.

Once the goat is hit by spell, they will despawn after 5 seconds (length of buff given to goat). This makes sure they are in their proper spot at the top of the mountain at all times.

**Comment by Echinaceax** [comment]
Confirmed fixed in ptr 

![12](https://user-images.githubusercontent.com/39439201/88378824-07f34180-cda2-11ea-811d-cb3faabf9d66.jpg)
