### ISSUE TITLE
[Quest] Razorbeak Friends (Quest ID: 26546) - The Hinterlands

### ISSUE THREAD

**Issue by polymorphism98** [WoWManiaUK/Blackwing-Lair#4525]
**Links:** https://www.wowhead.com/quest=26546/razorbeak-friends

**What is happening:**
1. Use the supplied [quest item](https://www.wowhead.com/item=58935/gryphon-chow) on the [gryphons](https://www.wowhead.com/npc=2657/trained-razorbeak).
2. The player gets no credit. Quest is not completeable.

**What should happen:**
1. Using the quest item should give credit and the quest should be completed.

**Is it crashing the server?:** No

**Other Information:** https://www.youtube.com/watch?v=lJ5hk7hOj6o

**Comment by Echinaceax** [comment]
confirmed in dev 
No quest credit given

**Comment by mfranca0009** [comment]
Needs testing in PTR, action list created and movement type set with proper flags_extra value set on creature_template.

**Comment by Echinaceax** [comment]
confirmed fixed in dev 
only other issue i see now is that you get double credit per one 

![2 for 1](https://user-images.githubusercontent.com/39439201/88378218-db8af580-cda0-11ea-8426-d0dda683ee47.jpg)

**Comment by Echinaceax** [comment]
Update - now only giving 1 per credit. thanks @mfranca0009 :)

**Comment by Echinaceax** [comment]
UPDATE
Something happened to the fix

**Comment by Echinaceax** [comment]
Better now ❤️ uploaded live tomorrow 

![conf2](https://user-images.githubusercontent.com/39439201/90505236-90bb8e00-e152-11ea-91af-65a4ba5b974a.jpg)
