### ISSUE TITLE
The Day that Deathwing Came

### ISSUE THREAD

**Issue by Asklaba** [WoWManiaUK/Blackwing-Lair#4526]
https://www.wowhead.com/quest=27714/the-day-that-deathwing-came-the-real-story

https://www.wowhead.com/quest=27715/the-day-that-deathwing-came-what-really-happened

The quests „The Day that Deathwing Came: The Real Story“ and „The Day that Deathwing Came: What really happend“ are not working - u can't speak to the npc‘s as u should be able to.

Normally u should be able to talk to the npcs to complete the quests, the npc‘s don‘t have a talk option for some reason
No, its actually not crashing the server xd

**Comment by Echinaceax** [comment]
reported already but thanks @Asklaba :)
#449

**Comment by polymorphism98** [comment]
@Echinaceax - The one reported in #449 is for 27713.
But there are two other quests with the similar name. Their IDs: 27714 and 27715 as mentioned in this issue's description above.

27713 is already addressed and put on .BQ as a part of #449 , but the other two aren't. It would be great if the other two can also be addressed somehow and if possible, be put on .BQ. That way, these three connected epic quests can have a full closure. Just a suggestion :)
