### ISSUE TITLE
The Warden‘s Game + The Sentinels Game - Badlands

### ISSUE THREAD

**Issue by Asklaba** [WoWManiaUK/Blackwing-Lair#4527]
https://www.wowhead.com/quest=27885/the-wardens-game

https://www.wowhead.com/quest=27886/the-sentinels-game

ye idk u simply can‘t do anything with those statues and u need to move em in the right direction to complete the quest but actually they‘re not even clickable

Normally u should be able to move em and change their direction to complete these 2 little puzzles

Actually its not crashing the server.

**Comment by Echinaceax** [comment]
reported already #448 for The Sentinels Game

**Comment by rzenne** [comment]
The warden's game #4438

**Comment by Echinaceax** [comment]
thank you @rzenne :)
