### ISSUE TITLE
[Quest] To The Hilt ID - 14357 - Desolace

### ISSUE THREAD

**Issue by gantor2** [WoWManiaUK/Blackwing-Lair#453]
- You can pick up the horde and alliance version of this quest at the same time from "Elune's Handmaiden"
- The creatures required to complete this quest do not drop the items needed 

 Item - Satyr Sabre ID - 48943
https://www.wowhead.com/quest=14219/to-the-hilt

**Comment by Rushor** [comment]
partly fixed condition for quest accept added

**Comment by Rushor** [comment]
70 percent chance now
