### ISSUE TITLE
[Quest] [Vortex] [Ashenvale}

### ISSUE THREAD

**Issue by rzenne** [WoWManiaUK/Blackwing-Lair#4531]
**Links:**
https://www.wowhead.com/quest=13888/vortex
from WoWHead or our Armory

**What is happening:**

NPC the vortex does not have an option to get vortex ability from it to fight  Lord Magmathar

**What should happen:**
https://www.youtube.com/watch?v=aHkbHY19AuI
**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
reported here #1022
