### ISSUE TITLE
[Achievement] Defender of a Shattered World - Missing rewarded title

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4532]
**Links:**

Achievement https://www.wowhead.com/achievement=5506/defender-of-a-shattered-world
title https://www.wowhead.com/title=227/defender-of-a-shattered-world

**What is happening:**

- [x] title reward not given

**What should happen:**
When you complete the requirements for this Achievement player should get the Achievement and reward title 

**Is it crashing the server?:**
no 

**Other Information:**

Reported to a GM

**Comment by Echinaceax** [comment]
Added to main report #4505

**Comment by mfranca0009** [comment]
Should be fixed now 👍

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 

![image](https://user-images.githubusercontent.com/39439201/126983330-ba5e82a1-26a3-4362-9d96-96fc6f8e51ef.png)

![image](https://user-images.githubusercontent.com/39439201/126983287-8ff2e548-01f2-4b37-add7-33a74e63c45a.png)

**Comment by mfranca0009** [comment]
On live 👍
