### ISSUE TITLE
[Quest]The Amulet of Sevine (Quest ID: 26168) - Blasted Lands

### ISSUE THREAD

**Issue by polymorphism98** [WoWManiaUK/Blackwing-Lair#4536]
**Links:** https://www.wowhead.com/quest=26168/the-amulet-of-sevine

**What is happening:**
1. Acquire the quest from [Kasim Sharim](https://www.wowhead.com/npc=42298/kasim-sharim).
2. Talk to NPC: [Salt-Flop](https://www.wowhead.com/npc=41265/salt-flop)
3. Upon talking to the NPC, there is no option to talk about the amulet.

**What should happen:**
1. Player should be able to talk to the NPC for the amulet and complete the quest by getting the quest item.

**Is it crashing the server?:** No

**Other Information:** https://www.youtube.com/watch?v=DUnu99Y1GA0

**Comment by Echinaceax** [comment]
reported already here #4270 
thanks though @polymorphism98
