### ISSUE TITLE
[Quest] The Bait for Lar'korwi - ID 24733 - Un'Goro Crater #516

### ISSUE THREAD

**Issue by rzenne** [WoWManiaUK/Blackwing-Lair#4537]
**Links:**
Quest - http://cata.cavernoftime.com/quest=24733
from WoWHead or our Armory

**What is happening:**
Doesn't appear to be working again. you place the meat but when you try to use preserved-pheromone-mixture it keeps saying you need the meat. after watching video if appears the meat is not being placed on the rock which is why mixture doesn't work.

**What should happen:**
https://www.youtube.com/watch?v=f-dNgzWsC5k
**Is it crashing the server?:**

**Other Information:**

**Comment by coffeelover38** [comment]
i think you are doing something wrong because i did it 6 hours ago just fine.

**Comment by Echinaceax** [comment]
It was reported and fixed here #516
dont open new report just use the old reports that way coders know they fixed it once before if it is regression @rzenne
