### ISSUE TITLE
[Death Knight] Pacified character

### ISSUE THREAD

**Issue by Lockthaar** [WoWManiaUK/Blackwing-Lair#4538]
Hi guys, 

I'm a lvl 62 DK (Darshehk) and I have a problem with "pacification". It started at Orgrimmar. I'm friendly with 1000/6000 points of reputation, but I still cannot interact with the NPC's and the game tells me I'm "Pacified" and that I cannot interact. 

I then went to Outlands and Thrallmar where the same thing happened. I'm not able to speak with NPC's and take some of the quests. I tried to start the ones i could take, and now I cannot event attack the mobs since i'm still "Pacified". Can you fix this for me please. It's been days and I cannot progress with my character

I don't understand what I did wrong since I finished all the DK questline.

Thank you for your help

PS: Here are the screenshots

![WoWScrnShot_052820_120403](https://user-images.githubusercontent.com/65899815/83128415-aed99b00-a0db-11ea-8b90-477643a5b076.jpg)

![WoWScrnShot_052820_120344](https://user-images.githubusercontent.com/65899815/83128404-aaad7d80-a0db-11ea-84bb-55b5047749df.jpg)

**Comment by Echinaceax** [comment]
Not sure it a bug as such @Lockthaar 
what i would do is make an ingame ticket and the GMs can check your questline or any hidden auras you might have on your char ...never seen this before 

going to look up "pacified" its odd

here is a possible reason https://truewow.org/forum/viewtopic.php?t=11513

Seems you didnt finish the DK startzone correctly and left to either go to the Mall or join an instance RDF any DK that leaves the startzone before finishing the questline fully bugs their own char

Therefor nothing a dev can do to fix players mistake
