### ISSUE TITLE
 [Quest] Death Comes From on High (Issue 2) - (Undead DK)  

### ISSUE THREAD

**Issue by ajoderalpersonal** [WoWManiaUK/Blackwing-Lair#4542]
**Links:**

from WoWHead or our Armory

**What is happening:**
im at the Chapel and i can't complete the quest

**What should happen:**
Quest should be complete able

**Is it crashing the server?:**
no

**Other Information:**

I tried to do with 2 Undead .. not success...

**Comment by Echinaceax** [comment]
reported here already @ajoderalpersonal #1899
Thanks for reporting

@Rushor http://cata.cavernoftime.com/quest=12641
I did my test on a Bloodelf months ago for questline report with no issues  :)

**Comment by Echinaceax** [comment]
Tested on live server undead DK - NO issues 

![no issue](https://user-images.githubusercontent.com/39439201/83334638-29571600-a2a8-11ea-8b0b-877a8987a881.jpg)

quest complete fine 

![no undead issue](https://user-images.githubusercontent.com/39439201/83334645-3411ab00-a2a8-11ea-9025-fd3311776b0e.jpg)

make sure you are updated to 1.1.0 and using Reign client
