### ISSUE TITLE
[NPC] Gek Nozzlerocket - phasing issue

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#455]
**command board (Undercity)**

-  Report to Gek Nozzlerocket at Light's Hope Chapel in the Eastern Plaguelands
Quest - https://www.wowhead.com/quest=28580/warchiefs-command-badlands

- Gek Nozzlerocket is not at the location at EPL
NPC - https://www.wowhead.com/npc=48704/gek-nozzlerocket

- Had to get a taxi to Badlands from a GM

**Comment by sarahkay88** [comment]
Same issue for alliance
Prevents the pick up for the following quests:
https://www.wowhead.com/quest=27762/fuselight-ho

**Comment by Fritzjof** [comment]
NPC still does not appear.
Date: 7/17/2019

**Comment by Rushor** [comment]
ingame now

![I](https://i.imgur.com/ec1KagM.jpg)
