### ISSUE TITLE
[NPC] Ticker -49002- (missing) - Twilight Highlands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4559]
**Links:**

https://www.wowhead.com/npc=49002/ticker

**What is happening:**
- npc missing 

**What should happen:**
needed for https://www.wowhead.com/quest=28592/parting-packages

**Comment by mfranca0009** [comment]
Added ticker, adjusted his phase, and adjusted his equipment template to replicate screenshots / videos of how he should be. Needs testing in PTR.
