### ISSUE TITLE
[Fishing Daily] Tadpole Terror - Tirisfal Glades

### ISSUE THREAD

**Issue by rzenne** [WoWManiaUK/Blackwing-Lair#4563]
**Links:**
https://www.wowhead.com/quest=29319/tadpole-terror
from WoWHead or our Armory

**What is happening:**
I finished from lvl 50 to lvl 140 with baubles on my line and caught zero Giant Flesh-Eating Tadpoles at Stillwater pond.

**What should happen:**
https://www.youtube.com/watch?v=5TraM8pmTlI
**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
- [ ]  this quest is missing gold (worth) payment too

**Comment by Echinaceax** [comment]
added to main report #5181
