### ISSUE TITLE
[Quest] Keep the Fires Burning - 13890 - Ashenvale

### ISSUE THREAD

**Issue by Marc-Andre-Grondin** [WoWManiaUK/Blackwing-Lair#4566]
**Links:**

https://www.wowhead.com/quest=13890/keep-the-fires-burning

**What is happening:**

You can get the blubbers from the hydras, cook it into oil but can't use it in the lighthouse.

**What should happen:**

You should be able to use it in the lighthouse's fire

**Is it crashing the server?:**

No

**Other Information:**

Video: https://www.youtube.com/watch?v=90NHV2JdEUc

**Comment by Echinaceax** [comment]
was reported here #1027 and supposed to have been fixed @Marc-Andre-Grondin 
i will reopen old report to let the devs know thanks
