### ISSUE TITLE
[NPC] Overlord Krom'gar -42106 - Stonetalon Mountain

### ISSUE THREAD

**Issue by Marc-Andre-Grondin** [WoWManiaUK/Blackwing-Lair#4573]
**Links:**

https://www.wowhead.com/quest=26101/might-makes-right

**What is happening:**

The NPC Overlord Krom'gar is missing. It's him that finishes the quest.

**What should happen:**

The NPC should be there to finish the quest.

**Is it crashing the server?:**

No.

**Other Information:**

Video: https://www.youtube.com/watch?v=8nk3G9goetE

**Comment by Echinaceax** [comment]
npc https://www.wowhead.com/npc=42106/overlord-kromgar

**Comment by Echinaceax** [comment]
Fixed in PTR
Added NPC 42106 @mfranca0009

**Comment by mfranca0009** [comment]
All set, needs testing in PTR 👍 @Echinaceax

**Comment by Echinaceax** [comment]
confirmed fixed in ptr
