### ISSUE TITLE
[Quest] Brother Against Brother - Sethekk Halls

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4575]
**Links:**

quest http://cata.cavernoftime.com/quest=29605

**What is happening:**
- Lakka has no dialog for rescue 

**What should happen:**
_Free Lakka from captivity. Return to Isfar inside the Sethekk Halls when you've completed the rescue._
https://www.wowhead.com/quest=29605/brother-against-brother#videos:id=95273

**Comment by mfranca0009** [comment]
Needs testing in PTR 👍

**Comment by Echinaceax** [comment]
confirmed fix PTR

![fixed22](https://user-images.githubusercontent.com/39439201/89510064-64a62180-d7d0-11ea-8adc-54bb49ebaefb.jpg)
