### ISSUE TITLE
[NPC] Dr. Hieronymus Blam - Badlands - Priority

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#458]
https://www.wowhead.com/npc=46664/dr-hieronymus-blam

- NPC area bugged (mobs)
- Pack of 4-5 wolves or dogs killed me while i was collecting the quest 
- mobs are flat on the ground, not stood up

![flat bug](https://user-images.githubusercontent.com/39439201/51035968-01301f80-15ac-11e9-8ca8-2544c8eb63ee.jpg)

- No matter where i rez they "slide" across the ground and kill me 
- Cant collect quests before i die

![bugged](https://user-images.githubusercontent.com/39439201/51036300-ff1a9080-15ac-11e9-81a9-3de64b2b2541.jpg)

- Had to sacrifice health spell to be able to pick quests up 

![sacrafic health](https://user-images.githubusercontent.com/39439201/51036585-d941bb80-15ad-11e9-9082-538cd99a65ea.jpg)

- Side note, NPC gives Horde ally quests 
#460 
#459 

- And cant hand in quest
#461

**Comment by Dranah** [comment]
These are multiple issues within one thread. Keep in mind, 1 report = 1 issue

As for the mobs killing you, this is not a problem with the quest giver NPC , he's in correct position. I'll open new thread for the bugged adds. (Stonevault Wanderers)
