### ISSUE TITLE
[Dungeon] stratholme is linked to wrong graveyard 

### ISSUE THREAD

**Issue by stoerebtw** [WoWManiaUK/Blackwing-Lair#4583]
**Links:**

https://classic.wowhead.com/stratholme

**What is happening:**

Whene we wiped in Stratholme we were teleported to the graveyard in Westfall ; Sentinel Hill
We could not get in a dungeon to be revived (we tried the deadmines but WoW knew it was the wrong one )

**What should happen:**

We should have been teleported to a graveyard somewhat close to stratholme

**Is it crashing the server?:**

nope

**Other Information:**

**Comment by Echinaceax** [comment]
from what i can find from caveroftime yes there should be a few spirit healers and one nearer the dungeon 
http://cata.cavernoftime.com/npc=6491

![ep spirit healer](https://user-images.githubusercontent.com/39439201/85668445-065d2d80-b6bf-11ea-9115-94a54b28da44.jpg)

**Comment by mfranca0009** [comment]
AreaTable.dbc

IDs from this dbc are used for tracking ghost position before being teleported to graveyard

IDs

2017 - Stratholme
2279 - Stratholme
4100 - The Culling of Stratholme
5513 - Stratholme Entrance
5514 - Stratholme Service Entrance
5560 - The Culling of Stratholme Entrance
5916 - Stratholme Main Gate
5917 - Stratholme Service Entrance


WorldSafeLocs.dbc

IDs from this dbc are used for graveyard zones

IDs

510 - Eastern Plaguelands, Pestilent Scar
634 - Eastern Plaguelands, Darrowshire
909 - Eastern Plaguelands, Blackwood Lake
927 - Eastern Plaguelands , Graveyard CG Tower
1369 - Eastern Plaguelands, Ebon Hold GY
1370 - Ebon Hold GY - Chapter 2/3 (related?)
1371 - Ebon Hold GY - Chapter 4 (related?)
1405 - Eastern Plaguelands, Acherus
1448 - Eastern Plaguelands, Northdale
1449 - Eastern Plaguelands, Stratholme
1450 - Eastern Plaguelands, West Graveyard
3244 - Eastern Plaguelands, Stratholme (Back Entrance)

Best bet would be 1449 being the closest spirit healer / graveyard for Stratholme. Will look into this.

**Comment by Echinaceax** [comment]
Fix confirmed in dev 
thanks @mfranca0009
