### ISSUE TITLE
[Dungeon] (hc) - Zul'Gurub 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4585]
### Will add this here for now as next patch report 

**Links:**
https://wow.gamepedia.com/Patch_4.1.0
https://wowwiki.fandom.com/wiki/Zul%27Gurub

video for future https://www.youtube.com/watch?v=JmI4LwuTfiw
https://www.youtube.com/watch?v=1GC9x9eKIYM

- [ ] Zanzil's Cauldron of Toxic Torment - not clickable at times 
https://www.wowhead.com/npc=52529/zanzils-cauldron-of-toxic-torment

- [x] Giant Sack - Empty 
https://www.wowhead.com/item=69818/giant-sack#contains

- [x] Gub's Catch - empty 
https://www.wowhead.com/item=69823/gubs-catch#contains

- [x] Mysterious Gurubashi Bijou - drops when you dont have the quest 
https://www.wowhead.com/quest=29242/putting-a-price-on-priceless

**Comment by Thelonnious** [comment]
To the testers. you need to kill  Zanzi first to bi able to klick on  Zanzi's Cauldron.

**Comment by Echinaceax** [comment]
> To the testers. you need to kill Zanzi first to bi able to klick on Zanzi's Cauldron.

The green gas cauldrons im taking about are not just at Zanzil, im talking about in general!!
- Cant you just check the cauldron thanks
there isnt just one green cauldron  

FYI @Xman993 - you dont have to "kill Zanzil first" to have the ability to use the cauldron, its to use throughout the fight depending on which phase your on 😄 

https://www.youtube.com/watch?v=GBuR9IVhmOE

**Comment by Echinaceax** [comment]
confirmed 3/4 fixed on PTR

- [x] Mysterious Gurubashi Bijou - drops when you dont have the quest still
https://www.wowhead.com/quest=29242/putting-a-price-on-priceless

Still not fixed still dropped without having the quest in my  quest log 

![not fixed](https://user-images.githubusercontent.com/39439201/89591038-78419e80-d849-11ea-8e9b-a9a99b734dac.jpg)


_i completed this quest and handed it in on my first run_
