### ISSUE TITLE
[Dungeon] Boss loots (hc) - Zul'Aman 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4586]
**Links:**
https://wow.gamepedia.com/Zul%27Aman_(instance)

![zul aman hc 85](https://user-images.githubusercontent.com/39439201/86159779-1768cd00-bb0b-11ea-9697-8c85f4d7b52a.jpg)

- [x] Akil'zon - Lvl 87 but 70 loot

![Akil zon 87 loot 70](https://user-images.githubusercontent.com/39439201/86159050-023f6e80-bb0a-11ea-8161-6ddd571c7b1a.jpg)

- [x] Nalorakk Lvl 87 but 70 loot

![nalorkk loot 70](https://user-images.githubusercontent.com/39439201/86159348-78dc6c00-bb0a-11ea-890f-ba3945655437.jpg)

- [x] Jan'alai Lvl 87 but 70 loot

![jan alal 70 loot](https://user-images.githubusercontent.com/39439201/86159409-97426780-bb0a-11ea-90fb-205ab9a2c8f4.jpg)

- [x] Halazzi Lvl 87 but 70 loot

![halazzi loot 70](https://user-images.githubusercontent.com/39439201/86159467-af19eb80-bb0a-11ea-80fa-6edab9f5e4ce.jpg)

- [x] Hex Lord Malacrass Lvl 87 but 70 loot

![hex lord malacrass loot 70](https://user-images.githubusercontent.com/39439201/86159536-c9ec6000-bb0a-11ea-9ded-7c96aa9bcab9.jpg)

- [x] Daakara Lvl 87 but 70 loot

![daakara loot 70](https://user-images.githubusercontent.com/39439201/86159600-e1c3e400-bb0a-11ea-8fa1-ad10a03b2436.jpg)

**Comment by Lumber-Jack-2** [comment]
updated the loot. pls just do ingame:

 .reload creature_loot_template
.reload reference_loot_template

and it should be fixed

**Comment by Echinaceax** [comment]
@Rushor no change, still 70 gear 

1. I did clear cache 
2. **.reload creature_loot_template** and **.reload reference_loot_template**

![still same](https://user-images.githubusercontent.com/39439201/87235146-fccf0780-c3d8-11ea-8209-a74737442a35.jpg)


![70 still2](https://user-images.githubusercontent.com/39439201/87235153-0f494100-c3d9-11ea-9a68-58566959d83b.jpg)

**Comment by Echinaceax** [comment]
- [ ] Akil'zon
- [ ] Nalorakk
- [ ] Jan'alai
- [ ] Halazzi
- [ ] Hex Lord Malacrass
- [ ] Daakara

**Comment by Echinaceax** [comment]
Reopened @Xman993 
Fix on live is still 70 loot for all bosses even tho on DEV was fixed i just checked again, need to ask Jani what went wrong because DEV first boss is 353  and the rest are  is lvl 70 gear still


- [x]  Akil'zon (85 gear)
- [x] Nalorakk (70 gear)
- [x] Jan'alai (70 gear)
- [x] Halazzi (70 gear)
- [x] Hex Lord Malacrass (70 gear)
- [x] Daakara (70 gear)

Confirmed still bugged by Online GM

**Comment by mfranca0009** [comment]
Fixed, needs testing in PTR 👍 

Hex Lord Malacrass drops a quest item, this needs to be tested to make sure it is dropping when player has quest and not dropping when player doesn't have quest.

quest item: https://www.wowhead.com/item=69264/the-hex-lords-fetish
quest: https://www.wowhead.com/quest=29186/the-hex-lords-fetish

Daakara drops a Chaos Orb with a 87% chance while dropping gear.

**Comment by Echinaceax** [comment]
Confirmed fixed again in PTR thanks @mfranca0009 

- [x]  Akil'zon (85 gear)
- [x] Nalorakk (85 gear)
- [x] Jan'alai (85 gear)
- [x] Halazzi (85 gear)
- [x] Hex Lord Malacrass (85 gear)
- [x] Daakara (85 gear)
- [x] Hex Lord Malacrass dropped quest item (while on quest)
- [x] Daakara drops a Chaos Orb
