### ISSUE TITLE
[Quest] The Dark Tower - Redridge Mountains

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4587]
**Links:**

quest https://www.wowhead.com/quest=26693/the-dark-tower

**What is happening:**
- No key dropping 
player killed 4 times and no key

**What should happen:**
_Recover the Key of Ilgalar._

**Other Information:**
Reported by GM from ticket

**Comment by mfranca0009** [comment]
I can confirm this, no item ID for "Key of Ilgalar" in General Fangore loot table. Also, it seems he may be dropping less items than usual. Will fix loot table completely.

There's no information on this NPC on Cavern of Time database site, will be using information from WoWhead.

**Comment by mfranca0009** [comment]
Quest item should now drop when player has quest, and full loot table has been adjusted; needs testing in PTR 👍

**Comment by Echinaceax** [comment]
confirmed fixed in PTR

![fixed 44](https://user-images.githubusercontent.com/39439201/89512448-8bb22280-d7d3-11ea-9807-834608c2f8ec.jpg)
