### ISSUE TITLE
[Quest] It's About Time! - Western Plaguelands ID: 27156

### ISSUE THREAD

**Issue by Leonardojrr** [WoWManiaUK/Blackwing-Lair#4591]
**Links:**

https://www.wowhead.com/quest=27156/its-about-time

**What is happening:** You can't challenge the Hearthglen Trainee

**What should happen:** You should be able to talk with the Hearthglen Trainee and fight with them

**Is it crashing the server?:** No

**Comment by Echinaceax** [comment]
reported here already #723
this is on the .BQ 27156 ingame command atm
