### ISSUE TITLE
[Object] Door stays locked (hc) - Zul'Aman

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4595]
**Links:**

https://wow.gamepedia.com/Hex_Lord_Malacrass

![door is locked](https://user-images.githubusercontent.com/39439201/86467745-40b97100-bd36-11ea-8eeb-34ea9978c1d0.jpg)

**What is happening:**
- after killing Hex Lord Malacrass
_the door stays locked and cant move to last boss_ 

**What should happen:**
_Door should open to let players get to last boss (i think)_

**Comment by mfranca0009** [comment]
I just watched a Hex Lord Malacrass kill video from Cataclysm Zul'Aman heroic and door doesn't open automatically after Hex Lord Malacrass is killed.

https://www.youtube.com/watch?v=Iz47-e6WdyU

Need more information on this to make sure it works as it should blizzlike

**UPDATE**

Player should be able to open door when Hex Lord Malacrass is dead.

**Comment by mfranca0009** [comment]
Fixed door locking issue through Hex Lord Malacrass's script 👍  Once Hex Lord Malacrass is dead, it will be unlocked and any player from the group should be able to open it.

Hex Lord Malacrass's script is still in-progress though, since he still doesn't function properly with his attacks.

**Comment by Echinaceax** [comment]
fix in dev confirmed
