### ISSUE TITLE
[Quest] The Captive Scouts - (hc) - Zul'Aman

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4596]
**Links:**

quest http://cata.cavernoftime.com/quest=29217

**What is happening:**
- cant Free the captive scouts - no dialog

**What should happen:**
_Free the captive scouts: Hazlek, Bakkalzu, Norkani, and Kasha. They are being held captive by the Amani high priests._

**Comment by mfranca0009** [comment]
https://www.wowhead.com/npc=52939/hazlek
https://www.wowhead.com/npc=52941/bakkalzu
https://www.wowhead.com/npc=52943/norkani
https://www.wowhead.com/object=187379/norkanis-cage
https://www.wowhead.com/object=186667/norkanis-package
https://www.wowhead.com/npc=52945/kasha
https://www.wowhead.com/object=187380/kashas-cage
https://www.wowhead.com/object=186672/kashas-bag

Norkani and Kasha aren't even spawned, bakkalzu's cage isn't able to be opened, hazlek's cage can be opened, and hazlek looks like he's on fire but bakkalzu doesn't.

Couple things wrong with this, will look at a reference video and fix shortly.

**UPDATE**
Norkani and Kasha's corpses are spawned and they are standing up, their cages are spawned and opened, and both of their container objects are spawned but Kasha's container is spawned inside a tall urn which can't be seen or accessed unless teleported to. 

https://www.wowhead.com/npc=52944/norkanis-corpse
https://www.wowhead.com/npc=52946/kashas-corpse

**Comment by mfranca0009** [comment]
So far, Removed Norkani's Corpse and Kasha's Corpse and put the actual NPCs within their cages and changed the cage states to 1 so they're closed from start. 

Will start scripting their AIs to make them unlock their chests if speed run timer is still active and not finished after saving them.

**Comment by mfranca0009** [comment]
All set, each NPC has been scripted to give quest credit for quest to player that selects the gossip and to party members. They have their events scripted for creature text, unlocking their containers, or making them selectable for the player.

All captive scouts and their containers will despawn if the speed run timer runs out. Hence they're captives because they're about to be sacrificed.

Needs testing in PTR 👍

**Comment by Echinaceax** [comment]
confirmed fixed in PTR

- [x] NPCs fixed and loot chests etc...
- [x] quest completed

![completed](https://user-images.githubusercontent.com/39439201/93671719-ab608a00-faa5-11ea-9c1f-6a327283fd08.jpg)
