### ISSUE TITLE
[Quest] Into the Dragon's Mouth - faction req missing - Badlands (Ally quest)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#460]
**As horde** 
- Horde can pick up ally quests from #458

Quest - https://www.wowhead.com/quest=27826/into-the-dragons-mouth
npc - https://www.wowhead.com/npc=46664/dr-hieronymus-blam

#459

**Comment by Echinaceax** [comment]
**New info noticed** 
- I abandoned this quest (completed i had the egg for Rhea)  
- but now my horde quest has (un-completed) 
Quest -  #461

- I will need to retake the quest to get the egg
https://www.wowhead.com/quest=27859/the-egg-lives-on

**Comment by Dranah** [comment]
Of course because it uses the same quest item as the horde version. If you lose the quest item for one, it affects both quests. You're not supposed to have both of them anyway.
