### ISSUE TITLE
Heartstone problem back to kezan

### ISSUE THREAD

**Issue by darkranger4** [WoWManiaUK/Blackwing-Lair#4600]
**Links:**

from WoWHead or our Armory

**What is happening:**
When playing as a Goblin and finished Kezan, you go to ogrimmar.
I used the heartstone to change the xp rate, but i don't know how to go back to ogrimmar.
Those on the ship do nothing.

**What should happen:**
Create a portal or link to get back to orgrimmar

**Is it crashing the server?:**
No

**Other Information:**
I have a level 7 goblin

**Comment by Echinaceax** [comment]
@darkranger4 
For now, Goblins are automatically ported to Orgrimmar after Kezan (coz Goblin lost isle is not fixed yet) 

When you got to Orgimmar didnt you save your HS at Orgrimmar ?

You will need to make an ingame ticket to get a GM to port you to ogrimmar
