### ISSUE TITLE
[Quest] [The Orc Report] [Dustwallow Marsh]

### ISSUE THREAD

**Issue by rzenne** [WoWManiaUK/Blackwing-Lair#4605]
**Links:**
https://www.wowhead.com/quest=27246/the-orc-report
from WoWHead or our Armory

**What is happening:**
As a horde player I am able to pickup the Spy's Report from the loose dirt.

**What should happen:**
I should not be able to pick it up.
**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
Confirmed, Ally quest can be picked up by horde players

![correct](https://user-images.githubusercontent.com/39439201/87480275-4879ef00-c62d-11ea-91ea-80b1a56f69bd.jpg)
