### ISSUE TITLE
[NPC] Highbank Guardsman (loot) - Twilight Highlands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4608]
**Links:**

http://cata.cavernoftime.com/npc=49023#drop

fish loot https://www.wowhead.com/item=53071/algaefin-rockfish

![algaefin](https://user-images.githubusercontent.com/39439201/87639479-a00b7e00-c745-11ea-822d-ea6542d6e4ab.jpg)

**What is happening:**
- Dropping fish only 
_loot table is wrong_ 

**What should happen:**
_should have a different loot table_ 

**Other Information:**
- also should check the pickpocket loot too 
https://wowwiki.fandom.com/wiki/Highbank_Guardsman

**Comment by mfranca0009** [comment]
Adjusted all loot for highbank guardsman, not enough pickpocket data available to adjust so will leave it alone for now.

**Comment by Echinaceax** [comment]
testing now @mfranca0009 :)
