### ISSUE TITLE
[Quest] New Kargath - faction req missing - prereq missing - Badlands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#461]
Quest - https://www.wowhead.com/quest=27889/new-kargath
npc - https://www.wowhead.com/npc=46664/dr-hieronymus-blam

- NPC not at location 
https://www.wowhead.com/npc=46654/rhea

**Comment by Echinaceax** [comment]
**More info** 

- I abandoned "into the dragons mouth" (completed quest)
- but now my "New Kargath" Quest has (un-completed, lost the egg item for Rhea)

Something its bugged with the npc 
https://www.wowhead.com/npc=46664/dr-hieronymus-blam

**Comment by sarahkay88** [comment]
I can collect this quest on alliance even thought its an horde quest - didn't attempt to hand in due to the horde elites guarding.

**Comment by Dranah** [comment]
Rhea has already been reported. Is there an issue with the faction requirement for this quest?

**Comment by Dranah** [comment]
https://www.wowhead.com/quest=27789/troggish-troubles should be first completed before unlocking this quest

**Comment by Echinaceax** [comment]
> https://www.wowhead.com/quest=27789/troggish-troubles should be first completed before unlocking this quest

Oh...never saw that quest, he didnt have it for me
