### ISSUE TITLE
[Quest/item] Jungle Remedy 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4610]
**Links:**

quest item http://cata.cavernoftime.com/item=2633#dropped-by

**What is happening:**
- Quest item dropping without having the quest 

**What should happen:**
Quest item should only drop if player has the quest active
 http://cata.cavernoftime.com/item=2633#objective-of

**Other Information:**

![jungle](https://user-images.githubusercontent.com/39439201/87848808-af283280-c8e3-11ea-9616-b175fbd02318.jpg)

reported by ingame player 
confirmed my me on dev

**Comment by mfranca0009** [comment]
Set condition to allow quest item drop if quest is active from Kurzen Jungle Fighter, Kurzen Medicine Man, and Kurzen Headshrinker.
