### ISSUE TITLE
[NPC] Highbank Marksman (loot) - Twilight Highlands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4612]
**Links:**

http://cata.cavernoftime.com/npc=49124

**What is happening:**
- Loots table

**Comment by mfranca0009** [comment]
http://cata.cavernoftime.com/npc=49024
http://cata.cavernoftime.com/npc=49124
http://cata.cavernoftime.com/npc=49341
http://cata.cavernoftime.com/npc=49366

All four of these entries of the same mob (Highbank Marksman) will be checked and corrected. Should be done shortly.

**Comment by mfranca0009** [comment]
All entries should have updated loot tables, needs testing on PTR

**Comment by Echinaceax** [comment]
thanks @mfranca0009 :)
