### ISSUE TITLE
[Quest][Maul Em With Kindness][Tanaris]

### ISSUE THREAD

**Issue by rzenne** [WoWManiaUK/Blackwing-Lair#4616]
**Links:**
https://www.wowhead.com/quest=24963/maul-em-with-kindness
from WoWHead or our Armory

**What is happening:**
You are not getting credit for feeding them Delicacy Morsels after weakening them.

**What should happen:**
https://www.youtube.com/watch?v=H4dL-gNk8xs
**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
@mfranca0009 
In PTR the quest item doesnt even work, i get a message " You cant do that yet"  https://www.wowhead.com/item=52044/bilgewater-cartel-promotional-delicacy-morsels

![item](https://user-images.githubusercontent.com/39439201/87916478-c6962580-ca73-11ea-8cfc-4125fa9db46d.jpg)


will need to test this on Live, i will let you know when ive tested live

**Comment by mfranca0009** [comment]
Needs testing in PTR 👍 Creating SQL file tomorrow

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 

![fixed15](https://user-images.githubusercontent.com/39439201/89098419-bec97000-d3e7-11ea-8f9f-4bc7b981df92.jpg)
