### ISSUE TITLE
[NPC] Dragonmaw Skirmisher (loot table) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4618]
**Links:**

npc http://cata.cavernoftime.com/npc=48799
Quest https://wowwiki.fandom.com/wiki/Quest:Something_Brewed

**What is happening:**
- loot table

**What should happen:**
different :)

**Comment by mfranca0009** [comment]
Deleted three entries that were present in their loot table; Dragonmaw Skirmishers shouldn't have loot.
