### ISSUE TITLE
Lost item

### ISSUE THREAD

**Issue by Truthseerguy** [WoWManiaUK/Blackwing-Lair#4619]
**Links:**

After Lycanthoth the Corruptor

**What is happening:**
Cut scene stalls

**What should happen:**
Should ride the wolf to a quest giver after the fight.
**Is it crashing the server?:**
Nope
**Other Information:**
I was stuck after completing the quest. Could not log out, only force quit the application. When I logged back in, my Tattered Dreadmist Shoulders were gone. I had them on during the fight and did not vend them. I went to a vendor and there were no items (none) in their buyback tab, which is very unusual. 
Could I have the shoulders restored so I can hand them down to my alt? Thank you.

**Comment by Echinaceax** [comment]
@Truthseerguy 
Yes the Tattered Dreadmist Shoulders will automatically be unequipped when you lvl past 81 because they are a 1-80 heirloom

they will be in your ingame mailbox  so you can send to other alt you may make in the future 

as for the quest, yes this is reported here for fix #4464
