### ISSUE TITLE
[Quest/ Item] Earthen Hieroglyph - ID 62596 / 62597 - Badlands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#462]
Quest item - https://www.wowhead.com/item=62596/earthen-hieroglyph

- This item too
Quest item - https://www.wowhead.com/item=62597/trogg-tool

- Quest item left overs remain in bags when quest is completed and delivered to quest giver.
Quest- https://www.wowhead.com/quest=27882/its-not-about-history-its-about-power
npc - https://www.wowhead.com/npc=46757/high-examiner-taethelan-bloodwatcher

- Mob drops are given with all kills 
- This could add to the problem of leftover quest items
Mob - https://www.wowhead.com/npc=46773/explorers-league-excavator

**Comment by Dranah** [comment]
if I understand well the problem is that the quest items stay in your bags after you handed in the quests
That means, the quest itself is doable?

**Comment by Echinaceax** [comment]
_Sorry for late reply (recently set my notification settings :)_

yes the quest was completed but the remaining quest items stayed in my bag 

- All kills drops the items and gave more than required so the leftover items remained in my bag 
(have to manually remove them)

**Comment by Echinaceax** [comment]
Sorry for late reply (recently set my notification settings :)

yes the quest was completed but the remaining quest items stayed in my bag 
- All the mobs dropped the quest items which resulted in having to many drops 
(had to manually remove extra items after quest back)

**Comment by Echinaceax** [comment]
@Kitzunu - this issue fixed but ...(noticed in dev when confirming this issue)

- [ ] New issue - theyre dropping these too without having a quest 
https://www.wowhead.com/item=62594/broken-chalice
https://www.wowhead.com/item=62595/dusty-vase

![dev - drops other stuff](https://user-images.githubusercontent.com/39439201/56067341-15d2ae00-5d7b-11e9-9ac5-943a91b94b8e.jpg)
