### ISSUE TITLE
[Quest/item] Marking the Fallen (27856) Horde - - Swamp of Sorrows

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4630]
**Links:**

https://www.wowhead.com/quest=27856/marking-the-fallen
https://www.wowhead.com/item=62548/banner-of-the-fallen

**What is happening:**
- Quest item goes on me instead of the Fallen 

**What should happen:**
_Use the Banner of the Fallen to mark 7 **_Fallen Stonard Warriors._**_

**Other Information:**

**Comment by mfranca0009** [comment]
Same issue as #756, will correct this shortly.

**Comment by mfranca0009** [comment]
Needs testing in PTR

**Comment by Echinaceax** [comment]
Fixed in PTR confirmed 
spawns are better too

![horde fix](https://user-images.githubusercontent.com/39439201/88725064-d248b280-d12b-11ea-9a32-547a809e0f10.jpg)
