### ISSUE TITLE
[General] Bloodmire portal bunny (game markers) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4632]
46771 Bloodmire Portal Bunny

**What is happening:**
- Players shouldnt see game markers

**What should happen:**
should be invisible to players

**Comment by mfranca0009** [comment]
I was able to cast this myself and have a green portal display, but for some reason when Stonard Warlocks cast it, it doesn't show anything or shows a bunny; Still looking into this.

https://www.wowhead.com/spell=87116/ritual-of-summoning-summon-portal
https://www.wowhead.com/spell=33339/green-portal-state
https://www.wowhead.com/spell=87114/ritual-of-summoning

Also, Stonard Warlock is suppose to be acting like he is summoning out of the portal when not in combat while the green portal is there.

**Comment by mfranca0009** [comment]
All set, smart scripting is in place and fixed Bloodmire portal bunny for Stonard Warlocks. Needs testing in PTR 👍 

I also added more Stonard Warlocks because there was only 9 spawned and there should be 23 in that area.

**Comment by Echinaceax** [comment]
Fix confirmed in PTR 

![done](https://user-images.githubusercontent.com/39439201/89017496-ad666200-d31a-11ea-96a3-003bf163f983.jpg)
