### ISSUE TITLE
[General] necropolis flower chicken (game markers)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4633]
**What is happening:**
- Players shouldnt see game markers

**What should happen:**
invisible to players

reported by GM 
confirmed by me and Mfranca

**Other Information:**

![chicken markers](https://user-images.githubusercontent.com/39439201/88964548-d39fe980-d2a9-11ea-8be7-855c8269c25e.jpg)

**Comment by mfranca0009** [comment]
Needs testing in PTR 👍

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR

![FIXED14](https://user-images.githubusercontent.com/39439201/89098180-6f824000-d3e5-11ea-95de-701b0763bd8b.jpg)
