### ISSUE TITLE
[NPC] Darktail Bonepicker (loot) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4634]
**Links:**

http://cata.cavernoftime.com/npc=42235

**What is happening:**
- missing half its loot table

**What should happen:**
- should be 113 not 57 

reported by Mfranca

**Comment by mfranca0009** [comment]
All set, needs testing in PTR 👍

**Comment by Echinaceax** [comment]
Cant really "test in PTR" @mfranca0009 for 113 different loots :)
so we can just say done i think 👍

**Comment by mfranca0009** [comment]
Yes lol makes sense :+1:
