### ISSUE TITLE
[NPC] Marshtide Mage 46775 - (missing) - Swamp of Sorrows

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4635]
**Links:**

npc https://www.wowhead.com/npc=46775/marshtide-mage
quest https://www.wowhead.com/quest=27855/reinforcements-denied

**What is happening:**
- npcs are missing

**What should happen:**
_Needed for quest_

**Comment by mfranca0009** [comment]
Needs testing in PTR 👍

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 

![fixed13](https://user-images.githubusercontent.com/39439201/89098127-0bf81280-d3e5-11ea-8687-39945d1ae747.jpg)
