### ISSUE TITLE
[NPC] Blood seeker 3868

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4645]
**Links:**

https://wow.gamepedia.com/Blood_Seeker
npc=3868

**What is happening:**
- Blood seekers despawn timer is missing (Blood Seeker should automatically despawn after six minutes)
- Research also says its a lvl 15 bat but the spawned one is 20 (not sure if that makes a difference)
_In PTR i npc info the bat and shows no automatic despawn timer at all_

**What should happen:**

![aeonaxx - blood seeker spawn info](https://user-images.githubusercontent.com/39439201/89306190-cf8c1700-d66f-11ea-8f3a-3b3fdabf863c.jpg)
![blood seeker despawn info](https://user-images.githubusercontent.com/39439201/89306198-d155da80-d66f-11ea-9e77-727e4c97713c.jpg)

**Other Information:**
linked to this issue #4640

**Comment by mfranca0009** [comment]
Blood Seeker is now level 15 and has a force despawn after 6 minutes out of combat 👍 Needs testing on PTR.
