### ISSUE TITLE
[Dungeon/raid] (Normal mode) - Zul'Gurub

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4647]
**Links:**

https://wowwiki.fandom.com/wiki/Zul%27Gurub_(raid)

**What is happening:**
- shouldnt be open 

**What should happen:**
needs locking, normal raid was removed in CATA

**Comment by mfranca0009** [comment]
All set, needs testing in PTR 👍

**Comment by Echinaceax** [comment]
this one you can still run in the portal 
(zul aman fix you are stopped completely from entering at normal mode)

up side 
you do get a message 

![ZG MSG](https://user-images.githubusercontent.com/39439201/99183022-2e662f80-2739-11eb-8b17-48b82af3883b.jpg)

**Comment by mfranca0009** [comment]
That's going to happen, only because Zul'gurub is part of the Stranglethorn map.
@Echinaceax
