### ISSUE TITLE
[Dungeon/raid] (Normal mode) - Zul'Aman

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4648]
**Links:**

https://wow.gamepedia.com/Zul%27Aman_(instance)

**What is happening:**
- shouldnt be open

**What should happen:**
need locking, normal mode was removed in cata

**Comment by mfranca0009** [comment]
All set, needs testing in PTR 👍

**Comment by Echinaceax** [comment]
Nice, fixed in PTR 👍 

Note:
I didnt get the HC only message like i got for ZG though
