### ISSUE TITLE
[NPC] Rhea - Missing - Badlands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#465]
- Learn Rhea's true identity.
- NPC Rhea is not at location, hence missing vital other quests lines

Quest - https://www.wowhead.com/quest=27769/rhea-revealed
npc - https://www.wowhead.com/npc=46654/rhea

**other related** 
#461

**Comment by Echinaceax** [comment]
#461

**Comment by Dranah** [comment]
One report per NPC is enough.
