### ISSUE TITLE
[Quest][Whistle of the Venomhide Ravasaur][Un'goro crater]

### ISSUE THREAD

**Issue by rzenne** [WoWManiaUK/Blackwing-Lair#4650]
**Links:**
https://www.wowhead.com/item=46102/whistle-of-the-venomhide-ravasaur
from WoWHead or our Armory

**What is happening:**
Venomhide ravasaur is not allowing it to be account wide

**What should happen:**
Venomhide should be account wide.
**Is it crashing the server?:**

**Other Information:**

**Comment by Thelonnious** [comment]
Account wide mounts are from MOP and up.
