### ISSUE TITLE
[General] Master looter 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4651]
**What is happening:**
- Master looter bug

We was on a World boss, player set master looter. when world boss was dead he DC / crashed, none of us could loot
when lootmaster came back he couldnt loot either, he tried changing looting to group loots but still none of us could loot

when lootmaster changed to me we got a message " loot is still being rolled for" 
but no roll was Shown because the loot master DC 

lost the loot coz World boss Despawned

**What should happen:**
if loot master DC loot master should be passed to different player and not jump back to orginal master looter 
as you see from the SS Vevandare was the master looter then he DC it swapped to me, then back to Vevandare when he relogged, 

i think thats what screwed up the looting tbh 

**Other Information:**
![ash master looted and dc we ll lots loot2](https://user-images.githubusercontent.com/39439201/89827439-e0e58f80-db57-11ea-8926-d731933dcf52.jpg)

**Comment by Echinaceax** [comment]
Update from 15mins ago @mfranca0009 

![give loot to](https://user-images.githubusercontent.com/39439201/100015781-c7034c00-2dd8-11eb-8e6d-8f38d217f4e6.jpg)

**Comment by mfranca0009** [comment]
This issue should now be resolved, I made several changes related to the commit from TrinityCore having a similar problem and needing to update multiple core files (Loot, Player, LootMgr, Item, etc.):
[#13300](https://github.com/TrinityCore/TrinityCore/issues/13300)

After these changes, it seems that it helped when the original master looter re-connected to give the master looter role to someone else, but still could not distribute loot on their own.

To fix this problem all together, I added a condition within the Player core file to reload the master looter's GUID when they re-log in (on _LoadGroup method) IF their GUID matched the original Master Looter GUID for the group.

**Comment by mfranca0009** [comment]
### MAIN ISSUE

- [ ] When master looter crashes or ALT-F4, then a group member tries to loot boss corpse, it will make it impossible for original master looter to distribute loot when logging back in (NO MASTER LIST SHOWS UP).

**If none of the group members try to loot boss corpse, then master looter can re-log in and distribute loot normally.**

**Comment by mfranca0009** [comment]
Almost everything has been done to try resolving the loot issue when the master looter crashes. At this time, simple solution: give someone else the master looter role if original master looter crashes and someone has already looted the creature/boss.

Can't do much of anything else, cause I can't tell what's happening when a player crashes. I assume, it's just not saving the player's data when crashing as it would if the player logged out normally.

Fixed for now 👍

**Comment by Echinaceax** [comment]
Agreed @mfranca0009 
As long as players DONT try and loot when the Masterlooter has DC'd all is fine with what you fixed.

**Players** 
If your master looter has DC/crashed for whatever reason, just wait for them to relog (then there is no issue)
If you do, then what you have to do is: when the master looter relogs they have to assign a new masterlooter then they can loot for the group
