### ISSUE TITLE
[NPC] Zulian Gnasher (spell cast) - Zul'Gurub

### ISSUE THREAD

**Issue by Thelonnious** [WoWManiaUK/Blackwing-Lair#4659]
**Links:**

https://www.wowhead.com/npc=52413/zulian-gnasher

**What is happening:**

dont cast spells 

**What should happen:**
need to cast spells
**Is it crashing the server?:**
no

**Other Information:**

**Comment by Echinaceax** [comment]
@Xman993 
What spells these 2 https://www.wowhead.com/npc=52413/zulian-gnasher#abilities:0+1+17+2 ?

**Comment by Thelonnious** [comment]
yes @Echinaceax

**Comment by Echinaceax** [comment]
Confirmed fixed in dev 

![spells](https://user-images.githubusercontent.com/39439201/90180244-fa344900-ddae-11ea-8d65-580c89cccc2e.jpg)

**Comment by Echinaceax** [comment]
Due to PTR wipe this reverted too

**Comment by mfranca0009** [comment]
SmartAI needs to be done on heroic NPC, it is currently on the normal NPC.
