### ISSUE TITLE
[Quest/Item] Blood of Zul'jin - Zul'Aman

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4663]
**Links:**

https://www.wowhead.com/item=33102/blood-of-zuljin

**What is happening:**
- Quest item dropped 

**What should happen:**
needs removing from game 
in this patch the quest is given at the start of the dungeon by https://www.wowhead.com/npc=52924/voljin

**Comment by mfranca0009** [comment]
This should be fixed after fixing loot for Bosses 👍
