### ISSUE TITLE
[Boss] Nalorakk - Zul'Aman

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4664]
**Links:**
https://www.wowhead.com/npc=23576/nalorakk/heroic-encounter-journal

**What is happening:**
- not attackable
- wrong location

![wrong map info](https://user-images.githubusercontent.com/39439201/90344481-90b87280-e01a-11ea-87b4-2020b83b0988.jpg)

**What should happen:**

- [ ] Should be attackable
- [ ] Should be at coords (40.5, 77.3)  https://www.wowhead.com/npc=23576/nalorakk#map

**Other Information:**
- plus still loot issues #4586

**Comment by mfranca0009** [comment]
Full 30 minute Zul'aman Heroic Run: https://www.youtube.com/watch?v=b3yeYGEgTgQ

This video shows him standing where he currently is, BUT he needs to be scripted where he will continue to run further up to where he should be. He should have yell text and it should almost look like he is sending troops down to kill you. Once you're at the altar, he will say a yell line and send the last 4 mobs to attack you. After these 4 mobs are killed, he will become attackable and you can start the fight with Nalorakk.

**Comment by mfranca0009** [comment]
Currently, Nalorakk's four waves have been scripted so far.

All that's left now is his actual boss events, they should be done shortly.

**Comment by mfranca0009** [comment]
Events and abilities should be functioning properly for Nalorakk now 👍

**Comment by Echinaceax** [comment]
confirmed fix in PTR
