### ISSUE TITLE
[Boss] Jan 'alai - Zul'Aman

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4665]
**Links:**

https://www.wowhead.com/npc=23578/janalai/heroic-encounter-journal

**What is happening:**
- no attacks

**What should happen:**
should use abilities

**Other Information:**
Still has 70 loot #4586

**Comment by mfranca0009** [comment]
Should be attackable off the bat, no scripted event or scene.

**Comment by mfranca0009** [comment]
Should be all set now, needs testing 👍

**Comment by Echinaceax** [comment]
fixed in PTR
fire breath and bird working
