### ISSUE TITLE
[Boss] Hex Lord Malacrass - Zul'Aman

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4666]
**Links:**

https://www.wowhead.com/npc=24239/hex-lord-malacrass/heroic-encounter-journal

**What is happening:**
- no attacks

**What should happen:**
should use abilities

**Other Information:**
Still has 70 loot #4586

**Comment by mfranca0009** [comment]
Should be attackable off the bat, no event or scene needed.

**Comment by mfranca0009** [comment]
This is almost all set, the last thing is the Fire Totem spell needing to be fixed here, #4913.

**Comment by mfranca0009** [comment]
Boss should be complete and scripted fully with all its abilities, needs another group testing on PTR 👍
