### ISSUE TITLE
[NPC] Vol'jin - Zul'Aman

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4667]
**Links:**

npc https://www.wowhead.com/npc=52924/voljin
quest https://www.wowhead.com/quest=11196/warlord-of-the-amani

**What is happening:**
- After picking up the quest from vol'jin at the begining of the dungeon and completing it, he standing at the stairs at the end of the dungeon with the (?)  but still with the "we're ready to open the gates" dialog, 
- lol i tested this and clicked on it,  Vol'jin glitched in the air all the way back to the start of dungeon and now there are 2 Vol'jin 

 **What should happen:**
not sure if the quest back npc Vol'jin should be at the end of the dungeon, just the quest back shouldnt have the dialog 

remove dialog from the quest back, this is only needed for the start of the dungeon

![vol](https://user-images.githubusercontent.com/39439201/90321916-787b2180-df4e-11ea-9f0c-e9f860706d3b.jpg)

coz if not it end up having x2 Vol'jin

![voljin x2](https://user-images.githubusercontent.com/39439201/90321430-c6d9f180-df49-11ea-80a6-e9f4dca47705.jpg)

**Comment by mfranca0009** [comment]
Both Vol'jin and Blood Guard Hakkuz have been fixed. Created a separate script for the second instance of Vol'jin and a new script for Hakkuz. They will now become visible and run up the stairs after Daakara has been killed. Needs testing in PTR 👍

**Comment by Echinaceax** [comment]
confirmed fixed in ptr  👍
