### ISSUE TITLE
Warchief's Command Board - Undercity (Priority)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#467]
Ive seen a pattern with the UC command board 

- ALL quests have had missing NPC in the new areas

#466 
#455
#468
#469

![badlands b](https://user-images.githubusercontent.com/39439201/51048038-44998680-15ca-11e9-819c-68d85a608810.jpg)
![epl b](https://user-images.githubusercontent.com/39439201/51048049-47947700-15ca-11e9-9961-6ae8b39fe9ed.jpg)
![tanaris b](https://user-images.githubusercontent.com/39439201/51048054-495e3a80-15ca-11e9-8fab-49c2089879ca.jpg)
![burning steppes bo](https://user-images.githubusercontent.com/39439201/51057781-e9c25800-15e6-11e9-9701-412602814811.jpg)

**Comment by Dranah** [comment]
Has nothing to do with the command board. These quests have it in common that they are all new cata quests that all start a long chain where the NPC moves and phases according to the progress. All of these NPCs are broken because this is not properly implemented yet.

**Comment by Echinaceax** [comment]
@Rushor @Kitzunu 
https://github.com/WoWManiaUK/Blackwing-Lair/issues/467#issuecomment-455522020

is the issue that Draah comment on going to get fixed then?
