### ISSUE TITLE
[Quest/NPC] Warchief's Command: Tanaris - ID 28509 - Tanaris

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#468]
https://www.wowhead.com/quest=28509/warchiefs-command-tanaris

#424

- I have a suspicion that the command board in Undercity is the problem
- Not 100% sure, needs checking though

**Comment by Dranah** [comment]
This is the same report as https://github.com/WoWManiaUK/Blackwing-Lair/issues/424
There is nothing to fix on the quest, the NPC is there, but phased. Once the NPC is fixed, this quest will be possible to hand in.
