### ISSUE TITLE
[Quest] Wenikee Boltbucket - The Barrens

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4684]
**Links:**

quest https://www.wowhead.com/quest=29026/wenikee-boltbucket
npc https://classic.wowhead.com/npc=9316/wenikee-boltbucket
2nd npc https://www.wowhead.com/npc=34674/brak-blusterpipe

**What is happening:**
- has no dialog to teleport too Wenikee Boltbucket
- return npc has no dialog either 

**What should happen:**

- [x] should teleport to Wenikee Boltbucket
- [ ] should teleport back too Brak Blusterpipe

**Comment by mfranca0009** [comment]
Does not need teleport back to Brak Blusterpipe, the quest for Samophlange ends there and after that, you need to collect bolt slugs that are located near Wenikee Boltbucket.

All set, needs testing in PTR 👍
