### ISSUE TITLE
[Quest][The Amulet of Grol][Blasted Lands]

### ISSUE THREAD

**Issue by rzenne** [WoWManiaUK/Blackwing-Lair#4692]
**Links:**
https://www.wowhead.com/quest=25699/the-amulet-of-grol
from WoWHead or our Armory

**What is happening:**
As an ally player I am able to complete both the ally and horde version of this quest.

**What should happen:**
Should not be able to accept horde quest from Bloodmage Lynnore
**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
@mfranca0009 wrong quest giver for Ally  http://cata.cavernoftime.com/quest=26169


http://cata.cavernoftime.com/?search=The+Amulet+of+Grol#quests
https://cata-twinhead.twinstar.cz/?search=The+Amulet+of+Grol
