### ISSUE TITLE
[Quest][The Amulet of Sevine][Blasted Lands]

### ISSUE THREAD

**Issue by rzenne** [WoWManiaUK/Blackwing-Lair#4693]
**Links:**
https://www.wowhead.com/quest=25698/the-amulet-of-sevine
from WoWHead or our Armory

**What is happening:**
As an ally player I am able to get quest from Bloodmage Lynnore

**What should happen:**
Should not be able to accept horde quest from Bloodmage Lynnore
**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
@mfranca0009 wrong quest giver for ally http://cata.cavernoftime.com/quest=26168


http://cata.cavernoftime.com/?search=The+Amulet+of+Sevine
https://cata-twinhead.twinstar.cz/?search=The+Amulet+of+Sevine
