### ISSUE TITLE
[Quest][The Amulet of Allistarj][Blasted Lands]

### ISSUE THREAD

**Issue by rzenne** [WoWManiaUK/Blackwing-Lair#4694]
**Links:**
https://www.wowhead.com/quest=25697/the-amulet-of-allistarj
from WoWHead or our Armory

**What is happening:**
As an ally player I am able to get quest from Bloodmage Lynnore

**What should happen:**
Should not be able to accept horde quest from Bloodmage Lynnore
**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
@mfranca0009 wrong quest giver for Ally http://cata.cavernoftime.com/quest=26167

http://cata.cavernoftime.com/?search=The+Amulet+of+Allistarj
https://cata-twinhead.twinstar.cz/?search=The+Amulet+of+Allistarj
