### ISSUE TITLE
[Quest][You Are Rakh'likh, Demon] (issue 2) - Blasted Lands

### ISSUE THREAD

**Issue by rzenne** [WoWManiaUK/Blackwing-Lair#4696]
**Links:**
https://www.wowhead.com/quest=25701/you-are-rakhlikh-demon#criteria-of
from WoWHead or our Armory

**What is happening:**
As an ally player I am able to get quest from Loramus Thalipedes

**What should happen:**
Should not be able to accept horde quest from Loramus Thalipedes
**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
Thanks @rzenne :)

Just checked on this and it is for both 
https://cata-twinhead.twinstar.cz/?search=You+Are+Rakh%27likh%2C+Demon
http://cata.cavernoftime.com/?search=You+Are+Rakh%27likh%2C+Demon
