### ISSUE TITLE
[Quest][The Altar of Storms][Blasted Lands]

### ISSUE THREAD

**Issue by rzenne** [WoWManiaUK/Blackwing-Lair#4697]
**Links:**
https://www.wowhead.com/quest=25688/the-altar-of-storms
from WoWHead or our Armory

**What is happening:**
As an ally player not able to do the ally version as it is bugged but able to complete it on horde version.

**What should happen:**
Should not be able to do horde quest
**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
ally version https://www.wowhead.com/quest=26162/the-altar-of-storms
