### ISSUE TITLE
[Profession] Duskwood - Herbalism

### ISSUE THREAD

**Issue by rzenne** [WoWManiaUK/Blackwing-Lair#4699]
**Links:**
https://classic.wowhead.com/object=1628/grave-moss
from WoWHead or our Armory

**What is happening:**
This should be the best place to collect grave moss but is pretty much non-existent in both locations.

**What should happen:**

**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
Was also added to this report #4349
At some point we need a full zone to zone report  of all classic herbs 

@rzenne have you checked these zones **Hillsbrad, Arathi, Wetlands** ?
https://www.wow-professions.com/farming/grave-moss-farming

**Update:** 
x0 Wetlands  
x1 Arathi
x0 Hillsbrad

**Comment by Echinaceax** [comment]
reported on main reports thanks @rzenne
