### ISSUE TITLE
[Talent]  Brain Freeze

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Blackwing-Lair#47]
**How it should work:**
> **Description:** 
>Your spells no longer trigger Arcane Missiles.  Instead, your Frost damage spells with chilling effects have a $h% chance to cause your next Fireball or Frostfire Bolt spell to be instant cast and cost no mana.  When Frostfire Bolt is instant, it can benefit from Fingers of Frost.  Brain Freeze cannot be triggered by Frostfire Bolt.

> **Patch notes:**
> - Cataclysm Patch 4.1.0 (2011-04-26): Can now proc from  [[Frostfire Orb]](https://wow.gamepedia.com/Frostfire_Orb) (Rank 2) 
> - Cataclysm Patch 4.0.1 (2010-10-12): Now causes spells to no longer trigger  [[Arcane Missiles]](https://wow.gamepedia.com/Arcane_Missiles), and causes  [[Frostfire Bolt]](https://wow.gamepedia.com/Frostfire_Bolt) to benefit from  [[Fingers of Frost]](https://wow.gamepedia.com/Fingers_of_Frost). 
> - Wrath of the Lich King Patch 3.3.3 (2010-03-23): This talent now allows your next Fireball or Frostfire Bolt to be instant and cost no mana. There is a small internal cooldown to keep the Frostfire Bolt from immediately triggering Brain Freeze again. 

**How it works:**

1. The Brain Freeze ID:57761 aura
![image](https://user-images.githubusercontent.com/14857593/38629798-460315b4-3dca-11e8-9c1a-72d6d90c86f1.png)
which is a random process of casting frost spells while having the [[Brain Freeze]](https://wow.gamepedia.com/Brain_Freeze) talent, is not fading when player casts Fireball or Frostfire Bolt spell, it only fades after its timer runs out. -> This issue is very similar to #42 
2. It still causes spells to trigger [[Arcane Missiles]](https://wow.gamepedia.com/Arcane_Missiles), which should no longer trigger when the player has  [[Brain Freeze]](https://wow.gamepedia.com/Brain_Freeze) talent.

_Can not check if this talent can process from [[Frostfire Orb] ](https://wow.gamepedia.com/Frostfire_Orb), since it is still not working at all._

**Comment by Keader** [comment]
Fixed, ready to test in next restart.
