### ISSUE TITLE
[Dungeon] Skinning - Zul'Aman

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4701]
**Links:**

Amani Bear - https://www.wowhead.com/npc=23584/amani-bear#skinning
Amani Lynx Cub https://www.wowhead.com/npc=24064/amani-lynx-cub#skinning
Amani Elder Lynx https://www.wowhead.com/npc=24530/amani-elder-lynx#skinning
Amani Crocolisk https://www.wowhead.com/npc=24047/amani-crocolisk#skinning
Tamed Amani Crocolisk https://www.wowhead.com/npc=24138/tamed-amani-crocolisk#skinning (not skinning at all)

**What is happening:**
- Wrong skinning table
- Tamed Amani Crocolisk not skinnable atm

**What should happen:**

- [ ] Should be Cata loot table
- [ ] Tamed Amani Crocolisk should be skinnable

**Comment by mfranca0009** [comment]
All set, corrected all skinning loot tables and needs testing 👍

**Comment by Echinaceax** [comment]
confirmed all 

Tamed Amani Crocolisk also perfect now :)
