### ISSUE TITLE
[NPC] Sullah (missing) Uldum

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4703]
**Links:**

npc https://www.wowhead.com/npc=48621/sullah
quest https://www.wowhead.com/quest=28482/sullahs-gift

**What is happening:**
- NPC missing for Uldum 
for Series quest line 

**What should happen:**
Npc should be spawned 

**Other Information:**
important start quests for Uldum 
![all missing](https://user-images.githubusercontent.com/39439201/91648030-da657c00-ea62-11ea-8720-a57d3b718951.jpg)

**Comment by mfranca0009** [comment]
Added Sullah and Harrison Jones.

**Comment by Echinaceax** [comment]
confirmed fixed in ptr 

![image](https://user-images.githubusercontent.com/39439201/106438426-c6d99980-6476-11eb-8565-0c4f1fc07290.png)
