### ISSUE TITLE
[NPC] Harrison Jones - 47158 / 49151 (missing) - Uldum

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4706]
**Links:**

Quest giver https://www.wowhead.com/npc=47158/harrison-jones
quest delivery https://www.wowhead.com/npc=49151/harrison-jones

**What is happening:**
- npc missing
for quest https://www.wowhead.com/quest=27748/fortune-and-glory

- npc missing 
for quest delivery https://www.wowhead.com/npc=49151/harrison-jones

**What should happen:**
npc should be in DB

**Comment by mfranca0009** [comment]
All set, added both Harrison Jones NPCs (47158 and 49151).
