### ISSUE TITLE
[NPC] Eye of Acherus

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Blackwing-Lair#471]
https://www.wowhead.com/quest=12641/death-comes-from-on-high
https://www.wowhead.com/npc=28511/eye-of-acherus#comments
https://www.wowhead.com/spell=51852/the-eye-of-acherus

When the Death Knight activates 'Eye of Acherus Control Mechanism' the eye should be launched to New Avalon across the starting map, instead of being launched it just sits in it's control mechanism with the player now having control over it, but it moves at a ridiculously slow rate far less than half of it's normal movement speed. To add to this, the spell giving the caster control over the eye(spell ID 51852) should be removed when the eye leaves the area, but it instead only matters if the caster leaves the area, meaning the eye can be flown out of the allowed zone. 
![wowscrnshot_011119_095528](https://user-images.githubusercontent.com/33989250/51050983-560d6f00-1587-11e9-8e30-cb22b6ff69d4.jpg)

**Comment by bluemonstrr** [comment]
Steps to reproduce; Simply make a new Death Knight and then use the eye while on the quest.

**Comment by bluemonstrr** [comment]
I believe the issue with the Eye not vanishing after leaving the area is due to the coding reading the player's position rather than the pets since the spell is cast on the player

**Comment by Dranah** [comment]
Issue with the NPC, the quest itself works fine.

**Comment by Dranah** [comment]
The ground speed is now correct.
NPC's flight speed must be adapted.
Not priority atm.

**Comment by Kitzunu** [comment]
This is core related to this spell https://www.wowhead.com/spell=51923/eye-of-acherus-flight-boost

**Comment by Dranah** [comment]
Reverted to both ground and flight speed being utter slow.
