### ISSUE TITLE
[Daily/Fishing] Level scaling issue (Horde/Ally)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4713]
**Links:**

https://www.youtube.com/watch?v=hsNDDBCTAG8

**What is happening:**
- Daily gold not scaling with lvl 
_im 85 and only getting 1s 25c_

![1s](https://user-images.githubusercontent.com/39439201/91917013-04b37580-ecbf-11ea-874a-f4ec8e5c6430.jpg)

**What should happen:**
should scale with lvl 
https://www.youtube.com/watch?v=hsNDDBCTAG8

![scalling](https://user-images.githubusercontent.com/39439201/91917299-cec2c100-ecbf-11ea-9e22-2403be5c9187.jpg)

**Extra info**
should scale to lvl like cooking 

![same as cooking](https://user-images.githubusercontent.com/39439201/91919256-93c38c00-ecc5-11ea-9ff5-637b41b3950f.jpg)

**Comment by mfranca0009** [comment]
I need the quest ID for the specified quest, submit a list of quests that are having this problem if it's more than one. @Echinaceax

**Comment by Echinaceax** [comment]
Orgimmar

- [x] https://www.wowhead.com/quest=26588/a-furious-catch
- [x] https://www.wowhead.com/quest=26572/a-golden-opportunity
- [x] https://www.wowhead.com/quest=26557/a-staggering-effort
- [x] https://www.wowhead.com/quest=26543/clammy-hands
- [x] https://www.wowhead.com/quest=26556/no-dumping-allowed

thunderbluff

- [x] https://www.wowhead.com/quest=29349/craving-crayfish
- [x] https://www.wowhead.com/quest=29345/pond-predators
- [x] https://www.wowhead.com/quest=29354/shiny-baubles
- [x] https://www.wowhead.com/quest=29348/the-race-to-restock
- [x] https://www.wowhead.com/quest=29346/the-rings-the-thing


Undercity

- [x] https://www.wowhead.com/quest=29317/fish-head
- [x] https://www.wowhead.com/quest=29319/tadpole-terror
- [x] https://www.wowhead.com/quest=29320/like-pike
- [x] https://www.wowhead.com/quest=29361/moat-monster
- [x] https://www.wowhead.com/quest=29322/time-for-slime


Sidenote: new proof shows that 85s should be (13g 23s) so Allies need editing from (9g 40s)

Stormwind

- [x] https://www.wowhead.com/quest=26488/big-gulp
- [x] https://www.wowhead.com/quest=26420/diggin-for-worms
- [x] https://www.wowhead.com/quest=26414/hitting-a-walleye
- [x] https://www.wowhead.com/quest=26442/rock-lobster
- [x] https://www.wowhead.com/quest=26536/thunder-falls

Darnassus

- [x] https://www.wowhead.com/quest=29325/a-slippery-snack
- [x] https://www.wowhead.com/quest=29359/an-old-favorite
- [x] https://www.wowhead.com/quest=29321/happy-as-a-clam-digger
- [x] https://www.wowhead.com/quest=29323/stocking-up
- [x] https://www.wowhead.com/quest=29324/the-sisters-pendant

Ironforge

- [x] https://www.wowhead.com/quest=29342/cold-water-fishing
- [x] https://www.wowhead.com/quest=29344/fish-fer-squrky
- [x] https://www.wowhead.com/quest=6609/i-got-nothin-left
- [x] https://www.wowhead.com/quest=29347/live-bait
- [x] https://www.wowhead.com/quest=29343/one-fer-the-ages
- [x] https://www.wowhead.com/quest=29350/the-gnomish-bait-o-matic


https://wowpedia.fandom.com/wiki/Fishing_quests#Cataclysm_fishing_dailies

![worth fishing](https://user-images.githubusercontent.com/39439201/113559026-f9337e80-9600-11eb-8bfe-ee2e009f0f0a.jpg)


Also 

- [x] the _Bag of Shiny Things_ https://cata-twinhead.twinstar.cz/?item=67414 has not all the drops 
https://wowpedia.fandom.com/wiki/Bag_of_Shiny_Things

![image](https://user-images.githubusercontent.com/39439201/113561412-d905be80-9604-11eb-9637-aa049e3dc134.png)

**Comment by mfranca0009** [comment]
Level 85s should now get the proper money associated with fishing dailies, also the Bag of Shiny Things now has the proper drop chances and loot within the bag when opened.
