### ISSUE TITLE
[NPC] Amani'shi Savage - Zul'Aman

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4714]
**Links:**

https://www.wowhead.com/npc=23889/amanishi-savage

**What is happening:**
- aggro range i think 

**What should happen:**
npc should run to play once the door opens

**Comment by mfranca0009** [comment]
Beginning of the instance, after opening the main gates, Amanishi Savages should run up from the bottom of the steps to assist in attacking the players who have entered the instance.

**UPDATE**
This is also needed by Hex Lord Malacrass's exit door, once it is open it should trigger the Amanishi savages there as well rushing towards the players.

**Comment by Echinaceax** [comment]
> Beginning of the instance, after opening the main gates, Amanishi Savages should run up from the bottom of the steps to assist in attacking the players who have entered the instance.
> 


they do run in eventually lol just a little slow to react 
![they do](https://user-images.githubusercontent.com/39439201/92313217-90801700-efc9-11ea-9bc6-6bcaf6ecdb56.jpg)

low dmg no abilities used

![low dmg no abilies used](https://user-images.githubusercontent.com/39439201/92313254-04222400-efca-11ea-9d84-19cc913846f4.jpg)

**Abilities missing**

- [ ] https://www.wowhead.com/spell=9080/hamstring
- [ ] https://www.wowhead.com/spell=12054/rend
- [ ] https://www.wowhead.com/spell=11971/sunder-armor

**Comment by mfranca0009** [comment]
Will fix abilities and the savages after hexlord exit, more testing shows that they do run up after one of the amanishi guardians is aggro'd.

**Comment by mfranca0009** [comment]
All fixed, savages by hexlord exit are now scripted so once the door opens they will have a 1 second delay before running towards the door.

They also cast Rend, Hamstring, and Sunder Armor. The timing seems okay, and they all get casted but it may not be perfect so, if need be, they can be adjusted later. Needs testing 👍

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 

- [x] The savages at the start are ok once the guardians start attacking 
- [x] The savages  at the bridge after boss now attack

![conf1](https://user-images.githubusercontent.com/39439201/93670956-620d3c00-fa9f-11ea-902b-d3a6dfa1e563.jpg)
