### ISSUE TITLE
[NPC] Amani Lynx - (Stealth missing) - Zul'Aman

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4716]
**Links:**

https://www.wowhead.com/npc=24043/amani-lynx

**What is happening:**
- missing stealth

**What should happen:**
should be stealth acording to video time stamp 7:04
https://www.youtube.com/watch?v=fzmR5JiNQmo

**Comment by mfranca0009** [comment]
Fixed 👍  Amani Lynx now have proper SmartAI attached with proper abilities being used. They go stealth when spawned in, after combat, or respawn. They will cast Feral Swipe in combat.

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 

- [x] stealth
- [x] Abilities
