### ISSUE TITLE
[Quest] Dig-Boss Dinwhisker - ID 27964 - Searing Gorge

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#472]
Quest - https://www.wowhead.com/quest=27964/dig-boss-dinwhisker

- Dig-Boss Dinwhisker is not showing up 
- Cant complete quest 

Pic of dude - https://www.wowhead.com/quest=27964/dig-boss-dinwhisker#screenshots:id=220933

**Comment by sarahkay88** [comment]
Also the same for ally killed around 15 of the required mobs and he was a no show.

**Comment by simonverse** [comment]
same

**Comment by Rushor** [comment]
https://i.imgur.com/1vkueJX.jpg

the creature will now spawn for 15 percent on kill of Dark Iron Excavators and Dark Iron Footmen. he will not spawn if Dig-Boss Dinwhisker is already spawned.
