### ISSUE TITLE
[Object] Halazzi (Entrance door) - Zul'Aman

### ISSUE THREAD

**Issue by mfranca0009** [WoWManiaUK/Blackwing-Lair#4720]
**What is happening:**

- Halazzi's entrance door is open at start of instance.

**What should happen:**

- Halazzi's entrance door should be closed and only open when previous boss is dead.

**Comment by mfranca0009** [comment]
Fixed, Halazzi's entrance door will open once previous boss is dead (Jan'alai). 👍

**Comment by Echinaceax** [comment]
This didnt open after killing Jan'alai @mfranca0009 

![entrance door](https://user-images.githubusercontent.com/39439201/92212494-52340c00-ee92-11ea-8872-0549f5f11566.jpg)

**Comment by Echinaceax** [comment]
fixed confirmed with Ally toon, going to check back on Horde toon also

**Comment by Echinaceax** [comment]
@mfranca0009 Horde char door is closed hmmmm
