### ISSUE TITLE
[NPC] Amani Elder Lynx - (Abilities missing) - Zul'Aman

### ISSUE THREAD

**Issue by mfranca0009** [WoWManiaUK/Blackwing-Lair#4721]
**Links:**
https://www.wowhead.com/npc=24530/amani-elder-lynx

**What is happening:**

Missing abilities used during combat using Smart Scripts.

**What should happen:**

Should use abilities from smart script during combat.

**Comment by Echinaceax** [comment]
confirmed fixed in PTR

- [x]  Abilities
