### ISSUE TITLE
[NPC] Amani Lynx Cub - (Abilities missing) - Zul'Aman

### ISSUE THREAD

**Issue by mfranca0009** [WoWManiaUK/Blackwing-Lair#4722]
**Links:**
https://www.wowhead.com/npc=24064/amani-lynx-cub

**What is happening:**

Missing abilities used during combat using Smart Scripts.

**What should happen:**

Should use abilities from smart script during combat.

**Comment by Echinaceax** [comment]
confirmed fixed in PTR

- [x]  stealth
- [x] Abilities
