### ISSUE TITLE
gurubashi arena quest bug

### ISSUE THREAD

**Issue by WiciadorWolf** [WoWManiaUK/Blackwing-Lair#4723]
**Links:**

https://www.wowhead.com/quest=26451/gurubashi-challenge-free-for-all-arena-combat

**What is happening:**
after killing summoned challanger quest doesnt complete
![WoWScrnShot_090620_084512](https://user-images.githubusercontent.com/70564657/92320049-c4d1f280-f01e-11ea-9b5d-8ea3d317c33d.jpg)

**Comment by Echinaceax** [comment]
im sure ive done this quest @WiciadorWolf 
will retest an update soon

**Comment by Echinaceax** [comment]
works fine for me @WiciadorWolf 

![words fine for me](https://user-images.githubusercontent.com/39439201/92323559-1176f700-f03a-11ea-8e2c-21a75cbd107c.jpg)

**Comment by WiciadorWolf** [comment]
i found that when my pet kill challanger quest doesnt complete when i
killed him myself quest complete

niedz., 6 wrz 2020 o 12:12 Echinaceax <notifications@github.com> napisał(a):

**Comment by Echinaceax** [comment]
ah yes @WiciadorWolf hunters cant be lazy anymore in CATA lol, hunter has to the the work too lol :)
