### ISSUE TITLE
[NPC] Argent Squire/Argent Gruntling (issue 2)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4727]
**Links:**
Horde http://cata.cavernoftime.com/item=45022
Ally http://cata.cavernoftime.com/item=44998

**What is happening:**
- when 2 players have their npcs out one players flag selection changes the other players flag also :)
- happens when you are close to each other

**What should happen:**
players should only have control of their own options for their own Argent Squire/Argent Gruntling and NOT each others 

**Other Information:**

![option flags](https://user-images.githubusercontent.com/39439201/92982426-5cf82d80-f49e-11ea-9e6e-5c7f54110057.jpg)

**Comment by mfranca0009** [comment]
Will look further into this issue shortly next time I have free to finish up the Argent Squire / Gruntling problems completely 👍

**Comment by mfranca0009** [comment]
Adjusted C++ script, needs testing in PTR 👍

**Comment by mfranca0009** [comment]
I've separated the scripts for Squire and Gruntling, there shouldn't be any interference between another player's Squire/Gruntling when changing flags now. Needs testing 👍 

**UPDATE**
Had to adjust the radius and implicit target to caster only in Spell Manager C++ as well after separating the C++ creature scripts.
