### ISSUE TITLE
 [Dirty Deeds] - quest dosent work

### ISSUE THREAD

**Issue by almoghr** [WoWManiaUK/Blackwing-Lair#4738]
**Links:**

from WoWHead or our Armory

**What is happening:**
i need to collect chunk of ores and the chunk of ores is uncollectable

**What should happen:**
the chunk of ores should be collectable and shiny but it is not
**Is it crashing the server?:**
no

**Other Information:**
the quest is marked as fixed but its aint

**Comment by Echinaceax** [comment]
Already reported @almoghr here #940
ive reopened the old report thanks
