### ISSUE TITLE
[Quest] Thorium Point: The Seat of the Brotherhood - ID 27965 - Searing Gorge

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#474]
Quest - https://www.wowhead.com/quest=27965/thorium-point-the-seat-of-the-brotherhood
Quest giver - https://www.wowhead.com/npc=47266/jack-rockleg

- Cant complete quest, Overseer oilfist is not there even though it shows on my map
Quest back to - https://www.wowhead.com/npc=14625/overseer-oilfist

![oilfist](https://user-images.githubusercontent.com/39439201/51053206-52a2d380-15d9-11e9-9178-287e4b6030da.jpg)

**Comment by Dranah** [comment]
Issue is the missing NPC reported elsewhere.
