### ISSUE TITLE
[NPC] Witch Doctor T'wansi (positioning) - Zul'Aman

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4743]
**Links:**
https://www.wowhead.com/npc=52925/witch-doctor-twansi

**What is happening:**
- Quest npc positioning

**What should happen:**
npc needs moving to position for quest back

**Comment by mfranca0009** [comment]
Initially not visible, becomes visible when Daakara is dead. Re-positioned by the stairs where Daakara stands. All set and needs testing 👍
