### ISSUE TITLE
[NPC] Siame-Quashi - Zul'Aman

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4744]
**Links:**

https://www.wowhead.com/npc=52938/siame-quashi

**What is happening:**

- Siame-Quashi need moving 

**What should happen:**
should only be the one that jumps on the platform at boss in this area

**Comment by mfranca0009** [comment]
C++ script added and will now jump up onto platform and walk towards the center once Daakara is dead. Needs testing 👍 

Will delete the others once I create an SQL file for the fix.
