### ISSUE TITLE
[Quest] Booty Bay's Interests - Bootybay / Zul'Gurub

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4745]
**Links:**
npc1 https://www.wowhead.com/npc=53151/overseer-blingbang
Npc2 https://www.wowhead.com/npc=2496/baron-revilgaz
Ally https://www.wowhead.com/quest=29154/booty-bays-interests
Horde https://www.wowhead.com/quest=29252/booty-bays-interests

**What is happening:**
- both Npcs offers both ally and horde quests 

**What should happen:**
- as horde i should only get horde quest

**Other Information:**
![quests for zul bootybay](https://user-images.githubusercontent.com/39439201/93689356-3190c680-face-11ea-9b7c-5e70252fe1ed.jpg)

**Comment by Echinaceax** [comment]
- [x] npc1 https://www.wowhead.com/npc=53151/overseer-blingbang (fixed)

- [ ] Npc2 https://www.wowhead.com/npc=2496/baron-revilgaz (not fixed)

![baron still 2 ](https://user-images.githubusercontent.com/39439201/107158547-34ac2680-698b-11eb-8909-b575cd00a835.jpg)

**Comment by mfranca0009** [comment]
Re-test.

Only 2 quests were listed, there are 4 quests available with this name (2 alliance / 2 horde).....

Should be fixed now. @Echinaceax

**Comment by Echinaceax** [comment]
much better thx @mfranca0009 👍 

![image](https://user-images.githubusercontent.com/39439201/107158787-a769d180-698c-11eb-8e3b-466d747b549f.png)
