### ISSUE TITLE
[Boss] Headless Horseman - 23682 - (Hallows end)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4747]
**Links:**
Hallows end https://www.tauri-veins.tk/hallows-end-2011

boss https://cata-twinhead.twinstar.cz/?npc=23682

**What is happening:**
- need checking via DB 
cant test by joining dungeon que from dev alone

**What should happen:**

- [x] should be 87 cata version 
- [x] should be 365 item

(Mounts)
_The Horseman's Reins is a mount that has a chance to drop once a day from the Headless Horseman, the boss of the event._

![4](https://user-images.githubusercontent.com/39439201/93716634-2b9ff180-fb71-11ea-8cea-90b0cb8dbdc7.jpg)

**Other Information:**
Going off cata release date 2010/2011

required for achv 

Horde https://cata-twinhead.twinstar.cz/?achievement=1657
Ally https://cata-twinhead.twinstar.cz/?achievement=1656

**Comment by Echinaceax** [comment]
note: ive reported this too as its the loot from the dung https://github.com/WoWManiaUK/Blackwing-Lair/issues/4783

**Comment by mfranca0009** [comment]
Adjusted loot table and made change to NPC level from 80 to 87 👍  Needs testing

**Comment by Echinaceax** [comment]
note: cant test until this is fixed as we cant start the event unless we temp spawn him to test @mfranca0009 
 https://github.com/WoWManiaUK/Blackwing-Lair/issues/4785

### Update:
I temp spawned him in brill

- [x] Lvl 87

![hh 87](https://user-images.githubusercontent.com/39439201/96709850-88bedb00-139b-11eb-8d0f-9f84077255e5.jpg)

- [x] kill achv

![achv hh](https://user-images.githubusercontent.com/39439201/96709886-95433380-139b-11eb-960e-7a54a8ae6310.jpg)

- [x] loot lvl (not checked) 
i couldnt attack him with spells, only the kill command (in PTR) and he disapeared so couldnt check loot of rings 

I added the Loot-filled pumpkin reward (ilvl 365)

![loot](https://user-images.githubusercontent.com/39439201/96712058-cec96e00-139e-11eb-9e30-c033fc681ae7.jpg)
![sword](https://user-images.githubusercontent.com/39439201/96712110-e143a780-139e-11eb-8073-adba22b2977c.jpg)
![head](https://user-images.githubusercontent.com/39439201/96712114-e274d480-139e-11eb-9dac-8dc6b6baa6a8.jpg)
