### ISSUE TITLE
[Quest/drop rates] Twilight Collars - ID 27982 - Searing Gorge

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#475]
Quest - https://www.wowhead.com/quest=27982/twilight-collars
Item - https://www.wowhead.com/item=62822/twilight-collar

- Not dropping 
- Unable to complete 

**Edited to completed but with some issues**
https://github.com/WoWManiaUK/Blackwing-Lair/issues/475#issuecomment-464921806

**Comment by sarahkay88** [comment]
same for ally checked both outside and inside the cave non of the mobs dropped the required items.

**Comment by Saintres** [comment]
there is only 1 npc [npc=47310] Minister Letherio that drop this item.
and to kill this guy 20 times?? to complete this quest.

**Comment by Echinaceax** [comment]
Nice testing Saintres
https://www.wowhead.com/npc=47310/minister-letherio - 39% drop rate (apparently)
![39](https://user-images.githubusercontent.com/39439201/52976814-40336b00-33cb-11e9-9430-720e2a960e81.jpg)

Can you confirm this is the only one that drops from?
do you need me to help retest all 20 times?

**Comment by Saintres** [comment]
Have killed him now 16 times and all dropped the item

**Comment by Echinaceax** [comment]
so is it only the % that needs tweaking?

**Comment by Saintres** [comment]
Ok i got all items now and there is 1 more npc that drop the item.
[npc=47309] Minister Kiyuubi.
Both npc's allso drop another item thats needed for another quest that you need to combine together,
these drops allso drop eatch time u kill the npc's

**Comment by Saintres** [comment]
either u improve the droprate to all other npc's too in the cave or u change the quest to 1 / 1 on 1 single kill on any minister.
Thats my sugestion.

**Comment by Echinaceax** [comment]
> I can now confirm that even [npc=47311] Minister Finister dropp the item.
> So all 3 Minister's dropp it and allso 1 other item that probably needed for another quest.
> You get 3 items thats needed to be combined to 1 item for that quest. Not 2 as i mentioned befor

confirmed,
i just came back to area on "Epic" to complete this quest.
i agree with Saintres the minister's are dropping the items

**Comment by Echinaceax** [comment]
Thanks to Saintres, I gathered more info regarding this org report

https://www.wowhead.com/item=62825/kiyuubis-spherule - 100% drop instead of 41%
https://www.wowhead.com/item=62823/letherios-spherule - 100% drop instead of 39%
https://www.wowhead.com/item=62824/finisters-spherule - 100% drop instead of 71%

So far 
https://www.wowhead.com/npc=5862/twilight-geomancer - 0% drop instead 79%
https://www.wowhead.com/npc=5860/twilight-dark-shaman - 0% drop instead 81%
https://www.wowhead.com/npc=5861/twilight-fire-guard - 0% drop instead 81%
https://www.wowhead.com/npc=8419/twilight-idolater -
