### ISSUE TITLE
[NPC] Animals no abilities - Zul'Aman

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4754]
**Links:**

- [x] Amani Bear - https://www.wowhead.com/npc=23584/amani-bear
- [x] Amani Lynx Cub https://www.wowhead.com/npc=24064/amani-lynx-cub
- [x] Amani Elder Lynx https://www.wowhead.com/npc=24530/amani-elder-lynx
- [x] Amani Crocolisk https://www.wowhead.com/npc=24047/amani-crocolisk
- [x] Tamed Amani Crocolisk https://www.wowhead.com/npc=24138/tamed-amani-crocolisk

What is happening:
none are using abilities

**What should happen:**
should use abilities

**Comment by mfranca0009** [comment]
Lynx Cub and Elder Lynx (#4721 and #4722) have been fixed. Rest need to be done still though.

**Comment by mfranca0009** [comment]
All set, fixed in PTR 👍 

Timing of abilities can be adjusted later down the road if they don't seem quite right. At this time, they seem reasonable.

**Comment by Echinaceax** [comment]
- [x]  Tamed Amani Crocolisk
![tamed crock](https://user-images.githubusercontent.com/39439201/99795741-97c8b280-2b2c-11eb-9d76-c092e5764f37.jpg)

- [x] Amani Crocolisk
![crock2](https://user-images.githubusercontent.com/39439201/99795989-0279ee00-2b2d-11eb-85e9-f6b0e1dad7c0.jpg)

- [ ] Amani Lynx Cub  (seems low)
![seems low](https://user-images.githubusercontent.com/39439201/99796344-9cda3180-2b2d-11eb-891f-263a70403d3c.jpg)

- [x] Amani Elder Lynx
![elder](https://user-images.githubusercontent.com/39439201/99796622-18d47980-2b2e-11eb-90b4-32af486ecc82.jpg)

- [x] Amani Bear
![bears](https://user-images.githubusercontent.com/39439201/99813124-96f14a00-2b47-11eb-8ecc-46626958b003.jpg)

**Comment by Echinaceax** [comment]
@mfranca0009 
seems gut rip isnt working for **Amani Lynx Cub**
says im affected by Gut Rip but no dmg shown for it 

all others are fixed tho

**Comment by mfranca0009** [comment]
Will take a look today 

UPDATE
‐-------------------------------‐

Gut Rip only reduces stamina by 5% from amani lynx cub, so if it is being applied then it just modifies the player's health and reduces it by 5%.

I don't think it would send combat info per the log, I would try checking your character window or unit frame health bar to see if max health is reduced by 5%.

**Comment by Echinaceax** [comment]
retested the **Amani Lynx Cub**
didnt really see the 5% hp drop

**Comment by mfranca0009** [comment]
Ok then, the spell must be broke and it's not doing anything but applying debuff without actual stat change.

Will need to be fixed.

**Comment by mfranca0009** [comment]
Gut Rip spell fixed 👍 

Normal health before gut rip: 
![image](https://user-images.githubusercontent.com/26092980/99863080-8acab400-2b6a-11eb-8609-0c5156c5ae47.png)

Modified health during gut rip (5 stacks / 20% stamina reduced): 
![image](https://user-images.githubusercontent.com/26092980/99863094-9ddd8400-2b6a-11eb-9945-ec592b0202a8.png)

Images are hard to see but here's my normal and modified health values:

Normal HP: 134501
Modified HP after 20% stamina reduced (5 stacks of Gut Rip): 111625

**Comment by Constant20** [comment]
confirmed in ptr
