### ISSUE TITLE
[NPC] Soaring Eagle - Zul'Aman

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4755]
**Links:**

https://www.wowhead.com/npc=24858/soaring-eagle

**What is happening:**
Eagles should be moving around not just hovering :)

**What should happen:**
- need movement

**Comment by mfranca0009** [comment]
Referencing this video again: https://www.youtube.com/watch?v=b3yeYGEgTgQ

I believe the soaring eagles ARE NOT suppose to be spawned initially, they should be summoned by Akil'zon by a spell which is also stated in the Dungeon Journal of the game.

They do however need to be fixed to allow actual flying, they are currently bugging out similar to the Darktail Bonepickers in Blasted Lands that I fixed for the quest `Curtail the Darktail`.

related to Akil'zon boss - #4717

**Comment by mfranca0009** [comment]
This issue is all set, fixed the eagles so they are actually in the air and are flying.

The remainder of their issues will be fixed in Akil'zon's boss script.

**Comment by Constant20** [comment]
confirmed in ptr
