### ISSUE TITLE
[NPC] Soaring Eagle - (issue 2) - Zul'Aman

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4756]
**Links:**

https://www.wowhead.com/npc=24858/soaring-eagle

**What is happening:**
- low dmg

**What should happen:**
should be more that 500 

**Other Information:**
![eagel dmg](https://user-images.githubusercontent.com/39439201/93800118-645acc00-fc40-11ea-9d4d-dfbfffd63ebc.jpg)

**Comment by mfranca0009** [comment]
Soaring Eagles should most likely have abilities which would damage the player more. This damage is only from their normal melee attack which is naturally probably low damage.

Related to Akil'zon boss - #4717

**Comment by mfranca0009** [comment]
You can close this issue, @Echinaceax.

I've linked their spell on Akil'zon's open issue, this will fix their low damage issue and the issue revolves around Akil'zon's boss script needing to be done. They're not suppose to be using melee combat anyways, they're only suppose to fly around and use Eagle Swoop spell to attack.

I tested the Eagle Swoop spell on Consta, it worked fine, dealing almost 14k damage each time I attacked him with it.
