### ISSUE TITLE
[NPC] Innkeeper Kyteran - (double dialog) - Darkshore

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4758]
**Links:**

https://www.wowhead.com/npc=43420/innkeeper-kyteran

**What is happening:**
- she has two innkeeper dialogs

**What should happen:**
she should have 1 Sales window and 1 innkeeper dialog

**Other Information:**

![inkeeper ally](https://user-images.githubusercontent.com/39439201/93850336-27c5b980-fcae-11ea-937e-f5f8e2c7ba11.jpg)

**Comment by mfranca0009** [comment]
This NPC does NOT sell anything, therefore she should only offer the hearthstone bind and not an option for viewing vendor items.

I'll delete the duplicate though of course 👍

**Comment by golosomie** [comment]
@mfranca0009 Confirmed fixed on your TR. Now directly offers Hearthstone bind when talking to her.

**Comment by mfranca0009** [comment]
I'll add the flag so it still displays gossip option instead of directly asking to set hearthstone bind, but either way fix confirmed 👍
