### ISSUE TITLE
[Quest] Prove Yer Allegiance / Scrapped Golems - ID 28225/28226 - interaction - Burning Steppes

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#476]
NPC - https://www.wowhead.com/npc=48033/stebben-oreknuckle

- He has 2 quests , but can only chose 1
- The other quest disappear

![stebben](https://user-images.githubusercontent.com/39439201/51058409-f9db3700-15e8-11e9-9d17-f69e5fcc9760.jpg)

**Comment by sarahkay88** [comment]
same for alliance I took the first quest and couldn't accept or complete the second

**Comment by Dranah** [comment]
IF issue is with quests, need IDs for quests. 
https://www.wowhead.com/quest=28225/prove-yer-allegiance
https://www.wowhead.com/quest=28226/scrapped-golems
