### ISSUE TITLE
[Quest] Hampering Their Escape - Borean Tundra

### ISSUE THREAD

**Issue by almoghr** [WoWManiaUK/Blackwing-Lair#4768]
**Links:**

https://www.wowhead.com/quest=11617/hampering-their-escape

**What is happening:**

i gather grenades from mobs and there is nothing to mark so i can throw at the platform

**What should happen:**
the platform should be marked somehow

**Is it crashing the server?:**
no

**Comment by HrafnValknutt** [comment]
It is working. Just need to be on the platforms.
