### ISSUE TITLE
[Quest]  All That Skitters ID 26310 Horde

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#4775]
**Links:**
quest
https://www.wowhead.com/quest=26310/all-that-skitters
video 
https://www.youtube.com/watch?v=5j1ZY7scHl4

**What is happening:**
u cant collect the spiders u can only attack them ;)

**What should happen:**
u shoud be able to collect the spiders
**Is it crashing the server?:**
no

**Comment by HrafnValknutt** [comment]
You can loot the spiders for quest item. :)

"Cant reproduce"
