### ISSUE TITLE
[Random Battleground] SoTA + AV + IoC

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4776]
### Rushor removed on mania 

needs removing here too 

All those 3 battlegrounds are removed from Random BG selection for now, since those bgs require way too many people and stay too long

note 
SoTa is still bugged https://github.com/WoWManiaUK/Blackwing-Lair/issues/896

**Comment by mfranca0009** [comment]
All set, all three BGs have been removed from Random Battleground rotation.
