### ISSUE TITLE
[profession] Herbalism 1-70

### ISSUE THREAD

**Issue by HrafnValknutt** [WoWManiaUK/Blackwing-Lair#4777]
**Link**
https://www.wow-professions.com/farming-guides
1-70 https://www.wow-professions.com/guides/vanilla-herbalism-leveling

 **Durotar**
- [x] Silverleaf
- [x] Peacebloom 
- [x] Earthroot

**Mulgore**
- [x] Silverleaf
- [x] Peacebloom 
- [x] Earthroot

**Tirisfal Glades**
- [x] Silverleaf
- [x] Peacebloom 
- [x] Earthroot
arthroot
 **Elwynn Forest**
- [x] Silverleaf
- [x] Peacebloom 
- [x] Earthroot

**Teldrassil**
- [x] Silverleaf
- [x] Peacebloom 
- [x] Earthroot
- [x] Mageroyal

**Dun Morogh**
- [x] Silverleaf
- [x] Peacebloom 
- [x] Earthroot

**Comment by HrafnValknutt** [comment]
Elwynn Forest: 
missing Earthroot nodes ID 2449

map 
https://www.wow-professions.com/images/herbalism_maps/elwynn-forest-herbalism-map.jpg

**Comment by Echinaceax** [comment]
@mfranca0009
with all herb guides it states the best zones etc...
eventually need all zones doing (maybe we can pull the low herb from Maina) ?

other reports here, i will close them and add them here 
[Profession] Duskwood - Herbalism #4699
[Profession] Arathi Highlands - Herbalism #4349
[Profession] Scarcity of herbalism nodes #4228

**Comment by mfranca0009** [comment]
All herbalism reports have been fixed in dev on these issues:
#4795 , #4796 , #4802 , #4813 

Should be all set 👍
