### ISSUE TITLE
[profession] Mining full zone report 

### ISSUE THREAD

**Issue by HrafnValknutt** [WoWManiaUK/Blackwing-Lair#4778]
**Link**
https://www.wow-professions.com/farming-guides

**Durotar**
- [x] Copper Ore

**Northern Barrens**
- [x] Copper Ore

**Mulgore**
- [x] Copper Ore

**Tirisfal Glades**
- [x] Copper Ore

**Stonetalon Mountains**
- [x] Copper Ore
- [x] Tin Ore

**Ashenvale**
- [x] Copper Ore
- [x] Tin Ore

**Silverpine Forest**
- [x] Copper Ore
- [x] Tin Ore

**Hillsbrad Foothills**
- [x] Tin Ore
- [x] Silver Ore

**Elwynn Forest**
- [x] Copper Ore

**Redridge Mountains**
- [x] Copper Ore
- [x] Tin Ore

**Dun Morogh**
- [x] Copper Ore

**Loch Modan**
- [x] Copper Ore
- [x] Tin Ore

**Teldrassil**
- [x] Copper Ore

**Darkshore**
- [x] Copper Ore
- [x] Tin Ore

**Azuremyst Isle**
- [x] Copper Ore

**Bloodmyst Isle**
- [x] Copper Ore

**Eversong Woods**
- [x] Copper Ore (Extremely Rare)

**Ghostlands**
- [x] Copper Ore (Extremely Rare)

**Comment by HrafnValknutt** [comment]
Bloodmyst Isle: missing Copper ID 1731 Tin ID 1732

Blood Elf starting zones (Eversong Woods and Ghostlands) have extremely low nodes on them.

**Comment by Echinaceax** [comment]
@mfranca0009 

Eversong Woods
Added Copper Vein ID 1731

Ghostlands
Added Copper Vein ID 1731

Ashenvale
Added Copper Vein ID 1731

Bloodmyst Isle 
Added Copper vein ID 1731
Added Tin vein ID 1732

**Comment by Echinaceax** [comment]
ok ready to go @mfranca0009 👍

**Comment by HrafnValknutt** [comment]
Fix in Dev confirmed.
