### ISSUE TITLE
[Item] Loot-Filled Pumpkin - Hallows end

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4783]
**Links:**

Cata version loot table https://cata-twinhead.twinstar.cz/?item=54516

Daily RDF 

![pumpkin reward](https://user-images.githubusercontent.com/39439201/96336940-463b8c80-1083-11eb-8f54-595fbfa71fc3.jpg)

**What is happening:**
- the loot lvl for gear is lvl 70
- ilvl is 115

**What should happen:**
- should be lvl 85 loot
- ilvl should be 365
- 24 justice points

**Other Information:**

lvl 70 

![lvl 70 gear](https://user-images.githubusercontent.com/39439201/96335554-c52bc780-1079-11eb-8cf2-66a4b7cb0515.jpg)

![70 sword](https://user-images.githubusercontent.com/39439201/96335581-fd330a80-1079-11eb-8c9b-0e1e57d5b946.jpg)

**Comment by Echinaceax** [comment]
note: ive reported this too as its the loot from the dung https://github.com/WoWManiaUK/Blackwing-Lair/issues/4783

**Comment by mfranca0009** [comment]
Adjusted loot to proper loot table 👍  needs testing

Added 24 justice points to the dungeon finder quest related to Headless Horseman holiday dungeon.
