### ISSUE TITLE
[NPC] Jacob Maniac (Profession Booster) - Mall

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4787]
**What is happening:**
- Npc is missing the confirmation funtion 

**What should happen:**
professions should have a confirmation funtion

"Are you sure you want ....blah blah"

**instead what happens is** 

1. Click on the profession you want and blam instant learn with no confirmation message at all 

![click and bam](https://user-images.githubusercontent.com/39439201/96363381-46479500-1134-11eb-810a-f26090fefc60.jpg)

**reason its important is** players can missclick for whatever reason and they have no way back,
 they are stuck with a profession they didnt want 

its happened to me personally, i just forget to report it

**Comment by mfranca0009** [comment]
Fixed in custom script, added a confirmation window, and also corrected the spelling of "Profession" in the notification to player. 👍
