### ISSUE TITLE
[NPC] Hegrid Blazewing - Deepholm

### ISSUE THREAD

**Issue by jgilbert201** [WoWManiaUK/Blackwing-Lair#4791]
Hegrid Blazewing is supposed to be a general goods vendor in deepholme @65,81.

You can only speak to her, not browse goods.

**Comment by Echinaceax** [comment]
NPC - https://www.wowhead.com/npc=45361/hegrid-blazewing

**Comment by mfranca0009** [comment]
Cavern of Time doesn't have information on this NPC selling items.

Using Twinstar data instead of WoWhead.

**Comment by mfranca0009** [comment]
All set, vendor is accessible and will also give an option to locate closest repair NPC.

Low priority issue, she isn't carrying a barrel as she should be. The spell is on her (hence why she is holding her hand in the air), but the spell doesn't display the barrel on her for some reason; won't fix for now.

**Comment by golosomie** [comment]
@mfranca0009 Confirmed fixed on your TR.
