### ISSUE TITLE
[Dungeon] Akil'zon (hc) - (Horde) - Zul'Aman 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4792]
**What is happening:**
done 2 runs on horde and seems to be a few issues 

- cant loot boss 
- cant free captives 

**What should happen:**
should work same as ally fix 

**side note**: we had 4 horde guildies and 1 ally in group

**Comment by mfranca0009** [comment]
Tested on live with Echi and Zinius, captives work as long as the timer doesn't run out and they despawn (get sacrificed). 

Akil'zon's loot functions, but will need to double check because he only dropped gold with no gear.
