### ISSUE TITLE
[profession] Herbalism full zone report

### ISSUE THREAD

**Issue by HrafnValknutt** [WoWManiaUK/Blackwing-Lair#4795]
**Link**
https://www.wow-professions.com/farming-guides
https://wowwiki.fandom.com/wiki/Herbs_by_area

_**Eastern Kingdoms**_

**Western Plaguelands**

- [x] Stranglekelp
- [x] Kingsblood
- [x] Liferoot
- [x] Fadeleaf
- [x] Khadgar's Whisker
- [x] Arthas' Tears

**Eastern Plaguelands**

- [x] Liferoot
- [x] Khadgar's Whisker
- [x] Arthas' Tears
- [x] Sungrass
- [x] Black Lotus (needs a 60-70 minute respawn timer) 

**Hinterlands**

- [x] Bruiseweed
- [x] Stranglekelp
- [x] Wild Steelbloom
- [x] Kingsblood
- [x] Liferoot
- [x] Fadeleaf
- [x] Goldthorn
- [x] Khadgar's Whisker
- [x] Blindweed

**Arathi Highlands**

- [x] Bruiseweed
- [x] Stranglekelp
- [x] Grave Moss
- [x] Wild Steelbloom
- [x] Kingsblood
- [x] Liferoot
- [x] Fadeleaf
- [x] Goldthorn
- [x] Khadgar's Whisker

**Wetlands**

- [x] Mageroyal
- [x] Briarthorn
- [x] Bruiseweed
- [x] Stranglekelp
- [x] Grave Moss
- [x] Wild Steelbloom
- [x] Kingsblood
- [x] Liferoot

**Twilight Highlands**

- [x] Cinderbloom
- [x] Twilight Jasmine

**Badlands**

- [x] Dragon's Teeth
- [x] Firebloom
- [x] Sungrass
- [x] Golden Sansam

**Searing Gorge**

- [x] Firebloom
- [x] Sungrass

**Burning Steppes**

- [x] Firebloom
- [x] Sungrass
- [x] Dreamfoil

**Swamp of Sorrows**

- [x] Stranglekelp
- [x] Golden Sansam
- [x] Sorrowmoss

**Stranglethorn Vale**

- [x] Bruiseweed
- [x] Stranglekelp
- [x] Wild Steelbloom
- [x] Kingsblood
- [x] Liferoot
- [x] Fadeleaf
- [x] Goldthorn
- [x] Khadgar's Whisker

**Comment by Echinaceax** [comment]
**Fixed in dev**  @mfranca0009 

**Western Plaguelands**
Added Arthas' Tears ID 142141

**Eastern Plaguelands**
Added Arthas' Tears ID 142141
Added Black Lotus ID 176589

**Hinterlands**
Added Khadgar's Whisker ID 2043

**Wetlands**
Added Briarthorn ID 1621
Added Bruiseweed ID 1622
Added Grave Moss ID 1628
Added Wild Steelbloom ID 1623

**Comment by HrafnValknutt** [comment]
Fix in Dev confirmed.

**Comment by mfranca0009** [comment]
@HrafnValknutt Have not put together SQL file for it yet, so another test after I do this will need to be completed.

**Comment by HrafnValknutt** [comment]
Fix in Dev double confirmed. :)

**Comment by Echinaceax** [comment]
update

player states that Goldthorn object=2046 is low spawns in Hinterlands

https://classic.wowhead.com/object=2046/goldthorn
