### ISSUE TITLE
[Talent] Fingers of Frost

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Blackwing-Lair#48]
**How it should work:**
> **Description:** 
>Gives your offensive Chill effects a $s1% chance to grant you the Fingers of Frost effect, which causes your next Ice Lance or Deep Freeze spell to act as if your target were frozen and increases Ice Lance damage by 25%.  Fingers of Frost can accumulate up to $44544s1 charges and lasts $44544d.

> **Patch note:**
> - Wrath of the Lich King Patch 3.3.0 (2009-12-08): This talent now triggers immediately on casting a spell rather than being delayed until the spell strikes the target. 

**How it works:**

The Talent is not triggering on cast (which should),  instead it delays until the spell strikes the target.

**Comment by Keader** [comment]
Fixed. Will be ready to test in next restart.

**Comment by TheManiax** [comment]
The reported issue is fixed
But there is an additional issue with it I just figured out
The buff  [Fingers of Frost] ID:44544 , is not fading on use
It's like a general issue on many spells
Maybe you can fix them all with changing one thing in main codes
