### ISSUE TITLE
[Spell] Holy Smite - ID 15498

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Blackwing-Lair#480]
https://www.wowhead.com/npc=28608/scarlet-medic#abilities
https://www.wowhead.com/spell=15498/holy-smite
![medic](https://user-images.githubusercontent.com/33989250/51063978-3a6b8e00-15b2-11e9-88c3-db5a60c3cd86.png)
As sourced on wowhead: School Damage (Holy) Value: 372
Currently it's hitting for more than 2 times the damage it should, making it possible for the medic to nearly 2 shot a leveling Death Knight.

![medic2](https://user-images.githubusercontent.com/33989250/51064034-8e767280-15b2-11e9-8d24-229eb0b27aaa.png)
Using Mania's Redemption realm for reference as well shows that the spell shouldn't be hitting this hard

**Comment by Keader** [comment]
lol, it dont happens in wotlk o.o
i will check it today.

**Comment by bluemonstrr** [comment]
The issue happened in the cata realm, I just used the wotlk realm for a reference on what it should be since wowhead no longer shows exact damage for most spells

**Comment by Dranah** [comment]
Legacy label means the npc/quest exist on wotlk in same way, so it can be copied over from Redemption.

**Comment by Dranah** [comment]
Damage is now correct.
