### ISSUE TITLE
[NPC] Agatian Fallanos <Shard Trader>

### ISSUE THREAD

**Issue by jgilbert201** [WoWManiaUK/Blackwing-Lair#4806]
**Links:**
https://www.wowhead.com/npc=50146/agatian-fallanos

**What is happening:**
NPC Location - 76.6, 49.4
NPC should sell the following recipe - Formula: Runed Elementium Rod - https://cata-twinhead.twinstar.cz/?npc=50146
The NPC does not sell it. Also the NPC's position, as well as all the NPC's positions in this build are wrong. Some are halfway up the wall....

**What should happen:**

NPC should sell recipe

**Is it crashing the server?:**
No
**Other Information:**

**Comment by Echinaceax** [comment]
thanks @flubbacrud 
have you checked the vendor in Orgimmar ?
http://cata.cavernoftime.com/npc=3346

i just checked Stormwind for ally 

![ally does](https://user-images.githubusercontent.com/39439201/97190004-88607e80-17a5-11eb-8bf5-153d49ecaace.jpg)

**Comment by jgilbert201** [comment]
Confirmed Orgrimmar NPC has this item.

**Comment by mfranca0009** [comment]
All set, item has been added and position of NPC has been corrected.
