### ISSUE TITLE
[Spell] Blood Frenzy

### ISSUE THREAD

**Issue by jgilbert201** [WoWManiaUK/Blackwing-Lair#4807]
**Links:**

https://wowwiki.fandom.com/wiki/Blood_Frenzy

**What is happening:**
Blood Frenzy is an arms talent for a warrior. Once this procs on a player, it never gets removed.

**What should happen:**

If the Arms warrior dies or the receiving target dies, the spell should be removed from the receiving target. I'd say it probably removes when the victim dies, but i'm yet to die, however when the warrior died in Tol Barad, It was still active and is still active on my character over 2 hours laters.

**Is it crashing the server?:**
no
**Other Information:**

Confirmed this has happened on multiple targets too.
<img width="1815" alt="Blood_Frenzy" src="https://user-images.githubusercontent.com/273787/97182357-58f54600-1794-11eb-9a1e-b32fac822ebf.png">

**Comment by mfranca0009** [comment]
Should have a 1 minute duration for both ranks; looking into this. [NOT CORRECT, was looking at it wrong.]

![image](https://user-images.githubusercontent.com/26092980/107259735-5e0c9700-6a0b-11eb-8e1e-d0bd00440b14.png)


**UPDATE**
What I said above is false, NPCs have auras removed (including Blood Frenzy) when leaving combat if player dies. Will need to incorporate this with player as well for PvP.

**Comment by mfranca0009** [comment]
- [ ] Remove aura when target dies
- [ ] Remove aura when target leaves a battleground
- [ ] Remove aura from target if player dies 
- [ ] Remove aura when target leaves arena [Should be handled same way as leaving a battleground]

**Comment by golosomie** [comment]
- [ ] Remove aura when target leaves combat
- [ ] Remove aura when player leaves combat

**Comment by mfranca0009** [comment]
Trinitycore issue back in 2012: https://github.com/TrinityCore/TrinityCore/issues/299

- [x] Remove Blood Frenzy when there isn't any bleed effects left on the target.

This should control it properly for players and creatures 👍

**Comment by mfranca0009** [comment]
All set 👍
