### ISSUE TITLE
[NPC] Scarlet Ghoul - Plaguelands: The Scarlet Enclave (low HP) 

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Blackwing-Lair#481]
https://www.wowhead.com/quest=12698/the-gift-that-keeps-on-giving
https://www.wowhead.com/item=39253/gift-of-the-harvester
https://www.wowhead.com/npc=28845/scarlet-ghoul#screenshots

Currently the Scarlet Ghoul's that spawn only have 2 health, meaning they will die to the first hostile mob you come across, repeatable by trying the quest 
![ghoul](https://user-images.githubusercontent.com/33989250/51069968-28a7dc00-15ee-11e9-9d7d-f2993336affe.jpg)

They should have 1200 + health based off what level they spawn at, since they level with the death knight

![ghoul2](https://user-images.githubusercontent.com/33989250/51070038-80931280-15ef-11e9-9c56-6009af7acee0.png)

**Comment by Dranah** [comment]
This is sorta a NPC bug. The quest itself works fine.

**Comment by Rushor** [comment]
hp increased now

![I](https://i.imgur.com/DDuYYSB.jpg)
