### ISSUE TITLE
[Quest] Proof of Allegiance - Shadowmoon Valley

### ISSUE THREAD

**Issue by Azkard** [WoWManiaUK/Blackwing-Lair#4814]
**Links:**
https://www.wowhead.com/quest=10622/proof-of-allegiance

**What is happening:**
[Zandras](https://www.wowhead.com/npc=21827/zandras) is missing. The objective to kill isn't there.

**What should happen:**
[Zandras](https://www.wowhead.com/npc=21827/zandras) must be there.

**Is it crashing the server?:**
No

**Other Information:**
1-I've Spammed "/tar Zandras" command around the zone, just to be sure.
2-After a considerable amount of time, I went again to the quest zone to check up on him, maybe he was killed for someone else before my 1st visit. but sadly, he was not there, still missing.

**Comment by Echinaceax** [comment]
confirmed missing

**Comment by mfranca0009** [comment]
For some reason, he had a condition to only show up during 'Arena Season 4' event; should be all set now 👍

**Comment by Echinaceax** [comment]
confirmed fixed in ptr 

![image](https://user-images.githubusercontent.com/39439201/106439059-8c243100-6477-11eb-961b-e9f24aa0b5f9.png)
