### ISSUE TITLE
[track the tracker] - quest bugged

### ISSUE THREAD

**Issue by almoghr** [WoWManiaUK/Blackwing-Lair#4815]
**Links:**

from WoWHead or our Armory

**What is happening:**
im getting the quest just as suposed to be, the npc to end the quest is nowhere

**What should happen:**
i should go to the npc and finish the quest, but the npc is not anywhere
**Is it crashing the server?:**
no
**Other Information:**

**Comment by Echinaceax** [comment]
you reported npc here #4816
thats good enough, so i will close this one
