### ISSUE TITLE
Grent Direhamme ID 52346 is missing

### ISSUE THREAD

**Issue by almoghr** [WoWManiaUK/Blackwing-Lair#4816]
**Links:**

from WoWHead or our Armory

**What is happening:**

no npc

**What should happen:**

**Is it crashing the server?:**
no
**Other Information:**

**Comment by Echinaceax** [comment]
for quest delivery https://www.wowhead.com/quest=29226/track-the-tracker

npc https://www.wowhead.com/npc=52346/grent-direhammer

After player got their quest completed by the GM  https://www.wowhead.com/quest=29226/track-the-tracker and picked up https://www.wowhead.com/quest=29227/the-hunters-revenge they are not given the body of Grent Direhamme for it to complete

NPC needs fixing first then i will retest for https://www.wowhead.com/quest=29227/the-hunters-revenge

video https://www.youtube.com/watch?v=TcfvYnYmruM

**Comment by Echinaceax** [comment]
@mfranca0009 
Added npc ID 52346 (in PTR) 
just need SQL please 😄

**Comment by mfranca0009** [comment]
All set, needs testing in PTR 👍 @Echinaceax

**Comment by HrafnValknutt** [comment]
Fix in Dev confirmed.
