### ISSUE TITLE
[Quest] Follow That Cat (missing quest start object) - Northern Stranglethorn

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4819]
**Links:**
object https://www.wowhead.com/object=208365/recently-disturbed-dirt-mound
quest https://www.wowhead.com/quest=29229/follow-that-cat

**What is happening:**
- missing quest from Recently Disturbed Dirt Mound

**What should happen:**
quest is given by the Recently Disturbed Dirt Mound
https://www.youtube.com/watch?v=7c0vDvC7Gks

**Other Information:**
this could be the reason the other questline is bugged #4818

**Comment by Echinaceax** [comment]
@mfranca0009 
Added **Recently Disturbed Dirt Mound** object
Needs SQL

**Comment by mfranca0009** [comment]
All set, needs testing in PTR 👍 @Echinaceax

**Comment by HrafnValknutt** [comment]
Fix in Dev confirmed.
