### ISSUE TITLE
[Talent] Lambs to the Slaughter - ID 84588

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Blackwing-Lair#482]
![lamb](https://user-images.githubusercontent.com/33989250/51070230-db7a3900-15f2-11e9-8dea-46b4d7eba940.png)
![slaughter](https://user-images.githubusercontent.com/33989250/51070249-15e3d600-15f3-11e9-9659-2f6c13a42418.png)

Currently using this talent set up
![arms](https://user-images.githubusercontent.com/33989250/51070266-4166c080-15f3-11e9-8aa7-19dd97683706.png)

When Slam(Spell ID 1464) or Overpower(Spell ID 7384) is used with this affect active, the bonus %dmg increase works fine, but Slaughter adds a new stack rather than consuming it.

How it should work; When the affect of Slaughter is used on Slam/Overpower/Execute, it's stack should then be depleted.

How it currently works; The stacks on Slaughter are continuously added to the affect, instead of consumed by the spells it states, while the %dmg increase is still happening

This can be reproduced by; Using the talents above, hitting an enemy with mortal strike, then hard casting slam. The Slaughter affect will at this point be at 2 rather than dropped off the caster

**Comment by bluemonstrr** [comment]
Swapping between Berserker stance and Battle stand also adds stacks each time the stance is swapped, but doesn't add anything when done with defensive stance

**Comment by Keader** [comment]
I cant find any evidence that mortal strike, overpower, etc should remove stacks/aura.
But just overpower need proc/stack it. This part is fixed.
If you find any evidence that those spells needs remove, tell me.

**Comment by Dranah** [comment]
This effect has stacks, not charges. The stacks don't need to be consumed by anything, they can just expire if you pause DPS due to a transition phase or something.
It is no longer proc'd by other spells, only MS. Other spells just benefit now.

**Comment by cocojumbo1** [comment]
hello...it shouldnt be consumed by any means its a buff thats refreshed by mortal strike...the issue is the bonus of 30% isnt added for example on execute and sometimes on other spells aswell

**Comment by cocojumbo1** [comment]
i think execute doesnt benefit from the talent
