### ISSUE TITLE
[Quest] Bloodlord Mandokir - Northern Stranglethorn

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4827]
**Links:**

quest https://www.wowhead.com/quest=26334/bloodlord-mandokir
npc https://www.wowhead.com/npc=42790/bloodlord-mandokir

**What is happening:**
After finishing https://github.com/WoWManiaUK/Blackwing-Lair/issues/4826 i cant pick up next quest coz hes not here

**What should happen:**
Npc should be here for pick up quest

**Comment by Echinaceax** [comment]
Added npc on ptr @mfranca0009 
just need SQL

**Comment by mfranca0009** [comment]
All set, needs testing in PTR 👍  @Echinaceax

**Comment by HrafnValknutt** [comment]
Fix in Dev confirmed.
