### ISSUE TITLE
[Quest] The Warden's Pawn / The Sentinel's Pawn - ID 27796/27797 - Interaction - Badlands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#483]
NPC - https://www.wowhead.com/npc=46760
1) Quest - https://www.wowhead.com/quest=27796/the-wardens-pawn
2) Quest - https://www.wowhead.com/quest=27797 - the sentinels pawn
Each quest prevents you from collecting then next
I took the first quest which is completable but then I am unable to take and complete the second quest.
However the follow on quest:
https://www.wowhead.com/quest=27709 the sentinels game can be picked up

**Comment by Echinaceax** [comment]
**Same for horde**
