### ISSUE TITLE
[Quest] Storming the Steamvault - Zangarmarsh

### ISSUE THREAD

**Issue by almoghr** [WoWManiaUK/Blackwing-Lair#4834]
**Links:**

from WoWHead or our Armory

**What is happening:**
there are no npcs for quests in the beginning of the dungeon

**What should happen:**
npc should be there
**Is it crashing the server?:**
no
**Other Information:**

**Comment by Echinaceax** [comment]
quest https://www.wowhead.com/quest=29616/storming-the-steamvault
npc https://www.wowhead.com/npc=54848/watcher-jhang

**Comment by Echinaceax** [comment]
@mfranca0009 (need SQL) 

 Added on PTR 

- [x] Watcher Jhang
entry 54848
GUID  160

- [x] Naturalist Bite
entry 54849
GUID 162

- [x] Windcaller Claw
entry 54851
GUID 168

![npc added](https://user-images.githubusercontent.com/39439201/97787960-a703b280-1bb5-11eb-914c-81f053a0d42e.jpg)
![Naturalist bite](https://user-images.githubusercontent.com/39439201/97788266-095db280-1bb8-11eb-8805-e91737d44099.jpg)
![windcaller claw3](https://user-images.githubusercontent.com/39439201/97788363-a587b980-1bb8-11eb-8c47-946e6eab4345.jpg)

**Comment by mfranca0009** [comment]
All set, needs testing in PTR 👍 @Echinaceax

**Comment by Echinaceax** [comment]
confirmed fixed in ptr

**Comment by Echinaceax** [comment]
more info ...

need moonkin and bear skins

![might be diff](https://user-images.githubusercontent.com/39439201/97922093-3a76e800-1d5c-11eb-8382-1246355707c1.jpg)
