### ISSUE TITLE
[Dungeon/quests/npc] Slave pens

### ISSUE THREAD

**Issue by almoghr** [WoWManiaUK/Blackwing-Lair#4835]
**Links:**

from WoWHead or our Armory

**What is happening:**

there are no npcs in the beginning of the dungeon

**What should happen:**
npcs should be there
**Is it crashing the server?:**
no
**Other Information:**

**Comment by Echinaceax** [comment]
more info needed @almoghr 

quest name ...
npc missing ...

**Comment by almoghr** [comment]
all of the npcs there are missing.. not one or any quest.. 
u cant see any npc there. no quest is available to even take.

**Comment by Echinaceax** [comment]
this doesnt help me though @almoghr 
need to know Quest names and NPCs names 

you havent provided any links to any quest or npc names

### UPDATED INFO 

This is how we need your reports to be @almoghr, if your doing loremaster, you will know what quests are needed

quest https://www.wowhead.com/quest=29564/a-brother-betrayed
start npc https://www.wowhead.com/npc=54668/nahuud
end https://www.wowhead.com/npc=54668/nahuud

quest https://www.wowhead.com/quest=29566/checking-up
start npc https://www.wowhead.com/npc=17841/ysiel-windsinger
End https://www.wowhead.com/npc=54667/watcher-jhang

quest https://www.wowhead.com/quest=29563/lost-in-action
start npc https://www.wowhead.com/npc=54667/watcher-jhang
end quest https://www.wowhead.com/npc=54667/watcher-jhang

quest https://www.wowhead.com/quest=29565/the-heart-of-the-matter
start npc https://www.wowhead.com/npc=54667/watcher-jhang
end npc https://www.wowhead.com/npc=54667/watcher-jhang

**Comment by Echinaceax** [comment]
@mfranca0009 Added npcs (PTR)

Entry 54668
GUID 216

Entry 54667
GUID 218

![added](https://user-images.githubusercontent.com/39439201/97872901-15ac5180-1d17-11eb-834a-0da65b23fd95.jpg)

**Comment by mfranca0009** [comment]
All set, needs testing in PTR 👍 @Echinaceax

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 

![comp2](https://user-images.githubusercontent.com/39439201/97966699-7d68a800-1dbc-11eb-91ef-e5da08a6b21f.jpg)
