### ISSUE TITLE
[Quest] The Warden's & Sentinel's Game - ID 27693/27709 - Badlands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#484]
Quest - https://www.wowhead.com/quest=27693/the-wardens-game
Quest - https://www.wowhead.com/quest=27709 - sentinels game
NPC -https://www.wowhead.com/object=206335
Unable to complete due to missing statues
This also apply to the sentinel's Games 
![world of warcraft 12_01_2019 11_15_10](https://user-images.githubusercontent.com/42302580/51072630-c71e5680-165b-11e9-862c-902b899d54dc.png)

**Comment by Echinaceax** [comment]
**For Horde**

- I chose the Sentinel one and that has same problems 
#448
#447

**Comment by sarahkay88** [comment]
Ho yours never came up when I check.. you covered everything I will close this.

**Comment by sarahkay88** [comment]
just add a not to yours saying same for the wardens quest
