### ISSUE TITLE
[Quest] The Zandalari Menace 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4841]
**Links:**
https://wow.gamepedia.com/The_Zandalari_Menace
https://www.wowhead.com/object=206109/warchiefs-command-board

**What is happening:**
- quest missing from boards

**What should happen:**
should be given at the hero/warchiefs board

**Comment by mfranca0009** [comment]
All set, needs testing in PTR 👍 @Echinaceax
