### ISSUE TITLE
[NPC] Fen Ray - (issue2) - The Underbog

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4842]
**Links:**

https://www.wowhead.com/npc=17731/fen-ray

**What is happening:**
- still sliding on the floor 
https://gyazo.com/19dbf2e65331a8ed3dc552ef11d441eb

**What should happen:**
should be up not lay on the floor 😄 

**extra info**
was partly fixed here https://github.com/WoWManiaUK/Blackwing-Lair/issues/4367

**Comment by mfranca0009** [comment]
All set, needs testing in PTR 👍 @Echinaceax
