### ISSUE TITLE
[Quest] Lost in Action - Slave Pens

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4844]
**Links:**

https://www.wowhead.com/quest=29563/lost-in-action

**What is happening:**
- https://www.wowhead.com/npc=17893/naturalist-bite (not completing quest)
- https://www.wowhead.com/npc=17890/weeder-greenthumb (wasnt spawned) 

**What should happen:**
naturalist-bite  should have a dialog at 5:09 https://www.youtube.com/watch?v=OFMg6_E16OA

**Comment by Echinaceax** [comment]
@mfranca0009 I added NPC

Entry 17890
GUID 220

noticed that the mobs could attack him though, even though his display is "dead" needs checking 

- [ ] still need dialog on https://www.wowhead.com/npc=17893/naturalist-bite

**Comment by mfranca0009** [comment]
@Echinaceax Weeder greenthumb was spawned, but I think since he's attackable when dead he was despawning super quick.

There were two of the same NPCs spawned when I teleported to that entry. They die in about 3 seconds and they despawn in about 5 seconds.

**Comment by mfranca0009** [comment]
Got rid of duplicate, fixed issues related to weeder greenthumb dying by mobs within dungeon, and fixed gossip option problem with naturalist bite 👍  needs testing in PTR @Echinaceax
