### ISSUE TITLE
[Profession] Enchanting player items

### ISSUE THREAD

**Issue by jgilbert201** [WoWManiaUK/Blackwing-Lair#4845]
**Links:**

**What is happening:**

When trying to enchant another players soul bound items, the trade window is being cancelled when the enchant completes

**What should happen:**

It should enchant the item then the trade can be completed

**Is it crashing the server?:**

That's a negatron ghost rider, it is not crashing the server

**Other Information:**

Workaround is to enchant a vellum and trade

**Comment by Echinaceax** [comment]
reported already https://github.com/WoWManiaUK/Blackwing-Lair/issues/4614 https://github.com/WoWManiaUK/Blackwing-Lair/issues/1530
but thx 😄 

yes we knew the workaround too just forgot to edit old report
