### ISSUE TITLE
[Quest] Exploring Gnomeregan - Gnomeregan

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4849]
**Links:**

quest https://www.wowhead.com/quest=26944/exploring-gnomeregan
npc https://www.wowhead.com/npc=44556/murd-doc

**What is happening:**
- npc missing

**What should happen:**
_Speak to Murd Doc._

**Comment by mfranca0009** [comment]
Spawned Murd Doc and his Mecha-Marines.

Murd Doc should be riding a swift green mechanostrider, but for some reason when I tried adding this like any other NPC using a riding/flying mount; it didn't seem to work as it normally does. For now, leaving it as is.

**Comment by Echinaceax** [comment]
confirmed fixed in ptr 

![image](https://user-images.githubusercontent.com/39439201/106439364-e45b3300-6477-11eb-9355-261be8a900af.png)
