### ISSUE TITLE
[Dungeon] No Justice points - Zul'Aman

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4850]
**What is happening:**
- No justice points given from any bosses

**What should happen:**
Just give Justice point on boss kills

**Comment by mfranca0009** [comment]
A list of justice point amounts based on the dungeon difficulty, daily dungeon, boss kills, etc.

https://www.wowhead.com/news=170048/cataclysm-justice-valor-point-drop-quantities

**Comment by mfranca0009** [comment]
Per the evidence above, each heroic Cataclysm dungeon boss should give out 75 Justice Points on kill.

Each Zul'Aman boss should now give out 75 Justice Points after being killed to each group member 👍

**Comment by Echinaceax** [comment]
confirmed fixed in ptr 

![jp](https://user-images.githubusercontent.com/39439201/99795339-e75aae80-2b2b-11eb-876e-298fa7a6553b.jpg)
