### ISSUE TITLE
[Custom] Shattrath Port at the Mall

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4853]
**Suggestion approved for Shattrath portal in the Mall** 

Horde https://wotlk-twinhead.twinstar.cz/?object=191014
Ally https://wotlk-twinhead.twinstar.cz/?object=191013

**What should happen:**
_Shattrath portal to be placed in the mall_

**Comment by Echinaceax** [comment]
@mfranca0009 
Added Shattrath portals Horde/Ally to the mall 

**note**:  shattrath needs the banners behind tho, a generic banner like Mania 
cant find a generic one

**Added:** lamposts for now until we can find a generic banner @mfranca0009

**Comment by Echinaceax** [comment]
this one fixed too @mfranca0009 ?

i add label

**Comment by mfranca0009** [comment]
Should have commented, but yes all set and SQL was created / submitted 👍

**Comment by mfranca0009** [comment]
Fix on live server, all set 👍
