### ISSUE TITLE
[NPC] Jacob Maniac

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4855]
**Suggestion approved** 

**What should happen:**
take Lockpicking out of the MP profession boost options from Jacob Maniac? 

_You don't even need to level Lockpicking in Cataclysm so I'm assuming the NPC was just imported from the mania server_

**Comment by mfranca0009** [comment]
This should be all set in PTR, needs testing 👍

**Comment by Echinaceax** [comment]
sorry no not fixed @mfranca0009 😢 

![not fixxxx](https://user-images.githubusercontent.com/39439201/99308133-c8bc9500-2857-11eb-9383-3d4909210660.jpg)

**Comment by mfranca0009** [comment]
It probably didn't go through cause the server needs to be rebuilt. It was done through a C++ script. @Echinaceax

**Comment by Echinaceax** [comment]
i retest later then :)

**Comment by mfranca0009** [comment]
![image](https://user-images.githubusercontent.com/26092980/99344151-68305680-285d-11eb-84b2-1f278568c96c.png)


All set after server rebuild 👍
