### ISSUE TITLE
[Quest] Thargad's Camp - Desolace

### ISSUE THREAD

**Issue by mfranca0009** [WoWManiaUK/Blackwing-Lair#4859]
**Links:**

https://www.wowhead.com/quest=14372/thargads-camp

**What is happening:**
This quest is able to be picked up by Horde, but it's an Alliance quest only.

**What should happen:**
Alliance players should only be able to pick up this quest.

**Is it crashing the server?:**
No

**Other Information:**
N/A

**Comment by mfranca0009** [comment]
All set, needs testing in PTR 👍

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 👍
