### ISSUE TITLE
[npc] Night Web Matriarch

### ISSUE THREAD

**Issue by k1ll3r** [WoWManiaUK/Blackwing-Lair#486]
in the cave in undead starting zone there is a mob that its not chargable or attackable :)

**Comment by Echinaceax** [comment]
https://www.wowhead.com/npc=1688/night-web-matriarch

- Inactive mob

**Comment by Dranah** [comment]
Is this mob needed for whatever quest?

**Comment by Rushor** [comment]
could you tell me the position of the mob?

**Comment by Echinaceax** [comment]
@Rushor 
![location](https://user-images.githubusercontent.com/39439201/54315730-42aa6e80-45df-11e9-876d-4fe3a86f370d.jpg)

**Comment by Dranah** [comment]
I can attack this mob without problem.
