### ISSUE TITLE
[Quest] Thunderdome Questline - unscripted/autocomplete - Tanaris

### ISSUE THREAD

**Issue by Eyamola** [WoWManiaUK/Blackwing-Lair#4861]
**Links:**

**Questline**

https://www.wowhead.com/quest=26895/the-thunderdrome

**Individual quests**

https://www.wowhead.com/quest=25067/thunderdrome-the-ginormus

https://www.wowhead.com/quest=25094/thunderdrome-zumonga

https://www.wowhead.com/quest=25095/thunderdrome-sarinexx

https://www.wowhead.com/quest=25513/thunderdrome-grudge-match **(A)**

https://www.wowhead.com/quest=25591/thunderdrome-grudge-match **(H)**

**What is happening:**

Like the Crucible of Carnage in Twillight Highlands (And i'm guessing the lines in Northrend and Outland) this series of quests can be completed as soon as it is started without fighting.

**What should happen:**

Mobs spawn upon receiving the quests, you fight, win, turn-in the quest. Rinse and repeat

**Is it crashing the server?:**

No

**Other Information:**

**Comment by Echinaceax** [comment]
thanks @Eyamola 
already reported here https://github.com/WoWManiaUK/Blackwing-Lair/issues/498
