### ISSUE TITLE
[Arena] Scoreboard Visual Problems

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4864]
**What is happening:**
- Arena wins display wrong team

**What should happen:**
should display winning team 

**Other Information:**

echi and Valknut are "The Solaria girls" not the team "winwang" lol

![arana](https://user-images.githubusercontent.com/39439201/98452521-3da11800-2150-11eb-9518-a988da984900.jpg)

**Comment by mfranca0009** [comment]
Multiple problems related to Arenas such as:
- [x] Arena ratings should start at 0, not at 1500. This was a change at or after patch 3.1
- [x]  Matchmaker ratings start at 1500.
- [x] Rating change is not displayed on the scoreboard after winning a match
- [x] Incorrect team names are displayed when winning and losing (as stated above)

![image](https://user-images.githubusercontent.com/26092980/123498248-d9a76300-d5fd-11eb-943e-bf16e5fa14c4.png)


The only working parts of the scoreboard currently are:
- [x]  Player names accurately printing
- [x] Killing blows accurately printing
- [x] Damage done accurately printing
- [x] Healing done accurately printing

We should move this issue to be a generic arena main report.

**Comment by Echinaceax** [comment]
Comfirmed fixed so far rrating change and name desplay 👍 

![image](https://user-images.githubusercontent.com/39439201/125826465-ace2f941-c7d4-4569-b792-6ffcd6612061.png)

**Comment by mfranca0009** [comment]
For the moment, visual problems on Arena scoreboard should be resolved 👍 

If any other Arena problems come up, then we can open new issue.

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 👍
