### ISSUE TITLE
[Spell/DK] Dark Simulacrum

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4871]
**Links:**

https://www.wowhead.com/spell=77616/dark-simulacrum

**What is happening:**
- Not working at all 

**What should happen:**

**_Places a dark ward on an enemy, triggering when the enemy next spends mana on a single-target spell, and allowing the Death Knight to unleash an exact duplicate of that spell.  Against nonplayers, only absorbs some harmful spells._**

**Comment by Keader** [comment]
Spell was working already.
But during tests me and @Echinaceax found a crash.
Fixed this crash found.
