### ISSUE TITLE
Archaeology Bug

### ISSUE THREAD

**Issue by drizztdo** [WoWManiaUK/Blackwing-Lair#4874]
**Links:**
There is nothing to link.
from WoWHead or our Armory

**What is happening:**

Sometimes when an archaelogical artifact is found, it spawns under terrain, inside walls etc.

**What should happen:**
It should spawn where it is reachable by the player always.
**Is it crashing the server?:**
No.
**Other Information:**

**Comment by Echinaceax** [comment]
know issue reported here #4237
