### ISSUE TITLE
[Spell/Class] Warrior Bloodthirst Ability/Blood Craze Talent Not Working Properly

### ISSUE THREAD

**Issue by Shizzy23** [WoWManiaUK/Blackwing-Lair#4876]
**Links:**

from WoWHead or our Armory

**What is happening:**Bloodthirst spell and Blood Craze talent is only healing for 1hp.

**What should happen:**Bloodthirst spell should heal according to level*(It says slightly).Blood Craze talent should heal %3 in 5 seconds. 

**Is it crashing the server?:**No

**Other Information:**

**Comment by Echinaceax** [comment]
Bloodthirst http://cata.cavernoftime.com/spell=30474
Blood Craze http://cata.cavernoftime.com/spell=16488

think these are the right ranks @mfranca0009 
depending on players lvl

**Comment by mfranca0009** [comment]
Bloodthirst should now be fixed, it was being calculated with an incorrect value, it will now heal you for 0.5% of max health.

After making the change for Bloodthirst, I tested Blood Craze, from rank 1 - 3 individually; I saw no issue. It was properly healing the play for 1% / 2% / 3% of player's max health over a 5 second duration.

**Comment by HrafnValknutt** [comment]
Fix in Dev confirmed. :)
