### ISSUE TITLE
Deleted Item in the mail.

### ISSUE THREAD

**Issue by Butterjib** [WoWManiaUK/Blackwing-Lair#4879]
Hello,  loving the server so far;  thanks.

I received an item in the mail earlier today 'adamanite rod'   and must have clicked 'delete' by mistake. Now both letter and item are missing,   I would have presumed that there would be a warning to prevent this happening with a full attachment and an option to 'cancel' the delete is made my mistake.

Is it possible to have this restored please?

Many thanks.

Butter.

**Comment by Echinaceax** [comment]
@Butterjib 
thanks for reporting,
yes it would help if we have a "are you sure you want to delete this item" message pop up, not sure if its blizzlike tho

players have to be more careful not to delete their items 

we can look into it 

Not sure you can get items resorted tho

**Comment by mfranca0009** [comment]
I can remember a warning message that should pop up if an item is still in the mail as an attachment.

Can't remember when this was added or if it was there from the start of the game.

I think this is a thing in WoW-Mania? I'm not 100% sure though cause I haven't played on Mania for a couple months.

**Comment by Echinaceax** [comment]
checked mania and theirs is the same as ours @mfranca0009

**Comment by Butterjib** [comment]
Hi Guys, thanks for commenting,  I remember it being a feature of the original game from as far back as I can remember, that's why I was so surprised for this to happen.    Any hoo, it is what it is.  Kind regards @Echinaceax  @mfranca0009

**Comment by mfranca0009** [comment]
No problem @Butterjib 

If we can find information somewhere through WoWhead or a youtube video during the Cata expansion of this feature then we will implement it. 

On the other hand, if we find no evidence of it being available in Cata then we will most likely close the issue without adding it.

**Comment by mfranca0009** [comment]
With further investigation, no evidence points to the warning message appearing; at least for WOTLK and CATA expansions.

If there is any evidence found, feel free to open another issue related to deleting mail with an item still attached and we will deal with it 👍
