### ISSUE TITLE
[NPC] Gordo

### ISSUE THREAD

**Issue by k1ll3r** [WoWManiaUK/Blackwing-Lair#488]
he gives you the quest but it should be a vendor too guess he needs a fixing too :) Abomination Gordo in undead zone

**Comment by Echinaceax** [comment]
Npc - https://www.wowhead.com/npc=10666/gordo

- Inactive vendor window

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/54418473-f1909c80-46fc-11e9-8c57-58913bce3685.png)
Works perfectly.

**Comment by Rushor** [comment]
this has regressed
