### ISSUE TITLE
[Spell] Leaping Bite

### ISSUE THREAD

**Issue by k1ll3r** [WoWManiaUK/Blackwing-Lair#489]
the mob is kinda bugged. It is suppose to do Leaping bite ability at the start of the combat or when the player is away but instead of that it is using it non stop and its pushing you around

**Comment by TheManiax** [comment]
@k1ll3r  regardless of how correct the content of your report is, this can be the correct format of your report:
[[Leaping Bite]](https://www.wowhead.com/spell=82797/leaping-bite) casted by [[Decrepit Darkhound]](https://www.wowhead.com/npc=1547/decrepit-darkhound)
**How it works:** Should be casted at the start of the combat or when the player is away.
**How it should work:** Is being casted non stop and its pushing you around.

**Comment by Keader** [comment]
Fixed.

**Comment by Dranah** [comment]
No longer spamcast.
