### ISSUE TITLE
[Talent] Executioner (Warrior)

### ISSUE THREAD

**Issue by Uncle1** [WoWManiaUK/Blackwing-Lair#49]
Talent ID=Not found

The talent isnt giving the Attack Speed bonus even if u spam it the talent property dont get trigered.

Executioner is a Warrior talent on tier 2 of the Fury tree. It grants your [Execute] hits a 50/100% chance to improve your melee attack speed by 5% for 9 seconds, stacking up to 5 times for a 25% attack speed increase.

**Comment by Keader** [comment]
Fixed.
Test tomorrow please.
