### ISSUE TITLE
[Spell]  Spell Reflection - Zul'Aman

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4906]
**Links:**

spell http://wotlk.cavernoftime.com/spell=59725
boss https://www.wowhead.com/npc=24239/hex-lord-malacrass

**What is happening:**
- Spell Reflection for Hex Lord Malacrass not working

**What should happen:**
Spell Reflection should put an aura/buff on the target and reflect any incoming spell. This aura/buff lasts 5 seconds.

**Comment by Keader** [comment]
fixed, try now pls

**Comment by mfranca0009** [comment]
Confirmed working on PTR 👍

**Comment by mfranca0009** [comment]
@Keader any reason why this is marked as Regression?

**Comment by Keader** [comment]
Yes, Just for organization (me and janitor) you can Just ignore it
