### ISSUE TITLE
[Quest] Ever So Lonely - ID 24974 - Tirisfal Glades

### ISSUE THREAD

**Issue by k1ll3r** [WoWManiaUK/Blackwing-Lair#491]
you get credit for delivering but not for capturing the murlock did it like 5 times and i coudnt complete cause of it :)

**Comment by Echinaceax** [comment]
Quest - https://www.wowhead.com/quest=24974/ever-so-lonely
Item - https://www.wowhead.com/item=52059/murloc-leash
NPC - https://www.wowhead.com/npc=38925/sedrick-calston

- Use the Murloc Leash on a Vile Fin murloc at the Whispering Shore, then return it to Sedrick Calston at Calston Estate.

**Comment by Rushor** [comment]
This works actually

https://i.imgur.com/0wclC1k.jpg

You must hit the orcale below 30 percent life, then use the Murloc Leash on it.

**Comment by Rushor** [comment]
Oh i was indeed bugged on live, the credit was no working for capturing and rope was not there

fixed now.

![I](https://i.imgur.com/pFK0KU4.jpg)
