### ISSUE TITLE
[Spell] Savage Defense - druid bear 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4910]
**Links:**
https://wowwiki.fandom.com/wiki/Savage_Defense
http://cata.cavernoftime.com/spell=62606

**What is happening:**
- very low absorb 

**What should happen:**
_Patch 4.1.0 (26-Apr-2011): 
Savage Defense has been redesigned slightly. Instead of a single charge absorption, it now places an absorption effect on the druid absorbing up to 35% of the druid's attack power (modified by mastery, if applicable) in damage and lasting 10 seconds. There are no longer any charges on the effect._

**Comment by Keader** [comment]
not problem found on it
