### ISSUE TITLE
Missing NPC at "Purification of Quel'Dalar"

### ISSUE THREAD

**Issue by HrafnValknutt** [WoWManiaUK/Blackwing-Lair#4912]
**Links:**
https://www.wowhead.com/quest=24564/the-purification-of-queldelar
from WoWHead 

**What is happening:**
Npc missing who can portal you to Sunwell
**What should happen:**
there should be a Npc at the gate of Sunwell Plateu raid who should teleport you to the quest area.
**Is it crashing the server?:**
No.

Like this:

https://www.youtube.com/watch?v=FILdWp5AaaQ

**Comment by Echinaceax** [comment]
https://www.wowhead.com/npc=37523/warden-of-the-sunwell

Edit
GM checked and npc missing plus no dialog shown on npc when he checked

**Comment by mfranca0009** [comment]
Added the NPCs, open the gossip dialog that is not there in a different issue. 

New issue needed because the teleport spell that should be used doesn't work and will need to be scripted on top of making the gossip option visible.

**Comment by Echinaceax** [comment]
confirmed npc is spawned in ptr 

but 

yes not fully fixed coz she has no teleporting dialog :)
after picking up the quest i spoke with the warden and no teleport dialog

want me to report this part seperately @mfranca0009 

![image](https://user-images.githubusercontent.com/39439201/106440197-d9ed6900-6478-11eb-81da-b6058c8f0386.png)
