### ISSUE TITLE
blast the infernals -  quest

### ISSUE THREAD

**Issue by almoghr** [WoWManiaUK/Blackwing-Lair#4917]
**Links:**

from WoWHead or our Armory

**What is happening:**

i fnished the quest and the question mark above the npc is stil lgray

**What should happen:**
the quest should be completeable
**Is it crashing the server?:**
no
**Other Information:**

**Comment by almoghr** [comment]
5 minutes later it became yellow and all works good.

you can delete this issue:)

thanks alot!

**Comment by Echinaceax** [comment]
thank you for update @almoghr :)
