### ISSUE TITLE
[QUEST] [The Conquest Pit: Mad Ferbolg Fighting] [QUEST = 12428] (issue2) - Grizzly Hills

### ISSUE THREAD

**Issue by Blametheheal** [WoWManiaUK/Blackwing-Lair#4919]
https://www.wowhead.com/quest=12428/the-conquest-pit-mad-furbolg-fighting

Whats happening : Furbolg despawns toward the end of the fight, but before quest flags as complete.

What should happen : Furbolg shouldn't despawn until dead and the quest should flag as complete upon his death.

Is it crashing the server?: No

**Comment by Echinaceax** [comment]
was fine for me 

![G1](https://user-images.githubusercontent.com/39439201/107129181-dbc58b00-68c3-11eb-810b-2a06744b3235.jpg)
![G2](https://user-images.githubusercontent.com/39439201/107129182-dec07b80-68c3-11eb-9dba-46b6a1939d69.jpg)
![G3](https://user-images.githubusercontent.com/39439201/107129183-dff1a880-68c3-11eb-8562-70ef026de7da.jpg)

ofc it could be that there wasnt enought damage atm if not done with 3 players/or lvl
