### ISSUE TITLE
[NPC] Apprentice Crispin - Tirisfal Glades

### ISSUE THREAD

**Issue by k1ll3r** [WoWManiaUK/Blackwing-Lair#492]
https://www.wowhead.com/npc=38978/apprentice-crispin
the npc is suppose to be vendor too but its not

**Comment by Kitzunu** [comment]
no change, still no vendor option
![image](https://user-images.githubusercontent.com/24550914/54374773-201c6200-4680-11e9-8dab-e7acac53ab95.png)
