### ISSUE TITLE
[Fishing]  A Penny For Your Thoughts 

### ISSUE THREAD

**Issue by Constant20** [WoWManiaUK/Blackwing-Lair#4922]
Links 

https://www.wowhead.com/achievement=2094/a-penny-for-your-thoughts
https://wow.gamepedia.com/A_Penny_For_Your_Thoughts

What is happening:

When fishing in the dalaran fountain after 30 min no coin is dropped 

What should happen:

https://www.youtube.com/watch?v=8sVwjBoRtYs&ab_channel=TheDetectivegamer

Is it crashing the server?:

No

Other Information:

**Comment by Echinaceax** [comment]
@Constant20 

can you check the achv and see if your have any off the list at all please 

![any at all](https://user-images.githubusercontent.com/39439201/100999236-cb5c0180-355c-11eb-926c-e84263f78c6b.jpg)

**Comment by Constant20** [comment]
![image](https://user-images.githubusercontent.com/39439201/112348489-29f1ea80-8cc8-11eb-805f-302d02c76885.png)

**Comment by Echinaceax** [comment]
adding to main report #5181

**Comment by Echinaceax** [comment]
fixed and confirmed fixed in dev
