### ISSUE TITLE
[Item] Mage armor glyph

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4923]
### reported by ingame player

**Links:**

https://cata-twinhead.twinstar.cz/?item=42749

**What is happening:**
- Mage armor glyph is not providing more mana

**What should happen:**

Your Mage Armor regenerates 20% more mana.

![mage glyph](https://user-images.githubusercontent.com/39439201/101044138-50f0a900-357f-11eb-8456-e0499719a6f0.jpg)

normal mage armor info no glyph info 
![mage armor](https://user-images.githubusercontent.com/39439201/101044259-6f56a480-357f-11eb-8db1-475a317a378b.jpg)

**Comment by mfranca0009** [comment]
All set 👍 

With Glyph:
![image](https://user-images.githubusercontent.com/26092980/107985899-01742380-6f99-11eb-9f51-aaf97920997e.png)


Without Glyph:
![image](https://user-images.githubusercontent.com/26092980/107985915-08029b00-6f99-11eb-8a51-351a151e086c.png)


It properly adds 20% more mana from the original calculation of Mage Armor.

**Comment by Echinaceax** [comment]
without glyph

![image](https://user-images.githubusercontent.com/39439201/107995238-80d81600-6fde-11eb-9889-5682f206f615.png)

with glyph 
![image](https://user-images.githubusercontent.com/39439201/107995095-4f5f4a80-6fde-11eb-87b1-6fa529eb4868.png)
