### ISSUE TITLE
[Quest] The Lodestone

### ISSUE THREAD

**Issue by tillouz** [WoWManiaUK/Blackwing-Lair#493]
The quest [The Lodestone](https://www.wowhead.com/quest=11366/the-lodestone) spawns double the amount of NPCs when seeing the vision.

**Comment by Dranah** [comment]
Is the quest possible to complete nonetheless?

**Comment by tillouz** [comment]
The quest is working as intended other than the NPCs double-spawning.

**Comment by Echinaceax** [comment]
not for me 
cant click on the broken tablet

![cant](https://user-images.githubusercontent.com/39439201/54459287-93000880-4766-11e9-94ba-32983aa9f0d9.jpg)

**Comment by Rushor** [comment]
no double spawn anymore

**Comment by Echinaceax** [comment]
> no double spawn anymore

can we click the tablet too now :P ?

**Comment by Kitzunu** [comment]
You dont click the table you use the quest item

**Comment by Echinaceax** [comment]
Oh ...ok :)
