### ISSUE TITLE
[spell/object] Cauldron of Battle 

### ISSUE THREAD

**Issue by Arishok** [WoWManiaUK/Blackwing-Lair#4932]
https://www.wowhead.com/spell=92643/cauldron-of-battle

**What is happening:**
Cauldron of Battle is giving Flask of Flowing Water ( Spirit ) to healers instead of Flask of the Draconic Mind ( Intellect )

**What should happen:**
Cauldron of Battle should give Flask of the Draconic Mind to the healers.
**Is it crashing the server?:**
No
**Other Information:**
https://www.mmo-champion.com/threads/842012-Cauldron-of-Battle-for-Healer 

https://www.wowhead.com/spell=92643/cauldron-of-battle#comments
" A big, fat cauldron for your 10-man raid, providing guild-funded flasks that match their talent set-up. Tanks get Steelskin, spellcasters get Draconic Mind, etc. Note that it doesn't include some specialized flasks, like Flowing Water, which gives a big ol' Spirit boost -- I imagine that this was to give healers a choice on whether they wanted the SP boost or the Spirit boost. It is only usable if your guild has the Better Living Through Chemistry achievement."

**Comment by Echinaceax** [comment]
Flask of Flowing Water - http://cata.cavernoftime.com/item=67438
Correct **Flask of Flowing Water**isnt listed in the create list 

 ![list of flasks](https://user-images.githubusercontent.com/39439201/101277286-af9e6880-37b3-11eb-8595-2812a73f46e8.jpg)

**Comment by revsmom** [comment]
The healers SHOULD get a spirit flask .. thats why we had a dps offspec like shadow on a priest if we wanted intel ... . so theres nothing wrong there :)

**Comment by Arishok** [comment]
@revsmom
Did you read any of the links that I sent?
I would like some references that the healers should get spirit from cauldrons. ( maybe I missed some info )
" thats why we had a dps offspec like shadow on a priest if we wanted intel  " I didn't get this point, can you explain it again please?

In case you didn't read anything of what I sent
"i duno what blizz is thinking about the Cauldron of Battle for heal specs, the most healer will get an intflask because its their highest stat, and the most healers know that they favorite spirt flask. This is in my guidl a realy problem rigth now. So what is blizz thinking about healers an Cauldron of Battle, is this a problem they are looking for or shout all healers live with the intflask? And is that a realy problem to use int?"
greetings"
source : https://www.mmo-champion.com/threads/842012-Cauldron-of-Battle-for-Healer
also feel free to read the comments too :)

**Comment by revsmom** [comment]
BACK in retail cata ....
HEalers got spirit from cauldrom 
DPS got str/int/agi from cauldrom 
Tanks got stamina from cauldrom 
i have no proof besides my knowlegde and my brain ... but i know that i always had my own flasks .. or .... i changed to dps to get intel and then when the flask was consumed i changed back to healer spec...  then i was healer with intel buff :

**Comment by Echinaceax** [comment]
The link you shown is a forum debate on blizzard and **"what was they thinking"**
here on Reign they are blizzlike , not player preference  @Arishok

**Comment by Arishok** [comment]
I did also play retail, but I can't say I remember everything that's why I bring links and other stuff.
@Echinaceax " what was they thinking" of giving the healer intellect flask from the cauldron, I guess that what he meant :)
ok take this one
![proof](https://user-images.githubusercontent.com/75563910/101286835-32e8aa00-3806-11eb-82d1-cc6e1a5c6d8e.png)

you can read it, the guy clearly says " I can 150% assure the flasks my Healers have been getting are Intellect and not spirit "


source: https://www.wowhead.com/item=62288/cauldron-of-battle#comments

"if your guild healers really want spirit flasks tell them to bring their own.. until then int is pretty much the better flask for all healing classes so they can take what they are provided!"
https://www.mmo-champion.com/threads/842012-Cauldron-of-Battle-for-Healer
comment number 14
in the end I take comments that being commented since 2011, so it has to be blizzlike. :)

**Comment by revsmom** [comment]
https://www.wowhead.com/item=65455/flask-of-battle#comments
here u go :D

**Comment by Arishok** [comment]
@revsmom 
You mean this one? because I didn't find any other comment speaks about the spirit flask.
![Healers cauld](https://user-images.githubusercontent.com/75563910/101287236-7cd28f80-3808-11eb-813c-83f867bdf1e0.png)

If you meant this one, then it really doesn't prove what you said if you read it carefully.
Intellect is the main stat while spirit is the second stat.
Anyways this is my last reply, unless you didn't mean that comment ( the one I just linked thinking that you meant it ).
