### ISSUE TITLE
[Quest] What came first, the Drake or the egg? - Blade's Edge Mountains

### ISSUE THREAD

**Issue by LightBringe1972** [WoWManiaUK/Blackwing-Lair#4933]
**Links:**

from WoWHead or our Armory

**What is happening:**
when opening an egg using the Temporal Phase Modulator and getting an adolescent or mature dragon, the dragons cannot be attacked.
The nether drakes (looks like basilisks, works.

**What should happen:**
after using the given item, all the dragons should be attack-able in order for the essence to drop.
**Is it crashing the server?:**
no
**Other Information:**

**Comment by Echinaceax** [comment]
http://cata.cavernoftime.com/quest=10609

**Comment by mfranca0009** [comment]
Nothing wrong with this quest, each NPC (Mature/Adolescent drakes, and the basilisks) are hostile after using the quest item. They are able to be attacked by the player and they attack the player once they're converted by the quest item. Quest items are able to picked up after killing them.

![image](https://user-images.githubusercontent.com/26092980/102019507-f7883700-3d41-11eb-97e4-e08434f1b1d9.png)

![image](https://user-images.githubusercontent.com/26092980/102019518-fd7e1800-3d41-11eb-8d2a-2eefd3a23c1f.png)

![image](https://user-images.githubusercontent.com/26092980/102019522-0242cc00-3d42-11eb-8287-9450ba12a4fb.png)
