### ISSUE TITLE
[NPC] Mazoga id 38927 Tanaris

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#4935]
**Links:**
npc
https://www.wowhead.com/npc=38927/mazoga
Quests
https://www.wowhead.com/quest=25021/blood-to-thrive
https://www.wowhead.com/quest=25025/sangthraze-the-deflector
https://www.wowhead.com/quest=25026/darkest-mojo
https://www.wowhead.com/quest=25032/secrets-in-the-oasis
https://www.wowhead.com/quest=25556/into-zulfarrak
https://www.wowhead.com/quest=27068/chief-ukorz-sandscalp
**What is happening:**
mazoga is not there for me 

**What should happen:**
mazoga shud be at 42.2, 23.8 
**Is it crashing the server?:**
no

**Other Information:**
he also starts 6 quests listed up there duno if its a phasing issue

**Comment by mfranca0009** [comment]
Yes, just doing some small checking, the NPC is in the current default phase but he has an aura attached to him for phasing him out. Will work on this shortly.

Tanaris Storyline: https://wow.gamepedia.com/Tanaris_storyline

I went through the beginning quests to check if he phases in after "Sandsarrow Watch" has been turned in but it still seems Mazoga is phased out and not accessible.

He should phase in when "Sandsarrow Watch" gets turned in, or he should already be visible with no phasing aura attached.

**Comment by Chargelol** [comment]
i followed zygor loremaster tanaris guide  cause i enjoy questing sometimes ;)

**Comment by mfranca0009** [comment]
Mazoga does not give out, https://www.wowhead.com/quest=27068/chief-ukorz-sandscalp, Mazoga's spirit gives this quest out.

https://www.wowhead.com/npc=40712/mazogas-spirit

**Comment by mfranca0009** [comment]
Removed invisibility aura, can't seem to find any evidence for the NPC to have the aura in the first place to phase it out. All set and needs testing in PTR 👍

**Comment by HrafnValknutt** [comment]
Confirmed fixed in PTR.
