### ISSUE TITLE
[NPC] Megs Dreadshredder id 38703 tanaris

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#4936]
**Links:**
https://www.wowhead.com/npc=38703/megs-dreadshredder

**What is happening:**
cant pickup 3 quests

**What should happen:**
shoud be able to pickup 3 quests from her
![WoWScrnShot_120920_003649](https://user-images.githubusercontent.com/50077942/101554365-c7920a00-39b6-11eb-847f-44e7e521b81b.jpg)
![WoWScrnShot_120920_003848](https://user-images.githubusercontent.com/50077942/101554423-ea242300-39b6-11eb-8a90-c4b4871ab2f6.jpg)
**Is it crashing the server?:**
no

**Comment by mfranca0009** [comment]
This also seems to be happening on the Alliance NPC quest giver as well:
https://www.wowhead.com/npc=38704/kelsey-steelspark

**Comment by mfranca0009** [comment]
The quest order for Alliance and Horde should be fixed with these quests. They should all be offered based on doing them in the proper order following this storyline order: https://wow.gamepedia.com/Tanaris_storyline
