### ISSUE TITLE
[Quest]  To The Ground! id 24928

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#4937]
**Links:**
http://www.cavernoftime.com/quest=24928
item 
http://www.cavernoftime.com/item=51547
video
https://www.youtube.com/watch?v=NyyYlD-PSSU
**What is happening:**
the item seems to be not working

**What should happen:**
the item shoud work and start a fire
**Is it crashing the server?:**
no

**Comment by mfranca0009** [comment]
Issue was confirmed, and has been fixed on PTR 👍 

Building should now display fire on top of it after using the item near each building and should now give out quest progress.

**Comment by HrafnValknutt** [comment]
Confirmed fixed in PTR.
