### ISSUE TITLE
[NPC] Rhea - phasing issue - Badlands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#494]
NPC - https://www.wowhead.com/npc=46654/rhea
npc Rhea is missing in Badlands
This prevents you from being able to complete the following quest
quest -https://www.wowhead.com/quest=27826/into-the-dragons-mouth
NPC -  https://www.wowhead.com/npc=46664
Search all the locations were she should be on the map but she isn't at any.

**Comment by Echinaceax** [comment]
**Same for Horde**
#465

**Comment by Dranah** [comment]
NPC is present but in wrong phase.

**Comment by zippoking** [comment]
For me she is still not there. I can´t complete the quest.

How it is:
![Into the dragons mouth - how it is](https://user-images.githubusercontent.com/18005338/59066028-61eb2c00-88ae-11e9-9378-93017261e5b6.png)



How it should be:
For this quest to end she should be at 21.2/57.8
![Into the dragons mouth - how it should be](https://user-images.githubusercontent.com/18005338/59066029-6283c280-88ae-11e9-8337-4874402710b1.png)
