### ISSUE TITLE
[Spell] Tectonic Plating - Zul'Gurub 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4940]
**Links:**

https://www.wowhead.com/spell=97987/tectonic-plating
https://www.wowhead.com/npc=52956/zandalari-juggernaut

**What is happening:**
- Spell steal is not working for this as it should (Mage)

**What should happen:**
Mages are supose to be able to spell steal this 

https://www.wowhead.com/spell=97987/tectonic-plating#comments

**Comment by mfranca0009** [comment]
ergh, isn't this for Zul'Aman? I know it says ZG on WoWhead link but we were testing this in Zul'Aman yesterday.
@Echinaceax

**Comment by Echinaceax** [comment]
emm no they are name differently
but there is an npc in ZA too that doesnt work too for same reason

**Comment by mfranca0009** [comment]
Mage "SpellSteal" works fine as long as the talent is acquired and mage has the spell.... works both in ZA and ZG.

![image](https://user-images.githubusercontent.com/26092980/101960900-7eb89c00-3bd6-11eb-9774-165b86c87230.png)

![image](https://user-images.githubusercontent.com/26092980/101960908-85471380-3bd6-11eb-952d-ac1f12380617.png)

![image](https://user-images.githubusercontent.com/26092980/101960919-8b3cf480-3bd6-11eb-9770-f33348ea07f0.png)
