### ISSUE TITLE
[Quest] Whispers of the Raven God - blade edge mountain

### ISSUE THREAD

**Issue by almoghr** [WoWManiaUK/Blackwing-Lair#4947]
**Links:**

from WoWHead or our Armory

**What is happening:**
after killing the arrakora i need to gain 2 minutes of speaking and i dont

**What should happen:**
i should get the speaking and then get the porphecys
**Is it crashing the server?:**
no
**Other Information:**

**Comment by mfranca0009** [comment]
@almoghr please provide links next time to the quest and other relevant information that is useful related to the quest where it says **"Links: from WoWhead or our Armory"**.

**Comment by Echinaceax** [comment]
https://www.wowhead.com/quest=10859/gather-the-orbs

**Comment by mfranca0009** [comment]
Prophecies quest:
https://www.wowhead.com/quest=10607/whispers-of-the-raven-god

While on this quest, if you kill an arrakora it should give you the 2 min buff so you are able to interact with the prophecy objects in order to complete the quest.

**Comment by Echinaceax** [comment]
found the problem @mfranca0009 

- when you kill any of the npcs, understanding buff is not given
they are not spell casting this on player https://www.wowhead.com/spell=37642/understanding-ravenspeech

also even when i cast the buff on myself the orbs are still not clickable
https://www.youtube.com/watch?v=0nz-dRGf2wE
https://www.youtube.com/watch?v=06UYmyjIN_Q

_It only takes 1 (one) kill to get the buff... you just have to kill the correct bird. Grishna Falconwings give the buff, but only if you are standing within Melee range. For casters, make sure you're close enough to take a swing at the Falconwing. If you're out in Wand or Spell range, you won't get the buff._

completed and working 
https://gyazo.com/562a9668472f6ce770abb1e262bc4384
