### ISSUE TITLE
[Quest] Terokkar Forest questline

### ISSUE THREAD

**Issue by Mrhype1** [WoWManiaUK/Blackwing-Lair#4948]
**Links:**

**What is happening:**
Hello! Soo i got to terokarr forest for an item (toy) which was [Time-Lost Figurine], the way to obtain this item is to kill terokk, an elite boss that can be summoned in Skettis, Terokk's Rest.

 So the first step to do this is to gather 6 shadow dusts from Skettis mobs and then go to Severin in Blackwind Landing so he can give you Elixir of Shadows, which gets us to the second step. The second step is to drink that elixir of shadows, go to Skettis and find time lost mobs there, these mobs drop time-lost scroll, you need to collect 40 time-lost scrolls to move on to the third step, though there's a catch, the elixir of shadows ends in 20 min after use so after that you can't see the time lost mobs anymore, but you can always go back to Severin for more elixir of shadows. 

After gathering 40 time - lost scrolls, keep them in your inventory, then you gotta make sure the you completed the quest "Adversarial blood" if not then the chain starts from an item named "ishaals almanac" that's drops from the mob talon priest ishaal (has 30% drop chance). So after adversarial blood you need to talk to hazzik that gives you another quest which is ishaals almanac, drops from talonpriest ishall (30% drop chance). 

Back to adversarial, you need to go the bone piles in skettis and summon 4 bosses that drop items needed for the last step, these are elite mobs so beware! After that you go back to hazzik and he will give you time lost offering, this is the items needed to summon terokk in terokk's rest. So you go to terokk's rest and interact with the ancient bone piles that fives you the option to summon him, he's an elite boss, then the fight begins! After he gets to low health, he gets a buff which is divine shield that makes him immune to ALL attacks, so basically he is invulnerable, the only way to remove this buff off him is to get to a blue smoke that spawns near you after he gets the buff. Then the bug is here! The smoke does not appear.So he is unkillable and all that farming went for nothing. Hope that gets fixed! 

**What should happen:**
The Blue Smoke should appear and it should remove the buff if terokk walks into the smoke. 
**Is it crashing the server?:**
No
**Other Information:**

 There's also the adversarial blood quest bug, it's a daily quest so you are able to re do it multiple times to get time lost offering (terokk is farmable) but the problem is even if you have the items, hazzik won't give you the quest so you can't get the time lost offering. 2 bugs in total hope this also gets fixed.

Thank you for listening!

**Comment by Echinaceax** [comment]
can you link all quest you need us to look into please @Mrhype1 

is this it https://www.wowhead.com/item=32782/time-lost-figurine

the other quest needs a seperate report

**Comment by Mrhype1** [comment]
Well I mean the only bugged quest is this:
https://www.wowhead.com/quest=11885/adversarial-blood

But the other bug is with terokk. Maybe this quest is related with what I wrote:
https://www.wowhead.com/quest=11073/terokks-downfall

**Comment by Echinaceax** [comment]
then clearer title please, and short explaination for each is more helpful,

So is this one about https://www.wowhead.com/quest=11885/adversarial-blood atm ?

**Comment by Mrhype1** [comment]
Yes it is that one, but you see that one is related to terokk, the rewards is used to summon terokk so if terokk is bugged, then still nothing will be resolved.

**Comment by Echinaceax** [comment]
yes @Mrhype1 i know, it usually happens like that with questlines, 

Terokkar Forest will be fixed in correct order as the coders get through the list

Thank you for reporting 

@mfranca0009 this also needs fixing https://github.com/WoWManiaUK/Blackwing-Lair/issues/2760 in same questline

**Comment by HrafnValknutt** [comment]
Test complete. 

All the quests are working fine. But the Terokk has issues still #2760. 
Also need to check tomorrow after dailies reset to see if the Adversarial Blood quest is offered as a daily.
