### ISSUE TITLE
[Quest] Bloodwatcher point - ID 27881- Badlands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#495]
Quest - https://www.wowhead.com/quest=27881/bloodwatcher-point
NPC- https://www.wowhead.com/npc=46664
I was able to obtain this on my alliance priest even though it is an horde quest.
It cannot be handed in by alliance because of the horde elites Guarding the base.
Incompletable.

**Comment by Dranah** [comment]
Wrong faction

**Comment by Rushor** [comment]
will now only be shown to horde
