### ISSUE TITLE
[Quest] Feathers for Nafian

### ISSUE THREAD

**Issue by Mrhype1** [WoWManiaUK/Blackwing-Lair#4951]
**Links:**

https://classic.wowhead.com/quest=8467/feathers-for-nafien

**What is happening:**
Hello! There is a quest in Felwood, Timbermaw Hold which is "Feathers for Nafien" , in this quest you are supposed to bring 5 deadwood headdress Feathers for An NPC named Nafien. The quest should be repeatable named as "More Feathers for Nafien" but its not, once you do it it's not there anymore. 

**What should happen:**

The quest comes back if you bring Nafien the 5 deadwood Headdress feathers. And then you can still be able to repeat it. 

**Is it crashing the server?:**
No
**Other Information:**

Quest Id: 28395

**Comment by Echinaceax** [comment]
that daily quest is isnt in Cata it seems 


its just a normal quest now only https://cata-twinhead.twinstar.cz/?quest=28395

conflicting info here says its repeatable 
_Feathers for Nafien awards 50 reputation and is repeatable with every 5 Deadwood Headdress Feather Icon Deadwood Headdress Feather turn-in._

questline https://www.icy-veins.com/wow-classic/timbermaw-hold-reputation-farming-guide


@mrhype1 have to tried just getting 5 feathers and visiting the npc to see if he just has the complete if you click the npc?

https://gyazo.com/54fdf1de33e6586de971162fa64f2bb9/draw

**Comment by Mrhype1** [comment]
Yes I did and nothing, and also, if there is no repeatable quest then how could you get exalted with timbermaw hold? After getting revered, the only way to earn rep is to do these repeatable quests.

**Comment by Echinaceax** [comment]
i found new info 
https://gyazo.com/52c9705807a952360b9a143c7c1f53cf

seems they made it into same quest name but just repeatable 

i'll test it tomorrow. thanks @Mrhype1

**Comment by Mrhype1** [comment]
Cannot see the image unfortunately :(
Send it in discord.
And no problem :D

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
confirmed fixed in ptr
