### ISSUE TITLE
System:  macro issue 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4955]
### Reported by Discord player 

**Links:**
https://eu.forums.blizzard.com/en/wow/t/mouseover-macros-for-idiots/43471/5

The problem that I’m having is with @mouseover (macro modifier) when I use it together with other target modifiers.

The target modifier per si is working normally when you use it to cast targeting with mouse, but the issue is when you put another modifier after him.
Macro supposed to work:
/use [mod1] [mod2] skill

->If [mod1] fails, it checks [mod2].

 But, when you put mod1 [@mouseover] and it fails, the system isn't checking the second modifier, it just announced that there is no target.

The link shows some examples about how it is supposed to work. I tried it a day ago and it didn't work.

**Comment by mfranca0009** [comment]
We need to know the exact macro trying to be used.... sure we can test a macro with two modifiers but we don't know what macro the user is trying to perform.... we need more information. @Echinaceax 

**UPDATE**
Macros work as intended, spoke to the user and straightened out the problem.
