### ISSUE TITLE
[Quest] What Lies Within - ID 25070 - Tanaris

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#496]
Quest - https://www.wowhead.com/quest=25070/what-lies-within
npc - https://www.wowhead.com/object=202474/antediluvean-chest
Video - https://www.wowhead.com/quest=25070/what-lies-within#videos:id=82472

- Defeat the Antechamber Guardian.
- He isn't summoned
- Cant complete

**Comment by Rushor** [comment]
![](https://i.imgur.com/CjbxPfz.jpg)
![](https://i.imgur.com/Dy5f7KN.jpg)
