### ISSUE TITLE
Fa-la-la-la-Ogri'la - winter veil - achievement

### ISSUE THREAD

**Issue by deni6** [WoWManiaUK/Blackwing-Lair#4962]
https://www.wowhead.com/achievement=1282/fa-la-la-la-ogrila

**What is happening:**
I just finished quest and no achievement was completed. 

**What should happen:**
Upon finishing quests you shall have you winter veil achievement finished. 
**Is it crashing the server?:**
No 
**Other Information:**
![image](https://user-images.githubusercontent.com/64712349/102546992-c8165900-40b8-11eb-8cdf-9818105e2dbf.png)

I did all pre quests, used  [Preserved Holly] to be flying reindeer.

**Comment by Echinaceax** [comment]
confirmed bug

![achv fa la la](https://user-images.githubusercontent.com/39439201/102615711-ab206b00-4136-11eb-9aeb-f7036d7d8ca7.jpg)

**Comment by Echinaceax** [comment]
retested on PTR and player must deliver quest back while mount is still a reindeer @mfranca0009 

![fa la](https://user-images.githubusercontent.com/39439201/102659943-89e16e00-417a-11eb-99be-5138c70f0557.jpg)
![fa la2](https://user-images.githubusercontent.com/39439201/102659946-8bab3180-417a-11eb-8073-7474eb34722f.jpg)
