### ISSUE TITLE
[Guild] Guild invite declining 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4964]
### Reported by ingame player

**What is happening:**
- When a guild member sends a player a guild invite that is already in another guild when they decline the invite they lose their existing guild

**What should happen:**
- Players that are in another guild shouldnt get another guild inv until they leave the guild that they are currently in
- should display " they are already in a guild"
- Declining a guild invite should NOT kick the player from their own guild that they are in (visual bug only) relog fixed this

**Is it crashing the server?:**

**Other Information:**

tested on PTR 
confirmed on PTR 

1. /who list 

![testman1](https://user-images.githubusercontent.com/39439201/102620177-ed00df80-413d-11eb-9bd4-0753f439f0b9.jpg)

2. send invite

![testman2](https://user-images.githubusercontent.com/39439201/102620284-115cbc00-413e-11eb-9005-08005f48a070.jpg)

3. invite sent 

![testman3](https://user-images.githubusercontent.com/39439201/102620360-32251180-413e-11eb-9ac1-daef78458b2d.jpg)

4. Decline invite

![testman4](https://user-images.githubusercontent.com/39439201/102620449-4d901c80-413e-11eb-90eb-a1ed7384e503.jpg)

5. lose guild you had before 

![testman5](https://user-images.githubusercontent.com/39439201/102620525-6ac4eb00-413e-11eb-9675-a0ab7baf3693.jpg)

**Comment by Echinaceax** [comment]
### note though

Guild kick is only a visual bug , fixed after relogging 
![testman5](https://user-images.githubusercontent.com/39439201/102626767-884a8280-4147-11eb-9f54-8b1a59977cf0.jpg)

![testman6](https://user-images.githubusercontent.com/39439201/102626840-a2846080-4147-11eb-9f1c-49cea6e5c26a.jpg)

**Comment by Echinaceax** [comment]
Also guild member can inv guild members of the same guild this way too

![testgnome1](https://user-images.githubusercontent.com/39439201/102628943-c6957100-414a-11eb-883d-2ea7ae664747.jpg)
![testgnome2](https://user-images.githubusercontent.com/39439201/102628944-c7c69e00-414a-11eb-830c-f8077d451d81.jpg)

relogging guild status was back

![testgnome3](https://user-images.githubusercontent.com/39439201/102628950-c8f7cb00-414a-11eb-89df-fcb6b9c971fe.jpg)


Tester was exactly with the reporter when this happened, and reporter was advised by player to relog to fix the visual bug regarding lost of guild status and guild rep, if player hadnt raged and /gquit himself their rep would have been fine. 

reactions from players are their own responability

**Comment by mfranca0009** [comment]
All fixed 👍

**Comment by Echinaceax** [comment]
confirmed fixed in ptr 😄
