### ISSUE TITLE
PvP: Vengeance ( Tanks )

### ISSUE THREAD

**Issue by Arishok** [WoWManiaUK/Blackwing-Lair#4968]
https://wow.gamepedia.com/Vengeance_(passive)

**What is happening:**
When dueling as a tank, you can see that the vengeance gets triggered when they hit you, which it shouldn't.
In Cata retail, they changed vengeance, Patch 4.3.2 (2012-01-31), that they made it to not be triggered in PvP.

**What should happen:**
In PvP, against other players, vengeance shouldn't be triggered by receiving damage from other players.

**Is it crashing the server?:**
No
**Other Information:**
Proof ( Patch notes of vengeance in cata )
https://wow.gamepedia.com/Vengeance_(passive)
" Cataclysm Patch 4.3.2 (2012-01-31): Vengeance is no longer triggered by receiving damage from other players. "

**Comment by Echinaceax** [comment]
Thank you @Arishok

**Comment by Echinaceax** [comment]
added info from Arishok 

![image](https://user-images.githubusercontent.com/39439201/103177812-09a7c080-487e-11eb-8484-958da9fe40bc.png)

**Comment by mfranca0009** [comment]
Now all fixed 👍

**Comment by Echinaceax** [comment]
confirmed fixed in PTR
