### ISSUE TITLE
Skinning: Mistwing Ravager / Mosshoof Courser

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4970]
Reported by Discord player

**Links:**

1. https://classic.wowhead.com/npc=8764/mistwing-ravager#skinning
2. https://classic.wowhead.com/npc=8761/mosshoof-courser#skinning

**What is happening:**
- Wrong skinning loot table 

**What should happen:**
- only leather should be dropped

**Other Information:**

![image](https://user-images.githubusercontent.com/39439201/102724060-02783400-430d-11eb-8d48-443f2d3e00b0.png)

**Comment by mfranca0009** [comment]
Should be all set 👍
