### ISSUE TITLE
Quest: Portal Overload -  Twilight Highlands

### ISSUE THREAD

**Issue by Loizo181** [WoWManiaUK/Blackwing-Lair#4974]
**Links:**

from WoWHead or our Armory

**What is happening:**
The object "Earth Portal Controller" doesn't work. https://www.wowhead.com/object=206018/earth-portal-controller
I guess https://www.wowhead.com/object=206019/air-portal-controller and https://www.wowhead.com/object=206017/water-portal-controller

**What should happen:**
These should debilitate the NPC's to fight them and complete the quest https://www.wowhead.com/quest=27659/portal-overload

**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
reported here #1880
