### ISSUE TITLE
Twilight Highlands quest bugged

### ISSUE THREAD

**Issue by Loizo181** [WoWManiaUK/Blackwing-Lair#4979]
**Links:**

http://cata.cavernoftime.com/quest=27788

from WoWHead or our Armory

**What is happening:**
Skullcrusher the Mountain isn't appearing

**What should happen:**
Skullcrusher appears and tries to crush the player 

**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
reported here #3304
please make sure you search if its already reported before making a new report 
thx LW
