### ISSUE TITLE
(NPC) Thistleshrub Dew Collector - Tanaris

### ISSUE THREAD

**Issue by Mrhype1** [WoWManiaUK/Blackwing-Lair#4980]
**Links:**
https://www.wowhead.com/npc=5481/thistleshrub-dew-collector

**What is happening:**
In Tanaris, Thistleshrub Valley, there should be mobs named Thistleshrub Dew Collectors, there isn't any of them there should be alot too. 

**What should happen:**
The mobs (Thistleshrub Dew Collectors) should be appearing as normal. 

**Is it crashing the server?:**
No
**Other Information:**

**Comment by mfranca0009** [comment]
More information needed... WoWhead comment provides evidence of them not existing at and possibly after patch 4.0.3

![image](https://user-images.githubusercontent.com/26092980/123492204-e076ab80-d5e6-11eb-9668-4548553ceb11.png)

**Comment by Echinaceax** [comment]
correct @mfranca0009 same info from https://wowpedia.fandom.com/wiki/Thistleshrub_Dew_Collector

![image](https://user-images.githubusercontent.com/39439201/123496145-06bc3b80-d627-11eb-8eda-580ffbcad436.png)
