### ISSUE TITLE
[Quest] Thunderdrome Grudge Match  - faction req missing - Tanaris 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#499]
- Gives Horde, Ally Quest

https://www.wowhead.com/quest=25513/thunderdrome-grudge-match

**Comment by Dranah** [comment]
Allies can also pick up the horde version.

https://www.wowhead.com/quest=25513/thunderdrome-grudge-match should be alliance-only
https://www.wowhead.com/quest=25591/thunderdrome-grudge-match should be horde-only
