### ISSUE TITLE
Daily/Fishing Darnassus, An Old Favorite

### ISSUE THREAD

**Issue by Chuonnasuan** [WoWManiaUK/Blackwing-Lair#4992]
**Links:**
https://www.wowhead.com/quest=29359/an-old-favorite

**What is happening:**
In order to complete this daily, one should go to Rut'theran Village to fish for 8 Kaldorei Herring.
( https://www.wowhead.com/item=69987/kaldorei-herring)
After fishing for almost an hour (twice) it doesn't fish up/drop.
So won't be able to complete this quest and the fishing achievement that comes with it.

**What should happen:**
The Kaldorei Herring should drop in Rut'theran

**Comment by Echinaceax** [comment]
added to main report #5181
