### ISSUE TITLE
[Quest] The Rebel Lord's Arsenal

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Blackwing-Lair#5]
http://wowwiki.wikia.com/wiki/Quest:The_Rebel_Lord%27s_Arsenal
When you do this  quest you get unphased, you dont see the npc and  mobs anymore.
I have try  to unphase unaura and so on but nothing got effect'
I have tried on difrent  worgens and is the same with all,

**Comment by fvicaria** [comment]
Please use wowhead.com links not wowwiki,
http://www.wowhead.com/quest=14159/the-rebel-lords-arsenal

Try following the comments in there also.

**Comment by gamer100** [comment]
http://www.wowhead.com/quest=14159/the-rebel-lords-arsenal

I have removed the quest from the char and the phase is normal again

**Comment by Dranah** [comment]
This quest 14159 right now can't be completed and has another issue too.

1) The limiting problem atm is that the cellar door leading to the room where you must go remains locked after you try to open it.
Like, when you click on it and it opens, there is a second door underneath that's still closed and cannot be opened - not even as a GM. This prevents you from reaching the NPC to hand in quest.

2) This quest becomes unlocked to pick up too early. 
It should be a follow-up from "Brothers in Arms" http://www.wowhead.com/quest=26129 when Crowley sends you back to Greymane with the information. 
Right now you can take it without any prerequisites, and skip the other 2 quests in the storyline. This makes the story non-linear, as well as this could be the reason behind the original phasing issue, as completing the quests in wrong order can severely fuck things up.

**Comment by Dranah** [comment]
UPDATE:
1st issue is fixed, cellar door is removed overall (solves the problem).

2nd issue still persists, you can take 14159 without prerequisites which messes up quest order and phasing.

**Comment by fvicaria** [comment]
The cellar door is still there and you can open it.

**Comment by Dranah** [comment]
I tested with two characters, one that existed before, and one I newly made.
The existing char sees the door clickable but nothing happens when I click it.
The new character doesn't see the door at all.
https://imgur.com/3PcmR5x

**Comment by Dranah** [comment]
Additional problems:

When you hand in this quest, the following should happen:
Josiah Avery (35369) transforms into a worgen and attacks you. You defeat him but he already applied worgen bite to you.

What actually happens:
Two worgen formed Josiah Averys spawn, that begin attacking you. The original NPC is still there as a friendly target and begins attacking himself (his worgen forms). There is also a visible and targetable "Josiah Event Trigger" somewhere inbetween that looks like a giant imp.
Actually, the whole Gilnean area is full of giant imps that aren't targetable, they are possibly other event triggers that we should not see as regular player.
