### ISSUE TITLE
[Spell] Ring of frost

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Blackwing-Lair#50]
[[Ring of Frost]](https://wow.gamepedia.com/Ring_of_Frost)

**How it should work:**
> **Description:** Summons a Ring of Frost, taking $91264d to coalesce.  Enemies entering the fully-formed ring will become frozen for $82691d.  Lasts $82676d.  $82676s2 yd radius.

**How it works:**
The ring (both graphic and effect) is moving to the caster location (no matter where you cast it)
Then it will start moving toward the target of your spells, meaning if you attack 5 different targets on 5 different location, the ring will move to them and the Ring effect (getting freezed) will be applied to all of them.

**Comment by Keader** [comment]
Fixed.
