### ISSUE TITLE
[NPC] Bogpaddle Privateer

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5002]
**Links:**

https://www.wowhead.com/npc=45887/bogpaddle-privateer

**What is happening:**
- NPCs were laid down dead

**What should happen:**
they should be standing up not dead :)

**Comment by mfranca0009** [comment]
Yes, all set and fixed in PTR 👍  SQL is uploaded with #541 as well.
