### ISSUE TITLE
Restoration Shaman - Nature's Blessing Talent

### ISSUE THREAD

**Issue by Arishok** [WoWManiaUK/Blackwing-Lair#5003]
https://wow.gamepedia.com/Nature%27s_Blessing
![N's B](https://user-images.githubusercontent.com/75563910/103538794-5740b080-4eb0-11eb-8d24-8c37f7004a0d.png)

**What is happening:**
The talent ' Nature's Blessing' is not working, the direct healing on the target with the ' Earth Shield' buff is not increased.

**What should happen:**
The talent ' Nature's Blessing' should increase the direct healing on ' Earth Shield' buffed targets by 18%. ( rank 3 )
**Is it crashing the server?:**
No

**Comment by Echinaceax** [comment]
talent ID http://cata.cavernoftime.com/spell=30869

nice i see you use IdTip @Arishok :)

**Comment by Keader** [comment]
fixed

**Comment by HrafnValknutt** [comment]
![WoWScrnShot_011121_204044](https://user-images.githubusercontent.com/72864958/104218333-a60cbe00-544d-11eb-81ec-54c6958ec5d7.jpg)


Fixed in Dev confirmed.
