### ISSUE TITLE
Quest The Drakkensryd Storm Peaks

### ISSUE THREAD

**Issue by Chuonnasuan** [WoWManiaUK/Blackwing-Lair#5005]
**Links:**
https://www.wowhead.com/quest=12886/the-drakkensryd
from WoWHead or our Armory

**What is happening:**
When i click a Dragon, or dragonrider, I will fall through the dragon and float aroud the temple of storms without body or mount. Unable to control my char. Only option provided is to dismount and fall to a certain death

**What should happen:**
(Copy/Paste from the comments provided on wowhead. Couldn't tell it better ;)  )
 the Drakkensryd is easily the most visually spectacular Kill X of Y quest in the game. When you pick it up from Gretta the Arbiter, she will hand you a Hyldnir Harpoon and pack you off on a proto-drake. The drake will fly west to the Temple of Storms, which rests on a very tall mountain peak. There you will enter formation with other riders, doing laps around the temple itself. At this point, dismounting is inadvisable, as there's no parachute.

To begin the quest itself, target a Hyldsmeet Proto-Drake (not a Hyldsmeet Drakerider), and use your harpoon. This will launch you to the back of the drake, where you and its rider will fight. So, yeah, there you are, on the back of a dragon, a mile above the ground, battling to the death. When you defeat your opponent, she falls to her doom, arms and legs flailing. Continue jumping from dragon to dragon until you've killed all ten, and when you're done, use your harpoon on a Column Ornament. That will get you into the temple itself, so you can turn in to Thorim.

**Is it crashing the server?:**
No
**Other Information:**
This is part 6 of a questline

**Comment by Chuonnasuan** [comment]
My apologies, i didn't see it was already a open issue. And have no idea how to delete this.

**Comment by Echinaceax** [comment]
no problem @Chuonnasuan :)
