### ISSUE TITLE
[Item] Twilight Documents 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5008]
**Links:**
https://www.wowhead.com/item=65734/twilight-documents

**What is happening:**
- only spawns once
_only one player gets the chance to loot it the others on the quest dont, they have to waity it next dungeon to get theirs_

**What should happen:**
_should respawn for other group members to loot for their quest too_ 
https://www.wowhead.com/quest=28815/twilight-documents

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
what timer for respawn @mfranca0009 
or was it a group loot fix ?

**Comment by mfranca0009** [comment]
No timer and no group loot, there is a setting to allow such gameobjects to have them never despawn. If you already received the quest item or you aren't on the quest then you can't interact with it.

**Comment by Echinaceax** [comment]
timer is 5 mins for respawn, i just timed it lol 

i looted it for myself and the respawn took exactly 5 mins to respawn again.
thats what i meant it is still despawning when i loot it then it respawns for next player 5 mins later 
(when they have moved to next boss) lol

**Comment by Echinaceax** [comment]
fixed in PTR
