### ISSUE TITLE
The blessing of Zim'Rhuk

### ISSUE THREAD

**Issue by LightBringe1972** [WoWManiaUK/Blackwing-Lair#5010]
**Links:**

from WoWHead or our Armory

**What is happening:**
Collected 10x drakari offerings, cannot interact with the statue to hand in the quest.

**What should happen:**
Once you have the 10x drakari offerings, the statue gives a a buff that lasts only in Zul Drak map
**Is it crashing the server?:**
no
**Other Information:**

**Comment by Echinaceax** [comment]
@LightBringe1972 ive dont this quest on most all my chars and is fine for me, i will check on a toon i havent done it on

**Comment by Echinaceax** [comment]
comfirmed not clickable

**Comment by Echinaceax** [comment]
i tested a few other ways and i found that you can actually deliver it back standing here 

![stand here](https://user-images.githubusercontent.com/39439201/104123492-ca807180-534b-11eb-9572-8ac485df9cb2.jpg)

**Comment by LightBringe1972** [comment]
thx echi :)

**Comment by Echinaceax** [comment]
np lightbringer :P
