### ISSUE TITLE
[going deep] - quest - desolace

### ISSUE THREAD

**Issue by almoghr** [WoWManiaUK/Blackwing-Lair#5012]
**Links:**

https://www.wowhead.com/quest=14260/going-deep

**What is happening:**

i get a disguise as an item and i need to use it to talk to the big naga lady. the disguise doesnt work

**What should happen:**
i should become a naga disguised and talk to the naga lady to complete the quest
**Is it crashing the server?:**
no

**Other Information:**

https://www.wowhead.com/item=49064/slitherblade-charm
this is the broken item

**Comment by almoghr** [comment]
btw this issue is holding back 7 quests from being able to happen as you can see in the wowhead link above

**Comment by mfranca0009** [comment]
Item spell doesn't trigger disguise, these spells trigger the disguise, underwater breathing, and movement speed boost:

Female: https://www.wowhead.com/spell=68165/naga-disguise
Male: https://www.wowhead.com/spell=68086/naga-disguise

The effect needs to be scripted.

**Comment by mfranca0009** [comment]
Fixed 👍 

BUT there's going to be further problems with: https://www.wowhead.com/quest=14264/wetter-than-wet

If you watch the video for this quest (https://www.youtube.com/watch?v=hBn23UnLiyI), you should have a vehicle bar with specific spells to use with this disguise. This vehicle bar does not appear, so this will also need to be scripted. Needs a new issue open, and most likely the rest of the quests handed out by Valishj (https://www.wowhead.com/npc=35827/valishj) need to be tested.
