### ISSUE TITLE
[Raid] Cache of the Dreamwalker - Icecrown Citadel

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5015]
**Links:**
https://www.wowhead.com/object=201959/cache-of-the-dreamwalker
https://www.wowhead.com/npc=36789/valithria-dreamwalker

**What is happening:**
- gave 3 items instead of 2

**What should happen:**
Should only give 2

![CASH OF THE DREAMWALKER](https://user-images.githubusercontent.com/39439201/104247837-c7c76e80-5468-11eb-97d9-0ff475b19445.png)

**Comment by mfranca0009** [comment]
Should be fixed now 👍
