### ISSUE TITLE
Worgen Female textures replaced with male, deformities, and now showing gear. 

### ISSUE THREAD

**Issue by onetoejoe** [WoWManiaUK/Blackwing-Lair#5016]
**Links:**
Imgur image link to problem:
https://imgur.com/a/pWZhyTZ

**What is happening:**

My friends and i made worgen characters to level together, 1 was female. After we got bitten in the questline and actually changed into worgen, the female character's body textures were replaced with male, and the face and hair textures were replaced with male face textures....Also, the armor did not show, so she always looked like how she does in the picture, even after changing armor, and trying to relog. 

**What should happen:**
The models should be replaced with the proper ones, so that the female worgen doesnt look like a monster. (and shows your gear)
**Is it crashing the server?:**
No, the game did not crash. No, the server did not crash.
**Other Information:**
I have not tried to replicate the problem. And my friend has not logged back in since then to test to see if the problem is gone. Further investigation would be needed to fiix.

**Comment by mfranca0009** [comment]
#5017
