### ISSUE TITLE
Spell: Soul swap/glyph of soul swap - warlock

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5018]
### Reported by ingame player

**Links:**

https://www.wowhead.com/spell=86121/soul-swap
https://cata-twinhead.twinstar.cz/?item=42466

**What is happening:**
warlock's soul swaps always works as if glyphed even when you don't glyph

**What should happen:**
should not give the bonus of the glyph only should give function of spell 
![soul swap](https://user-images.githubusercontent.com/39439201/104350118-170ead00-5504-11eb-9eb7-110907ada6a4.jpg)

**Comment by mfranca0009** [comment]
This is the glyph: https://cata-twinhead.twinstar.cz/?spell=56226

Can someone re-test this, cause currently there is a condition to make sure the player has the glyph before leaving the DoTs on the previous target. If the glyph isn't active, it shouldn't leave the DoTs on the previous target when using Soul Swap on a new target; it also shouldn't give a 30 minute cooldown. @Echinaceax

**Comment by HrafnValknutt** [comment]
It works like a charm , no issue found

Edited by Echi
