### ISSUE TITLE
Halls of Origination - Temple Guardian Anhuur

### ISSUE THREAD

**Issue by Itsshupz** [WoWManiaUK/Blackwing-Lair#5019]
**Links:**
www.wowhead.com/npc=39425/
from WoWHead or our Armory

**What is happening:**
Every 20 seconds the boss resets and gains full health.

**What should happen:**
Should go trough with the fight and pop a shield to drop down and pull the levers.

**Is it crashing the server?:**
No.

**Other Information:**
Cant get trough the rest of the dungeon because it is the first boss.

**Comment by Echinaceax** [comment]
nothing wrong with this dungeon, done it many times myself
tell your tank not to use any interepts 😉
