### ISSUE TITLE
distress beacon - item - aint triggering a quest (issue2)

### ISSUE THREAD

**Issue by almoghr** [WoWManiaUK/Blackwing-Lair#5025]
**Links:**
https://classic.wowhead.com/item=8705/oox-22-fe-distress-beacon
https://classic.wowhead.com/quest=2766/find-oox-22-fe
**What is happening:**

i click on the item and it says i do not meet the requirements for starting the quest
**What should happen:**
i should have  a quest starting
**Is it crashing the server?:**
no
**Other Information:**
quest link and item link are listed up above

**Comment by Echinaceax** [comment]
hi @almoghr i found no issue with it on PTR 
Will test on live server 

![not an issue for me](https://user-images.githubusercontent.com/39439201/105044198-c6003b00-5a66-11eb-8242-582f1bc5b55f.jpg)
![quest ](https://user-images.githubusercontent.com/39439201/105044218-c8fb2b80-5a66-11eb-9618-dcb62b78aeac.jpg)

**Comment by Echinaceax** [comment]
spoke with player 

the 2nd quest is availible before the 1st has been delivered (via the drop) 
I will report the other quest and close this one 

reported it here #5026 

![2nd quest here](https://user-images.githubusercontent.com/39439201/105050256-e253a600-5a6d-11eb-9727-919963138d45.jpg)
