### ISSUE TITLE
[Quest] Rescue OOX-22/FE! - Feralas 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5026]
**Links:**

2nd quest https://classic.wowhead.com/quest=2767/rescue-oox-22-fe
1st quest https://classic.wowhead.com/quest=2766/find-oox-22-fe

**What is happening:**
- This quest is available before the 1st quest is delivered 
which messes up the player when the 1st quest does drop 

**What should happen:**
shouldnt be available until the 1st quest is delevered

**Other Information:**
player gets the message "you dont meet the requirements"
coz they already completed the 2nd part of this  which was reported here today #5025

**Comment by mfranca0009** [comment]
Quest order should be fixed 👍
