### ISSUE TITLE
Stable masterstable master and flight master bug (issue 2)

### ISSUE THREAD

**Issue by ocop09** [WoWManiaUK/Blackwing-Lair#5027]
Hello there.
When I handed over a boar belonging to 35 LVL hunters to the stable master, I received the following error and subsequently all my flight routes I learned were lost.

https://i.hizliresim.com/KQIj40.png

**Comment by Echinaceax** [comment]
It has been reported here #4185 never seen the flightpaths disapear though, many of the flight paths dont need to be discovered in Cata so not sure why the stable but is interfering with flight paths

**Comment by Echinaceax** [comment]
i do believe that you havent unchecked your Reign folder from "read only" so the Flight paths you had didnt save 

i will close this because the stable issue is already reported here #4185
