### ISSUE TITLE
[NPC] Magatha Grimtotem - 47745 (missing) - Thousand Needles

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5029]
### Reported by a player to a GM 

**Links:**
https://www.wowhead.com/npc=47745/magatha-grimtotem

**What is happening:**
- npc missing 

**What should happen:**
npc needed for quest delivery and quest pickup 

**other info** 

quest delevery https://www.wowhead.com/quest=28142/to-the-withering
quest pick up https://www.wowhead.com/quest=28157/four-twilight-elements
quest pick up https://www.wowhead.com/quest=28158/unbound
quest pick up https://www.wowhead.com/quest=28159/the-doomstone
quest pick up https://www.wowhead.com/quest=28161/spread-the-word

**Comment by mfranca0009** [comment]
All set 👍 

![image](https://user-images.githubusercontent.com/26092980/106211953-956f7e00-6197-11eb-899a-a6285a6f38f5.png)
