### ISSUE TITLE
[Spell/Talent] Savage Defense 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5030]
### Reported by ingame players

**Links:**

https://wowwiki.fandom.com/wiki/Savage_Defense
https://cata-twinhead.twinstar.cz/?spell=62600

**What is happening:**
- Absorb amount is very low 

**What should happen:**

**patch 4.1 changes** 

Patch 4.1.0 (26-Apr-2011): Savage Defense has been redesigned slightly. Instead of a single charge absorption, it now places an absorption effect on the druid absorbing up to 35% of the druid's attack power (modified by mastery, if applicable) in damage and lasting 10 seconds. There are no longer any charges on the effect.

Each time you deal a non-periodic critical strike while in Bear Form, you have a 50% chance to gain Savage Defense, absorbing physical damage equal to 35% of your attack power for 10sec. | Each time you deal a non-periodic critical strike while in Bear Form, you have a 50% chance to gain Savage Defense, absorbing physical damage equal to 35% of your attack power for 10sec. 
Each time you deal a non-periodic critical strike while in Bear Form, you have a 50% chance to gain Savage Defense, **absorbing physical damage equal to 35% of your attack power for 10sec.**

**other info** 
comment on twinstar is https://cata-twinhead.twinstar.cz/?issue=3249

Poor conversion to absorb at less than 6k attack power this spell absorbed in the range of 70-600k dmg
Mastery should increase my absorb by 33%

Absorb me properly: 35% total attack power + 1 point mastery increases absorb by 4%
Ex .: at 25 master points, the bonus is increased by 100%, so the total absorb will be 70% attack power

and this 

I took a good look at it one more time, so hopefully it will be without confusion :)

savage defense is turned on in bear form in any talents, or without talents - right
it turns on me in pve and in pvp - right
a chance of 50% of non-periodic critics - estimated correctly
absorber size at 12.48 masters:

feral talents:
10790 ap
8 masters in the base increase the absorption by 32%,
for 4.48% masters from the team it is + 17.92%
total 49.92%
(0.35 * ap) * 1.4992 = 5661.729
absorb the bubble real in the game - 5661 - right

balance talents (same feral eq):
8632 ap
same masters 12.48
The balance druid should not profit from the masters, so the bubble should be large
0.35 * ap = 3021.2
but the real absorb is 4529 - wrong
(0.35 * ap) * 1.4992 = 4529
balance druid therefore benefits from feral masters, similarly it will probably be with resto talents and without talents
edit: tested even without talents and with resto talents - just a bugle as in balance

**Comment by HrafnValknutt** [comment]
"Savage Defense" is only working with Feral Combat Talent Tree and you need to be in Bear Form. On the screenshot, as you can see too, this mastery comes with Feral Combat Tree. 

![WoWScrnShot_012921_153521](https://user-images.githubusercontent.com/72864958/106276155-2dc53b80-6248-11eb-81c3-15cd8c7f6e05.jpg)

And tested with Tauren Druid (Feral) on a normal Tol Barad mob to see the amounts:

As you can see the character has %50 additional absorption that comes from Mastery. 

![WoWScrnShot_012921_152218](https://user-images.githubusercontent.com/72864958/106276316-77ae2180-6248-11eb-87f4-155c895caeb4.jpg)

And the Savage Defense gives %35 absorption about damages. As you can see that damage absorption on the next screen shot. 

![WoWScrnShot_012921_151713](https://user-images.githubusercontent.com/72864958/106276462-ad530a80-6248-11eb-8cc0-9c2f800ea864.jpg)

Character has 12k Attack Power, Savage Defense and Mastery gives Absorption that %85 of the Attack Power. (10k)

It seems totally allright.

**Comment by Echinaceax** [comment]
thank you @HrafnValknutt
