### ISSUE TITLE
[Quest Item] Charred Staff Fragment - Mount hyjal 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5031]
**Links:**

item https://www.wowhead.com/item=54461/charred-staff-fragment
quest https://www.wowhead.com/quest=25472/the-flameseers-staff 

**What is happening:**
- Recently its been noticed that the quest item isnt showing as it was before 

**What should happen:**
Quest item should be spawned and respawn for players to complete the quest 

**Other Information:**
GM says 2 players have same issue

**Comment by mfranca0009** [comment]
#5032 issue has been resolved as a whole inside core code, should be fixed once update goes to live 👍
