### ISSUE TITLE
[Objects] Gameobjects missing

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5032]
**Links:**
https://www.wowhead.com/quest=25472/the-flameseers-staff
https://www.wowhead.com/quest=27750/war-forage
https://www.wowhead.com/object=206786/windspeaker-pylon

#5031

**What is happening:**
- Noticed since fixing #5008 other objects from other quests are not spawning 

**What should happen:**
need objects to spawn like before :)

**Comment by mfranca0009** [comment]
Issue resolved within the core, shouldn't be a problem anymore once update goes to live 👍
