### ISSUE TITLE
 [The Pinnacle of Learning] - Azshara  quest

### ISSUE THREAD

**Issue by almoghr** [WoWManiaUK/Blackwing-Lair#5037]
**Links:**

https://www.wowhead.com/quest=14413/the-pinnacle-of-learning
https://www.wowhead.com/npc=35187/image-of-archmage-xylem
**What is happening:**

the npc (ID 36334) is missing i need to turn in a quest and cant
https://www.wowhead.com/npc=36334/image-of-archmage-xylem

**What should happen:**
the npc should be there:)

**Comment by mfranca0009** [comment]
Added the missing NPC, but we need a new issue open. Watch this video when accepting the quest, it's suppose to turn you into an orb and then it should fly you over to the turn-in automatically.

https://www.youtube.com/watch?v=D0sx7mbtSls

**Comment by Echinaceax** [comment]
confirmed fixed in ptr 

![image](https://user-images.githubusercontent.com/39439201/106442699-e1624180-647b-11eb-9190-156818690a5a.png)
