### ISSUE TITLE
[Quest] Warchief's Command: Azshara!  (missing) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5040]
**Links:**

quest missing https://wow.gamepedia.com/Warchief%27s_Command:_Azshara!
questline https://wow.gamepedia.com/Azshara_storyline

**What is happening:**
- Warchief's Command: Azshara!  (missing) from quest board
https://www.wowhead.com/npc=35086/labor-captain-grabbit

**What should happen:**
_Report to Labor Captain Grabbit at the Orgrimmar Rear Gate in Azshara._
https://www.youtube.com/watch?v=18zCHYOdmnc

**Other Information:**
messing up the quests for the quest order https://github.com/WoWManiaUK/Blackwing-Lair/issues/5045
after you pick up the **Warchief's Command: Azshara!** you are then sent to **Labor Captain Grabbit** where you then pick up 

2.Runaway Shredder!
3.The Captain's Logs
4.Up a Tree
5.Defend the Gates!
6.Arborcide

after adding quest, the next quest is given 

![image](https://user-images.githubusercontent.com/39439201/106273679-5ee74100-6233-11eb-96ee-6eac0bb734a0.png)

Screenshot taking from the end of the video,  Runaway Shredder! it the next quest and is given once you have delivered **Warchief's Command: Azshara!**

![image](https://user-images.githubusercontent.com/39439201/106274012-e1700080-6233-11eb-9d38-f0a1662612b2.png)

**Comment by mfranca0009** [comment]
Quest should now be available from Orgrimmar and Thunder Bluff war boards.

**Comment by Echinaceax** [comment]
confirmed fixed in ptr 

![confirmed](https://user-images.githubusercontent.com/39439201/106437547-ad841d80-6475-11eb-8cef-c8dd39e97b8c.jpg)
