### ISSUE TITLE
[Quest Item] Perfect Yeti Hide - feralas quest

### ISSUE THREAD

**Issue by almoghr** [WoWManiaUK/Blackwing-Lair#5047]
**Links:**

https://classic.wowhead.com/item=18972/perfect-yeti-hide

**What is happening:**

i killed more then 1k of the yetis and never got the hide

**What should happen:**
i should get eventually the item to start the quest
**Is it crashing the server?:**
no
**Other Information:**

**Comment by Echinaceax** [comment]
yes rare drops can take time @almoghr 
@mfranca0009 can check if all set to drop though 

Rare drop starts a quest @mfranca0009

**Comment by almoghr** [comment]
yes it is actually a check about rarity. i dun remember when it took me that long but maybe its my mistake:)
