### ISSUE TITLE
[Quest] Land's End - Tanaris

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#505]
Quest - https://www.wowhead.com/quest=25061/lands-end
npc - https://www.wowhead.com/npc=11811/narain-soothfancy

- Ally quest given to Horde

**Comment by simonverse** [comment]
can't turn in as ally

**Comment by Rushor** [comment]
condition added, questender added

![](https://i.imgur.com/DeMb6cI.jpg)
