### ISSUE TITLE
npc - ajamon ghostcaller - thousand needles 

### ISSUE THREAD

**Issue by almoghr** [WoWManiaUK/Blackwing-Lair#5051]
**Links:**
https://www.wowhead.com/npc=41060/ajamon-ghostcaller

**What is happening:**

he is not giving the 3 quests he should give, checked it with GM zinius also.

**What should happen:**
he should have 3 quests to give
**Is it crashing the server?:**
no
**Other Information:**

the quests:
https://www.wowhead.com/quest=25672/carcass-collection
https://www.wowhead.com/quest=25704/the-mad-magus
https://www.wowhead.com/quest=25661/with-a-little-help

**Comment by Echinaceax** [comment]
@almoghr 

Ok, after giving the quest back https://www.wowhead.com/quest=25660/haunted to Ajamon ghostcaller, i was offered the next quest (currently reported bugged here #5218 )

![image](https://user-images.githubusercontent.com/39439201/106360855-26229700-631b-11eb-8613-36dfbb215ab2.png)

what actually happened when you gave your  **haunted** quest too her?

**Comment by Echinaceax** [comment]
after handing back https://www.wowhead.com/quest=25661/with-a-little-help i am offered 

![image](https://user-images.githubusercontent.com/39439201/106361224-17d57a80-631d-11eb-8d14-3befc794101f.png)

**Comment by Echinaceax** [comment]
after handing in the quest _Carcass Collection_ i am offered _The Mad Magus_

![image](https://user-images.githubusercontent.com/39439201/106361758-b5ca4480-631f-11eb-859b-64c6b9a3606c.png)

**Comment by Echinaceax** [comment]
if quest are returned in the correct order then there is no issue there 
closing this report
