### ISSUE TITLE
 [Magic Carpet Ride] - borean tundra

### ISSUE THREAD

**Issue by almoghr** [WoWManiaUK/Blackwing-Lair#5056]
**Links:**

https://www.wowhead.com/quest=11636/magic-carpet-ride
**What is happening:**

i need to go to an npc and deliver the quest, the question mark above him is gray

**What should happen:**
the question mark should be yellow - hence it should be completeable
**Is it crashing the server?:**
no
**Other Information:**

<img width="838" alt="Screenshot 2021-02-01 115634" src="https://user-images.githubusercontent.com/59969075/106442904-8e40bc80-6484-11eb-96b7-3478ecf23ed9.png">

**Comment by Echinaceax** [comment]
was reported here @mfranca0009  but was invalid https://github.com/WoWManiaUK/Blackwing-Lair/issues/3970

**Comment by Echinaceax** [comment]
Tested on live @mfranca0009 found no issue 

![carpet1](https://user-images.githubusercontent.com/39439201/106744527-2f17af00-6620-11eb-9bce-d3995857e0bf.jpg)
![carpet2](https://user-images.githubusercontent.com/39439201/106744539-30e17280-6620-11eb-8554-7c62004ce215.jpg)
![carpet3](https://user-images.githubusercontent.com/39439201/106744552-3474f980-6620-11eb-94aa-c4750e7e4cc8.jpg)
![carpet4](https://user-images.githubusercontent.com/39439201/106744561-36d75380-6620-11eb-8a17-dcfcf93c8a34.jpg)
![image](https://user-images.githubusercontent.com/39439201/106744656-52daf500-6620-11eb-9c30-87f003b082d3.png)

**Comment by Echinaceax** [comment]
@almoghr 
Correct me if im wrong but i see you on your own rocket in your screenshot and not taking the flying carpet ride from Yanni, 
you need to speak with Yanni to take the carpet ride like i did 

![image](https://user-images.githubusercontent.com/39439201/106745653-b9acde00-6621-11eb-888b-4bbebee7c18e.png)


![carpet2](https://user-images.githubusercontent.com/39439201/106745169-0217cc00-6621-11eb-9b6d-ed75c1a461ba.jpg)


![carpet3](https://user-images.githubusercontent.com/39439201/106745011-d5fc4b00-6620-11eb-9a4a-a96fa75155c6.jpg)

**Comment by almoghr** [comment]
i talked to yanni and nothing appeared, abandoned the quest and took it again and the npc did gave me the oppurtunity to get the carpet.. something did went wrong there but im not sure what.. all works now:)
