### ISSUE TITLE
[General] Event ingame calendar

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5058]
**Links:**
https://wowwiki-archive.fandom.com/wiki/Calendar
https://wowwiki-archive.fandom.com/wiki/Event

**What is happening:**

- [x] shows in-game realm events (not working correctly)
- [x] players add their own events including raid scheduling (not working correctly)

Many of the Realm event not shown on Calendar, and just randomly activate so a GM has to deactivate.  
the order of the world events is messed up 

**What should happen:**
- love in the air 
- Lunar Festival 
- Children's Week 
- Midsummer Fire Festival 
- Pirates' Day - Brewfest 
- Hallow's End 
- Day of the Dead 
- Pilgrim's Bounty 
- Feast of Winter Veil
- Darkmoon Faire https://github.com/WoWManiaUK/Blackwing-Lair/issues/2700#issuecomment-561252962

all should be listed in the calender and activate on that set date according to the date of the event 

**Other Information:**
@mfranca0009 i do have a date DB list from Rushor if you need it 

https://www.wowhead.com/love-is-in-the-air-guide

**Love is in the Air (February 8 - February 21)**

our ingame calender not showing events as they should eg: 

![event love](https://user-images.githubusercontent.com/39439201/106729445-c45d7800-660d-11eb-8fc6-0315d8495f81.jpg)

**Comment by mfranca0009** [comment]
### Add Calendar Details Up to Year 2025 (With Correct Date Information)
- [x] Lunar Festival
- [x] Love Is In The Air
- [x] Pilgrim's Bounty
- [x] Children's Week
- [x] Noblegarden
- [x] Harvest Festival
- [x] Midsummer Fire Festival - 341
- [x] Pirates' Day - 398
- [x] Brewfest - 372
- [x] Hallow's End - 324
- [x] Day of the Dead - 409
- [x] Feast of Winter Veil - 141
- [x] Darkmoon Faire - 479 (As best as possible)
- [x] Darkmoon Faire Building (Elywnn Forest) (Removed from calendar, not in Cataclysm)
- [x] Darkmoon Faire Building (Mulgore) (Removed from calendar, not in Cataclysm)
- [x] Darkmoon Faire Building (Terokkar Forest) (Removed from calendar, not in Cataclysm)

### Update Game Event start and end times (To Trigger Properly)
- [x] Lunar Festival
- [x] Love Is In The Air
- [x] Pilgrim's Bounty
- [x] Children's Week
- [x] Noblegarden
- [x] Harvest Festival
- [x] Midsummer Fire Festival - 341
- [x] Pirates' Day - 398
- [x] Brewfest - 372
- [x] Hallow's End - 324
- [x] Day of the Dead - 409
- [x] Feast of Winter Veil - 141
- [x] Darkmoon Faire - 479
- [x] Darkmoon Faire Building (Elywnn Forest) (Removed from triggering, not in Cataclysm)
- [x] Darkmoon Faire Building (Mulgore) (Removed from triggering, not in Cataclysm)
- [x] Darkmoon Faire Building (Terokkar Forest) (Removed from triggering, not in Cataclysm)

**Comment by mfranca0009** [comment]
Player's creating their own events work fine, so I'm unsure the specifics of what is wrong with them... need more details on what issue is happening; also we should put it into a separate issue. @Echinaceax 


![image](https://user-images.githubusercontent.com/39439201/108140155-ccafbb80-70c1-11eb-9398-844a3d56673a.png)



All main events listed above have been updated to trigger properly and show in the calendar properly now until 2025 when they will need to be updated again. 👍
