### ISSUE TITLE
[Quest] Get The Centipaarty Started - ID 24957 - Tanaris

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#506]
quest - https://www.wowhead.com/quest=24957/get-the-centipaarty-started
item - https://www.wowhead.com/item=52041/centipaarts
npc - https://www.wowhead.com/npc=38849/megs-dreadshredder

- Items not dropping 

![not dropping](https://user-images.githubusercontent.com/39439201/51077446-47b67480-16a7-11e9-929f-8c054210ca5a.jpg)

**Comment by Rushor** [comment]
![I](https://i.imgur.com/y3fVO1J.jpg)

80 percent dropchance
