### ISSUE TITLE
[Quest] Thalorien Dawnseeker (missing)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5060]
**Links:**
Quest missing https://www.wowhead.com/quest=24563/thalorien-dawnseeker
Quest giver https://www.wowhead.com/npc=37527/halduron-brightwing

**What is happening:**
- Quest not given after the delivery of https://www.wowhead.com/quest=24562/journey-to-the-sunwell

**What should happen:**
quest should be given after the delivery of the **_Journey To The Sunwell_**

**Other Information:**
whole questline reported @mfranca0009

**Comment by mfranca0009** [comment]
This quest is being given out and available.

**Comment by Echinaceax** [comment]
after fixes of other questlines yes 👍
