### ISSUE TITLE
[Item Quest] Battered Hilt 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5061]
**Links:**

https://cata-twinhead.twinstar.cz/?item=50380
https://cata-twinhead.twinstar.cz/?item=50379

**What is happening:**
- not dropping from any of the correct NPCs (mfranca told me) 

**What should happen:**
all npc loot table need adding

**Comment by mfranca0009** [comment]
After looking, creatures do drop them.
