### ISSUE TITLE
Darrowmire Quest

### ISSUE THREAD

**Issue by dragann99** [WoWManiaUK/Blackwing-Lair#5065]
**Links:**

from WoWHead or our Armory

**What is happening:**
Going to Darrowmire's town square and activating the quest item does nothing

**What should happen:**

**Is it crashing the server?:**
No
**Other Information:**
Despite being in the correct location the quest says missing Darrowmire Town Square

**Comment by Echinaceax** [comment]
need more info 
1.quest name
2.wowhead link to the quest you mean

then we know what to test @dragann99 

edited
https://github.com/WoWManiaUK/Blackwing-Lair/issues/4409
if its the quest then you can type in chat screen **.bq 27390** to complete it yourself
