### ISSUE TITLE
Fiona

### ISSUE THREAD

**Issue by dragann99** [WoWManiaUK/Blackwing-Lair#5066]
**Links:**

from WoWHead or our Armory

**What is happening:**
Fiona the quest giver in Eastern Plague Lands isn't showing up
The mini map shows she is there but the character model isn't anywhere

**What should happen:**

**Is it crashing the server?:**
No
**Other Information:**
Looked all over the general area and still can't seem to find her

**Comment by Echinaceax** [comment]
need more info @dragann99 
need to know the quest name or is it that you want to start the quests from her?
https://wow.gamepedia.com/Fiona

A Gift For Fiona ?
https://wow.gamepedia.com/A_Gift_For_Fiona


@dragann99
Try starting the questline in the correct order, it could be a phasing issue, she is problerbly there just in wrong phase,

i will test it once you give more into

**Comment by Echinaceax** [comment]
tested NO issue finding fiona's first quest 

![1st](https://user-images.githubusercontent.com/39439201/107505920-a6f45500-6b9d-11eb-9e75-3d990e27f00a.jpg)
![2nd](https://user-images.githubusercontent.com/39439201/107505938-aa87dc00-6b9d-11eb-90ca-2748d5ccb4f3.jpg)

**Comment by mfranca0009** [comment]
Most likely talking about the caravan quests, which I believe don't function properly and are out-of-order or messed up due to this.

Could be many different reasons why such as, phasing, caravan transport is messed up, etc. @Echinaceax

**Comment by Echinaceax** [comment]
exactly @mfranca0009 
im on the full questline atm in PTR :p
Fiona is in wrong locations for a lot of quest deliveries
