### ISSUE TITLE
Thrallmar Reputation Vendor Missing Items

### ISSUE THREAD

**Issue by Novaveteran** [WoWManiaUK/Blackwing-Lair#5068]
**Links:**

https://www.wowhead.com/npc=17585/quartermaster-urgronn
Is the same as on other wikis etc.

**What is happening:**

The vendor is missing a bunch of class specific items.

**What should happen:**

It should have the class specific lvl 70 items.

**Is it crashing the server?:**

No.

**Other Information:**

**Comment by Echinaceax** [comment]
Thanks @Novaveteran 
@mfranca0009 compare from here too http://cata.cavernoftime.com/npc=17585

wowhead says (38)
Cavenoftime says (43) this is our amory 

so yes could be more like 43 items needed

**Comment by mfranca0009** [comment]
All set 👍 

3 items no longer needed (ammunition, keys, etc.) have not been added in.

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR
