### ISSUE TITLE
Mor'shan Caravan Pick-Up (Northern Barrens)

### ISSUE THREAD

**Issue by SindraEl** [WoWManiaUK/Blackwing-Lair#5069]
**Links:**
https://www.wowhead.com/quest=29109/morshan-caravan-pick-up#comments
https://wow.gamepedia.com/Mor%27shan_Caravan_Pick-Up

**What is happening:**
You can take the quest from Thork, but when you go to speak with Rocco Whipshank at the northern point of crossroads he is not there, instead he is still at the Grol'dom Farm and if you go speak to him there, still nothing happens

**What should happen:**
When you go to the northern point of crossroads Rocco Whipshank should be there

**Is it crashing the server?:**
No

**Other Information:**
Rocco Whipshanks should be in front of me
![Screenshot (2)](https://user-images.githubusercontent.com/78857015/107533844-440fb780-6bb7-11eb-8a2f-910e90bd95f2.png)

**Comment by Echinaceax** [comment]
Such a detailed report @SindraEl thanks for reporting But 
we already have this reported here #4588
