### ISSUE TITLE
Keepers of Time Reputation Vendor Missing Items

### ISSUE THREAD

**Issue by Novaveteran** [WoWManiaUK/Blackwing-Lair#5071]
Links:

https://www.cavernoftime.com/npc=21643
Is the same as on other wikis etc.

What is happening:

The vendor is missing a bunch of class specific items.

What should happen:

It should have the class specific lvl 70 items.

Is it crashing the server?:

No.

Other Information:

**Comment by mfranca0009** [comment]
All set 👍 

Only item missing is "Key of Time" (30635) because it was removed in Cataclysm expansion (at or before patch 4.2.0).

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 
some items are not seen coz of class specific
though seemd priests see all :P
