### ISSUE TITLE
Scarlet Monastery

### ISSUE THREAD

**Issue by Jowisee** [WoWManiaUK/Blackwing-Lair#5073]
**Links:**

from WoWHead or our Armory

**What is happening:**
Myself and my partner have tried to run through Scarlet Monastery today, however none of the mobs are dropping any loot other than money. We have reset instances both in and out of a party, have cleared our caches manually and through the launcher and I have also spoken to a GM and nothing has worked. The instances work fine solo, but as soon as we are in a party the issue returns. They were working fine yesterday as we ran through them all with another guild member. At this point we have tried everything that we and the GM could think of. 

**What should happen:**
Bosses and mobs should drop loot but are only dropping money

**Is it crashing the server?:**
No

**Other Information:**
Was told to submit by the GM who answered the ticket

**Comment by mfranca0009** [comment]
@Jowisee an update has been applied an hour ago to fix this problem.

Have you tried recently?

**Comment by Jowisee** [comment]
I was speaking to a gm less than half an hour ago, I just finished trying
everything before I posted this issue

**Comment by mfranca0009** [comment]
What was the loot method being used? Group Loot default?

**Comment by Jowisee** [comment]
We tried group loot, free for all and round robin

**Comment by mfranca0009** [comment]
@Jowisee 

Issue was resolved from the update that was done about an hour ago, and it seems you need to leave the current group (if you were in one) and logout. Re-login, and then create a new group.

This is at least the current solution to others that were having this problem after the update went out.
