### ISSUE TITLE
[NPC/Vendor] Earthmender Doros [Deepholm]

### ISSUE THREAD

**Issue by mfranca0009** [WoWManiaUK/Blackwing-Lair#5079]
**Links:**
https://cata-twinhead.twinstar.cz/?npc=45363
https://wow.gamepedia.com/Earthmender_Doros

**What is happening:**
Suppose to be a Repairs NPC, but only shows dialog text when interacting with; no gossip options.

**What should happen:**
Needs to show gossip options and provide a source for repairing items for players. Also, should have a gossip option to where player could go for general supplies AKA Hegrid Blazewing (https://www.wowhead.com/npc=45361/hegrid-blazewing)

**Is it crashing the server?:**
N/A

**Other Information:**

**Comment by mfranca0009** [comment]
Working on this, but need to implement "repair-only" type NPCs... since this NPC doesn't sell anything but only offers repairs.

**Comment by mfranca0009** [comment]
All set 👍

**Comment by golosomie** [comment]
@mfranca0009 Now has a repair option, but his wandering distance seems too large. Can you look into that or should I make another issue?

**Comment by mfranca0009** [comment]
Make new issue, and add tag of low priority @golosomie
