### ISSUE TITLE
[Twilight Highlands] Hortak Kenzo (Tailoring Supplies Vendor) is spawned inside a wall

### ISSUE THREAD

**Issue by golosomie** [WoWManiaUK/Blackwing-Lair#5080]
**Links:**
https://www.wowhead.com/npc=50456/hortak-kenzo

**What is happening:**
Hortak Kenzo (Tailoring Supplies Vendor in Dragonmaw Port, Twilight Highlands) is spawned inside a wall.

**What should happen:**
He should stand next to his buddy Aristaleon Sunweaver.

see screenshot in https://github.com/WoWManiaUK/Blackwing-Lair/issues/3985#issuecomment-778639809

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 👍
