### ISSUE TITLE
[NPC] Orphan Matron Mercy - (issue3) - Children's Week

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5089]
**Links:**
npc - https://www.wowhead.com/npc=22819/orphan-matron-mercy
quest - https://www.wowhead.com/quest=10942/childrens-week

![image](https://user-images.githubusercontent.com/39439201/108263410-87919500-7166-11eb-8ff3-2d29a3eecc05.png)

**What is happening:**
- duplicate quest 
- but when you pick one the other disapears 

**What should happen:**
should only be one per faction

**Comment by mfranca0009** [comment]
I corrected the double quests showing for both Horde and Alliance and two other problems as well:

- [x] Gossip options available when orphan whistle has been lost / deleted to retrieve another.
- [x] Correctly manage two different gossip menus to provide proper NPC text (for Alliance).

You can only see the gossip option to retrieve another whistle if you've completed the first "Children's Week" quest handed-out by Orphan Matron Mercy, if you haven't, then you can simply abandon the quest and re-accept it to get the whistle again.

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 

![image](https://user-images.githubusercontent.com/39439201/108500390-fcbcb180-72af-11eb-8422-e7588a33de54.png)


![image](https://user-images.githubusercontent.com/39439201/108500521-32619a80-72b0-11eb-8d34-28333a3d751e.png)
