### ISSUE TITLE
Coastal Delicacies

### ISSUE THREAD

**Issue by Atheros01** [WoWManiaUK/Blackwing-Lair#5092]
**Links:**

from WoWHead or our Armory

**What is happening:**

**What should happen:**

**Is it crashing the server?:**

**Other Information:**

**Comment by Atheros01** [comment]
https://www.wowhead.com/quest=28146/coastal-delicacies

Attempting to do this quest as a group crashes the server. Checked 3 times to confirm, now reported.

**Comment by Echinaceax** [comment]
thanks @Atheros01 was fixed here #312 

you mean crashed the game client or the server its self ?
will recheck it

**Comment by Echinaceax** [comment]
@mfranca0009 
confirmed server crashes while in group,  player on same quest 
spider confliction

**Comment by mfranca0009** [comment]
I know where the problem is, will have a fix made and tested hopefully by tonight 👍

**Comment by mfranca0009** [comment]
No crash after fix 👍

**Comment by Echinaceax** [comment]
confirmed fixed in dev 
no crash thx :)
