### ISSUE TITLE
Latent Disease (issue2) Suggestion 

### ISSUE THREAD

**Issue by Atheros01** [WoWManiaUK/Blackwing-Lair#5093]
**Links:**
https://www.wowhead.com/quest=26934/latent-disease

**What is happening:**
The needed quest item only spawns in one location in a group of 5, and has a horribly long respawn time

**What should happen:**
Suggest fix for spawn locations and respawn timers, as the quest is basically worthless due to the massive respawn timer and scarcity of said quest item (Plague Tangle)
**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
@mfranca0009 
wow head show 42 https://www.wowhead.com/npc=1815/diseased-black-bear
Twinstar shows 15 https://cata-twinhead.twinstar.cz/?npc=1815
 i will check how many are spawned 

update:

There are 15 spawned atm, yes a little low according to wowhead but same as twinstar, quest completable 
![image](https://user-images.githubusercontent.com/39439201/108498156-c16cb380-72ac-11eb-8c37-8972bbdfe1aa.png)

**Comment by Echinaceax** [comment]
i just did this quest myself and the quest item loots are from around the body , https://gyazo.com/94addd5337f5802c56dfa3fac58bc596

2 bears gave 10/20 quest items so 4 bears gave me quest complete 

no issue here completing the quest 

![image](https://user-images.githubusercontent.com/39439201/108499498-ae5ae300-72ae-11eb-85d7-574e269d0035.png)
