### ISSUE TITLE
[Quest] The Fallen Chieftain - Children's week

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5096]
**Links:**

https://www.wowhead.com/quest=29176/the-fallen-chieftain

from 04:11 https://www.youtube.com/watch?v=VtjYJqPDRI0

**What is happening:**
- nothing happens, no chat dialog 

**What should happen:**
_Take your orphan to Red Rocks to visit the funeral pyre of Cairne Bloodhoof. Call for your orphan if he is not present when you arrive._

  Take Your Orphan to Visit Red Rocks

**Comment by mfranca0009** [comment]
Will start working on this tomorrow.

**Comment by Echinaceax** [comment]
Nice work @mfranca0009 fixed in ptr 

- quest credit given
- npc move and light the fire
- npc text 
- spirit ancestors bow 

![image](https://user-images.githubusercontent.com/39439201/108815382-ace23100-75b4-11eb-80f8-fc41a1b314c7.png)
