### ISSUE TITLE
[Quest] Let's Go Fly a Kite - (ally) - Children's week

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5098]
**Links:**

https://www.wowhead.com/quest=29117/lets-go-fly-a-kite
npc https://www.wowhead.com/npc=52358/craggle-wobbletop
item missing https://www.wowhead.com/item=68890/dragon-kite-2-pack

**What is happening:**
- cant buy the item needed for quest 

**What should happen:**
Purchase a Dragon Kite Two-Pack from Craggle Wobbletop in Stormwind and then use it to fly kites with your Human Orphan. If your orphan is not present, call for him.

	Fly Dragon Kites with your orphan

https://www.wowhead.com/quest=29117/lets-go-fly-a-kite

**Comment by mfranca0009** [comment]
Horde and Alliance toy novelties vendor now sell the proper quest items for Children's Week.

**Comment by Echinaceax** [comment]
Confirmed fixed in DEV
