### ISSUE TITLE
 [Spell] Chakra

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Blackwing-Lair#51]
[[Chakra]](https://wow.gamepedia.com/Chakra) Priest Spell.
**How it should work:**
![image](https://user-images.githubusercontent.com/14857593/38813117-652cb92c-41a3-11e8-8174-35d23bc42fdc.png)
>Description: When activated, your next Heal, Flash Heal, Greater Heal, Binding Heal, Prayer of Healing, Prayer of Mending, Mind Spike or Smite will put you into a Chakra state.

>|CFFFFFFFFSerenity (Heal, Flash Heal, Greater Heal, Binding Heal)|R
>Increases the critical effect chance of your direct healing spells by $81208s1%, and causes your direct heals to refresh the duration of your Renew on the target.

>|CFFFFFFFFSanctuary (Prayer of Healing, Prayer of Mending)|R
>Increases the healing done by your area of effect spells and Renew by $81206s1% and reduces the cooldown of your Circle of Healing by $/1000;81206m2 sec.

>|CFFFFFFFFChastise (Smite, Mind Spike)|R
>Increases your total damage done by Shadow and Holy spells by $81209s1%.

>ToolTip: Your next Heal, Flash Heal, Greater Heal, Binding Heal, Prayer of Healing, Prayer of Mending, Mind Spike or Smite spell will put you into a Chakra state.

**How it works:**
It does not enter you to any chakra state. 
Simply it is not working at all.

**Comment by Keader** [comment]
Damn, this is big...
Working on it.

**Comment by Keader** [comment]
Ok fixed:

- Chakra choice spell.
- Serenity Chakra (renew renovation).
- Chakra of Sanctuary ground heal effect.
- Power Word: Sanctuary
- Chakra Stack
- T11 bonus when Chakra is active.
