### ISSUE TITLE
[NPC] Innkeeper Dreedle <Marshal Expeditions>- Un'Goro Crater

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#510]
NPC - https://www.wowhead.com/npc=38488/innkeeper-dreedle

- Comments by others ppl
- Seems hes not meant to have anything to sell (just checking) 

> I stayed at this inn for 2 days, I agree, no continental breakfast, the whole place, all of one cot, was filthy and stunk like ogre, the innkeeper, very inattentive, had no wares, no minisoaps (or bathroom to boot) or mints on pillows and waking up looking over and seeing ogre ass crack as he lay in foetal position sucking his thumb was very unpleasant, I rate this place no stars at all.

**Comment by Dranah** [comment]
what is the issue here?

**Comment by Echinaceax** [comment]
- Really just checking if its meant to be like this 
- According too the comments it is like this

- so was just double checking if it is meant to be this way (as an inn only) nothing to sell
