### ISSUE TITLE
[Quest] Malfurion Has Returned - Children's week

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5104]
**Links:**

https://cata-twinhead.twinstar.cz/?quest=29107

**What is happening:**
- no trigger
- not completable 

**What should happen:**
_Take your Human Orphan to meet Malfurion Stormrage in the Temple of the Moon in Darnassus. If your orphan is not present when you arrive, call for him._

	Visit Malfurion Stormrage with your orphan

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
fixed in PTR

![image](https://user-images.githubusercontent.com/39439201/108917364-e73ce400-762f-11eb-989d-04a9587f870f.png)
