### ISSUE TITLE
[Quest] A Warden of the Horde - Children's week 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5105]
**Links:**

https://cata-twinhead.twinstar.cz/?quest=5502

**What is happening:**
- After buying the foam sword rack the quest complete but cant deliver back to 

**What should happen:**
Should deliver back 
https://www.wowhead.com/quest=5502/a-warden-of-the-horde#videos:id=123812

**Comment by mfranca0009** [comment]
Correct NPC is properly set for quest ender.

**Comment by Echinaceax** [comment]
confirmed fixed in DEV
