### ISSUE TITLE
[Quest] A Warden of the Alliance - Children's week 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5106]
**Links:**

https://classic.wowhead.com/quest=171/a-warden-of-the-alliance

**What is happening:**
- Quest not offered after completing the other quest needed 

**What should happen:**
should be offered

**Comment by mfranca0009** [comment]
Correct NPC is properly set for quest ender.

**Comment by Echinaceax** [comment]
Confirmed fixed in DEV
