### ISSUE TITLE
Seeds of the Blacksouled Keepers

### ISSUE THREAD

**Issue by Atheros01** [WoWManiaUK/Blackwing-Lair#5107]
**Links:**
https://www.wowhead.com/quest=11319/seeds-of-the-blacksouled-keepers
from WoWHead or our Armory

**What is happening:**

when quest item is used on spore corpse quest credit is not given.

**What should happen:**
the opposite of above statement
**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
thanks for reporting @Atheros01 it was meant to be fixed here #915
I will reopen the other one
