### ISSUE TITLE
[NPC] Coralshell Tortoise/ Coralshell Lurker - skinning 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5109]
**Links:**

https://classic.wowhead.com/item=6352/waterlogged-crate
https://classic.wowhead.com/npc=6352/coralshell-lurker#skinning
https://classic.wowhead.com/npc=6369/coralshell-tortoise#skinning
**What is happening:**
- Waterlogged creates can be skinned from Coralshell Tortoise
4-6 waterlogged-crates each time 

**What should happen:**
need loot table for skinning fixing
waterlogged-crate shouldnt be in the skinning loot table 

**Other Information:**
![waterlogged create2](https://user-images.githubusercontent.com/39439201/109313593-abc93200-7848-11eb-9a0d-043f67648344.jpg)

Also most of the waterlogged-crate are empty

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
confirmed fixed in PTR
