### ISSUE TITLE
Paladin Glyph Seal of Truth bugging.

### ISSUE THREAD

**Issue by Novaveteran** [WoWManiaUK/Blackwing-Lair#5110]
**Links:**

https://i.imgur.com/92AbV8f.jpg
https://i.imgur.com/kqvFgQs.jpg
https://i.imgur.com/wrisKMh.jpeg

**What is happening:**

Glyph of Seal of Truth adds 10 expertise rating once applied.
That works fine.
But once you relog it does not work anymore.
Re applying seems to work.

**What should happen:**

Should just always have 10 extra expertise if using seal of righteousness or truth

**Is it crashing the server?:**

no

**Other Information:**

**Comment by Keader** [comment]
Fixed
