### ISSUE TITLE
Flight Masters Ashenvale

### ISSUE THREAD

**Issue by Atheros01** [WoWManiaUK/Blackwing-Lair#5112]
**Links:**

from WoWHead or our Armory

**What is happening:**

Two of the horde flight masters (that I know of) in Ashenvale don't allow you to depart form them regardless of connected flight paths, as they don't recognize that you have connected flight paths (regardless of personal visits to aforementioned connected flight paths). These Flight masters are at the following locations: Splintertree Post, and Zoram'Gar Outpost. 
Should have posted this before, but I'm doing it now :)

**What should happen:**

**Is it crashing the server?:**

**Other Information:**

**Comment by mfranca0009** [comment]
I think this is a client issue, and the flight path data is missing.

**Comment by Echinaceax** [comment]
this is already reported here https://github.com/WoWManiaUK/Blackwing-Lair/issues/942
thanks for posting tho :)
