### ISSUE TITLE
[Item] Bloated Giant Sunfish and Lightning Eel

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5117]
**Links:**
https://www.wowhead.com/item=13757/lightning-eel
contained in 
https://www.wowhead.com/item=35286/bloated-giant-sunfish
https://cata-twinhead.twinstar.cz/?item=13757#contained-in-item

**What is happening:**
- Seems the Lightning Eel is missing from the fish loot table 
when you fish in Blasted Lands for instance the other fish are working but there is no loot on the Bloated Giant Sunfish and the fishing pole does no error "fish got away" just ...no loot box forBloated Giant Sunfish it loots like

**What should happen:**
fishing should have loot box for Lightning Eel

apparently contained in https://www.wowhead.com/item=13757/lightning-eel
https://www.wowhead.com/item=35286/bloated-giant-sunfish

![image](https://user-images.githubusercontent.com/39439201/110367161-9c679700-8047-11eb-8d90-f87d12eadcb4.png)

**Comment by mfranca0009** [comment]
Should be all set, waiting on confirmation.

**Comment by Echinaceax** [comment]
fix confirmed in PTR for the Lightning Eel

![image](https://user-images.githubusercontent.com/39439201/111086771-6a11da00-851e-11eb-80f9-cd63587f20cd.png)
![image](https://user-images.githubusercontent.com/39439201/111086908-1358d000-851f-11eb-8de5-280c0230f01e.png)
