### ISSUE TITLE
A Mangled journal - Un'Goro Crater

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#512]
- A green mangled journal dropped in Un'goro 
- Cant click to start the quest 
- Cant find a reference about the green one (starts a quest at 48)

**_can only find a link blue one for lvl 100_** 
https://www.wowhead.com/item=122572/mangled-journal

![green](https://user-images.githubusercontent.com/39439201/51079379-3df03980-16c6-11e9-8f04-a3b768c624d5.jpg)

**Comment by Dranah** [comment]
Looks like this item has been removed on cataclysm. Isn't supposed to drop.
