### ISSUE TITLE
And Now, The Moment of Truth

### ISSUE THREAD

**Issue by Atheros01** [WoWManiaUK/Blackwing-Lair#5120]
**Links:**
https://www.wowhead.com/quest=10201/and-now-the-moment-of-truth
from WoWHead or our Armory

**What is happening:**

cannot interact with Grek to have him test out the oil

**What should happen:**
should be able to open dialogue option to have him test the oil
**Is it crashing the server?:**
no
**Other Information:**

**Comment by Echinaceax** [comment]
still has no dialog @Atheros01 hmm
was meant to have been fixed here #696 on my old report 

@mfranca0009  will take a look when he gets to it, thanks @Atheros01 for letting us know :)

**Comment by Echinaceax** [comment]
Tested and confirmed @mfranca0009 

After handing back the quest https://www.wowhead.com/quest=9993/olemba-seed-oil you are given https://www.wowhead.com/quest=10201/and-now-the-moment-of-truth but Grek doesnt have the dialog to test the oil as shown in the video 


video https://www.wowhead.com/quest=10201/and-now-the-moment-of-truth#videos:id=56298

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 

![image](https://user-images.githubusercontent.com/39439201/111084643-bc013280-8513-11eb-8e08-47caad6c12f8.png)

![image](https://user-images.githubusercontent.com/39439201/111084663-de934b80-8513-11eb-9b10-f4ca816d6699.png)
