### ISSUE TITLE
No way back up to Krazzworks

### ISSUE THREAD

**Issue by Atheros01** [WoWManiaUK/Blackwing-Lair#5121]
**Links:**

from WoWHead or our Armory

**What is happening:**
When you get automurdered by trying to use the cannons in the Krazzworks there is no way back up to your body so you have to take rez sickness to revive. this is ass, please fix cannons or add flying mount in death like in wrath content (like in icecrown)

**What should happen:**

**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
which quest is it?
you havent listed @Atheros01

**Comment by Echinaceax** [comment]
Everything but the kitchen sink, works as far as i can see on the main report, i did this quest myself withough issue
https://www.wowhead.com/quest=28589/everything-but-the-kitchen-sink

https://github.com/WoWManiaUK/Blackwing-Lair/issues/4463

Automurdered? by what?
video the guy isnt taking damage https://www.wowhead.com/quest=28589/everything-but-the-kitchen-sink#videos:id=96672


dying isnt a bug, so no additions will be done to this quest

**Comment by Atheros01** [comment]
Not quest, hopped in a krazz cannon and fired it off and promptly died. I
think it's supposed to be used against the elite gryphons.

**Comment by Echinaceax** [comment]
yes the cannons are for the quest 

do you mean that you just randomly jumped on a cannon and died then? @Atheros01 

i'll give it a test lol

**Comment by Atheros01** [comment]
No, fired it and died. I'm kind of fuzzy on the exact details, but I may
have been caught in the blast range and been killed that way.

**Comment by Atheros01** [comment]
Pretty sure I fired into sky though

**Comment by Echinaceax** [comment]
ok i tested it @Atheros01 
and the only time i could kill myself was when i aimed the cannon downwards 😄 
https://gyazo.com/4f859cdd87b321be66cf3f9398f21bae

**Comment by Atheros01** [comment]
must of clipped a piece of terrain or something... oof
