### ISSUE TITLE
quality construction

### ISSUE THREAD

**Issue by Atheros01** [WoWManiaUK/Blackwing-Lair#5122]
**Links:**

from WoWHead or our Armory

**What is happening:**

**What should happen:**

**Is it crashing the server?:**

**Other Information:**

**Comment by Atheros01** [comment]
I cant seem to fix the main part of this issue, dunno why, but here's what's happening. I can use the tape on the quest locations but they dont give quest credit.

**Comment by Echinaceax** [comment]
the item has been report here @Atheros01 #1870
i will close this as its a duplicate
