### ISSUE TITLE
Fervor (hunter talent)

### ISSUE THREAD

**Issue by Atheros01** [WoWManiaUK/Blackwing-Lair#5124]
**Links:**

from WoWHead or our Armory

**What is happening:**

Fervor is an ability picked up from beast mastery talent tree.
when used Fervor isn't restoring any focus to my pet, although it restores my own focus.

**What should happen:**
Should restore 50 focus to both me and pet, as per description

**Is it crashing the server?:**
no
**Other Information:**

**Comment by Echinaceax** [comment]
any reason why you closed your report @Atheros01 ?

**Comment by Atheros01** [comment]
I triple checked the issue and realize that I was suffering from lag

**Comment by Echinaceax** [comment]
Ok, thanks for the info, just wondered if you miss clicked :)
