### ISSUE TITLE
[Spell/Talent] Serpent Spread DOT time to low 

### ISSUE THREAD

**Issue by Schoxxy** [WoWManiaUK/Blackwing-Lair#5127]
**Links:**
http://cata.cavernoftime.com/spell=87934

from WoWHead or our Armory

**What is happening:**
If only skilled once in serpent spread the DOT time of serpent sting is only 4 sec.

**What should happen:**
The DOT time of serpent sting schould be 6 sec.

**Other Information:**
When skilled twice it is all workin fine.

**Comment by Echinaceax** [comment]
confirmed Serpent Spread 1/2 only gives 4secs and not 6secs

**Comment by Keader** [comment]
Fixed.

**Comment by Echinaceax** [comment]
confirmed fixed in PTR
