### ISSUE TITLE
Mimicking Nature's Call

### ISSUE THREAD

**Issue by Atheros01** [WoWManiaUK/Blackwing-Lair#5128]
**Links:**
https://www.wowhead.com/quest=11281/mimicking-natures-call
from WoWHead or our Armory

**What is happening:**

The quest item (Carved Horn) cannot be used, demanding that I use it at "Frozen Waterfall", and refuses to recognize the location when used there. In short the quest cannot be completed due to Carved Horn being bugged.

**What should happen:**
Should sound at location when used there and spawn Yetimus.
**Is it crashing the server?:**
no
**Other Information:**

**Comment by mfranca0009** [comment]
Missing the object trigger which is preventing item to be used, will fix when I get the time.

**Comment by Atheros01** [comment]
Kk

**Comment by Echinaceax** [comment]
this isnt bugged @Atheros01 
ive done this quest a few times on my other chars 

https://www.wowhead.com/quest=11281/mimicking-natures-call#videos:id=62326

just stand with your back at the ice wall then use quest item 


![image](https://user-images.githubusercontent.com/39439201/111464274-d65c2b80-8720-11eb-8a48-6703df9c34e4.png)



![image](https://user-images.githubusercontent.com/39439201/111457101-12d75980-8718-11eb-8029-fbd9a8311649.png)

**Comment by Echinaceax** [comment]
> Missing the object trigger which is preventing item to be used, will fix when I get the time.

trigger isnt missing, maybe it is a little to close to the waterfall (up to you if you want to move the trigger a little) 😄 @mfranca0009 
but the quest is completeable

**Comment by Atheros01** [comment]
Stood literally on the wall and all over the place in front of it. If it
isnt bugged its finicky as all hell.
