### ISSUE TITLE
Death To The Broodmother

### ISSUE THREAD

**Issue by Atheros01** [WoWManiaUK/Blackwing-Lair#5129]
**Links:**
https://www.wowhead.com/quest=25553/death-to-the-broodmother
from WoWHead or our Armory

**What is happening:**

isnt allowing me to place the skull in feeding grounds

**What should happen:**
should be able to place skull and lure mob so i can kill
**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
reported item here #3511 @Atheros01 
remember to search the quest/quest item/npc first before making a new report please
