### ISSUE TITLE
[NPC] Flying npc bug 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5131]
**Links:**

https://gyazo.com/d465e6843d6260ae1412a2c8807f0a35 
https://gyazo.com/3c330b180625e019d115281313ded18c 
https://gyazo.com/e7bdb9cfdc5509f14949da6871b6836f 
https://gyazo.com/ded72cb8f0548bc9a6bcdafaeb3dca6a 
https://gyazo.com/602cb9d33f1619327b7ddffabbf6188a

**Whats happening**
Something has happend to the flying movement of some flight npcs 

**What should happen** 
all flying npc should be smooth flying without jumping and glitching 

**Extra info**
Could be related to recent fixes ...not sure which tho @mfranca0009 they wasnt like this before

**Comment by Lumber-Jack-2** [comment]
is good now again

**Comment by Echinaceax** [comment]
confirmed fixed in PTR thanks @Rushor ❤️
