### ISSUE TITLE
[Quest/item] Clean" Beast Guts - Silverpine Forest

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5138]
**Links:**
quest item https://www.wowhead.com/item=60742/clean-beast-guts
quest https://www.wowhead.com/quest=26995/guts-and-gore

https://www.wowhead.com/npc=1778/ferocious-grizzled-bear
https://www.wowhead.com/npc=1765/worg

**What is happening:**
- quest item not dropping 
from bears and worg

**What should happen:**
_Recover 6 "Clean" Beast Guts._

**Other Information:**
https://www.wowhead.com/quest=26995/guts-and-gore#videos:id=37370

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
confirmed fixed in ptr
