### ISSUE TITLE
[NPC] Deathstalker Rane Yorick cutscene (missing) - Silverpine Forest

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5140]
**Links:**

quest https://www.wowhead.com/quest=27045/waiting-to-exsanguinate

**What is happening:**

- [x]  no Deathstalker Rane Yorick spawns for me after picking up the quest 
- [x] npc text 
- [x] cant hide in Armoire 
- [x]  cutscene missing 
- [x] cant complete the quest 
- [x] grouped members camera (**still to work on**)

**notes** 

Deathstalker Rane Yorick https://www.wow-freakz.com/spells.php?spell=83751&name=summon-deathstalker-yorick
summoning hide spot https://www.wow-freakz.com/npc_finder.php?npc=44893&name=armoire
hide spell  https://www.wow-freakz.com/spells.php?spell=83788&name=hide-in-armoire
cutscene https://www.wow-freakz.com/spells.php?spell=83762&name=summon-crowley-bloodfang-master

**What should happen:**

_Enter the Ivar Cottage and find a suitable hiding place upstairs. Then eavesdrop on Lord Darius Crowley._
https://www.wowhead.com/quest=27045/waiting-to-exsanguinate#videos:id=37392

**Comment by mfranca0009** [comment]
All the major issues have been fixed, but needing to clean-up and add detail to it, hopefully finishing it off tomorrow 👍

**Comment by Echinaceax** [comment]
- [ ] grouped members camera 
still to work on

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
confirm all fixed in PTR :)
