### ISSUE TITLE
[NPC] Admiral Hatchet (phasing) - Silverpine Forest

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5142]
**Links:**

https://www.wowhead.com/npc=44916/admiral-hatchet

**What is happening:**
- npc cant be seen by players (only GMs)

**What should happen:**
needs phasing to allow players to see them

quest delivery https://www.wowhead.com/quest=27065/the-warchiefs-fleet

![image](https://user-images.githubusercontent.com/39439201/120081852-e2208280-c0bf-11eb-9431-cebd277fd0a2.png)

![image](https://user-images.githubusercontent.com/39439201/120081872-febcba80-c0bf-11eb-873a-0a262675a9ae.png)

**Comment by mfranca0009** [comment]
Fixed 👍

**Comment by Echinaceax** [comment]
Applied on live
