### ISSUE TITLE
[NPC] Warlord Torok (phasing) - Silverpine Forest

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5143]
**Links:**

https://www.wowhead.com/npc=44917/warlord-torok

**What is happening:**
- npc cant be seen by players (only by GMs) 

**What should happen:**
should be seen by players

**for quests** 
Give 'em Hell!
Hair of the Dog
Skitterweb Menace

Deeper into Darkness (auto accept)

**Comment by mfranca0009** [comment]
fixed 👍

**Comment by Echinaceax** [comment]
Applied on live
