### ISSUE TITLE
[NPC] Forward Commander Onslaught - Ruins of Gilneas

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5153]
**Links:**

https://www.wowhead.com/npc=45315/forward-commander-onslaught

**What is happening:**

- [x] missing npc 

**What should happen:**
should be spawned for quest 
https://www.wowhead.com/quest=27333/losing-ground
https://www.wowhead.com/quest=27345/the-f-c-d
https://www.wowhead.com/quest=27349/break-in-communications-dreadwatch-outpost
https://www.wowhead.com/quest=27350/break-in-communications-rutsaks-guard

Note
info here, TWINSTAR says Gilneas
and wowwiki says and there are no mobs during the worgen starting experience.

https://cata-twinhead.twinstar.cz/?npc=45315
https://wowwiki-archive.fandom.com/wiki/Northgate_Woods

https://wowpedia.fandom.com/wiki/Losing_Ground_(Ruins_of_Gilneas)

![image](https://user-images.githubusercontent.com/39439201/115020711-3e866480-9ebb-11eb-809f-47451b6800a5.png)

not a worgen quest its a silverpine questline

**Comment by Echinaceax** [comment]
confirmed fixed in ptr 

![image](https://user-images.githubusercontent.com/39439201/120043491-5dc0f780-c00c-11eb-8199-31c21ef21087.png)

**Comment by Echinaceax** [comment]
NPC is missing again @mfranca0009 
may be due to current fixes 

After delivering forsaken-forward-command quest 
(player is on the quest https://www.wowhead.com/quest=27290/to-forsaken-forward-command )
they go to forsaken forward command to deliver quest back with Arthura flying the player there 

https://www.wowhead.com/npc=45315/forward-commander-onslaught should be here too pick up 2 quests 

https://www.wowhead.com/quest=27333/losing-ground
https://www.wowhead.com/quest=27345/the-f-c-d

**Comment by mfranca0009** [comment]
Was in the wrong location, I updated it

**Comment by Echinaceax** [comment]
confirmed relocated to correct position 

![image](https://user-images.githubusercontent.com/39439201/122087982-9da61e00-ce05-11eb-815e-04949b5f6bc2.png)
