### ISSUE TITLE
[Item] Heirloom Auto-unequip / equipment issue

### ISSUE THREAD

**Issue by Novaveteran** [WoWManiaUK/Blackwing-Lair#5159]
**Links:**

https://www.wowhead.com/heirloom-guide#about-heirlooms

**What is happening:**

Currently heirloom items become unequipped after their scale limit, for example lvl 80.
so lvling a rogue, using 2 heirloom weapons, I log out at 81 after some lvling. Log back in, to find i no longer have weapons, they are in my mailbox. I collect them, can't equip them.

**What should happen:**

Should still be able to use any heirloom no matter the max lvl. It just stops scaling at that certain lvl, and experience bonus should no longer work. But should still be equippable.

**Is it crashing the server?:**

no

**Other Information:**

**Comment by Echinaceax** [comment]
these heirlooms i believe @wow-mania 

https://wowwiki-archive.fandom.com/wiki/Balanced_Heartseeker
http://cata.cavernoftime.com/item=42944

note @wow-mania  that all heirlooms 1-80 automatically unquip when player hits 81 and logs out

**Comment by Novaveteran** [comment]
Yeah any lvl 80 heirloom should still be usable even at lvl 85, they just stop scaling at 80, and exp bonus no longer working

**Comment by Echinaceax** [comment]
@wow-mania We have found no evidence that 1-80 looms should automatically unquip when player hits81 and logs out 
they should remain on the player (without bonuses ofc) until the player can replace their looms with dungeon loot or quest rewards 

http://cata.cavernoftime.com/item=42946
http://cata.cavernoftime.com/item=42985
http://cata.cavernoftime.com/item=48691
http://cata.cavernoftime.com/item=42944
http://cata.cavernoftime.com/item=48687
http://cata.cavernoftime.com/item=42984
http://cata.cavernoftime.com/item=42952
http://cata.cavernoftime.com/item=48689
http://cata.cavernoftime.com/item=42950
http://cata.cavernoftime.com/item=48677
http://cata.cavernoftime.com/item=42951
http://cata.cavernoftime.com/item=48683
http://cata.cavernoftime.com/item=42992
http://cata.cavernoftime.com/item=42991
http://cata.cavernoftime.com/item=42948
http://cata.cavernoftime.com/item=48716
http://cata.cavernoftime.com/item=42945
http://cata.cavernoftime.com/item=48685
http://cata.cavernoftime.com/item=42949
http://cata.cavernoftime.com/item=42947
http://cata.cavernoftime.com/item=42943
http://cata.cavernoftime.com/item=48718

**Comment by Novaveteran** [comment]
I don't know what to say other than that it is a fact haha, been playing almost daily since early 2005. I made a retail support ticket as to fortify my claim, but it is a fact you can equip them even if you are 500, i am waiting for the ticket reaponse.

**Comment by Keader** [comment]
fixed
