### ISSUE TITLE
[Quest] The Bait for Lar'korwi - ID 24733 - Un'Goro Crater

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#516]
Quest - https://www.wowhead.com/quest=4292/the-bait-for-larkorwi
npc - https://www.wowhead.com/npc=9619/torwa-pathfinder
Provided - https://www.wowhead.com/item=11568/torwas-pouch
Item1 - https://www.wowhead.com/item=11570/preserved-pheromone-mixture
Item2 - https://www.wowhead.com/item=11569/preserved-threshadon-meat

- went to flat rock 
- tried every possible position on/off / side of rock nothing worked 
- Cant complete

**got error message**  
_Requires flat Un'Goro rock_ 

![flat rock](https://user-images.githubusercontent.com/39439201/51080062-2ec4b800-16d5-11e9-893a-6647544927f7.jpg)

**Comment by Dranah** [comment]
This quest has been redesigned since LK. The correct quest ID on cataclysm is 24933.

**Comment by Rushor** [comment]
http://cata.cavernoftime.com/quest=24733

**Comment by Rushor** [comment]
works now

![I](https://i.imgur.com/GXMQ6Qg.jpg)
![I](https://i.imgur.com/zB2O9Ts.jpg)

**Comment by jarvik76** [comment]
When does this normally hit prod?  If it should already have done, I think it may still be bugged.  The timing is not clear though.

**Comment by Rushor** [comment]
the object was removed. will refix

**Comment by rzenne** [comment]
Doesn't appear to be working again.  you place the meat but when you try to use preserved-pheromone-mixture it keeps saying you need the meat. after watching video if appears the meat is not being placed on the rock which is why mixture doesn't work.
