### ISSUE TITLE
[Talent/Hunter] Posthaste

### ISSUE THREAD

**Issue by Maxe1807** [WoWManiaUK/Blackwing-Lair#5169]
**What is happening** 
Hello i'm playing a Marksmanship hunter and the talent http://prntscr.com/1148xvz dosent work because if i use Disengage does this happen https://prnt.sc/113xbva   with friendly greetings Max

**What should happen**
Posthaste 
https://cata-twinhead.twinstar.cz/?spell=83558
https://cata-twinhead.twinstar.cz/?spell=83560

![image](https://user-images.githubusercontent.com/39439201/113521925-00c13c00-959d-11eb-803a-932b9fc055b8.png)
![image](https://user-images.githubusercontent.com/39439201/113521939-1898c000-959d-11eb-84ac-cde1ede2b532.png)

**Comment by Echinaceax** [comment]
Posthaste https://cata-twinhead.twinstar.cz/?spell=83558

**Comment by Keader** [comment]
fixed

**Comment by Echinaceax** [comment]
Fixed in dev 

![image](https://user-images.githubusercontent.com/39439201/113843100-9a523e80-9793-11eb-94a8-b680a0508b33.png)
