### ISSUE TITLE
[NPC] Overseer Oilfist - phasing issue - Searing Gorge

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#518]
NPC -https://www.wowhead.com/npc=14625/overseer-oilfist
His missing from his locations in searing gorge
#474 
The above quest is displayed on the mini map with a question mark but he cannot be located.

**Comment by Echinaceax** [comment]
**Exactly what i saw too...hes question mark is there but cant locate him** 

![oilfist](https://user-images.githubusercontent.com/39439201/51086207-0fb13f00-1744-11e9-8ed8-ff9b353f050e.jpg)

**Comment by gantor2** [comment]
This may help, check if you did these two quests mentioned, he may be phased ![Image](https://i.imgur.com/3cjcSWq.jpg)

**Comment by sarahkay88** [comment]
both those quest were completed they were part of the opening quest in the area.

**Comment by Echinaceax** [comment]
i reported that https://www.wowhead.com/quest=27964/dig-boss-dinwhisker

**Comment by Dranah** [comment]
The NPC is there, but phased.
However even if you complete the entire chain in correct order, you still won't be able to see him, he's simply in the wrong phase. (I did it with .q add and .q complete)
