### ISSUE TITLE
[QUEST] Recon Essential's -ID 27977- Searing Gorge

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#519]
**Quest** - https://www.wowhead.com/quest=27977/recon-essentials
**NPC** - https://www.wowhead.com/npc=14626
I can complete the first half of this quest by collecting : itemhttps://www.wowhead.com/item=18959
**NPC** - https://www.wowhead.com/npc=8566/dark-iron-lookout
**NPC** -  https://www.wowhead.com/npc=5840/dark-iron-steamsmith
However I am unable to find the item: https://www.wowhead.com/item=18960 
**I think this is because I cant locate the dark iron lookout NPC's.**

**Comment by zippoking** [comment]
The  Dark Iron Lookout NPC´s are available now. 
I just finished the Quest.

![Recon Essentials is fixed](https://user-images.githubusercontent.com/18005338/58496054-59da1080-8179-11e9-872d-e3555038d584.PNG)

**Comment by Rushor** [comment]
closing
