### ISSUE TITLE
[Spell]  Inner Focus

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Blackwing-Lair#52]
![image](https://user-images.githubusercontent.com/14857593/38849013-73e91970-421f-11e8-854a-543039c98196.png)
ID:89485
**How it should work:**
>Description: Reduces the mana cost of your next Flash Heal, Binding Heal, Greater Heal or Prayer of Healing by $s1% and increases its critical effect chance by $s2%.

>ToolTip: Mana cost of your next Flash Heal, Binding Heal, Greater Heal or Prayer of Healing reduced by $s1% and critical effect chance increased by $s2%.

**How it works:**
The effect is not fading on use of the spells named in tooltip.

**Comment by Keader** [comment]
Fixed.
Janitor should tell when it's up to test.
