### ISSUE TITLE
[NPC] John J. Keeshan - Missing - Burning Steppes & Redridge Mountains

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#520]
NPC - https://www.wowhead.com/npc=47811/john-j-keeshan
Quest -  https://www.wowhead.com/quest=28666/heros-call-burning-steppes
Unable to locate NPC so cannot complete the hero call quest.

**Comment by Dranah** [comment]
Completely missing from position at Flamestar Post:
Map: 0 (Eastern Kingdoms) Zone: 46 (Burning Steppes) Area: 5651 (Flamestar Post)
X: -8062.680176 Y: -999.831970 Z: 131.720993 Orientation: 4.014260

**Comment by sarahkay88** [comment]
Also missing from his location in the Lakeshire inn red ridge so unable to hand in https://www.wowhead.com/quest=26607/they-drew-first-blood
