### ISSUE TITLE
[NPC] Lady Sylvanas Windrunner - 45617 - (missing) - Silverpine Forest

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5200]
**Links:**

https://www.wowhead.com/npc=45617/lady-sylvanas-windrunner

**What is happening:**
- missing for quest pickups and delivery

**What should happen:**
needs spawning

**Comment by Echinaceax** [comment]
- [x] spawned in ptr
- [ ] (phasing) for her not fixed 

atm 45617 and 45525 are visible at the same time 

@mfranca0009 
what me to make new report for phasing?

**Comment by mfranca0009** [comment]
Yes, all phasing issues are being fixed last and all at once.

**Comment by Echinaceax** [comment]
> Yes, all phasing issues are being fixed last and all at once.

okidoki, cool. thanks @mfranca0009 :)
