### ISSUE TITLE
[Quest/npcs] Lessons in Fear - (missing 7th Legion Scout) - Silverpine Forest

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5207]
**Links:**

https://www.wowhead.com/npc=45883/7th-legion-scout
https://www.wowhead.com/npc=45882/forsaken-vanguard

**What is happening:**
- missing burning buildings
- 7th Legion Scout missing 
- missing dead forsaken vanguard

**What should happen:**
need 21 spawns

https://www.wowhead.com/quest=27548/lessons-in-fear

**Comment by mfranca0009** [comment]
Per the video, no buildings are on fire and there are already burnt buildings within this village.

Added the cowering troopers, 7th legion scouts, and dead forsaken vanguards.

**Comment by Echinaceax** [comment]
fixed in ptr
