### ISSUE TITLE
[NPC] Dwarven Infantry / General Marstone (missing) - Silverpine Forest

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5210]
**Links:**

https://www.wowhead.com/npc=45855/dwarven-infantry
https://www.wowhead.com/npc=45995/general-marstone

**What is happening:**

- [x] Dwarven Infantry missing (27)
- [x] General Marstone missing
- [ ] missing quest giver #5206

**What should happen:**
need spawning for https://www.wowhead.com/quest=27577/7th-legion-battle-plans

**Comment by mfranca0009** [comment]
Dwarven Infantry and General Marstone spawned. The quest giver is its own issue.
