### ISSUE TITLE
[UI] Can Sign Up to locked Guild Events 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5216]
### Tested this on PTR 

**What is Happening:**
Guild members can sign up to guild events that have been locked by the event moderator.

**What Should happen:**
There shouldn't be an option to sign up or an error should show.

**Steps to replicate:**
Create a guild event in the future
Lock the event on the character that created it and update
Log a different character in the same guild
Open calendar and right-click the event
Click Sign Up

Thanks to hawker357 (Mania tester) for this info 😄 

Confirmed same here too

![locked1](https://user-images.githubusercontent.com/39439201/116239806-600d0900-a763-11eb-9715-e120eddb5aff.jpg)
![locked 2](https://user-images.githubusercontent.com/39439201/116239605-22a87b80-a763-11eb-96d1-d7c0967a36cf.jpg)
![locked3](https://user-images.githubusercontent.com/39439201/116239612-24723f00-a763-11eb-951a-1d5278e57916.jpg)

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
confirmed fixed in ptr
