### ISSUE TITLE
[Spell/Warlock] Soul fire / Decimation OP proc bug 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#522]
- Noticed a problem with Soul fire (refreshing Decimation) constantly
- 1 Soul Fire procs Decimation 
- Decimation procs always, no rotation needed, 1 soul fire is all is needed

**soul fire spell**

![soulfire](https://user-images.githubusercontent.com/39439201/51087036-3bd1bd80-174e-11e9-85f0-38ab834d7212.jpg)

**Decimation talent**

![decimation](https://user-images.githubusercontent.com/39439201/51087044-5b68e600-174e-11e9-9799-f14b66d4cb7a.jpg)

![soul fire proccs refresh constanly](https://user-images.githubusercontent.com/39439201/51087048-691e6b80-174e-11e9-8bbe-13063e4c6e63.jpg)

**Comment by Dranah** [comment]
That's how this spell is supposed to work. Notice tooltip says Soul Fire is also eligible to proc it.
In execute phase, you just spam Soul Fire. Yes it's also OP for leveling so long as you can keep mobs faster than the decimation duration.

**Comment by Echinaceax** [comment]
yes but the decimation duration refreshes over and over if you have mulipule mobs around.
eg: i can get the decimation down to 1sec then pop it again for 9secs over and over

**Comment by Dranah** [comment]
Yes, that's how warlock execute works. Already on wotlk as well.

**Comment by Echinaceax** [comment]
wow , so OP defo ..thx Dranah
