### ISSUE TITLE
[Quest] Fletch Me Some Plumage - ID 14253 - Desolace

### ISSUE THREAD

**Issue by gantor2** [WoWManiaUK/Blackwing-Lair#523]
- Cannot complete due to enemies not dropping completion materials.
- NPC - ID 4692
- Item ID - 49032
- https://www.wowhead.com/quest=14253/fletch-me-some-plumage

**Comment by Kitzunu** [comment]
so what new can we write here.....

I guess nothing, Fixed will send later
