### ISSUE TITLE
[Item/Reward] Titanium Seal of Dalaran 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5232]
**Links:**

Titanium Seal of Dalaran https://www.wowhead.com/item=44430/titanium-seal-of-dalaran 
missing from the achv https://cata-twinhead.twinstar.cz/?achievement=2096

**What is happening:**
- item wasnt given after completing the achv 

**What should happen:**
After you complete The Coin Master achv, you are meant to receive the Titanium Seal of Dalaran

![the coin master](https://user-images.githubusercontent.com/39439201/119241996-ba2e9d80-bb5a-11eb-82b1-b794b89cb7a9.jpg)
![no loot reward](https://user-images.githubusercontent.com/39439201/119242011-d0d4f480-bb5a-11eb-8ef9-0403f73dc830.jpg)

**Comment by golosomie** [comment]
This is supposed to get sent via mail. Maybe wait some time and it might appear?

**Comment by Echinaceax** [comment]
> This is supposed to get sent via mail. Maybe wait some time and it might appear?

oh nice to know @golosomie 😄 got it 


![image](https://user-images.githubusercontent.com/39439201/119242103-ad5e7980-bb5b-11eb-9a99-7d9830f0d180.png)
