### ISSUE TITLE
 [It's All Fun and Games] Icecrown

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#5234]
https://www.wowhead.com/quest=12887/its-all-fun-and-games#comments
Icecrown 

U cant target the eye and kill it

You'r suppose to be able to target it and kill it

**Comment by Echinaceax** [comment]
@Saintres you can ive done this quest a few times
just go close to it and use the quest item Eyesore Blaster

![image](https://user-images.githubusercontent.com/39439201/119401720-2b498e80-bcdc-11eb-9181-03c0cf3bf34d.png)

Slight object bug tho @mfranca0009 
target is a game marker not the actually invis marker 

https://www.wowhead.com/quest=12887/its-all-fun-and-games#videos:id=73596
