### ISSUE TITLE
[Item/crash] Seafood Magnifique Feast - server crash

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5236]
**Links:**

https://www.wowhead.com/spell=88036/seafood-magnifique-feast

**What is happening:**
Tonight we noticed the feast crash the server now raid and in dungeons 
tested this 3 times and crashed 3 times

also confirmed crash on PTR 

**What should happen:**
Placing a feast shouldnt crash the server

**Is it crashing the server?:**
yes

**Other Information:**
Odd because our guild has used the Feasts many times...
so this is a new thing 

**Repro steps** 
1. learn cooking
2. add 88036
3. place a feast

BAM crash

**Comment by mfranca0009** [comment]
Crashes on gameobject use, the spell to make one and placing the feast is fine.

Looking into it

**Comment by mfranca0009** [comment]
Problematic spell causing the crash: https://www.wowhead.com/spell=87806/seafood-magnifique-feast

**Comment by Echinaceax** [comment]
> Problematic spell causing the crash: https://www.wowhead.com/spell=87806/seafood-magnifique-feast

Keader will take a look @mfranca0009

**Comment by mfranca0009** [comment]
**More information:**
Casting this directly via command without the triggered attribute works fine, but when you try to use the gameobject with this specific spell (87806) it will immediately crash the server.

I've tested swapping other spells similar to this one for the gameobject, no crash is present and works fine. Other SPELLCASTER gameobject types work as intended that act the same way with no crash:

- Goblin Barbecue
- Broiled Dragon Feast
- Refreshment Tables

**Comment by Keader** [comment]
work today fucked with me.
i will check it tomorrow night

**Comment by mfranca0009** [comment]
Thanks Keader, appreciate it ❤ @Keader

**Comment by Lumber-Jack-2** [comment]
seems fixed https://i.imgur.com/OoQq88R.jpeg all handled in spellscript now

**Comment by Echinaceax** [comment]
thanks @Rushor 
confirmed fixed in PTR (no crash)

![image](https://user-images.githubusercontent.com/39439201/120113669-ce3a5680-c17b-11eb-817e-68d418cf33bb.png)
![image](https://user-images.githubusercontent.com/39439201/120113727-178aa600-c17c-11eb-82a4-09eea097fc2e.png)
