### ISSUE TITLE
[Quest] Warchief's Command: Silverpine Forest!

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5241]
**Links:**

https://cata-twinhead.twinstar.cz/?quest=28568

**What is happening:**
- quest missing

**What should happen:**
quest should be at the Warchief's Command board in Undercity at level 10 and at  NPC Executor Zygand in Brill at level 10

**Comment by Echinaceax** [comment]
### Update 
This quest is only available after completing Take to the Skies https://cata-twinhead.twinstar.cz/?quest=25012
quest can be picked up by the war board or npc Executor Zygand https://cata-twinhead.twinstar.cz/?npc=1515

- [ ] should be available at level 9-10 
(_no prequest requirements as all horde races can do the Silverpine questline_)

![image](https://user-images.githubusercontent.com/39439201/120080182-f19bcd80-c0b7-11eb-8fbc-908afe978703.png)

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
confirmed fixed in ptr 

![image](https://user-images.githubusercontent.com/39439201/120392151-5d886b00-c330-11eb-91a1-b3caee37180e.png)
![image](https://user-images.githubusercontent.com/39439201/120392252-86106500-c330-11eb-86e5-fee0fc2c3c59.png)

not available if already picked up via the Brill npc Executor Zygand

![image](https://user-images.githubusercontent.com/39439201/120392610-08008e00-c331-11eb-8c68-ee0e7dc7b875.png)
