### ISSUE TITLE
[NPC] Bat Handler Maggotbreath - Silverpine 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5242]
**Links:**

npc https://www.wowhead.com/npc=44825/bat-handler-maggotbreath
quest https://www.wowhead.com/quest=26998/iterating-upon-success

**What is happening:**
- bat handler is missing dialog to use the bat for the quest 

**What should happen:**
 
- [x] Bat requisitioned from Bat Handler Maggotbreath
- [x] Full scripted done
- [x] Vile Fin Murloc slain  (50)

https://www.wowhead.com/quest=26998/iterating-upon-success#videos:id=37377

**extra info**

player can manually kill 50 Vile Fin Murloc slain BUT as the quest require to have used the bat the _Bat requisitioned from Bat Handler Maggotbreath_ quest cant be completed

**Comment by mfranca0009** [comment]
Should be all set, any waypoint tweaking needs to be done after implementing smooth waypoint pathing into the core 👍

**Comment by Echinaceax** [comment]
- [x] Full scripted done
- [x] Confirmed single player
- [x] Confirmed group
