### ISSUE TITLE
Flight paths missing from Zoram'gar Outpost [Ashenvale]

### ISSUE THREAD

**Issue by golosomie** [WoWManiaUK/Blackwing-Lair#5258]
Flight path data is missing for the horde flight master [Andruk](https://www.wowhead.com/npc=11901/andruk).
Players can take flights towards the flight master, but fly from Zoram'gar Outpost.

This is likely a client issue (as pointed out my @mfranca0009 [here](https://github.com/WoWManiaUK/Blackwing-Lair/issues/5112#issuecomment-787705212). Below is a list of flight points that should be available from Zoram'gar Outpost:

- Hellscream's Watch, Ashenvale
- Splintertree Post, Ashenvale
- The Crossroads, Northern Barrens
- Cliffwalker Post, Stonetalon Mountains
- Sun Rock Retreat, Stonetalon Mountains
- Thunder Bluff
- Emerald Sanctuary, Felwood

**Comment by mfranca0009** [comment]
@golosomie 
Wouldn't this be the same problem as #942 or do these two flight master NPCs have different flight path points and not the same?

**Comment by Echinaceax** [comment]
@mfranca0009 yes i believe so, but will wait till @golosomie replies
he added same list to the other report https://github.com/WoWManiaUK/Blackwing-Lair/issues/942#issuecomment-866811718

**Comment by Echinaceax** [comment]
renamed #942  for the full broken fightpaths for Ashenvale
closing this,  fixes will be done from orginal report
