### ISSUE TITLE
Haste bug death knight blood

### ISSUE THREAD

**Issue by andresexe92** [WoWManiaUK/Blackwing-Lair#5264]
**Links:**

from WoWHead or our Armory

**What is happening:**
a) Death King with blood talents has a haste of 20%.

b) With the same talents blood unholy presence change and haste decreases.

**What should happen:**
a) It should appear with a haste of 0% and increase according to the items that have haste on my team.

b) It should increase haste, but it goes from 20% to 10%. The opposite effect

**Is it crashing the server?:**
No, but it makes raids and PVP for the DK blood very easy

**Other Information:**

https://youtu.be/CgO1CHF4lt4?t=365
Watching this video in this one at minute 6:05 I see that the DK tank takes no damage compared to the rest of the team, even though I'm tackling Alfus in Heroic mode, it should be second in damage taken. since the first would be the PALADIN tank. But I come in last due to the haste that provides me with many lethal blows and a continuous damage absorption shield.

In the same minute, the haste can be seen at +21.14. This is bad since I don't have any items on my team that provide haste.

**Comment by Echinaceax** [comment]
@andresexe92 Can you provide linked evidence behind what you're stating here?

**Comment by golosomie** [comment]
@Echinaceax I can confirm that the Blood Talent "Improved Blood Presence" (Spell 50371) does grant not only +20% rune generation but also +20% haste.

The talent should not grant haste. Activating Unholy Presence correctly overwrites the player's haste.

**Comment by Echinaceax** [comment]
@mfranca0009 
any thing else you need ?

https://cata-twinhead.twinstar.cz/?spell=50371  /  http://cata.cavernoftime.com/spell=50371
![image](https://user-images.githubusercontent.com/39439201/124163933-6dff4300-daa0-11eb-84ad-946ea92868fc.png)

Blood haste 

![blood](https://user-images.githubusercontent.com/39439201/124164837-7310c200-daa1-11eb-847b-9a561d821a5b.jpg)


Frost haste
 
![frost](https://user-images.githubusercontent.com/39439201/124164856-7ad06680-daa1-11eb-9405-950bf9f7ef88.jpg)


Unholy haste 

![unholy](https://user-images.githubusercontent.com/39439201/124164888-81f77480-daa1-11eb-9976-6ad189e4dd9f.jpg)

**Comment by golosomie** [comment]
Confirmed fixed in dev. All ranks of the talent + all presences grant the correct haste and rune regeneration values.

**Comment by mfranca0009** [comment]
Fixed in Live 👍
