### ISSUE TITLE
[NPC] Doreen - Un'Goro Crater

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#527]
NPC - https://www.wowhead.com/npc=38277/doreen
NPC - https://www.wowhead.com/npc=38276/tara
NPC - https://www.wowhead.com/npc=38275/gremix

- All 3 NPCs dont stop moving to give back or pick up quests 
- If you click on Gremix they all stop, if you click on Doreen or Tara they dont.
- NPCs need to stop when clicked

![stop walking](https://user-images.githubusercontent.com/39439201/51087850-d1724a80-1758-11e9-98eb-4c56b6723325.jpg)

**Comment by Rushor** [comment]
generic issue with npcs and waypoint data pathing system
