### ISSUE TITLE
Missing Quest - All's Well (13924) - Ashenvale

### ISSUE THREAD

**Issue by ssmilazzo** [WoWManiaUK/Blackwing-Lair#5270]
**Links:**

https://www.wowhead.com/quest=13924/alls-well

**What is happening:**
Quest is not offered.

**What should happen:**
Upon completion of "In the Hands of the Perverse" (13922), The quest giver "Averus Illwhisper" (34335) sacrifices himself and the five "Fallen Moonstone" needed to complete the quest are deleted.  He then becomes "Averus the Redeemed" (34358) and offers the quest "All's Well" (13924). Upon acceptance you are given "Sanctified Moonstones" to turn in to "Pelturas Whitemoon" (3894) which ends the quest chain to cure Relara Whitemoon of her sickness.
**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
thanks @ssmilazzo

**Comment by Echinaceax** [comment]
bug confirmed 
Once player delivers the quest "In the Hands of the Perverse" (13922) as stated for @ssmilazzo 
https://www.wowhead.com/quest=13922/in-the-hands-of-the-perverse#videos:id=48377 

no sacrifice is made when you deliever the quest, and cant pick up https://www.wowhead.com/quest=13924/alls-well

**Comment by mfranca0009** [comment]
All set 👍, the transformation from Avrus Illwhisper to Avrus the Redeemed takes place and you are now able to pick up All's Well.

**Comment by Echinaceax** [comment]
confirmed fixed in PTR
