### ISSUE TITLE
Missing quests "Clear the Shrine" (13985) and "The Last Stand" (13987) - Ashenvale

### ISSUE THREAD

**Issue by ssmilazzo** [WoWManiaUK/Blackwing-Lair#5271]
**Links:**

https://www.wowhead.com/quest=13985/clear-the-shrine

**What is happening:**

Quest is not offered.

**What should happen:**

Upon completion of "In a Bind" (13982) the quest giver "Bolyun" (3698) should offer "Clear the Shrine" (13985). This is turned in to "Big Baobob" (34604) who then offers "The Last Stand" (13987) and this ends a three part chain that starts with "Check in on the Edunes" (13965).

**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
confirmed bugged, no other quests are offered after completing https://www.wowhead.com/quest=13982/in-a-bind
https://www.wowhead.com/quest=13982/in-a-bind#videos:id=48336

**Comment by mfranca0009** [comment]
Should be all set, properly phases the player to next stage ✔️

**Comment by Echinaceax** [comment]
confirmed fixed in PTR  

![image](https://user-images.githubusercontent.com/39439201/124660381-6d065100-dea6-11eb-8baa-15e03d933360.png)

and follow up quest also there 

![image](https://user-images.githubusercontent.com/39439201/124660495-90c99700-dea6-11eb-948e-cf7ace0c3fb9.png)
