### ISSUE TITLE
Quest - Defend the Tree (13935)

### ISSUE THREAD

**Issue by ssmilazzo** [WoWManiaUK/Blackwing-Lair#5273]
**Links:**

https://github.com/WoWManiaUK/Blackwing-Lair/issues/4529

**What is happening:**

I don't want to create a duplicate here. This doesn't appear to have ever been looked at. Any chance of adding this to the .BQ Command?

**What should happen:**

**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
Will add  #4529 to BG command 
thx @ssmilazzo

**Comment by ssmilazzo** [comment]
Amazing. Thank you.
