### ISSUE TITLE
[Item] Glyph of Dazing Shield

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5274]
### Reported by a guildy 

**Links:**

https://cata-twinhead.twinstar.cz/?item=43868

**What is happening:**
- dont work it doesnt daze any mobs or players

**What should happen:**

![image](https://user-images.githubusercontent.com/39439201/124506961-08c38e80-ddcd-11eb-8bf0-af2ce16d3682.png)

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 

![image](https://user-images.githubusercontent.com/39439201/124682482-2414c380-decb-11eb-986c-9c47205e4b4c.png)
