### ISSUE TITLE
[Spell/buff] Irradiated 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5275]
**Links:**

https://www.wowhead.com/spell=80653/irradiated
https://www.wowhead.com/quest=27635/decontamination

**What is happening:**
- Irradiated buff is staying on player if they skip the quest to cleanse it in their start zone

**What should happen:**
you should lose this upon exiting Gnomeregan

**Comment by mfranca0009** [comment]
All set 👍  also corrected the decontamination quest vehicle ride so its no longer bouncing and flies smoothly.

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 

![image](https://user-images.githubusercontent.com/39439201/124670275-0851f300-deb4-11eb-889f-11970a84602b.png)
