### ISSUE TITLE
Quest "Bearer of Good Fortune" (13557) - Darkshore

### ISSUE THREAD

**Issue by ssmilazzo** [WoWManiaUK/Blackwing-Lair#5276]
**Links:**

https://www.wowhead.com/item=44927/corruptors-master-key
https://www.wowhead.com/quest=13557/bearer-of-good-fortune

**What is happening:**

Vile Corruptors in Cliffspring Hollow should have a 31% chance to drop Corruptor's Master Key which starts quest. After 32 kills item has not dropped. 

**What should happen:**

**Is it crashing the server?:**

**Other Information:**

Character is a Worgen

**Comment by Echinaceax** [comment]
We fixed this a few times in different reports 
1 For the cages 
1 for them not moving when freed.

players never had an issue getting the key for starter quest though @ssmilazzo 

we can take a look at the drop %

**Comment by mfranca0009** [comment]
Drop chance was off by a SLIGHT .1 percent, and it should be dropping on next update. The key starts a quest, it doesn't complete a quest, and that was the problem preventing it from dropping.

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 

![image](https://user-images.githubusercontent.com/39439201/124661611-02561500-dea8-11eb-95d6-7b248100b7c2.png)
