### ISSUE TITLE
Quest "The Ancients Ire" (13514)

### ISSUE THREAD

**Issue by ssmilazzo** [WoWManiaUK/Blackwing-Lair#5278]
**Links:**

https://www.wowhead.com/quest=13514/the-ancients-ire

**What is happening:**

After accepting the quest you should be allowed to use one of the Vengeful Protectors as a vehicle to complete the quest.  The Vengeful Protectors do not work as a vehicle.

**What should happen:**

**Is it crashing the server?:**

**Other Information:**

Character is Worgen

**Comment by Echinaceax** [comment]
reported already here #1046  @ssmilazzo
