### ISSUE TITLE
Quest "They Set Them Up the Bomb" (13981)

### ISSUE THREAD

**Issue by ssmilazzo** [WoWManiaUK/Blackwing-Lair#5279]
**Links:**

https://www.wowhead.com/quest=13981/they-set-them-up-the-bomb

**What is happening:**
The bomb does not offer the quest.

**What should happen:**

**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
will check this after next server update @ssmilazzo (for the worgen) 

it does on my Human 

![image](https://user-images.githubusercontent.com/39439201/124672086-bc547d80-deb6-11eb-85b6-263d96a38536.png)

**Comment by ssmilazzo** [comment]
Might be a Worgen thing. We're so misunderstood.

**Comment by Echinaceax** [comment]
> Might be a Worgen thing. We're so misunderstood.

yes, we think so.
a lot of worgen conditions was fixed yesterday, that will hopefully fix this soon for you (on next server update though)

**Comment by mfranca0009** [comment]
@ssmilazzo  confirmed this will be fixed next update, there were 90 quests updated to allow Worgens to the Alliance specific quests.

80 quests updated to allow Goblins to do Horde specific quests.
