### ISSUE TITLE
[Quest] Repairing A-Me 01 - ID 24715 - Un'Goro Crater

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#528]
Quest - https://www.wowhead.com/quest=24715/repairing-a-me-01
Item - https://www.wowhead.com/item=50236/high-viscosity-coconut-milk
Video - https://www.wowhead.com/quest=24715/repairing-a-me-01#videos:id=83207
npc - https://www.wowhead.com/npc=9623/a-me-01

- _**obtain an Un'Goro Coconut, crack it on the rock nearby, and give her the High Viscosity Coconut Milk**_
- Can obtain coconut and to crack it on the rock but, no High Viscosity Coconut Milk given
- High Viscosity Coconut Milk missing inside cracked coconut

![cracked](https://user-images.githubusercontent.com/39439201/51088355-dd610b00-175e-11e9-8087-4c31fc199377.jpg)

**Comment by Rushor** [comment]
item added

![I](https://i.imgur.com/3B8pMzb.jpg)
