### ISSUE TITLE
Quest "Cry For The Moon" (26760) - Duskwood

### ISSUE THREAD

**Issue by ssmilazzo** [WoWManiaUK/Blackwing-Lair#5281]
**Links:**

https://www.youtube.com/watch?v=cX9vAMP8BVI

**What is happening:**

This quest was included here https://github.com/WoWManiaUK/Blackwing-Lair/issues/3616 in an amazing write up done by Priestelar but I wanted to add the video and and to say that it is not on the .bq list.
![Screenshot (19)](https://user-images.githubusercontent.com/25713425/124788911-cf4b6a00-df17-11eb-93ac-989192194338.png)

**What should happen:**

**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
i'll add to the main report @ssmilazzo https://github.com/WoWManiaUK/Blackwing-Lair/issues/3616#issuecomment-560289716

and close this 

note: if there is already a report open, please dont open new report. just saves you wasting your time for it to be closed
