### ISSUE TITLE
Quest "The Vortex" (13886) - Ashenvale

### ISSUE THREAD

**Issue by ssmilazzo** [WoWManiaUK/Blackwing-Lair#5283]
**Links:**

**What is happening:**
He offer the quest twice:
![Screenshot (24)](https://user-images.githubusercontent.com/25713425/125050070-9cb48500-e06f-11eb-9c57-f4d717e0cb95.jpg)

extra info
Not on .bq command as stated here https://github.com/WoWManiaUK/Blackwing-Lair/issues/4540
![Screenshot (23)](https://user-images.githubusercontent.com/25713425/125049367-e781cd00-e06e-11eb-83e8-762d2c0560e4.jpg)

**Comment by ssmilazzo** [comment]
He does however offer the quest twice:
![Screenshot (24)](https://user-images.githubusercontent.com/25713425/125050070-9cb48500-e06f-11eb-9c57-f4d717e0cb95.jpg)

**Comment by Echinaceax** [comment]
I will add new info to the already open report as the second issue @ssmilazzo  thanks

Horde already reported it here too https://github.com/WoWManiaUK/Blackwing-Lair/issues/1022
