### ISSUE TITLE
[Battleground] Battleground General Issues

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5289]
**What is happening:**

### **General Problem**

- [x] Badge of Justice should not be given in BGs `Wotlk currency`  https://github.com/WoWManiaUK/Blackwing-Lair/issues/2074 (jani fixing)
- [x] Need correct rep setting for each Battleground `for the titles` Ally https://www.wowhead.com/title=48/justicar / Horde https://www.wowhead.com/achievement=714/the-conqueror

https://wowwiki-archive.fandom.com/wiki/Battleground_reputation_mobs

**Alterac Valley rep**
- [x] Frostwolf Clan (Horde)
- [x] Stormpike Guard (Ally)

**Arathi Basin rep**
- [x] Forsaken Defilers (Horde)
- [x] The League of Arathor (Ally)

**Warsong Gulch rep**
- [x] Silverwing Sentinels (Ally)
- [x] Warsong Outrider  (Horde)

### **Warsong Gulch**
- [x] Warsong Gulch (no flags spawning now)
- [x] Power-ups added
- [x] Spirit Guide not providing their heal channel visual - Further fix needed, good for now.
- [x] Fix orientation of Alliance Spirit Guide
- [x] When flags are spawned, dropped, or respawning they should have individual broadcast messages displaying: `The Horde flag has been placed` or `The Alliance flag has been placed`. Not `Both flags have been placed at their base`.

### **Twin Peaks**
- [x] Twin peaks (no flags spawning now)
- [x] Power-ups added
- [x] Flag capture score UI at the top of the screen does not state the proper flag being picked up. When Horde picks up the Alliance flag, it states the Alliance picked up the Horde flag.
- [x] Delete duplicate Spirit Guides that are not spawned via safe location DBC checks
- [x] Spirit Guides not providing their heal channel visual - Further fix needed, good for now.
- [x] Fix orientation of Spirit Guides
- [x] Flags can not be picked up after being dropped, and they also do not record flag returns if the flag is same team/faction as player returning it.

### **Battle For Gilneas**
- [x] The battle of Gilneas (flags dont capture now)
- [x] Power-ups added
- [x] Capture flag points do not have spawn (light emitting from bottom of the post to top) or despawn (burning) animation
- [x] Only restoration powerups are being spawned, and not all powerup locations are known or scripted yet.
- [x] BG ending before the Resource Score Count UI actually updates to show 2000/2000 resources collected
- [x] Add missing achievement `Newbs to Plowshares` : https://www.wowhead.com/achievement=5254/newbs-to-plowshares
- [x] Flag captures do not provide the proper spell channel text of "Capturing", it's just a blank yellow spell channel cast
- [x] Flag Gameobjects are improperly being spawned, therefore all gameobject flags were `Lighthouse Banner`.
- [x] Spirit Guides not providing their heal channel visual - Further fix needed, good for now.
- [x] Fix orientation and/or positioning of Spirit Guides
- [x] Remove Rep `The League of Arathor` https://www.wowhead.com/faction=509/the-league-of-arathor
- [x] Announce messages set for "Assaulted", "Defended", or "Claimed".
- [x] Faction system message for "Near Victory" message.

### **Arathi Basin**
- [x] Arathi Basin (flags dont capture now)
- [x] Power-ups added
- [x] Flag captures do not provide the proper spell channel text of "Capturing", it's just a blank yellow spell channel cast
- [x] Capture flag points do not have spawn (light emitting from bottom of the post to top) or despawn (burning) animation
- [x] Announce messages set for "Assaulted", "Defended", or "Claimed".
- [x] Faction system message for "Near Victory" message.

### **Eye of the Storm**
- [x] Eye of the Storm (no base capture flags, no center flag spawns)
- [x] Power-ups added 
- [x] Netherstorm Flag does not provide the proper spell channel text of "Capturing", it's just a blank yellow spell channel cast
- [x] Netherstorm Flag not able to be re-picked up from being dropped.
- [x] Fix Draenei Ruins `Taken` broadcast message stating Horde captured when Alliance did, vice-versa.
- [x] Some Spirit Guides are not providing their heal channel visual - Further fix needed, good for now.

### **Looting/skinning dead players**

- [x] Client crashes on some races/genders. #5298 
- needed for loots of worth
- Quests in Alterac Valley  https://cata-twinhead.twinstar.cz/?search=Armor+Scraps#items / https://cata-twinhead.twinstar.cz/?search=Armor+Scraps#quests

### **Other BGs** 

- [x] Remove `Strand of the Ancients` - `Alterac Valley` - `Isle of Conquest` from the Random battle ground que (for now)
- Alterac Valley  (not enough players, wrong nps level, no loot and quests not working) #5300
- Isle of Conquest (not enough players)
- Strand of the Ancients (ships not working) https://github.com/WoWManiaUK/Blackwing-Lair/issues/4776 / https://github.com/WoWManiaUK/Blackwing-Lair/issues/896

**Comment by mfranca0009** [comment]
Identified the problem and where it's occurring, looking into it further tomorrow ✔️

**Comment by mfranca0009** [comment]
Warsong Gulch Score UI with player names fix:
![image](https://user-images.githubusercontent.com/26092980/126242796-49e3212b-cd20-4da4-9c70-884884ac88a6.png)


**UPDATE**
Unfortunately, still something wrong with this feature and it works or breaks at random. Will look into it further at some point, considering it low priority.   `/reload` command works to reload UI and fix the problem while in BG, flag carrier names will show up once the flag has been picked up as new or re-picked up if dropped by a player.

**Comment by Echinaceax** [comment]
**### Looting/skinning dead players**

Checked so far 

1. B-males skinning human females dont crash client ✔️ 
2. B-females skinning human females dont crash client ✔️ 
3, human females skinning B-females do crash ❌ 
4. B-males skinning Human males do crash(edited) ❌

**Comment by mfranca0009** [comment]
Strand of the Ancients - Alterac Valley - Isle of Conquest, have been removed from Random Battleground rotation, BUT they can still be queued for individually. This is because their level range cannot be set to 0 nor anything higher than 85 because it just retrieves the proper level range from DBC data.
