### ISSUE TITLE
Random Dungeon Finder - worgen

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#5290]
There is an issue with RDF for Ally worgens. (Drood)

Should be awaileble to join rdf but i get that i do not meet the requirement for this dungeon .. ?
Im at ilvl 341 

Should add me in queue for rdf.

**Comment by Echinaceax** [comment]
@Saintres can you make sure you completed https://www.wowhead.com/quest=28517/the-howling-oak, 
https://github.com/WoWManiaUK/Blackwing-Lair/issues/4501#issuecomment-754097872

get a GM to check your questline

**Comment by Saintres** [comment]
Im not a DK so i cant do that quest ??

Den ons 14 juli 2021 kl 23:07 skrev Echinaceax ***@***.***>:

**Comment by Saintres** [comment]
Ok did that quest and now it looks like it's working.

Den ons 14 juli 2021 kl 23:07 skrev Echinaceax ***@***.***>:

**Comment by Echinaceax** [comment]
i thought so :)
no problem saint..glad we fixed it 😄
