### ISSUE TITLE
NPC] Earthmender Norsala (Double spawn) - Deepholm

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5292]
**Links:**

https://www.wowhead.com/npc=43503/earthmender-norsala

**What is happening:**
- double spawned

**What should happen:**
Should only be one 

![image](https://user-images.githubusercontent.com/39439201/125709391-96ce0cca-7cd3-4c83-a10f-31b1678d3fa9.png)

Reported by new tester

**Comment by mfranca0009** [comment]
Duplicate removed, can be re-added if it was a phasing problem when we come across it.

**Comment by Echinaceax** [comment]
confirmed fixed in PTR

![image](https://user-images.githubusercontent.com/39439201/127031377-48273105-4e4a-40d7-9454-508d5d190c9b.png)

**Comment by Echinaceax** [comment]
Fixed on live
