### ISSUE TITLE
[Raid/Loot] Token boss % check 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5296]
- [x] **Nefarian / onyxia- Blackwing Descent 10/25 man normal/heroic**
https://www.wowhead.com/npc=41376/nefarian
https://www.wowhead.com/npc=41270/onyxia

https://www.wowhead.com/item=63682/helm-of-the-forlorn-vanquisher
https://www.wowhead.com/item=63684/helm-of-the-forlorn-protector
https://www.wowhead.com/item=63683/helm-of-the-forlorn-conqueror

- [x] **Cho'gall - The Bastion of Twilight 10/25 man normal/heroic**
https://www.wowhead.com/npc=43324/chogall

https://www.wowhead.com/item=64314/mantle-of-the-forlorn-vanquisher
https://www.wowhead.com/item=64315/mantle-of-the-forlorn-conqueror
https://www.wowhead.com/item=64316/mantle-of-the-forlorn-protector

- [x] **Al'Akir - Throne of the Four Winds 10/25 man normal/heroic**  (working as far as we know)
https://www.wowhead.com/npc=46753/alakir 

https://www.wowhead.com/item=63682/helm-of-the-forlorn-vanquisher
https://www.wowhead.com/item=63684/helm-of-the-forlorn-protector
https://www.wowhead.com/item=63683/helm-of-the-forlorn-conqueror

https://www.wowhead.com/item=64314/mantle-of-the-forlorn-vanquisher
https://www.wowhead.com/item=64315/mantle-of-the-forlorn-conqueror
https://www.wowhead.com/item=64316/mantle-of-the-forlorn-protector

**Comment by mfranca0009** [comment]
Nefarian should be all set now 👍

**Comment by golosomie** [comment]
Confirmed fixed. Killed Nefarian a bunch of times, every time he dropped 2 random items + the token as expected.
All 3 tokens were able to drop - should be good now!
