### ISSUE TITLE
[quest] Proving Pit

### ISSUE THREAD

**Issue by gorgar19** [WoWManiaUK/Blackwing-Lair#5297]
**Links:**
https://www.wowhead.com/quest=24780/proving-pit

**What is happening:**

quest dialog is off after you click your ready to go the end of the dialog he says is $n instead of the players name  

**What should happen:**

says your name 

**Is it crashing the server?:**
no
**Other Information:**

small typo in the script think it should be %n

**Comment by mfranca0009** [comment]
This should be fixed 👍 I've also added the 3 missing texts that the `Captive Spitescale Scouts` could potentially say. They have 4 lines total, and one is randomly selected to be said.

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 

![image](https://user-images.githubusercontent.com/39439201/126984351-a5815556-06e0-4050-9a53-4083e6087b25.png)

![image](https://user-images.githubusercontent.com/39439201/126984236-3f3c2f24-7339-4739-ba7f-5aa0887efa52.png)

**Comment by Echinaceax** [comment]
fixed on live
