### ISSUE TITLE
[Battleground] Looting/skinning dead players

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5298]
###  **Looting/skinning dead players**

Checked so far  (❌ do crash / ✔️ dont crash)

1. Bloodelf males skinning human females ✔️ 
2. Bloodelf females skinning human females  ✔️ 
3. human females skinning Bloodelf female  ❌ 
4. Bloodelf males skinning Human males  ❌ 
5. Worgen female skinning bloodelf male ✔️ 
6. bloodelf male skinning Worgen female ✔️ 
7. Worgen female skinning Bloodelf female ✔️ 
8. Nightelf Female skinning a Bloodelf female ❌ 
9. Bloodelf female skinning a Nightelf female ❌ 
10. Gnome Female skinning Bloodelf female ❌ 
11. Bloodelf female skinning Gnome Female ❌ 

**Note:** 
For now i think its best to disable the skinning of dead players for this week live update,
then once the other updates have gone live we can enable it again to continue testing until we can get this issue fixed after full test of all races/genders as this may take a while to complete the testing 

And as we are removing Alterac Valley from the RBG que for now this funtion isnt actually needed right at this moment for the AV Quests items https://cata-twinhead.twinstar.cz/?search=Armor+Scraps#items / https://cata-twinhead.twinstar.cz/?search=Armor+Scraps#quests

**Comment by golosomie** [comment]
I'm compiling a list of all combinations that cause crashes. Still a lot of stuff to go - 108/336 done

**Comment by Echinaceax** [comment]
looks like we have fixed this issue @golosomie 
Ive PM you how ...

**Comment by mfranca0009** [comment]
UNIT_FLAG_SKINNABLE was being forced on players, removing this resolved the client crash problems and you are still able to loot insignia from dead players once they release (AKA looting their corpse).

**Comment by golosomie** [comment]
@mfranca0009 uh, great that you found the cause, thank you!
Will test this asap

**Comment by Echinaceax** [comment]
> @mfranca0009 uh, great that you found the cause, thank you!
> Will test this asap

just the known combos that was crashing shouldnt now, we checked belf female and was no problem
