### ISSUE TITLE
[quest] Flash Heal (goblin)

### ISSUE THREAD

**Issue by gorgar19** [WoWManiaUK/Blackwing-Lair#5299]
Links:

https://wowpedia.fandom.com/wiki/Flash_Heal_(goblin)

What is happening:

players not getting credit for casting flash heal on the correct mobs

What should happen:

player should get credit for casting in on the injured employees right next to the quest giver

Is it crashing the server?:
no

Other Information:

couldn't find a good link on  wowhead kept getting links to the quest Learning the Word ,sorry.

**Comment by Echinaceax** [comment]
thanks @gorgar19 
we'll check this out 👍 

UPDATE
Injured Employee are at full hp atm , probly why its not working 

NPC https://cata-twinhead.twinstar.cz/?npc=48305
Quest https://cata-twinhead.twinstar.cz/?quest=14009

![image](https://user-images.githubusercontent.com/39439201/126702491-14ea068c-d691-4834-a2ea-c0b72e29a066.png)

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 

![image](https://user-images.githubusercontent.com/39439201/127009119-abeeb2e8-b2a5-4106-b0b1-a512838f4997.png)

**Comment by mfranca0009** [comment]
On live 👍
