### ISSUE TITLE
[Spell]  Divine Hymn

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Blackwing-Lair#53]
**How it should work:**
>Description: Heals $64843s2 nearby lowest health friendly party or raid targets within $64844A1 yards for $64844s1 every $64843t1 sec for $64843d, and increases healing done to them by $64844s2% for $64844d. Maximum of $*4;64843s2 heals. The Priest must channel to maintain the spell.

>ToolTip: Reciting Divine Hymn, healing nearby friendly party or raid targets most in need for $64844s1 every $t1 sec for $d.
![image](https://user-images.githubusercontent.com/14857593/38849568-f2a35594-4221-11e8-8115-cad698c363b9.png)

**How it works:**
It is doing an extra big heal on every heal it does.
![image](https://user-images.githubusercontent.com/14857593/38849456-5c418058-4221-11e8-9ff7-e0ee83a5ec3a.png)

**Comment by Keader** [comment]
Fixed.
Target number was wrong too (was like wotlk, 3 targets) need be 5.
Both fixed.
