### ISSUE TITLE
[NPC] Estulan - Missing - Feralas

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#530]
Quest - https://www.wowhead.com/quest=27132/the-highborne

- cant give quest back 

![npc est](https://user-images.githubusercontent.com/39439201/51090744-f8dd0d80-1780-11e9-85b4-6ddb4334b7fc.jpg)

**Comment by Dranah** [comment]
https://www.wowhead.com/npc=44991/estulan
