### ISSUE TITLE
[NPC] Risen Hillsbrad Peasant -Hillsbrad Foothills

### ISSUE THREAD

**Issue by gorgar19** [WoWManiaUK/Blackwing-Lair#5301]
Links:
https://www.wowhead.com/npc=47861/risen-hillsbrad-peasant

( just for an approximate location )
https://www.wowhead.com/quest=28189/do-the-right-thing

What is happening:

looks like their 2 or so that fall under the world that are able to attack players but players will get the out of range message  ,pets can attack it though. looks like when they spawn they fall through the ground. sometimes if you flee they will return above ground
approximate location 39.37 63.22 close to the shovel that gives the quest do the right thing.
 

What should happen:

Is it crashing the server?:
no

Other Information:

**Comment by Echinaceax** [comment]
thanks @gorgar19 
reported here already #1600
