### ISSUE TITLE
[Quest] The Endless Hunger ID 12848

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#5307]
**Links:**
https://www.wowhead.com/quest=12848/the-endless-hunger
from WoWHead or our Armory

**What is happening:**
When you get the key to free some initiates to fight them u cant target them or the lock that u should open.

**What should happen:**
When you click on the key in your quest u should free the initiate and then he will go and get his gear and fight me. that is not happening
**Is it crashing the server?:**

**Other Information:**

There was a guildie that started a DK and got this problem, so i started 1 allso to confirm the bug.

**Comment by Echinaceax** [comment]
I'll take a look @Saintres

**Comment by Echinaceax** [comment]
Hmm, no issue for me 

tested with a human male DK
https://gyazo.com/af32547d4840f66233912de348fd3300


I just clicked the clickable skull on the wall @Saintres 

`and then he will go and get his gear and fight me. that is not happening`

If you look closely they face the wall and aquire the clothes and weapon 

https://www.wowhead.com/quest=12848/the-endless-hunger#videos:id=52664

![clicked the skull](https://user-images.githubusercontent.com/39439201/128599149-0d830c2e-b371-4bad-b524-be0c250e302b.jpg)

![image](https://user-images.githubusercontent.com/39439201/128599088-9791c5fe-14b1-4743-82d1-706ca54d0fda.png)
