### ISSUE TITLE
[QUEST] The Last Line Of Defense - ICECROWN

### ISSUE THREAD

**Issue by gorgar19** [WoWManiaUK/Blackwing-Lair#5317]
![Screenshot (7)](https://user-images.githubusercontent.com/69017051/132112677-a5d8f90d-1f60-485f-868b-a40a3c941fe2.png)
![Screenshot (8)](https://user-images.githubusercontent.com/69017051/132112680-604070ac-7d55-4ab4-b2b4-5062834cb85a.png)
Links:

https://www.wowhead.com/quest=13086/the-last-line-of-defense

What is happening: after completion of this quest the bone pile is no longer available for the completion of 
https://www.wowhead.com/quest=13141/the-battle-for-crusaders-pinnacle.
completion of this quest should remove the spiders but not the bone pile at Crusaders' Pinnacle

Is it crashing the server?: No

Other Information:

**Comment by Echinaceax** [comment]
@gorgar19 this quest is reported here #4589 

Did you complete this yourself using the BQ command?

i will link this info to the the other report and close this one
