### ISSUE TITLE
[QUEST] The Restless Dead - Icecrown

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5319]
**Links:**

quest https://www.wowhead.com/quest=13110/the-restless-dead
quest item https://www.wowhead.com/item=43153/holy-water

**What is happening:**
Quest item isnt working to free 10 restless souls.

**What should happen:**
https://www.wowhead.com/quest=13110/the-restless-dead#videos:id=74423

**Comment by gorgar19** [comment]
just did  that quest yesterday 
![Screenshot (9)](https://user-images.githubusercontent.com/69017051/132130741-3df8d396-2a12-4ca8-bdcc-bb5a56511b23.png)

**Comment by Echinaceax** [comment]
@gorgar19 strange 😄 
can you PM be in Discord, i have a question about another issue :)

**Comment by Echinaceax** [comment]
retested today and is fine :)

![image](https://user-images.githubusercontent.com/39439201/132539357-01c5319c-f594-432a-a247-e4b95a17eee6.png)
