### ISSUE TITLE
[Zone] Splintertree post - Ashenvale

### ISSUE THREAD

**Issue by Icytalon** [WoWManiaUK/Blackwing-Lair#532]
there is an invisible wall in front of the Splintertree post camp main gate in Ashenvale I had to turn around to be able to get inside.

**Comment by Dranah** [comment]
Confirmed, main door is blocked by something invisible.
It is however possible to get into the town on the side.

**Comment by Dranah** [comment]
Map:1 (Kalimdor) Zone:331 (Ashenvale) Area:431 (Splintertree Post)
X:2230.981201 Y:-2541.350342 Z:86.861420

**Comment by Echinaceax** [comment]
yip, i came across this too
glad its reported :)
