### ISSUE TITLE
[Quest] Mostly Harmless / Croc-Out - Interaction - Swamp of Sorrows

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#533]
https://www.wowhead.com/npc=45786/trade-baron-silversnap

- Gives only one of the 2 quests 
- the other disappears

![trade baron](https://user-images.githubusercontent.com/39439201/51091240-5759ba00-1788-11e9-91f1-8021f74053cc.jpg)

**Comment by sarahkay88** [comment]
same for alliance

**Comment by Echinaceax** [comment]
Mostly harmless i think 
coz i remember doing the croc one

**Comment by mfranca0009** [comment]
Just tested this right now, was able to pick up both quests with no issue. Cannot reproduce issue anymore.
