### ISSUE TITLE
Worgen Druid Crash Report

### ISSUE THREAD

**Issue by Deathghat** [WoWManiaUK/Blackwing-Lair#5335]
**Links:**

**What is happening:**
Occasionally, when in cat form as a Worgen Druid, if you click on [Two Forms] (spell to change forms between human and worgen) and try to exit cat form shortly after, the game crashes.

**What should happen:**
Not that.

Update: upon researching further, it appears that the [Two Forms] would normally be available to be cast.
I assume appropriate behavior would be to force player to exit cat form and turn into a human.

**Is it crashing the server?:**
Crashes client.

**Other Information:**
Unsure *exactly* what is supposed to happen when clicking two forms in cat form as a worgen druid. I'm assuming it's normally disallowed to switch forms while in cat form. 

Error shown below:
![image](https://user-images.githubusercontent.com/89095218/134272166-88ea04ab-8508-4c7a-bb3d-f6bfc0298eb7.png)

**Comment by Echinaceax** [comment]
worgen report already noted #4396
