### ISSUE TITLE
[Quest] Gorat's Vengeance - ID 13621- Northern Barrens

### ISSUE THREAD

**Issue by Icytalon** [WoWManiaUK/Blackwing-Lair#534]
Quest link: https://www.wowhead.com/quest=13621/gorats-vengeance
Quest item link : https://www.wowhead.com/item=45023/gorats-imbued-blood
NPC link : https://www.wowhead.com/npc=33294/gorat

**using Gorat's Imbued Blood on his corpse says require Gorat corpse while I am on it**
![wowscrnshot_011419_002441](https://user-images.githubusercontent.com/33905184/51091461-86c1f400-1793-11e9-843f-19ddc2b76385.jpg)

**Comment by Saintres** [comment]
Same for me today

**Comment by Sammy974** [comment]
Corpse is not there yet...
