### ISSUE TITLE
Vote not working

### ISSUE THREAD

**Issue by NexusSqueek** [WoWManiaUK/Blackwing-Lair#5346]
I am trying to vote on website to get vote points, I have voted 2 days in a row, but have not received any vote points.

**Comment by Echinaceax** [comment]
Hi @NexusSqueek 
Github is for ingame bugs, this is not an ingame bug

however
Vote site is an external issue, and Janitor is aware of some of the vote sites are not giving tokens 
Some advice from other players is: make sure your not using an adblocker  

ATM i see only 1 token given 

![image](https://user-images.githubusercontent.com/39439201/141703530-bfd4481f-ddce-4a62-b168-9c958eefce7a.png)
