### ISSUE TITLE
[Item] [Large Raw Mightfish] id: 13893

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#5351]
**Links:**
https://cata-twinhead.twinstar.cz/?item=13893
from WoWHead or our Armory

**What is happening:**
I have fished on multiple locations in Swamp of sorrows 289 attempts
Blasted lands 60 attempts

**What should happen:**
According to wowhead, and google search farming, it should be catchable in this 2 locations
**Is it crashing the server?:**
no
**Other Information:**

**Comment by Echinaceax** [comment]
Reported already @TheSale https://github.com/WoWManiaUK/Blackwing-Lair/issues/5158
