### ISSUE TITLE
The Prophecy of Akida

### ISSUE THREAD

**Issue by Doxxy0** [WoWManiaUK/Blackwing-Lair#5357]
**Links:**
http://cata.cavernoftime.com/quest=9544
from WoWHead or our Armory

**What is happening:**
Missing cages around the captives, making the mission impossible to complete
![kép](https://github.com/WoWManiaUK/Blackwing-Lair/assets/84509345/43c39b62-51ca-4a7b-9be1-e388ae5ad2e4)

**What should happen:**
cages should be opened and add +1 to freed captives
**Is it crashing the server?:** no

**Other Information:**
cache deleted

**Comment by Echinaceax** [comment]
Thanks for reporting @Doxxy0 
it is already reported here though https://github.com/WoWManiaUK/Blackwing-Lair/issues/5064
Please check before making new reports for same issue. thank you
