### ISSUE TITLE
[Quest] Got Wood? - ID 13628 - Northern Barrens

### ISSUE THREAD

**Issue by Icytalon** [WoWManiaUK/Blackwing-Lair#538]
Quest link : https://www.wowhead.com/quest=13628/got-wood
NPC link: https://www.wowhead.com/npc=34006/kadrak
Quest item Link: https://www.wowhead.com/item=45051/kadraks-reins
Mount link: https://www.wowhead.com/npc=33374/brutusk
**After I accept the quest I have to speak to [Kadrak](https://www.wowhead.com/npc=34006/kadrak), to receive [Kadrak's Reins](https://www.wowhead.com/item=45051/kadraks-reins), which gives me a buff that will allow me to [ride ](https://www.wowhead.com/spell=62885/ride-brutusk)[Brutusk ](https://www.wowhead.com/npc=33374/brutusk)The mount which is standing few yards away from Brutusk, neither Kadrak or Brutusk are exist.** **ps: Brutusk should be where my cruiser is and Kadrak  should be where I am standing.**
![wowscrnshot_011419_010604](https://user-images.githubusercontent.com/33905184/51091816-9859ca80-1798-11e9-9a0c-546577c84327.jpg)

**Comment by Ranger-Bill** [comment]
I am having the same problem.

**Comment by Eirolla** [comment]
Confirmed.
![image](https://user-images.githubusercontent.com/26048748/62369158-6131e780-b537-11e9-85e4-6bdaa682ebaf.png)the NPC is not there at all.

**Comment by Kishilu** [comment]
Kadrak is on the tower right of the gates, but Brutusk still cannot be found or mounted.

**Comment by mfranca0009** [comment]
Issue still exists, Brutusk is not there.

**Comment by mfranca0009** [comment]
Spawned Kadrak and Brutusk, created gossip option for Kadrak, quest item is now obtainable from Kadrak, and Brutusk has npc_spellclick enabled now as mount hop-on. 

Will need to finish this, since it's far from done.

**Comment by mfranca0009** [comment]
Fixed in PTR, needs testing 👍  @Echinaceax

**Comment by Echinaceax** [comment]
EDITED

**Comment by Echinaceax** [comment]
Found the issue ...
Making new report and closing this one
