### ISSUE TITLE
[Quest] Kill Gil / Can't Take it With Them - Interaction -  (issue 1) - Swamp of Sorrows

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#539]
NPC - https://www.wowhead.com/quest=27597/crazy-larry

- Can only chose one of the quests, the other disappears

![crazy lary](https://user-images.githubusercontent.com/39439201/51091840-9f7cda80-1790-11e9-8ead-c26617570106.jpg)

**Comment by Dranah** [comment]
https://www.wowhead.com/quest=27598/kill-gil
https://www.wowhead.com/quest=27599/cant-take-it-with-them

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
confirmed fixed in ptr 

![image](https://user-images.githubusercontent.com/39439201/103442749-56faa800-4c59-11eb-856d-fa33198d48bf.png)
