### ISSUE TITLE
[Talent]  Evangelism

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Blackwing-Lair#54]
**How it should work:**
![image](https://user-images.githubusercontent.com/14857593/38850085-0fb1e9ea-4225-11e8-8110-1469461dc685.png)
>Description: When you cast Smite, Holy Fire or Mind Flay you gain Evangelism. Stacks up to $81660u times. Lasts for $87117d.

>|CFFFFFFFFEvangelism (Smite, Holy Fire)|R
Increases the damage done by your Smite, Holy Fire, and Penance spells by $81661s1% and reduces the mana cost of those spells by $81661s2%.

>|CFFFFFFFFDark Evangelism (Mind Flay)|R
Increases the damage done by your Periodic Shadow spells by $87118s1%.

**How it works:**
Casting non of the named spell in tooltip, will give you the the effect.
Simply talent is not working at all.

**Comment by Keader** [comment]
Talent was not implemented.
So i implemented it xD
