### ISSUE TITLE
[Quest] Can't Take It With Them - ID 27599 - (issue 2) - Swamp of Sorrows

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#541]
Quest - https://www.wowhead.com/quest=27599/cant-take-it-with-them
Item loot - https://www.wowhead.com/item=61923/steamwheedle-ditty-bag
video - https://www.wowhead.com/quest=27599/cant-take-it-with-them#videos:id=82752

- Unable to loot bodies 
- Cant complete

![no bags](https://user-images.githubusercontent.com/39439201/51092030-5712ec00-1793-11e9-8958-f80af218d364.jpg)

**Comment by mfranca0009** [comment]
Fixed in PTR, needs testing 👍 

This should work as it's suppose to 100% blizzlike looting the "dead" NPC, bringing up a loot window, and obtaining Steamwheedle Ditty Bags.

**Comment by Echinaceax** [comment]
confirmed fixed in ptr 👍
