### ISSUE TITLE
[Combat] - Hunter

### ISSUE THREAD

**Issue by gantor2** [WoWManiaUK/Blackwing-Lair#542]
noticed a weird thing with hunter basic attacking, some of my shots seem to be competing for speed

Not sure if this is a bug or not but it seems conflicting as it’s messing up talent procs.

When i choose to cast aimed shot at a target, my autoshot reaches the target before the spell i first selected and occasionally will make this tallent ineffective. 
![Image](https://i.imgur.com/h1Sqbz3.jpg)
![Image](https://i.imgur.com/zO863rq.jpg)

**Comment by Dranah** [comment]
I cannot reproduce this.
If i begin casting an Aimed Shot, it always lands sooner than the ranged shot which is triggered by the cast.
Could be lag related?

**Comment by gantor2** [comment]
When I get home I will re attempt and review

**Comment by gantor2** [comment]
It appears to be random when it happens as i cannot determine if any factors are causing this. i tried to see if it was something with the global attack speed cooldown by changing bows with different speeds or something along those lines but no changes.

**Comment by Keader** [comment]
Well, i only can fix bugs that i can reproduce.
Reopen it or make a new issue if you found a way to reproduce it.
