### ISSUE TITLE
[Quest] Putting Their Heads Together - ID 14227 - Desolace

### ISSUE THREAD

**Issue by gantor2** [WoWManiaUK/Blackwing-Lair#546]
- The skulls to use in the quest cannot identify the summoning circle when standing on it to summon the hostile creature which is required to kill.
- Item - ID 48953
- NPC - ID 35647
![image](https://user-images.githubusercontent.com/46546885/51119087-e514c400-17df-11e9-9592-ce624e170d86.png)

- https://www.wowhead.com/quest=14227/putting-their-heads-together

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/yNPNcdm.jpg)

creature can be spawned in the middle once 100 skulls are collected.
