### ISSUE TITLE
[NPC] Wind Rider Gorsch -  Azshara

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#548]
npc - https://www.wowhead.com/npc=36902/wind-rider-gorsch

- Inactive
- Cant get connection FPs 

![fp](https://user-images.githubusercontent.com/39439201/51136936-f55b8c00-183d-11e9-9c6c-fe4d5a0f8687.jpg)

**Comment by Dranah** [comment]
This NPC is not supposed to have a flight point. 20 yards to his right there's the actual Wind Rider Master, Kroum. The Valormok flight point works as intended.
