### ISSUE TITLE
[Spell] Mind Spike

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Blackwing-Lair#55]
**How is should work:**
>Description: Blasts the target for $73510s1 Shadowfrost damage, but extinguishes your Shadow damage-over-time effects from the target in the process.
>Mind Spike also increases the critical strike chance of your next Mind Blast on the target by $73510s2%. Stacks up to $73510s3 times.
![image](https://user-images.githubusercontent.com/14857593/38850325-2d720482-4226-11e8-88a4-abe39905e95d.png)

**How it works:**
It is not removing the shadow damage-over-time effects on the target.
![image](https://user-images.githubusercontent.com/14857593/38850404-83bc0be4-4226-11e8-9f20-9f7268da9219.png)

**Comment by Keader** [comment]
Fixed.
Will be ready to test tomorrow morning 💃
