### ISSUE TITLE
[Spell] Guardian of Ancient Kings

### ISSUE THREAD

**Issue by Icytalon** [WoWManiaUK/Blackwing-Lair#550]
when using [Guardian of Ancient Kings](http://cata-shoot.tauri.hu/?spell=86150) as retribution or protection nothing showing up "animation nor effect" I didn't try it in holy spec yet , the spell ID is 86150

**Comment by Dranah** [comment]
The guardian is now properly summoned.
For holy, it's not healing, but that belongs to the NPC report.
For prot, the damage reduction works fine.
For ret, the spell ID 86698 (retri power infuse effect) however does not work. I am not sure if this damage boost should be cast by the guardian as the tooltip states "attacks done by you and your guardian" not only those of the guardian. Both you and your guardian are auto attacking, but the "Ancient Power" ID 86700 stacks are not added. I believe this still belongs to this report.

**Comment by Keader** [comment]
@Dranah when 86700 need be added? in what conditions?

**Comment by Dranah** [comment]
Auto attacks done by the player and the guardian.

**Comment by Keader** [comment]
Fixed.

**Comment by Dranah** [comment]
Stacking properly by both the paladin's and the guardian's melee swings too, now.
