### ISSUE TITLE
[NPC] Innkeeper Teenycaugh - Felwood

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#551]
npc - https://www.wowhead.com/npc=48599/innkeeper-teenycaugh

- Cant lay HS there
- only opens sales window

**Comment by Echinaceax** [comment]
@Rushor - She has the HS now, but when you click it she doesnt cast ..my HS didnt change location from bloodelf startzone 

![nope](https://user-images.githubusercontent.com/39439201/56682579-231d6000-66cc-11e9-83e0-6431a221a250.jpg)

**Comment by Kitzunu** [comment]
works for me
