### ISSUE TITLE
[Quest] Scrambling for Eggs / The Wormwing Problem - Interaction - Mount Hyjal

### ISSUE THREAD

**Issue by Icytalon** [WoWManiaUK/Blackwing-Lair#552]
[she ](http://cata-shoot.tauri.hu/?npc=41006)gives only one of these quests [Scrambling for Eggs ](http://cata-shoot.tauri.hu/?quest=25656) or [The Wormwing Problem](http://cata-shoot.tauri.hu/?quest=25655)
![wowscrnshot_011519_003753](https://user-images.githubusercontent.com/33905184/51146139-978b6c00-185e-11e9-8868-58e1e49de447.jpg)

**Comment by Echinaceax** [comment]
**Just an idea** 
- Have you thought off abandoning the other 3 quests that she has give you already and testing 1 then 2 then 3 etc... i have tested like that a once or twice it gave quest in the right order

**Comment by Dranah** [comment]
Quest order is missing obviously. This NPC is also missing her phasing and repositioning for each stage of the quest chain. Has been already reported so add any extra info there.

**Comment by Dranah** [comment]
These two quests are at the same stage of the quest chain and both should be available and possible to complete at same time.

**Comment by Dranah** [comment]
This is fixed.

**Comment by Echinaceax** [comment]
Update on this = Phasing issue

**Comment by Echinaceax** [comment]
not the same issue @mfranca0009 
this one is about quest order
