### ISSUE TITLE
[Item/Quest] Blood Red Key - Felwood

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#553]
Item drop - https://www.wowhead.com/item=13140/blood-red-key

**_Starts a quest at 49_**

- Not clickable
- Wont start the quest 

![red key](https://user-images.githubusercontent.com/39439201/51148681-6a8b8900-185f-11e9-9517-54922080149f.jpg)

**Comment by Dranah** [comment]
https://www.wowhead.com/quest=5165/deprecated-dousing-the-flames-of-protection this quest should start

**Comment by Dranah** [comment]
Apparently you get this quest from the NPC (some newer version of it) and the one I linked above is deprecated. You no longer need the key, and it shouldnt be in the drop at all.

**Comment by Rushor** [comment]
okay we remove the item then from game drop
