### ISSUE TITLE
[Quest/Item] Hazzard Disposal - ID 28213 - Felwood

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#555]
item - https://www.wowhead.com/item=63284/kittys-eartag

_**Use Kitty's Eartag to get Winna Hazzard's attention, and then slay her**_

- item is not working on Winna Hazzard 
- When you use the ring you hear a ping noise but ..nothing 
- Unable to complete quest 

Quest - https://www.wowhead.com/quest=28213/hazzard-disposal
NPC - https://www.wowhead.com/npc=47679/winna-hazzard

**Ring used** 

![ring](https://user-images.githubusercontent.com/39439201/51150228-b2adaa00-1865-11e9-89a1-e5db16b8d375.jpg)

**Ring not used (invalid target) when you don't use the ring** 

![invalid](https://user-images.githubusercontent.com/39439201/51150277-e1c41b80-1865-11e9-85e9-482dd3f44814.jpg)

**Comment by glcabatuan** [comment]
**Quest:** http://cata.cavernoftime.com/quest=28213
**NPC/s:**  http://cata.cavernoftime.com/npc=47679
**Item/s:**  http://cata.cavernoftime.com/item=63284
**Object/s:** 
**Spell/s:**  http://cata.cavernoftime.com/spell=89297

**Current State:** 
http://cata.cavernoftime.com/npc=47679 doesn't react upon casting http://cata.cavernoftime.com/spell=89297 of the http://cata.cavernoftime.com/item=63284.

Note: http://cata.cavernoftime.com/npc=47679 is not covered with slime.

**Expected State:** 

http://cata.cavernoftime.com/npc=47679 should aggro upon casting http://cata.cavernoftime.com/spell=89297. Killing her to finish the quest.

As shown in: https://youtu.be/4TJ4ixIlJ_c?t=44

**Comment by Rushor** [comment]
fixed https://i.imgur.com/T0rqPSw.jpg
