### ISSUE TITLE
[Quest/Priest] Healing the Wounded - ID 10072 - sunstrider lsle

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#558]
https://www.wowhead.com/quest=10072
Note: wowhead is outdated as the quest has been redesigned on a later patch.

Problem:
Quest does not grant credit when healing Wounded Outrunners, cannot be completed.
https://www.wowhead.com/npc=44857/wounded-outrunner

**Comment by Echinaceax** [comment]
![heal the wounded](https://user-images.githubusercontent.com/39439201/51154206-55205a00-1873-11e9-9cc7-5ac7a30cec7f.jpg)
![healed](https://user-images.githubusercontent.com/39439201/51154220-5e112b80-1873-11e9-99e8-56fed6f383ef.jpg)

**Comment by Dranah** [comment]
Gives credit now, but you can't hand it in. NPC does not offer to.

**Comment by Dranah** [comment]
Nevermind, it works.
