### ISSUE TITLE
[Spell] Shadow Orbs (Passive)

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Blackwing-Lair#56]
**How it should work:**
>Description: You have a $77486h% chance for your Shadow Word: Pain and Mind Flay spells to grant you a Shadow Orb each time they deal damage.  Casting your Mind Blast or Mind Spike spell consumes all Shadow Orbs, increasing damage of that spell by ${$77486m1+10}% per Shadow Orb, and granting ${$77486m1+10}% increased damage on your periodic Shadow spells for $95799d.  You can have up to a maximum of $77487u orbs.
![image](https://user-images.githubusercontent.com/14857593/38850640-922e6c20-4227-11e8-8470-f96f91735a2e.png)

**How it works:**
Casting named spells in tooltip, does not grants the player any shadow orb.
Simply the spell is not working at all.

**Comment by Keader** [comment]
God, i "lost" 1 day fixing it.
Is partial fixed, scope of this issue is fixed. But still missing mastery part (that should increase damage done of shadow orb).
Anyway, is ready to test...

**Comment by TheManiax** [comment]
Gaining shadow orbs through casting SW:P and Mindflay is fixed
But as you said,
1. it is not scaling the Mind Blast damage
And also, 
2. taking **ANY** damage is triggering the orbs
No matter if I take critical hit or normal white damage, I'm getting a new orb

It is making Shadow Priest super OP
I know you have put (not lost) a lot of time on it, but take a look at these two issues as well when you have time please.

**Comment by DiomacheTharghan** [comment]
>  But as you said,it is not scaling the Mind Blast damage.

Still having this problem

**Comment by Keader** [comment]
@DiomacheTharghan Make a new issue, we can handle with it now
