### ISSUE TITLE
[Quest] Navarax's Gambit - ID 28264 - Felwood

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#561]
npc - https://www.wowhead.com/npc=47842/archdruid-navarax

- Text not clickable 
- Cant complete

for quest - https://www.wowhead.com/quest=28264/navaraxs-gambit

![not clickable](https://user-images.githubusercontent.com/39439201/51155957-b6e3c280-1879-11e9-9d4b-e27c8c9bd535.jpg)

**Comment by glcabatuan** [comment]
**Quest:**  http://cata.cavernoftime.com/quest=28264
**NPC/s:**  http://cata.cavernoftime.com/npc=47842
**Item/s:** 
**Object/s:** 
**Spell/s:** 

**Current State:** 
When trying to talk to http://cata.cavernoftime.com/npc=47842, he doesn't respond even if we click the dialogue.

**Expected State:** 
Once the dialogue was clicked/triggered, he immediately become an enlarged satyr(demon) and become hostile

As shown in: https://youtu.be/-D4sLUM6Rxw?t=58

**Comment by Rushor** [comment]
all fixed https://i.imgur.com/AnoGlOY.jpg https://i.imgur.com/PfJh338.jpg
