### ISSUE TITLE
[NPC] Feronas Sindweller - Felwood

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#562]
npc - https://www.wowhead.com/npc=47923/feronas-sindweller

- A few issues with him.
- Quest below was returnable completed with out actually doing anything 
- i didnt have to do anything , was just **completed** as i accepted the quest.

![all completed](https://user-images.githubusercontent.com/39439201/51157717-8011aa80-1881-11e9-8e29-7e3b8215f363.jpg)

1 - https://www.wowhead.com/quest=28256/the-skull-of-guldan
video - https://www.wowhead.com/quest=28256/the-skull-of-guldan#videos:id=82380

2 - https://www.wowhead.com/quest=28257/the-fall-of-tichondrius
video - https://www.wowhead.com/quest=28257/the-fall-of-tichondrius#videos:id=82381

3 - https://www.wowhead.com/quest=28218/a-destiny-of-flame-and-sorrow
video - https://www.youtube.com/watch?v=3jtVIF7zJrQ

-  there wasn't any cinematic's like in the videos

**Comment by Echinaceax** [comment]
**Also ...**
- completed this https://www.wowhead.com/quest=28261/deceivers-in-our-midst

**but...**

- cant complete
 
4 - https://www.wowhead.com/quest=28217/wanted-the-demon-hunter
video - https://www.youtube.com/watch?v=Hh6zU70dfJI

5 - https://www.wowhead.com/npc=47842/archdruid-navarax - reported #561

**Comment by Dranah** [comment]
Each quest separate report please, unless it is their interaction that is broken (one closing the other or wrong order)

**Comment by Echinaceax** [comment]
@Dranah 
Ive made all separate reports now :)
sorry for delay

**Comment by Dranah** [comment]
Thank you.
