### ISSUE TITLE
[Quest] Take it to the Tree  / quest order - Felwood 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#566]
npc - https://www.wowhead.com/npc=48127/darla-drilldozer

- broken quest 
- And missed up Quest Order

**Series order** 

![order](https://user-images.githubusercontent.com/39439201/51206477-6cf5ed80-1908-11e9-87f3-3236df05fdaa.jpg)

**Order i got** 

![all](https://user-images.githubusercontent.com/39439201/51206568-a3cc0380-1908-11e9-97fd-7e33614052d7.jpg)

1 - https://www.wowhead.com/quest=28333/its-time-to-oil-up 
2 - https://www.wowhead.com/quest=28334/a-flare-fight
3 - https://www.wowhead.com/quest=28336/slap-and-cap
4 - https://www.wowhead.com/quest=28339/is-your-oil-running
5 - https://www.wowhead.com/quest=28357/take-it-to-the-tree
6 - https://www.wowhead.com/quest=28370/wisp-napping

**missing quest from Series** 

https://www.wowhead.com/quest=28380/pikwik-in-peril
https://www.wowhead.com/quest=28373/timbermaw-hold

**will explain broken quest in next report below**

**Comment by Echinaceax** [comment]
quest - https://www.wowhead.com/quest=28339/is-your-oil-running
Item drop - https://www.wowhead.com/item=63519/crude-tarball

- This item drops before and after you complete the quest 
- quest is completed

**Comment by Echinaceax** [comment]
quest - https://www.wowhead.com/quest=28357/take-it-to-the-tree

_**Slay 8 Talonbranch Defenders**_

- Kills not giving kill credit

**Comment by Dranah** [comment]
Pikwik in peril is a follow-up you cannot get because 
5 - https://www.wowhead.com/quest=28357/take-it-to-the-tree
6 - https://www.wowhead.com/quest=28370/wisp-napping
cancel each other when you pick one up.
Timbermaw one requires a chain opened by Pikwik quest in order to be available.

**Comment by mfranca0009** [comment]
All set and should be giving all quests in proper order from Darla Drilldozer 👍  needs testing.
