### ISSUE TITLE
[Quest] Fire in the Hole! - ID 28368 -  Felwood

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#567]
Quest - https://www.wowhead.com/quest=28368/fire-in-the-hole
quest giver - https://www.wowhead.com/object=207104/master-control-pump
video - https://www.wowhead.com/quest=28368/fire-in-the-hole#videos:id=132329

**_Slay Grolvitar the Everburning_**

- grolvitar missing
https://www.wowhead.com/npc=48352/grolvitar-the-everburning

![not here](https://user-images.githubusercontent.com/39439201/51211291-5ace7c00-1915-11e9-9d1e-7fd74d13e9fd.jpg)

**Comment by Rushor** [comment]
![I](https://i.imgur.com/6stEJz3.jpg)

added
