### ISSUE TITLE
[Quest] Feathers for Nafien - ID 28395 - Felwood

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#568]
npc - https://www.wowhead.com/npc=15395/nafien

Location - https://www.wowhead.com/quest=28395/feathers-for-nafien#map
Item drop - https://www.wowhead.com/item=21377/deadwood-headdress-feather

- there are no mobs , all the camps is empty 
- So cant complete 

**Added more info** 
This quest was last quest i took before going into Winterspring 

the camp is meant to look like this 

![map](https://user-images.githubusercontent.com/39439201/51337124-9a68a580-1a86-11e9-8683-1be43df9680e.jpg)

camps have only 1 mob named Chieftain Bloodmaw
https://www.wowhead.com/npc=9462/chieftain-bloodmaw

![1 only](https://user-images.githubusercontent.com/39439201/51337161-b2402980-1a86-11e9-9d7c-0238583a3029.jpg)

Empty 

![emp](https://user-images.githubusercontent.com/39439201/51337232-d7cd3300-1a86-11e9-94c4-f31541cefbb9.jpg)
![empty](https://user-images.githubusercontent.com/39439201/51337240-dac82380-1a86-11e9-9850-8c5b06daaacd.jpg)

this is why the other quests with the related quests are broken/missing

**Comment by Dranah** [comment]
There's another deadwood camp on the south with lower level deadwood that are properly spawned
https://www.wowhead.com/npc=7155/deadwood-pathfinder
https://www.wowhead.com/npc=7153/deadwood-warrior
https://www.wowhead.com/npc=7154/deadwood-gardener

The item https://www.wowhead.com/item=21377/deadwood-headdress-feather should have a chance to drop from these mobs too, albeit with a lower drop rate than those on the north (16-18% versus 40-45)
The item however does not drop.
So 2 issues here

1) Missing NPCs in Felpaw (was reported in https://github.com/WoWManiaUK/Blackwing-Lair/issues/602)
2) Missing drop from NPCs generally

**Comment by Rushor** [comment]
drop added, and old condition prevented the drop
