### ISSUE TITLE
[NPC] Nafien - Felwood 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#569]
NPC - https://www.wowhead.com/npc=15395/nafien

missing quest line 

![no quest](https://user-images.githubusercontent.com/39439201/51213260-dd0d6f00-191a-11e9-8cc7-69e7c6c6f11a.jpg)

Series missing 

1 - https://www.wowhead.com/quest=28338/deadwood-of-the-north
 - missing mobs, poss related too #568

2 - https://www.wowhead.com/quest=28366/disarming-bears - completed
3 - https://www.wowhead.com/quest=28395/feathers-for-nafien - reported
4 - https://www.wowhead.com/quest=28521/speak-to-salfa - Completed
5 - https://www.wowhead.com/quest=28768/winterspring - Completed

**Comment by Echinaceax** [comment]
> The quest "Deadwood of the north" has prerequisites, have you completed all?

No the camps the Camps what empty, no mobs

**Comment by Dranah** [comment]
Nothing wrong with NPC, problematic quests are reported elsewhere.
