### ISSUE TITLE
[Talent] Mind Melt (passive)

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Blackwing-Lair#57]
**How it should work:**
>Description: Increases the damage done with your Shadow Word: Death by $s1% on targets at or below $14910s3% health, and when you deal damage with Mind Spike, the cast time of your next Mind Blast is reduced by $s2% lasting 6 sec. Mind Melt can stack up to 2 times.
![image](https://user-images.githubusercontent.com/14857593/38851087-8c34b17e-4229-11e8-9e73-e760799b719f.png)
![image](https://user-images.githubusercontent.com/14857593/38851034-451d88d8-4229-11e8-8aa4-32b4ac1a290c.png)

**How it works:**

1. The effect is not triggering on casting [[Mind Spike]](https://wow.gamepedia.com/Mind_Spike), Instead it is being triggered by casting  [[Devouring Plague]](https://wow.gamepedia.com/Devouring_Plague) [[Shadow Word: Pain]](https://wow.gamepedia.com/Shadow_Word:_Pain) [[Vampiric Touch]](https://wow.gamepedia.com/Vampiric_Touch)
2. The effect is not fading on use of [[Mind Blast]](https://wow.gamepedia.com/Mind_Blast)

**Comment by Keader** [comment]
Mind Blast is removing Effect here.
Mind Melt now proc with Mind Spike and not proc with other spells.
