### ISSUE TITLE
[Quest]  Winterfall Activity - ID 28522 - Winterspring

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#570]
Quest - https://www.wowhead.com/quest=28522/winterfall-activity
Items drop - https://www.wowhead.com/item=21383/winterfall-spirit-beads
npc - https://www.wowhead.com/npc=11556/salfa

**_Collect 10 Spirit Beads from Winterfall furbolg_**

- No beads are dropping

**Comment by Kitzunu** [comment]
fixed will send later

**Comment by Xman993** [comment]
still no beads are dropping

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/68411993-c545f680-018b-11ea-9d59-aa9b2b34af13.png)

**Comment by Rushor** [comment]
@Kitzunu the conditions broke it 

DELETE FROM `conditions` WHERE  `SourceEntry`=21383;
