### ISSUE TITLE
[Quest] The Arcane Storm Within - ID 28841 - Winterspring

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#571]
quest - https://www.wowhead.com/quest=28841/the-arcane-storm-within
quest item used - https://www.wowhead.com/item=66060/empowered-dreamcatcher

**_Use the Empowered Dreamcatcher to close 5 Arcane Tesseracts within Mazthoril._**

- Quest item casts fine but... 
- doesnt close the Tesseracts
- And quest item stuns me for 3 mins ..cant move, HS nothing
- Cant complete 

![not done](https://user-images.githubusercontent.com/39439201/51216830-054e9b00-1926-11e9-8fb2-bef3d1d10bc9.jpg)
![on 2](https://user-images.githubusercontent.com/39439201/51216840-0bdd1280-1926-11e9-9139-b56b3f8413c7.jpg)

**Comment by Echinaceax** [comment]
**New info** 

i have just noticed when i gave back a quest too -  https://www.wowhead.com/npc=10929/haleh

- the quest items are for different quests

**Comment by Rushor** [comment]
![I](https://i.imgur.com/q03M03z.jpg)

no only targets the Arcane Tesseract. will give credit and will be reavailable after 5 minutes.
