### ISSUE TITLE
[Quest] Rock Lobstrok! - ID 14379 - Desolace

### ISSUE THREAD

**Issue by gantor2** [WoWManiaUK/Blackwing-Lair#574]
- NPC's required to kill are not dropping the item needed. 
- NPC - Drysnap Crawler - ID 11562
- NPC - Drysnap Pincer - ID 11563
- ITEM - ID 49222

https://www.wowhead.com/quest=14379/rock-lobstrock

**Comment by Kitzunu** [comment]
fixed, will send later
