### ISSUE TITLE
[NPC] Khan Leh'Prah - phasing issue - Desolace

### ISSUE THREAD

**Issue by gantor2** [WoWManiaUK/Blackwing-Lair#576]
- NPC is missing and cannot start a long quest chain as a result.
- Quest relation - https://www.wowhead.com/quest=14312/an-introduction-is-in-order

**Comment by gantor2** [comment]
Ah quest order. I shouldn't of been allowed to pick it up.

**Comment by Dranah** [comment]
Nah, you should. This quest/stage is the beginning of chain, where he should still be visible, without any requirements. The problem is that the NPC is phased to the end of the chain, where at one point he moves elsewhere and is no longer visible on the original spot.
