### ISSUE TITLE
[Quest] Discrediting the Deserters - ID 27212 - Dustwallow Marsh

### ISSUE THREAD

**Issue by gantor2** [WoWManiaUK/Blackwing-Lair#577]
- Cannot interact with this NPC for a required quest interaction.
- Related Quest - https://www.wowhead.com/quest=11133/discrediting-the-deserters

**Comment by Dranah** [comment]
https://www.wowhead.com/quest=27212/discrediting-the-deserters this is the actual quest

**Comment by Saintres** [comment]
Tried to do this quest today. Still not working

**Comment by simonverse** [comment]
not working

**Comment by Rushor** [comment]
all fixed

select gossips, get credit

![I](https://i.imgur.com/q8or37e.jpg)
![I](https://i.imgur.com/NfDI69i.jpg)
