### ISSUE TITLE
[NPC] Lady jaina Proudmoore - ID 4968 - Dustwallow Marsh

### ISSUE THREAD

**Issue by gantor2** [WoWManiaUK/Blackwing-Lair#578]
Quest step requires to talk to her to teleport to stormwind. The option is missing.
Related Quest - https://www.wowhead.com/quest=27240/proof-of-treachery

**Comment by Dranah** [comment]
Quest is doable you just gotta get to Stormwind by yourself.

**Comment by gantor2** [comment]
but the second requirement is to click the portal which isnt there

**Comment by Dranah** [comment]
The quest shows complete when you pick it up. I tried going to Stormwind and i could hand it in...

**Comment by Rushor** [comment]
alright portal option added 

![I](https://i.imgur.com/LLqgxgL.jpg)
