### ISSUE TITLE
[Quest] Ashenvale Outrunners

### ISSUE THREAD

**Issue by Uncle1** [WoWManiaUK/Blackwing-Lair#58]
Quest ID=6503
The npcs objectives of the quest are missing, it means that u can't find any of them. 
Npc ID=12856
Please add some of them in Dor'Danil Barrow Den, This zone is the spawining area of this npcs.

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/38983547-806b6182-43bc-11e8-8838-51e170582429.png)


There are 20 of them in the right map region.
