### ISSUE TITLE
[Quest]Aces High! - Borean Tundra

### ISSUE THREAD

**Issue by Icytalon** [WoWManiaUK/Blackwing-Lair#580]
[Aces High!](https://cata-twinhead.twinstar.cz/?quest=13413) is a quest in [Borean Tundra](https://cata-twinhead.twinstar.cz/?zone=3537) , [Coldarra](https://cata-twinhead.twinstar.cz/?npc=32548) high above [The Nexus](https://cata-twinhead.twinstar.cz/?area=4120) [Corastrasza](https://cata-twinhead.twinstar.cz/?npc=32548) is the quest giver no problem so far however I have to kill 5 [Scalesworn Elite](https://cata-twinhead.twinstar.cz/?npc=32534) I have to speak to [Corastrasza](https://cata-twinhead.twinstar.cz/?npc=32548) to summon a drake called [Wyrmrest Skytalon](https://cata-twinhead.twinstar.cz/?npc=32535) to use it for kills which has no energy at all to use any of his abilities , I had to body pull 5 [Scalesworn Elite](https://cata-twinhead.twinstar.cz/?npc=32534) and kill them with my class abilities in order to complete it the [daily version](https://cata-twinhead.twinstar.cz/?quest=13414) comes upon complete the quest and the same issue occurs.
![wowscrnshot_011619_144306](https://user-images.githubusercontent.com/33905184/51249792-14246480-199d-11e9-943e-c6f268c5f657.jpg)

**Comment by Rushor** [comment]
moved to https://github.com/WoWManiaUK/Blackwing-Lair/issues/3238 generic issue
