### ISSUE TITLE
[Quest] Springing the Trap - ID 11969 - Coldarra

### ISSUE THREAD

**Issue by Icytalon** [WoWManiaUK/Blackwing-Lair#581]
[Springing the Trap](https://cata-twinhead.twinstar.cz/?quest=11969) is the quest name quest giver is [Raelorasz](https://cata-twinhead.twinstar.cz/?npc=26117) , I have to use [Raelorasz' Spark](https://cata-twinhead.twinstar.cz/?item=44950) near [Signal Fire](https://cata-twinhead.twinstar.cz/?object=194151). it's not working rather than light it it's explode on me quest can not be completed.
![wowscrnshot_011619_151159](https://user-images.githubusercontent.com/33905184/51251373-df66dc00-19a1-11e9-91a2-d820bb92758a.jpg)

**Comment by Saintres** [comment]
Tried to do the same quest  today and got the same resault as Icytalon. Not working.
