### ISSUE TITLE
[QUEST] Curtial the Darktail - ID 25709 - Blasted Lands

### ISSUE THREAD

**Issue by ghost** [WoWManiaUK/Blackwing-Lair#582]
Quest - https://www.wowhead.com/quest=25709/curtail-the-darktail
NPC - https://www.wowhead.com/npc=9540
Item - https://www.wowhead.com/item=57119
Item doesn't work has intended. you can throw it at the birds but they do not die therefore unable to complete the quest.

**Comment by Echinaceax** [comment]
Fixed here https://github.com/WoWManiaUK/Blackwing-Lair/issues/4426
