### ISSUE TITLE
[instance] The Nexus

### ISSUE THREAD

**Issue by Icytalon** [WoWManiaUK/Blackwing-Lair#583]
tried go in there to complete quests but there is a blue wall around all the tower can't get in from any entrance.
![wowscrnshot_011619_155041](https://user-images.githubusercontent.com/33905184/51253265-82215980-19a6-11e9-9556-6afd14ef4886.jpg)

**Comment by Dranah** [comment]
Cannot reproduce issue. No wall, i can enter without problems.
Judging by the load icon on your screen, perhaps you game hasn't downloaded that content yet.

**Comment by Echinaceax** [comment]
![ur ss](https://user-images.githubusercontent.com/39439201/53964659-0a42f600-40f0-11e9-8876-0dbcdf67253e.jpg)
