### ISSUE TITLE
[Quest] Lefty Loosey, Righty Tighty - doubled spawns - Borean Tundra

### ISSUE THREAD

**Issue by Icytalon** [WoWManiaUK/Blackwing-Lair#584]
[Lefty Loosey, Righty Tighty](https://cata-twinhead.twinstar.cz/?quest=11788) the quest giver is [Jinky Wingnut](https://cata-twinhead.twinstar.cz/?npc=25747) it asks to click 4 valves in 4 different locations [South Point Station Valve](https://cata-twinhead.twinstar.cz/?object=187987) , [North Point Station Valve](https://cata-twinhead.twinstar.cz/?object=187985) , [Mid Point Station Valve](https://cata-twinhead.twinstar.cz/?object=187986) and [West Point Station Valve](https://cata-twinhead.twinstar.cz/?object=187984)  to summon 4 different mobs [Twonky](https://cata-twinhead.twinstar.cz/?npc=25830), [ED-210](https://cata-twinhead.twinstar.cz/?npc=25831), [Max Blasto](https://cata-twinhead.twinstar.cz/?npc=25832), and [The Grinder](https://cata-twinhead.twinstar.cz/?npc=25833) to kill each time I use a valve a duplicate or a copy of the same mob spawn while one only should show up.
![wowscrnshot_011619_171649](https://user-images.githubusercontent.com/33905184/51258391-85224700-19b2-11e9-9317-8660f06113ef.jpg)

**Comment by Rushor** [comment]
fixed
