### ISSUE TITLE
[Quest] Blasted Lands: The Other Side of the World - faction req missing - Winterspring

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#585]
(As horde) 
npc - https://www.wowhead.com/npc=11118/innkeeper-vizzie

- Give me both horde and Ally quest

Ally - https://www.wowhead.com/quest=28857/blasted-lands-the-other-side-of-the-world

**Comment by Dranah** [comment]
https://www.wowhead.com/quest=28857/blasted-lands-the-other-side-of-the-world should be alliance-only
https://www.wowhead.com/quest=28858/blasted-lands-the-other-side-of-the-world should be horde-only
