### ISSUE TITLE
[Quest] Last Rites - ID 12019 - Borean Tundra 

### ISSUE THREAD

**Issue by Icytalon** [WoWManiaUK/Blackwing-Lair#586]
[Last Rites](https://cata-twinhead.twinstar.cz/?quest=12019) the quest giver is[ Thassarian](https://cata-twinhead.twinstar.cz/?npc=26170) I have to speak to him at the top floor of [Naxxanar](https://cata-twinhead.twinstar.cz/?area=4128) to start the event the problem is I can't communicate in any way with him instead i get the quest turn in which is not complete ofc.
![wowscrnshot_011619_185102](https://user-images.githubusercontent.com/33905184/51264659-ae959f80-19bf-11e9-9a1d-c1e5aa8de754.jpg)

**Comment by Saintres** [comment]
This quest stiull not working, cant start it

**Comment by mattm72980** [comment]
I just did the quest...not fixed

**Comment by jarvik76** [comment]
Still an issue as at 29th Sept

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/xgX28zs.jpg)
