### ISSUE TITLE
[Quest] There's Something Going On In Those Caves - ID 11694

### ISSUE THREAD

**Issue by Icytalon** [WoWManiaUK/Blackwing-Lair#587]
[There's Something Going On In Those Caves](https://cata-twinhead.twinstar.cz/?quest=11694) the quest giver is [Bixie Wrenchshanker](https://cata-twinhead.twinstar.cz/?npc=25705) the quest needs me to use [Bixie's Inhibiting Powder](https://cata-twinhead.twinstar.cz/?item=34915) while near [Den of Dying Plague Cauldron](https://cata-twinhead.twinstar.cz/?object=187879). the problem is I don't get credit for the quest to be complete
![wowscrnshot_011619_191530](https://user-images.githubusercontent.com/33905184/51266152-1a2d3c00-19c3-11e9-8bb9-23521989363b.jpg)

**Comment by Dranah** [comment]
Quest works but at the other cauldron in the other cave to the east.
