### ISSUE TITLE
[Quest] Turning the Earth - ID 28615 - Winterspring

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#589]
quest - https://www.wowhead.com/quest=28615/turning-the-earth
quest item used - https://www.wowhead.com/item=64637/tanrirs-overcharged-totem

**_Use Tanrir's Overcharged Totem to overload 4 Winterfall Earth Totems_**
**_Winterfall Earth Totem overloaded (4)_**

- Quest item casts but no credit given 
- Cant complete

![none](https://user-images.githubusercontent.com/39439201/51268789-1dbfc380-19c1-11e9-843c-07e30fe5ea9a.jpg)

**Comment by glcabatuan** [comment]
**Quest:**  http://cata.cavernoftime.com/quest=28615
**NPC/s:**  http://cata.cavernoftime.com/npc=49177
**Item/s:**  http://cata.cavernoftime.com/item=64637
**Object/s:** 
**Spell/s:**  http://cata.cavernoftime.com/spell=91647

**Current State:** 
usng the   http://cata.cavernoftime.com/spell=91647 of the http://cata.cavernoftime.com/item=64637 doesn't affect the  http://cata.cavernoftime.com/npc=49177 (doesn't overload it to ravage the nearby hostile)

**Expected State:** 

It should have overloaded the http://cata.cavernoftime.com/npc=49177 to explode and kill nearby
furlborg hostiles.


As shown in : https://youtu.be/sgVm8b-mlGA?t=8

**Comment by Echinaceax** [comment]
lol is what i stated 9 months ago

**Comment by glcabatuan** [comment]
Ahaha. Sorry , If this irritates you but I just more detailed information for debuggers could easily handle the bugs especially some bugs are regressing
