### ISSUE TITLE
[Quest] Let's See What You've Got, Zanzil

### ISSUE THREAD

**Issue by Uncle1** [WoWManiaUK/Blackwing-Lair#59]
QuestID=26534

When interact whit the npcs [Captain Bartholomew Softbeard (npc=43205), Orgus (npc=43204), Gmurgl(npc=43203)] it dont show any option for giving them the quest item [Jasper's Jungle Cooler(item=59030)].

![wowscrnshot_041918_180101](https://user-images.githubusercontent.com/35339001/39022561-bc262560-43fb-11e8-833a-0dc9f454d551.jpg)
![wowscrnshot_041918_180109](https://user-images.githubusercontent.com/35339001/39022562-bc45b51a-43fb-11e8-86f6-142b1bd0c408.jpg)
![wowscrnshot_041918_180104](https://user-images.githubusercontent.com/35339001/39022563-bc65a186-43fb-11e8-86b4-e2d21da88439.jpg)
How Should it works:
When u interact with the npcs this one should show u this dialog and when u use it the objectives will be completed
![image](https://user-images.githubusercontent.com/35339001/39022644-23fb1330-43fc-11e8-94ae-346cd2f7d5b4.png)
![image](https://user-images.githubusercontent.com/35339001/39022694-5fb758fc-43fc-11e8-997a-175c5416f3d7.png)
![image](https://user-images.githubusercontent.com/35339001/39022706-72705534-43fc-11e8-93f6-c0c5c8ecfc7f.png)

Then the pirate transform into a Ghoul and explode and the ogre and murloc die.

**Comment by fvicaria** [comment]
Very well described issue.
The screenshots helped me a lot to write the script. 
Keep it up!

**Comment by Uncle1** [comment]
Ty Janitor =D
