### ISSUE TITLE
[NPC]  Quel'dorei Spirit - Missing - Winterspring

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#590]
NPC - https://www.wowhead.com/npc=48659/queldorei-spirit

- Missing NPC

**Lost quests**
1- https://www.wowhead.com/quest=28535/descendants-of-the-high-elves
2- https://www.wowhead.com/quest=28518/legacy-of-the-high-elves

**Comment by Echinaceax** [comment]
Also missing Same area
NPC - https://www.wowhead.com/npc=48660/sindorei-spirit

**Lost quests** 
1- https://www.wowhead.com/quest=28519/pain-of-the-blood-elves
2- https://www.wowhead.com/quest=28536/the-curse-of-zin-malor

**Comment by Echinaceax** [comment]
- After looking into the missing Quest i listed above, ive noticed that the "spirit NPCs" quest start with 
NPC Kelek Skykeeper from Felwood - https://www.wowhead.com/npc=10920/kelek-skykeeper
- i will add more when ive traced it back a bit more

**Comment by Dranah** [comment]
These quests are in completely wrong order missing the prerequisites. Unsure when or how these NPCs should spawn so until the quest order is sorted, stays pending.

**Comment by Rushor** [comment]
added the two npcs, which require quest 28479 28534 28535 in order to see the creatures
