### ISSUE TITLE
[Quest] Blue-Feathered Necklace - ID 12558 - Winterspring

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#591]
Quest https://www.wowhead.com/item=12558/blue-feathered-necklace

- none starter 
- cant click 

![blue](https://user-images.githubusercontent.com/39439201/51272184-b8240500-19c9-11e9-9b73-a78e27dc1859.jpg)

**Comment by Dranah** [comment]
removed in cataclysm

**Comment by Dranah** [comment]
well, it needs to be removed from drop but thats no high prio
