### ISSUE TITLE
[Quest] Hellfire Fortifications - ID 10110 - Hellfire

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#595]
quest - https://www.wowhead.com/quest=10110/hellfire-fortifications

- pvp capture bar missing 
- Cant complete

![timer](https://user-images.githubusercontent.com/39439201/51276685-b5c7a800-19d5-11e9-84f6-a7177bd6c93d.jpg)
![pvp](https://user-images.githubusercontent.com/39439201/51276699-bd874c80-19d5-11e9-8f5c-e7afb3902b2e.jpg)

**Comment by Dranah** [comment]
This quest works fine. You need to be standing at the flag, not just anywhere near the tower.

**Comment by Echinaceax** [comment]
> This quest works fine. You need to be standing at the flag, not just anywhere near the tower.

Old server report as you know server has be wiped 4 times.
At the time of this report it wasnt working (as a pvper i know what was missing at the time of this report) 

check now ..and the bar is here thank you xxxx
