### ISSUE TITLE
[Quest] A Spirit Guide - ID 9410 - Hellfire

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#596]
quest - https://www.wowhead.com/quest=9410/a-spirit-guide
Quest item used - https://www.wowhead.com/item=23669/ancestral-spirit-wolf-totem

- spirit-wolf doesnt move once cast
- cant complete

![wolf](https://user-images.githubusercontent.com/39439201/51277068-d3e1d800-19d6-11e9-8dfa-f1070fdbb562.jpg)

**Comment by Rushor** [comment]
path will start now

![I](https://i.imgur.com/85ktpKT.jpg)
