### ISSUE TITLE
[Item/Quest] Crudely-Written Log - Starts: The Final Piece - Missing - Winterspring

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#597]
Quest drop - https://www.wowhead.com/item=12842/crudely-written-log

- This Item Begins a Quest (40) is Missing. 
- I killed High Chief Winerfall several times just now and didnt drop the quest book starter. 
- 68.27% drop rate
- Because of this missing i think this is why we are not in the right order for the other parts of the series. 
- This is the first part, and thats why im not getting the NPC spirit spawns (i think) for the loremaster list.

**series**
1. https://www.wowhead.com/quest=28471/the-final-piece
2. https://www.wowhead.com/quest=28472/words-of-the-high-chief
3. https://www.wowhead.com/quest=28479/the-ruins-of-keltheril
4. https://www.wowhead.com/quest=28513/pride-of-the-highborne
5. https://www.wowhead.com/quest=28534/descendants-of-the-highborne   - this one 
6. https://www.wowhead.com/quest=28518/legacy-of-the-high-elves - this one 
7. https://www.wowhead.com/quest=28535/descendants-of-the-high-elves - this one 
8. https://www.wowhead.com/quest=28519/pain-of-the-blood-elves - this one
9. https://www.wowhead.com/quest=28536/the-curse-of-zin-malor
10. https://www.wowhead.com/quest=28537/in-pursuit-of-shades
11. https://www.wowhead.com/quest=28848/trailing-the-spiritspeaker

**The ones ive listed with "this one" is in other report, they are connected i seen**

**Comment by Dranah** [comment]
Confirmed, isn't dropping with the required quest in your log either.

**Comment by Rushor** [comment]
item will drop now if quest is active :)
