### ISSUE TITLE
[NPC] Stonevault Wanderer - Badlands

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#599]
https://www.wowhead.com/npc=46713/stonevault-wanderer

These mobs are swarming around Agmond's End in Badlands.
Location: Map: 0 (Eastern Kingdoms) Zone: 3 (Badlands) Area: 345 (Agmond's End)
X: -7007.073242 Y: -3340.693115 Z: 241.726471 Orientation: 1.508712
The problem is they are untargetable and unattackable. They make it difficult to approach quest giver https://www.wowhead.com/npc=46664/dr-hieronymus-blam as you have no means to kill them.

original report by Echinaceax https://github.com/WoWManiaUK/Blackwing-Lair/issues/458

**Comment by Dranah** [comment]
No change here. NPCs still untargetable, unattackable, but will aggro to you.

**Comment by wow-mania** [comment]
Is that in dev?

**Comment by Echinaceax** [comment]
Tested on Dev 
https://www.wowhead.com/npc=2894/stonevault-shaman
https://www.wowhead.com/npc=2893/stonevault-bonesnapper

- No -  https://www.wowhead.com/npc=46713/stonevault-wanderer
in that location now (in Dev) 
- No https://www.wowhead.com/npc=46664/dr-hieronymus-blam
is that camp either now (in dev)

(in dev)

**camp is attackable now** 

![camp ok](https://user-images.githubusercontent.com/39439201/53356867-a6b90b80-392c-11e9-91f8-f7e29ec31588.jpg)

**Comment by Echinaceax** [comment]
tested 
- The Stonevault Wanderer dont attack you any more but...
- they are still dead :)

![cata there dead](https://user-images.githubusercontent.com/39439201/53363850-d45a8080-393d-11e9-9621-05338ccc75da.jpg)

**Comment by Dranah** [comment]
Well that solves the problem with getting to the quest NPC.
These mobs are not objective to anything to my knowledge so can wait with this one.

**Comment by Echinaceax** [comment]
1  down 1 to go exactly

**Comment by Kitzunu** [comment]
fixed
