### ISSUE TITLE
[Quest] Backdoor Dealings

### ISSUE THREAD

**Issue by Uncle1** [WoWManiaUK/Blackwing-Lair#60]
QuestID=26809

When you interact with the totem(npc=43252) this one dont show any option for starting the 2nd objective of quest
![wowscrnshot_041918_181552](https://user-images.githubusercontent.com/35339001/39022988-c0c19102-43fd-11e8-8bf5-37ae411eca42.jpg)
How should it work: When u interact with the Totem it should show this option,
![image](https://user-images.githubusercontent.com/35339001/39023057-23a2577a-43fe-11e8-8123-a151d4c28bf2.png)
after that u will get morphed to a bat and u will get to the place where Zanzil is
![image](https://user-images.githubusercontent.com/35339001/39023124-761f2b36-43fe-11e8-9c62-de746eca99db.png)
When u get to Zanzil he will start talking, after the dialog u will get tp back to the totem place and quest will get completed.
![image](https://user-images.githubusercontent.com/35339001/39023136-85194cd4-43fe-11e8-8073-7be01c23d87a.png)

**Comment by fvicaria** [comment]
I needed to know the name of the bat npc or the spell that is cast on the player to finish this one correctly.

**Comment by fvicaria** [comment]
Just giving full credit at the totem for now.

**Comment by sarahkay88** [comment]
@fvicaria  this may be what your looking for 
https://www.wowhead.com/spell=80802/backdoor-dealings-wings-of-hireek-cosmetic-1
https://www.wowhead.com/spell=80789/wings-of-hireek
https://www.wowhead.com/npc=43241/wings-of-hireek
