### ISSUE TITLE
[Quest] Deadwood of the north - ID 28338 - Felwood

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#602]
https://www.wowhead.com/quest=28338/deadwood-of-the-north

- Missing mobs missing
- Camps are empty

https://www.wowhead.com/npc=7156/deadwood-den-watcher
https://www.wowhead.com/npc=7158/deadwood-shaman
https://www.wowhead.com/npc=7157/deadwood-avenger

**Comment by Rushor** [comment]
pooling is fucked up because of ore pooling
