### ISSUE TITLE
[Spell/Warlock] Drain Soul - ID 1120

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#603]
Spell - http://www.wow-mania.com/armory/?spell=1120

- How it works atm: replenishes 3 shards on each and every tick, before Mob dies

![before death](https://user-images.githubusercontent.com/39439201/51341054-bf621600-1a90-11e9-9502-ef2310ab1b87.jpg)

- How it should work: replenish 3 shards when target dies

![sd](https://user-images.githubusercontent.com/39439201/51341072-c721ba80-1a90-11e9-929a-03e7af629fbe.jpg)

**Comment by Keader** [comment]
Fixed in dev
