### ISSUE TITLE
[Spells] Seed of corruption not working

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Blackwing-Lair#605]
Impemented spell seed of corruption.

**Comment by Dranah** [comment]
The spell deals dot damage but does not explode when the target dies or took the necessary damage.

**Comment by Keader** [comment]
What ?
I will look again
Work fine in my server.

**Comment by Keader** [comment]
Tested again now, and it explode when target took necessary damage.
But was not working when target die xD
Now should work for both.
It was a issue that make always give corruption when explode (even when has no soulburn), fixed too
