### ISSUE TITLE
[Talent] Zealotry - ID 85696

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Blackwing-Lair#606]
Spell is consuming Holy Power, when says it doesn't in its description:

"Your Crusader Strike generates 3 charges of Holy Power per strike for the next 20sec. Requires 3 Holy Power to use, but does not consume Holy Power."

**Comment by Keader** [comment]
Fixed.

**Comment by Dranah** [comment]
No longer consumes the HP.
