### ISSUE TITLE
[Spell] Divine Storm - ID 53385

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Blackwing-Lair#607]
Is generating Holy Power without attempting to hit an enemy, should only generate Holy Power if you hit 4 enemies or more with the spell.

"
Divine Storm
An instant attack that causes 100% weapon damage to all enemies within 8 yards. The Divine Storm heals up to 3 party or raid members totaling 25% of the damage caused, and will grant a charge of Holy Power if it hits 4 or more targets.
"

**Comment by Keader** [comment]
Test now

**Comment by Dranah** [comment]
Now only generates holy power if 4+targets are hit.
However, I noticed another issue which is that the empty casts (DS used with no enemy around) are capable of procing trinkets that proc when you deal damage, even though there's no damage dealt.
This affects stacking trinkets too, such as the BIS trinket from spine, you can stack it to 10 with DS before entering combat with anything.

**Comment by Keader** [comment]
gime a trinket entry to check it.

**Comment by Dranah** [comment]
item=77200
item=50355

Both trinkets work same way. One is old wotlk content trink, other is new from Spine that many will use in live cata.

**Comment by Keader** [comment]
Check now @Dranah

**Comment by Dranah** [comment]
Good now :) only proc if it hits an enemy.
