### ISSUE TITLE
[Talent] Sanctity of Battle - ID 25956

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Blackwing-Lair#608]
Haste isn't reducing the cooldown of Crusader Strike nor Divine Storm, whether item or buff.

"Haste effects lower the cooldown of your Crusader Strike and Divine Storm abilities.".

**Comment by Keader** [comment]
Fixed, try now.
PS: Maybe it can help...

Use macro targeting you

```
.aura 109804
.aura 109802
.aura 109787
.aura 109789
``` 

This aura add some hast in you character, and you can see the effect of hast in cooldown.

**Comment by Dranah** [comment]
No change my cooldown is 4,5sec fix on both abilities.
Nor auras, nor gear changes it.

**Comment by Keader** [comment]
![image](https://user-images.githubusercontent.com/7120913/51675868-b521a980-1fb3-11e9-9dca-6792c56dbe69.png)
Printed in game now.

I put comments to show you that it's working.
Cooldown is changed by haste.
Maybe server was not builded when you tested.

**Comment by Dranah** [comment]
Dear lord what kind of test method is that.
Mouse over the god damn tooltip it keeps showing 4,5sec and if you use the ability, it triggers 4,5sec cd.
I even counted it with stopwatch.

**Comment by Dranah** [comment]
Seems tooltip can't be fixed for now (as per keader).
As-is then, the cooldown itself is modded properly.
