### ISSUE TITLE
[NPC] Fel Soldiers - ID 18944 - Hellfire

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#609]
NPC - https://www.wowhead.com/npc=18944/fel-soldier

- To many NPCs
- Problem with Spawns

![not normal](https://user-images.githubusercontent.com/39439201/51346675-85980c00-1a9e-11e9-9fb0-92176667d4d1.jpg)

**Comment by Dranah** [comment]
Interesting, to me this area was empty... need to find out what triggers their spawn.

**Comment by Echinaceax** [comment]
> Interesting, to me this area was empty just now when i went here... need to find out what triggers their spawn.

Seriously, wow.
yes please that was insane i could even move for the lag

**Comment by Dranah** [comment]
The issue appears to be that the defenders ignore this specific mob. They attack and kill others (wrathguards and infernals) properly during the event, but they do not touch Fel Soldiers. So as the event is continuous, it's just more and more of them spawning.
Related issue, some of the defenders appear to attack opposite-faction players.  https://github.com/WoWManiaUK/Blackwing-Lair/issues/624

**Comment by Echinaceax** [comment]
yes ...coz i went to check again just now and its full to me again , just lower down the stairs 

![just again](https://user-images.githubusercontent.com/39439201/51390574-faffed00-1b2f-11e9-8877-2ab62ae5c403.jpg)

**Comment by Dranah** [comment]
No change here
Fel soldiers are still ignored by the NPCs, so over time they accumulate.
Players are still attacked by neutral opposite faction NPCs

**Comment by Echinaceax** [comment]
@Kitzunu - mass amount fixed but did you remove all ?
including the fel guards that are meant to be there ?

Its totally empty now 

![no at all now](https://user-images.githubusercontent.com/39439201/57948154-2ed20000-78e1-11e9-9206-c62dcb3a024e.jpg)

**Comment by Kitzunu** [comment]
All I did was to remove a flag that made NPC's not being able to attack them
