### ISSUE TITLE
[NPC] Drizle - ID 47556 - Missing - Felwood

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#611]
NPC - https://www.wowhead.com/npc=47556/drizle

- NPC is missing

**Comment by zippoking** [comment]
NPC is still not at his position. Only the yellow quest marker is shown on the minimap.

![Drizle - how it is](https://user-images.githubusercontent.com/18005338/58763342-b5314780-8559-11e9-90ce-9a3d88ff6ad8.png)

**Comment by glcabatuan** [comment]
**Quest:** 
**NPC/s:**  http://cata.cavernoftime.com/npc=48481
**Item/s:** 
**Object/s:** 
**Spell/s:** 

**Current State:** 
  Still Missing...

**Expected State:**

**Comment by Rushor** [comment]
he moves away after some time. he should stay on the ground
