### ISSUE TITLE
[NPC] Spirit Healer - Missing - Merchant Square Graveyard - Gilneas

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#612]
https://www.wowhead.com/npc=6491/spirit-healer
Position
X: -1389.887207 Y: 1370.140625 Z: 35.752079 Orientation: 0.000000
Map: 654 (Gilneas2) Zone: 4755 (Gilneas City) Area: 4756 (Merchant Square)

Spirit healer missing from the graveyard.

**Comment by Pitmaster** [comment]
Also missing at The Blackwald and the Stagecoach crash site (The default HS location)

Pitfourth: worgen warlock
