### ISSUE TITLE
[Quest] Take it to the tree - ID 28357 - Felwood

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#619]
quest - https://www.wowhead.com/quest=28357/take-it-to-the-tree

_**Slay 8 Talonbranch Defenders**_

- Kills not giving kill credit

**Comment by realdude19** [comment]
Added link to NPC's that are required to kill for quest objective.
[
Talonbranch Defenders](https://www.wowhead.com/npc=48452)
