### ISSUE TITLE
[Quest] Helboar, the Other White Meat - ID 9361 - Hellfire

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#620]
Quest - https://www.wowhead.com/quest=9361/helboar-the-other-white-meat
Quest item - https://www.wowhead.com/item=23248/purified-helboar-meat
Quest item used - https://www.wowhead.com/item=23268/purification-mixture

- Tainted Helboar Meat isnt dropping from Deranged Helboars
- Cant complete

**Comment by Rushor** [comment]
requires quest 9361 to be active to drop

**Comment by karteil** [comment]
Sorry to re-open it but I have tried the quest with my main character, abandoned it three times but nothing happened. I had opened a ticket and a gently GM helped me, then I tried the same quest with another character and it doesn't work. 
https://www.wowhead.com/quest=9361/helboar-the-other-white-meat


**What is happening:**
I killed many [Deranged Helboar](https://www.wowhead.com/npc=16863/deranged-helboar) but no one dropped the requested item [Tainted Helboar Meat](https://www.wowhead.com/item=23270/tainted-helboar-meat) 

**What should happen:**
Killing [Deranged Helboar](https://www.wowhead.com/npc=16863/deranged-helboar) should drop [Tainted Helboar Meat](https://www.wowhead.com/item=23270/tainted-helboar-meat) item 

Thank you for your hard work!
