### ISSUE TITLE
[PET] Hunter pet

### ISSUE THREAD

**Issue by gantor2** [WoWManiaUK/Blackwing-Lair#621]
My pet went away and nothing i do brings it back. Alliance. Character name jigy. tried clearing cache and reviving and all in between. Not sure what to say on this one its weird.

**Comment by Dranah** [comment]
What type of creature was it? What stance he was set to (passive/defensive etc)? Which area did this happen in? What talent build were you specced to?
Those could help.
It may be a personal glitch as well, but if you give some info I can try to see if i can reproduce. Mounting alone does not do this.

**Comment by gantor2** [comment]
Basic starter cat pet, dustwallow marsh, marksman spec

**Comment by gantor2** [comment]
Gonna try again when I get home

**Comment by gantor2** [comment]
I looked into it further. i was able to tame a new pet in its slot, the game registered the old pet as 100% gone. when i tried to summon it said you do not have a pet. had to get a new one.
