### ISSUE TITLE
[NPC] Jarroc Torn-Wing - ID 41164 - Blasted lands (low prio) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#626]
npc https://www.wowhead.com/npc=41164/jarroc-torn-wing

- Double spawned 

![jar](https://user-images.githubusercontent.com/39439201/51394221-1d970380-1b3a-11e9-95f3-3d85e01a0511.jpg)

**Comment by Kitzunu** [comment]
@Rushor Still 2 spawns, I think, if I have learnt correct one of the GUID's should be removed qq
![image](https://user-images.githubusercontent.com/24550914/54474076-959f4400-47e0-11e9-8cd2-ac2e0b5da2aa.png)
