### ISSUE TITLE
[Talent] Art of War - ID 87138

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Blackwing-Lair#629]
Doesn't proc at all, tested 50 autoattacks with a one handed weapon, even a 2handed.

R2 ID: 53488
R1 ID: 53486

"Your autoattacks have a 7%/14%/20% chance to make your next Exorcism instant, free and cause 100% additional damage."

**Comment by Keader** [comment]
Test now please.

**Comment by Dranah** [comment]
Procs fine now.
