### ISSUE TITLE
[Talent] Battle Trance - ID 85742

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Blackwing-Lair#633]
Does not proc. Tested in all 3 stances over 170  times total, did not proc once with 3/3 in the talent.

ID; 85742

![image](https://user-images.githubusercontent.com/33989250/51403262-cfb3d880-1b04-11e9-9307-b7ea85fbd97e.png)

**Comment by Keader** [comment]
Fixed.

**Comment by Dranah** [comment]
Proc'd as intended now.
