### ISSUE TITLE
[Talent] Blood Craze - ID 16492

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Blackwing-Lair#637]
![bloodcraze](https://user-images.githubusercontent.com/33989250/51418905-48358c00-1b3b-11e9-9d45-d9ad983cf851.png)

How it should work; The talent says that it should have a 10% chance to proc a heal for 3% of your maximum health over 5 seconds.

How it currently works; It heals for 6 % of your maximum HP each second, for 5 seconds

![bloodcrazehps](https://user-images.githubusercontent.com/33989250/51419089-a9aa2a80-1b3c-11e9-99e3-8d048ad10866.png)

My current HP is roughly 102.1k as shown below, meaning the heal should be around 3063 HP total over 5 seconds or 612HP per second. Initially this may seem low, but remember this does not have an ICD.

![bloodcrazehp](https://user-images.githubusercontent.com/33989250/51419092-b169cf00-1b3c-11e9-913e-949b05c6eae9.png)

To reproduce, take the talent and get hit by any form of damage a few times. it will then proc healing you.

**Comment by Keader** [comment]
Bad dbc data.
Fixed.

**Comment by Dranah** [comment]
Now the effect regens 3% of total health every 1sec for 5sec.
How it should work: It should be regening 3% **total** over 5sec , meaning 0,6% every 1sec.

**Comment by Dranah** [comment]
Something went off. I get 63% of my total health every second now.
Feels like you tried to add 0,6, became 60 and was added to the previous 3.

**Comment by Dranah** [comment]
Spell now procs but doesn't heal anything at all.

**Comment by Dranah** [comment]
Good now.
