### ISSUE TITLE
[Spell] Execute - ID 5308

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Blackwing-Lair#638]
![execute](https://user-images.githubusercontent.com/33989250/51419311-45886600-1b3e-11e9-92d7-8a2c4797c1fd.png)

How it should work; The spell can consume up to 20 ADDITIONAL rage, meaning 30 rage will be consumed and the damage will be nearly doubled as shown in the tooltip

Currently, Execute is either generating 10 rage, or only consuming 20, either way you look at it It's not receiving a proper damage increase regardless.

My Execute hits for 3308 when I use it with 10 rage and with 100 rage, there's no difference
![executedmg](https://user-images.githubusercontent.com/33989250/51419493-bbd99800-1b3f-11e9-8747-ba249033fbd6.png)

**Comment by Keader** [comment]
Test now.

**Comment by Dranah** [comment]
Works as intended now.
