### ISSUE TITLE
[Quest] Some People Just Need Killing - ID 25681 - Blasted lands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#639]
quest - https://www.wowhead.com/quest=25681/some-people-just-need-killing
video - https://www.youtube.com/watch?v=gjVtNCgzqsQ
npc  to kill - https://www.wowhead.com/npc=41173/chief-prospector-hondo

**_Slay Chief Prospector Hondo. Use the Inconspicuous Box to disguise yourself along the way._**

- The boxes are clickable but they dont work (no disguise appears)

![box](https://user-images.githubusercontent.com/39439201/51419733-0e8d7100-1b8d-11e9-8133-b4ea4ba9a951.jpg)

tested 
- I ran to the location to see if i could still "kill him"

![not here 2](https://user-images.githubusercontent.com/39439201/51419729-07fef980-1b8d-11e9-99ad-bf879023e250.jpg)

- NPC wasnt there

- not sure if its because the disguise didnt work or its a missing NPC problem

**Comment by Rushor** [comment]
will simply add the creature to the place
