### ISSUE TITLE
[Talent] Meat Cleaver - ID 12950

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Blackwing-Lair#640]
Spell ID - 85739
Talent ID - 12950

![meatcleaver](https://user-images.githubusercontent.com/33989250/51419880-c8abbb00-1b42-11e9-9835-437e7e531f3c.png)
![meatcleaver](https://user-images.githubusercontent.com/33989250/51419906-f55fd280-1b42-11e9-8f1b-aafc91f3f7ce.png)

How it should work; Cleave and Whirlwind both proc it allowing you to stack it to 3

How it currently works; Cleave and Whirlwind both proc it as intended, but Bloodthirst will also proc it, which it shouldn't

Bloodthirst Spell ID - 23881 

Reproduce by using Bloodthirst on any target with this talent selected. Dummy or any random mob.

**Comment by Keader** [comment]
Fixed.

**Comment by Dranah** [comment]
No longer proc'd by Bloodthirst.
