### ISSUE TITLE
[Spell] Bloodthirst - ID 23881

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Blackwing-Lair#641]
![bloodthirst](https://user-images.githubusercontent.com/33989250/51420100-51772680-1b44-11e9-9b5f-a6b5800ff698.png)

How it should work; The heal should be 0.5% of the casters HP. My HP being 112.3k the heal should be around 561-562
![bloodthirsthp](https://user-images.githubusercontent.com/33989250/51420113-723f7c00-1b44-11e9-9b61-935d99f36923.png)

Currently the heal is 10x what it should be, healing 5% of the casters HP rather than 0.5%

![bloodthirstheal](https://user-images.githubusercontent.com/33989250/51420142-b599ea80-1b44-11e9-8d4c-640e62fce719.png)

**Comment by gantor2** [comment]
Do you have any perks that modify it?

**Comment by gantor2** [comment]
Actually ignore that, nothing would modify it that much. It’s broken like ya said

**Comment by Keader** [comment]
Fixed.

**Comment by Kitzunu** [comment]
works.
Tested with 100000 HP
0.5% of 100000 = 500
![image](https://user-images.githubusercontent.com/24550914/53835981-0f3c6400-3f8f-11e9-970f-aab6d990ade6.png)

**Comment by Cenasty** [comment]
Another (might) bug on this spell, the irrelevant amount of damage it deal.

Here is the Dr.Damage, can you check it in the Database please ?

https://puu.sh/DXIyF/f59c1cbd66.png
https://puu.sh/DXIDm/8e52be04f8.png

**Comment by Eirolla** [comment]
Please make a new Github post for other bugs.
