### ISSUE TITLE
[NPC] Void Baron Galaxis /  Void Servant - ID 16939/19599 - Hellfire  (low prio)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#642]
1. npc - https://www.wowhead.com/npc=16939/void-baron-galaxis
2. npc - https://www.wowhead.com/npc=19599/void-servant

- both double spawned

![double](https://user-images.githubusercontent.com/39439201/51421151-4818a900-1b9a-11e9-92aa-0950e55e79e0.jpg)

- Completed quest  though

https://www.wowhead.com/quest=10295/from-the-abyss

- No other issues

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/cncxyCT.jpg)
