### ISSUE TITLE
[Spell] Seal of Righteousness - ID 20154

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Blackwing-Lair#643]
Seal of Righteousness is proccing from Hammer of Wrath, though it isn't a meele attack.
![sor](https://user-images.githubusercontent.com/16576459/51421941-73f25980-1baf-11e9-98da-e329aec18c91.png)

"Fills the Paladin with holy spirit for 30min, granting each melee attack x additional Holy damage."

Hammer of Wrath ID: 24275

**Comment by Keader** [comment]
Well...
it's melee attack haha
```
DamageClass = 2 (SPELL_DAMAGE_CLASS_MELEE)
```
