### ISSUE TITLE
[Spell] Forbearence - ID 25771

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Blackwing-Lair#645]
Should be applied as a debuff when using Divine Shield or Hand of Protection, currently you can cast both at the same time.

Lay on Hands on the other hand is working fine and applies Forbearence.

"Cannot be affected by Divine Shield, Hand of Protection or Lay on Hands."

Hand of Protection ID: 1022
Divine Shield ID: 642

**Comment by Keader** [comment]
Fixed.

**Comment by Dranah** [comment]
Both effects now properly apply forbearance.
