### ISSUE TITLE
[Spell] Ardent Defender - ID 31850

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Blackwing-Lair#646]
Gets dispeled right after being hit once/taking damage.

"Reduce damage taken by 20% for 10sec. While Ardent Defender is active, the next attack that would otherwise kill you will instead cause you to be healed for 15% of your maximum health."

**Comment by Dranah** [comment]
Consumed by any attack with no healing done.

**Comment by Keader** [comment]
Backing to work here 👍 
Fixed.

**Comment by Dranah** [comment]
The spell now only proc off attacks that would land a killing blow on the pally.
The problem is, they still land a killing blow. The damage should be prevented, and the paladin healed.
Currently, the paladin is healed for 15% and then still takes the killing blow.

**Comment by Keader** [comment]
What you mean ?

**Comment by Keader** [comment]
Test now.

**Comment by Dranah** [comment]
The spell now properly prevents a killing blow.
