### ISSUE TITLE
[Talent] Acts of Sacrifice - ID 85795

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Blackwing-Lair#647]
Cleansing yourself under a slow/impair isn't removing the effect while having the talent. (Tested on Slow only for now).

"Reduces the cooldown by 20% and mana cost by 20% of your Hand of Freedom, Hand of Salvation and Hand of Sacrifice. In addition, your Cleanse will remove one movement impairing effect if cast on yourself."

Rank 1 ID: 85446
Cleanse ID: 4987

**Comment by Keader** [comment]
Fixed.

**Comment by Dranah** [comment]
Works.
