### ISSUE TITLE
[Talent] Protector of the Innocent - ID 20140

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Blackwing-Lair#648]
Is not healing self by healing the target with any heal.

"Casting a targeted heal on any target, except yourself, also heals you for x."

Rank 1 ID: 20138
Rank 2 ID: 20139

**Comment by Keader** [comment]
Fixed.

**Comment by Dranah** [comment]
Spell now heals however healing value does not match the tooltip. (is less)
I couldn't find a formula for this anywhere, so it's difficult to tell how much it should heal, but I can already see it's healing doesn't scale with ICC buff at all, which makes me wonder if it will have scaling issues later on as well.

**Comment by Dranah** [comment]
Effect scales with healing boosts now.
