### ISSUE TITLE
[Spell] Exorcism - ID 879

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Blackwing-Lair#649]
Spell is applying Glyph of Exorcism DoT as a baseline, but the glyph is also not scaling with 20% of the Exorcism damage done (seems to be base damage?)

"Your Exorcism causes an additional 20% of its damage over 6sec"

Glyph of Exorcism ID: 41103

**Comment by Ovahlord** [comment]
https://github.com/Ovahlord/TrinityCore/commit/133b3180e93098ada8e9360c51a1f6bfbd7bbd96
Hi @Keader darling :P

**Comment by Keader** [comment]
Ty @Ovahlord (Elon darling :D )

**Comment by Dranah** [comment]
Works as intended now.
