### ISSUE TITLE
[Spell] Inner fire - Inner will

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Blackwing-Lair#65]
**How it should work:**
According to tooltips, you can only have Inner will **OR** Inner fire active at a time.

**How it works:**
Both inner fire and Inner will can be active at a time.
![image](https://user-images.githubusercontent.com/14857593/39091603-67cf59d8-460c-11e8-9f9a-5073ca10473a.png)
![image](https://user-images.githubusercontent.com/14857593/39091605-6f2e694e-460c-11e8-9cc8-bebb98c2685d.png)
![image](https://user-images.githubusercontent.com/14857593/39091608-78cabc50-460c-11e8-93e6-4382fd879ce0.png)

**Comment by Keader** [comment]
Fixed.
