### ISSUE TITLE
[Talent] Impending Victory - ID 80129

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Blackwing-Lair#651]
![impendingvictory](https://user-images.githubusercontent.com/33989250/51422225-f81cf080-1b5f-11e9-8d15-3effcd41e36b.png)

Currently the proc of Impending Victory is just giving the normal Victorious buff allowing for a normal Victory Rush after using Devastate on a target below 20% hp

![victorious](https://user-images.githubusercontent.com/33989250/51422250-6f528480-1b60-11e9-83a5-a365f75135f1.png)
This is the buff given for both a normal Victorious and the supposed 5% heal victory rush.

![victoryrush](https://user-images.githubusercontent.com/33989250/51422251-711c4800-1b60-11e9-80e0-51f96bb4b01f.png)

![impendingvictoryheal](https://user-images.githubusercontent.com/33989250/51422254-737ea200-1b60-11e9-8a67-58f5ee782b0a.png)
As you can see, I'm able to heal 20% of my 99.2k hp with 2 victory rushes that came from the talent proc off Devastate.
![impendingvictoryhp](https://user-images.githubusercontent.com/33989250/51422271-aaed4e80-1b60-11e9-9f28-31c7c4200cc5.png)

**Comment by Dranah** [comment]
Works as intended now.
