### ISSUE TITLE
[Quest] Attune the blood stone - missing - Blasted Lands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#653]
QUEST - https://www.wowhead.com/quest=26158/attune-the-bloodstone
NPC - https://www.wowhead.com/npc=42298
Quest is missing on not in correct order

this makes it impossible to use item: https://www.wowhead.com/object=203180/bloodstone-teleporter
when completing other quests.
My quest chain started at the amulet of allisatrj : https://www.wowhead.com/quest=26167/the-amulet-of-allistarj

**Comment by Dranah** [comment]
I am near certain the quest order is messed up but that does not mean the quest may not be missing as well.
https://www.wowhead.com/quest=26157/kasim-sharim should be the prerequisite for this one in the chain, did you hand this in?

**Comment by sarahkay88** [comment]
nope I am either unable to pick it up due to a quest reported or its not there

**Comment by sarahkay88** [comment]
So @Dranah  you were right the issue appears to be the quest order. this quest is there and is completable so you can close if you like. However the item is the issue it does not work has intended so I will do a fresh report for that.

**Comment by Dranah** [comment]
So if i understand well you were able to pick up Attune the bloodstone once you completed the prereq.
The item is however bugged and is reported elsewhere.

**Comment by sarahkay88** [comment]
That's correct.
