### ISSUE TITLE
[Quest] The Amulet of sevine - ID 26166 - blasted lands

### ISSUE THREAD

**Issue by ghost** [WoWManiaUK/Blackwing-Lair#654]
Quest - https://www.wowhead.com/quest=26168/the-amulet-of-sevine
NPC - https://www.wowhead.com/npc=42298
NPC - Salt -flop: https://www.wowhead.com/npc=41265/salt-flop doesn't supply you with the item:
Sevin's Amulet:https://www.wowhead.com/item=10754.

Quest incompletable.

**Comment by zippoking** [comment]
Confirmed.
He doesn´t have the dialogue to get the amulet.

How it is:
![Amulet of Sevine - how it is](https://user-images.githubusercontent.com/18005338/59131222-1306ca80-8972-11e9-98be-04962a863ca1.png)

How it should be:
![Amulet of Sevine - how it should be](https://user-images.githubusercontent.com/18005338/59131221-1306ca80-8972-11e9-8b8e-e8925157daff.png)

**Comment by Echinaceax** [comment]
fixed here https://github.com/WoWManiaUK/Blackwing-Lair/issues/4270
