### ISSUE TITLE
[Talent] Thunderstruck - ID 80980

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Blackwing-Lair#656]
![thunderstruck](https://user-images.githubusercontent.com/33989250/51433721-b5adef00-1c05-11e9-8503-189414565d7d.png)
![thunderstruckspell](https://user-images.githubusercontent.com/33989250/51433739-e2620680-1c05-11e9-992a-0f80130aaefe.png)

Currently the Thunderstruck talent is applying 1 stack for each enemy hit, while it should be applying once per use of Thunderclap (Spell ID 6343)

Pulling 1 enemy or 3 enemies with Thunderclap should add one stack per Thunderclap use.

Wowhead post on the talent itself can no longer be found but here's a link of people complaining about how it works from 2010 when it was active
https://www.wowhead.com/forums&topic=166790/thunderstruck

**Comment by Keader** [comment]
Fixed.
