### ISSUE TITLE
[Spell] Enraged Regeneration - ID 55694

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Blackwing-Lair#658]
![enragedregeneration](https://user-images.githubusercontent.com/33989250/51433886-27883780-1c0a-11e9-9315-90a2393344b1.png)

Currently Enraged Regeneration can sometimes be casted when not Enraged.

![enrage](https://user-images.githubusercontent.com/33989250/51433907-a7160680-1c0a-11e9-91a8-f1437e771012.png)
![notenraged](https://user-images.githubusercontent.com/33989250/51433909-aa10f700-1c0a-11e9-86d2-aafcaf5ad9dd.png)

Sometimes this means only 1 tick of healing then it completely drops off and goes on cooldown.
Enrage is also able to be reapplied during Enraged Regeneration.
![enragedenrage](https://user-images.githubusercontent.com/33989250/51433923-13910580-1c0b-11e9-9907-9e537a31a1bc.png)

**Comment by Dranah** [comment]
I need reproduce steps for "sometimes be cast when not enraged"
The spell cannot be simply triggered with no buffs on you, so I suppose there's some non-enrage buff it can work with?

**Comment by bluemonstrr** [comment]
I believe it may have been caused by the lagging on the server

Currently it seems I'm unable to reproduce it
