### ISSUE TITLE
[Talent] Surge of Light

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Blackwing-Lair#66]
**How it should work:**
> Description: You have a $h% chance when you Smite, Heal, Flash Heal, Binding Heal or Greater Heal to cause your next Flash Heal to be instant cast and cost no mana.
![image](https://user-images.githubusercontent.com/14857593/39091638-31d62b12-460d-11e8-8095-e23822159fee.png)

**How it works:**
- Casting any of the spells named in tooltip, will not consume the effect of the talent.Though it will be consumed after its timer goes off.  Pretty much the same issue as #52  #48  #42 
- The talent procs on pretty much any spell which should be only on (Smite, Heal, Flash Heal, Binding Heal or Greater Heal) , but according to tests done, it is being triggered by Levitate,Renew and even shadow word:death. I didn't check more spells.

**Comment by Keader** [comment]
Fixed.
