### ISSUE TITLE
[NPC] Bat Rider Guard - 15242 - Zangermarsh (low prio)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#660]
npc - https://www.wowhead.com/npc=15242/bat-rider-guard

- Friendly Bat rider guards bugged 
- for a sec they put you in combat (and screech) 

![bat attack](https://user-images.githubusercontent.com/39439201/51601198-07a38d00-1f04-11e9-9efc-436600edd80f.jpg)
![map zanger](https://user-images.githubusercontent.com/39439201/51601210-10945e80-1f04-11e9-80be-4111cd95d4f4.jpg)
![bats](https://user-images.githubusercontent.com/39439201/51601220-14c07c00-1f04-11e9-9643-8a5707375360.jpg)

**Comment by Echinaceax** [comment]
Seems like there is a bigger problem going on with the combat bug 
Kit made a new report for me about the problem #805

(issues could be connected) some how 
Ally Gryphons riders 
Horde Bat riders

**Comment by Dranah** [comment]
May have something to do with the fact these bat riders are in fact giant totems that you can only see in GM phase.
![WoWScrnShot_031619_210838](https://user-images.githubusercontent.com/31132743/54481039-16396100-4830-11e9-9ca2-58639c00f2b8.jpg)
Manually spawning a bat rider elsewhere does not produce the bug, however spawning one of those totems does.
NPC id for the giant totems that cause the problem:
22001
22002

**Comment by Echinaceax** [comment]
Oh nice work dranah, we have been trying to figure out why :)

**Comment by sarahkay88** [comment]
same issue at Thrallmar - just outside the inn

**Comment by Rushor** [comment]
the big totems spawn the guards

**Comment by Rushor** [comment]
fixed that faction issue. need to improved a bit in future, but for now it's working. Freindly player no longer spawn the guard.

![I](https://i.imgur.com/aSsRFQQ.jpg)
