### ISSUE TITLE
[Quest] WANTED: Chieftain Mummaki (bug) - 10117 - Zangermarsh (low prio) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#661]
https://www.wowhead.com/quest=10117/wanted-chieftain-mummaki

- After killing chieftain mummaki
- You are still in combat with the other 2 mobs thats with him.
- The mobs with him are not clickable, so cant kill
- Just have to run from them 

![chieftain](https://user-images.githubusercontent.com/39439201/51603980-a54e8a80-1f0b-11e9-9cda-c99ab0b71e26.jpg)

**Comment by Kitzunu** [comment]
fixed here https://github.com/WoWManiaUK/Blackwing-Lair/issues/1053
