### ISSUE TITLE
[NPC] Aged Clefthoof Bugged -17133- Nagrand 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#664]
https://www.wowhead.com/npc=17133/aged-clefthoof

**_Oshu'gun in Nagrand_**

- The clefthoofs in this area are already dead
- They move/slide around when you fly by them 

![deads but move](https://user-images.githubusercontent.com/39439201/51660722-f5325d80-1fae-11e9-9b95-4a9b57f2256e.jpg)

![moves](https://user-images.githubusercontent.com/39439201/51660781-1b57fd80-1faf-11e9-9468-615a04522a20.jpg)
![bugged](https://user-images.githubusercontent.com/39439201/51660792-214dde80-1faf-11e9-83bf-ec7378b6e01c.jpg)
![more bugged](https://user-images.githubusercontent.com/39439201/51660947-9faa8080-1faf-11e9-915a-0e6d5ec1722c.jpg)

**Comment by Kitzunu** [comment]
HP bar is fixed.
Though they are still appearing vissualized like if they were dead
![image](https://user-images.githubusercontent.com/24550914/54473988-7d7af500-47df-11e9-81b0-d40f86011203.png)

**Comment by Kitzunu** [comment]
fixed
