### ISSUE TITLE
[NPC] Loramus Thalipedes - missing-Blasted lands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#667]
NPC- https://www.wowhead.com/npc=7783/loramus-thalipedes

NPC does not appear in the cave at 62.4, 26.0 in serpents coils so I ma unable to hand in the follow quest  - https://www.wowhead.com/quest=26170/the-final-ritual.

**Comment by Dranah** [comment]
This NPC is meant to spawn after you complete the quest to resurrect him 
https://github.com/WoWManiaUK/Blackwing-Lair/issues/636 the event currently does not work and the NPC does not spawn.

ID=26170 should not be available without completing the altar quest first.
