### ISSUE TITLE
Quest Last Stand Duskhaven - Guilneas

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#668]
There is a bug when you done the quest Last Stand in Guilneas and get the cinimatic.
After the video i got stuck in the "headstock". To me it looks like they started to talk about me befor video is done and when they done talking nothing more happens. /script DEFAULT_CHAT_FRAME:AddMessage("\124cffffff00\124Hquest:14222:5\124h[Last Stand]\124h\124r");
[quest=14222]
[npc=35566]

**Comment by Saintres** [comment]
Ok i done this quest a few times now.
i found out that if you , when cinematic start u end it by force and then u are in Duskhaven trapped.
The NPC's are there and talk about you.
Click the quest giver standing close to you and you somehow complete a quest u dont have lol.
Then your out from the trap and can start questing again.

**Comment by Dranah** [comment]
This works as intended. You are stuck until you drink the potion to become human mind again (the quest you hand in)
