### ISSUE TITLE
Human/Pally quest Northshire [npc=925]

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#669]
There is a bug on quest " The power of the Light" (not listed in WoW head)

[npc=925]
This quest is not counting the action u do
Threw judgement spell on a training dummy

**Comment by Wicked16** [comment]
Ran into this issue today as well. learning spell judgement and cast on training dummies dosent work.
quest wont complete.

Wicked

**Comment by Echinaceax** [comment]
it is this one Saaint?
https://www.wowhead.com/quest=26918/the-power-of-the-light

**Comment by bagi84** [comment]
https://www.wowhead.com/quest=26918 is the human starter area quest link

**Comment by Echinaceax** [comment]
@Kitzunu its regressed somewhere
ive closed duplicate again and reopened this one

**Comment by Rushor** [comment]
going to remove the credit condition of spell learn from the quest
