### ISSUE TITLE
[Talent] [Spell] Archangel

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Blackwing-Lair#67]
**How it should work:**
> Description: Consumes your Evangelism effects, causing an effect depending on what type of Evangelism effect is consumed:
> |CFFFFFFFFArchangel (Evangelism)|R
> Instantly restores $87152s1% of your total mana and increases your healing done by $81700s1% for each stack. Lasts for $81700d. $87151s2 sec cooldown.
> |CFFFFFFFFDark Archangel (Dark Evangelism)|R
> Instantly restores $87153s3% of your total mana and increases the damage done by your Mind Flay, Mind Spike, Mind Blast and Shadow Word: Death by $87153s1% for each stack. Lasts for $87153d. $87151s3 sec cooldown.
![image](https://user-images.githubusercontent.com/14857593/39091752-3cdd4082-4611-11e8-8531-95ef94083952.png)

**How it works:**
The spell is not implemented at all.

**Comment by Keader** [comment]
Spell Implemented :)
