### ISSUE TITLE
[quest=14399] Grandma's Lost It Alright (double spawn) - Gilneas 

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#672]
**links**
https://www.wowhead.com/quest=14399/grandmas-lost-it-alright

**Whats happening**
When you have done the quest and going to hand it in there is 2 Grandma Whal [npc=36458] to complete it too.

**what should happen**
should be 1 i guess  ;-)

**Comment by Dranah** [comment]
Duplicate NPC? Is the quest doable though?

**Comment by Rushor** [comment]
one is in house and one in the open field. will remove the one from the field

**Comment by Rushor** [comment]
quest is doable yes
