### ISSUE TITLE
[NPC] Windroc Matriarch - ID19055 - (double spawn) Nagrand 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#674]
npc - https://www.wowhead.com/npc=19055/windroc-matriarch

- NPC spawns 2 times 
- A new was spawns as soon as the first one is dead
- Have to kill him twice 

Quest - https://www.wowhead.com/quest=10111/bring-me-the-egg

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/PR5JniE.jpg)
