### ISSUE TITLE
[Quest] Enemies, Old and New - 11503 - Nagrand

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#680]
Quest - http://www.wow-mania.com/armory/?quest=11503
NPC - https://www.wowhead.com/npc=24867/halaa-enemy-combatant

- phase issue ?
- The Halaa Enemy Combatant are not there 
- The flag is **_not_** contested (maybe why)
- I am flag pvp / will test without pvp flagged

(not sure if a dev has to test this or not) 
- Halaa is empty of all enemies
- Cant complete

![halaa empty](https://user-images.githubusercontent.com/39439201/52184296-b81d6500-2811-11e9-9a9a-dd71207fcc23.jpg)
 
![halaa map](https://user-images.githubusercontent.com/39439201/52184325-1ea28300-2812-11e9-854d-c87b3384e1ff.jpg)

**Comment by Rushor** [comment]
https://i.imgur.com/4pf7YqV.jpg

works fine meanwhile
