### ISSUE TITLE
[quest=26739]  [I Think She's Hungry] - Northern Stranglethorn

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#682]
It looks like the little raptor hatchling you get is not eating the Basiliks that she's suppose to do

[quest=26739] 
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffffff00\124Hquest:26739:-1\124h[I Think She's Hungry]\124h\124r");
[item=58165]
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffffffff\124Hitem:58165::::::::120:::::\124h[Lashtail Raptor Egg Fragment]\124h\124r");

**Comment by Echinaceax** [comment]
@Kitzunu @Rushor 
I closed this because another was opened, the description on the new title followed the "new" report system
