### ISSUE TITLE
[NPC] Cenarion Scout Jalia -51375- Silithus (low prio) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#683]
npc - https://www.wowhead.com/npc=15611/cenarion-scout-jalia

- Is this npc meant to be hiding inside a spider sac?

![npc spider sac](https://user-images.githubusercontent.com/39439201/52245472-07cb6180-28e2-11e9-945a-f6e73a960f68.jpg)

**_Edited to add_** 

- there are 2 Cenarion Scout Jalia

![there is 2](https://user-images.githubusercontent.com/39439201/52245561-6e507f80-28e2-11e9-9b47-2dabedeb9e42.jpg)

**Comment by mfranca0009** [comment]
There's only one instance of Cenarion Scout Jalia showing up on the PTR db and she seems to be in the right location. Is there still two on the live realm? 

The only issue I could see on PTR is that she continues to go stealth and out of stealth about every 5 minutes.

**Comment by Echinaceax** [comment]
@mfranca0009 i see from my Screen shot this test was in PTR (from testers guild name)  :)

from what i can find the egg one was removed from game 
https://classic.wowhead.com/npcs?notFound=51375
http://cata.cavernoftime.com/npc=51375
https://cata-twinhead.twinstar.cz/?npc=51375

> The only issue I could see on PTR is that she continues to go stealth and out of stealth about every 5 minutes.

that is the other ID 15611 (She is fine) 

All 3 of my research sites dont have this phase of npc i see that only npc=51375 needs removing 

ive edited the report title to 51375 npc, my mistake i reported the wrong ID number  :)

**Comment by mfranca0009** [comment]
Removed the instance of that npc ID, but I didn't delete the template just in case.

Needs to be tested on PTR 👍

**Comment by Echinaceax** [comment]
confirmed fixed :)
