### ISSUE TITLE
[Item] Talon of Tethis -3877-  Northern Stranglethorn

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#684]
**Link**
https://www.wowhead.com/npc=730/tethis

This item and the raptor Tethis have a wrong placed location.
Tethis i south of Mosh'ogg ogre mond
[item=3877]
[npc=730]

**Comment by Kitzunu** [comment]
Could you add more information?
There is no information here saying what is wrong and what should happen.
