### ISSUE TITLE
[Quest/Rogue] Eviscertation -10071- The sunspire

### ISSUE THREAD

**Issue by Revner17** [WoWManiaUK/Blackwing-Lair#687]
Pathstalker Kariel wants you pratice Eviscreration 3 times on the Training Dummy outside. Once completed you are suppose to hand this into Well Watcher Solanian but quest tracker tells you return to Pathstalker Kariel.  See images below

![eviscreration quest](https://user-images.githubusercontent.com/47263920/52249587-e5295080-28c1-11e9-8c42-a8e5420e105b.PNG)

https://www.wowhead.com/quest=10071/evisceration

**Comment by Echinaceax** [comment]
Quest - https://www.wowhead.com/quest=10071/evisceration

**Comment by Revner17** [comment]
Agreed, that’s probably what was throwing me off, once I get a moment I’ll update this. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kitzunu** [comment]
Fixed
