### ISSUE TITLE
[item=57990] [The Green Hills of Stranglethorn]

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#688]
[item=57990] [The Green Hills of Stranglethorn]
This is a Quest not listed on WoW Head only listed as an item.
I have got the page 14 [item=57990] and its not counting for the quest.
Quest still say i have to find the page 14 [item=57990].
However when i completed the Nesingwary endquest i got achivement 
The Green Hills of Stranglethorn ???

The questgiver for this quest is [npc=716] Barnil Stonepot

**Comment by sarahkay88** [comment]
#1550

**Comment by jarvik76** [comment]
Not sure this is a bug.  There are TWO versions of the page, one that is readable and one that is the actual quest item.
Item 57990 is indeed the quest item, but it sounds like the one that dropped for you is the readable non-quest item:
https://www.wowhead.com/item=2738/green-hills-of-stranglethorn-page-14

**Comment by Rushor** [comment]
item 57990 need to drop from more creatures. will add that

**Comment by Rushor** [comment]
the item 57990 will now drop for 5 percent while the quest is active from those creatures:

(943,  
(941,  
(43050,
(940,  
(938,  
(937,  
(905,  
(875,  
(871,  
(782,  
(772,  
(736,  
(731,  
(730,  
(729,  
(709,  
(702,  
(701,  
(699,  
(697,  
(696,  
(694,  
(691,  
(689,  
(688,  
(687,  
(686,  
(685,  
(684,  
(683,  
(682,  
(681,  
(676,  
(674,  
(670,  
(669,  
(667,  
(595,  
(588,  
(587,  
(4461, 
(4460, 
(4457, 
(2635, 
(1907, 
(1563, 
(1562, 
(1561, 
(1493, 
(1492, 
(1152, 
(1150, 
(1144, 
(1142, 
(1096, 
(1085, 
(1062, 
(1061,
