### ISSUE TITLE
[quest=26736] Spared from Madness - Northern Stranglethorn

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#689]
The three npc's to rescue are not in the cave.
[quest=26736]
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffffff00\124Hquest:26736:-1\124h[Spared from Madness]\124h\124r");

**Comment by Echinaceax** [comment]
@Kitzunu- not fixed
@fvicaria - may need server restart :)

**Comment by Kitzunu** [comment]
Recheck, restart wasnt succesful, should work now :)
