### ISSUE TITLE
[Talent] Harnessed Shadows

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Blackwing-Lair#69]
**How it works:**
> Description: Increases the chance for you to gain a Shadow Orb when dealing damage with your Mind Flay and Shadow Word: Pain by $s1%, and you have a $h% chance to gain a Shadow Orb when critically hit by any attack.
![image](https://user-images.githubusercontent.com/14857593/39204991-aa6e42e6-480e-11e8-81b7-26ed88c36aaa.png)

**How it should work:**
Getting any damage will trigger the talent and you will obtain a new shadow orb, Making Shadow Priest OP.

**Comment by Keader** [comment]
i will check tonight.

**Comment by Keader** [comment]
Fixed
