### ISSUE TITLE
[quest=26733] Control Sample - Northern Stranglethorn

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#690]
These Basilisk's dont drop the required item's
[quest=26733]
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffffff00\124Hquest:26733:-1\124h[Control Sample]\124h\124r");

**Comment by Echinaceax** [comment]
Fixed
![yip](https://user-images.githubusercontent.com/39439201/55647643-76dc0e00-57de-11e9-9e6b-60c26fc1f7a3.jpg)
