### ISSUE TITLE
[Quest] Scouring the Desert -9422- Silithus

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#692]
Quest - https://www.wowhead.com/quest=9422/scouring-the-desert
Video - https://www.wowhead.com/quest=9422/scouring-the-desert#videos:id=91826
npc - https://www.wowhead.com/npc=17079/general-kirika

**_Find and deliver Silithyst to the Silithyst Extractor then speak with General Kirika at the Horde encampment near Hive'Regal._**

- I find the "Silithyst"

![silithyst](https://user-images.githubusercontent.com/39439201/52300034-2df70d00-2987-11e9-96e3-a8f7b81956ab.jpg)

Deliver the "Silithyst"

![pvp](https://user-images.githubusercontent.com/39439201/52300090-49621800-2987-11e9-83a2-bbe6578b751c.jpg)

Quest not complete

![npc silver](https://user-images.githubusercontent.com/39439201/52300112-567f0700-2987-11e9-9a02-0a2906afe4e6.jpg)

Not sure if this has anything to do with it 
_

> This quest was marked obsolete by Blizzard and cannot be obtained or completed.

_

**Comment by deni6** [comment]
Still not working, tried it right now. Can`t finish the quest.

**Comment by Echinaceax** [comment]
havent been looked at yet @deni6

**Comment by gorgar19** [comment]
this quest can be removed from the .bq list just did it few minutes ago

**Comment by Echinaceax** [comment]
> this quest can be removed from the .bq list just did it few minutes ago

thanks @gorgar19
