### ISSUE TITLE
[Quest] Torgos! -10036- (double spawn) - Terrokkar forest

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#694]
quest - https://www.wowhead.com/quest=10036/torgos

**_Call down Torgos with Trachela's Carcass. Acquire a Tail Feather of Torgos and return it to Mawg Grimshot at Stonebreaker Hold in Terokkar Forest._**

used item - https://www.wowhead.com/item=30618/trachelas-carcass

- Spawns 2 Torgos
- Invalid target on both 
- cant complete

![torgos](https://user-images.githubusercontent.com/39439201/52311953-1466bd00-29a9-11e9-8114-3d36db884f6a.jpg)

**_Edited to add more info_**

- Thought i would test this again, so killed Trachela gain to get another Carcass 
https://www.wowhead.com/item=30618/trachelas-carcass

- Went back 
- and now there are 4 Torgos :)

_**The others where still spawned so redoing the quest only added x2 more Torgos**_ 

![torgos2](https://user-images.githubusercontent.com/39439201/52503268-5ed47d80-2be5-11e9-832e-960556dac5e3.jpg)

**Comment by Rushor** [comment]
![I](https://i.imgur.com/rHL8tOF.jpg)

fixed
