### ISSUE TITLE
[Quest] Rescue the Fallen -13613- Northern Barrens

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Blackwing-Lair#699]
**links**
https://www.wowhead.com/quest=13613/rescue-the-fallen
https://www.wowhead.com/npc=33263/dinah-halfmoon
https://www.wowhead.com/item=45001/medicated-salve

**what's happening**
With this  quest you have to  apply Medicated Salve on  a  wounded  defender.
You  can apply  but  it is not counting  for the  quest

**What should happen**
https://www.wowhead.com/quest=13613/rescue-the-fallen#videos:id=79278

**Comment by Saintres** [comment]
Same for me today

**Comment by Ranger-Bill** [comment]
tried to do this quest today. cant apply the salve to the Defenders.

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/8YAFe81.jpg)
