### ISSUE TITLE
[quest=13515] [Ending the Threat] - Darkshore

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#700]
**links**
https://www.wowhead.com/quest=13515/ending-the-threat
https://www.wowhead.com/npc=33178/huntress-sandrya-moonfall

_This quest your suppose to kill Jor'kil the Soulripper with help from [npc=33178] Huntres Sandrya Moonfall._

**Whats happening**
She tell you to talk to her when your ready to fight the boss Jor'kil.
But you dont get the option to talk to her and say your ready.
I tryed to fight the boss without talk to her and i got the help i needed but it dont count as a kill for the quest. 

**What should happen**
https://www.wowhead.com/quest=13515/ending-the-threat#videos:id=32767

**Comment by Rushor** [comment]
duplicate https://github.com/WoWManiaUK/Blackwing-Lair/issues/1047
