### ISSUE TITLE
[quest=13514] [The Ancients' Ire] - Darkshore

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#701]
**links**
https://www.wowhead.com/quest=13514/the-ancients-ire
https://www.wowhead.com/npc=33176/kerlonian-evershade

**Whats happening**
In this quest your suppose to take control over 1 [npc=43742] Vengeful Protector and kill 30 troll's and destroy 6 buildings.
But its not possible to take the control over the Vengeful Protector

**What should happen**
https://www.wowhead.com/quest=13514/the-ancients-ire#videos:id=32760

**Comment by Rushor** [comment]
duplicate https://github.com/WoWManiaUK/Blackwing-Lair/issues/1046

**Comment by Echinaceax** [comment]
still bugged

**Comment by baalvi** [comment]
still bugged nothing happened a npc treee use...
