### ISSUE TITLE
[quest=13560] An Ocean Not So Deep - Darkshore

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#702]
This quest you should get controll over a robot and kill murlocs.
The robot is doing nothing, can only run around and you dont get any "buttons" to click to kill murlocs.
[quest=13560]
[npc=32979] questgiver
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffffff00\124Hquest:13560:-1\124h[An Ocean Not So Deep]\124h\124r");

**Comment by Echinaceax** [comment]
mor info in second report #1038
