### ISSUE TITLE
[quest=13557] [Bearer of Good Fortune] - Darkshore

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#704]
**links**
https://www.wowhead.com/quest=13557/bearer-of-good-fortune

**Whats happening**
This quest im suppose to free 8 animals from cages.
I got the key to open the cages but the animals dont get out and the door closes again.
Animals still trapped.

**What should happen**
https://www.wowhead.com/quest=13557/bearer-of-good-fortune#videos:id=32614

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
confirmed fixed in ptr 

![image](https://user-images.githubusercontent.com/39439201/119258886-f3532600-bbcb-11eb-8790-78817a4b15a2.png)
