### ISSUE TITLE
[quest=13523] [Power Over the Tides] - Darkshore

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#705]
**links**
https://www.wowhead.com/quest=13523/power-over-the-tides

**Whats happening**
This quest your suppose to Beam a dead spirit that you have killed to free its spirit lol
Not counting as you done it after you freed the spirit

**What should happen**
https://www.wowhead.com/quest=13523/power-over-the-tides#videos:id=32830

**Comment by Echinaceax** [comment]
no quest credit @Rushor

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/rprHGB2.jpg)

once the Enraged Tidal Spirit isilled you can use the questitem http://cata.cavernoftime.com/item=44975 on them and a Tranquil Tidal Spirit will spawna nd give the credit.
