### ISSUE TITLE
[Quest] A Job for the Multi-Bot -26205- New Tinkertown

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#706]
Quest - https://www.wowhead.com/quest=26205/a-job-for-the-multi-bot
video - https://www.wowhead.com/quest=26205/a-job-for-the-multi-bot#videos:id=113648

_**Use the GS-9x Multi-Bot to clean up 5 Toxic Geysers at the Toxic Airfield. When you get close enough to a geyser, your GS-9x Multi-Bot will automatically begin its task.**_

- No Toxic Geysers
- cant complete 

**what its meant to show** 

![this](https://user-images.githubusercontent.com/39439201/52373207-63205f80-2a5a-11e9-8c1d-64f939de65aa.jpg)

**we see** 

![missing](https://user-images.githubusercontent.com/39439201/52373227-6e738b00-2a5a-11e9-93f7-9384315f99d4.jpg)

**Comment by bagi84** [comment]
I think the Imps may have something to do with problem .. Ive check a lot of Dun Morogh and were quests aren't working there seems to be these imps. the were present at Issue #824 as well 

![World of Warcraft 10_03_2019 20_59_36](https://user-images.githubusercontent.com/45798884/54091397-75eac480-4377-11e9-978c-ecf2d34f6303.png)

**Comment by z1179** [comment]
Also having this issue as of 5/1/2019, seems i am unable to progress in the zone until this quest is completed, In game: Khranus

**Comment by Echinaceax** [comment]
> Also having this issue as of 5/1/2019, seems i am unable to progress in the zone until this quest is completed, In game: Khranus

Yes this report was added to the other issues in the startzone you can see here #114
issue is now in the list with others in that area. 
hoped to be fixed soon

**Comment by Rushor** [comment]
will fix it like this: if your robot is close to Toxic pool which will bloob some slime, then i will start it's actions and give the questcredit.
