### ISSUE TITLE
[quest=13547] [Coaxing the Spirits]- Darkshore

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#707]
Here you should talk to dead ppl and coax them.
I dont get the opption to talk only open the window and say goodbye

[quest=13547]
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffffff00\124Hquest:13547:-1\124h[Coaxing the Spirits]\124h\124r");

**Comment by sarahkay88** [comment]
Quest - https://www.wowhead.com/quest=13547/coaxing-the-spirits
NPC - https://www.wowhead.com/npc=6887
IT  also prevents you from obtaining the next quest
call down the thunder -https://www.wowhead.com/quest=13558

**Comment by Echinaceax** [comment]
not fixed - no dialog to speak with the spirits

**Comment by Rushor** [comment]
![I](https://i.imgur.com/CXEDMFy.jpg)
![I](https://i.imgur.com/2BcOuu3.jpg)

okay credit and ghost summon added
