### ISSUE TITLE
[quest=13565] [Twice Removed] - Darkshore

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#708]
**links**
https://www.wowhead.com/quest=13565/twice-removed

**Whats happening**
here you suppose to kill Lady Janira [npc=33207] and summon 6 Withered Ents called [npc=34010]
in the quest it counted the kill of Lady Janira but it didnt count that i summoned the Ents.

**What should happen**
https://www.wowhead.com/quest=13565/twice-removed#videos:id=32656

**Comment by Rushor** [comment]
duplicate https://github.com/WoWManiaUK/Blackwing-Lair/issues/1051
