### ISSUE TITLE
[Talent] Eye for an eye

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Blackwing-Lair#71]
**How it should work:**
> Description: All magic attacks against you have a $h% chance to cause $s1% of the damage taken back to the attacker as well.
![image](https://user-images.githubusercontent.com/14857593/39464777-970bc252-4d34-11e8-8b8c-77022de048c7.png)

**How it works:**
The attacker(magic) is not taking any damage.
Simply the talent is not working.

**Comment by Keader** [comment]
Fixed.
