### ISSUE TITLE
[quest=13542] [Against the Wind] - Darkshore

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#710]
**Links**
https://www.wowhead.com/quest=13542/against-the-wind

**Whats happening**
This quest im suppose to destroy 8 [item=44868] in the moonwell.
Im standing in the moonwell but cant do anything with the item.
I only get message moonwell in Auberdine required

**What should happen**
https://www.wowhead.com/quest=13542/against-the-wind#videos:id=32844

**Comment by Rushor** [comment]
okay credit works now. and trigger are no longer visible

![I](https://i.imgur.com/73hA7j9.jpg)
