### ISSUE TITLE
[quest=13580] Soothing the Elements - Darkshore

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#712]
This quest dont accept any place to put down the totem that requierd for the quest 

[quest=13580]
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffffff00\124Hquest:13580:-1\124h[Soothing the Elements]\124h\124r");

**Comment by sarahkay88** [comment]
quest -https://www.wowhead.com/quest=13580/soothing-the-elements
NPC - https://www.wowhead.com/npc=33117
VIDEO - https://www.youtube.com/watch?v=RZa6hZapjMw

**Comment by sarahkay88** [comment]
This quest prevents npc https://www.wowhead.com/npc=34422/malfurion-stormrage  from phasing to his next location. therefore unable to pick up the following quest:
https://www.wowhead.com/quest=13987/the-last-stand

**Comment by sarahkay88** [comment]
This type of report is making my head hurt :(

**Comment by Rushor** [comment]
also fixed with next update then

![I](https://i.imgur.com/WFhZROE.jpg)

the totem will be summoned, you need to defeat it, then yu get the credit.
