### ISSUE TITLE
[NPC] Blood Elf Commoner - 19169 - Eversong Woods 

### ISSUE THREAD

**Issue by Revner17** [WoWManiaUK/Blackwing-Lair#713]
Seems there are two of the same NPC's next to the Dragonhawk Master outside Silvermoon City in Eversong Woods. Not sure if it is a duplicate. Both offered the same quest and performed same action.

![dup npc](https://user-images.githubusercontent.com/47263920/52381075-2181bb80-2a3e-11e9-9626-13d76dad4df5.PNG)

**Comment by Dranah** [comment]
There are many of these npcs, all around towns and cities. They are part of a world event that isn't supposed to be active at all times, was just turned on for testing.
