### ISSUE TITLE
[quest=13599] Grimclaw's Return - Darkshore

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#714]
There is noone in Lor'danel to complete this quest too..

[quest=13599]
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffffff00\124Hquest:13599:-1\124h[Grimclaw's Return]\124h\124r");

**Comment by sarahkay88** [comment]
isn't a quest issue its an NPC issue #1064 and #1062

**Comment by Kitzunu** [comment]
Can this be closed? 

test on dev if the fixes mentioned above fixed this
