### ISSUE TITLE
[quest=13892] Leave No Tracks Darkshore

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#715]
This quest your suppose to sneak up behind Foreman Balsoth [npc=34406]
and that should trigger a convo between him and a worker.  
This convo dont start so cant continue this quest.

[npc=34406]
[quest=13892]
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffffff00\124Hquest:13892:-1\124h[Leave No Tracks]\124h\124r");

**Comment by Rushor** [comment]
conversation not added, but you can transform and get th questcredit now if you enter the spot at the masters glaive and stay long enough there

**Comment by Kitzunu** [comment]
Quest is missing the Dialogue
Quest is missing text when you hand it in 
![image](https://user-images.githubusercontent.com/24550914/54078682-e4267d00-42cc-11e9-8c1d-7826f749977b.png)

Quest does get completed if you are there long enough
