### ISSUE TITLE
[quest=13899] [The Darkscale Warlord] - Darkshore

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#716]
The kill of this warlord dont count as killed

[quest=13899]
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffffff00\124Hquest:13899:-1\124h[The Darkscale Warlord]\124h\124r");

**Comment by Echinaceax** [comment]
more info to help Devs in the newest one
