### ISSUE TITLE
[quest=26612] [item=59145] - Stranglethorn Vale

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#719]
This item is not showing up anywhere to pick up and complete the quest [quest=26612]
There is multiple places to pick this up but i checked all of them and not showing anywhere.
There is 1 place i can see it but not pickable  lol

https://www.wowhead.com/quest=26612/details-of-the-attack
[item=59145]
[quest=26612]

**Comment by Echinaceax** [comment]
@Kitzunu
- [ ] Bloodsail charts (fixed)
- [ ]  Bloodsail Orders
https://www.wowhead.com/item=59145/bloodsail-orders

**Comment by Kitzunu** [comment]
Test now, dont forget to delete cache
