### ISSUE TITLE
[npc=44395] Celestine of the Harvest <Druid Trainer>

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#721]
This druid trainer [npc=44395] refuse to talk and train me in Stormwind

[npc=44395] Celestine of the Harvest 
https://www.wowhead.com/npc=44395/celestine-of-the-harvest

**Comment by Rushor** [comment]
can anyone confirm that?

**Comment by Kitzunu** [comment]
@Rushor Issue still persists.

This is what happens:
When you Right Click Celestine of the Harvest the UI does not open.
![image](https://user-images.githubusercontent.com/24550914/54142675-88710680-4428-11e9-8605-8f5b5cf29500.png)

**Comment by Kitzunu** [comment]
fixed
