### ISSUE TITLE
Missing quest  Id 14406- Gilneas

### ISSUE THREAD

**Issue by Bl00delve** [WoWManiaUK/Blackwing-Lair#724]
https://www.wowhead.com/quest=14406/the-crowley-orchard#screenshots:id=212090

the npc https://www.wowhead.com/npc=36452/gwen-armstead did not gife the quest

**Comment by giles1508** [comment]
tested today on fresh toon,   this quest giver still doesnt give the quest.... reopening

**Comment by Rushor** [comment]
still not fixed, tested by fresh worgen

**Comment by Rushor** [comment]
Tested yesterday with Giles and it works great now.
