### ISSUE TITLE
[NPC] Teribus the Cursed - (double spawned) - Terokkar Forest 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#725]
NPC - https://www.wowhead.com/npc=22441/teribus-the-cursed

- Spawns twice

![teribus](https://user-images.githubusercontent.com/39439201/52748748-a09b6480-2fe7-11e9-8140-11f813a60178.jpg)

**Comment by mfranca0009** [comment]
Not able to replicate this on the PTR, only had one spawn and I did this twice. Is this still a problem on live realm?

**Comment by Echinaceax** [comment]
@mfranca0009 will check 

**Update**
No longer an issue on live or on ptr (tested both)
