### ISSUE TITLE
[Quest] The Big Bone Worm -10930- Terokkar Forest

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#726]
quest - https://www.wowhead.com/quest=10930/the-big-bone-worm
Quest item provided - https://www.wowhead.com/item=31825/fumper
video - https://www.wowhead.com/quest=10930/the-big-bone-worm#videos:id=56035

**_Dwarfowitz at the Sha'tari Base Camp in the Bone Wastes wants you to recover Enormous Bone Worm Organs._**

- Big worm (hai shulud) isnt spawning
- Cant complete
NPC - https://www.wowhead.com/npc=22038/haishulud

- quest item works 

![hai shulud missing](https://user-images.githubusercontent.com/39439201/52750126-9ed3a000-2feb-11e9-8cb5-06e39c16adb2.jpg)

- you have to cast the fumper quest item after you killed the "clefthoofs"and then big worm "hai shulud" is meant to spawn (see video)

- killed and cast quest item on 50 and no NPC worm comes

**Comment by Rushor** [comment]
okay reworked the spell

![I](https://i.imgur.com/ug54pNE.jpg)

you now have a chance to either spawn SPELL_SUMMON_HAISHULUD, SPELL_SUMMON_MATURE_BONE_SIFTER1, SPELL_SUMMON_MATURE_BONE_SIFTER3

only one of the three will spawn once itme is used on DEAD Decrepit Clefthoof
