### ISSUE TITLE
[Quest] Welcoming the Wolf Spirit -10791- Terokkar Forest

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#729]
quest - https://www.wowhead.com/quest=10791/welcoming-the-wolf-spirit
Quest item supplied - https://www.wowhead.com/item=31344/ceremonial-incense

_Use the **Ceremonial Incense near the candles in Malukaz's hut** and observe the ceremony. When the ceremony is complete, speak with Malukaz again_

- Either the ceremonial-incense are not working or
- Its the "candles" thats the problem 

![missing candles](https://user-images.githubusercontent.com/39439201/52755196-6472fe80-2ffd-11e9-81e7-bd634320bd71.jpg)

- I have abandoned quest 3 times and still not working

**Comment by Rushor** [comment]
you can use the item now and get the credit 

![I](https://i.imgur.com/0bvrW5Y.jpg)
