### ISSUE TITLE
[Quest]  Red Snapper - Very Tasty!

### ISSUE THREAD

**Issue by Kadajj** [WoWManiaUK/Blackwing-Lair#73]
Hi Team,

This quest  [Red Snapper - Very Tasty](http://www.wowhead.com/quest=9452/red-snapper-very-tasty) was supposed to spawn a murloc (around 30% chance) while fishing with the quest item [Draenei Fishing Net](http://www.wowhead.com/item=23654) and kill it and loot [Red Snapper](http://www.wowhead.com/item=23614/red-snapper) .   

On the Fish Banks that were supposed to spawn the murloc, you dont get the quest item nor the murloc.

Quest is doable if you keep fishing banks where give the quest item directly.

Thanks

**Comment by fvicaria** [comment]
Works fine for me. Maybe even too much as you can use on the same spot.

![image](https://user-images.githubusercontent.com/9414661/39627201-ef3311fa-4f9c-11e8-8f82-44551fb7cd14.png)

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/39628593-71ed60ec-4fa1-11e8-9760-7c7db6ca4874.png)
Fixed now.

**Comment by Xman993** [comment]
It dose not work on live, still no murlock.

**Comment by Rushor** [comment]
30 percent now to spawn a murloc. it should not happen all the time!

![I](https://i.imgur.com/2pSHfUM.jpg)
