### ISSUE TITLE
[Quest] The Final Code -10447- Terokkar Forest

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#731]
quest - https://www.wowhead.com/quest=10447/the-final-code

**_Sergeant Chawni wants you to use the Final Code Sheet to set off the Mana Bomb. Then report back to Tooki at Stonebreaker Hold in Terokkar Forest._**

- You get the code from killing 
https://www.wowhead.com/npc=18554/sharth-voldoun
he drops - https://www.wowhead.com/item=29912/the-final-code

- then you go and Activate the mana bomb
But , doesnt give quest credit (quest 0/1 ) 
 
![activated](https://user-images.githubusercontent.com/39439201/52803748-f6711a80-3082-11e9-816e-d7a0e1519108.jpg)

- cant complete the series

1.What Are These Things? (completed)
2.Report to Stonebreaker Camp (completed)
3.Attack on Firewing Point (completed)
4.**The Final Code** (cant complete) 
5.Letting Earthbinder Tavgren Know (cant collect last quest)

**Comment by Dranah** [comment]
Visual problem only, it doesn't show complete but it is...
You can hand the quest in.
![Untitled2](https://user-images.githubusercontent.com/31132743/57565797-023f5500-73c4-11e9-8f34-dfdaa0661ee3.png)
