### ISSUE TITLE
[Quest/NPC] Secrets of the Talonpriests - ID 11005 - missing npcs - Terokkar Forest

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#732]
1. https://www.wowhead.com/npc=23068/talonpriest-zellek
2. https://www.wowhead.com/npc=23066/talonpriest-ishaal
3. https://www.wowhead.com/npc=23067/talonpriest-skizzik

Quest giver - https://www.wowhead.com/npc=23038/sky-commander-adaris

- All the npcs for this quest are missing
- No talons priests anywhere 
- Cant complete

![no preists](https://user-images.githubusercontent.com/39439201/52808762-f37c2700-308e-11e9-94e7-0f6967148af9.jpg) ![no preists 2](https://user-images.githubusercontent.com/39439201/52808767-f8d97180-308e-11e9-90bb-abdad6227e5f.jpg) ![no preists 3](https://user-images.githubusercontent.com/39439201/52808780-ff67e900-308e-11e9-8eff-5d3f9234dc6d.jpg)
![no talons](https://user-images.githubusercontent.com/39439201/52809536-d0527700-3090-11e9-88b4-8551a27e080c.jpg)

- I activated (v) so i can search everywhere, i dont see any of them

**Comment by Dranah** [comment]
https://www.wowhead.com/quest=11005/secrets-of-the-talonpriests

**Comment by Rushor** [comment]
you need the elexier first to see them :) https://www.wowhead.com/npc=23068/talonpriest-zellek#comments:id=207416
