### ISSUE TITLE
[quest=26595] [Kill-Collect] -  The Cape of Stranglethorn

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#734]
**Links**
[quest=26595]
https://www.wowhead.com/quest=26595/kill-collect#links

_Here is suppose to collect 3 items and kill 3 different npc's_
Maury's Clubbed Foot from [npc=2535]
Fitztittle's Ratcheting Torque Wrench from [npc=43376]
Ephram's Jeweled Mirror from [npc=43377].

**What is happening** 
The last one [npc=43377] is green and not killable even if,
as they say in wow head that u have to talk to him first,, did that too.

**What should happen** 
- He should be killable and lootable 
https://www.wowhead.com/npc=43377/ephram-midriff-moonfall

**Comment by zippoking** [comment]
Just make him hostile. Very quick and easy fix to complete the quest.

**Comment by Rushor** [comment]
https://i.imgur.com/VRAZLop.jpg
https://i.imgur.com/jTTAPtb.jpg
https://i.imgur.com/y6apBgY.jpg
https://i.imgur.com/FtxQf9r.jpg
