### ISSUE TITLE
[NPC] Larissia - Guild Vendor - Silvermoon City - #51502 (Low Priority)

### ISSUE THREAD

**Issue by Revner17** [WoWManiaUK/Blackwing-Lair#735]
This NPC which is located at the Silvermoon Registry in Silvermoon City is the Guild Vendor and when right clicking to speak to her you are not prompted with her items menu, even though the cursor indicates a bag symbol when you hover over her. 

![image](https://user-images.githubusercontent.com/47263920/52892790-f72dad80-3163-11e9-84dc-1994955d2179.png)

https://www.wowhead.com/npc=51502/larissia

**Comment by Echinaceax** [comment]
Reopened 
She is still inactive

**Comment by Echinaceax** [comment]
She is still broken (Inactive)

**Comment by Kitzunu** [comment]
On PTR?

**Comment by Echinaceax** [comment]
@Kitzunu - i seen it while checking on another NPC on dev

**Comment by Echinaceax** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/3129#issuecomment-552163372
