### ISSUE TITLE
[quest=28579]  [Hero's Call: Badlands!]

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#737]
here you suppose to go to Light's Hope Chapel in EPL to find this NPC. [npc=48704]
She is nowhere to find in EPL. LHC.

[quest=28579]
[npc=48704]
https://www.wowhead.com/quest=28579/heros-call-badlands

**Comment by Echinaceax** [comment]
Yours is the Ally version of mine right ?
#455

**Comment by Saintres** [comment]
Yes im Ally.

Den sön 17 feb. 2019 18:08 skrev Echinaceax <notifications@github.com>:
