### ISSUE TITLE
[NPC] Fera Palerunner <Bandage Trainer> - 19478 - Blade's Edge Mountains

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#739]
npc - https://www.wowhead.com/npc=19478/fera-palerunner

- Duplicate text 

![firstaid](https://user-images.githubusercontent.com/39439201/52917396-376b6800-32eb-11e9-94ca-038bede5d43a.jpg)

**Comment by Rushor** [comment]
that's intended the field on top only shows you the most current spell you can learn
