### ISSUE TITLE
[Quest] Hungry Nether Rays - 11093 -  Terokkar Forest

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#740]
quest - https://www.wowhead.com/quest=11093/hungry-nether-rays
item provided - https://www.wowhead.com/item=32834/nether-ray-cage

**_Use the Nether Ray Cage in the woods south of Blackwind Landing and slay Blackwind Warp Chasers near the Hungry Nether Ray. Return to Skyguard Handler Deesak when you've completed your task._**

- Not getting quest credit 

![quest not counting](https://user-images.githubusercontent.com/39439201/52917717-0e4cd680-32ef-11e9-855d-0004498267bd.jpg)

- I abandoned quest and retook
- Still no quest credit in quest log 
- Cant complete

![1 of 10](https://user-images.githubusercontent.com/39439201/52917732-3b00ee00-32ef-11e9-9ea3-39352afe7439.jpg)
 
10/10

![10 10](https://user-images.githubusercontent.com/39439201/52918277-79011080-32f5-11e9-8a97-34e729eb97f8.jpg)

**Comment by Dranah** [comment]
Only visual issue. You CAN hand in the quest, because it is complete.
![WoWScrnShot_051119_075902](https://user-images.githubusercontent.com/31132743/57565697-b17b2c80-73c2-11e9-8ac0-afc7bcc7f0c4.jpg)
