### ISSUE TITLE
[Quest] Escape from Skettis - 11085 - Terokkar Forest (unscripted/autocomplete) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#741]
quest - https://www.wowhead.com/quest=11085/escape-from-skettis
npc escort - https://www.wowhead.com/npc=23383/skyguard-prisoner

- skyguard-prisoner is in No cage
- Took the quest and it auto completed without us moving /escorting him anywhere

![no cage](https://user-images.githubusercontent.com/39439201/52918050-f11a0700-32f2-11e9-9df6-202334dddefe.jpg)
![escape](https://user-images.githubusercontent.com/39439201/52918083-4d7d2680-32f3-11e9-8330-e275e28193ad.jpg)

**Comment by Rushor** [comment]
fixed for all 3 spawned creatures

![I](https://i.imgur.com/6a2g3Y6.jpg)
![I](https://i.imgur.com/PODAJAY.jpg)
