### ISSUE TITLE
[Quest] Exorcising The Trees - ID 10830 - Blade's Edge Mountains

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#746]
npc - https://www.wowhead.com/item=31495/grishnath-orb

- Not working 
- Cant click on it 

for the quest
**_Collect 5 Grishnath Orbs and 5 Dire Pinfeathers and then combine them into Exorcism Feathers. Use these feathers to exorcise and slay 5 Koi-Koi Spirits from the Raven's Wood Leafbeards_**
 
quest - https://www.wowhead.com/quest=10830/exorcising-the-trees

![cant click](https://user-images.githubusercontent.com/39439201/52921174-a8734580-3314-11e9-99d2-2f2db8a89d81.jpg)

**Comment by Rushor** [comment]
clickable now

![I](https://i.imgur.com/tfiESuL.jpg)

quest works now
