### ISSUE TITLE
[npc=42357] Hulking Goretusk - Westfall

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#747]
This npc is not skinnable for some reason [npc=42357]

It's just a pig so it should be skinnable right ?

**Comment by Echinaceax** [comment]
Yes it says skinnable on the list
https://www.wowhead.com/npc=42357/hulking-goretusk#skinning

thanks Saaint

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/58296131-c6988800-7dd2-11e9-9900-4d7cdfb8626e.png)
