### ISSUE TITLE
[Quest Item] Costume Scraps -31121- Blade's Edge Mountains

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#748]
https://www.wowhead.com/item=31121/costume-scraps#dropped-by

- Still continue dropping after completing the quest and handing it back.

![costume drops](https://user-images.githubusercontent.com/39439201/52972003-b8913080-33b9-11e9-92c1-a213879c0297.jpg)

regents for - https://www.wowhead.com/item=31121/costume-scraps#reagent-for
For quest - https://www.wowhead.com/quest=10722/meeting-at-the-blackwing-coven
npc - https://www.wowhead.com/npc=22386/watcher-moonshade

dropped by 
https://www.wowhead.com/npc=21637/wyrmcult-scout
https://www.wowhead.com/npc=21382/wyrmcult-zealot
https://www.wowhead.com/npc=21383/wyrmcult-acolyte
https://www.wowhead.com/npc=22308/wyrmcult-hunter
https://www.wowhead.com/npc=21810/wyrmcult-hewer
https://www.wowhead.com/npc=21809/wyrmcult-poacher
https://www.wowhead.com/npc=21387/wyrmcult-blackwhelp
https://www.wowhead.com/npc=22099/wyrmcult-provisioner

**Comment by Echinaceax** [comment]
- Still can make the https://www.wowhead.com/spell=38156/create-overseer-disguise

![overseer](https://user-images.githubusercontent.com/39439201/52972786-38b89580-33bc-11e9-886a-ddfd9bf82dbc.jpg)
![disguise](https://user-images.githubusercontent.com/39439201/52972791-3b1aef80-33bc-11e9-8571-6ebbe95625f8.jpg)

**Comment by Kitzunu** [comment]
fixed, will send later
