### ISSUE TITLE
[Quest]Exodar Hippogryph Master 

### ISSUE THREAD

**Issue by Kadajj** [WoWManiaUK/Blackwing-Lair#75]
Hi Team,

It looks like the [Hippogryph Master Stephanos](http://www.wowhead.com/quest=9605/hippogryph-master-stephanos) cant give any filght paths from Exodar.

![wowscrnshot_050518_123153](https://user-images.githubusercontent.com/38867875/39662854-50a946d4-5060-11e8-8909-ddd74b2555cb.jpg)

**Comment by Dranah** [comment]
Have you picked up any flight path though? I mean it's normal that he doesn't show any if you haven't spoken to a single flight master outside exodar yet.

**Comment by Kadajj** [comment]
yup, did. you only get that description

**Comment by Kadajj** [comment]
There a quest that requires you to fly from Azure watch to exodar...everything fine.
On the Return quest when you need to fly from Exodar to Azure Watch you cant take the flight,
and this is also outside the quest, you can fly into exodar, cant fly from exodar
