### ISSUE TITLE
[quest=28181] [Warlocks Have the Neatest Stuff] - Burning Steppes

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#751]
1 item is missing for complete this quest. [item=63134]   Clear Glass Orb
WoW Head say 29 % droprate, i would say its more like 0.0001 %
Been killing atleast 50 Warlocks.

[quest=28181]
https://www.wowhead.com/quest=28181/warlocks-have-the-neatest-stuff
[item=63134]
https://www.wowhead.com/item=63134/clear-glass-orb

**Comment by Echinaceax** [comment]
Same for horde :)

**Comment by Rushor** [comment]
item added
