### ISSUE TITLE
Dire Wolf Skinning issue

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#752]
Dire Wolf's in Duskwood is not skinnable but they should probbably be that.
There is no npc # on them on wowhead

**Comment by Saintres** [comment]
Allso the Coalpelt Bear [npc=44016] in Duskwood should be skinnable but are not.

**Comment by Echinaceax** [comment]
> Not easy to lvl skinning when npc's are not skinnable.

This is exactly why Pross are "low pri" atm :)

**Comment by Rushor** [comment]
will add a lot of missing skinning loot
