### ISSUE TITLE
Prospecting  [Thorium Ore]- 10620- 

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#755]
Prospecting  [Thorium Ore] ends up in nothing.
Dont give any gems at all

**Comment by Echinaceax** [comment]
https://www.wowhead.com/item=10620/thorium-ore
https://www.wowhead.com/item=10620/thorium-ore#prospecting

**Comment by Kitzunu** [comment]
Fixed in the DEV Realm.
Dont forget to delete cache before testing.

**Comment by Saintres** [comment]
even prospecting Obsidium and Elementium gives 50-60 % zero catch. Means u get nothing out of it 
(0=zero gems)

**Comment by Saintres** [comment]
Creating Fire prism dont give any gems at all.

**Comment by Kitzunu** [comment]
Open new reports for issues that are not related to prospecting Thorium Ore
