### ISSUE TITLE
[NPC] Anchorite Avuun  -17127-  (missing) 

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#761]
NPC is missing to deliver the quest too.

[quest=27918]
[npc=17127]
https://www.wowhead.com/quest=27918/the-harborage

**Comment by Echinaceax** [comment]
So Anchorite Avuun is missing ?

**Comment by Saintres** [comment]
Yes i couldnt find him at the bed as he suppose to be

Den lör 23 feb. 2019 21:02 skrev Echinaceax <notifications@github.com>:

**Comment by Rushor** [comment]
Added correct pahasing aura, so people can see that creature while beeing on the quest.

**Comment by Kitzunu** [comment]
No change,
GM Off, on quest
![image](https://user-images.githubusercontent.com/24550914/53823576-5cf6a380-3f72-11e9-8f06-c32ebac9f0b5.png)

GM On
![image](https://user-images.githubusercontent.com/24550914/53823655-7dbef900-3f72-11e9-87fb-f4703b83a73a.png)
