### ISSUE TITLE
[Item] Flaming Torch (ally) 

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#763]
Use the Flaming Torch to burn the Horde Blade Throwers overlooking the Path of Glory. Then, bring the Flaming Torch to Dumphry in Honor Hold.

Eastern Thrower Burned
Central Eastern Thrower Burned
Central Western Thrower Burned
Western Thrower Burned

The torch dont work at the required places

https://www.wowhead.com/quest=10078/laying-waste-to-the-unwanted
https://www.wowhead.com/item=26002/flaming-torch

**Comment by Echinaceax** [comment]
https://www.wowhead.com/item=27479/flaming-torch

believe its the quest item related to horde quest #594

**Comment by zippoking** [comment]
Why is this one closed? Alliance and Horde quest are different to each other. I don´t undersatnd the Duplicate tag.....

It seems that #594 is fixed, but this one is still not working.

**Comment by Echinaceax** [comment]
> Why is this one closed? Alliance and Horde quest are different to each other. I don´t undersatnd the Duplicate tag.....
> 
> It seems that #594 is fixed, but this one is still not working.

was close as it was the item that want working and not the quest, ive reopened it and this qest item will be looked at. thank you

**Comment by jarvik76** [comment]
This is still an issue as at 28th Sept.

**Comment by Rushor** [comment]
not need anymore for list, has been fixed now.
