### ISSUE TITLE
[Quest] A Little Dash of Seasoning - Zeb'Now, Ghostlands - #9275

### ISSUE THREAD

**Issue by Revner17** [WoWManiaUK/Blackwing-Lair#766]
https://www.wowhead.com/quest=9275/a-little-dash-of-seasoning

Issue: Smoked Meat Rack is not interactive. Abandoned the quest and repicked up to see if that fixed it and still same issue. 

![screenshot 2](https://user-images.githubusercontent.com/47263920/53440128-d2da9800-39d1-11e9-9e18-1424af196284.png)

**Comment by Rushor** [comment]
flag 4 is set and it does not despawn and is always usable.

**Comment by Kishilu** [comment]
cannot interact with the meat rack or target it with the quest item.  non-completable

**Comment by Rushor** [comment]
got it, it was locked. sorry for that.

**Comment by Rushor** [comment]
meh wait, this is a really strange issue :o

**Comment by Rushor** [comment]
removed the 3. objective - there is some deep core issue with it. 

you only need to poison 2 gameobjects now.
