### ISSUE TITLE
[Quest] Dar'Khan's Lieutenants - Deatholme, Ghostlands - #9170

### ISSUE THREAD

**Issue by Revner17** [WoWManiaUK/Blackwing-Lair#767]
https://www.wowhead.com/quest=9170/darkhans-lieutenants

https://www.wowhead.com/npc=16247/borgoth-the-bloodletter

Issue: Borgoth the Bloodletter does not spawn in either location.

![screenshot 4](https://user-images.githubusercontent.com/47263920/53443168-108eef00-39d9-11e9-894f-712ba98d42d6.png)

**Comment by Kitzunu** [comment]
No change.
There are Spawn locations for the NPC at 2 places in the world, however there is no NPC there.
![image](https://user-images.githubusercontent.com/24550914/54078506-86dcfc80-42c9-11e9-9058-1d343b96a073.png)

**Comment by Kitzunu** [comment]
Fixed in the DEV Realm.
Dont forget to delete cache before testing.
