### ISSUE TITLE
[Quest] Captives at Deatholme - Deatholme, Ghostlands - #9164

### ISSUE THREAD

**Issue by Revner17** [WoWManiaUK/Blackwing-Lair#768]
https://www.wowhead.com/quest=9164/captives-at-deatholme

https://www.wowhead.com/npc=16209/ranger-vedoran

Issue: When speaking to Ranger Vedoran, he awakens from laying on the table and runs off and it changes the object to complete but quest tracker does not show completion status and I am unable to turn it in.

![screenshot 6](https://user-images.githubusercontent.com/47263920/53448425-5ce02c00-39e5-11e9-82a1-994bbd51b4bb.png)

![screenshot 7](https://user-images.githubusercontent.com/47263920/53448972-bf85f780-39e6-11e9-950d-d7cbc104eea5.png)
wa
![screenshot 8](https://user-images.githubusercontent.com/47263920/53449007-d6c4e500-39e6-11e9-93dd-a2e142da207d.png)

**Comment by Dranah** [comment]
Cannot reproduce. I can turn the quest in.

**Comment by rzenne** [comment]
I had the same problem today
