### ISSUE TITLE
[NPC] Margol the Rager - 5833- Searing Gorge 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#769]
npc - https://www.wowhead.com/npc=5833/margol-the-rager

- npc drops quest item without having a quest 
https://www.wowhead.com/item=10005/margols-gigantic-horn

![horn](https://user-images.githubusercontent.com/39439201/53608629-d59cdf00-3bc3-11e9-9fa8-e800e4be8ffc.jpg)

**Comment by Rushor** [comment]
Only show loot 'Margol's Gigantic Horn' is active

**Comment by Echinaceax** [comment]
okidoki 
thanks

**Comment by Kitzunu** [comment]
Margol's Gigantic Horn only drops if you have the quest
