### ISSUE TITLE
[quest=10016] Timber Worg Tails

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#770]
The droprate on these tails [item=25807] is terrible low.

wowhead say 23 % but its not even close to that.

Copyed this coment on wowhead.
Drop rate is somewhere between non-existant and ridiculous, leaning towards ridiculous, since every worg you find has a large fluffy tail which somehow seems to disappear at the moment you deal the killing blow. Very odd.
https://www.wowhead.com/quest=10016/timber-worg-tails

**Comment by Rushor** [comment]
dropchance set to 35 percent

**Comment by Saintres** [comment]
good work Rushor

**Comment by Kitzunu** [comment]
Seems to be good now.
