### ISSUE TITLE
[NPC] Gryphon Rider Guard (bug) -15241- Hellfire Peninsula

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#771]
npc https://www.wowhead.com/npc=15241/gryphon-rider-guard

![gryphon rider guard](https://user-images.githubusercontent.com/39439201/53610158-40e9af80-3bca-11e9-85f8-7344ddb2f0a1.jpg)

![roof](https://user-images.githubusercontent.com/39439201/53610250-8a39ff00-3bca-11e9-8ba1-bbc6463ac742.jpg)

**Comment by Rushor** [comment]
creatures should not be static spawns there. static spawns removed.

**Comment by Kitzunu** [comment]
Not fixed, you still enter Combat somehow in the enterance of Honor Hold Inn. 
![image](https://user-images.githubusercontent.com/24550914/53834510-807a1800-3f8b-11e9-8a88-394ebcb475f8.png)

**Comment by Rushor** [comment]
is that issue really related to those creatures or is it caused by sth else?

**Comment by Kitzunu** [comment]
@rushor I didnt make the report so I have no idea.
But I dont believe so.

NPC's are gone. Honor Hold is an ally place, Allys get in combat at the enterence of the inn.

This should probably have been 2 seperare reports

**Comment by Echinaceax** [comment]
Hi guys,
Ive not idea wait trigets this "in combat bug" 

it has to have something to do with th Gryphon Rider Guard themselves because the same bug in 3 other areas

**Comment by Kitzunu** [comment]
Since the NPCs are removed on Dev they cannot have something to do with the Combat bug.

The NPCs are removed. Confirmed in dev

**Comment by Echinaceax** [comment]
very odd indeed

**Comment by Kitzunu** [comment]
Upon further investigation I have come to conclude:
![image](https://user-images.githubusercontent.com/24550914/54159349-10690780-444d-11e9-9e39-f27d549b437d.png)
The Gryphons are back

AND, when you go near them, you enter combat.
So my guess is that Echi is correct and this has something to do with the gryphon.
