### ISSUE TITLE
[Issue] Quest Objectives - Arathi Highlands (Low Priority)

### ISSUE THREAD

**Issue by Revner17** [WoWManiaUK/Blackwing-Lair#774]
I am testing Arathi Highlands and picked up a handful of quests in Hammerfall and it areas the quest tracker for this area is not working. On the right side of the screen the quests boxed in red should be numbered 1-3 and should appear on the mini map since I have "Show Quest Objectives" checked but they do not. I have abandoned and reacquired a few times and cleared my cache and it does not solve the issue.

![screenshot 9](https://user-images.githubusercontent.com/47263920/53686267-f152d300-3cf2-11e9-8ff9-f8ae766e3a70.png)

**Comment by Echinaceax** [comment]
issue is with map and has been reported elsewhere :)
#136
