### ISSUE TITLE
[NPC] Gryphon Rider Guard (bug) -15241- Zangermarsh 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#775]
https://www.wowhead.com/npc=15241/gryphon-rider-guard

- Same in zangermarsh 
- incombat bug 

![gryphen guards](https://user-images.githubusercontent.com/39439201/53690807-e0957200-3d71-11e9-8a0e-ef50c36df60d.jpg)

- Horde bats are also have this bug in zangermash #660

**Edited to add more info**

when testing this Zangermarsh bug - if it still happens when youve looked into the "NPC behavior".
Can you please refer too #805 (could be same fix)

**Comment by sarahkay88** [comment]
same issue at Thrallmar - just outside the inn

**Comment by Rushor** [comment]
fixed that faction issue. need to improved a bit in future, but for now it's working. Freindly player no longer spawn the guard.

![I](https://i.imgur.com/aSsRFQQ.jpg)
