### ISSUE TITLE
[Innkeeper] Nerius <Innkeeper> - 43141- Abyssal Depths

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#779]
https://www.wowhead.com/npc=43141/innkeeper-nerius

- Sales window inactive

**Comment by Rushor** [comment]
i think he does not sell anything https://www.wowhead.com/npc=43141/innkeeper-nerius#comments

**Comment by Echinaceax** [comment]
thanks for checking :)
