### ISSUE TITLE
[NPC] Dubin Clay <Plate Armor Merchant> Dalaran 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#783]
https://www.wowhead.com/npc=34252/dubin-clay

- Inactive

**Comment by Rushor** [comment]
That's intended as is. if you are not a paladin, warrior or dk you cannot inspect his vendor page.

**Comment by Echinaceax** [comment]
> That's intended as is. if you are not a paladin, warrior or dk you cannot inspect his vendor page.

perfect, thanks for checking :)
