### ISSUE TITLE
[NPC] Horace Hunderland <Plate Armor Merchant> Dalaran 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#784]
https://www.wowhead.com/npc=35498/horace-hunderland

- Inactive

**Comment by Rushor** [comment]
That's intended as is. if you are not a paladin, warrior or dk you cannot inspect his vendor page.

**Comment by Echinaceax** [comment]
> That's intended as is. if you are not a paladin, warrior or dk you cannot inspect his vendor page.

Same with this too.
he still should be a repair vendor :)
he is on RED

![horace](https://user-images.githubusercontent.com/39439201/53701825-2f3e1d00-3e01-11e9-9fad-e9eb00ab6351.jpg)

**Comment by Rushor** [comment]
okay what exactly is the issue here then? @Echinaceax 

tested on dev. if i'm not a paladin, warrior or dk i cannot interact with the npc. if i am paladin, warrior or dk i can buy and repair :o 

pls contact me on discord for answer - thank you!

**Comment by Rushor** [comment]
okay i reason for the issueis: if there is not any kind of item the player could wear it will not show the page.

i will add a random item that everyone can see, so the repair page will be shown
