### ISSUE TITLE
[NPC] Rafael Langrom <Leather Armor Merchant>  Dalaran 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#785]
https://www.wowhead.com/npc=96978/rafael-langrom

- Inactive

**Comment by Rushor** [comment]
That's intended. If you are not a druid/rogue you cannot inspect his vendor page.

**Comment by Echinaceax** [comment]
still meant to be a repair vendor

**Comment by Rushor** [comment]
https://wowgaming.altervista.org/aowow/?npc=35497
