### ISSUE TITLE
[NPC] Matilda Brightlink <Mail Armor Merchant> Dalaran

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#786]
https://www.wowhead.com/npc=96980/matilda-brightlink

- Inactive
- need a Mail wearer to double check :)

**Comment by Rushor** [comment]
That's intended. If you are no shaman or hunter you cannot inspect her vendor page.

**Comment by sarahkay88** [comment]
it should still open up, to allow you to mend you gear

**Comment by Rushor** [comment]
https://wowgaming.altervista.org/aowow/?npc=35500
