### ISSUE TITLE
[quest=12521] [Where in the World is Hemet Nesingwary?] Sholazar Basin

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#787]
When u take the chopper from Dalaran and teleport into Sholazar Basin the chopper is nearly not moving

**Edited to add more info**
Allso i noticed, when i get shot down as i suppose to be i didnt get a parashot as im suppose to and died. Big bug
[quest=12521]
https://www.wowhead.com/quest=12521/where-in-the-world-is-hemet-nesingwary

**Comment by jarvik76** [comment]
Still an issue as at 3rd Oct.  Although, additionally the chopper did not despawn at all (although it took damage), so I was left sat in the chopper in mid-air unable to progress at all without GM assistance

**Comment by Rushor** [comment]
fixed!

speed is normal now

![I](https://i.imgur.com/MaGjaGo.png)
