### ISSUE TITLE
[quest=12645] [The Taste Test] Sholazar Basin

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#788]
This [npc=28047] refuse to tase [item=38697]
Quest not completable

[quest=12645]
https://www.wowhead.com/quest=12645/the-taste-test

**Comment by Rushor** [comment]
what exactly is not working? you need to go the the nps's target them and use the questitem on them.

**Comment by zippoking** [comment]
NPC: https://www.wowhead.com/npc=28047/hadrius-harlowe
Item: https://www.wowhead.com/item=38697/jungle-punch-sample

**What is happening:**
Out of 3 NPCs, this one is the only one at which the taste test doesn´t work. If you target him and use the item, it does not count towards the quest.
![The Taste Test - how it is](https://user-images.githubusercontent.com/18005338/59463589-a8003c80-8e26-11e9-97ce-791e6a75cb7d.png)


**What should happen:**
If you use the item on this NPC, it also should count towards the quest.

**Comment by Lerixo** [comment]
Can confirm. On same quest, same problem.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/IZpo3oa.jpg)
