### ISSUE TITLE
[quest=12569] [Crocolisk Mastery: The Ambush] Sholazar Basin

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#789]
Again 2 mobs summoned up on same time [npc=28317]

[quest=12569]
https://www.wowhead.com/quest=12569/crocolisk-mastery-the-ambush

**Comment by zippoking** [comment]
For me only one mob spawned. Seems to be fixed!

![Crocolisk Mastery - how it is](https://user-images.githubusercontent.com/18005338/59464245-34f7c580-8e28-11e9-88e9-88797d3f1692.png)

**Comment by Rushor** [comment]
then closed
