### ISSUE TITLE
[quest=12862] [When All Else Fails] The Storm Peaks

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#790]
This quest is not doable cuz of when you talk to Ricket in K 3 she summon a rocket
and that one should take you to Frosthold.
You can fly there by youself but when you come to Frosthold you cant get of the rocket
This is even same on Redemtion
And if you fly there by own bird this [npc=29744] Rork Sharpchin dont talk to you

[quest=12862]
https://www.wowhead.com/quest=12862/when-all-else-fails

**Comment by Rushor** [comment]
flight working now

![I](https://i.imgur.com/52q8uQy.jpg)

**Comment by Rushor** [comment]
https://www.wowhead.com/quest=12862/when-all-else-fails#videos:id=74931
