### ISSUE TITLE
stuck on "Success!"

### ISSUE THREAD

**Issue by yuwers** [WoWManiaUK/Blackwing-Lair#791]
my girlfriend and myself cannot log into the server, it continuously says "success" and gets stuck

**Comment by Echinaceax** [comment]
Hi to you both 
The cata server is a test server atm. (cata is off for the night)

This means its not live for anyone to play atm, only testers and devs are in there.

Server is on and off many times for fixes and whatnot
Wow-mania will up day the site when its "live"

**If you are interested in being a tester tho, you are more than welcome. you can contact @TheManiax 
here or in Discord**

**Comment by yuwers** [comment]
i would love to become a tester, my girlfriend would as well, i'd like to help in any way that i can! :)

**Comment by Echinaceax** [comment]
perfect :)
Are you both in wow-mania Discord ?
Pm Maniac or Phoenix and they will sort things out for you both
