### ISSUE TITLE
[quest=14482] [Call of Duty] -   Kelp'thar Forest

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#793]
This quest u cant turn in
When u come to the Briny Cutter then quest resiver is not there.
The ship is suppose to go under but thats not happening.

[quest=14482]
https://www.wowhead.com/quest=14482/call-of-duty

**Comment by Echinaceax** [comment]
Npc - https://www.wowhead.com/npc=36915/erunak-stonespeaker

**Comment by Kitzunu** [comment]
Duplicate of #244
