### ISSUE TITLE
[NPC] Helix Gearbreaker

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#794]
Second boss in Deadmines are bugged and not targetable (the little goblin) riding on the boss.
Not possible to get further in the instance
[npc=47297]

**Comment by Echinaceax** [comment]
I just watched the video to this fight (as ive never actually done this fit myself)

but in the video also doesnt attack him for a while 
take a look https://www.youtube.com/watch?v=CSRwjFLjmcc

**Comment by Kitzunu** [comment]
Confirmed.
https://www.wowhead.com/npc=47296/helix-gearbreaker

Helix Gearbreaker is not attackable
![image](https://user-images.githubusercontent.com/24550914/54040110-e30a2880-41c4-11e9-81ef-92ca645faf8c.png)
