### ISSUE TITLE
[Quest] Wildmane Cleansing id 24524 - Mulgore

### ISSUE THREAD

**Issue by dandancanfly** [WoWManiaUK/Blackwing-Lair#795]
Quest: Wildmane Cleansing
I am a level 9 Tauren Shaman

I'm at Wildmane Water Well, but I'm unable to cleanse the well. It says "Requires Wildmane Water Well".

Looks like item 5416 / quest 24524

https://www.wowhead.com/item=5416/wildmane-cleansing-totem

![image](https://user-images.githubusercontent.com/11138461/53752186-fd1dd100-3e7b-11e9-9777-0c40f7b34cc8.png)

**Comment by Kitzunu** [comment]
No change, same issue

**Comment by PsycsX** [comment]
Quest isn't flagged as bugged, so .bq doesn't work.

**Comment by Malfaeous** [comment]
I am also having the same problem with this issue, just thought you guys might want a heads up.

**Comment by rzenne** [comment]
same issue i'm having

**Comment by JustDNF** [comment]
@Rushor @wow-mania @Keader This needs a look at. Not working 19.11.20

**Comment by Echinaceax** [comment]
hey @GMWeeble :)

The main DEV for Reign now is @mfranca0009 😄

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
confirmed fixed in ptr 

![image](https://user-images.githubusercontent.com/39439201/119258512-36ac9500-bbca-11eb-9a5b-8c87dfcb5dd9.png)
