### ISSUE TITLE
[NPC] Twilight Infiltrator - (Doubles) - Mount Hyjal

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#796]
These 3 npc's u have to kill to enter the cove and blow the horn are not 3 but 6.
Doubblegangers. to many to  kill.

https://www.wowhead.com/npc=40882/twilight-infiltrator

[quest=25574]
https://www.wowhead.com/quest=25574/flames-from-above

**Comment by Echinaceax** [comment]
Still an issue 28.9.19
