### ISSUE TITLE
[quest=27135] [Something that Burns] The Maelstrom

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#797]
U cant summon the firemob anywhere in these lavapools. 
U only been told that u need to be in that area u allready are in.

[quest=27135]
https://www.wowhead.com/quest=27135/something-that-burns

**Comment by randomglitch** [comment]
Not listed as bugged in .BQ

![image](https://user-images.githubusercontent.com/7579461/92469514-d5c06680-f1cc-11ea-83fd-6275c5f2680d.png)

**Comment by Echinaceax** [comment]
@randomglitch We know, not all are going to be added too the .bq command
janitor only added a 170 to the list and is not doing anymore.

will have to wait for fix @randomglitch 
make a ticket and a gm will help you

**Comment by mfranca0009** [comment]
Quest item is able to be spawned, and once the totem is spawned, Magmatooth appears.

Almost fixed, still need to add Magmatooth's text interaction with player.

**Comment by mfranca0009** [comment]
All set, quest can now be completed and the Fire Totem quest item can be placed. On top of that, Magmatooth is summoned when totem is put down, and he says his proper text lines and performs his proper abilities. 👍

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR

![image](https://user-images.githubusercontent.com/39439201/103282695-dd538780-49d6-11eb-8c6b-8772eb115f48.png)
