### ISSUE TITLE
[Quest] A Fel Whip For Gahk -11079- Blade's Edge Mountains

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#800]
quest - https://www.wowhead.com/quest=11079/a-fel-whip-for-gahk
npc - https://www.wowhead.com/npc=23355/zarcsin

- He didnt drop the whip after kill - https://www.wowhead.com/item=32733/fel-whip

i had 35 shards to start the quest (so thats not the problem)

![didnt drop the whip](https://user-images.githubusercontent.com/39439201/53780054-e2db0600-3f02-11e9-9229-246d9546c09c.jpg)

there are a few other NPC that "could" drop it (haven't tested the others yet)
i may need to change this title too " NPC zarcsin" will let you know :)

**_Edited to add_** 
- galvanoth not dropping either

![galvanoth](https://user-images.githubusercontent.com/39439201/53781268-719e5180-3f08-11e9-9c1a-bd4ca8b10442.jpg)

**quote from wowhead comments**
> The demon that you summon regardless of which summoning stone you use will drop one Apexis Crystal, and the Fel Whip for this quest. 

- Safe to say "there is a problem"
https://www.wowhead.com/npc=22281/galvanoth

**Comment by Kitzunu** [comment]
Fixed, will send when I am home.
