### ISSUE TITLE
[NPC] Hungry Plaguehound -23943- Howling Fjord

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#801]
npc - https://www.wowhead.com/npc=23943/hungry-plaguehound

- The quest pet is ninja pulling the "wild worg"
https://www.wowhead.com/npc=24128/wild-worg

- Im sure hes not meant too :)
- Can you check his aggro 

![naught puppy](https://user-images.githubusercontent.com/39439201/53785149-de6d1800-3f17-11e9-9606-bac5a1df529d.jpg)
![argroing](https://user-images.githubusercontent.com/39439201/53785155-e2009f00-3f17-11e9-9aa1-7f33fd961fd1.jpg)

**Comment by Rushor** [comment]
they act defensive now.
