### ISSUE TITLE
[NPC]  North Fleet Marine -23983- (bugged) Howling Fjord (issue 1)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#802]
**Issue 1** 

npc - https://www.wowhead.com/npc=23983/north-fleet-marine

- north fleet marine is attacking dead forsaken-deckhands
 https://www.wowhead.com/npc=141638/forsaken-deckhand

![forsaken deckhand dead](https://user-images.githubusercontent.com/39439201/53787537-80dcc980-3f1f-11e9-812a-b179c6228b4c.jpg)
![still attacking it](https://user-images.githubusercontent.com/39439201/53787543-8a663180-3f1f-11e9-9bd6-d95958e43fc7.jpg)

**Comment by Kitzunu** [comment]
Not fixed.
NPC is still attacking dead Forsaken.
The Forsaken Deckhand is not able to respawn with `.respawn` 
Is it possible that something fucked up the respawn possibility of the npc?
![image](https://user-images.githubusercontent.com/24550914/53834726-1615a780-3f8c-11e9-84e5-94c37966c2b3.png)

**Comment by Rushor** [comment]
The Forsaken Deckhand are always dead they cannot be looted. Only the  North Fleet Marine can be looted once killed.

**Comment by Kitzunu** [comment]
AH okay, I missed that. My bad.
Though the North Fleet Marine is still attacking the Dead Forsaken

**Comment by Echinaceax** [comment]
> The Forsaken Deckhand are always dead they cannot be looted. Only the North Fleet Marine can be looted once killed.

No the loots are not "lootable" on the North Fleet Marine, i wasnt trying to loot the deads :)

**Comment by Kitzunu** [comment]
this was fixed long time ago by rushor
