### ISSUE TITLE
[NPC] North Fleet Marine -23983- (not lootable) Howling Fjord (issue 2)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#803]
**Issue 2** 

npc - https://www.wowhead.com/npc=23983/north-fleet-marine

- Not lootable = no loot (they should be)
- killed 13 so far and not 1 has been lootable :)
- No pretty sparkles indicating looting lol

![no loot](https://user-images.githubusercontent.com/39439201/53788069-fbf2af80-3f20-11e9-8229-8b3eb32e9914.jpg)

**loot drops** 

![marines loots](https://user-images.githubusercontent.com/39439201/53788417-0c575a00-3f22-11e9-9730-091bf003ac77.jpg)

**Comment by Echinaceax** [comment]
**correction** 

1 of 14 was lootable (grey junk) and thats not even on the loot table lol

![fur lined boots](https://user-images.githubusercontent.com/39439201/53788794-0e6de880-3f23-11e9-8d31-b03114dccc62.jpg)


- Still wrong loot %

![gray crap](https://user-images.githubusercontent.com/39439201/53788656-b931d700-3f22-11e9-87ee-4a555581b6f6.jpg)

**Comment by Kitzunu** [comment]
Cannot be tested yet until #802 is fixed

**Comment by Echinaceax** [comment]
thx guys :)
