### ISSUE TITLE
[Combat bug] Honor Hold Inn - Hellfire

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Blackwing-Lair#805]
**How it works:**
When you enter Honor Hold Inn, in the very entrance you will enter and leave combat immedietly.
![image](https://user-images.githubusercontent.com/24550914/53840529-a9ee7000-3f9a-11e9-887b-34ae90586b64.png)

**How it should work:**
You should not enter combat when you enter Honor Hold Inn

**Comment by Echinaceax** [comment]
> **How it works:**
> When you enter Honor Hold Inn, in the very entrance you will enter and leave combat immedietly.


The thing thats odd also is that the "screeching from the Gryphon Rider Guard"

After removing the Gryphon Rider Guard from above the Inn do you still get the screetching noise or just the in combat text now ?

**Comment by Kitzunu** [comment]
No
