### ISSUE TITLE
[Quest] Stocking Up -28419- Burning Steppes

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#806]
quest - https://www.wowhead.com/quest=28419/stocking-up
**item** - https://www.wowhead.com/item=63135/razor-sharp-scorpid-barb
quest npc - https://www.wowhead.com/npc=9691/venomtip-scorpid

**Current Behaviour:**

- venomtip scorpid not dropping quest item 63135

![scorpid](https://user-images.githubusercontent.com/39439201/53877420-62eb9380-4009-11e9-989d-203361d5d938.jpg)
![razor](https://user-images.githubusercontent.com/39439201/53877426-654ded80-4009-11e9-9406-fdc6b5d8b0a8.jpg)

**Expected Behaviour:**

- Should be dropping at 39% 
- 0% atm

**Comment by Kitzunu** [comment]
Fixed, will send when I am home
