### ISSUE TITLE
[Quest] A Future Project -28420- Burning Steppes

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#807]
quest - https://www.wowhead.com/quest=28420/a-future-project

**_Obtain 11 Ember Worg Hides._**

**Current Behaviour:**

- No Hides are dropping 
- Meant to be 82% droprate 

![a future](https://user-images.githubusercontent.com/39439201/53880069-561e6e00-4010-11e9-91e0-fd144b657a0d.jpg)

**ember-worg 82%**
npc https://www.wowhead.com/npc=9690/ember-worg
![ember-worg 82](https://user-images.githubusercontent.com/39439201/53878742-f2467600-400c-11e9-8c03-a9dc67539dcc.jpg)

**giant-ember-worg 1.3%** 
https://www.wowhead.com/npc=9697/giant-ember-worg

![giant-ember-worg 1](https://user-images.githubusercontent.com/39439201/53878764-012d2880-400d-11e9-84d4-9f8a4b6e5b0c.jpg)

**Expected Behaviour:**

- ember-worg 82% not 0%
- giant-ember-worg 1.3% not 0%

**Comment by Rushor** [comment]
added with 80 percent

![I](https://i.imgur.com/14zTbwg.jpg)
