### ISSUE TITLE
[spell=177928] [Recuperate]

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#808]
**Links:**
https://www.wowhead.com/spell=177928/recuperate

**What is happening:**
Rogue healing spell [spell=177928]

This spell you can use when u have combo points on the target. But when the target dies then the
combo point disapear 

**What should happen:**
i pretty sure that the combo points should stay on target even if its dead so u can use the spell [spell=177928] [Recuperate] to heal.

**Comment by Keader** [comment]
Pretty sure it's not valid '-'

**Comment by HarryRogue** [comment]
I still agree with first post.  I remember you could still use CP on death mobs.

**Comment by giles1508** [comment]
I've already made a post about this with video footage
