### ISSUE TITLE
[quest=13045] [Into The Wild Green Yonder] - Icecrown

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#810]
**Links:**
[quest=13045] https://www.wowhead.com/quest=13045/into-the-wild-green-yonder

_Rescue 3 Captured Argent Crusaders from Scourgeholme and drop them off at the Vanguard Infirmary at the center of the Argent Vanguard. Report to Highlord Tirion Fordring should you succeed._ 

**Current Behaviour:**
Cant drop the captured Crusader on dropsight

**Expected Behaviour:**
You should be able to drop the Crusader by the fire in camp but when u press the button to drop them of it says you cant do that yet.

**Steps to reproduce the issue:**

**Comment by Sammy974** [comment]
i can conferm that.

**Comment by NoraDR** [comment]
Not flagged as bugged? so rip the rest of the quests then ig.

**Comment by Echinaceax** [comment]
any more info on this ?

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/EsFJa9J.jpg)

you need to be near that position in order to get the credit.

**Comment by Echinaceax** [comment]
Still an issue according to player

**Comment by Echinaceax** [comment]
will retest this as the flight bug was fixed elsewhere

The new issue now is that you can mount the drake but you cant fly @Rushor
