### ISSUE TITLE
[Quest] The Skull of Gul'dan - ID28256 - Felwood

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#812]
**Links:**

quest - https://www.wowhead.com/quest=28256/the-skull-of-guldan
video - https://www.wowhead.com/quest=28256/the-skull-of-guldan#videos:id=82380

_See him in battle, <class>. Witness the one that fought the fiercest against the corruptors of Felwood, and struck at its source._

**What is happening:**

- Auto-completing without having to do anything

**What should happen:**

https://www.wowhead.com/quest=28256/the-skull-of-guldan#videos

**Comment by mfranca0009** [comment]
Going to start working on this shortly.

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
confirmed fixed in PTR
