### ISSUE TITLE
[Quest] The Fall of Tichondrius ID28257 - Felwood

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#813]
**Links:**
Quest - https://www.wowhead.com/quest=28257/the-fall-of-tichondrius
video - https://www.wowhead.com/quest=28257/the-fall-of-tichondrius#videos:id=82381

_Relive Illidan's battle with Tichondrius._

**What is happening:**

- Auto completing without doing anything

**What should happen:**
- I should fight Tichondrius

video - https://www.wowhead.com/quest=28257/the-fall-of-tichondrius#videos:id=82381

**Comment by Rushor** [comment]
this event is so huge i love it

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
CONFIRMED fixed in PTR
