### ISSUE TITLE
[Quest] WANTED: The Demon Hunter -28217- Felwood

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#815]
**Links:**
quest - https://www.wowhead.com/quest=28217/wanted-the-demon-hunter

**What is happening:**
- Cant attack him 

**What should happen:**
- I should fight him 

video - https://www.youtube.com/watch?v=Hh6zU70dfJI

**Comment by Kitzunu** [comment]
d

**Comment by mfranca0009** [comment]
This is NOT fixed, he should have a gossip option appear when the quest is active. When you select the gossip option, he will become hostile and you fight him. This does not happen currently.

![image](https://user-images.githubusercontent.com/26092980/103180779-1e2c8e80-4867-11eb-8b6b-f97d66082229.png)

![image](https://user-images.githubusercontent.com/26092980/103180793-33a1b880-4867-11eb-9616-3d19c768f1dc.png)

**Comment by mfranca0009** [comment]
This should be all set, needs testing in PTR 👍

**Comment by HrafnValknutt** [comment]
Fix in Dev confirmed.
