### ISSUE TITLE
[Talent] Impact - ID 12357

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Blackwing-Lair#816]
**Broken Talent;**
![image](https://user-images.githubusercontent.com/33989250/53961652-f8386780-409d-11e9-895a-424c3e9d1dac.png)

**Related Spells;**
![image](https://user-images.githubusercontent.com/33989250/53961563-bd363400-409d-11e9-9dc7-8c95272d0b58.png)
![impactpersonal](https://user-images.githubusercontent.com/33989250/53961759-3766b880-409e-11e9-82dc-073794067374.png)

**What's wrong;**
When Impact procs, it will never reset the cooldown of Fire Blast.

**How to reproduce;**
Use Fire Blast on any target, then use any damaging spell such as Scorch - ID 2948
When the talent procs, Fire Blast will not be usable yet, as it's CD will not have reset as shown below.

![impactcd2](https://user-images.githubusercontent.com/33989250/53962127-1f436900-409f-11e9-8879-a4e0488925de.png)

**Comment by Keader** [comment]
Fixed.
