### ISSUE TITLE
[Talent] Cauterize - ID 86949

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Blackwing-Lair#817]
**Talent;**
![cauterize](https://user-images.githubusercontent.com/33989250/53963682-9cbca880-40a2-11e9-8c3e-96c320e97e7b.png)

**What's wrong;**
Does not proc. 

**How to reproduce;** 
Take any fatal damage from any NPC/Player.

**Comment by Keader** [comment]
fixed.
