### ISSUE TITLE
[Spell] Portal: Shattrah -visual or missing

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#818]
**Links:**
spell: https://www.wowhead.com/spell=35715/teleport-shattrath
NPC: https://www.wowhead.com/?npc=20791

from WoWHead or our Armory

**What is happening:**
Mage's cannot learn the solo portal to Shattrath.
every other portal is available for my lvl 85 mage, including the group portal for Shattrath. Just not solo portal. I check spells available and spells learn by the trainer, but it isn't there. Never needs to use it until now, so only just noticed.

**What should happen:**
At level 62 a mage should be able to learn the spell portal: Shattrath however this is currently not supplied.
 

![world of warcraft 07_03_2019 17_12_44](https://user-images.githubusercontent.com/42302580/53975894-c820b100-40fd-11e9-85d9-8a56efc0f575.png)
![world of warcraft 07_03_2019 17_13_42](https://user-images.githubusercontent.com/42302580/53975896-c9ea7480-40fd-11e9-9142-d4c1150e6244.png)

**Comment by Keader** [comment]
Wrong.
Shattrath portal needs level 66.

**Comment by sarahkay88** [comment]
My toon is lvl 85

**Comment by Keader** [comment]
Still cant reproduce (tested in dev server)

![image](https://user-images.githubusercontent.com/7120913/53984882-010a5700-40f9-11e9-80a8-ceb2b7baf0ca.png)

**Comment by sarahkay88** [comment]
Yea I can get that one. It's the one that tps just the mage

**Comment by sarahkay88** [comment]
Wait it's my bad I linked the wrong spell let me see if u can find the solo one

**Comment by sarahkay88** [comment]
This is the correct spell: https://www.wowhead.com/spell=35715/teleport-shattrath - require level 62
Really sorry about that

**Comment by Keader** [comment]
Ah, now make sense.
Fixing...

**Comment by Keader** [comment]
![image](https://user-images.githubusercontent.com/7120913/53986919-32d1ec80-40fe-11e9-9a51-21d4983bf439.png)
Fixed on Dev.
Will be on "ptr" in next update 👍

**Comment by sarahkay88** [comment]
Cheers ty

**Comment by sarahkay88** [comment]
@Keader  its reverted and missing again

**Comment by Keader** [comment]
Fixed (again ¬¬)
