### ISSUE TITLE
[Quest] Apply Heat and Stir -11306- Howling Fjord

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#819]
**Links:**
quest https://www.wowhead.com/quest=11306/apply-heat-and-stir
video https://www.wowhead.com/quest=11306/apply-heat-and-stir#videos:id=62185

_Fill the Empty Apothecary's Flask at the Cauldron of Vrykul Blood, then mix the Flask of Vrykul Blood with Harris's Plague Samples nearby until you've obtained a Balanced Concoction_

**What is happening:**
- Nothing ..table is not active to mix with Harris's Plague Samples
- Table (see video) 

![not active](https://user-images.githubusercontent.com/39439201/54016229-8c7bfa80-4182-11e9-92f4-4650297f6ed8.jpg)

**What should happen:**
- Table is suppose to be sparkling to indicate that the Harris's Plague Samples is there 
- Should be able to interact with the table and Cauldron (back and forth till the right mix is completed)

**Comment by Rushor** [comment]
![I](https://i.imgur.com/0naYPhI.jpg)

you need to klick the items in your inventory until you get finally the questitem. there is high chance to fail that

**Comment by Echinaceax** [comment]
### Not fixed 

**fill from cauldren**
![fill](https://user-images.githubusercontent.com/39439201/79688282-a2952f00-824d-11ea-8470-ab1583d20843.jpg)

**mix on table**
![filled](https://user-images.githubusercontent.com/39439201/79688311-ceb0b000-824d-11ea-8387-d5a1d89002ad.jpg)



Items work and the filling and mixing woeks BUT no quest credit
