### ISSUE TITLE
[ITEM] Loramus' Legs - missing

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#820]
**Links:**
Quest: https://www.wowhead.com/quest=26161/not-just-any-body
NPC: https://www.wowhead.com/npc=42298
ITEMS:
1)https://www.wowhead.com/item=55829 - Loramus' Head
2)https://www.wowhead.com/item=55836 - Loramus' Torso
3)https://www.wowhead.com/item=55837 - Loramus' legs

from WoWHead or our Armory

**What is happening:**
I can collect item 1 & 2 needed for this quest, However item 3 is missing. This prevents you from completing the quest.

**What should happen:**
You should entre the 3 caves in the correct location, inside each cave is a chest with loot containing one of the items mentioned above, however the cave contain item 3 does not have a chest to loot.

**Comment by Kitzunu** [comment]
@Rushor Gameobject missing
