### ISSUE TITLE
(Quest) Culling the Wendigos - Low Priority - Dun Morogh

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#822]
**Links**
Quest - https://www.wowhead.com/spell=35715/teleport-shattrath
Npc - https://www.wowhead.com/npc=40950
Mob Npc - https://www.wowhead.com/npc=40940 -Young Wendigo
                   https://www.wowhead.com/npc=40941 - Wendigo
Video - https://www.youtube.com/watch?v=pU7i3199uW8&feature=youtu.be&list=PLt_6QKYzJ9hsIljvXcRqv3BfkpBUafyoz
from WoWHead or our Armory

**What is happening:**
Excessive Number of mobs outside cave and inside cave in packs of 3 so maybe due to double spawns  ( approx. - 25 outside 30-40 inside cave)
due to aggro range pulling vast numbers of mobs at once. making it harder to complete quest (is still doable hence low Priority)

**What should happen:**
In retail only 5-8 mobs outside and approx. 12 -18 inside cave not in packs of 3 

![world of warcraft 07_03_2019 22_20_58](https://user-images.githubusercontent.com/45798884/53993465-5fe6c500-4127-11e9-880d-a6c33436d213.png)

![world of warcraft 07_03_2019 22_22_08](https://user-images.githubusercontent.com/45798884/53993521-8c024600-4127-11e9-8631-329e9e0ad6a6.png)

**Comment by bagi84** [comment]
This also relates to the following quest for the same reasons due to having to collect items in the cave 
Quest - https://www.wowhead.com/quest=25668/pilfered-supplies
Npc - https://www.wowhead.com/npc=40951
Item - https://www.wowhead.com/item=55151

**Comment by Rushor** [comment]
reduced the amount of spawned Young Wendigos/Wendigo and added pooling to them

**Comment by Kitzunu** [comment]
Looks a lot better now
