### ISSUE TITLE
[Quest] Pushing Forward - ID 25792 - Dun Morogh

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#824]
**Links:**
Quest - https://www.wowhead.com/quest=25792/pushing-forward
NPC - https://www.wowhead.com/npc=40950
Quest item - https://www.wowhead.com/item=56009
from WoWHead or our Armory

**What is happening:**
Constriction Totems are in the correct place but not active ( as in not constricting mountaineers) and also Targetable but you are un able to use quest item to destroy them.
Not sure if its is related but there are random Imps near the totems that are un-targetable and inactive. These defiantly shouldn't be there. 

**What should happen:**
The Quest item should be able to be thrown at the totems to destroy them in order to complete the quest realsing the constricted mountaineers.

How it should appear
![191255-pushing-forward](https://user-images.githubusercontent.com/45798884/54029642-06bb7780-41a1-11e9-9a03-49367c770a47.jpg)

On test Realm
![world of warcraft 08_03_2019 12_44_09](https://user-images.githubusercontent.com/45798884/54029678-20f55580-41a1-11e9-8e88-d938553d89f4.png)

**Comment by iTz-AddriX** [comment]
**Confirmed** #4311

**Comment by mfranca0009** [comment]
Constriction Totem Aura: https://www.wowhead.com/spell=77311/constriction-totem-aura

![image](https://user-images.githubusercontent.com/26092980/119273894-04effa00-bbdb-11eb-828d-d66324af3884.png)

It states the Constriction Totem Aura that should effect the mountaineers was "removed", but the patch notes for 4.0.6 under creatures and quests does not reflect this, so for now, the aura will be used while fixing the rest of the quest.

Patch 4.0.6: https://wowwiki-archive.fandom.com/wiki/Patch_4.0.6

![image](https://user-images.githubusercontent.com/26092980/119273978-8b0c4080-bbdb-11eb-8847-9b369e23d419.png)

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
confirmed fixed in ptr 

![image](https://user-images.githubusercontent.com/39439201/119343320-8f496400-bc96-11eb-99c9-c2ef0c679e44.png)
