### ISSUE TITLE
[Quest] The View from Down Here- ID 28868 - Dun Morogh

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#826]
**Links:**
Quest - https://www.wowhead.com/quest=28868/the-view-from-down-here
NPC - https://www.wowhead.com/npc=50601
Quest Item - https://www.wowhead.com/item=67249
Mob NPC - https://www.wowhead.com/npc=50606
from WoWHead or our Armory

**What is happening:**
Quest is available without completing linking chain quest #302 ( ID 25839) which I believe it shouldn't be.
You receive the quest item and can use this item to shrink the Mob NPC but it doesn't count towards the quest

**What should happen:**
Quest item should be used to shrink Mob NPC for Quest completion

**Comment by Rushor** [comment]
not sure about the questline. please create a new issue for that. will fix the event first

**Comment by bagi84** [comment]
Add previous reported chain quest # number for you Rushor
