### ISSUE TITLE
[Quest] Seize the Ambassador - ID 26118 - IronForge

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#828]
**Links:**
Quest - https://www.wowhead.com/quest=26118/seize-the-ambassador
NPC - https://www.wowhead.com/npc=42129
Mob NPC - https://www.wowhead.com/npc=42146/ambassador-slaghammer
Quest Item - https://www.wowhead.com/item=56837
from WoWHead or our Armory

**What is happening:**
When Quest item is used to "Arrest" the Mob NPC it creates a duplicate of the Mob NPC instead of capturing it

**What should happen:**
the Item should be used to "arrest" the  Mob NPC  shackling it  and enable it to follow you back to the NPC.

![world of warcraft 08_03_2019 14_37_03](https://user-images.githubusercontent.com/45798884/54035277-e4315a80-41b0-11e9-8e0c-b7ac1362c45d.png)

**Comment by Rushor** [comment]
in progress

**Comment by Saintres** [comment]
I did the quest today and i captured him as i should do and he follow me back to the High Seat room.
But Moira dont get my quest to be completed when i get there. She still have a grey ? over her head even if we stand just beside her.

**Comment by bagi84** [comment]
Double checked this and item still duplicates npc even though the first use captures the npc

**Comment by Echinaceax** [comment]
Any new info on progress @Rushor ?

**Comment by rzenne** [comment]
Tried it today and problem still exists

**Comment by mfranca0009** [comment]
The only issue is quest completion not being triggered, arresting the Ambassador functions properly as it should. Also, this is missing all the creature dialog as well.

Working on this now

**Comment by Echinaceax** [comment]
i see Rushor was actually on this in the start, so duplication of NPCs must have been fixed
So its good that you saw were Rushor left off @mfranca0009 😄

**Comment by mfranca0009** [comment]
Incorporated the proper spell fail if player already has the prisoner 👍 
![image](https://user-images.githubusercontent.com/26092980/119552260-7f01b980-bd68-11eb-83ac-1ad6417553ce.png)

**Comment by mfranca0009** [comment]
All set 👍
