### ISSUE TITLE
[NPC] The Frozen Heart of Isuldof -11512- Howling Fjord

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#829]
**Links:**
https://www.wowhead.com/quest=11512/the-frozen-heart-of-isuldof

![isuldof](https://user-images.githubusercontent.com/39439201/54038188-375ed980-41c0-11e9-8c69-b2edd613188e.jpg)

![back a bit](https://user-images.githubusercontent.com/39439201/54038207-40e84180-41c0-11e9-92a4-a264487a564a.jpg)

![cant attack](https://user-images.githubusercontent.com/39439201/54038220-46458c00-41c0-11e9-8eff-ece324ed2116.jpg)

**What is happening:**
- He is hovering above the ground
- He is not attackable (invalid target)  

**What should happen:**
- He should not be hovering 
- He should be attackable

**Comment by Dranah** [comment]
This is intended. This NPC does not need to be killed.
The heart for quest ID 11512 is looted in some cave, not from this mob. This NPC is required for https://www.wowhead.com/quest=11568/a-return-to-resting which requires you to use a quest item on him. The quest does not require you to attack him. video https://www.youtube.com/watch?v=AR_TpmtJvOM
