### ISSUE TITLE
[NPC] Darnell -49425- Deathknell

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#830]
**Links:**
https://www.wowhead.com/npc=49425/darnell

**What is happening:**
- Darnell seems to be following me after i clicked the tombstone

![darnell](https://user-images.githubusercontent.com/39439201/54041027-f9b17f00-41c6-11e9-8362-6c161d181551.jpg)

- Is there meant to be a quest on this Tombstone?

**What should happen:**
not sure atm

**Comment by Kitzunu** [comment]
Darnell is a questgiver

**Comment by Echinaceax** [comment]
yes i saw that on the link but 
i clicked the tombstone as above SS shows ...then he started following me .

just now i picked up a quest https://www.wowhead.com/quest=26800/recruitment

where Darnell was picking up dead bodies (i had Darnell before) i took the quest for him to help:)

![recruitment](https://user-images.githubusercontent.com/39439201/54042927-9b3acf80-41cb-11e9-9cda-873e4d8d92ac.jpg)

**Comment by Echinaceax** [comment]
maybe my question should have been 
![darnell3](https://user-images.githubusercontent.com/39439201/54044160-8d3a7e00-41ce-11e9-83a0-b0e8dfa99379.jpg)

what is meant to be here ?

**Comment by Echinaceax** [comment]
> Darnell is a questgiver, so if he isnt giving you a quest at level 4 that would be an issue :)

notfor the issue i was reporting tho :)
