### ISSUE TITLE
[NPC] Agatha -49044- Deathknell 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#832]
**Links:**
https://www.wowhead.com/npc=49044/agatha

![agatha](https://user-images.githubusercontent.com/39439201/54041900-2feffe00-41c9-11e9-8932-e8cee352ee44.jpg)

**What is happening:**

- She is bugged half under the ground

**What should happen:**

- She should be higher up so she is hovering above the ground

**Comment by Rushor** [comment]
meh this was bugged for all those creatures again. refixed.

**Comment by Rushor** [comment]
![](https://i.imgur.com/mfSQI2S.jpg)
