### ISSUE TITLE
[NPC] Daschla -49128-Deathknell

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#833]
**Links:**
https://www.wowhead.com/npc=49128/daschla

![daschla](https://user-images.githubusercontent.com/39439201/54042282-084d6580-41ca-11e9-952d-d9463bfc2edf.jpg)

**What is happening:**

- She is bugged half under the ground

**What should happen:**

- She should be higher up so she is hovering above the ground

**Comment by Kitzunu** [comment]
no change
![image](https://user-images.githubusercontent.com/24550914/54076277-24c0cf00-42aa-11e9-9202-a413f9528ffc.png)

**Comment by Echinaceax** [comment]
awww noooo

**Comment by Rushor** [comment]
hmm but why

**Comment by Kitzunu** [comment]
@Rushor FYI it was because of creature_template_movement.flight = 2 (CanFly) instead of 1 (DisableGravity)
