### ISSUE TITLE
[Quest/warrior] Charge! - The Sunspire

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#834]
Npc - https://www.wowhead.com/npc=43010/delios-silverblade

- Cant complete Charge on Training dummies
- delios-silverblade hasnt trained us https://www.wowhead.com/spell=100/charge

![charge - war](https://user-images.githubusercontent.com/39439201/54070987-60867500-4267-11e9-9e0e-096a38a05d68.jpg)

- Need to learn charge

**Comment by Rushor** [comment]
creature questender is: https://www.wowhead.com/npc=15295/well-watcher-solanian

**Comment by Echinaceax** [comment]
I cant train "charge" spell from delios-silverblade
![learn charge](https://user-images.githubusercontent.com/39439201/54072273-d8a96680-4278-11e9-999c-93c0c1315e37.jpg)

**Comment by Echinaceax** [comment]
![charge t](https://user-images.githubusercontent.com/39439201/54072433-01caf680-427b-11e9-90b9-43ffd8257cf6.jpg)

**Comment by Kitzunu** [comment]
Works 
![image](https://user-images.githubusercontent.com/24550914/59540955-a8203b00-8eff-11e9-9af9-0bcaa9da1baf.png)
