### ISSUE TITLE
[Bloodelf] char selection screen (Hair and face) bugged

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#835]
![belf rogue no hair](https://user-images.githubusercontent.com/39439201/54071152-359d2080-4269-11e9-9600-790ea865a8d9.jpg)

**What is happening:**
- Rogue has 4 hair styles are missing (bald) 
- Warlock
- Mage

**What should happen:**
- they should have hair :)

**Reproduce**
- click through them all and you will see :)

**Comment by wow-mania** [comment]
This is going to be as-is for now. When we do a client patch we try to fix it as part of the HD Textures package.
