### ISSUE TITLE
[Quest/Warlock] immolate - The sunspire 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#837]
**Links:**
https://www.wowhead.com/npc=15283/summoner-telilarien

![teli lock](https://user-images.githubusercontent.com/39439201/54071864-f8d62700-4272-11e9-955d-ebfbb570119a.jpg)

**What is happening:**

- Cant hand quest back

**What should happen:**

Quest should be given back here

**Comment by Rushor** [comment]
questender for this quest is https://www.wowhead.com/npc=15295/well-watcher-solanian
