### ISSUE TITLE
[quest=26208] [The Fight Continues] - Dun Morogh

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#839]
**Links:**
[quest=26208]
https://www.wowhead.com/quest=26208/the-fight-continues

**What is happening:**
The quest works but it get completed just befor it start. kinda (auto completes)

**What should happen:**
You should se the NPC's talk and show the holographic befor it get completed.

**Comment by Rushor** [comment]
quest completition now only once the event is over
