### ISSUE TITLE
[Spell] Combustion

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#84]
Spell ID 11129

Currently the spell deals its instant damage part, but does not do anything else.

(sorry for copy pasta but i'm lazy - credits to the source)

    Here's how this spell works in 4.0.1 and beyond:

    1. You cast Combustion on an enemy target.
    2. It deals a small, insignificant amount of fire damage on its own.
    3. Then the game adds up the total DPS of all the fire dots you have on the target.
    4. A new dot, called Combustion, is placed on the target that ticks for that total dps, every second for 10 seconds.

    So let's say the following dots are on your target when you cast Combustion...

    Ignite ticking for 3000 every 2 seconds (1500 dps)
    Pyroblast ticking for 900 every 3 seconds (300 dps)
    Living Bomb ticking for 1500 every 3 seconds (500 dps)

    Combustion will tick for 2300 every second for 10 seconds, for a total of 23000 damage. Combustion's dot ticks are capable of critting and you also get more ticks the more haste you have. You can also spread Combustion to all targets in about 10 yards with Impact procs for some disgusting AoE damage.

Key fire mage ability, added priority.

**Comment by Dranah** [comment]
This is broken on this core version in same way.

**Comment by Cenasty** [comment]
New issue :

Combustion spread by Impact doesn't spread the same damage from original target to nearby ones.

Here, a small screenshot of Skada damage, not precise tho but relevant
Main target suffer Combustion for 12k, combined of all dot, and a nearby target, or all, I don't know, too much numbers ^^') suffer 0.6k.

Nearby target doesn't get the same amount of damage it should have

https://puu.sh/DY3RG/3966061ce3.png

**Comment by Cenasty** [comment]
Here a recount details damage showing that tick have not the same damage value, proofing that spreaded damage aren't right.

https://puu.sh/E1XuD/def65d3ff3.png

Since Combustion' DoT is gathering all current DoT and make it one 'big' new according to critics, haste, mastery and spellpower at the cast time, there shouldn't be any difference between min/max/average as in normal HITs or Crits
