### ISSUE TITLE
[Quest] joining the battle id 28780 - missing - Human Rouge

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#841]
**Links:**
Quest - https://www.wowhead.com/quest=28780/join-the-battle
NPC- https://www.wowhead.com/npc=43278
from WoWHead or our Armory

**What is happening:**

This is the 3rd quest in the start zone for human rouges, after handing in quest https://www.wowhead.com/quest=28759/lions-for-lambs, you should then receive the quest above however it is not supplied this prevents you from continuing the chain quest.
Effected quest that cannot be obtained:
 https://www.wowhead.com/quest=28791/they-sent-assassins
https://www.wowhead.com/quest=28817/the-rear-is-clear
this also prevents you from collecting the class specific quest:  the deepest cut https://www.wowhead.com/quest=26915/the-deepest-cut

**What should happen:**
After completing the second quest in this chain you should receive the quest above to complete the starting quest for human rouges.

**Comment by Rushor** [comment]
ypu first need to complete https://www.wowhead.com/quest=26917 and https://www.wowhead.com/quest=26910 in order to get https://www.wowhead.com/quest=28780/join-the-battle

please retest that

**Comment by sarahkay88** [comment]
Those are hunter quest that you linked. This is a human rouge issue

**Comment by bagi84** [comment]
Ive just double checked this and you can only do the first 2 quests in this area as a rouge,The rest are missing. 
I even check as both male and female human rouge only first 2 quest are present. After u hand in https://www.wowhead.com/quest=28759/lions-for-lambs there's no more quests in the area

**Comment by Rushor** [comment]
okay

**Comment by sarahkay88** [comment]
Several reports to say this issue is back.

**Comment by sarahkay88** [comment]
full test today: quest listed in order:
1) start quest - https://www.wowhead.com/quest=28764/beating-them-back - **works**  
leads on to
2) https://www.wowhead.com/quest=28772/lions-for-lambs - **works**
player then receives 
3) https://classic.wowhead.com/quest=3102/encrypted-letter - **works**

**but at this point no further quest are available.**

**How it should go is as follows**

1) **start ques**t - https://www.wowhead.com/quest=28764/beating-them-back - **available**

**then** 

2) https://www.wowhead.com/quest=28772/lions-for-lambs -**available**

**then**

 3) https://classic.wowhead.com/quest=3102/encrypted-letter - **available**

**then**

 4)https://www.wowhead.com/quest=26915/the-deepest-cut (rough training quest) - **needs adding**

**then**

5) https://www.wowhead.com/quest=28787/join-the-battle - **needs adding**

**then**** 

6) -https://www.wowhead.com/quest=28795/they-sent-assassins 
7) https://www.wowhead.com/quest=28811/fear-no-evil  
    **( both 6 & 7 should be available together)**

**then**

8) https://www.wowhead.com/quest=28821/the-rear-is-clear

**then**

9) https://www.wowhead.com/quest=26389/blackrock-invasion
10) https://www.wowhead.com/quest=26391/extinguishing-hope
**( both 9 & 10 should be available together)**

**then**

11) https://www.wowhead.com/quest=26390/ending-the-invasion

**then**

12) https://classic.wowhead.com/quest=54/report-to-goldshire

**on your way to handing in this quest player should also be able to pick up** 

13) https://classic.wowhead.com/quest=2158/rest-and-relaxation

**at this point player leaves the starting area and quest in gold shire.**




-

**Comment by Kitzunu** [comment]
fixed
