### ISSUE TITLE
[Quest/Pala] The Power of Light - ID 24528 - Anvilmar 

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#842]
**Links:**
Quest - https://www.wowhead.com/quest=24528/the-power-of-the-light
Npc - https://www.wowhead.com/npc=926 
from WoWHead or our Armory

**What is happening:**
Able to learn both Judgment and Seal Spells but not counting Judgement as learnt or as being used on training dummy which prevents completion of quest. 

**What should happen:**
The Judgement and seal spells need to be learnt to cast judgement on training dummy outside Anvilmar to complete the quest .

**Comment by bagi84** [comment]
Similar issue to #669

**Comment by Echinaceax** [comment]
can we get this fixed please :)
