### ISSUE TITLE
[spell/warrior] charge ID-100- (AoE pull) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#843]
**Links:**
Spell - http://www.wow-mania.com/armory/?spell=100

![wretched ghoul](https://user-images.githubusercontent.com/39439201/54073890-a0ac1e80-428c-11e9-8f45-fa26d922c733.jpg)

**What is happening:**
- "charge" Is behaving as AoE
- Wretched ghoul is my target after using "charge"
but the Rattlecage Skeleton is attacking me too 

**What should happen:**
- Its meant to be single target only

**Comment by Rushor** [comment]
please assign spell class mechanics to @Keader  :)
