### ISSUE TITLE
[NPC] Priest Spell Trainers - Alliance - Multipul Startzones

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#844]
**Links:**
Npc
- https://www.wowhead.com/npc=837/branstock-khalder (Anvilmar)
- https://www.wowhead.com/npc=375/priestess-anetta {Northshire Abbey)
- https://www.wowhead.com/npc=16502/zalduun (Crash site)
from WoWHead or our Armory

**What is happening:**
These NPC Class Trainers Should Only show Spells up to level 5 but they are showing all spells up to level 85.

**What should happen:**
the spells available from these NPC should only be the spells up to level 5 to encourage players to explore next area

**Comment by Rushor** [comment]
https://wow.gamepedia.com/Priest_trainers

**Comment by Rushor** [comment]
fixed fo all startzone creatures

(837, 38245, 15284, 16502, 42323, 375, 3595, 35870, 36632, 38795, 44468, 15284, 34692, 35805, 36523, 38516, 37724, 2123);
