### ISSUE TITLE
[Spell/Pala] Crusader Strike (AoE)  ID-35395-

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#845]
_Issue 1_ 
**Links:**
http://www.wow-mania.com/armory/?spell=35395

![crusader strike](https://user-images.githubusercontent.com/39439201/54074967-77de5600-4299-11e9-9ad8-0ed85df0e457.jpg)

**What is happening:**

- When i used Crusader strike on one mob, the other neutral mob was also pulled.

**What should happen:**

- Single target spell shouldnt pull other neutral mobs

**Comment by Echinaceax** [comment]
_Issue 2_

- can you check the values of these 

_from wow mania armory 75%_ 

![75](https://user-images.githubusercontent.com/39439201/54075017-08b53180-429a-11e9-91cc-84f2d5f1767d.jpg)

_From game 135%_

![135](https://user-images.githubusercontent.com/39439201/54075025-2387a600-429a-11e9-9d6d-e2f2e985aa23.jpg)

**Comment by Kitzunu** [comment]
WoW-Mania armory is has WotLK Values.
Check changelogs on WoWHead

**Comment by Rushor** [comment]
please assign spell class mechanics to @Keader  :)
