### ISSUE TITLE
[NPC] Darnell - (given for wrong quest) - Deathknell

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#847]
**Links:**
Quest - https://www.wowhead.com/quest=28608/the-shadow-grave

![darnell](https://user-images.githubusercontent.com/39439201/54076870-a4ea3300-42b0-11e9-8bbd-c4638a5b020c.jpg)

**What is happening:**
- Iam given Darnell too early 
- Hes not needed until the 6th quest 

**What should happen:**
Quest - https://www.wowhead.com/quest=26800/recruitment

![darnell quest](https://user-images.githubusercontent.com/39439201/54076950-d1527f00-42b1-11e9-9491-7376c2ba7e8d.jpg)

- Darnell is meant to be for this quest

**Comment by Rushor** [comment]
well that's fine. on retail he was also there: https://www.youtube.com/watch?v=IMY0gmyLj_c
