### ISSUE TITLE
[Quest] Off to the Bank -26711- Kezan

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#848]
**Links:**
https://www.wowhead.com/quest=26711/off-to-the-bank

**What is happening:**

- Duplicate quest given

**What should happen:**

- Should only get it once

**Comment by Rushor** [comment]
who is giving the quest twice?

**Comment by Echinaceax** [comment]
> who is giving the quest twice?

https://www.wowhead.com/npc=35054/chip-endale

**Comment by Echinaceax** [comment]
![chip and candy2](https://user-images.githubusercontent.com/39439201/56429245-84a39000-62c2-11e9-9d67-a0b6773b6485.jpg)

![chip and candy](https://user-images.githubusercontent.com/39439201/56429224-748bb080-62c2-11e9-8067-5d9c099d6b44.jpg)
