### ISSUE TITLE
[Spell] Flamestrike stacking

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#85]
ID 2120

Same issue we recently had over at WOTLK mania.
Casting multiple flamestrikes on the same location results in the ground-dot effect stacking multiple times, which is not intended.
Unlike on wotlk, where the spell has different ranks and only the same rank cannot stack with itself, cataclysm flamestrike has no ranks at all and only one version, which isn't meant to stack with itself.

**Comment by Echinaceax** [comment]
@wow-mania @Keader 
Player reported the server crash says this looks like the issue hes having

**Comment by Echinaceax** [comment]
new info given wasnt this afterall (reclosed it)
