### ISSUE TITLE
[NPC] Candy 35053/ Chip 39363 - Kazan

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#850]
**Links:**
Candy cane - https://www.wowhead.com/npc=39426/candy-cane

https://www.wowhead.com/npc=35053/candy-cane
_Candy_

![candy](https://user-images.githubusercontent.com/39439201/54078105-d9ff8100-42c2-11e9-9b0b-fdabff0d980b.jpg)

_Chip_

![chip](https://user-images.githubusercontent.com/39439201/54078108-e388e900-42c2-11e9-94c2-736b0009b8d2.jpg)

**What is happening:**
- are each giving same quests

**What should happen:**

- Should only be one set of quest 

cant find Chip Endale in the map area but hes there 

https://www.wowhead.com/kezan

**Comment by wow-mania** [comment]
As-is for now.

**Comment by Kitzunu** [comment]
Fixed with https://github.com/WoWManiaUK/Blackwing-Lair/issues/1523
