### ISSUE TITLE
[Quest] The new you -14109- (Goblin/Hunter) - Kazan

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#851]
**Links:**
https://www.wowhead.com/quest=14109/the-new-you
https://www.wowhead.com/npc=35128/szabo

**What is happening:**
- Szabo says i havent the macaroons as payment 

![i do](https://user-images.githubusercontent.com/39439201/54078486-0f0ed200-42c9-11e9-93ec-31b6e4c36826.jpg)

**What should happen:**
- he should sell me "Hip New Outfit"

**Comment by Rushor** [comment]
need to be rescripted with gossips

**Comment by Echinaceax** [comment]
full re test in now in progress so follow #2119
