### ISSUE TITLE
[NPC] Dire Wolf

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Blackwing-Lair#852]
**Links:**
https://www.wowhead.com/npc=43704/dire-wolf
https://www.wowhead.com/item=60989/wolf-skirt-steak

**What is happening:**
The Dire Wolf is dropping Quest Item without having a quest

**What should happen:**
Quest items should only drop when you are on the quest

**Comment by Saintres** [comment]
And stop droping them when u got enough
