### ISSUE TITLE
[quest=26818] [Plush Pelts] - The Cape of Stranglethorn

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#853]
**Links:**
[quest=26818]
https://www.wowhead.com/quest=26818/plush-pelts
from WoWHead or our Armory

**What is happening:**
The quest works but the item you need from the tigers is hard to get since
there is only 1 tiger in the whole area.
The area is the whole costline behind Gurubashi Arena
The Panters are fine.

**What should happen:**
There should be more tiger's to kill for the item [item=58812]

**Comment by Kadajj** [comment]
The lone Tigress 

![WoWScrnShot_041220_151036](https://user-images.githubusercontent.com/38867875/79070792-ddd4b280-7ccf-11ea-9ef4-cf605eeea663.jpg)
![WoWScrnShot_041220_151043](https://user-images.githubusercontent.com/38867875/79070796-df9e7600-7ccf-11ea-90e1-0895da5576e5.jpg)

**Comment by mfranca0009** [comment]
**Solution**

.npc add 772 (Stranglethorn Tigress)

Adjust data within creature table after adding new instances of 772

I tested this within local CATA server and the Stranglethorn Tigress / Elder Shadowmaw Panthers should have a spawndist set and MovementType of 1 so they are patrolling near their spawn point.

**Comment by mfranca0009** [comment]
Needs testing on PTR

**Comment by Echinaceax** [comment]
confirmed fixed 

1. more tigers and panthers seen
 2. Petrol movement also fixed

![fixed3](https://user-images.githubusercontent.com/39439201/85942485-d4033880-b929-11ea-878e-6dbe12e55bd5.jpg)
