### ISSUE TITLE
[Quest] Rolling with my Homies - 14071- Kezan

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#854]
**Links:**
quest - https://www.wowhead.com/quest=14071/rolling-with-my-homies
video - https://www.wowhead.com/quest=14071/rolling-with-my-homies
Item keys - https://www.wowhead.com/item=46856/keys-to-the-hot-rod

_**Drive the Hot Rod around and pickup your friends: Ace, Gobber, and Izzy.**_

**What is happening:**

- Cant click on the people 
- Car horn not working 
- Radio not working 

**What should happen:**
- I am supposed to click on the people to pick them up in my car 
- car horn not working 

- not sure about the radio :)

**Comment by Dranah** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/152 this quest was already reported , so it looks like a regress. Reopening old thread.
