### ISSUE TITLE
[Quest/Warrior] The Basics: Hitting Things -24639- Durotar

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#856]
**Links:**
quest - https://www.wowhead.com/quest=24639/the-basics-hitting-things
npc - https://www.wowhead.com/npc=38037/nortet

**What is happening:**
- Nortet hasnt got quest complete (?) -
- So had to open the window to see it was quest back to him 

**What should happen:**
- He should have a quest complete (?) above his head :)

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/59153984-111f3300-8a68-11e9-9e4f-0fc37cab821b.png)
