### ISSUE TITLE
[Quest] A rough start issue (2) -24641- Durotar

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#858]
**Links:**
https://www.wowhead.com/quest=24641/a-rough-start

![boar and cat](https://user-images.githubusercontent.com/39439201/54086340-ee865c80-4348-11e9-8751-530ede5a6ff4.jpg)

cat - https://www.wowhead.com/npc=38046/wildmane-cat
Boar - https://www.wowhead.com/npc=38141/docile-island-boar

**What is happening:**
- The are a few groups of boars and the cats are on top of each other 

**What should happen:**
They need spacing

**Comment by mfranca0009** [comment]
All set 👍 now moving around as they should be.

**Comment by golosomie** [comment]
Confirmed fixed in PTR. All boars and cats seem to be reasonably spaced.
