### ISSUE TITLE
[Tauren/Pala] [The Way of the Sunwalkers] -27023- Camp Narache

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#863]
**Links:**
https://www.wowhead.com/quest=27023/the-way-of-the-sunwalkers

**What is happening:**
Pallyquest  [The Way of the Sunwalkers] bugged.
When im using Jugement it doesnt count to the quest

**What should happen:**
When i use the Jugementspell it should count to 1/1 to complete the quest

**Comment by mfranca0009** [comment]
All set 👍 

Should now give credit on learning Judgement, give credit on attacking a target dummy with judgement, and if you already know Judgement, it will give credit for this objective on quest accept.

**Comment by golosomie** [comment]
Confirmed fixed in PTR. Credit is given both for learning Judgement and using it on Training Dummy.
