### ISSUE TITLE
[Quest] Warrior training - ID 9289 - MISSING - Dreanie start zone

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#864]
**Links:**
Quest - https://www.wowhead.com/quest=9289/warrior-training
NPC - https://www.wowhead.com/?npc=16477
from WoWHead or our Armory

**What is happening:** 
Not being supplied with warrior class quest after completing https://www.wowhead.com/?quest=9280 which is the second in the area

**What should happen:**
After completing quest: https://www.wowhead.com/?quest=9280 I should be supplied with the warrior quest above, Were I learn the spell: https://www.wowhead.com/spell=100/chargehttps://www.wowhead.com/spell=100/charge.

**Comment by Rushor** [comment]
the quest was removed with cata https://www.wowhead.com/quest=9289/warrior-training

you can just learn the spell at the trainer https://i.imgur.com/cYNg2dQ.jpg
