### ISSUE TITLE
[Spell] Revealing Strike

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Blackwing-Lair#865]
**Links:**
https://wow.gamepedia.com/Revealing_Strike
ID `84617` [Talent]

**What is happening:**
When you use this ability it does not apply the debuf to the target that is "increasing the effect of your offensive finishing moves on that target by 35%"

**What should happen:**
When you use the ability this Debuff should be applied to the target
![image](https://user-images.githubusercontent.com/24550914/54089169-7169e000-4366-11e9-911b-ec4532d49c74.png)

ID for debuff is unknown

**Comment by Keader** [comment]
Fixed.
