### ISSUE TITLE
[Quest] Hunter training - ID 9288 - missing -Draenie start area

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#866]
**Links:**
https://www.wowhead.com/quest=9288/hunter-training

from WoWHead or our Armory

**What is happening:**
Not being supplied with hunter class quest after completing https://www.wowhead.com/?quest=9280 which is the second quest in the area

**What should happen:**
After completing quest: https://www.wowhead.com/?quest=9280 I should be supplied with the hunter quest above, to learn the spell - https://www.wowhead.com/spell=56641/steady-shot

**Comment by sarahkay88** [comment]
not 100% sure if they actually have class test.

**Comment by sarahkay88** [comment]
found this
https://www.cataclysmwowguides.com/alliance-leveling-guides/draenei-leveling-guide-level-1-12/
read number 2

**Comment by Rushor** [comment]
you can just learn the spell at the trainer. i think the quest was removed with cata as can be seen in the comments https://www.wowhead.com/quest=9288/hunter-training#comments

**Comment by sarahkay88** [comment]
Maybe I miss worded what I was quest, in cata quest to orasxtice skills came in to an effect. This is the eqiesy to learn you skill and then practice it on.The target
