### ISSUE TITLE
[quest=765] [Supervisor Fizsprocket] - Mulgore

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#868]
**Links:**
[quest=765]
https://www.wowhead.com/quest=765/supervisor-fizsprocket#comments
from WoWHead or our Armory

**What is happening:**
This quest i got at lvl 9, but the npc spawn lvl 19 elite snake.
Its also a double spawn
So impossible to do at lvl 9
ALSO this quest you get two times from same npc
[quest=765]
[quest=26180]

**What should happen:**
Should probably not spawn a lvl 19 elite snake

**Comment by Rushor** [comment]
snake removed, double quest removed. with next update
