### ISSUE TITLE
[Quest] Dreanei Startzone Quest Order Broken

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#869]
**Links:**
Quests: https://www.wowhead.com/quest=9279/you-survived = NPC - https://www.wowhead.com/npc=16475
QUEST - https://www.wowhead.com/quest=10302/volatile-mutations & https://www.wowhead.com/quest=10304/vindicator-aldar -NPC -https://www.wowhead.com/npc=16514

from WoWHead or our Armory

**What is happening:**
Starting quest for the zone is you survived **https://www.wowhead.com/quest=9279/you-survived** but also available is **https://www.wowhead.com/quest=10302/volatile-mutations** and **https://www.wowhead.com/quest=10304/vindicator-aldar**. Without having to hand in the opening quest.

**What should happen:**
you should have to hand in **https://www.wowhead.com/quest=9279/you-survived** which then gives you the quest  **https://www.wowhead.com/quest=9280/replenishing-the-healing-crystals.** Once this quest is complete the two above quest should be come available.

**Comment by bagi84** [comment]
Also having same quest order issue whilst checking dreanei startzone
