### ISSUE TITLE
[Spell] Pyromaniac

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#87]
ID 34295

Talent does not work, does not grant the 10% haste buff when the criteria is fulfilled.

It should grant a Pyromaniac buff when 3 or more targets have fire dots affecting them, which increases your spell haste by 10%.
(Tested with Living bomb)

**Comment by sarahkay88** [comment]
Still isn't granting the 10% haste buff

**Comment by Keader** [comment]
Fixed.

**Comment by Dranah** [comment]
Well it procs now but only when all 3 targets have taken at least 1 tick of damage from yer dot (testing with Living bomb)
It should be always active when you have 3 targets with fire dots, not only in a short time window when all 3 dots have ticked.
The spell seems to only realize the presence of each DoT when it has ticked. This greatly reduces the uptime of the effect.

**Comment by Keader** [comment]
Well, rewrited script for match your new conditions.
Test now.

**Comment by Dranah** [comment]
Doesn't work... at all. Can't proc it.

**Comment by Keader** [comment]
Fixed.
I forgot to send 1 part of fix lol
