### ISSUE TITLE
[Quest] Aiding the injured - 24287 -Azuremyst Isle

### ISSUE THREAD

**Issue by ghost** [WoWManiaUK/Blackwing-Lair#871]
**Links:**
Unable to find quest id on wowhead 
related link: http://wow.mmorpg-life.com/24287/quest/aiding-the-injured/
NPC : https://www.wowhead.com/npc=16502/zalduun
from WoWHead or our Armory

**What is happening:**

I receive the quest and learn the spell but cant not heal the injured as they are full health and it doesn't acknowledge my heal

![World of Warcraft 10_03_2019 19_39_47](https://user-images.githubusercontent.com/42302580/54090538-1982a780-436d-11e9-9e2a-abef1cf2a4d8.png)

**What should happen:**
They shouldn't have full health, I should use my heal 5 times and this should complete the quest.

**Comment by Rushor** [comment]
quest=9283

**Comment by Rushor** [comment]
ehh sorry 26970

**Comment by sarahkay88** [comment]
that's learning the word: https://www.wowhead.com/quest=26970/learning-the-word isn't it?

**Comment by Rushor** [comment]
todo remove immune flags

**Comment by mfranca0009** [comment]
All set 👍

**Comment by golosomie** [comment]
Confirmed fixed on PTR. Injured Draenei reset to low health after ~1 minute.
