### ISSUE TITLE
[Quest] The Art of the priest - ID 26200 - Gnomergan

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#874]
**Links:**
Quest - https://www.wowhead.com/quest=26200/the-arts-of-a-priest 
NPC - https://www.wowhead.com/npc=42323 - Doc Cogspin
Taregt NPC- https://www.wowhead.com/npc=42501/wounded-infantry
Video - http://youtu.be/gqeXiI6ayW8
from WoWHead or our Armory

**What is happening:**
The NPC gives you a Quest to Flash heal the target NPC 5 times but the quest doesn't count the spell as working on the target NPC so unable to complete quest .

**What should happen:**
Use Flash heal 5 times on Target NPC to complete Quest .

** On a side note the quest id given in wowhead gives wrong quest details but if you read comments the do tie in with flash heal version of quest **

**Comment by Splittaz** [comment]
still broken

**Comment by Kitzunu** [comment]
fixed
![image](https://user-images.githubusercontent.com/24550914/64471940-98f40680-d157-11e9-8928-4f98382a9a7d.png)
