### ISSUE TITLE
[Quest] The Cipher of Damnation - Ar'tor's Charge / Illidari Point, Shadowmoon Valley - #10540

### ISSUE THREAD

**Issue by Revner17** [WoWManiaUK/Blackwing-Lair#875]
**Links:**

https://www.wowhead.com/quest=10540/the-cipher-of-damnation-artors-charge

https://www.wowhead.com/npc=20427/veneratus-the-many

**What is happening:**

After searching South of Illidari Point, Veneratus the Many does not spawn with the Spirit Hunter next to you. 

**What should happen:**

https://www.youtube.com/watch?v=FKNCSAbTRtQ

**Comment by Rushor** [comment]
![I](https://i.imgur.com/d23vDaR.jpg)

fixed
