### ISSUE TITLE
[NPC] Sanoru  21826 (Missing) - Shadowmoon Valley

### ISSUE THREAD

**Issue by Revner17** [WoWManiaUK/Blackwing-Lair#876]
**Links:**

https://www.wowhead.com/npc=21826/sanoru

https://www.wowhead.com/quest=10686/the-wardens-cage

**What is happening:**

In order to complete the quest The Warden's Cage you must travel to the Warden's Cage, South of the Ruins of Baa'ri. On entry and walking down the ramp, Sanoru is suppose to be at the bottom but he is not.

![Screenshot (10)](https://user-images.githubusercontent.com/47263920/54092126-da4d5a00-435e-11e9-86b1-292a6e30bb2f.png)

**What should happen:**

https://www.youtube.com/watch?v=rPgw4ezgxsY

**Comment by glcabatuan** [comment]
Yes, the http://cata.cavernoftime.com/npc=21826 is there but non- interactive. Can't complete the quest

**Comment by Echinaceax** [comment]
This npc is also needed for follow up questline **Proof of Allegiance**
http://cata.cavernoftime.com/quest=10622

**Comment by Echinaceax** [comment]
not fixed again, i will re-add and resend ID @Rushor

**Comment by mfranca0009** [comment]
Needs testing in PTR 👍

**Comment by Echinaceax** [comment]
fixed confirmed @mfranca0009 

![fixed6](https://user-images.githubusercontent.com/39439201/85959050-3267ff80-b99a-11ea-8f5a-85b89d9f6fc2.jpg)
