### ISSUE TITLE
[Spell/Rogue] Sinister Strike - (AoE ) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#877]
**Links:**

https://www.wowhead.com/spell=1752/sinister-strike

![shouldnt do this](https://user-images.githubusercontent.com/39439201/54092399-d08e1b80-438b-11e9-9aa5-e53c912b5f9b.jpg)

**What is happening:**
- Its acting as AoE 
- It Aggros Neutral mobs that are next to my target mob

**What should happen:**
- Single target only

**Comment by Kitzunu** [comment]
This does not make sense though.
It would only have aggroed those mobs if the ability attacked the mob.

Are you sure it isnt the npc that is fucked aggro?

**Comment by Echinaceax** [comment]
same thought as i had too.
tested also on other mobs in the area and its the same 

(also hunter - rogue - and ofc warrior)

**Comment by Kitzunu** [comment]
Might be the Netrual flag that is fucked too.

**Comment by Echinaceax** [comment]
https://www.wowhead.com/npc=3098/mottled-boar
https://www.wowhead.com/npc=3101/vile-familiar

atm im on my rogue test and its doing the same
