### ISSUE TITLE
[Quest] The Cipher of Damnation / The Altar of Damnation, Shadowmoon Valley - #10588

### ISSUE THREAD

**Issue by Revner17** [WoWManiaUK/Blackwing-Lair#880]
**Links:**

https://www.wowhead.com/quest=10588/the-cipher-of-damnation

**What is happening:**

When you activate the Cipher of Damnation and it completes its actions, the surrounding NPC's have dialogue and then Cyrukh the Firelord spawns in front of the alter along with Oeonok Torn-Heart, Borak Son of Oronok, Grom'tor Son of Oronok in the back. Issue is that all dialogue is duplicated and when the four NPC's spawn they spawn in duplicate over lapping each other. 

![Screenshot (11)](https://user-images.githubusercontent.com/47263920/54093199-77ae8b00-436b-11e9-91fd-48f9e5cd5ddd.png)

![Screenshot (12)](https://user-images.githubusercontent.com/47263920/54093201-7a10e500-436b-11e9-9337-3c9b2e9c4430.png)

![Screenshot (13)](https://user-images.githubusercontent.com/47263920/54093202-7bdaa880-436b-11e9-95ab-ca3c666258cf.png)

![Screenshot (14)](https://user-images.githubusercontent.com/47263920/54093204-7da46c00-436b-11e9-97eb-3c1d8c32a0e6.png)

**What should happen:**

 -Only single dialectic and one npc of each should spawn

https://www.youtube.com/watch?v=dn9Yuy00hZg

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/lZ7tEBt.jpg)
