### ISSUE TITLE
[Quest/Rogue] Eviscerate - 25141- Valley of Trials

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#881]
**Links:**
quest - https://www.wowhead.com/quest=25141/eviscerate
Npc - https://www.wowhead.com/npc=3155/rwag

**What is happening:**
- Trainer couldnt teach me 
- No training dialog 

![eviscerate](https://user-images.githubusercontent.com/39439201/54093500-c0c90400-4398-11e9-9f35-b24f902929f9.jpg)
![rogue training](https://user-images.githubusercontent.com/39439201/54093501-c32b5e00-4398-11e9-9e38-99bfb6573ca6.jpg)

**What should happen:**
-Should be a training ability dialog

**Comment by Rushor** [comment]
going to fix all trainers now
