### ISSUE TITLE
[quest=26984] [An Old, Crazed Friend] - Northern Stranglethorn / Scarlet Monastery

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#884]
**Links:**
[quest=26984]
https://www.wowhead.com/quest=26984/an-old-crazed-friend
from WoWHead or our Armory

**What is happening:**
[npc=44741] Joseph the Crazed is not in Scarlet Monastery as he should
Missing npc

**What should happen:**
Joseph the Crazed should be in the Armory

**Comment by mfranca0009** [comment]
Needs testing on PTR

**Comment by Echinaceax** [comment]
Confirmed fixed @mfranca0009  :)

![Joseph the Crazed fixed](https://user-images.githubusercontent.com/39439201/85941860-d19edf80-b925-11ea-99b0-da44afc2fee3.jpg)

**Comment by Echinaceax** [comment]
oops missclicked
