### ISSUE TITLE
[Talent/Mage] Improved Cone Of Cold - 12489 - 

### ISSUE THREAD

**Issue by yuwers** [WoWManiaUK/Blackwing-Lair#885]
the talent for Improved Cone of Cold on a Troll Frost/Fire mage has never proc'd for me even once, no matter how many targets or their distance. it does slow them but does not Freeze.

**Comment by wow-mania** [comment]
Please check wiki on how to login issues. Follow template.

**Comment by Echinaceax** [comment]
_Confirmed_

_On target_ 
![cone of colds1](https://user-images.githubusercontent.com/39439201/54120425-f0f3bf80-43f7-11e9-8a98-a500363f1014.jpg)

Procs others not Cone of cold
![pros others](https://user-images.githubusercontent.com/39439201/54120452-07018000-43f8-11e9-89d8-616ee5754d87.jpg)

Improved cone of cold talent
![talents](https://user-images.githubusercontent.com/39439201/54120501-24364e80-43f8-11e9-8240-9b5588f15a98.jpg)

links on the way when i find them :)

**Comment by Echinaceax** [comment]
**Links**
https://cata-twinhead.twinstar.cz/?spell=12489

_Confirmed_ 

_On target_

![cone of colds1](https://user-images.githubusercontent.com/39439201/54122152-8f821f80-43fc-11e9-8746-b405df1b7a43.jpg)

_Talent tree_ 

![talents](https://user-images.githubusercontent.com/39439201/54122186-a58fe000-43fc-11e9-8a00-dfa45c75928a.jpg)

**What is happening:**
- Cone of cold is not freezing the target


**What should happen:**
- Cone of cold (with the improved cone of cold 2/2) is meant to freeze the target for 4secs

**Comment by Kitzunu** [comment]
There is no reason linking to the WoW-Mania armory.
As I explained earlier, WoW-Mania Armory only has information for WotLK not for Cataclysm

**Comment by Echinaceax** [comment]
ofc i know 
i link below the reason i did that :)

> i would go with - https://cata-twinhead.twinstar.cz/?spell=12489
> As it states Cata - and wow-mania armory is wotlk atm :)

**Comment by Keader** [comment]
Fixed.
