### ISSUE TITLE
[Spell] dalaran brilliance -61316-

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#886]
**Links:**
http://www.wow-mania.com/armory/?item=44714
http://www.wow-mania.com/armory/?spell=61316

**What is happening:**
- When clicking on the spell dalaran brilliance, its Throwing me up in the air and i spin around :)

![cast buff](https://user-images.githubusercontent.com/39439201/54135248-be5abe80-4419-11e9-8cff-3f37cbd2046a.jpg)
![dalaran brilliance weee](https://user-images.githubusercontent.com/39439201/54135338-e518f500-4419-11e9-8d06-a3b1768d1a1f.jpg)

**What should happen:**
- The spell (once learnt from the book "Tome of Dalaran Brilliance") 
is suppose to give me and the group a buff (ofc only tested on myself) in PTR

- No buff from dalaran brilliance given
http://www.wow-mania.com/armory/?spell=61316

![dala buff](https://user-images.githubusercontent.com/39439201/54135348-ea763f80-4419-11e9-9141-53e1fe9337f3.jpg)

**Comment by Keader** [comment]
HAHAhahhaha
Fun bug btw.
Fixed.

**Comment by Echinaceax** [comment]
yeah i was giggling when i was making the report haha 
thanks @Keader

**Comment by Echinaceax** [comment]
yip, fixed in dev lol 

![dala buff fixed](https://user-images.githubusercontent.com/39439201/54208527-65a02a00-44dc-11e9-98e6-a666c681579b.jpg)
