### ISSUE TITLE
[NPC] Endora Moorehead <Magical Goods>-28715 - Dalaran

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#887]
**Links:**
http://www.wow-mania.com/armory/?npc=28715

_page 1_ 

![cata mage page1](https://user-images.githubusercontent.com/39439201/54136550-522d8a00-441c-11e9-8eb4-5d5c25da9b1b.jpg)

_page 2_

![cata mage page2](https://user-images.githubusercontent.com/39439201/54136584-607ba600-441c-11e9-8afc-05a7d535d95b.jpg)

**What is happening:**
- Double "dalaran brilliance tomb" 
- Missing "Tome of Dalaran Intellect"

**What should happen:**
- Should be only once. 
- Should also have the "Tome of Dalaran Intellect"
-  Tome of Dalaran Intellect need to replace one of the doubles 
http://www.wow-mania.com/armory/?item=44602

See sale table
http://www.wow-mania.com/armory/?npc=28715

This SS taken from wotlk wow-mania vendor 

![wotlk mage](https://user-images.githubusercontent.com/39439201/54136957-04fde800-441d-11e9-913f-f9f181518441.jpg)

**Comment by Rushor** [comment]
the items are not even in the db - strange

**Comment by Echinaceax** [comment]
Hmmm thats odd :)

**Comment by wow-mania** [comment]
This was fixed but will require client update so it won't be visible.
