### ISSUE TITLE
[Quest] Blast the Infernals! / Shadowmoon Village, Shadowmoon Valley - #10598

### ISSUE THREAD

**Issue by Revner17** [WoWManiaUK/Blackwing-Lair#892]
**Links:**
https://www.wowhead.com/quest=10598/blast-the-infernals

**What is happening:**

Quest works and likes you complete objectives, however when you return to quest giver, Blood Guard Gulmok you are unable to turn it in.

![Screenshot (19)](https://user-images.githubusercontent.com/47263920/54170649-df3d0700-444d-11e9-9b3c-aab75eab318a.png)

![Screenshot (18)](https://user-images.githubusercontent.com/47263920/54170618-c92f4680-444d-11e9-8df7-327f6de204d9.png)

**What should happen:**

Simply let you turn it in.

**Comment by Dranah** [comment]
I don't see the problem? You can turn it in.
