### ISSUE TITLE
[Quest/NPC]  Warchief's Command: Desolace! -28548- Desolace

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#899]
**Links:**
https://www.wowhead.com/quest=28548/warchiefs-command-desolace
https://www.wowhead.com/npc=35286/furien

**What is happening:**
- NPC missing 

**What should happen:**
- NPC is meant to be at location

**Comment by Kitzunu** [comment]
Please confirm this issue.

>https://www.wowhead.com/npc=35286/furien#comments:id=1621828
I made a ticket about this quest and a GM responded to me that this quest in fact is not broken or bugged. The quest is not even a "real quest", all of the "Warchief´s commands" are so called "breadcrumbs" to guide players in the right direction. However, have u already start questing in that area (not starting with the Command quest) and most likley done quest involving something with Furien, he will no longer be there. And reason why the "?" showing on map is cus of the log saying where he supposed to be, but seeing as Furien is a npc who wanders around and moves places along the questchain, hes somewhere else really. And if this is the case for you, just abandon the quest as it wont do you any good anymore. GM also then said in the future they will probably add some code to make the quest invalid so players dont go chasing ghosts! :)

**Comment by Echinaceax** [comment]
@Kitzunu - Hmmm, Good question 
I will ask around

**Comment by Echinaceax** [comment]
@Kitzunu - from the same link further down 
https://www.wowhead.com/npc=35286/furien#comments:id=1595471

> NPC still phased out. Went hours and days checking back and he's still gone. Dropped the quest and picked it up again, working it in rapid succession, and still gone. Had guildees w/o the quest check for him all over the area and nothing. Blizz could care less about this quest chain glitch. I feel duped! Details matter little to Blizz. Please step up on the quality checks Blizz doods!

And on cata-twinhead - i do see a questline from the this "warcheifs command"
https://cata-twinhead.twinstar.cz/?quest=28548

![questline](https://user-images.githubusercontent.com/39439201/56457351-a449bf80-6379-11e9-8fa1-6c274e7dda65.jpg)

**Comment by Kitzunu** [comment]
Because it is a breadcrumb quest

**Comment by Echinaceax** [comment]
yes exactly...
i will ask around the team and update when i know more @Kitzunu

**Comment by sarahkay88** [comment]
A breadcrumb quest means you dont necessarily have to do these quest to open the area, however if you chose the option of taking this quest before starting the area the npc should be there.

**Comment by Echinaceax** [comment]
Also from my questline SS above it says "this closes" 
 https://github.com/WoWManiaUK/Blackwing-Lair/issues/1285

![closes](https://user-images.githubusercontent.com/39439201/56457554-c0029500-637c-11e9-8997-bb2a5c7a3b1f.jpg)

Ans pitmaster reported "that quest" So there is definately a missing npc problem coz if you "skip" this breadcrumb quest , the npc isnt there for "Nothing Left for You Here" too

**Comment by sarahkay88** [comment]
https://wow.gamepedia.com/Hero%27s_Call_Board#Quest_zones
From levels 10 to 55, the Hero's Call Boards in different capital cities offer different quests in an attempt to direct players along a less continent-crossing path.

**Comment by Kitzunu** [comment]
However, have u already start questing in that area (not starting with the Command quest) and most likley done quest involving something with Furien, he will no longer be there.

**Comment by Echinaceax** [comment]
@Kitzunu 

pitmaster reported "that quest" So there is definately a missing npc problem coz if you "skip" this breadcrumb quest , the npc isnt there for "Nothing Left for You Here" too

**Comment by Kitzunu** [comment]
If you dont do the Command quest he will not be there.

**Comment by Echinaceax** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/899#issuecomment-485114478

**Comment by Kitzunu** [comment]
"that quest" what is "that"?

**Comment by Echinaceax** [comment]
if you do the command board - it closes the ability to get https://cata-twinhead.twinstar.cz/?quest=26134

**Comment by Kitzunu** [comment]
ah now I get it

**Comment by sarahkay88** [comment]
can i also add that theres hero boards play a vital role in opening the new areas from level 85 onward, you cant open these areas without the hero board.

**Comment by Rushor** [comment]
can be seen now.
