### ISSUE TITLE
Imp - Mana 

### ISSUE THREAD

**Issue by Zunrin** [WoWManiaUK/Blackwing-Lair#9]
What's happening:

- When my imp is level 1 (he has 72 mana) and he casts a fireball (that costs 1 mana), he goes straight down to 0 mana, does not regen mana at all, but can continue casting the fireballs.
- As soon as I reach level 2 (my imp reaches level 2 too), he still has 72 mana, fireball still costs 1 mana, but he can't fire it anymore (even if I didn't make him cast at all during level 1 and he's therefore full mana).

**Comment by Zunrin** [comment]
The issue only seems to happen until you log out and back in.

**Comment by fvicaria** [comment]
send me the id of the NPC or the name of your char

**Comment by Zunrin** [comment]
It happens on all warlocks, until you have relogged, or dismissed your pet and resummon it. (or get it killed and resummoned)

The spell id to summon the imp is 688.

**Comment by Zunrin** [comment]
Issue is still happening

**Comment by Dranah** [comment]
I can confirm this issue however I have a very simple suggestion to avoid this problem:
Make newly made warlocks start WITHOUT the imp being already summoned. As the bug requires you to resummon to fix it, just have the new locks summon their first imp themselves, so it will not happen.

**Comment by fvicaria** [comment]
That is probably the best solution.

**Comment by Keader** [comment]
I'm working on this.

**Comment by Dranah** [comment]
UPDATE:
Imp at level 1 now does not consume any mana at all with his spells. As you level up, his mana pool remains the same as on level 1 and does not lose any mana still.
Relogging and resummoning imp fixes it back to normal.

**Comment by Dranah** [comment]
It is a visual issue fixed upon relog. Marking fixed.
