### ISSUE TITLE
[Quest/NPC] Warchief's Command: Southern Barrens! -28549- Southern Barrens

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#900]
**Links:**
https://www.wowhead.com/quest=28549/warchiefs-command-southern-barrens
https://www.wowhead.com/npc=37135/nura-pathfinder

**What is happening:**

- NPC missing "Nura Pathfinder"

**What should happen:**

- She should be at location

**Comment by Velara** [comment]
Can confirm, she is missing. Should be around 31, 13, near the torch on the road.

**Comment by gamer100** [comment]
Npc is  still missing

**Comment by Echinaceax** [comment]
@Rushor did you send fix to jani?
still not on live
