### ISSUE TITLE
[NPC] Ortezza <Hunter Trainer> - 38247-Echo Isles

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#908]
**Links:**
https://www.wowhead.com/npc=38247/ortezza

![same one](https://user-images.githubusercontent.com/39439201/54362977-43d4ad80-466a-11e9-92b7-23c5729d9258.jpg)

**What is happening:**
The hunter trainer offers me the same hunter quest that i did in my own area at lvl3 (orc)

**What should happen:**
Trainers surely know if ive already done a hunter quest despite the zone 

only found this out coz of another quest sent me to that area 

- This quest is odd, it sent me to "Echo isle" (quest was doable) But...
- This area "Echo isle" is the start area for Trolls, but im sure my hunter trainer there should know ive already done my hunter quest in my own start area (hmm) 

but he gives me the same quest as my own start area of (Orc)
https://www.wowhead.com/quest=24778/the-arts-of-a-hunter

Something is messed up here with the Quest given "Clean up on Isle E."

- Needs checking
i think it messed the quest up coz of the  "Clean up on Isle E." #905
- Hunter trainer offers me the same hunter quest from Ortezza

https://www.wowhead.com/npc=38247/ortezza.

**Comment by wow-mania** [comment]
As-is.
