### ISSUE TITLE
[Quest] The Archmage's Staff / Arklon Ruins, Netherstorm - #10173

### ISSUE THREAD

**Issue by Revner17** [WoWManiaUK/Blackwing-Lair#909]
https://www.wowhead.com/quest=10173/the-archmages-staff

https://www.wowhead.com/npc=19493/ekkorash-the-inquisitor

**What is happening:**

While standing near the glowing brazier at the center of the Arklon Ruins, you are suppose to summon Ekkorash the Inquisitor by chicking the Conjuring Powder given to you by the quest giver. When clicked no action happens and you are given a error message saying Requires Arklon Brazzier even though I am standing right next to it.

![Screenshot (24)](https://user-images.githubusercontent.com/47263920/54402234-a6956b80-46a1-11e9-9f53-d19cfc28d103.png)

**What should happen:**

https://www.youtube.com/watch?v=i1o_zTFMnK4

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/4DAt8wx.jpg)
