### ISSUE TITLE
[npc=143607]Blackrock deeps Ring of the Law - Blackrock deeps

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#910]
**Links:**
https://www.wowhead.com/npc=143607/high-justice-grimstone
[npc=143607]
from WoWHead or our Armory

**What is happening:**
When you are in ring of the law, u should fight different mob's that comes out from a locked cave x 2.

But the npc only open 1 cave and then hes gone so he dont open the second cave to fight the last mob to open the exitgate from the ring of law. So im stuck here now

**What should happen:**
[npc=143607]
This npc should open the 2nd gate to fight the mobs that comes out so the exitgate opens and you can get out from the ring of the law

**Comment by Rushor** [comment]
okay fixed

![I](https://i.imgur.com/lLRJGmh.jpg)
![I](https://i.imgur.com/pWy2Xn1.jpg)
![I](https://i.imgur.com/vr6gLKw.jpg)
