### ISSUE TITLE
[npc=12018] Majordomo Executus - Molten Core

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#911]
**Links:**
[npc=12018]
https://www.wowhead.com/npc=12018/majordomo-executus#comments
from WoWHead or our Armory

**What is happening:**
This NPC is suppose to summon Ragnaros in Molten Core.
But when i try to talk to him to summon then i can click the option in chatwindow.

**What should happen:**
Majordomo Executus should summon Ragnaros when i tell him too.

**Comment by kDracku** [comment]
It worked for me

**Comment by Rushor** [comment]
fixed that some time ago

**Comment by Rushor** [comment]
fixed that some time ago

**Comment by Echinaceax** [comment]
not working again @rushor Player ingame spoke to a GM
