### ISSUE TITLE
[NPC] Glacion -24019- ( Double spawn) - Howling Fjord 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#917]
**Links:**
https://www.wowhead.com/npc=24019/glacion

![glacion](https://user-images.githubusercontent.com/39439201/54456879-33066380-4760-11e9-9998-0ea6886161b3.jpg)

**Whats happening**

- Double spawn

**What should happen:**
- Should be one

**Comment by Rushor** [comment]
fixed with https://github.com/WoWManiaUK/Blackwing-Lair/issues/918
