### ISSUE TITLE
[Quest/priest] Staff of the Light -27439- (loot) - Shadowfang keep

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#929]
**Links:**
quest - https://www.wowhead.com/quest=27439/staff-of-the-light
Quest item - https://www.wowhead.com/item=60875/ghostly-essence

**What is happening:**
- Quest item loot continues dropping after the amount needed is completed 5/5

**What should happen:**
- Quest item should stop when quest item needed is completed 5/5

**Comment by Kitzunu** [comment]
Does it drop when you dont have the quest too?

**Comment by Echinaceax** [comment]
> Does it drop when you dont have the quest too?

i"ll check that, i only tested drops while in there
