### ISSUE TITLE
[Quest] Defending the Wilds -29571- (npc missing) - The Underbog

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#931]
**Links:**

quest - https://www.wowhead.com/quest=29571/defending-the-wilds
npc - https://www.wowhead.com/npc=54675/watcher-jhang

**What is happening:**
- NPC Watcher Jhang is missing 

**What should happen:**
- NPC Watcher Jhang should be there to deliver and pick up new quest

**Comment by Rushor** [comment]
added
