### ISSUE TITLE
[Spell] Executioner

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#932]
ID 20503 warrior fury talent

How it should work: Execute hits should grant you a 5% melee attack speed improve, stacking up to 5 times.
How it works atm: Execute hits don't give you the proc.

This has been reported and fixed back on the previous core https://github.com/WoWManiaUK/Blackwing-Lair/issues/49 but that's obviously obsolete so i opened a new thread.

**Comment by Keader** [comment]
Try now.
