### ISSUE TITLE
[Spell] Hammer of Wrath

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#933]
ID 24275
Retribution paladin ability.

**How it should work:** This ability should not be able to proc seals that require a melee attack to proc them. This includes 
Seal of justice ID 20164
Seal of righteousness ID 20154
Seal of insight ID 20165
Plain and simply, because HoW is not a melee attack.
It has 30 yard range and deals holy damage. While it looks like a spell at first, it's actually categorized as a "ranged attack that deals non physical damage" so it mostly behaves like any other physical attack but is not considered melee. Therefore must not proc seals that proc off melee attacks.
Note: Seal of truth can proc off any "attack", therefore it is fine that it can proc off Hammer of Wrath too.
**How it works atm:** HoW can proc all seals currently.

**Comment by Keader** [comment]
Try now.
