### ISSUE TITLE
[Spell] Smoke Bomb

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Blackwing-Lair#935]
https://wow.gamepedia.com/Smoke_Bomb
ID: 76577

**Current Behaviour:**
Only places a cloud, with no effects

**Expected Behaviour:**
When you are in the cloud it should give LoS to any Caster outside.
That means that for example a mage should not be able to hit the enemy inside of the Smoke Bomb
OR
The enemy should not be able to heal his ally that is in the other factions smokebomb

This Debuff does not apply when you are in the area
![image](https://user-images.githubusercontent.com/24550914/54480651-2569e000-482b-11e9-9e4a-fc2f84f019cc.png)

**Comment by Dranah** [comment]
Looks good.
