### ISSUE TITLE
[Spell] Word of Glory

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#936]
ID 85673

**How it should work:**
Consumes all holy power to heal a target for X per charge of holy power.
Healing should scale up with more charges of holy power.
**How it works atm:**
Heals for same 1 charge amount regardless of how much holy power you have. Still consumes all HP it finds though.

**Comment by Keader** [comment]
Fixed.

**Comment by Dranah** [comment]
The healing now scales with Holy Power, but incorrect.
My tooltip says it heals ~2,1k per charge of HP.
I get 4,2k healing at 1 HP, 6,5k at 2 HP and 8k+ at 3 HP.
It feels like the starter counts at 0, so each state heals 1 HP more than intended.
How it should work:
1 HP should heal for 1 charge, 2 for 2 and 3 for 3.
How it really works:
1 HP heals as if you had 2, 2 HP heals as if you had 3, 3 HP heals as if you had 4.

Note, my paladin is naked and has only 90 SP, it can account for a maximum of 100~ healing error.

**Comment by Keader** [comment]
Test now please.

**Comment by Dranah** [comment]
Looks good.
