### ISSUE TITLE
[quest=26600] [A Giant's Feast] - The Cape of Stranglethorn

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#938]
**Links:**
[quest=26600]
https://www.wowhead.com/quest=26600/a-giants-feast
from WoWHead or our Armory

**What is happening:**
The two npc's that are suppose to sell these items for the quest dont offer any item to sell,
atleast not the questitems

**What should happen:**
The npc's should sell the required items to complete the quest

**Comment by Dranah** [comment]
ID for npcs
https://www.wowhead.com/npc=2664/kelsey-yance
https://www.wowhead.com/npc=2491/whiskey-slim

**Comment by Echinaceax** [comment]
@Kitzunu 
- [ ] kelsey-yance (fixed)
- [ ] whiskey-slim (not found)

![cant see](https://user-images.githubusercontent.com/39439201/56232089-3e5eee80-6080-11e9-890f-637e356e243c.jpg)
