### ISSUE TITLE
[Quest] Playing With Felfire -13730-  (visual bug) - Ashenvale

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#939]
**links**
https://www.wowhead.com/quest=13730/playing-with-felfire
https://www.wowhead.com/item=45478/reinforced-canister

_Draaka in Splintertree wants you to fill the Reinforced Canister with 7 Felfires from Felfire Hill._

**Whats happening** 
- Visual bug when siphoning reinforced-canister.

**What should happen**
https://www.wowhead.com/quest=13730/playing-with-felfire#videos:id=49290

**Comment by Xman993** [comment]
u can use [Reinforced Canister](https://www.wowhead.com/item=45478/reinforced-canister) wherever you want. It does not have to be fire. I finished it in the base by just spamming the item

**Comment by mfranca0009** [comment]
All set, imp triggers are not showing to player (they're now set as triggers and not visible), the item spell now requires the trigger NPC to be near the player casting the spell, and the quest credit spell that is triggered by the item spell now gives credit to the caster but also party members within the same area if on the quest as well.

Lastly, the trigger NPC is despawned a second after the channeled item spell has completed to prevent spamming for quest credit.

**Comment by Echinaceax** [comment]
Fix confirmed in ptr 👍
