### ISSUE TITLE
[NPC] King Genn Greymane

### ISSUE THREAD

**Issue by Kadajj** [WoWManiaUK/Blackwing-Lair#94]
Hi Team,

Gilneas, Worgen starting zone it's almost impossible to level as there are too many Bloodfang Ripper spawned and killing quest givers.
![wowscrnshot_051218_102930](https://user-images.githubusercontent.com/38867875/39955988-ea7a9f6e-55cf-11e8-9e82-31a80c182a10.jpg)
![wowscrnshot_051218_103030](https://user-images.githubusercontent.com/38867875/39955989-eadc20ae-55cf-11e8-8288-db4430905307.jpg)

**Comment by Dranah** [comment]
Which stage of the quest chain is this?
