### ISSUE TITLE
[NPC] Chin'toka <Innkeeper>-43633- Ashenvale

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#949]
**Links:**

https://www.wowhead.com/npc=43633/innkeeper-chintoka

**What is happening:**
- Dont have sales window

**What should happen:**
- Should be vendor too

**Comment by Kitzunu** [comment]
Now does not have the option to set heartstone

**Comment by Echinaceax** [comment]
Not sent to PTR
