### ISSUE TITLE
[Orc/Warlock] Pet has no actionbar

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#950]
**Links:**

from WoWHead or our Armory

**What is happening:**
Orc Warlock
The pet, voidwalker and imp both doesn't have a actionbar.

**What should happen:**
At least at lvl 10 they should get an actionbar on there own.

**Comment by Echinaceax** [comment]
He realized he needed the train control demon at lv10 first 
https://www.wowhead.com/spell=93375/control-demon

problem solved
