### ISSUE TITLE
[Quest] They Set Them Up The Bomb! - 13981- Ashenvale

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#952]
**Links**
quest - https://www.wowhead.com/quest=13981/they-set-them-up-the-bomb
quest giver - https://www.wowhead.com/object=195134/the-bomb
quest back - https://www.wowhead.com/npc=34354/huntress-jalin

![ally base](https://user-images.githubusercontent.com/39439201/54500047-fdf14100-4918-11e9-9f30-e4fb40778113.jpg)

**Whats happening**
- Horde could pick this Ally quest up 

**What should happen**
- Shouldnt be able to pick up Ally quest

**Comment by Rushor** [comment]
object is now only usable (with gm off) as alliance player

**Comment by Kitzunu** [comment]
Same issue, no change

**Comment by Dranah** [comment]
Still broken #2170
