### ISSUE TITLE
[NPC] Billibub Cogspinner - Stormwind City

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Blackwing-Lair#959]
No vendor + repair window
https://www.wowhead.com/npc=5519/billibub-cogspinner

**Comment by Kitzunu** [comment]
This has not been added to PTR...

**Comment by Echinaceax** [comment]
@Kitzunu - main issue fixed

new issue visual issue 

![eng](https://user-images.githubusercontent.com/39439201/56083465-ab2a7c80-5e25-11e9-8622-44cb53c27745.jpg)

**Comment by Kitzunu** [comment]
You need the correct Engineering level to buy them

**Comment by Echinaceax** [comment]
> You need the correct Engineering level to buy them

icons missing ;)

**Comment by Kitzunu** [comment]
That is the icon
