### ISSUE TITLE
[Blood Elf Models] Blood Elf Hair

### ISSUE THREAD

**Issue by jsfriendGaming** [WoWManiaUK/Blackwing-Lair#96]
There is only 4 hair styles to choose from and the rest are bald,  and as I run around the Starting Area all I see is this for hair.
![image](https://user-images.githubusercontent.com/38737813/39957318-ad69e666-55b6-11e8-9776-8c1e3cc02f94.png)

**Comment by jsfriendGaming** [comment]
More Pictures
![image](https://user-images.githubusercontent.com/38737813/39957354-2a321cea-55b7-11e8-92d9-8dd728f34398.png)
![image](https://user-images.githubusercontent.com/38737813/39957358-34a91f8e-55b7-11e8-89ef-cb17f5dc05de.png)
But the Guards Are fine

**Comment by Echinaceax** [comment]
https://github.com/wow-mania

**Comment by Echinaceax** [comment]
https://github.com/WoWManiaUK/Blackwing-Lair/issues/835#issuecomment-471270233
