### ISSUE TITLE
[Quest] Echeyakee -881- Northern Barrens

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#961]
**Links:**
https://www.wowhead.com/quest=881/echeyakee

from WoWHead or our Armory

**What is happening:**
For the quest you have to blow a horn. Blowing this on the right place must bring up Echeyakee. That doesn't happen.

Questgiver: https://www.wowhead.com/npc=3338/sergra-darkthorn

**What should happen:**
Echeyakee should appear.

ORC warlock

**Comment by Saintres** [comment]
Tryed it today and it still not working

**Comment by Echinaceax** [comment]
> Tryed it today and it still not working

No label "Tested in dev" confirmed in dev" means no fix done yet = still broken :)

**Comment by mfranca0009** [comment]
All fixed on PTR, needs testing 👍 

Spell has been fixed to do as it should, summon echeyakee and make the creature start attacking the player who used the item to summon.

**Comment by HrafnValknutt** [comment]
Fix in Dev confirmed.

**Comment by mfranca0009** [comment]
Fix on live server, all set 👍
