### ISSUE TITLE
[Loot] The Deadmines (Normal)

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#963]
**Links:**
[zone=1581]
https://www.wowhead.com/the-deadmines
from WoWHead or our Armory

**What is happening:**
The drops here in lvl 15 - 20 (low lvl ) is somewhat alil off.
The mobs drop lvl 80 stuff, not armor and weapons tho.
They drop high amount of  [Embersilk Cloth] [item=53010]
Also lots of  [Roasted Beef] [item=58268] and  [Sparkling Oasis Water] [item=58256]
And the most common moneydrop is 79 silver , 6 copper.  ( 4/5 )

### NPCs 
[npc=48230] Ogre Henchman
[npc=48229] Kobold Digger
[npc=48262] Ogre Bodyguard
[npc=48279] Goblin Overseer
[npc=48442] Mining Monkey
[npc=48820]  Mine Bunny 
[npc=48445] Oaf Lackey 
[npc=48419] Defias Miner
[npc=48418] Defias Envoker
[npc=48502] Defias Enforcer
[npc=48417] Defias Blood Wizard
[npc=48505] Defias Shadowguard
[npc=48521] Defias Squallshaper
[npc=48522] Defias Pirate

**What should happen:**
no 80 loot for lvl 20s normal dungeon

**Comment by wow-mania** [comment]
You need to tell the NPC that is dropping the wrong loot.

**Comment by Saintres** [comment]
All of them

Den tors 21 mars 2019 kl 14:12 skrev Janitor <notifications@github.com>:

**Comment by Echinaceax** [comment]
> All of them

I tried that one too @Saintres haha
Jani needs ALL mob names with IDs ;)

**Comment by Saintres** [comment]
Hope hes satisfied now. ;-)

**Comment by Echinaceax** [comment]
nice edit @Saintres

**Comment by Echinaceax** [comment]
Still an issue 8.12020

**Comment by Echinaceax** [comment]
Will confirm later thanks @Xman993
