### ISSUE TITLE
[Loot] Shadowfang keep (Normal) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#964]
_issue 1_

**link**
https://www.wowhead.com/item=59230/fungus-squeezings

**What is happening**
- High level loot (lvl 80)

**What should happen**
- Shouldnt drop lvl 80 loot in lvl 15-18 dungeon

**Comment by Echinaceax** [comment]
_Issue 2_

https://www.wowhead.com/item=53010/embersilk-cloth

**What is happening**
High level loot 

**What should happen**

Shouldnt drop high lvl loot in lvl 15-18 dungeon

**Comment by Echinaceax** [comment]
issue 3 

**What is happening**

- Dropping 1s 30c

**What should happen**
- Should drop Copper

**Comment by wow-mania** [comment]
What is the NPC dropping this?

**Comment by Echinaceax** [comment]
i'll logging in and get names :)

**Comment by Echinaceax** [comment]
No change on loot drops (in fact its worse) 

1 all the npc listed above are still dropping 
https://www.wowhead.com/item=59230/fungus-squeezings
https://www.wowhead.com/item=53010/embersilk-cloth
https://www.wowhead.com/item=58266/violet-morel

and now also dropped from HC loot now (in normal mode) didnt before
https://www.wowhead.com/npc=46963/lord-walden#drops:mode=heroic

![lord walden 85 hc item](https://user-images.githubusercontent.com/39439201/54767314-320c8080-4bfd-11e9-9e55-fb5042487ba5.jpg)

**Comment by wow-mania** [comment]
The dungeon has 2 modes.
Make sure you are not entering as Heroic

**Comment by Echinaceax** [comment]
i have :)

![normal mode](https://user-images.githubusercontent.com/39439201/54768224-09858600-4bff-11e9-8865-b5a97e954eb7.jpg)

**Comment by wow-mania** [comment]
Can you check Frantic Geist. This is the only NPC I have fixed. If this one is right I will do the others.

**Comment by Echinaceax** [comment]
omw :)

**Comment by Echinaceax** [comment]
@wow-mania 
Any new update on this ?

**Comment by Dranah** [comment]
This just misc loot, nothing game breaking. Can wait.

**Comment by sarahkay88** [comment]
still dropping level 85 cloth embersilk

**Comment by Echinaceax** [comment]
is game breaking when a level 21 can farm 80 cloth :)
just my opinion ofc

**Comment by Echinaceax** [comment]
Fixed and on live
