### ISSUE TITLE
[NPC] Vaultkeeper Jazra <Void Storage>- Orgrimmar

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#966]
**Links:**

https://www.wowhead.com/npc=54472/vaultkeeper-jazra

**What is happening:**
- cant close the window by the (x) 

**What should happen:**
- Should close when pressing the red (x)

**Comment by wow-mania** [comment]
Dialog closes just fine.
![image](https://user-images.githubusercontent.com/12248683/54681322-f346cf80-4b03-11e9-9079-15faa19590a6.png)

**Comment by Echinaceax** [comment]
still not Clickable for me in PTR :)
