### ISSUE TITLE
[Quest] Refleshification -14194-  Azshara

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#967]
**Links:**
https://www.wowhead.com/quest=14194/refleshification
https://www.wowhead.com/quest=14192/prismbreak
https://www.wowhead.com/item=48104/the-refleshifier

from WoWHead or our Armory

**What is happening:**
You get a device out of the quest "Prismbreak". You have to "de-stone" some npc's. The device doesn't have the effect it should.

**What should happen:**
It should have the effect that Mountainfoot Miners come back at life and count until 8.

Pitsecond: ORC warlock

**Comment by rzenne** [comment]
It worked for me yesterday. Did not have any problems at all. Orc warrior

**Comment by Echinaceax** [comment]
Tested and worked fine for me too @rzenne :)

![works for belf too](https://user-images.githubusercontent.com/39439201/87200440-d9cf2580-c2fc-11ea-87b7-ecb85f97674a.jpg)
