### ISSUE TITLE
[Quest] Memories of the Dead -14215- Azshara

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#968]
**Links:**
https://www.wowhead.com/quest=14215/memories-of-the-dead
from WoWHead or our Armory

**What is happening:**
You are send out to meet a ghost. The ghost isn't there.

**What should happen:**
There should be a ghost to talk to.

Pitsecond: ORC warlock

**Comment by Echinaceax** [comment]
noticed that the video has a ring buff (we dont)
https://www.wowhead.com/quest=14215/memories-of-the-dead#videos:id=35988

**Comment by mfranca0009** [comment]
Need to finish this aura functionality tomorrow, but basically done 👍 

https://www.wowhead.com/spell=67717/attuned-to-kalytha

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
confirmed fixed in ptr 

![image](https://user-images.githubusercontent.com/39439201/120122121-3b171600-c1a7-11eb-8d2f-a3225a81943c.png)

then https://www.wowhead.com/quest=14216/mystery-of-the-sarcen-stone is available
