### ISSUE TITLE
[Quest] When Science Attacks - Azshara

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#969]
**Links:**
https://www.wowhead.com/quest=14308/when-science-attacks
https://www.wowhead.com/item=49132/fireliminator-x-21
from WoWHead or our Armory

**What is happening:**
You get a device to spray goblins, that seem to work but they don't count.

**What should happen:**

They should count.

Pitsecond: ORC warlock

**Comment by mfranca0009** [comment]
all set 👍

**Comment by Echinaceax** [comment]
confirmed fixed in ptr 

![image](https://user-images.githubusercontent.com/39439201/120225174-0a85b980-c245-11eb-83a8-d0523904b555.png)
![image](https://user-images.githubusercontent.com/39439201/120225246-2be6a580-c245-11eb-86a3-aa527917c3e8.png)
