### ISSUE TITLE
[Quest] Befriending Giants - Azshara - 14377

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#971]
**Links:**
https://www.wowhead.com/quest=14377/befriending-giants
from WoWHead or our Armory

**What is happening:**
You have to "talk" to a giant. The giant is not located at his right place. The giant is "yellow" and you can attack him. 

**What should happen:**
You have to be able to "talk" to the giant. He has to stand on approx 47,75. He has to be "friendly".

Pitsecond: ORC warlock

**Comment by DiomacheTharghan** [comment]
The report is not accurate: The giant you are referring to is not the same.
You are referring to: https://www.wowhead.com/npc=37002/cliff-crasher
While the NPC you need to talk is: https://www.wowhead.com/npc=36297/gormungan which is totally missing

**Comment by Rushor** [comment]
gossip interaction added
