### ISSUE TITLE
[Quest] The Terrible Tinkers of the Ruined Reaches  - Azshara - 14383

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#972]
**Links:**
https://www.wowhead.com/quest=14383/the-terrible-tinkers-of-the-ruined-reaches
https://www.wowhead.com/npc=36407/bingham-gadgetspring
from WoWHead or our Armory

**What is happening:**
You have to kill 3 different npc's. Bingham Gadgetspring isn't there to kill.

**What should happen:**
Bingham Gadgetspring should be there to kill. And count for the quest.

Pitsecond: ORC warlock

**Comment by DiomacheTharghan** [comment]
There isn't any enemy NPC listed in the quest, not only Bingham. Gnomes are missing completely

**Comment by Echinaceax** [comment]
@DiomacheTharghan - can you make a new report about the "Gnomes are missing completely"

**Comment by polymorphism98** [comment]
> @DiomacheTharghan - can you make a new report about the "Gnomes are missing completely"

I have added an issue for the missing gnomes #4502
