### ISSUE TITLE
[Quest] Airborne Again - Azshara - 24497

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#973]
**Links:**
https://www.wowhead.com/quest=24497/airborne-again
from WoWHead or our Armory

**What is happening:**
You have to fly by plain to an other location. The plains that are there, which you can board, don't fly. You can take the fp and complete the quest.

**What should happen:**
The plains around the big canon must be able to fly. Automated or manual, i don't know.

Pitsecond: ORC warlock

**Comment by mfranca0009** [comment]
Per the video: https://www.youtube.com/watch?v=cDxcY40oIdE

It looks as if there should only be one plane that offers the ride, it should be all fixed now 👍

**Comment by Echinaceax** [comment]
confirmed fixed in ptr 

![image](https://user-images.githubusercontent.com/39439201/120316007-3d7b8c00-c2dd-11eb-94cf-811cf7b081d2.png)
