### ISSUE TITLE
[Quest] Absorbent - Azshara - 14323

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#976]
**Links:**
https://www.wowhead.com/quest=14323/absorbent
https://www.wowhead.com/item=49168/enchanted-azshari-sea-sponge
from WoWHead or our Armory

**What is happening:**
Nothing. Walking past the npc's who have to drop loot but nothing happened.

**What should happen:**
You should walk past npc's who, automatic give you the loot needed for the quest. This is automatic because of the item the questgiver gave to you, the "Enchanted Azshari Sea Sponge".

Pitsecond: ORC warlock

**Comment by Rushor** [comment]
once you get in combat with them, they will create the item to you inventory and get killed
