### ISSUE TITLE
[Quest] The Blackmaw Doublecross - Azshara - 14435

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Blackwing-Lair#978]
**Links:**
https://www.wowhead.com/quest=14435/the-blackmaw-doublecross
from WoWHead or our Armory

**What is happening:**
To complete this quest you have to be transported to a meeting to disturb it. The mage does not transport you. I tried to walk over there and do the thing manual but there was no one there to disturb.

**What should happen:**
A mage should transport you to a meeting.

Pitsecond: ORC warlock

**Comment by Rushor** [comment]
teleport should happen at the mage
