### ISSUE TITLE
[Quest] Riding On

### ISSUE THREAD

**Issue by Zunrin** [WoWManiaUK/Blackwing-Lair#98]
You should be able to talk to Raider Jhash who gives you a ride to Razor Hill. At the moment, talking with him does nothing. (Note: the quest is still doable if you walk to Razor Hill)

Links:
http://www.wowhead.com/quest=25171/riding-on
http://www.wowhead.com/npc=10676/raider-jhash

**Comment by Dranah** [comment]
This issue is still valid, no priority though.
