### ISSUE TITLE
[Spell] Thorns spell id 467 Druid

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#981]
**Links:**
Have been trying to find the spell on wowhead but cant find any links.
https://cata-twinhead.twinstar.cz/?spell=467

There is not links to this spell

**What is happening:**
This spell Thorns are not working for Druid's
Spell id 467
I dont get a dot on myself that say i have cast the spell on me 
and mobs that target me and hit me should get damage on themselves.
That dont happen either
**What should happen:**
I should get a  "dot" on me that shows i have cast the spell Thorns on me and mobs that hit me should take damage.

**Comment by Keader** [comment]
Working fine to me, tested in dev.
