### ISSUE TITLE
[Dungeon] Wailing Caverns (Normal)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#983]
**Links:**
https://www.wowhead.com/npc=3679/naralex

_let the event begin_ 

![naralex](https://user-images.githubusercontent.com/39439201/54835513-82014b00-4cc2-11e9-8003-f686276649b0.jpg)

**What is happening:**
- Cant click on "let the event begin"
- So cant complete this part 

**What should happen:**
https://www.wowhead.com/npc=3678/muyoh

> Usually after slaying all the other bosses as well, what you need to do is just to go back and speak with the Tauren that you saw while first arriving inside the instance, the Disciple of Naralex. Start the event and escort him up to where Naralex is, at the Dreamer's Rock, top north of the instance. During this escort the Disciple will stop and speak a few times. When this happens be prepared to fight, there are two waves: first, two elite Deviate Ravagers, and next time there'll be three elite among Deviate Viper and Deviate Adder.

**Comment by hediunchained** [comment]
still no fix ?

**Comment by gamer100** [comment]
![image](https://user-images.githubusercontent.com/33811022/66269695-cf529d80-e84b-11e9-97ff-8c6be0070115.png)
Naralex is there

**Comment by Echinaceax** [comment]
its working ?

**Comment by gamer100** [comment]
![image](https://user-images.githubusercontent.com/33811022/66269776-1f7e2f80-e84d-11e9-8967-7e86e5ab0bfb.png)

**Comment by Echinaceax** [comment]
Thank you for update @gamer100 :)
