### ISSUE TITLE
[NPC/Daily] Kah Mistrunner <Fishing Trainer>-3028 -Thunder Bluff

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#986]
**Links**
NPC - https://www.wowhead.com/npc=3028/kah-mistrunner
Dailies list - https://www.wowhead.com/npc=3028/kah-mistrunner#starts

![daily](https://user-images.githubusercontent.com/39439201/54841488-ae6f9400-4ccf-11e9-982e-98b281de662a.jpg)

**What is happening**
- Can take all 5 dailies 

**What should happen**
- 1 daily only

**Comment by Echinaceax** [comment]
_Issue2_

![kah](https://user-images.githubusercontent.com/39439201/55284752-2cd9cf00-537d-11e9-9746-45ee9676b4dd.jpg)

- [ ] He doesnt give any dailies to toons lvl 10

**Comment by Rushor** [comment]
works now. only gives one quest and also on level >=10 toons.
