### ISSUE TITLE
[Quest] Missing Parts

### ISSUE THREAD

**Issue by TenmanWoW** [WoWManiaUK/Blackwing-Lair#99]
Quest - Missing Parts - http://www.wowhead.com/quest=27038/missing-parts

NPC - Fargo Flintlocke (44806)  - http://www.wowhead.com/npc=44806/fargo-flintlocke

The NPC shows the quest turn in marker on the minimap. Upon arriving at the marker, I had to enable gm mode on to see him. Switching it off makes him disappear. Tested the on/off with several low level quests in SW, only had issue with quest NPC

![wowscrnshot_051218_131453](https://user-images.githubusercontent.com/25806987/39960477-79de0a56-55e9-11e8-90ff-097e44cbe735.jpg)
![wowscrnshot_051218_131447](https://user-images.githubusercontent.com/25806987/39960478-79f23bca-55e9-11e8-92ea-b53bdfbc5621.jpg)

**Comment by Saintres** [comment]
Still not working. Cant complete the quest or find the questresiver

**Comment by jarvik76** [comment]
I also experienced this again, perhaps needs re-opening.
May be related to #882 and #3542

**Comment by jburkiett** [comment]
Hopefully fix I sent in will work unsure of your DB Table format.
