### ISSUE TITLE
[quest=28398] [The Pyromancer's Grimoire] - Blackrock Depths

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#994]
**Links:**
[quest=28398]
https://www.wowhead.com/quest=28398/the-pyromancers-grimoire#comments
from WoWHead or our Armory

**What is happening:**
The item Loregrain's Grimoire [item=64305] is not droping from the npc [npc=9024] Pyromancer Loregrain

**What should happen:**
Pyromancer Loregrain should drop the item

Quest not completeble

**Comment by Kitzunu** [comment]
Fixed in the DEV Realm.
Dont forget to delete cache before testing.
